### ISSUE TITLE
Download Links not working

### ISSUE THREAD

**Issue by jasond727** [MicrosoftDocs/OfficeDocs-SharePoint#1]
The download links for the sharepoint migration tool on this page send you to a specified blob can't be found page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89de996c-fdbe-91dd-75c2-34b7e12b1f49
* Version Independent ID: 9961e4fe-6764-d6c8-9bde-271ef81c5a6d
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/SharePoint/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Link has been fixed.

**Comment by nickd3333** [comment]
I can download the package, but each time I click, "Install," I get a Cannot Start Application error that states, "Unable to retrieve application files. Files corrupt in deployment."

**Comment by nickd3333** [comment]
I am attempting to migrate from SharePoint Server 2010. I take it this is not supported? I saw a note on another article saying only SharePoint Server 2013 is supported.

**Comment by JoanneHendrickson** [comment]
Hi Nick -- have you tried deleting your temp.tmp folder and clearing your cache -- and then retry the download and install?

At this time only SharePoint 2013 is supported.

**Comment by jvalks** [comment]
It does not work at all!! Tried to copy a single file:
TaskID,Message,PendingAction,ExceptionId
"5924dc58-6f91-4491-9226-4c828535f318","The content type 'Folder' cannot be created or updated","ACTION_STOP","0x02060003"

Bummer!

**Comment by JoanneHendrickson** [comment]
Hi jvalks:  At what point did you receive this error? After you entered your info and clicked Migrate? What steps had you done up to that point?

**Comment by jvalks** [comment]
I entered the credentials and the site location link... I'm using other migration software normal, but since last week that software is getting throttled while uploading... It seems to be fixed today! I have to try if the SharePoint migration tool is also working, that means something spooky was going on at the Microsoft backend (not the first time...)...

**Comment by wenhua-helen** [comment]
Hi, jvalks, 
Thanks for your feedbacks. 
Please share everything under C:\Users\%user name%\AppData\Roaming\Microsoft\MigrationTool\admin@XXXX.onmicrosoft.com\WF_XXXXX folder to Migration feature crew migration_team@microsoft.com. 
We would like to work with you to address the issue encountered in your migration.

Migration feature crew team

**Comment by jvalks** [comment]
Done!

**Comment by kenwith** [comment]
@jasond727 - I am afraid this issue went stale in the issues here for documentation. I am sorry on the delay. It has been a long time so I hope you have the issue resolved. If not though, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
