### ISSUE TITLE
Format of CSV for OneDrive migration?

### ISSUE THREAD

**Issue by cdebbo** [MicrosoftDocs/OfficeDocs-SharePoint#10]
What is the CSV format for OneDrive. I have column1 and column4 but what about column 5, 6. Users start with any empty Onedrive. I can't be expected to first create a folder in the users' oneDrive and then migrate? 

Eg. I have this,
X:\home\janedoe,,,https://contoso-my.sharepoint.com/personal/janedoe_contoso_on_ca,",,

Tried this too,
X:\home\janedoe,,,https://contoso-my.sharepoint.com/personal/janedoe_contoso_on_ca,","Documents",  

.... and tried 'Shared Documents' too. 

HELP, and thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ade8182-a488-4d5e-e8d9-8d675ed90c0b
* Version Independent ID: f009c3da-f902-3304-5f18-7b544b8b77c4
* Content: [How to format your CSV file for data content migration](https://docs.microsoft.com/en-ca/SharePoint/migrate-to-sharepoint-online/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by cdebbo** [comment]
my URL is https://contoso-my.sharepoing.com/personal/janedoe_contoso_on_ca but still not working.
"Line #1, Invalid format"

**Comment by kenwith** [comment]
@cdebbo - sorry for the delay on this and that it has gone stale in the documentation issues. I know it has been a very long time so I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by solinear** [comment]
What's the status on this?  The documentation is still pretty stale and I'd love to use this feature also.

**Comment by kenwith** [comment]
@solinear - let's re-open the issue. @tseward - would this be one you could work on? @AndreaBarr - FYI.

**Comment by solinear** [comment]
I was able to use this, following the format of:

<file location (UNC or localpath)>,subfolder,,<OneDrive https location>,Documents (does not go into documents folder),<foldername in OneDrive (this is the actual folder in OneDrive that the folder goes into)>

If I left the second path location blank, it did not work.

Example:

C:\foldername,,,https://tenantname-my.sharepoint.com/personal/userid_contoso_org/_layouts/15/onedrive.aspx,Documents,Old_Homedrive

That will result in everything in C:\foldername to go to the "Old_Homedrive" folder in OneDrive (NOT inside the Documents folder, the Old_Homedrive folder in the root of OneDrive).

**Comment by TokyoScarab** [comment]
Hello, thanks for posting this issue!  I noticed in both of the lines that you said you tried, you had quote marks in incorrect spots (this is assuming the things you said you tried were exactly as shown in the original post). In each example shown, in the 5th column you have a singular quote mark ( " ).  You do need to provide a library name.  If you are still having issues with this, feel free to submit a ticket as listed above or comment back here, thanks!
