### ISSUE TITLE
[LOC] Invalid fwlink in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1005]
**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/administration/mobile-security-and-authentication
2. Check "_Find a lost phone_" link text (https://go.microsoft.com/fwlink/?LinkId=253669)
3. Click the link --> 404 error page

**Expected:** link should be removed or redirect to a valid page

![image](https://user-images.githubusercontent.com/47977325/58636387-79477980-82f0-11e9-859c-765b4462aa6b.png)

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@OfficeGlobal Thank you for your feedback. We have corrected the link via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1037

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
