### ISSUE TITLE
Hybrid Picker not working with Multi-factor authentication for Global Admin on Office 365

### ISSUE THREAD

**Issue by benjamingournay2** [MicrosoftDocs/OfficeDocs-SharePoint#101]
Hi,

The hybrid picker does not work with multi-factor authentication for Global Admin on Office 365. Is there a plan to release a version of the tool with multi-factor authentication for Global Admin.

Thks for help,

Best regards,

Benjamin Gournay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6535e2be-311a-5408-21ab-94cede62371b
* Version Independent ID: 3f4edc04-f79b-94ba-9764-fa2433e1ed4c
* Content: [Hybrid picker in the SharePoint Online admin center](https://docs.microsoft.com/en-us/sharepoint/hybrid/hybrid-picker-in-the-sharepoint-online-admin-center#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/hybrid-picker-in-the-sharepoint-online-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hybrid-picker-in-the-sharepoint-online-admin-center.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Per the PG, there is currently no plans to do so. Please vote on the following uservoice I created:

https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/34461736-enable-mfa-for-sharepoint-hybrid-config-wizard

**Comment by kenwith** [comment]
I upvoted too! Thanks @benjamingournay2 for reporting and @tseward for the User Voice votes!
