### ISSUE TITLE
[LOC] Invalid link in multiple articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1010]
There is an invalid link in an article.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/administration/connect-a-publishing-site-to-a-catalog
2. Search for "Create and manage terms in a term set"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link should redirect to an existing page

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/connect-a-publishing-site-to-a-catalog.md
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-cross-site-publishing.md
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/assign-a-category-page-and-a-catalog-item-page-to-a-term.md

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@OfficeGlobal Thank you for your feedback. We have made changes to the article via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1045

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
