### ISSUE TITLE
[LOC] Invalid link in multiple articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1011]
There is an invalid link in an article.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/administration/configure-cross-site-publishing
2. Search for "Keyboard shortcuts>"
3. Click on the link

The article above is just an example the "https://go.microsoft.com/fwlink/p/?LinkID=246504" link exist in multiple topic please scan the whole repository for this link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link should redirect to an existing page

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@OfficeGlobal thank you for the feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1046

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
