### ISSUE TITLE
Requesting information about LastAnalyticsUpdateTime

### ISSUE THREAD

**Issue by ttplaya** [MicrosoftDocs/OfficeDocs-SharePoint#1028]
Would it be possible to add information about how the LastAnalyticsUpdateTime works please? We have Sharepoint server 2016, and there are items that have a LastAnalyticsUpdateTime of a couple months ago. Originally I thought the explanation would be that the LastAnalyticsUpdateTime doesn't get updated unless there are actual views. However, there are also other items that have a LastAnalyticsUpdateTime of yesterday, and yet the ViewsLastMonths1 is 0. This is very confusing as we are trying to understand the view stats.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42f57b3-04de-6c25-5601-80595c98f6ed
* Version Independent ID: f7c417f0-0e8e-26e3-0a8e-f0aa29a15861
* Content: [Overview of analytics processing in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/overview-of-analytics-processing)
* Content Source: [SharePoint/SharePointServer/search/overview-of-analytics-processing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/overview-of-analytics-processing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@ttplaya Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @ttplaya 

Thank you for reaching out!

"LastAnalyticsUpdateTime" managed property and it's attributes are explained here in this article. Please see https://docs.microsoft.com/sharepoint/technical-reference/crawled-and-managed-properties-overview#managed-properties-overview.

Thank you.

**Comment by ttplaya** [comment]
Hi @sowjanya365

I looked at the link you posted and it only has information about the attributes -- it doesn't actually answer my question. What I'm looking for is how the LastAnalyticsUpdateTime actually works -- I see that different items have different LastAnalyticsUpdateTime timestamps. What determines when an item actually gets their analytics updated? Please see my original post for full explanation of my question.

Thanks.

**Comment by sowjanya365** [comment]
Hi @ttplaya 

Thanks for your response. 

This article gives high level overview of analytics processing. If you want to know the detailed information about the LastAnalyticsUpdateTime property, it is advised that please open a service ticket in your tenant and check the details related to your concern. If you wish to know how to open the service ticket, please follow this link: 

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thanks again, for taking out some time to open the issue.

**Comment by tseward** [comment]
@ttplaya @scanum I will take a look at this one next week. @ttplaya can you tell me where you're specifically seeing this property?

**Comment by scanum** [comment]
@tseward Thank you!

**Comment by ttplaya** [comment]
Hi @tseward

Thanks for taking a look! I have a page with a Popular Items web part, and the purpose of the page is just to show a list of the pages and documents in our Sharepoint site, ranked by popularity. In the Property Mapping of the web part, I've set LastAnaltyicsUpdateTime, as well as ViewsLastMonths1, ViewsLastMonths2, and ViewsLastMonths3.

I'm just trying to understand the relationships between those properties and how they get updasted. I've read that ViewsLastMonths1 shows the number of views in the current month, as of the LastAnalyticsUpdateTime. So for example, if the LastAnalyticsUpdateTime was in April, then ViewsLastMonths1 contains the number of views in April up to the date of the LastAnalyticsUpdateTime, even though it is currently June. I see that most of the listed items have a LastAnalyticsUpdateTime of yesterday. However, some items have older LastAnalyticsUpdateTime stamps. I'm just trying to make sense of it and find out why those items have older LastAnalyticsUpdateTime stamps, and what causes the LastAnalyticsUpdateTime to get updated for some items but not for others.

**Comment by tseward** [comment]
From what I can tell, the value is set when the item last had an entry in the usage analytics logs. E.g. a file is viewed/edited, it creates a usage data analytics entry in `C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\LOGS\AnalyticsUsage` (by default), the usage import/processing jobs run which then updates the data in `dbo.AnalyticsItemData` within the Analytics Search database. This seems to be a consistent pattern of how this works, but it certainly is possible you've found an edge case or a potential bug. What I'd probably recommend as next steps would be to open a support case with Microsoft to help identify why you're seeing inconsistent results, e.g. LastAnalyticsUpdateTime of <current_date> with ViewsLastMonths1 = 0 or other oddities.

**Comment by ttplaya** [comment]
@tseward Thanks for your explanation and suggestion. I will open a support case when I get a chance to.

**Comment by scanum** [comment]
@ttplaya Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
