### ISSUE TITLE
Duplicate paragraph needs to be removed:

### ISSUE THREAD

**Issue by SHRPNT247** [MicrosoftDocs/OfficeDocs-SharePoint#104]
"MinRole now manages the incoming email feature in SharePoint Server 2016. The incoming email feature can only be used on the following MinRole roles" 
appears twice which appears to be in error, see below for specific text copied from the site:

MinRole now manages the incoming email feature in SharePoint Server 2016. The incoming email feature can only be used on the following MinRole roles:

•Application

•Application with Search

•Front-end

•Search - (You need to create an SMTP smarthost for the servers in the farm, which then relays those emails to your normal SMTP server.)

•Custom

MinRole now manages the incoming email feature in SharePoint Server 2016. The incoming email feature can only be used on the following MinRole roles:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b1f842-b2ca-71a7-a063-d26ceaab8ffe
* Version Independent ID: 02434425-3bbb-127e-72e6-63548d4d5b57
* Content: [Plan incoming email for a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/incoming-email-planning)
* Content Source: [SharePoint/SharePointServer/administration/incoming-email-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/incoming-email-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Removed duplicate sentence and republished topic.
