### ISSUE TITLE
Doesn't Describe How to Change Permissions on Individual Site

### ISSUE THREAD

**Issue by ChaosFreak** [MicrosoftDocs/OfficeDocs-SharePoint#1042]
This doc mentions that "If you want to allow external file sharing on any sites, you need to turn it on globally (at the organization level). You can then turn it off for all other sites."
However, it doesn't mention how to find/edit the sharing setting on an individual site, it just shows instructions for editing the global setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a570bb-2567-565c-e9ff-bf1ccbf38d0e
* Version Independent ID: 3d342dea-9dd3-008c-20c6-902452302e95
* Content: [Manage sharing in OneDrive and SharePoint](https://docs.microsoft.com/en-us/onedrive/manage-sharing#feedback)
* Content Source: [OneDrive/manage-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/manage-sharing.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ChaosFreak Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by asoto87** [comment]
@ChaosFreak I believe you are looking for https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site

**Comment by ChaosFreak** [comment]
@asoto87  Thanks, that is exactly the information I needed. You may want to add that link to the main document.

**Comment by asoto87** [comment]
@ChaosFreak -- Agreed. This issue has been assigned to @scanum so hopefully this article is updated soon to reference, and clarify, the differences of policies defined at the Global level vs Site level as well as a new reference to the article for site level external sharing policies.

I think changing "Manage sharing" to "Global Policy" and adding "Site-Level Policy" would help clarify this in the future.

**Comment by scanum** [comment]
@ChaosFreak Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
