### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/OfficeDocs-SharePoint#105]
There is a link which redirects to a non existing page repro on two pages

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-hybrid-sites-featuresroadmap and https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2016
2. In the first page search for "hybrid sites features" and in the second search for "Plan for hybrid sites features"
3. Click on the links 

**GH Articles:**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-hybrid-sites-featuresroadmap.md

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-sharepoint-server-2016.md

**Actual results:**
Link does not work
**Expected results:**
Link redirects to a existing page

![image](https://user-images.githubusercontent.com/16706698/41595138-0928e524-73c6-11e8-95d6-6c25b0f6abd3.png)

**Comment by kenwith** [comment]
@OfficeGSX - confirmed and thanks for reporting. Working to get these resolved.

**Comment by MikePlumleyMSFT** [comment]
links fixed.
