### ISSUE TITLE
Error to get Tenant ID

### ISSUE THREAD

**Issue by scorpiozj** [MicrosoftDocs/OfficeDocs-SharePoint#1054]
Hi, I follow this [link](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) to start office add-on. When I try to get the Tenant ID, it shows error with:
>  Unable to complete due to service connection error, please try again later.

I  also tried this [link](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id) to get Tenant ID and it failed, too.
The screenshot is attached below:

<img width="1154" alt="屏幕快照 2019-06-03 下午1 55 13" src="https://user-images.githubusercontent.com/644156/58779097-6641eb80-8607-11e9-98b4-fc9540bd4fa4.png">

**Comment by scanum** [comment]
@scorpiozj thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
