### ISSUE TITLE
How to download files from blob after CreateSPAsyncReadJob Job is completed

### ISSUE THREAD

**Issue by upadhyayadhaval** [MicrosoftDocs/OfficeDocs-SharePoint#1055]
I have gone through [Migration Asynchronous Read API](https://docs.microsoft.com/en-us/sharepointmigration/spo-asynchronous-read-api#migration-asynchronous-read-api)  and able to successfully create CreateSPAsyncReadJob which stays in "Queued" state for sometime than turns its state to "Processing" and finally returns its state as "None" when completed. 

Sample:
Refer [Thread](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/973)

However there is not much information about how we download the Blobs generated and placed by the completed job.

Have tried some sample code as depicted below but it throws Microsoft.WindowsAzure.Storage.StorageException: 'The remote server returned an error: (403) Forbidden.' 

            using (var clientContext = new ClientContext(siteUrl))
            {
                var securePassword = new SecureString();
                foreach (var c in password) securePassword.AppendChar(c);
                clientContext.Credentials = new SharePointOnlineCredentials(userName, securePassword);

                var result = clientContext.Site.CreateSPAsyncReadJob($"{siteUrl}/Lists/SampleGenericList", new AsyncReadOptions() { });
                clientContext.ExecuteQuery();
                var jobData = result[0];

                MigrationJobState state;
                do
                {
                    Thread.Sleep(5000);
                    var status = clientContext.Site.GetMigrationJobStatus(jobData.JobId);
                    clientContext.ExecuteQuery();
                    state = status.Value;
                } while (state != MigrationJobState.None);

                var blobUri = new Uri(jobData.ManifestContainerUri);
                var blobAccountName = blobUri.Host.Split('.')[0];
                var containerName = blobUri.LocalPath.Replace("/", "");

                var storageCredentials = new StorageCredentials(blobAccountName, jobData.EncryptionKey);
                var cloudStorageAccount = new CloudStorageAccount(storageCredentials, true);
                var cloudBlobClient = cloudStorageAccount.CreateCloudBlobClient();
                var containerReference = cloudBlobClient.GetContainerReference(containerName);
                var blobs = containerReference.ListBlobs();
                List<string> blobNames = blobs.OfType<CloudBlockBlob>().Select(x => x.Name).ToList();
                foreach (var blob in blobNames)
                {
                    //Download blob
                }
            }

Any direction would be of great help?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39174cb2-71d0-b58a-6edc-3fcabd922e8e
* Version Independent ID: fae882c6-c489-6992-a343-6f0d657fb212
* Content: [Migration Asynchronous Read API](https://docs.microsoft.com/en-us/sharepointmigration/spo-asynchronous-read-api#feedback)
* Content Source: [migration/SPO-asynchronous-read-API.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPO-asynchronous-read-API.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@upadhyayadhaval thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tsegato** [comment]
Would it maybe be an option you update the documentation as there is nothing anywhere about this topic. Then we dont have to create a support case all of us?
