### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-SharePoint#1056]
This article is incomplete as it only provides a partial list of the service applications. For example, it is missing App Management Service Application, Word Automation, and several others. Please update the article to include the full set of service applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c8327e3-91dd-f24e-c969-b7f7fecab866
* Version Independent ID: a250e21f-f707-0345-7ec0-34faecdee44f
* Content: [Manage service applications in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/service-application-management)
* Content Source: [SharePoint/SharePointServer/administration/service-application-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/service-application-management.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
