### ISSUE TITLE
Are the reg keys still required to enable CA?

### ISSUE THREAD

**Issue by mirzakubat** [MicrosoftDocs/OfficeDocs-SharePoint#1058]
We have noticed during our testing that latest Enterprise ring and production ring versions seem to have CA support enabled by default ( we have ADAL + SilentConfig set already ) and do not require the Preview reg key. Has support for CA been released to OneDrive on Windows yet or does it suffice to only set the ADAL key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync client for Windows](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access#feedback)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mirzakubat thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by mirzakubat** [comment]
@scanum - The thing is that we have created an advistory case and the reply back was in essence "follow the docs but we do not know what "EnableTeamTier_Internal" registry key is and if it is needed as we cannot find anything in our internal documentation". 

As we turned to a dead end with the advisory case I wanted to check here if we could get someone from the PG to validate that the docs are still accurate and that both keys are required? 

Reason being that a) we already have EnableADAL set ( as we use silent autoconfig ) and b) MS Support seems to claim that they have no record of the second key in the registry file linked in this doc. 

Can you please re-open the case and check internally with the PG to get confirmation whether or not both keys ( as referenced in the docs ) are needed?

In parallel we have contacted our TAM to see if we can get some assistance from there. At the moment this is blocking us from moving forward with a big change for our +30k seat environment.
