### ISSUE TITLE
Onboard script process.

### ISSUE THREAD

**Issue by jasond727** [MicrosoftDocs/OfficeDocs-SharePoint#106]
The Azure AD requirements are wrong now.  The link to Azure Active Directory Module for Windows PowerShell go to an expired page.  The new installation process install-module msonline in powershell does not create the required registry key entries required in the onboard script.

Please update documentation to reflect updates on the connect microsoft site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3014e33-1611-5cf7-431c-8132b7717986
* Version Independent ID: 4479c7fd-32f7-5b31-9aad-da6174bfd995
* Content: [Configure cloud hybrid search - roadmap](https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-cloud-hybrid-searchroadmap#BKMK_SetupSearchArch)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-cloud-hybrid-searchroadmap.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-cloud-hybrid-searchroadmap.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
Thank you for your feedback! I'm working on a fix to this, you should see it show up very soon.

**Comment by tklarsen** [comment]
I've updated the article with a working link. The team has also updated the [Onboard-CloudHybridSearch.ps1 script] (https://go.microsoft.com/fwlink/?LinkId=717902) in conjunction with this.

**Comment by tklarsen** [comment]
Updated the link and republished
