### ISSUE TITLE
Why doesn't this apply to SharePoint 2016?

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-SharePoint#1060]
What is different about the people picker in SP2016? Why wouldn't this article also apply to it? The linked articles have been updated to apply to 2016 and 2019.  Please update the article and remove specific references to SharePoint 2013, and change this just to SharePoint so it applies to 2016 and 2019.
Plan for People Picker in SharePoint https://docs.microsoft.com/en-us/sharepoint/administration/plan-for-people-picker
Plan for custom claims providers for People Picker in SharePoint https://docs.microsoft.com/en-us/sharepoint/administration/plan-for-custom-claims-providers-for-people-picker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f4e27b5-fcef-038d-2d4d-2df638bc4c6f
* Version Independent ID: f2b4eda5-e5bc-b9e9-e7fa-eee15f5accae
* Content: [People Picker and claims providers overview in SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/people-picker-and-claims-providers-overview)
* Content Source: [SharePoint/SharePointServer/administration/people-picker-and-claims-providers-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/people-picker-and-claims-providers-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tseward** [comment]
@SharePointBlackBelt you're correct, this article applies to 2013, 2016, and 2019. It needs to have the APPLY TO updated and remove references to specific versions of SharePoint.

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
