### ISSUE TITLE
Analytics Reporting -- "split database"?

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#1063]
Under Analytics Reporting, recommended scaling method, it says:

"Scale out by creating additional Analytics Reporting database using a split operation when the main database becomes &gt;200 GB. "

What does this mean? How do we split the analytics reporting database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8065895-eb6b-e4a5-967a-73bee4605d50
* Version Independent ID: ce168605-1ed4-d626-476d-d4120be2a6cf
* Content: [Database types and descriptions in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/database-types-and-descriptions)
* Content Source: [SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@repton-infinity Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@repton-infinity Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
