### ISSUE TITLE
Typo In First Bullet Under 'Enable silent configuration'

### ISSUE THREAD

**Issue by MikelRbrts** [MicrosoftDocs/OfficeDocs-SharePoint#1064]
"Enable silent account configuration. For info, see Silently sign in users to the OneDrive sync client with their Windows credentials. If a device is not already joined to Azure AD, enabling this setting wil join it."

Should be... 

"Enable silent account configuration. For info, see Silently sign in users to the OneDrive sync client with their Windows credentials. If a device is not already joined to Azure AD, enabling this setting will join it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@MikelRbrts Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@scanum I've made a PR for it

**Comment by scanum** [comment]
@MikelRbrts Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
