### ISSUE TITLE
Wrong credential used for migration

### ISSUE THREAD

**Issue by AViens** [MicrosoftDocs/OfficeDocs-SharePoint#1065]
Hi, I've got an issue with the migration tool. In our organisation we try to migrate users files from an server to SharePoint. We use the CSV file to set this up. We have set up an on site administrator to be used for the migration. This administrator have all the rights on the server and the SharePoint. 

When I launch the migration from my computer with the administrator credential the migration start and finish within a minutes for about 30 locations. I check the migration report and in the FailureSummaryReport.csv I have an access denied error on the source path for all the location except one. 

The only one that work is my folder wich is the one that I have admin right on it with my personal crendential. I try to migrate another user with me having admin right on his folder and that worked too. Dont forget I'm always using the administrator credential that we set up for the migration. It's seem that at some point my personal credential are used somewhere … 

Sorry for my English it's not my native language.

**Comment by scanum** [comment]
@AViens thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
