### ISSUE TITLE
Redirect and move Windows known folders to OneDrive doesn't work (on premise AD)

### ISSUE THREAD

**Issue by cjp78** [MicrosoftDocs/OfficeDocs-SharePoint#1080]
Hello,
I've been trying to apply gpo to Redirect and move Windows known folders to OneDrive and it doesn't seem to apply. I activated thoses parameters :
- move silently windows knows folders...
- silently connect users....
the Gpo is targeted on Computers
Am I missing something ? 
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/OneDrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@cjp78 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by cjp78** [comment]
It's ok know, It seems that it took a little more time to applicate to computer.
thanks
