### ISSUE TITLE
Formatting (Markdown) Error

### ISSUE THREAD

**Issue by dmclaugh78** [MicrosoftDocs/OfficeDocs-SharePoint#1088]
These two line are showed read as:
**/ODBC:< file>** Install Microsoft ODBC Driver 11 for SQL Server from < file>.
**/DotNetFx:< file>** Install Microsoft .NET Framework 4.6 from < file>.

Instead of:
**/ODBC:< file>**Install Microsoft ODBC Driver 11 for SQL Server from < file>.
**/DotNetFx:< file>**Install Microsoft .NET Framework 4.6 from < file>.

**Comment by tseward** [comment]
Which article are you referring to?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by dmclaugh78** [comment]
Sorry, very new to Github, this is the page and section:
https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements#prerequisite-installer-operations-and-command-line-options

**Comment by scanum** [comment]
@tseward

**Comment by scanum** [comment]
@dmclaugh78 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
