### ISSUE TITLE
No split on versions ?

### ISSUE THREAD

**Issue by annigam01** [MicrosoftDocs/OfficeDocs-SharePoint#1089]
The list of supported features does not says which version of the tool supports ALL vs few. If i remember correctly the currently GA version of this tool does not support ALL the above listed features. Is there a way to flag which item is supported in preview built ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support?](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@annigam01 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @annigam01 
Thanks for your feedback.
I could check, that the list in referenced article, is updated with the last current release version of SPMT, this is better explained in the [SPMT Release Notes](https://docs.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool), so I will create a pull request to add this link to the article.

Thank you

**Comment by scanum** [comment]
@annigam01 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
