### ISSUE TITLE
Windows Server 2016 Standard or Datacenter

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#1090]
Above, there is a mention about "At this time, Windows Server 2016 RTM is not supported."
This means that Windows Server 2016 Standard or Datacenter are supported?  There is no express mention about these OS versions.

Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171d6bb7-4f08-573b-a2c7-5e78add14340
* Version Independent ID: 8c204184-9c39-727c-2ac3-6106be7ce1b8
* Content: [Hardware and software requirements for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-0#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Any edition of Server 2016 is not supported with SharePoint 2013. _Most_ articles will not say "Standard" or "Datacenter" in terms of Windows Server. You will only see the version.

**Comment by scanum** [comment]
@danone1985 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
