### ISSUE TITLE
Seamless SSO support?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/OfficeDocs-SharePoint#1095]
Based on what I have seen, this feature seems to work fine with Seamless SSO and password hash sync. So not only with AD FS: Should you update this page to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21bd120e-26c1-3a5a-499b-8dbd01a435e6
* Version Independent ID: 2ced3050-f8ce-a5c3-a292-e0d668e4a47a
* Content: [Enable auto-acceleration in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/enable-auto-acceleration)
* Content Source: [SharePoint/SharePointOnline/enable-auto-acceleration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/enable-auto-acceleration.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ArttuArstila  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Adding @kaarins Hello Kaarin, can we get confirmation from the product group on this? 
Thank you

**Comment by get-itips** [comment]
Hello @kaarins can you help us with this?
Thank you!

**Comment by get-itips** [comment]
Hello @kaarins can you kindly help us with this?
Thank you!

**Comment by kaarins** [comment]
Hi, I'm working on an update to this article. I'm waiting on information from the feature team. Thank you!

**Comment by scanum** [comment]
@kaarins Hi Kaarin, any update on this? Thanks!

**Comment by get-itips** [comment]
> Hi, I'm working on an update to this article. I'm waiting on information from the feature team. Thank you!

Hello @kaarins did you have chance to get the update on this article? Thank you!

**Comment by scanum** [comment]
@kaarins Wondering if there is an update on this issue? Thanks!

**Comment by get-itips** [comment]
@kaarins could you get the update to this article? Thank you! 👍

**Comment by scanum** [comment]
@kaarins Following up on this issue.

**Comment by scanum** [comment]
@kaarins Following up on this issue.

**Comment by scanum** [comment]
@kaarins Following up on this issue.

**Comment by kaarins** [comment]
@StephenRiceMSFT can you please advise?

**Comment by scanum** [comment]
@StephenRiceMSFT Any updates on this? Thanks

**Comment by scanum** [comment]
@StephenRiceMSFT Any updates on this? Thanks

**Comment by scanum** [comment]
√

**Comment by scanum** [comment]
@StephenRiceMSFT Any updates on this? Thanks

**Comment by StephenRiceMSFT** [comment]
@Jeff<mailto:jmcdowe@microsoft.com>, have you had a chance to answer this by chance?


<http://aka.ms/weboutlook>

________________________________

**Comment by scanum** [comment]
@StephenRiceMSFT Any updates on this issue? Thanks!

**Comment by StephenRiceMSFT** [comment]
Tagging @Jeff McDowell<mailto:jmcdowe@microsoft.com> 🙂
________________________________

**Comment by tseward** [comment]
This is meant for non-AAD IdPs, so instead of sending you to login.microsoftonline.com -> IdP, you're immediately sent to your IdP. See https://techcommunity.microsoft.com/t5/sharepoint-support-blog/auto-acceleration-in-sharepoint-online/ba-p/172423 for more information.

**Comment by scanum** [comment]
@ArttuArstila Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
