### ISSUE TITLE
Maximum of 1000 domains limitation is not seen in practical from Admin Center. I think it is only a recommendation.

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/OfficeDocs-SharePoint#1098]
Hello Team, 

I see that Maximum of 1000 domains limitation is not seen in practical from Admin Center for external sharing. I think it is only a recommendation to go with 1000 count. Can you please update this blog to reflect the same. This will help others also who are working on this area.

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Restricted domains sharing in SharePoint Online and OneDrive for Business](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing#feedback)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@bhanuchintha  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by bhanuchintha** [comment]
Thanks @scanum

**Comment by get-itips** [comment]
Hello @bhanuchintha 
Can you share the blog link that you are talking about in your post ?
Thank you

**Comment by bhanuchintha** [comment]
Hello @get-itips , Sure. Please find the attached mail from the O365 support ticket that i have raised and the response i received.

![O365 Support Ticket](https://user-images.githubusercontent.com/19674673/59922678-37aa7a00-9429-11e9-960f-17d4d5d9bed5.PNG)

Thanks & Regards,
Bhanu

**Comment by get-itips** [comment]
Adding @MikePlumleyMSFT 
Hello Mike, do you think that is enough to change the maximum guidance currently present in the article to a recommendation? Thank you

**Comment by bhanuchintha** [comment]
Also, in the site collection level sharing, it is accepting 100 domains not 60 domains. Please correct this also if possible.

**Comment by MikePlumleyMSFT** [comment]
I have checked on this and the plan is to keep the guidance as is for the time being.

**Comment by get-itips** [comment]
Thanks @MikePlumleyMSFT for clarification. So we won't update the article and leave it as is, this can be closed @yogkumgit

**Comment by bhanuchintha** [comment]
Thanks @MikePlumleyMSFT . So, It is recommended to configure only the external domains less than or equal to #1000 count. Even though the textbox accepts additional text.

**Comment by bhanuchintha** [comment]
Hello @MikePlumleyMSFT, 

May i know, If I configure external sharing such a way with - "Don't allow sharing with users from these blocked domains" - This means i can share my site to any number of domains & more than 1000 domains also and I do not need to specify them in the text box provided - https://<<TenantName>>-admin.sharepoint.com/_layouts/15/online/ExternalSharing.aspx. Am i right? So, This way - i can overcome the 1000 allowed domains. Can you please confirm? 

Thanks & Regards,
Bhanu

**Comment by MikePlumleyMSFT** [comment]
@bhanuchintha, yes, that's correct. If you use **Don't allow sharing with users from these blocked domains** then you can share with any domains other than those listed. If the setting is off, you can share with any domain. The only time there's a limit to the domains that you can share with is if you use **Allow sharing only with users from these domains**.

**Comment by bhanuchintha** [comment]
Thanks @MikePlumletMSFT for the clarification.

**Comment by TennysonMonSQL** [comment]
Is this functionality available on GCC high? Anyone know when it will be available. Looking for a tenant level (Azure) solution, for GCC high site owner to allow a user to read & contribute to a document on SharePoint with the user restricted to that folder(object). Any feedback welcome!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
