### ISSUE TITLE
Indicate whether these GPO Settings available on Windows 7 and 8.x

### ISSUE THREAD

**Issue by gtageek** [MicrosoftDocs/OfficeDocs-SharePoint#1099]
Hello - the article does not indicate clearly whether (or not) these GPO settings are available on Windows 7 and 8.x.

Can you add that info please?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@gtageek  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @gtageek thanks for your feedback.

Opening the .admx file, all of the following policies

- Configure team site libraries to sync automatically
- Use OneDrive Files On-Demand

 have the following setting
`<supportedOn ref="windows:SUPPORTED_Windows_10_0_RS3" />`

So we can confirm what the article currently says for the following policies, which is

> The feature is available to users running Windows 10 Fall Creators update (version 1709 or later)

the only one that does not says so is

- Convert synced team site files to online-only files

So I'll create a Pull Request to add a note for it.

All other policies say:

`      <supportedOn ref="windows:SUPPORTED_Windows7" />`

**Comment by scanum** [comment]
@gtageek Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
