### ISSUE TITLE
broken link (documentation feedback)

### ISSUE THREAD

**Issue by aendie** [MicrosoftDocs/OfficeDocs-SharePoint#110]
The link to "Quick reference guide: SharePoint Server 2016 databases" does nowhere. Please repair it. I'm on: https://docs.microsoft.com/en-us/SharePoint/technical-reference/database-types-and-descriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8065895-eb6b-e4a5-967a-73bee4605d50
* Version Independent ID: ce168605-1ed4-d626-476d-d4120be2a6cf
* Content: [Database types and descriptions in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/technical-reference/database-types-and-descriptions)
* Content Source: [SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by Techwriter40** [comment]
@bentoncity for your review

**Comment by bentoncity** [comment]
Have removed this link to the site that showed the poster and republished the article. The links to download this poster as PDF or Visio files is still present.
