### ISSUE TITLE
There seems to be a problem with one of your paragraphs

### ISSUE THREAD

**Issue by v-lorm** [MicrosoftDocs/OfficeDocs-SharePoint#1100]
This paragraph doesn't have the proper style for an Important note and the last sentence is not complete.
"Important: It is not recommended to delete the root site collection. If you delete the root site collection, all SharePoint sites in your organization will be inaccessible until you restore the site or create a new site at "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bd11d3-f2a4-2811-09bd-449c3c3607da
* Version Independent ID: 2f47da99-02e6-3357-ed41-b28bd5190907
* Content: [Delete a site](https://docs.microsoft.com/en-us/sharepoint/delete-site-collection#feedback)
* Content Source: [SharePoint/SharePointOnline/delete-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delete-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@v-lorm Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @v-lorm thanks for noting this. I created a Pull Request to correct this.
Thank you

**Comment by scanum** [comment]
@v-lorm Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
