### ISSUE TITLE
Extra right-angle bracket

### ISSUE THREAD

**Issue by v-lorm** [MicrosoftDocs/OfficeDocs-SharePoint#1101]
You have a trailing right-angle bracket in the following Note:
If you don't see the options above, under Admin centers, select SharePoint and then select New &gt; Private Site Collection. &gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0419db4c-9918-fcbe-53b3-4aca315e7703
* Version Independent ID: 0eca18cd-d073-8a6c-47ba-3e3330d63167
* Content: [Create a site](https://docs.microsoft.com/en-us/sharepoint/create-site-collection)
* Content Source: [SharePoint/SharePointOnline/create-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@v-lorm  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@v-lorm I've created a PR for it
