### ISSUE TITLE
Last purple note with "AutoSave" tab should actually say "Backup" tab

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SharePoint#1106]
"Users can direct their known folders by opening OneDrive sync client settings, clicking the AutoSave tab, and then clicking Update folders."

should be: 

"Users can direct their known folders by opening OneDrive sync client settings, clicking the Backup tab, and then clicking Manage backup"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@soyalejolopez Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@soyalejolopez I confirm the issue and created a PR to fix it
