### ISSUE TITLE
Please clarify what you mean with "when you DELETE a user"

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#1110]
Up to now we have DELETED users by blocking sign in. In this document you are not making clear what action you exactly refer to when you say  "when you delete a user" . I realize that from your perspective is should be totally clear .. duh "you press delete" , but you need to clarify please, using Azure, Using O365, what step triggers this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion?redirectSourcePath=%252farticle%252fef883c48-332c-42f5-8aea-f0e2366c15f9)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Deletion means removed from Azure AD. Blocking, as you're doing, isn't deleting. See the first step, which outlines what you're asking:

> A user is deleted from the Microsoft 365 admin center or is removed through Active Directory synchronization.

**Comment by blouwagie** [comment]
Thank you Trevor,
My remark is/was more for other readers to benefit from and to share how
readers may not quite get unless really really clear. Ok maybe it's me :-)
Thank you for confirming
Bart


Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)

http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call is needed)

**Comment by tseward** [comment]
@blouwagie is there anything in the article that you'd like to change? In my personal opinion, I think the 1. section under 'The OneDrive deletion process' is fairly clear.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@blouwagie We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
