### ISSUE TITLE
Enabling Files on Demand locks the OneDrive folder in the users profile preventing profile deletion

### ISSUE THREAD

**Issue by hal18ut** [MicrosoftDocs/OfficeDocs-SharePoint#1111]
If a user enables Files on Demand, we can no longer delete that users profile cleanly as the OneDrive folder (and its contents) under %userprofile% can't be deleted by any of the usual clean up methods like the advanced tab on sysdm.cpl for deleting profiles, the "Delete user profiles older than a specified number of days on system restart"  group policy, etc.
The OneDrive folder left behind under %userprofile% after attempting to delete the profile can't even be shifted via an smb connection to the windows pc.

This is causing us a huge headache, as we run a large number of lab machines for students to use and they keep filling their drives with stuck contents of OneDrive.

Just to clarify - this isn't roaming profiles I'm talking about as they're not supported. This happens to local profiles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116a7d33-b79a-f07d-b9de-d032d805c8d5
* Version Independent ID: 94908ca2-5edc-eb8c-b8a2-72cf61969dc7
* Content: [Set Files On-Demand states](https://docs.microsoft.com/en-us/onedrive/files-on-demand-mac#feedback)
* Content Source: [OneDrive/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hal18ut thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
