### ISSUE TITLE
"Large Sites" reports is not being generated

### ISSUE THREAD

**Issue by madhawak** [MicrosoftDocs/OfficeDocs-SharePoint#1112]
Hey guys, We ran the the SMAT tool for our SP2013 farm but I couldn't find the Large Sites reports. Any idea how to generate this report?

https://docs.microsoft.com/en-us/sharepointmigration/migration-assessment-scan-large-sites

**Comment by scanum** [comment]
@madhawak thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
