### ISSUE TITLE
Set OneDrive delegation manaully

### ISSUE THREAD

**Issue by rickyf56** [MicrosoftDocs/OfficeDocs-SharePoint#1113]
In my organization we would like to turn off the automatic OneDrive delegation to manager's but there might be cases where would like enable this feature for specific user's or for one-off instances, is that a possibility?  If so, where can I find this documentation?  Thanks!

**Comment by scanum** [comment]
@rickyf56 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
