### ISSUE TITLE
No download link

### ISSUE THREAD

**Issue by CloudSmithBrandon** [MicrosoftDocs/OfficeDocs-SharePoint#1114]
"Download and install the SharePoint Migration Tool using Internet Explorer, Edge or Chrome browser." is obvious and not helpful.  Please supply a fwlink to the appropriate download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by joshuc** [comment]
I proposed a change to the documentation to more clearly point to the download links.

**Comment by scanum** [comment]
@CloudSmithBrandon Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@CloudSmithBrandon Thank you for reaching out, I have checked and the link is reflecting, perhaps it was fixed in the interim. Please let me know and thank you for helping to improve MS Docs.

**Comment by JoanneHendrickson** [comment]
fixed.
