### ISSUE TITLE
Setting IP restriction for Individual sites

### ISSUE THREAD

**Issue by mukteswarp** [MicrosoftDocs/OfficeDocs-SharePoint#1116]
Is it possible to restrict individual sites with IP restriction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Control access to SharePoint Online and OneDrive data based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location?redirectSourcePath=%252fen-us%252farticle%252fcontrol-access-to-sharepoint-online-and-onedrive-data-based-on-defined-network-locations-b5a5f1f1-1174-4c6b-91d0-9273a6b6971f)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Yes, see the other article in the index - https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-a-specific-sharepoint-site-or-onedrive

**Comment by scanum** [comment]
@mukteswarp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
