### ISSUE TITLE
Default Folder Path environment variable?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/OfficeDocs-SharePoint#1117]
Hello,

Is it possible to use the "HOME" environment variable as a part of the default folder path? If so, what would be the syntax? Would like to have something like "$HOME/OneDrive". Not sure how to indicate that within XML.

Thanks,
Craig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync client for Mac](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos?redirectSourcePath=%252fen-us%252farticle%252fConfigure-the-new-OneDrive-sync-client-on-macOS-eadddc4e-edc0-4982-9f50-2aef5038c307)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@FMCUSystemAdmins thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
