### ISSUE TITLE
Query doubt

### ISSUE THREAD

**Issue by hemantse** [MicrosoftDocs/OfficeDocs-SharePoint#112]
I want to migrate from on-premise  file share to share point online.  I have  content type at destination document library and few custom column for that document library. How can I specify  those values(metadata) while executing those commands. I want to use Migration API in windows service and want to run as Job. I was expecting that there will be some way by which I will create xml file where I can add values and than pass on this xml to one of these commands and those commands in tern modify the manifest.xml and destination document library can be updated with those values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b01f633-962a-274d-1769-e008e7049f03
* Version Independent ID: c63b4c45-f5c6-d0fb-e14f-095f79b1a415
* Content: [Upload on-premises content to SharePoint Online using PowerShell cmdlets](https://docs.microsoft.com/en-us/sharepointmigration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets)
* Content Source: [migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@hemantse - I am not a SME on this in particular. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. It seems like what you are trying is reasonable and we need to get this scenario documented if it is supported. Opening a service ticket will get this routed and prioritized so it doesn't go stale here in the doc issues.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
