### ISSUE TITLE
Limits for user profile properties

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/OfficeDocs-SharePoint#1121]
Unfortunately, the page does not list if there is a limit for user profile properties. It would be great, if this can be added, if there are any limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d1a46c-4a3b-f99d-cca8-326b36235b1d
* Version Independent ID: d99a6050-b1af-afa2-8948-b1bba2ea7398
* Content: [Software boundaries and limits for SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
I can't think of any specific limits regarding UPSA properties. You should be able to create as many as you need to.

**Comment by scanum** [comment]
@lafe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
