### ISSUE TITLE
Change text to add remark on using SQL aliases - this is preferred over DNS aliases and it is missing

### ISSUE THREAD

**Issue by flaviuc** [MicrosoftDocs/OfficeDocs-SharePoint#1122]
We currently have this snippet in the article:

To help simplify maintenance, such as to make it easier to move databases to another server, create DNS aliases that point to the IP address for all instances of SQL Server. For more information about DNS or Hostname aliases, see How to Add a Hostname Alias for a SQL Server Instance.

However this is not really the recommended way, the better technical option is SQL aliases.
There are PROs and CONs of course, but SQL aliase is overall a better option and is not even mentioned.
It should be at least added, if not even marked as recommended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588cac-efbb-da8f-8b1f-8f4a21298116
* Version Independent ID: d5fead27-6212-5bc7-5bbf-9ce2066f479d
* Content: [Best practices for SQL Server in a SharePoint Server farm](https://docs.microsoft.com/en-us/SharePoint/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm)
* Content Source: [SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@flaviuc @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @flaviuc 

Thanks for your suggestions and patience.

We will pass this on to the team and consider adding it in the future after investigating. 

Thank you! :)

**Comment by scanum** [comment]
@sowjanya365 Any updates on this? Thanks

**Comment by scanum** [comment]
@sowjanya365 Any updates on this? Thanks

**Comment by scanum** [comment]
@sowjanya365 Any updates on this? Thanks

**Comment by sowjanya365** [comment]
Hi @flaviuc 

Thank you for your patience!

After the investigation, we understand that DNS Alias is now the MS recommended approach to configuring SQL Server instances for SharePoint. 

If you are specifically looking for how to add SQL Alias, please refer to the following article. 

https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/how-to-change-the-database-in-farms#step-1-create-a-new-sql-alias-on-all-sharepoint-servers-in-the-farm

Hope this clarifies. Thank you!

**Comment by scanum** [comment]
@flaviuc 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
