### ISSUE TITLE
SharePoint Online tenant to tenant

### ISSUE THREAD

**Issue by AdvisiconIT** [MicrosoftDocs/OfficeDocs-SharePoint#1123]
Can this tool be used to do a SharePoint Online tenant to tenant migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support?](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
No, it cannot.

**Comment by AdvisiconIT** [comment]
Any plans on making tenant to tenant in the future?

**Comment by tseward** [comment]
I can't speak to unannounced features, if one exists. UserVoice would be the proper location to ask, and there is a UV item you can vote on here which does have an MSFT response:

https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-and-migration/suggestions/31785250-support-sharepoint-online-to-sharepoint-online-mig

**Comment by scanum** [comment]
@AdvisiconIT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
