### ISSUE TITLE
Tenant IDs have letters not just numbers

### ISSUE THREAD

**Issue by anyITsolution** [MicrosoftDocs/OfficeDocs-SharePoint#1127]
Hi Team, I was setting this up with my client today the instructions for verifying that the setting worked you guys did not specify that is for Verification purposes instead we kept trying to set this manually at the PC level there should be at least an indicator that is how you verify after you have setup the GPO that handles this configurations. Also on the tenant ID you guys use an example 1111-2222-3333-4444 tenant ID's also use letters at least do an example that includes one set of letter such as A111-B222-C333-D444 so users recognize this as the tenant ID at least newly incoming Cloud Admins .. Hope this helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@anyITsolution thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
