### ISSUE TITLE
This article is poor

### ISSUE THREAD

**Issue by AmirRiaz19** [MicrosoftDocs/OfficeDocs-SharePoint#1128]
Opening duplicate paragraphs, grammar mistakes and less refined words. Flow is not correct. The whole note paragraph with "All drives are physically destroyed before leaving the datacenter" is completely irrelevant....

Please fix this article. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac22961-da69-7b22-6dff-f7bc5ee82ed3
* Version Independent ID: dd4ed11e-a0f9-4e97-48ae-8bd94f510c07
* Content: [How the SharePoint Migration Tool works](https://docs.microsoft.com/en-us/sharepointmigration/how-the-sharepoint-migration-tool-works#feedback)
* Content Source: [migration/how-the-sharepoint-migration-tool-works.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-the-sharepoint-migration-tool-works.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@AmirRiaz19  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Improving article on PR #1143
