### ISSUE TITLE
Can't enable SPO feature

### ISSUE THREAD

**Issue by wnzn** [MicrosoftDocs/OfficeDocs-SharePoint#1129]
Set-SPOTenant : Setting the property EnableAzureADB2BIntegration is not supported by your version of the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview#feedback)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by sergeyz7** [comment]
Same here. On Targeted release, in Europe.

**Comment by MikePlumleyMSFT** [comment]
The feature is currently rolling out. You should see it available on your tenants within the next ten days.

**Comment by sergeyz7** [comment]
Thanks for the clarification @MikePlumleyMSFT

**Comment by wnzn** [comment]
Thanks, Mike. I read this page before I saw the announcement in the message center. A notification header on the page that it's still rolling out would be nice (but not necessary).

**Comment by scanum** [comment]
@Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by jcallaghan** [comment]
Would it be possible to standardise the message that is returned when the feature isn't available? For other SPO features, we've previously seen messages about a given feature is experimental which immediately called out it wasn't available in that particular tenant.
