### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by ramch11** [MicrosoftDocs/OfficeDocs-SharePoint#113]
Look and Feel of the page is not as good as the old version, It was fantastic in technet.microsoft.com, Structure of the content was also very good in TechNet. but not in docs.microsoft.com. You don't get feel to read in docs.micrsofot.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79c20edf-7382-7fe9-d8be-135fbe746100
* Version Independent ID: 5f7d0158-5095-1b61-ffd1-986dcf7ceb55
* Content: [SharePoint PowerShell](https://docs.microsoft.com/en-us/SharePoint/sharepoint-powershell)
* Content Source: [SharePoint/SharePointServer/sharepoint-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sharepoint-powershell.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
thank you for your comment, what would you like to see change or added?

**Comment by kenwith** [comment]
@ramch11 - let us know what we can improve. There is a team that is constantly working on improvements with docs.microsoft.com and the source being open on GitHub. Thanks for feedback above. We will let that team know and if you can provide some specifics as Kirk mentioned that would be awesome.

**Comment by ramch11** [comment]
Just see how the structure and feel of the the Amazon, it is very nice and pleasure to see .. for ex : https://docs.aws.amazon.com/quickstart/latest/deep-security/step3.html , I want microsoft one like this.. earlier technet was good but not docs.microsoft.com

**Comment by kenwith** [comment]
@ramch11 - this is great info and I see how nice the amazon link you provided looks. It has a nice look and feel. I will send this feedback to the team that handles docs.Microsoft.com. Thanks for taking the time to submit!
