### ISSUE TITLE
How to add/remove SharePoint Online site administrators?

### ISSUE THREAD

**Issue by clarpaul** [MicrosoftDocs/OfficeDocs-SharePoint#1130]
How can I add or remove SharePoint Online site administrators? I need to remove myself from the set of users responsible for site administration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ec832-b81d-d057-27e6-a73ddf5a6632
* Version Independent ID: 7062cc8d-9769-3463-6b75-226679d720d1
* Content: [Default SharePoint groups](https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups#site-administrators)
* Content Source: [SharePoint/SharePointOnline/default-sharepoint-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/default-sharepoint-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@clarpaul thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
