### ISSUE TITLE
SharePoint Online limits

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-SharePoint#1134]
Hello,

This document doesn't apply to SharePoint online. Does this mean that 50,000 scopes per list or document library limit doesn't apply to SharePoint Online? or is there another document which targets to SharePoint online. If there is one could you please share which is applicable for SharePoint Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f583c6-5b66-377b-3fa1-07594621b82a
* Version Independent ID: 4f9bab3d-17df-7200-1a59-82ebd33ecc0f
* Content: [Best practices for using fine-grained permissions in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@ravick4u Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
@ravick4u Yes indeed, there's one:
https://docs.microsoft.com/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits

**Comment by scanum** [comment]
@ravick4u Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
