### ISSUE TITLE
Telemetry blocking

### ISSUE THREAD

**Issue by EnjoyThisCode** [MicrosoftDocs/OfficeDocs-SharePoint#1138]
Can you block traffic to bl3301-g.1drv.com, bn2.vortex.data.microsoft.com.akadns.net etc without breaking the app? We have no intention of allow telemetry or data gathering

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42bcdeb-a2a5-e6f1-4779-d7d5b837db1e
* Version Independent ID: 2d2bc902-f138-621f-3fc2-1de76bbe3f22
* Content: [Supporting the SharePoint mobile apps online and on-premises](https://docs.microsoft.com/en-us/sharepoint/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises#feedback)
* Content Source: [SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by scanum** [comment]
@EnjoyThisCode thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by EnjoyThisCode** [comment]
Its not so much an issue but a question and one that would be good to share. We will block the traffic and see if it breaks the app.
