### ISSUE TITLE
Site migration

### ISSUE THREAD

**Issue by AsherBH12345** [MicrosoftDocs/OfficeDocs-SharePoint#1141]
If in the Source fields, only a site is required (I want to migrate all libraries), why is Column E required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration#feedback)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@AsherBH12345 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by santechuser** [comment]
when we use JSON fore Migration input, it is awlays coming up with error 
"There is a problem with your file. Check your file to see if it is formatted correctly and that it contains less than 100 tasks." I don't think the example is correct, can you pl check

we using very simple block and it doesn't work

{
  "Tasks":[
    {
      "SourcePath":"\\xxx\aip",
      "TargetPath":"https://xxx.sharepoint.com/sites/xxx",
      "TargetList":"TestingDocs",
      "TargetListRelativePath":"Folder1"
    }
  ]
}
