### ISSUE TITLE
Is this supposed to be 2019

### ISSUE THREAD

**Issue by dmcrock** [MicrosoftDocs/OfficeDocs-SharePoint#1142]
In step 2 below should it be 2019 instead of 2016?

Register Workflow Manager with SharePoint Server 2019
Use the following steps to register Workflow Manager with SharePoint Server 2019:

In the SharePoint 2016 farm, on the Central Administration website click Application Management and click Manage Service Applications, and then delete Workflow Service Applidcation Proxy.

In the SharePoint Server 2016 farm, run the following Microsoft PowerShell cmdlet to pair SharePoint 2016 together with the same Workflow Manager installation:

PowerShell

Copy
   Register-SPWorkflowService -SPSite &lt;SharePoint site URL&gt; -
   WorkflowHostUri &lt;Workflow service endpoint URL&gt; -force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfe3ea9f-a88d-1459-c536-bdab2617e2bb
* Version Independent ID: b1af7642-58d9-8329-3611-46cb18481e18
* Content: [Upgrade SharePoint 2016 to SharePoint 2019 through Workflow Manager](https://docs.microsoft.com/en-us/sharepoint/administration/upgrade-sharepoint-2016-to-sharepoint-2019-through-workflow-manager#feedback)
* Content Source: [SharePoint/SharePointServer/administration/upgrade-sharepoint-2016-to-sharepoint-2019-through-workflow-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/upgrade-sharepoint-2016-to-sharepoint-2019-through-workflow-manager.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **toresing**

**Comment by scanum** [comment]
@dmcrock Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving with PR #1144

**Comment by tomresing** [comment]
Article was updated already addressing this issue
