### ISSUE TITLE
Outdated information?

### ISSUE THREAD

**Issue by poweroftao** [MicrosoftDocs/OfficeDocs-SharePoint#1146]
I cannot find this menu on my OneDrive account page. The provided link above https://admin.onedrive.com/?v=SyncSettings goes to https://onedrive.live.com and I cannot find the relevant link to access sync settings (e.g.  (https://onedrive.live.com/?v=managestorage). Please update this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types#feedback)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@poweroftao  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by mikewaretena** [comment]
The link takes you to the right location in the OneDrive for Business admin center. Perhaps you are looking at OneDrive personal account?

**Comment by scanum** [comment]
@poweroftao  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by LuGuoHuas** [comment]
Hello, I also met the same problem.
When I open https://admin.onedrive.com/?v=SyncSettings, I actually entered https://onedrive.live.com. I didn't find a similar option in the settings. I hope to ignore one. File or file type to ensure that onedrive has no exception prompt.
I am an office 365 Home Edition user.

**Comment by dc3671** [comment]
@mikewaretena Could you please provide more information about personal onedrive?
