### ISSUE TITLE
Import SSL certificate to Web Application Proxy server - requirements clarification

### ISSUE THREAD

**Issue by ashokgop** [MicrosoftDocs/OfficeDocs-SharePoint#1147]
There appears to b conflicting details on the SSL certificate private key requirements when installing on the WA-P.  
The article (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn584113%28v%3dws.11%29#ad-fs-proxy-functionality) indicates "Web Application Proxy servers do not have access to the private keys that are used to produce tokens."
However the current article section "Import Secure Channel SSL Certificate" (https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-web-application-proxy-for-a-hybrid-environment#import-the-secure-channel-ssl-certificate) seems to indicate that the private key is required on the WA-P along with the Full Control permissions for the service account running the WA-P service.
 Can you please clarify?

Thanks
AG
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1f3f563-76c3-64c0-71ee-f54f61e7124c
* Version Independent ID: f9d03093-9aff-bf0b-fecb-f00dce23a4cf
* Content: [Configure Web Application Proxy for a hybrid environment](https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-web-application-proxy-for-a-hybrid-environment)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-web-application-proxy-for-a-hybrid-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-web-application-proxy-for-a-hybrid-environment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ashokgop  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
@ashokgop 
Absolutely:
In the article you mention [the second one](https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-web-application-proxy-for-a-hybrid-environment#import-the-secure-channel-ssl-certificate) the reference are to the **service account of the Web Application Proxy Service** the one that requires the access to the private key, not the server itself like your 1st reference.

On the 1st reference it's related to the Proxy server without having access to the Private key, but the

**Comment by scanum** [comment]
@ashokgop Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
