### ISSUE TITLE
Target Links Issue

### ISSUE THREAD

**Issue by mmohamedbasith** [MicrosoftDocs/OfficeDocs-SharePoint#1148]
There is a link behavior issue with links from different site(same tenant) in my hub navigation opens in different tab.  According to this article(https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience), it should open in same tab .
By default, navigation links on modern SharePoint sites open as follows:
Link points to a page or site in the same tenant (same site or another site): Links open in the same tab.

I have raised this issue by calling MS Support . They have acknowledged it as issue and created this uservoice 
https://office365.uservoice.com/forums/264636-general/suggestions/37557853-sharepoint-sites-that-are-registered-as-hub-site-h . 

I tested this in multiple tenants. same result. This is a very minor issue to fix . Expecting a quick turnaround to fix it from MS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience#feedback)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@mmohamedbasith  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@mmohamedbasith Thanks for commenting, we believe the best option is to follow up with support since this is not strictly related to documentation.  Based on the outcome let me know if it is something that can be called out in the docs. Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
