### ISSUE TITLE
SP 2016 / 2019

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#1149]
Need updated recommendations based on MinRole deployment types for how large the cache size should be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff8221d-8995-2bd1-9ab4-e0043afe1c5f
* Version Independent ID: 2b157758-daa4-dad2-5edb-891e421d921f
* Content: [Manage the Distributed Cache service in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tseward** [comment]
@danmyhre MinRoles have no impact on cache size guidance. The solution provided is an example. If you have a need to reserve more than 2GB (as might be the case for a shared MinRole), do so.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot close
