### ISSUE TITLE
Incorrect documentation of supported SharePoint 2013 login name format

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/OfficeDocs-SharePoint#1152]
The [documentation](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#using-the-sharepoint-migration-tool-1) states:

> Enter your username and password to the SharePoint Server site; username must use the format of someone@example.com. 

This is **not** correct.

For SharePoint Migration Tool version 3.0.111.5. I can successfully log in using my windows login name (without the domain part) and the login name does **not** have the format "_someone@example.com_". It is just "_username_".

This should be clarified so that answers based on this documentation don't lead into wrong directions, as (probably) can be seen [here](https://social.msdn.microsoft.com/Forums/en-US/7c367fdb-f197-4f54-b75e-2f6354c7f025/migration-with-microsoft-sharepoint-migration-tool?forum=Office365forDevelopers).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@heinrich-ulbricht  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by heinrich-ulbricht** [comment]
Note: my assumption is that this behavior is the same in SPMT v2. This assumption might be wrong.

**Comment by sowjanya365** [comment]
Hi @heinrich-ulbricht 

Thanks for reaching out!

Would you so kind as to elaborate more on this? You are saying that, you were able to login to "Migration tool" with the windows credentials. And the following statement from documentation states about entering the credentials on "SharePoint Server Site". Both are different steps. 

"Enter your username and password to the SharePoint Server site; username must use the format of someone@example.com."

Hope this clarifies your query. Kindly confirm. Thank you!

**Comment by scanum** [comment]
@heinrich-ulbricht We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by heinrich-ulbricht** [comment]
@sowjanya365 Here is my understanding of the documentation.

This preface describes the option to migrate from SharePoint 2013 and that you have to log in to the SharePoint Server 2013 site via the Migration tool:

> You will be prompted for the current location of your data files and the location of the SharePoint Online site collection where you want them copied. The **SharePoint Migration Tool lets you select from two sources** from which to migrate your data: **from an on-premises SharePoint Server** 2010 or **2013 site** or from a local file share or network path.

> SharePoint on-premises: If you select the SharePoint on-premises option, you **will be asked [by the migration tool] to enter the name of the SharePoint Server site** where your files are located and **prompted for your credentials for that site**.

(Emphasis and addition mine.)

Then when describing how to actually use the migration tool there is the sentence you cited and which I claim to be wrong:

> Enter your username and password to the SharePoint Server site; username must use the format of someone@example.com.

In my understanding this means: when migrating from SharePoint 2013 and when logging in to a SharePoint 2013 site via the Migration Tool I must use the format _someone@example.com_. This does not correspond to my experience because I had to use a non-e-mail-format username.

But maybe I'm reading this wrong in which case I'd be interesting to know how to read this properly.

**Comment by heinrich-ulbricht** [comment]
@scanum Could you please re-open the issue? I'm not permitted to do this.
