### ISSUE TITLE
Document confusing error handling of SSL/TLS certificate errors

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/OfficeDocs-SharePoint#1153]
When connecting to a SharePoint 2013 server that serves an invalid SSL/TLS certificate the error message in the SharePoint Migration Tool user interface is confusing:

![image](https://user-images.githubusercontent.com/3469970/60882506-5772d800-a248-11e9-910d-4cdd0442e0e4.png)

> Please re-enter your user ID or password.

You can re-enter as much as you want it won't help. As long as this error message is so confusing the documentation should state SSL/TLS certificate errors as possible cause for such an error as it is extremely misleading.

Currently only looking at the log file helps identifying the correct cause:

`2019-07-09 12:45:58.3717|ERROR|GLB|44|Fail to check user has enough permission or not for given site https://<url>. Microsoft.SharePoint.MigrationTool.MigrationLib.SharePoint.MigSPWebException: Web Issue when doing SP Query ---> Microsoft.SharePoint.MigrationTool.MigrationLib.Common.Web.WebExceptionBase ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

(Btw the log files are located in _C:\Users\<username>\AppData\Roaming\Microsoft\MigrationTool\GlobalLog_ - which is also not documented anywhere it seems.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#using-the-sharepoint-migration-tool-1)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@heinrich-ulbricht thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by heinrich-ulbricht** [comment]
@scanum Since this issue is caused by the _on-premises_ SharePoint 2013 Server getting support from Microsoft is not an option (anymore). And not necessary, since we can solve this issue ourselves.

This ticket is about the current error handling in the SharePoint Migration Tool which is utterly misleading. There is nothing wrong with the user ID or password. Entering it again won't help. My assumption is that this won't be fixed soon. So the documentation should be updated.

I propose to add a troubleshooting section to the documentation, like this:

## Troubleshooting

#### When trying to log in to SharePoint on-premises the login fails with "Please re-enter your user ID or password."

Possible causes:
* the username or password used is not correct
* SSL/TLS certificate validation for the entered URL failed
* the URL entered into the URL field is not correct

**Comment by escricco** [comment]
I had same error (Please re-enter your user ID or password) when connecting to a SharePoint 2010 farm, and the log shows this error:
Web Issue when doing SP Query ---> Microsoft.SharePoint.Migration.Common.Exceptions.WebExceptionBase ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

It turns out I do require a proxy that is requiring authentication. Is that not supported?

Thanks
