### ISSUE TITLE
Why still in Preview

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#1154]
When will this feature become GA? it has been in preview for a few years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65452cc-aa20-7c77-b15c-bce7f443228a
* Version Independent ID: f5b34529-3968-4861-31f6-25d6cd501385
* Content: [Configure SharePoint Hybrid Auditing in SharePoint 2016 (Preview)](https://docs.microsoft.com/en-us/SharePoint/administration/configure-sharepoint-hybrid-auditing-preview#related-topics)
* Content Source: [SharePoint/SharePointServer/administration/configure-sharepoint-hybrid-auditing-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-sharepoint-hybrid-auditing-preview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@DeanGross thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
