### ISSUE TITLE
JIT conversion of existing ad hoc accounts

### ISSUE THREAD

**Issue by brassman2000** [MicrosoftDocs/OfficeDocs-SharePoint#1155]
Will there be JIT conversion of SPO ad hoc accounts into new AAD Guest accounts for the new AAD B2B model with integration into SPO/OneDrive?

I tested an existing ad hoc account that was previously shared from OneDrive prior to implementing AAD B2B with SPO/OneDrive integration.  After integration implementation, the ad hoc account was not converted to an AAD guest account.  I had heard there may be JIT conversion for SPO/OneDrive ad hoc accounts with the new AAD B2B model.

Retrieve ad hoc account via <https://Tenant OneDrive Url>/personal/_api/web/GetUserById(21) 
Sharing BEFORE change:  "LoginName": "i:0#.f|membership|urn%3aspo%3aguest#firstname.m.lastname@mycompany.com"
Sharing AFTER change - no change and the new AAD Guest account is not created.

**Comment by MSFTRafLop** [comment]
Yes - JIT conversion should be enabled for all tenants by the end of this week. I don't think your test tenant was enabled for JIT conversion during the private preview phase, hence why you're not yet seeing it. If you try again next week it should work.

The behavior is such that when the ad-hoc user clicks on their old/existing sharing link, we'll create a Guest account for them at that moment on behalf of the person who originally shared with that ad-hoc user (meaning the conversion is still subject to AAD settings such as Members can Invite).

**Comment by scanum** [comment]
@brassman2000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
