### ISSUE TITLE
[LOC] CodeBlock is not properly formatted

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1156]
**Article:** remove-users.md
**URL:**  https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/remove-users.md
**Author:** kaarins

Could you please check and update CodeBlock  _Remove-SPOExternalUser -UniqueIDs @($ExtUser.UniqueId)_  
Character \`\`\` are missing below the code. Therefore article text below is excluded from XLF and we're not able to translate the article properly

![image](https://user-images.githubusercontent.com/47977325/60944190-6ad58000-a2e8-11e9-8c29-468aaa29fe01.png)

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
