### ISSUE TITLE
User experience when sharing using B2B sharing preview

### ISSUE THREAD

**Issue by davegreen** [MicrosoftDocs/OfficeDocs-SharePoint#1157]
After enabling the preview functionality as per the guide, attempting to share to a domain that is disallowed (using the `Allow invitations only to the specified domains (most restrictive)` or `Deny invitations to the specified domains` setting in AzureAD) results in the following error instead of a user friendly 'you can't do that' error.

![image](https://user-images.githubusercontent.com/759393/60972901-0aae0080-a31f-11e9-8c21-1e58e0386eae.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview#feedback)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MSFTRafLop** [comment]
Thanks for submitting the issue! This is a good example of something that is currently expected / known issue but we'll certainly work on improving the experience throughout the preview phase and certainly by the time it exits preview.

You'll get the same sort of non-friendly error message for any other AzureAD settings you have which prevent the user from creating an invitation in SharePoint/OneDrive. For example, if Members Can Invite is turned off.

**Comment by scanum** [comment]
@davegreen thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Kazzan** [comment]
Hi, this error is still present. Also, it differ if also in SPO is limitation for external sharing to specific domains. These lists should be merged or mentioned that it apply for Teams, SharePoint and OneDrive also and both apply (AAD to External Guest, SPO to External Guests and External Sharing). I opened case because we run into the same. If you need number for reference, just let me know.

**Comment by cloudhal** [comment]
This error is a problem, we would like to enable this feature but do not allow guests from any domains. This will confuse a lot of users.
