### ISSUE TITLE
adding private IP subnet 10.242.0.0/16 not accepting

### ISSUE THREAD

**Issue by abid1975** [MicrosoftDocs/OfficeDocs-SharePoint#1158]
when i am trying to add my LAN IP range 10.242.0.0/16, it is taking ages and does not accept,, however adding public IP works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4264cd-3476-61ae-49dc-c5fa6118722a
* Version Independent ID: 8c419a14-db06-3b0d-66d3-ab396924721e
* Content: [Control access based on network location or app](https://docs.microsoft.com/en-us/onedrive/control-access-based-on-network-location-or-app#feedback)
* Content Source: [OneDrive/control-access-based-on-network-location-or-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-based-on-network-location-or-app.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@abid1975  thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
