### ISSUE TITLE
References to SharePoint 2016

### ISSUE THREAD

**Issue by pkothare** [MicrosoftDocs/OfficeDocs-SharePoint#1162]
The page has a note at the top that this article is explicitly for SharePoint 2013 only, yet a couple of steps in the article reference SharePoint 2016 cmdlets and timer jobs. Please fix this to avoid confusion, or provide additional detail in those steps specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80526df-f494-2aca-9a4a-ca6b8ee8ca08
* Version Independent ID: cbb5f0c3-7cce-489c-1bff-28df5709c5ab
* Content: [Synchronize user and group profiles in SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/configure-profile-synchronization)
* Content Source: [SharePoint/SharePointServer/administration/configure-profile-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-profile-synchronization.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@pkothare Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!
@scanum

**Comment by JohanFreelancer9** [comment]
Please open Pull Request.

**Comment by j0rt3g4** [comment]
I think that all has been already placed in place because there are no references to 2016 now on documents...
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1303

**Comment by j0rt3g4** [comment]
@scanum

**Comment by pkothare** [comment]
@j0rt3g4 not to be nitpicky 😅, I know that the title to this issue only mentioned SP 2016, but there is one more reference to SP 2010 I see on the page that could cause confusion.

Step 16 of  [Start Profile Synchronization](https://docs.microsoft.com/en-us/sharepoint/administration/configure-profile-synchronization#start-profile-synchronization)  has a hyperlink with a title  _Timer jobs cmdlets (SharePoint Server 2010)_

If that's insignificant feel free to close this issue.

**Comment by sowjanya365** [comment]
Hi @pkothare 

Thanks you. We've updated the document now. Once the PR gets merged, we will be able to see the changes. 

Thank you!
