### ISSUE TITLE
Confusing PowerShell instructions

### ISSUE THREAD

**Issue by carlyhublou** [MicrosoftDocs/OfficeDocs-SharePoint#1163]
Under step 1, I think it would be more helpful/user-friendly to format the list of emails as it should be formatted in the .txt file for this script to work, which is one email per line. The way it is written here suggests that emails should be written on the same line in the .txt. file, but this does not work with the script as written and is confusing to a non-PowerShell pro. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts#feedback)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@carlyhublou Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
