### ISSUE TITLE
Is there a plan to have a simliar article for SPO?

### ISSUE THREAD

**Issue by b6202lam** [MicrosoftDocs/OfficeDocs-SharePoint#1164]
See subject line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f583c6-5b66-377b-3fa1-07594621b82a
* Version Independent ID: 4f9bab3d-17df-7200-1a59-82ebd33ecc0f
* Content: [Best practices for using fine-grained permissions in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/best-practices-for-using-fine-grained-permissions-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
In many cases, this comes down to performance as to why you wouldn't want to say, have 50k scopes. Because performance is not something you can control in SPO (or server-side settings), while the article _technically_ applies, there isn't much to take away from it. An equivalent article for SPO would be targeted at an Information Worker/Site designer rather than an administrator.

**Comment by bernardlam** [comment]
@tseward Most of the best practices described in this article are things that developers and site collection admins should do, which is why I thought it can be adapted for SPO.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
