### ISSUE TITLE
Will this be turned on by default when rolled out after the preview?

### ISSUE THREAD

**Issue by wayno4** [MicrosoftDocs/OfficeDocs-SharePoint#1166]
I'm not clear if this will be turned on by default after it has completed rollout, or you will still need to enable it?  Can someone clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview#feedback)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@wayno4, it is the preview that has been rolling out. During the preview, you'll need to configure the feature using PowerShell as shown. After the preview period, it will be on by default.

**Comment by scanum** [comment]
@wayno4 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
