### ISSUE TITLE
Please add "Upload Document Template to Content Type" as a blocked feature

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/OfficeDocs-SharePoint#1168]
I found that custom scripts are necessary when attempted to add a document template to a content type in SPO, from Microsoft's response to the question below. Please update the document to reflect this.

https://answers.microsoft.com/en-us/msoffice/forum/all/cannot-upload-document-template-to-content-type/f3b27abb-52d0-41e5-be45-dc5185ba3f0e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#feedback)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@oliviadudley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @oliviadudley 

Thanks for reaching out!

Kindly let us know what exact error that you see when you try to "Upload Document Template to Content Type". Did you try contacting support team? 

Looking forward to your response. Thank you!

**Comment by oliviadudley** [comment]
Hi, Please reopen the request. According to the Microsoft employee responding to the thread linked below, due to custom scripts being disabled, users will be unable to upload document templates to content type. Please update the document to reflect this.

https://answers.microsoft.com/en-us/msoffice/forum/all/cannot-upload-document-template-to-content-type/f3b27abb-52d0-41e5-be45-dc5185ba3f0e

**Comment by oliviadudley** [comment]
Hi @sonika24 & @scanum, Please reopen the request. According to the Microsoft employee responding to the thread linked below, due to custom scripts being disabled, users will be unable to upload document templates to content type. Please update the document to reflect this.

https://answers.microsoft.com/en-us/msoffice/forum/all/cannot-upload-document-template-to-content-type/f3b27abb-52d0-41e5-be45-dc5185ba3f0e

**Comment by oliviadudley** [comment]
*bump* @scanum @sonika24

**Comment by oliviadudley** [comment]
*bump* @scanum @sonika24
