### ISSUE TITLE
No mention to sub-site creation options

### ISSUE THREAD

**Issue by ATJSM** [MicrosoftDocs/OfficeDocs-SharePoint#1171]
Previously, [this article](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation) included a section that talked about sub-site creation options like in the image attached below:

![image](https://user-images.githubusercontent.com/13952319/61345362-9fc26500-a809-11e9-81c1-5f71653e2667.png)

Why is the article not including this anymore? My target release tenant still shows those options.

Thanks!

**Comment by scanum** [comment]
@ATJSM Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @ATJSM 

Thanks for reaching out!

As the title says this article shows the information related to Site creation options and settings only. Thank you!

**Comment by ATJSM** [comment]
Hi @sowjanya365 

Not sure what you mean. There is a section within that article explicitly titles "Manage detailed site and **subsite** creation settings in the classic SharePoint admin center"

Thanks,

**Comment by sowjanya365** [comment]
Hi @kaarins 

Need your inputs and suggestions here. Thank you.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, could you please help up on next steps? Thanks!

**Comment by scanum** [comment]
@kaarins Hi Kaarin, could you please help up on next steps? Thanks!

**Comment by kaarins** [comment]
This was fixed some time ago.
