### ISSUE TITLE
Missing details on language packs

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#1173]
Missing details on how to update when language packs are involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757daa4f-85eb-2b0e-094a-f01b9ed3d874
* Version Independent ID: acfb92cf-1d51-d6a7-bebc-9c145f5b7710
* Content: [Install a software update for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
As you should be applying both the security and language-dependent fix (given one is shipped for a given month), this covers any language dependent fixes required.

**Comment by andikrueger** [comment]
see: https://docs.microsoft.com/en-us/sharepoint/support/administration/administration-tool-stopped-working-during-a-slipstream-installation

**Comment by danmyhre** [comment]
Not sure what that link has to do with this, but the page mentions no details on updating language packs.  It should be mentioning the sts* vs the wssloc* files, the order you install them in, and if you need to run psconfig only once after both are installed, etc.  Also missing details on steps you need to do with dist cache: Use-CacheCluster; Stop-CacheHost -HostName SERVERFQDN -CachePort 22233 -Graceful 

Thanks!

**Comment by tseward** [comment]
@danmyhre I see how that info could be useful. And that doesn't shutdown the cache cluster gracefully. You need to follow the guidance at https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service#perform-a-graceful-shutdown-of-the-distributed-cache-service-by-using-a-powershell-script.

I'll work on the article, taking a look at how we can incorporate the patch information.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by danmyhre** [comment]
Sounds good.  Thanks for the link to the script!  I'll get the Stop-SPDistributedCacheServiceInstance part added to my processes.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
