### ISSUE TITLE
Slipstream

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#1174]
Might be good to add details on maintaining and building a slipstream version of what is installed on the farm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d5bda8-9221-95d9-517e-99dfafa480ad
* Version Independent ID: 568872c6-5498-04a3-6263-a603f7c73292
* Content: [Software updates overview for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/software-updates-overview)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/software-updates-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/software-updates-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Slipstream cannot be done in 2016 due to a bug.

**Comment by andikrueger** [comment]
@tseward are you referencing this issue? https://docs.microsoft.com/en-us/sharepoint/support/administration/administration-tool-stopped-working-during-a-slipstream-installation

**Comment by tseward** [comment]
@andikrueger correct. This was resolved in SharePoint Server 2019.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by danmyhre** [comment]
How is it resolved?  The documentation is still out of date for 2019 and is missing versioning information.  Seems like a lot of the 2016 and 2019 docs are bleeding together but isn't versioned correctly.

**Comment by tseward** [comment]
I would agree that the documentation needs to be generalized for SharePoint 2016 and 2019 in this case, as the procedure is identical for both products. 2013 does have a slipstream section, which is what the 2019 built-in product documentation points to (https://go.microsoft.com/fwlink/?linkid=2003452) as the process is identical.
