### ISSUE TITLE
O365E Link Dead

### ISSUE THREAD

**Issue by Keybonesabi** [MicrosoftDocs/OfficeDocs-SharePoint#1175]
O365E Link Dead. Attempted to click on link. Points to Microsoft Dead Link Site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fbcb0b-9e6d-d2e7-5194-5593d35fff63
* Version Independent ID: f6d30df6-858b-4d3c-542f-a4d6b45ec3d8
* Content: [Hardware and software requirements for SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@Keybonesabi  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Keybonesabi** [comment]
Sweet! no problem.

Michael J. Martinez Jr.
Sharepoint Administrator
Army North Contractor
(210) 317-9487
michael.j.martinezjr@hotmail.com
https://LinkedIn.com/in/texasit



________________________________

**Comment by dplotnikov** [comment]
@Keybonesabi I've removed the link since Office 365 has nothing to do in that article

@Techwriter40 feel free to merge my PR and close this issue

**Comment by scanum** [comment]
@Keybonesabi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
