### ISSUE TITLE
Storage Sense + OneDrive Documentation?

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SharePoint#1180]
This roadmap item shows as launched, but not finding documentation on it: 

**ODB Admin: Management of Files On-Demand Storage Sense via GPO**
With Windows 10 Version 1903, admins can enable Storage Sense automated cleanup of OneDrive files via a GPO.
Featured ID: 49099
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=OneDrive%20for%20Business&searchterms=storage%2Csense

We have the following article but it's not specific to OneDrive: 
https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-storage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@soyalejolopez  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@soyalejolopez Thank you for reaching out and helping improve MS Docs.  Are you suggesting adding the link above to this article, but stipulating that it's not specific to OneDrive?

**Comment by soyalejolopez** [comment]
Hey @lindspea , indeed, having a link to the above article would be helpful, but even better would be OneDrive specific guidance. In our roadmap for OneDrive we announced the availability of this capability, but no link for further information/guidance.

**Comment by scanum** [comment]
@soyalejolopez Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
