### ISSUE TITLE
Device Access by location (IP) - Does it include shared links?

### ISSUE THREAD

**Issue by danielbls** [MicrosoftDocs/OfficeDocs-SharePoint#1181]
It isn't clear weather the device access by location (IP Address) restrictions apply to logging into OneDrive itself or if it also stops anyone from outside that IP range from using shared links. Will shared links work with this option enabled for someone outside the whitelisted IP range?

**Comment by scanum** [comment]
@danielbls Please link the document you are referring to. Thanks

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@danielbls 
 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
