### ISSUE TITLE
OneDrive does not restart after update to machine based version

### ISSUE THREAD

**Issue by A55imilat0r** [MicrosoftDocs/OfficeDocs-SharePoint#1183]
We are attempting to update from user based install to machine based install OneDriveSetup.exe /allusers via sccm. 
However after installed OneDrive fails to restart for the user as expected and as quoted by the machine based install docs. I also submitted this feedback via the feedback tab in the OneDrive app the onedrive support number is 1452225 and I would appreciate some support around this. Otherwise well need to not released the machine based version to production moving forward.

**Comment by scanum** [comment]
@A55imilat0r thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
