### ISSUE TITLE
SharePoint 2007 & 2010 Software Boundries and Rate limits doc missing

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/OfficeDocs-SharePoint#1184]
Whilst SharePoint 2007 is out of support and SharePoint 2010 is nearing end of support, both products are still in use in organisations and as such these documents are critical for those helping either support these systems or understand 

As  I would expect that there should be a similar doc here for these versions as there is for 2016/2019 - https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0

The closest I can find to this was a technet link via the Wayback archive that has both 2007 and 2010 docs - https://web.archive.org/web/20170708023615/https://technet.microsoft.com/en-us/library/cc262787%28v=office.14%29.aspx

As docs.microsoft.com replaced technet this should be made available with notices that this is only provided for historical support reasons

**Comment by scanum** [comment]
@kilasuit Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@kilasuit Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
