### ISSUE TITLE
we turned on comptiable mode as IE 11 on master page causing issues

### ISSUE THREAD

**Issue by mdittakavi** [MicrosoftDocs/OfficeDocs-SharePoint#119]
In our master page we have turned on
<meta http-equiv="X-UA-Compatible" content="IE=11" />  . By default it is IE=9

But this causing issue for 'Open with explorer' feature not working.  if we use IE=10 mode then it works.
we need some apps  on sharepoint to work using IE=11 only.  How this can be solved to work with IE 11 mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d1b075-d17b-510d-f886-4f5deed4cc9e
* Version Independent ID: 336f78e0-78e2-0a55-5e1b-2bf41072a0cb
* Content: [Plan browser support in SharePoint Server 2016](https://docs.microsoft.com/en-us/SharePoint/install/browser-support-planning-0)
* Content Source: [SharePoint/SharePointServer/install/browser-support-planning-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/browser-support-planning-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@mdittakavi - thank you for submitting feedback. I am not positive on this setting and I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mdittakavi** [comment]
Hi Ken

We are talking about on-prem. How online team can help on this.

Thanks and Regards,
Murali Dittakavi
Integration & Collaboration Technical Lead

**Comment by kenwith** [comment]
Please open a support ticket through your normal channel for on premises products. This list is for issues with documentation and we aren't set up to provide support. I am afraid if we leave this issue open in this list it will go stale and not be responded properly which is why I want to make sure any problem you are having goes through official support so that they can prioritize and handle correctly.
