### ISSUE TITLE
CreateSPAsyncReadJob gives error - value can not be null for parameter name: azureContainerManifestUri 

### ISSUE THREAD

**Issue by jayshah295** [MicrosoftDocs/OfficeDocs-SharePoint#1191]
Hi,

I am trying to execute CSOM API **CreateSPAsyncReadJob** for Asynchronous read metadata.
Below is my code .

                    var asyncReadOptions = new AsyncReadOptions();
                    asyncReadOptions.IncludeVersions = true;
                    asyncReadOptions.IncludeSecurity = true;
                                       
                    var result=clientContext.Site.CreateSPAsyncReadJob(${clientContext.Web.Url}/Shared Documents", asyncReadOptions);
                    clientContext.ExecuteQuery();

I am getting Below Error:
   
**Error Message: Value cannot be null.
Parameter name: azureContainerManifestUri**

Previously I was able to execute this API successfully without parameter azureContainerManifestUri however today I am getting this error.

As per definition of this API there is no need of parameter **azureContainerManifestUri** to execute this API.
  public IList<AsyncReadJobInfo> CreateSPAsyncReadJob(string url, AsyncReadOptions options);

**Reference Document** : https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPO-asynchronous-read-API.md

Any help will be appreciated.

Thanks in Advance.

**Comment by scanum** [comment]
@jayshah295 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
