### ISSUE TITLE
Advanced settings for shareable links

### ISSUE THREAD

**Issue by bytemybitz** [MicrosoftDocs/OfficeDocs-SharePoint#1192]
It's not clear if setting the files and folders options to 'view' limits the sharing permission immutably or if this is setting a default that can be overidden by the user.

**Comment by scanum** [comment]
@bytemybitz Please link the document you are referring to. Thanks!

**Comment by bytemybitz** [comment]
Apologies, wrongly assumed that was passed in when I followed the feedback link.

https://docs.microsoft.com/en-us/onedrive/manage-sharing
-> Advanced settings for shareable links

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @bytemybitz 

Thank you for reaching out!

Setting the "Files and Folders" options do not limit the sharing permission. But the users with the sharing link are limited to either "view" or "View, edit, and upload" permissions on the files and folders present on the link.

Hope this clarifies your query. Kindly confirm. Thank you.

**Comment by scanum** [comment]
@bytemybitz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by bytemybitz** [comment]
Sorry for not responding sooner.  If I as an admin set the files to 'view', can an end user - not the link recipient - override this and share with 'view, edit, and upload'?
