### ISSUE TITLE
Terminology confusing

### ISSUE THREAD

**Issue by Cloudmaister** [MicrosoftDocs/OfficeDocs-SharePoint#1193]
Based on this article and others, it sounds like the lists, files and content is actually MOVED which would be disastrous from a testing and change management perspective. Even the tool itself uses this language which caused me not to press go.  Is the data actually COPIED or is it MOVED?  Which one? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Cloudmaister:

Thank you for pointing this out -- I agree that it is not clear.  I just updated the article (and will look at other topics that also use this phrase) to make it clear.  The content is COPIED.  It is not deleted from the source.  

Thanks for the feedback!

Joanne

**Comment by Cloudmaister** [comment]
You guys rock!

Please excuse any typos. Sent from my iPhone

On Jul 23, 2019, at 6:22 PM, JoanneHendrickson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Cloudmaister:

Thank you for pointing this out -- I agree that it is not clear. I just updated the article (and will look at other topics that also use this phrase) to make it clear. The content is COPIED. It is not deleted from the source.

Thanks for the feedback!

Joanne
