### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#1196]
The UserProfile service and My Sites are in the left side navigation but not in the above table, please add them to ensure completeness. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e5b873-c1d5-08c7-d5cf-f9a8f820d4d1
* Version Independent ID: 010d3581-aa4a-71d6-32f9-9a6fd405d354
* Content: [Configure SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/install/configure)
* Content Source: [SharePoint/SharePointServer/install/configure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/configure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
