### ISSUE TITLE
Location based control vs. conditional access policy?

### ISSUE THREAD

**Issue by mikewaretena** [MicrosoftDocs/OfficeDocs-SharePoint#1198]
How does this complement (or not) location based conditional access policies? Should it be set here as well or having CAS policies (with location based criteria) in place is enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Control access to SharePoint Online and OneDrive data based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mikewaretena Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by ucphger** [comment]
Hi there, We are trying to use this feature but it will not take the IP's. 192.168.100.0/24 and external IP as well
Any idea?

**Comment by j0rt3g4** [comment]
Hello @ucphger  I think the best bet is to contact support so they can help you with your query and specifics.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
