### ISSUE TITLE
.msg?

### ISSUE THREAD

**Issue by mrsbeata** [MicrosoftDocs/OfficeDocs-SharePoint#1201]
Outlook email format is .msg. When that is moved to OneDrive or SharePoint can it be searched? And what attributes are searchable? It would make sense that you could set up a search page in an archive for e-mail format. Such as sender, reciever, dates, contents of email and enclosed documents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca49f43-3737-be54-f95f-0e510c892143
* Version Independent ID: 0d3fb4e8-008a-a864-5702-20dc966f3856
* Content: [Default crawled file name extensions and parsed file types in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types#feedback)
* Content Source: [SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@mrsbeata Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@mrsbeata thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by mrsbeata** [comment]
I believed that I asked a question, not reporter an error. 

Is it possible? The documentation doesn’t specify.

**Comment by mrsbeata** [comment]
Hello? It's not a ticket issue, it's a documentation issue.
