### ISSUE TITLE
Incorrect Download Link

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#1202]
The download link for language packs is for 2016. Since this page applies to 2019 as well, another link should be added: https://www.microsoft.com/en-us/download/details.aspx?id=57463

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44037d12-85d4-e21e-d78a-440de38c48bd
* Version Independent ID: 830be840-8a90-192f-3b7f-0da8964edb5c
* Content: [Install or uninstall language packs for SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/install-or-uninstall-language-packs-0)
* Content Source: [SharePoint/SharePointServer/install/install-or-uninstall-language-packs-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-or-uninstall-language-packs-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@ scanum Cannot edit.
