### ISSUE TITLE
Update this page to match latest tool support updates

### ISSUE THREAD

**Issue by GamalMohamed** [MicrosoftDocs/OfficeDocs-SharePoint#1204]
This page is outdated, some lists that are stated here as not supported are being supported now by the public preview or the current release. So, please update this page as this is maybe misleading for viewers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390c33f7-7e70-6741-2a61-9538b87bec0a
* Version Independent ID: c3be3fb4-c28b-5513-651a-fe8b174a0a33
* Content: [SharePoint Migration Tool supported SharePoint List templates](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates#feedback)
* Content Source: [migration/sharepoint-migration-supported-list-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-migration-supported-list-templates.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@GamalMohamed Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum Cannot edit.

**Comment by GamalMohamed** [comment]
Any updates guys?

**Comment by nenonix** [comment]
@scanum have you assigned this issue? @GamalMohamed if you have the info you can edit the page yourself, or paste it here and I can add for you.

**Comment by scanum** [comment]
@nenonix Hi Nicole! @sowjanya365 is working on this issue. Thanks!

**Comment by sowjanya365** [comment]
Hi @GamalMohamed 

Thanks for reaching out! 

Kindly help us with the information. What are all the templates are note supported by SMTP now?

Thank you!

**Comment by scanum** [comment]
@GamalMohamed We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
