### ISSUE TITLE
OTP to External Azure Active Directory - Conversion

### ISSUE THREAD

**Issue by heymybru** [MicrosoftDocs/OfficeDocs-SharePoint#1205]
Has anyone managed to test what happens when a guest account of "Source" type OTP eventually becomes an Organisational account. 

Does the source change to "External Azure Active Directory"?
Does the invite remain valid?
Does the user authenticate via their credentials or continue being issues with an OTP?

Thank you

**Comment by scanum** [comment]
@heymybru thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
