### ISSUE TITLE
Access Services

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#1208]
Missing details on how to upgrade / migrate Access Services (2013 & 2010)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97493854-efe6-3451-d96b-a04b6ac32075
* Version Independent ID: 46b84a4a-fbe2-5afc-f442-13d8411e395e
* Content: [Upgrade service applications to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @danmyhre This article Applies to Sharepoint 2016 and 2019.
Basically at the start says that it is not applicable to Sharepoint 2013, and 2010 is not even on the map.
![image](https://user-images.githubusercontent.com/5489996/66102306-85319980-e577-11e9-831a-9fcaee57cb7b.png)

**Comment by danmyhre** [comment]
Right, but Access Services 2013 and 2010 (i am talking about the service applications, not the version of SharePoint Server itself) all need to be upgraded

**Comment by j0rt3g4** [comment]
Please, @danmyhre  Suggest the changes. I honestly do not know what you want us to add.
Kindly suggest the changes so we can move forward on this.

**Comment by danmyhre** [comment]
I would recommend raising this to the PG.  I am not sure on what their plan is for upgrading these service applications.

**Comment by scanum** [comment]
@j0rt3g4

**Comment by j0rt3g4** [comment]
@scanum  Hello!, I'm waiting for the recommendations from @danmyhre .

**Comment by danmyhre** [comment]
See comment from October - this needs to be raised with the product group

**Comment by j0rt3g4** [comment]
@scanum  there you go the answer from @danmyhre

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by danmyhre** [comment]
I am not seeing anything on this page for Access Services yet.  #reopen
