### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-SharePoint#1216]
The link for "Branding SharePoint: The New Normal" is not going to anything helpful. Bob has changed his site; here's the correct deep link - https://bob1german.com/2018/09/04/branding-sharepoint-the-new-normal/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe029ff2-3230-3320-aef5-9f16ab9464cc
* Version Independent ID: d791f3f6-257f-9a9b-461f-a12693d4bfde
* Content: [Branding your SharePoint Online site](https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience)
* Content Source: [SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @spowriter
* Microsoft Alias: **clake**

**Comment by spowriter** [comment]
+ @Steve Hord<mailto:stevhord@microsoft.com>

Claudia Lake
Senior Content PM | Knowledge Management
CSS Digital & Data SBU
• email: clake@microsoft.com<mailto:clake@microsoft.com> - • phone: x56097

**Comment by scanum** [comment]
@Michael-Sampson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@Michael-Sampson @claudialake It seems that the link is fixed now, it must've been interim. Please confirm. Thanks

**Comment by claudialake** [comment]
Yes, it's fixed now. Steve Hurd updated the link late last week. Thanks, Steve!



Claudia Lake

Senior Content PM | Knowledge Management

CSS Digital & Data SBU

email: clake@microsoft.com<mailto:clake@microsoft.com> -phone: x56097

________________________________

**Comment by scanum** [comment]
@Michael-Sampson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
