### ISSUE TITLE
OneDriveSetup.exe /allusers not working

### ISSUE THREAD

**Issue by petegriggs** [MicrosoftDocs/OfficeDocs-SharePoint#1218]
OneDriveSetup.exe /allusers is not installing during a task sequence for a new build as it would appear the default Windows per user client installer is running in the background. Once this installs the /allusers option works.

Any ideas please?

**Comment by scanum** [comment]
@petegriggs thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
