### ISSUE TITLE
Formatting errors in PowerShell section

### ISSUE THREAD

**Issue by egor-yudkin** [MicrosoftDocs/OfficeDocs-SharePoint#1219]
Formatting of PowerShell section is messed up with some lines formatted as a code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fea9c4-b648-cf4d-e44a-178c755c3b30
* Version Independent ID: 2b3d3b44-aec8-d16f-be8b-fa450cfeecca
* Content: [Attach or detach content databases in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/attach-or-detach-content-databases#feedback)
* Content Source: [SharePoint/SharePointServer/administration/attach-or-detach-content-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/attach-or-detach-content-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@egor-yudkin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum
