### ISSUE TITLE
Ensure the Max degree of parallelism is set to 1

### ISSUE THREAD

**Issue by dmce** [MicrosoftDocs/OfficeDocs-SharePoint#122]
The link to the Microsoft article doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca9caedd-719e-e80b-8052-c8b3a262d7ee
* Version Independent ID: 0c363923-2851-0f8c-0e59-654f20588479
* Content: [Install SharePoint Server 2016 on one server](https://docs.microsoft.com/en-us/sharepoint/install/install-sharepoint-server-2016-on-one-server#feedback)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@dmce  - This is fixed with PR from @tseward . Thanks all! Much appreciated!
