### ISSUE TITLE
List of OOTB MPs is not accurate for 2016+

### ISSUE THREAD

**Issue by toskr** [MicrosoftDocs/OfficeDocs-SharePoint#1221]
This list seems to contain only the OOTB managed properties in 2013.
It's missing props like CreatedById and SPWebURL introduced in 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5306fd4c-ca0f-9457-580a-88ab1928a0bd
* Version Independent ID: f44f5fcf-0d49-ed1a-73aa-66a13b03030b
* Content: [Overview of crawled and managed properties in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/crawled-and-managed-properties-overview#feedback)
* Content Source: [SharePoint/SharePointServer/technical-reference/crawled-and-managed-properties-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/crawled-and-managed-properties-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@toskr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by tseward** [comment]
@scanum please assign to me.

**Comment by scanum** [comment]
@toskr

**Comment by toskr** [comment]
I can see the page has been thoroughly updated to contain not only the properties in SP2013, as well as new ones introduced in 2016 and 2019.
I love it. Thank you so much! 

The list is important when migrating the Search Service Application to a newer SharePoint version. The Restore-SPEnterpriseSearchServiceApplication command might fail with a duplicate key exception, if a customer manually created a property with a name matching one of the new 2016/2019 MPs before upgrading.

The https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016 article already contains a note about it referring to the SPWebURL property, but I will ask for that to be amended to refer to this full list of MPs added in 2016 and 2019.

**Comment by tseward** [comment]
@toskr you're welcome.

Are you just looking for a note that says "and for a full list of MPs, go here"?

**Comment by toskr** [comment]
@tseward more or less. I would like the note to say:

If there's a manually created Managed Property in the Schema in the existing Search Service Application in SharePoint 2013, which name matches one of the new properties introduced in SharePoint 2016 (for example SPWebURL), the upgrade of the Search Service Application might fail with a duplicate key exception.
That Managed Property might need to be renamed or removed in SharePoint 2013 before the upgrade.
For complete list of Managed Properties introduced in SharePoint 2016 please refer to:
https://docs.microsoft.com/en-us/sharepoint/technical-reference/crawled-and-managed-properties-overview

**Comment by tseward** [comment]
Sounds like a plan. Will do.
