### ISSUE TITLE
Error about quota template not being applied automatically

### ISSUE THREAD

**Issue by cloudgreen** [MicrosoftDocs/OfficeDocs-SharePoint#1224]
I believe there is an error in the text under the heading [Change the settings of a quota template](https://docs.microsoft.com/en-us/sharepoint/sites/create-edit-and-delete-quota-templates#change-the-settings-of-a-quota-template).

It currently says:

> A modified quota template is **not automatically applied** to any existing site collections that use the quota template. A member of the Farm Administrators group must manually apply all modified values to all existing sites that use the quota template.

...but I have made tests and found that that is not true. If you change the settings of a quota template, say, the site storage limit, any sites using that quota template will inherit the new setting. (At least the new setting is reflected in "Configure quotas and locks"...)

My finding above is also corroborated further down [on the same page](https://docs.microsoft.com/en-us/sharepoint/sites/create-edit-and-delete-quota-templates#change-the-quota-template-for-a-site-collection):

> If a site collection is close to exceeding its storage limits and you want to increase its size, you can change the quota template that is applied to the site collection so the quota template has higher limits. **This automatically updates** the warning and storage limits for the site collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0294b786-e1f8-cfc3-3f45-a23741eb3540
* Version Independent ID: 272ff99b-b805-6ddd-ea1e-a69b46820fee
* Content: [Create, edit, and delete quota templates in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/create-edit-and-delete-quota-templates)
* Content Source: [SharePoint/SharePointServer/sites/create-edit-and-delete-quota-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/create-edit-and-delete-quota-templates.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@cloudgreen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dplotnikov** [comment]
@cloudgreen I've made a test on my end and this is what I found - the article is accurate and it works in the same way on my end as well. The 2nd part you highlighted is confusing, no doubts here and further, it explains how to set the new quota template. 

Does it make any sense now?

**Comment by dplotnikov** [comment]
@cloudgreen I would consider closing this issue if you are okay with it

**Comment by scanum** [comment]
@cloudgreen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by cloudgreen** [comment]
@dplotnikov Thanks for your input and sorry for my late reply!

If I didn't misunderstand something, the problem with the documentation is that the article says two conflicting things:

first (**#1**) that _"A modified quota template is not automatically applied"_ and then (**#2**) _"you can change the quota template // This automatically updates the warning and storage limits"_.

I would say that #1 is wrong. A modified quota template **is** automatically applied to site collections, as far as my tests go. Can you corroborate?

Thanks!

**Comment by dplotnikov** [comment]
@cloudgreen no, the 2nd statement says about Changing the quote template from the current to a new one, so this that statement is okay

**Comment by cloudgreen** [comment]
@dplotnikov Ah, I see. I think I interpreted the statement differently... :) The following wording would have been clearer:

_"you can change the quota template that is applied to the site collection **to a another** quota template **with** higher limits._

But about the 1st statement: I made a test and found that if you change the settings of a quota template, then a site collection using that quota template actually inherited the new quota setting. At least the new setting was reflected in "Configure quotas and locks". But the article says this is not the case?! 

Can you confirm this or was I maybe hallucinating? :)

**Comment by dplotnikov** [comment]
@cloudgreen agreed I've created a PR for the change. As for the 2nd one, my tests are showing that the article is okay and I've also made a research about this and no one was saying the opposite.

**Comment by cloudgreen** [comment]
Okay, weird but I won't argue, I must've been hallucinating. :)

Thanks for your attention.
