### ISSUE TITLE
Separate Azure B2B whitelist from SPO/ODfB Whitelist

### ISSUE THREAD

**Issue by Joachim83** [MicrosoftDocs/OfficeDocs-SharePoint#1229]
We are using the whitelist in Azure B2B to allow only certain partners becoming guest users in our tenant and collaborate in Teams etc. However in SPO/ODfB we have no whitelist as we want our users to be able to share documents with any external users instead of sending attachments in email.
This new Azure B2B integration seem to enforce the whitelist from Azure B2B to SPO/ODfB, and I am afraid that once the preview ends and we are forced over to the new experience, the document sharing experience will be severly limited by the whitelist from Azure B2B. 

How can we prevent document sharing in SPO/ODfB from syncing the Azure B2B whitelist in the new sharing experience and let it remain unrestricted?

**Comment by scanum** [comment]
@officedocs assign @scanum

**Comment by MikePlumleyMSFT** [comment]
@MSFTRafLop is following up on this through other channels.
