### ISSUE TITLE
 SharePoint Migration Tool Public Preview Version 3.2.113.4

### ISSUE THREAD

**Issue by danlebaron** [MicrosoftDocs/OfficeDocs-SharePoint#1230]
When prompted to sign into the current sharepoint site i am continually prompted to re-enter your user ID or password.  I am entering correct credentials. This is for a Sharepoint 2010 site.  Any ideas?

**Comment by scanum** [comment]
@danlebaron thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
