### ISSUE TITLE
How about the permission needed for Application Pool?

### ISSUE THREAD

**Issue by xuguang-sp** [MicrosoftDocs/OfficeDocs-SharePoint#1232]
This article only addresses the permission about farm configuration database. Application pool is domain account and they need permission to content database. When a site collection is provisioned from CA, the permission is given automatically by SharePoint.  More details need to be provided about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48860fcc-2469-2699-5786-6200155513e9
* Version Independent ID: aac6aea8-b777-4abd-506d-58ca896ab2ae
* Content: [Deploy Azure SQL Managed Instance with SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019#feedback)
* Content Source: [SharePoint/SharePointServer/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@xuguang-sp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
I personally haven't done Application Pool permissions to any Sharepoint On-premises manually. To clarify I'd ask @scanum  if she can ask the author of the article to check if this needs to be added and which ones should be. Thank you

**Comment by scanum** [comment]
@bentoncity Hi! Could you please aid us in the next steps? Thanks!

**Comment by scanum** [comment]
@bentoncity Hi! Could you please aid us in the next steps? Thanks!

**Comment by scanum** [comment]
@bentoncity Hi! Could you please aid us in the next steps? Thanks!

**Comment by scanum** [comment]
@bentoncity Hi! Could you please aid us in the next steps? Thanks!

**Comment by scanum** [comment]
@bentoncity Hi! Could you please aid us in the next steps? Thanks!

**Comment by acewmu** [comment]
Hi, I was able to provision a Web Application using Powershell. (it failed via Central Admin site)

Using SQL account:
$DBCredential = Get-Credential -Message "Provide the user name and password for the Azure SQL Managed Instance database login." 

Then:
New-SPWebApplication -Name "**sitename**" -Port 80 -HostHeader sitename -URL "**http://sitename**" -ApplicationPool "**sitename**" -ApplicationPoolAccount (Get-SPManagedAccount "**DOMAIN\account**") -DatabaseCredentials $DBCredential -DatabaseName WSS_Content -DatabaseServer **SQLINSTANCE**

**Comment by scanum** [comment]
@xuguang-sp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
