### ISSUE TITLE
Phase 2: The platform image 'MicrosoftSQLServer:SQL2014SP1-WS2012R2:Standard:latest' is not available

### ISSUE THREAD

**Issue by ninijay** [MicrosoftDocs/OfficeDocs-SharePoint#1233]
If I run your code sample, I get this exception...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure#feedback)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by scanum** [comment]
@ninijay thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
