### ISSUE TITLE
Office Server requiments

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#1234]
where are the requirements for Office Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fbcb0b-9e6d-d2e7-5194-5593d35fff63
* Version Independent ID: f6d30df6-858b-4d3c-542f-a4d6b45ec3d8
* Content: [Hardware and software requirements for SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by TroyStarr** [comment]
Hi Dean, can you clarify which product you mean by "Office Server?"  Do you mean Office Online Server (OOS)?  If so, you can find those system requirements here:

[Plan Office Online Server](https://docs.microsoft.com/officeonlineserver/plan-office-online-server)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by DeanGross** [comment]
Yes, I meant the Office Online Server.  It would be helpful if this page included a link to the requirements for that product like it does for all of the other related products.

**Comment by dplotnikov** [comment]
@DeanGross that's because SharePoint has nothing to do with Office Online Server since Office Online Server depends on SharePoint and not vice versa. Does it make sense now?

**Comment by dplotnikov** [comment]
@DeanGross I would suggest closing this issue then

**Comment by scanum** [comment]
@DeanGross We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
