### ISSUE TITLE
Configure team site libraries to sync automatically

### ISSUE THREAD

**Issue by filipkcz** [MicrosoftDocs/OfficeDocs-SharePoint#1236]
Im set Library ID in GPO. Onedrive Create folder "Company name" with subfolder team_1 . After that Im set another Library ID (different team) in same GPO (add new line) but Onedrive on client create second folder "Copany name (1)" with subfolder Team_2. So I have two Copany name folders Copany name, Company name (1)  in file explorer  Where is the issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@filipkcz thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
