### ISSUE TITLE
Add consideration for proxy settings used for cloud hybrid search 

### ISSUE THREAD

**Issue by franzmiltner** [MicrosoftDocs/OfficeDocs-SharePoint#125]
We ran into the fact that if you setup hybrid search behind a proxy, you have to consider an additional proxy setting in the machine.config of .Net (for the servers hosting QPC if you try federated hybrid search for example) and followed https://sharepointrelated.com/2015/12/11/cloud-hybrid-search-proxy-settings/ 
This is confirmed by MS Premier to be the expected behaviour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37896b90-73e5-7657-6081-c32337f7b0dc
* Version Independent ID: 47ed5412-4f06-26b8-bd29-6d284806e62b
* Content: [Configure proxy server settings for Search in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/configure-proxy-server-settings-for-search#feedback)
* Content Source: [SharePoint/SharePointServer/search/configure-proxy-server-settings-for-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/configure-proxy-server-settings-for-search.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by franzmiltner** [comment]
Thanks and np! While doing SharePoint topics I actually like the way with docs (even though it has it's theething troubles here and there still) suggestion of documentation improvemenst are much easier then with the old msdn/technet platforms

**Comment by AndreaBarr** [comment]
@tseward Is investigation this issue.

**Comment by tseward** [comment]
@franzmiltner I chose to put this in the hybrid configuration article as this specifically relates to that scenario.

**Comment by tseward** [comment]
@scanum please close.
