### ISSUE TITLE
Document Library Bug

### ISSUE THREAD

**Issue by dudax97** [MicrosoftDocs/OfficeDocs-SharePoint#1254]
On my Tenant I have a site collection with a document library and inside it I have folders.
I am developing a script to remove automatically folders from document libraries and when I am doing my tests I get a bug in folders.
If I'm inside a folder and I delete it using Powershell, in my case I'm using PNP (Remove-PnPFolder) commands, my page changes to a photo like this one.
![Capture](https://user-images.githubusercontent.com/37797875/62936725-7c67e700-bdc2-11e9-8f1a-f9260659e32e.PNG)
The problem is that the image changes constantly, simultaneously with others and never stops. It is an infinitive loop.

To test this create a document library in Sharepoint Online and inside it create a folder. Then go into the folder. Now using powershell, run the following command "Remove-PnPFolder" and delete your folder. If you look to the browser again you are still inside the folder, but you got an image error always popping.

**Comment by scanum** [comment]
@dudax97 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
