### ISSUE TITLE
msg files in SharePoint

### ISSUE THREAD

**Issue by mrsbeata** [MicrosoftDocs/OfficeDocs-SharePoint#1256]
Ok, my last issue got closed after not understanding the issue. Please moderators, read, understand and act. #1201 

I want to know if I can use the properties of the msg files for search and index. It doesn't specify in the documentation. I'm not some wildling who madly go about testing Everything I see, I want to know if it's possible, check the documentation and ask a question. 

With the new search experience Everything of old seem to be out when it comes to refiners and such.

**Comment by scanum** [comment]
@mrsbeata  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@mrsbeata thank you for reaching out and helping improve MS Docs. Please have a look at these articles and let me know if they help with any of your questions - https://docs.microsoft.com/office365/securitycompliance/partially-indexed-items-in-content-search and https://social.technet.microsoft.com/Forums/76dac179-ec7e-4d16-b84f-2ca7025ed9f5/sharepoint-search-not-retrieving-content-of-msg-files?forum=SP2016.  I see this doc might have been updated  so please confirm if this has been clarified in the interim.

**Comment by scanum** [comment]
@mrsbeata We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
