### ISSUE TITLE
Unable to install SharePoint Migration Tool Public Preview (Version 3.2.113.4)

### ISSUE THREAD

**Issue by ksgsharma** [MicrosoftDocs/OfficeDocs-SharePoint#1258]
Hi Im able to download the exe but when trying to install getting below error.

![image](https://user-images.githubusercontent.com/16601463/63035028-032ec980-be80-11e9-933c-595c140e831c.png)

Im an Admin on this system

System Configuration
----------------------
![image](https://user-images.githubusercontent.com/16601463/63035216-5e60bc00-be80-11e9-8d24-557e8ff6f47f.png)

**Comment by scanum** [comment]
@ksgsharma thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
