### ISSUE TITLE
Link is for the wrong product.

### ISSUE THREAD

**Issue by milazzom** [MicrosoftDocs/OfficeDocs-SharePoint#126]
The capacity management and sizing overview for SharePoint Server 2013 link goes to a page for SharePoint 2010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d3ce71-fc9f-dc3f-799d-dd34ee05fc40
* Version Independent ID: 8d7e952c-86c8-34c9-a230-4d1b954ff4f6
* Content: [Capacity management and sizing for SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/capacity-management-and-sizing-for-sharepoint-server-2013)
* Content Source: [SharePoint/SharePointServer/administration/capacity-management-and-sizing-for-sharepoint-server-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/capacity-management-and-sizing-for-sharepoint-server-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@milazzom - looks like this is fixed now from Pull Request of @asgr86 .   Thanks for making the docs better all! Appreciated!
