### ISSUE TITLE
Unable to run Set-SPOTenant -EnableAzureADB2BIntegration $true command

### ISSUE THREAD

**Issue by callmann** [MicrosoftDocs/OfficeDocs-SharePoint#1260]
I'm trying to opt-in to the preview but I'm unable to execute the "Set-SPOTenant -EnableAzureADB2BIntegration $true", and receive the "A parameter cannot be found that matches parameter name 'EnableAzureADB2BIntegration'." error.

I enabled the OTP preview setting in the Azure AD portal and was also able to successfully execute the -SyncAadB2BManagementPolicy command.

I noticed the comments in some of the closed issue indicated that the preview was still rolling out to tenants, but it's been over a month, so I'm wondering if there is something else I'm missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@callmann do you have the required version of the SPO PowerShell module? Minimum version 8924.1200.

**Comment by callmann** [comment]
Yes, but it seems that an older version was also still installed. I removed everything and started from scratch and I was able to get it to work. Thanks for your help!
