### ISSUE TITLE
Please prioritize adding SPMT to the PowerShell Gallery

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/OfficeDocs-SharePoint#1262]
Considering the issues seen in this issue https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/120, and the PowerShell team's guidance for both the Community and Microsoft itself, please prioritize adding this module to the PowerShell Gallery. 

Over one year ago on August 1, 2018, it was [stated](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/120#issuecomment-409520121) that adding it to the gallery was backlogged.

I searched https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool and did not find matches for Gallery or Install-Module.

I also searched for it on the PowerShell Gallery and could not find it there.

![image](https://user-images.githubusercontent.com/8278033/63083394-e7dbc100-bf48-11e9-8853-141fcbc3ffb1.png)

**Comment by tseward** [comment]
Given this is a ClickOnce application and the module is shipped as part of it (versus the ClickOnce laying down just a module), this is probably unlikely to happen.

**Comment by potatoqualitee** [comment]
The required DLLs can also be packaged within the PowerShell module so that no additional applications are necessary.

**Comment by tseward** [comment]
I don't see the PG making 2 packages for this. ClickOnce can be "force" updated, unlike PoSh gallery solutions.

Since this repo is for documentation bugs rather than feature requests on products, I'd suggest you post at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365 which the PG watches for feature requests.

**Comment by potatoqualitee** [comment]
ahh thanks, it is the wrong place
