### ISSUE TITLE
Overlapping IP addresses

### ISSUE THREAD

**Issue by cyest** [MicrosoftDocs/OfficeDocs-SharePoint#1264]
Please update the article with error messages when an overlapping IP addresses is added. The error message that comes up is "Something went wrong" with correlation ID. Upon checking our logs it points to "The input IP allow list has overlaps". The issue was resolved on the backend. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4264cd-3476-61ae-49dc-c5fa6118722a
* Version Independent ID: 8c419a14-db06-3b0d-66d3-ab396924721e
* Content: [Control access based on network location or app](https://docs.microsoft.com/en-us/onedrive/control-access-based-on-network-location-or-app#feedback)
* Content Source: [OneDrive/control-access-based-on-network-location-or-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-based-on-network-location-or-app.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@cyest Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@cyest are you suggesting adding a note to the article?

**Comment by cyest** [comment]
@lindspea yes, ideally adding sample error message when an overlapping ip address is added or other error for other scenarios that is related to ip addresses.

**Comment by scanum** [comment]
@lindspea

**Comment by lindspea** [comment]
@scanum thanks Manuela. Waiting on e-mail from @kaarins - "...checking whether the cryptic message was a bug or whether better messages are in the works (or even feasible)"

**Comment by omegagx** [comment]
@kaarins @cyest @scanum @lindspea Are there any updates on this? When I have an overlapping IP range, I lose all access to our OneDrive and SharePoint Online with the cryptic error message an no way to get back in. Support took over a week to diagnose and fix the issue because the error didn't properly illustrate what was happening.

**Comment by lindspea** [comment]
@kaarins

**Comment by omegagx** [comment]
any updates on this? It's been a few months now with no status.

**Comment by lindspea** [comment]
@kaarins have you got an update for this issue yet? "...checking whether the cryptic message was a bug or whether better messages are in the works (or even feasible)"

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by kaarins** [comment]
I missed that this is the control in the OneDrive admin center. I'm now directing customers to use the new SharePoint admin center for this setting. If you enter overlapping IP addresses there, you'll get an error when you click Save. I also added the note about "The input IP allow list has overlaps" to that article (https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location) and have submitted a feature request for more specific errors in the experience.
