### ISSUE TITLE
B2B Sync for iOS

### ISSUE THREAD

**Issue by bovie2k** [MicrosoftDocs/OfficeDocs-SharePoint#1265]
Any ETA of when B2B Sync for the iOS app is coming? Its working well on the Windows and Mac OS Client.

**Comment by scanum** [comment]
@bovie2k thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
