### ISSUE TITLE
OneDrive - Disable desktop backup

### ISSUE THREAD

**Issue by AlexJohnH** [MicrosoftDocs/OfficeDocs-SharePoint#1267]
We're implementing the move known folders [GPO](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders) via OneDrive.

Is there a way to disable the desktop back up in OneDrive? Doesn't appear to be working as well as the Pictures and Documents.

**Comment by scanum** [comment]
@AlexJohnH thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
