### ISSUE TITLE
Show or Hide App Tiles Screenshot needs updating

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/OfficeDocs-SharePoint#1268]
The Screenshot in step 5 shows OneDrive for Business and Sites as the 2 options. In an E5 and E3 tenant on the classic settings page (/_layouts/15/online/TenantSettings.aspx) this is now showing OneDrive and Office Online and SharePoint. 

The major distinction here is that when hiding OneDrive - Word, PPT, Excel, and OneNote will also be hidden here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96de5069-51dc-3934-ec44-cae3ab121476
* Version Independent ID: 21955afd-18c1-20f0-061f-f552f71fbfc1
* Content: [Hide the OneDrive and SharePoint app tiles](https://docs.microsoft.com/en-us/sharepoint/hide-app-tiles-on-app-launcher#feedback)
* Content Source: [SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@Mlavieri , yes, thank you! We recently updated the UI and need to update the screenshot accordingly.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by theGnic** [comment]
This doesn't seem to have any effect on our client's Office 365 Portal. Both the OneDrive & SharePoint tiles are selected to show on the portal but neither does. I've hidden then and then showed them again, still not there.......

**Comment by j0rt3g4** [comment]
Updated Image on PR #1408

**Comment by scanum** [comment]
@Mlavieri Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
