### ISSUE TITLE
Sync SP Document library content with Gmail.com domain external users

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/OfficeDocs-SharePoint#1269]
Hello Team, 

Can you please let me know if we can sync the SP Document library content with Gmail.com domain external users.

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync#feedback)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
This functionality requires the guest user have an Azure AD tenant in place, so no it will not work with services like Gmail. This is outlined under the B2B Sync requirements:

> Sharing recipients must have an Office 365 work or school account (in Azure AD).

**Comment by scanum** [comment]
@bhanuchintha Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
