### ISSUE TITLE
OS Desciption wrong

### ISSUE THREAD

**Issue by joachimloe** [MicrosoftDocs/OfficeDocs-SharePoint#1272]
"Windows Server 2016 R2 or Windows Server 2012 R2 (both support VHDX)"

There is no Windows Server 2016 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc677c5-4514-fb8b-a864-4edd711d6f44
* Version Independent ID: 1e3dbf59-48d4-2696-ad8a-7f9cb60871ec
* Content: [Use the sync client on virtual desktops](https://docs.microsoft.com/en-us/onedrive/sync-vdi-support#feedback)
* Content Source: [OneDrive/sync-vdi-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-vdi-support.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by lindspea** [comment]
@joachimloe Thank you for reaching out and helping improve MS Docs. Are you suggesting removing the information from the article? I've done some research and from what I can see, Windows Server 2016 R2 was released on June 2017?

**Comment by joachimloe** [comment]
@lindsdea Not removing the info, updating it. I dont think it exist an official OS with the name "Windows Server 2016 R2". It might be that someone calls it that when a patch is installed, but you will not find an official ISO or technet article that the R2 version of 2016 is released.

You cant download it from here..

https://www.microsoft.com/en-us/evalcenter/search?k=&p=27&a=try&s=&r=16&so=

2012 version of windows was released with R2, 2016 went straight to 2019.

So if the requirement in the article is Server 2016 at a certain patch level, it should be stated, rather then saying R2

Correct me if I'm wrong 😀

/Joachim

**Comment by lindspea** [comment]
@joachimloe Thanks for that. Yes, it appears you are correct, there is no official OS. I'll have the team look into updating the article soonest.

**Comment by kaarins** [comment]
@gacarini, can you please help confirm the Windows Server version numbers? Thanks!

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@joachimloe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
