### ISSUE TITLE
Module path and Getting Started instructions

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/OfficeDocs-SharePoint#1274]
[Related to issues #867 and #120.]

The instructions (and the Sharepoint Migration Tool) assume that the users module folder is always at $env:UserProfile\Documents\WindowsPowerShell\Modules, but this may not be the case if folder redirection is implemented (either redirected manually or through OneDrive's Backup Your Folders feature).  Ideally, the SPMT installer should respect the user's Documents user shell folder location, wherever it is located.

In the meantime, the documentation should at least note that the path in the instructions may differ if it has been redirected, or to use the full path to the module directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets#feedback)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@bryhall Thank you for pointing this out and helping improve MS Docs.  Are you suggesting having a note added to the article?

**Comment by scanum** [comment]
@bryhall We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bryhall** [comment]
@scanum / @lindspea - Apologies, did not see the notifications for replies.  I'm not sure how to re-open this issue without creating a new one.

My recommendation is primarily that the installer respect the user's actual modules path.  However for the documentation, I think it would be helpful for others (especially if they use OneDrive's feature) to be aware of the path mismatch.
