### ISSUE TITLE
Word Automation Services bug above

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#128]
You mentioned in the DB storage table the size for Word Automation Services is 1GB, then say a few lines down it repeats and it says Minimal https://docs.microsoft.com/en-us/sharepoint/administration/storage-and-sql-server-capacity-planning-and-configuration#gather-storage-and-sql-server-space-and-io-requirements

Word Automation Services 
The Word Automation service application has one database. We recommend that you allocate 1 GB for it. It has minimal IOPS. 
PerformancePoint Services 
The PerformancePoint service application has one database. We recommend that you allocate 1 GB for it. It has minimal IOPS. 
Business Data Connectivity service 
The Business Data Connectivity service application has one database. This database is small and significant growth is unlikely. It has minimal IOPS. 
App Management 
The App Management service application has one database. This database is small and significant growth is unlikely. It has minimal IOPS. 
Word Automation Services 
The Word Automation Services service application has one database. This database is small and significant growth is unlikely. It has minimal IOPS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70a2b05-ceef-af7f-78b2-18100771af3c
* Version Independent ID: 2fa1c886-a3cf-4c90-7d36-5257ea4d593a
* Content: [Storage and SQL Server capacity planning and configuration (SharePoint Server)](https://docs.microsoft.com/en-us/sharepoint/administration/storage-and-sql-server-capacity-planning-and-configuration)
* Content Source: [SharePoint/SharePointServer/administration/storage-and-sql-server-capacity-planning-and-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/storage-and-sql-server-capacity-planning-and-configuration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by eschrader** [comment]
I think 1 is supposed to be Word Automation Service and the other Word Conversion Service. Not sure which one is the 1 GB one and which one is the other.

**Comment by bentoncity** [comment]
Thanks @eschrader, I removed two duplicate db entries and set topic to republish.
