### ISSUE TITLE
Typo in HitHighlightedSummary

### ISSUE THREAD

**Issue by armn** [MicrosoftDocs/OfficeDocs-SharePoint#1282]
"HitHighlightedSummary" is twice referred to as "HitHilightedSummary".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fc9e1d-1b7b-846e-61e4-24fb5049b916
* Version Independent ID: 817a10fd-1ec5-4489-762a-5e5db4b58fda
* Content: [Understanding how item display templates and hit highlighting work in the classic search experience in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/understanding-how-item-display-templates-and-hit-highlighting-work#feedback)
* Content Source: [SharePoint/SharePointServer/search/understanding-how-item-display-templates-and-hit-highlighting-work.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/understanding-how-item-display-templates-and-hit-highlighting-work.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@armn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
