### ISSUE TITLE
After configuration, the OneDrive shortcut spawns an additional process

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/OfficeDocs-SharePoint#1283]
When using the per-machine installer, the OneDrive start menu shortcut (which targets the OneDrive exe in the ProgramFiles x86 folder) spawns another OneDrive process and does not open the users onedrive folder, which is the behavior on the per-user installer.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@danjpadgett 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
