### ISSUE TITLE
Future possibility for Synching SP Document library content with Gmail.com domain external users

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/OfficeDocs-SharePoint#1284]
Hello Team,

Is there any possibility in the future to include the feature of "Synching SP Document library content with gmail.com/outlook.com external users"?

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
I would suggest searching for or creating a uservoice entry over at https://onedrive.uservoice.com/forums/913531. That will get the attention of the product group.

This repository is for issues on the documentation themselves rather than for product feature requests.

**Comment by scanum** [comment]
@bhanuchintha Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
