### ISSUE TITLE
Article only mentions SharePoint 2013 and 2016

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-SharePoint#1286]
Does this also apply to SharePoint 2019? Please update the article to show hybrid site following for SharePoint 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769d19ad-d993-4abb-e0e1-ddcc3e88708e
* Version Independent ID: 1f692cb5-68e8-e33b-db7f-21322774c2d3
* Content: [Hybrid site following](https://docs.microsoft.com/en-us/sharepoint/hybrid/hybrid-site-following)
* Content Source: [SharePoint/SharePointServer/hybrid/hybrid-site-following.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hybrid-site-following.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@andikrueger 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
