### ISSUE TITLE
who can grant permissions in sharepoint

### ISSUE THREAD

**Issue by git-ML-hub-CCC** [MicrosoftDocs/OfficeDocs-SharePoint#1287]
Thank you scanum. Any updates?

## Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Product: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@git-ML-hub-CCC Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving PR #1300

**Comment by j0rt3g4** [comment]
@scanum

**Comment by scanum** [comment]
@git-ML-hub-CCC Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by git-ML-hub-CCC** [comment]
All I got is 2 contradictory statements:
1. Only members of **Company Administrator** or **Group Owners** groups may assign permissions to a brand new site. 
2. If you are a member of the SharePoint Site, you will also be able to **invite** or **share** the site with internal/external users. 

Can anyone explain?

**Comment by j0rt3g4** [comment]
I don't think they are contradictory.

If you have a brand new site your Administrator (a global admin) or a group owner can assign permissions. And If you're a member you can "invite or share a site"...

To assign permissions you must be a member of the tenant so you can have access inside the tenant, sharing a site is giving permissions to guests not people inside the same tenant.

That's why they're different.
