### ISSUE TITLE
Important information that isn't mentioned regarding running the PowerShell Script

### ISSUE THREAD

**Issue by haflidif** [MicrosoftDocs/OfficeDocs-SharePoint#1289]
Hi,
I recently found out if you are trying to pre-provision OneDrive for business accounts, it will fail if the user account is blocked for sign-in (Disabled), so I added a Note that states that all effective users or those user/users that need their ODFB pre-provisioned needs to be allowed for sign-in.

Can you please add this to the documentation, I've created a pull request with proposed changes 

Kind Regards
Haflidi Fridthjofsson.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts#feedback)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@haflidif Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving adding not into PR #1301
