### ISSUE TITLE
IIS_WPG vs WSS_WPG

### ISSUE THREAD

**Issue by Keybonesabi** [MicrosoftDocs/OfficeDocs-SharePoint#1291]
IIS_WPG Role is mentioned to include Farm Administrator User Account as a member.
IIS_WPG Role is not mentioned elsewhere in the article.
Did yall mean WSS_WPG Security group or database role?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92c42e5-2016-b7d7-a232-d2a16b098892
* Version Independent ID: 9b03a07a-5056-d33f-fc4f-8a6f3c3e14cc
* Content: [Account permissions and security settings in SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-2013)
* Content Source: [SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Keybonesabi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
