### ISSUE TITLE
Hyperlink points to error Page

### ISSUE THREAD

**Issue by prabhu244** [MicrosoftDocs/OfficeDocs-SharePoint#1293]
Hi, 

The Hyperlink "Office 365 system requirements" under [what you need to get at Delve] Section at Paragraph 3 points to the Error Page.

Thanks,
Prabhu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21ad738-c2a1-ef1f-d745-eebe907311ac
* Version Independent ID: e931c7e1-fdb4-414b-986d-d7755fc797c4
* Content: [Office Delve for Office 365 admins](https://docs.microsoft.com/en-us/sharepoint/delve-for-office-365-admins?redirectSourcePath=%252fen-us%252farticle%252fOffice-Delve-for-Office-365-admins-54f87a42-15a4-44b4-9df0-d36287d9531b#feedback)
* Content Source: [SharePoint/SharePointOnline/delve-for-office-365-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delve-for-office-365-admins.md)
* Service: **sharepoint-online**
* GitHub Login: @gretel
* Microsoft Alias: **gretel**

**Comment by scanum** [comment]
@prabhu244 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@prabhu244 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
