### ISSUE TITLE
New-SPConfigurationDatabase throws error: This Alter database statement is not supported: Azure documents conflict with this document

### ISSUE THREAD

**Issue by savoeva** [MicrosoftDocs/OfficeDocs-SharePoint#1297]
Command here: New-SPConfigurationDatabase -DatabaseServer -DatabaseName -FarmCredentials $FarmCredential -DatabaseCredentials $DBCredential -Passphrase $FarmPassphrase -LocalServerRole

Throws error: This Alter database statement is not supported

When we look at what SharePoint does, it tries to issue:
alter database [configDB Name] set AUTO_CLOSE off

But based off this article:
This type of alter statement is not supported in Azure:
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information

ALTER DATABASE statement
Some file properties can't be set or changed:
• A file path can't be specified in the ALTER DATABASE ADD FILE (FILENAME='path') T-SQL statement. Remove FILENAME from the script because a managed instance automatically places the files.
• A file name can't be changed by using the ALTER DATABASE statement.
The following options are set by default and can't be changed:
• MULTI_USER
• ENABLE_BROKER ON
AUTO_CLOSE OFF

With that said, does SharePoint 2016/2019 work with Azure managed databases?

**Comment by tseward** [comment]
2016/2019 do work with Azure SQL Managed Instances, see https://docs.microsoft.com/en-us/sharepoint/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019.

Pay special note that you must first install a specific PU prior to creating the farm.

**Comment by savoeva** [comment]
Thanks for the confirmation, was testing on SP 2016 Aug 2019 build.  Rolled back to May 2019 and that works fine with Azure managed instances.

**Comment by scanum** [comment]
@savoeva **Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
**
