### ISSUE TITLE
How is the migration done?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1298]
At the beginning of the article, it states, "As an admin, you can also run the tool on behalf of your users."  That's great but the only instructions are to "see SharePoint and OneDrive Migration Tool."  If you follow the link to the Migration Tool, you are treated to a myriad of articles on using the migration tool for SharePoint but nothing for OneDrive, much less how an administrator can migrate user data from file shares to individual OneDrives.  

Could you please post the actual instructions to migrate data to OneDrive or at least link to another article that actually details how this is done with the migration tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8673a55f-50c6-bd98-6b4f-d54db859216d
* Version Independent ID: 571c56c2-0be7-0296-ab36-3a75ff3874a9
* Content: [Migrating Content to OneDrive for Business](https://docs.microsoft.com/en-us/sharepointmigration/migrating-content-to-onedrive-for-business)
* Content Source: [migration/Migrating-content-to-OneDrive-for-Business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Migrating-content-to-OneDrive-for-Business.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Canis-Lupis:

Thanks for your feedback -- And I agree.  I will update the content with specific instructions for OneDrive.

Thanks!

Joanne

**Comment by Canis-Lupis** [comment]
Thanks so much!  We're looking to do a mass migration of users U drives on file servers to their OneDrives in the near future and this would be very helpful--especially if it can be done en masse.  Installing the migration tool on each and every workstation and asking users to do it manually themselves just won't work in our environment.
________________________________

**Comment by JustinCredible-** [comment]
@Canis-Lupis when you run the tool it asks you for the SharePoint Site URL. Go to O365 portal and then OneDrive under the user, get the link, copy/paste into SPMT. Log in using credentials that have access to that folder

**Comment by Canis-Lupis** [comment]
"Go to O365 portal and then OneDrive under the user, get the link..."  are you referring to OneDrive admin center in the portal? If so, that doesn't list any OneDrive URLs.  Do you mean under Active Users? I do see OneDrive settings there such as Quota and Data Retention, but no OneDrive URL.


________________________________

**Comment by benol5en** [comment]
@Canis-Lupis Not in OneDrive admin center, under the active users in main admin center, select  the user and then OneDrive Settings and then "access files". Depending on how usernames are created, they will have similar URLs which just a username change.

**Comment by scanum** [comment]
@Canis-Lupis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Canis-Lupis** [comment]
I tried to figure this out today and could not.  First off, you'll need to make the distinction of which admin center you are referring to.  Under the current admin center, there is no "OneDrive Settings" for a user in Active Users.  

However, under the Preview Admin center, there is a OneDrive tab for a user in Active Users.  Still, when I click on this tab, all I get is "0."  Not sure what that means but no URL was listed.

**Comment by JustinCredible-** [comment]
You go to O365 admin center. Go to users. Click a user. Go to OneDrive tab. There is a place to get the link in there. If you’re just seeing a 0 there you may need to contact Microsoft support

**Comment by Canis-Lupis** [comment]
Hi, Justin, thanks for the feedback.   I can contact MS regarding the 0, but checking other accounts shows a message, "OneDrive‎ isn't set up for this user. Ask the person to go to portal.office.com/onedrive to set it up. It might take a while."  So, even though the account is licensed, does this mean OneDrive isn't created until the user logs into it?  If so, then this makes bulk OneDrive migrations impossible.
________________________________

**Comment by JustinCredible-** [comment]
My apologies. Yes their OneDrive must be provisioned first if I remember right. There is a way to do this in bulk via power shell.

But if I’m wrong, I do know the URL is in the format https://<orgname>-my.sharepoint.com/personal/emailaddress
For The email address convert any dots to underscores. You can just try that and see if it works

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
