### ISSUE TITLE
No, sorry, still greyed out.

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/OfficeDocs-SharePoint#1299]
The settings are set exactly as shown in the screenshot for "In the left pane of the new SharePoint admin center, under Policies, select Sharing". It still says that "your organization is preventing" the use of anyone links.

Eventually discovered (remembered) that you have to hold your tongue the right way while standing on your head, and set the exact some option in two places -- at the site as well. 

I personally think the design is flawed, but since it is what it is, it should be documented correctly. The steps in THIS article to not achieve the goal of external link sharing. You should at least mention the need to activate it by site and link to https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by boomalator** [comment]
Oh, sorry, I did just realize the link is at the top. But the explanation is still lacking, i think.

**Comment by scanum** [comment]
@boomalator  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@boomalator I'm not sure if you've managed to handle your original scenario or not

**Comment by MikePlumleyMSFT** [comment]
@boomalator I added a clarification after the organization-level setting procedure that you also need to set the site-level setting.

**Comment by mattgrimley** [comment]
I'd love to know what you did to make this work. I've tried working through these pages repeatedly and cannot get sharing options to work on folders (though they work fine for files).
Both "Anyone with the link" and "People in xxx with the link" are greyed out at folder level.
I get this on an Office365 group associated Sharepoint as well as one with no Office group.
>Sharing settings in the admin center permit Anyone sharing for Sharepoint.
>Sharing settings on SP site in admin center permit "Anyone" for sharing.
> SharingCapability and SiteDefinedSharingCapability are set to ExternalUserAndGuestSharing via powershell.

Either I'm missing something simple in the docs, the docs are missing something key or this just doesnt work in certain circumstances. Any ideas?

**Comment by MarkJR84** [comment]
I just got mine working, Mike referenced to it above.

I went to Sharepoint admin center and on the left menu go to Sites > Active Sites. Click the tick box next to your site to select it then click Sharing. A settings menu opens on the right.

When it opened the "Anyone" option was already selected. So all I did to get mine working was selected the second option "New and Existing Guests" then clicked save. Then I selected "Anyone" again and then clicked save.

I refreshed my form and the option to share to anyone with the link was no longer greyed out. I have tested it on a different browser signed out of office.com and it works.

Hope this helps.

**Comment by mattgrimley** [comment]
Thanks, I'll check that out on Monday. Sounds like a definite bug in the UI
though.
I restored an old SharePoint which has it working which proves my tenant is
setup okay, so it makes sense that it's an issue at site level.

Thanks again.

**Comment by cortisol** [comment]
We are experiencing the same problem. After turning off and turning on guest access in Active sites at Sharepoint a file sharing became possible. But we still cannot share folders. What we have to do?

**Comment by MikePlumleyMSFT** [comment]
See [Collaborating with people outside your organization](https://docs.microsoft.com/Office365/Enterprise/collaborating-with-people-outside-your-organization) for detailed steps to enable external sharing for different scenarios.

**Comment by cortisol** [comment]
> 
> 
> See [Collaborating with people outside your organization](https://docs.microsoft.com/Office365/Enterprise/collaborating-with-people-outside-your-organization) for detailed steps to enable external sharing for different scenarios.

Thank you, but I have seen this article and set up all the necessary settings, but problem still occurs.

**Comment by JoaoTSS** [comment]
Same here.
Files are OK.
Folders NOK.

**Comment by cortisol** [comment]
Are there any solutions? Files are OK. Folders NOK.

**Comment by MikePlumleyMSFT** [comment]
If you are still experiencing issues, I recommend you [open a support request](https://docs.microsoft.com/office365/admin/contact-support-for-business-products).

**Comment by JoaoTSS** [comment]
Thank you MikePlumleyMSFT.

After my support session I finally solved the problem.

In the "site settings" > "Site collection features" > DEACTIVATE the following option > "Limited-access user permission lockdown mode"

**Comment by scanum** [comment]
@boomalator Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
