### ISSUE TITLE
Windows File Version History support

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-SharePoint#13]
Is Windows File Version History supported? 
By this I'm referring to, the built-in feature in Windows 10. https://msdn.microsoft.com/en-us/library/hh829789(v=vs.85).aspx

And what other types of file versions are accepted for this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041ce12b-b77a-9b46-66ad-4b9fda465122
* Version Independent ID: 20a73f2f-a66f-e5af-8ced-6fa70e2e5e3f
* Content: [Migration Assessment Scan File Versions](https://docs.microsoft.com/en-us/sharepoint/migrate-to-sharepoint-online/migration-assessment-scan-file-versions)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/migration-assessment-scan-file-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/migration-assessment-scan-file-versions.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by haneef95** [comment]
Also, I have some SAMBA shares that support Shadow Copy or VSS, will those versions be migrated in the SPMT aswell?

Thanks,

**Comment by JoanneHendrickson** [comment]
This particular scan article is referring to versions in the source SHAREPOINT environment. 

This assessment scan does not look at file versions in Windows/File Shares.
