### ISSUE TITLE
server farm account

### ISSUE THREAD

**Issue by stusims** [MicrosoftDocs/OfficeDocs-SharePoint#1304]
In the section 'To run the SharePoint Products Configuration Wizard' step 9 you refer to the 'Server Farm Account' where as in the 'Required accounts in SharePoint Server' list of account specified here : https://docs.microsoft.com/en-us/sharepoint/install/initial-deployment-administrative-and-service-accounts-in-sharepoint-server#required-accounts-in-sharepoint-server , there is no such account, from the description of the account it is actually the 'Farm service account' you are referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca9caedd-719e-e80b-8052-c8b3a262d7ee
* Version Independent ID: 0c363923-2851-0f8c-0e59-654f20588479
* Content: [Install SharePoint Servers 2016 or 2019 on one server](https://docs.microsoft.com/en-us/sharepoint/install/install-sharepoint-server-2016-on-one-server)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Thanks, I will update the doc.

**Comment by scanum** [comment]
@stusims Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
