### ISSUE TITLE
Privacy issue with point 4 ?

### ISSUE THREAD

**Issue by Jahz19** [MicrosoftDocs/OfficeDocs-SharePoint#1306]
Regarding point 4 and the manager having access to his former team member onedrive, aren't you afraid of potential privacy issues ? Even when strictly related to work, I guess that some documents such as chat history could be considered as private.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#feedback)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
This will largely depend on your local privacy laws/company privacy policy.

However, this repo is for documentation bugs. I would recommend closing this particular issue :-)

**Comment by Jahz19** [comment]
> This will largely depend on your local privacy laws/company privacy policy.
Yes agree. Maybe a warning should be added to this feature ?

> However, this repo is for documentation bugs. I would recommend closing this particular issue :-)
Well, I didn't intended to report as a bug, I just used the "leave feedback" button on the page, and that's what happened.

**Comment by tseward** [comment]
What you could do is leave feedback on Uservoice - https://sharepoint.uservoice.com/forums/330318-sharepoint-administration.

The feedback button on the docs is specifically for feedback on the documentation itself rather than the product.

Thanks!

**Comment by Jahz19** [comment]
Thanks, so closing it.
