### ISSUE TITLE
Documentation needs more clarity please.

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SharePoint#1308]
Can you please clarify if classic as well as modern sites support public (anonymous) websites on SharePoint 2019 on premise? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77666cf9-941c-592a-62c6-06d6c786237e
* Version Independent ID: f842d829-716c-7665-bd74-024b96764caf
* Content: [Manage anonymous access for a web application in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-anonymous-access-for-a-web-application)
* Content Source: [SharePoint/SharePointServer/administration/manage-anonymous-access-for-a-web-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-anonymous-access-for-a-web-application.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@rachoksh  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@rachoksh yes, both options work. I've added a PR with clarifications

**Comment by tseward** [comment]
@TroyStarr may also be able to provide input, here.

**Comment by scanum** [comment]
@MikePlumleyMSFT @TroyStarr Following up on this issue. Please let me know if there is anything I can do to help.

**Comment by elpecora** [comment]
@MikePlumleyMSFT @TroyStarr @scanum Any updates on this issue? Thank you!

**Comment by scanum** [comment]
@MikePlumleyMSFT @TroyStarr Following up on this issue. Please let me know if there is anything I can do to help.

**Comment by TroyStarr** [comment]
Hi folks, anonymous access is supported with modern sites in SharePoint 2019.  However, the product team is aware of some bugs in this scenario that would result in unexpected authentication prompts.  The team is investigating these issues, but we don't currently have an ETA on when fixes would be available.

If you're running into issues with anonymous access, please open a support case with Microsoft Support so they can ensure the SharePoint product team knows about the specific issue you're encountering.  They can also ensure you're notified of any fixes once they're released.

**Comment by scanum** [comment]
@rachoksh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
