### ISSUE TITLE
Missing diagram

### ISSUE THREAD

**Issue by jarmistead** [MicrosoftDocs/OfficeDocs-SharePoint#1309]
The last sentence on the page says "Yammer users exist in a limited number of states, as shown in the following diagram:"

BUT, there is no "following diagram" !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e905f15-4a16-f03a-47f4-4d1509c465c0
* Version Independent ID: 17aff17a-dd89-27fe-61f8-ec3b45939d2e
* Content: [Yammer networks, groups, and users overview](https://docs.microsoft.com/en-us/sharepoint/administration/yammer-networks-groups-and-users-overview#feedback)
* Content Source: [SharePoint/SharePointServer/administration/yammer-networks-groups-and-users-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/yammer-networks-groups-and-users-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@jarmistead  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT feel free to merge the PR and close this issue

**Comment by scanum** [comment]
@jarmistead Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
