### ISSUE TITLE
Should be able to install SPMT via PowerShell

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/OfficeDocs-SharePoint#1310]
Since it is common for an organization performing mass migrations to have multiple hosts running those migrations (the FastTrack guidance recommends it, in fact), it would be nice to be able to just invoke a webrequest or something like that via PowerShell to download and install the SPMT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
I suppose you could `Invoke-WebRequest https://spmtreleasescus.blob.core.windows.net/build/build.application` but you should add this as a feature request in UserVoice - https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365.

**Comment by scanum** [comment]
@AspenForester Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by AspenForester** [comment]
Since @tseward  was able to provide the answer doesn't that seem to indicate that it does NOT need to be a product feature, but rather, just an update to the documentation?

**Comment by tseward** [comment]
@AspenForester no, this would need to be a product feature and should go on UserVoice.
