### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-SharePoint#1313]
Under the Ad-hoc external recipient column, the entry for Can have friendly name reads "Friendly name is the email address that the file or folder was share with", but it should be "shared with".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-sharing-in-targeted-release)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@douglasac10  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT feel free to merge the PR and close this issue

**Comment by scanum** [comment]
@douglasac10 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!
