### ISSUE TITLE
Does not provide the default external sharing setting when new site is created

### ISSUE THREAD

**Issue by Ravi-WesCEF** [MicrosoftDocs/OfficeDocs-SharePoint#1315]
Can we please have the default external sharing permission when a new site is created by a user using Teams or any other way?

for eg: If Organization level settings are set to Anyone and users create a new site what value is selected by default for external sharing from the options below?
1) Anyone
2) New and existing guests
3) Existing guests only
4) Only people in your organization

Also will the users be able to change from the default setting in the above scenario?
If this information is already provided somewhere then please guide me to that.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3106844b-caae-38c5-3c88-fb17a9d67536
* Version Independent ID: 3e88e60e-24a3-cd83-9bfc-8bc3037a86ce
* Content: [Change the external sharing setting for a site](https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site)
* Content Source: [SharePoint/SharePointOnline/change-external-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-external-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Ravi-WesCEF  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@Ravi-WesCEF this is  covered in the [guest sharing reference](https://docs.microsoft.com/Office365/Enterprise/microsoft-365-guest-settings#sharepoint-site-level). Only SharePoint or Global admins can change the sharing setting.

**Comment by dplotnikov** [comment]
@Ravi-WesCEF let me know if you still have any questions but if not, I'll consider this issue as closed

**Comment by Ravi-WesCEF** [comment]
All good mate, please close the issue.
Thanks
