### ISSUE TITLE
How do I check if a SharePoint online library is sycned?

### ISSUE THREAD

**Issue by rajeshkhanikar** [MicrosoftDocs/OfficeDocs-SharePoint#1316]
We would like to check [using PowerShell] if a particular SharePoint online library is synced (Windows 10 computers). We don't to check the synced folder path in the local drive, because the user may have removed the sync from OneDrive client and the folder may still exists in the disk (without a sync). Please let us know if it is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
In `C:\Users\userName\AppData\Local\Microsoft\OneDrive\settings\Business1` you should see a file with a GUID in it ending in `.ini`. This should have references to all synchronized locations (probably one of the first few lines). You could parse that for each location.

For example, here is one line entry I have:

```
libraryScope = 1 0015324795fb40e09b5f80597e101668+1 5 "hc2" "Documents" 4 "https://tenantName.sharepoint.com/sites/hc2" "2393cc18-6c82-413d-a480-93207fa460a8" 94547721bcb447eaa968855fdfa1116c 51ba4a5f624340f7ad77909eebccd9c0 7a6eee3c67ad425a80b7ec4001897978 1568122259 "C:\Users\userName\tenantName\hc2 - Documents" 1 b07e49cf-fee1-4201-916b-2b3a9ee8c64f  
```
You'll see the source site path, the GUID value starting with `94547721` is the Site ID, `51ba4af5` is the Web Id, and finally `7a6eee3c` is the Document Library Id.

**Comment by scanum** [comment]
@rajeshkhanikar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
