### ISSUE TITLE
Are these keys and types up-to-date?

### ISSUE THREAD

**Issue by thycotic-benny** [MicrosoftDocs/OfficeDocs-SharePoint#1317]
Hello,

I've been looking at centrally managing the OneDrive systems on our Macs and I am having some issues when following these settings on this guide. For starters, using OneDrive 19.152.0801.0007 (Standalone) (OSX 10.14.6) I noticed the key in the plist file "OpenAtLogin" is a integer with value 1 when enabled, but this guide lists it as a boolean.

While attempting to use the keys from this guide, my plist file keeps getting deleted and replaced by a default generated one. Are the values on this page correct and up-to-date with the latest version of OneDrive and OS X?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync client for Mac](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos?redirectSourcePath=%252fen-us%252farticle%252fConfigure-the-new-OneDrive-sync-client-on-macOS-eadddc4e-edc0-4982-9f50-2aef5038c307#feedback)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@thycotic-benny Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@thycotic-benny thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
