### ISSUE TITLE
Modern Web parts

### ISSUE THREAD

**Issue by amt-james** [MicrosoftDocs/OfficeDocs-SharePoint#1318]
Does the migration of all these web parts assume the migration is to Classic experience on SharePoint Online or do some work with Modern experience?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df9fa1f-bca5-5e75-cfb3-d0c525b784de
* Version Independent ID: 6ef36756-5dfc-fb42-eb96-c18972a70768
* Content: [SharePoint Migration Tool supported SharePoint web parts](https://docs.microsoft.com/en-us/sharepointmigration/spmt-supported-webparts#feedback)
* Content Source: [migration/spmt-supported-webparts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-supported-webparts.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
The webparts listed are for classic pages. Pages need to be recreated if you want to go from classic to modern.

**Comment by scanum** [comment]
@amt-james Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
