### ISSUE TITLE
Popularity Trends report

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#1319]
"The Popularity Trends report is an Excel report that shows daily and monthly hits...": are those unique hits or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849aee0b-2a53-7231-6106-e652c03bc378
* Version Independent ID: 9c0aebac-8e48-43a6-afb6-ef08e8f78715
* Content: [View usage reports in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/view-usage-reports#feedback)
* Content Source: [SharePoint/SharePointServer/administration/view-usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/view-usage-reports.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@LuigiBruno Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LuigiBruno** [comment]
> @LuigiBruno Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

Thank you @scanum.

**Comment by j0rt3g4** [comment]
Hello @LuigiBruno They are not "unique hits" they are "hits"

**Comment by LuigiBruno** [comment]
> Hello @LuigiBruno They are not "unique hits" they are "hits"

Thanks @j0rt3g4.

**Comment by scanum** [comment]
@LuigiBruno Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
