### ISSUE TITLE
Steps to rename the Search Service application databases on SharePoint Server 2019

### ISSUE THREAD

**Issue by Roness** [MicrosoftDocs/OfficeDocs-SharePoint#1320]
The method from this documentation are not working for Search Service Application in SharePoint Server 2019. 
Instead you should use this method : 
1. Restore Search Service Application from Search Admin DB
2. Suspend the Search Service
3.Associate the Search Administration Database
4.Associate the Search Analytics Reporting  Database
5.Associate the Search Crawl Store Database
6.Associate the Search Links Store Database
7.Suspend the Search Service
Use this PS Script : 
&lt;########################################################################################################
    This script intend to change the SharePoint 2019 Search Service Application Databases names
    Description : The formal process from older sharepoint versions not applicable for SharePoint 2019,
                  Use this script to rename the databases name
                  This Script assume you allready restore the search administration database
    Author : Ron Ness (Microsoft)
    Date : August,25 2019
#########################################################################################################&gt;

#Add SharePoint *.DLLs if needed
if ((Get-PSSnapin "Microsoft.SharePoint.PowerShell" -ErrorAction SilentlyContinue) -eq $null){
    Add-PSSnapin *SharePoint* 
}

&lt;#===============================================================================================================================
Step 1 Suspend the Search Service : 
    1.On the Start menu, click All Programs. 
    2.Click Microsoft SharePoint Products. 
    3.Click SharePoint Management Shell. 
    4.In the SharePoint Management Shell, enter the following Windows PowerShell statement to suspend the search service: 
=================================================================================================================================#&gt;
$searchServiceApplicationName = "&lt;Search Service Application Name&gt;"
$ssa = Get-SPEnterpriseSearchServiceApplication $searchServiceApplicationName
Suspend-SPEnterpriseSearchServiceApplication -Identity $ssa

&lt;#===============================================================================================================================
Step 2 Associate the Search Administration Database : 
    1.On the Start menu, click All Programs. 
    2.Click Microsoft SharePoint Products. 
    3.Click SharePoint Management Shell. 
    4.In the SharePoint Management Shell, enter the following Windows PowerShell statement to associate the new Search 
      Administration database with the Search Service Application:

* Please note that if you have restored Search Administration DB you can continue to the next step (3)
=================================================================================================================================#&gt;
#$ssa = Get-SPEnterpriseSearchServiceApplication $searchServiceApplicationName
#$ssa | Set-SPEnterpriseSearchServiceApplication -DatabaseName SP_Search -DatabaseServer SQLSP19SRV

&lt;#===============================================================================================================================
Step 3 Associate the Search Analytics Reporting  Database : 
    1.On the Start menu, click All Programs. 
    2.Click Microsoft SharePoint Products. 
    3.Click SharePoint Management Shell. 
    4.In the SharePoint Management Shell, enter the following Windows PowerShell statement to associate the new Analytics Reporting 
      database with the Search Service Application:
=================================================================================================================================#&gt;
Add-SPServerScaleOutDatabase -ServiceApplication $ssa -DatabaseServer SQLSP19SRv -DatabaseName SP_AnalyticsReportingDB #if you get an error that the database allready exist you will need to remove row object from 'SharePoint_Config' DB : Delete From Objects where Name = 'Database Name'; 
$temp = Get-SPServerScaleOutDatabase -ServiceApplication $ssa 
Remove-SPServerScaleOutDatabase -ServiceApplication $ssa -Database $temp[0]

&lt;#===============================================================================================================================
Step 4 Associate the Search Crawl Store Database : 
    1.On the Start menu, click All Programs. 
    2.Click Microsoft SharePoint Products. 
    3.Click SharePoint Management Shell. 
    4.In the SharePoint Management Shell, enter the following Windows PowerShell statement to associate the new Crawl Store 
      Database with the Search Service Application:
=================================================================================================================================#&gt;
New-SPEnterpriseSearchCrawlDatabase -SearchApplication $ssa -DatabaseName SP_CrawlStoreDB -DatabaseServer SQLSP19SRV #Create new Crawl Store Database
$crawlDBToDelete = $ssa | Get-SPEnterpriseSearchCrawlDatabase -Identity "&lt;Old Crawl Store Database&gt;"
Remove-SPEnterpriseSearchCrawlDatabase -Identity $crawlDBToDelete
#Optional for viewing details 
$CrawlDatabase0 = ([array]($ssa | Get-SPEnterpriseSearchCrawlDatabase))[0]
#Please Note : the below command doesn't works on SharePoint 2019
#$CrawlDatabase0 | Set-SPEnterpriseSearchCrawlDatabase -DatabaseName SP_CrawlStoreDB -DatabaseServer SQLSP19SRV

&lt;#===============================================================================================================================
Step 5 Associate the Search Links Store Database : 
    1.On the Start menu, click All Programs. 
    2.Click Microsoft SharePoint Products. 
    3.Click SharePoint Management Shell. 
    4.In the SharePoint Management Shell, enter the following Windows PowerShell statement to associate the new Links Store
      Database with the Search Service Application:
=================================================================================================================================#&gt;
New-SPEnterpriseSearchLinksDatabase -DatabaseName SP_LinksStoreDB –SearchApplication $ssa  -DatabaseServer SQLSP19SRV # Create new Links Store Database

$oldLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[0] # Get Old Links Store Database Identity (Run this command :'$ssa | Get-SPEnterpriseSearchLinksDatabase' to ensure this is the right Database)
$newLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[1] # Get New Links Store Database Identity (Run this command :'$ssa | Get-SPEnterpriseSearchLinksDatabase' to ensure this is the right Database)
Move-SPEnterpriseSearchLinksDatabases -SearchApplication $ssa -TargetStores @($newLinksStoreDB) -Confirm:$false

Resume-SPEnterpriseSearchServiceApplication -Identity $ssa #Resume the Search Service Application, Without resuming the the search service application you won't be able to remove the old Links Store Database

Remove-SPEnterpriseSearchLinksDatabase -Identity $oldLinksStoreDB -SearchApplication $ssa -Confirm:$false
#Please Note : the below command doesn't works on SharePoint 2019
#$LinksDatabase0 | Set-SPEnterpriseSearchLinksDatabase -DatabaseName SP_LinksStoreDB -DatabaseServer SQLSP19SRV -SearchApplication $ssa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0c1428-d756-3353-887a-3e0b33319c68
* Version Independent ID: 64436001-711f-a29f-15ff-02fcff2dae89
* Content: [Move or rename service application databases in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/move-or-rename-service-application-databases#feedback)
* Content Source: [SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@scanum please assign to me.

**Comment by scanum** [comment]
@tseward Hi Trevor! Any updates on this? Thanks!

**Comment by tseward** [comment]
@scanum document modifications are in progress.

**Comment by tseward** [comment]
@Roness I submitted a PR for this. Could you please do a review?

**Comment by Roness** [comment]
@tseward<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftseward&data=02%7C01%7CRon.Ness%40microsoft.com%7C9727ac723755437e0a1108d7455d0f13%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637054138306988653&sdata=Fn5xw1vkI913AJBl%2B34xsXuXs2k6FiROGQ7pkEgglas%3D&reserved=0> Hi Trevor
I reviewed this PR and it look great !

Best Regards,
Ron.

[cid:image001.jpg@01D57A31.4D58A960]

Ron Ness


Premier Field Engineer
Enterprise Services
Microsoft
Office:   +972 74 7119287
Mobile:   +972 54 5259524
roness@microsoft.com<mailto:roness@microsoft.com>

**Comment by scanum** [comment]
@Roness Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by radityoardi** [comment]
One of the commands is not clear enough, end up running some unwanted command which leads to deleting the database name object in the SharePoint_Config database.

> Point the Analytics Reporting database to the new location. At the PowerShell command prompt, type the following commands:
`Add-SPServerScaleOutDatabase -ServiceApplication $ssa -DatabaseServer <OriginalServerName> [-DatabaseName <NewDbName>]`
`$temp = Get-SPServerScaleOutDatabase -ServiceApplication $ssa`
`Remove-SPServerScaleOutDatabase -Database $temp[0] -ServiceApplication $ssa`

In my case is a database rename task. This step is not clear whether to rename the database first or to run this command first.
The right step (in my opinion) should be to remove the existing database by executing this command.
`$temp = Get-SPServerScaleOutDatabase -ServiceApplication $ssa`
Verify the database name by calling
`$temp | Select-Object { $_.Name }`
Then,
`Remove-SPServerScaleOutDatabase -Database $temp[0] -ServiceApplication $ssa`
Then rename the DB in SQL Server,
Then, execute the following
`Add-SPServerScaleOutDatabase -ServiceApplication $ssa -DatabaseServer <OriginalServerName> [-DatabaseName <NewDbName>]`

I was confused when it was instructed to add first then to remove.
