### ISSUE TITLE
Limited also by Azure AD B2B

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-SharePoint#1321]
If SPO is not limited to specific domains, but AAD Guests are, this experience does not work. MSA domains like hotmail.com must be also added as approved. This article should mention this or link to the other with integration preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Restrict sharing of SharePoint and OneDrive content by domain](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing?redirectSourcePath=%252farticle%252frestricted-domains-sharing-in-sharepoint-online-and-onedrive-for-business-5d7589cd-0997-4a00-a2ba-2320ec49c4e9)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Kazzan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Kazzan** [comment]
Hi @scanum, just also quick update. We investigate if it is needed for generic and master personal MSA domains like outlook.com, or it just does not recognize some national variants like outlook.cz as MSA and thinks that this should be standard invite to AAD.

**Comment by j0rt3g4** [comment]
Hello @Kazzan 

If you stand from the SPO perspective and you're wanting to share to outlook.com or hotmail.com, you are perfectly fine to share file on one drive or SPO.

AAD Guest are more a sort of user that has access to specific resources inside a tenant.

I'm not clear about what would you like to mention or link into the article.

**Comment by Kazzan** [comment]
Hello @j0rt3g4.

Imagine this scenario with Azure AD B2B integration: 
1. SharePoint Admin allow sharing to all domains in SPO admin center and tell users.
2. Azure Admin restrict creating Guest accounts only to allowed domains in AAD (and not add personal one domains).
3. User try to share the file from SPO and receive error that sharing invite cannot be send (sharing is limited).
4. SharePoint admin does not see AAD console and cannot solve the user problem in step 3.

It is because in this case user cannot create Guest account in AAD from SPO.

So mention to future Azure AD B2B and how to handle AAD/MSA in setup will be fine improvements of this article (or at least to AAD guide for external collaboration).

**Comment by MikePlumleyMSFT** [comment]
@Kazzan we call out the Azure AD domain settings in our [Collaborating with people outside your organization](https://docs.microsoft.com/Office365/Enterprise/collaborating-with-people-outside-your-organization) configuration articles.

**Comment by Kazzan** [comment]
Hi @MikePlumleyMSFT, nice article. So just please adding link to them to these article. Point of view. SharePoint admin does not know and does not bother about AAD and setup there. They just look there and see, everything is ok, call support.

**Comment by scanum** [comment]
@j0rt3g4

**Comment by j0rt3g4** [comment]
Adding information on PR #1439

**Comment by j0rt3g4** [comment]
Hello @MikePlumleyMSFT  Can you suggest what would be done in this article so we can move forward to the closure? 
@scanum

**Comment by MikePlumleyMSFT** [comment]
I added a note and a link to the Azure AD article about Azure AD domain filtering.

**Comment by j0rt3g4** [comment]
@MikePlumleyMSFT  Thank you !

**Comment by scanum** [comment]
@Kazzan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
