### ISSUE TITLE
Affect of Disabling

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#1322]
Is there any affect on the new Microsoft Search (Bing for Business) when the Office Graph is disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21ad738-c2a1-ef1f-d745-eebe907311ac
* Version Independent ID: e931c7e1-fdb4-414b-986d-d7755fc797c4
* Content: [Office Delve for Office 365 admins](https://docs.microsoft.com/en-us/sharepoint/delve-for-office-365-admins?redirectSourcePath=%252fen-us%252farticle%252f54f87a42-15a4-44b4-9df0-d36287d9531b)
* Content Source: [SharePoint/SharePointOnline/delve-for-office-365-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delve-for-office-365-admins.md)
* Service: **sharepoint-online**
* GitHub Login: @gretel
* Microsoft Alias: **gretel**

**Comment by wobba** [comment]
@DeanGross can you elaborate? And you talk about Microsoft Search in Bing explicitly, or Microsoft Search overall? (sp home, office.com, bing). And do you mean Office Graph off overall, or individual user disabling Delve Documents?

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by DeanGross** [comment]
@wobba  I meant MS Search overall as well as Office Graph overall

**Comment by j0rt3g4** [comment]
Hello @wobba 
As long as the application (in this case Microsoft Search) does or doesn't require Microsoft Graph it will be impacted or not.

So:
Microsoft Search (**Bing for business**) is not based on Microsoft Graph.

But if you go here:
https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Welcome-to-Microsoft-Search-intelligent-search-for-the-modern/ba-p/509097

Then the "Microsoft Search" (**which is not bing for business**) does rely on Microsoft Graph, so it should be affected.

**Comment by wobba** [comment]
It's called "Microsoft Search for Bing" when it appears in Bing 😉 Microsoft search is the same from a back-end perspective regardless if you use it from Bing or SPHome/Office.com.

Trending insights are not used for search result recall or ranking, nor query suggestions today. Query suggestions in the search box are backed by the "used insights api", thus are being used in Microsoft Search.

To sum up @DeanGross, turning off Delve for a tenant will not impact Microsoft Search.

Question, what would you like to happen/not happen if you disable Delve on a tenant? Also, why do you want to disable Delve?

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by DeanGross** [comment]
@wobba I don't want to disable it, I'm trying to convince my client to turn it on and I want to make sure I give them a complete listing of everything that they are missing.
