### ISSUE TITLE
Authentication protocols

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SharePoint#1323]
What prototocol does ODfB client use/support for authentication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df67a6d7-8d87-cd0f-ceba-740727cc2aa7
* Version Independent ID: 0e33e2ed-b837-46b1-c587-0be823f12e5e
* Content: [How sync works](https://docs.microsoft.com/en-us/onedrive/sync-process)
* Content Source: [OneDrive/sync-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@angoo-atea Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@angoo-atea for SharePoint 2019 or Online? NTLM for 2019; fed auth for Online.

**Comment by j0rt3g4** [comment]
Other pointers are:
https://it.phhp.ufl.edu/files/2015/02/How_OneDrive_for_Business_sync_works.pdf

So every chunk of information is encrypted with a unique key and it's unencripted end to end, using the protocols of authentication that @tseward mentioned.

**Comment by angoo-atea** [comment]
@tseward - Both. Thanks for the info, this should be included in this page.

@j0rt3g4 - Yes, I've seen that document, and there's not a single specific reference or use of the word authentication, NTLM or Fed Auth in that document. So in my opinion that document is incomplete and should be updated.

**Comment by scanum** [comment]
@j0rt3g4 @kaarins Hi Kaarins, could you please aid in next steps. Please let us know if we should update the document. Thanks!

**Comment by j0rt3g4** [comment]
Please let me know @kaarins  to update the documentation accordingly. Thanks in advance.

**Comment by tseward** [comment]
@j0rt3g4 I would put a link to https://docs.microsoft.com/sharepoint/authentication under a related section.

**Comment by angoo-atea** [comment]
Also, is this entire page relevant for the ODfB client on all platforms? (Win/OSX/iOS/Android)

**Comment by tseward** [comment]
Since authentication is done server-side, yes it would be.

**Comment by j0rt3g4** [comment]
Indeed no matter what client app you use @angoo-atea

**Comment by scanum** [comment]
@angoo-atea Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
