### ISSUE TITLE
Support for SAML 2.0 auth in SP 2019

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SharePoint#1324]
Does SP2019 support SAML 2.0, if not currently, will it ever?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4559926-c6e8-03b7-f07c-20adc26c14d6
* Version Independent ID: 7094c31c-64de-5504-d1a4-500478309181
* Content: [Implement SAML based authentication in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
No, it does not support SAML 2.0 and no, it will not get this feature (or rather, it is extremely unlikely you'll see any feature changes in 2019).

**Comment by angoo-atea** [comment]
Thanks. Is OAUTH/OpenID Connect to be preferred in that case?

**Comment by tseward** [comment]
SharePoint supports OAuth, but not OIDC. It continues to support SAML 1.1.

From an authentication perspective, Windows auth is the preferred method (sans where OAuth is used for things like Office Online Server or Addins).

**Comment by scanum** [comment]
@angoo-atea Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
