### ISSUE TITLE
Which takes precedence?

### ISSUE THREAD

**Issue by glmag** [MicrosoftDocs/OfficeDocs-SharePoint#1325]
If an admin sets the Days to retain files in OneDrive to 3650, will the deleted site also be preserved/remain active for 3650 days as opposed to just 93 days in Site Recycle Bin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users](https://docs.microsoft.com/en-us/onedrive/set-retention#feedback)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@glmag Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
If an admin sets 3650 days of retention of Onedrive. it will remain 3650 days while the files or site exists.

If you remove a site (I'm assuming the "-my-" site, meaning removing the license of Onedrive for Business), the site will be deleted at 93 days.

In conclusión, it's a mix of both.
If the user contains an OFB license it will get the admin retention applicated.
if the user doesn't contain an OFB license the site will be removed at 93 days. (or even 30)

**Comment by scanum** [comment]
@glmag Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
