### ISSUE TITLE
Separation in multiple instances

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SharePoint#1327]
There's no guidance here related to separation of SharePoint databases into multiple instances. For example, keeping all SP admin/service databases in one instance and all web application content databases in another. Or even separate instances for each web application. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588cac-efbb-da8f-8b1f-8f4a21298116
* Version Independent ID: d5fead27-6212-5bc7-5bbf-9ce2066f479d
* Content: [Best practices for SQL Server in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm)
* Content Source: [SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@angoo-atea Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@angoo-atea that wouldn't necessarily be 'best practice'. Using multiple instances on the same SQL Server wouldn't be -- you would have to closely manage memory for each instance.

In most cases, a single properly sized and configured SQL Server is more than sufficient.

**Comment by angoo-atea** [comment]
@tseward - well, best practices are also "what not to do". So maintaining a single instance is "best practice", separation into multiple instances is not recommended due to performance overheads. Worthy of a line or two in this article in any case.

**Comment by tseward** [comment]
I think the only issue with that is the list of 'what not to do's' could be quite long. It isn't practical to list them all out.

**Comment by angoo-atea** [comment]
Well then a simple statement that it's best practice to use a single instace and anything else will cause an overhead in management of SQl resurces will be sufficient?

**Comment by j0rt3g4** [comment]
I tried to be on the middle ground of both points of views and yes a new line won't hurt anybody.
PR #1355

**Comment by scanum** [comment]
@angoo-atea Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
