### ISSUE TITLE
Backup tab missing on version 19.158

### ISSUE THREAD

**Issue by hsantan** [MicrosoftDocs/OfficeDocs-SharePoint#1331]
I'd like to known why is missing Backup tab on the sync client version 19.158
Is there some config that need to be enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#feedback)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hsantan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @hsantan  I think the best way to get your issue a proper treatment would be via a support ticket 

https://support.office.com/home/contact

**Comment by scanum** [comment]
@hsantan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by turpie** [comment]
Make sure that g.msn.com isn't blocked on your network. We had the msn.com domain blocked at our school (due to the headlines often being unsuitable for young children.)
Once we whitelisted g.msn.com, OneDrive KFM Backup tab started working again.
