### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by SPLeon** [MicrosoftDocs/OfficeDocs-SharePoint#1337]
I have enabled the Custom Tiles on the Portal web application (SharePoint 2019). 
On the MySite Web application I ran the PowerShell commands as mentioned:

$w.Properties.CustomTilesListHostUrl = "Portal web app url"
$w.Update()

The custom tiles are not populated to the mysite. After investigation I came to the conclusion the application pools are different for both web apps (best practice, use another identity for you Mysite Pool). 

Eventvwr error:

SQL Database 'WSS_Content_Portal02' on SQL Server instance '<SQLSERVER>' not found. Additional error information from SQL Server is included below.

Cannot open database "WSS_Content_Portal02" requested by the login. The login failed.
Login failed for user '<DOMAIN>\sys_spMySitePool19'.

Ensure that the other Application Pool identity (Mysite) has permissions on the database where the Root site and the Custom Tiles list is located:

- SPDataAccess / PSDataAccess

This solved my issue

**Comment by scanum** [comment]
@SPLeon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
