### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by ITGuy99** [MicrosoftDocs/OfficeDocs-SharePoint#1338]
PDF and PowerPoint slide links are not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87003868-0ab6-3c6a-fb62-0671cd45a32e
* Version Independent ID: 395c27e4-ff49-ec4d-7a5d-eecc0cf80a05
* Content: [OneDrive for Business Known Folder Move (KFM) Workshop](https://docs.microsoft.com/en-us/onedrive/known-folder-move-workshop#feedback)
* Content Source: [OneDrive/known-folder-move-workshop.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/known-folder-move-workshop.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by MikePlumleyMSFT** [comment]
@ITGuy99 they should be working now.

**Comment by ITGuy99** [comment]
They're working now thanks!
