### ISSUE TITLE
Typographical and grammatical errors

### ISSUE THREAD

**Issue by MarkWagner** [MicrosoftDocs/OfficeDocs-SharePoint#1347]
The second bullet in the "Service account recommendations" section has one typo and one grammatical usage error.

Change "simplify" to "simplifies"
Change "significally" to "significantly"

The last sentence is.
"This simplify the management of the SharePoint Farm Administrator accounts significally."

Correction:
"This simplifies the management of the SharePoint Farm Administrator accounts significantly."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73d53bc-485a-a5d8-d864-e2e402c07625
* Version Independent ID: 72edd383-b5cb-3b66-4fb2-e9f5ab7d56ce
* Content: [Account permissions and security settings in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016#service-account-recommendations)
* Content Source: [SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@MarkWagner  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@MarkWagner Thank you for your feedback. We have made the changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1358

Thanks
Sri

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT feel free to close the issue
