### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by chmielo117** [MicrosoftDocs/OfficeDocs-SharePoint#1348]
There seems to be some inconsistency between Set up term set article (https://docs.microsoft.com/en-us/sharepoint/set-up-new-term-set) and Assign roles and permissions to manage term sets (https://docs.microsoft.com/en-us/sharepoint/assign-roles-and-permissions-to-manage-term-sets). The first article has a note marked as important:
"To add a term set in the Term Store management tool, you must be a Group Manager or a Term Store Administrator."
The second article mentions also Contributor: "A Contributor can create or change a term set." It defines that the only difference between the Group Manager and Contributor is the ability to modify the memberships of Contributors. Having that in mind, the Important note appears to be inaccurate as it does not list all roles that can handle that task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449a5cb7-2200-f64b-ee4f-c0af2c7ba7ad
* Version Independent ID: 18da722e-9d9a-2858-e4dc-91fd99b7656c
* Content: [Set up a new term set](https://docs.microsoft.com/en-us/sharepoint/set-up-new-term-set)
* Content Source: [SharePoint/SharePointOnline/set-up-new-term-set.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/set-up-new-term-set.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@chmielo117  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT please merge the PR and close this issue

**Comment by scanum** [comment]
@chmielo117 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
