### ISSUE TITLE
Active Directory DFL and FFL

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#1350]
What about the Domain Functional Level and Forest Functional Level versions supported by SharePoint 2013? Is there a lower/upper limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171d6bb7-4f08-573b-a2c7-5e78add14340
* Version Independent ID: 8c204184-9c39-727c-2ac3-6106be7ce1b8
* Content: [Hardware and software requirements for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-0#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Lower limit for all supported versions of SharePoint is 2003 native mode (it used to be referred as "2003 SP2" in an old TN article).

I'll find a section to put this in for the 2013-2019 versions of this article.

**Comment by scanum** [comment]
@LuigiBruno Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by tseward** [comment]
@scanum I'll be updating multiple documents, please re-open this issue.

Thanks!

**Comment by LuigiBruno** [comment]
> Lower limit for all supported versions of SharePoint is 2003 native mode (it used to be referred as "2003 SP2" in an old TN article).
> I'll find a section to put this in for the 2013-2019 versions of this article.

Thanks @tseward.

**Comment by Au8ust** [comment]
@tseward Is there any upper limits?

**Comment by tseward** [comment]
@Au8ust there is not.
