### ISSUE TITLE
CC Options for the Video?

### ISSUE THREAD

**Issue by ssomu-ms** [MicrosoftDocs/OfficeDocs-SharePoint#1351]
Is it possible to get CC options added to the video on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d200ef95-40fd-a858-56b9-06b33184c203
* Version Independent ID: c2e4319b-ba48-8df0-ce13-0697ed3c3a86
* Content: [Video demo of Zero Downtime Patching in SharePoint Server 2016](https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/video-demo-of-zero-downtime-patching-in-sharepoint-server-2016?redirectedfrom=MSDN#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/video-demo-of-zero-downtime-patching-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/video-demo-of-zero-downtime-patching-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ssomu-ms thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
