### ISSUE TITLE
Clarity around whether OneDrive contents are retained when a user's UPN changes

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/OfficeDocs-SharePoint#1359]
It is implied, but not explicit, that when a UPN changes the user's existing OneDrive [site] is renamed and retains all its contents, as opposed to a new, empty OneDrive being established with the new URL, in which case data would need to be migrated from the old OneDrive to the new.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes#feedback)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@adamgourd  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@adamgourd making a test on my end to confirm

**Comment by dplotnikov** [comment]
@adamgourd I've made a test and I see that old site is not available and the new one has all files, so no migration is needed here

**Comment by scanum** [comment]
@adamgourd Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
