### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#136]
Is there any guidance around the ports for the WF Server? Looks like ports 12290 and 12291 and some Service Bus ports need to be opened, but these are not on docs.microsoft.com but on social/technet sites. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9696f9c-aeb8-e0b9-2a43-bc24e9c7b2b2
* Version Independent ID: e267b2fe-5cb3-9f79-f062-4f02763d7505
* Content: [Install and configure workflow for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/install-and-configure-workflow-for-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by kenwith** [comment]
@eschrader - you can find the ports for Workflow Manager here: https://msdn.microsoft.com/en-us/library/jj193485.aspx  All of the content is moving from MSDN/TechNet to open source model using GitHub and surfaced on docs.microsoft.com. It looks like the Workflow Manager documentation hasn't moved yet though. Thanks for feedback.
