### ISSUE TITLE
Impact of UPN and OneDrive URL change on Teams conversation attachments

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/OfficeDocs-SharePoint#1360]
Files attached to ad hoc Microsoft Teams conversations are stored in the OneDrive of the user attaching the file. How does a UPN and corresponding OneDrive URL change impact access to those attachments in Teams chats?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes#feedback)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
As Teams performs the sharing on behalf of you, the impact is outlined at https://docs.microsoft.com/en-us/onedrive/upn-changes#shared-onedrive-files.

**Comment by scanum** [comment]
@adamgourd Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
