### ISSUE TITLE
Manage ODB updates via Windows Service Update Services (WSUS) 

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SharePoint#1361]
Hello Team, OneDrive does not appear to be in the WSUS categories and it's not listed as an update in the O365 updates. Can we have additional guidance on how to manage the OneDrive updates using WSUS? Or can the updates only be managed through 1) the online process or 2) using OneDriveSetup.exe? Thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise#manage-onedrive-by-using-system-center-configuration-manager)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@soyalejolopez  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @soyalejolopez, thank you for your feedback.

You can manage OneDrive updates using System Center Configuration Manager with WSUS, not standalone.
Also using the online process and network location.

**Comment by scanum** [comment]
@soyalejolopez Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mpsprouse** [comment]
Do you have any other information on managing the OneDrive updates using System Center? We do not see the product "OneDrive" listed as an available product in on the Software Update Point.

Thank you
