### ISSUE TITLE
Sentence incomplete in PDF

### ISSUE THREAD

**Issue by carlyhublou** [MicrosoftDocs/OfficeDocs-SharePoint#1368]
In the PDF, on slide 5, under "Limit Network Bandwidth," the final bullet point is an incomplete thought: "Roll out gradually and monitor other potential"

**Comment by dplotnikov** [comment]
@carlyhublou please share PDF link

**Comment by scanum** [comment]
@carlyhublou  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@carlyhublou any word on this? it's almost impossible to find a mentioned PDF document without a link

**Comment by carlyhublou** [comment]
Sure, it's linked on this page: https://docs.microsoft.com/en-us/onedrive/known-folder-move-workshop where it says "Download the PDF." I imagine the PowerPoint might need to be updated too, but I haven't opened that file.

**Comment by dplotnikov** [comment]
@carlyhublou thanks for sharing! I'll check this shortly

**Comment by dplotnikov** [comment]
@kaarins please merge the PR and feel free to close this issue

**Comment by scanum** [comment]
@carlyhublou Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
