### ISSUE TITLE
Please Update: To limit domains for a Modern site collection

### ISSUE THREAD

**Issue by twalker-ms** [MicrosoftDocs/OfficeDocs-SharePoint#1369]
I have verified that limit is 100 for both Classic and Modern Site collection

Can you add a section that states the 100 limit applies to Modern Site Collections as well?

Something like this:

For Modern site collections, you can only configure this setting by using the Set-SPOSite Windows PowerShell cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Restrict sharing of SharePoint and OneDrive content by domain](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing#feedback)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@twalker-ms  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT  feel free to merge the PR and close this issue

**Comment by scanum** [comment]
@twalker-ms Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
