### ISSUE TITLE
Installing Update on Distributed Cache Server

### ISSUE THREAD

**Issue by KRyan318** [MicrosoftDocs/OfficeDocs-SharePoint#137]
After running the executable, the servers prompted to restart. You may want to add this to the steps. Also, under the heading, "To install an update without backward compatibility," should there by a step between 8 and 9 that says to run the executable on the distributed cache server? Likewise, should there by a step between steps 13 and 14 that says to run the Configuration Wizard on the distribute cache server? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757daa4f-85eb-2b0e-094a-f01b9ed3d874
* Version Independent ID: acfb92cf-1d51-d6a7-bebc-9c145f5b7710
* Content: [Install a software update for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Not all patches will require a restart. It depends on the role and the state of services. As for your other questions, this article doesn't talk about particular roles per se, just that there are 6 SharePoint servers, 4 "web", 2 "app".

**Comment by kenwith** [comment]
@KRyan318 and @tseward - thanks for the conversation on this and helping the community. Let me know if there is a Pull Request or anything that should be added on the doc. Thanks!
