### ISSUE TITLE
No actual instructions to enable SharePoint Home Page

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/OfficeDocs-SharePoint#1370]
The article's title is "Enable SharePoint home page in SharePoint Server 2019 farms". While it talks about what the page is and why it is useful, it doesn't give any instructions about how to actually enable it. 

There are troubleshooting steps, but they may not apply if the page isn't even enabled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6243ae66-37bb-35dd-86c7-c9ae6d84079d
* Version Independent ID: b1e649b9-b691-6553-bea7-04dd0c115d09
* Content: [Enable SharePoint home page in SharePoint Server 2019 farms](https://docs.microsoft.com/en-us/SharePoint/sites/enable-sharepoint-home-page-in-sharepoint-server-2019-farms)
* Content Source: [SharePoint/SharePointServer/sites/enable-sharepoint-home-page-in-sharepoint-server-2019-farms.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/enable-sharepoint-home-page-in-sharepoint-server-2019-farms.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@sympmarc on the page you linked to, the list of requirements are outlined at the anchor https://docs.microsoft.com/en-us/SharePoint/sites/enable-sharepoint-home-page-in-sharepoint-server-2019-farms#requirements-to-enable-the-sharepoint-home-page.

**Comment by sympmarc** [comment]
I thought that might be the answer, but the article doesn't really make that clear. It says "Requirements to enable the SharePoint home page", but it doesn't say if all of those are in place then the SharePoint home page will just show up.

**Comment by tseward** [comment]
Well, the app launcher will show up once you do those things. Without the UPSA, you get no app launcher.

**Comment by scanum** [comment]
@sympmarc Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
