### ISSUE TITLE
KFM cross-volume support introduced since build 19.152.0801.0006

### ISSUE THREAD

**Issue by alinefmr** [MicrosoftDocs/OfficeDocs-SharePoint#1375]
OneDrive release notes for build 19.152.0801.0006 (August 21, 2019) mentioned: "New features gradually rolling out to users: Cross-volume support when you enable backup of your important folders". Could you please provide clarification? This article says a known folder must be on the same volume than the OneDrive folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@alinefmr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ltobiasg** [comment]
Any additional information for this cross-volume syncing?

**Comment by dariomws306** [comment]
Hi @alinefmr, thank you for your feedback.

This was removed from the article on October 14.

**Comment by DaanvanBeek** [comment]
It's rolling out apparently: microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=56383

**Comment by dariomws306** [comment]
Yes, it was officially announced in October:
https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/onedrive-roadmap-roundup-october-2019/ba-p/961330

And removed from the article:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/6d3f10d2f70a0cb697629f8af5a7ca7414e5c104#diff-13a7696fbc794fe5626174dda8472053

**Comment by alinefmr** [comment]
Thank you. Feel free to close this one.

**Comment by scanum** [comment]
@alinefmr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
