### ISSUE TITLE
Missing errors

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-SharePoint#1377]
Missing errors: 

"Failed","SERVER FAILURE","Errors or timeout for Server Processing the file:Job Fatal Error","0x01710006"

"Failed","SERVER FAILURE","Errors or timeout for Server Processing the file:Not all the items in the package have been migrated","0x01710009"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshooting SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues#feedback)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Marweis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by GrimmjowZA** [comment]
Another missing error:
"Failed","UPLOADING FAILURE","Failed to Upload the Job to Server:Upload file failed during migration","0x01510001"

**Comment by scanum** [comment]
@Marweis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
