### ISSUE TITLE
Doc vs. ADMX discrepancy with "Prevent users from fetching files remotely"

### ISSUE THREAD

**Issue by NorbertKlein-Ildefeld** [MicrosoftDocs/OfficeDocs-SharePoint#1379]
In Doc it says [HKLM\SOFTWARE\Policies\Microsoft\OneDrive\Remote Access] "GPOEnabled"="dword:00000001"
In ADM is says [HKLM\SOFTWARE\Policies\Microsoft\OneDrive\] "GPOEnabled"="dword:00000001"
Please check

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#RemoteAccessGPOEnabled)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by NorbertKlein-Ildefeld** [comment]
by ADM I mean the lADMX template

**Comment by scanum** [comment]
@NorbertKlein-Ildefeld  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by NorbertKlein-Ildefeld** [comment]
Hi @scanum, any update on this. The discrepancy is obvious. I take that the ADMX is correct. If not then setting would not be picked up by Onedrive

**Comment by zwaloo** [comment]
+1 here, this is an issue that conflicts with DISA STIGs for OneDrive, which is going to play merry hell during audits. If we can get some confirmation that either 1) the ADMX is correct and documentation (and STIGS) needs to be updated or 2) documentation is correct and the ADMX/L need to be fixed, we can use that to support compliance during audits.

**Comment by NorbertKlein-Ildefeld** [comment]
@scanum - any update please, this was posted 3 months ago!

**Comment by dariomws306** [comment]
Hi @NorbertKlein-Ildefeld, thank you for your feedback.

Based on my test ADMX is correct so I have updated the article.

**Comment by scanum** [comment]
@NorbertKlein-Ildefeld Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
