### ISSUE TITLE
Third Party Migration Providers

### ISSUE THREAD

**Issue by sremala** [MicrosoftDocs/OfficeDocs-SharePoint#1380]
As written in this document under "Migration service providers" section, some organizations need to work with a third-party service to migrate from Box to OneDrive. 

https://www.cloudfuze.com/how-to-transfer-files-from-box-to-onedrive/

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/cloudfuze.cloudfuze_cloud_file_transfer?tab=Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dd9b09-7975-6ac0-fa4e-2c09c17c2045
* Version Independent ID: e34a0e26-2f32-98fe-a7d3-01033d6f3a7e
* Content: [Box to OneDrive and SharePoint Migration Guide](https://docs.microsoft.com/en-us/sharepointmigration/box-to-onedrive-and-sharepoint-migration-guide#feedback)
* Content Source: [migration/Box-to-OneDrive-and-SharePoint-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Box-to-OneDrive-and-SharePoint-migration-guide.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dplotnikov** [comment]
@sremala sorry but the official documentation is not the place to promote or give preferences to any 3rd party solutions/vendors

**Comment by scanum** [comment]
@sremala Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
