### ISSUE TITLE
2019 Optimization Script and DistributedClientSideAppUpdateTimeCache Property

### ISSUE THREAD

**Issue by RGrizzzz** [MicrosoftDocs/OfficeDocs-SharePoint#1381]
Does the 2016 script also apply for 2019?

In the following link, it mentions 6 new containers for SP2016 (and 2019?) The optimization script sets the settings for 5 of the 6 settings. It's missing DistributedClientSideAppUpdateTimeCache. Should that be included as well? With the same settings as the others? 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/clear-spdistributedcacheitem?view=sharepoint-ps

ronalg@microsoft.com 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff8221d-8995-2bd1-9ab4-e0043afe1c5f
* Version Independent ID: 2b157758-daa4-dad2-5edb-891e421d921f
* Content: [Manage the Distributed Cache service in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service#feedback)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
`DistributedClientSideAppUpdateTimeCache` isn't actually included with 2016 -- it is one of the referenced but non-existent caches. You'll see numerous ULS errors about it after you deploy an app.

**Comment by scanum** [comment]
@RGrizzzz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
