### ISSUE TITLE
STS certificate expired

### ISSUE THREAD

**Issue by paulewert** [MicrosoftDocs/OfficeDocs-SharePoint#1382]
Worthy to note that an expired STS certificate can also lead to this symptom. If so, the Windows Application event log will show Event ID 8311 for source SharePoint Foundation, category Topology with "NotTimeValid" in the message. It will also identify the expired certificate. The article at https://docs.microsoft.com/en-us/sharepoint/administration/replace-the-sts-certificate gives directions for updating the certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f9d93f3-982e-8f16-361e-b0feb7bf0712
* Version Independent ID: 77bbdd41-adbd-3ab5-00a1-cb0220c3dcdc
* Content: [The Security Token Service is not available (SharePoint Server)](https://docs.microsoft.com/en-us/sharepoint/technical-reference/the-security-token-service-is-not-available)
* Content Source: [SharePoint/SharePointServer/technical-reference/the-security-token-service-is-not-available.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/the-security-token-service-is-not-available.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@paulewert  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @paulewert, thank you for your feedback.

Could you kindly give me more detail about what is your suggestion to improve this article?

**Comment by paulewert** [comment]
Hi, @dariomws306. Thank you for looking at this.  I managed to find this technical reference titled "[The Security Token Service is not available (SharePoint Server)](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/the-security-token-service-is-not-available.md)," (referenced in the Document Details of my original comment on September 26) but the two proposed resolutions within it were not at all the issue we ran into. I recommend/request adding a third resolution in said technical reference mentioning further diagnostics to look for the Windows Application event log Event ID 8311 for source SharePoint Foundation, category Topology with "NotTimeValid" and giving a link to the article at [https://docs.microsoft.com/en-us/sharepoint/administration/replace-the-sts-certificate](https://docs.microsoft.com/en-us/sharepoint/administration/replace-the-sts-certificate) which gives directions for updating the certificate. (Unfortunately, for that article, @tseward is suggesting the expiration of the certificate is not an issue and doesn't want to add clarification to the article on how to update the STS certificate once it _has_ expired. It _is_ a _real_ issue for some Admins which leaves us struggling to resolve.) 

I have submitted a proposed change to this article to help others who may also experience the "STS is not available" issue due to an expired STS certificate.

**Comment by tseward** [comment]
I think my point was that in order for the cert to have expired, you already had to follow the instructions to replace the STS with your own cert. The expiration of the default cert is outside of our lifetimes.

**Comment by dariomws306** [comment]
Hi @paulewert, thank you for your feedback.

I'm agree with @tseward but I have created a Pull Request so in this way the author could approve it or not if he/she thinks this solution is accurate.

**Comment by scanum** [comment]
@paulewert Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
