### ISSUE TITLE
Identifying an expired STS certificate

### ISSUE THREAD

**Issue by paulewert** [MicrosoftDocs/OfficeDocs-SharePoint#1383]
If your STS certificate has expired, you will see a Windows Application event log for Event ID 8311, source SharePoint Foundation, category Topology with "An operation failed because the following certificate has validation errors" and "NotTimeValid: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file" in the message. It will also identify the expired certificate. This page is great for resolving this issue!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f58e6f-436d-1be5-1160-c4a026f3835b
* Version Independent ID: f6232934-7bf4-3fe5-f752-2067d57bcd28
* Content: [Replace the STS certificate for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/replace-the-sts-certificate)
* Content Source: [SharePoint/SharePointServer/administration/replace-the-sts-certificate.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/replace-the-sts-certificate.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@paulewert are you looking for any changes to this page?

**Comment by paulewert** [comment]
The page is great: very good instructions! It would be helpful for readers to have reasons they would need to replace the STS certificate. I lost three days of work time because the certificate on my Dev box had expired after five years. Microsoft Premier Support took two days just to scope our support ticket and didn't even get to searching for a resolution before I finally found this page and resolved the issue without Support's help. Having the reasons such as the comment I'd like to see added to the page will help others identify their issue and be right on the page they need in order to fix it without any further lost time waiting for Support.
 
Thanks!
   ---PaulE---
 
-----Original Message-----

**Comment by scanum** [comment]
@paulewert  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@paulewert what was your reason for replacing the certificate to begin with? There are certainly valid scenarios to do so. The article does indicate the process is to be followed when the certificate will expire.

> As public certificates and by default, private certificates expire within 1 to 3 years depending on the specified validity period, this procedure should be followed when the certificate requires renewal.

**Comment by paulewert** [comment]
@tseward STS certs in my farm had already expired (as indicated in the application event message given above). This caused SharePoint to essentially sieze up: only serving up 500 errors. We've checked our other farms to try to head off the painful process of replacing the certs _after_ expiration. We've got at least two other farms wherein the STS certs expire within the next four months. This article was the only thing I could find for help after expiration, even though it is written primarily for use _before_ expiration.

**Comment by scanum** [comment]
@tseward

**Comment by tseward** [comment]
@scanum  I think we can close this. Since the STS by default doesn't expire for hundreds of years, one would have to purposefully replace it following these instructions in the first place.

**Comment by paulewert** [comment]
It is still a very real issue that an Admin can run into an expired STS certificate, whether the expiration date was set by default or purposefully. Please include help in the article for how to replace the certificate _after_ expiration. I'll try to find some time to fork an edit of the document and submit it for approval.

**Comment by tseward** [comment]
@paulewert are you indicating the instructions will not work for an _expired_ STS certificate?

**Comment by paulewert** [comment]
@tseward Correct. The information in the instructions for a non-expired certificate were helpful for fixing the issue with some trial-and-error, but the process for fixing an already expired certificate was different. The instructions would be much better if they included directions for _both_ scenarios more defined. Thanks!

**Comment by scanum** [comment]
@paulewert Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
