### ISSUE TITLE
GCC cannot share externally

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-SharePoint#1384]
A note should  be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dplotnikov** [comment]
@Marweis what is GCC?

**Comment by Marweis** [comment]
Govt cloud.

**Comment by scanum** [comment]
@Marweis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Marweis, thank you for your feedback.

I understand that it should be enabled based on service description:
https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod#sharepoint-online

**Comment by scanum** [comment]
@Marweis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
