### ISSUE TITLE
Manually Permanently delete OneDrive 

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1385]
Is there any way to permanently delete OneDrive for deleted accounts before the retention period is up?  If so, can you add that here?  Sometimes, especially for testing, you can't wait for the retention period to end before wanting the OneDrive location deleted.  Example: we have a test account called DTEST that we've used for testing and then deleted a few times already.  However, the OneDrive Usage report still shows THREE OneDrive locations existing for this account.  I need to delete all 3 of these and not wait for the retention period to end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Canis-Lupis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@Canis-Lupis would adding a reference under a new 'additional info' section to `Get-SPODeletedSite` and `Remove-SPODeletedSite` be sufficient?

**Comment by Canis-Lupis** [comment]
I don’t think Get-SPODeletedSite shows OneDrive sites, only SharePoint.  I will test to be sure, though.

**Comment by tseward** [comment]
It does, you just have to use the `-IncludePersonalSite` switch.

**Comment by Canis-Lupis** [comment]
tseward, thank you so much! That worked!
