### ISSUE TITLE
Please add "Upload Document Template to Content Type" as a blocked feature

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/OfficeDocs-SharePoint#1388]
I found that custom scripts are necessary when attempted to add a document template to a content type in SPO, from Microsoft's response to the question below. Please update the document to reflect this.

https://answers.microsoft.com/en-us/msoffice/forum/all/cannot-upload-document-template-to-content-type/f3b27abb-52d0-41e5-be45-dc5185ba3f0e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@oliviadudley Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
