### ISSUE TITLE
Microsoft does not allow customers to select tenant names.

### ISSUE THREAD

**Issue by DGDC** [MicrosoftDocs/OfficeDocs-SharePoint#1390]
Because Microsoft no longer allows customers to specify/request tenant names (at least sales and support know of no way) the proposed solution is not an option. Microsoft generates a combination of the domain, TLD, and random numbers for the tenant name. E.g. mydomaincom533

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name#feedback)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
The tenant domain is one you enter as part of the Office 365 initial account/tenant creation.

**Comment by scanum** [comment]
@DGDC Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by DGDC** [comment]
With all do respect and having a support ticket opened on the matter, customers cannot simply select their tenant domain.  Your documentation is out of date.

**Comment by LtCmdrKeene** [comment]
I purchased a new subscription but it didn't let me pick my tenant name. It ended up being called "gibborimproductionscom", which is much longer than I wanted.
