### ISSUE TITLE
Acronyms not spelled out

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/OfficeDocs-SharePoint#1392]
The word "ADAL" is used without an explanation of what it is. Searching for "Active DIrectory L" doesn't yield anything. 

In technical writing, it's best to always mention an acronym spelled out, the put the acronym in parenthesis. As web pages can be linked to without reading previous sections, it's probably a good idea to build in a call out so you can hover over the acronym, or spell it out like you would on dead trees. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-gb/onedrive/use-group-policy#SilentAccountConfig)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jgwinner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ChrisKibble** [comment]
ADAL is no longer in the document, probably can close this issue?

**Comment by jgwinner** [comment]
Sure! Thanks for listening.
