### ISSUE TITLE
Configure Add-Ins for an Environment with Multiple WFEs

### ISSUE THREAD

**Issue by dwolfinoc** [MicrosoftDocs/OfficeDocs-SharePoint#1394]
These instructions are fine for a farm with a single web front end.
We could use prescriptive help with configuring an environment with two (or more) WFEs behind a load balancer (in our case, and f5). 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be97870a-7b79-08fb-c640-f4c3c7f8b6ac
* Version Independent ID: 775b9c05-5e88-b24e-1507-ecd678357673
* Content: [Configure an environment for apps for SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/configure-an-environment-for-apps-for-sharepoint#feedback)
* Content Source: [SharePoint/SharePointServer/administration/configure-an-environment-for-apps-for-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-an-environment-for-apps-for-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@scanum assign to me.

@dwolfinoc for the short of it, you would create a CNAME per the article that points to an A record that is assigned the IP address of the VIP on your load balancer. From the SharePoint side, the configuration is no different.

**Comment by dwolfinoc** [comment]
Thank you for responding Trevor. Totally surprised and greatly appreciated that you read my post asking for additional information.
(My copy of your and Vlad’s book “Deploying SharePoint 2016” is very dog-eared from use.)

After we followed Microsoft’s prescriptive document Configure an environment for apps for SharePoint Server<https://docs.microsoft.com/en-us/SharePoint/administration/configure-an-environment-for-apps-for-sharepoint> without joy, I found the brief mention of the Host (A) entry on page 95 of your book when load balancing for multiple WFEs is used. I wish that Microsoft would expand their article to detailed, prescriptive instructions for configuring DNS for load balancing; we cannot be the only ones with multiple WFEs.

I hate to take advantage of your kind reply, but could use some help. If you have time, please continue reading:

Something that possibly complicates our situation further is that the f5 requires a ‘catch all’ binding for all unassigned port 443 connections to pass traffic to the SharePoint WFE servers. If this binding is disabled or loses reference to the SSL certificate, the f5 will not direct traffic to the WFE.
[cid:image003.png@01D5790C.525F1870]

This conflicts with the same type of binding all instructions say to use for the Addins web application:
[cid:image005.png@01D5790C.525F1870]

Any thoughts?
I instinctively created a second IP address on the each of the two WFE servers, because I could not see how we could have two virtual IIS instance use the same IP address for two All Unassigned port 443 bindings.
IIS won’t let you:
[cid:image009.png@01D5790C.525F1870]

Am I correct in creating a second IP address on the WFE servers and using that for the Addins web application?
Or should I assign the second IP address to all other IIS instances and keep the default IP address for Addins?
Or am I all wet with this idea.

Again, anything you can recommend will be helpful not only to us, but to probably thousands of others who may be struggling with this same issue.

Thank you,

Dave
David A. Wolf
Senior SharePoint Administrator

GIBSON DUNN

Gibson, Dunn & Crutcher LLP
3161 Michelson Drive, Irvine, CA 92612-4412
Tel +1 949.451.3821 • Fax +1 949 451 4220
DWolf@gibsondunn.com<mailto:DWolf@gibsondunn.com> • www.gibsondunn.com<http://www.gibsondunn.com/>

**Comment by tseward** [comment]
@dwolfinoc do me a favor and open a thread on TechNet in the appropriate SharePoint forum - https://social.technet.microsoft.com/Forums/. Will be easier to follow and should allow us to close this docs-related issue unless you have feedback that needs to be incorporated.

**Comment by dwolfinoc** [comment]
Thank you, Trevor. Will do. Will share anything special we have from our side in case this helps others.

Dave

David A. Wolf
Senior SharePoint Administrator

GIBSON DUNN

Gibson, Dunn & Crutcher LLP
3161 Michelson Drive, Irvine, CA 92612-4412
Tel +1 949.451.3821 • Fax +1 949 451 4220
DWolf@gibsondunn.com<mailto:DWolf@gibsondunn.com> • www.gibsondunn.com<http://www.gibsondunn.com/>

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
