### ISSUE TITLE
Missing info on search and timer jobs

### ISSUE THREAD

**Issue by altevid** [MicrosoftDocs/OfficeDocs-SharePoint#1395]
There is no information on what the process is like, what happens when you run the command and what happens after.
What about the site collection not being completely removed, just "deleted" flag set to "1", how the Gradual site delete timer job will delete the site collection from content database, long after you execute Move-SPsite command.
 
The consequence of search results about crawl is active while doing a Move-SPsite, what should you do to avoid problems.

We often have problems with this when we move site collections, we often move site collections that are relatively large, or that we move many at the same time.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 9bb82eb3-40f3-23d3-5aea-491f98dcbaf3
* Version Independent ID: b704f90f-41a6-fa5f-d21c-898e136b5220
* Content: [Move site collections between databases in SharePoint Server](https://docs.microsoft.com/sv-se/SharePoint/administration/move-site-collections-between-databases?redirectedfrom=MSDN#feedback)
* Content Source: [SharePoint/SharePointServer/administration/move-site-collections-between-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/move-site-collections-between-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@scanum assign to me.

@altevid for the short of it, you would create a CNAME per the article that points to an A record that is assigned the IP address of the VIP on your load balancer. From the SharePoint side, the configuration is no different.

**Comment by altevid** [comment]
Hello
Don't know what CNAME, A record and load balancer have to do with this, or do I misunderstand something ??

Best regards
/Altevid
________________________________
Från: Trevor Seward <notifications@github.com>
Skickat: den 2 oktober 2019 03:11
Till: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
Kopia: altevid <altevid@msn.com>; Mention <mention@noreply.github.com>
Ämne: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Missing info on search and timer jobs (#1395)


@scanum<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscanum&data=02%7C01%7C%7C729ab33074d2427f25ea08d746d5696c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637055754711648671&sdata=mbnBMQ3BFeLm5NSCK%2Fuwnw6hLpFJavBxr9cW9ZMc2Gw%3D&reserved=0> assign to me.

@altevid<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltevid&data=02%7C01%7C%7C729ab33074d2427f25ea08d746d5696c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637055754711658676&sdata=r77RDr2zr2rmS5K5SJzXtK3SUmOUAqYA0y8NVHrAA8U%3D&reserved=0> for the short of it, you would create a CNAME per the article that points to an A record that is assigned the IP address of the VIP on your load balancer. From the SharePoint side, the configuration is no different.

**Comment by scanum** [comment]
@altevid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@altevid sorry, I had replied to the wrong thread :)

**Comment by dariomws306** [comment]
Hi @altevid, thank you for your feedback.

@tseward @MikePlumleyMSFT could you help on this issue? Do you think we can add this information? Thanks!

**Comment by tseward** [comment]
Typically the cmdlets don't go into this level of detail as the internal implementation may change over time and that information isn't readily surfaced outside of the product group.

**Comment by scanum** [comment]
@altevid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
