### ISSUE TITLE
Search Usage reports page is misleading as it only applies to Classic Search

### ISSUE THREAD

**Issue by pdemro** [MicrosoftDocs/OfficeDocs-SharePoint#1396]
As far as I am aware there is no analytics capability for modern search (or any other extensibility for that matter - fingers crossed for ignite 2019).  This page should be clarified that it only applies to the mostly obsolete classic SharePoint search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4931479-b37a-8350-aba7-13f87937ecc6
* Version Independent ID: 52da4c04-0646-1d3a-39cd-ddce72c2f811
* Content: [View search usage reports](https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports#feedback)
* Content Source: [SharePoint/SharePointOnline/view-search-usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-search-usage-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
If by 'classic' Search you mean SharePoint Search, it applies to content searched from SharePoint. It does not apply to content searched from Microsoft Search (e.g. Bing).

**Comment by scanum** [comment]
@pdemro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pdemro** [comment]
Thanks for reviewing @scanum.  I'm not sure what the resolution is or was.  The page looks like it is identical (maybe an update was pushed to a separate branch)?

In any case, perhaps an update would be more appropriate on this page: https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search.  According to this page, modern search leverages the search index.  It is unclear as to whether search queries in modern sites are captured in the analytics capabilities mentioned on the OP article.

Any guidance would be greatly appreciated!
