### ISSUE TITLE
Can more detail be given about "By default, when you delete a user, ownership of the OneDrive is transferred to the user's manager?"

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1397]
How does O365 know who the manager is? Where is that set?  I'm assuming it is from the Manager field in Azure (or AD for hybrid) but our managers are not getting notified regarding this ownership.  I have checked and we do have "Enable Access Delegation" checked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#configure-automatic-access-delegation)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Yes, it uses the `manager` attribute in the SharePoint User Profile (sync'ed from AAD). If this isn't working for you, I would suggest you open a support case with O365 support who can investigate.

**Comment by scanum** [comment]
@Canis-Lupis thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Canis-Lupis** [comment]
I have opened a service ticket and, so far, they seem pretty clueless about this documented default behavior.  They keep asking me to check Exchange delegation (which isn’t even OneDrive) and manually add each user’s manager if not there, which defeats the purpose of the ‘default’ behavior stated in this document. Even at that, I have seen documentation that a user’s mailbox, along with OneDrive, is supposed to default to giving access to the manager as well when the account is deleted, so I am at a loss to explain why the response I get from MS support is the equivalent of starring blankly into space when I bring it up.

Is there not any more documentation about this feature that can be added?  Something I can show MS support and say, “see, this is what it is supposed to do!”  Even a PowerShell command I can run to show that this default option isn’t working correctly that I can send to support would be helpful.

**Comment by tseward** [comment]
The documentation is accurate (my company leverages this feature all the time and it works automagically as it is supposed to). Make sure to be explicit that you need someone who supports OneDrive (or SPO) and that the assigned manager in the SharePoint User Profile for the exited employee is not being automatically assigned SCA on the exited employee's OneDrive site.

**Comment by Canis-Lupis** [comment]
Thanks for the feedback, Trevor.  It is good to hear that it SHOULD work.  MS support did have an Outlook support person contact me and I was told by then that this feature isn't available for email.  Actually, I think it would be nice to have for email as well but that's another topic for another day.  They did transfer my ticket to OneDrive support and I'm waiting to hear back from them.

In the meantime, what do you mean by "..the assigned manager in the SharePoint User Profile for the exited employee is not being automatically assigned SCA on the exited employee's OneDrive site?"  What is SCA? I'm not good with TLAs (Three Letter Acronyms).  I tried going to User Profile-->Manage Profiles but deleted users don't appear to show up there.

I did go to my profile as well as a few other active users profiles and the Manager field is set there for them, so I'm assuming it was set for the past employees as well. So, I'm not sure what else needs to be turned on for this feature to work.


________________________________
