### ISSUE TITLE
Host Named Site Collections

### ISSUE THREAD

**Issue by Mr-Nivek** [MicrosoftDocs/OfficeDocs-SharePoint#1399]
How do you migrate host named site collections that are contained in their own Content Database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85532d82-2f23-8016-bbd9-a5be8287d821
* Version Independent ID: 0bb20c79-5b3d-b0bb-ecef-e2e848513ada
* Content: [Upgrade content databases to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-content-databases#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-content-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-content-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Mr-Nivek thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Mr-Nivek** [comment]
This has nothing to do with Office 365. We are working on SharePoint 2013 to 2016 migration. The process for migrating a standard content database is documented here on this page, but there are no notes on how to handle host named site collections.
