### ISSUE TITLE
Incorrect PowerShell command

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/OfficeDocs-SharePoint#14]
Hello, in the section, "To set permission to a published service application for a publishing farm by using PowerShell", the command,
Get-SPServiceApplication -Name <ServiceApplicationName>.Id
should be
Get-SPServiceApplication  <ServiceApplicationName>.Id
The -name parameter doesn't work with the Service Application ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34195aa1-1ebe-da6e-d868-b8ff29d6d785
* Version Independent ID: f303e401-d196-1a17-8f75-82e43b0054a2
* Content: [Set permissions to published service applications in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/set-permission-to-a-published-service-application#to-set-permission-to-a-published-service-application-for-a-publishing-farm-by-using-powershell)
* Content Source: [SharePoint/SharePointServer/administration/set-permission-to-a-published-service-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/set-permission-to-a-published-service-application.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by Techwriter40** [comment]
@bentoncity this is yours...please review and correct.  looks like an easy fix.

**Comment by bentoncity** [comment]
Thank you for finding this Joe.  I've revised the cmdlet as you show and this change is live.

**Comment by bentoncity** [comment]
Cmdlet has been fixed so closing comment.
