### ISSUE TITLE
Maxim number of followable users

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#1400]
The "Distributed cache service limits" sections states that "The total number of entities that can be followed by a single user on a distributed cache host with 16GB RAM assigned to the distributed cache service is 400,000.": is this the upper limit to the number of users a SharePoint user can follow? Is there any other limit related to the number of users a SharePoint user can follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits#feedback)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@LuigiBruno Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@MikePlumleyMSFT do you have insights on this?

**Comment by tseward** [comment]
The max you can set via the UI is 1000, which is also the default. You can set the value up to [Int32.MaxValue](https://docs.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=netframework-4.8) in PowerShell, but I don't know what the consequences of setting a value that high would be sans performance issues.

**Comment by LuigiBruno** [comment]
> The max you can set via the UI is 1000, which is also the default. You can set the value up to Int32.MaxValue in PowerShell, but I don't know what the consequences of setting a value that high would be sans performance issues.

Thank you @steward.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
