### ISSUE TITLE
Folksonomy and tagging

### ISSUE THREAD

**Issue by TroyReisch** [MicrosoftDocs/OfficeDocs-SharePoint#1401]
As I understand it "Tags" are no longer allowed in SharePoint online - does the Folksonomy and Tagging sections need to be updated?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d14723-ab30-719c-c69d-e42f94a680b5
* Version Independent ID: 182bf188-87f6-f966-4e86-77ef8927905c
* Content: [Introduction to managed metadata](https://docs.microsoft.com/en-us/sharepoint/managed-metadata#feedback)
* Content Source: [SharePoint/SharePointOnline/managed-metadata.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/managed-metadata.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@TroyReisch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@TroyReisch Social Tags were deprecated and removed. Metadata tags are still valid.
