### ISSUE TITLE
Upload User Mapping File steps 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1403]
The steps for uploading User mapping file should be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user mapping file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration#feedback)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dplotnikov** [comment]
@Padavid could you please give me more insights on the outdated information here?

**Comment by Padavid** [comment]
The steps to upload your mapping file seem like for the old V2 tool.

Here are the steps I had to follow for the latest V3


  1.  Start the SharePoint Migration tool. Enter your Office 365 username and password and then click Sign in.
  2.  Click on “Start your first Migration”
  3.  Choose your migration type
  4.  Enter your source information. Click Next
  5.  Enter your destination information. Click Next
  6.  Review your Migration details click on Next.
  7.  On the choose your settings screen expand “View all settings”
  8.  Under Users section in the User mapping box, click Choose file and select your user mapping file.
  9.  Click Save.


Patrick David
Sr. Premier Field Engineer (SharePoint)
Microsoft
US PFE - Public Sector
Office: +1 (216) 750-4604
Mobile: +1 (440) 821-9586
patrick.david@microsoft.com<mailto:patrick.david@microsoft.com>
[Twitter]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=GMvICN4fL7tv9z2WXixrm%2BoC7vGIncuAIa%2FhfRRHrYw%3D&reserved=0>    [Facebook] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=7GV6giUGL4UKalzU%2FysutD3ig8I%2BdKUC0wGFEJBEw2E%3D&reserved=0>     [Linkedin] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=rZhit9e2v19xp48PflSj%2BhkM4PBYNb6GmIW%2B99O6M1s%3D&reserved=0>     [Youtube] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=1QtQ8jCahvI1CmjaY1B%2FTvTo%2Fy%2FIJpy8HCoZdOOcgT0%3D&reserved=0>
[Microsoft Logo]

If you have any feedback about my work, please let either me or my manager Beth MacAlarney know at bethm@microsoft.com<mailto:bethm@microsoft.com>.

**Comment by dariomws306** [comment]
Hi @Padavid, thank you for your feedback.

If you can please check my pull request to see if it's ok. Thank you again!

**Comment by Padavid** [comment]
I took a look and those directions look good.

**Comment by dariomws306** [comment]
@Padavid Thank you!

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
