### ISSUE TITLE
Update Chart - Permissions vs Sharing

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1404]
The chart should be updated. User with full control will map to Full Control in SPO not contribute role. Also some clarifications around the "SharePoint item access" column some of these roles are not in SPO so I am not sure what is meant by this column example "Read and execute" and "List folder contents" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [File share to OneDrive and SharePoint Migration Guide](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide#feedback)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Fileshare-to-ODSP-migration-guide.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
