### ISSUE TITLE
File names - expanded support for special characters

### ISSUE THREAD

**Issue by asepdf** [MicrosoftDocs/OfficeDocs-SharePoint#141]
File names with leading dots are still not accepted when creating a wiki page or documents via OOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4a4e12-f4ab-7c6b-54a4-16d159bb1da5
* Version Independent ID: 158e3039-1567-d5a0-28ef-958e4876b351
* Content: [New and improved features in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@asepdf Are you asking for any content change in this article? I was able to create a Word document in OOS with a leading period. Can you give some detail on how you tested?

**Comment by asepdf** [comment]
Our testing team is creating wiki files with leading dots at the **end** of the file name. Just want to confirm if accepted leading dots should be from the start or middle of the filename?

**Comment by tseward** [comment]
It looks like Pages (wiki or Publishing) do not support the expanded character set of files (including preceding period characters). I've put in a PR to update the article to reflect this limitation.

**Comment by kenwith** [comment]
@asepdf - thanks for reporting issue and thanks @tseward for fix!
