### ISSUE TITLE
Needs clarification: Zip files

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-SharePoint#1410]
Are the individual files within a .zip file indexed as well?
Asked another way: If I do a keyword search for a word that is (ONLY) inside a document which is inside a .zip file, what kind of result would I get, if any?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca49f43-3737-be54-f95f-0e510c892143
* Version Independent ID: 0d3fb4e8-008a-a864-5702-20dc966f3856
* Content: [Default crawled file name extensions and parsed file types in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types)
* Content Source: [SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
I do not believe so, but it is easy to test. You can also look at the crawl log as each item itself would have to be indexed.

**Comment by scanum** [comment]
@sparkitect Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
