### ISSUE TITLE
MiM support SharePoint 2019

### ISSUE THREAD

**Issue by BeVoK** [MicrosoftDocs/OfficeDocs-SharePoint#1416]
Article States that Mim is only supported in SharePoint 2016. Surely it's supported in SharePoint 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fce18fe-f0e9-a06d-1f5a-537d56b2895f
* Version Independent ID: 3198803b-9b3d-a050-c9e7-94cf21130d4c
* Content: [Configure profile synchronization by using SharePoint Active Directory Import in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import#targetText=On%20the%20Manage%20Profile%20Service,option%2C%20and%20then%20click%20OK.)
* Content Source: [SharePoint/SharePointServer/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@BeVoK  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
