### ISSUE TITLE
What happens when Manager leaves?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/OfficeDocs-SharePoint#1417]
When a  manager leaves, will his OneDrive and all the OneDrives of all that have left (and who reported to him) be automatically assigned to the manager's manager?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#feedback)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
No, the process only looks at the manager attribute for the user who has been unlicensed/unsynchronized from AAD. It doesn't do skip level checks.

**Comment by scanum** [comment]
@SB-o-matic Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you
