### ISSUE TITLE
Tags & Notes feature retired

### ISSUE THREAD

**Issue by toskr** [MicrosoftDocs/OfficeDocs-SharePoint#1418]
Apart from the features mentioned, Tags & Notes are also deprecated/removed, as decribed in this SPO article:
https://support.office.com/en-us/article/SharePoint-Online-Tags-Notes-feature-retired-77851BD5-6D5E-42FE-9BF6-D7C17EEB771F
Particularly: you can still add the note board we parts, but they will render completely blank.

The 2016 article actually contains a hint, that this would be removed in 2019:
https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2016
"The Tags and Notes feature is deprecated in SharePoint Server 2016. This means that users can still create new tags and notes and access any existing ones. However, we don't recommend using this feature because it will be removed in the next release."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@toskr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@scanum assign to me.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
