### ISSUE TITLE
Enable-SPOCommSite

### ISSUE THREAD

**Issue by jtlivio** [MicrosoftDocs/OfficeDocs-SharePoint#1419]
Doesn't work at time of this comment
Enable-SPOCommSite -SiteUrl https://contoso.sharepoint.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site](https://docs.microsoft.com/en-us/sharepoint/modern-root-site#feedback)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jtlivio Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by beverin4ever** [comment]
Still doesn't work at time of this comment.
Enable-SPOCommSite -SiteUrl https://contoso.sharepoint.com

**Comment by pyoungberg** [comment]
Not released yet. See https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=46338 for release info.

**Comment by jtlivio** [comment]
> Not released yet. See https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=46338 for release info.

Thanks

**Comment by SLCPS** [comment]
What is the expected time frame for this?

**Comment by dariomws** [comment]
Hi @jtlivio and @SLCPS, thank you for your feedback.

It should be released soon, based on the roadmap in the next days I think:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=46338

**Comment by scanum** [comment]
@jtlivio Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
