### ISSUE TITLE
Content in above documentation page needs to be updated

### ISSUE THREAD

**Issue by ajksingh** [MicrosoftDocs/OfficeDocs-SharePoint#142]
Refer section 'Type the following command to add the Search service application proxy to the default proxy group:'. Here, change:

From: Add-SPServiceApplicationProxyGroupMember -member $ssap -identity " "
To: Add-SPServiceApplicationProxyGroupMember -member $ssap -identity ""

Also, change:
From: You use an empty Identity parameter (" ") to add it to the default group.
To: You use an empty Identity parameter ("") to add it to the default group.

Change description: In current documentation, there is a white-space inside double-quotes. However, there should not be any white-space inside double-quotes for this command to run successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67cc68b-2d40-7d78-9ae5-a71938b6fa78
* Version Independent ID: 52fd8de6-598e-7672-eb34-2fa7a46b0182
* Content: [Upgrade service applications to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@ajksingh thank you for your feedback. 
can you submit this as a pull request instead of a comment please?

**Comment by obhayes** [comment]
Hi i think there is  typo / copy paste error in this article, when you look at the user profile upgrade steps, there is a line that talks about getting the Id for the search service application, but we are in the user profile service?

6.Create the User Profile service application proxy and add it to the default proxy group by completing these actions:

•Type the following command to get the ID for the Search service application and store it as a variable

**Comment by tseward** [comment]
@obhayes let's address this one in #613.

**Comment by obhayes** [comment]
Yes apologies Trevor, I replied inline to a previous comment, thanks.
