### ISSUE TITLE
SharePoint Report 

### ISSUE THREAD

**Issue by kidbui** [MicrosoftDocs/OfficeDocs-SharePoint#1421]
I do not have a "Run report" option in that section when I get to the site usage. Was there another part I need to do to enable that option? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing](https://docs.microsoft.com/en-us/sharepoint/sharing-reports#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@kidbui Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@kidbui this feature is currently rolling out and should be fully available by end of November.

**Comment by kidbui** [comment]
> this feature is currently rolling out and should be fully available by end of November.

Great! Thank you for the update @MikePlumleyMSFT . Definitely looking forward to this feature!

**Comment by WilliamJYoung** [comment]
The functionality provides info on unique internal permissions, as well as external shares,  but seemingly only when I externally share something (otherwise no "Run Report"). As the info is available, can't I get it without externally sharing?

**Comment by zvoltejinylogin** [comment]
Thank you for this Feature!

However I would like to know if it will be available for Admins to run on behalf of a user/users in OneDrive Admin Central or provide a posibility to run via powershell.

**Comment by scanum** [comment]
@kidbui https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1421
