### ISSUE TITLE
"Everyone Except External Users" group being applied to "Private" Team site?

### ISSUE THREAD

**Issue by Caelxn** [MicrosoftDocs/OfficeDocs-SharePoint#1423]
Hi,

This is my first GitHub/MS post, so please bear with me...

So, I am trying to create multiple Team sites where we want to have everyone in the organisation to have R/O access to most of these sites, with Site Members able to Edit and Site Owners with Full Control.

At first, we were using "Public" groups and using the "Everyone Except External Users" (EEEU) group to give permission for other users in the organisation to gain read access to the site. However we then realised that the EEEU group kept being changed to Edit permissions instead of Read by a background task/timer job - which was confirmed in multiple threads, including this one: (https://techcommunity.microsoft.com/t5/SharePoint/Everyone-except-external-users-disappears-form-Group-Visitors/m-p/330066)

To solve this, we put our own "All Staff" AD group in the Site Visitors section of each team site - after making them all "Private" to take out the EEEU group.

This was working fine - until this afternoon (UK Time) where I created 8 Team sites, all Private - and using a PnP script to apply custom content types to new libraries, changing the navigation etc. This script however does not fix the site permissions - so these have to be done manually.

As I was fixing the permissions - the first 2 sites appeared as expected, however the other 6 that were created (all set to "Private" when creating the group in the Exchange interface) all had the EEEU group appearing under Site Members with Edit permissions - which I believe will take priority over the "All Staff - R/O" group.

Does anyone know if this was a change that was made by Microsoft to have EEEU appear even in Private sites? All the documentation I have found thus far points to EEEU not being available if the site isn't public - which is what makes this particularly odd.

If anyone else is having this issue, or has had it in the past and has found a solution - please let me know.

Thanks for reading,

Caelan

**Comment by scanum** [comment]
@Caelxn thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
