### ISSUE TITLE
Access Control Behavior for non-AAD Premium Customers?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SharePoint#1424]
### Would it be possible to elaborate on the expected SharePoint behaviors for non-AAD Premium customers?  

Specifically, since "blocking or limiting access on unmanaged devices relies on Azure AD conditional access policies...", and [Azure AD conditional access is only included with Azure AD Premium](https://azure.microsoft.com/en-us/pricing/details/active-directory/) - what can other customers expect to see in their SharePoint admin pages?  Will that admin page/option be unavailable or disabled.  Or will the options still exist, but silently fail?  

If I'm not mistaken, some of the other 'Access control' settings in SharePoint admin rely on AAD conditional access policies as well:  Network location and blocking apps without modern authentication.  If that's the case, how will those operate/behave for non-AAD Premium customers?  

I have tried experimenting to see what happens, but I only have access to tenants with E5 licenses so I don't think my experience is accurate.  

![image](https://user-images.githubusercontent.com/38665906/66679395-efef6e80-ec22-11e9-89e6-24b09509ae0e.png)
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-access-using-the-new-sharepoint-admin-center)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by asampson68** [comment]
The instructions for the section titled "Block or limit access to a specific SharePoint site or OneDrive" (and the associated graphic) shows zero controls selected for Granting or Denying access under the Access Controls section. I'm trying to reproduce the steps outlined here but there is no option for me to create the policy without some kind of Grant or Block setting configured. How are you able to create the policy without one?

**Comment by dariomws306** [comment]
Hi @TracyGH, thank you for your feedback.

I think that note is clear, you need to have Azure AD Premium to apply this kind of restrictions. Users without AAD Premium shouldn't enable this.

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
