### ISSUE TITLE
Pls confirm how this app connects to on premise SharePoint farm

### ISSUE THREAD

**Issue by ltenison** [MicrosoftDocs/OfficeDocs-SharePoint#143]
The content is somewhat vague about HOW this app connects to a SP Server farm.  SP 2016 is mentioned, can the app also connect to SP 2013?  What network changes are required to support this app from a farm?  What certs are required installed on each device?  What other on premises changes are required to support this app?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42bcdeb-a2a5-e6f1-4779-d7d5b837db1e
* Version Independent ID: 2d2bc902-f138-621f-3fc2-1de76bbe3f22
* Content: [Supporting the SharePoint mobile apps online and on-premises](https://docs.microsoft.com/en-us/sharepoint/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises)
* Content Source: [SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
@ltenison thanks so much for your feedback. I've updated the article to remove to be more clear that it doesn't only apply to 2016. The app connects to 2013, as well.

**Comment by tseward** [comment]
@ltenison The app connects to SharePoint like any web browser would, through HTTPS calls. As long as you expose your Web Application(s) via HTTPS to the Internet and use one of the supported authentication mechanisms with SharePoint, that's all that will be required. No certificates need to be installed on user devices.

**Comment by kenwith** [comment]
Thanks for fix and clearity and thanks @ltenison for reporting and making the docs better.
