### ISSUE TITLE
Missing Delve Enable/Disable Admin Options

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SharePoint#1432]
### Per the following documentation, I should find options to enable/disable Delve within my dev tenant.  I did confirm that my user has an appropriate license assigned (E5).
![image](https://user-images.githubusercontent.com/38665906/66781226-950a8100-ee87-11e9-9c24-dbb06a16b72e.png)
### But I do not appear to have those administrative options available within my tenant.
![image](https://user-images.githubusercontent.com/38665906/66781385-f7638180-ee87-11e9-8acb-f451d939f120.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21ad738-c2a1-ef1f-d745-eebe907311ac
* Version Independent ID: e931c7e1-fdb4-414b-986d-d7755fc797c4
* Content: [Office Delve for Office 365 admins](https://docs.microsoft.com/en-us/sharepoint/delve-for-office-365-admins#control-access-to-delve-and-related-features)
* Content Source: [SharePoint/SharePointOnline/delve-for-office-365-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delve-for-office-365-admins.md)
* Service: **sharepoint-online**
* GitHub Login: @gretel
* Microsoft Alias: **gretel**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@TracyGH In the SharePoint Admin center, click Settings on the left hand nav, then there is a small classic settings link in the main pane. This is what the article is describing.

**Comment by TracyGH** [comment]
Documenting my misunderstanding, in case it helps out someone else.

### It's not this one, which shows 'some' classic menu items in the modern admin page.
![image](https://user-images.githubusercontent.com/38665906/67045855-f29b0980-f0e3-11e9-8e88-b7a7f25ca53f.png)
### It's this one, which opens the settings menu from the classic admin page.
![image](https://user-images.githubusercontent.com/38665906/67045771-c8e1e280-f0e3-11e9-83d9-b1dfc029d7e7.png)
