### ISSUE TITLE
dctmindexconn.exe installer doesn't register the Set-SPEnterpriseSearchDCTMConnectorConfig command correctly in SharePoint 2016

### ISSUE THREAD

**Issue by toskr** [MicrosoftDocs/OfficeDocs-SharePoint#1434]
It appears that the installer for the connector hasn't been updated to work with SharePoint 2016 as good as in SharePoint 2013.

In SharePoint 2016 you may get an error message saying that the Set-SPEnterpriseSearchDCTMConnectorConfig command is not recognized. 

You may need to copy the DCTMCmdlet.XML file
from
C:\Program Files\Common Files\microsoft shared\Web Server Extensions\15\CONFIG\POWERSHELL\Registration
to
C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\CONFIG\POWERSHELL\Registration

And restart SharePoint Management Shell. 

The Set-SPEnterpriseSearchDCTMConnectorConfig command should now be recognized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9336ec76-919d-b71e-8f35-a40254bd2b81
* Version Independent ID: 93043a19-fb48-5548-00fb-cfc508c42a2d
* Content: [Configure and use the Documentum connector in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/configure-and-use-the-documentum-connector)
* Content Source: [SharePoint/SharePointServer/search/configure-and-use-the-documentum-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/configure-and-use-the-documentum-connector.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@toskr have you opened a support case with Microsoft? This should probably be logged as a product bug.

**Comment by scanum** [comment]
@toskr thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
