### ISSUE TITLE
Effect on Teams and Groups

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/OfficeDocs-SharePoint#1435]
How (if at all) does changing this setting affect when users create new Groups or Teams and those products then create a corresponding SharePoint site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de79eee-3a56-4611-7654-0be9c9ccdf51
* Version Independent ID: 9c60ba38-755e-b1a9-eef2-c91bd600840e
* Content: [Let users create modern site pages](https://docs.microsoft.com/en-us/sharepoint/let-users-create-modern-site-pages)
* Content Source: [SharePoint/SharePointOnline/let-users-create-modern-site-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-create-modern-site-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@NickDorak Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@NickDorak Thanks for reaching out.  Which setting are you referring to?  Just need some clarification so I can help answer your question.

**Comment by NickDorak** [comment]
> @NickDorak Thanks for reaching out. Which setting are you referring to? Just need some clarification so I can help answer your question.

"Prevent users from creating site pages"

**Comment by lindspea** [comment]
Thanks @NickDorak. Did you see this article? Maybe it gives some more clarity?  Let me know. https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6

**Comment by NickDorak** [comment]
> Thanks @NickDorak. Did you see this article? Maybe it gives some more clarity? Let me know. https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6

I think you posted the wrong link, as it has nothing to do with the topic.

**Comment by lindspea** [comment]
> Thanks @NickDorak. Did you see this article? Maybe it gives some more clarity? Let me know. https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6
> 
> I think you posted the wrong link, as it has nothing to do with the topic.

Oops, let me double check that.

**Comment by lindspea** [comment]
@LoreenLa could you provide some clarity please?

**Comment by irshadnazly** [comment]
I have tried the scenario "Allow users to create site pages in specific site collection when site pages creation is disabled in SharePoint Admin center" and it does not allow to create site page even though the feature is enabled in site collection.

**Comment by LoreenLa** [comment]
Adding @Kaarin Shumate<mailto:kaarins@microsoft.com> to see if she can help with this question.

**Comment by kaarins** [comment]
I'm reaching out to the team to get answers to these questions.

**Comment by lindspea** [comment]
@kaarins any update on this yet?

**Comment by scanum** [comment]
@kaarins any update on this? Thanks!

**Comment by kaarins** [comment]
Thanks for the reminder. I will reach out again in the new year.

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by lindspea** [comment]
@kaarins

**Comment by kaarins** [comment]
Team sites and group sites can still be created. They are independent settings.
 
Even if the Site pages feature is activated at the site level, it does not supersede the organization-level setting.

When you disable the creation of modern pages, it hides most entry points for creating pages, regardless of site type. The creation of new modern pages isn't completely blocked. Users can still create new pages from the "New" menu on an existing site page and from the News webpart within site pages.
