### ISSUE TITLE
Please indicate which setting no longer works in the new shared experience.

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SharePoint#1437]
The following note appears at the bottom of this page.  Can you elaborate on exactly what 'setting no longer works for the new shared experience'?  

![image](https://user-images.githubusercontent.com/38665906/66947554-f0637d00-f007-11e9-9b23-4952df8dd1ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b523280d-569c-bad0-209f-b428837f3e3b
* Version Independent ID: 0a11f32d-874b-2eba-32fb-52b3fc7e78f3
* Content: [Turn on external sharing notifications for OneDrive](https://docs.microsoft.com/en-us/onedrive/turn-on-external-sharing-notifications)
* Content Source: [OneDrive/turn-on-external-sharing-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/turn-on-external-sharing-notifications.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TracyGH thanks for reaching out.  From what I can see it looks like the note is referring to the screenshot where it says "an anonymous access link is created or changed."

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
