### ISSUE TITLE
ADMX Files

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-SharePoint#1438]
Can you check / provide more info on Point 2 right at the top of the page?
"Browse to %localappdata%\Microsoft\OneDrive\BuildNumber\adm, to the subfolder for your language as necessary.
(Where BuildNumber is the number displayed in sync client settings on the About tab.) "
As the BuildNumber folder doesn't seem to exist based on all the installations of OneDrive clients I've tried (per-user, system-wide, production latest... the one O365 installs vs the Win10 app)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by mattsmacblog** [comment]
found them...

**Comment by tommurphy288** [comment]
Where?

**Comment by mattsmacblog** [comment]
> Where?
64bit Client
C:\Program Files\Microsoft OneDrive\<version-number>\adm

**Comment by HansBrender** [comment]
where is the issue? The client will update this automatically. If you want to deploy this via Intune or MEM to your clients, you have to install it on a seperate device to get the newest admx/adml files automatically. There is **no seperate download** available for the admx/adml files.

**Comment by tommurphy288** [comment]
my OD on win11 had been installed for a good few weeks and no auto update. my win10 VM using for testing has been around for 2 months and no new version or ADMs on the system, fully windows updated. 

Can we just get the documentation to state if you don't have the ADMs presence please install OD from Microsoft and you will then have the files.

**Comment by HansBrender** [comment]
No: You should read: https://docs.microsoft.com/en-us/onedrive/use-group-policy

_Install the OneDrive sync app for Windows. (To see which builds are releasing and download builds, go to the release notes.) Installing the sync app downloads the .adml and .admx files._

**Comment by tommurphy288** [comment]
if it comes with the system its already installed, so why would someone re-install it. that's counterintuitive.
