### ISSUE TITLE
Does this setting apply to both OneDrive & SharePoint?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SharePoint#1442]
Does this setting apply to both OneDrive & SharePoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kaarins could you perhaps help answer this please?

**Comment by lindspea** [comment]
@TracyGH From my understanding it applies to OneDrive only. Let me know if you need any further help.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by lindspea** [comment]
@scanum can be closed thanks.

**Comment by danmyhre** [comment]
This actually does apply to both SharePoint online sites as well as OneDrive for business.  I would recommend that this page be updated to indicate that.

**Comment by lindspea** [comment]
@kaarins

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
