### ISSUE TITLE
Does this setting apply to both OneDrive and SharePoint?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/OfficeDocs-SharePoint#1443]
Does this setting apply to both OneDrive and SharePoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TracyGH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kaarins

**Comment by lindspea** [comment]
@TracyGH thanks for reaching out. From my understanding it only applies to OneDrive.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
