### ISSUE TITLE
Inconsistencies in PowerShell commands

### ISSUE THREAD

**Issue by LL-chill** [MicrosoftDocs/OfficeDocs-SharePoint#1444]
The documentation here states `Start-SPOSiteContentRename` but the linked page states `Start-SPOSiteRename`

It also makes double mention of the switch `-ValidationOnly` which is not present on the linked page.

It is also quite disappointing that this breaks the Teams link.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview)](https://docs.microsoft.com/en-au/sharepoint/change-site-address#change-a-site-address-in-the-new-sharepoint-admin-center)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@LL-chill Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by shemp321** [comment]
There is also an issue when you rename a URL, let it finish, and then retry to go back to the old URL such as in the case of wanting to change the case of the URL.  The change seems to work in the site itself but in the admin console you get an error that states "couldn't update site.  Try changing this site individually"  The URL of the site stays what it was before trying the change.   For example try changing /sites/siteABC to /sites/siteabc1 (works), then try changing it back to /sites/siteabc (works except the URL in the admin console fails to change).

**Comment by lindspea** [comment]
@shemp321 the site rename cmdlet creates a shell redirect site at the old URL so users don't have to memorize the new URL. This does mean that if you want to reuse the old URL, you must first delete the "site" that currently resides at the old URL, first.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
