### ISSUE TITLE
Get a Secure Channel SSL certificate

### ISSUE THREAD

**Issue by martinaffectoericsson** [MicrosoftDocs/OfficeDocs-SharePoint#1445]
Get a Secure Channel SSL wildcard or SAN (Subject Alternative Name) certificate for your on-premises public domain from a well-known certificate authority, such as DigiCert, VeriSign, Thawte, or GeoTrust.

Please clarify: are the CA:s listed above the only supported?
Thanks
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a1ac50-df4e-a3a1-9af4-c6517af605dc
* Version Independent ID: 1de86435-cc21-b50e-0d2c-a646f24d2fa9
* Content: [Plan connectivity from Office 365 to SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/hybrid/plan-connectivity-from-office-365-to-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/plan-connectivity-from-office-365-to-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/plan-connectivity-from-office-365-to-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
No, that is why it says "such as".

**Comment by martinaffectoericsson** [comment]
Great! Thanks for the clarification.
