### ISSUE TITLE
SharePoint Online

### ISSUE THREAD

**Issue by freemstr** [MicrosoftDocs/OfficeDocs-SharePoint#1446]
Could you please point me to a version of this document for SharePoint Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e19898d-6400-f2ad-63aa-825469026e99
* Version Independent ID: 79bc10e2-1ee3-00aa-82b2-ffe0bc14914e
* Content: [Overview of the search schema in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/search-schema-overview#feedback)
* Content Source: [SharePoint/SharePointServer/search/search-schema-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/search-schema-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@freemstr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@freemstr Thank you for reaching out.  Is this perhaps what you're looking for? https://docs.microsoft.com/sharepoint/manage-search-schema

**Comment by freemstr** [comment]
Thank you very much.
It seems to be as close as it gets for the online version.
Working with MS support on the gap between the two document sets and implementation details.
