### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by siegardj** [MicrosoftDocs/OfficeDocs-SharePoint#1447]
I'd just like some clarifications on this.

"Do not enable this setting for libraries with more than 5,000 files or folders. Do not enable this setting for the same library to more than 1,000 devices."

Does this mean that if I apply the GPO to sync a library to more than 1,000 devices things will stop working or just that no more than 1,000 users can not auto sync the same library at the same time? 

Also is there any changes expected to the 5,000 folder limit? 

We'd like to start using document libraries in place of traditional files shares as much as possible. We thought the sync w/ files on demand would be the solution but between the two limits listed above and the 8 hour delay for initial sync I don't see how the OneDrive sync for document libraries is feasible.

**Comment by scanum** [comment]
@siegardj Please link the document you are referring to. Thanks

**Comment by NickBryant1** [comment]
I was going to ask the same thing. @scanum - I found the limitation documented at https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutoMountTeamSites

Similarly to @siegardj, we are planning to use SharePoint Online to replace on-prem SMB shares and were hoping to mount them to users via the OneDrive Sync Client and Files On Demand

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
