### ISSUE TITLE
 SharePoint Online custom scripts allowed/enabled

### ISSUE THREAD

**Issue by tyreeballard** [MicrosoftDocs/OfficeDocs-SharePoint#1452]
I still cannot upload .aspx or .stp files after enabling custom scripts in the SharePoint admin and at the site level via SharePoint management shell. I also have been waiting over 24hrs for these changes to take affect. Please help!

**Comment by scanum** [comment]
@tyreeballard thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
