### ISSUE TITLE
SharePoint Site URL Rename - Reuse of old URL possible?

### ISSUE THREAD

**Issue by anders-ove** [MicrosoftDocs/OfficeDocs-SharePoint#1453]
Is it possible to release the old URL's (that by default is redirecting to the new URL's) - so that they can be reused?

**Comment by tseward** [comment]
Yes, you can delete the redirect site (which is a special site template name), remove the redirect site from the deleted site list, then create a new site at that URL.

**Comment by anders-ove** [comment]
Great @tseward, thank you for the information.
