### ISSUE TITLE
Optimizing SharePoint Performance before setting root site clarification? 

### ISSUE THREAD

**Issue by DS2019** [MicrosoftDocs/OfficeDocs-SharePoint#1454]
When it says:  Important
Before you launch an intranet landing page at your root site location, we strongly encourage you to review the guidance about optimizing SharePoint performance the link given goes to a page with over 20 links. I read the first 5, and they seem to be all kind of general SP Performance guidelines, most better suited to on-premise rather than online. I didn't see anything that seemed especially to refer to optimizations required before setting a root site. 
Rather than point us to a general page with a bunch of links, could you please clarify for us just what we should take into account about setting a root site and the optimization that should be done beforehand?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site](https://docs.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@DS2019  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @DS2019, thank you for your feedback.

My apologies but we cannot provide that as there are several best practices to consider to optimize a portal and all of them have their detailed explanation.
I have verified the links and all of them are for SharePoint Online/Office 365. Also you have a section "Optimize your Performance" with several links.

Hope you understand. Thank you!

**Comment by DS2019** [comment]
Thanks, @dariomws306 - but it seems the information I had posted about has totally changed from a bunch of disparate links to  a new link on "review the guidance about launching healthy portals," and there are helpful links now in a table: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/portal-health.md 
From looking at the history, the changes were made in Nov 2019 and Dec 2019. So, what I reported on has been fixed, and it has been provided.

**Comment by SLCPS** [comment]
Wow.

**Comment by scanum** [comment]
@DS2019 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
