### ISSUE TITLE
One Drive Silent sign with windows credentials does not work with OneDrive 

### ISSUE THREAD

**Issue by geovan897** [MicrosoftDocs/OfficeDocs-SharePoint#1456]
Current Build on test device of One Driver Version  19.152.0927.0012
Current OS Version: 1903  build: 18362.418
Device is Azure AD joined 

Current Settings Applied below 

Silently sign in user to the OneDrive Sync Client with their Windows Credentials  - enabled 
Silently move Windows known folder to OneDrive - enabled with tenant id 
Use OneDrive Files On-Demand
Prevent users from changing the location of their OneDrive folder 
Prevent users from redirecting their Windows known folders to OneDrive 

Assignments applied in the context of devices
Even trying to manually login triggers an error 

There was a problem signing you in. 
Login was either interrupted or unsuccessful. Please try logging in again. (Error Code: 0x8004deb4)

Microsoft's resolution https://support.office.com/en-us/article/error-code-0x8004deb4-when-signing-in-to-onedrive-for-business-e8a8d97c-a87e-4dda-a67e-bae4fef05dcb

Even after manually adding this key via powershell  auto sign in does not work

**Comment by scanum** [comment]
@geovan897 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
