### ISSUE TITLE
Suggestion for Wiki pages in modern page experience

### ISSUE THREAD

**Issue by mikewaretena** [MicrosoftDocs/OfficeDocs-SharePoint#1457]
Under wiki pages, readers could also be advised to [Use Markdown web part](https://support.office.com/en-us/article/use-the-markdown-web-part-6d73c06d-2877-4bc9-988b-f2896016c50b) as this provides formatting capabilities similar to that of what wiki pages used to provide back in the day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e6d056-3733-6925-4c58-40eaa01a6580
* Version Independent ID: 7802375b-467b-53e0-4e9d-ca990a8b2c54
* Content: [Moving from Publishing sites to Communication sites](https://docs.microsoft.com/en-us/sharepoint/publishing-sites-classic-to-modern-experience#pages)
* Content Source: [SharePoint/SharePointOnline/publishing-sites-classic-to-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/publishing-sites-classic-to-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@mikewaretena  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mikewaretena thanks for your feedback, created a pr to propose adding this to the article.
Thank you

**Comment by get-itips** [comment]
@scanum pr was merged, this thread can be closed now. Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
