### ISSUE TITLE
"View Only" permission level and Office Online Server

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#1458]
Is there any difference in the behaviour of the "View Only" permission level between Office Web Apps 2013 and Online Server 2016?
I've seen a scenario when a user having that permission in SharePoint 2013 cannot download a file from SharePoint and cannot print in Office Web Apps 2013; the same user in SharePoint 2016 cannot download a file from SharePoint, but can print in Office Online Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels#feedback)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Product: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@LuigiBruno  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
Was IRM implemented in 2013 on the library containing the doc?

**Comment by get-itips** [comment]
Hello @LuigiBruno have you seen @tseward question regarding IRM?
Thanks

**Comment by LuigiBruno** [comment]
> Was IRM implemented in 2013 on the library containing the doc?

I don't know, since it is a problem that has been reported to me: I'll ask for more detail.
Thank you @tseward.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
