### ISSUE TITLE
Why didn't you include timestamps in the external users report?

### ISSUE THREAD

**Issue by USAFin0365** [MicrosoftDocs/OfficeDocs-SharePoint#1462]
I think this is a great start but I'd like to present a use case. I work in the Financial Industry and we really want to use the capabilities of SharePoint to share content externally with clients. That said, we are heavily regulated by FINRA & the SEC. When I saw this new feature was released I was excited to see what was included. When I found the external users report, I was certain I'd find what I needed there.

I was baffled when I pulled the report and there were no dates or timestamps for the activity. Not only that but no where in the report or documentation I've seen so far does it explain what period of time these reports cover.

Improvements I'd like to see.

- Timestamps (with data & time) for each user, each time a file is accessed (not only modified).
- Something that shows, explains, or allows you to tweak the duration of time the report is covering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing](https://docs.microsoft.com/en-us/sharepoint/sharing-reports#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
As this is a repo for reporting issues with documents rather than features, I would suggest posting this on Uservoice if you can't find a similar result - https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration.

**Comment by scanum** [comment]
@USAFin0365 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
