### ISSUE TITLE
Doesn't work for Modern experience

### ISSUE THREAD

**Issue by hlsidey** [MicrosoftDocs/OfficeDocs-SharePoint#1463]
These directions are not relevant if you aren't on the classic experience. I did find the Site Usage page, but it doesn't let me change the popular items timeline and wont' show me all document views, only top 20. So I have no option to see how many times a page has been viewed unless it's a top 20 in the last 7 days. Could we get directions/details for the modern view 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb55f79c-8118-474e-175b-f8cfb0737bc4
* Version Independent ID: 43071ae4-5da9-056b-9bd9-333fb100c8ef
* Content: [View Popularity Trends and Most Popular Items](https://docs.microsoft.com/en-us/sharepoint/view-popularity-trends-and-most-popular-items?redirectSourcePath=%252fen-us%252farticle%252fView-Popularity-Trends-and-Most-Popular-Items-a522cc35-4e63-49da-9968-85c588878932#feedback)
* Content Source: [SharePoint/SharePointOnline/view-popularity-trends-and-most-popular-items.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-popularity-trends-and-most-popular-items.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
If you look near the top of the article there is a Note section which provides a link for more information on the modern experience way of doing this.

**Comment by scanum** [comment]
@hlsidey Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
