### ISSUE TITLE
Managed property of type URL type

### ISSUE THREAD

**Issue by bolatovumar** [MicrosoftDocs/OfficeDocs-SharePoint#1464]
What should be `SiteColumnNameOWSURLH` is spelled as `SiteColumnNameOWSURHL`. Notice the ending there. Should be **URLH** but it's **URHL** in docs. A junior dev on my team read the docs and attempted to follow this precisely and was confused why his code wasn't working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a04f2619-a855-4d1b-3d32-de0f0a1bcb7e
* Version Independent ID: 0b76c5be-c85c-1e18-d53c-1585ba3e4549
* Content: [Automatically created managed properties in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/automatically-created-managed-properties-in-sharepoint#feedback)
* Content Source: [SharePoint/SharePointServer/technical-reference/automatically-created-managed-properties-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/automatically-created-managed-properties-in-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@bolatovumar  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bolatovumar** [comment]
@scanum fix looks good to me, nothing else to say here.
