### ISSUE TITLE
How to stop SPMT from overwriting duplicate files in the SP Online target

### ISSUE THREAD

**Issue by laurence73** [MicrosoftDocs/OfficeDocs-SharePoint#1465]
Hi - is there any way to get the SharePoint Migration Tool to rename files if a duplicate already exists in the target library?

**Comment by scanum** [comment]
@laurence73 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
