### ISSUE TITLE
Content Database Limits - wrong description on limit

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#147]
[Enter feedback here]
The description of the content database limitations, is from upload size:
"The default file size is 2047 MB, which can be increased to a maximum of 10 GB. Multiple site collections can share a single content database. Each site collection needs to be fully stored in a single content database. "

This should be corrected. 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d1a46c-4a3b-f99d-cca8-326b36235b1d
* Version Independent ID: d99a6050-b1af-afa2-8948-b1bba2ea7398
* Content: [Software boundaries and limits for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@danone1985 thanks for  your feedback. What should the value be ?? and has this been tested?

**Comment by kenwith** [comment]
Thanks for feedback @danone1985 and fix @tseward !

**Comment by gnnsekhar** [comment]
As per MSDN, It is suggested that for ease of backup and restore that individual site collections within a content database be limited to 100 GB.
if site collection storage consumption is more than that, then how to restrict the site collection to use new content database rather than old existing one?
