### ISSUE TITLE
Azure AD - Conditional Access Policy

### ISSUE THREAD

**Issue by Beritknight** [MicrosoftDocs/OfficeDocs-SharePoint#1470]
There is a note in this article that this setting does not work with Azure AD domains, suggesting Conditional Access instead.
I've read the page at https://docs.microsoft.com/en-us/onedrive/enable-conditional-access
which refers to https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices
for an outline how to set a conditional access policy to allow or deny a thing based on whether the computer is compliant or not. That's good as far as it goes. What I can't find is any documentation that explains how to define syncing a document library in the OneDrive sync client on a PC as the thing you're trying to control.

Is there anything anywhere that covers creating a CA policy that reproduces the behaviour of the "Allow syncing only on PCs joined to specific domains" setting documented on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains#feedback)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Beritknight Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Beritknight, thank you for your feedback.

Have you verified these articles?
https://docs.microsoft.com/azure/active-directory/conditional-access/require-managed-devices
https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices

**Comment by scanum** [comment]
@Beritknight  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by PhilippZumdohme** [comment]
Hello @scanum
On behalf of the original poster, I'd like to reopen this issue.
The current situation is, that a customer wants to shift from legacy OnPremises AD Enviroments to a clean new EASE Golden/Red-Forest construct.
In the new construct all clients will be autopilot-enrolled via Intune and only Azure AD Joined, not Hybrid joined, as they should have never contact to the Domain Controller.
The customer wants to secure OneDrive sync to his local legacy domains (7 in total) and to his newly added Azure AD Joined Devices.
With the current setup we do not see the capability to restrict access to both, we can realize either, but not both. Conditional Access does not offer us the capability to restrict based on local domain and the OneDrive Sync Restrictions do not allow Azure AD Joined devices to bypass this setting.
Can this be done in anyway?

**Comment by dariomws** [comment]
Hi @PhilippZumdohme, thank you for your comment.

Docs.microsoft.com is available to improve Microsoft documentation. I don't have the information that you are requesting, so I cannot provide it.
I think the right place to get this kind of help is support, consulting services, or even https://techcommunity.microsoft.com/.

**Comment by PhilippZumdohme** [comment]
Hello @dariomws 
No Problem, but then I would advise not to add the passus about Azure AD Joined or state, that this will currently block all Azure AD Joined devices from synchronizing, as they have no local Domain GUID that can be added to the allowed list.
It is confusing and leads people into the wrong direction.

**Comment by dariomws** [comment]
If you have devices which are only Azure AD joined, you should use Conditional Access. I understand that the note at the end doesn't tell us that we can block devices to sync OneDrive based on their Azure AD Domain.

You can use Conditional Access policies to ensure syncing is only done with compliant devices:
https://docs.microsoft.com/onedrive/enable-conditional-access

**Comment by SpamsRevenge** [comment]
Hi Dariomws,

That link that you provided does not actually contain information on how to configure the Conditional Access for OneDrive. 

I have seen this document but it doesn't say how to enable - it talks about enable ADAL which is type of Authentication. I have never found a way to specify the OneDrive Sync Clients to be controlled by Conditional Access Polices- only controls for all of Office products or SharePoint Sites permissions.

Thanks
