### ISSUE TITLE
Could be better

### ISSUE THREAD

**Issue by kmckeowncasto** [MicrosoftDocs/OfficeDocs-SharePoint#1471]
Why is this even released yet if it is going to break functionality in Teams? Most people probably want to rename a SharePoint site so they can either reclaim a name to use for a new site/group, or update a name based on some requirement from a site owner or department head. The fact that this breaks things in Teams, makes it pretty much useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview)](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by simpkinspete** [comment]
...I wish I would have realized this before updating the majority of our sites

**Comment by mr-koelkast** [comment]
One of the effects with changing a site adres is published on the site. I have renamed 1 site, my Team file tab isn't connected anymore. I want to rollback, but it can't! Help!
[https://docs.microsoft.com/nl-nl/sharepoint/change-site-address]
Teams (for Office 365 group-connected sites)
After the site address is changed, users won't be able to view the team's files within the Teams app, but they can access them from Teams by selecting Open in SharePoint.

**Comment by AdwoodMicrosoft** [comment]
Hello all. The Files Tab ceasing to work in teams is a known regression. Teams is working to address.

**Comment by scanum** [comment]
@kmckeowncasto  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@kmckeowncasto 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Todd312** [comment]
@scanum
Any progress or update on this? I am about to roll out a new Intranet within my Business however I need to rename the URL before sending it out to everyone. Teams is integral and I cant roll it out if it will break the files tab
