### ISSUE TITLE
SPOTenantSyncClientRestriction

### ISSUE THREAD

**Issue by BintMi** [MicrosoftDocs/OfficeDocs-SharePoint#1474]
Since it was not mentioned here, I would like to know if the B2B sync also works if we have restrict non-domain joined machines from syncing. Following link as a reference - https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenantsyncclientrestriction?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync#feedback)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BintMi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @BintMi, thank you for your feedback.

I think you have read it, but just in case this is the way to block external sync:
https://docs.microsoft.com/onedrive/b2b-sync#policy-setting-to-prevent-b2b-sync

I understand that B2B sync won't work if you set restrict non-domain joined machines from syncing:
"Regardless whether a computer is managed by a device management solution, a sync relationship will not be established unless they are joined to a domain in the Safe Recipient List."
Any type of sync won't work.

**Comment by scanum** [comment]
@BintMi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
