### ISSUE TITLE
Onedrive move known folders

### ISSUE THREAD

**Issue by MiweDK** [MicrosoftDocs/OfficeDocs-SharePoint#1475]
When using the move known folder gpo, it moves the files to onedrive but translates everything into danish even though the operating system is running either US/Ger/GB/SWE which is a huge annoyance since desktop is suddenly called Skrivebord when opening explorer.

**Comment by scanum** [comment]
@MiweDK  thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
