### ISSUE TITLE
Broken links in the Communication and Training Guide

### ISSUE THREAD

**Issue by lemon-at-ocas** [MicrosoftDocs/OfficeDocs-SharePoint#1476]
The linked Communication and Training guide makes references to download kits that have email templates to help with launch.  The links are broken and land on an error page. Can that document be updated with working links please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise#feedback)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@lemon-at-ocas Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@lemon-at-ocas Thank you for reaching out. The link seems to be working fine my side. Please let me know if you have anymore questions.

**Comment by Reeced40** [comment]
@kaarins

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by kaarins** [comment]
Thank you. I have passed along this feedback to the owner of the linked guide. We will either update the guide or update the link within this article to point to a different resource.
