### ISSUE TITLE
Enable Files On-Demand Is Missing From This Page

### ISSUE THREAD

**Issue by SCCMAdmin** [MicrosoftDocs/OfficeDocs-SharePoint#1478]
Considering this is the Use Group Policy to configure OneDrive web page, I can't see any reference to Enable Files On-Demand setting. This is discussed here https://techcommunity.microsoft.com/t5/Microsoft-OneDrive-Blog/OneDrive-Files-On-Demand-For-The-Enterprise/ba-p/117234 under heading Enable Files On-Demand which shows the computer GPO to enable this. This and other settings on that web page should all be summarised here as the one stop shop for all OneDrive Group Policy.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy?redirectSourcePath=%252fen-us%252farticle%252fUse-Group-Policy-to-control-OneDrive-sync-client-settings-0ecb2cf5-8882-42b3-a6e9-be6bda30899c#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SCCMAdmin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @SCCMAdmin how are you ? 👍 

Maybe I am misunderstanding you, but the content under https://docs.microsoft.com/en-us/onedrive/use-group-policy#FilesOnDemandEnabled isn't what you are looking for?

Thanks

**Comment by SCCMAdmin** [comment]
Hi @get-itips well thanks. Happy New Year!

It has been some time since my post (31st Oct 2019). I'm having to refresh myself as to what I meant exactly and holiday brain doesn't help either. :)

Firstly, thanks for pointing that out sub link. The information for a Registry setting is there. I also note the AGPM template view is shown in an image for this setting, Excellent. 

The web page has been recently updated and I'm not sure if this computer settings section was something added after my post or not.

My only final comment would be to call the paragraph "Enable OneDrive Files On-Demand" as right now you can search the web page and only find this phrase once where Enable OneDrive Files On-Demand is not being discussed. No one will search for "Use OneDrive Files On-Demand" but I think many will search for "Enable OneDrive Files On-Demand".  As at [https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/onedrive-files-on-demand-for-the-enterprise/ba-p/117234](url) there is a heading with the word Enable in it which seems to stand out more.

I will leave it to you what to decide ultimately, but that's my suggestion. Thanks and cheers.

**Comment by get-itips** [comment]
Hello @SCCMAdmin Thanks for your answer, I created a pr to propose changing from _use_ to _enable_.
Thank you

**Comment by get-itips** [comment]
@scanum Manuela, PR was not accepted by the author, please close this thread now. Thanks

**Comment by SCCMAdmin** [comment]
Bummer. Thanks for trying @get-itips .
Fianlly, for future reference what does PR stand for?

**Comment by get-itips** [comment]
> Bummer. Thanks for trying @get-itips .
> Fianlly, for future reference what does PR stand for?

Pull Request, the way we have to propose changes to articles. 👍

**Comment by get-itips** [comment]
@scanum Please kindly close this one. Thanks

**Comment by scanum** [comment]
@SCCMAdmin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
