### ISSUE TITLE
KFM with Blocked File Types

### ISSUE THREAD

**Issue by Naz9mm** [MicrosoftDocs/OfficeDocs-SharePoint#1480]
When/how long does this take to apply? i am testing this with Known Folder Move and after adding ISO to the block list i can still add new iso to my desktop which syncs up to OneDrive 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types#feedback)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Naz9mm Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Naz9mm , I tried in my lab and took +- 1 hour to apply.
I did not recognize a need to edit the article.
Hope this information helps you.

**Comment by get-itips** [comment]
Hello @scanum kindly please close this thread. thanks

**Comment by scanum** [comment]
@Naz9mm Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
