### ISSUE TITLE
Retention with SharePoint Online

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-SharePoint#1481]
I can see this document is not valid for SharePoint Online but this feature is still available in SharePoint Online. Could you please let me know what's Microsoft's direction on using this feature in SharePoint Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2d05a9-ef09-ce9f-d7b8-80535608f3d9
* Version Independent ID: 4c5ddcca-451f-5276-5f85-7663b54bc7d5
* Content: [Plan for information management policy in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/information-management-policy-planning)
* Content Source: [SharePoint/SharePointServer/governance/information-management-policy-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/information-management-policy-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ravick4u Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ravick4u 
You should start here https://docs.microsoft.com/en-us/microsoft-365/compliance/ for Sharepoint/Microsoft 365 Information Protection

**Comment by ravick4u** [comment]
Thanks, @get-itips for the response

The link you shared with me explains new features in O365 but it doesn't have all features available which describes here. For e.g. Deleting all previous versions of the item, Site Policies.

What I would like to understand is it ok to use these features in O365 because there no one to one mapping with this to new O365 features.

**Comment by get-itips** [comment]
Hello @kaarins can you help us here ? Thanks

**Comment by get-itips** [comment]
Hello @kaarins can you guide us here ? Thanks

**Comment by scanum** [comment]
@kaarins Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by scanum** [comment]
@kaarins Following up on this, any updates? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr can you help?

**Comment by scanum** [comment]
@TroyStarr Any updates on this issue? Thanks!

**Comment by scanum** [comment]
@ravick4u Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
