### ISSUE TITLE
Confirmation command

### ISSUE THREAD

**Issue by iBrooks** [MicrosoftDocs/OfficeDocs-SharePoint#1483]
Hello,

Since it takes 24 hours before you can test whether or not you have succeeded, it would be really nice if you included a command to confirm this setting has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script?redirectSourcePath=%252fen-us%252farticle%252fTurn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f#feedback)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@iBrooks Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @iBrooks I am afraid there is no command to confirm if this setting has taken effect besides testing.
Hope this information helps you.

**Comment by get-itips** [comment]
Hello @scanum please kindly close this one. Thanks

**Comment by scanum** [comment]
@iBrooks Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
