### ISSUE TITLE
Wow, what a limiting and bad design.

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/OfficeDocs-SharePoint#1484]
Ya, it's too bad every tenant doesn't have a GUID. Oh wait.
It's too bad you can't attach custom domains to your tenant. Oh wait.
It's really lucky that companies never merge, acquire, divest or rebrand. Oh wait.

Someone thought this was a good idea. Does that someone still work there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name#feedback)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@boomalator Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by robinwilson16** [comment]
Please make this possible. Surprising it isn't. Don't want to continue using an old company name everywhere but don't really want to set up everything from scratch again including SharePoint sites etc.

**Comment by boomalator** [comment]
Nope. All you can do is create a brand new tenant, transfer all the subscriptions and data.

Mind numbingly stupid, isn’t it?


Mobile: big fingers, little buttons, and don't get me started about autocorrect.

On Nov 9, 2019, at 5:48 AM, Robin Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:


Please make this possible. Surprising it isn't. Don't want to continue using an old company name everywhere but don't really want to set up everything from scratch again including SharePoint sites etc.

**Comment by robinwilson16** [comment]
Yes it's a surprising limitation.
I keep moving between Google and Microsoft for things as both seem to have their issues but neither has the perfect combination of systems (e.g. Google Drive is much more reliable than OneDrive for MS documents but GSuite doesn't allow you to upgrade one user's storage and you must upgrade everyone and spend much more or create a second subscription - such basic restrictions :(

**Comment by awhipwell** [comment]
This is a joke...

**Comment by jeremyBass** [comment]
And why does it have to be the '.sharepoint.com'. Should address all of it at the same time.  We really would like our sharepoint url to be sharepoint.myDomain.com

**Comment by KIKOMAK** [comment]
An other proof that Microsoft hate their customers...

**Comment by jeremyBass** [comment]
oh they love us.  I "gave" them all those, 3-4mil/yr positive recapture, and that complete cover to there exposed private parts they where baring to the world..  and they ghosted me, and gave it to a premiere partner to get credit.  plain ingore all my email and tickets.  I am now losing my kids for it.. next my house.   I approcate the dedication here, and certainly love to help them improve their products so they can better stomp me in the ground faster.  the money from those bug bounties.. would have paid my house off, ensured my kids custody so my son and daughter stayed together and in would have a stable run for a year to produce more products for the market place..   have to say..  full champion of the little man...

**Comment by get-itips** [comment]
Hello @boomalator and all that commented.

This issue system is specifically to address issues in documentation, like typos or missing or wrong information.
In this case, for feature requests, I need to kindly redirect you to [Sharepoint UserVoice](https://sharepoint.uservoice.com/) or [Microsoft 365 Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap)

Hope this information helps you,

**Comment by boomalator** [comment]
So two full months after my comment, Microsoft’s reply is “go tell someone who cares” at a link where no one cares. 

@get-itips Feel free to file a bug or open an issue or call/Skype/email/Jazz/tweet/whatever the right person. Or not. 

It’s a bad design. Responsive, customer driven companies crave customer feedback and build internal systems that get the feedback to the right place. Mediocre companies force customers to go find some other channel. Terrible companies ignore the customers for months or years at a time.

**Comment by boomalator** [comment]
Oh, and the concept that the “issues system” is so that customers can fix typos instead of the publisher having good writing and competent  copy editors is beyond sad.

**Comment by robinwilson16** [comment]
Could someone not move the issue to the correct location?
I have logged issues in the past in .NET Core and bugs I logged from 2018 are still in the product as of today so it is rather disappointing, especially when we have to do all the running around posting issues in different places carefully including steps to replicate the issues and all that happens is our issues are closed and forgotten about.
It is confusing having so many different platforms on which to log queries and issues, why not unify on Github since Microsoft purchased it?

**Comment by get-itips** [comment]
> So two full months after my comment, Microsoft’s reply is “go tell someone who cares” at a link where no one cares.
> 
> @get-itips Feel free to file a bug or open an issue or call/Skype/email/Jazz/tweet/whatever the right person. Or not.
> 
> It’s a bad design. Responsive, customer driven companies crave customer feedback and build internal systems that get the feedback to the right place. Mediocre companies force customers to go find some other channel. Terrible companies ignore the customers for months or years at a time.

@boomalator I can understand your frustration on the delay getting an answer, personally, as a collaborator in this repo, I was assigned this issue two days ago and my task is limited to documentation issues, when I can not directly solve something because is not a documentation issue, I can give people other options, for example User Voice is a resource where **your request can reach the product team**, I am sorry it does not fulfill your needs in this case.
cc @scanum

**Comment by Krytical13** [comment]
@get-itips

The real problem is that you and the others who contribute here on Github actually respond.

On UserVoice, I think people don't feel heard...
There will be something on UserVoice with hundreds or thousands of responses,
but silence from MS or this fabled product team you mention..

It's your own fault for being so good at your job lol.

**Comment by get-itips** [comment]
Hello @Krytical13 
I can understand your frustration, however, let me tell you that we know that indeed the product group reviews the suggestions created in user voice.

I took the time to browse SharePoint User Voice, and found this thread  [Enable renaming the SPO tenant domain](https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/13217277-enable-renaming-the-site-collection-urls
) and a member of the PG replied saying **they are working on it**.

**Comment by boomalator** [comment]
At the earth-shattering pace of Cloud Development where UI changes are pushed out weekly, or even daily, that thread is now in it's FOURTH year. It has thousands of votes in support, but untold thousands more users that just think it's common sense to be able to rename a domain. (Active Directory domain rename, for example, was introduced in Windows Server 2003.)

"Working on it" for four years pretty much makes the point of the value of "User Voice".

**Comment by get-itips** [comment]
> At the earth-shattering pace of Cloud Development where UI changes are pushed out weekly, or even daily, that thread is now in it's FOURTH year. It has thousands of votes in support, but untold thousands more users that just think it's common sense to be able to rename a domain. (Active Directory domain rename, for example, was introduced in Windows Server 2003.) "Working on it" for four years pretty much makes the point of the value of "User Voice".

The _Working on it_ reply message is from November 15, 2019.

**Comment by boomalator** [comment]
Meaning that it takes four years for the Product Group to acknowledge it? 

I, personally, doubt very much that it's getting much traction, because I think it would be a pretty major roadmap item to allow tenant name changes or sharepoint vanity URLs.

**Comment by Krytical13** [comment]
> I, personally, doubt very much that it's getting much traction, because I think it would be a pretty major roadmap item to allow tenant name changes or sharepoint vanity URLs.
> 
> Edit: (Sorry, @get-itips, posted to soon)... The first working on it is January 2018 (2 years ago), the next "working on it" was a year later in March 2019 which said: "We plan to increase availability to this feature throughout 2019." I don't recall seeing this "throughout 2019". Then, in November 2019, they are "working on it" again.



@get-itips 
Maybe that's something the documentation team can do?
Update the road map? You'd have to be able to find out where to put it on the roadmap internally... 
This internal discussion would potentially push the product team to come up with a deadline and (hopefully) deliver?

**Comment by get-itips** [comment]
Hello @Krytical13 How are you? Hope you are doing good.

Our scope of collaboration here is: certain repos in docs.microsoft.com, we do not have influence in Roadmap documentation.
As our only duty here is to maintain and correct documentation, I am afraid I can not help you beyond that, whenever the current feature is changed, I could update the document based on that, however I can not help on the addition of new features (that is the goal of User Voice, even if it takes time). 
I hope you understand that and my job here, if there is not a documentation change, I can not help further.
@scanum please review and close this thread if you agree.

Thank you

**Comment by kenwith** [comment]
Completely agree with this thread and also voted on the User Voice that was linked: https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/13217277-enable-renaming-the-site-collection-urls

The good news is that it looks like someone from product team responded and they are working on it. Looking forward to updating this documentation when this is possible!

**Comment by eugenevdm** [comment]
Just leaving a comment and lots of love for the Microsoft team as a reminder that companies merge and change names and so on and this would really be a lovely feature.
