### ISSUE TITLE
Issue on PS script?

### ISSUE THREAD

**Issue by hdinwoodie** [MicrosoftDocs/OfficeDocs-SharePoint#1485]
I found I had to use Standard_LRS instead of "StandardLRS" when using the script to create the VM for adVM. Not sure if this is the same for everyone and the above script is out of date? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure#feedback)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by tseward** [comment]
See https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/701. It may have changed during this time frame but please confirm the version of the Azure cmdlets you're running.

**Comment by hdinwoodie** [comment]
Hi, I ran Install-Module -Name Az -AllowClobber -Scope CurrentUser

In Powershell last week so I assume I have the latest version of azure cmdlets? Got the above from here: https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.0.0

Thanks

Hollie Dinwoodie
SQL BI Developer
Abercrombie & Kent Ltd.
Tel: +44 (0)1242 547841

**Comment by scanum** [comment]
@hdinwoodie  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
