### ISSUE TITLE
is it possible to call the OD Sharing Report via Graph or API or CSOM? 

### ISSUE THREAD

**Issue by zvoltejinylogin** [MicrosoftDocs/OfficeDocs-SharePoint#1486]
Hello and thank you for the report, but will it be possible to utilize the report in an automation?

Either as an admin to generate reports on behalf of users in a script (not going manually grant yourself access and go click on report, if I will be managing 100k OD accounts).  

or base on this feature an automation for users to single-click in a SP list that would run a logic of find user's OD site, grant mechID access to site, generate report for user, send notification, remove mechID from site (either flow or Azure automation with powershell)

**Comment by scanum** [comment]
@zvoltejinylogin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by zvoltejinylogin** [comment]
Hello, that was a general question in the lack of documentation on your part. You provide a feature and now I would like to know how I can use that feature :) thanks anyway.
