### ISSUE TITLE
Step 4 missing a backslash

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#1490]
Existing text: Paste the .admx file in your domain's Central Store, \domain\sysvol\domain\Policies\PolicyDefinitions (where domain...

Needs to be 
Paste the .admx file in your domain's Central Store, \\domain\sysvol\domain\Policies\PolicyDefinitions (where domain....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @blouwagie 
Thanks for noticing, created a pull request to correct the backslash escaping in markdown file.

**Comment by get-itips** [comment]
@scanum please kindly close this thread. thanks

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
