### ISSUE TITLE
Additional missing error codes

### ISSUE THREAD

**Issue by Cloudmaister** [MicrosoftDocs/OfficeDocs-SharePoint#1491]
0x01710004 - Errors or timeout for Server Processing the file:Fail to lookup folder name. The item may exist in other list or site in the same site collection. Or the item is in the recycle bin
0x0131000F - Failed to Read the file:File is checked out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshooting SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues#feedback)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Cloudmaister Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Cloudmaister 
Thanks for your contribution, created a pull request proposing adding those error codes, if it gets approved, they will show up in the live version of the article.
Thanks again.

**Comment by scanum** [comment]
@Cloudmaister Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@Cloudmaister Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
