### ISSUE TITLE
OS Requirements

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1492]
Are these minimum requirements for the OS meaning the tool is not supported on anything greater then Windows Server 2012 R2? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues#check-to-make-sure-all-system-prerequisites-have-been-installed)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Padavid 
Actually, Windows Server 2012 R2 is on the "Reqs for Best Performance" table, and Windows Server 2008 R2/Windows 7 is on the minimum reqs table.

Personally, I installed it on later versions of Server OSs however as you might know, one thing is "works" and another different thing is "is supported", so I think we need an official statement by the Product Team here, please @JoanneHendrickson can you step in to confirm if later versions are "supported"? Thank you

**Comment by get-itips** [comment]
please @JoanneHendrickson can you step in to confirm if later versions are "supported"? Thank you

**Comment by scanum** [comment]
@JoanneHendrickson Could you please help on this issue? Thanks.

**Comment by scanum** [comment]
@JoanneHendrickson Could you please help on this issue? Thanks.

**Comment by scanum** [comment]
@JoanneHendrickson Could you please help on this issue? Thanks.

**Comment by scanum** [comment]
@JoanneHendrickson Could you please help on this issue? Thanks.

**Comment by JoanneHendrickson** [comment]
confirming with product, will update shortly

**Comment by JoanneHendrickson** [comment]
Yes -- later versions of the OS are supported. updating topic now.
