### ISSUE TITLE
Endpoint for GCC

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1493]
This list of end points does not include the ones for GCC which should be: 

*.blob.core.usgovcloudapi.net	Azure Government Blob Storage	Used for temp encrypted Azure Storage for Migration API
*.queue.core.usgovcloudapi.net	Azure Government Queue Storage	Used for temp encrypted Azure Storage for Migration API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues#check-to-make-sure-all-system-prerequisites-have-been-installed)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by BPWMaddog82** [comment]
We had the same issue with it. In the documentation it is stated that *.blob.core.windowns.net is needed but from network monitor, it shows also *.store.core.windows.net as destination and failed on that.

**Comment by get-itips** [comment]
Hello @Padavid thanks for noticing and reporting, created a pull request to improve the article.

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
