### ISSUE TITLE
How to get external sharing report for teams site and onedrive sharing for all users?

### ISSUE THREAD

**Issue by RaviD-Git** [MicrosoftDocs/OfficeDocs-SharePoint#1494]
1) How to get external sharing report for sites created via teams? so eg: As an admin how do I get report for https://contoso.sharepoint.com/teams/****?

2) Onedrive sharing report currently gives the user to download his sharing report. How can a administrator download the external sharing report for onedrive for all users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing](https://docs.microsoft.com/en-us/sharepoint/sharing-reports)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by knutale** [comment]
Same question here.

**Comment by scanum** [comment]
@RaviD-Git  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by zvoltejinylogin** [comment]
Ditto on the same question, I would welcome a possibility in OneDrive Admin central to produce sharing reports for individual users or gather all into a DB or CSV file, if one should manage 1k+ users then we need some simple tools to do it. 

I've tried PnP powershell, standard powershell module and looked at Graph, I am no developer but the lack of documentation is staggering...

**Comment by get-itips** [comment]
Hello @RaviD-Git 
How are you? Hope you are doing good.

1. I was able to get the report for a Sharepoint Teams-associated team site, entering each site and following the steps outlined, is that what you wanted or I am missing something? Please let me know.

2. I can confirm there isn't a way yet to do this from OneDrive Admin Panel, so I need to kindly redirect you to [SharePoint UserVoice](https://sharepoint.uservoice.com/) to suggest your idea there, where it can reach the product team and they can decide to add it to the [Microsoft 365 RoadMap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=)

Hope this information helps you.

**Comment by get-itips** [comment]
@scanum kindly close this one, thanks

**Comment by scanum** [comment]
@RaviD-Git Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
