### ISSUE TITLE
List of IE-only features is missing "Open with Explorer"

### ISSUE THREAD

**Issue by cloudgreen** [MicrosoftDocs/OfficeDocs-SharePoint#1496]
The list of IE-only features is missing the feature "Open with Explorer".

That feature, and its IE-exclusivity as it's relying on ActiveX, is discussed on the support page below:

https://support.office.com/en-us/article/open-in-explorer-or-view-with-file-explorer-in-sharepoint-66b574bb-08b4-46b6-a6a0-435fd98194cc

I think it would be a good idea to add that to the list here.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d1b075-d17b-510d-f886-4f5deed4cc9e
* Version Independent ID: 336f78e0-78e2-0a55-5e1b-2bf41072a0cb
* Content: [Plan browser support in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/browser-support-planning-0#feedback)
* Content Source: [SharePoint/SharePointServer/install/browser-support-planning-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/browser-support-planning-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@cloudgreen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Grunge** [comment]
There are like 10 different ActiveX in SharePoint that cause trouble with all Browsers except IE. The often just to really small things. Could they not be handled in the New Edge Browser? 
Example, if SharePoint throws the ActiveX of type "Open with Explorer" the the Edge Browser on Windows is connecting the Windows File Explorer with the WebDav and Path of the Site/DocLib and not really interpreting/running the ActiveX, so no ActiveX engine would be needed anymore.
This could be the Business Feature of the new Edge...

**Comment by get-itips** [comment]
Hello @Grunge thanks for the information provided.
@MikePlumleyMSFT Mike, I can add a row for "Open with Explorer" to the current table however to make it complete I would need the information about the dll file name used in that scenario, can you help with that ? Thanks

**Comment by cloudgreen** [comment]
@MikePlumleyMSFT Would it be possible to add information about whether Microsoft intends to somehow "re-engineer" some of these ActiveX-based features to work with Edge Chromium (as @Grunge also suggests above)?

I have several on-premise clients who are transitioning to Chrome and they are very concerned about "Open with Explorer" only working in IE, as it's a unique way of restructuring files in SharePoint Server. They are very invested in the SharePoint Server product. So it would be very helpful to know if it's on Microsoft's roadmap to make this work in Edge Chromium?

Thank you so much for any insights!

**Comment by MikePlumleyMSFT** [comment]
I'm not aware of a specific plan for the various ActiveX controls, For the "Open with Explorer" option, the recommendation would be to use the sync app to sync the files that you want to be able to access through Explorer. If you have Open with Explorer scenarios where the sync app won't work, let me know what they are and I'll pass them along to the feature team. Also, feel free to post any specific functionality needs to [UserVoice](https://sharepoint.uservoice.com).

**Comment by get-itips** [comment]
@MikePlumleyMSFT Thanks for responding to the issue creator, I wonder if you could see my question, do we have the information of the dll used by the "Open with Explorer" action so I can add that information to the article? Thank you.

**Comment by scanum** [comment]
@MikePlumleyMSFT Following up on this last comment. Please let us know if you have any questions. Thanks!

**Comment by cloudgreen** [comment]
> 
> 
> I'm not aware of a specific plan for the various ActiveX controls, For the "Open with Explorer" option, the recommendation would be to use the sync app to sync the files that you want to be able to access through Explorer. If you have Open with Explorer scenarios where the sync app won't work, let me know what they are and I'll pass them along to the feature team. Also, feel free to post any specific functionality needs to [UserVoice](https://sharepoint.uservoice.com).

Thanks a lot for your reply, really appreciated. Sorry for my super late reply!

Well, several of my government customers, who use SharePoint Server on-prem, don't use OneDrive at all. The "Open with Explorer" feature is almost the only feasible way of restructuring many files simultaneously, like moving multiple files upwards or downwards in a folder hierarchy. And even if they did use OneDrive, it's a slow process and it feels a bit backwards to be forced to download a (potentially huge!) list just to be able to restructure it.

The "loss" of "Open with Explorer" will be a big one, for us. Sure, IE will still be around for a long time, so it's probably more of a nuisance to be forced to maintain multiple browsers and a training issue to educate end users to use IE for some features. It will complicate matters.

**Comment by scanum** [comment]
@MikePlumleyMSFT Following up on this last comment. Please let us know if you have any questions. Thanks!

**Comment by scanum** [comment]
@cloudgreen Thank you for engaging with the community here for the docs. We appreciate your contributions.

I know the product teams are always looking for user feedback and how to make SharePoint better. It would be great if you can comment there regarding the feature asks in this particular issue.They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cloudgreen** [comment]
Thanks @scanum! Porting the SharePoint feature "Open with Explorer" to Edge has indeed been requested multiple times at Uservoice.

One of the suggestions were denied already back in 2018:

> "We are putting all our energy into making the OneDrive app with Files On Demand the best way to interact with all your SharePoint and OneDrive documents. The legacy Open in Explorer feature depends on some very particular interactions between IE and the Windows OS that can’t be generalized to other browsers, and in addition prevents us from integrating features like sharing links."

I added my support to another suggestion below, for what it's worth...

https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/33196501-view-in-file-explorer-for-edge

Thanks for listening!
