### ISSUE TITLE
GCC Endpoint

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1498]
Do we need to add the GCC endpoints to this endpoint list. 

*.blob.core.usgovcloudapi.net
*.queue.core.usgovcloudapi.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624f51bf-bf14-03ae-099b-2ee8b8657bf2
* Version Independent ID: 71bc428f-3fe9-1e9b-a996-871407127f96
* Content: [Setup Migration Manager clients](https://docs.microsoft.com/en-us/sharepointmigration/mm-setup-clients)
* Content Source: [migration/mm-setup-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-setup-clients.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
