### ISSUE TITLE
Misspelling 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1500]
There looks to be a misspelling of the word migration in the endpoints. 

Current: https://*.sharepoint.com	Destination for migratrion
Should be: https://*.sharepoint.com	Destination for migration 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Padavid thanks for noticing and reporting, created a pull request to correct the article.

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
