### ISSUE TITLE
Invalid site URL (ErrorCode: 0x0201000F)

### ISSUE THREAD

**Issue by dorseytm** [MicrosoftDocs/OfficeDocs-SharePoint#1501]
Trying to migrate a Sharepoint 2013 on-prem site collection to a SharePoint online site and receiving an "Invalid site URL" message.  Verified I can navigate to the 2013 site by entering the site's url in a browser.
[FatalError_R1.xlsx](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/3815709/FatalError_R1.xlsx)

Using the Sharepoint Migration Tool v. 3.2.114.2

**Comment by scanum** [comment]
@dorseytm thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
