### ISSUE TITLE
SPO start page - I would like to remove the "News From Sites" section or move to bottom of page

### ISSUE THREAD

**Issue by tierratom** [MicrosoftDocs/OfficeDocs-SharePoint#1502]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d22faa3-6e72-a382-cb45-fd2f98d735d2
* Version Independent ID: 8e095a7f-d8af-4105-6c4a-effe3d3856bc
* Content: [Add featured links to the SharePoint start page](https://docs.microsoft.com/en-us/sharepoint/change-links-list-on-sharepoint-home-page#delete-a-link)
* Content Source: [SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tierratom  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
The start page cannot be changed. The only control you have is for the featured links.

**Comment by tierratom** [comment]
Thank you, Trevor

Tom Greene
East End Computers
________________________________

**Comment by get-itips** [comment]
@scanum this one can be closed. Thanks

**Comment by scanum** [comment]
@tierratom Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
