### ISSUE TITLE
Block files types from Web

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/OfficeDocs-SharePoint#1503]
Hello,
Sorry but we don't use Onedrive or sharepoint, we've choosen another collaboration tool. Unforfunately one drive is the only way to use Onenote with Mac users, because of this, we cannot completely disable One Drive (Thanks Microsoft!!) 

How do we block all file types from being saved into One Drive web or through the Word/Excel/Powerpoint direct connection? These instructions only apply to syncing which is not helpful.

I'd prefer One drive and sharepoint weren't enabled like this, not every company is going to use your product espicially with great alternatives like Box, Dropbox, Google Drive etc.

**Comment by tseward** [comment]
The only option you have is to disable synchronization of specific file types. There are no file type blocks in place which is controlled at the Web Application level, which only Microsoft has access to.

**Comment by scanum** [comment]
@afield1235 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
