### ISSUE TITLE
Nested Site Collections

### ISSUE THREAD

**Issue by bratyslav** [MicrosoftDocs/OfficeDocs-SharePoint#1504]
Can a Site Collection contain another Site Collection? If you have an answer, please give also a sourse of information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba398055-8dc1-82ca-5327-fbdb76a34ce4
* Version Independent ID: cba2864a-6dd5-b9af-4bcd-ae373662df83
* Content: [Overview of sites and site collections in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/sites-and-site-collections-overview#feedback)
* Content Source: [SharePoint/SharePointServer/sites/sites-and-site-collections-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/sites-and-site-collections-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
No, the Site Collection is the container for Webs (an `SPSite` object contains one or more `SPWeb` objects).

**Comment by scanum** [comment]
@bratyslav Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by bratyslav** [comment]
Thank you for response!
