### ISSUE TITLE
Advanced configurations | External users

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#1505]
Hello, 
We try to apply Conditional Access policy for SharePoint, this is done in tenant level and applied "Allow-limited, web-only access" and then we run this cmdlet: Set-SPOTenant -ApplyAppEnforcedRestrictionsToAdHocRecipients $false
Still external users after 48 hours not able to download files.
Can u please confirm how this cmdlet should work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-specific-sharepoint-site-collections-or-onedrive-accounts)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Have you configured the Conditional Access Policy in Azure?

**Comment by lightupdifire** [comment]
Yes, it is created automatically if we enable limited access in SharePoint admin center.

**Comment by lightupdifire** [comment]
Hello,
I think that besides the PS command, external users must be also excluded from Conditional Access policies.
Just tested this and then my test external and guest users start to work for download:
![image](https://user-images.githubusercontent.com/39700914/68584495-05ed8a80-0480-11ea-805a-7de92882ea38.png)

If this is a case, the article should be updated accordingly.

So in short:
1. If scenario apply to SPO level and Device access enabled: "Allow-limited, web-only access"
2. Run PS: Set-SPOTenant -ApplyAppEnforcedRestrictionsToAdHocRecipients $false
3. Exclude Gues/External from Conditional Access policies

**Comment by lightupdifire** [comment]
Hello,
Small update, after playing with Conditional Access policies I got this now:
1. Existing in AAD Guest users - limited to download
2. Shared files to Ad-Hoc users - allowed to download

So like now I got exactly how it should work: "All users limited download, but Ad-Hoc can download".
What I did is:

1. Changed Conditional Access policy from Include All users -> to only my user (with which was testing)
2. Changed Conditional Access policy back to Include All users

Just in case will test tomorrow, but I have a feeling that CA stuck somehow and should be like "re-changed"......

Still, this will provde that it is working like it should, but maybe an FAQ could be handy for this behavior :)

**Comment by Jmartinez589** [comment]
Thank you for the additional details. It is important to make this feature set clearer and for there to be more testing by the product group to ensure the configuration is consistent with the intent. For you to have to change it from a group with one user, then back just sounds like this feature is flawed.

**Comment by scanum** [comment]
@lightupdifire Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Jmartinez589** [comment]
Hello Manuela,

Can you take a closer look at this issue?
I understand that you may want to close it, maybe you get credit for closures, but if you haven't fully considered @lightupdifire's comments he is basically explaining that the article does not work as described. There are bugs that he was want to work through. The article needs more work.
________________________________
