### ISSUE TITLE
Onedrive reverted and is now full and wont update back

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/OfficeDocs-SharePoint#1506]
I ran all this 6+ months ago on my onedrive and it randomly reverted to 5GB cap yesterday from 5TB. I reran PS Commands to set cap and reset default space as well. Now i have critical flow processes failing that depend on onedrive... It seems every 3-6 months im dealing with onedrive randomly dying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tpmeredith thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
