### ISSUE TITLE
Align with Password policy recommendations for Office 365

### ISSUE THREAD

**Issue by sguitardude** [MicrosoftDocs/OfficeDocs-SharePoint#1507]
I recommend we update the password section to more closely align with Password policy recommendations for Office 365, in particular, Don't require character composition requirements.
https://docs.microsoft.com/en-us/office365/admin/misc/password-policy-recommendations?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8234ffd6-eecf-088e-6ac4-76a750c123a9
* Version Independent ID: 7dfd076b-7c10-948d-4a48-3ddefc3c8795
* Content: [Install SharePoint Servers 2016 or 2019 across multiple servers](https://docs.microsoft.com/en-us/sharepoint/install/install-sharepoint-server-2016-across-multiple-servers#feedback)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
These are two very different use cases and using the recommendations for Office 365 would not be appropriate for SharePoint Server service accounts.

**Comment by scanum** [comment]
@sguitardude Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
