### ISSUE TITLE
Control specific users to access share point   based on location?

### ISSUE THREAD

**Issue by lakshmanakanth** [MicrosoftDocs/OfficeDocs-SharePoint#1509]
Is it possible to control specific users to access share point   based on location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Control access to SharePoint Online and OneDrive data based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by MikePlumleyMSFT** [comment]
@lakshmanakanth this isn't possible from the SharePoint admin center, but you can set up a conditional access policy in Azure AD. See [Conditional Access: Block access by location](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-conditional-access-policy-location) for information.

**Comment by scanum** [comment]
@lakshmanakanth Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by subodhpatil** [comment]
I don't think this is resolved. 
I think the Azure AD conditional access can control only managed/unmanaged devices restriction at site level.
Although conditional access allows specifying public IP address , SharePoint site does not hour that setting.
