### ISSUE TITLE
Migration does not terminate gracefully when out of working space

### ISSUE THREAD

**Issue by gjohncock** [MicrosoftDocs/OfficeDocs-SharePoint#1510]
We had a rather large migration display a message saying something like "allocated space was running low" but it had consumed all available space on the drive, which happened to be the system drive and no easy way to terminate the application apart from cancelling the process in Task Manager.  
Is this the expected behaviour in this situation?  Is there some way that the tool can be aware of the free space available and provide options before all the spare space on the drive is consumed?

**Comment by scanum** [comment]
@gjohncock thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
