### ISSUE TITLE
Disabling DenyAddAndCustomizePages does not work on Modern Team Sites

### ISSUE THREAD

**Issue by TeodoraI** [MicrosoftDocs/OfficeDocs-SharePoint#1512]
Hi, 
I want to disable DenyAddAndCustomizePages (Set-SPOSite XXX -DenyAddAndCustomizePages 0) on a Modern Team Site but it seems the command does not work anymore. I tried also doing the same with the Chrome Office Add in and gives an error ‘Field or property "storageentitiesindex" does not exist.’

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#feedback)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TeodoraI thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by TeodoraI** [comment]
Hi, I am using a demo tenant and I think this is a bug as it is not documented anywhere and according to the documentation this should work. Could you check if it is a bug or somethings has changed in how this PS cmdlet works?
