### ISSUE TITLE
Variations Deprecated

### ISSUE THREAD

**Issue by vaibhavantriwale** [MicrosoftDocs/OfficeDocs-SharePoint#1513]
Request you to please update this article to reflect that Variation is deprecated in SharePoint and also suggest alternatives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39359ae1-9134-3247-64d8-2ef89043376e
* Version Independent ID: 2042e42c-8315-92e2-b3fb-e40f7c21abdc
* Content: [Variations overview in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/variations-overview#feedback)
* Content Source: [SharePoint/SharePointServer/administration/variations-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/variations-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@vaibhavantriwale Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @vaibhavantriwale I am proposing thru a PR to add a note to the article, thanks
@JoanneHendrickson 
I couldn't find a clear official statement about a replacement feature, is there any? Thanks

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by JoanneHendrickson** [comment]
@TroyStarr @SerdarSoysal     Troy can you assist?

**Comment by tseward** [comment]
As of now, there are no alternatives for 2019 given the modern variations feature from Microsoft is only available in SPO.

Unless developed by a 3rd party/the community, there will likely be no replacement specifically in SharePoint 2019, but it is a good idea for vNext.

@scanum can you close this issue as the change to note deprecation was merged?
