### ISSUE TITLE
Cannot block the site using Powershell Sharepoint online management shell

### ISSUE THREAD

**Issue by lamanirmal** [MicrosoftDocs/OfficeDocs-SharePoint#1515]
Trying to block a site for unmanaged devices using the command below: 

Set-SPOSite -Identity https://<SharePoint online URL>/sites/<name of site or OneDrive account> -ConditionalAccessPolicy BlockAccess

But I am getting following errors:

Set-SPOSite : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Set-SPOSite -Identity https://xxxxxx.sharepoint.com/sites/VerySecure -C ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SPOSite], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Online.SharePoint.PowerShell.SetSite
Can anyone please help me. 

Thanks in advance.

**Comment by scanum** [comment]
@lamanirmal thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
