### ISSUE TITLE
Unable to Restore SharePoint Online Site by ID

### ISSUE THREAD

**Issue by fleitzelar** [MicrosoftDocs/OfficeDocs-SharePoint#1516]
When multiple sites with the same URL have been deleted on SharePoint Online, you cannot restore the site you need by SiteID. 
It renders the SiteID property useless for SharePoint Online sites.

**Comment by scanum** [comment]
@fleitzelar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
