### ISSUE TITLE
SQL Server 2019 support?

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#1517]
Is Sql Server 2019 support with SharePoint 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fbcb0b-9e6d-d2e7-5194-5593d35fff63
* Version Independent ID: f6d30df6-858b-4d3c-542f-a4d6b45ec3d8
* Content: [Hardware and software requirements for SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@TroyStarr ping :-)

**Comment by TroyStarr** [comment]
Thanks @tseward, [pull request](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1528) submitted!

@paololec, yes, SharePoint Server 2019 (and SharePoint Server 2016) is now supported with SQL Server 2019.

**Comment by get-itips** [comment]
@scanum please close this one. thanks

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
