### ISSUE TITLE
Documentation is not correct

### ISSUE THREAD

**Issue by nancywagar** [MicrosoftDocs/OfficeDocs-SharePoint#1519]
Under configure hybrid specific settings, the steps are:
1) In Central Admin, under system settings, click "Manage services in this farm".  There is no such option.
2) For the Microsoft SharePoint Foundation Subscription Settings Service, click Enable Auto Provision - WHERE IS THIS OPTION?  I see nothing similar to enable auto provision.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1671c351-27e4-e726-858d-c3d660777977
* Version Independent ID: 6cbafe83-90b9-1113-a49b-9212505338b5
* Content: [Set up SharePoint services for hybrid environments](https://docs.microsoft.com/en-us/sharepoint/hybrid/set-up-sharepoint-services-for-hybrid-environments)
* Content Source: [SharePoint/SharePointServer/hybrid/set-up-sharepoint-services-for-hybrid-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/set-up-sharepoint-services-for-hybrid-environments.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@nancywagar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @nancywagar 

I found that those directions are for 2019 menu options, that's probably you are using SharePoint 2013.
I will create a pull request to add the SharePoint 2013 alternatives.

Thank you

**Comment by get-itips** [comment]
Hello @scanum you can close this now 👍

**Comment by get-itips** [comment]
Hello @scanum kindly close this now. thanks

**Comment by scanum** [comment]
@nancywagar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
