### ISSUE TITLE
Picture should be updated 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#1520]
The picture in the What content goes where section should reflect both OneDrive and SharePoint for the top of the column and not just OneDrive. Similar to the file share Picture

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dd9b09-7975-6ac0-fa4e-2c09c17c2045
* Version Independent ID: e34a0e26-2f32-98fe-a7d3-01033d6f3a7e
* Content: [Box to OneDrive and SharePoint Migration Guide - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/box-to-onedrive-and-sharepoint-migration-guide#feedback)
* Content Source: [migration/Box-to-OneDrive-and-SharePoint-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Box-to-OneDrive-and-SharePoint-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@JoanneHendrickson Joanne, do you have this original editable image?

![](https://docs.microsoft.com/en-us/sharepointmigration/media/migration-whatgoeswhere-box-to-odsp-520x.png)

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by JoanneHendrickson** [comment]
Found the original art (its in AI) and am updating it.

**Comment by JoanneHendrickson** [comment]
Art fixed.
