### ISSUE TITLE
How long will shared OneDrive files be accessibile after an employee leaves?

### ISSUE THREAD

**Issue by rbahne** [MicrosoftDocs/OfficeDocs-SharePoint#1521]
How long will shared OneDrive files be accessible after an employee leaves?

Dick shares a file with Jane.
Jane sees the file in her Shared OneDrive Folder. 
Dick leaves the company and is marked for deletion. 

When will Jane's access to see Dick's shared file cease?
A. The day Dick was marked for deletion.
B. Thirty days after Dick was marked for deletion
C. If the orphaned account policy is set for longer than 30 days - when that policy expires.  
D. Some other duration (PLEASE EXPLAIN)

**Comment by rbahne** [comment]
Is anyone out there? :)

**Comment by tseward** [comment]
Once the user is de-licensed or deleted from Azure AD (if a cloud user, in AAD, or if AD, either in AD or removed out of the scope of sync between AD and AAD), the timer starts on the next synchronization between AAD and SPO -- this should be fairly quick. At that point, the user object is marked for deletion in SPO UPSA and the user's manager receives the notification.

The ODfB is retained for however long you've specified after user deletion; by default 30 days. The ODfB site then is retained in the site recycle bin for 93 days.


https://docs.microsoft.com/onedrive/retention-and-deletion#the-onedrive-deletion-process

**Comment by scanum** [comment]
@rbahne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
