### ISSUE TITLE
Allow users to create site pages in specific site collection when site pages creation is disabled in SharePoint Admin center 

### ISSUE THREAD

**Issue by irshadnazly** [MicrosoftDocs/OfficeDocs-SharePoint#1522]
I have tested scenario described in the subject and it does not allow to create site page even though the feature is enabled.

**Comment by tseward** [comment]
Which document are you referencing? Can you supply the URL?

**Comment by scanum** [comment]
@irshadnazly We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by irshadnazly** [comment]
> Which document are you referencing? Can you supply the URL?

This is the article that I am referring to.

https://docs.microsoft.com/en-us/sharepoint/let-users-create-modern-site-pages

**Comment by tseward** [comment]
@irshadnazly on a Modern Team/Comm site, are your users not able to use the New -> Page function? Do they have the appropriate permission on the site in question?

**Comment by irshadnazly** [comment]
> @irshadnazly on a Modern Team/Comm site, are your users not able to use the New -> Page function? Do they have the appropriate permission on the site in question?

@tseward : yes the do have the relevant permission. Further, users are able to create "web part" and wiki pages.

**Comment by irshadnazly** [comment]
I escalated this to Microsoft and below is their response. So it has to be allowed from the tenant level in order to use at the site level.

1.	Tenant level settings should always be enabled in order to Allow or Prevent users to create site pages on site level.
2.	If in case Tenant level settings are disabled and even if we run the script to enable site pages feature it will not take effect.
3.	This is by default mechanism of SharePoint Online sites and SharePoint admin tenant.
