### ISSUE TITLE
User License Mapping

### ISSUE THREAD

**Issue by JeroenDerde** [MicrosoftDocs/OfficeDocs-SharePoint#1523]
Make sure that all your on-premises users have a Enterprise license. Else Hybrid federated search result in SharePoint Server will not work. I had a standard license configured via user license enforcement, and this resulted in the Result block for SharePoint Online results not showing in the on-premises search center.

https://www.sharepointeurope.com/user-license-enforcement-in-sharepoint-2013/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3b1a41-c3cd-82d8-b8f1-0a9f0ac324c8
* Version Independent ID: a9c5bf96-e604-c8b0-4d9c-53bb63c438a4
* Content: [Display hybrid federated search results in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/hybrid/display-hybrid-federated-search-results-in-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/display-hybrid-federated-search-results-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/display-hybrid-federated-search-results-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@JeroenDerde Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @MikePlumleyMSFT Can you help me confirm this? I am afraid I can not test this in my lab.

**Comment by MikePlumleyMSFT** [comment]
This is covered in the [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description). Hybrid features should work with both SharePoint Standard and SharePoint Enterprise.

**Comment by get-itips** [comment]
Hello @scanum 
Question should be covered now, please review and close this thread. Thank you 👍

**Comment by scanum** [comment]
@JeroenDerde Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
