### ISSUE TITLE
This article needs to be updated with information about increasing a users ODFB storage quota above 5TB

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/OfficeDocs-SharePoint#1525]
This article needs to be updated with information about increasing a users ODFB storage quota above 5TB.
Does increasing it beyond 5TB require a support ticket to be submitted? Or can this be done using  
Set-SPOSite -Identity &lt;user's OneDrive URL&gt; -StorageQuota &lt;quota&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space](https://docs.microsoft.com/en-us/onedrive/change-user-storage#feedback)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
This is outlined at: https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description#storage-space-per-user.

It would be a good idea to put a NOTE or See Also section pointing to the above article.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
