### ISSUE TITLE
URL Change - Teams - Viewing teams files

### ISSUE THREAD

**Issue by Todd312** [MicrosoftDocs/OfficeDocs-SharePoint#1534]
Hi, any update on when a fix will be coming through for the issue where files aren't able to be viewed within Teams after changing the URL of the site? I need this functionality extremely soon before rolling out a new internal intranet for our business. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Todd312 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Todd312 
How are you? I am afraid we don't have that information here, please kindly contact support directly from your tenant to get an update on that issue.

**Comment by get-itips** [comment]
@scanum  please close this thread. thanks

**Comment by Todd312** [comment]
I just found that this is meant to be fixed from another website, however I don't have permission to put in a request to check if this is true. Can anyone please check this and then update this page and thread if it has actually been fixed

https://office365itpros.com/2019/05/02/sharepoint-online-rename-site-names/

"Update: January 2, 2020: Renaming a site used to have an effect on the connection between Teams (via the Files channel tab) and SharePoint. Microsoft has fixed the problem and you shouldn’t have any problems with Teams now."

**Comment by prashant1380** [comment]
This still does not work at least in our tenant. When we try to drag/drop a file to Teams channel File tab then upload fails.

**Comment by jczinger** [comment]
I renamed an SPO site connected to an MS Team on friday. After about 90 minutes, the team was working correctly. I can browse/add/remove documents from inside of Teams for all channels. I've since deleted the SPO site redirect and re-created a new site on the previous URL. Everything is working as expected.

**Comment by scanum** [comment]
@Todd312 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
