### ISSUE TITLE
OneDrive Permission

### ISSUE THREAD

**Issue by Tomkungz** [MicrosoftDocs/OfficeDocs-SharePoint#1535]
I can't adjust sharing permissions to everyone while setting and pressing save the screen does not respond.
[https://drive.google.com/open?id=1_IgrjCJSUIJiRPQ_4GhoJle4gVOAPWDQ](url)

**Comment by scanum** [comment]
@Tomkungz thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
