### ISSUE TITLE
Document OneDriveSetup.exe /allusers

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#1537]
We spent literally weeks with Microsoft support trying to find out how to pre-install OneDrive for all users on a system so that end-users would not need how to do this, only to discover that this is actually a setting in the installation. ((Why this is not the default baffles me/us/ and baffled Microsoft support).  Please document the existence of this extremely useful option needed to deploying OneDrive for you business users: 
* OneDriveSetup.exe /allusers *

They call it Per Machine installation https://docs.microsoft.com/en-us/onedrive/per-machine-installation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise#feedback)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1538

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
