### ISSUE TITLE
Please add the wording "installing OneDrive for all users"

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#1538]
We spent literally weeks with Microsoft support trying to find out how to pre-install OneDrive for all users on a system so that end-users would not need how to do this, only to discover that this is actually a setting in the installation. ((Why this is not the default baffles me/us/ and baffled Microsoft support).  Please document the existence of this extremely useful option needed to deploying OneDrive for you business users: 
* OneDriveSetup.exe /allusers *

Somehow none of us thought that Microsoft was going to call this "per machine" installation. Please add some wording so that search engines would find that they need to do this when they want to pre-install OneDrive for all users.  Again, why this is not the default, or a question during installation, is beyond me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CCDFischer** [comment]
To be fair, the "Per Machine" vs "Per User" language is consistent with how MS labels other installers (see Teams), and you are installing it for the machine instead of for users (that is how all users will have the software installed). I am surprised that support was not able to point you in this direction, but adding the wording you are asking for here could introduce more ambiguity between the two installation methods.
Why there are still enterprise grade software that was only ever designed to install per user is baffling in itself but that is a discussion for another topic.

**Comment by blouwagie** [comment]
It may be consistent with other wording but documentation is there for the
consumer. Leave the per machine wording and just add a sentence like... "If
you want this to be installed for all users add the flag..". This is so
that search engines would find it.
It is really making that the installer does not ask this should be
installed just for this user or for every user as many other software
packages do.

bart

bart@louwagie.com

**Comment by get-itips** [comment]
@blouwagie How are you? Hope you are doing great.
While I pull my lab to test this, wanted to ask you something to understand better, I see that the article presents this command:

> Run “OneDriveSetup.exe /allusers” from a command prompt window

I see that this line was present at the time you created this issue, so I think that you tried that one and the one that worked for you was adding the * asterisk character, is that right? Thanks

**Comment by scanum** [comment]
@blouwagie We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
