### ISSUE TITLE
App Catalog under "More Features"

### ISSUE THREAD

**Issue by Jack-DMZ** [MicrosoftDocs/OfficeDocs-SharePoint#1539]
In the new SharePoint Admin center, the "App Catalog" is now displayed in a grid after engaging "More Features". A quick revision could be:
Step 1: Create the App Catalog site collection
...
  3. In the left pane, select Classic features or More features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc1e9c0-2e35-3357-7f57-5bd02b0e10bc
* Version Independent ID: 1443a95a-ce5b-024d-d942-001b83bf8d8c
* Content: [Use the App Catalog to make custom business apps available for your SharePoint Online environment - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/use-app-catalog#feedback)
* Content Source: [SharePoint/SharePointOnline/use-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/use-app-catalog.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Jack-DMZ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Jack-DMZ 
Steps [have been fixed](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/3d4a6248c09a868133c58cb722d5189e296f6668#diff-779972135bccb91dd320f179cb116a28) after you reported this 👍 

@scanum please close this one thanks

**Comment by get-itips** [comment]
@scanum please close this one thanks

**Comment by scanum** [comment]
@Jack-DMZ Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
