### ISSUE TITLE
nothing about 2019

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#1540]
there is no text about SharePoint 2019 on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8fe7471-d644-095c-4fbe-af23d7bb80e2
* Version Independent ID: 07920952-4448-ab49-6f53-8d56a5aa1d45
* Content: [Business intelligence in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/business-intelligence-0)
* Content Source: [SharePoint/SharePointServer/administration/business-intelligence-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/business-intelligence-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
