### ISSUE TITLE
Clarification of supported authentication methods

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SharePoint#1542]
The article states under section Common messages received by users:  "SharePoint Server is using basic authentication which isn't currently supported by this app - The SharePoint mobile app can use NTLM authentication, and Forms-based authentication."
Please also clarify whether the app supports other forms or authentication or not, specifically most commonly used ADFS and Kerberos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42bcdeb-a2a5-e6f1-4779-d7d5b837db1e
* Version Independent ID: 2d2bc902-f138-621f-3fc2-1de76bbe3f22
* Content: [Supporting the SharePoint mobile apps online and on-premises](https://docs.microsoft.com/en-us/sharepoint/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises)
* Content Source: [SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
Please see the [referenced app articles](https://support.office.com/en-us/article/sharepoint-mobile-app-for-ios-339402ce-16bb-4c97-9475-0c5375ccef7a) for the official authentication support statement. The current statement for iOS is "For On-Premises, we do not support: ADFS, Kerberos, Basic Authentication, Digest Authentication, self signed SSL or Multiple Authentication types in one zone"
