### ISSUE TITLE
MS support is claiming that the GPO-driven OneDrive features are still under development ("Insider Build")

### ISSUE THREAD

**Issue by jitterbox** [MicrosoftDocs/OfficeDocs-SharePoint#1543]
Microsoft Support is claiming that the OneDrive client's implementation of group policy-driven settings is still under development, despite there being **no indicators** on this article that these features are in preview, beta, or some other pre-release state such as "Insider Build only".  This doc was updated almost a month ago...is it true that the documented features are not yet fully released?  Where is the authoritative source of that information, if not the product documentation?

**Comment by scanum** [comment]
@jitterbox thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jitterbox** [comment]
We've had a ticket open since Oct. 29. The feature has been in a partially working state for a full year, and there's apparently great confusion on what has actually been released, and we're getting pushback on what they are "obligated" to support. I realize this is one of the difficulties with modern software lifecycles and CI/CD, but we deployed GPOs, SharePoint libraries and OneDrive syncs to our entire organization on the premise that the documentation was trustworthy...as have many others by the posts I'm seeing.
