### ISSUE TITLE
MS support is claiming that the GPO-driven OneDrive features are still under development ("Insider Build")

### ISSUE THREAD

**Issue by jitterbox** [MicrosoftDocs/OfficeDocs-SharePoint#1544]
Microsoft Support is claiming that the OneDrive client's implementation of group policy-driven settings is still under development, despite there being **no indicators** on this article that these features are in preview, beta, or some other pre-release state such as "Insider Build only".  This doc was updated almost a month ago...is it true that the documented features are not yet fully released?  Where is the authoritative source of that information, if not the product documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jitterbox Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jitterbox 
Thanks for your feedback, Docs should be treated as the source of auth, in any case, I would also like to add @kaarins to the conversation to confirm.

**Comment by j0rt3g4** [comment]
Hello @scanum 
I think that all the information related to this issue is outdated, the article was updated recently by admins and there is a video explaining how to get the features, no more beta or preview, the features are up and running.

**Comment by scanum** [comment]
@jitterbox Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
