### ISSUE TITLE
B2B Sync with external party

### ISSUE THREAD

**Issue by PMLIO** [MicrosoftDocs/OfficeDocs-SharePoint#1547]
Hi,

Sorry but I need some clarification. For the B2B sync to work does that require the external party to be paying subscribers of Office 365? Does this mean we can't have B2B sync if they are don't have an Office 365 plan? If so, will this be added as a feature so our partners who don't have O365 plans can collaborate using B2B sync?

Thanks

**Comment by scanum** [comment]
@PMLIO thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
