### ISSUE TITLE
SQLIO has been retired

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-SharePoint#1548]
Can we update the link for the SQLIO tool to DiskSpd (https://aka.ms/diskspd) instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e12588-d632-a9fa-c3e8-aa6bb1b46f73
* Version Independent ID: a7c0a603-f37a-ebad-2870-b35a9b3e76e3
* Content: [Plan enterprise search architecture in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/plan-enterprise-search-architecture#test-the-storage-io-subsystem)
* Content Source: [SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Yep, I'll take a look at this. Looks like the doc needs quite a few updates to accommodate this change.

**Comment by j0rt3g4** [comment]
Changes were made on  #1688

**Comment by scanum** [comment]
@j0rt3g4 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by joshtransient** [comment]
Excellent update! Thank you, team 👍👍👏👏
