### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by docwisdom** [MicrosoftDocs/OfficeDocs-SharePoint#1550]
Well that didnt work

Set-SPOHomeSite : The requested operation is part of an experimental feature that is not supported in the current
environment.
At line:1 char:1
+ Set-SPOHomeSite -HomeSiteUrl https://REMOVED.sharepoint.com/sites/h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOHomeSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SPOHo
   meSite+SetSPHSite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/home-site#feedback)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
See the note at the top of the page. It's a feature that is rolling out to TR tenants _soon_ and the error indicates that it isn't available in your tenant yet.

**Comment by scanum** [comment]
@docwisdom
