### ISSUE TITLE
Sharing a script that worked for a new, large environment of users

### ISSUE THREAD

**Issue by jordonthreadgill** [MicrosoftDocs/OfficeDocs-SharePoint#1554]
$users = get-msoluser -All | ? {$_.islicensed -eq $true}
$count = $users.count
$list = @()
$i = 0
$ii = 0
foreach ($u in $users)
{

$i++; $ii++; write-host "$i of $count"

if ($ii -lt 199)
{
    $upn = $u.userprincipalname
    $list += $upn
    }
if ($ii -gt 199)
{
    Request-SPOPersonalSite -UserEmails $list 
    Start-Sleep -Milliseconds 655
    $list = @()
    $ii = 0
}
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts#feedback)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jordonthreadgill  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
PR #1689

**Comment by erictechtips** [comment]
Thank you jordonthreadgill.  That script worked well and we successfully provisioned all accounts in my organization (90,000+).

**Comment by scanum** [comment]
@jordonthreadgill Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Ellestad1995** [comment]
About the script:
The script doesn't provision the leftover users if the count never reaches greater than 199. 
After the loop finishes, if there are less than 199 users counted in the variable $ii ($j in the doc) they will not get provisioned. I did something similar when provisioning about 1200 users for a new client of mine. 
What must be done is to check **after the loop** if there are leftover users to provision, like this:

```Powershell
if($j -gt 0){
    # provision the leftover users
    Request-SPOPersonalSite -UserEmails $list
}
```

So the whole script would look like this:

```Powershell
$list = @() # Array to hold UserPrinicpalNames to be provisioned. Up to 199 at a time
#Counters
$j = 0 # Provisioning up to 199 counter
$i = 0 # Total progress counter

$users=get-msoluser -All | ? {$_.islicensed -eq $true} #Get licensed users
$count = $users.count #total licensed users

foreach ($user in $users){
    if ($j -gt 199){
        Request-SPOPersonalSite -UserEmails $list
        Start-Sleep -Milliseconds 655 # Short sleep between provisioning requests
        $list = @() # Reset UserPrincipalNames array
        $j = 0 # Reset count
    }
     
    $upn = $user.userprincipalname
    $list += $upn
    $j++; # Count up to 199 limit
    $i++; # Count up the total of processed users
    Write-Host "$i/$count"
 
}

if($j -gt 0){
    Request-SPOPersonalSite -UserEmails $list # provision the leftover users if $j is less than 199 and above 0
}
```

**Comment by jordonthreadgill** [comment]
My only objection to trying to immediately check right after is that this can take up to 24 hours to work on a user's account.  

I see what you're saying about the last 199 though...

It could also be said to just loop all users, since we no longer have to upload files of 200 users at a time.
$list = @()
#Counters
$i = 0; $j = 0
    
#Get licensed users
$users=get-msoluser -All | ? {$_.islicensed -eq $true}
#total licensed users
$count = $users.count

foreach ($u in $users){
    $i++; $j++; 
    Write-Host "$i/$count"
       $upn = $u.userprincipalname
       Request-SPOPersonalSite -UserEmails $upn
       Start-Sleep -Milliseconds 655
}
