### ISSUE TITLE
Issues Unregistering/Swapping/Re-registering a Hub site

### ISSUE THREAD

**Issue by jbhoward** [MicrosoftDocs/OfficeDocs-SharePoint#1555]
I followed the instructions above regarding unregistering a hub site before swapping the to the root. I then reregistered it.

On reregister, it actually acts as though my "hub" is associating with the previous hub, rather than "being" a hub:
1. The hub site navigation isn't editable from the hub,
2. Web parts on the hub homepage don't offer "this hub" scopes, and
3. Sites associated with the hub don't pick up the hub site navigation either.

I've tried unregistering it as a Hub, both in the UI and via PS. I've tried disassociating it with itself, too, and that doesn't work.

Anything I can do... or undo... that will fix it or allow it to clean itself up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jbhoward  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @jbhoward  The description of the issue seems more like a support ticket than a correction on the documentation itself.

**Comment by scanum** [comment]
@jbhoward Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
