### ISSUE TITLE
Rollback SharePoint Hybrid Configuration

### ISSUE THREAD

**Issue by MarwaMS92** [MicrosoftDocs/OfficeDocs-SharePoint#1556]
I can't see any public document that mentions how to rollback/disable this hybrid configuration. Could you please let us know how to achieve this in a proper way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f71bd9-7499-229c-e3b1-a381b27c6915
* Version Independent ID: 80692f9c-0678-e9db-1d89-3e06f4c4a925
* Content: [Hybrid for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/hybrid/hybrid?redirectSourcePath=%252farticle%252fsharepoint-hybrid-4c89a95a-a58c-4fc1-974a-389d4f195383#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hybrid.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@MarwaMS92  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@scanum I can take a look at this one. It is a multi-step process (depends on what has been configured).

**Comment by scanum** [comment]
@tseward Thanks!

**Comment by tseward** [comment]
@scanum @MarwaMS92 this has been addressed in the new article https://docs.microsoft.com/en-us/sharepoint/hybrid/removing-sharepoint-hybrid-scenarios.

**Comment by MarwaMS92** [comment]
Thanks so much , this is very helpful 😊

Thanks,
Marwa Mohamed.

**Comment by scanum** [comment]
@MarwaMS92 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
