### ISSUE TITLE
Error code missing from page

### ISSUE THREAD

**Issue by dneimke** [MicrosoftDocs/OfficeDocs-SharePoint#1557]
There seems to be another error code which is missing from the list on this page `0x02060007`.

From what I can tell, it seems like the sub-site equivalent of `0x02060009`.

I would love to see some more specific guidance relating to this error which is often described as _"This site cannot be created or updated"_.  Are there common reasons as to why a site (or site collection) couldn't be created... other than the 2 more specific problems which are detailed in the article:

* URL is already in use or an invalid URL
* URL contains invalid character

#Migration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshooting SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@dneimke  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
#aded information on  #1691

**Comment by scanum** [comment]
@dneimke Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
