### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by lordherbert** [MicrosoftDocs/OfficeDocs-SharePoint#1558]
Hi, there shouldn't be a space between - and HomeSiteUrl in Set-SPOHomeSite - HomeSiteUrl &lt;siteUrl&gt;.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-gb/SharePoint/home-site#feedback)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by MikePlumleyMSFT** [comment]
Thanks, @lordherbert. Fixed in PR [1561](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1561) by expiscornovus.
