### ISSUE TITLE
Silent Known Folder Move 

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/OfficeDocs-SharePoint#1560]
What should be the behavouir when the folders already exist on the Onedrive location and, there is data inside both online and local folders. Do the folders merge with the local folders silently? We use version 19.192.0926.0012.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BakkerJan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@BakkerJan The article contains a note now which describes the behavior:

"If users already have blocked file types in their OneDrive, the files will sync to their computer, but any changes they make on their computer won't be uploaded."

**Comment by j0rt3g4** [comment]
I've verified @BakkerJan  that it does a Silent Merge it has always been like that ... I would replicate it on another account

**Comment by scanum** [comment]
@BakkerJan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
