### ISSUE TITLE
The message a user gets is No License, which is misleading and license provisioning was expected when raised to O365 support

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/OfficeDocs-SharePoint#1562]
The message "No License" "Please contact your Office 365 admin for assistance."  This was not helpful and O365 had to escalate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96de5069-51dc-3934-ec44-cae3ab121476
* Version Independent ID: 21955afd-18c1-20f0-061f-f552f71fbfc1
* Content: [Hide the OneDrive and SharePoint app tiles - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/hide-app-tiles-on-app-launcher#feedback)
* Content Source: [SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ScottStauffer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@ScottStauffer Are you seing a different message when a users clicks a tile for a service they don't have? The article states they should see a "Access Denied message"

What exactly do you want to have changed within the article? I just want to be 100% clear before requesting any changes to it.

**Comment by j0rt3g4** [comment]
Hello @ScottStauffer, can you clarify what is the issue or what would you like to be changed to the article because it's not clear for us the reason why you create it?
Thank you in advance

**Comment by scanum** [comment]
@ScottStauffer  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
