### ISSUE TITLE
An link to a doc or a Note explaining how to audit this Tenant Setting would be helpful too.

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/OfficeDocs-SharePoint#1563]
Please add details on how to turn on auditing, if it isn't by default, and where to see this, and the category of the auditing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96de5069-51dc-3934-ec44-cae3ab121476
* Version Independent ID: 21955afd-18c1-20f0-061f-f552f71fbfc1
* Content: [Hide the OneDrive and SharePoint app tiles - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/hide-app-tiles-on-app-launcher#feedback)
* Content Source: [SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ScottStauffer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@ScottStauffer There is no native method of auditing if "Show or Hide App Tiles" setting is set to on or off. I guess you could use [SharePoint APIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index) to achieve this goal, but i have not tested it.

I recommend providing this feedback (Add a method to audit this specific setting within SharePoint Online) via [UserVoice for SharePoint](https://sharepoint.uservoice.com/) in order for it to reach the Product Group via the support channel.

**Comment by j0rt3g4** [comment]
Sadly @ScottStauffer  right now that document or article doesn't exist, because that setting is not auditable, other than searching it over the user's interface of the O365 portal.
I'd  recommend you to create a user's voice case on 
https://office365.uservoice.com/
or give support to the existing proposals as:
https://office365.uservoice.com/forums/264636-general/suggestions/36627967-hide-specific-app-tiles-from-office-365-home-or-ap

**Comment by scanum** [comment]
@ScottStauffer Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
