### ISSUE TITLE
Cant connect to anyting other than the 'root' site on sharepoint 201

### ISSUE THREAD

**Issue by russgove** [MicrosoftDocs/OfficeDocs-SharePoint#1564]
Hi, When I try to connect to a site at 
http://test.ns.namakwa.co.za/dept/hr
i get an error message saying:

We are unable to connect to the site you provided. Please check the site URL

The site exists and I am an admin on it.
I can connect to 
http://test.ns.namakwa.co.za   ( the 'root' site) with no issues.

**Comment by russgove** [comment]
This issue is related to the SharePoint Migration tool. trying to migrate from sp 2010 to O365.

**Comment by scanum** [comment]
@russgove 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fruitybasket** [comment]
I got stuck in the same situation. May I know the solution for this error message where SPMT says "We are unable to connect to the site you provided".  Any help on this would be appreciated.
