### ISSUE TITLE
Migration client failed to login

### ISSUE THREAD

**Issue by hristochr** [MicrosoftDocs/OfficeDocs-SharePoint#1567]
It seems I can't login with my admin account via the Migration Client.
Works with my non-admin account. Both accounts have MFA. 
The admin account lacks the "Additional security verification" menu.
![Capture](https://user-images.githubusercontent.com/22388580/69958039-3d41db00-1504-11ea-8ef5-ba5d6318ee79.PNG)

I am guessing this has something to do with how the admin account is configured. Input will be appreciated.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
