### ISSUE TITLE
Step 6 Variables reference is missing.

### ISSUE THREAD

**Issue by pathade90** [MicrosoftDocs/OfficeDocs-SharePoint#1569]
In Step 3 we setup a few variables which worked fine till step 5. The variables used in steps 6 are different from what we used.  Specially $job = Invoke-SPOMigrationEncryptUploadSubmit -SourceFilesPath $sourceFiles -SourcePackagePath $spoPackagePath -Credentials $cred -TargetWebUrl $targetWebUrl

Common variable would be a nice approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b01f633-962a-274d-1769-e008e7049f03
* Version Independent ID: c63b4c45-f5c6-d0fb-e14f-095f79b1a415
* Content: [Upload on-premises content to SharePoint Online using PowerShell cmdlets - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets#feedback)
* Content Source: [migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@pathade90 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
