### ISSUE TITLE
Use CreateSPAsyncReadJob missing LookupListMap.xml

### ISSUE THREAD

**Issue by LeoJiang1988** [MicrosoftDocs/OfficeDocs-SharePoint#1570]
Hi Team,

I use CSOM API CreateSPAsyncReadJob, the export XMLs missing the LookupListMap.xml.

The export list include lookup column. The queue message like:
{"Event":"JobQueued","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:45.938","SiteId":"c96a6c8c-562b-4816-9934-47466cc0c729","DbId":"09ee44f2-ff0c-4981-9d9c-b430ad700828","TotalRetryCount":"0","MigrationType":"AsyncRead","MigrationDirection":"Export","CorrelationId":"450c1e9f-d07e-0000-44ca-8b9b8285e6bf"}
{"Event":"JobStart","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:48.853","SiteId":"c96a6c8c-562b-4816-9934-47466cc0c729","WebId":"00000000-0000-0000-0000-000000000000","DBId":"09ee44f2-ff0c-4981-9d9c-b430ad700828","FarmId":"cc0cd2c1-10de-42b7-b7f9-dfa2a4d8ded3","ServerId":"70d87a5d-b0d3-4973-9235-b694c712dd5e","SubscriptionId":"b377c72b-26c5-4728-bd1f-97beb2f17b34","TotalRetryCount":"0","MigrationType":"AsyncRead","MigrationDirection":"Export","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}
{"Event":"FinishManifestFileUpload","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:50.150","ManifestFileName":"1efa0a61-ec6e-4225-83fe-14196215476c/Manifest.xml","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}
{"Event":"FinishManifestFileUpload","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:50.212","ManifestFileName":"1efa0a61-ec6e-4225-83fe-14196215476c/Requirements.xml","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}
{"Event":"FinishManifestFileUpload","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:50.228","ManifestFileName":"1efa0a61-ec6e-4225-83fe-14196215476c/SystemData.xml","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}
{"Event":"FinishManifestFileUpload","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:50.275","ManifestFileName":"1efa0a61-ec6e-4225-83fe-14196215476c/ExportSettings.xml","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}
{"Event":"JobEnd","JobId":"1efa0a61-ec6e-4225-83fe-14196215476c","Time":"12/04/2019 01:47:50.321","FilesCreated":"4","BytesProcessed":"15501","ObjectsProcessed":"7","TotalExpectedSPObjects":"0","TotalErrors":"0","TotalWarnings":"0","TotalRetryCount":"0","MigrationType":"AsyncRead","MigrationDirection":"Export","WaitTimeOnSqlThrottlingMilliseconds":"0","TotalDurationInMs":"1764.902","CpuDurationInMs":"740","SqlDurationInMs":"161","SqlQueryCount":"12","CreatedOrUpdatedFileStatsBySize":"{}","ObjectsStatsByType":"{}","TotalExpectedBytes":"0","SaveFileTimeMilliseconds":"11","CorrelationId":"460c1e9f-901b-0000-357d-ce21398ef257"}

Best Regards!

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
