### ISSUE TITLE
Why is PS in Intune recommended for AADJ computers?

### ISSUE THREAD

**Issue by JasonG-IT** [MicrosoftDocs/OfficeDocs-SharePoint#1571]
Toward the end of the page (at the time of writing), there's a note that reads as follows:

"If the computers on your network are not connected to Active Directory on-premises, but only to Azure AD, we recommend using Intune and a Microsoft PowerShell script to set the registry keys required to enable silent config."

Administrative templates went GA a few months ago, and one of the available options is named "Silently sign in users to the OneDrive sync client with their Windows credentials."

Is deploying a PS script still the recommended method for enabling silent sign-in, or should simply using the available administrative template be the go-to method in scenarios with no prohibitive requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
- Removed some extra lines
- Fixed PS Code on PR #1700

**Comment by scanum** [comment]
@JasonG-IT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
