### ISSUE TITLE
Sharepoint to sharepoint?

### ISSUE THREAD

**Issue by Bozzl** [MicrosoftDocs/OfficeDocs-SharePoint#1572]
Is it possible to move data from one tenant to another? Both are online.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/nl-be/sharepointmigration/introducing-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
