### ISSUE TITLE
Issue with links inside of the "Plan your Office 365 Launch: Communication and Training Guide" document

### ISSUE THREAD

**Issue by tbailen** [MicrosoftDocs/OfficeDocs-SharePoint#1573]
On https://aka.ms/commandtraining, all of the "Download the kit" links are broken. It looks like the correct target URLs are of the format: https://fto365dev.blob.core.windows.net/media/Default/Resources/LocalizedResources/en-us/&lt;filename.zip&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise#keys-to-successful-user-adoption)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @tariqbell  We'll review where this file should be put I've got then already fixed. thank you
[Office_365_Communication_Guide.docx](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/4076108/Office_365_Communication_Guide.docx)

**Comment by scanum** [comment]
@tbailen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
