### ISSUE TITLE
PowerApps Form Broken

### ISSUE THREAD

**Issue by steevinBradlee** [MicrosoftDocs/OfficeDocs-SharePoint#1576]
I didn't realized that PowerApps associated with a site that has had its URL changed will need to be recreated. A form I put many hours into building is now broken. Why is this not given as an EXPLICIT warning when changing a site's URL? Is there any way to recover forms that have been lost?

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
