### ISSUE TITLE
Is there an active uservoice request to have this exposed in the admin portal?

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/OfficeDocs-SharePoint#1578]
This would be really helpful to have a GUI interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfb6e9b-57d4-749f-a1d0-5f5c24e141ce
* Version Independent ID: e67e1021-7801-477b-1642-43c283742e59
* Content: [Manage site redirects - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects)
* Content Source: [SharePoint/SharePointOnline/manage-site-redirects.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-redirects.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by robertafreese** [comment]
That would be great, thanks for considering it. As it stands, I now have a way in the portal to make redirects that I can't manage or remove.

**Comment by JonathanHerschel** [comment]
Agreed, I take it the redirect will remain there until we remove it?  After we remove the redirect, will the new/correct Url show up as the Site's URL in admin center?  I changed a Sites' URL, but the old siteUrl remains as the text for the URL, but the actual URL has changed.

**Comment by robertafreese** [comment]
I have tried to use the Powershell and it gives an incomplete URL. It has a table of URL Owner and Storage Quota as columns and the URL is truncated as https://TENANT.share... with no owner info displayed before the storage quota amount. This feature is not useful. I cannot run the Powershell command to remove a redirect if I cannot see the full URL. I think you may want to disable it, as I now have two redirects that I cannot manage and other admins may add more.

**Comment by j0rt3g4** [comment]
@JonathanHerschel 
I think you'd need this cmdlet:
 ´´´Powershell
Connect-SPOService
Get-SPOSite -Template REDIRECTSITE#0
´´´
Actually there's none usersvoice related to this on
https://office365.uservoice.com/

**Comment by scanum** [comment]
@robertafreese Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
