### ISSUE TITLE
Silently redirect Windows known folders to OneDrive

### ISSUE THREAD

**Issue by tcjdunkeson** [MicrosoftDocs/OfficeDocs-SharePoint#158]
The documentation is unclear here:

"Use this policy to redirect your users' known folders to OneDrive without user interaction. (You can choose to display a notification to users after their folders have been redirected.) This policy works when all known folders are empty, and on folders redirected to a different OneDrive account. We recommend using this policy together with 'Prompt users to move Windows known folders to OneDrive.'"

Are the known folders empty on premise or in the cloud in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders?redirectSourcePath=%252fen-us%252farticle%252fredirect-and-move-windows-known-folders-to-onedrive-e1b3963c-7c6c-4694-9f2f-fb8005d9ef12)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kenwith** [comment]
@tcjdunkeson - this is fixed now. Thanks @kaarins!

**Comment by djmoz** [comment]
Is there any plan to have the "Silently move Windows known folders to OneDrive" feature available to deploy via Intune and the Admin templates in preview?
