### ISSUE TITLE
Please include required user permissions at the tenant and site level

### ISSUE THREAD

**Issue by paulhaskew** [MicrosoftDocs/OfficeDocs-SharePoint#1581]
Current documentation does not include information that you need to be a site collection admin to perform the migration work, nor what permissions may be required at the tenant level such as a SharePoint Admin. Please consider adding this to the documentation for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@paulhaskew Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solved on PR #1604

**Comment by Matt-Mueller-MSFT** [comment]
Previous comment says, it says this is solved but does not look like the document is updated. When will it be corrected?

**Comment by j0rt3g4** [comment]
Hello @Matt-Mueller-MSFT 
I've created a PR (Pull Request, that you can see it as OPEN)
![image](https://user-images.githubusercontent.com/5489996/73371623-8cde2200-427b-11ea-8ee2-4d323101c98c.png)

Actually is reviewed by @JoanneHendrickson  and she needs to MERGE my content and it will be updated in a week after MERGING. it's the way github works.

**Comment by scanum** [comment]
@paulhaskew Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
