### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MWPatterson2000** [MicrosoftDocs/OfficeDocs-SharePoint#1582]
When I run this against a SharePoint 2013 Site it says your content will be moved.  Does this mean it will delete the data from the On Premise server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@MWPatterson2000 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
I'd say yes.
It will move all your data from one point and save it into another one, I'd use the analogy of "cut/Paste".
Can you confirm this @MikePlumleyMSFT  ?

**Comment by scanum** [comment]
@MWPatterson2000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
