### ISSUE TITLE
O365 Group as root site

### ISSUE THREAD

**Issue by mattwoodbristol** [MicrosoftDocs/OfficeDocs-SharePoint#1583]
It's not clear to me from [this page](https://docs.microsoft.com/en-us/sharepoint/modern-root-site) whether I can convert an O365 Group/Team Site to a root site. Is that possible?

As a complete newbie with the management shell i'm hesitant to do something i might not be able to undo.

**Comment by tseward** [comment]
Per that page:

* The source and target sites can't be connected to an Office 365 group.

But it can be a non-Group connected Modern Team site (STS#3).

**Comment by scanum** [comment]
@mattwoodbristol Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
