### ISSUE TITLE
By default, script is NOT allowed on sites that admins create.

### ISSUE THREAD

**Issue by erkanch** [MicrosoftDocs/OfficeDocs-SharePoint#1584]
I think this is wrong: By default, script is allowed on sites that admins create.
All modern sites that are created by admins are no-scripts sites, meaning DenyAddAndCustomizePages is Enabled.

**Comment by scanum** [comment]
@erkanch Please link the documentation you are reffering to.

**Comment by j0rt3g4** [comment]
@erkanch  waiting for the comment of the author of the ticket.

**Comment by scanum** [comment]
@erkanch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
