### ISSUE TITLE
Scripts broken, code missing

### ISSUE THREAD

**Issue by pjblecha** [MicrosoftDocs/OfficeDocs-SharePoint#1585]
This page is a complete mess. Did anyone proofread after they copied and pasted into it, or was it something that didn't deserve more than 30 seconds of their attention? Missing quotes, commands out of order, blocks of code being referred to that don't exist on the page... wow. This is just crap. How are we supposed to get this done from this crap? Can someone point me to a legitimate knowledge base for setting up SharePoint 2016 on-prem with an ADFS server on-prem? Or does Microsoft just not care any more if you aren't going to the cloud?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4559926-c6e8-03b7-f07c-20adc26c14d6
* Version Independent ID: 7094c31c-64de-5504-d1a4-500478309181
* Content: [Implement SAML based authentication in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
I'll take a look at correcting this documentation/script.

Thanks for bringing it to our attention.

**Comment by j0rt3g4** [comment]
Solved a lot of PS issues on PR #1608

**Comment by scanum** [comment]
@pjblecha Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
