### ISSUE TITLE
Why would someone want to use Azure AD B2B vs SPO/OneDrive Guest/External Sharing?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-SharePoint#1588]
There are many nuances and conflicts riddled throughout the documentation here and elsewhere about B2B API and existing SPO guest/external collaboration; Please include a definitive list of reasons/benefits as to why B2B would be required/needed/preferred as opposed to SPO/OneDrive "native" guest/external collaboration. As of now, my take away is B2B Api is a guest invitation api, that supports direct federation which would allow the partner orgs users to make use of their own IDP.... I thought that maybe it also was the only way to manage external invites to exclude or include only specific domains but that does not appear to be the case... so apart from enforcing a 5:1 ratio... what's the point? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MSFTRafLop** [comment]
@jebalert there are several advantages to using Azure AD B2B with OneDrive/SharePoint. Here are some examples

1. If you’ve configured your organization with conditional access policies that apply to Guests, then they will be respected when external users attempt to access content in OneDrive/SharePoint. The most common example here is MFA.

2. It brings the one-time passcode recipient experience to externally shared sites, document libraries and list items. Without this integration, the OTP experience is only available when sharing files/folders.

3. It allows IT to manage and control Guests in a consistent way rather than needing to learn differences with how SharePoint and OneDrive treat external users compared to the rest of Microsoft 365.

Hope that helps as a start.

**Comment by jebalert** [comment]
@MSFTRafLop thanks for the insight. Number 3 in your list sticks out the most. Does this confirm that SPO/ODfB does not use B2B API's on the backend? I'm curious because another area of documentation was unclear on that matter. I've referenced it here in the feedback section: https://docs.microsoft.com/en-us/azure/active-directory/b2b/o365-external-user. 

Are there plans enforce the utilization of Azure B2B on SPO/ODfB in the future? Some of the documentation on this subject alludes to it, but in other areas it is not obvious.

Lastly, in regards to the Guest User; when making use of Direct Federation, is my understanding of this concept correct in that it does not establish an org relationship or suddenly enlist all users of that org into your directory - on the contrary it simply enables users you invite to make use of their own IdP when authenticating to access your resources? Doesn't seem like direct federation/azure b2b is the way forward to address potential multi tenant orgs sharing the same IdP.

Thanks!

**Comment by j0rt3g4** [comment]
@jebalert  is there anything else we can clarify for you? 
@MSFTRafLop do you think we should add something to the documentation?

**Comment by scanum** [comment]
@jebalert We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
