### ISSUE TITLE
Broken codeplex link

### ISSUE THREAD

**Issue by bkrekacs** [MicrosoftDocs/OfficeDocs-SharePoint#1590]
All codeplex link are broken. Could you please fix it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c517332b-3776-06fb-13f7-c24ff9d87ea8
* Version Independent ID: 4ce992f7-ba2e-cdc1-a3ab-f42c914c5425
* Content: [Configure AdventureWorks for Business Intelligence solutions](https://docs.microsoft.com/en-us/sharepoint/administration/configure-adventureworks)
* Content Source: [SharePoint/SharePointServer/administration/configure-adventureworks.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-adventureworks.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@bkrekacs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@bkrekacs are you indicating that the two CodePlex links need to be swung over to https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks?

**Comment by j0rt3g4** [comment]
Solved on PR #1605

**Comment by scanum** [comment]
@bkrekacs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
