### ISSUE TITLE
I can't create a new Folder for my site

### ISSUE THREAD

**Issue by Olaf-Bentz** [MicrosoftDocs/OfficeDocs-SharePoint#1591]
When I click on "New", I can't choose to create a new Folder (only files)

**Comment by Olaf-Bentz** [comment]
![Capture](https://user-images.githubusercontent.com/58771612/70613398-d78ed680-1c08-11ea-9acf-e30a3009b0c2.PNG)

**Comment by scanum** [comment]
@Olaf-Bentz thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
