### ISSUE TITLE
Purpose of the automatically created crawled and managed properties

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/OfficeDocs-SharePoint#1592]
I'm in the process of troubleshooting a search problem and have discovered that the &lt;columnName&gt;OWSTEXT property is missing. But other fields that have this is working as expected. So I think I can just "chat it" and use a refinable string, but don't know if I can just do this.
What is the purpose og the automatically created crawled and managed properties?
And can I replace the mapping between the ows_q_text_&lt;columnName&gt; and &lt;columnName&gt;OWSTEXT ?

TL;RD: What is the purpose og the automatically created crawled and managed properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215afe55-1f3c-d3ff-df15-ca70ef0b749a
* Version Independent ID: 3cf66b2b-0c3a-fcb6-0300-45855622793f
* Content: [From site column to managed property - What's up with that?](https://docs.microsoft.com/en-us/sharepoint/administration/from-site-column-to-managed-propertywhat-s-up-with-that#feedback)
* Content Source: [SharePoint/SharePointServer/administration/from-site-column-to-managed-propertywhat-s-up-with-that.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/from-site-column-to-managed-propertywhat-s-up-with-that.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@2ndcahl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@2ndcahl We are a documentation team, this is such a technical issue. Please proceed by opening a Technical support ticket

**Comment by 2ndcahl** [comment]
I’m not trying to solve my issue here. I’m just trying to tell that the document says “We create these extra columns” but don’t tell why these extra columns are created.
My description of my technical issue is about how that information could be useful. Sorry for the confusion.

Mvh
Anders Lund
2ndC A/S
31 64 34 57
________________________________
Fra: Jose Gabriel Ortega Castro <notifications@github.com>
Sendt: Sunday, December 15, 2019 1:26:18 AM
Til: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
Cc: Anders H. Lund <AHL@2ndc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Purpose of the automatically created crawled and managed properties (#1592)


@2ndcahl<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F2ndcahl&data=02%7C01%7C%7Cb070afb4a6714386ef1508d780f567df%7Cced97294935e4250a0675960109f4c09%7C1%7C0%7C637119663817067754&sdata=4VGCryztZTyvwayrE%2BXvbp5IGezNe6bjejQNyUyDoeM%3D&reserved=0> We are a documentation team, this is such a technical issue. Please proceed by opening a Technical support ticket

**Comment by 2ndcahl** [comment]
I’m not trying to solve my issue here. I’m just trying to tell that the document says “We create these extra columns” but don’t tell why these extra columns are created.
My description of my technical issue is about how that information could be useful. Sorry for the confusion.

**Comment by scanum** [comment]
@2ndcahl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
