### ISSUE TITLE
WVD

### ISSUE THREAD

**Issue by Rudolf112** [MicrosoftDocs/OfficeDocs-SharePoint#1594]
...is no longer in preview as the second bullet suggests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc677c5-4514-fb8b-a864-4edd711d6f44
* Version Independent ID: 1e3dbf59-48d4-2696-ad8a-7f9cb60871ec
* Content: [Use the sync app on virtual desktops](https://docs.microsoft.com/en-us/onedrive/sync-vdi-support)
* Content Source: [OneDrive/sync-vdi-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-vdi-support.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Rudolf112 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solved on PR #1606

**Comment by scanum** [comment]
@Rudolf112 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
