### ISSUE TITLE
User Licensing and Deletion

### ISSUE THREAD

**Issue by fox-on-the-run** [MicrosoftDocs/OfficeDocs-SharePoint#1596]
[Enter feedback here]
Hi there, as far as I know users need to have an Intune license, otherwise policies cannot be applied. Additionally, as I saw from tests, disabling the policy does not remove the policy from Intune. Please remark this too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb73e568-9145-abd7-a0fe-4b03bdb875ee
* Version Independent ID: 8036cdd2-2877-e9cd-2878-04121ab9666c
* Content: [Control access to features in the OneDrive and SharePoint mobile apps](https://docs.microsoft.com/en-us/onedrive/control-access-to-mobile-app-features?redirectSourcePath=%252farticle%252fd25713bb-5cf8-4874-9b5b-e8bee3b94f13#feedback)
* Content Source: [OneDrive/control-access-to-mobile-app-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-to-mobile-app-features.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@fox-on-the-run Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @fox-on-the-run  The 1st line on the article says clearly what you need: *Microsoft Intune* or *Enterprise Mobility + Security*. The only way you can have Microsoft Intune is if you have a license.

**Comment by j0rt3g4** [comment]
Added a note in PR #1607

**Comment by scanum** [comment]
@fox-on-the-run Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
