### ISSUE TITLE
Lack of root url modification

### ISSUE THREAD

**Issue by smpltechno** [MicrosoftDocs/OfficeDocs-SharePoint#1599]
Some deviant signed up our tenant using Companyname0 for some strange reason .... now anything in SP is referenced as Companyname0.sharepoint.com - we are about to move a ton of services over to SP and the mis-naming is causing a huge nightmare... the ability to change the root domain url is crucial - or at least the option to wipe everything out in SP and start from scratch - I cant even do this without cancelling the entire tenant and starting from scratch (mail is already online in Exchange - so this is not an option).

**Comment by tseward** [comment]
Yes, that is correct. It is currently not possible to change the SharePoint Online tenant URLs.

**Comment by scanum** [comment]
@smpltechno Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
