### ISSUE TITLE
The migration tool is only supported for SharePoint 2013 sources? Is there a plan to support SharePoint 2010?

### ISSUE THREAD

**Issue by johncallaway58** [MicrosoftDocs/OfficeDocs-SharePoint#16]
I have attempted to connect to a SharePoint 2010 endpoint and I get an error. "The SharePoint version is not supported."
My first clue is that it does say "SharePoint 2013 Site URL" when asking for the source.

**Comment by JoanneHendrickson** [comment]
At this time only SharePoint 2013 is supported.
