### ISSUE TITLE
Error-2 OneDrive.admx & OneDrive.adml

### ISSUE THREAD

**Issue by awcarver** [MicrosoftDocs/OfficeDocs-SharePoint#160]
I've added the files to the location specified as directed but now I get an Error-2 Parsing error when trying to create a GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy?redirectSourcePath=%252fen-us%252farticle%252fuse-group-policy-to-control-onedrive-sync-client-settings-0ecb2cf5-8882-42b3-a6e9-be6bda30899c)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by Absoblogginlutely** [comment]
You need to put the admx file in the C:\Windows\SYSVOL\sysvol\dnsdomain\Policies\PolicyDefinitions folder and then put the adml file in the appropriate language directory such as en-us. They do not both go in the same directory.

**Comment by awcarver** [comment]
That corrected the issue! Thank you very much!

**Comment by kenwith** [comment]
@Absoblogginlutely - this would be a great note to put in the doc. I tried to take a stab at it but wasn't sure where to put the information in the doc. Would you be open to submit a Pull Request to add this info to the doc? I can guide you on it. You can see instructions in the README here and in the video in the README: https://github.com/MicrosoftDocs/office-docs-powershell   (note, it is a different repo but making edits are same). You can find the source for the article in the "Content Source:" label at top of this issue.

Or if you just want to guide me I can add the PR too.

**Comment by kaarins** [comment]
Thanks, @Absoblogginlutely ! I updated the steps to clarify, and am publishing the change.

**Comment by kenwith** [comment]
Awesome, thanks!
