### ISSUE TITLE
onprem sharepoint server to sharepoint online

### ISSUE THREAD

**Issue by onkarthg** [MicrosoftDocs/OfficeDocs-SharePoint#1600]
we are migrating onprem sharepoint server to share point online using sharepoint tools so when we try to migrate it. it will provide error. 
ERROR-The host name of side you provided cannot be resolved. please cheack URL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dccdf92-2869-83ce-1565-d50b4b84729f
* Version Independent ID: ea4ef549-4335-b6c3-d902-996847ca663b
* Content: [Introduction to SharePoint Online - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/introduction)
* Content Source: [SharePoint/SharePointOnline/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/introduction.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@onkarthg  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by onkarthg** [comment]
@scanum Thank you for update.
