### ISSUE TITLE
How do I migrate content to PRIVATE channels?

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/OfficeDocs-SharePoint#1602]
I can't find private channels in the migration tool (they are simply not shown).

And since I cannot convert a non-private-channel to a private channel, I can't migrate the content and make the channel private later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by RipRapRob** [comment]
I solved it myself: 

A private channel is in fact a completly different SharePoint-site so for each private channel you have to find the corresponding Sharepoint-site 😯

Please include in the documentation.

Thanks.

**Comment by scanum** [comment]
@RipRapRob Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
