### ISSUE TITLE
sharepoint to sharepoint online migration Tools

### ISSUE THREAD

**Issue by onkarthg** [MicrosoftDocs/OfficeDocs-SharePoint#1609]
I tried yesterday to migrate the subfolder form sharepoint server website to online sharepoint communication site link but the sharepoint migration tool doesn't accept the communication site link.

following error is Occured.

![rock](https://user-images.githubusercontent.com/54263809/70859457-db3c9900-1f39-11ea-934e-6a795bc74412.JPG)

**Comment by scanum** [comment]
@onkarthg thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
