### ISSUE TITLE
Block or limit access to a specific SharePoint site or OneDrive

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#1610]
Hello,
Regards "Block or limit access to a specific SharePoint site or OneDrive"
4. Under Conditions, select Client apps, then select both Mobile apps and desktop clients and Browser.
Not possible to select only "Mobile apps and desktop clients", the sub-selection should be done. Please update doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-specific-sharepoint-site-collections-or-onedrive-accounts)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
While this portion of the feature is in a preview state, it is possible to select "Mobile apps and desktop clients".

**Comment by lightupdifire** [comment]
Hello @tseward 
Please explain, from my side not possible:
![image](https://user-images.githubusercontent.com/39700914/71238028-5d92d780-2303-11ea-922a-55ef86ae18b7.png)

**Comment by tseward** [comment]
"Mobile apps and desktop clients" requires a sub-selection. When you check that box, by default it does select certain options (sorry, didn't record which ones).

**Comment by lightupdifire** [comment]
@tseward 
If I try, then all checked in, but this is not as in article...
![image](https://user-images.githubusercontent.com/39700914/71344861-02135480-2564-11ea-9856-8e86683ce722.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
