### ISSUE TITLE
Setup changed

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#1611]
Hello,

We have created "limiting download" policy (apply in SPO limiting download and used a default setup of AAD-CA) in February 2019 and assign it to all users, was working before December 2019:

1.            Internal Azure AD users – limited download, this works correct now
2.            B2B Azure AD users – limited download, this works correct now
3.            Share a file from SharePoint site or OneDrive to fully external user, not a B2B/Guest  - limited download, this stop work in December 2019

Because 3rd option of the previous setup stops work, we re-build the same policy and current policy, with same settings, of December 2019:

1.            Internal Azure AD users – limited download, this works correct now
2.            B2B Azure AD users – limited download, this works correct now
3.            Share a file from SharePoint site or OneDrive to fully external user, not a B2B/Guest  - not limiting download

Can you please help to understand what is by design for the "limiting download" policy? 
We think maybe policy in February was working wrong and now it works correctly? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-specific-sharepoint-site-collections-or-onedrive-accounts)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lightupdifire** [comment]
Hello @scanum, 
By talking to Microsoft support, they try to say, that if a file is shared with the user and user don't have Microsoft account, then the limitation will not apply.
From my side, by reading this article, nothing is telling about this "exception", only opposites, the article is warning that "External users will be affected when you use conditional access policies to block or limit access from unmanaged devices." but this not happening anymore, if file shared to External user, then External user can download file... So "Control access from unmanaged devices" cannot control users who don't have Microsoft account... like protection without protection...
So this brings me to a question to this article, I think it is missing more detailed information what exactly will be limited if this solution deployed as "Allow limited, web-only access".
