### ISSUE TITLE
This is available but not working for classic experience site (30GB size) with managed metadata navigation

### ISSUE THREAD

**Issue by patidarpankaj** [MicrosoftDocs/OfficeDocs-SharePoint#1612]
I tried this, its working on a newly created site collection but failing on a existing site collection of 30GB size with managed metadata navigation and in classic experience mode. Please let me know if there are limitations to the application of this functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
