### ISSUE TITLE
Detailed Report with Mapped Permissions

### ISSUE THREAD

**Issue by ranjithsingh7** [MicrosoftDocs/OfficeDocs-SharePoint#1614]
Hi,

Presently the tool does not provide the detailed item wise / folder wise / sub folder wise permissions mapped. Without this, it will be difficult to cross-verify the permission mapped between on-premise File Server vs Migrated Document Libraries. Any help is much appreciated.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
