### ISSUE TITLE
Please clarify how Retention impacts this

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#1619]
Please document what happens IF you permanently delete, but there is a retention policy as well. The retention policy should over-rule and you should still be able to recover the documents. HOW?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3384358-57c3-7117-f4c4-5da891cbf2fd
* Version Independent ID: e253e442-722d-acc7-1155-ee90ed1c324f
* Content: [Restore a deleted OneDrive](https://docs.microsoft.com/en-us/onedrive/restore-deleted-onedrive)
* Content Source: [OneDrive/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
If a retention policy enables this to take relevance over the deletion process.


So a person can delete a file permanently on outlook but those files are still recoverable using the content search options.

**Comment by anyITsolution** [comment]
I believe the request was to supply us with the powershell commands that you describe can be used when the 30 days have gone by: After seven days, the OneDrive for the deleted user is moved to the site collection recycle bin, where it is kept for 93 days ) will there be an update showing such commands?

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
