### ISSUE TITLE
Limit All is in the wrong place on the PowerShell command

### ISSUE THREAD

**Issue by dubahu** [MicrosoftDocs/OfficeDocs-SharePoint#162]
It should be Get-SPWebApplication | Get-SPSite  -Limit All | Format-Table -Property URL,ContentDatabase
Otherwise you get an error because get-spwebapplication doesn't know what to do with -Limit All

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6520bb3-81b9-3834-906a-5af3afc0ef1c
* Version Independent ID: a588621a-ada7-847c-97ab-0ab741cf207c
* Content: [View all site collections in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/view-all-site-collections)
* Content Source: [SharePoint/SharePointServer/sites/view-all-site-collections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/view-all-site-collections.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by kenwith** [comment]
@dubahu - Thank you for the catch and for taking the time to submit feedback. It is really appreciated! 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better.

I made a note to request the team to update this when the work is complete.

**Comment by bentoncity** [comment]
@dubahu - I've revised this PowerShell command as per your suggestion and republished this topic.
