### ISSUE TITLE
Why I can only save the report in "Documents" library

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint#1621]
When Running the "Shared with external users" Why can't the user chose another library but only "Documents"? 
Also, Why can't we have who shared the file/ folder with the external user and when it happened.
These are very important pieces of information

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
