### ISSUE TITLE
cannot rename url of a sharepoint site

### ISSUE THREAD

**Issue by ottofit** [MicrosoftDocs/OfficeDocs-SharePoint#1622]
I am unable to rename sharepoint site either via web interface and via powershell with 
`Start-SPOSiteRename -Identity  https://xxx.sharepoint.com/sites/CostBook54 -NewSiteUrl  https://xxx.sharepoint.com/sites/CostBook -ValidationOnly`

The new name has been used for a previous site which has been taken out of retention policy, deleted and after that recycle bin has been emptied and verified with powershell  
`Get-PnPTenantRecycleBinItem | % { Clear-PnPTenantRecycleBinItem -url $_.url }
Remove-SPODeletedSite -Identity https://xxx.sharepoint.com/sites/CostBook`

error is
```

PS C:\Users\name> Start-SPOSiteRename -Identity  https://xxx.sharepoint.com/sites/CostBook54 -NewSiteUrl  https://xxx.sharepoint.com/sites/CostBook 
CorrelationId: 12ca229f-40a5-2000-3a1b-f5ec4483f3fa
Start-SPOSiteRename : Something is wrong, please check your parameters and retry later.
At line:1 char:1
+ Start-SPOSiteRename -Identity  https://xxx.sharepoint.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOSiteRename], Exception
    + FullyQualifiedErrorId : Something is wrong, please check your parameters and retry later.,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename
 
Start-SPOSiteRename : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Start-SPOSiteRename -Identity  https://xxx.sharepoint.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-SPOSiteRename], RestApiClientException
    + FullyQualifiedErrorId : Microsoft.Online.SharePoint.PowerShell.RestApiClientException,Microsoft.Online.SharePoint.PowerShell.StartSPOSiteRename

```

**Comment by tseward** [comment]
Please open a support ticket at admin.microsoft.com.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
