### ISSUE TITLE
SPMT New Error Code 0x01310011 - Failed to Read the file:Cannot populate web parts

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1625]
Hi Team,

I am getting an error while migrating the site from SP 2013 to Online. The error code is 0x01310011 and message for error is "Failed to Read the file:Cannot populate web parts".
The web parts are Content Editor Web Part, Script Editor and XsltListViewWebPart. I ran the job 3 times and getting same error.

Can you please help me on this errors.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by PrabhaSP2010** [comment]
Hi Scanum,
Thanks for update!
I don't have access to raise the service ticket. will try from my end to find the root cause of issue.
