### ISSUE TITLE
Sharepoint tenant rename

### ISSUE THREAD

**Issue by smpltechno** [MicrosoftDocs/OfficeDocs-SharePoint#1626]
It might be understandable "you have to abandon your entire sharepoint and start from scratch", maybe even onedrive docs, but instead "you have to junk your entire tenant, scrap your mail and all other content and start a new O365 account" - that is next to impossible for many users to interrupt their business like that just to rename the sharepoint root url... instead my users are looking at Box.com - they will move from an airplane to a bicycle for travel now.

**Comment by tseward** [comment]
This feature is not yet available but is under development.

**Comment by smpltechno** [comment]
That is encouraging to hear .... I would like to be on the beta test list if possible. ;)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
