### ISSUE TITLE
Cannot add multiple Owners with semi-colon delimited string after provisioning

### ISSUE THREAD

**Issue by etherjack** [MicrosoftDocs/OfficeDocs-SharePoint#1627]
When creating a new O365-connected Team site, I can paste in a semi-colon delimited string to add multiple people to the Owner list at the same time. But, after the site is provisioned, this does not appear to work. Adding any additional Owners post-provisioning is requiring me to enter a single user, one at a time.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
