### ISSUE TITLE
'Respect default organization settings' checkbox details should be removed from article

### ISSUE THREAD

**Issue by viralnaik77** [MicrosoftDocs/OfficeDocs-SharePoint#1628]
Article should be updated to reflect following changes for #6 and #7
- 'Respect default organization settings' checkbox is no longer available in ExternalSharing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default sharing link for a site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-default-sharing-link?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
This setting is still present as directed by that page.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
