### ISSUE TITLE
Getting Access Denied while running the build 

### ISSUE THREAD

**Issue by dashimanshu** [MicrosoftDocs/OfficeDocs-SharePoint#163]
I am getting Access Denied while running the application. It installed perfectly but while running the access denied error comes in. I am using Windows 10 and planning to test SP 2010 to SharePoint Online migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@dashimanshu - thank you for submitting feedback. 

I don't think you should be getting an error so I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. They will be able to escalate to a service engineer and get this figured out for you. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by samstarzy** [comment]
I'm experiencing the same problem, only I am using SP 2013. I am able to verify my credentials for the on-prem site, and then when I start the migration, the app says my account does not have enough permissions (I am an owner for the site.)

**Comment by TickoBoston** [comment]
I have experienced the same issue only to discover that you have to be a Site Collection Administrator.
This is unfortunate, since it prevents us from delegating migration tasks to site owners.

**Comment by AndreaBarr** [comment]
@dashimanshu Thank you for this feedback


It appears that you need to open a ticket at was referanced and that should resolve this issue. 


@TickoBoston @jfetrow Thank you for also contributing to this feedback. 

If you are having this same issue please submit a ticket to support so we can get this addressed properly. Based on the outcome please let me know if it's something we can point out in the docs. 


Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
