### ISSUE TITLE
SPMT - OOTB and Designer Workflow are not Migrating

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1630]
Hi,

SharePoint Migration Tool (SPMT) is not migrating out of the box (OOTB) and SP Designer workflows.
Can you please provide any alternative solution to migrate the workflows through SPMT

**Comment by tseward** [comment]
You can vote for this feature here:

https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-and-migration/suggestions/38809024-migrate-workflow-definitions

Otherwise, you'll need to use a 3rd party tool. My personal preference is Sharegate.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
