### ISSUE TITLE
You or your

### ISSUE THREAD

**Issue by DavidApps2** [MicrosoftDocs/OfficeDocs-SharePoint#1632]
Please check whether you have mixed up the words "you" and "your". A grammar check facility might help you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f3baf1-62a6-348a-8f7d-25ba27d7b292
* Version Independent ID: 520aaaa6-1d41-9712-0dd6-67a8ff586f3b
* Content: [How SharePoint Online and OneDrive safeguard your data in the cloud - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/safeguarding-your-data#feedback)
* Content Source: [SharePoint/SharePointOnline/safeguarding-your-data.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/safeguarding-your-data.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@DavidApps2 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@DavidApps2 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by DavidApps2** [comment]
Thank you.
