### ISSUE TITLE
SharePoint 2016 and 2019 support

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#1633]
Does the tool support migration from SharePoint 2016 and 2019 to SharePoint Online? If not, is there any plan for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support? - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt#feedback)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
Not at this time. Microsoft focused on the most common/legacy platforms first. You can find and vote on user voice items for support of these platforms.

https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365?query=2019

**Comment by scanum** [comment]
@LuigiBruno Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by LuigiBruno** [comment]
> Not at this time. Microsoft focused on the most common/legacy platforms first. You can find and vote on user voice items for support of these platforms.
> https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365?query=2019

Thank you @tseward.
