### ISSUE TITLE
PnP Poweshell - PnP Commands slow execution

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1635]
Hi Team,

I have an requirement to insert between 500 to 15000 records into the list in SharePoint online site on everyday. I was trying to use the pnp commands but the commands are taking minimum 2 hours to insert the 5000 records.

Can you please let me know, what could be the reason for slow execution.

**Comment by scanum** [comment]
@PrabhaSP2010 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
