### ISSUE TITLE
Wording regarding effects on PowerApps and Flows

### ISSUE THREAD

**Issue by LeonSig** [MicrosoftDocs/OfficeDocs-SharePoint#1636]
Wanted to leave a note for anyone that may be reading this documentation. The descriptions for what happens to PowerApps and Flows should be updated since saying that both need to be "recreated" seems a bit misleading.

After changing the site URL, it seems that with the changes to Flow (now Power Automate) existing flows are automatically updated to the new site URL.

As for PowerApps, you need to reconnect the app to your data source. Start by deleting the existing SharePoint connections to any lists you may have before you reconnect to your data.  Once you've done that, reconnect your app to the SharePoint lists you were using. Most fields should update automatically. Certain types seem to have trouble and can be fixed by simply deleting the field and then undoing the delete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@LeonSig Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@LeonSig thank you for pointing this out and helping improve MS Docs.  I'll look into having the wording changed for clarification.

**Comment by lindspea** [comment]
@kaarins please let me know if we can elaborate on the PowerApps and Flows and if I can add the suggested information in a PR.

**Comment by j0rt3g4** [comment]
Comments taken on PR #1696

**Comment by scanum** [comment]
@LeonSig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
