### ISSUE TITLE
Results of 2019 SPO Tenant Rename Survey - forward backlog item? 

### ISSUE THREAD

**Issue by OnewebAP** [MicrosoftDocs/OfficeDocs-SharePoint#1638]
I understand that there was a survey performed in early 2019 (https://aka.ms/SPO-RenamePilot) which was aimed at addressing this customer requirement.

Is there a review on where this is leading to in regard to the forward 365 roadmap and whether this feature is on the 2020 horizon or not? 

I believe many customers would welcome a clear view as to whether 'it isn't possible to change' is a permanent limitation, or one that Microsoft is still aiming to address, and therefore avoid the prospect of a tenancy migration.

Welcome feedback from the SPO product team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name#feedback)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
This isn't a docs topic but instead a Uservoice one. It isn't on the Microsoft 365 roadmap yet, which means it isn't quite ready - https://www.microsoft.com/en-us/microsoft-365/roadmap.

**Comment by scanum** [comment]
@OnewebAP thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
