### ISSUE TITLE
"Manage External Sharing" link missing for SharePoint admin

### ISSUE THREAD

**Issue by Rocket101101** [MicrosoftDocs/OfficeDocs-SharePoint#1640]
As a SharePoint admin, my user can see the OneDrive tab for user and the related links like "Create link to file", "Manage data retention". However the "Manage external sharing" link is missing under Sharing section. 

I can confirm the function itself should be okay. Sign in as the same SharePoint admin user and run PowerShell Set-SPOSite -Identity $ODBURL -SharingCapability Disasbled, the poweshell script is working.

Global admin will not have the issue. Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Change the external sharing setting for a user's OneDrive](https://docs.microsoft.com/en-us/onedrive/user-external-sharing-settings?source=docs#feedback)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by Rocket101101** [comment]
Here is the screenshot.
![Screenshot_1](https://user-images.githubusercontent.com/48820042/71656754-99a05080-2d77-11ea-8934-6119b8805892.png)

**Comment by scanum** [comment]
@Rocket101101 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Rocket101101 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
