### ISSUE TITLE
SharePoint Modern Design understanding permissions levels

### ISSUE THREAD

**Issue by GamalielCorona** [MicrosoftDocs/OfficeDocs-SharePoint#1646]
Hi there, thanks for this information, is there any plan to update this page or create a new one to describe permissions level for SharePoint Modern Design? there are many settings on this document that are not available on the new SharePoint, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels#feedback)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@GamalielCorona Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @GamalielCorona, thank you for your feedback.

Maybe it's the article you're looking for:
https://docs.microsoft.com/sharepoint/modern-experience-sharing-permissions

**Comment by scanum** [comment]
@GamalielCorona Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
