### ISSUE TITLE
Confused: OneDrive in a SharePoint page

### ISSUE THREAD

**Issue by JohnMegens-SMC** [MicrosoftDocs/OfficeDocs-SharePoint#165]
I tried to find how I can see who are my Admins, and came acros this page that suddenly states OneDrive in a page about SharePoint. No intro, just BANG Add/remove admins OneDrive. A COPY-PASTE issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kenwith** [comment]
@JohnMegens-SMC - I see what you mean and we will get this resolved ASAP. Thank you for taking the time to report this one! Much appreciated.

**Comment by AndreaBarr** [comment]
@JohnMegens-SMC Thank you for this feedback. 

I have added this to the SharePoint teams backlock to get this addressed.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by AndreaBarr** [comment]
It looks like Trevor has resolved this issue. I am going to close this issue as resolved. If this issue is not resolved please re-open this issue.
