### ISSUE TITLE
Documents as List Item Attachments are Not Audited

### ISSUE THREAD

**Issue by suhood** [MicrosoftDocs/OfficeDocs-SharePoint#1655]
[Enter feedback here]
The documentation needs to be clarified in the Audit section that view List Item Attachments are no longer audited for SP 2016 or SP 2019.  List Item Attachments are listed as documents, but the documents listed in the article refer to Document Libraries and not documents attached to a list item.  This is confusing to customers who believe it should work as in SharePoint 2013 days or if they just simply want document views to be audited.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2d05a9-ef09-ce9f-d7b8-80535608f3d9
* Version Independent ID: 4c5ddcca-451f-5276-5f85-7663b54bc7d5
* Content: [Plan for information management policy in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/information-management-policy-planning)
* Content Source: [SharePoint/SharePointServer/governance/information-management-policy-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/information-management-policy-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@suhood  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kaarins Kaarin as what the user says here is sensitive, I would like you to confirm this with your reach to Product Group information, in case we have a confirmation I can make an addition of the information into this article. thank you

**Comment by get-itips** [comment]
@kaarins Kaarin can you help us here ? Thank you 👍

**Comment by kaarins** [comment]
The feature owner verified that create, read, update, and delete operations on attachments are audited.
