### ISSUE TITLE
Is Azure Storage fee needed?

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-SharePoint#1657]
There are no explanation about Azure Storage fee in [Requirements and costs] section. If Azure Storage needs fee and use premium storage, it will take large amount of fee.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0386fc0-8592-8798-65ad-e6dfc18a6334
* Version Independent ID: c7767a55-cd31-a472-d039-76d07178ab27
* Content: [How to migrate your file share content to SharePoint Online using the Azure Data Box - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-migrate-file-share-content-to-spo-using-azuredatabox#feedback)
* Content Source: [migration/how-to-migrate-file-share-content-to-SPO-using-AzureDataBox.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-migrate-file-share-content-to-SPO-using-AzureDataBox.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
No fee is incurred for migration from on-prem to SPO, including Azure storage and networking.

**Comment by scanum** [comment]
@takeakitake thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by takeakitake** [comment]
Thanks for your quick reply! I would like to make sure.
In below "Azure Data Box family pricing" page is written "Standard storage rates and transaction fees charged separately."

https://azure.microsoft.com/en-us/pricing/details/databox/

And SPMT with Azure Data Box migration uses Azure Files.
However in case of migration from on-prem to SPO, Azure Files is no fee. Is this understanding correct?

If It is correct, I can use it more easily. That's good news for me. 
And I think it is good to write it clearly in this page. It will make accelerate migration to SPO.

**Comment by tseward** [comment]
@takeakitake for the express purposes of using Azure for migration to SPO, there is no fee for using the *default* settings. If you choose to use your own Azure blob storage instance for the migration (you can in 3rd party products, I don't recall for SPMT if you can explicitly set your own Azure blob storage destination), you *would* incur a cost.

Data box isn't related to SPMT as that involves shipping data through a postal carrier.

**Comment by takeakitake** [comment]
@tseward
Thank you!
I understood that there is no fee for Azure storage if we use SPMT default settings.

@scanum
I understood I need to confirm about Azure Files fee before submitting feedback.
Thank you.
