### ISSUE TITLE
Building 2nd Web App for SharePoint using Azure Script

### ISSUE THREAD

**Issue by ltenison** [MicrosoftDocs/OfficeDocs-SharePoint#166]
Kudos for creating this script to build a single-server SharePoint 2016 test farm in Azure.  Saved me a lot of time.  One of the nicest features is how it opens up a public IP address for the web server and main portal web app, so that I can run SharePoint from my PC without a VPN.  However, this creates an issue -- how to build a second web app for Personal OneDrive sites like we normally do, and have a public IP address for that web app as well.  There may be more than 1 way to do this, I am not sure which is the "best" way.  Do you have a script addition that would allow me to create a new "Mysites" host web app in this scenario?  

Thanks,
Larry Tenison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/SharePoint/administration/sharepoint-server-2016-dev-test-environment-in-azure#feedback)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by tseward** [comment]
You would just create a second web app with the same IP:Port binding (it will be "*" and hopefully you're using SSL, so "*:433"). This is very common practice.

**Comment by ltenison** [comment]
Trevor, thanks for the quick feedback and suggestion.  I'm sorry, but I think things are a bit more foggy than I may have implied in my OP.  Yes, for sure -- in a "normal" production farm build, we always procure valid certs and use them for SSL binding on all our web apps.  However, this instance is the result of a script I used to build a small dev/test SP2019 preview farm in Azure and it did things a certain way.  For example:
1. created a VNET
2. put some firewall rules on the VNET to allow http from the Internet and RDP traffic
3. created a public IP for the web front end
4. created a NIC w/ a static IP internally from the VNET
5. associated the PIP to the NIC
6. built the VM on the VNET w/ the ipconfig of the NIC and the PIP associated (all in one move)

So the single server farm came up w/ all port 80 traffic routed through from the <mainwebapp> westus cloudapp Internet PIP to the internal NIC static IP address.  Meaning I have the ability to log into the farm from my PC or anywhere else using proper domain credentials, which is convenient.  There is (apparently) a DNS host record someplace in Azure for my main web app that points to my VNET and to that particular NIC IP address.  What I'd like to be able to do is create a 2nd DNS host record for "<mainwebapp>-my.westus.cloudapp.azure.com" and then set an AAM to the "-my" web app mysite host, like I did for the main web app.  Maybe there's no way to do that, but that's what I was hoping to do.

I'd like to leverage what I have built so far, if that's possible, so as not to defeat the purpose of the handy build script I used.

**Comment by kenwith** [comment]
@ltenison - this is amazing what you are putting together. I could see it being very valuable for other SharePoint experts as well. I don't know the answer to your question but will loop in @JoeDavies-MSFT who I believe created the scripts. I am going to set this to closed since I don't have an answer but just replying will re-open this issue. I am not sure if Joe has time to look into this but he is just down the hall from me and I will ping him about it. Thanks for taking the time on this and providing the detail information too!
