### ISSUE TITLE
User and computer joined in domain but outside Organization

### ISSUE THREAD

**Issue by warleygr** [MicrosoftDocs/OfficeDocs-SharePoint#1662]
Does the user will be allowed to sync the files outside organization?

E.g.: If the user is in a client or traveling and is using his laptop (domain joined), will be able to sync the files?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by warleygr** [comment]
And does it work for both OneDrive desktop app and web?

**Comment by tseward** [comment]
Yes, the computer's domain is identified based on a GUID.

**Comment by scanum** [comment]
@warleygr thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
