### ISSUE TITLE
missing upgrade of App Management and Subscription Service Application Databases

### ISSUE THREAD

**Issue by rgshah26** [MicrosoftDocs/OfficeDocs-SharePoint#1663]
This request is part of ticket # 17973542 / 119121721001149
Please update this documentation to include steps to upgrade App Management and Subscription Service Application Databases.

**Comment by tseward** [comment]
Target doc is https://docs.microsoft.com/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016#upgrade-the-search-service-application.

**Comment by tseward** [comment]
@scanum please assign this one to me. @rgshah26 please keep our Yammer thread updated for outcomes from your case.

**Comment by scanum** [comment]
@tseward Hi Trevor! Any updates on this? Thanks!

**Comment by tseward** [comment]
@rgshah26 did you get an update to your support case?

**Comment by scanum** [comment]
@rgshah26 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
