### ISSUE TITLE
App Catalog site collection Lock status and its repercussions on other site collections in web app

### ISSUE THREAD

**Issue by kiranbellala** [MicrosoftDocs/OfficeDocs-SharePoint#1664]
App Catalog's lock status should never be set to No Access. If App Catalog is locked, then rest of the site collections in that web app will not be accessible. When you access other site collections, you will receive error : Sorry something went wrong. Access to this web site has been blocked and the error does not produce correlation id. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c53cb08-4210-46d6-768b-a67f4f9edb62
* Version Independent ID: 87869d0e-6fe8-2740-77ac-1fd37c3b1962
* Content: [Manage the App Catalog in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-app-catalog)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-app-catalog.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@kiranbellala  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kiranbellala 
To evaluate if an addition to the documentation to warn about this is needed, I tried to reproduce in my lab, however I could not, I still can access other SCs, which version of SharePoint Server are you using?
Thanks

**Comment by scanum** [comment]
@kiranbellala We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
