### ISSUE TITLE
Links in "See also" section are broken or go to wrong place

### ISSUE THREAD

**Issue by mcox13579** [MicrosoftDocs/OfficeDocs-SharePoint#1665]
Two of the four links in the "See also" section are broken or go to the wrong place.  The 3rd link, "Deploying SQL Server 2016 PowerPivot and Power View in SharePoint 2016" is broken - it displays a 404 Page not found error.  The 4th link, "Deploying SQL Server 2016 PowerPivot and Power View in a Multi-Tier SharePoint 2016 Farm" takes you to a very generic page entitled, "Install SQL Server Business Intelligence Features" which does not talk about multi-tier SharePoint 2016 farm at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4cc69b-80e7-c15c-b921-9132552639e9
* Version Independent ID: ea9b2f81-eec8-4c7e-e288-0c57d0952267
* Content: [Software requirements for business intelligence in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/software-requirements-for-business-intelligence#feedback)
* Content Source: [SharePoint/SharePointServer/administration/software-requirements-for-business-intelligence.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/software-requirements-for-business-intelligence.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@mcox13579  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@mcox13579 Thanks for pointing this out and helping improve MS Docs. I'll have a look and get it sorted soonest.

**Comment by scanum** [comment]
@mcox13579 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
