### ISSUE TITLE
Invalid JSON Syntax

### ISSUE THREAD

**Issue by santechuser** [MicrosoftDocs/OfficeDocs-SharePoint#1666]
when we use JSON for Migration input, it is always coming up with error
"There is a problem with your file. Check your file to see if it is formatted correctly and that it contains less than 100 tasks." I don't think the example is correct, can you pl check

we using very simple block and it doesn't work

{
"Tasks":[
{
"SourcePath":"\xxx\aip",
"TargetPath":"https://xxx.sharepoint.com/sites/xxx",
"TargetList":"TestingDocs",
"TargetListRelativePath":"Folder1"
}
]
}

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
