### ISSUE TITLE
SharePoint App Launcher

### ISSUE THREAD

**Issue by ejbulaong** [MicrosoftDocs/OfficeDocs-SharePoint#1667]
When selecting SharePoint at the Office 365 App Launcher, it will take you to the Home site but will display the "My SharePoint" page, not the home page of the home site.

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
