### ISSUE TITLE
SharePoint App Launcher

### ISSUE THREAD

**Issue by ejbulaong** [MicrosoftDocs/OfficeDocs-SharePoint#1668]
When selecting SharePoint at the Office 365 App Launcher, it will take you to the Home site but will display the "My SharePoint" page, not the home page of the home site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/home-site#feedback)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by divyachapan** [comment]
SharePoint in the app launcher will always take you to the system driven user personalized start page experience. With a Home site, that start page will also show the header, nav and footer of the Home site making it easier for users to get to the Home site ( just click on "Home" in the site navigation that shows up in the start page.=).

**Comment by ejbulaong** [comment]
OK thanks. I just had this question from a fellow team member if there is a way to direct the user to the home page of the home site when SharePoint is selected. My work around is to add a custom tile to the app launcher.
