### ISSUE TITLE
Update SharePoint hybrid support to reflect what's the real story in regards SP 2019

### ISSUE THREAD

**Issue by jcgonzalezmartin** [MicrosoftDocs/OfficeDocs-SharePoint#1675]
Hybrid support pages should be updated to reflect any concerns in regards of hybrid features with SP 2019. It seems all the pages reflect the support provided by SP 2013 and SP 2016, but nothing about SP 2019 is being said.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f79181-8511-5f1f-e227-b3edd79abaf7
* Version Independent ID: 4733698e-bf05-fd61-ff87-f86fc2ad3e72
* Content: [Plan hybrid SharePoint taxonomy and hybrid content types](https://docs.microsoft.com/en-us/sharepoint/hybrid/plan-hybrid-sharepoint-taxonomy-and-hybrid-content-types?source=docs#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/plan-hybrid-sharepoint-taxonomy-and-hybrid-content-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/plan-hybrid-sharepoint-taxonomy-and-hybrid-content-types.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
What needs to be changed? The features are identical with 2016.

**Comment by scanum** [comment]
@jcgonzalezmartin We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
