### ISSUE TITLE
This page needs a diagram

### ISSUE THREAD

**Issue by MikeTheNomadArchitect** [MicrosoftDocs/OfficeDocs-SharePoint#1680]
It would be really helpful to include a diagram (or other graphic) showing the sequence of events (number of days after termination, manager notification, items permanently deleted, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#feedback)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@MikeTheNomadArchitect Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kaarins Kaarin, how are you?
Do we have such that artwork? do you, as author of the article, see value adding that?
Thanks

**Comment by get-itips** [comment]
@kaarins Kaarin, do you think we can provide a diagram for this page ? Thank you!

**Comment by kaarins** [comment]
@MikeTheNomadArchitect thanks for this suggestion! We're working on it.
