### ISSUE TITLE
Update release notes and add release date information

### ISSUE THREAD

**Issue by dneimke** [MicrosoftDocs/OfficeDocs-SharePoint#1682]
I've noticed that the release notes on the Microsoft Docs site appear to be lagging the actual releases.

The latest version I have is 3.2.115.2 whereas the most recently listed release on the site is 3.2.114.0.

Is there any chance that these could be updated and include information about fixes that have been included. For example, I've noticed some improvements in how permissions are migrated, but it's hard to validate without available release notes.

Also, adding release dates to the release notes would be super helpful.

#Migration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c911d1d-3570-6e0a-cfa7-77b7516a1f55
* Version Independent ID: 261252f1-7191-5be9-a735-cdb307b72a7c
* Content: [New and improved features in the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/new-and-improved-features-in-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/new-and-improved-features-in-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@dneimke Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @dneimke Darren 👍 how are you ?
I see that the document has already been updated, and that happened after you made this comment.

**Comment by scanum** [comment]
@dneimke Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
