### ISSUE TITLE
How to resolve a sharingLink to get the user IDs?

### ISSUE THREAD

**Issue by drmiru** [MicrosoftDocs/OfficeDocs-SharePoint#1683]
the docs state: "Friendly name of the user or group that has access to this item. If this is a sharing link, the user name is SharingLink"

How can I resolve the sharing link programatically to get the User IDs / emails behind the sharing link?

**Comment by scanum** [comment]
@drmiru Could you please link the doc. Thanks

**Comment by drmiru** [comment]
https://docs.microsoft.com/en-us/sharepoint/sharing-reports

**Comment by get-itips** [comment]
Hello @MikePlumleyMSFT 
Mike, is there a way to do what is @drmiru Michael asking here?
Thanks

**Comment by MikePlumleyMSFT** [comment]
@StephenRiceMSFT do you know?

**Comment by StephenRiceMSFT** [comment]
As part of the CSV file, each item that is of type "SharingLink" also has a "LinkID" column with a unique identifier. For users who access the item via that link, they will show up in their own row with the "AccessViaLinkID" being populated with the same identifier as in the "LinkID" column.

**Comment by get-itips** [comment]
Hello @drmiru I hope that the explanation by @StephenRiceMSFT clarifies your inquiry.

**Comment by scanum** [comment]
@drmiru Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
