### ISSUE TITLE
Typo in Advanced configurations section

### ISSUE THREAD

**Issue by sharon1188** [MicrosoftDocs/OfficeDocs-SharePoint#169]
The documentation for -LimitedFileAccessType indicates to use a dash before the parameter values (OfficeOnlineFilesOnly, WebPreviewableFiles, OtherFiles). There should be no dash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#advanced)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@sharon1188 , thank you for catching this and telling us about it. I am fixing it now!
