### ISSUE TITLE
Provide information about where to get help on SPMT

### ISSUE THREAD

**Issue by dneimke** [MicrosoftDocs/OfficeDocs-SharePoint#1694]
The [Troubleshooting Page](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues) is OK, but it is far from comprehensive.  

For example, I am consistently getting errors with the following message when I run migrations: `0x01410001 | Packaging Failure: Cannot open the file`.  The message is mentioned on the troubleshooting page, with the following advice:

```
Packaging failed due to non-existing source. Check if you can access the source root folder.
```

In my situation, the file does exist and I can access the root folder.

So... what can I do next?  Where should I go to get help with deeper troubleshooting?

A quick look around the internet reveals several forums (e.g. the [TechNet SPMT Forum](https://social.technet.microsoft.com/Forums/en-US/home?forum=SharePointMigrationTool)). 

However, the questions posted on that forum largely go unanswered.

So where should users go to get support and help?  

Maybe mention that on the Troubleshooting page!?

**Comment by scanum** [comment]
@dneimke thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by dneimke** [comment]
Thanks @scanum , will do!

**Comment by albegut** [comment]
@dneimke any updates with the error? I have the same error

 PACK FAILURE | Packaging Failure:Cannot open the file | 0x01410001 

thank you in advance!!

**Comment by dneimke** [comment]
Hi @albegut, I never quite got to the bottom of this.  There was some issue regarding certain files (between 3 and 5% overall) where they wouldn't migrate due to this failure.  Even re-running the migration would show that the same files would fail repeatedly.

I ended up developing my own workaround solution using Powershell scripts which involved:

- Identify all failures and extract them to a .csv file
- Enumerate all failures and download the file to a local `cache directory` - and write the file properties to a separate .csv `metadata` file for each download
- Run a separate Powershell to run through all entries in the `metadata` file and upload the files to SharePoint online.

My guess was that the cause of the issue has something to do with the SPMT tool using BinaryFile streams to download files from the SP2010 source because I can reproduce it using that approach.

Whereas I can successfully download the files using the .NET HttpClient's DownloadFile method.

HTH
