### ISSUE TITLE
Public access to a folder in a private group?

### ISSUE THREAD

**Issue by pacelote** [MicrosoftDocs/OfficeDocs-SharePoint#1695]
The page details how to give access to known individuals and group. It does not describe, however, how to provide PUBLIC access to a folder in a private group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e8d0f1-f6a3-82c0-e46b-974e167fe5b1
* Version Independent ID: 22b0a6c2-2e90-34ab-c3c8-bd7ba721c791
* Content: [Customize SharePoint site permissions - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions#feedback)
* Content Source: [SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@pacelote Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@pacelote you can share a folder with people outside the group by using a sharing link. See [Share SharePoint files and folders](https://support.office.com/article/1fe37332-0f9a-4719-970e-d2578da4941c) for details.

**Comment by pacelote** [comment]
> @pacelote you can share a folder with people outside the group by using a sharing link. See Share SharePoint files and folders for details.

True (and that's what I did) but it forces me to list individuals... one by one (painful, when there are 100+ of them). Instead, I want to make the folder "free for all" under the organization.

**Comment by MikePlumleyMSFT** [comment]
You can use a "People in your organization" link to grant access to the folder to anyone in the organization. You can also grant direct access to the folder to the "Everyone except external users" group.

**Comment by scanum** [comment]
@pacelote Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
