### ISSUE TITLE
Please add CLICONFG (32 & 64) option as MOST if not all SharePoint Servers DO NOT have SQL installed.

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SharePoint#17]
"cliconfg" & "%SystemRoot%/SysWow64/CliConfg.exe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3659f8a1-257c-e35e-fac9-5f1094217ddc
* Version Independent ID: 8915a0d7-882a-8e62-c0b6-3142dee12f95
* Content: [Move all databases in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/move-all-databases#to-point-the-web-application-to-the-new-database-server-by-setting-up-sql-server-connection-aliases)
* Content Source: [SharePoint/SharePointServer/administration/move-all-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/move-all-databases.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Confirmed this utility is still valid, added steps to topic, and republished.

**Comment by tseward** [comment]
Why are we using cliconfg for x86? This shouldn't be necessary with all components being x64.

**Comment by bentoncity** [comment]
Removed mention of cliconfg for x86.

**Comment by bentoncity** [comment]
Republished topic with mention of cliconfg for x64 only.
