### ISSUE TITLE
Nice for overview, but ...

### ISSUE THREAD

**Issue by donzelch** [MicrosoftDocs/OfficeDocs-SharePoint#1702]
Practically not usable at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d14723-ab30-719c-c69d-e42f94a680b5
* Version Independent ID: 182bf188-87f6-f966-4e86-77ef8927905c
* Content: [Introduction to managed metadata - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/managed-metadata#feedback)
* Content Source: [SharePoint/SharePointOnline/managed-metadata.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/managed-metadata.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@donzelch Thanks for the feedback, could you please let us know a little bit in more detail what you would like us to update/change? Thanks!

**Comment by get-itips** [comment]
Hello @donzelch 
How are you? We appreciate your feedback.
Could you please be more precise about what issues do you see and how do you think this article could be improved?
Did you review the other articles in the same section that also talk about Managed Metadata ?

[Open the Term Store management tool](https://docs.microsoft.com/en-us/sharepoint/open-term-store-management-tool)

[Set up a new group for term sets](https://docs.microsoft.com/en-us/sharepoint/set-up-new-group-for-term-sets)

[Create and manage terms in a term set](https://docs.microsoft.com/en-us/sharepoint/create-and-manage-terms)

[Set up a new term set](https://docs.microsoft.com/en-us/sharepoint/set-up-new-term-set)

[Assign roles and permissions to manage term sets](https://docs.microsoft.com/en-us/sharepoint/assign-roles-and-permissions-to-manage-term-sets)

Thank you

**Comment by scanum** [comment]
@donzelch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
