### ISSUE TITLE
Search Suggestions

### ISSUE THREAD

**Issue by dataCollegechurch** [MicrosoftDocs/OfficeDocs-SharePoint#1703]
Can you provide some pics of what this will look like once implemented for the end user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393443ee-bbb2-09d5-c16c-2522ca855c57
* Version Independent ID: 44ae935c-f080-d1ce-4c2c-463121fb7911
* Content: [Customize query suggestions in SharePoint search - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-query-suggestions#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-query-suggestions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-query-suggestions.md)
* Service: **sharepoint-online**
* GitHub Login: @arnek
* Microsoft Alias: **arnek**

**Comment by scanum** [comment]
@dataCollegechurch  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @dataCollegechurch I am proposing thru a Pull Request, to add a Screenshot to the article, if the author approves it, it will be reflected online. Thanks

**Comment by scanum** [comment]
@dataCollegechurch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
