### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/OfficeDocs-SharePoint#1705]
I think the link learn more in:
Having a great search experience is critical for the success of the home site. Learn more
is wrong.
It goes to a partner site, URL:
https://transform.microsoft.com/login?returnUrl=%2Fproducts%2Fmicrosoft-search
You have to be a partner to log in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@CharlesYeomans  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kaarins Kaarin, how are you? I could verify what @CharlesYeomans is saying here, the link is restricted to partner accounts only, is this intended?

![image](https://user-images.githubusercontent.com/36666927/75779269-f2ac4680-5d1e-11ea-9b33-3e7e1ad43184.png)

Thank you

**Comment by kaarins** [comment]
@divyachapan I can't find the perfect destination for this link. Do you have a page in mind?

**Comment by kaarins** [comment]
This has been fixed. Thanks!
