### ISSUE TITLE
CIO

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-SharePoint#171]
You mention "Internal network" and "External network". As a reader I need a link to know where to define those. Without such a link you create a lot of hoops and create additional questions. OK in this case I could find a link like https://support.office.com/en-us/article/create-and-manage-an-external-network-in-yammer-04ffd9c0-f004-498f-b058-3ea7da3b7311  but maybe that is not the right link? Since you are creating documentation, make sure that your documentation uses hyperlinks to other relevant/related topics !!
Thank you
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e905f15-4a16-f03a-47f4-4d1509c465c0
* Version Independent ID: 17aff17a-dd89-27fe-61f8-ec3b45939d2e
* Content: [Yammer networks, groups, and users overview](https://docs.microsoft.com/en-us/sharepoint/administration/yammer-networks-groups-and-users-overview)
* Content Source: [SharePoint/SharePointServer/administration/yammer-networks-groups-and-users-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/yammer-networks-groups-and-users-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@blouwagie Thank you for this feedback. 

I want to make sure these link referances are being addressed. I am making sure the SharePoint team gets this and addresses it properly. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by blouwagie** [comment]
Thank you for for following up. Generally Microsoft should cross reference its own documentation a lot more. Thanks again.
Bart

**Comment by AndreaBarr** [comment]
It looks like Trevor has resolved this issue. I am going to close this as resolved. If this is not resolved please re-open this issue.

**Comment by dariomws306** [comment]
I have added 2 links to See Also section, I think you will see it in some days.

**Comment by kenwith** [comment]
@dariomws306 - can you paste the link to the PR in here so it will cross reference? You can just paste the link and it will auto cross link. Going to close this but you can still post the PR for future references. :)

**Comment by dariomws306** [comment]
Yes sure @kenwith : 
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/435
