### ISSUE TITLE
What about Teams sites?

### ISSUE THREAD

**Issue by cmosses** [MicrosoftDocs/OfficeDocs-SharePoint#1710]
MS Teams automatically created many subsites, one for each team created in MS Teams. What will happen with them if I do the swap? The page says "Replacing the root site with another site replaces any subsites within the sites." Does that mean all the Teams sites will be lost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/modern-root-site#feedback)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Microsoft Teams creates Site Collections, not subsites.

**Comment by scanum** [comment]
@cmosses Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
