### ISSUE TITLE
Typos...

### ISSUE THREAD

**Issue by ChrisGreenacre** [MicrosoftDocs/OfficeDocs-SharePoint#1711]
Seems to be a fair few typos in "The underlying technologies" section...

 Microsoft-my.shareppoint.com

Sharepoint is spelt wrong, twice.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df67a6d7-8d87-cd0f-ceba-740727cc2aa7
* Version Independent ID: 0e33e2ed-b837-46b1-c587-0be823f12e5e
* Content: [How sync works](https://docs.microsoft.com/en-gb/onedrive/sync-process#feedback)
* Content Source: [OneDrive/sync-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ChrisGreenacre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ChrisGreenacre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
