### ISSUE TITLE
Private Channel Document Library Sync

### ISSUE THREAD

**Issue by bafjohnson** [MicrosoftDocs/OfficeDocs-SharePoint#1712]
I have been using the group policy setting "Configure team site libraries to sync automatically" in order to connect users to libraries for teams they are members of. But I cannot make it work for libraries of private channels. Is this expected behaviour? Can anyone recreate this? Many thanks! Happy to post more information if required.

**Comment by scanum** [comment]
@bafjohnson thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
