### ISSUE TITLE
Has the migration tool changed since this document was last updated?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1714]
I used the migration tool a few months ago to migrate some users' files from their on prem shared drive to their OneDrive.  I used a csv and mapped a drive on my computer to the source files location (Z:\Users).  In the csv, the source for each user was in the format of Z:\Users\[user's share name].  This worked just fine.  Now, however, when I go to run the migration tool, I get an error, "The source path Z:\Users\[user's share name] is invalid.'  So, I changed the source drive format to \\[server]\[share]\[user's share name].  This got rid of the previous error, but created a new error, "We are unable to connect to the source site.  Please check the source."

What gives? This all worked fine before?  Has there been a change to the csv file format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by Canis-Lupis** [comment]
Need to make some typo corrections to my initial posting:
1.  Format was "Z:\[user's share name]" not "Z:\Users[user's share name]."
2. Source drive format was changed to "\\[server]\[share]\[user's share name]" not "\[server][share][user's share name]."

**Comment by Canis-Lupis** [comment]
Correction to my correction:
It seems slashes don't show up in text here so just be advised that my drive mappings were in the correct format.

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Canis-Lupis 
How are you?

Can you please enclose your paths in markdown backquotes?

![image](https://user-images.githubusercontent.com/36666927/75781718-55074600-5d23-11ea-902a-5d935cbde35d.png)

That way they will be preserved in your post so I can see how you are declaring them on the CSV.

Besides that, I tried several methods of declaring Shared Folder/Mapped drives and I did not experienced issues.

**Comment by Canis-Lupis** [comment]
@get-itips I think I found the problem.  The problem wasn't my source path but the error message itself--it is misleading.  I'm finding this error,  "The source path is invalid," is a very generic error message the tool uses and could have nothing to do with the source path.  In my case, I found out that it was the destination path that was the problem; the OneDrive sites hadn't been created yet. You'd think I get a "the destination path is invalid or does not exist" message but, no, this is the one you get.

**Comment by get-itips** [comment]
@Canis-Lupis Thanks for returning to share your latest feedback. I am glad you could overcome the last, misleading, error.

**Comment by scanum** [comment]
@Canis-Lupis We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
