### ISSUE TITLE
PST In One Drive Supported with Differential Sync?

### ISSUE THREAD

**Issue by theprez1980** [MicrosoftDocs/OfficeDocs-SharePoint#1716]
I see this document references PSTs, are they now supported in the cloud with the ongoing deployment of 100GB uploads and Differential Sync support?  In years past, having PSTs in the cloud (OneDrive, etc) was not recommended because of file locking and lack of Differential Sync so that's what's driving the question.  Thx 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#feedback)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@theprez1980  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Lou240** [comment]
Based on my observations Feb 2020 and with sync client v19.222.1110.0006, .pst files are not supported in differential sync, and I've seen it create many versions of the users .pst file and run the user out of OneDrive (for Business) space of 1TB.

**Comment by get-itips** [comment]
Hello @theprez1980 
PST reference in this article has been removed, it is not present on the article. Said that, I tried to find an official statement about PST support and could not, so I think it is not supported as @Lou240 says. However, maybe @kaarins can add a confirmation here.

**Comment by tseward** [comment]
I believe PSTs are not supported due to their frequent changes and the lock Outlook creates on the PSTs (in other words, a sync would never complete). PSTs have never been supported on any form of network share, either, due to similar reasons.

Microsoft recommends not using PSTs and instead using Exchange [Online] archive mailboxes.

**Comment by kaarins** [comment]
@gacarini please let me know if you would like me to explicitly mention pst files in this article.

**Comment by scanum** [comment]
@gacarini Hi! Any updates on @kaarins question? Thanks

**Comment by gacarini** [comment]
PST files are supported by differential sync. We still don't recommend syncing them given the frequent updates and since Outlook keeps a lock on the file while it's open but they are supported.

**Comment by scanum** [comment]
@Lou240 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
