### ISSUE TITLE
Multiple sites

### ISSUE THREAD

**Issue by Balde4** [MicrosoftDocs/OfficeDocs-SharePoint#1717]
On the script can we target multiple for example 2 sites/groups instead of 1 site name?
$groupNames = 'SiteName1','SiteName2'

**Comment by tseward** [comment]
Which page are you referring to?

**Comment by Balde4** [comment]
https://docs.microsoft.com/en-us/onedrive/b2b-sync#methods-of-sharing

**Comment by tseward** [comment]
Based on the script as-is, no. There would need to be a `foreach` for the $groupName variable. Right now it targets a single Group.

**Comment by Balde4** [comment]
Can you share the updated script based on 2 groupNames?

**Comment by tseward** [comment]
Yes, I can update the script.

**Comment by Balde4** [comment]
Any update? Once you include the foreach for the 2 groups I will update to cover more groups as this is a very typical use case.

**Comment by tseward** [comment]
@Balde4 keep in mind we edit these docs/scripts as time permits. I personally won't have time prior to this weekend to make the requested edits.

**Comment by Balde4** [comment]
@tseward, that'll be fine, I ll check back on Monday. Thanks

**Comment by tseward** [comment]
Reading over this script, the `$redirectUrl` value is where the invited user will be directed to upon accepting the invite while the $groupName value is the specified Azure AD Security Group (not a Site, I think that is poor wording).

In other words, the idea here is you create a single AAD Security Group, add it to one or more sites (nested in a SharePoint Group), then send out the invite. The `$redirectUrl` is where the guest will be sent after accepting the invite (which may or may not be a SharePoint site).

Were you expecting this to invite users to one or more Office 365 Groups and/or SharePoint Groups? That would fundamentally alter the script to what I believe is not the original intent based off of the preview feature described at https://docs.microsoft.com/en-us/azure/active-directory/b2b/tutorial-bulk-invite -- this link is in the bottom of the script you linked to.

What I'd suggest is that you open a thread on one of the support forums. If you want to approach it from an Azure AD B2B angle, I'd post at https://docs.microsoft.com/answers/questions/index.html. From an Office 365 Group angle, perhaps at https://techcommunity.microsoft.com/t5/sharepoint/bd-p/SharePoint_General.

**Comment by Balde4** [comment]
Can you share the foreach for the 2 AAD Security Groups ($groupNames) so the invited user is added to both groups instead of one group?

**Comment by scanum** [comment]
@Balde4 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
