### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#1718]
What permissions are required to access the Secure Store in SPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78da1cd-d47b-3dea-5c7e-7d7ed5061cdf
* Version Independent ID: a92e04f1-723d-f665-d377-fc2eff3a0ba3
* Content: [Create or edit a Secure Store Target Application - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-or-edit-secure-store-target-application)
* Content Source: [SharePoint/SharePointOnline/create-or-edit-secure-store-target-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-or-edit-secure-store-target-application.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@eschrader Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
