### ISSUE TITLE
Why would AAD / Hybrid AAD join be a pre-requisite?

### ISSUE THREAD

**Issue by uttampcu** [MicrosoftDocs/OfficeDocs-SharePoint#172]
Why would AAD / Hybrid AAD join be a pre-requisite?  Please provide details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently deploy and configure the OneDrive sync client](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@uttampcu Thank you for this feedback. 


I want to make sure your questions on these pre-reqs are answered fully. Support will be able to handle this issue to resolution. 


I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs

**Comment by uttampcu** [comment]
This git comment was added on Aug 9th after Support was unable to answer the question.  They are the ones who suggested posting on this site to get an answer from the developers.

> @uttampcu Thank you for this feedback.
> 
> I want to make sure your questions on these pre-reqs are answered fully. Support will be able to handle this issue to resolution.
> 
> I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.
> 
> Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
> 
> If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs

**Comment by AndreaBarr** [comment]
@uttampcu Thank you for letting us know that support sent you here for answers. I'll get this over to the SharePoint team for investigation and update so we can find those answers for you. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by KyleSchroeder** [comment]
Guess that work is still in progress?

**Comment by AndreaBarr** [comment]
@uttampcu That was the process we were using at the time. It has since changed to keep these open until it's completed. 

@tseward Could you please work on this as well. Thank you.

**Comment by thedrum808** [comment]
To answer the question, Hybrid Azure AD Join or Azure AD join is a prerequisite because the script uses registry keys that rely on the Azure AD credential/token used on the Windows user account to configure the parameters of the OneDrive account. If the device is not Azure AD-joined or Hybrid Azure AD-joined, there will be no Azure AD credentials to draw from, and these registry settings that rely on the Azure AD properties of the user account will fail.

If you are trying to use domain credentials to set up Azure AD services on devices, the right way to do this is to set up Hybrid Azure AD-join, as detailed here: https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan
