### ISSUE TITLE
Quick Launch Links Open in New Tab

### ISSUE THREAD

**Issue by kk-sdsu** [MicrosoftDocs/OfficeDocs-SharePoint#1722]
According to this section https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience#link-targets I would expect Quick Launch links from other domains to open in a new tab, but this is not the case. In Modern there is no way to make external links in Quick Launch open in a new tab. In Classic we have the Site setting "Navigation" that would allow this feature. This should either be documented or developed as a feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience#link-targets)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@kk-sdsu  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @LoreenLa Loreen 👍 how are you?
I could verify what the user is saying here, contacting you to find out if you know this will change shortly (Quick Launch external URLs opening in new tabs by default) or not, so we can clarify this making a PR against this article. I appreciate, thanks.

**Comment by LoreenLa** [comment]
Still waiting to get an answer on this. Will let you know as soon as I can. Thanks!

**Comment by get-itips** [comment]
@LoreenLa Loreen, how are you ? 👍 any updates? Thank you

**Comment by LoreenLa** [comment]
Sorry, still waiting for an answer. I am working on it. Thanks for your patience!

**Comment by LoreenLa** [comment]
The documentation appears to be correct in that, for modern sites, external URLs open in a new tab, while internal URLs open in the same tab. There is no way to change this behavior currently. A good way to request this feature is to post in SharePoint User Voice: https://sharepoint.uservoice.com/. Thank you!

**Comment by scanum** [comment]
@kk-sdsu Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
