### ISSUE TITLE
Unable to Migrate Large Library with 48771 Files and Folder Through SP Migration Tool

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1725]
Hi Team,

I am trying to migrate library from SP 2013 to SP Online through SP Migration Tool. The document library has 48771 files and folders.
While trying to migrate the library getting an below error after 60% or 80% or 90%
ScanSharePoint Access Failure - Web issue. Sites:http://sharepoint2013/subsite User: domain\loginname (ErrorCode: 0x02010018)

I have tried 4 times and it is taking every time minimum more than 12 hours and stopping it.
Can you please help me on this issue and also any better approaches to do the large library or list migration.

**Comment by scanum** [comment]
@PrabhaSP2010 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
