### ISSUE TITLE
Filter out lists with names - SP Migration Tool

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1726]
Hi Team,

I am migrating the site from SP 2013 to SP Online by using SPMT. 
I am trying to use the setting option **Filter out lists with names** from advanced settings. Able to exclude one library but trying to filter 2 libraries by separating with comma but tool is not excluding with this approach.
Can you please let me know, how do i filter when want to be exclude more than 1 list or library.

**Comment by scanum** [comment]
@PrabhaSP2010 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
