### ISSUE TITLE
5TB

### ISSUE THREAD

**Issue by Chukaka** [MicrosoftDocs/OfficeDocs-SharePoint#1728]
According to this "If your organization has a qualifying Office 365 plan and 5 or more users, you can change the storage space to more than 5 TB.", it should not be possible to proceed with increasing the cap if you do not have the required amount of OD/SPO plan 2s.
However, it is still possible to do so even if you have just a single plan 2 license.

Would the max storage for a given account revert back eventually if the system notices that the tenant does not have the required licenses for the 5tb cap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space#feedback)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Chukaka Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@kaarins Hello Kaarin 👍 can you shed some light here? Thank you!

**Comment by nktran13** [comment]
I have many users, so I set 5TB, but someone has 5TB in onedrive, but another users just have 2GB? I don't know why?

**Comment by WayneEwington** [comment]
@Chukaka Please contact Microsoft support to discuss your needs and the prerequisites.

**Comment by WayneEwington** [comment]
> I have many users, so I set 5TB, but someone has 5TB in onedrive, but another users just have 2GB? I don't know why?

@nktran13 If the default Quota size is changed, then the User's OneDrive for Business Quota size is not changed until the user next accesses their OneDrive for Business.

**Comment by get-itips** [comment]
Thanks @WayneEwington Wayne for your contribution.
@scanum Manuela please proceed closing this one.

**Comment by nktran13** [comment]
@Wayne Ewington, so I deleted the user, example deleted phuong.cao@vietcad.com and then re-create phuong.cao@vietcad.com again, then I sign in these account in onedrive.com, so check it has storage 5TB. 




Tải Outlook for Android







On Fri, Mar 20, 2020 at 3:28 AM +0700, "Andres Mariano Gorzelany" <notifications@github.com> wrote:















Thanks @WayneEwington Wayne for your contribution.

@scanum Manuela please proceed closing this one.

**Comment by get-itips** [comment]
@scanum please close this thread.

**Comment by scanum** [comment]
@Chukaka Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
