### ISSUE TITLE
What about Farm solution ? 

### ISSUE THREAD

**Issue by seaSide974** [MicrosoftDocs/OfficeDocs-SharePoint#173]
I guess there are not possible to be deployed , could you document it ? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019 Public Preview](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
That's not the case at all and the page makes no mention of farm solutions, hence not deprecated nor removed.

**Comment by kenwith** [comment]
@seaSide974 thanks for question and thanks for answer @tseward !  If there is a way to include a note or improve the doc with this info it would be awesome to submit a Pull Request. @seaSide974 - if you decide to make an edit you can find instructions on how to do it in the README that shows at the bottom of the main repo here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint  Feel free to ping me with any questions on edits too.
