### ISSUE TITLE
SPMT - Error - Failed to Read the file:Could not get all list item versions

### ISSUE THREAD

**Issue by PrabhaSP2010** [MicrosoftDocs/OfficeDocs-SharePoint#1731]
Hi Team,

I am using SPMT (Microsoft SharePoint Migration Tool) to migrate the content from SP 2013 to SP Online.

While migrating the content getting an error message "Failed to Read the   file:Could not get all list item versions" and error code of error is '0x0131000D'.

Can you please let me know, if you have any solution for this error.

**Comment by scanum** [comment]
@PrabhaSP2010 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
