### ISSUE TITLE
Owners tab is now Permissions tab

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-SharePoint#1732]
There is now a disctinction in the details pane: Site Admins vs Site Owners. How does each autopopulate from, or relate to, the Microsoft 365 admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659548ea-eb6e-8eee-2892-f352512db6a1
* Version Independent ID: 2e0e6017-2b29-e831-ff61-0a798dfb175f
* Content: [Manage site admins - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-administrators#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-administrators.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-administrators.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ingepepe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ingepepe 👍 Thanks for noticing, created a pr to correct the article.

**Comment by scanum** [comment]
@ingepepe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
