### ISSUE TITLE
Migration Manager work folder Missing

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-SharePoint#1733]
“ Migration Manager work folder” is not available, at least not in our tenant. Should add clarification if this is not available in all tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c58f8a6-488f-7e3b-47f4-f5816801e804
* Version Independent ID: eed21d0d-7343-17eb-2afe-6cba550441a5
* Content: [Migration Manager settings - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-settings#feedback)
* Content Source: [migration/mm-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Mikael:  Can you contact me directly @jhendr@microsoft.com with the following info:  tenant info, such as TenantID or url, so our dev team can check your environment.

Joanne

**Comment by scanum** [comment]
@JonesMikael Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
