### ISSUE TITLE
Article does not apply to 2016 and 2019. 

### ISSUE THREAD

**Issue by UmrG** [MicrosoftDocs/OfficeDocs-SharePoint#1734]
Hello, 
the article "https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts" says it applies to 2013, 2016 and 2019. 

but when read the same article with "https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016" you can see some conflicting information specially regarding the usage of one application pool or multiple app pools. 

Keeping the first one for 2013 only will be helpful and less conflicting.

**Comment by scanum** [comment]
@UmrG Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@UmrG technically it does apply, but I can see how it isn't clear. I will provide clarity in the doc regarding accounts.

**Comment by UmrG** [comment]
Thanks Trevor , Yes, just a bit clarity will help clients.

**Comment by UmrG** [comment]
-->**Applies to 2013 , 2016 & 2019** 
https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts
"If you create additional application pools to host sites, plan for additional application pool identity accounts. The following table describes the application pool identity account."

vs 

-->**Applies to 2016 & 2019**. 
https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016
"A single account should be used for all Web Applications, named Web Application pool account. This allows the administrator to use a single IIS Application Pool for all Web Applications."

**Comment by tseward** [comment]
Yep, it's a bit inconsistent :)

**Comment by scanum** [comment]
@UmrG Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
