### ISSUE TITLE
What is not supported?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-SharePoint#1735]
Would be helpful to see what SPMT does not support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support? - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by gregbnz** [comment]
Hi there, does SPMT support syncing Deletes yet? From past experience you would do one sync and upload the everything, and then if you wanted to do a second sync just before cutover, it would add missing files, but it wouldnt delete files that had been removed from source. Has this changed, and if so when? Thanks!

**Comment by get-itips** [comment]
Hello @jebalert Joseph how are you?
Generally speaking, what is not expressly mentioned is not supported, however we could ask  @JoanneHendrickson as the article's author to understand if anything about that can be added to the article.
Thank you

**Comment by get-itips** [comment]
@JoanneHendrickson Can you help us here? Thank you!

**Comment by scanum** [comment]
@JoanneHendrickson Can you help us here? Thank you!

**Comment by scanum** [comment]
v

**Comment by KarlaK-fl** [comment]
When migrating from file shares to SharePoint online or to OneDrive or Teams, is the file metadata retained? I'm specifically needing created by, created on, modified by, modified on.  
And are the file and folder permissions retained from file share and NTFS permissions?

**Comment by JoanneHendrickson** [comment]
Addressing a number of comments from above.
SPMT does not delete content from the source -- it copies.
Incremental passes are handled depending on your settings. See here:  https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#incremental-migration

The migration of content types and term stores is supported. Global term store migration requires global tenant admin permissions.

By default, managed metadata migration is turned off, and taxonomy is updated in incremental round.

**Comment by JoanneHendrickson** [comment]
updated topic.

**Comment by gregbnz** [comment]
Thanks Joanne, my question was not about SPMT deleting from source - rather SPMT removing files from SPO when they are deleted from the source.

The requirement stems from large file shares needing several days to upload. By the time they have finished, some of the files in the source have been deleted or moved. I am looking for SPMT to add the functionality (potentially as a selectable option) to not only copy new files, but also copy the deletes that happen on source, so they are also removed from the destination (SPO).

**Comment by JoanneHendrickson** [comment]
Hi Greg:  I am going to pull in a PM on this -- can you email me at jhendr@microsoft.com and we can take this conversation from there.
