### ISSUE TITLE
Update PowerShell command's comment

### ISSUE THREAD

**Issue by wizneeraj** [MicrosoftDocs/OfficeDocs-SharePoint#1736]
Please clarify what enabling & disabling the feature does to the site as the comments in the PowerShell code are not clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8659498a-6c73-763a-31a0-354010572115
* Version Independent ID: dc4c2e96-fb55-67c0-ec7b-6f1f608eb0cb
* Content: [Disable automatic modernization of classic site home pages - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/disable-auto-modernization-classic-home-pages#feedback)
* Content Source: [SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@wizneeraj Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @wizneeraj 
How are you ? that cmdlet, enables the site feature "ModernizeHomepageOptOut" that keeps the classic team site home page (not modernized) as the article currently says 

> To prevent modernization of an uncustomized home page

That feature is also mentioned at the update criteria list.

**Comment by scanum** [comment]
@wizneeraj Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
