### ISSUE TITLE
"Update criteria" section

### ISSUE THREAD

**Issue by yoinuma** [MicrosoftDocs/OfficeDocs-SharePoint#1741]
The content of the "Update criteria" section is different for each language-specific page.

en-us: "Home page name is Home.aspx’
ja-jp: ホームページの名前は 'default.aspx' です。

Which content is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8659498a-6c73-763a-31a0-354010572115
* Version Independent ID: dc4c2e96-fb55-67c0-ec7b-6f1f608eb0cb
* Content: [Disable automatic modernization of classic site home pages - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/disable-auto-modernization-classic-home-pages#feedback)
* Content Source: [SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@officeglobal Hi! Could you please help with the following issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@yoinuma , @scanum the article has been HumanTranslated and published live

**Comment by scanum** [comment]
@yoinuma Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by yoinuma** [comment]
It looks like the change is reverted.

 "ホームページ名は ' default.aspx ' です。"

Could you please check it?

Which name of page will be affected actually?
 - "ホーム.aspx"
 - "home.aspx"
