### ISSUE TITLE
Custom Themes impact

### ISSUE THREAD

**Issue by wizneeraj** [MicrosoftDocs/OfficeDocs-SharePoint#1742]
Please clarify the impact on the sites with custom themes. How will the theme be displayed on the modern home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8659498a-6c73-763a-31a0-354010572115
* Version Independent ID: dc4c2e96-fb55-67c0-ec7b-6f1f608eb0cb
* Content: [Disable automatic modernization of classic site home pages - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/disable-auto-modernization-classic-home-pages)
* Content Source: [SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@wizneeraj Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @wizneeraj 
I think that the information you are looking for is [here](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations) if I understood you well, if not, please kindly inform me and I will try to help.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
