### ISSUE TITLE
Not able to upload JSON file to Migration Manager

### ISSUE THREAD

**Issue by jorik99** [MicrosoftDocs/OfficeDocs-SharePoint#1743]
I am trying to use the Migration Manager of SharePoint Online.
A single task is working fine. But if I want to use JSON files for bulk operations it is not working.
I have attached a screenshot. 

error message: 

_There is a problem with your file. Check your file to see if it is formatted correctly and that it contains less than 1000 tasks._ 

Who can help me with this issue.
[testjson.txt](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/4165600/testjson.txt)
![2020-02-06 15_34_32-SharePoint admin center en nog 5 pagina's - Test - Microsoft Edge](https://user-images.githubusercontent.com/40631327/73946875-e804ba00-48f6-11ea-99ca-45e793a888d2.png)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/nl-NL/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jorik99 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Mike-Crowley** [comment]
I got this error too, though mind said 50000 tasks. I was only attempting 500, but after trying lower numbers, it finally accepted one with ~325 tasks in it. I think this is a bug. @jorik99 Did you end up contacting support?
