### ISSUE TITLE
Add Note: Default settings not supported

### ISSUE THREAD

**Issue by mattgaspar** [MicrosoftDocs/OfficeDocs-SharePoint#1745]
Per Microsoft support I was informed there is no way to set the default external sharing settings for new team sites or group sites.
This page makes no mention of that and I think that it would be assumed by most people that whats described in this article would be the way to set the default.

"Like you said it is assumed the organization default settings control the new site creation setting but that is not the behavior. The behavior is not documented as you requested but this is a known behavior across all tenant."

Support ticket #18596059

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage sharing settings - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off#file-and-folder-links)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@mattgaspar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mattgaspar Matt how are you ? 👍 
I want to make sure to understand well what you experienced (I understand also that Support confirmed).
In my lab, I made some changes to the SharePoint Admin Center - Sharing page, and then I created new team sites, and they honored the settings I made at the Admin Center.
Am I interpreting you the right way? if not, please tell me specifically what happened to you on newly created sites.

Thank you

**Comment by scanum** [comment]
@mattgaspar We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
