### ISSUE TITLE
Unable to Make Default link type as "Existing Access"

### ISSUE THREAD

**Issue by arjunumenon** [MicrosoftDocs/OfficeDocs-SharePoint#1746]
We are trying to make the default link type as **Default Link to Existing Access** in SharePoint Site Collection. Part of that when we try to execute the command 
`Set-SPOSite -Identity https://mysite.sharepoint.com/ -DefaultLinkToExistingAccess` , we are getting the error `Set-SPOSite : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1`.

Is it because that the feature is not released in our Tenant. 

_PS : We also did the Pre-requisite mentioned in the same article._ 

Can you let us know  where I am going wrong. Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default sharing link for a site - SharePoint Online](https://docs.microsoft.com/en-in/sharepoint/change-default-sharing-link#feedback)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@arjunumenon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
