### ISSUE TITLE
Starting appfabric service from console can cause other issues. 

### ISSUE THREAD

**Issue by UmrG** [MicrosoftDocs/OfficeDocs-SharePoint#1748]
Many experts have written that starting the service from services console can leave your farm in non working state and in some cases might have to rebuild the SharePoint farm. 

This article states : "4. Restart the Distributed Cache service on all cache hosts. To restart the Distributed Cache service, go to Services on Server in Central Administration, and Start the Distributed Cache service on all cache hosts in the farm."

After RAM update each host starts automatically and incase one fails it is recomended to use AFC command or SP distributed cache command set e.g. 
Start-CacheHost –ComputerName $env:computername –CachePort 22233

Please double check if this is correct statement.

**Comment by scanum** [comment]
@UmrG  Thank you for submitting feedback and contributing to the docs. Please link the documentation you are referring to.

**Comment by UmrG** [comment]
https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service

<--Restart the Distributed Cache service on all cache hosts. To restart the Distributed Cache service, go to Services on Server in Central Administration, and Start the Distributed Cache service on all cache hosts in the farm.-->

**Comment by tseward** [comment]
@UmrG I'm not seeing the issue. The instructions look fine.

**Comment by UmrG** [comment]
Hey Trevor, 
Sorry man, You are correct. I over looked section of the article. Please ignore.

**Comment by scanum** [comment]
@UmrG Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
