### ISSUE TITLE
Maximum throughput value detection

### ISSUE THREAD

**Issue by ruairidhlc** [MicrosoftDocs/OfficeDocs-SharePoint#1751]
Regarding the 'Limit the sync client upload rate to a percentage of throughput' setting, can Microsoft advise exactly how the throughput is detected?  

I assumed it would be a percent of the NIC's limitations, but it sounds like an internet speed test is carried out - "the maximum throughput value detected by the sync app can sometimes be higher or lower than expected because of the different traffic throttling mechanisms that your Internet Service Provider (ISP) might use."  

Some clarity on what's going on would be great :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ruairidhlc  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@kaarins Kaarin 👍 how are you? Can we provide some Product Group information on the method used to detect the throughput? Thank you

**Comment by get-itips** [comment]
@kaarins Kaarin, can you please step in to shed some light here? Thank you!

**Comment by kaarins** [comment]
@andreyesipov can you provide more info? Thanks!

**Comment by andrey-esipov** [comment]
Hi, Everyone. The way this value is recorded is outlined here https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutomaticUploadBandwidthPercentage. But in essence, when the sync client uploads the files it will periodically record (within a 1 minute period) the maximum available rate that the file can get uploaded at. Available network speeds + ISP settings + the number of files being uploaded from the sync client in parallel (more files uploaded in parallel from the sync client generally result in higher upload rates vs when uploading a single file) all play a factor in the upload rate.

**Comment by get-itips** [comment]
> Hi, Everyone. The way this value is recorded is outlined here https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutomaticUploadBandwidthPercentage. But in essence, when the sync client uploads the files it will periodically record (within a 1 minute period) the maximum available rate that the file can get uploaded at. Available network speeds + ISP settings + the number of files being uploaded from the sync client in parallel (more files uploaded in parallel from the sync client generally result in higher upload rates vs when uploading a single file) all play a factor in the upload rate.

Thanks @andrey-esipov for that explanation ! 
@ruairidhlc I hope that clarifies it to you.

**Comment by ruairidhlc** [comment]
> 
> 
> > Hi, Everyone. The way this value is recorded is outlined here https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutomaticUploadBandwidthPercentage. But in essence, when the sync client uploads the files it will periodically record (within a 1 minute period) the maximum available rate that the file can get uploaded at. Available network speeds + ISP settings + the number of files being uploaded from the sync client in parallel (more files uploaded in parallel from the sync client generally result in higher upload rates vs when uploading a single file) all play a factor in the upload rate.
> 
> Thanks @andrey-esipov for that explanation !
> @ruairidhlc I hope that clarifies it to you.

Perfect :) Thank you.
