### ISSUE TITLE
Using Managed navigation for Application pages in sharepoint

### ISSUE THREAD

**Issue by pdalvi1893** [MicrosoftDocs/OfficeDocs-SharePoint#1752]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733eb6b7-4399-93f1-cbce-a247d42bb793
* Version Independent ID: 88442db6-2065-dfa4-c481-7fc5b6dae806
* Content: [Overview of managed navigation in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/overview-of-managed-navigation)
* Content Source: [SharePoint/SharePointServer/administration/overview-of-managed-navigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/overview-of-managed-navigation.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@pdalvi1893 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
