### ISSUE TITLE
Please elaborate on "replaces any subsites"

### ISSUE THREAD

**Issue by Arknev** [MicrosoftDocs/OfficeDocs-SharePoint#1753]
In the Limitations section of Replace Your Root Site, the following can be found:

 - Replacing the root site with another site replaces any subsites within the sites.

Can you elaborate on what this means? Specifically, if we have a root site with subsites and a separate modern site that also has subsites, will we lose any sites/content. We would like to do a rebuild of an intranet and would like to do a complete replacement with a modern site/sites while keeping the old classic sites for archive and to store content that will be migrated over time.

**Comment by kaarins** [comment]
@Arknev this feature works at the site collection level, so the entire site collection is archived and replaced with the new site collection. I hope this helps. Thanks
