### ISSUE TITLE
Can I implement this with InTune compliance policy?

### ISSUE THREAD

**Issue by OneTechToFixThemAll** [MicrosoftDocs/OfficeDocs-SharePoint#1755]
Am looking to limit OneDrive client to sync only from corporate laptops, I noticed that this is doable via OneDrive Sync from domain option, but was wondering if I can do something similar using InTune?

**Comment by scanum** [comment]
@OneTechToFixThemAll 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
