### ISSUE TITLE
Can I implement this with InTune compliance policy?

### ISSUE THREAD

**Issue by OneTechToFixThemAll** [MicrosoftDocs/OfficeDocs-SharePoint#1756]
I am looking to limit OneDrive client to sync only from corporate laptops, is there a way to achieve the same goal by using InTune compliance polices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@OneTechToFixThemAll 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
