### ISSUE TITLE
Folder names in this article are for SharePoint 2010

### ISSUE THREAD

**Issue by rainerasbach** [MicrosoftDocs/OfficeDocs-SharePoint#1759]
In step 8 of 
https://docs.microsoft.com/en-us/sharepoint/search/create-a-custom-dictionary#create-a-custom-dictionary-1 you refer to 
%ProgramFiles%\Microsoft Office Servers\14.0\Bin
This should be at least 15.0  for SharePoint 2013 and 16.0 for SharePoint 2016 and 2019

The same is for step 2 in 
https://docs.microsoft.com/en-us/sharepoint/search/create-a-custom-dictionary#copy-the-custom-dictionary-to-each-application-server

In  https://docs.microsoft.com/en-us/sharepoint/search/create-a-custom-dictionary#stop-and-restart-the-sharepoint-server-search-14-service-on-each-application-server  the reference includes the number 14, this should be changed to 15 for SharePoint 2013 as the minimum supported version of the article or better to 16 as the supported version SharePoint 2016 and 2019 use 16 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61d58a6-0a9a-2009-cf90-af6b985d750e
* Version Independent ID: b5b02a89-16a7-56c0-ef9c-1f7bbd171e22
* Content: [Create a custom dictionary](https://docs.microsoft.com/en-us/sharepoint/search/create-a-custom-dictionary#copy-the-custom-dictionary-to-each-application-server)
* Content Source: [SharePoint/SharePointServer/search/create-a-custom-dictionary.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/create-a-custom-dictionary.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@rainerasbach Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @rainerasbach 👍 thanks for reporting, created a pr to improve the article based on your comments.

**Comment by scanum** [comment]
@rainerasbach Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
