### ISSUE TITLE
Renaming SP2019 databases has wrong order with Links databases

### ISSUE THREAD

**Issue by Rob3r70** [MicrosoftDocs/OfficeDocs-SharePoint#1763]
Hi,

Step 5 for renaming SP2019 databases is wrong, because you have to resume Search SA before you can run this command:
Move-SPEnterpriseSearchLinksDatabases -SearchApplication $ssa -TargetStores @($newLinksStoreDB) -Confirm:$false.

If you run it before resuming Search SA, you get an error:
Move-SPEnterpriseSearchLinksDatabases : LinksStoresRefactoring: LinksStoreInput analysis is in state EnginePaused, but SSA is not paused for LinkDBRepartitioning. Make sure SSA is not already paused when moving LinkDBs.
At line:1 char:1
+ Move-SPEnterpriseSearchLinksDatabases -SearchApplication $ssa -Target ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Offic...hLinksDatabases:MoveSearchLinksDatabases) [Move-SPEnterpriseSearchLinksDatabases], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Office.Server.Search.Cmdlet.MoveSearchLinksDatabases

So correct order would be:

New-SPEnterpriseSearchLinksDatabase -DatabaseName &lt;SearchServiceLinksDatabase&gt; –SearchApplication $ssa -DatabaseServer &lt;SearchServiceDatabaseServer&gt;
$oldLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[0]
$newLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[1]

Resume-SPEnterpriseSearchServiceApplication -Identity $ssa

Move-SPEnterpriseSearchLinksDatabases -SearchApplication $ssa -TargetStores @($newLinksStoreDB) -Confirm:$false
Remove-SPEnterpriseSearchLinksDatabase -Identity $oldLinksStoreDB -SearchApplication $ssa -Confirm:$false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0c1428-d756-3353-887a-3e0b33319c68
* Version Independent ID: 64436001-711f-a29f-15ff-02fcff2dae89
* Content: [Move or rename service application databases in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/move-or-rename-service-application-databases#feedback)
* Content Source: [SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Rob3r70  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Rob3r70 thank you for reaching out and helping improve MS Docs. Related link https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1764

**Comment by scanum** [comment]
@Rob3r70 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
