### ISSUE TITLE
Step 5 in SharePoint 2019 databases will not always work

### ISSUE THREAD

**Issue by Rob3r70** [MicrosoftDocs/OfficeDocs-SharePoint#1764]
Getting databases by the array number will not always work:
$oldLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[0]
$newLinksStoreDB = ([array]($ssa | Get-SPEnterpriseSearchLinksDatabase))[1]

Should be corrected to this:
$oldLinksStoreDB = Get-SPEnterpriseSearchLinksDatabase -Identity &lt;oldDbName&gt;
$newLinksStoreDB = Get-SPEnterpriseSearchLinksDatabase -Identity &lt;newDbName&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0c1428-d756-3353-887a-3e0b33319c68
* Version Independent ID: 64436001-711f-a29f-15ff-02fcff2dae89
* Content: [Move or rename service application databases in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/move-or-rename-service-application-databases#feedback)
* Content Source: [SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/move-or-rename-service-application-databases.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Rob3r70  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MikePlumleyMSFT please could you assist with this. Related issue #1763

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr can you help?

**Comment by lindspea** [comment]
@TroyStarr any update perhaps?

**Comment by scanum** [comment]
@TroyStarr any update perhaps?

**Comment by scanum** [comment]
@TroyStarr any update on this issue?

**Comment by scanum** [comment]
@TroyStarr any update on this issue?

**Comment by scanum** [comment]
@Rob3r70 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Rob3r70** [comment]
Hi Manuela,

As far as I can see you were not waiting for my feedback but feedback from Troy Starr, or did I miss something?

Regards,

Robi

Sent from Nine<http://www.9folders.com/>
________________________________
