### ISSUE TITLE
Please address if this will properly survive a sysprep

### ISSUE THREAD

**Issue by jaxidian** [MicrosoftDocs/OfficeDocs-SharePoint#1765]
If you google/bing `onedrive sysprep`, you'll find the internet is littered with people trying to get OneDrive to survive a sysprep. Please address this scenario in this document. I think it should, but the world would love to know!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by jaxidian** [comment]
Related: This other support page has information that, form all of my testing, is incorrect. The method on that page does *not* survive a sysprep.

https://support.microsoft.com/en-us/help/4459304/unable-to-open-onedrive-on-images-using-sysprep

**Comment by scanum** [comment]
@jaxidian  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jaxidian Thank you for reaching out and helping improve MS Docs. Please have a look at this forum discussion and let me know if it helps. There are a few suggestions and links to look at. https://social.technet.microsoft.com/Forums/19c6778b-6a44-4214-a8a1-bc763f795c6f/how-to-provision-apps-before-sysprep

**Comment by scanum** [comment]
@jaxidian Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jaxidian** [comment]
I do not believe my issue has been resolved unless the resolution is "we choose not to make a change". After much trial & error, I have confirmed that the `/allusers` flag **does** survive a Sysprep, but this is not mentioned in the documentation. I believe it should be.

**Comment by jaxidian** [comment]
@scanum I'm unable to re-open this issue but I believe it should be re-opened. See my previous message ^^
