### ISSUE TITLE
Missing details continued

### ISSUE THREAD

**Issue by MarkWagner** [MicrosoftDocs/OfficeDocs-SharePoint#1766]
On Jul 18, 2019 danmyhre commented:
"Not sure what that link has to do with this, but the page mentions no details on updating language packs. It should be mentioning the sts* vs the wssloc* files, the order you install them in, and if you need to run psconfig only once after both are installed (or after each is installed?), etc."

This document does not address the need (if needed, or not) to install both the language-dependent AND the language-independent updates.  The only place I find this mentioned is in a Microsoft employee's personal blog; not an official source, found here:
https://blog.stefan-gossner.com/2019/08/13/august-2019-cu-for-sharepoint-server-2016-is-available-for-download/

**Comment by scanum** [comment]
@MarkWagner  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MarkWagner** [comment]
This is in reference to https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update.  I expect this thread is somehow linked to that document but it is not clear from the visibility I have, but just to be clear.  Thank you.

**Comment by lindspea** [comment]
@MarkWagner Thanks for pointing that out Mark. I'll have a look and see if I can find anything official that I can add for clarity to the article. Give me a few days.

**Comment by tseward** [comment]
The information is linked at the top of the article already.

[Software updates overview for SharePoint 2016](https://docs.microsoft.com/sharepoint/upgrade-and-update/software-updates-overview)

> Micrososft releases Public Updates each month. The first update is known as the language independent update. This update will often include both feature and security fixes. It is also known as the 'sts-x-none' patch.

> The second type of patch is the language dependent patch. This patch covers all language packs, including English installations. This patch is required to fully update the farm, although may not be released every month. This patch is also known as the 'wssloc' patch.

**Comment by lindspea** [comment]
@MarkWagner please see at the top of the article as per @tseward 's comment.

**Comment by MarkWagner** [comment]
Thank you

**Comment by scanum** [comment]
@MarkWagner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
