### ISSUE TITLE
SharePoint Templates - Home Site templates

### ISSUE THREAD

**Issue by m-mygithub** [MicrosoftDocs/OfficeDocs-SharePoint#1767]
In the 'Choose solution components' section it mentions 'Home sites' as a SharePoint site option.  Could not find such a template option in the SharePoint admin center when going to create a site.  It would be nice for this to be updated to reflect options in the SharePoint admin center portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01638ec5-b81c-f3ce-9c79-020f31f5c051
* Version Independent ID: fef6293d-ce0f-1471-8e2d-c294a752a553
* Content: [Plan an intelligent SharePoint intranet - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/plan-intranet#feedback)
* Content Source: [SharePoint/SharePointOnline/plan-intranet.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-intranet.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@m-mygithub  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@m-mygithub you can find information about home sites in [Set up a home site for your organization](https://docs.microsoft.com/sharepoint/home-site). I'll add a link to the article.

**Comment by scanum** [comment]
@m-mygithub Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
