### ISSUE TITLE
Saved migrations missing from SharePoint migration tool

### ISSUE THREAD

**Issue by KarlPower** [MicrosoftDocs/OfficeDocs-SharePoint#1768]
I've run a number of migrations from file shares to SharePoint online over the past week. I've saved the migrations after they completed but this morning when I opened the SharePoint migration tool the option to "Show saved migrations" wasn't available and I wasn't available, I wasn't able to find any of the previous saved migrations so I can't do an incremental migration. This is a serious issue as it means I have to do full migrations again for all of the company data

**Comment by scanum** [comment]
@KarlPower thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
