### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by brassman2000** [MicrosoftDocs/OfficeDocs-SharePoint#177]
1)  Section titled "Block access to SharePoint and OneDrive content using the SharePoint admin center" - Steps 7, 8 and 9 seem incomplete or incorrect.  Please confirm.

2) Under section "Block or limit access to specific SharePoint site collections or OneDrive accounts", I followed all the steps, however when running PowerShell to block access, I receive the following error:
PS C:\Users\xxxxxxx&gt; Set-SPOSite -Identity 'https://xxxx.sharepoint.com/sites/xxxxxx' -ConditionalAccessPolicy BlockAccess
Set-SPOSite : This parameter can only be set if ConditionalAccessPolicy is set to AllowLimitedAccess or AllowFullAccess.
At line:1 char:1
+ Set-SPOSite -Identity 'https://xxxxx.sharepoint.com/sites/xxxxxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOSite], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Online.SharePoint.PowerShell.SetSite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@brassman2000 , thank you for this feedback. I am investigating!

**Comment by Sanjoyan** [comment]
This issue is due to the fact that you are using a very old SPO powershell.  The latest one is available here:
https://www.microsoft.com/en-us/download/details.aspx?id=35588

The article also has this link. Thanks.
