### ISSUE TITLE
Missing issue

### ISSUE THREAD

**Issue by javnguyen** [MicrosoftDocs/OfficeDocs-SharePoint#1770]
I am getting a code 0x0204000E packaging failed due to root source folder doesnt not exist.  I keep getting this about 46% done with migration.

**Comment by scanum** [comment]
@javnguyen thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
