### ISSUE TITLE
Needs to be more practical and user friendly

### ISSUE THREAD

**Issue by Jabfag2356** [MicrosoftDocs/OfficeDocs-SharePoint#1771]
This description needs to be better related to metadata use such as lists with case studies/examples. There is a lot of assumed knowledge. I have just read the SharePoint Maven's metadata blog from 2016 and it was more user friendly. Your metadata jargon, although simple, doesn't seem to gel. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d14723-ab30-719c-c69d-e42f94a680b5
* Version Independent ID: 182bf188-87f6-f966-4e86-77ef8927905c
* Content: [Introduction to managed metadata - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/managed-metadata#feedback)
* Content Source: [SharePoint/SharePointOnline/managed-metadata.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/managed-metadata.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Jabfag2356 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @MikePlumleyMSFT Mike 👍 I need to kindly ask you to step in, as designated author of the article to review @Jabfag2356 comments, do you see something can be improved based on them? Thank you.

**Comment by get-itips** [comment]
@scanum Manuela, we can close this issue now.

**Comment by scanum** [comment]
@Jabfag2356 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
