### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SharePoint#1772]
I was under the impression that the verification code was in lieu of having a Microsoft account, not in addition to it. According to paragraph two, the recipient of a sharing link must log into their MS account, then enter the verification code, then log into their account again? Also, I'm not clear on the difference between how guests were added previously (a partial guest?)  vs. the new way--as a "full" guest. Can you please clarify these concepts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-sharing-in-targeted-release#feedback)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@jmuehlenbein if the user does have an Office 365 account, they'll be asked to use the passcode the first time the log in, and thereafter can use their regular user name and password. If they don't have an Office 365 account or other Microsoft account, then they can just use the passcode and don't need to get a Microsoft account.

The word "full" is perhaps misleading. It's just a guest account in Azure AD for users of Microsoft or Office 365 accounts. If you set up the [SharePoint and OneDrive integration with Azure AD B2B preview](https://docs.microsoft.com/sharepoint/sharepoint-azureb2b-integration-preview), then passcode users who do not have a Microsoft or Office 365 account will also get a guest account in Azure AD.

**Comment by scanum** [comment]
@jmuehlenbein Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
