### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by Jabfag2356** [MicrosoftDocs/OfficeDocs-SharePoint#1773]
I forgot to add diagrams are also very handy for explaining concepts such as the term store hierarchy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d14723-ab30-719c-c69d-e42f94a680b5
* Version Independent ID: 182bf188-87f6-f966-4e86-77ef8927905c
* Content: [Introduction to managed metadata - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/managed-metadata#feedback)
* Content Source: [SharePoint/SharePointOnline/managed-metadata.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/managed-metadata.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Jabfag2356 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
This seems like a continuation of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1771

**Comment by get-itips** [comment]
@scanum Manuela, article has been updated to improve it, please close this. @Jabfag2356 Please review the updated article.

**Comment by scanum** [comment]
@Jabfag2356 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
