### ISSUE TITLE
PACK FAILURE migrating from file system to SharePoint Online

### ISSUE THREAD

**Issue by pefilice** [MicrosoftDocs/OfficeDocs-SharePoint#1774]
Result category: PACK FAILURE
Message: Packaging Failure:Unknown error
Error code: 0x0141000B

Logs are attached.
[Logs.zip](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/4225288/Logs.zip)

**Comment by scanum** [comment]
@pefilice thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
