### ISSUE TITLE
Modify SharePoint app link

### ISSUE THREAD

**Issue by frankok** [MicrosoftDocs/OfficeDocs-SharePoint#1775]
Hi, 
By default, the SharePoint app link goes to the https://&lt;tenantname&gt;.sharepoint.com/_layouts/15/sharepoint.aspx page.
Is there any way to modify this? We would very much like it to point to the root home page, i.e. https://&lt;tenantname&gt;.sharepoint.com/. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d22faa3-6e72-a382-cb45-fd2f98d735d2
* Version Independent ID: 8e095a7f-d8af-4105-6c4a-effe3d3856bc
* Content: [Add featured links to the SharePoint start page - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-links-list-on-sharepoint-home-page)
* Content Source: [SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@frankok Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
This isn't something you can change. I'd recommend opening a Uservoice entry at https://sharepoint.uservoice.com to provide this feedback.

**Comment by frankok** [comment]
Hi Trevor, 

I've already posted the idea on the Office 365 Uservoice:
https://office365.uservoice.com/forums/325347-office-com-home-page/suggestions/39755581-modify-sharepoint-app-link-on-office-com.

Thank you for your feedback! 
Kind Regards, 
Frank-Ove

**Comment by scanum** [comment]
@frankok Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
