### ISSUE TITLE
Sync document library on MacOS

### ISSUE THREAD

**Issue by AJRus** [MicrosoftDocs/OfficeDocs-SharePoint#1776]
Is it possible to sync a specified sharepoint document library or folder in a library on a Mac with this feature, like you can with GPO and the 'copy library ID' feature for Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos?source=docs#feedback)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@AJRus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @AJRus do you mean this https://support.office.com/en-us/article/sync-files-with-onedrive-on-mac-os-x-d11b9f29-00bb-4172-be39-997da46f913f#bkmk_syncsp ?

**Comment by scanum** [comment]
@AJRus We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
