### ISSUE TITLE
Adding guests to AAD when a users shares files or folders

### ISSUE THREAD

**Issue by stewalshy** [MicrosoftDocs/OfficeDocs-SharePoint#1778]
In the article it states "To ensure that all guests are added to your directory, use the SharePoint and OneDrive integration with Azure AD B2B preview."

This is under the section describing sharing files and folders with recipients who have a Microsoft Account.

Does the preview also create guest accounts for users who are of the following type or do they still just get a verification code even with the new AAD B2B integration?
- A work or school account in Azure AD from another organization
- An email address that isn't a Microsoft account or a work or school account in Azure AD

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint Online](https://docs.microsoft.com/en-gb/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@stewalshy Both types of users will get guest accounts in Azure AD. Users with a work or school account will be able to authenticate with their regular user name and password, and those with a non-Microsoft account will authenticate with a pass code, but they will both show up in the directory.

**Comment by stewalshy** [comment]
Thanks for the quick reply, that's what I was hoping! It might be worth updating the documentation as I found it slightly confusing due to the fact it was placed under the discussion of Microsoft Accounts only.

**Comment by stewalshy** [comment]
Also if I share a site currently I believe it will prompt the recipient to create a Microsoft Account (if they do not already have one for that email address and do not have a work or school account in another AAD tenant). Is that correct?

With the B2B integration, will this remain the same or will the instead be setup with a guest account with OTP?

**Comment by MikePlumleyMSFT** [comment]
With the default experience, sharing a site does require the recipient to have a Microsoft account, but sharing files and folders goes through an OTP experience for those with non-Microsoft accounts. With Azure B2B integration, site sharing is included in the OTP experience, so no need for a Microsoft account.

**Comment by scanum** [comment]
@stewalshy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
