### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by MDanihy** [MicrosoftDocs/OfficeDocs-SharePoint#1779]
What do you do when your migration tool will not work?  It is only supported on 2008 R2 and above.  The difficulty in working with MS products makes me want to tell our clients to go elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8673a55f-50c6-bd98-6b4f-d54db859216d
* Version Independent ID: 571c56c2-0be7-0296-ab36-3a75ff3874a9
* Content: [Migrating Content to OneDrive for Business - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/Migrating-content-to-OneDrive-for-Business#feedback)
* Content Source: [migration/Migrating-content-to-OneDrive-for-Business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Migrating-content-to-OneDrive-for-Business.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@MDanihy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
You do not have to run the tool on the source machine, it can be run remotely.

**Comment by scanum** [comment]
@MDanihy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
