### ISSUE TITLE
Storage Reports

### ISSUE THREAD

**Issue by jluce512** [MicrosoftDocs/OfficeDocs-SharePoint#1781]
Currently we have the retention policy set to 30 days we want to change that to 210 days.  What I want to know is where is all the data stored and how does it affect our allocation?  Is the data going to take up SharePoint storage or is it hidden storage on the back end that i'm not aware of.  Is there some way to find out how large our retention repository is?

**Comment by tseward** [comment]
Data retention for SharePoint is stored in a library on the same site where the data resides. It will increase your storage usage.

**Comment by scanum** [comment]
@jluce512 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
