### ISSUE TITLE
Download page not responding

### ISSUE THREAD

**Issue by Anyman99** [MicrosoftDocs/OfficeDocs-SharePoint#1782]
For days now, the download page for the Microsoft Sharepoint Migration tool has been unresponsive. I have a time-sensitive need to access this tool. Please investigate.

Ed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Anyman99 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Anyman99 
I see that the download page is working now. Besides that, here we can handle documentation issues only, for the next time that this happens, I recommend opening a ticket directly on your tenant, where they will be able to provide support in your scenario.
Thank you

**Comment by scanum** [comment]
@Anyman99 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
