### ISSUE TITLE
one of the link is not properly linked

### ISSUE THREAD

**Issue by selwyndd21** [MicrosoftDocs/OfficeDocs-SharePoint#1787]
In the text "For more information about how to use groups to help manage permissions, see Choose security groups (SharePoint Server 2010)", the url links back to the front page, which is a bit misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a791cf8-87ec-909b-7f49-0c538f91b021
* Version Independent ID: 506426a7-accd-8e74-d17a-539181b4f012
* Content: [Overview of site permissions in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/overview-of-site-permissions-in-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/sites/overview-of-site-permissions-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/overview-of-site-permissions-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@selwyndd21  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @selwyndd21 Tawei
Thanks for reporting this, I created a pr to correct the link.

**Comment by scanum** [comment]
@selwyndd21 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
