### ISSUE TITLE
Japanese name is not Home.aspx

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/OfficeDocs-SharePoint#1788]
Japanese name is not Home.aspx. but, Japanese default name is ホーム.aspx
it's the home page modernization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8659498a-6c73-763a-31a0-354010572115
* Version Independent ID: dc4c2e96-fb55-67c0-ec7b-6f1f608eb0cb
* Content: [Disable automatic modernization of classic site home pages - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/disable-auto-modernization-classic-home-pages#feedback)
* Content Source: [SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/disable-auto-modernization-classic-home-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@TomoharuMisawa  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Could you please help with this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@TomoharuMisawa , @scanum article was HumanTranslated, the homepage name is "home.aspx" to keep it consistent with source

**Comment by TomoharuMisawa** [comment]
In short, does this feature not work in a Japanese SharePoint environment? (In Japanese environment, Home.apsx becomes ホーム.aspx)

**Comment by scanum** [comment]
@TomoharuMisawa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
