### ISSUE TITLE
May we have the diagram please

### ISSUE THREAD

**Issue by merly-cortez** [MicrosoftDocs/OfficeDocs-SharePoint#1789]
May we have the diagram showing how an on-premises Active Directory uses DirSync to feed profile information to the Office 365 Directory Service, which in turns feeds the SharePoint Online profile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@merly-cortez  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
