### ISSUE TITLE
Pooling unused storage for users

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-SharePoint#1791]
I wanted to know if there is a way to pool unused space to allocate to another users who does need it?  Example: User A is a light user with 1 TB of ODfB storage but they only ever need 1 GB, can the other 999 GBs be allocated to a heavy user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@AndySanchezVM Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @AndySanchezVM, thank you for your feedback.

I understand there is no way to do it. You can give your vote this feature here:
https://onedrive.uservoice.com/forums/913534-onedrive-security-policy-administration/suggestions/35359180-pooled-storage-option-for-onedrive-premium-users

**Comment by scanum** [comment]
@AndySanchezVM Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
