### ISSUE TITLE
EnableSideBySide  = $false at the end ? 

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#1796]
The following recommendation is not clear:

"Please note that administrators can opt out of side-by-side by setting the 'enableSideBySide' value to $false."
They can opt out, meaning not use it at all ? Or opt out at the end, once ZDP is finished ?

To improve the article, couldn't it be updated with the above parameter set to false, at the end of the zdp procedure ?
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ccb7df-8dca-b5fc-4e84-e3624d2804cc
* Version Independent ID: 669daf62-d97c-3489-786b-6924c1e755b0
* Content: [SharePoint Server 2016 zero downtime patching steps](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@danone1985 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cloudgreen** [comment]
I agree it needs clarification, I was wondering about this also.

Is _side-by-side_ completely optional when doing ZDP?

**Comment by dariomws** [comment]
Hi @danone1985, thank you for your feedback.

@MikePlumleyMSFT could you kindly help with this issue? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr can you help?

**Comment by scanum** [comment]
@TroyStarr Wondering if there is an update on this issue? Thanks

**Comment by scanum** [comment]
@TroyStarr Wondering if there is an update on this issue? Thanks

**Comment by scanum** [comment]
@danone1985 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
