### ISSUE TITLE
Broken links in 2nd paragraph

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#18]
The links in the 2nd paragraph appear to be broken, such as "Software updates overview for SharePoint 2013" navigates to "http://%20https//docs.microsoft.com/SharePoint/upgrade-and-update/software-updates-overview-for-sharepoint-server-2013".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d44eab35-5200-0d0d-bb64-b5ec67cb5df6
* Version Independent ID: a9d42d04-8be6-064c-7405-c05b00cd4cef
* Content: [SharePoint Updates](https://docs.microsoft.com/en-us/SharePoint/sharepoint-updates#feedback)
* Content Source: [SharePoint/SharePointServer/sharepoint-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sharepoint-updates.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@tseward - sorry for delay. I think I just merged your fix. Appreciated!
