### ISSUE TITLE
문구 수정 요청 합니다.

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/OfficeDocs-SharePoint#180]
도메인의 중앙 저장소의.admx 파일을 붙여 \ 도메인\sysvol\domain\Policies\PolicyDefinition (여기서 도메인 는 corp.contoso.com 등의 도메인 이름으로는)와 (과 같은 해당 하는 언어 하위 폴더에.adml en-미국).

아래 글로 변경 요청 합니다.

도메인의 중앙 저장소의.admx 파일을 붙여넣기 합니다.
경로는 도메인\sysvol\domain\Policies\PolicyDefinition (여기서 도메인은 corp.contoso.com 등의 도메인 이름 입니다.)
그리고 .adml 파일은 다음과 같은 언어 하위 폴더에 붙여넣기 합니다.
예) Ko-kr

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [그룹 정책을 사용하여 OneDrive 동기화 클라이언트 설정 제어](https://docs.microsoft.com/ko-kr/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@AnnTaeYoun You were correct and our localization team is working on fixing this. Thank you for pointing this out to us.
