### ISSUE TITLE
Where is the corresponding documentation for the on-premises version?

### ISSUE THREAD

**Issue by NinjaSciurus** [MicrosoftDocs/OfficeDocs-SharePoint#1801]
Since the same sharing feature is available in SharePoint Server 2019, there should be appropriate documentation on how to manage it. Currently, there's only this page, describing the options for SharePoint Online - they can't be applied on-premises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage sharing settings - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off#feedback)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@NinjaSciurus  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @NinjaSciurus, thank you for your feedback.

@MikePlumleyMSFT could you kindly help with this issue? I think Modern Sharing Experience it's not fully available yet.

**Comment by MikePlumleyMSFT** [comment]
SharePoint Server 2019 does have shareable links, but there is no capability to share with external users. @TroyStarr are there any central admin controls for the shareable links?

**Comment by TroyStarr** [comment]
Hi @MikePlumleyMSFT, I'm afraid we have no SharePoint farm administration controls to manage sharing in SharePoint Server 2019.  As you said, on-premises sharing doesn't support external/guest sharing, so users can only share content with users that can be resolved by SharePoint Server.
