### ISSUE TITLE
What ports are used when using hybrid search?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-SharePoint#1802]
I believe its 443, but can we confirm / update this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7efb50d3-899f-efd2-37c3-34a6f3de3cb9
* Version Independent ID: 97fa8e3b-1b07-6ae0-6d20-ed67b4b20bc0
* Content: [Hybrid search in SharePoint](https://docs.microsoft.com/en-us/sharepoint/hybrid/hybrid-search-in-sharepoint#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/hybrid-search-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hybrid-search-in-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@jebalert  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jebalert, thank you for your feedback.

You can find this information in the next article:
https://docs.microsoft.com/sharepoint/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid#inbound-connectivity-requirements

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
