### ISSUE TITLE
SharePoint Online

### ISSUE THREAD

**Issue by err-unknown-username** [MicrosoftDocs/OfficeDocs-SharePoint#1806]
This article is not applicable to SharePoint Online, but it would be very helpful to point to similar documentation for SharePoint Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72787b7c-a17c-55e1-70b2-59e2aa4a74b7
* Version Independent ID: acf83d63-ea7e-5870-1534-694a5e4f8e53
* Content: [How to add refiners to your search results page in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/how-to-add-refiners-to-your-search-results-page#feedback)
* Content Source: [SharePoint/SharePointServer/search/how-to-add-refiners-to-your-search-results-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/how-to-add-refiners-to-your-search-results-page.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@err-unknown-username  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @err-unknown-username, thank you for your feedback.

I think it's the article that you are looking for:
https://docs.microsoft.com/sharepoint/refinement-web-part

**Comment by tseward** [comment]
This documentation would be the equivalent for SPO:

https://microsoft-search.github.io/pnp-modern-search/

Specifically, https://microsoft-search.github.io/pnp-modern-search/search-parts/search-refiners/

**Comment by scanum** [comment]
@err-unknown-username Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
