### ISSUE TITLE
next scheduled crawl

### ISSUE THREAD

**Issue by Madjid677** [MicrosoftDocs/OfficeDocs-SharePoint#1807]
Hi, it would be good to know what is the standard value for "next scheduled crawl" and as well if a SharePoint Admin can changed the standard value to other values like "Every hour" or "Every two hours" or "Every day" and so on. Thanks in advance for your support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18cdf74-1e86-aa79-3282-69ffc9cdd282
* Version Independent ID: 39cea6c4-be38-1908-7815-aa9ee552cedf
* Content: [Manually request crawling and re-indexing of a site, a library or a list - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/crawl-site-content#feedback)
* Content Source: [SharePoint/SharePointOnline/crawl-site-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/crawl-site-content.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Madjid677  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by heinrich-ulbricht** [comment]
In addition it would be good to know when the last crawl happened. Even if we might not be able to control the crawl we should be able to see if the crawler came by.

**Comment by dariomws** [comment]
Hi @Madjid677 and @heinrich-ulbricht, thank you for your feedback.

"SharePoint Online does not provide a real-time dashboard for monitoring the status of the crawler or indexer. Each crawl and indexing job will take a varying amount of time."
Source:
https://techcommunity.microsoft.com/t5/sharepoint-support-blog/introduction-to-sharepoint-online-search/ba-p/170708

**Comment by heinrich-ulbricht** [comment]
Adding information how to determine the last crawl time would be helpful. Something like this: https://www.techmikael.com/2015/01/crawl-time-for-sharepoint-online-and.html - if this is still applicable.

**Comment by dariomws** [comment]
My apologies @heinrich-ulbricht, I cannot add this information to the article as it's not official information.

**Comment by heinrich-ulbricht** [comment]
@dariomws Then let's make it official :D

I suspect one could use the crawl log to check an item for the last time it has been crawled, maybe even infer the crawl interval. There is some documentation around this (e.g. [how to give permissions to the log](https://docs.microsoft.com/en-us/sharepoint/set-crawl-log-permissions)) - but nothing immediately accessible on how to actually get those logs. Maybe a link to [Get-PnPSearchCrawlLog](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsearchcrawllog?view=sharepoint-ps) would be handy?

While the whole situation is not very convenient (once we waited days for items to be crawled) it is what it is. Your [comment](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1807#issuecomment-598910977) sums this up very well. So in my view this ticket (unfortunately) can be closed.

**Comment by dariomws** [comment]
Unfortunately, I think I can't do anything else, but I think the blog post is conclusive.

**Comment by Madjid677** [comment]
Hi all, thank you for all your inputs. Before closing that question, I would like to see a print screen of crawl log content as an example. Is that possible without displaying confidential info? If so, please help us. Best regards,

**Comment by dariomws** [comment]
@Madjid677:
![image](https://user-images.githubusercontent.com/33589238/76976174-613df680-6912-11ea-99f8-8b45adad28e7.png)

I'm also adding the link to Get-PnPSearchCrawlLog to see if it gets approval.

**Comment by scanum** [comment]
@Madjid677 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by hwkwicre** [comment]
I think it would be a good idea to provide why the Get-PnPSearchCrawlLog link is in the article.

**Comment by dariomws** [comment]
Hi @hwkwicre, thank you for your feedback. It was added to the **See also** section.
