### ISSUE TITLE
Client can't be setup without an Internet connection

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/OfficeDocs-SharePoint#1808]
I tried also the Mac App Store version and both won't offer input to specify the SharePoint Server farm. Instead, the completely ignore whatever I put it and try to go to the Internet for something else. Since there is no Internet, it fails doing anything.

I tried setting SharePointOnPremFrontDoorUrl with the farm's address but it will not only ignore it but go and overwrite the preference list file with the stock config.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#feedback)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@vitaprimo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
