### ISSUE TITLE
Limit external sharing per sub-domain supported?

### ISSUE THREAD

**Issue by Michaelvsk** [MicrosoftDocs/OfficeDocs-SharePoint#181]
Hi,
the format to limit external sharing is declared as "domain.com" in this documentation. Is it also supported to use sub-domains like "sub.domain.com"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Restricted domains sharing in SharePoint Online and OneDrive for Business](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Michaelvsk** [comment]
Can someone please answer the question and clarify the docs?

**Comment by AndreaBarr** [comment]
@Michaelvsk Thank you for your feedback

I want to make sure your question about sub.domain.com gets answered. Support will be able to handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs
