### ISSUE TITLE
Missing sections from the documentation

### ISSUE THREAD

**Issue by anoopras4** [MicrosoftDocs/OfficeDocs-SharePoint#1810]
We have missed two options below in this article.

1) To remove a server from a SharePoint farm by using PowerShell
2) To remove a SharePoint server from a farm by using PSConfig

The same is available on the other article (https://docs.microsoft.com/en-us/sharepoint/administration/remove-a-server-from-a-farm-in-sharepoint-server-2016#remove-a-server-from-a-sharepoint-farm-by-using-microsoft-powershell) for SPS 2016\2019.

Can we get it fixed?

Regards,
Anoop
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec189285-e725-8cad-0c09-7aabe7bfc764
* Version Independent ID: ffd7a333-8921-a3c5-d194-9c0cc08c983a
* Content: [Remove a server from a farm in SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/administration/remove-a-server-from-a-farm-in-sharepoint-2013#feedback)
* Content Source: [SharePoint/SharePointServer/administration/remove-a-server-from-a-farm-in-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/remove-a-server-from-a-farm-in-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@anoopras4  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by anoopras4** [comment]
Hi Manuela,
Any updates on this request?
Regards,Anoop Prasad
    On Saturday, March 7, 2020, 05:21:32 AM GMT+5:30, Manuela Scanu <notifications@github.com> wrote:  
 
 
@anoopras4 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by anoopras4** [comment]
Hi  Manuela,
I haven't heard back on this? Are we getting the document updated?
I can try other channels like RFC with our PG in case you can't help.
Waiting for your response.
Regards,Anoop Prasad
    On Tuesday, March 10, 2020, 06:58:30 PM GMT+5:30, anoop prasad <anoop_prasad@yahoo.com> wrote:  
 
  Hi Manuela,
Any updates on this request?
Regards,Anoop Prasad
    On Saturday, March 7, 2020, 05:21:32 AM GMT+5:30, Manuela Scanu <notifications@github.com> wrote:  
 
 
@anoopras4 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@anoopras4 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
