### ISSUE TITLE
Bad Link:

### ISSUE THREAD

**Issue by EricMcComac** [MicrosoftDocs/OfficeDocs-SharePoint#1812]
Please updat the Fix sync problems link.  Its no longer valid.

https://support.office.com/article/aaa2d172-8d45-4e94-9c04-5364d04ca2f4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a922b4-4bf0-db6f-6b05-69bd3a39610b
* Version Independent ID: 9939ca09-6f30-cea7-70f4-1c18e698e292
* Content: [Sync - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharepoint-sync#feedback)
* Content Source: [SharePoint/SharePointOnline/sharepoint-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@EricMcComac  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@EricMcComac Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
