### ISSUE TITLE
Search LinkStore Possible Limit

### ISSUE THREAD

**Issue by SuperioOne** [MicrosoftDocs/OfficeDocs-SharePoint#1813]
Is there a limit for Sharepoint Search LinkStore especially for page impression queries? It seem we can store maximum 2.075.000 query impression per month.

Update :
It seems there is daily 65.000 log limit at search service application by default. Recommended and top limit values are still unknown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d1a46c-4a3b-f99d-cca8-326b36235b1d
* Version Independent ID: d99a6050-b1af-afa2-8948-b1bba2ea7398
* Content: [Software boundaries and limits for SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0#feedback)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@SuperioOne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @SuperioOne, thank you for your feedback.

@MikePlumleyMSFT could you kindly help to get this information? Thanks!

**Comment by scanum** [comment]
@MikePlumleyMSFT could you kindly help to get this information? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr do you know?

**Comment by tseward** [comment]
See if this impacts your page impression daily limit. I haven't tested this, but based on your additional information, it does appear to be the correct setting.


```powershell
$ssa = Get-SPEnterpriseSearchServiceApplication
$ssa.QueryLogSettings

QLogEnabled              : True
CleanupDays              : 100
LoggingPercent           : 100
**TenantDailyLimit         : 65000**
SearchServiceApplication : SearchServiceApplication Name=Search Service Application

$ssa.QueryLogSettings.TenantDailyLimit = 80000
$ssa.Update()
```

**Comment by scanum** [comment]
@SuperioOne  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
