### ISSUE TITLE
Document Version History is not maintained in SPMT

### ISSUE THREAD

**Issue by ranglanimanish90** [MicrosoftDocs/OfficeDocs-SharePoint#1816]
I am using SharePoint Migration Tool, in Advanced Settings, I have enabled to keep file version history but every time when I run the tool, it overwrites the file. Is this a known limitation though in the documentation it says version history is maintained?

**Comment by scanum** [comment]
@ranglanimanish90 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
