### ISSUE TITLE
[LOC] Sentence does not make sense

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#1817]
There is a sentence which does not make sence in the article below.

Repro steps:
1. Go to https://docs.microsoft.com/en-us/SharepointMigration/mover-o365-to-o365
2. Search for "Test for multiple usone user, then three to five."

Actual results:
Test for multiple usone user, then three to five.
Expected results:
Test for multiple users, three to five. ?

GH article:
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-o365-to-o365.md
![image](https://user-images.githubusercontent.com/47977325/76080762-f0a8e880-5fa7-11ea-8552-e1b356804c63.png)

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
