### ISSUE TITLE
All the Sharing settings are grayed out.

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SharePoint#1818]
Is there another place I have to go to set this?  I'm following this page (https://docs.microsoft.com/en-us/microsoftteams/guest-access-checklist) and did Steps 1-4 but Step 5 takes me to this section and I can't change any settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3106844b-caae-38c5-3c88-fb17a9d67536
* Version Independent ID: 3e88e60e-24a3-cd83-9bfc-8bc3037a86ce
* Content: [Change the external sharing setting for a site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site)
* Content Source: [SharePoint/SharePointOnline/change-external-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-external-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@kelemvor33 usually if the site-level sharing settings are grayed out, it means that sharing has been disabled at the organization level. Take a look at [Change the organization-level external sharing setting](https://docs.microsoft.com/sharepoint/turn-external-sharing-on-or-off#change-the-organization-level-external-sharing-setting).

**Comment by scanum** [comment]
@kelemvor33 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
