### ISSUE TITLE
External users aka Guest cannot have a licence

### ISSUE THREAD

**Issue by Jakub-Urban** [MicrosoftDocs/OfficeDocs-SharePoint#182]
In the article there is a mention that #EXT# users can have assigned license. 
You should better describe this is possible only through the MORE button, as described here. 

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/assign-a-pro-license-to-a-guest-user-in-o365-admin/f70b2a84-269d-43f4-8890-1d0e65c307a2 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by kaarins** [comment]
@Jakub-Urban , thank you for this tip. You're right, the command for assigning a license to an external user is a little hard to find. I updated the text in the article and the changes will be published shortly. Thanks!
