### ISSUE TITLE
Is Directory ID = <Name>.OnMicrosoftOnline.com

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/OfficeDocs-SharePoint#1820]
Hi,
In this document the Tenant ID is clarified as Directory ID

Can you clarify by adding few lines explaining whether the Directory ID (GUID) is mapped to  subdomain of &lt;Name&gt;.OnMicrosoftOnline.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93351c-948b-67f7-edd7-8f84982f1834
* Version Independent ID: b3d722cc-3e6e-9b0a-efdb-7d61a76c874f
* Content: [Find your Office 365 tenant ID](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id)
* Content Source: [OneDrive/find-your-office-365-tenant-id.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/find-your-office-365-tenant-id.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@sing-ideas  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sing-ideas** [comment]
Many of my doc doubts or clarification request are around - <Tenant>.OnMicrosoftOnline.com - 

Need to do a feasibility study for a multi-tenant application using CDS. Looks like Docs are using different terminology for same thing, like Tenant, Instance, Org. 

Now in Power Platform CDS, the terminology "Environment" has become subset of Tenant. 

Is <Name>.OnMicrosoftOnline.com is the power apps tenant doc refers to?

Example :

Our eMaili ID = <User1-(n)>@MyDomain.com


Should be able to login into
<tenant1>@OnMicrosoftOnline.com
<tenant2>@OnMicrosoftOnline.com
<tenant3>@OnMicrosoftOnline.com

**Comment by dariomws** [comment]
Hi @sing-ideas, thank you for your feedback.

I think I don't understand you. Each O365 tenant has a unique ID/directory ID and a unique initial domain (<companyname>.onmicrosoft.com). I think there is no direct relationship.

**Comment by scanum** [comment]
@sing-ideas Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
