### ISSUE TITLE
What happens to subsites of the current root site?

### ISSUE THREAD

**Issue by rjgeeky** [MicrosoftDocs/OfficeDocs-SharePoint#1821]
Our current root site is a classic Enterprise Wiki page with dozens of subsites. The site that will be promoted is a modern communications site with no subsites. Creating subsites is not allowed for modern communication or team sites in our tenant.

What is meant by 'Replacing the root site with another site replaces any subsites within the sites.' The documentation is not clear at all on this. Do the subsites of the current root site become subsites of the newly promoted root site? Or do all the current subsites just get deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/modern-root-site?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@rjgeeky  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
@rjgeeky this feature works at the site collection level, so the entire current site collection (including all subsites) will be archived and replaced with the new site collection (which in your case would not have subsites). I will make this clearer in the article. Thanks for this feedback.
