### ISSUE TITLE
Can you please clarify this document for SharePoint 2013? SP2013 does not support to configure TLS for outgoing email. The document will mislead our customers.

### ISSUE THREAD

**Issue by Jiankui2018** [MicrosoftDocs/OfficeDocs-SharePoint#1822]
[Enter feedback here]
Can you please clarify this document for SharePoint 2013? SP2013 does not support to configure TLS for outgoing email. The document will mislead our customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281f143b-b1d6-582a-25a7-d803518181a4
* Version Independent ID: 8f82c931-36a6-d4a2-822c-3dce64beb25a
* Content: [Configure outgoing email for a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/outgoing-email-configuration)
* Content Source: [SharePoint/SharePointServer/administration/outgoing-email-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/outgoing-email-configuration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Jiankui2018  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Jiankui2018, thank you for your feedback.

This article doesn't have instructions to configure TLS on the IIS SMTP server. You don't need to configure it on SP2013. Sorry but maybe I misunderstood you.

**Comment by TroyStarr** [comment]
Hi @dariomws, I think the concern is that this article discusses the "Use TLS connection encryption" setting in a couple of different places.  However, TLS connection encryption was first introduced in SharePoint Server 2016.  Older versions of SharePoint don't have this feature.

Maybe we should add a note about this to the top of the article, just like this note we added about SMTP authentication:

> The SMTP authentication feature is only available in SharePoint Server 2019.

**Comment by dariomws** [comment]
@TroyStarr agree I think a note is a good idea. Thank you!

Only 2019? What about 2016?

**Comment by Jiankui2018** [comment]
Yes, that's what I would like to see. Thanks all.
