### ISSUE TITLE
Remove outdated document

### ISSUE THREAD

**Issue by pschneidermsft** [MicrosoftDocs/OfficeDocs-SharePoint#1825]
This document is no longer valid and should be removed for SharePoint Online.  The current search architecture doesn't support removing documents in this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6483a618-3769-564c-6497-cede9ab053c9
* Version Independent ID: 6953d747-40ec-6a06-7877-a98e42dcce1f
* Content: [Remove search results - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/remove-search-results#feedback)
* Content Source: [SharePoint/SharePointOnline/remove-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/remove-search-results.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@pschneidermsft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @pschneidermsft, thank you for your feedback.

Sorry but I think it's not to remove documents, you only remove URLs from search results. If you are sure that this option doesn't work I can apply a pull request to check if it gets approval.

**Comment by pschneidermsft** [comment]
Actually, things are more complicated than what I originally wrote and what the article says.

Yes, the page is for removing URLs from search results (we normally refer to indexed items as documents no matter what they really are).  But putting a URL in on this page won’t always work.  It might be better to take this discussion to email and include a few people from the crawl team to decide how we can better word things on this page, assuming we want to keep it.

**Comment by dariomws** [comment]
@pschneidermsft thank you! Let's do it in this way.

**Comment by scanum** [comment]
@pschneidermsft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
