### ISSUE TITLE
Setting files to Online-only - Windows Server 2008

### ISSUE THREAD

**Issue by c-arthurs** [MicrosoftDocs/OfficeDocs-SharePoint#1826]
Hi, I can use the attrib +u command on my windows 10 pc to offload files to the cloud. 

When I tried to deploy this script on a Windows Server 2008 machine I get the error - Invalid switch - -U 

Any ideas on the best automated way to set online only on a windows 2008 server? 

Thanks

**Comment by scanum** [comment]
@c-arthurs thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
