### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by benchapmanvuw** [MicrosoftDocs/OfficeDocs-SharePoint#1828]
Can I request that “You’ll know your done when” be replaced with “You’ll know you’re done when”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 871e3ed2-4749-654b-610d-c06167103ee1
* Version Independent ID: 685537c2-c689-48bb-579e-ecbc0778f7ae
* Content: [Modern intranet roadmap - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/intranet-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/intranet-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/intranet-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@benchapmanvuw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@benchapmanvuw Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
