### ISSUE TITLE
Remove reference to "license" and "fee"

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-SharePoint#1830]
In this "Number of users to migrate" section there are references to "license" and "fee". I think this is just because it's a cut'n'paste from the mover.io documentation. I don't think this no longer applies since there is no longer a specific mover.io license required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655d8e8e-ff4d-ad9a-4962-417499d583f6
* Version Independent ID: 1b333710-811a-4fdd-d51f-81e3f9027135
* Content: [How to Migrate from On-premises file shares to Office 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-fileshare-to-o365)
* Content Source: [migration/mover-fileshare-to-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-fileshare-to-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Mikael:  This language is in the process of being removed from the documentation.  Mover is free, and no licensing fees apply any longer.    Joanne
