### ISSUE TITLE
Configure team site libraries to sync automatically important info section

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#1834]
For this GPO the text in the important section says "Do not enable this setting for libraries with more than 5,000 files or folders. Do not enable this setting for the same library to more than 1,000 devices" but doesn't explain why, can we provide some more info here, on what the user experience is, a lot of people move departmental file shares into SharePoint and may look at this feature to sync to keep a consistent windows explorer view for users. Is it that the sync would constantly be spinning looking for changes? I think some more info is required here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutoMountTeamSites)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@obhayes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @obhayes, thank you for your feedback.

I understand that this is the reason:
https://docs.microsoft.com/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#sync

But now this limit don't apply to the new client and I think it must be updated. I will do.

**Comment by dariomws** [comment]
About the 1000 devices limit, it's related to Windows Push Notification Services (WNS):
https://docs.microsoft.com/onedrive/sync-process

**Comment by scanum** [comment]
@obhayes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
