### ISSUE TITLE
What does "The number of CPU cores is specified here, not the number of CPU threads." mean?

### ISSUE THREAD

**Issue by felixbohnacker** [MicrosoftDocs/OfficeDocs-SharePoint#1836]
The statement "The number of CPU cores is specified here, not the number of CPU threads." caused quite a bit of confusion for me. 

Are the CPU requirements for the different servers referring to the amount of virtual processors the respective virtual machine should have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e12588-d632-a9fa-c3e8-aa6bb1b46f73
* Version Independent ID: a7c0a603-f37a-ebad-2870-b35a9b3e76e3
* Content: [Plan enterprise search architecture in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/plan-enterprise-search-architecture#feedback)
* Content Source: [SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
A physical CPU can have more than one thread (i.e. SMT) so the idea here is that you would not be considering SMT when performing your implementation.

**Comment by scanum** [comment]
@felixbohnacker Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by felixbohnacker** [comment]
@tseward Thank you, that was exactly what I was wondering.
