### ISSUE TITLE
Should this work for Teams?

### ISSUE THREAD

**Issue by AmoebaFrank** [MicrosoftDocs/OfficeDocs-SharePoint#1837]
I have successfully implemented this and it works as expected in SharePoint, displaying 'Your organisation doesn't allow you to download.....' users can edit but have no option to download files.

My reason for implementing is to restrict downloading via Teams. After implementing I can see in Teams that the 'Download' option has been removed from the menu bar which is good.

When I open an Office document within Teams I get the message 'Your organisation doesn't allow you to download.....' but if you select the ellipsis [More Options] you have the option to Download and it allows the user to download. It's the same for files I cannot preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@AmoebaFrank thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
