### ISSUE TITLE
Already-provisioned users

### ISSUE THREAD

**Issue by OwainYoung** [MicrosoftDocs/OfficeDocs-SharePoint#1844]
How does Request-SPOPersonalSite behave when any of the specified users already have a personal site?  

Or put another way: in an organisation where some users have already been using their personal site and some haven't, is there any problem with running Request-SPOPersonalSite for every user?  Including those that have already used their personal site.

Thanks

**Comment by tseward** [comment]
There is no impact/change as it will detect the site was already provisioned.

**Comment by OwainYoung** [comment]
Thanks!

**Comment by scanum** [comment]
@OwainYoung Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
