### ISSUE TITLE
Support SharePoint 2016

### ISSUE THREAD

**Issue by staehelir** [MicrosoftDocs/OfficeDocs-SharePoint#1845]
How can I migrate from SharePoint 2016 to SharePoint Online?
As it seems, SharePoint 2016 is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
SharePoint 2016 is not supported by SPMT at this time. Microsoft recently purchased mover.io so you may want to investigate using that tool.

Otherwise, you can look at 3rd party options of which there are many.

**Comment by staehelir** [comment]
I got the info from mover.io _Unfortunately, with the acquisition by Microsoft, we are no longer able to migrate data from SharePoint On-premises._

**Comment by staehelir** [comment]
at this time, it is only possible to migrate from SharePoint 2016 to SharePoint Online with 3rd party tools.
