### ISSUE TITLE
auto update statistics ? 

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#1846]
this option is logical to be set to False.
There is no pointer about this. thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70a2b05-ceef-af7f-78b2-18100771af3c
* Version Independent ID: 2fa1c886-a3cf-4c90-7d36-5257ea4d593a
* Content: [Storage and SQL Server capacity planning and configuration (SharePoint Server)](https://docs.microsoft.com/en-us/SharePoint/administration/storage-and-sql-server-capacity-planning-and-configuration?redirectedfrom=MSDN#Section6)
* Content Source: [SharePoint/SharePointServer/administration/storage-and-sql-server-capacity-planning-and-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/storage-and-sql-server-capacity-planning-and-configuration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Can you expand upon what you mean by 'no pointer', as in there is no instruction on how to do this?

**Comment by scanum** [comment]
@danone1985  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
