### ISSUE TITLE
Need more detail

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/OfficeDocs-SharePoint#1854]
I need it to show the anonymous identifiers in addition to the names so I can match them up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f92a9b5-b3b2-aceb-9813-a3e48bb469ca
* Version Independent ID: 55aa37c6-998b-a8d8-8986-88c4ed868aea
* Content: [Get a list of all user OneDrive URLs in your organization](https://docs.microsoft.com/en-us/onedrive/list-onedrive-urls#feedback)
* Content Source: [OneDrive/list-onedrive-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/list-onedrive-urls.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@cfizz34  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by cfizz34** [comment]
When I run this all I get is the username via numbers and not the friendly name.  I need a way to match this up to the real username,displayname, UPN that comes from the PS command you guys are suggesting to use to get all the onedrive accounts.

    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/users/?$skiptoken=X%2744537074020001000000133A313535373535403438666F7274792E636F6D29557365725F30313437363862312D303165622D343633362D383637302D613239376664306435373734B900000000000000000000%27",
    "value": [
        {
            "businessPhones": [],
            "displayName": "112357",
            "givenName": "112357",
            "jobTitle": null,
            "mail": null,
            "mobilePhone": null,
            "officeLocation": null,
            "preferredLanguage": null,
            "surname": null,
            "userPrincipalName": "112357@48forty.com",
            "id": "a11ef910-c4eb-4613-b976-6fbfae6474db"
        },

**Comment by scanum** [comment]
@cfizz34 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
