### ISSUE TITLE
"LimitedAccessFileType WebPreviewableFiles (default)" - Inaccurate Information Correction

### ISSUE THREAD

**Issue by brent-smith-msft** [MicrosoftDocs/OfficeDocs-SharePoint#1855]
The current value on this section is:

-LimitedAccessFileType WebPreviewableFiles (default) Allows users to preview Office files and other file types (such as PDF files and images) in the browser. Note that the contents of file types other than Office files are handled in the browser. This option optimizes for user productivity but offers less security for files that aren't Office files.

This is no longer correct and is misleading. A correct/concise version would be:

-LimitedAccessFileType WebPreviewableFiles (default) Allows users to preview Office files in the browser. This option optimizes for user productivity but offers less security for files that aren't Office files. **Warning:** This option is known to cause problems with PDF and image file types because they can be required to be downloaded to the end user's machine to render in the browser. Plan the use of this control carefully. Otherwise, your users could be faced with unexpected "Access Denied" errors.

**************************

The reason is that with this option, only files that can be rendered in Office Online Server (OOS) can be accessed by unmanaged devices (and just in read-only mode).

The original text suggests that PDFs and image files (like JPG/GIF) could be downloaded or rendered with this setting in place. This is not true or correct.

The reality is that PDF files and image files that are downloaded to an unmanaged device via direct links (or having been embedded in the SharePoint site) are actually blocked from download, by policy, to those devices due to their unmanaged state.

NOTE: This can also happen when this conditional access policy is in place and the users create sharing links with the "People with Existing Access" policy on the sharing link.

**Comment by scanum** [comment]
@brent-smith-msft Please link the documentation you are referring to. Thanks!

**Comment by brent-smith-msft** [comment]
Hi @scanum - https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#advanced-configurations is the article.

Sorry for any confusion on my part when I submitted. I didn't realize that the source URL would not carry over into my feedback automatically.

**Comment by brent-smith-msft** [comment]
Just adding a note that now 2 customers have opened Sev-A tickets because they did not understand the article. The suggested change will alleviate and remove any misunderstandings on the topic.

**Comment by brent-smith-msft** [comment]
The suggested text has been modified to more appropriately reflect the reality that our customers face when they use this option to control unmanaged devices.

**Comment by dariomws** [comment]
Hi @brent-smith-msft, thank you for your feedback.

I have one question. Can they preview some PDF and image files using the browser or it never works?

Thanks.

**Comment by brent-smith-msft** [comment]
Hi @dariomws  - No. It is not possible to preview PDF and image files using a browser in the scenario that I laid out.

**Comment by scanum** [comment]
@brent-smith-msft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
