### ISSUE TITLE
Support for Edge, Chrome and ect..

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/OfficeDocs-SharePoint#1856]
Hi All,
 
I just completed configuring this and things works as expected on IE, but not with Edge, Chrome ect. Please update the article clarifying what works and on what condition. This feature is awesome, but right now useless because no one uses IE as browser anymore. That said when can we see an updated versjon of this feature.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JimmyHang thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
