### ISSUE TITLE
Error: Please check that the target document library exist in target site.

### ISSUE THREAD

**Issue by liaqatba** [MicrosoftDocs/OfficeDocs-SharePoint#1859]
I am doing a pilot project to move users data from shared path UNC to OneDrive for Business by using SPMT. I am using  **Select .JSON or .CSV file for bulk migration**. But when I choose below CSV file and click Add then getting the below error:

**CSV File**
"\\DC01\C$\temp\diegos",,,https://m365x683021-my.sharepoint.com/personal/user_m365x683021_info,user,

**Error:**
Task 1. Please check that the target document library exist in target site.

Need Help to resolve this issue.

**Comment by scanum** [comment]
@liaqatba thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
