### ISSUE TITLE
OneDrive Example

### ISSUE THREAD

**Issue by AndyTuke** [MicrosoftDocs/OfficeDocs-SharePoint#1860]
Can you please give some examples for OneDrive migrations as well as SharePoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration#feedback)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@AndyTuke Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by robertcaretta** [comment]
I am interested in this as well. Thank you.

**Comment by dariomws** [comment]
Hi @AndyTuke and @robertcaretta, thank you for your feedback.

This article apply to both (SP and OneDrive), so you should use this format. But maybe I don't understand your suggestion.

**Comment by robertcaretta** [comment]
The documentation doesn't make a reference to OneDrive usage. So as a reader I can not assume it is supported. I think some basic examples of usage would help, or even add another Q&A to the FAQs section.

**Comment by dariomws** [comment]
Understood now!

**Comment by AndyTuke** [comment]
Its the formatting of the csv file for OneDrive that isn't clear.  A previous github question that is now closed gives an example, otherwise I doubt I would have worked it out

**Comment by dariomws** [comment]
Hi @AndyTuke,

You just need to add the OneDrive Personal URL, Documents as target library and an optional subfolder. It's no more than that. I tested it and works in this way.

**Comment by AndyTuke** [comment]
@dariomws Thanks, I know that now.
But the issue was logged here because this is the official Microsoft documentation on this process, and for someone who doesn't know how to do this, they're going to struggle to learn from reading this page.  I was suggesting that the documentation is updated to include a clear csv file and json example for a OneDrive migration.

**Comment by robertcaretta** [comment]
I am in agreement with this statement.

**Comment by dariomws** [comment]
@AndyTuke I added an OneDrive example in the CSV section 2 days ago. You can see it in the PR above.

**Comment by AndyTuke** [comment]
Thanks, I can see it in the PR.  How long till it appears in the docs?  Its not there yet.

**Comment by dariomws** [comment]
Once the state changes from Open to Merged, it would take a couple of hours.

**Comment by JonesMikael** [comment]
Still no example? I'd love to see once, specially if it has a scenario when copying to a subfolder in the path.

**Comment by scanum** [comment]
@robertcaretta Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
