### ISSUE TITLE
Unable to find Manager as site admin after Cleanup my Sites job runs. 

### ISSUE THREAD

**Issue by cblaylo3** [MicrosoftDocs/OfficeDocs-SharePoint#1863]
The MS documentation [here](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion?redirectSourcePath=%252farticle%252fef883c48-332c-42f5-8aea-f0e2366c15f9) states that this job will provide the manager with full access to the deleted users onedrive. My problem isn't that this isnt happening, my problem is that I can find any way to verify it through powershell. 

When I run **Get-SPOuser <OnedriveURLhere> | Where-object {$_.IsSiteAdmin -eq $true}** I get no results for my deleted users. From what I have been able to find online, the "clean up my sites" job should be adding the Manager as a secondary site collection administrator. 
I'm not sure what is wrong here. Is powershell incorrectly reporting this back, am I running the wrong commands or is it an entirely different process than what I have been able to find?

**Comment by scanum** [comment]
@cblaylo3 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
