### ISSUE TITLE
Limit access to specific site has wrong cmdlet

### ISSUE THREAD

**Issue by CThreadgill** [MicrosoftDocs/OfficeDocs-SharePoint#1866]
Under step 9 to limit access to multiple sites, the command after the pipe is currently Set-SPOTenant however it needs to be Set-SPOSite

**Comment by scanum** [comment]
@CThreadgill Please link the documentation you are referring to. Thanks!

**Comment by dariomws** [comment]
Hi @CThreadgill, thank you for your feedback.

I think this issue is related to this article:
https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices#limit-access-using-powershell
Please confirm.

**Comment by scanum** [comment]
@CThreadgill Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
