### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Disorganise** [MicrosoftDocs/OfficeDocs-SharePoint#1867]
In the sync section  https://docs.microsoft.com/en-us/OneDrive/plan-onedrive-enterprise#sync , it says "then you'll need to follow a slightly different process to upgrade to the new sync clieappnt"

I assume "clieappnt" is a typo and should be "client app"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/OneDrive/plan-onedrive-enterprise#sync)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Disorganise  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Disorganise Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
