### ISSUE TITLE
Is file retention linked to file ownership and can it be migrated?

### ISSUE THREAD

**Issue by Disorganise** [MicrosoftDocs/OfficeDocs-SharePoint#1868]
The text says:  "you can also configure data retention settings for users whose accounts have been deleted (the maximum value is 10 years)." with link back to the to this same page which is not overly useful.
If multiple people in an organisation access/update a particular file, and the original creator leave and has their account deleted, is the file at risk of being automatically deleted at the end of the retention period?  Is there a simple way to report on such files and address the (potential) issue?
If this is already documented somewhere, please add the link to the section above :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/OneDrive/plan-onedrive-enterprise#manage-onedrive-using-microsoft-endpoint-configuration-manager)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Disorganise  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Disorganise, thank you for your feedback.

OneDrive is a Personal Cloud Storage. You can share files with colleagues, instead of attaching in an email, but if you want to share files with your team and collaborate on them you need to use SharePoint Online.
I can add that you can assign this Personal Cloud Storage to another user:
https://docs.microsoft.com/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide#access-a-former-users-onedrive-documents

**Comment by Disorganise** [comment]
Thanks.  I had read OneDrive and SharePoint utilise the same back-end blob storage and assumed they were essentially alternative front-ends to each other, especially as the share link interface is identical.
So just to be clear...
If I store and share a file via OneDrive, the retention policy engine applies and file is deleted some time after my account is deleted.
If I store and files via SharePoint and then sync them to my PC via OneDrive, and then share via OneDrive, the retention policy does NOT apply because the files are 'owned' by SharePoint rather than OneDrive.
Do I have that correct?

**Comment by dariomws** [comment]
If you store files in SharePoint and remove a user, only OneDrive files will be removed after retention period, not SharePoint files.

**Comment by scanum** [comment]
@Disorganise Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
