### ISSUE TITLE
Connection not working

### ISSUE THREAD

**Issue by abymanutd** [MicrosoftDocs/OfficeDocs-SharePoint#1870]
Hello,

Starting today, am not able to pass authentication with SPMT.
After inserting username and password, SPMT its stuck in the loading state . Not able to connect with source or destination site. 
Please see the image. 
![spmt](https://user-images.githubusercontent.com/24238949/77348453-ddb84700-6d0f-11ea-8fed-3c586d6d4e04.jpg)

**Comment by scanum** [comment]
@abymanutd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
