### ISSUE TITLE
1000 domains limit

### ISSUE THREAD

**Issue by junterpfe** [MicrosoftDocs/OfficeDocs-SharePoint#1871]
contradicting info here https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing
is it 1000 or 3000?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage sharing settings - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@junterpfe  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@junterpfe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
