### ISSUE TITLE
Request add Information

### ISSUE THREAD

**Issue by hisuzuki** [MicrosoftDocs/OfficeDocs-SharePoint#1872]
Please add Information for NOTE.
“This setting affects the other web applications such as Teams ...”
And list all affected applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hisuzuki  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@hisuzuki thank you for reaching out and helping improve MS Docs. This article was recently updated. Please let me know if you still need help.
