### ISSUE TITLE
Automated site quota management

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/OfficeDocs-SharePoint#1873]
If is mentioned that if we will use automated site quota management, then all sites will get 25TB of storage quota. What will happen in a scenario where there are thousands of sites and each site will have a quota limit of 25 TB but then total SP quota becomes less than as compared to no. of sites x 25TB and in actual all sites are using very less space (not full 25 TB). Could you please clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@prashant1380 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @prashant1380, thank you for your feedback.

In this case, you should monitor your storage and when you are running out of storage for your tenant/organization, you should buy more:
https://docs.microsoft.com/microsoft-365/commerce/add-storage-space

**Comment by prashant1380** [comment]
Thanks for your comment. But if we have not utilized the full quota then why we need to buy extra? Lets take this example:
- Total quota available for SPO tenant = 10 TB (with automated quota management)
- Due to automated quota management : 10 SPO sites x 25 TB = 250 TB
- Actual space utilization of each site: 10 SPO sites x ~1 GB =  ~5 GB
So based on this given example, do you think we have to buy 240 TB extra space? Because in actual we are using only 5GB out of available 10 TB

**Comment by dariomws** [comment]
@prashant1380 you need to buy extra storage if you reach your tenant limit. In your example, you didn't reach it yet. Just one correction: "Actual space utilization of each site: 10 SPO sites x ~1GB = ~10GB"

Similar example but in this case you reach the quota limit:
- Total quota available for SPO tenant = 10TB (with automated quota management)
- Due to automated quota management : 10 SPO sites x 25TB = 250TB
- Actual space utilization of each site: 10 SPO sites x ~1TB = ~10TB

**Comment by dariomws** [comment]
This information is in the paragraph:
"By default, your SharePoint storage is available in a central pool from which all sites can draw. You, as a global or SharePoint admin, don't need to divvy up storage space or reallocate space based on usage. That's all handled automatically: sites use what they need when they need it. If you previously set storage limits manually and switch to using pooled storage, SharePoint resets all the limits to 25 TB (25600 GB). (**Note that the total storage for your organization might be less than 25 TB**.)"

**Comment by scanum** [comment]
@prashant1380 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
