### ISSUE TITLE
Modern Search & Cloud Hybrid Search

### ISSUE THREAD

**Issue by srinivasamyneni** [MicrosoftDocs/OfficeDocs-SharePoint#1874]
How does this works with Modern Search in Office 365. Does it allow to add a new vertical for SP 2016 results to appear as a separate tab in Modern Search results page? Like "All", "Files", "Sites", "People", "News" and "SP2016".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d441302d-3491-cfbe-c1a9-1478ece0e49f
* Version Independent ID: 45a81d7d-3397-7b18-733a-a70c095f9ca6
* Content: [Cloud hybrid search service (Cloud SSA) FAQ](https://docs.microsoft.com/en-us/sharepoint/hybrid/cloud-hybrid-search-faq#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/cloud-hybrid-search-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/cloud-hybrid-search-faq.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@srinivasamyneni Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@srinivasamyneni Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
