### ISSUE TITLE
External O365 users not recieving invitation email

### ISSUE THREAD

**Issue by Maartenf2** [MicrosoftDocs/OfficeDocs-SharePoint#1875]
Hi,

I am testing the SP B2B preview.

When I share my file with an external Office365 user, this user doesn't get the invitation e-mail.

In my AAD, the user is added as 'invited user'.

Any idea how to resolve this?

It seems to be happening only when sharing to O365 domains, I've tried multiple.

Kr,

Maarten

**Comment by scanum** [comment]
@Maartenf2 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
