### ISSUE TITLE
BLOB Cache Performance Counters

### ISSUE THREAD

**Issue by jacobmoran** [MicrosoftDocs/OfficeDocs-SharePoint#1876]
The BLOB Cache Performance Counters are located in the \SharePoint Disk-Based Cache object, not the \SharePoint Publishing Cache as referenced above. (Typeperf.exe -q for the win!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889bdc1a-54b0-0aea-3871-879c562261aa
* Version Independent ID: 3de69659-cf91-ba73-683d-0ba9fd3a763d
* Content: [Monitor cache performance in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/administration/monitor-cache-performance#feedback)
* Content Source: [SharePoint/SharePointServer/administration/monitor-cache-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/monitor-cache-performance.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jacobmoran  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jacobmoran, thank you for your feedback.

@JoanneHendrickson could you kindly help?

This is what I see:
![image](https://user-images.githubusercontent.com/33589238/78067313-e2fb3e80-736c-11ea-99a5-4a6b956497a8.png)
![image](https://user-images.githubusercontent.com/33589238/78067336-ed1d3d00-736c-11ea-9d4e-132e6599dd30.png)
![image](https://user-images.githubusercontent.com/33589238/78067354-f8706880-736c-11ea-8847-0f0536fc94b1.png)

![image](https://user-images.githubusercontent.com/33589238/78067370-00c8a380-736d-11ea-9bbd-9601f04b13d6.png)
![image](https://user-images.githubusercontent.com/33589238/78067392-0b833880-736d-11ea-850e-f0d543cf814b.png)

Thanks!

**Comment by jacobmoran** [comment]
That is correct, but the documentation does not reference the SharePoint Disk-Based Cache counter group when discussing BLOB cache performance but instead references the SharePoint Publishing Cache counter group:[cid:d26b994c-5a09-413b-8959-8a0fc1556610]

Thank you,
Jacob Moran

________________________________

**Comment by scanum** [comment]
@JoanneHendrickson could you kindly help?

**Comment by scanum** [comment]
@JoanneHendrickson could you kindly help?

**Comment by dariomws** [comment]
@JoanneHendrickson could you kindly help?

**Comment by scanum** [comment]
@JoanneHendrickson could you kindly help?

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by JoanneHendrickson** [comment]
@TroyStarr   Can you confirm this is correct?

**Comment by tseward** [comment]
@scanum please close this issue.
