### ISSUE TITLE
SyncAadB2BManagementPolicy $true

### ISSUE THREAD

**Issue by burtzz** [MicrosoftDocs/OfficeDocs-SharePoint#1878]
May I  get more details on what does this command change?
taken from a question already closed: "When you run Set-SPOTenant -SyncAadB2BManagementPolicy $true it does tell SPO to sync AAD policies/settings"
What AAD policies/settings are synced?
I got external sharing on SP and OD enabled by group membership, also we limit the domains with who we can share with on the SP root and also at the site collection level.
At b2b level I got this option on Collaboration restrictions:   Allow invitations to be sent to any domain (most inclusive)

What happens when I enable this sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@burtzz when you enable B2B sync, then SharePoint will respect the Azure AD settings in the same way that SharePoint sites respect the SharePoint tenant settings. In the case of  Collaboration restrictions: Allow invitations to be sent to any domain (most inclusive), you can invite guests from any domain from within Azure, but any SharePoint or OneDrive restrictions you've put in place will hold true for those workloads. I believe Office 365 groups and Teams rely on the Azure AD settings for guest sharing restrictions. @MSFTRafLop am I missing anything?

**Comment by burtzz** [comment]
Great, thanks. Glad that Sharepoint/Onedrive still hold true.
I did opt-in for B2B a few hours ago.
At sharepoint admin level I can still see the list of allowed external domains.
To make sure I tried to share with a domain that isn't on the list and it didn't work.

**Comment by scanum** [comment]
@burtzz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
