### ISSUE TITLE
Site administrator vs. Collection administrator controlled

### ISSUE THREAD

**Issue by swatt6400** [MicrosoftDocs/OfficeDocs-SharePoint#1879]
I came looking for details on those.  What exactly are the implications of choosing one vs. the other?  No explanation really, except reciting that you can choose one or the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38c711b7-da62-2354-b70c-aa94ddfab6f9
* Version Independent ID: 84b1d7f4-39a1-ef00-25df-fccdef6db1e3
* Content: [Manage the lock status for site collections in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/manage-the-lock-status-for-site-collections)
* Content Source: [SharePoint/SharePointServer/sites/manage-the-lock-status-for-site-collections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/manage-the-lock-status-for-site-collections.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@swatt6400 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@swatt6400 thank you for reaching out and helping improve MS Docs. I see the article has recently been updated. From what I've researched I think the correct term is site collection administrator, so I don't think they are separate entities (site administrator/collection administrator) Please let me know if you need further help.

**Comment by swatt6400** [comment]
Thanks for following it up and improving the docs!
    
    On 6/4/2020 7:20 AM, Lindsay wrote:
    
    
      
      @swatt6400
        thank you for reaching out and helping improve MS Docs. I see
        the article has recently been updated. From what I've researched
        I think the correct term is site collection administrator, so I
        don't think they are separate entities (site
        administrator/collection administrator) Please let me know if
        you need further help.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1879#issuecomment-638760302",
"url": "https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1879#issuecomment-638760302",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by scanum** [comment]
@swatt6400 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
