### ISSUE TITLE
We should note the current on-prem limitation 

### ISSUE THREAD

**Issue by mikelee-msft** [MicrosoftDocs/OfficeDocs-SharePoint#1880]
There is a current limitation of being able to only sync one on-prem web application URL Farm wide.  We are seeing that many customers that are trying to sync more then one on-prem web applications (URL) and failing, then opening support cases. Can we please update this article to state the known limitation to help customers avoid any misunderstandings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0d9527-a78b-d18b-d218-881fac11423d
* Version Independent ID: 3ad8fc7b-4869-dbdc-802b-a804f65d0e39
* Content: [Configure syncing with the new OneDrive sync app for SharePoint 2019](https://docs.microsoft.com/en-us/sharepoint/install/new-onedrive-sync-client#feedback)
* Content Source: [SharePoint/SharePointServer/install/new-onedrive-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/new-onedrive-sync-client.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mikelee-msft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mikelee-msft** [comment]
Thank you!!   Looks Great!
