### ISSUE TITLE
A mistake in the content of the article

### ISSUE THREAD

**Issue by Disc0veryX** [MicrosoftDocs/OfficeDocs-SharePoint#1882]
There are two same text links in the content of the article - "How to import a query suggestions file to SharePoint Server". However the first one should be "How to import a query suggestions file to SharePoint Online".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a4cea1-5da6-266b-0e72-9fc0c3cd20f1
* Version Independent ID: d1b1c93e-0aff-0e06-9567-083a5b2e035a
* Content: [Create and import query suggestions for the classic search experience in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/create-and-import-query-suggestions#feedback)
* Content Source: [SharePoint/SharePointServer/search/create-and-import-query-suggestions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/create-and-import-query-suggestions.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Disc0veryX Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Disc0veryX Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
