### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by Disc0veryX** [MicrosoftDocs/OfficeDocs-SharePoint#1883]
"WordCustomRefiner1, WordCustomRefiner2, WordCustomRefiner3, WordCustomRefiner4, WordCustomRefiner5WordExactCustomRefinerWordPartCustomRefiner1, WordPartCustomRefiner2, WordPartCustomRefiner3. WordPartCustomRefiner4, WordPartCustomRefiner5WordPartExactCustomRefinerThese"

Some punctuation marks in this fragment of the text are absent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fb35d4-5d34-4b24-61fa-1037f2e8dc8d
* Version Independent ID: b5c2e6d6-7e76-1234-0de8-2fcceaa690b0
* Content: [Create and deploy custom entity extractors in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/create-and-deploy-custom-entity-extractors)
* Content Source: [SharePoint/SharePointServer/search/create-and-deploy-custom-entity-extractors.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/create-and-deploy-custom-entity-extractors.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Disc0veryX Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Disc0Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
veryX
