### ISSUE TITLE
an unknown error occurred. (Error code 0x80004005)

### ISSUE THREAD

**Issue by atfernando** [MicrosoftDocs/OfficeDocs-SharePoint#189]
Hi, I'm getting the error in the title when trying to sync pictures and desktop folders. I used to have a folder redirection that redirect the documents folder to onedrive but it's been removed and the registry has been updated to %Userprofile%\documents. No other gpos applied. Any suggestions?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-au/onedrive/redirect-known-folders?redirectSourcePath=%252fen-us%252farticle%252fredirect-and-move-windows-known-folders-to-onedrive-e1b3963c-7c6c-4694-9f2f-fb8005d9ef12)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@atfernando  - thank you for submitting feedback. 

Whith you getting this error I think support can address this and bring it to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
