### ISSUE TITLE
What do new sites created default to?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1891]
If I have organization-level setting set to Anyone, will new sites created be automatically set to Anyone as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3106844b-caae-38c5-3c88-fb17a9d67536
* Version Independent ID: 3e88e60e-24a3-cd83-9bfc-8bc3037a86ce
* Content: [Change the external sharing setting for a site - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/change-external-sharing-site#feedback)
* Content Source: [SharePoint/SharePointOnline/change-external-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-external-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@Canis-Lupis it depends on what kind of site is being created. See [Default site sharing settings](https://docs.microsoft.com/microsoft-365/solutions/microsoft-365-guest-settings?view=o365-worldwide#default-site-sharing-settings) for info.

**Comment by Canis-Lupis** [comment]
Thanks, but that's a little confusing in that doesn't every non-classic site create a group connection if you haven't already?  So, wouldn't all non-classic SP sites then default to what's listed under "Group-connected sites?"

________________________________

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
