### ISSUE TITLE
Site Address Change - Huge Issue - Site Collection left in ERROR STATE - CANNOT UNDUE.

### ISSUE THREAD

**Issue by cclarke3** [MicrosoftDocs/OfficeDocs-SharePoint#1893]
I changed a site address through the Admin Console.  Then on dev - Changed it in Admin Console and powershell and recreated the same issue.  The site is stuck saying its updating the url.  It times out on the process apparently and then never completes.  The new site seems to be up, the old site redirects to the new site, but the power app we had on the new site is broken and can not be recovered.  I can't go back or anything because the site is in an error state.  Any advice?

**Comment by tseward** [comment]
Please open a case via admin.microsoft.com for support on technical issues.
