### ISSUE TITLE
SharePoint URL Change - Teams - Planner Files

### ISSUE THREAD

**Issue by vjones-bowiestate** [MicrosoftDocs/OfficeDocs-SharePoint#1894]
This is related to Viewing Team Files after a SharePoint URL Change.

- Team Planner Attachments links are redirected in Planner Web App, but not in Teams App.
- Team Planner Attachments links open blank from Teams Web App.

**Comment by tseward** [comment]
@vjones-bowiestate you should raise these issues with the product group; if you're part of the preview program, raise with that specific group, otherwise file a ticket via admin.microsoft.com.
