### ISSUE TITLE
SharePoint URL Change - Teams - Class Materials Folder

### ISSUE THREAD

**Issue by vjones-bowiestate** [MicrosoftDocs/OfficeDocs-SharePoint#1896]
This is related to viewing Team files after a SharePoint URL change:

Class Materials Folder produces the error: “The specified list is invalid” in Teams Desktop and Web.

**Comment by tseward** [comment]
This is documented at https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address.

**Comment by vjones-bowiestate** [comment]
Hello Trevor,

I was attempting to submit a couple of additional issues to the list (of 8) at the bottom of that page.‎ It says to do this through github and provides a link.

What is the process?

Thanks!
From: Trevor Seward
Sent: Monday, March 30, 2020 7:40 PM
To: MicrosoftDocs/OfficeDocs-SharePoint
Reply To: MicrosoftDocs/OfficeDocs-SharePoint
Cc: Vernon Jones; Author
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] SharePoint URL Change - Teams - Class Materials Folder (#1896)


This is documented at https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsharepoint%2Fchange-site-address%23effects-of-changing-a-site-address&data=02%7C01%7Cvjones%40bowiestate.edu%7C7651b1fd8d0c4d6a376208d7d503b149%7C94728e829ce44d9199c94adbe58ed910%7C0%7C1%7C637212084163505628&sdata=awB9DGKc%2Fyww9F8IQnhtVIibkarRizMiaqUlJw2h8H4%3D&reserved=0>.

**Comment by tseward** [comment]
These repositories are for the docs themselves (i.e. out of date info, incorrect formatting, and so forth). For actual product issues, those need to be addressed via the proper support channels such as the support options via the M365 Admin Center.

**Comment by vjones-bowiestate** [comment]
OK. Now I need a place to suggest they make that clear on the page. Thanks.

From: Trevor Seward
Sent: Monday, March 30, 2020 8:12 PM
To: MicrosoftDocs/OfficeDocs-SharePoint
Reply To: MicrosoftDocs/OfficeDocs-SharePoint
Cc: Vernon Jones; Author
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] SharePoint URL Change - Teams - Class Materials Folder (#1896)


These repositories are for the docs themselves (i.e. out of date info, incorrect formatting, and so forth). For actual product issues, those need to be addressed via the proper support channels such as the support options via the M365 Admin Center.

**Comment by vjones-bowiestate** [comment]
I see what happened.  I didn't click on the correct link to submit directly to this project, but I see it now.  Sorry for the confusion.

**Comment by scanum** [comment]
@vjones-bowiestate Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
