### ISSUE TITLE
Error 0x01110011 not listed 

### ISSUE THREAD

**Issue by bebobebo** [MicrosoftDocs/OfficeDocs-SharePoint#1898]
Scan File Failure:The item created time or modified time is not supported

I got this on a bunch of PDF files (product manuals) all of which had a created date of 11/07/2019 and a blank modified date. I am guessing that SPMT can't deal with an empty modified date field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshooting SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@bebobebo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@bebobebo thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by bebobebo** [comment]
It's not a tenant issue! I'll forward this to Chris Pratley. He'll
understand

**Comment by Rykimaruh** [comment]
I am having this same issue when using the SharePoint Migration tool. I added a virtual server, hosted on cloud, as a network drive on my machine and when I attempt to migrate the files from here, I get this error too. Not sure if the time format used in that virtual server is different to what the migration tool is used to.
