### ISSUE TITLE
This is extremely confusing

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-SharePoint#1899]
The examples on this page relate to a future version of the application not in current public preview and should be hidden or marked as not-current.
For example, the current version of Migration Manager only supports file shares, but this gives examples on how to migrate from an On-Prem SharePoint server to SharePoint Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [How to format a CSV or JSON file for bulk upload in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jantoney  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JoanneHendrickson** [comment]
Thank you for seeing this.  The document has been updated to reflect only  file shares only.
