### ISSUE TITLE
SPMT Error: "Package Engine has stopped because Azure queue failed"

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-SharePoint#19]
Hi,

I'm trying to migrate some files from a local drive to OneDrive for Business and I keep getting this error. I have tried it with different folders as well.

Screenshot attached below:

https://1drv.ms/u/s!At3D4ZK2R-kyhly7xaqS330LckfJ (Sorry, couldn't attach image, as the forum blocks it.)

How can I fix this issue?

Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89de996c-fdbe-91dd-75c2-34b7e12b1f49
* Version Independent ID: 9961e4fe-6764-d6c8-9bde-271ef81c5a6d
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-gb/SharePoint/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by zhigangz74** [comment]
Please contact this email with your logs and reports to acquire help: migration_team@microsoft.com

**Comment by kenwith** [comment]
@haneef95 - sorry for the delay on this and that it has gone stale in the documentation issues. I know it has been a very long time so I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
