### ISSUE TITLE
SharePoint URL Change - Teams - Class Materials Folder

### ISSUE THREAD

**Issue by vjones-bowiestate** [MicrosoftDocs/OfficeDocs-SharePoint#1900]
After a SharePoint URL change, Class Materials Folder produces the error: “The specified list is invalid” in Teams Desktop and Web.
![capture-20200331-teams-url-rename-class-materials](https://user-images.githubusercontent.com/62909346/78029477-a6105700-732e-11ea-848f-64fb39bed3a7.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@vjones-bowiestate  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikeMittonBio** [comment]
@scanum Any update on this? I'm in this situation I would like to know if I have to recreate the site to get it working again.

**Comment by kaarins** [comment]
@AdwoodMicrosoft can you help this customer, or should they file a support ticket?

**Comment by MikeMittonBio** [comment]
@kaarins @AdwoodMicrosoft No need for a support ticket. I just deleted the group and made a new one. I am curious what the fix would be though.

**Comment by lawrencefrias** [comment]
This would be handy for Teams that need to be truncated due to long SharePoint site names. Any update on this issue?

**Comment by kaarins** [comment]
There is a known issue that after changing the address, the Files tab will need to be refreshed. If this is a persistent issue, please contact Support.
