### ISSUE TITLE
SharePoint URL Change - Teams - Planner Files

### ISSUE THREAD

**Issue by vjones-bowiestate** [MicrosoftDocs/OfficeDocs-SharePoint#1901]
After changing the URL:
- Planner attachment links are redirected in Planner Web App, but not in Teams App.
- Planner attachment links open blank from Teams Web App.
![capture-20200331-teams-url-rename-planner-files](https://user-images.githubusercontent.com/62909346/78030468-25eaf100-7330-11ea-9b29-74ce88c5504f.PNG)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@vjones-bowiestate thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by vjones-bowiestate** [comment]
I did some more testing and from what I’ve found, I believe that the nature of both issues is how Teams now interacts with Planner Files.
- When Planner uploads a file, it’s placed outside of channel folders.
- Planner within Teams no longer allows files to be uploaded.  You must first place the file in a channel, then locate and link it or use the link option to access a file from anywhere.
- It appears that the issue is Teams can no longer access files that are not located in a channel (root of Team Shared Documents), thus is the cause of both errors.
- So the issue is not a URL Change issue, but a Teams Planner Files issue.
- This issue now becomes the inability for users to access uploaded Planner files from Teams.

I don’t see any reference to this issue on the internet, expect for complaints about not being able to upload files into Planner within Teams.
