### ISSUE TITLE
GraphAPI

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/OfficeDocs-SharePoint#1902]
Any way to do this via GraphAPI? Specifically, updating the "Allowed Domain" list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Restrict sharing of SharePoint and OneDrive content by domain - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@PChipVIA thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by PChipVIA** [comment]
Wait, I am asking how to do it with GraphAPI as there are no instructions in the document and you're referring me to a service ticket?  What is the relevancy?  Worse yet, you immediately close the issue without waiting for my confirmation or at least some time for me to respond.  What kind of process is this?  

Now I will ask again:

- CAN this be done using GraphAPI?
- if yes HOW can this be done using GraphAPI and WHERE is the documentation?
