### ISSUE TITLE
Microsoft Message Analyzer is no longer available.

### ISSUE THREAD

**Issue by sebmatthews** [MicrosoftDocs/OfficeDocs-SharePoint#1904]
Just an observation requiring a small change - Microsoft Message Analyzer as cited above is no longer available since lagte 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5288caa-2ae0-8a92-507f-d28427aae3cc
* Version Independent ID: a2673258-2eb0-2aba-28ad-b1e0895a4620
* Content: [Network utilization planning for the OneDrive sync app](https://docs.microsoft.com/en-us/onedrive/network-utilization-planning#feedback)
* Content Source: [OneDrive/network-utilization-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/network-utilization-planning.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@sebmatthews Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
