### ISSUE TITLE
Error 0x0300001E not listed

### ISSUE THREAD

**Issue by albegut** [MicrosoftDocs/OfficeDocs-SharePoint#1905]
This is the error when try to migrate calculated field with date field referenced

"Failure","Skip migrate the content of the list because the required field(s) FechaCalculada cannot be created or updated","0x0300001E"

I have tried to migrate other calculated field with numeric fields referenced and I had have not problems

**Comment by scanum** [comment]
@albegut thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by albegut** [comment]
The error was due to an error in the formula of the calculated field. I cannot confirm that the error code is specific to this problem.

**Comment by friendbool** [comment]
I have the same problem. My website uses Italian regional settings. If I set the formula =CONCATENATE("a","b") in a field, the migration program fails. If I modify the formula to ="a"&"b", then the program runs correctly. It seems that the problem only occurs with formulas that contain functions. Is it the problem that you have also encountered?
