### ISSUE TITLE
How would redirects work if I rename a site to another's old name?

### ISSUE THREAD

**Issue by DesignerGeeking** [MicrosoftDocs/OfficeDocs-SharePoint#1907]
Here's the situation: one SharePoint/O365 group was created through Yammer, and another SharePoint/O365 group was created through Teams with the same name.

One got the the [Name] for the URL, the other got [Name]475 as the URL. We would like to change the [Name] URL to something different, like [Name]Announcements and change [Name]475 to just [Name]. What will happen with the redirects in this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by DesignerGeeking** [comment]
Even better would be to merge the two O365 groups for Yammer and Teams, but that doesn't appear to be an option at this time.

**Comment by scanum** [comment]
@DesignerGeeking thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
