### ISSUE TITLE
"Apparently" there is an undocumented character limit for the value you can provide to this GPO on your SharePoint Synchronization URL. 

### ISSUE THREAD

**Issue by Pentao** [MicrosoftDocs/OfficeDocs-SharePoint#1910]
Hi all, 

I had 2 tickets open with Microsoft support regarding the implementation of the Group Policy "Configure team site libraries to sync automatically". 

I my case I had mixed experience configuring team site libraries to sync automatically, some of the mapped, and some others never, ever did. 

Luckily, I stumbled upon a YouTube Channel called Intune.Training, where the guys there mention an "undocumented character limit" for the value you can provide to this GPO on your SharePoint Synchronization URL. 

Could you guys confirm if it is True that such limitation exists?

The name of the video is:  Intune.Training - Episode 32 - Automating the Syncing of SharePoint Team Site Libraries
You can see the reference to this limitation on the minute 11:25 of the video. 
Intune.Training - Episode 32 - Automating the Syncing of SharePoint Team Site Libraries.

https://www.youtube.com/watch?time_continue=1006&v=Zoac9lbUuG0&feature=emb_logo

For all the members of the community reading this entry, I have successfully implemented the script that Ben shares in that video, and it worked like a charm, using the same SPO site and libraries I have been struggling with since November last year. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy?WT.mc_id=M365-MVP-4040055&source=docs#AutoMountTeamSites)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Pentao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
This is a very, very well documented limit (400 characters, encoded). By default, Win32 applications such as Windows Explorer have a limit of 260 characters but that can be adjusted (MAX_PATH) to the maximum limit of NTFS of 32k characters.

_However_ even if you adjust MAX_PATH, Office applications do not use the correct API and are limited to a 260 character path in Windows.

https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-US&rs=en-US&ad=US#filenamepathlengths

**Comment by scanum** [comment]
@Pentao Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
