### ISSUE TITLE
Scenarios where the Powershell script to pre-provision multiple users will miss users

### ISSUE THREAD

**Issue by Ritty5** [MicrosoftDocs/OfficeDocs-SharePoint#1911]
[OneDrive Pre-provision Accounts](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts)

The script at the bottom of the page under the heading
> Pre-provision many users at the same time
In some scenarios will miss users.

If your tenant has 599 users it will miss 199 of them
- _foreach_ will go through each user
- do the first _if_ statement until _$i_ equals 199
- when _$i_ equals 199 it will run both _if_ statements, there will be 200 users to _$list_. This will run the _Request-SPOPersonalSite_ command and set _$list_ to a _null array_.
- on the third time through the above _$list_ will be 199 users and the second _if_ statement will not run and the _foreach_ loop will end

**Current script**
```
    $list = @()
    #Counters
    $i = 0; $j = 0
    
    #Get licensed users
    $users=get-msoluser -All | ? {$_.islicensed -eq $true}
    #total licensed users
    $count = $users.count

    foreach ($u in $users){
        $i++; $j++; 
        Write-Host "$i/$count"

        if ($j -lt 199){
            $upn = $u.userprincipalname
            $list += $upn
        }
        if ($j -gt 199){
            Request-SPOPersonalSite -UserEmails $list
            Start-Sleep -Milliseconds 655
            $list = @()
            $j = 0
        }
    }
```

**Add this to the end of the script**
```
    if ($list.length -gt 0){
        Request-SPOPersonalSite -UserEmails $list
        Start-Sleep -Milliseconds 655
        $list = @()
    }
```

edit: added URL at beginning to specify the page this issue is about.

**Comment by scanum** [comment]
@Ritty5 Please link the documentation you are referring to.

**Comment by Ritty5** [comment]
Apologies, did not realise this was not specific to the Docs.

https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts

**Comment by scanum** [comment]
@Ritty5 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
