### ISSUE TITLE
Better clarification about OS requirement

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/OfficeDocs-SharePoint#1913]
This is about Minimum requirements for a single server with built-in database and for front-end web servers and application servers in a farm

It is better to clarify 2008 R2 SP1 is minimum req and it is supported up to 2012 R2 including 2012. 
Also, it might be better to mention 2012 R2 is recommended based on the issue [1492](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1492).

***** excerpt
The 64-bit edition of Windows Server 2008 R2 Service Pack 1 (SP1) Standard, Enterprise, or Datacenter or the 64-bit edition of Windows Server 2012 R2 Standard or Datacenter.
*****

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171d6bb7-4f08-573b-a2c7-5e78add14340
* Version Independent ID: 8c204184-9c39-727c-2ac3-6106be7ce1b8
* Content: [Hardware and software requirements for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-0#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@takawazo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
