### ISSUE TITLE
Consumer version of OneDrive article incorrect location under OneDrive for Business

### ISSUE THREAD

**Issue by bramdejager** [MicrosoftDocs/OfficeDocs-SharePoint#1914]
Hello support, 

the article is referring to the URLs and ports for the consumer version of OneDrive. Which is a bit odd and confusing since the document is part of the OneDrive for Business documentation based on the menu navigation. Breadcrumb: OneDrive for Business » OneDrive » Sharing and security » Required URLs and ports. 

Maybe this document needs to be move to another location? 

Regards Bram

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4308cb37-c2e4-e751-c62f-07bef7b50c14
* Version Independent ID: 29ae5f3f-50e4-a9fb-7c1c-0b56f236e214
* Content: [Required URLs and ports for OneDrive consumer](https://docs.microsoft.com/en-us/onedrive/required-urls-and-ports)
* Content Source: [OneDrive/required-urls-and-ports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/required-urls-and-ports.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@bramdejager Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bramdejager,

Thank you for your feedback.

This article is intended for organizations/companies, this is why it´s there I think. And there is a reference to the article about the URLs and IPs for OneDrive for Business in M365.

Maybe it can be moved to another place, but I think it's not bad here, and to be honest I'm not sure if there is a better place to move it.

**Comment by scanum** [comment]
@bramdejager Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
