### ISSUE TITLE
Invalid FWLINK - page moved from sqlmag.com to itprotoday.com

### ISSUE THREAD

**Issue by panjkov** [MicrosoftDocs/OfficeDocs-SharePoint#1915]
Affected page: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-high-availability.md

Affected FWLINK in text block: "For help deciding which SQL Server availability technology to use, see Choosing a SQL Server Availability Technology."

FWLINK https://go.microsoft.com/fwlink/?LinkID=799828&clcid=0x409
points to "http://sqlmag.com/scaling-success-sql-server-2016/choosing-sql-server-availability-technology"
should be updated to point to "https://www.itprotoday.com/business-resources/choosing-sql-server-availability-technology"

**Comment by scanum** [comment]
@panjkov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@panjkov Thank you for providing this feedback. Keeping in mind that "https://www.itprotoday.com/business-resources/choosing-sql-server-availability-technology" is not an official MS documentation, i will create a request to reference this article, which includes all the information of the above document, and much more - https://docs.microsoft.com/en-us/sharepoint/administration/plan-for-high-availability

**Comment by panjkov** [comment]
@VLG17 I agree that it is not official documentation, but it is behind our official link shortener (FWLINK) – so we should either update the FWLINK or use direct link to the article, or  equivalent article that we own on that topic.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tseward** [comment]
I would link to the official docs at https://docs.microsoft.com/sql/database-engine/sql-server-business-continuity-dr?view=sql-server-ver15.

**Comment by MikePlumleyMSFT** [comment]
Agreed - we should link to the Microsoft docs for this.

**Comment by scanum** [comment]
@tseward Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
