### ISSUE TITLE
Disable "Help Menu" section into OneDrive client

### ISSUE THREAD

**Issue by gp92** [MicrosoftDocs/OfficeDocs-SharePoint#1916]
I followed your guide to disable the help section into OneDrive client without success:
https://support.office.com/en-us/article/how-to-disable-get-help-and-send-feedback-in-onedrive-for-business-edf62c21-a30f-4330-b98a-f6d482f69f8b. Configured both GPO and tenant settings but still I have the option. How to completely disable it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@gp92 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
