### ISSUE TITLE
URL incorrect

### ISSUE THREAD

**Issue by v-mianth** [MicrosoftDocs/OfficeDocs-SharePoint#1918]
the URL here doesn't seem to match the page description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116a7d33-b79a-f07d-b9de-d032d805c8d5
* Version Independent ID: 94908ca2-5edc-eb8c-b8a2-72cf61969dc7
* Content: [Set Files On-Demand states](https://docs.microsoft.com/en-us/onedrive/files-on-demand-mac)
* Content Source: [OneDrive/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@v-mianth Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@v-mianth Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
