### ISSUE TITLE
Where is the crawl log actually viewed?

### ISSUE THREAD

**Issue by baconbum** [MicrosoftDocs/OfficeDocs-SharePoint#1920]
This document details how to configure permissions, but how do you actually see crawl logs?

The description at the top of this article mentions eDiscovery, but when I was in the Security and Compliance Center I created a case in the eDiscovery section and didn't see any option to view the crawl log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852613da-1319-1d20-04d4-a3fd9aa6bc72
* Version Independent ID: c912d988-603a-9e37-cd43-aee69bf01c91
* Content: [Crawl log permissions - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/set-crawl-log-permissions#feedback)
* Content Source: [SharePoint/SharePointOnline/set-crawl-log-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/set-crawl-log-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@baconbum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by hsantan** [comment]
I have the same doubt!

**Comment by VLG17** [comment]
@baconbum As far as i know there are 2 ways to get the crawl log in SPO:

1. eDiscovery as you mentioned, but there are a few more things you need to configure before you can view the crawl log. You need to specify the correct source and a few more things. Although not an official MS article, you can find the details [here](https://exploresharepointfeatures.com/2016/11/05/view-sharepoint-online-spo-crawl-logs-in-office-365/)

2. Powershell with the help of [Get-PnPSearchCrawlLog](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsearchcrawllog?view=sharepoint-ps)

Get-PnPSearchCrawlLog -Filter "https://<tenant>-my.sharepoint.com/personal"

**Comment by scanum** [comment]
@baconbum 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
