### ISSUE TITLE
Secure Channel SSL certificates requirement

### ISSUE THREAD

**Issue by ashokgop** [MicrosoftDocs/OfficeDocs-SharePoint#1921]
The section "About Secure Channel SSL Certificate" states as below...

"This certificate must be either a wildcard or a SAN certificate and be issued by a public root certification authority. The subject field of this certificate must contain the host name of the external endpoint of the reverse proxy server or a wildcard URL that covers all host names in the namespace."

In the section below it under "Get a Secure Channel SSL certificate" states as below....
"This certificate must support multiple names and must be at least 2048 bits. &gt; The Subject or Subject Name field of the certificate must contain a wildcard entry of the domain name in the External URL..."  And then continues to give an example.

The above two appear to contradict each other.   Could you please clarify?

Thanks
AG.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a1ac50-df4e-a3a1-9af4-c6517af605dc
* Version Independent ID: 1de86435-cc21-b50e-0d2c-a646f24d2fa9
* Content: [Plan connectivity from Office 365 to SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/hybrid/plan-connectivity-from-office-365-to-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/plan-connectivity-from-office-365-to-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/plan-connectivity-from-office-365-to-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ashokgop Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ashokgop** [comment]
> @ashokgop Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

Hello,
Checking in to see if there is any update on this.  Thank you!
-AG

**Comment by VLG17** [comment]
@ashokgop I will create a pull request and remove this part "**_> The Subject or Subject Name field of the certificate must contain a wildcard entry of the domain name in the External URL. For example, if your external URL is https://spexternal.public.adventureworks.com, the subject of your wildcard certificate should be *.public.adventureworks.com. >_**" which was already handled in the Note above:

![image](https://user-images.githubusercontent.com/41186174/80193140-fb374400-8620-11ea-93c1-9ba3620bd79f.png)

**Comment by scanum** [comment]
@ashokgop 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
