### ISSUE TITLE
How do we determine the optimal number of agents?

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/OfficeDocs-SharePoint#1923]
&gt; Based on the size of the content you want to migrate, you can setup as many agents as you need

But how do we determine the number of agents needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624f51bf-bf14-03ae-099b-2ee8b8657bf2
* Version Independent ID: 71bc428f-3fe9-1e9b-a996-871407127f96
* Content: [Setup Migration Manager agents - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-setup-clients?source=docs#feedback)
* Content Source: [migration/mm-setup-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-setup-clients.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@DmitryVorobyov thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DmitryVorobyov** [comment]
My question was theoretical at this point. Just wanted to point out that since this article already states that the number of agents should be based on the volume of content being migrated, it should also include guidance on how to calculate the said number... Thank you!
