### ISSUE TITLE
What about anonymous users?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-SharePoint#1924]
It seems that all SharePoint site sharing revolves around getting an emailed 'link' or logging in.  What if I create an information site with some pdf files that anyone in the world can download freely?  Isn't there a setting where I can let anyone go to https://mydomain.sharepoint.com/sites/Info without needing to be emailed a link? That is, just by typing https://mydomain.sharepoint.com/sites/Info into a browser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Canis-Lupis thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
