### ISSUE TITLE
What is governance? poster

### ISSUE THREAD

**Issue by jamesamayes** [MicrosoftDocs/OfficeDocs-SharePoint#1926]
This poster makes reference to SharePoint 2013. Is there a more current version of this poster?  If not, and the content is still relative, can the "2013" piece be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ef16cf-db32-9d8f-8282-55490518ffef
* Version Independent ID: b07676fd-f360-54f9-e539-68e6e9f4e987
* Content: [What is governance in SharePoint?](https://docs.microsoft.com/en-us/sharepoint/governance/what-is-governance-in-sharepoint#feedback)
* Content Source: [SharePoint/SharePointServer/governance/what-is-governance-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/what-is-governance-in-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jamesamayes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jamesamayes, thank you for your feedback.

I think there is no more current version and it´s still relative to 2016 and 2019. I don´t have access to update the PDF.

@JoanneHendrickson could you kindly help? Is there a way to update (remove 2013) from the PDF and Visio? Thanks!

**Comment by scanum** [comment]
@JoanneHendrickson could you kindly help?

**Comment by dariomws** [comment]
@JoanneHendrickson could you kindly help?

**Comment by dariomws** [comment]
@JoanneHendrickson could you kindly help?

**Comment by dariomws** [comment]
@JoanneHendrickson @samanro could you kindly help?

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by dariomws** [comment]
@JoanneHendrickson @samanro could you kindly help?

**Comment by JoanneHendrickson** [comment]
@dariomws    Hi Dario -- this is currently being updated and new generic version created..

**Comment by dariomws** [comment]
@JoanneHendrickson thanks!

**Comment by JoanneHendrickson** [comment]
The posters have been updated, and the revised version is now live.
