### ISSUE TITLE
missing error message: The folder name is invalid, 0x0171000D

### ISSUE THREAD

**Issue by rsulliva** [MicrosoftDocs/OfficeDocs-SharePoint#1928]
"The folder name is invalid, 0x0171000D" was observed.

It turns out that source folder name for the migration was copied onto NTFS disk from a Mac, and it's first character was a space (0x20).  Didn't know the Mac would allow that.  

Anyway, it worked on the mac it was copied from, but was caught and reported as an error by SPMT.  Files in that folder got 0x01710009 error messages, since the target folder could not be created I suppose.

**Comment by scanum** [comment]
@rsulliva thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
