### ISSUE TITLE
Option to run this on all sites at once.

### ISSUE THREAD

**Issue by sheepson** [MicrosoftDocs/OfficeDocs-SharePoint#1929]
We have tenants with a lot of sites and I would like to do the reporting on all sites at once, either via powershell or the admin portal. Is this possible, or will it be possible in the near future?

For now i've also created a uservoice entry:
https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/40174579-create-a-report-for-all-shared-files-and-folders-o

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharing-reports#feedback)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by jjohnkc** [comment]
Second this request 100%. We absolutely need to be able to see files and folders shared externally across all sites, not just individual ones. We limit external sharing simply because we do not have this visibility currently.

Sheepson, I voted on your SharePoint UV entry also - thanks!

**Comment by scanum** [comment]
@sheepson thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
