### ISSUE TITLE
Integration between Home Site & SharePoint Start Page

### ISSUE THREAD

**Issue by BlazeOfFeathers** [MicrosoftDocs/OfficeDocs-SharePoint#1930]
Hi,

Is the integration between the home site and the SharePoint Start Page being cancelled or postponed? 

This was finally a good way to not completely separate the SharePoint Start Page from the rest of the Intranet. Users get confused when they suddenly end up on a completely different page when they click on "SharePoint". Admin cannot control this page as well. What's the point of a root home page..

Thanks for the update..

**Comment by scanum** [comment]
@BlazeOfFeathers thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
