### ISSUE TITLE
MFA for all apps breaks Onedrive (guest users)

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/OfficeDocs-SharePoint#1935]
I have the next setup: I have CA configured to force MFA for all guest and external users. Since this, guest users' Onedrive client wont sync anymore, giving this error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0ff1-ce00-000000000000

Is this by design? Do we have to exclude some apps from the policy in order to let this work? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app for Windows](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BakkerJan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by marschallphilipp** [comment]
Unfortunately this seems to be a restriction....

[](https://sysadmin-central.com/2020/08/03/onedrive-b2b-guest-sharing-sorry-onedrive-cant-add-your-folder-right-now/)
