### ISSUE TITLE
Site collection feature may affect anonymous sharing of folders

### ISSUE THREAD

**Issue by msftfdbk** [MicrosoftDocs/OfficeDocs-SharePoint#1936]
When the site collection feature [“Limited-access user permission lockdown mode”](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/cannot-access-shared-folder) is active, existing anonymous sharing links to folders may not work, and new links can’t be created.  This is not mentioned in the article.  See O365 support ticket #19584248 for reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage sharing settings - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@msftfdbk  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @msftfdbk, thank you for your feedback.

Maybe we should reference the article you provided. Are you agree? I don´t have access to check support ticket #19584248.

Thanks!

**Comment by msftfdbk** [comment]
When “Limited-access user permission lockdown mode” is active, users can’t _create_ anonymous sharing links to folders.  As far as I know there’s currently no documentation about this behavior.  The troubleshooting article I linked to only addresses the inability to _use_ sharing links to folders (which have already been created), although I believe underlying cause is the same.  @dariomws

**Comment by dariomws** [comment]
What do you suggest? Adding a note in the article and referring to the troubleshooting article?

Or maybe adding the troubleshooting article to the "See also" section? I think this could work.

Thanks!

**Comment by scanum** [comment]
@msftfdbk  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
