### ISSUE TITLE
Format of CSV is incorrectly show on this page

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/OfficeDocs-SharePoint#1937]
The SharePoint Migration Manager bulk import process doesn't allow you to import the sample as shown with the local drive path.  You have to use a UNC path for it to accept it.  This needs to be updated in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [Format JSON or CSV for data content migration - SharePoint Online - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-US/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration#feedback)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@DDog80sRocked  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DDog80sRocked, thank you for your feedback.

I tested and could migrate files from C:\Temp to my OneDrive for Business storage using a CSV file. SPMT is installed on my Windows 10 machine.

**Comment by ryanharnwell** [comment]
I confirm the same. The path does need to exist though.

**Comment by DDog80sRocked** [comment]
Are we talking about SPMT or SPMM?  I was trying to import the CSV into SPMM and I also have a C:\temp folder but it wouldn't work.

**Comment by ryanharnwell** [comment]
This doc is for SPMT.

I think you should post feedback in https://docs.microsoft.com/en-US/sharepointmigration/mm-bulk-upload-format-csv-json

**Comment by dariomws** [comment]
@ryanharnwell thank you for confirming this information.

@DDog80sRocked this article is related to SharePoint Migration tool (SPMT).

**Comment by scanum** [comment]
@DDog80sRocked Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
