### ISSUE TITLE
My Documents and Documents Bug

### ISSUE THREAD

**Issue by avidpontoon** [MicrosoftDocs/OfficeDocs-SharePoint#1939]
I have two 1909 PC's with the latest version of OneDrive. While using silent KFM via GPO. When i login to the fist PC, it creates the 'Desktop', 'Documents' and 'Pictures' folders within onedrive and redirects my folders to them.

However when i login to another PC, The desktop stays the same but instead of redirecting my documents to the already created' documents' folder within onedrive, it creates a 'My Documents' folder in OneDrive and redirects to that instead. The same happens for the Pictures folder. So I end up with this:

![image](https://user-images.githubusercontent.com/37943903/79670124-b0e53b80-81b8-11ea-8db9-0d6c8c4e907f.png)

Am i doing something wrong or is this a bug?

**Comment by scanum** [comment]
@avidpontoon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
