### ISSUE TITLE
Export to CSV File

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#194]
The file does not contain the admins for the group connected sites, which limits its usefulness. Please add that data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a532bd5d-9109-6b31-8b1c-be3c066a672a
* Version Independent ID: adf7fd35-a09d-2d4c-de62-bc1273554200
* Content: [Manage sites in the new SharePoint admin center](https://docs.microsoft.com/en-US/sharepoint/manage-sites-in-new-admin-center#export-to-csv)
* Content Source: [SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@DeanGross , thanks for trying the new SharePoint admin center preview, and for sharing this feedback. I have passed it along to the team. If you have additional feedback, please click the Feedback button in the lower-right corner of the new SharePoint admin center. The team is monitoring this feedback closely, and working to add more functionality for managing group-connected team sites.
