### ISSUE TITLE
Cannot set a site as a home site 

### ISSUE THREAD

**Issue by Amyversa** [MicrosoftDocs/OfficeDocs-SharePoint#1942]
The following does not work
Set-SPOHomeSite -HomeSiteUrl <siteUrl>
Set-SPOHomeSite : The requested operation is part of an experimental feature that is not supported in the current
environment

**Comment by scanum** [comment]
@Amyversa 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Amyversa** [comment]
Hi @scanum - I'm referring to this document - 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohomesite?view=sharepoint-ps
When I do that, it says - The requested operation is part of an experimental feature that is not supported in the current environment
