### ISSUE TITLE
TotalItemCount - for site collection or content database?

### ISSUE THREAD

**Issue by spg-iwilson** [MicrosoftDocs/OfficeDocs-SharePoint#1943]
TotalItemCount - this seems to be reporting the total number of items in the content database, not the site collection. My report is showing the same TotalItemCount for each of the personal site collections. These are all in the same content database. SMAT version 1.0.1804.23001

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f59654f-e2cf-affd-6952-0e5319f2ff02
* Version Independent ID: 6ddf11f3-f67b-ef38-dd06-85113c3a3699
* Content: [Migration Assessment Scan Large Lists - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-au/sharepointmigration/migration-assessment-scan-large-lists#feedback)
* Content Source: [migration/migration-assessment-scan-large-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migration-assessment-scan-large-lists.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@spg-iwilson 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
