### ISSUE TITLE
Sharepoint 2019 ON PREMISE / OneDrive sync

### ISSUE THREAD

**Issue by luxzg** [MicrosoftDocs/OfficeDocs-SharePoint#1946]
Got to say, docs are confusing as hell.

First of all, despite most / all docs being tagged as Sharepoint 365, Sharepoint 2019 this is NOT true. Most of them only describe walkthroughs for 365 version such as LINKS to SharePoint 365 Admin page, and not saying WHICH admin interface that should be on-premise. So the whole docs should get a review from the on-premise viewpoint.

Anyway, I was trying to solve a seemingly simple task - sync my on-premise Library to Widnows 10 Desktop using OneDrive. And I am stuck.

This is how far I got:
- docs say to enable it on server/admin page but in the comments it seems this only affects old 365 users, while on-premise SharePoint 2019 is "taken care of" by default, so I skipped that after not finding any options to switch this feature on/off or switch it betwen "new" and "old" apps
- Went to our SharePoint Site -> Subsite -> Site contents -> Documents -> clicked "cog" icon -> Library Settings -> General settings -> Advanced settings -> Office client availability -> Allow .... -> Yes
- Went back to Site contents -> Documents -> Sync (button is there and prompts to open app)
- Allow opening of the app -> pre-populated with my DOMAIN\username -> Sign-in

And there I get this error:
"Sorry, there was a problem with OneDrive. Please try again in a few minutes. (Error Code: 0x8004de81)"

This error number is found exactly 3x on whole Google search, and all are Word related, and never answered / unsolved.

There is OneDrive error-codes page in these docs, but this error code isn't there.

Likewise, description is perfectly useless "there was problem" and so is a proposed solution "try again". Neither helped.

I uninstalled all OneDrive versions, went to exact link proposed by SharePoint 2019 little help popup ( https://go.microsoft.com/fwlink/p/?LinkId=248256 ), got that, installed that. Same error.

Upper management decision makers are rooting for NextCloud (dooh!) just because of desktop file sync, and I can't show them it DOES work with SharePoint. Tomorrow is the big meeting, and our SharePoint / OneDrive integration is nonexistant.

So please:
- help with error, ASAP
- add that error code to error code page list
- review the docs and add appropriate paragrafs for on-premises clients

**Comment by scanum** [comment]
@luxzg vthank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
