### ISSUE TITLE
Spelling Error - First sentence

### ISSUE THREAD

**Issue by Sdean1234** [MicrosoftDocs/OfficeDocs-SharePoint#1950]
See "you can use either of the folloiwng tools" --- following is misspelled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8673a55f-50c6-bd98-6b4f-d54db859216d
* Version Independent ID: 571c56c2-0be7-0296-ab36-3a75ff3874a9
* Content: [Migrate content to OneDrive in Office 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/Migrating-content-to-OneDrive-for-Business)
* Content Source: [migration/Migrating-content-to-OneDrive-for-Business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Migrating-content-to-OneDrive-for-Business.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Sdean1234 Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
@Sdean1234 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
