### ISSUE TITLE
Choose Drive to Install on

### ISSUE THREAD

**Issue by aaron-medrano** [MicrosoftDocs/OfficeDocs-SharePoint#1951]
I'm looking to see if there is a way to specify which drive this tool is installed and the local cache it stores it on. I've got a file share install with 200 GB to migrate and i'm worried i'll run into issues with my local C drive getting full since it can only go to 160 GB. i have another drive i added with 300 GB of storage i would rather use instead on another letter drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues#feedback)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@aaron-medrano thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
