### ISSUE TITLE
Sharepoint site name change causes total failure of teams to work!

### ISSUE THREAD

**Issue by chanansh** [MicrosoftDocs/OfficeDocs-SharePoint#1952]
This is an insult to software design. Fix this, please.

After the site address is changed, users won't be able to view the team's files within the Teams app, but they can access them from Teams by selecting Open in SharePoint. This issue is actively being worked on and will be addressed soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by chanansh** [comment]
also the url change takes forever cycling "Updating site address..."
I tried to "Add Cloud Storage" to try to reconnect the teams to sharepoint but it doesn't seem to be working

**Comment by scanum** [comment]
@chanansh Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @chanansh Hanan, how are you?
I understand your request, however, here we are limited to documentation fixes, for this kind of issues, we recommend uservoice, I searched and I found [this one](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38951875-renaming-sp-site-breaks-files-tab) that talks about it, and voted for it.
Hope this information helps you.

**Comment by scanum** [comment]
@chanansh We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Vittorio4** [comment]
Closed does not mean resolved in this forum. That much is clear.

**Comment by chanansh** [comment]
It should be bolded red at top of the page
