### ISSUE TITLE
Please add a reference to Mover on the Migration section.

### ISSUE THREAD

**Issue by Pentao** [MicrosoftDocs/OfficeDocs-SharePoint#1955]
In the section
# Migration
## How to migrate content from file shares, SharePoint Server, or other cloud providers to OneDrive in Microsoft 365
* Please add a link to the Mover articles, this tool is way more powerful than the SharePoint migration tool: 
** https://docs.microsoft.com/en-us/sharepointmigration/mover-fileshare-to-o365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dccdf92-2869-83ce-1565-d50b4b84729f
* Version Independent ID: ea4ef549-4335-b6c3-d902-996847ca663b
* Content: [Introduction to SharePoint Online - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/introduction#feedback)
* Content Source: [SharePoint/SharePointOnline/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/introduction.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Pentao Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @Pentao Humberto, how are you? Created a pr to propose adding the link to the article. Thanks!

**Comment by scanum** [comment]
@Pentao Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
