### ISSUE TITLE
Ip addresses 

### ISSUE THREAD

**Issue by JTB25** [MicrosoftDocs/OfficeDocs-SharePoint#1956]
Hi!

We have setup the Network access control and add a few ip-addresses. 
We have now setup 20 ip-addresses but we cannot add anymore. Is 20 the maximum for this?

**Comment by scanum** [comment]
@JTB25 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
