### ISSUE TITLE
Links go to old site

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/OfficeDocs-SharePoint#1957]
Hi the links are going to fslogix.com and should be to https://docs.microsoft.com/en-us/fslogix/overview  There also seems to be some confusion over the name, unless it's changing the current name is Office 365 container. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc677c5-4514-fb8b-a864-4edd711d6f44
* Version Independent ID: 1e3dbf59-48d4-2696-ad8a-7f9cb60871ec
* Content: [Use the sync app on virtual desktops](https://docs.microsoft.com/en-us/onedrive/sync-vdi-support)
* Content Source: [OneDrive/sync-vdi-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-vdi-support.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JimMoyle Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @kaarins I see that the name was changed from FSLogix Office 365 Container to FSLogix Microsoft 365 Container, it seems this was done as part of a [general rebranding change](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/4a3f85c0500e7445038d7a01d4529ab74307b733#diff-6947eb04741e590b839eb408b29fc7f0), can you kindly confirm if this change should be maintained for this product? Thank you

**Comment by kaarins** [comment]
Yes, it should be changed back to "Office Container" and the link should go to the destination Jim specified. Thanks!

**Comment by kaarins** [comment]
A different pull request just came in on this article, and I made this change. Thanks!
