### ISSUE TITLE
Minor typo in Prerequisites section

### ISSUE THREAD

**Issue by HilaryStoupa** [MicrosoftDocs/OfficeDocs-SharePoint#1958]
There is trailing slash instead of a period at the end of this sentence:
"We cover how to configure the separate app domain and the service applications in the apps for SharePoint configuration article/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f09c46e-a0cf-709d-96d5-b5ab30250727
* Version Independent ID: 4bf78e94-59be-b58d-e8f4-a9ededfccb9c
* Content: [Plan for apps for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/plan-for-apps-for-sharepoint)
* Content Source: [SharePoint/SharePointServer/administration/plan-for-apps-for-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-apps-for-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@HilaryStoupa Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @HilaryStoupa 👍 Thanks for noticing and reporting.

**Comment by scanum** [comment]
@HilaryStoupa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
