### ISSUE TITLE
Guidance for our users

### ISSUE THREAD

**Issue by Vittorio4** [MicrosoftDocs/OfficeDocs-SharePoint#1959]
We are just starting to rollout out 0365 and are in the planning stages. Correct me if I'm wrong, but after reading the documentation (and all of these very helpful comments), and until there is definitive guidance from Microsoft, the net is **we should expect to NOT change site names or URLs anytime soon**. It just seems like 

- it's either NOT possible, as in the case of Hub sites (not sure why its' not possible; I have not seen an explanation) 
- it's NOT recommended because of the cascade effect it on file access, sharing, permissions...

Please correct if I'm wrong.

**Comment by scanum** [comment]
@Vittorio4 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Vittorio4** [comment]
Ok but this doesn't answer my question and why would the answer lie in the Tenant when the issue is in the foundation? We will escalate through another channel then.
