### ISSUE TITLE
SPMT - Update this week causes error migrating to subfolders.

### ISSUE THREAD

**Issue by tech4ce** [MicrosoftDocs/OfficeDocs-SharePoint#1960]
We ran a successful initial migration on Monday for a customer using the CSV method. In column F we had a subfolder within a subfolder defined for many of the destinations in Teams (e.g. General/Folder). The initial migration completed successfully and we saw it build out the folder structure for those subfolders as intended and populate them with data. Today, the SPMT installed an update, and we were then met with errors when attempting to perform a Incremental sync with the tool throwing a 0x0207000B error on any line item that has a subfolder within a subfolder defined.  Our current migration is at a standstill.  We have opened a support ticket but was hoping this would raise awareness for this issue.  Please help!

**Comment by scanum** [comment]
@tech4ce thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
