### ISSUE TITLE
Files larger than 15GB are not migrated?

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/OfficeDocs-SharePoint#1962]
OneDrive for Business only allows 10GB per file. Is this section only for SharePoint Online?
Or is it allowed to migrate more than 10GB files to OneDrive for Business with Mover?

Section: https://docs.microsoft.com/en-us/sharepointmigration/mover-box-to-o365#will-there-be-unsupported-files-and-characters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 705f89ed-97f2-cb71-28f7-c35f55cce879
* Version Independent ID: c6b41e73-0db7-89ff-59cb-84d51df02394
* Content: [Migrating from Box to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-box-to-o365#will-there-be-unsupported-files-and-characters)
* Content Source: [migration/mover-box-to-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-box-to-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@pkothree thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
