### ISSUE TITLE
Continuous crawl randomly misses items

### ISSUE THREAD

**Issue by jay1050** [MicrosoftDocs/OfficeDocs-SharePoint#1965]
We have continuous crawl enabled for our sharepoint content

We find it will randomly miss items. These items are not picked up unless they are edited again

Is this expected behaviour

**Comment by scanum** [comment]
@jay1050 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
