### ISSUE TITLE
InfoPath forms

### ISSUE THREAD

**Issue by ioshi13** [MicrosoftDocs/OfficeDocs-SharePoint#1968]
Does this also support migrating InfoPath forms?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support? - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-gb/sharepointmigration/what-is-supported-spmt?source=docs#feedback)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@ioshi13 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ioshi13** [comment]
I don't need support. I am just asking a question."Does SPMT also support migrating InfoPath forms?"
