### ISSUE TITLE
Should App Mngmt and subs be included in the list of 3 at the beginning of the article?

### ISSUE THREAD

**Issue by ldusolier** [MicrosoftDocs/OfficeDocs-SharePoint#1971]
At the beginning of the article these 3 services are mentioned as prereqs for hybrid as SP Services, however later on, App Management and Subscription Settings Service are also included but not listed in the list at the beginning of the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1671c351-27e4-e726-858d-c3d660777977
* Version Independent ID: 6cbafe83-90b9-1113-a49b-9212505338b5
* Content: [Set up SharePoint services for hybrid environments](https://docs.microsoft.com/en-us/sharepoint/hybrid/set-up-sharepoint-services-for-hybrid-environments)
* Content Source: [SharePoint/SharePointServer/hybrid/set-up-sharepoint-services-for-hybrid-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/set-up-sharepoint-services-for-hybrid-environments.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ldusolier thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
