### ISSUE TITLE
Access denied after site swap using central admin page

### ISSUE THREAD

**Issue by DMZ011** [MicrosoftDocs/OfficeDocs-SharePoint#1972]
I tried the site swap as mentioned in this article: https://docs.microsoft.com/en-us/sharepoint/modern-root-site#feedback

I followed the steps as mentioned in the article using the admin center:

- Go to the Active sites page of the new SharePoint admin center, and sign in with an account that has admin permissions for your organization.

- In the upper right, make sure the All sites view is selected.

- In the URL column, select to sort A to Z so the current root site appears at the top of the list.

- Select the root site (https://contoso.sharepoint.com).

- Select Replace site.

- In the URL of the site you want to use box, enter the full or relative URL of the site that you want to become the new root site.

- Select Save.

I waited for 48 hours so far, and each time I try to go to my root site, I get access denied page. I am the tenant admin, I was the site collection admin on both sites.

**Comment by scanum** [comment]
@DMZ011 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
