### ISSUE TITLE
You cannot replace the root site with anything other than a communications site

### ISSUE THREAD

**Issue by tnewton1** [MicrosoftDocs/OfficeDocs-SharePoint#1974]
If you create a modern team site not connected to an Office 365 group and then try to replace the root site following these instructions (https://docs.microsoft.com/en-us/sharepoint/modern-root-site#use-the-new-sharepoint-admin-center), you will get an error that it can't be completed and try again in 10 minutes. If you wait and try again, it will give you the same message, failing each time. 

I then tried to run Invoke-SPOSiteSwap which fails with "The Site is not a communications site or has the classic publishing feature enabled." If I delete my modern team site and replace it with a communications site, everything works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/modern-root-site#use-the-new-sharepoint-admin-center)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tnewton1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tnewton1** [comment]
No need for me to open a ticket because I fixed the issue faster than support would have found the fix. I'm providing the fix so the documentation can be updated for anyone else who might have this issue.

The documentation states (first bullet point on the top of the page):

> If you have a different site that you want to use as your root site (a communication site or modern team site that isn't connected to an Office 365 group), replace (swap) the root site with the other site.

This is incorrect. It should read:

> If you have a different site that you want to use as your root site (a communications site), replace (swap) the root site with the other site.

You cannot swap the root site with anything other than a communications site. If it is anything but a communications site and you try to swap it, you'll receive an error that it couldn't be swapped and try again in 10 minutes. If you try to swap via PowerShell, it complains that it's not a communications site. The documentation is therefore wrong and needs to be corrected.
