### ISSUE TITLE
OneDrive: Enable silent account configuration will join device to Azure AD?

### ISSUE THREAD

**Issue by jamesryanmoat** [MicrosoftDocs/OfficeDocs-SharePoint#1975]
According to this OneDrive URL,
https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration, it states that using the OneDrive group policy it can silently sign in users to the OneDrive sync app with their Windows credentials. **If a device is not already joined to Azure AD, enabling this setting will join it.**

Is this still correct? It seems like it does NOT join the device to Azure AD. For silent account config to work and auto sign-in, the computer already has to be Azure AD registered or joined. Is this documentation incorrect? Or is this feature not working as intended? It would be great if the Group Policy actually did join the device to Azure AD so that it could sign-in automatically on devices that aren't already previously Azure AD registered.

**Comment by scanum** [comment]
@jamesryanmoat thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
