### ISSUE TITLE
Where is the More Features Link 

### ISSUE THREAD

**Issue by iabide** [MicrosoftDocs/OfficeDocs-SharePoint#1979]
OK. Where is the link to MORE FEATURES in the admin center?  I can get to it through the More features links in this page but not directly from the admin center.  How do I get to the More Features page without searching for More Features Help?  Very frustrating to read the instructions and they do not match what I see in real life.  I am Global Admin for the O365 environment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f0e99c-724d-9fc3-6b8b-bda185f92c19
* Version Independent ID: d38a6ff9-e4cd-5776-b152-9694fcafbee1
* Content: [What's new in the SharePoint admin center - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-admin-center#feedback)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
There was an issue today with the left navigation, and some customers weren't seeing the More features page. Thanks for reporting this. The issue should be fixed now. You can also access the page by going to Admin.microsoft.com/SharePoint?page=classicFeatures&modern=true.
