### ISSUE TITLE
Hub Sites Multigeo Support

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/OfficeDocs-SharePoint#198]
It's mentioned "If using the SharePoint sites multigeo feature, you can create a hub site in any geo/satellite location and associate sites from any geo/satellite location." and in the same article "Hub sites don't support OneDrive and SharePoint Multi-Geo features". Does SharePoint online Hub sites support multigeo or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4df1d8-955c-63d2-628e-8359391b8710
* Version Independent ID: 01326ab6-1270-d096-64e8-eb7d63ea9863
* Content: [Create a hub site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-hub-site)
* Content Source: [SharePoint/SharePointOnline/create-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@ahamin01 Thank you for your feedback. 

I want to make sure your hub questions get addressed appropriatly. The support team can handle these qestions to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
