### ISSUE TITLE
Replace root site option not showing in tenant

### ISSUE THREAD

**Issue by pwr42** [MicrosoftDocs/OfficeDocs-SharePoint#1981]
Logged in with tenant admin/spo admin account and not seeing the option to Replace Root Site.  Is this is still being rolled out?

**Comment by scanum** [comment]
@pwr42 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
