### ISSUE TITLE
Local Security Policy / User Rights Assignment

### ISSUE THREAD

**Issue by DennisGoss** [MicrosoftDocs/OfficeDocs-SharePoint#1982]
Any reason why the Local User Rights like "Impersonate a client after authentication" are not reflected in this page? Feels like this should be guidance coming from the vendor for justification of the needed exceptions to Security Hardening (i.e. STIGs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73d53bc-485a-a5d8-d864-e2e402c07625
* Version Independent ID: 72edd383-b5cb-3b66-4fb2-e9f5ab7d56ce
* Content: [Account permissions and security settings in SharePoint Servers](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016#feedback)
* Content Source: [SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@DennisGoss thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DennisGoss** [comment]
My feedback is that the documentation is incomplete.  How is a service ticket going to help? Maybe my original post was unclear but the document should list information about the user rights assignments required for SharePoint (on premises) service accounts as in something like this - https://docs.microsoft.com/en-us/archive/blogs/leesab/how-to-determine-what-user-rights-assignments-are-required-by-sharepoint-2010 - I am also confused how you came to the conclusion that my comment is for a cloud instance when the page I submitted feedback for specifically excludes SharePoint Online.
