### ISSUE TITLE
I don't have the "Replace site" option

### ISSUE THREAD

**Issue by BBKing77** [MicrosoftDocs/OfficeDocs-SharePoint#1983]
When I follow the above steps for replacing the site using the new SharePoint admin center, I select the root site, but I cannot find a Replace site option anywhere. Is there something I'm missing, or did this option go away with the latest refresh of the admin center a couple months ago?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/modern-root-site?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BBKing77 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by BBKing77** [comment]
After contacting support, it appears you need the Global admin role to have the "Replace site" function (I don't have Global admin), so perhaps this can be specified in the doc.
Thanks!
