### ISSUE TITLE
Effect on Recycle bin on URL change outdated

### ISSUE THREAD

**Issue by ChristianGalla** [MicrosoftDocs/OfficeDocs-SharePoint#1984]
In my recent tests, the content of the recycle bin was moved and I was able to restore files from it, so the documentation is outdated.
Is there any special content of the recycle bin that is not moved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ChristianGalla thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hwkwicre** [comment]
I don't think this is a problem with the tenant and therefore does not need a service ticket. I have seen the same thing too

**Comment by ChristianGalla** [comment]
According to the support, the documentation can not be entirely correct. Primary aim of the documentation is to prevent data loss. If data is lost, the 3rd level support is able to restore data within 14 days.
