### ISSUE TITLE
Pre-requisites are not detailed enought

### ISSUE THREAD

**Issue by chaplic** [MicrosoftDocs/OfficeDocs-SharePoint#1986]
The pre-reqs suggest we just need an up to date OS is all that's required.  This is missing detail

Silent sign in does NOT work if explorer is not the shell. This can be see by running a normal config, setitng up onedrive normally  procmon and you can see onedrive consult the Silent Sign in keys to get the tennant ID and so on.

If explorer is not the shell, (for example a Citrix Xenapp published app) it never consults the relevant registry keys and never even attempts silent sign in, going through the user questionnaire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@chaplic  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@chaplic thank you for pointing this out. This article has been updated recently and a few changes made, so please let me know if you still need assistance.

**Comment by scanum** [comment]
@chaplic Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
