### ISSUE TITLE
Be nice to have information regarding second-stage Recycle Bin

### ISSUE THREAD

**Issue by JaniceLu-cos** [MicrosoftDocs/OfficeDocs-SharePoint#1987]
I feel there could be some elaborated information regarding the second-stage recycle bin.  I read that, when a file has been moved to (first-stage) recycle bin, 93 days recycle bin retention period starts.  For whatever reason when a file is deleted from the first-stage recycle bin, the file will be moved to the second-stage, where the file will stay for the remaining 93 days period.

**Comment by scanum** [comment]
@JaniceLu-cos thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
