### ISSUE TITLE
Link to Roadmap is not working

### ISSUE THREAD

**Issue by SP-lbe** [MicrosoftDocs/OfficeDocs-SharePoint#1988]
In the section:
" Note
Integration between the home site and SharePoint start page (where the branding, theming, header, navigation, and footer elements from the home site are applied to the start page and users can easily navigate between the pages) is not available at this time. Please watch for updates in the Microsoft 365 roadmap."

The link to the Microsoft 365 Roadmap navigates a page with this error message:
"We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available."

Replacing Office-365 with Microsoft-365 seems to solve it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-us/SharePoint/home-site#feedback)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SP-lbe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@SP-lbe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
