### ISSUE TITLE
Scapy Art Group Official

### ISSUE THREAD

**Issue by ScapyArtGroup** [MicrosoftDocs/OfficeDocs-SharePoint#199]
This channel by Scapy Community

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa1be12-1a09-c79f-fbc7-7eb25da19a24
* Version Independent ID: e213d10c-c0d7-e42f-be53-199d77ec50db
* Content: [SharePoint hybrid sites and search](https://docs.microsoft.com/en-us/sharepoint/hybrid/sharepoint-hybrid-sites-and-search#SitesFeatures)
* Content Source: [SharePoint/SharePointServer/hybrid/sharepoint-hybrid-sites-and-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/sharepoint-hybrid-sites-and-search.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@ScapyArtGroup  Thank you for submitting this Feedback.

From my understanding the issue  has been resolved. If the issue is not resolved please re-open this issue.
