### ISSUE TITLE
Starting Full Profile Synchronization in SharePoint 2013 switches to Incremental

### ISSUE THREAD

**Issue by devhead67** [MicrosoftDocs/OfficeDocs-SharePoint#1990]
When I select 'Start Full Profile Synchronization' from the 'Start Profile Synchronization' page, after it starts running, it is switched to or replaced by the Incremental synchronization on the Timer job.  No matter what I do, it never completes a full synchronization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 364d54fe-4c99-12aa-4098-e4bd1d62dc33
* Version Independent ID: add1b7a2-c6c5-5555-b120-94c870dcb46f
* Content: [Start profile synchronization manually in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/start-profile-synchronization-manually)
* Content Source: [SharePoint/SharePointServer/administration/start-profile-synchronization-manually.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/start-profile-synchronization-manually.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@devhead67 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
