### ISSUE TITLE
Azure Active Directory Only

### ISSUE THREAD

**Issue by IfEyeOnlyKnew** [MicrosoftDocs/OfficeDocs-SharePoint#1991]
I am asking if we only have On-Prem Active Directory setting up a SharePoint 2019 on a VM in Azure and creating an Azure Sql Managed Instance is not going to work? Authentication will not work unless accounts are ALL AAD? SharePoint Admin accounts need to be AAD?

Testing access to SQL server/instance/alias: zsqlname.database.windows.net
  - Trying to connect to 'zsqlname.database.windows.net'
  - Using connection string 'Server=zsqlname.database.windows.net;Integrated Security=SSPI;'...Failed

**Comment by scanum** [comment]
@IfEyeOnlyKnew thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
