### ISSUE TITLE
Question about the 100 limit

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SharePoint#1993]
1. Is the 100 limit for domains on a site only for the admin center UI or PowerShell also? 
2. Can I add a max of 3000 domains on a site in batches of 100?
3. Are these limits same for classic, modern, group connected and standalone sites?
4. Can the documentation specify this for more clarity? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing#limiting-domains)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@rachoksh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
