### ISSUE TITLE
Format of CSV is incorrectly show on this page

### ISSUE THREAD

**Issue by DDog80sRocked** [MicrosoftDocs/OfficeDocs-SharePoint#1994]
The SharePoint Migration Manager bulk import process doesn't allow you to import the sample as shown with the local drive path. You have to use a UNC path for it to accept it. This needs to be updated in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [How to format a CSV or JSON file for bulk upload in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-US/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@DDog80sRocked  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Rupalikothawade** [comment]
Bulk input csv does not take local drive path, neither single source migration allows local drive path. And error message simply says error in line1.
Please update the documentation

**Comment by JoanneHendrickson** [comment]
Thanks for your feedback!  I have updated the article.  For an individual tasks:  You can only specify the site URL. The site always defaults to the documents library.

For bulk task upload: You can specify both the site URL and the document library folder.
