### ISSUE TITLE
User Profile Service related timer job never run on WFE server role

### ISSUE THREAD

**Issue by legendgod** [MicrosoftDocs/OfficeDocs-SharePoint#1995]
Our SP2016 farm only have 1 WFE role server and 1 custom role server. By default,  UPS only started in WFE server and stopped in custom server. Because of some bug or unknown issue, the related timer jobs (e.g. User Profile Service Application - User Profile ActiveDirectory Import Job ) never trigger. Nothing will happen if you click "Run now" button.
However, after we "started" the custom role UPS, everything is working as expected. Immediately effect, no reboot required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbcd95d-56ce-63b6-804f-14098ce1953b
* Version Independent ID: 78166e52-c779-2ad6-7b1f-cc3bcde47515
* Content: [Description of MinRole and associated services in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@legendgod thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by legendgod** [comment]
I am not SP online user. What "tenant" do you mean?
