### ISSUE TITLE
Transition from the Windows Folder Redirection Group Policy objects

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-SharePoint#1996]
These instructions dont work. Disable GPO is not being respected and KFM cant be enabled as it still kind of "detects" the former policy. So we need a better description in detail on how to get off successfully from the previous policy to be able to use KFM at the end. 

The process of getting rid of the old policy is currently really insane and it would be appreciated if MS could provide a much better expirience here since a lot of customers will be blocked in moving over to KFM due to the fact that they cant get off from the former folder redirect policy successfully.

Another poor expirience is even these days, where loads of people are working remotely. While they all connect to their corporate networks via VPN, any policy enforcement simply just dont work as the policy cant be pulled while booting/logging in as the VPN tunnel isnt ready at that point and hecne it makes it impossible to change or even use any new policy settings at all.

So the phrase "Disable the Window Folder Redirection Group Policy" is not correct as it simply just dont work that way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders?source=docs#feedback)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@stche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rstilekar** [comment]
Following, I have a same issue in our environment. I changed folder redirection from home drive back to default "Redirect to local userprofile location" then when all were changed backed to default the change the policy back to not configured for folder redirection and then implementing Known folder move for onedrive using silent config as well as prompt user to move known folders but nothing works. Expecting a better and straight forward way to handle this issue for Known folder move from Folder Redirection. This document just simply don't help.

**Comment by jhayesksb** [comment]
+1 for this issue. Same issue here.

**Comment by Jeep16** [comment]
Additionally "Disable the Window Folder Redirection Group Policy" is not helpful when there is not a "Disable" option on these policies.  They are either configured or not.  So if it is/was configured is it to be just set to 'not configured'?

**Comment by cartergreen** [comment]
Thank you all for your feedback.  I followed up with the Windows Folder Redirection policies and here are the two pieces of support ([link](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn789199(v%3dws.11))) around configuring and disabling the policies.

1. Set the Policy Removal option to "Leave the folder in the new location when policy is removed"
2. The GPO to enable/disable - \User Configuration\Windows Settings\Administrative Template\System\Folder Redirection

Let me know if this resolves your ability to disable the redirection.

**Comment by lindspea** [comment]
@stche thank you for reaching out and helping improve MS Docs. Thanks also @cartergreen.  Please let me know if this issue is solved and can be closed.

**Comment by VinceyNoir** [comment]
I suspect @stche is having problems as he's on a VPN, where the documents that @cartergreen is referring to is assuming you're sat on the corporate network "at the office" so to speak. As the folder redirection policy applies at boot/log on, the policy doesn't apply as the vpn tunnel isn't up at this point. I'm seeing the same thing.

**Comment by cartergreen** [comment]
@PaulLeRoy1028 I recognize that working right now is difficult since a lot of us are working from home.  Applying policies that are applied on boot/log on can be difficult due to VPM tunneling. Try running ‘gpupdate /force’ is almost equal to boot/log on experience and should solve your problem. GP will blindly re-apply all the policies and further periodic refresh will not alter them if they are not changed.

**Comment by PaulLeRoy1028** [comment]
Classification: Unsecured

I think folder redirection is a policy that must be applied at logon and gpupdate /force doesn't work in this instance. You'll see this in the event logs.

**Comment by lindspea** [comment]
@stche please let me know if this issue is resolved or if you need further assistance.

**Comment by scanum** [comment]
@Jeep16 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by stche** [comment]
Hello @lindspea ;
I am sorry for my delayed reply but I was on vacation the last two weeks.
Its actually not "resolved" as the descpiption in the documantation simply just dont work or is incomplete.
The initial purpose of this request was to complement the documentation with additional infos on scenarios where the given approach would work vs. where it doesnt work.

The point is that you may have to do way more than just "disable" the GPO and that it isnt even pulled when you dial in via a VPN connection. Sicne these days with COVOD almost everyone is working remotely, solutions or deployments via GPO are not really workign due to the VPN constraints and that needs to be clarified and added to the doc.
  
Pls. see the comments from **PaulLeRoy1028** above as well.
Kr
Steve

**Comment by Jeep16** [comment]
For anyone following or discovering this conversation there is now updated guidance in https://docs.microsoft.com/en-us/onedrive/redirect-known-folders has been updated with new guidance and a compliance check script.  Note it now says "The OneDrive Known Folder Move Group Policy objects won't work if you previously used Windows Folder Redirection Group Policy objects to redirect the Document" but a method is provided to setup known folders in OneDrive.

**Comment by bitslacker** [comment]
How do we disable Folder Redirection if users are remote and connect to vpn after logon?

**Comment by Wardrop** [comment]
So what is the procedure here? The docs currently say:

> The OneDrive Known Folder Move Group Policy objects won't work if you previously used [Windows Folder Redirection Group Policy objects](https://learn.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection) to redirect the Documents, Pictures, or Desktop folders to a location other than OneDrive.

But then below that it has instructions on how to do it:

> If folders have been redirected to a network file share:
> 
> [Use Migration Manager](https://learn.microsoft.com/en-us/sharepointmigration/mm-get-started) to copy contents in the network file share location to a user's OneDrive, making sure that all contents go into the existing Documents, Pictures, or Desktop folders.

> 
> Disable the Window Folder Redirection Group Policy and make sure to leave the folder and contents on the network file share.
> 
> Enable Known Folder Move Group Policy. Known folders move to OneDrive and will merge with the existing Desktop, Documents, and Pictures folders, which contain all the file share content that you moved in the first step.

That doesn't work though, and it's confusing that is says it won't work. Full stop. But then goes onto give instructions on how to do it... but which doesn't work. What is the correct procedure here, do we have to configure group policy to redirect the users known folder to their OneDrive?
