### ISSUE TITLE
Link in Note at bottom of the page points to a dead URL.

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/OfficeDocs-SharePoint#1997]
The following note at the bottom of the page has a pointer to a dead/incorrect URL: 
"For info about removing a user's license, see Remove licenses from users in Microsoft 365 for business."
The linked text points to: https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/remove-licenses-from-users

This link is no longer valid. 

Correct, current URL is: https://docs.microsoft.com/en-us/microsoft-365/admin/manage/remove-licenses-from-users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#feedback)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jwojan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jwojan Thank you for reaching out and helping improve MS Docs. It looks like the link has been fixed in the interim. Please could you check and confirm from your side. Thanks again.

**Comment by scanum** [comment]
@jwojan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
