### ISSUE TITLE
JSON Format functionality degredation

### ISSUE THREAD

**Issue by MickH3** [MicrosoftDocs/OfficeDocs-SharePoint#1998]
I have lost the ability to use TargetListRelativePath and provide a path other than a single folder at the top of the library.  I used to be able to supply a value like "Subfolder/SubFolderA/SubFolderA_B" and it would work.  As of the latest version of the tool, 3.2.118.0, I am now getting a Task Validation Error telling me the path is invalid.  

Full Example below.  This worked 3 months ago.

                                        {
                                            "SourceList":"Documents",
                                            "TargetList":"Documents",
                                            "SourceListRelativePath":"Subfolder/SubFolderA/SubFolderA_B",
                                            "TargetListRelativePath":"Subfolder/SubFolderA/SubFolderA_B"
                                        }

**Comment by MickH3** [comment]
As an update, I rolled back to 3.2.115.3 and I am now able to migrate to n-depth subfolder paths.

**Comment by scanum** [comment]
@MickH3 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
