### ISSUE TITLE
Minor error in content

### ISSUE THREAD

**Issue by ImmortalFeb** [MicrosoftDocs/OfficeDocs-SharePoint#1999]
Hi, 
In the section "Install and configure OneDrive on a mobile device", you have:
"
To learn how to perform tasks in OneDrive on an iOS device, see Use OneDrive on iOS.

To learn how to perform tasks in OneDrive on an iOS device, see Use OneDrive for Android.
"

Second entry should be "on an Android device" instead. 

Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7781f0-fe4d-c88b-1870-0c22a8e94449
* Version Independent ID: 79faccce-8e41-ae27-5a44-a66ab93b0df1
* Content: [OneDrive QuickStart guide for small businesses](https://docs.microsoft.com/en-us/onedrive/one-drive-quickstart-small-business#feedback)
* Content Source: [OneDrive/One-Drive-Quickstart-Small-Business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/One-Drive-Quickstart-Small-Business.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ImmortalFeb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ImmortalFeb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
