### ISSUE TITLE
Fine Tune

### ISSUE THREAD

**Issue by KoenVosters** [MicrosoftDocs/OfficeDocs-SharePoint#20]
Seems on the fine tuning that several container types are not available. The script also fails on SP2013.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff8221d-8995-2bd1-9ab4-e0043afe1c5f
* Version Independent ID: 2b157758-daa4-dad2-5edb-891e421d921f
* Content: [Manage the Distributed Cache service in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/manage-the-distributed-cache-service#finetune)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by bentoncity** [comment]
Thank you for finding this Koen. The topic is now fixed and republished.
