### ISSUE TITLE
Delve F3 Licensing

### ISSUE THREAD

**Issue by fkalyva** [MicrosoftDocs/OfficeDocs-SharePoint#2001]
According to official licensing documentation, Delve is not available for F3 users. When I sign in as an F3 user however, I can still access Delve normally from the M365 navigation bar, by clicking on my user name (top right corner) and then "My Office Profile", which redirects me to Delve. 

What I would expect, is that F3 users are not able to see that link at all, just like Delve is (understandably) hidden as a product from the waffle menu. Otherwise this is entirely confusing and it is hard to explain to customers and end-users why they see Delve, whereas their licensing says they shoudnt.

How do you explain that user experience and what do you recomend in that scenario?

**Comment by scanum** [comment]
@fkalyva thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fkalyva** [comment]
This is not a support request neitheir is specific to my tenant. This should be feeback sent to the product group as the way we offer this feature to our customers needs to be redesigned.
