### ISSUE TITLE
Does silent config work on latest OneDrive?

### ISSUE THREAD

**Issue by loosus456** [MicrosoftDocs/OfficeDocs-SharePoint#2002]
We have been using silent configuration with OneDrive for some time.  However, it no longer works.  We have verified that other organizations are having the issue; we have not misconfigured our environment.

Is silent configuration still supported?  Do the docs need to be updated to indicate that the feature is deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@loosus456 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by loosus456** [comment]
@scanum  Why would I open a service ticket if I don't even know if there is a problem?  I am asking if this feature is still supported.  Do you know **for sure** that silent config is still supported in the OneDrive client?
