### ISSUE TITLE
manage OneDrive using Group policy

### ISSUE THREAD

**Issue by HansBrender** [MicrosoftDocs/OfficeDocs-SharePoint#2005]
Browse to **%localappdata%\Microsoft\OneDrive\BuildNumber\adm** is not the only location of the files, if you have a vault in OneDrive Personal installed, it changed the location so:

you should add:

**%programfiles(x86)%\Microsoft OneDrive\[Build number]\adm**

Hans
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@HansBrender thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by HansBrender** [comment]
Hi all,

So that’s not what I thought. The documentation is not correct.
And I will not open a ticket.
I do not will write anything, that’s not my JOB

@Gaia Carini<mailto:gacarini@microsoft.com>
so that I often heard about github.
The responsible people has no idea of about the product, they close the ticket (maybe there were paid about it)
and its no my thing, to open a ticket.

If this is my work, I will never write any thing there.
THAT’s not my JOB

Could You please say, whats going on there?

Hans Brender

Hans Brender, Cloud Productivity Evangelist
Office Apps and Services MVP

Hans.Brender@HBsoft.de<mailto:Hans.Brender@HBsoft.de> |https://hansbrender.com<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhansbrender.com&data=02%7C01%7Chbrender%40bright-skies.de%7Cfac8e1329d114872ecb808d65f7383d9%7C42ecfa8dc13f4fd8b061c0786b8bb072%7C0%7C0%7C636801347087922832&sdata=oXFCdfU2C0V1pkc85DdOSwnBDtoZR9hw5py4c1M2v%2FQ%3D&reserved=0> | @HansBrender<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FHansBrender&data=02%7C01%7Chbrender%40bright-skies.de%7Cfac8e1329d114872ecb808d65f7383d9%7C42ecfa8dc13f4fd8b061c0786b8bb072%7C0%7C0%7C636801347087932840&sdata=BdPou%2FLxLDwXgtUeSVYZDzuIm3v6bboMckSQ2NmQeuI%3D&reserved=0>  | +49 171 7736198
Number 7 of SharePoint Top 25 Influencer 2019<https://hansbrender.com/2019/05/23/sharepoint-top-25-influencers-2019/>
[cid:image001.png@01D6276E.9B2A1300]

**Comment by gacarini** [comment]
@scanum  I asked Hans to submit this as feedback since I confirmed it was a gap we forgot to fill when we rolled out support for the per machine install. There is no need to open a ticket for it.

**Comment by tommurphy288** [comment]
This still does not work, the current installed clients that come with Windows 10 or 11 do not have the ADM files or build numbers, where does one get these templates?

**Comment by HansBrender** [comment]
after installing OneDrive the first thing is ... you got the newest version, depending on the ring
then, it depend, what OS version you have... you will find the 3 locations

32 Bit:  %localappdata%\Microsoft\OneDrive\BuildNumber\adm\ 

or machine installation 

32 Bit C:\Program Files (x86)\Microsoft OneDrive\Buildnumber\adm
**64 Bit C:\Program Files\Microsoft OneDrive\Buildnumber\adm**

But these admx/adml files come with each new OneDrive update, and the adminstrators have it on her devices
The Buildnumber is the OneDrive Version number and you can show them in the onedrive app
