### ISSUE TITLE
Powershell command needs update in this document

### ISSUE THREAD

**Issue by elhamkarshenas** [MicrosoftDocs/OfficeDocs-SharePoint#201]
I guess the command be updated to: Unregister-SPOHubSite -identity [URL] 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96fc2661-679c-dff4-7e87-651f0b154513
* Version Independent ID: 9a0a4a29-c1e9-572a-9009-ed3c320a070d
* Content: [Remove a hub site](https://docs.microsoft.com/en-gb/sharepoint/remove-hub-site)
* Content Source: [SharePoint/SharePointOnline/remove-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/remove-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
Thank you for submitting this feedback.

I want to make sure this PowerShell code gets updated. I am going to make sure the SharePoint team gets this information and addresses it appropriately.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
