### ISSUE TITLE
Typo in section Improving your connectivity to 0ffice 365 and Azure

### ISSUE THREAD

**Issue by EEmpire** [MicrosoftDocs/OfficeDocs-SharePoint#2010]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/19501870/81554814-05479980-93ba-11ea-96f0-0444a84af00f.png)
Typo: "0ffice"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e1dc7e-46ae-1b74-a205-e6f75a1f4cdd
* Version Independent ID: e1e8803a-0190-429e-fa3f-4a410bf580c0
* Content: [Improving your SPMT performance - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-performance-guidance#feedback)
* Content Source: [migration/SPMT-performance-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-performance-guidance.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@EEmpire Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@EEmpire Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
