### ISSUE TITLE
Trying to transfer on beefy machine and taking WEEKS

### ISSUE THREAD

**Issue by solinear** [MicrosoftDocs/OfficeDocs-SharePoint#2013]
I've used the SPMT previously for migrations to OneDrive and am currently trying to transfer to SharePoint.  I have a folder with a few million files and it is taking weeks to transfer and will eventually fail out.  I don't expect that the "send files to us" option will work any better, as that just uses a VM in Azure and this isn't a file transfer issue.

What can we do to speed up these migrations?

**Comment by scanum** [comment]
@solinear thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by solinear** [comment]
Did so.  With Document  Libraries, you can include subfolders.  Example:

Source,SourceDocLib,SourceSubFolder,TargetWeb,TargetDocLib,TargetSubFolder
C:\MigrationTests\testfiles,,,https://contoso.sharepoint.com/sites/Sample/,DocLibraryName,DocLibraryName_subfolder/subsubfolder

This properly places the files another level deep.  This can be useful for migrating document libraries with an exceptional number of files (in the millions).
