### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2016]
more tha Microsoft search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb4771c-6c09-daca-5a88-e6f0b2e08175
* Version Independent ID: 5156d0e5-1a97-b722-a8dd-f6c7a2ecd1e1
* Content: [SharePoint Online classic search administration overview - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-search-the-admin-center)
* Content Source: [SharePoint/SharePointOnline/manage-search-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-search-the-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
