### ISSUE TITLE
Adherence to the settings for allowing users to add new guests to the organization

### ISSUE THREAD

**Issue by Simon-de-V** [MicrosoftDocs/OfficeDocs-SharePoint#2019]
Does the new method of securely sharing files and folders with external users adhere to the settings in the tenant and Azure Active Directory for allowing users to add new guests to the organization?

A short test from my side indicates it doesn't. I don't allow users to add new guests to the organization, but I'm still able to share a file with an external user who has a work account. And consequently a guest user is created in my tenant.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint - SharePoint Online](https://docs.microsoft.com/nl-NL/sharepoint/what-s-new-in-sharing-in-targeted-release)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@Simon-de-V the experience described in this article does not adhere to the Azure AD settings. However, you can use [SharePoint and OneDrive integration with Azure AD B2B (Preview)](https://docs.microsoft.com/sharepoint/sharepoint-azureb2b-integration-preview) which will.

**Comment by Simon-de-V** [comment]
Ok, so it is only governed by the settings for external sharing in the SharePoint admin center?

**Comment by MikePlumleyMSFT** [comment]
Yes, file and folder sharing are only governed by the SharePoint settings unless you've enabled integration with Azure B2B.

**Comment by scanum** [comment]
@MikePlumleyMSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
