### ISSUE TITLE
Add Reference to the URL "oneclient.sfx.ms"

### ISSUE THREAD

**Issue by gtageek** [MicrosoftDocs/OfficeDocs-SharePoint#202]
Hello,
In our experience, we learnt that the OneDrive for Business (ODfB) Sync Client can only update itself successfully if the computer is able to reach the URL "oneclient.sfx.ms". If this URL is not reachable from the computer where the ODfB Sync Client is running, then the Sync Client can never update itself and will eventually block the user from signing in. We learnt this the hard way and once we updated our web filtering to not block the URL "oneclient.sfx.ms" the ODfB Sync Client issue was immediately resolved.

This URL also appears in the XML file published by Microsoft in the article called Office 365 URLs and IP Address Ranges - https://support.office.com/en-us/article/office-365-urls-and-ip-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2.

Please add a reference to this so it can benefit other customers.
Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8d826-fd44-b260-77e7-24d9ddd6e67f
* Version Independent ID: b0df9532-a918-a341-2790-a61a8c5c6894
* Content: [The OneDrive sync client update process](https://docs.microsoft.com/en-ca/onedrive/sync-client-update-process?redirectSourcePath=%252fen-us%252farticle%252fthe-onedrive-sync-client-update-process-2f748bc6-6f01-4406-a791-ec047f066d6d)
* Content Source: [OneDrive/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
Thank you for this helpful note, @gtageek ! I have added it and the update will be published shortly. Much obliged!
