### ISSUE TITLE
Organisational Asset Library license clarification.

### ISSUE THREAD

**Issue by TristanJamesBall** [MicrosoftDocs/OfficeDocs-SharePoint#2020]
Can you please clarify the license terms? Does "Office.com" mean the the web versions of the office applications?
Is this available for - for example, for an Microsoft 365 Business Premium user, running the desktop app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library#feedback)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TristanJamesBall Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TristanJamesBall thank you for reaching out. Yes, as far as I know, that means the web version. Here is the link to show what is included with Microsoft 365 Business Premium plan -https://www.microsoft.com/microsoft-365/business/microsoft-365-business-premium?market=af

**Comment by scanum** [comment]
@TristanJamesBall Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
