### ISSUE TITLE
Picture export From SharePoint to Active Directory

### ISSUE THREAD

**Issue by NileshGhodekar** [MicrosoftDocs/OfficeDocs-SharePoint#2022]
Hi,
 The SPMA supports either import -only (from SharePoint to MIM) or export-only (from MIM to SharePoint)  operation on Picture / Photo attribute, just not both at the same time. So the statement "There is no support of picture export from SharePoint to Active Directory, so you need to plan for this migration." looks out of context here. Can this be confirmed and the document updated correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6b12de-cdad-0c60-acb7-24b4a18c4f23
* Version Independent ID: fb7a97d7-d5f6-022f-08a1-2b173de21bb0
* Content: [Deployment considerations for implementing Microsoft Identity Manager with SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/administration/deployment-considerations-for-implementing-microsoft-identity-manager-with-share#picture-export-from-sharepoint-to-active-directory)
* Content Source: [SharePoint/SharePointServer/administration/deployment-considerations-for-implementing-microsoft-identity-manager-with-share.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/deployment-considerations-for-implementing-microsoft-identity-manager-with-share.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@NileshGhodekar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@MikePlumleyMSFT could you perhaps confirm and I'll do the PR.

**Comment by MikePlumleyMSFT** [comment]
@TroyStarr can you confirm?
