### ISSUE TITLE
Modern Team Site Without Group

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-SharePoint#2030]
I created a new site with the template "Modern Team Site Without Group"(STS#3). The flag value for "DenyAddAndCustomizePages" is "Disabled" but at the same time, I can see a lot of the settings which should not be there as per this document.

Under the section "Features affected when custom script is blocked" it says that "The following site settings are unavailable when users are prevented from running custom script"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script?redirectSourcePath=%252farticle%252f1F2C515F-5D7E-448A-9FD7-835DA935584F#features-affected-when-custom-script-is-blocked)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ravick4u thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
