### ISSUE TITLE
Default sharing link type options have changed

### ISSUE THREAD

**Issue by DaveWitwicki** [MicrosoftDocs/OfficeDocs-SharePoint#2031]
Default sharing link type options now include option for People with existing access. Launched Q1 CY2020 - Feature ID: 60335.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default sharing link for a site - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/change-default-sharing-link#feedback)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@DaveWitwicki  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@DaveWitwicki Thank you for reaching out and helping improve MS Docs. As far as I can see the article reflects this, or am I maybe missing something? Please clarify so I can double check and add a note. Thanks again.

**Comment by DaveWitwicki** [comment]
@lindspea In the "Change the default link type for the site" section - item 4, the screenshot doesn't show the new option added recently: 
![image](https://user-images.githubusercontent.com/17456364/82069072-d32b8580-96a0-11ea-866d-59c2c0c8377e.png)

Also, the Note on using Set-SPOSite should mention that this only works with sites that are not connected to an Office 365 Group. Hopefully that gets changed at some point; I think I saw an open issue for this regarding Set-SPOSite.

**Comment by lindspea** [comment]
Hi @MikePlumleyMSFT, is this updated screenshot in the pipeline? Let me know if you'd like me to do the PR.

**Comment by MikePlumleyMSFT** [comment]
New screenshot should be published sometime tomorrow.

**Comment by scanum** [comment]
@DaveWitwicki  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
