### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/OfficeDocs-SharePoint#2032]
The steps above do not work.  It completes but doesn't actually provision it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts#feedback)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mattdreher thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattdreher** [comment]
I figured out the issue.  Even though you can create the one drive manually by going to your online portal and clicking on OneDrive, you cannot do it through the provisioning steps in this documentation without having the SharePoint Online license.  You may want to adjust the instructions to indicate that this does not working in such circumstances.
