### ISSUE TITLE
Missing admin piece in documentation

### ISSUE THREAD

**Issue by bharto** [MicrosoftDocs/OfficeDocs-SharePoint#2033]
I've found that one needs to be an owner of the document library when adding the asset library.  If this is correct I believe documentation should be updated to reflect 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library#feedback)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@bharto  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bharto Thank you for reaching out and helping improve MS Docs. I think this link in the article provides more clarity https://support.office.com/article/customize-permissions-for-a-sharepoint-list-or-library-02d770f3-59eb-4910-a608-5f84cc297782?ui=en-US&rs=en-GB&ad=GB. Let me know if you agree.

**Comment by scanum** [comment]
@bharto Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
