### ISSUE TITLE
How to resume task on password change

### ISSUE THREAD

**Issue by Rupalikothawade** [MicrosoftDocs/OfficeDocs-SharePoint#2034]
What to expect if the connection between the agent and Migration Manager is stopped due to password change of SharePoint admin account connecting to target path.
Will the migration agent need to be open and configure again with new password, and task will be automatically picked from manager or need to activate/resume from admin center interface?

**Comment by scanum** [comment]
@Rupalikothawade thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
