### ISSUE TITLE
Alerting for automatic storage limit

### ISSUE THREAD

**Issue by joerifeyen** [MicrosoftDocs/OfficeDocs-SharePoint#2036]
"By default, your SharePoint storage is available in a central pool from which all sites can draw. You, as a global or SharePoint admin, don't need to divvy up storage space or reallocate space based on usage. That's all handled automatically: sites use what they need when they need it. If you previously set storage limits manually and switch to using pooled storage, SharePoint resets all the limits to 25 TB (25600 GB). (Note that the total storage for your organization might be less than 25 TB.)"
When using automatic storage limit. Is the tenant or sharepoint admin alerted when sharepoint reaches the organization limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/manage-site-collection-storage-limits#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@joerifeyen thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
