### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bramdejager** [MicrosoftDocs/OfficeDocs-SharePoint#2037]
The 2nd link in Related Topics is broken, this is the link "Configure and deploy mobile application management policies in the Microsoft Intune console" which links to https://go.microsoft.com/fwlink/?linkid=2003554. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb73e568-9145-abd7-a0fe-4b03bdb875ee
* Version Independent ID: 8036cdd2-2877-e9cd-2878-04121ab9666c
* Content: [Control access to features in the OneDrive and SharePoint mobile apps](https://docs.microsoft.com/en-us/onedrive/control-access-to-mobile-app-features?redirectSourcePath=%252farticle%252fd25713bb-5cf8-4874-9b5b-e8bee3b94f13#feedback)
* Content Source: [OneDrive/control-access-to-mobile-app-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-to-mobile-app-features.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@bramdejager  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@bramdejager thank you for pointing this out and helping improve MS Docs. I think the article has possibly been updated and renamed. Please have a look at these two links and let me know if one could be correct. https://docs.microsoft.com/mem/intune/apps/app-management and https://docs.microsoft.com/mem/intune/apps/app-lifecycle

**Comment by scanum** [comment]
@bramdejager Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
