### ISSUE TITLE
How to get a list of those new Active Sites using CSOM?

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/OfficeDocs-SharePoint#2038]
How to get a list of those new Active Sites using CSOM?

Can I have a Remote Event Receiver in a site like that?

**Comment by scanum** [comment]
@tbebekis thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
