### ISSUE TITLE
The Application will exit because of sign-in failure

### ISSUE THREAD

**Issue by Rupalikothawade** [MicrosoftDocs/OfficeDocs-SharePoint#2039]
hi Team,

We are facing issues while opening an existing install SharePoint migration tool. Error message as mentioned below
The application will exit because of sign-in failure.
Please double check and try again.

Can you suggest- where to double check, any specific config file?
This error is coming on opening the application.

**Comment by scanum** [comment]
@Rupalikothawade thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Rupalikothawade** [comment]
Seems like it was related to end point pre-requisites, fixed with IE proxy settings.
