### ISSUE TITLE
Limit type

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2040]
Limit type for Maximum number of on-premises items indexed in Microsoft 365 is Threshold.
Should it be either Boundary or Supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171ee42a-95a9-6543-dd99-696ba7025cd0
* Version Independent ID: a3b3b40f-b808-7ac6-b420-a9b7bb0361fb
* Content: [Search limits for SharePoint Online - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/search-limits?redirectSourcePath=%252fen-us%252farticle%252fSearch-limits-for-SharePoint-Online-7C06E9ED-98B6-4304-A900-14773A8FA32F)
* Content Source: [SharePoint/SharePointOnline/search-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/search-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@hwkwicre thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hwkwicre** [comment]
I was actually referring to something in the document though. It's not a problem on my tenant.
