### ISSUE TITLE
Can't import any csv file

### ISSUE THREAD

**Issue by robdegekste** [MicrosoftDocs/OfficeDocs-SharePoint#2042]
Hi all,
I wanna use the csv file to import all the path for the migration. Around the 400 lines.
Every csv file i try, doens't work. I tried it with two different tenants but none of my csv file works. 

I use just three columns:

Column A: networksource of drive letter: 
Column C: Site in SharePoint
Column D: Name of the library

I don't see whats wrong?

![Import](https://user-images.githubusercontent.com/65591194/82298703-cf577600-99b4-11ea-902c-4b99a377542b.png)
![import 2](https://user-images.githubusercontent.com/65591194/82298707-cff00c80-99b4-11ea-94b9-7870c1ae3331.png)

**Comment by scanum** [comment]
@robdegekste thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
