### ISSUE TITLE
The SharePoint Migration Assessment Tool

### ISSUE THREAD

**Issue by Arthur-Avanesyan** [MicrosoftDocs/OfficeDocs-SharePoint#2043]
As I see SharePoint Migration Tool (Preview) supports SharePoint 2016.
What about The SharePoint Migration Assessment Tool? Will it ever support SP2016?

**Comment by scanum** [comment]
@Arthur-Avanesyan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Arthur-Avanesyan** [comment]
I'd already opened a service ticket, but didn't get any confirmation, that this will be resolved ever. They don't have any estimations and cannot even confirm, whether there will be SMAT support for SharePoint 2016 or not.
