### ISSUE TITLE
Typo in Improving your connectivity to 0ffice 365 and Azure

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/OfficeDocs-SharePoint#2044]
Pedantic, but the product name is Office 365, not 0ffice 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdbc84db-7466-2e82-44c9-97a9047a6adf
* Version Independent ID: 1add53aa-0ace-3309-4e4d-8146ee4331f9
* Content: [Improving your Migration Manager performance - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-performance)
* Content Source: [migration/mm-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-performance.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@cabtilx Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@cabtilx Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
