### ISSUE TITLE
Supported Destinations

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/OfficeDocs-SharePoint#2045]
Please make it clear that OneDrive or Teams are supported destinations. This is not documented anywhere here and is only obvious when users click through the Migration Manager task wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210e3fb6-665e-a4e6-7b5e-fe3776ec1635
* Version Independent ID: 80b1c7f6-736f-70a4-ae6c-503d64e94a26
* Content: [Get started with Migration Manager  - SharePoint Online - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-get-started)
* Content Source: [migration/mm-get-started.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-get-started.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@cabtilx Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cabtilx thank you for reaching out and helping improve MS Docs. Please can you be a bit more specific about which section of this article needs to be updated with that information so that I can assist further.

**Comment by cabtilx** [comment]
Hi @lindspea 

Where it says "Access to the destination: You must either be a global admin or SharePoint admin to the Microsoft 365 tenant where you want to migrate your content." This suggests the destination has to be SharePoint. OneDrive is not mentioned on the document at all yet this is also a valid destination.

**Comment by scanum** [comment]
@cabtilx  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
