### ISSUE TITLE
OneDrive Manage backup

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/OfficeDocs-SharePoint#2047]
How different is this mode from the manual Manage backup option in the OneDrive client? The UI looks the same with "Back up your folders" title instead of "Your IT department wants you to protect your important folders".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://docs.microsoft.com/en-us/OneDrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@icelava thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cartergreen** [comment]
There is no difference between the two Manual vs Policy-enabled.  They perform the same operation they are just controlled or rather triggered from two different sources.  If an admin would like to deploy Known Folder Move across their environment they would use these policies instead of relying on user's manually enabling the feature.
