### ISSUE TITLE
Full Control permission not migrating from File Share to SharePoint Online

### ISSUE THREAD

**Issue by sarikapawar26** [MicrosoftDocs/OfficeDocs-SharePoint#2048]
We have done migration from File share to SharePoint Online in our testing environment and found that we are able to migrate Read, Read and execute, modify permissions to SPO, But we are unable to migrate Full Control permissions from File Share to SharePoint online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33316097-fcf2-3efb-8684-dfab3ac0624d
* Version Independent ID: 94ab0da3-a0ad-9c6b-7e27-aa87e356ba43
* Content: [File & folder permission when using SharePoint Migration Tool - SharePoint Online - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/understanding-permissions-when-migrating#feedback)
* Content Source: [migration/understanding-permissions-when-migrating.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/understanding-permissions-when-migrating.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@sarikapawar26 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
