### ISSUE TITLE
Ransomware protection

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/OfficeDocs-SharePoint#2049]
Why isn't there any page here (especially the Sharing and security section) that discusses ransomware protection issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises - OneDrive](https://docs.microsoft.com/en-us/OneDrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@icelava thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by icelava** [comment]
This isn't a tech support issue; it's about the documentation making no mention of the feature. Only a few pages from support.microsoft.com, and other 3rd-party technical communities dominate the topic. If docs.microsoft.com is supposed to be the _authoritative_ source, more writing work needs to be done.

**Comment by kaarins** [comment]
Hi @icelava, thanks for this feedback. We have articles about ransomware, but they are part of other M365 security documentation and don't live with the SharePoint articles. I hope these links help: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/ransomware-malware
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams?view=o365-worldwide
https://docs.microsoft.com/en-us/office365/enterprise/office-365-malware-and-ransomware-protection
