### ISSUE TITLE
Conflicting instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#205]
I don't quite understand what is meant by the 2nd bullet below the following statement, it seems to contradict the initial sentence. 
 
The AD import option does not support multi-Forest scenarios such as:
* If you have a trust between two forests, the trusted forest objects will not be imported.
* AD import does support importing users from multiple forests provided you create one synchronization connection per forest. As an alternative, consider using Microsoft Identity Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fce18fe-f0e9-a06d-1f5a-537d56b2895f
* Version Independent ID: 3198803b-9b3d-a050-c9e7-94cf21130d4c
* Content: [Configure profile synchronization by using SharePoint Active Directory Import in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import#situations-unsupported-by-ad-import)
* Content Source: [SharePoint/SharePointServer/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-profile-synchronization-by-using-sharepoint-active-directory-import.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Yeah, it's confusing -- basically what bullet point one means is that the objects from the trusted forest won't be sync'ed because there is an explicit trust. Point two says that you can create multiple sync connections, one per forest, to sync objects and that does work.

I was the last one to update bullet point 2. If you have suggestions on wording changes, let me know.

**Comment by AndreaBarr** [comment]
@DeanGross  Thank you for submitting this Feedback.

From my understanding the question you had on the bullet points has been answered. If the issue is not resolved please re-open this issue.
