### ISSUE TITLE
OneDrive shows two folders in navigation pane

### ISSUE THREAD

**Issue by kpropell** [MicrosoftDocs/OfficeDocs-SharePoint#2050]
The default installation created a OneDrive-folder and is visible in Explorer navigation pane.
When we use the Per-machine installation and users log in (non-persistant VDI), our organizational OneDrive folder get's created, but the default OneDrive does not get removed and users unfortunately move files to the wrong folder and then nothing is saved to the real OneDrive.

Can this be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine - OneDrive](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@kpropell thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
