### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by tanktopArmy** [MicrosoftDocs/OfficeDocs-SharePoint#2051]
There's a typo in "Permanently Delete a Site" Step 3 - it says "yo" instead of "to".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bd11d3-f2a4-2811-09bd-449c3c3607da
* Version Independent ID: 2f47da99-02e6-3357-ed41-b28bd5190907
* Content: [Delete a site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/delete-site-collection#feedback)
* Content Source: [SharePoint/SharePointOnline/delete-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delete-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tanktopArmy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@tanktopArmy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
