### ISSUE TITLE
Please add more details on Exclude Settings

### ISSUE THREAD

**Issue by aurasa** [MicrosoftDocs/OfficeDocs-SharePoint#2052]
1. How to separate subsites if I want to exclude more than one? Same for 'Filter lists and libraries' and 'Filter content type'

2. What exactly does it expect? URLs? relative, site-relative, absolute? (localized) display names or technical name (Lists can be renamed but the Object Model refers to the original name as far as I know? GUIDs? 

Thank you for clarification. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad86450-d9ac-4cc4-fc75-63f8b285c298
* Version Independent ID: d1e8c85a-b365-78c0-be1a-5a03ee082491
* Content: [Available settings in SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-settings#feedback)
* Content Source: [migration/SPMT-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@aurasa  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@aurasa thank you for reaching out. Please have a look at this article and let me know if it helps at all - https://docs.microsoft.com/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration

**Comment by scanum** [comment]
@aurasa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by aurasa** [comment]
Hello Lindsay @lindspea and thank you for trying to help me. I am sorry for my late response, it seems Git did not send me a notification or it went into my spam folder. Unfortunately the page you reference does not provide the information I was looking for. 
I asked for more details and examples on the settings page of the SharePoint migrator for the following settings: 
- Filter subsites
- Filter lists and libraries
- Filter content type

"Enter the names of ..." is quite unspecific. How to separate names if there is more than one? And does it want the (probably localized) display name or the technical name or the GUID? 

![SPMT_Exclude_Settings](https://user-images.githubusercontent.com/26224663/84781625-5c5b1280-afe7-11ea-9370-142f4401ec0b.png)
