### ISSUE TITLE
Time required for CDN set-up and Publication

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/OfficeDocs-SharePoint#2054]
The documentation should give an idea how long this will take to come into effect and start working. I've set-up two Organizational Assets Libraries and after several hours, they still aren't visible anywhere. Even if it's just a broad range to give customers an idea how long it could potentially take.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library#feedback)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@richardjgreen @kevball2 thank you for engaging with the community here for the docs.

 
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.
