### ISSUE TITLE
"Example_CSV_Map.csv" is not hyperlinked

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/OfficeDocs-SharePoint#2057]
In the section "Migrate Users" (anchor https://docs.microsoft.com/en-us/sharepointmigration/mover-o365-to-o365#migrate-users) the text reads: "Download an example CSV: Example_CSV_Map.csv".

However, "Example_CSV_Map.csv" is not hyperlinked.  Could you please either remove that text, or provide a suitable example CSV?  Meanwhile, I appreciate that the section does include the format the CSV file must follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08856382-39dd-695b-5c39-8bfb27c8f663
* Version Independent ID: 5ef7ad6b-9514-09fc-4f60-4cf4bd50955f
* Content: [Migrating to Microsoft 365 from Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-o365-to-o365#feedback)
* Content Source: [migration/mover-o365-to-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-o365-to-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson

**Comment by scanum** [comment]
@rsoakford  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thanks Manuela.

**Comment by scanum** [comment]
@rsoakford  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
