### ISSUE TITLE
Generating Open Graph code

### ISSUE THREAD

**Issue by FisherFast** [MicrosoftDocs/OfficeDocs-SharePoint#206]
Early in the article, the author writes: "By using Search Engine Optimization capabilities of SharePoint Server 2016 we can retrieve the information about the page as follows:"

How do you generate the open graph code that follows, using Sharepoints SEO capabilities? I'm particularly interested in finding out how to generate open graph code for a page image. I'm using item display templates with cross-site publishing.

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38de4b6-af0d-bdf3-d875-b623c28549e1
* Version Independent ID: 491f608b-207a-3884-2d1d-36ac34834606
* Content: [Integrating social media with public-facing websites in SharePoint](https://docs.microsoft.com/en-us/sharepoint/administration/integrating-social-media-with-public-facing-websites)
* Content Source: [SharePoint/SharePointServer/administration/integrating-social-media-with-public-facing-websites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/integrating-social-media-with-public-facing-websites.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@FisherFast Thank you for your feedback. 

I want to make sure you are get the information about generating the graph code. The support team will be able to handles this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
