### ISSUE TITLE
The link https://docs.microsoft.com/office-365/compliance/retention-policies is missing

### ISSUE THREAD

**Issue by khairop** [MicrosoftDocs/OfficeDocs-SharePoint#2060]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c77b51-93e6-ddaf-d49f-6e703ced3b84
* Version Independent ID: 79ecbd91-f096-e6b6-4561-96b41ebe005b
* Content: [SharePoint governance overview - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/governance-overview)
* Content Source: [SharePoint/SharePointOnline/governance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/governance-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@khairop  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@khairop thank you for reaching out and helping improve MS Docs. Please can you clarity what is missing from the article and in which section. The link you mentioned returns 404 - page not found.

**Comment by khairop** [comment]
Hello,

the link https://docs.microsoft.com/en-us/office-365/compliance/retention-policies is missing from titled "Overview of the retention policies" is missing from the page  https://docs.microsoft.com/en-us/sharepoint/governance-overview

**Comment by scanum** [comment]
@khairop Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
