### ISSUE TITLE
Local Files Migration to ODFB

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SharePoint#2061]
This document mentions that "If you have **files and folders on your computer** or on a network drive, you can use either of the following tools to to migrate that content to your own OneDrive for FREE!"
But Migration Manager and SPMT can be used to migrates files from file shares. I couldn't find any way to migrate files from individual computer to their respective OneDrive.

Can you please provide some clarity on Local Files and Folder migration from individual desktop to OneDrive in the Article?
Thanks.                                                 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8673a55f-50c6-bd98-6b4f-d54db859216d
* Version Independent ID: 571c56c2-0be7-0296-ab36-3a75ff3874a9
* Content: [Migrate content to OneDrive in Office 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/migrating-content-to-onedrive-for-business)
* Content Source: [migration/Migrating-content-to-OneDrive-for-Business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Migrating-content-to-OneDrive-for-Business.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@3novsan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@3novsan Thank you for reaching out and helping improve MS Docs. Please have a look at this article and let me know if it helps at all. https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/migrate-your-files-to-onedrive-easily-with-known-folder-move/ba-p/207076

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
