### ISSUE TITLE
In People Search Result, how can we display user account only?

### ISSUE THREAD

**Issue by Vishni92** [MicrosoftDocs/OfficeDocs-SharePoint#2062]
Hi,

In a people search result page, we have 1500+ user accounts. But there are several services
accounts added by the company needed.  We want to creat to display only user accounts on people search results page. 
For instance; test@xxxx.com,info@xxx.com, helpdesk@xxxx.com, and name@yyy.com
The problem is there are so many accounts we want to exclude and preview. If we use -accountname:test*, but in some cases it doesn't work. Is there any option to do this easier?

Thanks

**Comment by scanum** [comment]
@Vishni92 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
