### ISSUE TITLE
Applies To section

### ISSUE THREAD

**Issue by swapz17** [MicrosoftDocs/OfficeDocs-SharePoint#2064]
Applies to section like the one currently available in SharePoint server docs would help to understand which of the SharePoint online documentation applies to SharePoint 2019 server and SharePoint 2016 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc5a61a-6ec4-319b-ef96-4c4ed022995c
* Version Independent ID: 9ba50dad-1afd-edf4-8cbe-c9e59138871a
* Content: [Information architecture for the modern experience - SharePoint - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/information-architecture-modern-experience)
* Content Source: [SharePoint/SharePointOnline/information-architecture-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/information-architecture-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@swapz17 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@swapz17 the SharePoint Online documentation is meant only for SharePoint Online. It does not apply to SharePoint Server.

**Comment by scanum** [comment]
@swapz17  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
