### ISSUE TITLE
"Site"/"Site Collections" naming consistency

### ISSUE THREAD

**Issue by 4x0v7** [MicrosoftDocs/OfficeDocs-SharePoint#2065]
Hi there!

The wiki page mentions 

> sites (previously called "site collections")

and the M365DSC [page here](https://github.com/microsoft/Microsoft365DSC/wiki/SPOSite) calls them Site Collections

It would be nice to have the naming conventions consistent for SharePoint Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7461c2ef-3439-2c86-4dde-8992b62bf9a7
* Version Independent ID: faa4e3aa-8ec4-f1f1-d4bd-4058999545f3
* Content: [About the SharePoint admin role in Microsoft 365 - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharepoint-admin-role)
* Content Source: [SharePoint/SharePointOnline/sharepoint-admin-role.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-admin-role.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@4x0v7  thank you for engaging with the community here for the docs.
 
 
 
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.
