### ISSUE TITLE
How to switch SQL Managed Instance hosted in one region to another in case of DR??

### ISSUE THREAD

**Issue by osmanteyeb** [MicrosoftDocs/OfficeDocs-SharePoint#2066]
let's assume that I have a SharePoint farm hosted as IaaS, and SQL Managed Instance in a primary region. 
also, I have a DR environment in another region that will fallback in case of Disaster. 
How the failover of SQL MI will occur in this scenario?

**Comment by scanum** [comment]
@osmanteyeb thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
