### ISSUE TITLE
Problems with Firefox on sharepoint.com

### ISSUE THREAD

**Issue by notanic** [MicrosoftDocs/OfficeDocs-SharePoint#208]
I have found there are problems performing certain actions with Firefox and Sharepoint online.
1. You cannot open file:// links. So if you have docs on file shares inside your organization they won't work. They worked pre-quantum with an addon, but not now.
2. When you click on a Sharepoint hosted doc, it will download a read only copy to your local computer and open with Office, i.e you cannot edit the doc.  When opening the same link from Internet Explorer it loads directly from the sharepoint URL, and gives the option to open for editing.  So Firefox does not let you edit docs directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d1b075-d17b-510d-f886-4f5deed4cc9e
* Version Independent ID: 336f78e0-78e2-0a55-5e1b-2bf41072a0cb
* Content: [Plan browser support in SharePoint Servers 2016 and 2019 Public Preview](https://docs.microsoft.com/en-us/sharepoint/install/browser-support-planning-0)
* Content Source: [SharePoint/SharePointServer/install/browser-support-planning-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/browser-support-planning-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
You should report issue 1 to your browser vendor. http://bugzilla.mozilla.org/ is likely what you'd want to use. It is up to the browser vendor to support the file:// protocol.

This has always been true with non-IE browsers and classic mode sites.

The document does list that there are limitations, but this isn't designed (IMO) to be an exhaustive list of all things that will not work. It is going to be up to the organization to determine the best browser choice.

**Comment by jmhdk** [comment]
https://docs.google.com/document/d/1qnPkS9OdDnp7GzqbK41byitMjryLQILI9Sv2vQ4tHIE/edit?usp=drivesdk

**Comment by notanic** [comment]
I'm not going to click on that link.

**Comment by AndreaBarr** [comment]
@notanic Thank you for the feedback.


From my understanding this question about the Firefox missing the file:// links has been answered. If the issue is not resolved please re-open this issue.
