### ISSUE TITLE
Default document size threshold value misleading

### ISSUE THREAD

**Issue by radukg** [MicrosoftDocs/OfficeDocs-SharePoint#2081]
There are two sections in [article](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0) around default document size threshold, in first case it is 250 MB:
"the default document size threshold is set to 250 megabyte (MB)", and in second it is 2 GB: "The default file size is 2 gigabytes (GB) (2,047 MB)". The request is to update 1st sentence in the article as far as default value is 2 gigabytes (at least in SP2016)

**Comment by scanum** [comment]
@radukg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @radukg

**Comment by scanum** [comment]
@radukg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
