### ISSUE TITLE
Home Site and Multi-Geo?

### ISSUE THREAD

**Issue by GitUser47** [MicrosoftDocs/OfficeDocs-SharePoint#2082]
How do SharePoint home sites work in multi-geo scenarios? 
Can I define a home site for each geo-location root or is it still only one home site for the whole organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@GitUser47 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
