### ISSUE TITLE
Missed logincdn.msauth.net in list of endpoints required for OneDrive

### ISSUE THREAD

**Issue by Aynyuh** [MicrosoftDocs/OfficeDocs-SharePoint#2083]
The article doesn't contain endpoint logincdn.msauth.net:443 although it's required to load page https://login.live.com/ correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4308cb37-c2e4-e751-c62f-07bef7b50c14
* Version Independent ID: 29ae5f3f-50e4-a9fb-7c1c-0b56f236e214
* Content: [Required URLs and ports for OneDrive consumer - OneDrive](https://docs.microsoft.com/en-us/onedrive/required-urls-and-ports)
* Content Source: [OneDrive/required-urls-and-ports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/required-urls-and-ports.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Aynyuh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Aynyuh 
The article lists the endpoints needed by the OneDrive client (OneDrive.exe), not the endpoints needed for the web browser to login to login.live.com.

> This reference article lists every endpoints used by the consumer version of OneDrive

Also checked with a http sniffer.

You also can find *.msauth.net in the [referenced article](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)

**Comment by scanum** [comment]
@Aynyuh Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
