### ISSUE TITLE
Limited Access Not working on OneDrive user accounts

### ISSUE THREAD

**Issue by satyamg448** [MicrosoftDocs/OfficeDocs-SharePoint#2086]
We would like enable the web-limited access for all of our OneDrive files. We do not want the restrictions to apply to other SharePoint collections.
I ran the below mentioned command and its executed successfully.
PS C:\WINDOWS\system32> Set-SPOSite -Identity https://CompanyName-my.sharepoint.com -ConditionalAccessPolicy AllowLimitedAccess

Now when I ran the below command to check the conditional access policy applied to OneDrive Site or not. 
Get-SPOSite -Identity https://CompanyName-my.sharepoint.com | Select ConditionalAccessPolicy

ConditionalAccessPolicy
AllowFullAccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-a-specific-sharepoint-site-or-onedrive)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@satyamg448 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
