### ISSUE TITLE
Error codes not listed

### ISSUE THREAD

**Issue by dsghi** [MicrosoftDocs/OfficeDocs-SharePoint#2090]
0x01110010
0x0111000F

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05218c9e-0104-3116-2f0e-b5a53b2c9b75
* Version Independent ID: b680d4fa-78e9-6a3d-cd3e-0686c187018d
* Content: [Troubleshooting Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-troubleshoot)
* Content Source: [migration/mm-troubleshoot.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-troubleshoot.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@dsghi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@dsghi thank you for reaching out and helping improve MS Docs. @JoanneHendrickson are these two error codes still to be updated here?

**Comment by scanum** [comment]
@JoanneHendrickson could you kindly help?

**Comment by lindspea** [comment]
Any update yet @JoanneHendrickson

**Comment by JoanneHendrickson** [comment]
Added error codes. publishing shortly.
