### ISSUE TITLE
How does scripting affect cross-site copy?

### ISSUE THREAD

**Issue by dsghi** [MicrosoftDocs/OfficeDocs-SharePoint#2092]
Support pages from both [OneDrive](https://support.microsoft.com/en-gb/office/copy-files-and-folders-between-onedrive-and-sharepoint-sites-67a6323e-7fd4-4254-99a8-35613492a82f?ui=en-us&rs=en-gb&ad=gb) and [SharePoint](https://support.office.com/en-us/article/move-or-copy-files-in-sharepoint-00e2f483-4df3-46be-a861-1f5f0c1a87bc) regarding file copying/moving between sites reference this page for administrators to manage cross-site copy/move. However, it's not clear on this page if we need to enable or disable scripting as the method of enabling or disabling cross-site file copy/move.

The only reference on this page to cross-site copying is in the "Important" box for sites "set up for your organization before 2015" ... And it has a circular reference back to the link above regarding how to copy files between OneDrive and SharePoint. 😢

Further, there is no information in the list of features affected when custom scripting is blocked referring to cross-site copying.

So, is there a relationship between custom scripting and cross-site file copy/move?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@dsghi thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
