### ISSUE TITLE
SharePoint 2019 with Azure SQL Managed Instance

### ISSUE THREAD

**Issue by IGotKids** [MicrosoftDocs/OfficeDocs-SharePoint#2097]
Unable to create SharePoint Content/Service application databases without using the SQL MI Account. I followed the limited instruction here: https://docs.microsoft.com/en-us/sharepoint/administration/deploy-azure-sql-managed-instance-with-sharepoint-servers-2016-2019

Is this be design?

**Comment by scanum** [comment]
@IGotKids thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
