### ISSUE TITLE
OneDrive- Silent Account Configuration

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SharePoint#2098]
This Article mentions "If you federate your on-premises Active Directory with Azure AD, you must use AD FS to enable this feature." You should provide more clarity there, such as : 
1. Does that mean that if we have ADFS in our environment then we don't need to setup this GPO Settings?
2. Do we need to have Hybrid AD Joined devices even if we have ADFS in our environment?
3. If Hybrid AD Joined config and Silent account config GPO is not required, Then what kind of configuration is needed on ADFS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@3novsan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
