### ISSUE TITLE
How is the call made to get the Azure Container and Queue? 

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-SharePoint#21]
Hi,
I would like to know as to how this call could be made. This document doesn't seem to mention that. 

It just says, 'public SPProvisionedMigrationContainersInfo ProvisionMigrationContainers()'

Is it made on powershell, C# or VB.Net?

And module or library is required to make that call?

Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c396fc-dea7-68ba-5da3-93829c26b4d4
* Version Independent ID: c1140964-4128-1475-64a9-deca4ef855ea
* Content: [SharePoint Online provided Azure containers and queues for SPO Migration API](https://docs.microsoft.com/en-us/sharepoint/migrate-to-sharepoint-online/sharepoint-online-provided-azure-containers-and-queues-for-spo-migration-api)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/sharepoint-online-provided-azure-containers-and-queues-for-spo-migration-api.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/sharepoint-online-provided-azure-containers-and-queues-for-spo-migration-api.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@haneef95 - sorry for the delay on this. We will look into how the call can be made and get this into the document for clarification. Thanks for the time to submit this. You are making the documentation better and it is greatly appreciated!

**Comment by kenwith** [comment]
@haneef95 - sorry for the delay. I found the product team for this and am getting this answered and clarified. Sorry for the long delay.

**Comment by killerewok2000** [comment]
Hi this call can be made in C#. You can do it through sharepoint client side object model

**Comment by kenwith** [comment]
@killerewok2000 - thanks for the info! I added a note with this Pull Request. Looks ok to merge?

**Comment by kenwith** [comment]
@haneef95 - merged, thanks all!
