### ISSUE TITLE
SilentConfig Issues

### ISSUE THREAD

**Issue by Farandinio** [MicrosoftDocs/OfficeDocs-SharePoint#210]
Hello, I'm trying to use this GPO to get OneDrive to auto sign in, but I cannot get it to work. 

Please advise on what my next steps should be! 

Thanks!

**Comment by AndreaBarr** [comment]
@Farandino - thank you for submitting feedback. 

Thank you reaching out to us. Support will be able to handle this case and escalate it to resolution. I want to make sure this gets resolved and the issues in GitHub are for the documents.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
