### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2100]
Site permissions: Use Remote Interfaces
It might be a good idea to explain here what remote interfaces are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
> Site permissions: Use Remote Interfaces
> It might be a good idea to explain here what remote interfaces are.

Hello @hwkwicre !
How are you ?
The explanation is already included in the article:

> Use Simple Object Access Protocol (SOAP), Web DAV, or SharePoint Designer interfaces to access the website.

Thanks

**Comment by scanum** [comment]
@hwkwicre  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
