### ISSUE TITLE
Put a link to the UserVoice entry for this one so people can get an update

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/OfficeDocs-SharePoint#2101]
Add a link on the page to https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/13217277-enable-renaming-the-site-collection-urls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@trajano Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @trajano Archimedes How are you? We value your feedback, however, Docs articles do not include references to direct uservoice articles. People is directly referenced to the uservoice main site to look and vote for suggestions. Thanks

**Comment by scanum** [comment]
@trajano  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
