### ISSUE TITLE
OneDrive.admx file is broken

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/OfficeDocs-SharePoint#2102]
the onedrive.admx file supplied with version 19.222.1110.0011 doesn't work in either GPMC or GPEdit because of an error at Line 337 column 308, i.e. 

`  <policy name="LocalMassDeleteFileDeleteThreshold" class="Machine" displayName="$(string.LocalMassDeleteFileDeleteThreshold)" explainText="$(string.LocalMassDeleteFileDeleteThreshold_help)" presentation="$(presentation.LocalMassDeleteFileDeleteThreshold_Pres)" key="SOFTWARE\Policies\Microsoft\OneDrive">`

It looks the same as similar values, but GPMC/GPEdit don't like it, and stops the user from seeing any of the OneDrive GPO settings

**Comment by scanum** [comment]
@loaderladdy thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
