### ISSUE TITLE
example URL is not working - https://microsoft-my.sharepoint.com/personal/user1_contoso_com

### ISSUE THREAD

**Issue by nvgni** [MicrosoftDocs/OfficeDocs-SharePoint#2103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@nvgni Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@nvgni How are you? The sample url is not intended to be browseable. Thanks

**Comment by scanum** [comment]
@nvgni  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
