### ISSUE TITLE
the command is not woring

### ISSUE THREAD

**Issue by nvgni** [MicrosoftDocs/OfficeDocs-SharePoint#2104]
[Enter feedback here]
when i use this command , I am getting the below errror

> `Set-SPOSite : https://xxx-my.sharepoint.com/personal/xx_xx_xx_com is a OneDrive for Business site collection. The only valid parameters for this type
of site collection are '-Identity', '-AllowDownloadingNonWebViewableFiles', '-AllowEditing', '-ConditionalAccessPolicy', '-DefaultLinkPermission',
'-DefaultSharingLinkType', '-DisableCompanyWideSharingLinks', '-LimitedAccessFileType', '-LockState', '-Owner', '-SharingAllowedDomainList', '-SharingBlockedDomainList',
'-SharingCapability', '-SharingDomainRestrictionMode', '-ShowPeoplePickerSuggestionsForGuestUsers', '-StorageQuota', and '-StorageWarningLevel'.
At line:1 char:1
+ Set-SPOSite -Identity "https://xx-my.sharepoint.com/personal ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetSite`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@nvgni thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
