### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#2105]
Is there a way to deploy a list site design (or apply one) without SP Tenant Admin or Global Admin rights? Such as SCA or Owner? PowerShell connection is to the tenant, but even REST SP Context gets access denied when trying to add the template (I can GET templates however)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd09eee5-c545-e689-1194-e6b6cd70d63c
* Version Independent ID: 81523a20-4bed-a41c-9f5e-e5b5200d2f75
* Content: [Set up a site design for your hub site - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/set-up-site-design-hub-site)
* Content Source: [SharePoint/SharePointOnline/set-up-site-design-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/set-up-site-design-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@eschrader thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by eschrader** [comment]
I used PnP templates.
$siteURL = "https://companyname.sharepoint.com/sites/contoso"
cd C:\users\User1\Desktop\
Connect-PnPOnline -Url $siteURL
$template = Read-PnPProvisioningTemplate -Path .\MyModernTemplate.xml
$template
$template.Lists
Save-PnPProvisioningTemplate -Template $template -Out .\template.pnp


Apply-PnPProvisioningTemplate -Path template.pnp -TemplateId TEMPLATE-BIGOLDIDHERE -Verbose
