### ISSUE TITLE
What do you mean by 'STS' and 'WSS' packages?

### ISSUE THREAD

**Issue by legendgod** [MicrosoftDocs/OfficeDocs-SharePoint#2107]
I have not seen the term 'STS' long time. Is it indicate SharePoint Team Server? 
Should the term ['STS' and 'WSS' packages] replaced by [Cumulative update packages]?

**Comment by scanum** [comment]
@legendgod thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
