### ISSUE TITLE
Phase 2 - References SQL VM image that is no longer available. 

### ISSUE THREAD

**Issue by PhilB-MSFT** [MicrosoftDocs/OfficeDocs-SharePoint#2108]
The existing Azure PowerShell is incorrect:

`$vm=Set-AzVMSourceImage -VM $vm -PublisherName MicrosoftSQLServer -Offer SQL2014SP1-WS2012R2 -Skus Standard -Version "latest"`

This results in the error: 
ErrorCode: PlatformImageNotFound
ErrorMessage: The platform image 'MicrosoftSQLServer:SQL2014SP1-WS2012R2:Standard:latest' is not available. Verify that all fields in the storage profile are correct.

If you do want to use SQL Server 2014 images, you should use the latest Service Pack:

`$vm=Set-AzVMSourceImage -VM $vm -PublisherName MicrosoftSQLServer -Offer SQL2014SP3-WS2012R2 -Skus Standard -Version "latest" `

**Comment by scanum** [comment]
@PhilB-MSFT Hi Phil, thanks for your feedback. Could you link the article you are referring to? Thanks!

**Comment by PhilB-MSFT** [comment]
My bad - I assumed that the issue linked to the page I was viewing. For the SQL docs I usually just go ahead and edit and create a PR, but thought there should be some sanity checks by the SP team in case there is an issue with using the Service Pack 3 image for some reason.

The docs page that references an image that is no longer available is [https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure#phase-2-add-and-configure-a-sql-server-2014-virtual-machine](url)

**Comment by scanum** [comment]
@PhilB-MSFT  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
