### ISSUE TITLE
Summary unclear

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/OfficeDocs-SharePoint#211]
The summary of this document is unclear. It states: "... The rule checks to see if the memory usage exceeds the allocated amount ...". First of all, it seems to me physically impossible that more memory is used than is allocated: memory that hasn't been allocated can't be used! So what does "usage" mean exactly? Also, the rule name suggests that this is about the total memory of the server. However, when I read the documentation, I get some hints the alert might be about the memory that is assigned to the distributed cache. The summary should address very clearly what memory is meant when it says "... memory usage has exceeded ..." and "... allocated memory ...". Furthermore, the summary mentions: "If it finds the memory usage has exceeded the allocated amount then it triggers an alert.". For diagnostic purposes and to clearly understand what is going on, it would be very helpful if the remainder of the article would describe how the memory usage is measured by the rule (so a sysadmin can reproduce the finding) and also what the consequences are that the memory is low (i.e., is there a way to see the effects this low memory condition causes, e.g. can the sysadmin measure a large number of cache evicts of see symptoms of users repeatedly having to log on to the system or social feeds that are emptied out etc.?) The latter is useful to determine if additional memory is actually needed and to calculate the desired size of the memory allocated to the distributed cache.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71ece67-7cf9-6bba-7dcf-09421927b801
* Version Independent ID: 0659431d-9739-c62d-760b-8ab11dbc84ed
* Content: [The current server is running low on memory (SharePoint Server)](https://docs.microsoft.com/en-us/SharePoint/technical-reference/the-current-server-is-running-low-on-memory)
* Content Source: [SharePoint/SharePointServer/technical-reference/the-current-server-is-running-low-on-memory.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/the-current-server-is-running-low-on-memory.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by niderost** [comment]
I have found the following blog post that elaborates a bit on what is going on: https://www.c-sharpcorner.com/uploadfile/roji.joy/understanding-and-configuring-the-distributed-cache-in-share/ 
From this blog post I hypothesize that following:
"The current server is running low on memory" -> memory = total physical memory assigned to the distributed cache service = 2 times the value set with "Update-SPDistributedCacheSize -CacheSizeInMB CacheSize"
"memory usage" -> the total memory that is currently used for caching items in the cache service (= data storage)
"allocated amount" -> the value set with memory configured with "Update-SPDistributedCacheSize -CacheSizeInMB CacheSize" = half the total physical memory assigned to the distributed cache service.
"exceeds" -> cache items are now stored in the part of the physical memory that is normally used by the distributed cache service for data management purposes, which isn't a healthy situation in the long run.

**Comment by AndreaBarr** [comment]
@niderost Thank you for this feedback.

I want to make sure these statements gets clarified. I am going to get this over to the SharePoint team to that they can address this appropriately. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by tseward** [comment]
@niderost This health analyzer rule doesn't have the best wording. The check flows like this:

1. Check the current percentage of memory load. We use the [GlobalMemoryStatusEx](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex) Win32 API to return the memory load percentage.

2. If the returned value is 85% or higher, the health analyzer rule throws an error.

So this particular rule doesn't look at the memory used by any one particular process but rather the overall memory usage in the system.

I'm not sure if there is a good spot in the HA articles to go into the details about the internal rules (very few would technically care about what Win32 API was being called, etc. :)) so I'm going to exclude that for now. As far as symptoms, what ends up happening is items in the AppFabric cache begin being evicted prior to their typical expiration. While this may have no apparent impact, especially on smaller farms, there may be other consequences that do appear, such as a slow response for end users.

As an aside, you can adjust the trigger value yourself via PowerShell!
```PowerShell
$server = Get-SPServer SPServerName
$server.CacheHostApproachingThrottlingThresholdPercentage = 60
$server.Update()
```

**Comment by niderost** [comment]
Thank you for the detailed analysis. I agree that there isn't a clear spot in the HA articles to go into these details. I would argue however that the summary of the article is wrong when it states: 

"The rule checks to see if the memory usage exceeds the allocated amount for a server that hosts the Distributed Cache service. If it finds the memory usage has exceeded the allocated amount then it triggers an alert."

Instead, a summary like the following would seem more correct:

"The rule checks to see if the current server memory usage exceeds 85% of the total amount allocated to a server that hosts the Distributed Cache service. If it finds the memory usage has exceeded the threshold then it triggers an alert."

**Comment by AndreaBarr** [comment]
It looks like this was resolved by Trevor. I am going to close this as resolved. If this issue is not resolved please re-open this issue.
