### ISSUE TITLE
No IPs Provided

### ISSUE THREAD

**Issue by FadelH** [MicrosoftDocs/OfficeDocs-SharePoint#2112]
Hi team,

We need to whitelist mover's IPs but I can't find these is the article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655d8e8e-ff4d-ad9a-4962-417499d583f6
* Version Independent ID: 1b333710-811a-4fdd-d51f-81e3f9027135
* Content: [How to Migrate from On-premises file shares to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-fileshare-to-o365)
* Content Source: [migration/mover-fileshare-to-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-fileshare-to-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@FadelH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@JoanneHendrickson is it possible to get those IP ranges needed for mover's migration? Thanks

**Comment by JoanneHendrickson** [comment]
this article has been retired. See Migration Manager for file share migration.
