### ISSUE TITLE
SharePoint Migration Tool support

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#2113]
Please add clear indication that the tool contains many bug and there is no support and no fix from Microsoft (es. some lists copied with wrong data for all versions of the tools).  I try also some MS official forum and other methods but not have any answer on bug that I have. After eight months!! no solution/no improvements. Also missing sp2019 support.
So it's neeed to use other pay tools for real migrations that works fine and have support for problems/bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - SharePoint Online - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Hi @paololec, thanks for your feedback. I will communicate it to our team.
