### ISSUE TITLE
How to change the language for the e-mails sent out from shares

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/OfficeDocs-SharePoint#2114]
If you share a document, it sends an email to the person the document is shared with. In the wrong language.
How do you change the language of the e-mails sent out?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3106844b-caae-38c5-3c88-fb17a9d67536
* Version Independent ID: 3e88e60e-24a3-cd83-9bfc-8bc3037a86ce
* Content: [Change the external sharing setting for a site - SharePoint Online](https://docs.microsoft.com/en-US/sharepoint/change-external-sharing-site)
* Content Source: [SharePoint/SharePointOnline/change-external-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-external-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@richard-artes I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
