### ISSUE TITLE
Please update this document concerning if this feature is supported for Office package on MAC.

### ISSUE THREAD

**Issue by HansGrunberg** [MicrosoftDocs/OfficeDocs-SharePoint#2115]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@scanum Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @HansGrunberg How are you?
I am not sure if I understand, an org assets library allows you to define a central location for images or logos, was this the topic you wanted to create an issue against to? Thanks for clarification.

**Comment by HansGrunberg** [comment]
Hi

I wanted the documentation updated to clarify that the organizational assets for Office templates is not supported on MAC clients yet.

Info from Microsoft incident:
Case #:20152309
"I've receive the information from the team
Saying that this is a new feature which is not yet rolled out to public audiences on Mac.
Currently we still don't have dates for when it will be available on Mac due to the restrictions on new features which require SPO integration."

Regards

Hans

**Comment by get-itips** [comment]
Thanks for adding some more information @HansGrunberg Hans.

@kaarins Do you have confirmation from your side about what @HansGrunberg says here? thanks

**Comment by scanum** [comment]
@kaarins Following up on this issue. Thanks!

**Comment by kaarins** [comment]
Mac support is available in targeted release and will be coming to standard release shortly.

**Comment by scanum** [comment]
@HansGrunberg  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
