### ISSUE TITLE
What are the available Intune Policies for OneDrive

### ISSUE THREAD

**Issue by iburg** [MicrosoftDocs/OfficeDocs-SharePoint#2116]
Please add the available Intune policies for OneDrive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#require-users-to-confirm-large-delete-operations)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@iburg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
@iburg thank you. We're working on this! (Long overdue, I know)

**Comment by kaarins** [comment]
This new article describes how you can use Administrative Templates in Intune to configure all the settings in the .admx file that you previously configured in the Group Policy Management Editor: https://docs.microsoft.com/en-us/onedrive/configure-sync-intune
