### ISSUE TITLE
Need to be more specific

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#2117]
docs page report:
"However, during evening and weekend hours for the region, the service will be ready to process a significantly higher volume of requests from background apps."

Please specify more details, example:
-in europe region evening (from 6pm to 8am), weekend (saturday,sun).
-higher volume of request (throttling is active or not during evening ?): I want details similar as expect at least/minimal 10GB/hour for small files (~50 kb) and 200 request/second for list items with 20 columns mixed typed.

Please add also throttling details (if are dynamic do a statics page of last month with timerange, so everyone can known the "normal" range supported of request). For example I know if I delete more that 150 item in a list it's go into error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ed221a-ca52-7a6a-4b89-1417066ffcbd
* Version Independent ID: e7fdb3a0-c148-85d1-48cf-57998d190a8a
* Content: [Migration performance guide for SharePoint & OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-online-and-onedrive-migration-speed)
* Content Source: [migration/sharepoint-online-and-onedrive-migration-speed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-online-and-onedrive-migration-speed.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Hi @paololec Thanks for your feedback. We will consider adding this.
