### ISSUE TITLE
Preprovision Code Incomplete

### ISSUE THREAD

**Issue by Sekers** [MicrosoftDocs/OfficeDocs-SharePoint#2118]
The sample PowerShell code does not provision oneddrive for users if it there are fewer than 200 or for the last x number of users above a multiple of 200.

This command needs to be run one more time after the foreach loop finishes:

Request-SPOPersonalSite -UserEmails $list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization - OneDrive](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by Sekers** [comment]
I also recommend adding in some verification code such as the following:

$provisioned_accounts_list = Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.sharepoint.com/personal/'" | Select-Object -ExpandProperty Url
Write-Host Count is $provisioned_accounts_list.count
Write-Host $provisioned_accounts_list -Separator ([environment]::NewLine)

**Comment by scanum** [comment]
@Sekers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @Sekers will propose to improve the script thru a pr
