### ISSUE TITLE
Multi-user clients and Transition from the Windows Folder Redirection

### ISSUE THREAD

**Issue by nielsranosch** [MicrosoftDocs/OfficeDocs-SharePoint#2121]
Hi!

While I agree with the general idea of using a background copy job for migrating from a Folder Redirection scenario to OneDrive, there seems to be a design gap when multi-user clients are in use. The main cause for these issues is that OneDrive's KFM GPO settings are machine settings, although they should be user settings. 

For example: If "Silently move Windows known folders to OneDrive" (KFMSilentOptIn) is set, then the known folders of all users using the machine will be moved to OneDrive, even if some of the users are not yet ready to be moved. This could be avoided by providing the setting / registry key "KFMSilentOptIn" as a user setting instead of a computer setting.

If providing a user setting is not realistic at this time, what is the proposed approach for migrating from a scenario with mutli-user clients and folder redirection to OneDrive?

Thanks in advance!
Niels Ranosch

For reference: The instructions for Folder Redirection have first been added by in commit https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/f0382cee0bea578b87d279f55b4dd37ec59f3ba1. Thank you to @cartergreen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@nielsranosch Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
