### ISSUE TITLE
Change a site address documentation of Recent lists misleading

### ISSUE THREAD

**Issue by ChristianGalla** [MicrosoftDocs/OfficeDocs-SharePoint#2122]
Hello,

I think the following paragraph should be extended or a new one created:

> **Recent lists in Office apps**<br>
> The Word, Excel, and PowerPoint desktop apps and apps for the web will show the new URL after the change. 

Updated is only the recent list in the home screen **inside** the app. If you for example right click on the app in the taskbar, there is still the old location linked in the list of pinned or recent opened files. If you try to open such a link, for example Excel is prompting that it is unable to open the file because it was moved to a new location.

Ideally, the application should open the file from the new location, but until this is implemented, I think the documentation should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ChristianGalla  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks @ChristianGalla Christian for reporting, will propose clarifying this thru a pr.
