### ISSUE TITLE
Records Management

### ISSUE THREAD

**Issue by causeway74** [MicrosoftDocs/OfficeDocs-SharePoint#2123]
Can you please add some clarity on the records management feature. Does this preserve record declaration settings in the target? Do files need to be undeclared as records in advance of migration? Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c911d1d-3570-6e0a-cfa7-77b7516a1f55
* Version Independent ID: 261252f1-7191-5be9-a735-cdb307b72a7c
* Content: [New and improved features in the SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-gb/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool)
* Content Source: [migration/new-and-improved-features-in-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/new-and-improved-features-in-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@causeway74  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@JoanneHendrickson How are you? Can we get some more information about records management to expand this article?

**Comment by JoanneHendrickson** [comment]
Sorry for the delay.  I am researching with the product team and will get back to you shortly.

**Comment by JoanneHendrickson** [comment]
updated doc with clarification surrounding the limitations of support.   Support for SharePoint Server migration of Record libraries with limitations. Library record declaration settings are supported for SharePoint Server 2013 and 2016 only. Files declared as recrods can be migrated directly.  Site collection record declarations settings are not supported for SharePoint Online group sites and communication sites.
