### ISSUE TITLE
missing commas in example json

### ISSUE THREAD

**Issue by neiljackson1984** [MicrosoftDocs/OfficeDocs-SharePoint#2125]
The example json content is not valid json; several commas are missing, there is an extra comma, and the the backslashes in the strings are not escaped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [How to format a CSV or JSON file for bulk upload in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@neiljackson1984  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lancegosby** [comment]
There are also duplicate `MigrateOneNoteNotebook` properties

**Comment by get-itips** [comment]
Thanks for your feedback, tried the current JSON, fixing it thru a pr.
