### ISSUE TITLE
bad link: Configure and deploy mobile application management policies in the Microsoft Intune console

### ISSUE THREAD

**Issue by beaucoup1980** [MicrosoftDocs/OfficeDocs-SharePoint#2126]
link: Configure and deploy mobile application management policies in the Microsoft Intune console (https://go.microsoft.com/fwlink/?linkid=2003554) 

resolves to a 404: https://docs.microsoft.com/en-us/intune/deploy-use/configure-and-deploy-mobile-application-management-policies-in-the-microsoft-intune-console

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb73e568-9145-abd7-a0fe-4b03bdb875ee
* Version Independent ID: 8036cdd2-2877-e9cd-2878-04121ab9666c
* Content: [Control access to features in the OneDrive and SharePoint mobile apps - OneDrive](https://docs.microsoft.com/en-us/onedrive/control-access-to-mobile-app-features)
* Content Source: [OneDrive/control-access-to-mobile-app-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-to-mobile-app-features.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@beaucoup1980  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your report @beaucoup1980
