### ISSUE TITLE
Nice Article

### ISSUE THREAD

**Issue by mbadruddin** [MicrosoftDocs/OfficeDocs-SharePoint#213]
Nice article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24b1046-9f65-1067-9f7c-d6bcbd37d705
* Version Independent ID: 819ca362-f0c1-f3ab-d872-c8d09bac92dc
* Content: [Create a web application in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/create-a-web-application)
* Content Source: [SharePoint/SharePointServer/administration/create-a-web-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/create-a-web-application.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@mbadruddin thank you for your feedback.
