### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2135]
To run the report (OneDrive)
Open OneDrive.
On the Settings menu, click OneDrive settings.
Click More settings, and then click Run report.
Choose a location to save the report, and then click Run report.

I tried it, it's actually "Run sharing report" instead of "Run report".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharing-reports)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks @hwkwicre
