### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2136]
When I click the link to SharePoint Framework on this page, my browser says "can’t reach this page".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdc8c01-4004-138d-87fa-4f02d90ab7b9
* Version Independent ID: fa05c817-1441-39d3-5cda-103df2a1d0d1
* Content: [Security considerations of allowing custom script - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/security-considerations-of-allowing-custom-script)
* Content Source: [SharePoint/SharePointOnline/security-considerations-of-allowing-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/security-considerations-of-allowing-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @hwkwicre 
I couldn't repro, tried all links in the referenced article. Can you check? Thanks

**Comment by hwkwicre** [comment]
The SharePoint Framework is a page and web part model that provides a governed and fully supported way to build solutions using scripting technologies with support for open source tooling.
There's a link for "SharePoint Framework" and it's broken

**Comment by get-itips** [comment]
Ok a fix is on the way, thanks
