### ISSUE TITLE
Missing notes?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2137]
The first Note doesn't contain anything.
And what is this?
<<<<<<< Updated upstream

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30bdf1cb-df3d-0f43-fc43-430127678f06
* Version Independent ID: a78f502b-2f2a-7333-d22e-864990153758
* Content: [Let users connect classic team sites to new Microsoft 365 groups - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/let-users-connect-classic-sites-to-groups)
* Content Source: [SharePoint/SharePointOnline/let-users-connect-classic-sites-to-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-connect-classic-sites-to-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @hwkwicre
