### ISSUE TITLE
Why don't I have Content services in my SharePoint admin center?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2138]
I'm using the new SharePoint admin center (not the classic version) and the left navigation only has Home, Sites, Policies, Settings, Migration, Advanced, and More features. Term store is under More features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede0b3b6-c209-a6ed-9374-23a2cc9b010c
* Version Independent ID: d5f088d4-97f7-ba69-e5f5-5f51a081983e
* Content: [Open the Term Store Management Tool - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/open-term-store-management-tool)
* Content Source: [SharePoint/SharePointOnline/open-term-store-management-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/open-term-store-management-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@hwkwicre the new term store user interface is currently rolling out. You should see it soon.

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback. We understand that this issue has been resolved and an update will be made soon.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
