### ISSUE TITLE
Question about the site URL already in use

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2139]
I wonder if it would be a good idea to put what happens when the Relative URL to be used for the site is already used, for example:

Site URL already in use
The URL provided is already in use and the target site is based on a template that is not valid for the current package. Please provide a different URL.

Does that mean if the target site is based on a template valid for the current package it will be able to replace whatever is on the old site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524a79c8-760d-3141-9840-17fc7d55c279
* Version Independent ID: 2681ae66-d048-5c2e-6bdb-3c6b7e4bb7ba
* Content: [Add a sample site to your tenant - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/add-sample-site)
* Content Source: [SharePoint/SharePointOnline/add-sample-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/add-sample-site.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
