### ISSUE TITLE
OneDrive Personal

### ISSUE THREAD

**Issue by kajirashad** [MicrosoftDocs/OfficeDocs-SharePoint#214]
Is there same instruction for a different type of account (i.e. personal instead of business).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
This documentation is for the business version only. Personal does not have these management capabilities.

**Comment by AndreaBarr** [comment]
@kajirashad Thank you for your feedback.

From my understanding your questions has been answered about the business and personal account versions. If the issue is not resolved please re-open this issue.
