### ISSUE TITLE
Root site?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2140]
Is there any difference between home site and root site, or are they just the same thing?
If they're different, can this article add some explanations on their difference?
Because this article as well as other ones have mentioned "root site".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hwkwicre** [comment]
That was a question about an article, not my tenant though.
