### ISSUE TITLE
Regarding "Filter lists and libraries" in SharePoint Migration Tool

### ISSUE THREAD

**Issue by deepayan21** [MicrosoftDocs/OfficeDocs-SharePoint#2141]
How do I separate multiple lists and libraries? Using a comma or a semi-colon or something else? For example, while migrating a SP 2010 site, I want to exclude the "Documents" and "Site Pictures" libraries. How do I specify it in the "Filter lists and libraries" box? What is the delimiter we have to use to separate more than 1 list?

**Comment by scanum** [comment]
@deepayan21 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
