### ISSUE TITLE
Needs update?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/OfficeDocs-SharePoint#2145]
On the Site Settings page, under Users and Permissions, there's only Access requests and invitations. There aren't all the things talked about in this page, and I believe you need the direct URL to go in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e8d0f1-f6a3-82c0-e46b-974e167fe5b1
* Version Independent ID: 22b0a6c2-2e90-34ab-c3c8-bd7ba721c791
* Content: [Customize SharePoint site permissions - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions)
* Content Source: [SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@hwkwicre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your report @hwkwicre
