### ISSUE TITLE
Link to CSV missing

### ISSUE THREAD

**Issue by Silversurfer79** [MicrosoftDocs/OfficeDocs-SharePoint#2146]
[Enter feedback here]

The link to the CSV is missing,
![image](https://user-images.githubusercontent.com/58236890/84880986-2c624c80-b085-11ea-974c-3755a53e918e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 705f89ed-97f2-cb71-28f7-c35f55cce879
* Version Independent ID: c6b41e73-0db7-89ff-59cb-84d51df02394
* Content: [Migrating from Box to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-box-to-o365#users-to-migrate)
* Content Source: [migration/mover-box-to-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-box-to-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by Silversurfer79** [comment]
Adding in all the migration paths into the CSV as examples would be helpful,

Source Path,Destination Path,Tags
user1@example.com,user__1@corp.example.com,"Pilot, IT"
user2@example.com,user__2@corp.example.com,"Pilot, Sales"
user3@example.com/src dir,user3@example.com/migrated,"Pilot, IT"
Source Shared Drive,user4@example.com/Team Folder,"Pilot, Sales"
https://TENANT02.sharepoint.com/sites/SiteName/Shared%20Documents,user5@example.com,"Marketing, Sales"

**Comment by scanum** [comment]
@Silversurfer79 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Silversurfer79 How are you?
The article you opened the issue for as been replaced, you can find more information here

https://docs.microsoft.com/en-us/sharepointmigration/mover-box
https://docs.microsoft.com/en-us/sharepointmigration/mover-create-migration-csv

content index https://docs.microsoft.com/en-us/sharepointmigration/mover-plan-migration

Hope this helps you,

**Comment by scanum** [comment]
@Silversurfer79  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
