### ISSUE TITLE
Issue when setting this up and using as an external user

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/OfficeDocs-SharePoint#2147]
**Configure custom PNP Search page on SharePoint site (access via external account)**
Hi - 

Wondering if anyone can help. I have created a PNP search page on my SharePoint site & configured the search settings so that when a user searches when on the site they land on the PnP search results page rather than the native default of Microsoft Search.

This works, however, when I access as an external user, the search functionality defaults back to default & lands back on the default Microsoft search page. Can anyone help me?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50867596-18e6-b132-b8fb-5f51563d5944
* Version Independent ID: 1150103d-949d-5bd2-7c90-9281f1158e8e
* Content: [Specify search settings for a site collection or a site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/override-default-search-center)
* Content Source: [SharePoint/SharePointOnline/override-default-search-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/override-default-search-center.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@nathanwlee1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nathanwlee1** [comment]
@scanum Ok thanks, I have just raised a ticket. Will keep you updated.
