### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by jholl016** [MicrosoftDocs/OfficeDocs-SharePoint#215]
The section on 'Silently Redirect Windows Known Folders to OneDrive' seems to contradict itself. I can't make any sense of how it's intended to work.  First, there's these 2 statements:

> This setting lets you redirect your users' Documents, Pictures, and Desktop folders to OneDrive **without user interaction**.

and
> We recommend using this policy together with "Prompt users to move Windows known folders to OneDrive."

Why would I want to use the "Prompt users" policy if my intention is to do something "without user interaction"?  If I'm prompting the user for anything, then it's not silent.  Hence, this instruction makes no sense.

Secondly, there's the issue of whether known folders must be empty or not for this policy to work.  The description contains these 2 conflicting instructions:
> This policy works when all known folders are empty...

and

> When you enable this policy, future releases will no longer check for empty known folders. Instead, known folders will be redirected and content within them will be moved.

So, which is it?  Is this a redirection that only works on empty folders, or does it move existing content from the current known folder location into the OneDrive target?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#SilentConfig)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jholl016 Thank you for you feedback. 

I want to make sure you get the clarification you need for these installation options.  

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by llacefield** [comment]
@jholl016

Was this ever cleared up? This is very much the same issue for our organization.
I have a GPO setup to do the following but not redirecting folders silently.

**Comment by kaarins** [comment]
@jholl016 @llacefield We made an update to this policy in build 18.171.0823.0001. Before this build, the policy only redirected empty known folders, so you needed to use it in conjunction with "Prompt users to move Windows known folders to OneDrive." Now, this policy redirects AND moves content. If you enable both policies, the content will be moved silently, but if the silent move fails, the user will be prompted. I hope this helps!
