### ISSUE TITLE
Sharepoint groupid=0

### ISSUE THREAD

**Issue by MeshDigital** [MicrosoftDocs/OfficeDocs-SharePoint#2155]
Dears

It would be great if there would be a PowerShell cmdlet that would allow to get all the users from a SharePoint that can be found via groupid=0.
Getting an overview of all users that are known on a site this way is quite valuable.

Kr 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50aa0393-41e2-de3b-4380-74bf012a7914
* Version Independent ID: 09b51e37-62d7-01f8-9d34-723b03b8ee80
* Content: [Remove deleted users from SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/remove-users)
* Content Source: [SharePoint/SharePointOnline/remove-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/remove-users.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@MeshDigital I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
