### ISSUE TITLE
To which SharePoint objects does this apply?

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SharePoint#2157]
Per the article, "invitations to **a SharePoint site** use Azure AD B2B..." Does this mean that invitations for other object types (e.g., file, folder, list, library, page) do NOT use Azure AD B2B auth when this integration is enabled? When I tested this with the one-time passcode feature, the behavior was as described for all objects EXCEPT for sites....which still prompt guest users to sign in with or create a Microsoft account.

**Comment by scanum** [comment]
@jmuehlenbein Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jmuehlenbein** [comment]
I did open a case only to discover I was not able to reproduce the unexpected behavior. So essentially, I've verified that enabling the Azure AD B2B auth integration (in addition to the One-time Passcode/OTP preview) allows ANY SharePoint object (e.g., file, folder, list, library, page OR site) to be shared via OTP. So there you have it.
