### ISSUE TITLE
Update for 2019

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/OfficeDocs-SharePoint#216]
Looks like there were some slight UI changes in the My Site Settings page for 2019. The steps above for that section don’t match. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852df3ef-cbca-40ff-b438-1856a499c46c
* Version Independent ID: 490ddd82-19b5-559d-4ba1-d9eb62492576
* Content: [Configure My Sites in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/install/configure-my-sites)
* Content Source: [SharePoint/SharePointServer/install/configure-my-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/configure-my-sites.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Techwriter40** [comment]
updated by @tseward in other PR
