### ISSUE TITLE
Where do i trouble shoot login problems?

### ISSUE THREAD

**Issue by brunis** [MicrosoftDocs/OfficeDocs-SharePoint#2161]
[Enter feedback here]
I just manually logged into my hosted sharepoint, but when i try to connect the migration tool, it keeps insisting the same login credentials are invalid. I can connect to the localhost:xxxx Admin site though.. but i'm not really interested in migrating the Admin site :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Dennis:  Can you contact me directly at jhendr@microsoft.com ?  We can help troubleshoot this for you.   Joanne

**Comment by killerewok2000** [comment]
Hi @brunis  i am the Senior PM for the Migration Tool. 
We would like to investigate further with you what  is happening there. 

can you send an email to migrationuservoice@microsoft.com. we would like to have a bit more details and hopefully unblock you and potentially others in the same situation. 

Simon

**Comment by scanum** [comment]
@brunis We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by sswitzermyra** [comment]
I'm having the exact same problem as @brunis 

I'm running SPMT on a Windows server, needing to access my SP 2013 site as localhost. When asking to connect to my site as http://localhost/ I'm getting "Please re-enter your user ID or password". Note that the same login to localhost using Chrome or IE works just fine.
![image](https://user-images.githubusercontent.com/99300211/153099190-e00fc200-cb6c-4d8e-b9d5-67c8d58e7adc.png)

Can this issue be re-opened?
