### ISSUE TITLE
Info graphic in "The OneDrive deletion process" is not accurate

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/OfficeDocs-SharePoint#2162]
Info graphic states that within the first phase only PowerShell can recover the OneDrive after 30 days, regardless of OneDrive service retention setting. However, the OneDrive URL is still available for what ever retention policy that is defined within the OneDrive service. PowerShell comes into play once it is in the 3rd phase "Recycle Bin". However, PowerShell is mentioned in the first phase.

The infographic does not match actual behavior and does not match the steps laid out above it in the "The OneDrive deletion process" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion - OneDrive](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SLeuthold  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SLeuthold** [comment]
Hi @scanum let me know if there are any updates. Trying to clarify this process with a few customers and I can imagine this could be confusing for the greater IT pro community. Thank you!

**Comment by scanum** [comment]
Hi @kaarins could you please help with this issue? Thanks!

**Comment by scanum** [comment]
@SLeuthold Hi Stephen! Thanks for checking with us. We are still working on this. We appreciate your patience.

**Comment by SLeuthold** [comment]
Thank you @scanum :)

**Comment by kaarins** [comment]
@WayneEwington should we simply remove the phrase "and the OneDrive can only be restored by using PowerShell"?

**Comment by WayneEwington** [comment]
@kaarins That would be the easiest solution :)

**Comment by WayneEwington** [comment]
Accidently removed myself as the assignee. Trying to reassign back to @kaarins

**Comment by kaarins** [comment]
The fix was published some time ago and I must have missed closing this!
