### ISSUE TITLE
Was this PowerShell command tested when the admin account has MFA enabled?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SharePoint#2163]
I am trying to work through this article for an account that has MFA enabled. the Global Admin account, and this command is failing. I do not understand why.

Remove-SPOUser -Site https://fabrikam.sharepoint.com -LoginName jondoe_fabrikam.com#EXT#@fabrikam.onmicrosoft.com

It would make sense that it should work the same as an account that does not have MFA enabled, but for some unknown reason it is failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50aa0393-41e2-de3b-4380-74bf012a7914
* Version Independent ID: 09b51e37-62d7-01f8-9d34-723b03b8ee80
* Content: [Remove deleted users from SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/remove-users)
* Content Source: [SharePoint/SharePointOnline/remove-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/remove-users.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by MikePlumleyMSFT** [comment]
@Jmartinez589 my guess is that you need to use the User Principal Name as shown in Azure Active Directory rather than the Username shown in the Microsoft 365 admin center.

**Comment by Jmartinez589** [comment]
I hear you, and that might make sense, but I am using an account that is an Office 365. I am testing this and find that I can add a member to a site. The account has no #EXT# extension, it's UPN matches the FQDN in Office 365. I'm simply trying to run the command as noted in the article and it fails. Maybe things have changed. I get that, but this article may need to be re-veted to ensure it still works as documented.

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
