### ISSUE TITLE
Unable to set storagequota due to automatic site storage management

### ISSUE THREAD

**Issue by 40-Cal-Banana** [MicrosoftDocs/OfficeDocs-SharePoint#2164]
As per this kb:

https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps

I am unable to follow this page due to:

If Site Collection Storage Management is enabled for the tenant, you will not be able to set quota and will have a generic error returned. To workaround this issue, set the site collection storage management to "manual" temporarily, set your quotas and then set the site collection storage management setting back to its original setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
