### ISSUE TITLE
OneDrive /getpin error

### ISSUE THREAD

**Issue by lgimyuen** [MicrosoftDocs/OfficeDocs-SharePoint#2168]
# BUG: 
`/getpin` produce this error and the file status icon is not shown in Finder.

`$ /Applications/OneDrive.app/Contents/MacOS/OneDrive /getpin /Users/username/OneDrive` 
`2020-06-29 12:16:07.204 OneDrive[37720:1054071] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
2020-06-29 12:16:07.246 OneDrive[37720:1054071] pin state=None`

**Comment by scanum** [comment]
@lgimyuen Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
