### ISSUE TITLE
Goot documentation

### ISSUE THREAD

**Issue by mksowmya** [MicrosoftDocs/OfficeDocs-SharePoint#218]
The documentation in precise and concise and helped in restoring the deleted one drive site. Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users](https://docs.microsoft.com/en-us/onedrive/set-retention)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kenwith** [comment]
@mksowmya - thanks for the feedback! Appreciated!
