### ISSUE TITLE
OneDrive and Limit Access policy with use of SharePoint Sensitivity Labels

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#2187]
Hello,

We have applied for protection in our tenant the solution that is Limiting download from unmanaged devices, those settings applied in the SharePoint Admin center for Unmanaged devices in the access control policy.
This, of course, limited all OneDrive and SharePoint sites and we have to work per site/user to remove limitation when/if users work with B2B/Guest on some project where the download is required.

Very soon, a new product will be under GA "https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide", this will allow applying Sensitivity label to SharePoint Site and remove the download limitation using Sensitivity Label, but, in order to do so, the access control policy in SharePoint Admin for Unmanaged devices, must be set as: "Allow full access...". If we do so, then CA polices will be turned off, of course, we can turn them back on, but then, because access control policy settings in SharePoint Admin for Unmanaged devices are set to "Allow full access...", then CA not applied, and of course, we can think about running PowerShell script that will run per user and set user Conditional Access Policy to Limited Access...

But how come that one solution force undo another solution?
What are plans now will be for OneDrive and Limit Access policy if we want to use Sensitivity Labels in SharePoint sites that force us to set control access policy as "Allow full access..."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@lightupdifire Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
