### ISSUE TITLE
Sentence duplication

### ISSUE THREAD

**Issue by jasperoosterveld** [MicrosoftDocs/OfficeDocs-SharePoint#2188]
This sentence is added twice in the global navigation summary: 

_Use a single hub for the entire organization. This might be a reasonable strategy for a small organization, but the benefits of hubs decrease in value if you only have one so this may not work for the long term._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Plan navigation for the modern experience in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by tomresing** [comment]
Hi @jasperoosterveld! Thanks so much for raising your first issue in this repo. I've reached out to the author since I recognized your name in the list of issues.

**Comment by Holland-ODSP** [comment]
Thanks @tomresing - @scanum I just submitted the edit.

**Comment by tomresing** [comment]
@jasperoosterveld your change is live. Thanks for your feedback!
