### ISSUE TITLE
Behavior for broken inheritance seems different than what's described

### ISSUE THREAD

**Issue by JeighBI** [MicrosoftDocs/OfficeDocs-SharePoint#2189]
Hi,

This is in reference to this paragraph:

> "**When a user shares or stops sharing an item that contains other items with broken inheritance, a one-time push down of that permission _addition or removal_ is sent to all child items, _even those with broken inheritance_**. This is true for both direct permissions and sharing links. When managing permissions for an item with broken inheritance, users are able to remove any direct permissions on it. If an item with broken inheritance is accessible by a sharing link that was created on one of its parent folders and a user does not want that link to grant access to the item, then users can either remove the link entirely or they can move the file outside of the folder for which sharing link has permissions."

First off, I was surprised to find that changing permissions at the site (parent) level had _any_ effect on a library with unique permissions. So, after reading this post, I performed some testing and found this behavior:

- ADDING a group at the site level did NOT add it to a library with unique permissions;
however...
- If the library was _already_ granting permissions to group A, and the site was also granting permissions to group A, then when I removed permissions for group A from the site, it would also remove group A from the library (even though it's not inheriting)

All of this was news to me, but based on my testing, only "removals" are sent to child items with unique permissions, not additions.

Thank you,

Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a18d328-f487-b16c-11d7-07bd63d88eb7
* Version Independent ID: 15445bd1-b63a-6fa3-a605-72d3e906aaf5
* Content: [What is permissions inheritance? - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/what-is-permissions-inheritance)
* Content Source: [SharePoint/SharePointOnline/what-is-permissions-inheritance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-is-permissions-inheritance.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@JeighBI Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JeighBI, thank you for your feedback.

I've verified with the PM and they said that this sentence is correct.

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by scanum** [comment]
@JeighBI Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
