### ISSUE TITLE
Message Center 145909 - Reg Keys

### ISSUE THREAD

**Issue by nz0n48** [MicrosoftDocs/OfficeDocs-SharePoint#219]
MC145909 - Updated feature: OneDrive for Business admin center setting is now honored
This message center item refers to erg keys being set previously to have Outlook honor this setting.  What were those reg keys?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a570bb-2567-565c-e9ff-bf1ccbf38d0e
* Version Independent ID: 3d342dea-9dd3-008c-20c6-902452302e95
* Content: [Manage sharing in OneDrive and SharePoint](https://docs.microsoft.com/en-us/onedrive/manage-sharing?redirectSourcePath=%252farticle%252fmanage-sharing-in-onedrive-and-sharepoint-ee8b91c5-05ec-44c2-9796-78fa27ec8425)
* Content Source: [OneDrive/manage-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/manage-sharing.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@nz0n48 Thank you for your feedback

I want to make sure you are able to get the correct reg keys. The support team will be able to handles this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
