### ISSUE TITLE
If you resubmit a job, will it purge files that have been deleted?

### ISSUE THREAD

**Issue by tommylux** [MicrosoftDocs/OfficeDocs-SharePoint#2191]

**Comment by tommylux** [comment]
I followed link to github from the Sharepoint Migration tool. I wondered when re-submitting a job, will it purge files that have been deleted?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tommylux** [comment]
We are the supplier.. FYI, when you re-submit a job, changes in either the source or destination are retained (last modified is retained), whereas deleted items in the source are not purged in the destination. I could not see any documentation regarding this.
