### ISSUE TITLE
Download versions do not match the chart on the release notes

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#2192]
The Download page with versions does not match the chart on the release notes. I am not sure which one is current. 

From Download page:

  | Public preview | First release | Rolling out | Full General Availability
-- | -- | -- | -- | --
Last released build | 3.4.119.1 | 3.4.119.1 | 3.2.119.0 | 3.2.118.0

From Release notes:

  | Public preview | First release | Rolling out | Full General Availability
-- | -- | -- | -- | --
Last released build | 3.4.119.3 | 3.4.119.2 | 3.4.119.2 | 3.4.119.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [SharePoint Migration Tool for SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JoanneHendrickson** [comment]
this has been corrected.
