### ISSUE TITLE
Does not mention feature support for SP2016

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#2193]
The feature list only shows File Share and SharePoint 2010 and 2013. SPMT also supports SP2016 in Public Preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support? - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
