### ISSUE TITLE
SPMT - large files

### ISSUE THREAD

**Issue by karenreali** [MicrosoftDocs/OfficeDocs-SharePoint#2198]
With SP and OneDrive now supporting large file sizes it looks like the migration tool is outdated and is blocking anything over 15GB

**Comment by scanum** [comment]
@karenreali Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
