### ISSUE TITLE
Broken link in run-hybrid-picker.md article

### ISSUE THREAD

**Issue by PiotrekKrakowiak** [MicrosoftDocs/OfficeDocs-SharePoint#22]
The OfficeDocs-SharePoint / SharePoint / SharePointServer / hybrid / run-hybrid-picker.md article contains a broken link (*THE* link to download the hybrid picker):

https://configure.office.com/scenario.aspx?Sid=54

Using the link you come into an endless Auth loop.

Therefore it is impossible to use the hybrid picker.

**Comment by MikePlumleyMSFT** [comment]
The link is correct. There may have been a temporary glitch. Please try again.
