### ISSUE TITLE
XSLT

### ISSUE THREAD

**Issue by Walter-Kuhn** [MicrosoftDocs/OfficeDocs-SharePoint#220]
I cannot find information on which XSLT version is supported in Sharepoint 2016. 1.0, 2.0, 3.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4a4e12-f4ab-7c6b-54a4-16d159bb1da5
* Version Independent ID: 158e3039-1567-d5a0-28ef-958e4876b351
* Content: [New and improved features in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2016#feedback)
* Content Source: [SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@Walter-Kuhn Thank you for your feed back 

I want to make sure you get the information on XST versions. The support team will be able to handles this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
