### ISSUE TITLE
SPMT tool settings for max file size upload

### ISSUE THREAD

**Issue by Rupalikothawade** [MicrosoftDocs/OfficeDocs-SharePoint#2200]
[Enter feedback here]
Hello team,

is there any feature planned for setting maximum single file upload limit for migration to OneDrive.
With current update from OneDrive, it now allows 100GB of file upload, while our requirement is to not migrate files greater than 15GB.

Thanks and regards,
Rupali Kothawade
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad86450-d9ac-4cc4-fc75-63f8b285c298
* Version Independent ID: d1e8c85a-b365-78c0-be1a-5a03ee082491
* Content: [Available settings in SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-settings)
* Content Source: [migration/SPMT-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Rupalikothawade Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
