### ISSUE TITLE
Blocking Sync only

### ISSUE THREAD

**Issue by JRHJRH** [MicrosoftDocs/OfficeDocs-SharePoint#2201]
The document intimates that you can limit OneDrive Sync using conditional access, but does not mention that in order to do that you need to block *all* application (desktop) access (set to web only) to SharePoint.  

In our scenario we wish to block sync on unmanaged devices but allow access to SharePoint/OneDrive downloads and via native apps such as Word Desktop, this is not possible (as confirmed by FastTrack), this document should point out those limitations.

https://docs.microsoft.com/en-us/onedrive/enable-conditional-access

**Comment by scanum** [comment]
@JRHJRH Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JRHJRH** [comment]
Hi, this has already been through fast track (https://www.microsoft.com/en-gb/fasttrack?rtc=1) and they have confirmed that it is not possible without the limitations, the document should be updated to add those limitations.
