### ISSUE TITLE
Missing URL link

### ISSUE THREAD

**Issue by MrNigel** [MicrosoftDocs/OfficeDocs-SharePoint#2202]
In the last sentence of the last paragraph this link is missing: See **<Link to consent info>** for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca1a36-e67f-e52d-9b13-fe1887e1cf26
* Version Independent ID: b09efc79-8a7f-57b9-dc13-5b0d1c38fcaf
* Content: [SharePoint Migration Identity Mapping Tool Azure Active Directory Identity Scan - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-identity-mapping-tool-azure-active-directory-identity-scan)
* Content Source: [migration/sharepoint-migration-identity-mapping-tool-azure-active-directory-identity-scan.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-migration-identity-mapping-tool-azure-active-directory-identity-scan.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@MrNigel Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
