### ISSUE TITLE
Will it work on-premises

### ISSUE THREAD

**Issue by jpfreire** [MicrosoftDocs/OfficeDocs-SharePoint#2205]
There's no mention to on-premises SharePoint will it have a similar feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe029ff2-3230-3320-aef5-9f16ab9464cc
* Version Independent ID: d791f3f6-257f-9a9b-461f-a12693d4bfde
* Content: [Branding your SharePoint site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience)
* Content Source: [SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@jpfreire Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
