### ISSUE TITLE
Incorrect menu guidance

### ISSUE THREAD

**Issue by MrNigel** [MicrosoftDocs/OfficeDocs-SharePoint#2206]
The opting in to the preview menu guidance is incorrect:

Under Manage, select Organizational Relationships.
Select Settings.
Under Enable Email One-Time Passcode for guests (Preview), select Yes.
Select Save.

It should read:

Under Manage select 'User Settings'
Under 'External users' select 'Manage External Collaboration Settings'
Under Enable Email One-Time Passcode for guests (Preview), select Yes.

![image](https://user-images.githubusercontent.com/8640497/86904838-4f32ce80-c122-11ea-8eed-6a6188b975a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@MrNigel thanks for catching this. Updated the article.

**Comment by scanum** [comment]
@MrNigel Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
