### ISSUE TITLE
Blocking Site Collections

### ISSUE THREAD

**Issue by tsls** [MicrosoftDocs/OfficeDocs-SharePoint#221]
Dear Microsoft,

I'm unable to block access based on conditional access

I have created a conditional access policy which is configured as follows:
Assignments:
Users: All Users
Cloud Apps: SharePoint Online
Conditions: Client Apps (Browser\Mobile\Desktop Apps), Location (All Regions except UK)
Access controls: 
Grant: (Default states Grant 0)
Session: Use app enforce restricts 

I have then executed: Set-SPOSite https://tenant.sharepoint.com/sites/Team -ConditionalAccessPolicy BlockAccess

The Tenant is set to full access: Set-SPOTenant -ConditionalAccessPolicy AllowFullAccess

I have tested using What IF in CA and can see that my user will evaluate the block rule, however the block never happens.

I have tried the rule without Location and makes no differents. 

Ultimately I want a rule which will only allow certain IP's to access a site collection, i.e. I only want data accessible from the UK for certain site collections.

Kind Regards 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-specific-sharepoint-site-collections-or-onedrive-accounts)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@tsls Thank you for you feedback 

I want to make sure you are able to block access correctly for your needs. The support team will be able to handles this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
