### ISSUE TITLE
Publishing and running OneDrive as a remote app will allow syncing of files

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/OfficeDocs-SharePoint#2210]
While the sync app is not supported in remote app scenarios, it should be noted that if you also publish OneDrive as a remote app and run it, it will start the sync app.  This means any files save to OneDrive from another remote app running will be sync'd in real-time.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc677c5-4514-fb8b-a864-4edd711d6f44
* Version Independent ID: 1e3dbf59-48d4-2696-ad8a-7f9cb60871ec
* Content: [Use the sync app on virtual desktops - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-vdi-support)
* Content Source: [OneDrive/sync-vdi-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-vdi-support.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@pnwnightowl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @pnwnightowl, thank you for your feedback and help us to improve docs.microsoft.com.

I think if it's not supported you shouldn't publish the OneDrive sync app in a remote app scenario. I highly recommend this.

**Comment by scanum** [comment]
@pnwnightowl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
