### ISSUE TITLE
The word "subscription" is hard to understand

### ISSUE THREAD

**Issue by temiyaha** [MicrosoftDocs/OfficeDocs-SharePoint#2215]
In the text below on this page, I think the word "tenant" is more accurate than "subscription".

_You can also use external sharing to share between licensed users on multiple Microsoft 365 subscriptions if your organization has more than one subscription._

I think the word "subscription" is more appropriate in Azure, but in M365 the word "tenant" is easier to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@temiyaha thanks for the feedback. We've found that "tenant" is a confusing term for many customers, so we avoid using it in the help documentation. Normally we'd say "organization" but in this case we're talking about one organization with multiple Microsoft 365 subscriptions.

**Comment by scanum** [comment]
@temiyaha Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
