### ISSUE TITLE
Requiring a Secondary Contact does not work for Communication Site

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/OfficeDocs-SharePoint#2216]
When creating a Communication Site the prompt for adding a secondary site contact is skipped and users are redirected directly to the site. However, this setting does apply for Team Sites

**Comment by scanum** [comment]
@Mlavieri Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
