### ISSUE TITLE
Rings are now Channels

### ISSUE THREAD

**Issue by JaniceLu-cos** [MicrosoftDocs/OfficeDocs-SharePoint#2217]
[I don't think this document is still valid?  There's a document that explain the details of Channel, which was used to be Ring.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8d826-fd44-b260-77e7-24d9ddd6e67f
* Version Independent ID: b0df9532-a918-a341-2790-a61a8c5c6894
* Content: [The OneDrive sync app update process - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-client-update-process)
* Content Source: [OneDrive/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JaniceLu-cos  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@kaarins please can you help? Should this article be updated to read the correct channels info? Or should I add this link to the article - https://techcommunity.microsoft.com/t5/office-365-blog/a-new-wave-of-innovation-to-help-it-modernize-servicing-of/ba-p/1380733

**Comment by kaarins** [comment]
The OneDrive sync app still releases through the rings. The changes to M365 app channels don't affect OneDrive.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lindspea** [comment]
@JaniceLu-cos thank you for reaching out. Please see @kaarins comment. @scanum this can be closed thank you.

**Comment by scanum** [comment]
@JaniceLu-cos Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
