### ISSUE TITLE
Error running script 

### ISSUE THREAD

**Issue by tbey80** [MicrosoftDocs/OfficeDocs-SharePoint#222]
You cannot call a method on a null-valued expression.
At C:\users\beyt\desktop\BulkEnqueueOneDriveSite.ps1:56 char:1
+ $loader.Context.ExecuteQuery()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts?redirectSourcePath=%252fen-gb%252farticle%252fHow-to-pre-provision-user-sites-in-OneDrive-for-Business-ceef6623-f54f-404d-8ee3-3ce1e338db07)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@Tyeb80 - thank you for submitting feedback. 

Thank you reaching out to us. Support will be able to handle this case and escalate it to resolution. I want to make sure this script issue gets resolved and the issues in GitHub are for the documents.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by CMACKINTOSH1975** [comment]
There is a simpler way to do this
$admin = 'admin@tenant.onmicrosoft.com'

$password = Get-Content "C:\EncryptedPassword.txt" | ConvertTo-SecureString

$cred = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $admin,$password

Connect-SPOService –Url https://tenant-admin.sharepoint.com/ -Credential $cred 

$users = Get-Content -path "C:\Userlist.txt"

Request-SPOPersonalSite -UserEmails $users


.......................
Userlist.txt

user1@tenant.com
user2@tenant.com
user3@tenant.com
