### ISSUE TITLE
SharePoint Group Mapping

### ISSUE THREAD

**Issue by albegut** [MicrosoftDocs/OfficeDocs-SharePoint#2220]
As noted at the bottom of the page, it is not possible to map a SharePoint group to a SharePoint group using the SPMT tool. As noted in the notes to Release [3.4.119.2](https://docs.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool#spmt-341192), changes have been made to map SharePoint groups. Hasn't the user mapping been done yet or hasn't the information been updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user mapping file for data content migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@albegut  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@albegut thank you for reaching out. Would you suggest removing the note at the bottom and adding the link you mentioned with updates?

**Comment by albegut** [comment]
@lindspea I was asking because the SPMT is not doing rigth that functionallity andI would like to know if the documentation is rigth or the tool has a bug. I´m in contact with the SPMT support to know the current status of that functionallity

**Comment by lindspea** [comment]
@JoanneHendrickson could you possibly assist please?

**Comment by JoanneHendrickson** [comment]
Thanks albegut --  investigating now with the PMs.

**Comment by lindspea** [comment]
@JoanneHendrickson any news yet please?

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by JoanneHendrickson** [comment]
Sorry for delay.   The improvement in  3.4.119.2 was that now SPMT migrates default SharePoint groups.  It is still not possible to map an AD group to a SharePoint group in the target site.  You also can't map a SharePoint Server group to a SharePoint group using SPMT.  Both release notes and topic updated.
