### ISSUE TITLE
Add Permission requirements needed to use the SharePoint Migration tool

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/OfficeDocs-SharePoint#2223]
[In the "Prerequisites & Endpoints for the SharePoint Migration Tool" located at https://docs.microsoft.com/en-us/sharepointmigration/spmt-prerequisites, please add all of the required permissions and admin roles needed to successfully run the SharePoint Migration tool in order to migrate content from SharePoint on-premise to SharePoint online  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e2247-016b-74b2-cf03-3041af3df550
* Version Independent ID: 3d6d4b62-4f26-81d1-6be2-ecfe7ebd81bf
* Content: [Prerequisites and Endpoints for SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-prerequisites)
* Content Source: [migration/SPMT-Prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-Prerequisites.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Jvasil Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
