### ISSUE TITLE
PNP Powershell Bandwidth Impact with these Group Policies.

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/OfficeDocs-SharePoint#2224]
With regards to the bandwidth group policy section where you can control the amount of bandwidth One Drive uses. Does this also then apply to any uploads / downloads that you would do via PNP power-shell? i am seeking clarity on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jasonwbaxter Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jasonwbaxter, thank you for your feedback and help us to improve docs.microsoft.com.

I understand that "Limit the sync app download speed to a fixed rate" group policy setting only impacts the OneDrive sync app (OneDrive.exe). I think it's reflected in the article:
"This setting lets you configure the maximum speed at which the OneDrive sync app (OneDrive.exe) can download files"

**Comment by scanum** [comment]
@jasonwbaxter Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
