### ISSUE TITLE
error 0x02010017 - Is site ownership on source really required?

### ISSUE THREAD

**Issue by nla-p1** [MicrosoftDocs/OfficeDocs-SharePoint#2228]
We are recently testing the MS migration tool.
1) The migration tool is complaining about missing permissions on the source (error 0x02010017). The message indicates the migrator user needs to be site owner. As the target site is created on the migrator's behalf, this should not be an issue.
We understand, the tool might need to read not just content but user information and settings. However: Why is "owner group" membership still not enough?
2) We tried to use the farm account for the source SharePoint. Now the tool hangs. The summary report has "faild" without an actual error number.
3) In order to migrate OneDrive on Premise (SP 2013-based MySites) - would we need to first "take ownership" of each single site in order to migrate? Or is it considerable to rather migrate the local replication folder on the end users's computers in order? At least this would work even if OneDrive replication has errors.

**Comment by scanum** [comment]
@nla-p1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nla-p1** [comment]
C1-Non sensitive

________________________________
Hi Manuela

Thank you for this. Agree. This is what I am attempting to do.
However, in a big organization still I need to wait for somebody else who is on short work.

Kind Regards
Norbert
