### ISSUE TITLE
Tool Migrates Unwanted Libraries

### ISSUE THREAD

**Issue by jfetrow** [MicrosoftDocs/OfficeDocs-SharePoint#223]
Migrating from SharePoint 2013 Foundation blog site to SharePoint Online Modern Communication site.  I specified one document library to migrate but the tool migrated the posts list, categories list, and comments list from the old blog site.  There is no option to delete them.  This is undesired behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@jfetrow Thank you for your feedback. 

I want to make sure you are able to the desired libraries without additional unwanted items. The support team will be able to handles this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
