### ISSUE TITLE
Faq not correct

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#2231]
Question: Does Migration Manager work with non-English SharePoint sites?
Wrong answer it's seems also non-english site work fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @paololec how are you? Can you kindly give us more information on the issues you ran into so I can check if the documentation should be corrected? Many thanks

**Comment by paololec** [comment]
It seems already correct now: 
Question: Can Migration Manager migrate content to non-English SharePoint sites?
Answer: Yes, Migration Manager can migrate content to non-English sites as long as the site title doesn’t include non-EN characters.
