### ISSUE TITLE
Invalid settings options reported or not yet release

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#2232]
Advanced Settings -> Migration Manager work folder
This settings seems not exists (and I need it! I have space on E drive not C drive!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c58f8a6-488f-7e3b-47f4-f5816801e804
* Version Independent ID: eed21d0d-7343-17eb-2afe-6cba550441a5
* Content: [Migration Manager settings - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-settings)
* Content Source: [migration/mm-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@paololec Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
