### ISSUE TITLE
auto-acceleration affect onedrive?

### ISSUE THREAD

**Issue by googol13** [MicrosoftDocs/OfficeDocs-SharePoint#2236]
does auto acceleration affect onedrive, since you have external users you are trying to share onedrive files and folders with? those external users wouldnt be able to authenticate anymore since everything routed to our authentication provider, idp, aka ADFS.

also sounds like our onmicrosoft.com accounts (backup ones) would break too, only your domain based accounts would work for sharepoint online if you turn on auto acceleration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21bd120e-26c1-3a5a-499b-8dbd01a435e6
* Version Independent ID: 2ced3050-f8ce-a5c3-a292-e0d668e4a47a
* Content: [Enable auto-acceleration in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/enable-auto-acceleration)
* Content Source: [SharePoint/SharePointOnline/enable-auto-acceleration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/enable-auto-acceleration.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@googol13 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
