### ISSUE TITLE
Hybrid extranet B2B collaboration sites link is broken

### ISSUE THREAD

**Issue by dimachernov** [MicrosoftDocs/OfficeDocs-SharePoint#224]
The link from the note to the Hybrid extranet B2B collaboration sites article is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496da599-0a29-be5c-cc78-a1c4a3046862
* Version Independent ID: 07f1ddf4-a924-af57-4f47-f90ccf87c705
* Content: [Minimum public update levels for SharePoint hybrid features](https://docs.microsoft.com/en-us/SharePoint/hybrid/minimum-public-update-levels-for-sharepoint-hybrid-features)
* Content Source: [SharePoint/SharePointServer/hybrid/minimum-public-update-levels-for-sharepoint-hybrid-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/minimum-public-update-levels-for-sharepoint-hybrid-features.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Link fixed. Thanks for catching that.
