### ISSUE TITLE
Permanently delete a OneDrive

### ISSUE THREAD

**Issue by Pixa1** [MicrosoftDocs/OfficeDocs-SharePoint#2240]
On the last section "Permanently delete a OneDrive" the document states:
_After you recover the data you need from the OneDrive, we recommend that you permanently delete the OneDrive by running the following command:_

`Remove-SPODeletedSite -Identity <URL>`

The problem here is, when you restore a site, it is no longer listed as deleted site, so you cannot use that command that you mention.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3384358-57c3-7117-f4c4-5da891cbf2fd
* Version Independent ID: e253e442-722d-acc7-1155-ee90ed1c324f
* Content: [Restore a deleted OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/restore-deleted-onedrive)
* Content Source: [OneDrive/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Pixa1  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
