### ISSUE TITLE
Document links open in new tab

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/OfficeDocs-SharePoint#2244]
Our experience is a bit different than the documentation.  In the Links section, it states that documents open in a new tab in the browser.  
"Link points to a document (same site or different site): Links open in a new tab."

We are seeing both PDF and XLSX document open in the same tab instead of a new tab. We've tested and validated from Quick Links and Menu Links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Plan navigation for the modern experience in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@melkinsco Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
