### ISSUE TITLE
Support for SharePoint 2016?

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/OfficeDocs-SharePoint#2245]
I have been told by some PFEs and MSFT support that this will work for SharePoint 2016. Is it supported? Please consider adding that in the documentation (and download links).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [SharePoint Migration Assessment Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@mcantin Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mcantin** [comment]
Case# 20950581, I was verbally told per Microsoft PFE that SMAT will work for SharePoint 2016, but it doesn't say that in these docs.

"The tool is built to be run from within a SharePoint 2010 or 2013 farm." under https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool#prerequisites

**Comment by mcantin** [comment]
@scanum I believe this isn't tenant related. This is documentation related. Can this be reopened?
