### ISSUE TITLE
"Enable automatic upload bandwidth management for OneDrive" registry key should be EnableAutomaticUploadBandwidthManagement instead of ENABLE_AUTOMATIC_UPLOAD_BW_MGMT 

### ISSUE THREAD

**Issue by rantipole1** [MicrosoftDocs/OfficeDocs-SharePoint#2246]
I believe the **Enable automatic upload bandwidth management for OneDrive** registry key should be _EnableAutomaticUploadBandwidthManagement_ instead of _ENABLE_AUTOMATIC_UPLOAD_BW_MGMT_ 

Thank you,
Rantipole1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@rantipole1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rantipole1** [comment]
Hi Manuela,

I don't need to open a ticket for something I've already resolved, but OneDrive documentation appears to have a typo. Can you please confirm that it has been corrected?

Thank you,
Rantipole1

Sent from my mobile device

________________________________

**Comment by rantipole1** [comment]
Going to address the bad key/typo?
