### ISSUE TITLE
Add section about "Only the end user may disable OneDrive Desktop Backup"?

### ISSUE THREAD

**Issue by rantipole1** [MicrosoftDocs/OfficeDocs-SharePoint#2247]
After unsuccessfully searching for a way to programmatically (SCCM, GPO, etc) disable OneDrive Desktop Backup for all domain users as a backout plan, I opened Microsoft Support Ticket #20656463. I was eventually informed that there is no way to revert or disable OneDrive Desktop Backup once enabled it via GPO. Users must manually disabled the feature individually, through the OneDrive Settings GUI. It would be nice to include a section in the GPO doc explaining that, to allow administrators to consider that fact when planning their rollout.

Thank you,
Rantipole1

**Comment by scanum** [comment]
@rantipole1 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rantipole1** [comment]
Hi Manuela,

I don't need to open another ticket for this issue. It appears that you didn't read my submission. I stated that I had a ticket open and included the MDFT Support ticket number. The OneDrive documentation appears to be missing some critical information for administrators in that only end users can turn off Desktop Backup. Can you please address my original concern?

Thank you,
Rantipole1

Sent from my mobile device

________________________________

**Comment by rantipole1** [comment]
Are we going to get any any traction on this problem or are you going to just keep closing this ticket without addressing the issue?
