### ISSUE TITLE
Very clear article, thank you for this.

### ISSUE THREAD

**Issue by TijmenMav** [MicrosoftDocs/OfficeDocs-SharePoint#225]
Very clear article, thank you for this. Even for a non tech person.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4df1d8-955c-63d2-628e-8359391b8710
* Version Independent ID: 01326ab6-1270-d096-64e8-eb7d63ea9863
* Content: [Create a hub site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-hub-site?redirectSourcePath=%252farticle%252fcreates-a-hub-site-92bea781-15d8-4bda-805c-e441e2191ff3)
* Content Source: [SharePoint/SharePointOnline/create-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@TijmenMav Thank you for your complements we strive to make all article clear and concise.
