### ISSUE TITLE
Is there any reason why we are keeping this feature on the classical interface as it is not active?

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/OfficeDocs-SharePoint#2255]
This feature is not active, when are we planning to remove it from the classical interface & remove it from our documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6668926-c332-1348-2559-ee4e6dbf68a9
* Version Independent ID: 214e5b3a-ba59-2dd3-5e97-7d642072afaf
* Content: [Enable or disable preview features in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/enable-or-disable-preview-features)
* Content Source: [SharePoint/SharePointOnline/enable-or-disable-preview-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/enable-or-disable-preview-features.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jamilhaddadin Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
