### ISSUE TITLE
Incorrect link for SharePoint Governance

### ISSUE THREAD

**Issue by eemancini** [MicrosoftDocs/OfficeDocs-SharePoint#2256]
The resource link for "SharePoint governance overview" links to a permissioned area: https://review.docs.microsoft.com/sharepoint/governance-overview?branch=hokavian-intranet-governance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb43d6e3-6ceb-adfe-640c-b87fb133c7fd
* Version Independent ID: 0c6d323b-84ea-7c16-7879-8664404f7bc8
* Content: [Planning intranet governance - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/intranet-governance)
* Content Source: [SharePoint/SharePointOnline/intranet-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/intranet-governance.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@eemancini Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Looks like the link has been fixed in the PR. @scanum please close. @eemancini Emily, thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
