### ISSUE TITLE
Support for SP2016

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#2258]
Tool show only support for SP2010 and SP2013 while SPMT now supports SP2016. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migrate-to-sharepoint-online.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing @Padavid
