### ISSUE TITLE
Enconding of CSV for Migration Manager

### ISSUE THREAD

**Issue by JoseMonteiroMS** [MicrosoftDocs/OfficeDocs-SharePoint#2259]
Hello Team,

There is no input on the documentation what encoding needs the CSV to be accepted by Migration Manager.
Can you please clarify what enconding it need?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [How to format a CSV or JSON file for bulk upload in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json#feedback)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JoseMonteiroMS Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JoseMonteiroMS how are you? I could guess UTF-8 but I'll try to confirm. Thanks for your feedback.

**Comment by JoseMonteiroMS** [comment]
Hello Andres,

I have now the confirmation from PG, but would worth it to be mentioned as well in the documentation?
Once you got the confirmation from your side..

Thanks for coming back to me.

Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://www.microsoft.com/Pt-PT/>[cid:image005.png@01D69005.79967CB0]<https://www.linkedin.com/company/microsoft/>
[cid:image006.png@01D69005.79967CB0]<https://www.microsoft.com/Pt-PT/>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580979275&sdata=0hQJKbqnJEupPpJF6dQGyn9yAEI4OlnhebVQ5nGhDFE%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580989274&sdata=IQ5K0J%2BPZuQs7j0EXmJbg%2FZ2r0FT%2F6hRld%2BcY1ixntA%3D&reserved=0>

**Comment by get-itips** [comment]
> Hello Andres, I have now the confirmation from PG, but would worth it to be mentioned as well in the documentation? Once you got the confirmation from your side.. Thanks for coming back to me. Best Regards, José Monteiro FTC EMEA MVM Lead FastTrack Center 

Hello @JoseMonteiroMS Yes I think it is worth to mention, what is the information you got from PG? Because I'll try to reach them too my path could be slower. :) Thanks for sharing

**Comment by JoseMonteiroMS** [comment]
Hello Andres,

It was @Hongliang Zhu<mailto:hozhu@microsoft.com> he can confirm the UTF8 format requirement.

Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://www.microsoft.com/Pt-PT/>[cid:image005.png@01D6904B.0B70D820]<https://www.linkedin.com/company/microsoft/>
[cid:image006.png@01D6904B.0B70D820]<https://www.microsoft.com/Pt-PT/>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580979275&sdata=0hQJKbqnJEupPpJF6dQGyn9yAEI4OlnhebVQ5nGhDFE%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580989274&sdata=IQ5K0J%2BPZuQs7j0EXmJbg%2FZ2r0FT%2F6hRld%2BcY1ixntA%3D&reserved=0>

**Comment by get-itips** [comment]
@JoseMonteiroMS Thanks for the info Jose, will propose adding thru a PR and ask for review by the article's designated author.

**Comment by JoseMonteiroMS** [comment]
Thanks amazing.

Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://www.microsoft.com/Pt-PT/>[cid:image005.png@01D6904E.2B4D1890]<https://www.linkedin.com/company/microsoft/>
[cid:image006.png@01D6904E.2B4D1890]<https://www.microsoft.com/Pt-PT/>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580979275&sdata=0hQJKbqnJEupPpJF6dQGyn9yAEI4OlnhebVQ5nGhDFE%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7CJose.Monteiro%40microsoft.com%7Cebc5765797174341c8ca08d84e8d9dc0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637345717580989274&sdata=IQ5K0J%2BPZuQs7j0EXmJbg%2FZ2r0FT%2F6hRld%2BcY1ixntA%3D&reserved=0>
