### ISSUE TITLE
Conversion of user principal names with '_' to their actual values

### ISSUE THREAD

**Issue by mag382** [MicrosoftDocs/OfficeDocs-SharePoint#2260]
[Enter feedback here]

On this page a onedrive url with a username in it has all special characters converted to '_'.  The documentation gives an example conversion:
"(where user1_contoso_com corresponds with user1@contoso.com)"

However, this is insufficient information to know how to convert the username with '_'s into the valid userPrincipalName in all scenarios.  For example, a user name like:
"user_middle_lastname_subdomain_domain_com"

Programmatically, there seems to be no way to know if this should become "user_middle_lastname@subdomain.domain.com", or maybe even "user.middle.lastname@subdomain.domain.com".

Does Microsoft have any documentation on how to convert these underscore usernames to the userPrincipalName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes#onedrive-url)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mag382 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mag382** [comment]
I would like to add that I've found in some other testing that when multiple users of similar punctuation are created, MS creates distinct Sharepoint URLs for them by adding a number to the end.

For example first_last@domain.com, and first.last@domain.com.  The Sharepoint URL for each of these becomes something like:
https://contoso-my.sharepoint.com/personal/first_last_domain_com
https://contoso-my.sharepoint.com/personal/first_last_domain_com1

As far as I can tell, the only way to find out the actual userId or userPrincipalName given a string like "first_last_domain_com1" is to make a call to /v1.0/users/userId/drives for EVERY user in the system, and check the webUrl there.

**Comment by get-itips** [comment]
Hello @mag382 How are you?
I could verify the behavior that you describe here on my lab tenant.
Will propose adding a note to the article stating that, if the username already contains an underscore, it'll remain in the onedrive url.
Thank you
