### ISSUE TITLE
Effects of Teams File Sharing

### ISSUE THREAD

**Issue by SOM-Scott** [MicrosoftDocs/OfficeDocs-SharePoint#2261]
There is no note as to weather or not Teams Shared Files will be effected. It appears as though they are no longer available after a name change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SOM-Scott Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @SOM-Scott Scott, how are you?
That is covered under "Shared OneDrive files", the same applies.
Thank you

**Comment by scanum** [comment]
@SOM-Scott Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
