### ISSUE TITLE
Directory ID box has changed to Tenant ID

### ISSUE THREAD

**Issue by chrisbacapcltm** [MicrosoftDocs/OfficeDocs-SharePoint#2262]
[Enter feedback here]
Directory ID box referenced in the article seems to have changed to Tenant ID. (So at least it makes a little more sense when documenting, right? )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93351c-948b-67f7-edd7-8f84982f1834
* Version Independent ID: b3d722cc-3e6e-9b0a-efdb-7d61a76c874f
* Content: [Find your Microsoft 365 tenant ID - OneDrive](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id)
* Content Source: [OneDrive/find-your-office-365-tenant-id.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/find-your-office-365-tenant-id.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@chrisbacapcltm Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
