### ISSUE TITLE
Instructions unclear regarding first column

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-SharePoint#2264]
Hi!

The instructions for creating the mapping file say that column A should be the login name of the user, however in the illustration, it has an SID instead. 

The instructions or illustration should be amended to clarify which is correct (or if both are acceptable)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user-mapping file for data content migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@douglasac10  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @douglasac10 
How are you?
I see that the article has been updated recently to clarify that SP2013&2016 can accept SID and Login name as the instructions says, and a new screenshot has been added.

Hope this clarifies it to you,
Thanks

**Comment by scanum** [comment]
@douglasac10 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
