### ISSUE TITLE
Default Content Types

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-SharePoint#2265]
Could you add a section where you list the default content types AND their metadata columns, please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96aaa197-d69d-0cc1-aa52-7c1519442fc2
* Version Independent ID: a60ef9d8-b49f-c983-e4b6-0c30b388116c
* Content: [Create or customize a content type - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/create-customize-content-type)
* Content Source: [SharePoint/SharePointOnline/create-customize-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-customize-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@ingepepe  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ingepepe thank you for reaching out and helping improve MS Docs. Please see here - https://support.microsoft.com.office/introduction-to-content-types-and-content-type-publishing-e1277a2e-a1e8-4473-9126-91a0647766e5. Let me know if this article helps at all.

**Comment by scanum** [comment]
@ingepepe  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
