### ISSUE TITLE
Browser Support Matrix needed

### ISSUE THREAD

**Issue by alinefmr** [MicrosoftDocs/OfficeDocs-SharePoint#2266]
Documentation Center lacks information on supported web browsers and their versions, similar to https://docs.microsoft.com/en-us/sharepoint/install/browser-support-planning-0 for SharePoint on-premises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe029ff2-3230-3320-aef5-9f16ab9464cc
* Version Independent ID: d791f3f6-257f-9a9b-461f-a12693d4bfde
* Content: [Branding your SharePoint site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience)
* Content Source: [SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@officedocspr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MikePlumleyMSFT** [comment]
@alinefmr, the browser requirements for Microsoft 365 are listed in [Microsoft 365 and Office Resources](https://www.microsoft.com/microsoft-365/microsoft-365-and-office-resources).

**Comment by alinefmr** [comment]
> @alinefmr, the browser requirements for Microsoft 365 are listed in [Microsoft 365 and Office Resources](https://www.microsoft.com/microsoft-365/microsoft-365-and-office-resources).

Thank you for pointing out, Mike. I suggest adding a link to it somewhere in the SPO branding (or overall planning) documents for easier access and reference.

**Comment by scanum** [comment]
@alinefmr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
