### ISSUE TITLE
SharePoint supportability 

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/OfficeDocs-SharePoint#2269]
Document says classic workflow will be supported until 2026, but recent events put this expiring on Nov 1st 2020, but please specify SharePoint 2010 workflows on SharePoint Online vs SharePoint 2013 workflows on SharePoint Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76ff1b8-cf92-2014-8847-35ff8befd854
* Version Independent ID: cb83aa55-6973-c3e7-f58e-ff6f8df45320
* Content: [SharePoint Server Team Sites Migration Guide - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sp-teams-sites-migration-guide)
* Content Source: [migration/sp-teams-sites-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sp-teams-sites-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@mcantin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mcantin Mike, how are you?
I will propose adding a link to a support article that clarify this.
Thanks
