### ISSUE TITLE
Query form a customer: GDrive Migration

### ISSUE THREAD

**Issue by JoseMonteiroMS** [MicrosoftDocs/OfficeDocs-SharePoint#2271]
Hello Team,

I have a customer that asked the below query:

"Is there a risk to import malware ?
		E.g. if there is malware on a Google Drive that may be useless in an Google environment but dangerous for Microsoft systems, would this be sorted out during the migration ?”

Besides that it appears unlikely to happen, does mover have any kind of validation?

BR, Jose Monteiro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 754ae29b-5d5f-1972-8551-6d52b086c452
* Version Independent ID: 1621208b-02e6-f6f0-ee36-59930c7697b0
* Content: [Mover Migration FAQ - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-migration-faq)
* Content Source: [migration/mover-migration-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-migration-faq.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson

**Comment by scanum** [comment]
@JoseMonteiroMS Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
