### ISSUE TITLE
Setting up Conditional Access for OneDrive Sync App

### ISSUE THREAD

**Issue by AlphaXD001** [MicrosoftDocs/OfficeDocs-SharePoint#2273]
**OfficeDocs-SharePoint/OneDrive/enable-conditional-access.md** indicates that it is possible to put in an Conditional Access Policy for OneDrive Sync Client syncing - the OneDrive Sync App is not available in a form that matches the Sync App ID so therefore never gets triggered on a Conditional Access policy - the only way to block OneDrive syncing is through the Sharepoint Online Cloud App - which then breaks all the other apps that require a form of Sharepoint online like Teams.  

Application:  OneDrive SyncEngine
Application ID: ab9b8c07-8f02-4f72-87fa-80105867a763

There is no Azure AD Enterprise Application available that matches that Application ID to put Conditional Access Rules Against.

**Comment by scanum** [comment]
@AlphaXD001 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by AlphaXD001** [comment]
I have had tickets open with Microsoft - SharePoint Team, Intune Teams, and Azure Teams.  This document says you can do something with Conditional Access Policies but then provides no description of how and then everyone who questions this document here gets told to talk to Microsoft Support with the canned response.  Someone try to create a OneDrive Sync Engine Conditional Access Policy.

**Comment by pza** [comment]
@AlphaXD001 , I'm curious if you ever worked this out?  I'm facing the same issue and raising a ticket to support hasn't helped - I probably got the same irrelevant canned response you did!
