### ISSUE TITLE
Incorrect Registry Key

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/OfficeDocs-SharePoint#2275]
The registry key listed to verify the existence of OneDrive is incorrect.  It shows up under HKCU **NOT** HKLM.

Please update
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine - OneDrive](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BigIve Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rickym61** [comment]
Experiencing the same thing, HKCU not HKLM. Installs fine to c:\program files (x86) using SCCM 1910 here.

**Comment by BigIve** [comment]
@scanum (and @rickym61) Doing some more testing, it appears the correct location is:
HKEY_LOCAL_MACHINE\SOFTWARE\\**WOW6432Node**\Microsoft\OneDrive
