### ISSUE TITLE
SPMT-Offline installation and open ports 

### ISSUE THREAD

**Issue by crazyhorse4** [MicrosoftDocs/OfficeDocs-SharePoint#2276]
I'm trying to install the SPMT without an internet connection and get an error.
Also,  searched online for specific ports that SPMT using to upload data and did not find anything.
The server located in close data center and without a specific destination I can't open ports.

**Comment by scanum** [comment]
@crazyhorse4 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
