### ISSUE TITLE
Migration Manager - Mapping file

### ISSUE THREAD

**Issue by JoseMonteiroMS** [MicrosoftDocs/OfficeDocs-SharePoint#2278]
Hello Team,

We are struggling to find any documentation around the right format of the user mapping file to be used in Migration Manager.

Waiting for your feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c58f8a6-488f-7e3b-47f4-f5816801e804
* Version Independent ID: eed21d0d-7343-17eb-2afe-6cba550441a5
* Content: [Migration Manager settings - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-settings)
* Content Source: [migration/mm-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JoseMonteiroMS Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JoseMonteiroMS** [comment]
Hello Manuela,

I really feel that there is a gap in the documentation, how can you close this?
