### ISSUE TITLE
Reversing this procedure

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/OfficeDocs-SharePoint#2279]
It would be helpful to have documentation on how to back out of this procedure. 
I.E. how to remove the redirect, then swap the URL back.

Thanks for considering this!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@robertafreese Thanks for submitting feedback. We will consider adding this in the future.
