### ISSUE TITLE
Crawl database recommended limits

### ISSUE THREAD

**Issue by github33** [MicrosoftDocs/OfficeDocs-SharePoint#228]
The doc recommends adding an additional analytics DB when it reaches 250 GB total size, or 20 M total rows. What is the recommendation for the crawl database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits#search-topology-limits)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@tklarsen , tone, can you comment on the size limit of the crawl DB pls. thx

**Comment by AndreaBarr** [comment]
@github33  thank you for submitting feedback. 

I want to make sure you get the best information on crawl database recommendations. I believe support will be able to get this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
