### ISSUE TITLE
More information regarding this tool.

### ISSUE THREAD

**Issue by kempt101** [MicrosoftDocs/OfficeDocs-SharePoint#2280]
Would like to see a step by step of how to add the tasks. Also possibly it would be worthwhile to have a tutorial like other doc's pages and also more information on how permissions get preserved and more on how those gets moved over. Seems like right now the information is a little bare. Also more in-depth information around how the migration works instead of just a high level overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210e3fb6-665e-a4e6-7b5e-fe3776ec1635
* Version Independent ID: 80b1c7f6-736f-70a4-ae6c-503d64e94a26
* Content: [Get started with Migration Manager  - SharePoint - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-get-started)
* Content Source: [migration/mm-get-started.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-get-started.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@kempt101 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kempt101 Sean, how are you?
Several updates were applied since you opened this feedback to the Migration Manager articles, I would like to know if you could review them. The team welcomes your feedback and is working on constantly improving the articles.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
