### ISSUE TITLE
One-Time Passcode for guests - SyncAadB2BManagementPolicy

### ISSUE THREAD

**Issue by HematM** [MicrosoftDocs/OfficeDocs-SharePoint#2281]
[Enter feedback here]

Hello,

I have installed the latest version of SharePoint Online Management Shell. However the latest version is not showing showing any output for this cmdlet:

SyncAadB2BManagementPolicy

Get-SPOTenant | Select-Object EnableAzureADB2BIntegration, SyncAadB2BManagementPolicy | fl

EnableAzureADB2BIntegration : True
SyncAadB2BManagementPolicy  : 

This parameter "EnableAzureADB2BIntegration" is configured as true.  Also in the Azure AD, the preview feature is enabled.. However, the domains added in Azure AD for external collaboration are not working for sharing in OneDrive or SharePoint Online.

Thanks,
Hemat
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@HematM Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
