### ISSUE TITLE
Support for SP2016

### ISSUE THREAD

**Issue by JulienSeg** [MicrosoftDocs/OfficeDocs-SharePoint#2282]
Support is specified for migration from SP2010 and SP2013 but I just find out that migration from SP2016 is now available. Does SPMT support the same features for SP2016 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dd218-a3cd-85e8-bdea-f491b98e9e48
* Version Independent ID: 1acc3912-f82b-510e-262b-785040d28795
* Content: [What does SPMT support? - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt)
* Content Source: [migration/What-is-supported-SPMT.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/What-is-supported-SPMT.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JulienSeg Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
