### ISSUE TITLE
bulk script missing NoWait parameter

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-SharePoint#2283]
The bulk script example should include the -NoWait parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization - OneDrive](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@gnerd  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @gnerd
