### ISSUE TITLE
great content! Thanks

### ISSUE THREAD

**Issue by PHWiest** [MicrosoftDocs/OfficeDocs-SharePoint#2284]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@PHWiest Thanks for sharing! We appreciate your feedback.
