### ISSUE TITLE
Install WorkflowManager after migration of SharePoint 2016 Server

### ISSUE THREAD

**Issue by emaborsa** [MicrosoftDocs/OfficeDocs-SharePoint#2287]
I have a SharePoint 2016 OnPremise farm and needed to migrate them to a new hardware.
I wanted to reinstall the WorkflowManager, but its components seem to be deprecated and completely removed from the web.
Using the WebPlatformInstaller (5.1) I get some errors. Trying to download them by the following commands I get some 404 error:

**Commands**
- Webpicmd /offline /Products:ServiceBus /Path:E:\ServiceBus
-  Webpicmd /offline /Products:WorkflowClient /Path:E:\WorkflowClient
-  Webpicmd /offline /Products:WorkflowManagerRefresh /Path:E:\WorkflowManagerRefresh

**Errors**
- Download of product 'WindowsImagingComponent failed. Failed to download file: 'http://download.microsoft.com/download/6/4/5/645FED5F-A6E7-44D9-9D10-FE83348796B0/wic_x64_enu.exe'.
- Download of product 'WorkflowClient failed. Failed to download file: 'http://go.microsoft.com/fwlink/?LinkID=717130&clcid=0x409'.

I need to install the manager, how can I do?

**Comment by emaborsa** [comment]
**EDIT 26.08.2020**
Today the WindowsImagingComponent works, but 'WindowsFabric_1_0_960_0 rises a 404:

- Download of product 'WindowsFabric_1_0_960_0 failed. Failed to download file: 'http://go.microsoft.com/fwlink/?LinkId=264989&clcid=0x409'. Skipping download of product 'ServiceBus': required dependency 'WindowsFabric_1_0_960_0' failed.

**Comment by scanum** [comment]
@emaborsa Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by emaborsa** [comment]
I wrote [here](https://docs.microsoft.com/en-us/answers/questions/76314/how-to-install-workflow-manager-for-sharepoint.html), they fixed it.
