### ISSUE TITLE
I dont see how this page provides the instructions I need

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/OfficeDocs-SharePoint#2289]
It looks like the new documentation for all the "MODERN" versions coming out is sorely lacking.  This link has no useful instructions on it like this page does for the old method:  https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions

There are no images, diagrams, or anything of help or use.  This only talks about new permission options but nothing about how to do what I need to do.  

We need actual directions, not whatever this is.  Everything has changed and there's no documentation.  If I attempt to follow the old link, it is immediately evident this no longer works.

What is this document supposed to be as it relates to how I have to do my job, and is there ACTUAL instructions somewhere hidden? If you're releasing these new versions for public use, we need DOCS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c667543-9b4d-52bb-5cc6-e2dc9c092e9e
* Version Independent ID: b005a5f1-7616-4d94-f230-8c3bd78baaeb
* Content: [Sharing & permissions in the SharePoint modern experience - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions)
* Content Source: [SharePoint/SharePointOnline/modern-experience-sharing-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-experience-sharing-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@VNJoe, procedures for configuring sharing in modern SharePoint are covered in [Manage sharing settings](https://docs.microsoft.com/sharepoint/turn-external-sharing-on-or-off). [Turn external sharing on or off for a site](https://docs.microsoft.com/sharepoint/change-external-sharing-site), [Set up secure collaboration with Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/solutions/setup-secure-collaboration-with-teams), and [Collaborate with guests in a site](https://docs.microsoft.com/microsoft-365/solutions/collaborate-in-site). We'll add some additional links to this article to these resources.

**Comment by VNJoe** [comment]
Thanks, definitely need those!

**Comment by VNJoe** [comment]
I still don't see any of those links having information as to how they relate to individual folders in SharePoint, or in how inheritance is incorporated in the new method.

**Comment by lindspea** [comment]
@VNJoe please have a look at the article as it's been updated recently. Let me know if you still need assistance. Thanks again for helping improve MS Docs.

**Comment by scanum** [comment]
@VNJoe  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
