### ISSUE TITLE
SharePoint and OneDrive integration with Azure AD B2B (Preview)

### ISSUE THREAD

**Issue by Silberthau** [MicrosoftDocs/OfficeDocs-SharePoint#2291]
Is there any expectation for how long this functionality will be in preview mode.

Tried following the instructions. I am new to Powershell. I was able to run the powershell commands. I think that I can confirm this is OK as by going to the Preview Features button within the All Users page  in Azure Active Directory and "Enhanced user management" is set to on.

However when I go to External collaboration settings within Azure Active Directory the ability to change
Enable Email One-Time Passcode for guests (Preview) to Yes is disabled.

The functionality that I want to test is : I have a PowerApps with a flow that uses a One Drive action (eg: converting a word template to a PDF). Unfortunately a guest user does not have access to the Powerapps because they cannot authenticate OneDrive.

I was hoping that this functionality in Preview would help.

Appreciate any assistance so that i can test this further.

regards,

Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Silberthau Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
