### ISSUE TITLE
unnecessary comma in front of one of the scripts

### ISSUE THREAD

**Issue by Gerasz87** [MicrosoftDocs/OfficeDocs-SharePoint#2292]
There is an unnecessary comma in front of one of the scripts, so if you copy the entire line and don't listen, your copied line of code will be incorrect.

`,(Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.sharepoint.com/personal/'") | Set-SPOTenant -ConditionalAccessPolicy AllowLimitedAccess`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Gerasz87 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @Gerasz87

**Comment by get-itips** [comment]
Hello @Gerasz87 I am sorry, but I was warn about this statement in the doc that slipped into the cracks for me:

> This example gets the OneDrive for every user and passes it as an array to Set-SPOTenant to limit access. **The initial comma and the parentheses are required for running this cmdlet as a batch request, which is fastest.**

**Comment by scanum** [comment]
@Gerasz87 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
