### ISSUE TITLE
Where to file bug reports for the SharePoint Migration Tool (SPMT)?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [MicrosoftDocs/OfficeDocs-SharePoint#2293]
The troubleshooting page should contain a link to where one can file bug reports.

E.g. I found that the SPMT - in certain circumstances - creates the wrong root folder name when migrating from source folder to destination doc lib while renaming the doc lib. What do I do now? I'd like somebody to know about this bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@heinrich-ulbricht Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @heinrich-ulbricht Heinrich, how are you?
The current tool to share feedback about the product is [this](https://sharepoint.uservoice.com/) the article currently references it at the bottom.
**Thank you**

**Comment by scanum** [comment]
@heinrich-ulbricht Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
