### ISSUE TITLE
Add a link to explanation article

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-SharePoint#2294]
This page is great for setting up the Organization Assets libraries. It could be improved by pointing to the article that explains how to use such libraries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ingepepe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ingepepe thanks again for helping improve MS Docs. Please have a look at the article as it's been updated recently with more information. Let me know if you need further assistance.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
