### ISSUE TITLE
How can we filter content types from content type hub based on published or unpublished?

### ISSUE THREAD

**Issue by anomepani** [MicrosoftDocs/OfficeDocs-SharePoint#2295]
How can we filter content types from content type hub based on published or unpublished?
I have searched but not able to find it away. I am using SPonline and using CSOM in c#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52f3c87-422d-70ad-8b29-673b3913bfdd
* Version Independent ID: 35b68646-fd17-b7a7-524d-9385b1187382
* Content: [Publish a content type - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/publish-content-type)
* Content Source: [SharePoint/SharePointOnline/publish-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/publish-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
