### ISSUE TITLE
Please add note for non-English versions of SharePoint

### ISSUE THREAD

**Issue by dennisameling** [MicrosoftDocs/OfficeDocs-SharePoint#2299]
The document mentions the following:

> If you use the standard out-of-the-box Document library ("Shared Documents"), you must use the internal name "Documents" as the placeholder value for the Source Document Library (Column B) in your CSV file. If you enter "Shared Documents" in that column, you will receive an "invalid document library" error.

However, this is only relevant to the **English** version of SharePoint. For other locales, the procedure needs to be as follows:

- Go to https://`ORG`.sharepoint.com/sites/`SITENAME`/_layouts/15/viewlsts.aspx?view=14
- Find the localized name for the Documents folder (e.g. in Dutch it's "Documenten"):
![image](https://user-images.githubusercontent.com/17739158/91975284-76231080-ed1f-11ea-9cf7-9d32fea33955.png)
- Use that name in the CSV file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [Format JSON or CSV for data content migration - SharePoint - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@dennisameling Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @dennisameling
