### ISSUE TITLE
Will this location-based policy affect the Microsoft Graph API call?

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/OfficeDocs-SharePoint#230]
Hi there, we tested this scenario and found the location-based policy would break down the Microsoft Graph API call even we added the hosted server IP address to the allowed list.  Our app is a first-party application. 

Does something we missed? Or it's by design? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Control access to SharePoint Online and OneDrive data based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by chenxizhang** [comment]
Any advice? @officedocspr

**Comment by AndreaBarr** [comment]
@chenxizhang  thank you for submitting feedback. 

We want your Microsoft Graph API to work properly. I believe support will be able to get this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
