### ISSUE TITLE
Uninstallation Instructions

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/OfficeDocs-SharePoint#2301]
There are no instructions at present for how to uninstall the Migration Manager agent. As Migration Manager does not appear in Add/Remove Programs, it is not obviously that you have to re-run the setup installer to access the uninstall option.

Will uninstalling an agent automatically delete it from SPO Admin Center or is that a separate task that is required?

**Comment by scanum** [comment]
@richardjgreen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
