### ISSUE TITLE
SilentConfig Setting for ADFS environment

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-SharePoint#2303]
This Article mentions "If you federate your on-premises Active Directory with Azure AD, you must use AD FS to enable this feature." But doesn't provide more details on what needs to be done on ADFS Side. Also the article its pointing to about AAD Connect doesn't give clarity on what exactly needs to be done. It would be great if you can add more details here.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @3novsan how are you?
Have you seen the links in the Note?

For more info, see How to configure hybrid Azure Active Directory joined devices.

https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan#federated-environment

Thanks

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
