### ISSUE TITLE
How do I Share a Document Library (not the entire site)? 

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-SharePoint#2307]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c667543-9b4d-52bb-5cc6-e2dc9c092e9e
* Version Independent ID: b005a5f1-7616-4d94-f230-8c3bd78baaeb
* Content: [Sharing & permissions in the SharePoint modern experience - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions)
* Content Source: [SharePoint/SharePointOnline/modern-experience-sharing-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-experience-sharing-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@HandyAndyOnGitHub Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
