### ISSUE TITLE
Silently move Windows known folders to OneDrive - how to disable? 

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/OfficeDocs-SharePoint#2309]
[Enter feedback here]
One enabled (which created key whose name and value is Tenant ID) how do I disable? The obvious answer is to delete the registry value but this is not supported for Configuration Manager baselines. Is it as simple as putting in a dummy Tenant ID (such all zeroes)? Disabling with Group Policy deletes KFMSilentOptIn and the related KFMSilentOptInWithNotification. If KFMSilentOptInWithNotification is set to 0 does that just disable the notification or is the whole Silently Move feature disabled? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#set-the-sync-app-update-ring)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
