### ISSUE TITLE
Base URL for SSS content pack has changed SSK -> sss

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/OfficeDocs-SharePoint#2310]
Old Base URL: http://microsoft.github.io/customlearning_staging/SSK/
New Base URL: http://microsoft.github.io/customlearning_staging/sss/

Note: lowercase is important. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5e30b9-c57e-52e0-e6b4-d1598ad446fc
* Version Independent ID: 1d182504-5c6c-8fa1-a21f-92a0b0d4d6d1
* Content: [Add SharePoint Success Site content to your M365 Learning Pathways solution - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/add-sss-cdn)
* Content Source: [SharePoint/SharePointOnline/add-sss-cdn.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/add-sss-cdn.md)
* Service: **sharepoint**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **holland-odsp**

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@Holland-ODSP Can you kindly confirm what @jsuddsjr is saying? Thanks

**Comment by get-itips** [comment]
@Holland-ODSP Holland could you see this one? Thanks!!

**Comment by Holland-ODSP** [comment]
Hey @get-itips , this comment has already been resolved. Please close this ticket. Thank you.

**Comment by get-itips** [comment]
@Holland-ODSP Thanks for the info.
@scanum please close this one. Thanks

**Comment by get-itips** [comment]
@scanum please close
