### ISSUE TITLE
Instructions to enter CDN URL should be removed.

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/OfficeDocs-SharePoint#2311]
```
Important

Enter this address in the URL field - https://microsoft.github.io/customlearning_staging/learningpathways/
```

This text does not apply to the SSS template provisioning flow and should be removed.

Note: this instruction applies to the M365LP *test* template only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c747f8-17cb-209a-a503-a9caa9da8cd8
* Version Independent ID: 0a7ae298-5bd2-1327-5933-7adfd7c0975a
* Content: [Overview of the SharePoint Success Site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-sss)
* Content Source: [SharePoint/SharePointOnline/provision-sss.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-sss.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **Holland-ODSP**

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jsuddsjr Looks like it has been removed already. Thanks for reporting.

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
