### ISSUE TITLE
The SSS "overview" contains too much detail, especially about M365 learning pathways

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/OfficeDocs-SharePoint#2312]
I appreciate your walkthrough of the SSS site layout, but provisioning instructions should be left to another page. The details about M365 learning pathways seemed especially out of place, since documentation exists elsewhere to provision and update M365LP. Consider linking to documentation for LP rather than duplicating it. 

Overview: https://docs.microsoft.com/en-us/office365/customlearning/
New Provisioning: https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#to-provision-learning-pathways
Update Web Part: https://docs.microsoft.com/en-us/office365/customlearning/custom_update#update-the-learning-pathways-web-part-package

Note: I realize that some of the steps for multi-lingual (ML) LP will be confusing, since SSS only supports one language. Honestly, the ML documentation should be moved to its own topics within the LP documentation. To minimize confusion. I provided internal links, so you can skip directly to the most salient sections of the topics. 

PS: For the bug-bash, the extra comments about changing the CDN URL are important, and need to be called out separately for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c747f8-17cb-209a-a503-a9caa9da8cd8
* Version Independent ID: 0a7ae298-5bd2-1327-5933-7adfd7c0975a
* Content: [Overview of the SharePoint Success Site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-sss)
* Content Source: [SharePoint/SharePointOnline/provision-sss.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-sss.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **Holland-ODSP**

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jsuddsjr 
I see that the article has been updated heavily since you created this issue and it seems there is also work currently being done on it by @Holland-ODSP 
Thanks

**Comment by Holland-ODSP** [comment]
Thanks all - this ticket can be closed. Already addressed this issue.
