### ISSUE TITLE
Misplaced mention of App Catalog in M365LP provisioning flow

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/OfficeDocs-SharePoint#2313]
`4. Wait about 30 minutes for the App Catalog to finish provisioning before adding the SharePoint Success Site.`

I feel like these instructions are misplaced. First, the user is provisioning "M365 learning pathways" in this step, not the App Catalog. The App Catalog must be provisioned first from the SharePoint Admin Center, and a freshly created App Catalog will block the provisioning process for 2 hours. I think you're referring to the wait of up to 30 minutes that occurs AFTER successfully provisioning M365 learning pathways, so this note would be better positioned AFTER the provisioning steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c747f8-17cb-209a-a503-a9caa9da8cd8
* Version Independent ID: 0a7ae298-5bd2-1327-5933-7adfd7c0975a
* Content: [Overview of the SharePoint Success Site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-sss)
* Content Source: [SharePoint/SharePointOnline/provision-sss.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-sss.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **Holland-ODSP**

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Holland-ODSP** [comment]
Hey @scanum , I addressed most of @jsuddsjr feedback in my latest revision of the articles that will get published later this afternoon. So I think we can go ahead and close the tickets unless John has more he would like to add?

**Comment by scanum** [comment]
@Holland-ODSP Yes! Thank you very much for your time and help. Appreciate it!

@jsuddsjr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
