### ISSUE TITLE
URL for web application and HNSC will never be same

### ISSUE THREAD

**Issue by Nitinkumar-Ambekar** [MicrosoftDocs/OfficeDocs-SharePoint#2314]
Following line need to be changed form:

This creates a host-named site collection that has the URL, http://portal.contoso.com, in the SharePoint Server web application that has the URL, http://**portal**.contoso.com.

to

This creates a host-named site collection that has the URL, http://portal.contoso.com, in the SharePoint Server web application that has the URL, http://**webapp**.contoso.com.

**Comment by scanum** [comment]
@Nitinkumar-Ambekar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@Nitinkumar-Ambekar Hi there. Thank you for reaching out. Could you please add the source of the problem.

**Comment by scanum** [comment]
@Nitinkumar-Ambekar We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
