### ISSUE TITLE
Mover.io - Box to M365 - File version migrated?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-SharePoint#2315]
Hi,

Could you add some info as to if file versions in Box are migrated to SharePoint Online/OneDrive for Business please?

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5366e6b-779b-29d6-1e06-a30963c4535d
* Version Independent ID: df5eaa56-f7a2-46a1-4852-2fdf70b7699a
* Content: [Mover migration - Setting up your Box source connector - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-box)
* Content Source: [migration/mover-box.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-box.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@haneef95 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @haneef95 
I think this answers your question

https://docs.microsoft.com/en-us/sharepointmigration/mover-migration-faq#does-mover-preserve-file-versions

Thanks

**Comment by scanum** [comment]
@haneef95 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
