### ISSUE TITLE
Stated Office.com support to be reviewed

### ISSUE THREAD

**Issue by markuspelto** [MicrosoftDocs/OfficeDocs-SharePoint#2316]
Should this be reviewed: "Office templates. When a user selects to create a new Office file (from **Office.com** or the Word, Excel, or PowerPoint desktop app), **the user can select the tab for your organization to see the template**s. (To use this feature on **Office.com**, users need to be assigned a license to Office 365 E3 or E5.)"

Based on our premier support reply from PG engineers, there is currently a gap in the features. Asset library templates are not supported in Office Online (Word, Excel and PP in browser). The advise is to use content types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@markuspelto Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@markuspelto thank you for reaching out and helping improve MS Docs. Please see updated article with new wording - "Office templates. When a user selects to create a new Office file (from Office.com or the Word, Excel, or PowerPoint desktop app), the user can select the tab for your organization to see the templates. (To use this feature on Office.com, users need to be assigned a license to Office 365 E3 or E5. The templates aren't available from the New menu. To create a doc from a template, go to Office.com > app start page > Office Template Library.)" Let me know if you need further assistance.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by AureliaDumitru** [comment]
@scanum , Can it also be included in the article that asset library templates are not supported in Office Online (Word Online, Excel Online) but only in Powerpoint Online? It is not clearly mentioned this. Thank you.
