### ISSUE TITLE
Under new SharePoint admin center -> Settings, there is no "classic settings page" option

### ISSUE THREAD

**Issue by legendgod** [MicrosoftDocs/OfficeDocs-SharePoint#2321]
Also I cannot find how to  show or hide the Create site command.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29978b1-a400-bacb-1330-55ed3d652053
* Version Independent ID: eae9fd16-57fc-1a80-3ce9-9b34b68eb1e0
* Content: [Manage site creation in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation)
* Content Source: [SharePoint/SharePointOnline/manage-site-creation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-creation.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@legendgod Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
