### ISSUE TITLE
Add Prerequisites for SMIT

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#2322]
In working with the PG team we found that we need access to the following Endpoints from the machine running SMIT. 

Please add these so customers can make sure they have success with SMIT. 

https://graph.windows.net

https://login.windows.net/common

https://aadcdn.msftauth.net

https://login.microsoftonline.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acade027-8af4-6581-cb4c-c5ca13abc19c
* Version Independent ID: e33ffc48-ec13-e590-270d-addc5040393a
* Content: [SharePoint Migration Identity Mapping Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-identity-mapping-tool)
* Content Source: [migration/sharepoint-migration-identity-mapping-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-migration-identity-mapping-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
