### ISSUE TITLE
Support for SharePoint 2016

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/OfficeDocs-SharePoint#2323]
We should update this to SharePoint 2016 support. Using SPMT. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migrate-to-sharepoint-online.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Padavid Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Padavid** [comment]
Sorry I maybe was not clear on the request. I was calling out that in the doc here Migrate to Microsoft 365 - Migrate to SharePoint and OneDrive | Microsoft Docs<https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online> we do not mention that we support SharePoint 2016.

[A screenshot of a social media post  Description automatically generated]

When now both SPMT and PowerShell for SPMT support SharePoint 2016.
[A picture containing bird  Description automatically generated]


Patrick David
Sr. Customer Engineer (SharePoint, O365, Teams)
Microsoft | US Education
Office: +1 (216) 750-4604
Mobile: +1 (440) 821-9586
patrick.david@microsoft.com<mailto:patrick.david@microsoft.com>
[Twitter]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=GMvICN4fL7tv9z2WXixrm%2BoC7vGIncuAIa%2FhfRRHrYw%3D&reserved=0>    [Facebook] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=7GV6giUGL4UKalzU%2FysutD3ig8I%2BdKUC0wGFEJBEw2E%3D&reserved=0>     [Linkedin] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=rZhit9e2v19xp48PflSj%2BhkM4PBYNb6GmIW%2B99O6M1s%3D&reserved=0>     [Youtube] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=1QtQ8jCahvI1CmjaY1B%2FTvTo%2Fy%2FIJpy8HCoZdOOcgT0%3D&reserved=0>
[cid:image007.gif@01D68D38.AEB1A110]

If you have any feedback about my work, please let either me or my manager Chris Ancona know at cancona@microsoft.com<mailto:cancona@microsoft.com>.
