### ISSUE TITLE
Images for step 10 and 11 are too small.

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/OfficeDocs-SharePoint#2324]
10. When you see Provisioning completed, select the CustomLearningAdministration tab as shown in the following image:

[Too small to see] Image of the M365 learning pathways solution tab

11. Select Complete as shown in the following image:

[Too small to see] Image of the M365 learning pathways solution complete button

I would reconsider how we instruct the user to return to the administration page. You might simply say:
* Close the provisioning site to return to the learning pathways administration page. 
* If you have closed the administration page, you can reopen it now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c747f8-17cb-209a-a503-a9caa9da8cd8
* Version Independent ID: 0a7ae298-5bd2-1327-5933-7adfd7c0975a
* Content: [Provision the SharePoint Success Site - SharePoint in Microsoft 365](https://review.docs.microsoft.com/en-us/SharePoint/provision-sss?branch=sss-2-provision)
* Content Source: [SharePoint/SharePointOnline/provision-sss.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-sss.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by jsuddsjr** [comment]
In other words, I'm not sure that images will be helpful here.

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jsuddsjr John, how are you?
Document has been updated after you opened this ticket with bigger images.
Thanks
@scanum please close

**Comment by scanum** [comment]
@jsuddsjr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
