### ISSUE TITLE
SharePoint Migration Tool Working Folder on a Network Location

### ISSUE THREAD

**Issue by Scottie2z** [MicrosoftDocs/OfficeDocs-SharePoint#2329]
We have had SPMT migrations fail because the C: drive ran out of space so we got the OS disk expanded to accommodate for the temp space this app needs but it just keeps needing more.  Does it make sense to set the SharePoint Migration Tool working folder to a network location?  We have file shares with many user home directories that we are trying to scan prior to migrating them to OneDrive.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
