### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by aravindmp** [MicrosoftDocs/OfficeDocs-SharePoint#233]
Osearch15 or Osearch16 (for SP2016)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757daa4f-85eb-2b0e-094a-f01b9ed3d874
* Version Independent ID: acfb92cf-1d51-d6a7-bebc-9c145f5b7710
* Content: [Install a software update for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by aravindmp** [comment]
https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/deploy-software-updates-for-sharepoint-2013
We are being redirected from this page again to the page we are addressing the correction. Should it be corrected the way I had mentioned here or as in PR #236 ?

**Comment by tseward** [comment]
@aravindmp please open a new Issue for the redirection.

**Comment by AndreaBarr** [comment]
@aravindmp -Thank you for submitting this Feedback.

From my understanding the issue of Osearch has been resolved. If the issue is not resolved please re-open this issue.
