### ISSUE TITLE
Help page on Mover.io for Office365

### ISSUE THREAD

**Issue by mozzis** [MicrosoftDocs/OfficeDocs-SharePoint#2335]
At the end, it seems like the Connect to Source step is repeated twice, while there is no step for Connect to Destination. Also, the whole thing ends abruptly at that point. I was really hoping to see what I needed (or was able) to do after the connections were made - selecting users and data, for instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da7ce00b-f843-f8d1-c949-bf4a15a53fb6
* Version Independent ID: abd7e5ff-1cee-2c1f-71ef-7b9c27b023b2
* Content: [Authorizing the Office 365 Connector - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-o365)
* Content Source: [migration/mover-o365.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-o365.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@mozzis Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
