### ISSUE TITLE
If you add files to block from syncing, then users are shown sync errors for all files of that type.

### ISSUE THREAD

**Issue by brettemery** [MicrosoftDocs/OfficeDocs-SharePoint#2338]
If you add files to block from syncing, then users are shown sync errors for all files of that type.  Please do not bother users when admins add file sync exceptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types - OneDrive](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
