### ISSUE TITLE
Documents won't move when language pack is installed

### ISSUE THREAD

**Issue by bakkus** [MicrosoftDocs/OfficeDocs-SharePoint#234]
Greetings.
I've discovered a problem on (at least) the Norwegian Language Pack for Windows 10.
It seems the Language Pack generates 3 junction points in the Documents folder called "Intern Video", "Min musikk", and "Mine bilder". These are junctions/symlinks to c:\users\%username%\Videos, c:\users\%username%\Music, and c:\users\%username%\Pictures accordingly.
Note that these are automatically generated by Windows without any user action.
These are not generated on an English install of Windows.
There might be other language packs that create similar localized files, but we've not been able to verify this yet.
We solved this at a client rollout by scripting the removal of these junctions in user context in order to get Known Folders to work as intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@bakkus - Thank you for submitting this feedback.

We appreciate you finding this potential bug. I am going to make sure we get this to the sharepoint team for investigation.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by b0bbyB** [comment]
This issue is also probably related to this:
Using an English Windows 10 with Danish langauge pack on results in the 3 folders being renamed to it's English counter parts in File Explorer: "Desktop"/"Skrivebord", "Pictures"/"Billeder", "Documents"/"Dokumenter".
All other folders are in Danish expect for the Known Folder Moved folders.

**Comment by MOKknudsen** [comment]
We have a similar experience, when we enable "Protect your important folders", then 3 DANISH folders "Billeder, Dokumenter and Skrivebord" are created under OneDrive for Business, even though the user context is English (US) locally. It should have been Pictures, Documents and Desktop. How can we fix this ?
