### ISSUE TITLE
APPDATA location 

### ISSUE THREAD

**Issue by vpo01** [MicrosoftDocs/OfficeDocs-SharePoint#235]
Can OneDrive be installed like any other app in the program files location ?
AppLocker does not work great with this....  certainly not in an enterprise environment.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8d826-fd44-b260-77e7-24d9ddd6e67f
* Version Independent ID: b0df9532-a918-a341-2790-a61a8c5c6894
* Content: [The OneDrive sync client update process](https://docs.microsoft.com/en-gb/onedrive/sync-client-update-process)
* Content Source: [OneDrive/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@vpo01 
 -thank you for submitting feedback. 

We want to make sure you can install OneDrive in a way that AppLocker works well with it. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by lusassl-msft** [comment]
@vpo01: Look at this: https://docs.microsoft.com/en-us/onedrive/per-machine-installation
