### ISSUE TITLE
Note about what an activity is is likely to be wrong

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SharePoint#2351]
Hello,

I think the statement in the note about what an activity is is wrong.

`Activity is counted as requests sent to SharePoint, such as mouse clicks.  Moving the mouse and scrolling are not counted as activity.`

There are no requests sent to the SharePoint by just clicking; a mouse click has to happen on a button or link to send a request as mentioned in the note, I think. That would make more sense because moving the mouse and scrolling isn't counted too. So clicking on an active element to trigger a link open or an action counts as activity.

Most likely the person who wrote this was right about how it works. Just the wording is a bit unclear.

Thank you for checking this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaf9fb8-afec-06b3-ed85-244a7af5b6dd
* Version Independent ID: 016c6f7d-8fd1-ba7f-ab54-a0ef1d34d026
* Content: [Sign out inactive users - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sign-out-inactive-users)
* Content Source: [SharePoint/SharePointOnline/sign-out-inactive-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sign-out-inactive-users.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@GiantCrocodile  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sowjanya365** [comment]
Hi @GiantCrocodile 

Thank you for reaching out and sharing your views. 

To clarify this, the mouse clicks are within the context of a site and there are considered as activity, and they are sent to SharePoint as an active request. 

Hope this clarifies your query. Thank you!

**Comment by GiantCrocodile** [comment]
Hi @sowjanya365! That does surprise me but makes sense. I will try to reproduce what you say and if it's successful, I will close this issue on GitHub. Thank you for your help.

**Comment by GiantCrocodile** [comment]
I can't approve this @sowjanya365. Moving the mouse around (e. g. above a menu or a SharePoint list) doesn't trigger any HTTP calls. Same with clicking on e. g. white spaces in a list or a menu. This only works if you click a button or a link. If the timeout popup occurs, a click anywhere indeed works. Maybe that's what you mean?

**Comment by sowjanya365** [comment]
Yes @GiantCrocodile! Thank you for your response on this. 

Could you please help us with the wordings what exactly needs to be updated on this page. We will review it and update as per your recommendation. Thank you so much for your contribution. 

Look forward to your response. Thank you in Advance! :)
