### ISSUE TITLE
No mention of Limitations for CSV / JSON Files.

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/OfficeDocs-SharePoint#2356]
Hi , There is no limitations listed for the CSV / JSON files.

I found an article which states no more than 500 tasks/ Jobs per CSV. And i am not sure on the JSON limitations .

But it would certainly assist users to no run into these limitations when trying to migrate at a folder level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [Format JSON or CSV for data content migration - SharePoint - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jasonwbaxter Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
