### ISSUE TITLE
Transition from the Windows Folder Redirection Group Policy objects

### ISSUE THREAD

**Issue by NickBatchelor** [MicrosoftDocs/OfficeDocs-SharePoint#2357]
Hi, I've noticed an issues with the instructions "If folders have been redirected to a network file share"

1. I've done the mover.io migration and copied the files for 1 user over to their onedrive folder; that worked a treat.
2. Then I took him out of the GPO that applied folder redirection to our local server (note; this left his desktop, docs, etc still pointing at the server, just the they weren't enforced now).
3. Then I applied the KFM Group Policy using InTune - it applies on the client, but pops up with a warning about files having the same name and for each duplicate they'll add '-Copy' to the file. I thought it would do a comparison of the files and then just sync them? 

Am I better off applying another GPO for force the desktop, docs, etc to the local C drive of the client (i.e. an empty folder)?

Thanks.

Nick

![image](https://user-images.githubusercontent.com/46203946/94792077-635c3400-03d0-11eb-8c65-6157e7dc2357.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
