### ISSUE TITLE
The site points to "Potentially Malicious" site for download

### ISSUE THREAD

**Issue by explorerv** [MicrosoftDocs/OfficeDocs-SharePoint#2359]
[Enter feedback here]
Hello team,

When trying to download the SharePoint Migration Tool we were redirected to the site https://spmtreleasescus.blob.core.windows.net/install/default.htm , which is malicious according to this report:

https://urlscan.io/result/3176db1e-425a-465a-ab67-58f806e26998/

Please advise and provide safe site for downloading.

br,
Victor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [SharePoint Migration Tool for SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
