### ISSUE TITLE
Update to reflect existence of site collection app catalogs

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#2368]
This page says things like
> You can have only one App Catalog site collection 

Which is no longer true, now that [site collection app catalogs](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog) exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc1e9c0-2e35-3357-7f57-5bd02b0e10bc
* Version Independent ID: 1443a95a-ce5b-024d-d942-001b83bf8d8c
* Content: [Distribute business apps using the App Catalog - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/use-app-catalog#see-also)
* Content Source: [SharePoint/SharePointOnline/use-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/use-app-catalog.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@fowl2  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
@fowl2 the statement is correct. You can only have a single **App Catalog** site collection per tenant as this is the global app cat. You can have one site App Cat per site collection.

There should probably be a link to an article that describes the local app cat setup, etc. process with a note on the article you linked.

Just nuance in the wording :-)

**Comment by scanum** [comment]
@fowl2  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
