### ISSUE TITLE
Disable updates in a non persistent VDI environment

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/OfficeDocs-SharePoint#2371]
How can we best disable updates in a non persistent VDI environment where it is not appropriate?

Regards
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8d826-fd44-b260-77e7-24d9ddd6e67f
* Version Independent ID: b0df9532-a918-a341-2790-a61a8c5c6894
* Content: [The OneDrive sync app update process - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-client-update-process)
* Content Source: [OneDrive/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by andykn** [comment]
HI, this has nothing to do with tenants _per se_ but any non persistent VDI environment; Citrix, VMWare etc. It's a OneDrive updater issue, the customer should be able to disable it in situations where it is not appropriate to have it try and self update,
