### ISSUE TITLE
sites from private channels

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/OfficeDocs-SharePoint#2372]
This page does not acknowledge that sites from Teams private channels cannot be managed in the admin center, although I found that information on this page: https://docs.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center
Therefore this page does not explain how to enable external sharing for Teams private channel sites. It would be helpful if you could link to the relevant PowerShell docs there. I had to open a support ticket in order to find that info. https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3106844b-caae-38c5-3c88-fb17a9d67536
* Version Independent ID: 3e88e60e-24a3-cd83-9bfc-8bc3037a86ce
* Content: [Change the external sharing setting for a site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site)
* Content Source: [SharePoint/SharePointOnline/change-external-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-external-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@mgcharumilind Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mgcharumilind  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
