### ISSUE TITLE
managing sites from Teams private channels

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/OfficeDocs-SharePoint#2373]
This page acknowledges that SharePoint sites from Teams private channels do not appear in the admin center. It would be helpful if you could link to the relevant PowerShell docs there for doing so. I had to open a support ticket in order to find this info: https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c744272-76d3-f60a-9d06-570d36ffb529
* Version Independent ID: 24208c34-c0f1-4ab0-5d92-9c3997211729
* Content: [Manage sites in the new SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center)
* Content Source: [SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
When you say "manage", what exactly are you changing? In general, changing private Team site settings is not supported (i.e. adjusting membership of the site, creating new libraries, etc.).

**Comment by mgcharumilind** [comment]
I was looking to enable a specific type of external sharing for the documents on that site. I have opened an issue for the external sharing doc page too. Support provided a PowerShell command which worked to accomplish what I needed. When I asked about documentation, they sent me that link to PS commands page.

Mary Garcia Charumilind
Director of Advanced Analytics and Applications
The Franklin Institute
mcharumilind@fi.edu
+1-215-448-2195

________________________________

**Comment by lindspea** [comment]
@mgcharumilind related issue https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2372

**Comment by scanum** [comment]
@mgcharumilind  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
