### ISSUE TITLE
Modern Document Sets?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-SharePoint#2374]
I don't see anything within the M365 SharePoint documentation regarding "Modern Document Sets" is this documented in-depth somewhere else? If so can we ensure that it is linked from here? If not can Page(s) be added to unpack this topic?

In particular would be good to have information regarding:
1) Relationship between modern Document Sets and configuration of content types within those document sets
2) Relationships and functionality between modern document sets (child documents), and retention/sensitivity labels?
3) Modern document sets and search?
4) Modern document sets and things like versioning?
5) Do modern document sets count as 1 item towards the 5,000 list view limit? Or do they count as the number of child documents in the set?
6) Differences between Folders in Modern SharePoint library, and Modern Document Sets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1787d668-b65b-8de4-a182-2b22b43e429e
* Version Independent ID: 64957a69-2f4b-3947-d631-ac9c29e6f68b
* Content: [Introduction to SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/introduction)
* Content Source: [SharePoint/SharePointOnline/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/introduction.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
