### ISSUE TITLE
Query rule vs. Bookmark

### ISSUE THREAD

**Issue by Stacey-Crutcher** [MicrosoftDocs/OfficeDocs-SharePoint#2375]
This [page](https://docs.microsoft.com/en-us/sharepoint/manage-query-rules) speaks about query rules in Microsoft 365 and how they apply to classic search, "As a global or SharePoint admin in Microsoft 365, you can improve search results in the classic search experience by creating and managing query rules." If Query rules are created at the root level (tenant level/organization level) they appear in the out-of-box M365 search result page too. So how are query rules different from bookmarks? When should I use one over the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f082d30-62d1-e099-8307-5ab5c15d410f
* Version Independent ID: 24906b5f-8745-96f9-0f79-3dc67f1e6720
* Content: [Manage query rules - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-query-rules)
* Content Source: [SharePoint/SharePointOnline/manage-query-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-query-rules.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
