### ISSUE TITLE
Cannot Find Storage Option for a Site

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/OfficeDocs-SharePoint#2377]
Could not find the storage option for a site. Clicking on a site opens a window or the right but there's no Storage option there.

We have one site that is out of space at 4.9 GB, when our SharePoint account has 1.29 TB and it's set for Automatic storage size at the top level. What do we change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits#manage-individual-site-storage-limits&solutionType=AlchemyInsight&title=Manage%20your%20SharePoint%20Online%20storage&clientAppName=ConciergeWidget)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
