### ISSUE TITLE
SPMT error code 0x01110009

### ISSUE THREAD

**Issue by marschallphilipp** [MicrosoftDocs/OfficeDocs-SharePoint#2378]
I´m getting error code 0x01110009 (Scan File Failure:Could not retrieve file's metadata) even I have read permissions on the file share I would like to migrate to SPO.

Error code 0x01110009 is not published on troubleshooting site (https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues).

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
