### ISSUE TITLE
Organizational Assets Library not displaying templates

### ISSUE THREAD

**Issue by Mandylf** [MicrosoftDocs/OfficeDocs-SharePoint#2379]
I have followed the process to create the Org Asset Library, the images work fine, and I can use them in the News Posts. However, the template library doesn't display the documents?  I open the Office application, and can see that the Org Asset Library has been set up, the thumbnail is visible, but when I select it, i get a message saying “we couldn’t find any templates in this location”

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
