### ISSUE TITLE
SPMT File Size Limit

### ISSUE THREAD

**Issue by harp365** [MicrosoftDocs/OfficeDocs-SharePoint#2380]
Hi,

Not sure how to phrase this as the last attempt just got closed down. So I will try and phrase differently.

Please update the documentation to include this limitation or better yet still, get the SPMT tool to align with the latest SP limit of 100GB, not 15GB which it currently seems to be adhering to.

Thanks

Henry

**Comment by scanum** [comment]
@harp365 Please link the documentation you are referring to. Thanks!
