### ISSUE TITLE
Links have been removed - incomplete article - SCANNING

### ISSUE THREAD

**Issue by heymybru** [MicrosoftDocs/OfficeDocs-SharePoint#2381]
[Enter feedback here]

The links have been removed in the scanning section of this document. Can the wording be changed or the documentation updated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f08a57-d8a0-86d8-d81e-b1d8d6c34644
* Version Independent ID: 024af5b6-c33b-d571-1bdb-4a2934432984
* Content: [Mover Migration Tools overview and planning - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-plan-migration?source=docs)
* Content Source: [migration/mover-plan-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-plan-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@heymybru Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@heymybru thank you for pointing this out. Does this look like a link to be added - https://docs.microsoft.com/sharepointmigration/mover-running-migration

**Comment by heymybru** [comment]
Yes this is exactly what I expecting

**Comment by scanum** [comment]
@heymybru  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
