### ISSUE TITLE
Correction on step #1

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/OfficeDocs-SharePoint#2382]
Under Sync Process, step #1 says " Azure on-premises to Azure AD" . However, there is no such thing as Azure on-premises. AAD Connect synchronizes from **AD** to Azure AD. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ff426d-6bba-75ea-970b-03f16fe191b5
* Version Independent ID: 51db9ad2-9e46-4391-601a-062b640b00d2
* Content: [About user profile synchronization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/user-profile-sync)
* Content Source: [SharePoint/SharePointOnline/user-profile-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/user-profile-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@josuvil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@josuvil  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
