### ISSUE TITLE
Migrate a List item with multiple versions with attachments to SPO

### ISSUE THREAD

**Issue by vianeyhm** [MicrosoftDocs/OfficeDocs-SharePoint#2384]
[Enter feedback here]
Hello experts,
This settings do not clarify if I can migrate from SharePoint 2010 or higher to SPO a list item with multiple versions and where any version includes an attachment, for example, If I have 3 versions for a list item in SP 2010 on-prem where each one has an attachment, when they are migrated to SPO, only the last version of that list item shows the attachment, the previous versions of the same item shows the attachment field empty. No sure if it is not covered by SPMT or if I need to do something additional for that and the documentation does not clear about it. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad86450-d9ac-4cc4-fc75-63f8b285c298
* Version Independent ID: d1e8c85a-b365-78c0-be1a-5a03ee082491
* Content: [Available settings in SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-settings)
* Content Source: [migration/SPMT-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPMT-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@vianeyhm Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by vianeyhm** [comment]
Hi Manuela;

My concern about the content info is that it does not mention if what we need to do related with the list item versions and their attachments is supported by SPMT and it is why we would like to know if it´s possible, if it isn't, it does not make sense to open a break-fix ticket.

Thanks in advance!
Best regards;
Vianey
________________________________
De: Manuela Scanu <notifications@github.com>
Enviado: miércoles, 21 de octubre de 2020 05:45 a. m.
Para: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
CC: vianeyhm <marquez_v11@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Migrate a List item with multiple versions with attachments to SPO (#2384)


@vianeyhm<https://github.com/vianeyhm> Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
