### ISSUE TITLE
Is the "Access control: network location" requires AAD Premium license?

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/OfficeDocs-SharePoint#2386]
I believe the "[access control from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)" requires an AAD Premium license, but I don't think this "[access control based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location)" requires an AAD Premium license. It should work without AAD premium license.
Hence, I would recommend to delete the "important" notice" from [this ](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location) document, it makes customer to confuse.

Further info,
[This ](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#security-and-compliance-features) article doesn't mention the "Access control: network location" requires AAD Premium license. so

/////////////////////
Security and compliance features
Unless otherwise noted, the following features are available across all plans that include SharePoint, and all SharePoint standalone plans:
Access control: network location
Access control: unmanaged devices. Requires Azure AD Premium P1.
/////////////////////

**Comment by o365tatsuyan** [comment]
or either change "important" notice like below;
/////////////////////
Important
Azure AD conditional access policies are used for device-based controls. In order to use these, an Azure AD Premium P1 or P2 subscription is required.
/////////////////////

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
