### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by tmacardail** [MicrosoftDocs/OfficeDocs-SharePoint#2387]
The following link is broken. Posters, email templates: customizable templates to generate internal awareness and excitement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@bratsche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@tmacardail thank you for pointing this out and helping improve MS Docs. Please let me know if this link could be the correct link - https://resources.techcommunity.microsoft.com/templates-downloads/
