### ISSUE TITLE
Add statement on default on SharePoint sharing setting when creating team with sensitivity label that blocks guests

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SharePoint#2388]
Can you make it explicitly clear what the default SharePoint sharing setting when creating a Team/ Group that has a container sensitivity label that blocks guests to the Team group  or created via PowerShell or Graph API with guest access blocked.

I  am sure the the rules as stated below still stand and the Share{pint site has sharing of "New and existing guests. 

_Even if your organization-level setting allows external sharing, not all new sites allow it by default. The default sharing setting for Microsoft 365 group-connected team sites is "New and existing guests." The default for communication sites and classic sites is "Only people in your organization."_

This is a risk as Admins & User will assume that if the Teams has blocked Guests then the SharePoint site will be created as with the permission "Only people in your organization."

I recommend adding an explicit statement/ warning to highlight the risk
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nikki-c thank you for helping improve MS Docs. Do you think adding any of these links to the article would help? - https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide, https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide,  https://techcommunity.microsoft.com/t5/microsoft-teams/allow-or-block-guest-users-from-a-specific-team-in-microsoft/m-p/175918?

**Comment by nikki-c** [comment]
Hi. the links you have provided are irrelevant.
The issue is when you have guest access enabled in the tenant and you switch off guest access to a Team either via PowerShell or sensitivity labels to teams  then this action will only stop teams owners from adding guests to the Team. The associated SharePoint site permissions are not changed. they are stall existing and new guest. this means even if you have blocked Teams from being added to your Team you should also update your SharePoint site external sharing permissions for the Teams site to only people in your organisation.  I think this should be highlighted in a warning message that the PowerShell or Sensitivity label only impact the Team/groups and not the associated SharePoint site. If you want to restrict access to the SharePoint site this must be actioned separately. Too many admins think that by switching guest access off for a team then the SharePoint site sharing permissions are automatically changed.   The only page I can think that may be suitable to linking to is this one  https://docs.microsoft.com/en-us/microsoft-365/solutions/configure-teams-three-tiers-protection?view=o365-worldwide as this give the examples of what controls need to be changed when controlling different types of information

**Comment by MikePlumleyMSFT** [comment]
@lindspea this article is also worth a link:

[Settings interactions between Microsoft 365 Groups, Teams and SharePoint](https://docs.microsoft.com/microsoft-365/solutions/groups-sharepoint-teams-governance)

**Comment by nikki-c** [comment]
This is part useful.

However it is missing a section that describes the effects of Teams settings on SharePoint online.

For example
When Guests are enabled in Teams and in a specific Team is created with guests access blocked the corresponding external sharing settings in SharePoint online are not automatically changed. The sharing setting will remain New and existing users. If you want to stop the ability for users to share files externally then the sharing settings in SharePoint will need to be manually changed

Nikki Chapple
Organisational Change Manager
United Kingdom | Cloud Communications
NTT

T:
+442080800656
M:
+447500766185
E:
n.chapple@arkadin.com<mailto:n.chapple@arkadin.com>

NTT Cloud Communications UK Ltd. is an entity of NTT Ltd.

[cid:image001.jpg@01D6B6A9.8D7D0F80]<https://arkadin.com/> [cid:image003.jpg@01D6B6A9.8D7D0F80] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~>  [cid:image005.jpg@01D6B6A9.8D7D0F80] <https://www.linkedin.com/company/arkadin/>  [cid:image007.jpg@01D6B6A9.8D7D0F80] <https://www.facebook.com/ArkadinCloudComm>  [cid:image009.jpg@01D6B6A9.8D7D0F80] <https://www.instagram.com/globalntt/>  [cid:image011.jpg@01D6B6A9.8D7D0F80] <https://www.youtube.com/user/ArkadinConference>
[cid:image013.jpg@01D6B6A9.8D7D0F80]<http://www.arkadin.com/>

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
