### ISSUE TITLE
Recommendations aren't shown on all newly-created pages and news posts by default

### ISSUE THREAD

**Issue by jmountforduk** [MicrosoftDocs/OfficeDocs-SharePoint#2389]
The article states that "recommendations are shown on all newly-created pages and news posts by default". However, this isn't the case. When a page is created the toggle doesn't appear until the page is edited after being published for the first time. I've had previous engagement through the support team about this and told this was expected behaviour while the feature is in early-release phase, but this document contradicts that guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173d4704-81ff-4501-81b7-ef1f00d06c80
* Version Independent ID: 65e585b9-07b6-1efd-39ee-c5ad5c01f547
* Content: [How SharePoint page recommendations are generated - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint_page-recommendations)
* Content Source: [SharePoint/SharePointOnline/sharepoint_page-recommendations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint_page-recommendations.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@jmountforduk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jmountforduk thank you for reaching out and helping improve MS Docs. Could you perhaps send me a suggestion of what you would like changed/added in this article?

**Comment by jmountforduk** [comment]
Recommendations aren't shown on all newly-created pages and news posts by default - a user has to go back in to edit the page after it's been published to enable on the page using the toggle.

The [support document](https://support.microsoft.com/en-us/office/sharepoint-page-recommendations-12bf4c4e-3452-4575-afd4-ef7536b027fa?ui=en-us&rs=en-us&ad=us) that the page links to states that "this feature is in an early release phase" with a link to the roadmap that doesn't display the item.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@jmountforduk  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
