### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by jwood-msft** [MicrosoftDocs/OfficeDocs-SharePoint#2395]
Got to this page by clicking on a link in the Mover CSV upload get more information. "Please read our handy guides for more on submitting a CSV." https://docs.microsoft.com/en-us/SharepointMigration/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1f689c-0eb0-ad35-3786-ed4ce23be240
* Version Independent ID: b57f3ca3-041f-3cfc-f79b-8eb7fd55f745
* Content: [Welcome to SharePoint Migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/SharepointMigration/#feedback)
* Content Source: [migration/index.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/index.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jwood-msft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jwood-msft Thank you for reaching out. It looks like the link has been fixed in the interim. Please confirm.

**Comment by get-itips** [comment]
I think @jwood-msft refers to the link in this screen inside Mover

![image](https://user-images.githubusercontent.com/36666927/112466049-29973500-8d44-11eb-995c-3cfca1648e48.png)

However that link isn't on the Docs site, so we can not edit it, we will try to pass this information on.

Thank you!

**Comment by scanum** [comment]
@officedocspr  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
