### ISSUE TITLE
Files >15GB - Scan File Failure:File size exceeds limit (SPMT)

### ISSUE THREAD

**Issue by DewayneHyatt** [MicrosoftDocs/OfficeDocs-SharePoint#2397]
We are not able to migrate files larger than 15GB to Teams/OneDrive despite both services supporting up to 100GB files. We're migrating file servers to cloud storage and this has added a lot of complexity and manual work to an otherwise wonderful process using SPMT.

When can we expect SPMT's file size limitations to align with the limitations of the SPO service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@DewayneHyatt Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DewayneHyatt** [comment]
The error "Scan File Failure:File size exceeds limit" is not listed on the Troubleshooting common SPMT issues and errors page and there is no mention in the documentation anywhere that there is a 15GB file size limit until you actually run into the error during a migration. This is why I left the feedback on this particular page. The tool, the documentation, and the products it supports are all out of alignment.
