### ISSUE TITLE
This feature isn't fully deployed yet

### ISSUE THREAD

**Issue by SafM123** [MicrosoftDocs/OfficeDocs-SharePoint#2399]
I created an organisation assets library and had a number of issues. After raising a ticket with MS, I was told that this feature isn't fully deployed. There is no ETA of when it will be fully working. The article does not state this. It only states that it isn't available for Germany, China and US government plans.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SafM123 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SafM123** [comment]
Morning Manuela,

I have raised a ticket with MS and that is what they told me, that the feature isn’t fully deployed and that there is no ETA on when it will be. I provided the feedback so that other users are aware of this as it does not mention it on the documentation.


Kind Regards,
Safinaz
