### ISSUE TITLE
Link to Azure Active Directory Module goes to MS connect which has retired

### ISSUE THREAD

**Issue by JonathanHerschel** [MicrosoftDocs/OfficeDocs-SharePoint#24]
It appears Azure Active Directory Module in MS connect is retired.  Should the modules from MSOnline and MSOnlineExtended be updated as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d499cfa0-9a8e-37c8-4607-874d3d72ed69
* Version Independent ID: 267ded1d-8e8d-3d11-44b4-3e83c70d40c8
* Content: [Configure server-to-server authentication from SharePoint Server to SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-server-to-server-authentication#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md)
* Service: **unspecified**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Link fixed. Thanks for spotting that.
