### ISSUE TITLE
Where to ask your technical questions about SPMT

### ISSUE THREAD

**Issue by MRuimerman** [MicrosoftDocs/OfficeDocs-SharePoint#2400]
Where can I ask my questions about the SharePoint Migration Tool. I have some specific questions about user mapping. 

The Docs article links to the SharePoint Migration Tool Feedback and Support Forum, but this will be closed on November 4 and looks like it is not active anymore. It directs you to a general Microsoft Q&A but there is no subtopic for SPMT.

**Comment by scanum** [comment]
@MRuimerman Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
