### ISSUE TITLE
Using SharePoint Migration Tool to migrate: SOURCE folders are created as DESTINATION folders

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/OfficeDocs-SharePoint#2401]
Scenario:

Migrating files from C:\SOURCE\ (selected as source).

Migrating to Team called TEAM to Channel called DESTINATION.

Result: The SMT migrates content of C:\SOURCE\ to a folder under the Channel DESTINATION called SOURCE

Expected: Only Content of C:\SOURCE\ should be migrated, not into a Folder with the name SOURCE (just like if I copied from C:\SOURCE\ to D:\DESTINATION\ I wouldn't end up with a folder called D:\DESTINATION\SOURCE).

**Comment by scanum** [comment]
@RipRapRob Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
