### ISSUE TITLE
Sample Configuration Manager package detection code

### ISSUE THREAD

**Issue by RykarrONE** [MicrosoftDocs/OfficeDocs-SharePoint#2402]
The sample Configuration Manager package, detection script has an error in the code.

The following line does not capture the version information in the log file:
Write-Log "Version found:$OneDriveFile.VersionInfo.FileVersion"

The log shows the following information:
Date Time Version found:c:\users\username\appdata\local\microsoft\onedrive\onedrive.exe.VersionInfo.FileVersion

The correct command is:
Write-Log "Version found: $($OneDriveFile.VersionInfo.FileVersion)"

This updated code shows the following in the log:
Date Time Version found: 20.169.0823.0008

**Comment by scanum** [comment]
@RykarrONE Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
