### ISSUE TITLE
Web Only Limited Access

### ISSUE THREAD

**Issue by kevincrossman** [MicrosoftDocs/OfficeDocs-SharePoint#2409]
I am seeing a permission level "Web Only Limited Access" but I can't find any documentation regarding this permission level. Seems like it should be here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels#feedback)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@kevincrossman Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
