### ISSUE TITLE
Impact of rename on PWA (Project Web App) site 

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SharePoint#2413]
Is it possible to include the Impact of changing site address on a PWA (Project Web App) site? It seems these type of sites cannot be renamed but we need to make the documentation more clearer. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@rachoksh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
@WayneEwington can you please confirm?

**Comment by WayneEwington** [comment]
@kaarins Site Rename does NOT support renaming PWA sites. In the article we do state which types of sites are supported versus explicitly naming which ones we don't. I'm not sure what the best option here is although I don't believe that explicitly naming the "black list" is the right approach.

**Comment by kaarins** [comment]
Incorporated into note. Thank you!
