### ISSUE TITLE
Not Working with Format from Article

### ISSUE THREAD

**Issue by mTooki** [MicrosoftDocs/OfficeDocs-SharePoint#2415]
I created the CSV using the 6 columns needed.  I'm getting an error when trying to upload the file stating the header id could not be found.  I was able to get this to work with csv using Source Path,Destination Path as the headers and just using the destination URL with folders ndded.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
