### ISSUE TITLE
Clarify/officialize the following permissions figures for "Everyone Except external Users"

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/OfficeDocs-SharePoint#2417]
1) For a **public** site if it is allowed to change the "Everyone Except Exertnal Users" group permission from Edit to Read (Visitors Group)
2) For a **private** site if it is allowed to add "Everyone Except External Users" to the Visitors SP group.

Right now both are possible and no background jobs reverting these changes (this has not been the case a while ago). However this is not what is documented. What is being documented and how permissions behave should be consistent and reflected in all M365 tenants.

_Please note that you cannot change default permissions granted to "Everyone except external users" on Microsoft 365 group-connected team sites._
[https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups](https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
