### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by gbalanced** [MicrosoftDocs/OfficeDocs-SharePoint#2418]
I am a Microsoft FastTrack Engineer that is trying to get end user materials for a migration to OneDrive for Business and the following links under **Onboarding related resources** are broken:

Microsoft 365 adoption guide: https://devfasttrackv4storage.blob.core.windows.net/marketing/en-us/resources/Microsoft%20365%20User%20Adoption%20Guide.pdf
Posters, email templates: https://fasttrack.microsoft.com/office365/resourcehub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dd9b09-7975-6ac0-fa4e-2c09c17c2045
* Version Independent ID: e34a0e26-2f32-98fe-a7d3-01033d6f3a7e
* Content: [Box to OneDrive Migration Guide - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/box-to-onedrive-and-sharepoint-migration-guide#onboarding-related-resources)
* Content Source: [migration/Box-to-OneDrive-and-SharePoint-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Box-to-OneDrive-and-SharePoint-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@gbalanced Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting. @gbalanced
