### ISSUE TITLE
Comment and questions

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/OfficeDocs-SharePoint#2420]
Hello, I have a comment and a couple of questions:

1) It seems there is a typo here: "The tenant where the site will be provisioned must have the App Catalog installed and have the latest version of M365 learning pathways. installed."

It should be "The tenant where the site will be provisioned must have the App Catalog installed and have the latest version of M365 learning pathways installed." (without extra space and period between "pathways" and "installed")

2) Does "provision" in this doc means "configure"/"set up", or does it mean "to provide contents for"?

3) Is "M365 learning pathways" available in other languages? If so, could you provide me with a easy way to access the French version?

Thanks and best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c747f8-17cb-209a-a503-a9caa9da8cd8
* Version Independent ID: 0a7ae298-5bd2-1327-5933-7adfd7c0975a
* Content: [Provision the SharePoint Success Site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-sss)
* Content Source: [SharePoint/SharePointOnline/provision-sss.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-sss.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Hi François,

Thank you so much for your feedback.


  1.  Corrected the typo
  2.  Think of the word “provision” as downloading and then setting up in your tenant. Its how we talk about using the PnP service to download templates from the look book<https://docs.microsoft.com/en-us/sharepoint/add-sample-site#start-provisioning>.
  3.  Yes, it is available in French. Check out this article<https://docs.microsoft.com/en-us/office365/customlearning/custom_overview_ml>, and let me know if you don’t find what you need.


Take care,


Holland

**Comment by scanum** [comment]
@FranNev  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
