### ISSUE TITLE
This page is entierly blank.

### ISSUE THREAD

**Issue by gbeaudoin78** [MicrosoftDocs/OfficeDocs-SharePoint#2421]
This page is entierly blank. Is that normal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1f689c-0eb0-ad35-3786-ed4ce23be240
* Version Independent ID: b57f3ca3-041f-3cfc-f79b-8eb7fd55f745
* Content: [Welcome to SharePoint Migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/SharepointMigration/)
* Content Source: [migration/index.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/index.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@gbeaudoin78  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@gbeaudoin78 Hello, do not know at the time you browsed it however the page/article is working ok.
Thank you

**Comment by scanum** [comment]
@gbeaudoin78  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by gbeaudoin78** [comment]
Thanks you!
