### ISSUE TITLE
the SMTP Service MAX HOP Count of 15 is to low

### ISSUE THREAD

**Issue by mikelee-msft** [MicrosoftDocs/OfficeDocs-SharePoint#2423]
Many customers experience intermittent incoming mail failures due to the default "MAX HOP" count setting of 15 in the SMTP Service properties.  This setting is too low considering our end-to-end network security devices of today.

We should make a note in this article stating that the MAX HOP count should be increased to 30 to prevent these intermittent incoming mail failures.

**Comment by scanum** [comment]
@mikelee-msft Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mikelee-msft** [comment]
This is an  On-Prem article and this is an On-Prem issue. I'm recommending guidance to proactively help customers when they are building their on-prem SharePoint Farms.
