### ISSUE TITLE
Onedrive per machine installs

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/OfficeDocs-SharePoint#2425]
Would you please clarify if a machine is already on per user setup, does that version, even if it's already higher than suggested below have to be uninstalled first or can a new installation simply be run over the top using the /allusers switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine - OneDrive](https://docs.microsoft.com/en-us/OneDrive/per-machine-installation?WT.mc_id=M365-MVP-4040055)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@alanbmhs Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by alanbmhs** [comment]
Hi Manuela,
I have received a reply from MS and they state that the Onedrive sync app can be run over the top of any existing per-user installation. I’ve now tested this and it does work. I now have another issue with the document in that it states in the first para that it can be installed in either Program File (x86) or Program Files depending on the architecture but then under the heading Deployment Instructions it states it will be installed in the x86 directory. So how do I install it in the Program Files directory on a 64 bit OS installation?

Alan.
