### ISSUE TITLE
Is there a min supported SharePoint level for tool

### ISSUE THREAD

**Issue by cloudedturtle** [MicrosoftDocs/OfficeDocs-SharePoint#2432]
I am working with a customer that is using an RTM version of SharePoint 2010 (running on SQL Server 2008 R2 build 10.50.1617) and we are seeing a number of issues running the SQL commands from the analyzer. my assumption is that this is because the tool is looking for some command/scripts/queries that were released in updates to SharePoint 2010. 

Can you please confirm the min viable farm/SharePoint version for the tool and update the prerequisite information as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [SharePoint Migration Assessment Tool - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@cloudedturtle Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
