### ISSUE TITLE
Issues with information on the page

### ISSUE THREAD

**Issue by GavinTinnellySIT** [MicrosoftDocs/OfficeDocs-SharePoint#2433]
Hi Team,

From reading this page it would seem that its possible to restrict access to Onedrive and Sharepoint via the browser on devices that are not azure ad registered. This doesn't seem to be the case, i had a case open with support and they confirmed this. Could this documentation please be updated to reflect what actually needs to be done in order to resolve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@GavinTinnellySIT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by GavinTinnellySIT** [comment]
Hi guys, 

Any updates on this? I'm wondering if you're investigating it to redo the document or if you have a solution in mind?

**Comment by get-itips** [comment]
Hello @GavinTinnellySIT How are you?
I am taking over this issue you created, and I would like to understand better.
Did you "blocked access" tenant-wide and you could still access from unmanaged device's browser ?
Thanks

**Comment by get-itips** [comment]
Hello @GavinTinnellySIT I am returning to check if you could see my question here, thank you

**Comment by GavinTinnellySIT** [comment]
Hi Andres,

Im so sorry for the late reply on this.

I  have a client who looks after elderly people. Recently I moved their files to SharePoint and it’s been working great, but we noticed a slight snag – we wanted to stop users accessing SharePoint and OneDrive via the 365 portal on personal devices.
I read up on how this can be done and I found this article that explained the process https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices
We Azure AD Joined all users laptops & desktops, thus giving them the Azure AD Registered status in the portal. From the article above it sounded like this was all I needed for the policy to work – turns out its not the case.

My client wants this: they want all staff who have a company device (azure ad joined) to have the ability to access everything as normal , but If someone signs into www.office.com on a non azuread joined device (laptop/desktop/mobile) they should not get access to SharePoint or OneDrive, but they should still be able to open Teams and Outlook. Is this possible?


Gavin Tinnelly
Cloud Services Engineer
supportIT
Unit 10 Manor Street Business Park, Manor Street, DublinD07 TR26, Ireland
E: gtinnelly@supportit.ie
T: + 353 (0) 1-902-2112
w: www.supportIT.ie
This email, its contents and attachments contain information from supportIT it may be privileged, confidential or otherwise protected from disclosure. The information is intended to be for the addressee(s) only. If you are not an addressee, any disclosure, copy, distribution, or use of the contents of this message is prohibited. If you have received this email in error please notify the sender by reply e-mail and delete the original message and any copies. supportIT trading as Tarjo ltd. Company number 484262. 
Dedication
​Knowledge
​Trust
​Technology

**Comment by get-itips** [comment]
Hello @GavinTinnellySIT how are you?

Thanks for returning and explaining your scenario in detail.

When you select "Block Access" in "unmanaged devices" as explained in this article, a Conditional Access rule is created in AAD (as explained in the article), with certain conditions, one of these conditions is that the application affected is Office 365 SharePoint Online, if you view this rule, you will see this warning message, confirming that also Teams will be affected.

![image](https://user-images.githubusercontent.com/36666927/105851888-4d8b0400-5fa9-11eb-82b0-c6f44e81985e.png)

Hope this information helps you.

**Comment by GavinTinnellySIT** [comment]
Hi Andres,

Yes I seen that message. But, even if I was to enable that policy it doesn’t work, it doesn’t distinguish between an Azure AD Joined device and a non Azure AD device. It blocks access for everyone.


Gavin Tinnelly
Cloud Services Engineer
supportIT
Unit 10 Manor Street Business Park, Manor Street, DublinD07 TR26, Ireland
E: gtinnelly@supportit.ie
T: + 353 (0) 1-902-2112
w: www.supportIT.ie
This email, its contents and attachments contain information from supportIT it may be privileged, confidential or otherwise protected from disclosure. The information is intended to be for the addressee(s) only. If you are not an addressee, any disclosure, copy, distribution, or use of the contents of this message is prohibited. If you have received this email in error please notify the sender by reply e-mail and delete the original message and any copies. supportIT trading as Tarjo ltd. Company number 484262. 
Dedication
​Knowledge
​Trust
​Technology

**Comment by get-itips** [comment]
> Hi Andres, Yes I seen that message. But, even if I was to enable that policy it doesn’t work, it doesn’t distinguish between an Azure AD Joined device and a non Azure AD device. It blocks access for everyone. Gavin Tinnelly

Hello **Gavin**, how are you? Hope you are doing good! In that case, as I do not have in my lab a hybrid Azure AD joined device to test, the best would be to open a support ticket, as you already have a support ticket open, I encourage you to come back and share the outcome of it, if in any case, the documentation needs to be improved somehow.

**Thank you**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
