### ISSUE TITLE
Prerequisites broken link -- Microsoft SQL Server 2012 native client

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#2436]
there are broken links in prerequisites installer
Installation fails by script or via GUI, apparently due to broken link in 
Microsoft SQL Server 2012 Service Pack 1 (SP1) Native Client (installs with Microsoft SQL Server 2012 Feature Pack)

[sp2016.pdf](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/5530331/sp2016.pdf)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
