### ISSUE TITLE
Applicability of feature to GCC

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-SharePoint#2437]
The first Note on the page mentions that the feature is not yet available to GCC tenants.

However, the Note comes directly after two bullets about sub-features and does not specify whether it applies only to the second sub-feature (Office Templates) or to the entire Feature (Organization Asset Libraries).

Please consider:
a). moving the Note to the top of the page, if the entire Feature is not available to GCC tenants, OR
b). editing the Note to be clearly specific to the sub-feature (Office Templates) not being available to GCC tenants, if indeed that is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@sparkitect Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@sparkitect  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
