### ISSUE TITLE
MIssing information

### ISSUE THREAD

**Issue by RascoPK** [MicrosoftDocs/OfficeDocs-SharePoint#2439]
I got t this page from mover.ie.
Page is empty and should coning infomration from link called "Please read our handy guides for more on submitting a CSV."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1f689c-0eb0-ad35-3786-ed4ce23be240
* Version Independent ID: b57f3ca3-041f-3cfc-f79b-8eb7fd55f745
* Content: [Welcome to SharePoint Migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/SharepointMigration/)
* Content Source: [migration/index.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/index.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@RascoPK Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@RascoPK thank you for reaching out. I've just looked through the article and I see it was recently updated. I can't find the link you are referring to. Please can you check and let me know.

**Comment by scanum** [comment]
@RascoPK  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
