### ISSUE TITLE
The Base URL is incorrect- it should be https://pnp.github.io/custom-learning-office-365/sss/

### ISSUE THREAD

**Issue by declawson** [MicrosoftDocs/OfficeDocs-SharePoint#2440]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5e30b9-c57e-52e0-e6b4-d1598ad446fc
* Version Independent ID: 1d182504-5c6c-8fa1-a21f-92a0b0d4d6d1
* Content: [Add SharePoint Success Site content to your M365 Learning Pathways solution - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/add-sss-cdn#add-the-sharepoint-success-site-cdn)
* Content Source: [SharePoint/SharePointOnline/add-sss-cdn.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/add-sss-cdn.md)
* Service: **sharepoint-online**
* GitHub Login: @pamgreen-msft
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
