### ISSUE TITLE
Example format of URLs in Sample CSV did not work. Replacing URL Encoding with original character did work.

### ISSUE THREAD

**Issue by JamesGMorrison** [MicrosoftDocs/OfficeDocs-SharePoint#2441]
The sample CSV shows URL encoding for spaces in the names of document libraries (i.e. %20 for a space).
This did not work for me. However, replacing the %20's with the original spaces did work.

The current example shows this (which did not work for me):
https://TENANT01.sharepoint.com/sites/SiteName/Shared%20Documents | https://TENANT02.sharepoint.com/sites/SiteName/Shared%20Documents

This example shows the format which did work for me:
https://TENANT01.sharepoint.com/sites/SiteName/Shared Documents | https://TENANT02.sharepoint.com/sites/SiteName/Shared Documents

-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a91832-871e-c850-9852-20694814354a
* Version Independent ID: a6a00872-be3f-f759-a492-00f619aecd32
* Content: [Mover - Create a new migration with a CSV file - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-create-migration-csv)
* Content Source: [migration/mover-create-migration-csv.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-create-migration-csv.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@JamesGMorrison  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
