### ISSUE TITLE
Overwrite and delta functionality within the tool

### ISSUE THREAD

**Issue by rfinneyWork** [MicrosoftDocs/OfficeDocs-SharePoint#2444]
Hi there 

One thing in the FAQs that I couldn't find is whether there is the ability to do Delta syncs within the tool and if what what level of functionality is there around it i.e. only upload modified files or newly created files?

Also what is the default behaviour of the tool? Does it overwrite by default?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@rfinneyWork Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
