### ISSUE TITLE
Cannot find Search Reports in SC Admin?

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/OfficeDocs-SharePoint#2445]
I can't find any link to "Search Reports" in Site Collection admin, so if you're retiring the search usage reports in one month, how can I answer "what are our users searching for on our Intranet"? Does the page have to use a specific template to have "Search Reports" in site collection admin? Does it not support Hub sites?
Regards // Kristoffer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4931479-b37a-8350-aba7-13f87937ecc6
* Version Independent ID: 52da4c04-0646-1d3a-39cd-ddce72c2f811
* Content: [View search usage reports - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/view-search-usage-reports)
* Content Source: [SharePoint/SharePointOnline/view-search-usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-search-usage-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@stoff75 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
