### ISSUE TITLE
The libary doesnt shows up

### ISSUE THREAD

**Issue by grumm90** [MicrosoftDocs/OfficeDocs-SharePoint#2446]
Hi,
I did the steps according to this article: 
https://docs.microsoft.com/en-us/sharepoint/organization-assets-library
The command ran successfully but the folder doesn't show up in any office app.
For Get-SPOOrgAssetsLibrary command, it shows the site I added and OrgAssetType : OfficeTemplateLibrary.
I tried to restart, sing in out from office, delete the cache but still don't works.
Could you please advise?
Regards,
Gabor

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by grumm90** [comment]
It seems like we just had to wait. It took 2 days to work. CDN was really slow this time.
Thanks,
Regards,
Gabor
