### ISSUE TITLE
UPN change time

### ISSUE THREAD

**Issue by BrogieB** [MicrosoftDocs/OfficeDocs-SharePoint#2447]
UPN change timing seems to take longer than "hours" should be updated to days. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes?source=docs)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
