### ISSUE TITLE
Migration Manager - Agent States

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/OfficeDocs-SharePoint#2449]
Could you please provide some additional documentation about the different agent "States" and what they mean? I have an agent that was working, but now it says it is "Disconnected". Also there isn't any information inside the O365 SharePoint Microsoft Admin  site regarding what might be wrong. My task is Queued up to run but appears to be stuck.

I am also seeing that the SharePoint Migration Service is stopped. When I attempt to restart it just stops again. I've tried restarting the machine without luck.
![Screenshot 2020-11-17 153748](https://user-images.githubusercontent.com/1613085/99454128-99effe80-28eb-11eb-9cac-ea8d7d0732da.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by robertcaretta** [comment]
Wow. Thanks for the standard response, I guess. I'm providing feedback
about your documentation. I think it needs more details. I wouldn't have
opened this if I didn't think it was needed. That's regardless of a support
ticket.

**Comment by JoanneHendrickson** [comment]
Hi Robert:  @robertcaretta   

Thank you for taking the time to provide feedback -- I am the author of this topic and will definitely include a table that gives more information on states and what they mean. Please continue to help me improve the content -- I welcome your suggestions!
Joanne
