### ISSUE TITLE
I get error 0x0201000C	(Check your credentials and then re-enter your username and password) in the middle of a Migration

### ISSUE THREAD

**Issue by bartwillemkorn** [MicrosoftDocs/OfficeDocs-SharePoint#2451]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05218c9e-0104-3116-2f0e-b5a53b2c9b75
* Version Independent ID: b680d4fa-78e9-6a3d-cd3e-0686c187018d
* Content: [Troubleshooting Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-troubleshoot)
* Content Source: [migration/mm-troubleshoot.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-troubleshoot.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by bartwillemkorn** [comment]
I get error:
The user 'domain\user' does not have enough permission to access 'http://xyz/ListName' (ErrorCode: 0x0201000C) OriginalMessage: Credential Issue when doing SP Query
 The remote server returned an error: (401) Unauthorized
In the middle of a migration of a document library, being a site collection admin, how is that even possible?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
