### ISSUE TITLE
Please document how Vanity URL can be used

### ISSUE THREAD

**Issue by rogereriksen** [MicrosoftDocs/OfficeDocs-SharePoint#2453]
It is not very obvious how Migration Manager can use "Vanity URL". What is the use case?

Roger

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 327723fa-dd54-7777-e39c-d70514eb41f7
* Version Independent ID: ef4968aa-d845-19a0-f1c4-3a04d812c37a
* Content: [What's new in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-whats-new)
* Content Source: [migration/mm-whats-new.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-whats-new.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
