### ISSUE TITLE
When was the disable OneDrive Profile creation introduced?  

### ISSUE THREAD

**Issue by alexlevin11** [MicrosoftDocs/OfficeDocs-SharePoint#2454]
When was the disable OneDrive Profile creation introduced?  We had been looking for a solution like this for years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
