### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/OfficeDocs-SharePoint#2455]
Hi,

I have a question regarding this sentence: "You'll need to know the path of the file share and enter it using the format: \contoso\fileshare."

As this whole guidance page is about helping a "generic" user, why using "contoso" in the file share path? Shouldn't it be "name_of_your_organization" or something like that instead? Or is this guidance based on demo files?

Also, does "fileshare" mean "name of your file share"?

Thanks for help and best regards,

François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341198a2-dad6-ea64-2bf6-7e0faec6771e
* Version Independent ID: e2da40fd-880d-6519-c31f-8f1d35f30794
* Content: [How to use Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-how-to-use)
* Content Source: [migration/mm-how-to-use.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-how-to-use.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@FranNev Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
