### ISSUE TITLE
Instructions out-of-date

### ISSUE THREAD

**Issue by ErikPederson61** [MicrosoftDocs/OfficeDocs-SharePoint#2459]
It appears as if the individual OneDrive sharing may have been removed. Following the steps in this article, once I reach step 4, there is no OneDrive tab for a selected user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Change the external sharing setting for a user's OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/user-external-sharing-settings)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ErikPederson61  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ErikPederson61, thank you for your feedback.

I tested it, and the OneDrive tab is there in my demo tenant:
![image](https://user-images.githubusercontent.com/33589238/100643467-d6beeb00-3318-11eb-944e-1db367641d6c.png)

**Comment by dariomws** [comment]
If you still cannot see the tab, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
