### ISSUE TITLE
Changing the default search scope for a Hub site

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/OfficeDocs-SharePoint#246]
I noticed the sentence: "A hub will default to only showing content from its own associated sites, but it's easy to configure it to include other related sites as well, even if those sites are associated with different hubs." . When looking at the upper right search text box, I don't see an 'easy' way to change the scope to include associated an non-associated sites  Whereas, changing the search  scope settings we see in the Highlighted  Content Web Part is a doddle.  Can you please explain what you mean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites#feedback)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@westerdaled Thank you for this feedback.

I'll get this over to the SharePoint team for investigation and updating. 
I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
The documentation in that area will be changed to link to some supplementary information that will elaborate on the site association process.  You can find out more by visiting the link [here](https://support.office.com/en-us/article/associate-a-sharepoint-site-with-a-hub-site-ae0009fd-af04-4d3d-917d-88edb43efc05).

**Comment by scanum** [comment]
PR #245
