### ISSUE TITLE
Web-Only Limited Access? 

### ISSUE THREAD

**Issue by qubika** [MicrosoftDocs/OfficeDocs-SharePoint#2460]
Could an entry be added for the 'Web-Only Limited Access' permission level?  

If this carries the same properties as Limited Access then it would seem sufficient to add a note / update the existing section instead of adding a new row.  Either way I'm looking for a formal documentation update which can be referenced?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/understanding-permission-levels?redirectSourcePath=%252fen-us%252farticle%252funderstanding-permission-levels-in-sharepoint-87ecbb0e-6550-491a-8826-c075e4859848)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@qubika we just added that in PR #2461. Should be live on the site later today.

**Comment by scanum** [comment]
@qubika Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
