### ISSUE TITLE
Not showing up in Powerpoint on Win/Mac

### ISSUE THREAD

**Issue by cb2206** [MicrosoftDocs/OfficeDocs-SharePoint#2466]
Hi,
I followed the instructions and got a successful response from the powershell commandlet to add the asset library. But neither in Powerpoint for Mac nor Windows is the Asset Library showing up. We are using Microsoft 365 Business Premium and based on the description of the page, my understanding is that the asset library should show up in the installed office apps but the web versions would require E3/E5.
Is there some delay or so until the asset library shows up?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
There is a delay, I believe up to 24 hours. I don't believe this is compatible with macOS Office.

**Comment by cb2206** [comment]
Indeed, they just started showing up - in Powerpoint for Windows and(!) macOS. Great!

**Comment by cb2206** [comment]
@scanum It may be good to add a comment to the documentation that there is a delay of around 24 hours for published files showing up in Powerpoint. This is not only during initial setup but also if you upload new .potx files to the Sharepoint site.
