### ISSUE TITLE
Microsoft Forms File Upload questions will break when the site URL is changed

### ISSUE THREAD

**Issue by rebeccadh-s** [MicrosoftDocs/OfficeDocs-SharePoint#2469]
The "Effects of changing a site address" section should also state that if the site being renamed is a M365 Group-connected site that has any group forms in Microsoft Forms, the File Upload questions in those forms will break. The questions will need to be recreated in order for responders to upload files again. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@rebeccadh-s Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
@WayneEwington should we add this info?

**Comment by WayneEwington** [comment]
Although this does appear to be an edge case, it should be added to the list of known limitations.

**Comment by kaarins** [comment]
Added info. Thanks!
