### ISSUE TITLE
How about Integrated SSRS?

### ISSUE THREAD

**Issue by rgshah26** [MicrosoftDocs/OfficeDocs-SharePoint#247]
Will Integrated SSRS be supported in SharePoint 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019 Public Preview](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
@rgshah26 , this is a SQL Server Reporting Services decision to remove SharePoint Integration. See, https://blogs.msdn.microsoft.com/sqlrsteamblog/2016/11/17/simplifying-our-sharepoint-integration-story/

**Comment by rgshah26** [comment]
Agreed, but if Integrated SSRS is removed from SharePoint, it should be documented in this article.  That's the point i was trying to make. :)

**Comment by tseward** [comment]
@rgshah26 I think what @bentoncity was raising was that this is a SQL Product Group decision, not a SharePoint PG decision. This means the documentation resides with the SQL PG rather than the SharePoint PG.

With that said, @bentoncity perhaps a link off to the SQL PG announcement from this page might be something to look at?

**Comment by rgshah26** [comment]
I agree with Trevor that a link to SQL PG announcement from this page would be sufficient.  My point is that I will be sending a link to this article to our end users, and when they read this article, i want them to be aware that their Integrated SSRS reports will not work in SharePoint 2019.  The end users do not understand or care who (SharePoint PG or SQL PG at Microsoft) is responsible for the technology behind the scene.  They only care that their reports will not work in SP19.

**Comment by tseward** [comment]
@rgshah26 I'll see if I can find the proper space/wording for this tonight and put in a PR.

**Comment by AndreaBarr** [comment]
@rgshah26 Thank you for this feedback

From my understanding Trevor has submitted a pull request to resolve this issue. I am going to close this as resolved. If this update didn't resolve the issue please reopen this issue.

**Comment by DeanGross** [comment]
I'm not seeing anything in the content that addresses this issue.

**Comment by tseward** [comment]
@DeanGross can you open a new issue on this?

Thanks
