### ISSUE TITLE
There is no 64 bit version...

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/OfficeDocs-SharePoint#2471]
"With the new per-machine installation option, you can install OneDrive under the "Program Files (x86)" or "Program Files" directory (depending on the OS architecture)" ... at least none I can find. I have downloaded a fresh copy of OnedriveSetup.exe and installed it several times now using the /allusers switch and it always installs in the x86 folder even though we only have 64 bit W10 installs. Is the document:
(a) wrong;
(b) premature in that the 64 bit version is in development; or
(c) am I missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine - OneDrive](https://docs.microsoft.com/en-us/OneDrive/per-machine-installation?WT.mc_id=M365-MVP-4040055)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@alanbmhs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kaarins Kaarin, how are you? Can you help me confirm that the architecture image of onedrive is available only in 32 bit? I tested and always installs under \program files (x86)\ looks like the sentence was added [here](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1618/).

**Comment by kaarins** [comment]
Hi @get-itips , we're working on a PR to fix this. Thanks!

**Comment by get-itips** [comment]
> Hi @get-itips , we're working on a PR to fix this. Thanks!

Hello, @kaarins can you kindly tell me if there were any news? Thank you!

**Comment by kaarins** [comment]
The team is working on it, but it has not yet rolled out: https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/11575911-make-onedrive-64-bit

**Comment by get-itips** [comment]
> The team is working on it, but it has not yet rolled out: https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/11575911-make-onedrive-64-bit

Thanks @kaarins do you think we should update the article until this is rolled out? Thanks

**Comment by get-itips** [comment]
Hello!, getting back to this thread, as the Public Preview for OneDrive 64 is out, (per the uservoice) I installed it using `/allusers` switch on a lab machine and it got installed in `C:\Program Files\Microsoft OneDrive`.
@scanum I think we can close this thread now. Thank you all!
