### ISSUE TITLE
Please elaborate on the different kinds of users/roles involved when using mover.io

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/OfficeDocs-SharePoint#2476]
1. There could be two different organizations involved in the mover process, still this is not addressed at all. Please elaborate.

2. Who should do the move?  Is it a user from the source or a user from the destination?
    - What privilege's are needed in the source and the destination?
    - How does the source control and/or limit what can be moved?
    - Does the privilege's of the user who is logged to mover.io in any way affect what can be moved?

3. Are you supposed to login with a personal account on the mover.io site? What if that person get's sick or ran over by the buss in the middle of the migration project, how can then someone else access the mover setup and continue the migration project?

4. What is a **migrator users**?
    - A user who uses/runs/do a migration at the mover.io site?
    - An "impersonate as" user, which is used to run the migration done at mover.io?
    - or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da13f61a-6d45-7150-3037-819b5b6df40c
* Version Independent ID: 6384527d-aa00-3709-1191-72600c44b6d5
* Content: [Mover - Create a new migration - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-create-migration)
* Content Source: [migration/mover-create-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-create-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Bartolomeus-649  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Bartolomeus-649 
1) I think you refer to 365 Tenant to Tenant, right? I could authorize the source with one tenant and the destination with another tenant, using the same mover account.

2) I think you can choose here whatever you want/can, remember that you authorize a connector using either local or destination credentials, depending on the type of connector.

3) You could setup a migration account...

4) With that option enabled, after the admin gave consent, tried to re-authorize the connector using a regular user, but couldn't until I explicitly added the user a role for the application.

Hope this clarifies it to you.
