### ISSUE TITLE
How to restrict sites owners from removing association?

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/OfficeDocs-SharePoint#2480]
[Enter feedback here]
There might be cases where sites are associated to hub site automatically via Site Design but associated site owner has a possibility to remove this association. So how we can block associated site owners from removing the association?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@prashant1380 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
