### ISSUE TITLE
"Failed to acquire token silently" when Conditional Access Policies apply

### ISSUE THREAD

**Issue by tmsvl** [MicrosoftDocs/OfficeDocs-SharePoint#2482]
The migration tool gives an unclear "Failed to acquire token silently as no token was found in the cache. Call method AcquireToken" error during the installation process if Conditional Access policies apply to Sharepoint logons. Temporary disabling those Conditional Access policies allows you to proceed in the installation process.

Policy names (not sure which one of the two blocked the access):
[SharePoint admin center]Block access from apps on unmanaged devices
[SharePoint admin center]Use app-enforced Restrictions for browser access 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
