### ISSUE TITLE
License Required for SharePoint Admin?

### ISSUE THREAD

**Issue by jreinhardtproarch** [MicrosoftDocs/OfficeDocs-SharePoint#2484]
The bubble that shows on this link that " Global admins, SharePoint admins, and site admins all need to be assigned a SharePoint license." may need some clarification. Is this truly still a requirement? If so is it a technological requirement? A license compliance requirement? I have not had issue recently with SharePoint Online administration with using a global admin or SharePoint administrator account that didn't have a license. If it is a licensing compliance issue where it may work but you're not in compliance, then that's a serious concern since in such a case it appears to not be enforced and it is also a rare requirement that an admin needs to be licensed. But if it just has technical issues, then that might be acceptable to still do what you can do without a license. If it is only a technological issue, maybe a statement that "...admins all need to be assigned a SharePoint license. If you don't, you may have issues with administration." Thanks for your time.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7461c2ef-3439-2c86-4dde-8992b62bf9a7
* Version Independent ID: faa4e3aa-8ec4-f1f1-d4bd-4058999545f3
* Content: [About the SharePoint admin role in Microsoft 365 - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-admin-role)
* Content Source: [SharePoint/SharePointOnline/sharepoint-admin-role.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-admin-role.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jreinhardtproarch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
It's a license compliance/terms of service requirement. While any user can access SharePoint/OneDrive without a license (the service doesn't perform license enforcement), including users holding admin roles, if they use the service they must be licensed.

**Comment by jreinhardtproarch** [comment]
Hi Trevor, obviously we can accept the statement in this article if it is true. However, the reason you give I question. Administering the service is not using the service. The administrator does not benefit from using the service by administering it. This question has significance concerning partners who may only administer a SharePoint Online environment for a customer without actually using it themselves because they are paid only to administer it for those who use it. I would ask for further review by someone else if it wouldn't be too inconvenient. Thank you for your response.

**Comment by tseward** [comment]
> Administering the service is not using the service. 

_Technically_ correct. I should restate: _accessing_ the service. As an admin, you do this in a variety of ways be it the web UI, PowerShell, etc.

Partners should contact Microsoft Partner support with any licensing questions.
