### ISSUE TITLE
OneDrive (Desktop) no longer an option when creating Microsoft 365 Apps application in Intune

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/OfficeDocs-SharePoint#2488]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/38565287/101959834-c128ab80-3bcb-11eb-9b4c-bf3c3bb7c78f.png)

I saw it there a week or two ago when I tried this method of creating a OneDrive app for Intune. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-intune)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rasldasl** [comment]
It seems this feature was removed by the M365 Apps team. 
https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-office365
Note says "Deployment of OneDrive through Intune is not supported."
