### ISSUE TITLE
SPOL extranet advice

### ISSUE THREAD

**Issue by MrNigel** [MicrosoftDocs/OfficeDocs-SharePoint#249]
Does this page need updating in relation to Teams external sharing? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c998e7f7-f18f-24fe-74bd-a7cb92a9a115
* Version Independent ID: 1806bc13-c8bb-b667-5c40-62800ada160d
* Content: [Use SharePoint Online as a business-to-business (B2B) extranet solution](https://docs.microsoft.com/en-gb/sharepoint/create-b2b-extranet)
* Content Source: [SharePoint/SharePointOnline/create-b2b-extranet.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-b2b-extranet.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@MrNigel Thank you for this feedback

I will get this over to the SharePoint team for investigation and updating. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
Hello! Thank you for bringing up this issue.  I was wondering if you would be able to elaborate a little bit more on why you think the linked doc might be outdated in relation to Teams external sharing? Thanks!
