### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by teamneroblanco** [MicrosoftDocs/OfficeDocs-SharePoint#2490]
Hi there,  

This page talks about a Public API under the API Servers section, but doesn't have a link to the public API itself.  Is it possible to add a link to this public API?

Regards
Twan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a322ff-ef0c-3e25-5989-cc1f0b4ed57e
* Version Independent ID: d6dacddd-72cd-9ef1-ceb8-adf7b1cc8e2a
* Content: [Mover services migration security - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mover-security)
* Content Source: [migration/mover-security.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-security.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
