### ISSUE TITLE
This doc is not-sync with current version of OneDrive app for mac (ver. 20.169.0823.0006)

### ISSUE THREAD

**Issue by SeRgI1982** [MicrosoftDocs/OfficeDocs-SharePoint#2494]
[Enter feedback here]

Hi,

Today I have installed OneDrive app for mac - the latest version from the microsoft web page (ver. 20.169.0823.0006)
My MacOS Catalina ver. 10.15.07

After instalation and syncking with my OndDrive account, I have found a correct .plist file in location: ~/Library/Preferences/com.microsoft.OneDrive.plist
but this file is completely unreadable in texteditor and in XCode shows different properties than described in this document.

What I need to know ?

I do drag&drop functionality using Xamarin and mac app.
When I drop file from OneDrive folder I have path to this file.
I would like to check if file path belongs to OndDrive folder path (DefaultFolderLocation from this documentation).
DefaultFolderLocation should give me also TenantId. 
Having TenantId I would like to get access to App folder in the cloud (I guess using OneDrive API).
At the end, dropped file should point to an appropriate web url (the file in OneDrive in the cloud).

Can you tell me how those things are working with current version of OneDrive app for mac ?

Best regards,
Lukas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#feedback)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
