### ISSUE TITLE
search service hangs on Pause sharepoint 2013 paused by system Cant resume via powershell too?

### ISSUE THREAD

**Issue by mohammedisteyaq** [MicrosoftDocs/OfficeDocs-SharePoint#25]
($ssa.IsPaused() -band 0x80) -ne 0 this gave me True and I tried many times to resume the application also tried force resume which returned False to me. Tried many things then checked the Instance of search service application with command: 
Get-SPEnterpriseSearchServiceInstance
"Status      : Provisioning " 
So I gave below commands to make it online:
$ssa = Get-SpEnterpriseSearchServiceInstance
$ssa.status=0
$ssa.update()
$ssa
This made it online and After this everything looks fine so I opened CA and went to Search Application. From there I clicked on Pause/resume link in Search service application. And It resumed the Search service application. 
That redirected me on crawl page. Where I could see the "start full crawl" (earlier they were not visible under pause state) buttons that means my application was online. 
I checked admin component Get-SPEnterpriseSearchAdministrationComponent with supplying search service application and that was showing me index location path and initialized status true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0ba5bd-cc19-bb57-b16c-1ecb16becc8e
* Version Independent ID: ec016404-f9bd-7318-5162-1ec538bc7b3b
* Content: [Manage a paused Search service application in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/manage-a-paused-search-service-application)
* Content Source: [SharePoint/SharePointServer/search/manage-a-paused-search-service-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/manage-a-paused-search-service-application.md)
* Service: **unspecified**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by Techwriter40** [comment]
@tklarsen please review and respond.  thanks

**Comment by mohammedisteyaq** [comment]
what to review I see only profile of https://github.com/tklarsen ?

No solution page there.

*Thank you,*
*Mohammedisteyaq Mansuri*
*SharePoint Consultant*
*+1732 956 7288 <(732)%20956-7288>*

**Comment by Techwriter40** [comment]
mohammed, this was a note for the writer who owns the topic. she will review the request and get back to you.. thank you.

**Comment by mohammedisteyaq** [comment]
ohk thats fine. Thank you for that support.

*Thank you,*
*Mohammedisteyaq Mansuri*
*SharePoint Consultant*
*+1732 956 7288 <(732)%20956-7288>*

**Comment by kenwith** [comment]
@mohammedisteyaq - sorry for the delay on this and that it has gone stale in the documentation issues. I know it has been a very long time so I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mohammedisteyaq** [comment]
I already solved it posted the solution  and you forwarded it to
https://github.com/tklarsen for review my solution. If u can see mail trail
you will come to know.

**Comment by kenwith** [comment]
Great, thank you!
