### ISSUE TITLE
Which versions of Office support Organizational Asset libraries?

### ISSUE THREAD

**Issue by dustinwalsh** [MicrosoftDocs/OfficeDocs-SharePoint#2502]
[This article](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library) needs to clarify which versions of Office support this feature. My (template) asset library is showing up in the M365 clients, but I'd like to know if my users with Office 2016 Pro Plus will be able to utilize this?

Also, the templates show up in PowerPoint Online, but not Word Online (even after clicking More Templates).

**Comment by scanum** [comment]
@dustinwalsh  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
Thank you for submitting this issue. I updated the article with the version info.

**Comment by get-itips** [comment]
> Thank you for submitting this issue. I updated the article with the version info.

Thanks @kaarins !
