### ISSUE TITLE
Typo in path

### ISSUE THREAD

**Issue by sdaudet-ua** [MicrosoftDocs/OfficeDocs-SharePoint#2506]
Missing \ in the path below before <username>
[Enter feedback here]
Question: Where are local Migration Manager logs stored?
Answer: The logs are stored here: C:\Users<Username>\AppData\Roaming\Microsoft\SPMigration.
                                                                         ^
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@sdaudet-ua  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @sdaudet-ua
