### ISSUE TITLE
Third party identity providers

### ISSUE THREAD

**Issue by zburtondbrs** [MicrosoftDocs/OfficeDocs-SharePoint#251]
Hello,

Your document mentions that silent account config does not work for devices that require MFA. Does it work for environment that use third-party identity providers? https://docs.microsoft.com/en-us/office365/enterprise/about-office-365-identity#third-party-authentication-and-identity-providers

I opened a support case on this issue, and they didn't know what a third-party IdP was...

Thanks,
Zane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@zburtondbrs Thank you for this feedback

I will get this over to the SharePoint team for investigation so we can find an answer about these third party IDP's.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
Yes, this does support third party IDPs with some caveats.  For more information, please look into this page and the links on it. I will make sure to include this information in the doc for more clarity.  Thanks!
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-compatibility
