### ISSUE TITLE
SPMT Migration Tool Option Setting -StartMigrationAutomaticallyWhenNoScanIssue not able to put on false

### ISSUE THREAD

**Issue by pixel-maniac** [MicrosoftDocs/OfficeDocs-SharePoint#2511]
Hi Ladies and Gents,

I am doing onedrive migrations and I cant set the option -StartMigrationAutomaticallyWhenNoScanIssue for the SPMT tool through powershell to false. I use the -scanonly:$true and -StartMigrationAutomaticallyWhenNoScanIssue:$false.
However when the SPMT is registered the file globalsettings.csv it stays the options is set to True.
I only want to pre-scan and not migrated straight away. Now it is scanning and migrating.
Am I doing something wrong or not?

SPMT version SPMT 3.4.121.1 Beta, Also tested 3.4.120.1 and 3.4.120.7 all have the same issue.
Fresh installed server win 2016 with powershell

**Command**
`Register-SPMTMigration -SPOCredential $O365Credential -Force -IgnoreUpdate -UseCustomAzureStorage:$true -CustomAzureStorageAccount <secrect> -CustomAzureAccessKey <secrect> -WorkingFolder P:\Reports -IncludeHiddenFiles:$false -ScanOnly:$true -StartMigrationAutomaticallyWhenNoScanIssue:$false`

**globalsettings.csv**
Setting,Value
Migration auto re-run,False
User mapping file,
Use custom Azure storage,True
Enable encryption,True
Azure account,sssss
Azure key,sssss
Delete temporary files when migration is done,False
Migrate file version history,True
Keep all versions,True
Filter out created date before,
Filter out modified date before,
Filter out files with extensions,
Filter out sites with names,
Filter out lists with names,
Filter out content types with names,
Automatic user mapping,True
Preserve user permission for SharePoint Server,True
Preserve user permission for File Share,False
Filter out hidden files,False
Migrate OneNote folder as OneNote notebook,False
Temporarily allow migration of scripts,False
**Only Perform Scan,True**
**Start Migration If No Scan Issue,True**
Preserve Permission Inheritance,True
Migrate Site Settings,PRESERVE_ALL_SETTINGS
Skip List With Audience Enabled,True
Migrate All Web Fields ContentTypes,False
Migrate Navigation,True
Migrate Managed Metadata,False
Migrate Pages Options,RENAME
Replace invalid characters in files and folder,False
Replacement of invalid characters in files and folder,
Working Directory Path,P:\Reports

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pixel-maniac** [comment]
Hi Manuela,

Is there somebody that can test it and confirm?
I have opened a ticket for microsoft through the company tentant.

However it would be nice to see if someone else is experiencing the same issue.

Thanks!

________________________________
Van: Manuela Scanu <notifications@github.com>
Verzonden: zaterdag 26 december 2020 03:51
Aan: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
CC: pixel-maniac <sharif.m@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] SPMT Migration Tool Option Setting -StartMigrationAutomaticallyWhenNoScanIssue not able to put on false (#2511)


Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
