### ISSUE TITLE
How to create a Sharepoint link that will only work for Microsoft Team members

### ISSUE THREAD

**Issue by arthurlichtenberger** [MicrosoftDocs/OfficeDocs-SharePoint#2512]
It seems like a very basic and important Sharepoint link sharing option in Microsoft Teams would be the ability to create a share link that will only work for Team members. Guests would not be able open, or at least not be able to edit. If the link was listed on a website, it would only work for team members. I haven’t been able to figure out how to do this, or if it is even possible. Such a basic and security important scenario should be addressed in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
