### ISSUE TITLE
Joke?

### ISSUE THREAD

**Issue by psumi** [MicrosoftDocs/OfficeDocs-SharePoint#2513]
This is a joke, right? Otherwise I'd be spending days before opening another MS365 tenant, like I spent before finding a name for my child.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
