### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by hbwheat** [MicrosoftDocs/OfficeDocs-SharePoint#2515]
Hello, 

This particular government environment setting does not work. The azure file storage location will still point to commercial and error out

. As well, the setup process that is identified before installation doesn't follow the flow of how the app installation works. The application never presents a "welcome" in such a way to edit the config file to the setting listed. The application installs and even setting the config option after installation doesn't take effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ceaa921-290f-7730-e787-2ee040d616ae
* Version Independent ID: a0140e51-138c-7cf5-1f6c-ac66a0588a6c
* Content: [Migration Manager Government Cloud settings - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-gov-cloud)
* Content Source: [migration/mm-gov-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-gov-cloud.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
