### ISSUE TITLE
SharePoint Migration tool not pulling over correct Metadata

### ISSUE THREAD

**Issue by jamesmcdonagh** [MicrosoftDocs/OfficeDocs-SharePoint#252]
I am migrating data from an on-premise file server to SPO. When the content is migrated the default columns labeled 'Created By' and 'Modified By' both list 'Builtin\Administrators' as the value. What can I do to have the actual usernames that created the file show up? 

Thank you,
James

**Comment by AndreaBarr** [comment]
@jamesmcdonagh Thank you for this feedback

We want to get this issue with the migration tool handled quickly. Support will be able to handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
