### ISSUE TITLE
Prevent users from syncing libraries and folders shared from other organizations

### ISSUE THREAD

**Issue by edmund-davis** [MicrosoftDocs/OfficeDocs-SharePoint#2521]
Enabling this policy also blocks us from synchronizing with our own SharePoint On-premises farms. If we have both on-premises and online SharePoint, how can we mark the internal SPO sites to allow OneDrive to synchronize with them?  Would adding them to the Intranet Zone work?

**Comment by scanum** [comment]
@edmund-davis Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
