### ISSUE TITLE
How to do the reverse of "provision" user space in SharePoint/OneDrive?

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/OfficeDocs-SharePoint#2522]
The page on (pre-)provisioning user space in SharePoint/OneDrive is very clear.

But how about remove the space in the case that user account still exists?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization - OneDrive](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@cheesecracker Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
