### ISSUE TITLE
Clarification on 'Configure team site libraries to sync automatically' limit

### ISSUE THREAD

**Issue by danielcecil** [MicrosoftDocs/OfficeDocs-SharePoint#2523]
The documented item limit for the policy setting 'Configure team site libraries to sync automatically' is 5,000 which seems rather low.  

Other documentation states that the limit is 300,000 across all synced libraries: https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#sync 

I have tested this policy using a large library and there is no physical limit imposed, though possibly a performance hit if rolling out the policy to many users at the same time.

Please can this be clarified in the documentation as to why there is a 5,000 item limit on this policy.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@danielcecil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @danielcecil Dan, how are you?
I dug into this and the note in the article you opened the issue for is specifically about the TenantAutoMount policy.
I hope this information helps you,

**Comment by get-itips** [comment]
@scanum please close.
