### ISSUE TITLE
Does not install per-machine

### ISSUE THREAD

**Issue by scottbreenmsft** [MicrosoftDocs/OfficeDocs-SharePoint#2526]
This configuration does not result in OneDrive being installed as a per-machine configuration. OneDrive is still installed as a per-user install.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-intune#deploy-the-onedrive-sync-app-to-windows-10-devices)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@scottbreenmsft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @scottbreenmsft Scott, how are you? Hope you are doing great.
Out of Intune, I tried OneDriveSetup (version 21.62.328.1) using the `/allusers` switch and it got installed on `c:/program files (x86)/` (per-machine), it seems this version honored the switch, did not see the same with past versions. It seems this is tied to the binary used, (maybe not intune?), did you try this lately Scott? Thank you!

**Comment by scottbreenmsft** [comment]
Hi there @get-itips, my comment on this article is that we suggest that installing OneDrive via the Microsoft 365 Apps in Intune instaslls OneDrive as per machine which is not the case. 

If I install OneDrive using OneDriveSetup and the /allusers switch then is works for me as wel.

**Comment by get-itips** [comment]
Ok @scottbreenmsft I see you are from the Intune team, will suggest moving that sentence to the end of the article, I think that sentence at the beginning of the procedure might be the origin of the confusion.
Thank you!

**Comment by scottbreenmsft** [comment]
I've submitted a PR and worked with Kaarin on this. Maybe cancel you PR?

**Comment by scottbreenmsft** [comment]
My PR: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/pull/3465

**Comment by get-itips** [comment]
> My PR: [MicrosoftDocs/OfficeDocs-SharePoint-pr#3465](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/pull/3465) @get-itips
Great that you worked with Kaarin, can you verify the link? does not work for me. Thanks

**Comment by scottbreenmsft** [comment]
An updated doc should be published in the next 24/48 hours
