### ISSUE TITLE
List tempalte 301 It is not supported

### ISSUE THREAD

**Issue by albegut** [MicrosoftDocs/OfficeDocs-SharePoint#2528]
List template 301 Posts is not supported by SPMT or SharePoint Online. If you start a migration with one list with that template you will always have the same error:

"Invalid SharePoint Online list 'Demo list post template'","ACTION_STOP","0x0201000D"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390c33f7-7e70-6741-2a61-9538b87bec0a
* Version Independent ID: c3be3fb4-c28b-5513-651a-fe8b174a0a33
* Content: [SharePoint Migration Tool supported SharePoint List templates - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates)
* Content Source: [migration/sharepoint-migration-supported-list-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-migration-supported-list-templates.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@albegut Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JoanneHendrickson can you kindly confirm with the SPMT team what @albegut is saying here? Thank you

**Comment by get-itips** [comment]
> List template 301 Posts is not supported by SPMT or SharePoint Online. If you start a migration with one list with that template you will always have the same error:
> 
> "Invalid SharePoint Online list 'Demo list post template'","ACTION_STOP","0x0201000D"


Hello @albegut Alberto, revisiting your message, can you give me some extra details

What source of migration are you trying to use?
What version exactly of SPMT?
Also, have you seen this?

> Error Code | Recommended action
> -- | --
> 0x0201000D | Check if the list exists or if you can access it in the source site and target site.

https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues

Thanks for the clarification.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
