### ISSUE TITLE
Classic site list page was deprecated

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/OfficeDocs-SharePoint#2529]
Classic site list page was deprecated last year (Oct 29th 2020).
Explanation of "Site list" should be modified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd224d48-9dab-31ae-6548-2e929bd62d7c
* Version Independent ID: 6a98ec78-5f74-266f-61a5-95dfdcf673e9
* Content: [Find site collection features in the new SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/site-collections-page#site-list)
* Content Source: [SharePoint/SharePointOnline/site-collections-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/site-collections-page.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mitanabe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @mitanabe
