### ISSUE TITLE
WSS and STS

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#253]
In the slipstream section, it says you need to get both the WSS and the SharePoint server update package.  This is no longer the case.  SharePoint server update packages include everything you need (includes the WSS updates as well).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e94d7c-469a-d1f1-667a-b36802bd2062
* Version Independent ID: b34a46ae-aa69-f0ab-2d68-22443f748ffa
* Content: [Prepare to deploy software updates for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/prepare-to-deploy-software-updates)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/prepare-to-deploy-software-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/prepare-to-deploy-software-updates.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Looks like this was a copy/paste from SharePoint 2016[/2019], where you do need wssmui/sts-x-none packages. Can update this to reflect the individual package(s) you want to slipstream.

**Comment by AndreaBarr** [comment]
@danmyhre Thank you for this feedback

From my understanding Trevor has submitted a pull request to resolve this issue. I am going to close this as resolved. If this update didn't resolve the issue please reopen this issue.
