### ISSUE TITLE
classic settings page is no longer available since 01/01/2021

### ISSUE THREAD

**Issue by simonTIG** [MicrosoftDocs/OfficeDocs-SharePoint#2531]
Since 01/01/2021 the classic settings page is no longer available and this setting cannot be changed anymore.

We need another official method, currently I have to go through the MS support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96de5069-51dc-3934-ec44-cae3ab121476
* Version Independent ID: 21955afd-18c1-20f0-061f-f552f71fbfc1
* Content: [Hide the OneDrive and SharePoint app tiles - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/hide-app-tiles-on-app-launcher)
* Content Source: [SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/hide-app-tiles-on-app-launcher.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@simonTIG Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @simonTIG 
I could successfully enter the classic settings page using the instructions in the article
I checked on several tenants, isn't it available for you?

![image](https://user-images.githubusercontent.com/36666927/104328072-113bac00-54b1-11eb-8c87-ea210deb63a4.png)

Thank you

**Comment by simonTIG** [comment]
Hi,

Yes I can see it, I somehow missed it and was distracted by this message:
[cid:86ec410f-1cd7-4ee3-b7c6-8b0682585243]


It's my bad, but I would add a screenshot to the page just in case 😉


Thanks a lot for following up.


Best regards

[https://static.theitguys.ch/files/email/global/icon/THE-IT-GUYS.png]
Simon Cateau

Technical Architect

The IT Guys Sàrl

Helping you win with IT

[https://static.theitguys.ch/files/email/global/assets/phone-icon-2x.png]
+41 22 552 01 11<tel:+41225520111>
[https://static.theitguys.ch/files/email/global/assets/email-icon-2x.png]
simon.cateau@theitguys.ch<mailto:simon.cateau@theitguys.ch>
[https://static.theitguys.ch/files/email/global/assets/link-icon-2x.png]
theitguys.ch<https://redirect.theitguys.ch/email/theitguys.ch>
[https://static.theitguys.ch/files/email/global/assets/address-icon-2x.png]
Chemin des Mollies 36, CH-1293 Bellevue
Get our weekly email<https://redirect.theitguys.ch/email/weekly>



________________________________

**Comment by get-itips** [comment]
> Hi, Yes I can see it, I somehow missed it and was distracted by this message
thanks for returning and confirming @simonTIG

**Comment by get-itips** [comment]
@scanum please close.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
