### ISSUE TITLE
SharePoint 2013 Database Server Requirements

### ISSUE THREAD

**Issue by alexjebens** [MicrosoftDocs/OfficeDocs-SharePoint#2533]
According to the following article SharePoint 2013 database servers (including SQL Server 2014) must be installed on Windows Server 2012 or 2008SP2. 

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md#minimum-software-requirements

@SerdarSoysal 

Is it really true that I have to install an older version of Windows Server for the databases than is supported by SharePoint 2013 FE and App Servers (2012R2) or is this information outdated? 

Can I not simply go by the supportability Matrix of the SQL Server version (e.g. SQL Server 2014 supports up to Windows Server 2019)?

**Comment by scanum** [comment]
@alexjebens Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by alexjebens** [comment]
I would also like to add that the same paragraph does not list support for SQL Server 2014 meaning that this document contradicts itself.

**Comment by get-itips** [comment]
Hello @alexjebens Alexander, how are you? Currently looking into this...

**Comment by tseward** [comment]
This article needs to be updated to follow the supported OS guidelines of SQL Server and should probably just link to https://docs.microsoft.com/en-us/troubleshoot/sql/general/sql-server-windows-8-later-versions.
