### ISSUE TITLE
Outdated List Link

### ISSUE THREAD

**Issue by cdorazi** [MicrosoftDocs/OfficeDocs-SharePoint#2539]
The first link to the work list in this paragraph goes to a video of a classic list.  It should go to a modern list

"Collect and manage content using SharePoint pages. Use lists for information you might collect in Excel. Lists enable you and your audience to gather, track, and share information. Improve the display of lists with column and list view formatting using the List web part. Use libraries to store documents. Easily add, reorder, sort, filter, and create custom views of libraries using the Document library web part."
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 871e3ed2-4749-654b-610d-c06167103ee1
* Version Independent ID: 685537c2-c689-48bb-579e-ecbc0778f7ae
* Content: [Intelligent intranet roadmap - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/intranet-overview#content-authors)
* Content Source: [SharePoint/SharePointOnline/intranet-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/intranet-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
