### ISSUE TITLE
Migration Manager would succeed in migrating to a site with the non-English title

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint#2540]
Hello,

According to the Migration Manager FAQ, migration to a site with a Non-English title is non-supported. 

![image](https://user-images.githubusercontent.com/13634805/104548865-0467b580-5675-11eb-9e42-03351025819d.png)

However, when I tried the migration on a site with a Japanese title, the migration was successful without any errors.
Is this limit obsolete due to recent updates? 

Non-English users might change the title of their existing site to English only for migration purposes. If a recent update mitigates this limitation, we would appreciate it if you could update the article.

In the release notes, there was no mention so far. 
https://docs.microsoft.com/en-us/sharepointmigration/mm-whats-new

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
