### ISSUE TITLE
No explanation about 'Set-SPOTenant -SyncAadB2BManagementPolicy $true'

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/OfficeDocs-SharePoint#2541]
Whilst I appreciate this feature is in preview, it is not great that there is no documentation to explain `Set-SPOTenant -SyncAadB2BManagementPolicy $true`

It appears that this is not setting a value, but instead a command to perform an action as there is no equivalent `Get-SPOTenant` value returned for `SyncAadB2BManagementPolicy`. However it isn't clear whether this needs to be done periodically, or whether it is turned on now moving forward - and it doesn't provide any description about what actually happens.

NB: Aware that this bug is only against the documentation, not the product, but if indeed it is a 'command' initiating some action, but is tied to the `Set-SPOTenant` cmdlet; this seems poor practice from a PowerShell perspective. Ideally it would use the `Initiate` or `Start` or other such similar PowerShell verb.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by webash** [comment]
Hrmm I think you've misunderstood me. There isn't a support problem here, there is a documentation one. There is a function on a cmdlet that doesn't have documentation. That needs to be fixed.
