### ISSUE TITLE
Clarification around OneDrive reporting

### ISSUE THREAD

**Issue by jamesamayes** [MicrosoftDocs/OfficeDocs-SharePoint#2542]
The instructions are bit vague in several areas.

Example: "Open OneDrive"

Since OneDrive is a per user storage system, what is being referred to here?  The goal would be to report on all files shared externally by all users via OneDrive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharing-reports)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @jamesamayes ! an improvement to the article is on the way.
