### ISSUE TITLE
error in the script

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/OfficeDocs-SharePoint#2543]
This line throws a "can't divide by 0" error on my system:
      $percent = $site.StorageUsageCurrent / $site.StorageQuota * 100 

I replaced the line above with this if statement and now the script runs:
if($site.StorageQuota -gt 0) {
     $percent = $site.StorageUsageCurrent / $site.StorageQuota * 100 
     }else {
     $percent = 0
     }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits#manage-individual-site-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
No issues running it, here. Sounds like a site might have an erroneous value for StorageUsageCurrent and/or StorageQuota. You may want to examine those properties outside of the script to see if you can narrow it down. When you find the culprit, you may want to open a support case with Microsoft at admin.microsoft.com.

With that said, the script itself doesn't need an adjustment.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
