### ISSUE TITLE
OneDrive - file share folder redirection before KFM

### ISSUE THREAD

**Issue by tompsmith14** [MicrosoftDocs/OfficeDocs-SharePoint#2545]
I believe the documentation around migrating from group folder redirection file shares needs more detail. 
disabling the settings isn’t an option it’s either “not configured” or redirect the folder somewhere else ..
If you set the folder to not configured the known folder paths remain intact. With half the world working from home and using a vpn , this won’t be enough for KFM policy to 
Work properly ... add some detail to this section please

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
