### ISSUE TITLE
Login to SharePoint from powershell

### ISSUE THREAD

**Issue by Adminny** [MicrosoftDocs/OfficeDocs-SharePoint#2546]
This good page.
But for convenience it is better to add a simple login command
Connect-SPOService -Url https://$orgName-admin.sharepoint.com
into point 2:
2. Connect to SharePoint as a global admin or SharePoint admin in Microsoft 365. To learn how, see Getting started with SharePoint Online Management Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3384358-57c3-7117-f4c4-5da891cbf2fd
* Version Independent ID: e253e442-722d-acc7-1155-ee90ed1c324f
* Content: [Restore a deleted OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/restore-deleted-onedrive?redirectSourcePath=%252fen-us%252farticle%252frestore-a-deleted-onedrive-e487f40d-5321-46a8-9504-92b600b65cb9)
* Content Source: [OneDrive/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@Adminny this generally isn't done due to the large amount of documentation that would be impacted and not just this particular site. Point 2 includes a link on how to connect to SPO with PoSh.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
