### ISSUE TITLE
Regkey path is incorrect

### ISSUE THREAD

**Issue by gsagar2877** [MicrosoftDocs/OfficeDocs-SharePoint#2547]
Hey i was going through some testing in OneDrive.
I found a problem in implementing the regkey for low disk space on the page mentioned page.
https://docs.microsoft.com/en-us/onedrive/use-group-policy#prompt-users-when-they-delete-multiple-onedrive-files-on-their-local-computer
So i thought just confirm with you as regkey value should be "MinDiskSpaceLimitInMB" instead of "WarningMinDiskSpaceLimitInMB".

Please let me know if my observation is right or wrong.WORK.txt](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/5835828/WORK.txt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#prompt-users-when-they-delete-multiple-onedrive-files-on-their-local-computer)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
