### ISSUE TITLE
Lacking detail on Buy Storage option

### ISSUE THREAD

**Issue by cf5joe** [MicrosoftDocs/OfficeDocs-SharePoint#2549]
On this page, I'm looking for the replacement for "Buy Storage" for SharePoint at the tenant level.  All this page says is to go to the "Purchase Services" link in the Admin center.  However, it doesn't say which section or category this option resides in.  I have searched high and low in my purchase services area, multiple sub-sections and even add-ons and CANNOT find this.  It would be much more helpful if specific steps to find the "buy storage" for sharepoint item was made more clear.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd224d48-9dab-31ae-6548-2e929bd62d7c
* Version Independent ID: 6a98ec78-5f74-266f-61a5-95dfdcf673e9
* Content: [Find site collection features in the new SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/site-collections-page)
* Content Source: [SharePoint/SharePointOnline/site-collections-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/site-collections-page.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@cf5joe  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @cf5joe how are you?

Have you seen this https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide ?

I hope you find this information helpful in your scenario.

**Comment by cf5joe** [comment]
No I have not, but this information is missing from the other page that I had found and filed this report against.

Regards,
Joe

**Comment by get-itips** [comment]
> No I have not, but this information is missing from the other page that I had found and filed this report against. Regards, Joe 

Joe, will propose adding that link to the article you filed the report, if it gets approval, it will be published and other administrators will benefit from your feedback. Thanks!
