### ISSUE TITLE
Organization assets library not supported in Office Online (Word Online, Excel Online) but only in Powerpoint Online

### ISSUE THREAD

**Issue by AureliaDumitru** [MicrosoftDocs/OfficeDocs-SharePoint#2552]
Organization assets library is not supported in Office Online (Word Online, Excel Online) but only in Powerpoint Online. 
This needs to be clearly added to the article: https://docs.microsoft.com/en-us/sharepoint/organization-assets-library

"The documentation has been a point of confusion because the Word and Excel desktop apps support the feature, but not Word Online and Excel Online" . This is the response that I got from PG as there are a lot of customers reporting that they cannot use the feature in online applications and that it is not mentioned in the article.

Thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by AureliaDumitru** [comment]
@scanum , I have an opened RFC with PG and this was the response that I have received from the PM owners of the feature. It needs to be mentioned in the article that Organization assets library is not supported in Office Online (Word Online & Excel Online). The article is very confusing for the customers and they are opening requests to us (Microsoft) . There is nothing that can be fixed for now. This feature works in the Office client applications and Powerpoint Online.
If this is not the correct channel to open the request for modifying this article (including this information in the article), let me know. Thank you.
