### ISSUE TITLE
Prepare your OneDrive environment Update

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-SharePoint#2553]
Need to add a note that the migration account must have permission to the destination OneDrive sites and that the migration tool does not have the capability to do this at run time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide?source=docs)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Marweis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @Marweis

**Comment by Marweis** [comment]
Any update on this?

**Comment by Marweis** [comment]
Any update on this?

**Comment by get-itips** [comment]
> Any update on this?
The PR is pending review and approval. Thanks

**Comment by Marweis** [comment]
Please let me know when this is published. Thank you!
