### ISSUE TITLE
Prepare your OneDrive environment

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-SharePoint#2554]
Add note in the the 'Prepare your OneDrive environment' section that not only do the OneDrive sites need to be pre-provisioned but the migration account needs to be added as an admin so it has permissions to write/migrate content to each destination site. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088d4ec6-16f9-7af9-006b-db169d3390d2
* Version Independent ID: 6a4171f9-b32f-baa5-47b1-ca4d1475acae
* Content: [Migrate from My Sites to OneDrive in Office 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mysites-to-onedrive-migration-guide)
* Content Source: [migration/MySites-to-OneDrive-Migration-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/MySites-to-OneDrive-Migration-Guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Closing because duplicate

**Comment by Marweis** [comment]
There are multiple pages that should have this caveat noted. This request was not a duplicate but for a different page.
