### ISSUE TITLE
SP2013 - SQL Server 2014 Support

### ISSUE THREAD

**Issue by alexjebens** [MicrosoftDocs/OfficeDocs-SharePoint#2555]
Even though the following documentation contains specific requirements for installing SharePoint Server 2013 on  SQL Server 2014 it does not list SQL Server 2014 as one of the supported SQL Server versions:

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md#minimum-software-requirements

The following article also states that SharePoint Server 2013 supports SQL Server 2014:
https://docs.microsoft.com/en-us/sharepoint/administration/overview-of-sql-server-in-a-sharepoint-server-2013-environment

@get-itips

**Comment by get-itips** [comment]
@alexjebens Alexander, how are you?

Do you refer to this?

> One of the following:
The 64-bit edition of Microsoft SQL Server 2012.
The 64-bit edition of SQL Server 2008 R2 Service Pack 1

If so, please take into account that it says:

> Minimum requirements for a database server in a farm:

Let me know if I understood you well! Thanks

**Comment by alexjebens** [comment]
I am fine. How are you?

Yes I am refering to that.

I understand that these are minumum requirements but at the same time the article says that SQL Server 2016 is not supported. I am sure that the same applies to SQL Server 2019. Therefore the requirements are not only minimum but also maximum. IMHO the easiest way to express that in this case is a taxative list of supported SQL versions (2008, 2012, 2014).
