### ISSUE TITLE
By design - Organization assets library not supported in Office Online (Word Online, Excel Online) but only in Powerpoint Online

### ISSUE THREAD

**Issue by AureliaDumitru** [MicrosoftDocs/OfficeDocs-SharePoint#2561]
Hi,

I've opened a previous request but unfortunately it was closed. 
We need a clear statement regarding the supportability of organization assets library in the Office web applications to be included in the article: https://docs.microsoft.com/en-us/sharepoint/organization-assets-library : Organization assets library is not supported in Office Online (Word Online, Excel Online) but only in Powerpoint Online. 

I have an opened RFC with PG and this was the response that I have received from the PM owners of the feature. The article is very confusing for the customers and they are opening requests to us (Microsoft) . This is not an issue, the behavior is by design. This feature works in the Office client applications and Powerpoint Online but not in World Online & Excel Online.
If this is not the correct channel to open the request for modifying this article (including this information in the article), let me know. 

Thank you.

KR,
Aurelia Dumitru
Support Escalation Engineer for M365 Apps

**Comment by scanum** [comment]
Hi @AureliaDumitru the team will be reaching out to you personally. Closing this issue.
