### ISSUE TITLE
Incorrect "is supported" statement on activating Publishing features on modern Team Sites

### ISSUE THREAD

**Issue by andrewconnell** [MicrosoftDocs/OfficeDocs-SharePoint#2564]
This doc states "SharePoint Publishing Infrastructure is supported for a modern Team Site." in the first bullet, however, the SharePoint product group actively discourages this and does not support it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e6d056-3733-6925-4c58-40eaa01a6580
* Version Independent ID: 7802375b-467b-53e0-4e9d-ca990a8b2c54
* Content: [Why move from publishing sites to communication sites? - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/publishing-sites-classic-to-modern-experience#feedback)
* Content Source: [SharePoint/SharePointOnline/publishing-sites-classic-to-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/publishing-sites-classic-to-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by get-itips** [comment]
Hello @Holland-ODSP how are you? I see that you are the author of the [supportability text](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/e9749bbed776610b8ece1aa59ecd20ef8606cbd0) that @andrewconnell Andrew kindly mention, can you help us clarify? Thank you, I appreciate it.

**Comment by andrewconnell** [comment]
BTW, I verified what I said above with SP engineering, specifically @VesaJuvonen, prior to posting this comment. I added the comment as we got a question from a confused customer who indicated the statement in the SP developer docs contradicted this doc (the one this comment is tied to).

**Comment by get-itips** [comment]
> SP developer docs

I will propose a PR against the article and ask for a review. Thanks Andrew.
