### ISSUE TITLE
Box admin has changed, screenshots need updating

### ISSUE THREAD

**Issue by cloudhal** [MicrosoftDocs/OfficeDocs-SharePoint#2566]
[Enter feedback here]
Box admin has been updated, and some of the descriptions and screenshots no longer match what is in the Box admin console.

e.g.
Apps is not under Enterprise any more, it has its own icon on the left toolbar (under section Removing app access, shows old screenshot).
Also the app name shown is not Mover any more, it shows as Microsoft 365 migration.

Also, the app ID/api key appears to have changed and is no longer 7ypzdr66s3m80h3hutop34u7yml8928x, we had to get the client_id from the Box error page and that worked.

etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5366e6b-779b-29d6-1e06-a30963c4535d
* Version Independent ID: df5eaa56-f7a2-46a1-4852-2fdf70b7699a
* Content: [Mover migration - Setting up your Box source connector - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/SharepointMigration/mover-box)
* Content Source: [migration/mover-box.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-box.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@cloudhal thank you for pointing this out. I had a look at the screenshots and it seems the document was updated on the 9th February. Please have another look at the screenshots in the article and let me know if there are any more changes needed.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
