### ISSUE TITLE
Download "other file types" while using unmanaged devices

### ISSUE THREAD

**Issue by MarwaMS92** [MicrosoftDocs/OfficeDocs-SharePoint#2567]
I'm asking about "session control" for "unmanaged devices" specially this attribute -> -LimitedAccessFileType OtherFiles because it's somehow confusing.. When this policy get applied does it allow unmanaged devices to download zip, exe, etc ? or how it will work?
The doc says:
"When Access Control for **Unmanaged** Devices in SharePoint is set to Allow limited, web-only access, SharePoint files **cannot be downloaded** but they can be previewed." Does this means that the download limitation (using LimitedAccessFileType OtherFiles) will be applied to unmanaged devices and they will not be able to download other file types? while the managed devices will be able to download other file types ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
