### ISSUE TITLE
No explanation about 'Set-SPOTenant -SyncAadB2BManagementPolicy $true' REOPENED

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/OfficeDocs-SharePoint#2568]
_This issue was originally logged as #2541 , but was closed for being misinterpreted as a support request, which it isn't. The request below is for the documentation both on Set-SPOTenant and this page to explain what the `SyncAadB2BManagementPolicy` attribute does._

Whilst I appreciate this feature is in preview, it is not great that there is no documentation to explain `Set-SPOTenant -SyncAadB2BManagementPolicy $true`

It appears that this is not setting a value, but instead a command to perform an action as there is no equivalent `Get-SPOTenant` value returned for `SyncAadB2BManagementPolicy`. However it isn't clear whether this needs to be done periodically, or whether it is turned on now moving forward - and it doesn't provide any description about what actually happens.

<br>
<br>
_Side note worth raising internally at Microsoft once this documentation bug is resolved:_
If indeed SyncAadB2BManagementPolicy is actually a 'command' initiating some action NOT just a setting/flag, it is poor practice from a PowerShell perspective for it to be on a `Set-` verb'd cmdlet. Instead it should use the Initiate or Start or other such similar PowerShell verb. Before this command goes GA is the perfect time to fix and change this, along with the documentation on what it does and why it is required :)

<br>
<br>

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@webash  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by webash** [comment]
thanks :)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
