### ISSUE TITLE
Silent Sign in still working?

### ISSUE THREAD

**Issue by SebastianPiendl** [MicrosoftDocs/OfficeDocs-SharePoint#2569]
I see the issue on severall customer tenants were this feature worked like a charm. But now I wanted to implement it on new customer tenant and it's not working anymore. Checked the config on other customer tenants. Same experience: User needs to enter his username and password.
Please do not recommend to ask M365 Support for this issue!!!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
