### ISSUE TITLE
Link Does not work

### ISSUE THREAD

**Issue by arjunr1** [MicrosoftDocs/OfficeDocs-SharePoint#257]
https://doc.co/qrafhS

Quick reference guide: SharePoint Server 2016 databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9832c1ba-de43-28ea-fa98-af7569619325
* Version Independent ID: 3095abbc-a8a9-7171-efb8-55a4d798aaa6
* Content: [Overview of SQL Server in a SharePoint Server 2016 environment](https://docs.microsoft.com/en-us/sharepoint/administration/overview-of-sql-server-in-a-sharepoint-server-2016-environment)
* Content Source: [SharePoint/SharePointServer/administration/overview-of-sql-server-in-a-sharepoint-server-2016-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/overview-of-sql-server-in-a-sharepoint-server-2016-environment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
The poster view process no longer work, so removed broken link and revised statement to download either the PDF or Visio file.

**Comment by AndreaBarr** [comment]
@arjunr1 Thank you for this feedback

From what I understand the article has been updated and this should reslove this issue. Closing due to resolution. If this issue is not resolve please reopen this issue.

**Comment by arjunr1** [comment]
thanks

**Comment by AndreaBarr** [comment]
@arjunr1 closing until the merge is complete or we have an update.
