### ISSUE TITLE
No "OneDrive Sync Button" or "Sync Client for SharePoint," 

### ISSUE THREAD

**Issue by shs-hathawayrob** [MicrosoftDocs/OfficeDocs-SharePoint#2572]
I don't see a "OneDrive Sync Button" or "Sync Client for SharePoint,"  on the classic settings page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367f3b91-1252-7bce-fd1e-21ceb1ae12f3
* Version Independent ID: 66e3f10a-0231-e7e0-0659-0be66eaf13fa
* Content: [How to let users sync SharePoint files with the OneDrive sync app - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/let-users-use-new-onedrive-sync-client#set-sharepoint-to-sync-with-the-onedrive-sync-client)
* Content Source: [SharePoint/SharePointOnline/let-users-use-new-onedrive-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-use-new-onedrive-sync-client.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@shs-hathawayrob Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
