### ISSUE TITLE
Can't see storage used on SharePoint Active site page

### ISSUE THREAD

**Issue by aecportalsmtj** [MicrosoftDocs/OfficeDocs-SharePoint#2574]
When I access the SharePoint "Active sites" page to view the storage used (as described at the beginning of this "Manage site storage limits" page), I always see "0.00 MB used of 1.05 TB". I know this is not correct because when I go to the 365 Admin Portal usage page for SharePoint (linked below), I see the correct storage usage metrics. How can I get the "Active sites" page to show the same/accurate usage?

https://admin.microsoft.com/Adminportal/Home?source=applauncher#/reportsUsage/SharePointSiteUsageV1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
