### ISSUE TITLE
NEO hub solution page links to wrong site

### ISSUE THREAD

**Issue by jdrussell78** [MicrosoftDocs/OfficeDocs-SharePoint#2580]
Hi,

The link entitled "NEO hub solution page" which can be found under Step 1: Provision NEO Hub, sub section - Provision NEO hub is linking to the incorrect place.

It currently links here - https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239

and it should be linking to here - https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19

Thanks.

Jon

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3739a833-d9b7-baee-2d17-26cba48d7da8
* Version Independent ID: 0618f0c0-e98a-d932-fb29-65a4852fe90b
* Content: [Overview of the Microsoft New Employee Onboarding hub - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/provision-neo-hub)
* Content Source: [SharePoint/SharePointOnline/provision-neo-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-neo-hub.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@jdrussell78 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @jdrussell78
