### ISSUE TITLE
There is no replacement for classic 'Add Support Partner option' option

### ISSUE THREAD

**Issue by tommykr2** [MicrosoftDocs/OfficeDocs-SharePoint#2581]
Regarding the Add Support Partner option, this page states the following:
"This option is available in PowerShell only. Go to the Site Permissions page for a site where you’ve added the support partner. Copy the encoded string for the partner, and to add it to other sites"

Well, if the support partner has not been added to any sites yet, how does one go about acquiring the encoded string for the first time? The 'Add Support Partner' option allowed you to add a support partner as a site admin for the first/initial time. From there we have always been able to copy with PowerShell. Now, we have lost the ability to add support partners to a tenant. There is no replacement for this function which has been taken from us by deprecating the classic admin site.

https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/42154054-add-support-partner-option-from-modern-site-admin

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd224d48-9dab-31ae-6548-2e929bd62d7c
* Version Independent ID: 6a98ec78-5f74-266f-61a5-95dfdcf673e9
* Content: [Find site collection features in the new SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/site-collections-page)
* Content Source: [SharePoint/SharePointOnline/site-collections-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/site-collections-page.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tommykr2 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@tommykr2 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
