### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chrish1961** [MicrosoftDocs/OfficeDocs-SharePoint#2582]
the link "Posters, email templates: Customizable templates to generate internal awareness and excitement" does not appear to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@chrish1961 thank you for pointing this out. I see that it's not working from my side either. Please let me know if this is the correct link to be added to the article - https://support.microsoft.com/office/create-and-use-site-templates-in-sharepoint-server-versions-60371b0f-00e0-4c49-a844-34759ebdd989 and I'll do the PR asap.

**Comment by chrish1961** [comment]
Thanks Lindsay,
                 That look right to me.

Regards,

Chris

Chris Hadji | Data and Information Team | Prison Technology Transformation Programme
07971 781185

**Comment by nam31** [comment]
Closing via #2592 
Thank you
