### ISSUE TITLE
Required endpoints not exhaustive

### ISSUE THREAD

**Issue by dooleydo** [MicrosoftDocs/OfficeDocs-SharePoint#2584]
There are additional endpoints needed in order to sign into the MMA agent for SPO access. For example login.microsoftonline.com and *.msauth.net. These should be fully documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624f51bf-bf14-03ae-099b-2ee8b8657bf2
* Version Independent ID: 71bc428f-3fe9-1e9b-a996-871407127f96
* Content: [Setup Migration Manager agents - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-setup-clients)
* Content Source: [migration/mm-setup-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-setup-clients.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@dooleydo thank you for reaching out. Are you suggesting adding these to the table as follows:
https://login.microsoftonline.com  -  For signing into the MMA agent for SPO access.
and
https://*.msauth.net  - For signing into the MMA agent for SPO access.

**Comment by dooleydo** [comment]
Yes, there may be even more that are required but we found those two were certainly needed in order to sign into SPO via the MMA software when installing.

**Comment by nam31** [comment]
Closing via #2593 
Thank you
