### ISSUE TITLE
Specific domains of what type?

### ISSUE THREAD

**Issue by ang216** [MicrosoftDocs/OfficeDocs-SharePoint#259]
When you say "allow syncing only on PCs joined to specific domains" do you mean local Active Directory domains or Azure Active Directory domains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
It refers to Active Directory domains. On Step 4, it clearly takes you to an AD cmdlet to determine that information.

**Comment by AndreaBarr** [comment]
@ang216 Thank you for this feedback

From my understanding Trevor has answered your question and resolved this issue. If this issue is not resolved please reopen this issue.
