### ISSUE TITLE
1024000 MB = 10 TB?

### ISSUE THREAD

**Issue by leethengwei** [MicrosoftDocs/OfficeDocs-SharePoint#2595]
I think there is 1 zero missing for the 10TB definition.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage?redirectSourcePath=%252fen-us%252farticle%252fSet-your-OneDrive-for-Business-storage-quota-7448173d-a38c-48cf-acbb-09ac1b6237d4)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@leethengwei  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by derhallim** [comment]
No need for a change here, 1024000MB is actually 1.24TB

**Comment by derhallim** [comment]
10240000MB (four zeroes) = 10.24TB, which is correct as documented.
