### ISSUE TITLE
OD/SP integration with AAD B2B is no longer in preview

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/OfficeDocs-SharePoint#2597]
This excerpt refers to the SharePoint and OneDrive integration with Azure AD B2B as being in preview, I don't believe this is the case anymore, as that page does not include any such warnings.

`
These recipients will typically be added to your directory as guests, and then permissions and groups work the same for these guests as they do for internal users. (To ensure that all guests are added to your directory, use the SharePoint and OneDrive integration with Azure AD B2B preview.)
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@webash thanks for catching that. I submitted a PR to update the link.

**Comment by webash** [comment]
Awesome - closing issue.
