### ISSUE TITLE
macos macdrive and /preferences/manage app/blocked option

### ISSUE THREAD

**Issue by pperquin** [MicrosoftDocs/OfficeDocs-SharePoint#2599]
Hi,

I read your doc  but it seem that there other configuration file:

I'm woking with 'File and demand' and i want to make a backup but without downloading all file.
I'm running macOS 11.2.1 and one drive for mac 21.020.00128.0002 with a professional account

I try to use a command like that
rsync --archive --recursive --verbose --delete --delete-excluded --exclude-from=forexclude.txt "/Volumes/datas/AFP/" "/Volumes/datas/totest/cible"

How can i block rsync to download ?

for info onedrive  not Notify me that rsync is try to download even if i check it in preference.

If i put an app in /preferences/manage app/blocked in my mac there is not HydrationDisallowedApps in plist.
The exclusion seem to be in a file "1c4ec919-1ebb-4ab3-85ef-4236430b9e3f.ini" that is in "Users/pil_afp/Library/Application\ Support/OneDrive/settings/Business1/".
Have you any documentation about that ?

it seem also not possible to add rsync in /preferences/manage app/blocked

regards.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
