### ISSUE TITLE
Content Type Hub in SharePoint Online - Timer job schedule missing from documentation

### ISSUE THREAD

**Issue by CallumCrowley** [MicrosoftDocs/OfficeDocs-SharePoint#2604]
**Issue**

The "Publish a content type - SharePoint in Microsoft 365" documentation does not provide a schedule for the content type hub syndication job or the subscriber job in SharePoint Online. This means users do not know how long they will need to wait for their published content types to appear in their sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52f3c87-422d-70ad-8b29-673b3913bfdd
* Version Independent ID: 35b68646-fd17-b7a7-524d-9385b1187382
* Content: [Publish a content type - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/publish-content-type)
* Content Source: [SharePoint/SharePointOnline/publish-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/publish-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@CallumCrowley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
Microsoft does not publish timer job schedules for SPO as they may make changes at any time. In addition, timer jobs such as this have a widely variable runtime due to the number of tenants on a particular stamp and the number of published CT hubs per tenant. The expectation is up to ~72 hours for CT publish to complete. This is a slightly old number and _has_ gotten better within the past 1 - 1.5 years.

**Comment by CallumCrowley** [comment]
@tseward Appreciate that they could make changes to the schedule at any time. This however, doesn't explain why the schedule isn't visible to tenant administrators via the admin portal. It also doesn't explain why tenant administrators are not able to see that the timer job is running and how long it has been running for. At the very least, a guideline in the documentation would be helpful so that consultants and administrators can at least give a better answer than "we don't know how long it will take" to end users. I've not found any official documentation on how long this process can typically take in SharePoint Online.

**Comment by tseward** [comment]
If that level of control/visibility is needed, SharePoint Server would be the better option. You're correct, anything considered "server side" is not viewable or configurable by customers in SPO.

No documentation is more or less intentional due to the variability. It would potentially lay out expectations that cannot be met in a particular tenant.

This is similar to Search where there is no particular SLA for crawls.... again, too much variability to provide that information in a meaningful and useful manner to customers.

**Comment by CallumCrowley** [comment]
@tseward I wouldn't expect SaaS to provide server side configuration to tenant administrators but visibility wouldn't affect the service and would allow administrators to understand the status of their content type synchronisation. Alternatively, the documentation could give examples of how long it could take based on a set number of content types and sites in a tenant and how long is too long e.g. when to open a support ticket.

Many organisations are switching to a flat architecture and the only out-of-the-box way of propagating content types is via the Content Type Hub. We could programmatically keep content types up to date ourselves but this isn't ideal. When users create a new site, we don't know how long they will have to wait to start using the site (assuming the content types are important for day to day work).

I have seen a [new feature of SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/push-content-type-to-hub) resolves this problem by pushing content types to a site within a matter of minutes rather than hours when a site is connected to a designated Hub. Sadly, this is requires another licence per user which is a difficult proposition if an organisation only requires content types to be synchronised in a more timely manner and not the wider features of SharePoint Syntex e.g. topics etc.

I suppose, improved documentation on the matter might help consultants manage the expectations of end users.

**Comment by tseward** [comment]
I would suggest you add your votes to https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/15147006-in-sharepoint-online-admin-would-be-good-to-see-t as this would be a new feature request for the platform.

**Comment by CallumCrowley** [comment]
@tseward thank you for the link, I'll check it out.

However, I still think that the documentation on this matter needs to be improved. Even if there is no SLA, there should be an explanation regarding the content type synchronisation. Currently there is no documentation on this matter.
