### ISSUE TITLE
Download agent instructions are incomplete

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/OfficeDocs-SharePoint#2607]
[Enter feedback here]
After following the link, as instructed, there are no visible links to download the migration agent. To get the link, one must select the "Agents" tab, then press the "Add+" button before the download link is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624f51bf-bf14-03ae-099b-2ee8b8657bf2
* Version Independent ID: 71bc428f-3fe9-1e9b-a996-871407127f96
* Content: [Setup Migration Manager agents - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-setup-clients)
* Content Source: [migration/mm-setup-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-setup-clients.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JLambEJG Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JoanneHendrickson** [comment]
@JLambEJG  Thank you for catching this, the workflow had changed recently.  I have updated the article.  Thanks!
