### ISSUE TITLE
Empty Content type gallery 

### ISSUE THREAD

**Issue by kavitajoshi** [MicrosoftDocs/OfficeDocs-SharePoint#2608]
Content type gallery in newly provisioned tenant shows no content types for SharePoint Admin who is not Global Admin. During **automatic** provisioning of Content Type Gallery (Content Type Hub Site Collection) M365 / SPO should assign 'SharePoint Service Administrator' role in addition to 'Global Administrator' as Site Collection Admin.

Workaround is to navigate to Content Type Hub Site collection as a Global Admin and add 'SharePoint Service Administrator' role as Site Collection Admin.

**Comment by tseward** [comment]
Since this isn't a documentation issue, I would suggest you add that as a feature request at https://sharepoint.uservoice.com/.
