### ISSUE TITLE
Incomplete Infomation - 3. Set your site design for the hub site

### ISSUE THREAD

**Issue by Justin-Nash** [MicrosoftDocs/OfficeDocs-SharePoint#261]
There is no information on what is or is not supported when connecting a site design to a hub site. 
Dose it support:
- Creating new lists?
- Creating new Site Columns?
- Creating new Site Content types?
- Creating new fields?
- [Any of the Site design JSON schema options?](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema)

There is no feedback to say the design has be connected to the hub site. 
At time of this writing there is no UI option ether. Please provide more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd09eee5-c545-e689-1194-e6b6cd70d63c
* Version Independent ID: 81523a20-4bed-a41c-9f5e-e5b5200d2f75
* Content: [Set up a site design for your hub site](https://docs.microsoft.com/en-us/sharepoint/set-up-site-design-hub-site)
* Content Source: [SharePoint/SharePointOnline/set-up-site-design-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/set-up-site-design-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@Justin-Nash Thank you for this feedback

I will get this over to the SharePoint team for investigation and updating. For expidated answers please open a support ticket. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by alokegupta** [comment]
@AndreaBarr There is still no additional information. I have been struggling with activating app customizer as per [https://github.com/SharePoint/sp-dev-site-scripts/blob/master/samples/site-register-spfx-extension/register_extension.json](https://github.com/SharePoint/sp-dev-site-scripts/blob/master/samples/site-register-spfx-extension/register_extension.json). Just to check I also added schema to add lists before and after the app customizer activation code. Both of those lists get created. It looks as if it ignores "_installSolution_" & "_associateExtension_" verbs in case of hub site design. Finally, same site design works fine when used directly at the time of creation of site.`{
    "$schema": "schema.json",
    "actions": [
        {
            "verb": "createSPList",
            "listName": "Customer Tracking",
            "templateType": 100,
            "subactions": [
                {
                    "verb": "setDescription",
                    "description": "List of Customers and Orders"
                }
            ]
        },
        {
            "verb": "installSolution",
            "id": "c3afb54b-207e-439d-95e0-6863d51aafe0",
            "name": "Branding Solution"
        },
        {
            "verb": "associateExtension",
            "title": "Branding",
            "location": "ClientSideExtension.ApplicationCustomizer",
            "clientSideComponentId": "7ac4540d-17b2-427d-8e7f-0cf3e319b3c2",
            "scope": "Web"
        },
        {
            "verb": "createSPList",
            "listName": "Customer Tracking 2",
            "templateType": 100,
            "subactions": [
                {
                    "verb": "setDescription",
                    "description": "List of Customers and Orders"
                }
            ]
        }
    ],
    "bindata": { },
    "version": 1
}`

**Comment by AndreaBarr** [comment]
@alokegupta Thank you for this feedback. 

At this point we really need to get you to support if you are having issues with this. They have the resources there to find a resolution better than we can here in the Docs department. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
