### ISSUE TITLE
How is the performance report generated?

### ISSUE THREAD

**Issue by jwood-msft** [MicrosoftDocs/OfficeDocs-SharePoint#2611]
I don't think the report aggregator includes the performance report. Please include instructions on how to generate the performance report. Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca02c1ed-5060-da34-8177-ecda29144eef
* Version Independent ID: 45eab3ad-7f4f-e8b7-9a93-17ade9365ae4
* Content: [Migration Manager Reports - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-reports?source=docs#download-detailed-task-reports)
* Content Source: [migration/mm-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
