### ISSUE TITLE
Question on locking down OneDrive

### ISSUE THREAD

**Issue by 73kruegs** [MicrosoftDocs/OfficeDocs-SharePoint#2616]
[Enter feedback here]

I'm trying to follow through on this document and lock down OneDrive from non hybrid joined devices.  My question revolves around when I choose the "Cloud app or actions" option in the conditional access policy and I choose to select a particular app, should I be able to see "OneDrive SyncEngine" for an option to select?  Or, do you need to select the SharePoint option?

When I select All Cloud apps and run the policy in Report-Only I can see that the app "OneDrive SyncEngine" would get blocked so if possible, I would like to be able to select that specific app, but am not seeing it in the list.

Thanks,

E. Krueger
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app - OneDrive](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
