### ISSUE TITLE
Discovery capabilities are still present in mobile apps

### ISSUE THREAD

**Issue by jcwmoore** [MicrosoftDocs/OfficeDocs-SharePoint#2618]
On the OneDrive mobile app (Android version at least) there is a "Discover" view.  There is a learn more link on that view that directs to this doc page.  Will this "discovery" function be removed from the mobile app in a future update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc38a8f9-a969-c426-a61e-976186795361
* Version Independent ID: 672b76ff-61c2-4a6d-1b75-ddb0f98c22b3
* Content: [About Discover view - OneDrive](https://docs.microsoft.com/en-us/onedrive/help-users-use-discover-view)
* Content Source: [OneDrive/help-users-use-discover-view.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/help-users-use-discover-view.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
