### ISSUE TITLE
No longer an option

### ISSUE THREAD

**Issue by RMC-Kbly** [MicrosoftDocs/OfficeDocs-SharePoint#2619]
Adding the OneDrive Desktop application via this method does not appear to be available any longer, only the legacy (Groove) app is listed in the Configuration designer via the Endpoint Manager admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-intune)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by mosoccer** [comment]
Seeing the same thing and came her to put in the same issue.

![image](https://user-images.githubusercontent.com/581426/109909426-b1b97b80-7c6b-11eb-8517-e12bddfe2b00.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mosoccer** [comment]
@scanum - I did open a ticket with support as you suggested and they are reporting seeing the same thing as my screenshot above (that just the Groove version is showing).  I think this requires further research and change on the documentation side.

**Comment by mosoccer** [comment]
@RMC-Kbly - Microsoft Support confirmed the documentation was incorrect and has updated the screenshot.
