### ISSUE TITLE
Where is Step 14?

### ISSUE THREAD

**Issue by ccchow** [MicrosoftDocs/OfficeDocs-SharePoint#262]
&lt;SuperUser&gt; is the account to use for the Portal Super User account as you saw it displayed in the User Column field mentioned in Step 14 of the previous procedure.

&lt;SuperReader&gt; is account to use for the Portal Super Reader account as you saw it displayed in the User Column field mentioned in Step 14 of the previous procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b69c9e-7d46-b6bb-f1bc-f9415304b462
* Version Independent ID: 425ded65-eea7-dfd2-2e7a-bc083ce744e3
* Content: [Configure object cache user accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-object-cache-user-accounts)
* Content Source: [SharePoint/SharePointServer/administration/configure-object-cache-user-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-object-cache-user-accounts.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
I missed updating this step reference when updating the procedure earlier. Step now refers to step 11 instead of step 14, and republishing topic.
