### ISSUE TITLE
SPO Home Site

### ISSUE THREAD

**Issue by MedinaFab** [MicrosoftDocs/OfficeDocs-SharePoint#2620]
Setting SPO Home site will be needed for us to use the Global Navigation with the App Bar BUT if we set this script, we will see the site title on our news web part. We have a news web part showing on the top-left of the page and all top 4 news announcement have the page title as link icons. Why do we need to see the site title so many times? There should be a way, via properties to hide this or even PowerShell. If there is, please let me know. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
