### ISSUE TITLE
Wrong link for poster

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-SharePoint#2622]
The link for _Microsoft Teams and related productivity services in Microsoft 365 for IT architects_ is wrong. It should go to https://docs.microsoft.com/en-us/microsoft-365/solutions/productivity-illustrations?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd782a6-36d8-d7d6-f30b-f54dc960c069
* Version Independent ID: 9666c599-3457-c9ce-9b36-acf2157f0908
* Content: [Plan & deploy a file collaboration environment - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/deploy-file-collaboration?source=docs)
* Content Source: [SharePoint/SharePointOnline/deploy-file-collaboration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/deploy-file-collaboration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@fselkirk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
