### ISSUE TITLE
JSON example 

### ISSUE THREAD

**Issue by Larendsen** [MicrosoftDocs/OfficeDocs-SharePoint#2626]
To move te Windows Known Folders to OneDrive, the expample on this page (https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration) is minimal. It took me several hours to find out the right format. Our fileservers are in English and the clients Windows 10 are in Dutch. This is the format to migrate the Windows Known Folders. Maybe someone else will benefit from it ;-)
(Pictures (= Afbeeldingen), Documents (=Documenten), Music (= Muziek), Videos ( = Video's))

{
  "Tasks": 
  [
    {
      "SourcePath": "\\\\servername\\Folder\\username\\My Documents",
      "TargetPath": "https://contoso-my.sharepoint.com/personal/username_contoso_com",
      "TargetList": "Documenten",
	  "TargetListRelativePath": "Documenten"
    },
	{
      "SourcePath": "\\\\servername\\Folder\\username\\Music",
      "TargetPath": "https://contoso-my.sharepoint.com/personal/username_contoso_com",
      "TargetList": "Documenten",
	  "TargetListRelativePath": "Muziek"
    },
	{
      "SourcePath": "\\\\servername\\Folder\\username\\Pictures",
      "TargetPath": "https://contoso-my.sharepoint.com/personal/username_contoso_com",
      "TargetList": "Documenten",
	  "TargetListRelativePath": "Afbeeldingen"
    },
	{
      "SourcePath": "\\\\servername\\Folder\\username\\Videos",
      "TargetPath": "https://contoso-my.sharepoint.com/personal/username_contoso_com",
      "TargetList": "Documenten",
	  "TargetListRelativePath": "Video's"
    }
  ]
}

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [Format your JSON or CSV file for data content migration - SharePoint - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
