### ISSUE TITLE
Changed Site URL - Teams no longer sees Sharepoint location or OneNote

### ISSUE THREAD

**Issue by vvaghani88** [MicrosoftDocs/OfficeDocs-SharePoint#2628]
I've recently updated a couple of site URLs and can no longer add or access Sharepoint locations/files, or OneNote, within MS Teams. There appears to be no way to update the link or force sync to new URL. 

Thanks,

Vinny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@vvaghani88  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by vvaghani88** [comment]
Thanks Manuela. I’ve read a couple of articles that it had been resolved in MS fixes, but we’ve only recently experienced this issue and some of these references are from many months ago. I’ve found no way to resync teams or manually repoint the Sharepoint location it looks for via Teams.

Look forward to your update.

Thanks,


Vinny

**Comment by vvaghani88** [comment]
Hi, I've noticed Teams is trying to point to an old deleted URL, the rest of the site and links appear to work fine, its just Teams that seems to be pointing to the old URL. Can you confirm how I can change this setting for MS Teams? The site has 100% been deleted as i cannot locate it in any url search, including via Powershell.

Using the open in sharepoint option via Teams, all other sites that have been renamed have worked fine and repointed, its just a single Team site issue. 

Your assistance would be appreciated.

Thanks,

**Comment by VLG17** [comment]
@vvaghani88 I understand that you followed the steps described in the article you linked to update a SharePoint site address, and after the change you are unable to access it anymore from Teams, correct?

If that's the case, this needs to be looked into from a support perspective. My recommendation is to [open a support request](https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.teams). If it comes back that the article needs to be updated, we can do that. We can help with documentation updating, but not with technical issues.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
