### ISSUE TITLE
Define "Duration" format

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/OfficeDocs-SharePoint#2629]
In the aggregated summary report, the page says that the "Duration" column returns number of minutes. However, the format of the data is "00:32:51". Clarify the document. Is this HH:MM:SS, or MM:SS:MS, or something different? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca02c1ed-5060-da34-8177-ecda29144eef
* Version Independent ID: 45eab3ad-7f4f-e8b7-9a93-17ade9365ae4
* Content: [Migration Manager Reports - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-reports)
* Content Source: [migration/mm-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JLambEJG** [comment]
I'm not sure I understand. This is not an issue with my instance or anything unique to me or my company. Your documentation says that in the summary report, the "Duration" returns minutes. Instead, the report returns a formatted output that should be defined in the documentation.
