### ISSUE TITLE
TotalGB and Total GB Migrated are actually MB

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/OfficeDocs-SharePoint#2630]
The Total Bytes column returns the actual total bytes of data in the source. However, the "Total GB" and "Total GB Migrated" actually return MB.

Example:

```
Total Bytes | TotalGB | Total Bytes Migrated | Total GB Migrated
1927553454 | 1838.258223 | 1927553454 | 1838.258223
```
Should be:
Total Bytes = 1,927,553,454 = 1.838258223 TotalGB
Total Bytes Migrated = 1,927,553,454 = 1.838258223 Total GB Migrated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca02c1ed-5060-da34-8177-ecda29144eef
* Version Independent ID: 45eab3ad-7f4f-e8b7-9a93-17ade9365ae4
* Content: [Migration Manager Reports - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-reports)
* Content Source: [migration/mm-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JLambEJG** [comment]
Are you suggesting that your documentation is correct, and that this is my problem? Your documentation says the report returns GB, when it in-fact returns MB. Fix your documentation.
