### ISSUE TITLE
No more internal UI at admin.microsoft.com

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/OfficeDocs-SharePoint#2632]
Trying to create a new site from admin.microsoft.com only redirects back to the SharePoint admin center's UI tenant-admin.sharepoint.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0419db4c-9918-fcbe-53b3-4aca315e7703
* Version Independent ID: 0eca18cd-d073-8a6c-47ba-3e3330d63167
* Content: [Create a site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/create-site-collection)
* Content Source: [SharePoint/SharePointOnline/create-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
