### ISSUE TITLE
Guidance on management of the asset libraries

### ISSUE THREAD

**Issue by AlexVincent1** [MicrosoftDocs/OfficeDocs-SharePoint#2633]
Hello - I think it would be useful if you could update the article to give advice and best practice on how to manage the contents of an asset library after creation. For example, what precautions should be taken when updating or removing existing images in an asset library and what the impact will be on SharePoint pages which are already using those images.
Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
