### ISSUE TITLE
I dont see the option "Manage Sharing" when i select the OneDrive tab for an active user.  

### ISSUE THREAD

**Issue by harikumh** [MicrosoftDocs/OfficeDocs-SharePoint#2634]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Change the external sharing setting for a user's OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/user-external-sharing-settings)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by harikumh** [comment]
![image](https://user-images.githubusercontent.com/22823695/110978875-e6939580-8331-11eb-9877-3aa3bb0778f6.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
