### ISSUE TITLE
SharePointOnline Permissions

### ISSUE THREAD

**Issue by ddsmatt** [MicrosoftDocs/OfficeDocs-SharePoint#2635]
[https://docs.microsoft.com/en-us/sharepointmigration/understanding-permissions-when-migrating]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ed221a-ca52-7a6a-4b89-1417066ffcbd
* Version Independent ID: e7fdb3a0-c148-85d1-48cf-57998d190a8a
* Content: [Migration performance guide for SharePoint & OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-online-and-onedrive-migration-speed)
* Content Source: [migration/sharepoint-online-and-onedrive-migration-speed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-online-and-onedrive-migration-speed.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
