### ISSUE TITLE
Customize edit in grid view

### ISSUE THREAD

**Issue by manvendrautralia** [MicrosoftDocs/OfficeDocs-SharePoint#2636]
Furthur to the option  "edit in grid view" on sharepoint online, can I modify the view to:

1. Make Grid lines thicker and thus more visible

2. Customize column width, to make the view readable

Thanks for helping out.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf2d4570-0024-e5c0-035a-8827759aeabc
* Version Independent ID: 42e2105b-5ede-3d22-139d-96cc61cf4ec5
* Content: [Control Microsoft Lists - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-lists)
* Content Source: [SharePoint/SharePointOnline/control-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-lists.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
