### ISSUE TITLE
AutoMountTeamSites does not work for main site.

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/OfficeDocs-SharePoint#2638]
[Enter feedback here]
Hi there,
I was able to configure this setting and it runs correctly when the sharepoint library is not the default one. 

To ilustrate that i have 2 document libraries (identical) but one sits at the default sharepoint site and the other at another site i created (Dev)

both deployed using the **Copy library ID **
i can see both at the registry
only the one where the library ID url contains /sites/Dev

webUrl=https://mydomain.sharepoint.com/sites/Dev&version=1
webUrl=https://mydomain.sharepoint.com&version=1

Can that be confirmed? 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by schenardie** [comment]
I can replicate that behaviour accross multiple tenants. Its not a (one tenant) kind of issue.
