### ISSUE TITLE
OneDrive Desktop cannot be deployed via Intune

### ISSUE THREAD

**Issue by eronad** [MicrosoftDocs/OfficeDocs-SharePoint#2644]
OneDrive Desktop app cannot be deployed via Intune when using Configuration designer. The only option that can be selected is OneDrive (Groove) on the list. 

![image](https://user-images.githubusercontent.com/14807541/111526463-2a710b00-8735-11eb-9767-b893428f5cf9.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-intune#deploy-the-onedrive-sync-app-to-windows-10-devices)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mosoccer** [comment]
@eronad @scanum - I did opened a ticket with Microsoft Support and they confirmed the issue and had the screenshot updated.
