### ISSUE TITLE
Link goes to 403

### ISSUE THREAD

**Issue by DanLongMSFT** [MicrosoftDocs/OfficeDocs-SharePoint#2648]
It looks like the link under this header on the page: https://docs.microsoft.com/en-us/SharePoint/sharepoint-app-bar#temporarily-disable-the-sharepoint-app-bar goes to a 403 page. I think it's supposed to link over to this download page instead: https://www.microsoft.com/en-us/download/details.aspx?id=35588

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cb90e0-b8bb-32b2-d8b1-1710af6312f2
* Version Independent ID: 9d7a64c4-a3b0-47b8-b209-16e257a9a23a
* Content: [Use the new SharePoint app bar and set up global navigation - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/sharepoint-app-bar)
* Content Source: [SharePoint/SharePointOnline/sharepoint-app-bar.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-app-bar.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@DanLongMSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Holland-ODSP** [comment]
Hey @scanum I already fixed this a few days ago - we can close this one.
