### ISSUE TITLE
[App Store OneDrive, OSx: Configure sync app settings] Unclear how to implement changes in .plist configuration file 

### ISSUE THREAD

**Issue by floriandierickx** [MicrosoftDocs/OfficeDocs-SharePoint#2652]
I am trying to change configuration settings of the OneDrive application (App Store version, OSx) through the .plist settings file located at `~/Library/Containers/com.microsoft.OneDrive-mac/Data/Library/Preferences/com.microsoft.OneDrive-mac.plist`

More specifically, want to **activate the 'Files on demand' setting** as this option disappeared from my application some time ago (as [seems](https://forums.macrumors.com/threads/onedrive-files-on-demand-option-missing.2166619/) [to](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onedrivefb-mso_mac-mso_o365b/no-files-on-demand-options-on-mac/1e296ecc-1bda-4a20-a90e-b605dcbc173f) [be](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_onedrivefb-mso_mac-mso_o365b/onedrive-files-on-demand-on-macos-button-not/ab27da46-ac40-4177-a031-e3b41fba888f) [a](https://answers.microsoft.com/en-us/msoffice/forum/all/files-on-demand-options-not-availabledisappeared/1736df1e-27a0-4701-a0d4-779c95cdf3bc) [frequent](https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-mac-missing-on-demand/99ba3eae-b9e1-4866-8c0f-e6d7abda5de0) [issue](https://www.reddit.com/r/Office365/comments/aje7qg/files_on_demand_now_available_for_mac_i_cant_seem/))

In this regard, I find it unclear how to implement changes in the .plist file.

The [Configure sync app settings docs](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#configure-sync-app-settings) mention to:

1. Quit the OneDrive app.
2. **Define the settings you want to change by creating a .plist file with the values**. You can also use a script to set the default values.
3. Deploy the settings onto the local computer.
4. **Refresh the preferences cache**.
On the next start of OneDrive, the new settings will be picked up.

For:

2. I added the setting `FilesOnDemandEnabled = :true;` in the properties of the full `com.microsoft.OneDrive-mac.plist` file using a text editor (personal info left out):
```
// !!! BINARY PROPERTY LIST WARNING !!!
//
// The pretty-printed property list below has been created
// from a binary version on disk and should not be saved as
// the ASCII format is a subset of the binary representation!
//
{	BITApplicationDidEnterBackgroundTime = ;
	BITApplicationWasLaunched = :true;
	CampaignManagerVersionKey = "";
	HockeySDKAutomaticallySendCrashReports = :false;
	HockeySDKCrashReportActivated = :true;
	IsBusinessProvisioned = :true;
	NSNavLastRootDirectory = "";
	NSNavPanelExpandedSizeForOpenMode = "{800, 450}";
	NSOpenGLContextReplaceViewLayer = :false;
	"NSWindow Frame NSNavPanelAutosaveName" = " ";
	OpenAtLogin = 1;
	RatingsCampaignNextPollInterval = ;
	FilesOnDemandEnabled = :true;
}
```
).

3. I understand as to save the changes in the (original) .plist file `com.microsoft.OneDrive-mac.plist`

4. Question: How should I refresh the preferences cache of OneDrive? I tried to:
    - run the `ResetOneDriveApp.command` (located in OneDrive.app --> Contents --> Resources) script after changing the .plist file, but this script **also deletes the .plist file**.
    - shut down OneDrive, change the .plist-settings file and restart OneDrive, but **OneDrive overwrites the .plist-file with the original settings**

If you have any guidance on how to implement a .plist-settings file properly, I would be very grateful.

**UPDATE** : Given the binary property list warning, I also tried to change the setting by running `defaults write ~/Library/Containers/com.microsoft.OneDrive-mac/Data/Library/Preferences/com.microsoft.OneDrive-mac.plist FilesOnDemandEnabled -bool true` in the terminal. Using this strategy: the setting FilesOnDemandEnabled seems 

(i) to be **succesfully added** to the `com.microsoft.OneDrive-mac.plist` file
(ii) **not to be overwritten anymore** when restarting OneDrive
(iii) But: **neither the OneDrive preference pane nor the finder context menu do indicate the 'Files on demand' option** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by floriandierickx** [comment]
Ok, thanks for your reply! I unfortunately don't know who is the admin of my organisation. I did send feedback through the app referring to this issue for more details. It seems to be a frequent issue.

If of further use, I think it might however be useful for other users to clarify point 2 to 4 of the guidelines:

Points 2 and 3 "Deploy the settings onto the local computer" --> command-line changes of .plist-file (for example `defaults write ~/Library/Containers/com.microsoft.OneDrive-mac/Data/Library/Preferences/com.microsoft.OneDrive-mac.plist FilesOnDemandEnabled -bool true`in OSx).

It remains unclear to me how to refresh the preferences cache of OneDrive (Point 4).
