### ISSUE TITLE
Invalid Link "Settings page of the new SharePoint admin center"

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/OfficeDocs-SharePoint#2653]
Hi,

The link in the section "To allow custom script on OneDrive or user-created sites", 1st step "Settings page of the new SharePoint admin center" is invalid as it will take the users to a wrong page, rather the right link should be https://admin.microsoft.com/sharepoint?page=settings&modern=true 

Best regards,
Ahmed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#to-allow-custom-script-on-onedrive-or-user-created-sites)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ahamin01 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
