### ISSUE TITLE
Support for partial writes (PATCH verb) with WebDAV and SharePoint/OneDrive

### ISSUE THREAD

**Issue by jschwartzenberg** [MicrosoftDocs/OfficeDocs-SharePoint#2654]
Some web servers that support WebDAV also support the PATCH verb to enable partial writes. Unfortunately there are multiple dialects:
https://blog.sphere.chronosempire.org.uk/2012/11/21/webdav-and-the-http-patch-nightmare

Does IIS/SharePoint/OneDrive on MS Office 365 support partial writes in any way when accessing using WebDAV?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
