### ISSUE TITLE
Old document version?

### ISSUE THREAD

**Issue by KyleSchroeder** [MicrosoftDocs/OfficeDocs-SharePoint#266]
Is the original version of this document (https://support.office.com/en-us/article/Redirect-known-folders-to-OneDrive-for-Business-e1b3963c-7c6c-4694-9f2f-fb8005d9ef12) still available?  We were utilizing this method, but now only the new documentation referencing the built-in Known Folders functionality is posted.  I need the prior article version, which detailed using Group Policy Folder Redirection policies to manage this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders?redirectSourcePath=%252fen-us%252farticle%252fRedirect-known-folders-to-OneDrive-for-Business-e1b3963c-7c6c-4694-9f2f-fb8005d9ef12)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@KyleSchroeder Thank you for this feedback

I am not sure if we still have the old document. Support would be able to look this up for you. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
