### ISSUE TITLE
Issue After Migration

### ISSUE THREAD

**Issue by doumbix** [MicrosoftDocs/OfficeDocs-SharePoint#2660]
Hi Team, i got an issue after Migration. When i add a new file and i want to synch normally just this file should be migrate , but all files are uplaoded.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
