### ISSUE TITLE
Explicitly call out the use of the Office template format

### ISSUE THREAD

**Issue by mitsubishop** [MicrosoftDocs/OfficeDocs-SharePoint#2663]
Hi,

I think it would be good to call out the fact that files uploaded to an organization asset library to use as templates need to be in the .dotx, .potx or .xltx format.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by derhallim** [comment]
Added a pull request for this. #2664
