### ISSUE TITLE
Stopped working on MacOS a week ago

### ISSUE THREAD

**Issue by cb2206** [MicrosoftDocs/OfficeDocs-SharePoint#2669]
I successfully configured the org asset library feature end of November 2020 and it has been working fine for our Win and macOS users. Starting 5 days ago, I've been getting macOS user reports that Powerpoint is now showing the message "Sorry, were having a problem finding files in this folder. Try opening the folder again." instead of the templates in the New dialog. I see the same behavior on my Mac but haven't found any solution.
I realize that this is not a bug reporting site but are out of out of ideas and maybe this is something known.
Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
