### ISSUE TITLE
Content still encrypted/protected?

### ISSUE THREAD

**Issue by allanwith** [MicrosoftDocs/OfficeDocs-SharePoint#267]
Could you please clarify whether synced irm libraries will still be encrypted on the local hard drive? For instance, how much will another local administrator on a given client computer be able to see, if they gain access to another users local profile, where there files are synced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930a4d28-a511-e037-fa15-e4f3aebc7064
* Version Independent ID: 22a6cf03-0378-84b1-0ade-236018d49b3b
* Content: [Let users sync IRM-protected files with the OneDrive sync client](https://docs.microsoft.com/en-us/sharepoint/let-users-sync-irm-protected-files?redirectSourcePath=%252fen-us%252farticle%252fEnable-users-to-sync-IRM-protected-files-with-the-OneDrive-sync-client-Preview-6778d4de-b5f8-423c-af43-a1b2449e9b99)
* Content Source: [SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@allanwith Thank you for this feedback

I agree that these details should be in the article. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
Yes, the libraries will still continue to have IRM protection in place.  This applies to the synced library that gets transferred from the cloud as well as the library that is synced to the cloud.  The protections stay in place ensuring your information is protected.

**Comment by lewisdenise801** [comment]
Help me encrypt

**Comment by scanum** [comment]
PR #700
