### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by miguelrodriguezeicke** [MicrosoftDocs/OfficeDocs-SharePoint#2673]
Step 2 is not possible, because the sync option is not available in SharePoint admin center (anymore).
Instead, we have to go to OneDrive Admin Portal.

thx,
Miguel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains - OneDrive](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains?source=docs#feedback)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@miguelrodriguezeicke Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by derhallim** [comment]
The step is actually available in SharePoint admin center, you just have to click settings on the left menu, then the sync option will appear. I just made a PR for it.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
