### ISSUE TITLE
Add information about Office Online

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/OfficeDocs-SharePoint#2676]
In the following Note, could you add more information about users using services in Office such as Excel Online or Word Online. Our users seem to be logged out while editing documents hosted from OneDrive and SharePoint locations. The expectation is that they should be able to remain signed in but are not. They are actively working on documents and get kicked out by our time out.

 Note

If a user is active in another Microsoft 365 service (such as Outlook), but inactive in SharePoint and OneDrive, they are signed out across Microsoft 365. If a user has multiple tabs to OneDrive and SharePoint sites open at the same time, they won't be signed out unless they are inactive on all the sites. > Users won't be signed out if they selected to stay signed in when they signed in. ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaf9fb8-afec-06b3-ed85-244a7af5b6dd
* Version Independent ID: 016c6f7d-8fd1-ba7f-ab54-a0ef1d34d026
* Content: [Sign out inactive users - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sign-out-inactive-users)
* Content Source: [SharePoint/SharePointOnline/sign-out-inactive-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sign-out-inactive-users.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@pagejustin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @pagejustin Justin, how are you?
I tested this, however, I could not reproduce it, in case we need to adjust the documentation, can you detail browser used?
Thank you

**Comment by get-itips** [comment]
@scanum please close.
