### ISSUE TITLE
I can't see "retention" in the "Settings page of the new SharePoint admin center"

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/OfficeDocs-SharePoint#2677]
I was reading this page:
https://docs.microsoft.com/en-us/onedrive/set-retention

Which tells me to go to "Settings page of the new SharePoint admin center".

Once there, I cannot see the "retention" option.  I also tried the "classic settings page" but it's no help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users - OneDrive](https://docs.microsoft.com/en-us/onedrive/set-retention)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
