### ISSUE TITLE
File Size limit

### ISSUE THREAD

**Issue by MarwaMS92** [MicrosoftDocs/OfficeDocs-SharePoint#2679]
What is the maximum file size limit for the Migration Manager? I'm aware of the new file size limit on OneDrive and SharePoint which is 250 GB but I got an error while trying to move 20 GB file using the Migration Manager and the report is saying "File exceed the limit". any notes on this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MarwaMS92** [comment]
Thanks @scanum , i will do that.
