### ISSUE TITLE
Office 365 Groups External Access & SharePoint Online External Sharing Levels

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-SharePoint#268]
It looks as though the Office 365 Group setting for not permitting external access does not overrule SharePoint Online's External sharing level anymore. Was this a recent change? The Message Center does not show an announcement of this effect. I believe it'd be worth outlining the impact on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a570bb-2567-565c-e9ff-bf1ccbf38d0e
* Version Independent ID: 3d342dea-9dd3-008c-20c6-902452302e95
* Content: [Manage sharing in OneDrive and SharePoint](https://docs.microsoft.com/en-US/onedrive/manage-sharing)
* Content Source: [OneDrive/manage-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/manage-sharing.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@ferrety2006 Thank you for this feedback

I am not sure if this is a recent change or a possible bug. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by jmvelo** [comment]
We have the same problem. We are going to open a ticket.

**Comment by jmvelo** [comment]
There is a solution.
Go to SharePoint Administration Portal. Select the office 365 group. At right panel you can see the options of that site. The last option is about shared use. External Access is not allowed by default.

**Comment by dariomws306** [comment]
Hi @ferrety2006 , @jmvelo , thank you for your feedback.

I don't know if this was updated or not but there were updates recently on these docs and SharePoint admin portal. You can see some information about this:
"If you disable external access, or limit external access to a more restrictive form, external users will typically lose access within one hour of the change. If you disable external access, access to resources will also be blocked to guests in Office 365 Groups."
"By default, guests can access group files and the group OneNote notebook. To turn off guess access, you need to turn off the SharePoint external sharing setting at the organization level. For the steps, see Turn external sharing on or off for SharePoint Online, "Manage external sharing for Office 365 Group site collections."
However, even if the SharePoint external sharing setting is turned off, the files from SharePoint sites can still be shared with new guest users based on SharePoint settings. To learn more, see Manage external sharing for your SharePoint Online environment." 
From:
https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-guest-access-in-groups
https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off
