### ISSUE TITLE
We need a way to rename a domain.

### ISSUE THREAD

**Issue by jasonseatosky** [MicrosoftDocs/OfficeDocs-SharePoint#2680]
I desperately need a way to rename a SharePoint site. I have two different customers that need to be renamed.
Customer 1 - 500+ staff and changed their company name. I don't want to move them to a new tenant as we're using InTune, SharePoint, OneDrive... Everything.
Customer 2 - 100-200 Staff and a misspelled domain. I also don't want to move them to a new tenant.

**Is there a way we can pay Microsoft to rename the SharePoint site in the backend rather than migrating?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jasonseatosky** [comment]
Support referenced this page and said it's not possible and we would need to migrate to another tenant. That answer wasn't helpful and I'm looking for someone a little higher up who might be able to tell us if we can pay for the engineers to make it happen.
