### ISSUE TITLE
**Company name** cannot exceed 32 characters. Otherwise the upload of the zip file in the Teams Admin Center will fail.

### ISSUE THREAD

**Issue by DwayneSelsig** [MicrosoftDocs/OfficeDocs-SharePoint#2681]
https://docs.microsoft.com/en-us/SharePoint/viva-connections#step-by-step-guide-to-setting-up-viva-connections-desktop

Section 4: 
**Company name** cannot exceed 32 characters.
Section 5:
The upload will fail if the Company name is longer that 32 characters.

(It would be nice if The Viva Connections for desktop PowerShell script has a check for this, but currently it hasn't.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
