### ISSUE TITLE
Can no longer block file type

### ISSUE THREAD

**Issue by StephaneSeguin** [MicrosoftDocs/OfficeDocs-SharePoint#2682]
The file type can no longer be blocked.  
All file type are now allowed.

Stephane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types - OneDrive](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@StephaneSeguin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by derhallim** [comment]
All file types are allowed in SharePoint sites, however you can still control file types when syncing to OneDrive For Business, which is different and it's what this article is referring to. No change needed.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
