### ISSUE TITLE
Should the policy also affect Teams on unmanaged devices?

### ISSUE THREAD

**Issue by fdebout** [MicrosoftDocs/OfficeDocs-SharePoint#2683]
We have the unmanaged policy set to block access to SharePoint from unmanaged devices.
The policy also seems to affect the Teams mobile app as we get a "Can't access this resource from here" message.
Is this the expected behaviour?

Florian

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
