### ISSUE TITLE
Everyone except external users and public sites in SharePoint Online 

### ISSUE THREAD

**Issue by kjetilorama** [MicrosoftDocs/OfficeDocs-SharePoint#2684]
Hi 

I have a feedback on this particular page. https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups

Currently it says that for public sites, **everyone except external users** by default have edit access to public sites in SharePoint online, and that if you remove this user groups rights or change it to "read", it will be changed back to "edit". I.e the group is automatically set to members of the site. 

We have done some testing in my organizations, and from microsoft.techcommunity, I have noticed that several others have to come to the same conclusion: This does not occur anymore. Everyone except external users does not switch back to edit rights. 

Can you please confirm or clarify what is correct in this matter. 

Best regards, 
Kjetil 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ec832-b81d-d057-27e6-a73ddf5a6632
* Version Independent ID: 7062cc8d-9769-3463-6b75-226679d720d1
* Content: [Default SharePoint groups - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups)
* Content Source: [SharePoint/SharePointOnline/default-sharepoint-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/default-sharepoint-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@StephenRiceMSFT can you confirm?

**Comment by tseward** [comment]
Yes, I believe this did ultimately change back to the previous behavior where you can set Everyone except external to Viewer rights and it will 'stick' on a Public Team site.
