### ISSUE TITLE
Change Root Site causes hub settings issues

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/OfficeDocs-SharePoint#2685]
I've seen this issue twice.  Once with a client where it was just changing the URL and now on my own tenant where I changed the root site.  In both cases, I unregistered the site as a hub site and then made the change.  Upon re-registering the site as a hub site, the hub site settings are gone along with the ability to edit the navigation.

I've dug into the latest instance of the issue a bit.  Even though I unregistered the old site as the hub before the switch, when I registered the new site as a hub, the old (archive) site still has the hub site settings. To change the navigation, I need to go to the archive site.  I'm sure the issue will resolve over time as it did with the previous URL change.  The new root communications site is registered as a hub.  When looking at the Site Information settings, the new root communications site is associated to "itself" as the hub.  The archived site is associated to the new root site even though the hub site settings are on the archived site itself.  

I'm not sure how long one should wait after unregistering a hub site before doing a URL rename or change in root site. It's pretty frustrating.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by melkinsco** [comment]
Thank you, Manuela. I have submitted a ticket online and am working with someone.  The current request is to reproduce the error.  That's impossible for me as the system is preventing me from changing hub settings.  I cannot un-register the hub on the new root site, nor can I change the hub affiliation of the previous root site (now archive).  The hub settings are on the archive site, not the root site.  Needless to say, I'm in a bit of a catch-22.

Best,
Michael

Michael Elkins
Mobile: 303.246.7847
www.KeenIM.com<http://www.keenim.com/>
KEENIM
Advantage through information


________________________________
