### ISSUE TITLE
Powershell should validate for PNG icon format

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-SharePoint#2689]
The Viva powershell app creation process doesn't indicate the images needed need to be in PNG format. If its unable to be validated before building the application, when it  asks for the 192x192 and 32x32 image, it should indicate that the icon be in PNG format. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@StuBeck32  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @StuBeck32 how are you?
Here we are limited to documentation changes and improvements, a [recent commit](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/494dbe4dec2d1f4d61b6f49fb37ccc989f6fe7fd) was added to inform the PNG requirement to the article.
Thank you!
