### ISSUE TITLE
How long does it take to enable Anonymous one drive? Its been spinning for 10 minutes

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#269]
I am enabling it per the article, but it keeps spinning. Can someone add a note to the article on how long it usually takes to enable on an existing tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a570bb-2567-565c-e9ff-bf1ccbf38d0e
* Version Independent ID: 3d342dea-9dd3-008c-20c6-902452302e95
* Content: [Manage sharing in OneDrive and SharePoint](https://docs.microsoft.com/en-us/onedrive/manage-sharing)
* Content Source: [OneDrive/manage-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/manage-sharing.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by eschrader** [comment]
Anonymous External sharing needs to be enabled in SPO Admin and then in One Drive, otherwise it spins forever. If disabled in SPO Admin, it is disabled in One Drive.

**Comment by AndreaBarr** [comment]
@eschrader Thank you for this feedback

I agree these two details need to be in the article. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @eschrader , thank you for your feedback.

I think there is a line in the article about this:

"The external sharing setting for SharePoint can be more permissive than what you allow in OneDrive, but not less permissive. If you turn off external sharing for SharePoint in your organization, you can't turn it on for OneDrive."

Are you agree?
