### ISSUE TITLE
Summer 2021 not 2020

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/OfficeDocs-SharePoint#2690]
The page says "Viva Connections for mobile will become available in Summer 2020". Presumably this should be "Summer 2021"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Duplicate issue
