### ISSUE TITLE
Edit the document to note that this is a per geo setting

### ISSUE THREAD

**Issue by sudeepg100** [MicrosoftDocs/OfficeDocs-SharePoint#2694]
The content in this article is great, but it misses out on the fact that the sync and many settings for tenants who have muti-geo enabled are applied per geo, not tenant wide. Please update this article to include the information that in a muti-geo tenant, the settings are applied on per geo. Without that admins will apply a policy for a geo and run into issues where the geo is not being applied for a user simply because the user is in a different geographic location than what the policy is configured for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Allow syncing only on computers joined to specific domains - OneDrive](https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@sudeepg100  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @sudeepg100 how are you?
I do not have a multi-geo tenant lab available to test this, however, Set-SPOTenantSyncClientRestriction seems to be tenant-wide, @tseward what do you think about this? I appreciate your opinion. Thanks

**Comment by tseward** [comment]
@get-itips this, among other settings in the ODSP admin centers, are geo-specific.

**Comment by sudeepg100** [comment]
Thank you @tseward. I can confirm the behaviour since I have a customer who ran into this problem and we rectified it by applying the policy on the correct geo.

**Comment by get-itips** [comment]
@sudeepg100 will propose an improvement to the article. Thanks
