### ISSUE TITLE
Can't access referenced app bar cmdlets

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SharePoint#2696]
Hello, I've updated to the latest version of the Microsoft.Online.SharePoint.PowerShell module I can (16.0.20717.12000) but when I run the command Get-SPOTemporarilyDisableAppBar, I get "The term 'Get-SPOTemporarilyDisableAppBar' is not recognized as the name of a cmdlet, function, script file, or operable program."  Are the referenced cmdlets maybe not released yet or am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cb90e0-b8bb-32b2-d8b1-1710af6312f2
* Version Independent ID: 9d7a64c4-a3b0-47b8-b209-16e257a9a23a
* Content: [Use the new SharePoint app bar and set up global navigation - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-app-bar)
* Content Source: [SharePoint/SharePointOnline/sharepoint-app-bar.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-app-bar.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Hey @jmuehlenbein yes the script is available. 

Did you uninstall your older version of PowerrShell too?

**Comment by jmuehlenbein** [comment]
No, but the cmdlets should be cumulative if more than one version installed. I have the latest (as far as I can tell). Are you suggesting that removing an older version will somehow allow the new cmdlet to be surfaced?

**Comment by Holland-ODSP** [comment]
I agree its not an intuitive process to uninstall the older version. I do have a note in the notes section under "Temporarily disable the app bar" - but maybe they were too easy to miss?

Anyway, yes please uninstall the outdated PowerShell and then try again.

**Comment by jmuehlenbein** [comment]
I have to admit I doubted you but yeah...I can now access the cmdlets. Thanks so much! Guess I missed the part you're referring to above.

**Comment by Holland-ODSP** [comment]
I should make that note more obvious - glad we got this sorted out!

**Comment by jmuehlenbein** [comment]
Actually, I just re-read and it says to use the latest version of PowerShell but actually it seems we need the latest version of the Microsoft.Online.SharePoint.PowerShell module. It would be great if you could clarify for my fellow admins.
