### ISSUE TITLE
Please include which version of SharePoint this article applies to

### ISSUE THREAD

**Issue by dipetersen** [MicrosoftDocs/OfficeDocs-SharePoint#2697]
[Enter feedback here]
When reading these documents, SharePoint is mentioned generically when there are significant differences between SharePoint on-premise and SharePoint Online.  Specifically in the Modern experience.  While SharePoint 2019 adds the Modern Experience, a lot of the functionality that exists on SPO does not work on SP2019. It would be helpful to know which version of SharePoint you are referring to so when we search for SP2019, we aren't directed to SPO only functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe029ff2-3230-3320-aef5-9f16ab9464cc
* Version Independent ID: d791f3f6-257f-9a9b-461f-a12693d4bfde
* Content: [Branding your SharePoint site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience)
* Content Source: [SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@dipetersen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tseward** [comment]
I'm a little confused about the confusion. The article is in the SPO document tree -- is there a reason you would look for SharePoint Server docs in the SPO docs?

**Comment by dipetersen** [comment]
Unfortunately, I don't have the link.  I was doing massive research about branding / customizing the modern page on SP2019 and somehow landed here.  I came to the realization that what I wanted to do in 2019 was only possible on SPO so I gave up.  If I can find the linked page, I'll update this post.
