### ISSUE TITLE
Macros Excel is working after migrate to SharePoint Site 

### ISSUE THREAD

**Issue by Norafify89** [MicrosoftDocs/OfficeDocs-SharePoint#2699]
Hi, 

We have user that use Macros Excel 2010, Is Macros Excel will be working after migrate to SharePoint Teams Site? If not working, what is the consideration should we take if we want move to O365.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
