### ISSUE TITLE
Install RBS on second content database

### ISSUE THREAD

**Issue by mrdaipn** [MicrosoftDocs/OfficeDocs-SharePoint#270]
Hi there,

Today I have run out steps to install RBS on a second content database. Just notice on the note on this post saying that:
&gt; [!NOTE]
&gt; If you attempt to install SQL Server 2012 Remote Blob Store for an additional database on the same instance of SQL Server, you will receive an error. For more information, see [KB2767183](https://support.microsoft.com/en-us/kb/2767183). 

After receiving this error, copy and paste the following command into the Command Prompt window without the  `/qn` switch. This opens the RBS installer window where you can change only the database name and then follow the default options. You will then see the RBS tables are created in the second database.

msiexec  /lvx* rbs_install_log.txt /i RBS.msi TRUSTSERVERCERTIFICATE=true FILEGROUP=PRIMARY DBNAME="WSS_Content_RBS" DBINSTANCE="SQL2012SERVER" FILESTREAMFILEGROUP=RBSFilestreamProvider FILESTREAMSTORENAME=FilestreamProvider

I realized I have to remove the "DBNAME" parameter in this command in order to able to change the content database name in the installation wizard.

Appreciate if you can verify and correct the document (if I'm correct).

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4bfb2a-e225-fad9-5970-ca30acf9d92d
* Version Independent ID: 7cc3baec-8c7e-e5ee-cf16-812a4aa3c035
* Content: [Install and configure RBS with FILESTREAM in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/install-and-configure-rbs)
* Content Source: [SharePoint/SharePointServer/administration/install-and-configure-rbs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/install-and-configure-rbs.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@mrdaipn Thank you for this feedback

I agree this should be verified and updated. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.
