### ISSUE TITLE
Add information about deployment time

### ISSUE THREAD

**Issue by frnk01** [MicrosoftDocs/OfficeDocs-SharePoint#2700]
It should say something about the time it takes from the library is activated to it showing up in Office desktop applications. Have seen people saying it can take up to 48 hours.. I have now waited 24  hours, and still nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@frnk01 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
