### ISSUE TITLE
Configure team site libraries to sync automatically does not work on Root Sharepoint Site

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/OfficeDocs-SharePoint#2702]
We had a case open with MS (24738282) because a few customers Sharepoint Root sites weren't synching when using these policy and a few were. 
We found via this link (https://docs.microsoft.com/en-us/sharepoint/modern-root-site) provided on the troubleshooting that tenants setup after April 2019 automatically create a root site of the Communications type and not Teams Site anymore. Hence the automount policy currently does not work on sites which are not Teams type.

It would save people a lot of time to have a note on this policy telling people how to check the root site type and explaining it does not work if the root site is communications site.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#configure-team-site-libraries-to-sync-automatically)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by schenardie** [comment]
That exactly what this ticket is for. I had a ticket and something needs to be addressed on the docs.

**Comment by schenardie** [comment]
Can this be re-open?
