### ISSUE TITLE
 Set-SPOSite : This site has exceeded its maximum file storage limit. To free up space, delete files you don't need and empty the recycle bin.

### ISSUE THREAD

**Issue by humbletrad** [MicrosoftDocs/OfficeDocs-SharePoint#2703]
Hi, Sharepoint365, 

I have a site that under F3 then I update it to Business Standard and immediately run following. So how can I resolve max file storage limit?

Set-SPOSite -Identity "https://XXX.sharepoint.com/personal/XXXx" -StorageQuota "4194304" -StorageQuotaWarningLevel "4194000"

Set-SPOSite : This site has exceeded its maximum file storage limit. To free up space, delete files you don't need and
empty the recycle bin.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by HansBrender** [comment]
Business Standard has a max of 1 TB
https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
