### ISSUE TITLE
Change a site address - old address preserved by system for X days

### ISSUE THREAD

**Issue by mikael71** [MicrosoftDocs/OfficeDocs-SharePoint#2704]
In my example, we decided to change the template from Communication to Modern Team Site by some reason.

After changing the address to the sharepoint site, the site owner will be changed to **SHAREPOINT\system** and the old address is then **preserved for a time and cannot be re-used**.

![image](https://user-images.githubusercontent.com/8925981/115679202-9a853900-a352-11eb-9682-7401beb0504f.png)

The article doesn't mention anything about this, or how to remove the old URL.
As an administrator you cannot do anything with the old URL, since you do not have the rights.

**Either this is a bug, or documentation should be updated to also tell how long time the old URL will be preserved.**

Preferably I would, as an admin like to complete the removal.

As you can see below, I changed the site us to us2old, then I wanted to create a new us with another template, which was not possible so it was now us2
![image](https://user-images.githubusercontent.com/8925981/115679577-036cb100-a353-11eb-98c6-2a073e30c145.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mikael71** [comment]
> Thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

I have raised a couply of tickets, but since this site address change is missing, servicedesk doesn't understand the ticket, really annoying. 
To this documentation https://docs.microsoft.com/en-us/sharepoint/change-site-address section https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address team could just document:

When a site address is changed, the old site address can't be re-used for 93 days.
or
When a site address is changed, the old site address can't be re-used at all. Microsoft has changed the ownership for that address to SHAREPOINT\system
or
the best thing would be to explain how the site address (URL) could be reused.

**Comment by mikael71** [comment]
I recieved this from Office 365 support
https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects
since, the article above describe actions to do, the article below should refer to that article to ease up the admin work.
https://docs.microsoft.com/en-us/sharepoint/change-site-address
