### ISSUE TITLE
This release only supports small to medium Box accounts. 

### ISSUE THREAD

**Issue by JeffTheSPAdmin** [MicrosoftDocs/OfficeDocs-SharePoint#2706]
Can you please define what is meant by small to medium Box accounts?  Does this mean number of users, amount of content, type of license?  I'd like to migrate the content of only a few Box users to SPO but the Migration Manager fails with, "This Box account exceeds the maximum users supported by this preview."  Thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
