### ISSUE TITLE
Running the Viva Connections Desktop Script - Cmdlet not recognised "Get-SPOIsCommSite"

### ISSUE THREAD

**Issue by BloomerzUK** [MicrosoftDocs/OfficeDocs-SharePoint#2707]
Hi,

When running the provided script, it fails on the Teams Site validation process why the " Get-SPOIsCommSite" cmdlet is invoked. It seems as if this cmdlet doesn't exist (yet?).

I commented out lines 10 through 26 in the scripts and the rest seems to run normally.

Cheers

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/SharePoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
