### ISSUE TITLE
Link to private review document instead of public

### ISSUE THREAD

**Issue by alexwelcing** [MicrosoftDocs/OfficeDocs-SharePoint#2708]
In Viva Connection Recommendations, Home Site link goes to the internal review.docs version instead of the public documentation.

Section -> https://docs.microsoft.com/en-us/sharepoint/viva-connections#viva-connections-recommendations

Change 
https://review.docs.microsoft.com/sharepoint/home-site?branch=viva-connections-desktop
to
https://docs.microsoft.com/en-us/sharepoint/home-site?branch=viva-connections-desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections#viva-connections-recommendations)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thanks @alexwelcing I edit that now.
