### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by atdhe18** [MicrosoftDocs/OfficeDocs-SharePoint#2713]
Under  Step 3: Share the NEO sites with end users -> Share the Pre-onboarding site

2. In the Share site pane, enter the names of people to add them to the site. The permission level will be **ready** only.

Shouldn't it be "... The permission level will be **read** only"

**Comment by scanum** [comment]
@atdhe18 Please link the document you are referring to.

**Comment by atdhe18** [comment]
@scanum I'm sorry i totally forgot to put the link in the request.
https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub

**Comment by JarbasHorst** [comment]
Hello @atdhe18,

thanks for reporting this issue. I've authored a pull request, whenever it gets merged it'll close this issue!
@scanum, I also applied other fixes to the document.

Regards,
Jarbas
