### ISSUE TITLE
Where did the Agent Source Connector go in Mover?

### ISSUE THREAD

**Issue by propelrhead** [MicrosoftDocs/OfficeDocs-SharePoint#2714]
Mover documentation references File Server/Share migration sources via Agent app install ([https://mover.io/connectors/agent/](url)).  

Release notes even reference it: [https://docs.microsoft.com/en-us/sharepointmigration/mover-release-notes#agent-v135-september-22-2020](url), and a screenshot of the Source is shown here [https://www.mover.io/guides/general/#azure-blob-storage](url).

I managed to find and install the Agent on my system.  However, I do not see the Agent app as a valid Source Connector in the mover.io app.  Has it been killed off; perhaps in favour of the Migration Manager Task? If so, please bring it back so we can choose the tool we prefer to use.  If I should be seeing it, perhaps detail clear steps to make it appear.

Thanks in advance for taking the time to review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to Microsoft 365 - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migrate-to-sharepoint-online.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
