### ISSUE TITLE
Affect on data loss prevention policies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#2716]
It is my understanding that some of these limits may have an impact on DLP policies. If this is true, please add some explanation about this topic. Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171ee42a-95a9-6543-dd99-696ba7025cd0
* Version Independent ID: a3b3b40f-b808-7ac6-b420-a9b7bb0361fb
* Content: [Search limits for SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/search-limits)
* Content Source: [SharePoint/SharePointOnline/search-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/search-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @DeanGross Dea, how are you? hope you are doing good 👍 
I dug into this however could not find those limits, could you please detail which limits you heard that may have an impact on DLP? That way I can narrow the search,
Thank you!

**Comment by DeanGross** [comment]
If a file exceeds these limits what happens with DLP policies? are they ignored or does something else happen?

**Comment by get-itips** [comment]
> If a file exceeds these limits what happens with DLP policies? are they ignored or does something else happen?

Thanks for returning and detailing your inquiry.

I found this in another article:

> DLP evaluates any content that can be indexed.

[Source](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)

So according to that, anything that can not be indexed is not evaluated.
