### ISSUE TITLE
Link to download latest SharePoint Online Management Shell only has x86 version available to download

### ISSUE THREAD

**Issue by RichardMcElroy** [MicrosoftDocs/OfficeDocs-SharePoint#2725]
The link to download the latest SharePoint Online Management Shell only has the x86 version available to download.
Instructions on the page indicate download of the x64 version for 64 bit OS.
If the x86 download is the correct download for a 64 bit OS, the instructions on the page should be corrected, otherwise an additional link to the correct download page for the x64 version should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @RichardMcElroy I am looking into this.

**Comment by get-itips** [comment]
Hello @RichardMcElroy Richard, how are you?
I could dig into this, actually, the currently published link should offer both versions, I could report this and it should be corrected.
Thank you!
