### ISSUE TITLE
SharePoint, Permissions and Sharing

### ISSUE THREAD

**Issue by savindwarf** [MicrosoftDocs/OfficeDocs-SharePoint#2726]
I believe there is type of permission missing - and its causing me some problems, as follows:

1) Sharing.  We should be able to grant the rights to SHARE on any object (List/ Library).  Ideally we should have ShareRead and ShareWrite as separate permission grants.
   [Note, I believe in the current model someone with VIEW only access could share EDIT to an item (but perhaps this has been fixed)

2) A library/list should have an OPTION to block/allow sharing

3) For the non-technical users (i.e. most of them) its very confusing to understand the difference between sharing with someone that has an email address that can be validated and those than cannot and hence in a code on the share.  Its very confusing when the user has put in five email addresses and they are a mix.  I don't I don't know the answer, maybe just some better text explaining the situation.??

4) Sharing to Outsiders should have an option to put an expiration date whether the email can be validated or not.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c667543-9b4d-52bb-5cc6-e2dc9c092e9e
* Version Independent ID: b005a5f1-7616-4d94-f230-8c3bd78baaeb
* Content: [Sharing & permissions in the SharePoint modern experience - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions)
* Content Source: [SharePoint/SharePointOnline/modern-experience-sharing-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-experience-sharing-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @savindwarf 
How are you? Hope you are doing good.
I am afraid that here we are limited to issues in documentation, like missing information or corrections. For feature requests please follow [here](https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a?ui=en-us&rs=en-us&ad=us) on how can you communicate that kind of feedback.
Hope this information helps you.
