### ISSUE TITLE
Publishing Pages are not migrated with the SharePoint Migration Tool

### ISSUE THREAD

**Issue by spg-iwilson** [MicrosoftDocs/OfficeDocs-SharePoint#2727]
> "The files can migrate however the pages may not function correctly on the new platform"

In my experience, the migration tool does not migrate pages. The structure report includes the following entries for the Pages libraries:

> The list template 850 is not supported

The source is SharePoint 2013. The destination is a classic publishing portal in SharePoint Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58490214-7269-a09a-4e8d-8ddbc7a28b41
* Version Independent ID: b9b4abdd-c2ac-abf7-2388-3205eaa3e18f
* Content: [Migration Assessment Scan Publishing Pages - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/migration-assessment-scanpublishing-pages)
* Content Source: [migration/migration-assessment-scanpublishing-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migration-assessment-scanpublishing-pages.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @spg-iwilson how are you?

Here you will find the supported list templates by SPMT (SharePoint Migration Tool) https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates

The article you opened the issue for is about the Migration Assessment Scan Tool.

Let me know if I understood you well.

**Comment by spg-iwilson** [comment]
You understand me correctly. The Migration Assessment tool documentation states that the publishing pages files can be migrated. However in reality, these files are not migrated due to the list template 850 not being supported.

**Comment by get-itips** [comment]
Hello @spg-iwilson how are you?
I fired up my lab to test this, I could see the _The list template 850 is not supported_ message and that message links back to the mentioned article. @JoanneHendrickson Can I kindly request for your help here understanding if an edit is necessary for [this page](https://docs.microsoft.com/en-us/sharepointmigration/migration-assessment-scanpublishing-pages) regarding the support of SPMT with publishing pages?
Thank you, appreciate it.

**Comment by scanum** [comment]
@spg-iwilson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
