### ISSUE TITLE
Previous content in this article missing / linked to viva connections

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-SharePoint#2728]
"Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams | Microsoft Docs"
(https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites)"

Above is the title of the article that was located at the hyperlink provided. I recommend keeping (restoring) the previous content, as it may be beneficial to customers who want to create SPO sites as apps outside of Viva Connections use cases. 

Recommend pointing to Viva connections from the link rather than replacing the content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by get-itips** [comment]
Hello, I am looking into this.

**Comment by get-itips** [comment]
Hello @jebalert Joseph, how are you?

I could get some information, Viva Connections is the recommended and supported way to bring your intranet into Teams as it addresses many of the shortcomings and challenges customers faced in the approach referenced in the older article.

Hope this information helps you,

@scanum please close.

**Comment by jebalert** [comment]
Recommend keeping open, whoever made the change by deleting the old content should restore it and backlink to Viva Connections. 

I reiterate, use cases for SPO sites as apps for individual teams is valid, we shouldn't delete content that holds value. There's more to SPO sites as apps than just a main hub portal (intranet) use case which Viva Connections is.
