### ISSUE TITLE
Source of the pain

### ISSUE THREAD

**Issue by electronicnation** [MicrosoftDocs/OfficeDocs-SharePoint#2730]
I don't know why you warn me about the facts of this matter, when, you all brought me here. I was content destroying everything and starting a new. Oh wait what was the question? You know its a years part time service if you ask me stupid questions? Thats too far. I'm going home.

**Comment by electronicnation** [comment]
Where is the plutonium assholeio

**Comment by tnhung2011** [comment]
Kinda sus spam
