### ISSUE TITLE
SharePoint news published (users receive these based on relevancy)

### ISSUE THREAD

**Issue by Ian-Hawk-Hawkins** [MicrosoftDocs/OfficeDocs-SharePoint#2732]
Please can you provide more details about what "SharePoint news published (users receive these based on relevancy)" means?  If a user simply follows a site does this mean that they should get push notifications in the mobile app if a new news post is posted on the site(s) they follow?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e17f3ec-9489-1ab0-2f73-4a16f9f87e17
* Version Independent ID: 2ff1ac04-2a4e-a5b8-d03d-dc4b03e0ce1e
* Content: [Control notifications - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/notifications)
* Content Source: [SharePoint/SharePointOnline/notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/notifications.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @Ian-Hawk-Hawkins how are you? 👍 

I think this other link expands that scenario

> Notifications on mobile
> When an important, relevant news article is posted by someone in your close sphere of work, or posted to a site in which you are active, you will receive a notification on your mobile device ‘from SharePoint’ within your device’s notification tray. When you click on a notification, you are taken directly into the SharePoint mobile app to view the news article and all its data-rich, interactive content.

[Source](https://support.microsoft.com/en-us/office/create-and-share-news-on-your-sharepoint-sites-495f8f1a-3bef-4045-b33a-55e5abe7aed7)

Does this answer your question? Thank you

**Comment by Ian-Hawk-Hawkins** [comment]
Hi,

Thanks for the reply.

Unfortunately the reasons why you may get a push notification is still a bit too vague for us – what does “a site in which you are active” actually mean?

This post from August 2018: More granular push notification subscription? - Microsoft Tech Community<https://techcommunity.microsoft.com/t5/sharepoint-ama/more-granular-push-notification-subscription/m-p/240117>, says “we are working on evolving the News Published notification logic so that you are notified for news published in Sites you explicitly Follow.”

Did this ever get implemented?  It would be perfect if it was.  This would give users have the choice of following a site that they may not be “active” in, so they would always get the push notifications from that site.  This could work side-by-side with the Graph AI that determines the other site news that may be relevant to them.

Giving us the opportunity to manually “subscribe” to a sites new push notifications by following it would resolve all the questions we get from our users who are confused as to why some people get the notifications and they don’t.  Currently we just have to reply saying “you have to be more ‘active’ on the site”, which is not very helpful.

Many thanks,
Ian

**Comment by get-itips** [comment]
I understand @Ian-Hawk-Hawkins unfortunately, I do not have precision about if that notification logic was finally implemented. @kaarins Kaarin, can I kindly request your help clarifying this? I appreciate it.

**Comment by Ian-Hawk-Hawkins** [comment]
Hi @kaarins do you have any further information on how this works and it there is likely to be any changes to it?

A simple business case we have is our product teams are creating news articles when new functionality is added to products that we want our Sales team to know about.

Currently, as Sales are in a different part of the organisation to Product, then the functionality to get a push notification does not work: "Using the power of Microsoft Graph, SharePoint sends notifications based on:
- People you work with
- Managers in the chain of people you work with, mapped against your own chain of management and connections"

Our Sales team would simply like to follow the Product site to "opt in" to get push notifications when they post news.

**Comment by Ian-Hawk-Hawkins** [comment]
Hi - is there any update to this query?  Many thanks, Ian

**Comment by Ian-Hawk-Hawkins** [comment]
Hi - is there any update to this query? Many thanks, Ian

**Comment by Ian-Hawk-Hawkins** [comment]
Hi @kaarins - is there any update to this query? Many thanks, Ian

**Comment by get-itips** [comment]
@tseward Trevor, maybe you have some information about that? Thank you

**Comment by tseward** [comment]
@get-itips We'll need to ping the PG on this one.

**Comment by tiburd** [comment]
Sorry - I mistakenly linked a PR to this issue.

This issue is still open.

**Comment by tiburd** [comment]
@Ian-Hawk-Hawkins 
We have forwarded your query to the product group. We're sorry to say that, after their research, they are unable to provide specific details.

Thank you + best wishes.
