### ISSUE TITLE
Link to SharePoint Discussions Forums out of date

### ISSUE THREAD

**Issue by James-Simms** [MicrosoftDocs/OfficeDocs-SharePoint#2733]
Hi,

The link in the 'Need Help' section at the end of this page to the 'SharePoint discussion forum' points to a now closed forum site.  This section should be updated to reference MS Q&A instead and link to https://docs.microsoft.com/en-us/answers/topics/office-sharepoint-online.html.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-a-specific-sharepoint-site-or-onedrive)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@scanum this can be closed thanks.
