### ISSUE TITLE
How to use permissions as term store group manager?

### ISSUE THREAD

**Issue by taikuli** [MicrosoftDocs/OfficeDocs-SharePoint#2735]
Can you elaborate on how a user that has been assigned group manager permissions might use his permissions to manage the term group?

Of course the user is not a member of any other admin role. ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5356ce0-3900-09a4-c9e7-5d9804302f71
* Version Independent ID: 7136f8c3-11d7-1bec-9355-26e42787e0b2
* Content: [Assign roles and permissions to manage term sets - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/assign-roles-and-permissions-to-manage-term-sets)
* Content Source: [SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by taikuli** [comment]
The reason I'm asking for this information is, that I assigned some users as group managers and term store admins.
However, these users are unable to access the Term Store Management tool as they are no SharePoint Admins.
So maybe this is not a problem in the documentation, but a design flaw in the implementation since one has to be SharePoint Admin to access the Term Store Management tool.

**Comment by get-itips** [comment]
Hello @taikuli Martin, how are you?

Please see [here](https://docs.microsoft.com/en-us/sharepoint/open-term-store-management-tool#open-term-store-management-for-a-site)

Tested with a non-global admin user and group manager.

Hope this information helps you!
