### ISSUE TITLE
How many total Viva Connection Team Apps can be created in a Tenant?

### ISSUE THREAD

**Issue by ejazhussain** [MicrosoftDocs/OfficeDocs-SharePoint#2736]
How many total Viva Connection Team Apps can be created in a Tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Hey @ejazhussain technically, there is no limit to how many that can be created but its recommended that only one instance be deployed in Microsoft Teams as an app.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ejazhussain** [comment]
@Holland-ODSP Thank you for clarification
