### ISSUE TITLE
Google drive not activated

### ISSUE THREAD

**Issue by ma7mgte** [MicrosoftDocs/OfficeDocs-SharePoint#2737]
All of the Google Workspace shared drives have a status of "Google drive not activated" in the Scan status column.  I'm using the same account that I use for the Mover.io app.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
