### ISSUE TITLE
Google drive not activated

### ISSUE THREAD

**Issue by ma7mgte** [MicrosoftDocs/OfficeDocs-SharePoint#2738]
All of the Google Workspace shared drives have a status of "Google drive not activated" in the Scan status column. I'm using the same account that I use for the Mover.io app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e276bebe-2aaa-5701-57da-59a2baa73c58
* Version Independent ID: 1405b814-f193-5950-1908-6d1bac65d004
* Content: [Overview: Migrate Google Drive using Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-US/sharepointmigration/mm-google-overview)
* Content Source: [migration/mm-google-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-google-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by NickLoenders** [comment]
@ma7mgte did you manage to solve this? I am having the same issue.
