### ISSUE TITLE
LAN IP or Public IP?

### ISSUE THREAD

**Issue by pepperagusa** [MicrosoftDocs/OfficeDocs-SharePoint#2739]
In the article https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location#set-a-location-based-policy-in-the-new-sharepoint-admin-center, the screenshot has two examples: 172.16.x.x and 192.168.x.x.
One is a public IP, the other one is a LAN range. I would think that for Powerpoint 365, you need to enter a public IP (or public IP range), not a LAN range. Is that right? If so, the example in the screen is a bit misleading.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
