### ISSUE TITLE
Update Documentation for 64bit

### ISSUE THREAD

**Issue by SirBeredan** [MicrosoftDocs/OfficeDocs-SharePoint#2743]
The advise regarding detection rule probably needs to be updated to address the 64 bit client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync app per machine - OneDrive](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @SirBeredan how are you? Hope you are doing good.
The 64-bit client is still in public preview, once it reaches GA the article could be updated. 
Thank you!
