### ISSUE TITLE
BAD DESIGN DECISIONS - Cannot rename domain!

### ISSUE THREAD

**Issue by vjirasek** [MicrosoftDocs/OfficeDocs-SharePoint#2744]
Why, just why?!
https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name

Has anyone in Microsoft actually thought about this? Clearly, Microsoft does not need to rename their own subscription as they keep buying companies! But hey, other companies are changing names, merging and divesting. 

This is BIG FAIL!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
