### ISSUE TITLE
Is there a side by side old and new experience?

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-SharePoint#2746]
I'm struggling to understand this as just a long page of text. Could any visuals or a short video be added for learners who cannot maximise learning from text alone? Please could you also include how to check settings wherever you write how to set them? This would help those learning PowerShell to understand where they are starting from i.e check value, if not set, set by doing this, check value again to confirm it has been changed, exit process. Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
