### ISSUE TITLE
Note Correction

### ISSUE THREAD

**Issue by scottmurdock** [MicrosoftDocs/OfficeDocs-SharePoint#2747]
There appears to be an error in one of the notes on this page.  Referring to the Active Sites page in the SharePoint admin center, it says "To configure the site collection setting for site collections that do not appear in this list (such as Group-connected sites or individual OneDrive site collections)..."

It's true that OneDrives don't appear in the list but group connected sites do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scottmurdock** [comment]
Manuela, I don't understand this response.  I don't have any issue to resolve and don't need support.  I was just noting an error in the page.  The article says group-connected sites don't appear in the active sites list when actually they do.
