### ISSUE TITLE
File scheme is missing

### ISSUE THREAD

**Issue by yalattas** [MicrosoftDocs/OfficeDocs-SharePoint#2748]
For us to plan the migration in advance and reducing the risk of losing files, we should be able to know how the tool will work and clarify few assumptions such as if migration will happen to user-by-user and Admin must decide on the destination considering the fact that user could have thousands of files and folders with complex sharing scheme.
Other than that, what if an Admin is attempting to initiate a process for company-wide migration to move completely from Google Workspace to Microsoft Business. We should be able to anticipate how migration will work, what if a user is the owner of a root folder but inside of it hundred of files owned by another user within the same organization or different organization.

All these cases should be mentioned or at least stated as included on excluded for us to know which documentation to read and follow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402bdf2a-1b81-fca5-42f3-ba9a140a6fb6
* Version Independent ID: ed361570-2aa3-44a8-8b7a-74de71a6528a
* Content: [Review the destination paths for your Google migration with Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-google-step4-review-destinations)
* Content Source: [migration/mm-google-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-google-step4-review-destinations.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
