### ISSUE TITLE
Missing details on conditional access setting

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#2750]
Enum value of "AuthenticationContext"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @danmyhre Dan, how are you?
Can you kindly expand on your explanation about what you see is missing? Do you refer to Application Context feature that is in Preview currently?
I appreciate it, thanks

**Comment by danmyhre** [comment]
Correct, in PowerShell, it shows "AuthenticationContext" as a valid value, but there is no documentation on this. This isn't preview powershell.

**Comment by get-itips** [comment]
Hello @danmyhre Dan, I wasn't referring to preview PowerShell but to AuthenticationContext feature, which seems to be in Preview according to UI and documentation. 

Have you already seen these articles?

https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#authentication-context-preview and

https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#more-information-about-the-dependencies-for-the-authentication-context-option

I tried to use it as a parameter for ConditionalAccessPolicy, it was accepted but ignored, so probably the article you opened the issue for will be updated when it gets out of preview and becomes usable.

Hope this information helps you.

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
