### ISSUE TITLE
Steps for adding admins to disabled acccount

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/OfficeDocs-SharePoint#2751]
Where there is a warning about not admins from their own OneDrive, there is no guidance about adding additional site collection admins to a disabled account. 

When an AAD account is disabled, it seems to remove the mapped account object/profile in SPO. This means when you try to add an additional site collection admin to someone who is disabled, but hasn't yet been deleted, it produces red errors, and you must remove their object from the primary administrator and site collection administrators before you can add new ones. 

Some guidance about this or a link to another procedure / document would be useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-user-profiles#add-and-remove-admins-for-a-users-onedrive)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
