### ISSUE TITLE
Incorrect boolean syntax

### ISSUE THREAD

**Issue by talkingmoose** [MicrosoftDocs/OfficeDocs-SharePoint#2753]
Booleans in plists are not expressed as `<Bool>True</Bool>`. They are expressed as `<true/>` or `<false/>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
@talkingmoose Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @talkingmoose
