### ISSUE TITLE
View Only permission level prevents PDF download and the documentation needs correction

### ISSUE THREAD

**Issue by rachoksh** [MicrosoftDocs/OfficeDocs-SharePoint#2754]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@rachoksh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rachoksh** [comment]
See attached. 
<img width="501" alt="viewonly" src="https://user-images.githubusercontent.com/26829811/120045417-f2f8c780-bfdd-11eb-9519-4d37b0622bde.PNG">

**Comment by get-itips** [comment]
Hello @rachoksh I am looking into this.
