### ISSUE TITLE
OneDrive external sharing policies

### ISSUE THREAD

**Issue by aamir-khan-confiz** [MicrosoftDocs/OfficeDocs-SharePoint#2758]
When we are changing any external sharing setting in one drive organization wide, from this document we can have an overview of the deployment. But the impact of the change in sharing setting organization wide is not available in any of the Microsoft documentation. Please include a section in the documentation in which  organization wide impact of every change should be available  for administrators so they can communicate with their users more clearly while changing external sharing setting.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Change the external sharing setting for a user's OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/user-external-sharing-settings)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by aamir-khan-confiz** [comment]
Hi Concerned,

Here my point is to the improve the Microsoft documentation and include the impact of the change in sharing setting in the documentation. From the documentation it is understandable how we can change internal/external sharing of OneDrive but what is the impact of these changes on existing shared links, it is not available in the documentation. Being a tenant we are not facing any problem but documentation improvement is necessary and should have details about the impact of the changes on already shared links.

I hope you will understand my point and include these points on available documentation.

Regards,
-Aamir
