### ISSUE TITLE
OneDrive URL 

### ISSUE THREAD

**Issue by RDX-Vivek** [MicrosoftDocs/OfficeDocs-SharePoint#276]
I need a list OneDrive URL for all the users mapped with either their email id or AD ID or both

**Comment by AndreaBarr** [comment]
@RDX-Vivek Thank you for this feedback

I want to make sure your issue gets resolved quickly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
