### ISSUE TITLE
The URL for provisioning new Microsoft New Employee Onboarding sites will takes me to a page for creating MICROSOFT 365 LEARNING PATHWAYS

### ISSUE THREAD

**Issue by mvcsharepointdev** [MicrosoftDocs/OfficeDocs-SharePoint#2760]
I am reading this article @ [provision-neo-hub](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub) on how to provision NEO hub sites, but when i click on this link :-

![image](https://user-images.githubusercontent.com/79726511/120253648-35453180-c288-11eb-9239-5dd0869c00e0.png)

I will be redirected to a page to provision the "MICROSOFT 365 LEARNING PATHWAYS" and not the NEO sites.. any advice please? what is the url for creating NEO sites?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
