### ISSUE TITLE
This document has never been updated to actually provide any information on how to enable Conditional Access for OneDrive Sync Client

### ISSUE THREAD

**Issue by AlphaXD001** [MicrosoftDocs/OfficeDocs-SharePoint#2764]
This page says "Enable Conditional access support in the OneDrive sync App"

Where? How?

I have seen this document but it doesn't say how to enable - it talks about enable ADAL which is type of Authentication.  I have never found a way to specify the OneDrive Sync Clients to be controlled by Conditional Access Polices- only controls for all of Office products or SharePoint Sites permissions.

The page says updated Mar 2021 but I don't see any information since I asked the question in August 2020 on how to actually do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app - OneDrive](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by ngrahamdg** [comment]
Same here, I don't understand why they wouldn't at least just show a brief overview or example of a conditional access policy for the OneDrive Sync Client.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
