### ISSUE TITLE
"Other options" button missing???

### ISSUE THREAD

**Issue by sguyan** [MicrosoftDocs/OfficeDocs-SharePoint#2765]
[Enter feedback here]

Hi there,
I'm trying to create a Wiki Enterprise but the "Other Options" button isn't appearing under my "Team Site" and "Communications Site" buttons. Why is it missing?

Thanks,
Stephen G

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0419db4c-9918-fcbe-53b3-4aca315e7703
* Version Independent ID: 0eca18cd-d073-8a6c-47ba-3e3330d63167
* Content: [Create a site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/create-site-collection)
* Content Source: [SharePoint/SharePointOnline/create-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
