### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by mcloum** [MicrosoftDocs/OfficeDocs-SharePoint#2769]
Box-OneDrive permissions comparison image missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5366e6b-779b-29d6-1e06-a30963c4535d
* Version Independent ID: df5eaa56-f7a2-46a1-4852-2fdf70b7699a
* Content: [Mover migration - Setting up your Box source connector - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-box)
* Content Source: [migration/mover-box.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-box.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@mcloum  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @mcloum
