### ISSUE TITLE
Copy Libary ID missing

### ISSUE THREAD

**Issue by krisoshau** [MicrosoftDocs/OfficeDocs-SharePoint#2771]
Under the section "Configure team site libraries to sync automatically" please be aware the 'Copy library ID' no longer appears when clicking sync on the SharePoint library.

Generally, there should be a way to just see this in the SharePoint active sites page.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
