### ISSUE TITLE
Links are broken in GitHub info

### ISSUE THREAD

**Issue by pgdrews** [MicrosoftDocs/OfficeDocs-SharePoint#2773]
Several broken links exist in this page => https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md 

Just an FYI>  Thx.

**Comment by scanum** [comment]
@pgdrews  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @pgdrews Patrick, how are you?
Did you try to use a link directly from the markdown file? be aware that they might not work from there but from the published version:
https://docs.microsoft.com/en-us/sharepoint/viva-connections

I tested links in the article and they work for me, can you point to the link that is not working for you in the published article? https://docs.microsoft.com/en-us/sharepoint/viva-connections

Thanks!

**Comment by pgdrews** [comment]
It was the GitHub published version from this link OfficeDocs-SharePoint/viva-connections.md at live · MicrosoftDocs/OfficeDocs-SharePoint · GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md>.  I had assumed that this was the same version as published, but had not validated the live public page.  The live public page does not have the same issues.

Thanks!

Patrick Drews, MCSE
http://linkedin.com/in/patrickdrews
Email: ***@***.******@***.***>

________________________________

**Comment by get-itips** [comment]
Thanks for returning and sharing your comments!
@scanum please close

**Comment by get-itips** [comment]
@scanum please close

**Comment by scanum** [comment]
@pgdrews Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
