### ISSUE TITLE
Bad instructions - "Step 2. Under Dropbox, select Get started" - Dropbox does not exist on this page.

### ISSUE THREAD

**Issue by Bob-Fx** [MicrosoftDocs/OfficeDocs-SharePoint#2775]
If you open the link in Step 1. the page that is opened does not have any selection for "Dropbox" (Screenshot attached)
![NoDropBoxOption](https://user-images.githubusercontent.com/65665844/121410868-02a6d300-c931-11eb-800c-4d826a241210.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a83a2dc-b338-fcbe-1c12-f837396516fd
* Version Independent ID: ee0ef078-f0ac-c411-027a-bedfc62f934d
* Content: [Connect to Dropbox with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-dropbox-step1-connect)
* Content Source: [migration/mm-dropbox-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-dropbox-step1-connect.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
