### ISSUE TITLE
Mac Configuration missing

### ISSUE THREAD

**Issue by vmalapati** [MicrosoftDocs/OfficeDocs-SharePoint#2776]
[Enter feedback here]
###This page doesn't help to update deployment ring configurations for mac devcies

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8d826-fd44-b260-77e7-24d9ddd6e67f
* Version Independent ID: b0df9532-a918-a341-2790-a61a8c5c6894
* Content: [The OneDrive sync app update process - OneDrive](https://docs.microsoft.com/en-gb/onedrive/sync-client-update-process)
* Content Source: [OneDrive/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
@vmalapati  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @vmalapati how are you?
Checking to understand if you have seen this linked page https://docs.microsoft.com/onedrive/deploy-and-configure-on-macos#tier ?

**Comment by scanum** [comment]
@vmalapati Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
