### ISSUE TITLE
Google drive migration to Teams not working

### ISSUE THREAD

**Issue by NickLoenders** [MicrosoftDocs/OfficeDocs-SharePoint#2777]
The Google Workspace shared drives I want to migrate have a status of "Google drive not activated" in the Scan status column?

How can I solve this?

**Comment by scanum** [comment]
@NickLoenders  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
