### ISSUE TITLE
limited access and app-catalog-based web parts errors on unmanaged devices

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SharePoint#2779]
Along the lines of images not displaying when limiting access on unmanaged devices, when we view web pages via unmanaged device, we get errors (sorry something went wrong, etc.) on every web part originating from the app catalog. Is this expected? Any way around it like for the images? This is a showstopper for moving our intranet to SharePoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jmuehlenbein  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @jmuehlenbein how are you? Tried to reproduce (I think I followed your exact scenario, in case you feel not please provide more detail) in case we needed to correct or improve the article but couldn't. I think in this case the best would be to open a support ticket directly from your tenant, so you receive help on your specific scenario.
Hope this information helps you.

**Comment by jmuehlenbein** [comment]
Thank you for looking into it. I've done additional testing and it appears it may be some other CA policy that is causing the issue. I'll open a ticket as you suggested.

**Comment by get-itips** [comment]
@scanum please close thanks

**Comment by scanum** [comment]
@jmuehlenbein Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
