### ISSUE TITLE
Please can you clarify the starting point for this - where does this new experience get created from?

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-SharePoint#2780]
Hi, the page isn't clear about where these Teams are being created from. Will the UI change or does this refer to someone having a group-connected SharePoint site and adding a Team to it? I'm not sure where the starting point is, what is a user or admin clicking to get the new experience?

Thanks, Darrel

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bc6df5-e361-4aeb-6eb4-20a8c017fa39
* Version Independent ID: 1c50aa81-9779-8725-963a-5dc94a60940d
* Content: [Manage Teams connected sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/SharePoint/teams-connected-sites)
* Content Source: [SharePoint/SharePointOnline/teams-connected-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/teams-connected-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
@Darrelo365  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by Holland-ODSP** [comment]
Hi @Darrelo365
When you create a new Team in Microsoft Teams, the SharePoint team site gets automatically created even though you weren't using SharePoint. These Teams connected team sites store and manage content for the Team in Microsoft Teams. Most users who don't use SharePoint wont access the site, it exists for technical reasons. There is no change to the way you create and manage teams in Microsoft Teams or SharePoint sites, this article just explains how to manage the sites that get created in the event you need to but the bottom line if you should manage everything in Microsoft Teams. Hope this helps.
