### ISSUE TITLE
SPMT supportability for SharePoint 2019

### ISSUE THREAD

**Issue by MarwaMS92** [MicrosoftDocs/OfficeDocs-SharePoint#2782]
Hi ,

Is there is a way to use the tool with SharePoint 2019 ? or any estimated date/road-map for supporting SP19 on the SPMT ?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [SharePoint Migration Tool for SharePoint and OneDrive - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Investigating.

**Comment by MarwaMS92** [comment]
Any update please?

**Comment by JoanneHendrickson** [comment]
@MarwaMS92  - Sorry for the delay. At this time there is no immediate plan to support SP2019.  For some basic content migration it could be possible if you changed a registry key to make it work.  Its not an official feature but could be a workaround and not supported.

**Comment by MarwaMS92** [comment]
Hello,

Thanks a lot for your reply 😊

Do you know what’s the name of this registry key ?

Thanks,
Marwa Mohamed.

**Comment by koenti** [comment]
I'm also interested in the workaround we could use SPMT for SP2019...  Possible via which registry key?
