### ISSUE TITLE
batch change size recommendation

### ISSUE THREAD

**Issue by 410sean** [MicrosoftDocs/OfficeDocs-SharePoint#2786]
there is a recommendation 
"If you're changing many UPNs within your organization, make the UPN changes in batches to manage the load on the system."
where can we get some more details on batch size, for instance is 10,000 over night ok?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f86983-2dba-6234-61a5-44e956d25bc7
* Version Independent ID: 98c70405-65b4-3487-6c56-2df7d2ee7e0e
* Content: [How UPN changes affect OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/upn-changes)
* Content Source: [OneDrive/upn-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/upn-changes.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@410sean  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @410sean Sean,
I am looking into this.

**Comment by kaarins** [comment]
@WayneEwington can you advise? Thanks!

**Comment by WayneEwington** [comment]
@kaarins lets discuss as per my email to you.

**Comment by WayneEwington** [comment]
Unfortunately there are many moving factors that can influence what would be recommended batch size. The general guidance is to keep these reasonably sized such that any required processing is distributed. If further guidance is required for your actual scenario, then the recommendation is to contact Microsoft Support.

**Comment by get-itips** [comment]
Thanks @WayneEwington 
@scanum please kindly close
