### ISSUE TITLE
These instructions seem to be for the older style term store managemnent page and not the new page.

### ISSUE THREAD

**Issue by chloegilbert** [MicrosoftDocs/OfficeDocs-SharePoint#2787]
These instructions dont seem to tie up with what we are seeing here. 

Yes Im a tenant admin and Im trying to get access for a term store manager without gicving them SP admin rights.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5356ce0-3900-09a4-c9e7-5d9804302f71
* Version Independent ID: 7136f8c3-11d7-1bec-9355-26e42787e0b2
* Content: [Assign roles and permissions to manage term sets - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/assign-roles-and-permissions-to-manage-term-sets)
* Content Source: [SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@chloegilbert  Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by get-itips** [comment]
Hello @chloegilbert Chloe, how are you? Hope you are doing good.
Tried this on my test tenant, to check if we needed to correct the article, I could follow the instructions successfully, once I added myself as a Term Store administrator. Even though I am a tenant admin.

Could you please check you have this permission?

Thanks

**Comment by scanum** [comment]
@chloegilbert Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
