### ISSUE TITLE
Intune Admin template to Enable OneDrive Health

### ISSUE THREAD

**Issue by rautwar** [MicrosoftDocs/OfficeDocs-SharePoint#2792]
I can't find the OneDrive admin template setting in Intune to enable OneDrive Health.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://docs.microsoft.com/en-us/OneDrive/sync-health)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
