### ISSUE TITLE
Wrong like operator pattern

### ISSUE THREAD

**Issue by Urpiano** [MicrosoftDocs/OfficeDocs-SharePoint#2793]
On the script to generate a file with the OneDrive for Bussiness sites, the expression for the like operator on the filter for the Get-SPOSite Cmdlet hasn't wildcards, so, it never will found any Onedrive for Bussines site!

This: `Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like '-my.sharepoint.com/personal/'"`
Should be this: `Get-SPOSite -IncludePersonalSite $true -Limit All -Filter "Url -like '*-my.sharepoint.com/personal/*'"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f92a9b5-b3b2-aceb-9813-a3e48bb469ca
* Version Independent ID: 55aa37c6-998b-a8d8-8986-88c4ed868aea
* Content: [Get a list of all user OneDrive URLs in your organization - OneDrive](https://docs.microsoft.com/en-us/onedrive/list-onedrive-urls?redirectSourcePath=%252fen-us%252farticle%252fhow-to-display-a-list-of-onedrive-for-business-site-collections-8e200cb2-c768-49cb-88ec-53493e8ad80a)
* Content Source: [OneDrive/list-onedrive-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/list-onedrive-urls.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Urpiano** [comment]
Sorry, I don't need open a service ticket caused by a typo on your document! :-P

Simply, try the Cmdle Get-SPOSite with the like filter as the one on the document and nothing will be retrieved; try it with the modification I proposed and you'll get the OneDrive Sites
