### ISSUE TITLE
Error when trying to install SPMT if O365 account has 2FA enabled

### ISSUE THREAD

**Issue by akosibananaman** [MicrosoftDocs/OfficeDocs-SharePoint#2794]
Hi all,

I encountered an error while trying to install the SPMT agent to one of my Windows Server 2019 machines. After I entered my company credentials that has Sharepoint admin privileges (it usually asks for 2FA afterwards), I get this error.

Cannot access Sharepoint Online Migration Service.

Error: The Migration agent couldn't be installed. Close setup and try again.

Failed to acquire token silently as no token was found in the cache. Call method AcquireToken.

Help, please?

Thanks and regards,

Aaron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [SharePoint Migration Tool for SharePoint and OneDrive - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool?source=docs)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
