### ISSUE TITLE
Site Swap: "This site is on hold"

### ISSUE THREAD

**Issue by jimmywim** [MicrosoftDocs/OfficeDocs-SharePoint#2797]
If the swap intending to be swapped in has a retention policy on it, the text "This site is on hold" appears.

The documentation should include caveats around retention policies on sites that intending to be swapped in so that we can take this into account when using this article as a reference in preparation for a site swap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jimmywim** [comment]
Hi - I know how the resolve the problem I have no need to create a support ticket, I created this issue because the documentation is missing information about needing to ensure Retention Holds are not in place prior to a site swap being done.
