### ISSUE TITLE
Domain Verification?

### ISSUE THREAD

**Issue by JankeSkanke** [MicrosoftDocs/OfficeDocs-SharePoint#2798]
Is the domain supposed to be autoverified? After adding a new .onmicrosoft.com domain I just get the normal "Verify your domain" prompt. And ofc I cant add DNS entries to make that work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by mikelee1313** [comment]
As of right now, you need to use the URL in step 2 to make it work.

**Comment by JankeSkanke** [comment]
Thank you. When we try to run the Start-SPOTenantRename  command we get the follwing error: 
Start-SPOTenantRename : Error Code: -773,Not Implemented! Any idea on when we should except this to work, and if there is a way to verify the preview is in place?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JankeSkanke** [comment]
I have learned that this feature thst requires manual flighting of the tenant. This should be set as a note on the docs page with a link to the nomination form. 

https://aka.ms/SPOTenantRenameNomination

Right now the docs gives the impression this is open to anyone.
