### ISSUE TITLE
255 character limit has to be changed to 400

### ISSUE THREAD

**Issue by bhanuchintha** [MicrosoftDocs/OfficeDocs-SharePoint#28]
Hello Team,

I think this 255 character limit is being changed now to 400 for SP Online. For SP Server versions this 255 character limit stands correct. Please review & modify .

Thanks & Regards,
Bhanu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca80d4a-c182-215b-3ecc-df556fc49d7d
* Version Independent ID: 3ab60a99-be05-49d6-f460-bb43c0a14377
* Content: [Migration Assessment Scan Long OneDrive URLs](https://docs.microsoft.com/en-us/sharepoint/migrate-to-sharepoint-online/migration-assessment-scan-long-onedrive-urls)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/migration-assessment-scan-long-onedrive-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/migration-assessment-scan-long-onedrive-urls.md)
* Service: **unspecified**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
updated.
