### ISSUE TITLE
eDiscovery functionality

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#280]
What is meant by the statement, "You might have to set up eDiscovery separately"? Will an O365 eDiscovery case include content from SP 2013/2016? Will the O365 Data Loss Prevention Policies, apply to content from on-premises?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a7967e8-384b-4edd-6f0a-5c4ecbe9c9e4
* Version Independent ID: 14267c4c-2f0f-0aed-71b3-1d5f1fb02304
* Content: [Learn about cloud hybrid search for SharePoint](https://docs.microsoft.com/en-us/sharepoint/hybrid/learn-about-cloud-hybrid-search-for-sharepoint)
* Content Source: [SharePoint/SharePointServer/hybrid/learn-about-cloud-hybrid-search-for-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/learn-about-cloud-hybrid-search-for-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

I agree that this should be clerified. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by tseward** [comment]
@DeanGross I think the answer to this is that you absolutely need to set up a separate eDiscovery on-prem as you can no longer create those in SPO (https://support.office.com/en-us/article/Set-up-an-eDiscovery-Center-in-SharePoint-Online-A18F8975-AA7F-43B4-A7D6-001D14744D8E). Will look into the DLP part of your question and get back to any edits that may need to be made on this article.
