### ISSUE TITLE
SCCM-OneDrive.zip on this Page Does Not Work, Please Fix It.....

### ISSUE THREAD

**Issue by MikhailCompo** [MicrosoftDocs/OfficeDocs-SharePoint#2800]
The "the sample Configuration Manager package" on this page 'SCCM-OneDrive.zip' does not work and has never worked since July 2020, the installation fails as the detection method is garbage. Please fix it and investigate why something that does not work was not reviewed before making public.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using Microsoft Endpoint Configuration Manager - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @MikhailCompo How are you? hope you are doing good.
I was digging into this, the sample Configuration Manager package file is not hosted in Docs, but in a separate repository, so I'll try to pass this on.
Thank you

**Comment by scanum** [comment]
@MikhailCompo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
