### ISSUE TITLE
Verify XML for EnableODIgnore is correct

### ISSUE THREAD

**Issue by talkingmoose** [MicrosoftDocs/OfficeDocs-SharePoint#2802]
The XML example for EnableODIgnore does not follow property list (plist) specifications. Is the `<dict>...</dict>` part of this necessary? Arrays can include lists of strings. Dictionaries typically require key/value pairs.

The example provided is:

```
<key>EnableODIgnore</key>
<array>
    <dict>
        <string>*.PST</string>
    </dict>
</array>
```

I would expect:

```
<key>EnableODIgnore</key>
<array>
        <string>*.PST</string>
</array>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#enableodignore)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
