### ISSUE TITLE
SPAdmin cannot add an Org Asset Library

### ISSUE THREAD

**Issue by sudeepg100** [MicrosoftDocs/OfficeDocs-SharePoint#2804]
In the section, Use Microsoft PowerShell to specify a library as an organization assets library, point #5, we are saying Connect to SharePoint as a global admin or SharePoint admin in Microsoft 365.

The reality is that when logged in with a SharePoint Admin role, the user cannot successfully add an organization asset library using the Add-SPOOrgAssetsLibrary cmdlet. It fails with this error

Add-SPOOrgAssetsLibrary : Attempted to perform an unauthorized operation.
At line:1 char:1
+ Add-SPOOrgAssetsLibrary -LibraryUrl <Url>

I realize this may be a product defect and needs correction but please add a section of Known issues for this article if possible and suggest remediation as using a global administrator temporarily. I am a MSFT employee and will submit a formal hotfix request to get this sorted out.

Cheers,
Sudeep

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @sudeepg100

**Comment by AmonM15** [comment]
Hi,

Has a resolution for this issue been found as I'm currently having the same issue.
