### ISSUE TITLE
Contradiction among MS Docs with url length limit

### ISSUE THREAD

**Issue by RoyKimYYZ** [MicrosoftDocs/OfficeDocs-SharePoint#2806]
According to this statement in this document

Long URLs | Any absolute URLs to sites or content that exceed the maximum URL length limit of 400 characters won't work. | If the new domain name is longer than the original, review the URLs of all sites, lists, document libraries, list items, and files before your change the domain name to make sure the new URLs won't exceed 400 characters.

is in contradiction to 

https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa
  
File name and path lengths
Applies to:     
Different apps and Office versions have different limits, and the combination of limitations may be unique to your setup.
The entire decoded file path, including the file name, can't contain more than 400 characters for OneDrive, OneDrive for work or school and SharePoint in Microsoft 365. The limit applies to the combination of the folder path and file name after decoding. 
For example, if the file URL in SharePoint is https://www.contoso.com/sites/marketing/documents/Shared%20Documents/Promotion/Some%20File.xlsx, the limit applies to “sites/marketing/documents/Shared Documents/Promotion/Some File.xlsx.”

Please clarify if absolute or relative to the domain name url.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @RoyKimYYZ Roy, how are you?
I tracked down a little bit the last update on this limit, see [this](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/new-maxpath-limits-in-sharepoint-and-onedrive/ba-p/68273) 

My take is that what the Docs article says is the current limit, but I'll try to confirm.

@tseward in case you want to add something, be my guest

**Comment by WayneEwington** [comment]
@RoyKimYYZ  After reviewing this with the Engineering team, the limitation associated with URL lengths is being removed as you are correct in that this applies to URL after the domain name.  However, although there is also a length limit associated with the Domain name portion, this is not expected to be encountered.

**Comment by get-itips** [comment]
Thanks @WayneEwington Wayne for clarifying!

**Comment by scanum** [comment]
@WayneEwington Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by RoyKimYYZ** [comment]
Thank you everyone. 

Roy Kim (MVP)
