### ISSUE TITLE
Correction needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#2807]
This statement is impossible.

_Files and folders can be shared only with users whose segment matches that of the OneDrive_. In the above example, **users in the Sales segment can share OneDrive content with other users in either the Sales or HR segment** whereas users in the HR segment can share their OneDrive content with other users in the HR segment only.

Since OneDrive can only be shared with users whose segment matches, a user in Sales (since a segment is applied) would ONLY be able to share with other users in Sales. Users in HR would not be able to access the content because their segment does not match that of the site. Even though there is no policy blocking it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef03ccd-fd27-4724-75c1-eec90be8ad8b
* Version Independent ID: a9e393d2-9bcc-3814-2654-bd40f23d5306
* Content: [Use information barriers with OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/information-barriers)
* Content Source: [OneDrive/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/information-barriers.md)
* Service: **one-drive**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @danmyhre Dan, I am digging into this.
Thanks

**Comment by get-itips** [comment]
Hello @danmyhre 

I tested the described scenario on my lab:

> Users in the Sales segment can share OneDrive content with other users in either the Sales or HR segment whereas users in the HR segment can share their OneDrive content with other users in the HR segment only.

I could verify what that sentence describes, using a user in Sales I could share with other users in Sales and in HR (but not with users in research) and logging in with a user in HR i could only share with users in HR.

Please take into account that a onedrive can have more than one segment.

`InformationSegment : {3a195426-3fb3-408d-9871-4d530534a300, c8b4de8c-f182-4b60-b9a1-666cecb62224}`

Let me know if I understood you well,

**Comment by danmyhre** [comment]
The information segment of the OneDrive site would be based on the segment of the user. It is not clear how a OneDrive would have multiple segments since there is a 1:1 relationship between a user (only 1 segment possible) and a OneDrive site.

**Comment by get-itips** [comment]
> The information segment of the OneDrive site would be based on the segment of the user. It is not clear how a OneDrive would have multiple segments since there is a 1:1 relationship between a user (only 1 segment possible) and a OneDrive site.

From the article:

> With information barriers in OneDrive, when a segment is applied to a user, within 24 hours that segment is automatically associated with the user's OneDrive. Other segments that are compatible with the user's segment and with each other will also get associated with the OneDrive. A OneDrive can have up to 100 segments associated with it.

Hope this information clarifies it to you!

**Comment by danmyhre** [comment]
I am not seeing that behavior. The user's ODfB site only has 1 segment attached to it.

**Comment by get-itips** [comment]
> I am not seeing that behavior. The user's ODfB site only has 1 segment attached to it.

@danmyhre Dan, then I recommend going thru again the documentation as that did not happen to me, setting up this scenario, and as I shared in the last message, an ODfB can have more than one segment.
Hope this information helps you,

**Comment by danmyhre** [comment]
@get-itips I found where the defect is. The OneDrive is only properly stamped with all compatible segments IF it has a policy assigned to its user's own segment. For users that don't have a block policy attached to their segment, the OneDrive is not properly stamped. I will open a support ticket on this defect.
