### ISSUE TITLE
 Error Code: -773,Not Implemented!

### ISSUE THREAD

**Issue by prattay56** [MicrosoftDocs/OfficeDocs-SharePoint#2808]
I get the below error 
_CorrelationId: b017d49f-d039-0000-a3e1-1c8af3834b20
Start-SPOTenantRename : Error Code: -773,Not Implemented!
At line:1 char:1
+ Start-SPOTenantRename -DomainName **<MASKED for privacy>** -Confirm -ScheduledDateTime ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-SPOTenantRename], Exception
    + FullyQualifiedErrorId : Error Code: -773,Not Implemented!,Microsoft.Online.SharePoint.PowerShell.StartSPOTenantRename_

What is the meaning of this ?  **Error Code: -773,Not Implemented!**
I have 
1. Targeted release 
2. 24 hours in the future
3. Latest module  16.0.21314.0
4. 
![image](https://user-images.githubusercontent.com/74849664/122794306-b74dd680-d2d9-11eb-875e-610eddfb0a93.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by WayneEwington** [comment]
@prattay56 This feature is currently in Private Preview with the documentation being updated to reflect this. As you are getting a "Not implemented" exception, then either you have NOT been accepted into the Private Preview OR if you have, then your enablement is still being rolling out across the service (and you can retry in a few hours).
