### ISSUE TITLE
Get latest sync client

### ISSUE THREAD

**Issue by BacharBader** [MicrosoftDocs/OfficeDocs-SharePoint#281]
Didn't find the OneDrive sync client build 18.171.0823.0001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@BacharBader Thank you for this feedback. 

The Article states To use the following Group Policy objects, you need the OneDrive sync build 18.111.0603.0004 or later. 

I an not sure what you inquiring about. 

If this is not an inquiry about the article and you need to find the software contact support and they can handle that to resolution 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by BacharBader** [comment]
Thank you for your reply and support.
The article states to use the sync client build 18.171.0823.0001 or later. but latest production ring according to Microsoft is 18.151.0729.0012. Ref: https://support.office.com/en-us/article/new-onedrive-sync-client-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0

so this setting of "Silently move Windows known folders to OneDrive" will not be effective in this production ring update, and we should wait until version 18.171.0823.0001 is released. right?

**Comment by AndreaBarr** [comment]
@BacharBader The article that you commented on states to use 18.111.0603.0004 or later. This second article states that 18.172.0826.0010 is an insider ring and hasn't been pushed out to production yet.

**Comment by BacharBader** [comment]
@AndreaBarr I'm talking about one setting only that is require this newer version. here is below i will copy and paste from the article above:

Silently move Windows known folders to OneDrive

Use this policy with the sync client build 18.171.0823.0001 or later to move your users' known folders to OneDrive without user interaction. (You can choose to display a notification to users after their folders have been redirected.)

Note

Previously, this policy only redirected empty known folders to OneDrive. Now it redirects and moves any content in known folders.

**Comment by AndreaBarr** [comment]
@BacharBader Yeah It looks like the Insider Ring is for internal Microsoft users. I faintly remember an "insider program" Though. Either way we shouldn't be referencing a version not available yet in the article. I am going to get this over to the SharePoint team so we can get this looked into. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kaarins** [comment]
@BacharBader , thanks for this feedback. I will add the links to the Insider program!
