### ISSUE TITLE
"Plan, build, and manage a home site" link goes to a 404

### ISSUE THREAD

**Issue by JellyKid** [MicrosoftDocs/OfficeDocs-SharePoint#2810]
The link goes to 404.
I think this should be the correct link:
https://docs.microsoft.com/en-us/sharepoint/home-site-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@scanum please close, already fixed.
