### ISSUE TITLE
Search for people within a site of the hub or within the hub does not display People

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-SharePoint#2813]
Search in a site or in a hub, does not return People Section.
People section is only visible if you search the SharePoint homepage or the office.com homepage, or by clicking "search all org" after the search per site does not return the proper info.

The article suggests PEOPLE search might be available at HUB site level, while it is not
"Can users search across all sites of an administrative unit?
It's possible, but it takes some effort to do this with classic search. It's better to use a hub site to organize the sites. Hub sites use Microsoft Search, which is scoped to search for news, **people**, files, and sites **across all sites that are associated with the hub**. Learn more about hub sites" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b864d5f6-b3d0-418b-62f9-5e33a69c6e37
* Version Independent ID: 7763bfd1-5cda-ab14-b7e8-ff6b4f16200a
* Content: [Get started with the modern search experience - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/get-started-with-modern-search-experience)
* Content Source: [SharePoint/SharePointOnline/get-started-with-modern-search-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/get-started-with-modern-search-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by teomonda** [comment]
hello Manuela,

I don;t think it makes sense to reach out to support as this is an option that is simply not there and I doubt a support request would "resolve" it. It is not quite an incident but rather a design limitation.
I was highlighting that the documentation seems to erroneously set the expectation that you could do it, so I would simply remove the "people" note from that line.
