### ISSUE TITLE
About adding supported list templates ("Page" library)

### ISSUE THREAD

**Issue by temiyaha** [MicrosoftDocs/OfficeDocs-SharePoint#2814]
In a SharePoint on-premise environment, the "Page" library (template id 850) is used by many users. 
This template can't be migrated by SPMT tool.
>The list template 850 is not supported

Could you clearly mention that "Page" library is not supported in this page?
https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390c33f7-7e70-6741-2a61-9538b87bec0a
* Version Independent ID: c3be3fb4-c28b-5513-651a-fe8b174a0a33
* Content: [SharePoint Migration Tool supported SharePoint List templates - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates)
* Content Source: [migration/sharepoint-migration-supported-list-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-migration-supported-list-templates.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @temiyaha Tetsuo,
How are you? Hope you are doing good, the article lists those templates that are supported, so everything that is not explicitly mentioned = not supported.

**Comment by temiyaha** [comment]
Hell @get-itips 
Thanks for the reply. I'm doing well. Hope you are doing well too.

Some list templates are clearly listed as unsupported. (Supported by SPMT is "No") 
The "Page library" (850) is used by many customers, so it's very helpful to have it clearly stated in this page.
Is it difficult to list? 
Or could you mention that "everything that is not explicitly mentioned is not supported." at the top of this page?

**Comment by get-itips** [comment]
@temiyaha Tetsuo, you are right, I'm sorry there is indeed a supported column in the table.
Will propose an improvement to the article and ask for a review.

**Comment by temiyaha** [comment]
Thank you in advance for your consideration.
Let me know if there's anything I can do to help.

**Comment by temiyaha** [comment]
Hello @get-itips 
Do you have any update on this issue?

**Comment by get-itips** [comment]
> Hello @get-itips
> Do you have any update on this issue?

Hello! PR is awaiting approval

**Comment by temiyaha** [comment]
Thank you for your support!
