### ISSUE TITLE
How to verify a secondary onmicrosoft Domain

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-SharePoint#2816]
Hi,
you describing how to add a secondary onmicrosoft domain as an custom domain. How can I set another onmicrosoft.com Domain in the status "Verified". MSFT is responsible for this namespace.

Regards 
Jakob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename?WT.mc_id=M365-MVP-5002378)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by J-a-k-o-b** [comment]
If you're using the link which is written in the docs here it works like a charm. I navigated before manually to the place where to add an domain. But the link that's provided contains some *magic*.
I think you should note it in the docs that this special link has to be used.
