### ISSUE TITLE
I have set up a communication site as Home site but starter page is not changed

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/OfficeDocs-SharePoint#2817]
Hi team,

i have created a new communication site and same is done successfully but the startup page is not linked to the newly created site and still going to sharepoint startpage. 
Home is correctly set up , do i need to change this site to root site also to make that change happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d251803-3835-ca8f-f664-1a056496fbbe
* Version Independent ID: 58bb7de2-7f44-d53d-8026-0f5023dcd9f9
* Content: [Set up a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
