### ISSUE TITLE
What is a 'vanity domain'?

### ISSUE THREAD

**Issue by CW-RKR** [MicrosoftDocs/OfficeDocs-SharePoint#2822]
You write here https://docs.microsoft.com/en-us/sharepoint/tenant-rename

`
Vanity domain configurations | Your domain name can't be changed if you have a vanity domain configuration.
`

Can you please clarify what a vanity domain is? Is it the same as a custom domain (used for mail)? I wanted to change my SP-name from 'joesboringcompany.sharepoint.com' to 'joesawesomecompany.sharepoint.com', sort of. But my custom domain is 'joescompany.com'. Do I have a vanity domain related problem?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
