### ISSUE TITLE
Hub site navigation with extended header on homesite

### ISSUE THREAD

**Issue by guywel** [MicrosoftDocs/OfficeDocs-SharePoint#2824]
Your Note:
  When you apply the extended header layout to the site, **you will no longer see the hub navigation**.
This did not work as expected.

Our homesite is a hub-site with extended header and 'hub or global navigation' selected. The 'site navigation' disappears and is replaced with the hub-navigation. 
When scrolling down, the extended header will collapse and the site navigation will appear replacing 'the hub navigation' on the header. 

I already raised a ticket with Microsoft Support and they claim that this is 'By design'. 
Their advice is to not use extended design. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cb90e0-b8bb-32b2-d8b1-1710af6312f2
* Version Independent ID: 9d7a64c4-a3b0-47b8-b209-16e257a9a23a
* Content: [Use the new SharePoint app bar and set up global navigation - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-app-bar#customize-global-navigation-in-the-app-bar)
* Content Source: [SharePoint/SharePointOnline/sharepoint-app-bar.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-app-bar.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by guywel** [comment]
Hi Manuela,

 

I did log a ticket, but then they said it was ‘By Design’ so the ticket was closed.

So how can it be ‘By design’ when it does not match with the documentation?

 

Documentation says that the hub-navigation disappears, but in reality the site navigation disappeared.

 

Please advise…

 

Kind regards, 

 

Guy

 

 

Van: Manuela Scanu ***@***.***> 
Verzonden: dinsdag 29 juni 2021 23:55
Aan: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
CC: guywel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Hub site navigation with extended header on homesite (#2824)

 

Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Holland-ODSP** [comment]
Hey @guywel - You are right, there is an error in the article here. I'll get this updated. Thank you!
