### ISSUE TITLE
Domain Name Format for Rename Command

### ISSUE THREAD

**Issue by ForeheadSQX** [MicrosoftDocs/OfficeDocs-SharePoint#2828]
The documentation shows the following format for the rename:

Start-SPOTenantRename -DomainName <DomainName>

The example command shows the following:

Start-SPOTenantRename -DomainName "fabrikam"

Is the rename command setup to use just the domain prefix "fabrikam" or the entire domain name "fabrikam.onmicrosoft.com"?

For ID: "e0a4a71a-aa4d-1066-8f76-742c3411f06c"

**Comment by WayneEwington** [comment]
@ForeheadSQX As per the example (and text), the parameter is only expected to contain the name of the domain. I.e. the part before "sharepoint.com" or "onmicrosoft.com". For example, if you are renaming your SPO tenant to fabrikam.sharepoint.com, the the DomainName parameter value would be "fabrikam".

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
