### ISSUE TITLE
Soon to be deprecated links.

### ISSUE THREAD

**Issue by TeslaSysA** [MicrosoftDocs/OfficeDocs-SharePoint#2833]
Please update the admin.onedrive.com links to the SharePoint admin center links. The currently link will be deprecated/unavailable in 2 weeks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises - OneDrive](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@TeslaSysA Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @TeslaSysA
