### ISSUE TITLE
Connect to Dropbox does not specify minimum account level

### ISSUE THREAD

**Issue by jmcarthurcorr** [MicrosoftDocs/OfficeDocs-SharePoint#2834]
When using the SharePoint migrator for connecting to Dropbox, I get an error "please sign in with a work account." There is nothing in the documentation on this tool or process that indicates a Dropbox business account is required. Please update with this requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a83a2dc-b338-fcbe-1c12-f837396516fd
* Version Independent ID: ee0ef078-f0ac-c411-027a-bedfc62f934d
* Content: [Connect to Dropbox with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-dropbox-step1-connect)
* Content Source: [migration/mm-dropbox-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-dropbox-step1-connect.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jmcarthurcorr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @jmcarthurcorr
