### ISSUE TITLE
outdated info

### ISSUE THREAD

**Issue by timmayo** [MicrosoftDocs/OfficeDocs-SharePoint#2838]
Page content should be updated to reflect this new feature:
https://docs.microsoft.com/en-us/sharepoint/tenant-rename

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback! @timmayo

**Comment by get-itips** [comment]
@scanum please close. thanks
