### ISSUE TITLE
Two issues regarding sharepoint migration tool documentation

### ISSUE THREAD

**Issue by bertinmicrosky** [MicrosoftDocs/OfficeDocs-SharePoint#2851]
[Enter feedback here]

Under both sharepoint and Teams it says select onedrive
which it should say teams and sharepoint for those

also i would reccomend adding that migrating to teams requires license to the admin user who is migrating the content

Teams
Highlight the row. Under Destination, select Edit.
Select OneDrive as a destination.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b683af2f-25e8-d1ef-3161-3736d481fef0
* Version Independent ID: 8c7300b4-9115-69f5-1c59-d1f85799923f
* Content: [Review the destination paths for your Dropbox migration with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-dropbox-step4-review-destinations#feedback)
* Content Source: [migration/mm-dropbox-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-dropbox-step4-review-destinations.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by bertinmicrosky** [comment]
![image](https://user-images.githubusercontent.com/69045522/125620552-fa30a038-e6e7-4e16-8ed7-0103efc492ef.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JoanneHendrickson** [comment]
@bertinmicrosky   I will update the documentation. Thanks!
