### ISSUE TITLE
Please add error code 0x0111000A to the table of SPMT error codes

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SharePoint#2852]
Please add error code 0x0111000A to the table of SPMT error codes as it is not clear that the SPMT cannot process files greater than 100Gb.

Result category	
SCAN FAILURE

Message
Scan File Failure:File size exceeds limit

Error Code
0x0111000A

Recommended action
SPMT is unable to upload files greater than 100Gb (see[ release notes](url)) . The only option is to use OneDrive for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues?source=docs)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@buildbod Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @buildbod how are you?
I tested and could verify, adding the information thru a pr.
Thanks for your feedback

**Comment by buildbod** [comment]
Great thanks for confirming and making the change

Simon
________________________________
