### ISSUE TITLE
Migration of pages and lists

### ISSUE THREAD

**Issue by Jakub-Urban** [MicrosoftDocs/OfficeDocs-SharePoint#2858]
Hello, please clearly state that migration of SharePoint lists and pages is not supported. Customers often would like to migrate within the same tenant not only documents. 
The best option is to add this to a migration tool :)

Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb5783d-8e13-a082-66dc-86a3e87e2252
* Version Independent ID: 10739dac-3f2e-5403-6f0e-3d3cb4868e13
* Content: [Mover Microsoft 365 Migration FAQ - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-microsoft-365-faq)
* Content Source: [migration/mover-microsoft-365-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-microsoft-365-faq.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Jakub-Urban Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for the feedback @Jakub-Urban
