### ISSUE TITLE
Copy Library ID missing from Sync option

### ISSUE THREAD

**Issue by jamesonp** [MicrosoftDocs/OfficeDocs-SharePoint#2859]
I searched for this documentation issue and found #2771.  This was just closed out by the moderator without any testing on their end.

"Copy Library ID" is missing from the sync prompt which makes getting a library ID almost impossible without doing a lot of work to get it.

Please do not close this and tell me to contact Microsoft 365 Support.  This is not an issue with my tenant.  I'm signed in with Global Admin/SharePoint Admin privs.  I've tested it on multiple tenants with multiple browsers (Chrome, Edge, Firefox) and it's not there.  The feature is just missing now and needs different documentation on how to obtain it.

![Missing](https://i.imgur.com/JUvHI1T.png)

Please test this for yourself before just closing it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutoMountTeamSites)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by HansBrender** [comment]
I can confirm  this behavior, But as an Tenant Admin its easy. You have to  come from the site. Then You are able to do the same action. It is a little more cumbersome

**Comment by scanum** [comment]
@jamesonp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jamesonp how are you? Hope you are doing good 👍 
I tested this **several times** and every time, the link to Copy library ID was rendered after clicking the _Sync_ button on a library.
I would be glad to improve the article if we get the exact steps taken to reproduce, maybe @HansBrender that confirmed also can share the steps to reproduce.
Thank you!

**Comment by jamesonp** [comment]
> Hello @jamesonp how are you? Hope you are doing good 👍
> I tested this **several times** and every time, the link to Copy library ID was rendered after clicking the _Sync_ button on a library.
> I would be glad to improve the article if we get the exact steps taken to reproduce, maybe @HansBrender that confirmed also can share the steps to reproduce.
> Thank you!

So I retested this and I figured out what is going on.  If you click the sync button of a library from the default home page of a SharePoint site where the "Documents" is added as a content piece, the sync button doesn't show.  If you go directly to that library, the sync ID link will show.

I'll admit that was my mistake but it's strange to me that the sync buttons in any place, even when the library is added as a content piece, doesn't show the same thing.
