### ISSUE TITLE
Nice Article

### ISSUE THREAD

**Issue by Krishnangshu17** [MicrosoftDocs/OfficeDocs-SharePoint#286]
Nice Article. You can check this article which is very short but nice -
https://indianjackofalltrade.com/what-is-new-in-sharepoint-2019/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0c473c-9953-3f98-5ba5-7fda35879614
* Version Independent ID: 79194e89-ce43-eefc-6439-cf2bd5bdac57
* Content: [New and improved features in SharePoint Server 2019 Public Preview](https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@Krishnangshu17 Thank you for the link and feedback
