### ISSUE TITLE
App Enforced restrictions breaks file preview and open in MAM-WE scenario

### ISSUE THREAD

**Issue by appelboom** [MicrosoftDocs/OfficeDocs-SharePoint#2861]
Hi Team,

As of the last week the use of app enforced restrictions on in a MAM-WE scenario breaks document preview and results in permission denied errors. Please reference Case #:26619103 for more information.

Eric 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03f90ae-ce47-fddb-bbd6-9c6310a6da44
* Version Independent ID: b06a11ec-975e-ae62-b0ad-c89e9bb50392
* Content: [Use app-enforced restrictions - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/app-enforced-restrictions)
* Content Source: [SharePoint/SharePointOnline/app-enforced-restrictions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/app-enforced-restrictions.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@appelboom Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @appelboom Eric, how are you? Hope you are doing good.
Here, we are limited to documentation changes and improvements, is there any special issue you see with this article that needs to be corrected?
(We do not have access to the case you reference for more information)
Thank you

**Comment by appelboom** [comment]
Hi Andres

We had a incident this week when a CA policy with app enforced restrictions is scopped to iOS / Android with a intune app protection policy results in users being unable to preview documents in MAM-WE policy protected app like Teams, OneDrive or open in Word, Excel, PowerPoint. It results in a permissions issue. Premier support responded saying this scenario is not supported with SahrePoint so just sharing here. Please close issue as you see fit as this is something you team can take up internally.

**Comment by get-itips** [comment]
@scanum please close.
