### ISSUE TITLE
Wrong example to update multiple sites at once

### ISSUE THREAD

**Issue by AlyaKoni** [MicrosoftDocs/OfficeDocs-SharePoint#2862]
In the section "Block or limit access to a specific SharePoint site or OneDrive" you show an example (the 3th once) to update multiple sites at once. The shown example is out of my opinion wrong. 

Your actual example:
,(Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.sharepoint.com/personal/'") | Set-SPOTenant -ConditionalAccessPolicy AllowLimitedAccess

Should be:
(Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.sharepoint.com/personal/'") | Set-SPOSite -ConditionalAccessPolicy AllowLimitedAccess

So the comma at the beginning should not be there. Don't know what the comma at the beginning should do.
Then you set for each found site, the rule on tenant level. I think you like to set the value for each found site itself!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#block-or-limit-access-to-a-specific-sharepoint-site-or-onedrive)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@AlyaKoni Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @AlyaKoni Konrad, how are you?

About the comma, the article states:

> This example gets the OneDrive for every user and passes it as an array to Set-SPOTenant to limit access. **The initial comma and the parentheses are required for running this cmdlet as a batch request**, which is fastest.

About the Set-SPOTenant, have a look at [this](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/968#issuecomment-495812186), as the change was rejected by product team, anyway I'll try to revisit this 👍

**Comment by get-itips** [comment]
Hello @AlyaKoni Konrad, how are you?
`Set-SPOSite` does **not** take pipelined input.
I could confirm with the team that the cmdlet is correct.
Thank you
cc @kaarins

**Comment by AlyaKoni** [comment]
As of https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps the cmdlet Set-SPOSite has a parameter [-Identity] <SpoSitePipeBind> which takes pipelined input.

It's Set-SpoTenant which does not take any pipelined input. There is no parameter documented which can take pipelined input. So what's the sense behind the example, piping several sites to a cmdlet which does not take pipelined input?

Your example is doing following thing: get all existing OneDrive site collections and set on tenant level for each found site the property ConditionalAccessPolicy. So as an example, if you have 200 OneDrive site collections, you set 200 times the property ConditionalAccessPolicy on tenant level. Why you should set 200 times the same property? What's the reason behind? 

After this command all 200 OneDrive site collections still don't have set the property ConditionalAccessPolicy on site level. Which is not, what the example text states: "update multiple sites at once". No site at all will be updated. Only the tenant about 200 times!

This example is definitely wrong!

**Comment by get-itips** [comment]
@AlyaKoni Konrad, how are you? hope you are doing good! 
I also thought at first that Get-SpoSite | Set-SPOTenant couldn't be right however I could get information from the team and they informed me that was ok.
I also tried it and the policy at Tenant level was never affected (when running just like that, with the pipe)

![image](https://user-images.githubusercontent.com/36666927/127148914-88225608-01d3-4c28-a0ba-b846aa475ca6.png)

Please kindly share with me your test results and I would be glad to review them.

**Comment by AlyaKoni** [comment]
Did some testing. Set-SPOSite looks like completely broken. Using the undocumented feature referenced in the completely misleading and non understandable example from the side, everything works! So you are right. The example works correctly.
