### ISSUE TITLE
improve search results in the classic search experience only? 

### ISSUE THREAD

**Issue by AndreSchiemann** [MicrosoftDocs/OfficeDocs-SharePoint#2867]
[Enter feedback here]
There is a statement "improve search results in the classic search experience by creating and managing query rules." Does it mean that a query rule does not affect the search behavior in the Microsoft Search box?

Thanks,
André
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f082d30-62d1-e099-8307-5ab5c15d410f
* Version Independent ID: 24906b5f-8745-96f9-0f79-3dc67f1e6720
* Content: [Manage query rules - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-query-rules#overview-of-conditions-that-make-a-query-rule-fire)
* Content Source: [SharePoint/SharePointOnline/manage-query-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-query-rules.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @AndreSchiemann André, how are you? Hope you are doing good.

Further in the article, it explains:

> SharePoint has both a classic and a modern search experience. Only query rules that return promoted results and that are defined for the default result source can affect the modern search experience. Query rules which do query re-writes are not supported for modern experiences. Users might see such promoted results on the All tab on the search results page when they search across all of SharePoint. Learn more about the differences between the classic and modern search experiences in SharePoint. 
https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search

Hope this information helps you!

**Comment by get-itips** [comment]
@scanum please close.
