### ISSUE TITLE
Is the table "Default unused managed properties" correct?

### ISSUE THREAD

**Issue by miguelisidoro** [MicrosoftDocs/OfficeDocs-SharePoint#287]
I believe there are already 200 refinablestring managed properties (I checked my tenant and have from 0 up to 199). Can you update the doc? Didn't check the other types...

Check this page that has already 200 as the number of RefinableString managed properties: https://techcommunity.microsoft.com/t5/SharePoint/How-many-refinable-managed-properties-do-we-get-in-Sharepoint/td-p/93761

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c8364b1-ba49-1fe6-3ffe-abcc58a30aa2
* Version Independent ID: 4438f918-c251-5b05-6b72-11df8845b17d
* Content: [Manage the search schema in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/manage-the-search-schema)
* Content Source: [SharePoint/SharePointServer/search/manage-the-search-schema.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/manage-the-search-schema.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
In SharePoint 2019 there are 200 RefinableString. In 2016 there are 100. @Techwriter40 how should a table like this be handled for difference between versions?

**Comment by Techwriter40** [comment]
@tklarsen is it possible for SPO ???

**Comment by tklarsen** [comment]
@tseward, my immediate thought is to have separate columns for the counts. But that depends on whether there's also a different count for SP 2013.
I've noted that it's also appreciated for SPO and put it on my backlog. Unfortunately I don't have bandwidth to start working on it quite yet.

**Comment by tseward** [comment]
@tklarsen Since there is also a property name, I think what I'll do is create separate tables for each applicable version of SharePoint 2013+.

**Comment by scanum** [comment]
@miguelisidoro Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
