### ISSUE TITLE
Storage Requests or Limits Alerts are not going to SharePoint Admins as stated in document.

### ISSUE THREAD

**Issue by enigmanet** [MicrosoftDocs/OfficeDocs-SharePoint#2870]
I have tested this on multiple tenants and the following area needs to be revised till feature is back to working.

Go to the Site Settings page.
Under Site Collection Administration, select Storage Metrics.
This sends a storage request email to the **global** and **~~SharePoint admins~~** in the organization.
Select Request more quota in the upper right.

^^ SharePoint admin do not get the email alerts and only Global Admins.  Certain tenants cannot give global admin to all SP Admins. 

ICM: 244528198

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits#manage-individual-site-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
