### ISSUE TITLE
Use of $global is unneccesary

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/OfficeDocs-SharePoint#2875]
The PowerShell examples use `$Global:` which is unnecessary and should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Migrate to SharePoint and OneDrive using PowerShell cmdlets - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks @kilasuit for the feedback.
