### ISSUE TITLE
ListColor and ListIcon parameters

### ISSUE THREAD

**Issue by nyoung30** [MicrosoftDocs/OfficeDocs-SharePoint#2876]
It would be nice if a  listing of options were available for the ListColor and ListIcon parameters in the Add-SPOListDesign example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6665386e-1ad4-e9d3-565b-4b3cb3c3ea99
* Version Independent ID: 870237f7-66ec-270e-1372-c993e8dedbe9
* Content: [Custom list templates - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/lists-custom-template?WT.mc_id=M365-MVP-5003629)
* Content Source: [SharePoint/SharePointOnline/lists-custom-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/lists-custom-template.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thanks for the suggestion @nyoung30 !
