### ISSUE TITLE
Missing new parameter

### ISSUE THREAD

**Issue by kdavison-uk** [MicrosoftDocs/OfficeDocs-SharePoint#2877]
For SPMT release 3.4.120.7 there is mention of a new **Start-SPMTMigration** parameter **-ReplacementOfInvalidChar**, however this parameter is not in the cmdlet documentation and does not exist in the cmdlet (installed latest version). What happened?

Thanks
Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c911d1d-3570-6e0a-cfa7-77b7516a1f55
* Version Independent ID: 261252f1-7191-5be9-a735-cdb307b72a7c
* Content: [SharePoint Migration Tool (SPMT) Release notes - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool)
* Content Source: [migration/new-and-improved-features-in-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/new-and-improved-features-in-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@kdavison-uk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kdavison-uk 
Installed the last one and the parameter is not there anymore, seem it was removed later.
