### ISSUE TITLE
Issue with AllowTenantList

### ISSUE THREAD

**Issue by BigIve** [MicrosoftDocs/OfficeDocs-SharePoint#2878]
Hi,

I'd like to ask about the 'AllowTenantList' control that is detailed on this page.

I'm currently deploying this to several devices as part of a larger OneDrive policy (PLIST converted to a mobileconfig file as the Intune Plist deployment option doesn't allow for the use of <dict> commands).

The AllowTenantList control appears to be the only one not functioning.  I've locked the config down to only the customers tenant ID, however I'm still able to add accounts for any (corporate) account that I have access to and they have ZERO issues synchronizing.  Is there any other controls that need to be used in conjunction with AllowTenantList?  I'm not using the Block Tenant control.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos?source=docs#allowtenantlist)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
