### ISSUE TITLE
Group owner permissions are needed to rename a site.

### ISSUE THREAD

**Issue by JeremyEsposito** [MicrosoftDocs/OfficeDocs-SharePoint#2882]
This document states the following for required permissions to rename a Modern Team site (associated with an O365 group)
As a global or SharePoint admin in your organization, you can change the URL for the following types of SharePoint sites.

This is not entirely accurate.
When renaming a modern team site associated with an O365 group, the user making the site name change will need to have the following permissions:
SharePoint Online administrator
O365 group owner 

The rename will fail if the user does not have O365 group owner permissions.

To help our customers and support engineers, please update this article to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JeremyEsposito Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JeremyEsposito how are you? Hope you are doing good. 👍 
I tested the scenario that you described on my lab tenant and I could successfully rename a Modern Team site (associated with an O365 group) site being only a Global Administrator (not a O365 group owner), tested several times to be sure.
Please correct me if I wrongly understood the case.
Thank you

**Comment by JeremyEsposito** [comment]
Thanks for the update.
Yes… you don’t need to be an O365 group owner rename a site IF you are a global admin.

But… If you are NOT a global admin, but you are a SharePoint admin, you will need to be an O365 group owner rename a site.

Many SPO admins are not global admins… and this was the scenario for the support case I had.
The SPO admin was able to rename the site after adding the SPO admin user to the O365 group owner.
Prior to adding themselves to O365 group owner group… they were getting an error when trying to rename a (O365 team) site.


Let me know if you have any questions.
Thank you,
Jeremy Esposito
Sr. Support Escalation Engineer
O365 SharePoint - OneDrive for Business
Customer Service & Support
http://support.microsoft.com/<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsupport.microsoft.com%2F&data=01%7C01%7Cjeesposi%40microsoft.com%7Cc562eb1ac3894f1008ef08d6d7cafed9%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=yoSGBDaTsB%2B7xt723NGDgWpoal0YcKiPaFFT20NjATE%3D&reserved=0>
Phone:   +1 781 398 4724
Hours:    9:00AM – 5:30PM EST
***@***.******@***.***>
5 Wayside, Burlington, MA 01803
Manager: Floyd Mathias
***@***.******@***.***>

You can submit your O365 service and support feedback from the admin portal<http://aka.ms/o365satisfaction> by viewing support service requests.

**Comment by get-itips** [comment]
@JeremyEsposito Ok Jeremy, thanks for clarifying, will test that exact scenario and get back.

**Comment by get-itips** [comment]
> But… If you are NOT a global admin, but you are a SharePoint admin, you will need to be an O365 group owner rename a site.

@JeremyEsposito I re-tested this using a SharePoint Administrator (no Global Admin role) and verified that it was not owner of the 365 group, and I could successfully change the site name and URL. Tested with two different SharePoint admins.

Are you doing this thru the SharePoint admin portal or the PowerShell module?

Thanks

**Comment by JeremyEsposito** [comment]
I was on a remote session with the customer and watched the rename issue happen.
Once the customer added themselves to the O365 group as owner... they were able to rename the site.
The customer is a site collection admin, and SPO admin.
Hope this helps.
Jeremy

**Comment by JeremyEsposito** [comment]
Sorry forgot to answer your initial question.
Customer is using the SPO admin portal to rename the site.

From: Jeremy Esposito
Sent: Wednesday, July 28, 2021 2:18 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>; MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SharePoint] Group owner permissions are needed to rename a site. (#2882)

I was on a remote session with the customer and watched the rename issue happen.
Once the customer added themselves to the O365 group as owner... they were able to rename the site.
The customer is a site collection admin, and SPO admin.
Hope this helps.
Jeremy

**Comment by get-itips** [comment]
Hello @JeremyEsposito Jeremy,
Also used the SPO admin, tested in multiple tenants with multiple users. Maybe this was fixed recently.
Thank you

**Comment by JeremyEsposito** [comment]
Could be... maybe this update is not needed. 
At least we/support know of a workaround when the issue does happen.

**Comment by get-itips** [comment]
> Could be... maybe this update is not needed.
> At least we/support know of a workaround when the issue does happen.

Exactly! Thank you

**Comment by get-itips** [comment]
@scanum please close.
