### ISSUE TITLE
UnsupportedDataConnectionTypes Data connections that are not supported on the new platform.

### ISSUE THREAD

**Issue by spshane** [MicrosoftDocs/OfficeDocs-SharePoint#2883]
Trying to find out more detail on what this means
UnsupportedDataConnectionTypes | Data connections that are not supported on the new platform.
Does this mean that the InfoPath form could contain a SQL connection and that the data connection isnt supported on the new platform without additional infrastructure and licensing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [SharePoint Migration Assessment Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
researching.

**Comment by spshane** [comment]
Hello.  Just following up.  Any more details?

Shane Ramos | Grp Mgr, Tech Architect
Enterprise Technology Architecture
Avanade Inc.
1191 Second Avenue Suite 100, Seattle, WA 98101
Cell: +1-206-239-6459;ext=21238
www.avanade.com<http://www.avanade.com/>
***@***.***

**Comment by JoanneHendrickson** [comment]
Hi @spshane    I believe the error means that the InfoPath forms contain a data connection that is not supported on SPO; for example Soap Connection, REST Connection, RPC Connection and Ado Connection. The connection URL is usually reported. You should be able to check the URL to confirm which connection it is.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
