### ISSUE TITLE
[LOC]Over Translation (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SharePoint#2887]
ja-jp:"https://docs.microsoft.com/ja-jp/sharepoint/administration/configure-usage-and-health-data-collection"
configure-usage-and-health-data-collection_j
![configure-usage-and-health-data-collection_j](https://user-images.githubusercontent.com/40815708/127628431-95d32b70-62f3-4bf0-ae57-15b54f714885.png)

en-us:"https://docs.microsoft.com/en-us/sharepoint/administration/configure-usage-and-health-data-collection"
configure-usage-and-health-data-collection_e
![configure-usage-and-health-data-collection_e](https://user-images.githubusercontent.com/40815708/127628452-3dcb8c32-69b8-4361-9182-e16dbb09d96e.png)

related: https://github.com/MicrosoftDocs/feedback/issues/3659#issuecomment-889517959
#PingMSFTDocs

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@Officeglobal Could you kindly help with this issue?
