### ISSUE TITLE
configure-site-mailboxes-in-sharepoint.md

### ISSUE THREAD

**Issue by Xeroxxx** [MicrosoftDocs/OfficeDocs-SharePoint#2889]
Documentation is depreacted. EWSManagedAPI.msi is not offered as download anymore. (https://www.microsoft.com/download/details.aspx?id=42951) 404

New EWSManagedAPI  NuGet Package does not register in GAC. Currently no appropriate documentation to install SiteMailboxes for SharePoint 2013 and up.

https://github.com/OfficeDev/ews-managed-api

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Xeroxxx** [comment]
Basically I don't have anyone to contact as I'm an action pack user/developer.

I did a write up how I solved this for me.

If you can tell me someone to get in touch with feel free.

https://www.techspark.de/install-ewsmanagedapi-nuget-github-for-sharepoint-2013-2016-2019/
