### ISSUE TITLE
Hub site theme - unexpected behavior on subsites

### ISSUE THREAD

**Issue by Gregghis** [MicrosoftDocs/OfficeDocs-SharePoint#2890]
Hi,

I bump into an unexpected behaviour applying a theme on a new hub.
The hub navigation bar has a different background color between root site and subsites. This behavior works in the same way in standard and in custom themes.
Where the theme was applied already (a couple of months ago) the background color works properly on subsites.

Hubsite - header
![HubNav_01](https://user-images.githubusercontent.com/50576392/127844629-a84ed867-a3bd-4368-9acc-999175899be5.jpg)

Subsite - header
![HubNav_02](https://user-images.githubusercontent.com/50576392/127844634-813e23da-31e8-4ae5-9b0f-3d3a6c53641f.jpg)

Any ideas is appreciated,
Best regards,
Greg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe029ff2-3230-3320-aef5-9f16ab9464cc
* Version Independent ID: d791f3f6-257f-9a9b-461f-a12693d4bfde
* Content: [Branding your SharePoint site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/branding-sharepoint-online-sites-modern-experience)
* Content Source: [SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
