### ISSUE TITLE
Please add content that the tool can not map local users/groups

### ISSUE THREAD

**Issue by jianhuashi2038** [MicrosoftDocs/OfficeDocs-SharePoint#2894]
Please add content that the tool can not map local users/groups.

If it is of local users/groups, they will simply be ignored

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user-mapping file for data content migration - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jianhuashi2038 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jianhuashi2038, thank you for your feedback.

Did you mean SharePoint groups? Only AD groups are supported, and there is a note about it:

> [!Important]
> SPMT only migrates default SharePoint groups.
>
> You can't map an AD group to a SharePoint group in the target site. You can't use SPMT to map a SharePoint Server group to a SharePoint group.

I also understand that local accounts or groups for use in SharePoint are not recommended.

**Comment by jianhuashi2038** [comment]
Thanks the follow,  Dario.

The issue occurs with SharePoint On-premise server local user.

Customer set mapping rule for local user to Online user, but found the access right on the file share is not valid on the file at SharePoint online.


Windows の メ`ル<https://go.microsoft.com/fwlink/?LinkId=550986> から送信

差出人: Dario ***@***.***>
送信日r: 2021年8月12日 18:12
宛先: ***@***.***>
CC: Jianhua ***@***.***>; ***@***.***>
件名: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Please add content that the tool can not map local users/groups (#2894)


Hi @jianhuashi2038<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjianhuashi2038&data=04%7C01%7Cjianshi%40microsoft.com%7C0bc8bc0285db43b7fcfd08d95d7158c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637643563710416114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6uTvpG8c4IOkrD4x%2FkC5pJVLdRTigqyz4aqGKQNYte8%3D&reserved=0>, thank you for your feedback.

Did you mean SharePoint groups? Only AD groups are supported, and there is a note about it:

[!Important]
SPMT only migrates default SharePoint groups.

You can't map an AD group to a SharePoint group in the target site. You can't use SPMT to map a SharePoint Server group to a SharePoint group.

I also understand that local accounts or groups for use in SharePoint are not recommended.

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fissues%2F2894%23issuecomment-897476880&data=04%7C01%7Cjianshi%40microsoft.com%7C0bc8bc0285db43b7fcfd08d95d7158c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637643563710416114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TGmnStiDSSFL3oduwEJ2L4Jqe8glZez2MlPHNKPGJkI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPTRZTCPMBVRXWKXPK75WY3T4OGAZANCNFSM5BS6DSNA&data=04%7C01%7Cjianshi%40microsoft.com%7C0bc8bc0285db43b7fcfd08d95d7158c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637643563710426059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x1Kh3472yjQA4sXaHjEKagKVL0EjG7aJABtK9BO9F74%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjianshi%40microsoft.com%7C0bc8bc0285db43b7fcfd08d95d7158c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637643563710426059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uAmRHaNpJzll7KC%2B0FtJdxFL1N5Cn%2BtcU4DGgvQ%2FOyA%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjianshi%40microsoft.com%7C0bc8bc0285db43b7fcfd08d95d7158c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637643563710436026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7UweYEf7ZozoGVuNYKmAu165IbZICxOdk%2BlajsjMti8%3D&reserved=0>.

**Comment by get-itips** [comment]
Hello @jianhuashi2038 
Can you clarify, a **local AD domain user** was specified in the column A and an Online user was specified in Column B?
Please provide all the details you can so we can reproduce to see if we have to impact the document. 
Thank you
