### ISSUE TITLE
default behavior

### ISSUE THREAD

**Issue by T0437247436** [MicrosoftDocs/OfficeDocs-SharePoint#2897]
It would be good to know the default behavior.    It appears to be OneDrive as the destination path was the username but it was not clear in the interface itself.  So it would be good to list the default selection (Od first, then SP then Teams?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402bdf2a-1b81-fca5-42f3-ba9a140a6fb6
* Version Independent ID: ed361570-2aa3-44a8-8b7a-74de71a6528a
* Content: [Review the destination paths for your Google migration with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-google-step4-review-destinations)
* Content Source: [migration/mm-google-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-google-step4-review-destinations.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
