### ISSUE TITLE
"Step 4: Review destinations"   link is incorrect. 

### ISSUE THREAD

**Issue by T0437247436** [MicrosoftDocs/OfficeDocs-SharePoint#2898]
"Step 4: Review destinations"   link is incorrect.  It links to Box instructions Step 4 (https://docs.microsoft.com/en-us/sharepointmigration/mm-box-step4-review-destinations)  instead of Google Workspace (https://docs.microsoft.com/en-us/sharepointmigration/mm-google-step4-review-destinations).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b80dd83-55ac-6601-cb86-a1181c6a04cf
* Version Independent ID: 084de71e-b5c7-72c0-c299-31d3dc05844c
* Content: [Step 3: Copy to migrations tab for Google migration - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-google-step3-copy-to-migrations)
* Content Source: [migration/mm-google-step3-copy-to-migrations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-google-step3-copy-to-migrations.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Thanks @T0437247436  -- the link has now been fixed.
