### ISSUE TITLE
Links for File share migration poster download point to the same location as SharePoint Server migration poster links

### ISSUE THREAD

**Issue by ChrisStoneham** [MicrosoftDocs/OfficeDocs-SharePoint#2899]
Links for File share migration poster download point to the same location as SharePoint Server migration poster links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606fc564-19ed-f136-47f8-f965c8cf3b0a
* Version Independent ID: def16eb5-837e-81b0-5386-8760cf36809b
* Content: [Content Migration solutions posters - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/migration-solution-posters#feedback)
* Content Source: [migration/migration-solution-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migration-solution-posters.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by modery** [comment]
Page 1 of the linked PDF contains the poster for File share migration, page contains the poster for the SharePoint Server migration

**Comment by get-itips** [comment]
@ChrisStoneham Chris, exactly as @modery Rene explains.
@scanum please close. thanks

**Comment by ChrisStoneham** [comment]
I still think the layout of the page is confusing, but, you are right that the content is there.
