### ISSUE TITLE
Repetitive & Broken links

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [MicrosoftDocs/OfficeDocs-SharePoint#29]
Documentation Page:
https://docs.microsoft.com/en-us/sharepoint/hybrid/learn-about-cloud-hybrid-search-for-sharepoint

The links under "Learn More" sections are repetitive as well as broken.
All the links are referring to some section of the (non-existing)page with following URL.
https://technet.microsoft.com/library/af830951-8ddf-48b2-8340-179c1cc4d291%28Office.14%29.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a7967e8-384b-4edd-6f0a-5c4ecbe9c9e4
* Version Independent ID: 14267c4c-2f0f-0aed-71b3-1d5f1fb02304
* Content: [Learn about cloud hybrid search for SharePoint](https://docs.microsoft.com/en-us/sharepoint/hybrid/learn-about-cloud-hybrid-search-for-sharepoint)
* Content Source: [SharePoint/SharePointServer/hybrid/learn-about-cloud-hybrid-search-for-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/learn-about-cloud-hybrid-search-for-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
Thank you for reporting this! The links are now corrected.
