### ISSUE TITLE
Unsegmented Users

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#2900]
This article should include examples of when users are unsegmented. With how this is implemented on OneDrive, there are tradeoffs between having unsegmented users and having everyone segmented, even when there are no blocks. In either case, IBs overreach and block unintended actions. For more details, please see the design idea I submitted under DCR 26924449.

In either case, this doc should show the impacts of unsegmented in the table and visuals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef03ccd-fd27-4724-75c1-eec90be8ad8b
* Version Independent ID: a9e393d2-9bcc-3814-2654-bd40f23d5306
* Content: [Use information barriers with OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/information-barriers)
* Content Source: [OneDrive/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/information-barriers.md)
* Service: **one-drive**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@danmyhre - thanks so much for the feedback, will review with product team and review for possible topic updates WRT to your DCR.
