### ISSUE TITLE
Google Drive .gsheet and .gdocs after migration not converting into .xlsx .Docs 

### ISSUE THREAD

**Issue by BirenGroove** [MicrosoftDocs/OfficeDocs-SharePoint#2901]
Hi there,

I am using this Migration Manager for migrating google drive to OneDrive but seem like google file not talking docs and Excel format

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
