### ISSUE TITLE
[Wrong information]organization assets library types should be available for Word/Excel as well, not just PowerPoint

### ISSUE THREAD

**Issue by forester123** [MicrosoftDocs/OfficeDocs-SharePoint#2904]
As titled, the article indicates user can create organization assets library type for PowerPoint template only, this is not correct. It also supports Word/Excel.

This could cause misunderstanding and mislead customers, please rivise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jackpoz** [comment]
This confused me today too as the page didn't mention Word and yet it works with Word.

**Comment by get-itips** [comment]
Thanks for your feedback, working on this.

**Comment by jackpoz** [comment]
was this solved ? PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/2912 is still in Draft and https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md doesn't mention anything about Word still
