### ISSUE TITLE
Several small typos in one docs

### ISSUE THREAD

**Issue by ZCplayground** [MicrosoftDocs/OfficeDocs-SharePoint#2906]
Extra "the" in this docs: https://docs.microsoft.com/en-us/SharePoint/administration/configure-usage-and-health-data-collection?redirectedfrom=MSDN#configure-usage-and-health-data-collection-by-using-central-administration

![image](https://user-images.githubusercontent.com/24431029/129530879-9617b12c-5942-4470-8f55-1cfcb920ee42.png)

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-usage-and-health-data-collection.md

**Comment by ZCplayground** [comment]
![image](https://user-images.githubusercontent.com/24431029/129531791-f887e618-f4ad-48d9-973c-7c1994c0f59a.png)

Missing a left bracket leads to wrong markdown syntax.

**Comment by ZCplayground** [comment]
Strange render effect that only the single word "where" is listed in a code block:
![image](https://user-images.githubusercontent.com/24431029/129533419-3820a252-97a8-45c0-b0e4-9ade178ea077.png)

Consider to change the correspond markdown here:

![image](https://user-images.githubusercontent.com/24431029/129533498-55b8ff0a-3a6c-4872-ac63-35347dd34622.png)

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
thanks for your feedback! @ZCplayground
