### ISSUE TITLE
AllowTenantList policy has incorrect example of the plist file

### ISSUE THREAD

**Issue by martin-suma** [MicrosoftDocs/OfficeDocs-SharePoint#2909]
[Enter feedback here]
Hello team,

the AllowTenantList policy has incorrect example of the plist file. The result is that when set this way the policy is not working. The correct structure is without the array. Solution provided by the OneDrive product team - Carter Green.

Correct example of AllowTenantList policy:

<key>AllowTenantList</key>
    <dict>
        <key>TenantId1</key>
        <true/>
        <key>TenantId2</key>
        <true/>
    </dict>

Thanks and have a good day, Martin (McKinsey & Company)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by martin-suma** [comment]
Attaching a screenshot because the tags were not saved.

![image](https://user-images.githubusercontent.com/84710625/129729880-cab698e4-d2b5-4c7c-87c0-3d06fc5c7853.png)

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @martin-suma
