### ISSUE TITLE
Access denied while remove the redirect site.

### ISSUE THREAD

**Issue by ndocosta** [MicrosoftDocs/OfficeDocs-SharePoint#2922]
[Enter feedback here]

trying to remove the redirect site results in access denied error, even if connected at tenant level.

#First need to unlock site
Set-SPOSite "OLDSITEURL" -LockState Unlock

#Then add current user as site collection admin
Set-SPOUser -Site "OLDSITEURL" -LoginName "UPNOfUser" -IsSiteCollectionAdmin $true

#And only after that, we can remove the redirect site.
Remove-SPOSite "OLDSITEURL"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfb6e9b-57d4-749f-a1d0-5f5c24e141ce
* Version Independent ID: e67e1021-7801-477b-1642-43c283742e59
* Content: [Manage site redirects - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects)
* Content Source: [SharePoint/SharePointOnline/manage-site-redirects.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-redirects.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
