### ISSUE TITLE
Issue with aggregatereports.ps1

### ISSUE THREAD

**Issue by mortkar** [MicrosoftDocs/OfficeDocs-SharePoint#2923]
[Enter feedback here]
The aggregatereports.ps1 doesn't work now. I just updated to the new version today, and any criteria I put into the form, it give me this error
I tried on multiple machines.  I chose different values each test. One time I did Task Name Contains, making sure the checkbox was clicked. Then I did Tasks created before. Same results. 

Successfully getting the tenant admin url
Your selection:
status: All
EndDate:  8/18/2021
Cannot convert null to type "System.DateTime".

The PS looks like it completes - but the report folder is empty and the above message shows in the LOG /aggregation.log file
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca02c1ed-5060-da34-8177-ecda29144eef
* Version Independent ID: 45eab3ad-7f4f-e8b7-9a93-17ade9365ae4
* Content: [Migration Manager Reports - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-reports#feedback)
* Content Source: [migration/mm-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cdimare** [comment]
Does this work for scan results? We are looking for a way to pull all scan results with errors from the migration manager console.
@scanum
