### ISSUE TITLE
Link to Submit and view feedback for 'This product' useless

### ISSUE THREAD

**Issue by muwim** [MicrosoftDocs/OfficeDocs-SharePoint#2925]
The linked service https://sharepoint.uservoice.com/ is disabled, so it should be removed or pointed to a functional service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @muwim how are you?
Hope you are doing good.
I am looking into this.
Thanks

**Comment by get-itips** [comment]
Hello @muwim 
The link will be changed soon to https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472
Thank you
