### ISSUE TITLE
Sync client requirements?

### ISSUE THREAD

**Issue by NorbertKlein-Ildefeld** [MicrosoftDocs/OfficeDocs-SharePoint#2927]
v21.078 is mentioned as pre-req. We are on that version now but in Deferred Ring. We see it working though with v21.150 also configured for deferred ring. This does not make sense to me. Will the Deferred Ring limitation be lifted with v21.150 rollout in October?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-health)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @NorbertKlein-Ildefeld I could confirm with the team that the deferred ring is not yet supported for the mentioned functionality.
@scanum Please close.
