### ISSUE TITLE
Explorer Path Issue

### ISSUE THREAD

**Issue by ApolloDNA** [MicrosoftDocs/OfficeDocs-SharePoint#2932]
Kind of an odd issue from the SharePoint migrations I have performed and this issue being the first one and wanted to see if I could get some help. I am working with a client where the files are migrating to a Teams site but once the users sync the general's folder in the document library some of the folders deep down the tree are breaking that 256 character limit through the migrations I have complete normally I would see that be a scan issue I can resolve before the migration takes place. Any help would be great,

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
