### ISSUE TITLE
Sharepoint migration tool vulnerable 

### ISSUE THREAD

**Issue by my62** [MicrosoftDocs/OfficeDocs-SharePoint#2934]
The sharepoint migration tool can be installed without the agreement of the terms of service and privacy policy. If you agree on the terms the install button will be greyed out. Legal vulnerability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool?redirectSourcePath=%252farticle%252fHow-to-use-the-SharePoint-Migration-Tool-65462df1-42fe-40cf-88f7-e39f82f5130f)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
@my62   Thanks for your feedback. Can you please provide the steps you took to skip the terms of service and install regardless?  I just tested all the possible download links and the Install button stays successfully greyed out until I accept the terms of service.  Thanks!  joanne

**Comment by JoanneHendrickson** [comment]
@my62   Just following up -- can you provide the steps you took to be able to install SPMT without accepting the terms?

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by my62** [comment]
Sorry for the late reply,

It seems that it worked now.

I simply opened the below address for the problem:
https://spmt.sharepointonline.com/install/default.htm
