### ISSUE TITLE
Impact of Multi-geo

### ISSUE THREAD

**Issue by danielgatley** [MicrosoftDocs/OfficeDocs-SharePoint#2938]
How is the location of the assets library determined with the office application?  Do multi-geo environment impact this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @danielgatley 
How are you?
You can read more about how the PDL is determined in the linked article

> When a user creates a SharePoint group-connected site in a multi-geo environment, **their PDL is used to determine the geo location where the site and its associated Group mailbox is created.** (If the user's PDL value hasn't been set, or has been set to geo location that hasn't been configured as a satellite location, then the site and mailbox are created in the central location.)

and

> Select an existing site or create a new site for the organization assets. This can be any type of site, such as a communication site, a team site that's connected to a Microsoft 365 Group, or a modern team site that isn't connected to a Microsoft 365 Group.

Source https://docs.microsoft.com/en-us/sharepoint/organization-assets-library

Please let me know if I understood you well,

**Comment by danielgatley** [comment]
I understand use of PDL in the creation of sites but I'm interested to know if the PDL of a user has any impact on the discovery of organization asset libraries, in particular for Office templates storage.  Does the PDL of the user come into play when identifying the location of the library?  We have users who have a PDL outside of our home tenant (where our current asset library is stored) who do not see the template store within the Office applications, this is the only significant and common different we have identified.  Does a multi-geo setup require a assets library per tenant?  If we understood what process Office uses to identify the organisation library location this would likely go a long way to answering this question.

**Comment by get-itips** [comment]
Hello @danielgatley Daniel,
I understand better now, thanks for the explanation.
I am not 100% sure if PDL affects in that way to the Org Assets libraries, @kaarins can I kindly ask for your help here?

**Comment by get-itips** [comment]
Thanks for returning and sharing that feedback @danielgatley
