### ISSUE TITLE
Link is broken for "planning and building a home site"

### ISSUE THREAD

**Issue by Danorexic** [MicrosoftDocs/OfficeDocs-SharePoint#2939]
The link to the guide is broken on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d3ba5d-e16b-0d9b-c623-37a75802d6ea
* Version Independent ID: 24f1a751-a2de-ee1d-a58e-c4a630d543fb
* Content: [Designate a home site from the SharePoint admin center (Preview) - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/home-site-admin-center)
* Content Source: [SharePoint/SharePointOnline/home-site-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @Danorexic

**Comment by Holland-ODSP** [comment]
Thanks @Danorexic , just fixed this. New doc will be refreshed in the next few hours.

**Comment by get-itips** [comment]
@scanum please close. Thanks
