### ISSUE TITLE
How to use SharePoint mobile app as my sharepoint online web application default app

### ISSUE THREAD

**Issue by giridhardunga** [MicrosoftDocs/OfficeDocs-SharePoint#294]
We developed sharepoint online web application with sharepoint site/Homepage.aspx

We are trying to use sharepoint mobile app as our application app.

We are able to access the site through ULT open with sharepoint app. but unable to navigate to homepage while opening sharepoint app directly.

Could you please help us with suggestions.

Thanks,
Giridhar

**Comment by AndreaBarr** [comment]
@giridhardunga Thank you for this feedback. 

I am not sure how to assist in this issue but Support has more resources than I do and can handle this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
