### ISSUE TITLE
More specifics on the process around 25TB conversion

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/OfficeDocs-SharePoint#2941]
This section "For any user that reaches at least 90% capacity of their 25 TB of OneDrive storage, additional cloud storage will be provided as 25 TB SharePoint team sites to individual users."

a couple questions here:

1. Does the admin need to contact MS support to get the OneDrive converted to a Team Site? 
2. If a Retention policy is used for OneDrives But NOT for SPO Team Sites, what happens to the retention on the content that is converted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space - OneDrive](https://docs.microsoft.com/en-us/onedrive/change-user-storage?source=docs)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @sinnamingrrl how are you?
In the link that follows, [Check OneDrive site eligibility for increased storage](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/storage/check-storage-increase-eligibility) the same note appears and also asks to contact support for more information and assistance, will propose adding that to this article too.
Hope this information helps you,

**Comment by get-itips** [comment]
@scanum please kindly close.
