### ISSUE TITLE
Missing Browser/OS list

### ISSUE THREAD

**Issue by mosoccer** [MicrosoftDocs/OfficeDocs-SharePoint#2942]
In one of the beginning paragraphs it has the text:  " (unless they use one of the browser and operating system combinations listed below)"

I'm not seeing that browser/OS list anywhere in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by kaarins** [comment]
It should link to this list: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#supported-browsers. @scanum can you please assign to update?

**Comment by get-itips** [comment]
@kaarins I am assigned, I will do the update and ask for your review, thank you!!
