### ISSUE TITLE
What is the maximum number of extensions that we can block ?

### ISSUE THREAD

**Issue by GK-2021** [MicrosoftDocs/OfficeDocs-SharePoint#2943]
[Enter feedback here]
Has there any max number of extensions we can add to the following location
![image](https://user-images.githubusercontent.com/90867815/133674565-b1fe4c13-ce2b-4992-99b7-843d77b6ace6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types - OneDrive](https://docs.microsoft.com/en-us/onedrive/block-file-types#feedback)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by GK-2021** [comment]
from my testing , it seems like 510 is the limit. But would like to confirm if this is a hardlimit ?
![image](https://user-images.githubusercontent.com/90867815/133675698-dacb4f04-4a05-47ea-80e1-afa316e8d584.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
