### ISSUE TITLE
The SORTING tab" > Rank Model is disabled.  Doc outdated?

### ISSUE THREAD

**Issue by edixon-github** [MicrosoftDocs/OfficeDocs-SharePoint#2945]
Under "The SORTING tab" > Rank Model, this feature was recently disabled in the query builder dialog.  Does the documentation need to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4072d3b5-45f9-746a-2954-64006add2181
* Version Independent ID: 66f9429e-6fd5-500b-048f-add3fdb61b5f
* Content: [Manage result sources - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-result-sources#the-sorting-tab)
* Content Source: [SharePoint/SharePointOnline/manage-result-sources.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-result-sources.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by edixon-github** [comment]
Huh? I raised is because the online documentation is wrong.  

https://docs.microsoft.com/en-us/sharepoint/manage-result-sources#the-sorting-tab
