### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pratapladhani** [MicrosoftDocs/OfficeDocs-SharePoint#2946]
[Enter feedback here]
Hi the link **Learn more about Viva Connections desktop** is broken and is pointing currently to - https://docs.microsoft.com/en-us/SharePoint/SharePointOnline/viva-connections.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958b2a50-d11c-7b65-21c1-7789f5c6c071
* Version Independent ID: 0162517a-2007-2258-46d8-55518e22581f
* Content: [Overview: Viva Connections (Preview) - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections-overview)
* Content Source: [SharePoint/SharePointOnline/viva-connections-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenL
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
