### ISSUE TITLE
Add file location to troubleshooting SMTP installation article

### ISSUE THREAD

**Issue by jarossmsft** [MicrosoftDocs/OfficeDocs-SharePoint#2950]
The following page isn't clear on what location a GCCH or DoD customer needs to browse to edit their file. I am suggesting we add the location %localappdata%\Apps\SharePointMigrationTool\SPMT\microsoft.sharepoint.migration.common.dll.config to make this article clearer.

Government cloud support
If you are on a government cloud, you must first take these steps:
**Open microsoft.sharepoint.migration.common.dll.config.**
Change the value of SPOEnvironmentType to:
3 if you are DoD
2 if you are GCC high
0 if you use the Worldwide consumer cloud or GCC
Double-click "microsoft.sharepoint.migrationtool.advancedapp.exe" to start SPMT.

to

Government cloud support
If you are on a government cloud, you must first take these steps:
**Open %localappdata%\Apps\SharePointMigrationTool\SPMT\microsoft.sharepoint.migration.common.dll.config.**
Change the value of SPOEnvironmentType to:
3 if you are DoD
2 if you are GCC high
0 if you use the Worldwide consumer cloud or GCC
Double-click "microsoft.sharepoint.migrationtool.advancedapp.exe" to start SPMT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jarossmsft Jason, thanks for your feedback. Proposing to add the path to the article thru a PR.
Thanks
