### ISSUE TITLE
Where are the ADM/ADMX/ADML files - they are not in the instructions in step 2?

### ISSUE THREAD

**Issue by tommurphy288** [MicrosoftDocs/OfficeDocs-SharePoint#2951]
Trying to test this, none of the default installed OneDrive clients as of 21/09/21 have the ADM/ADMX/ADML files in the locations listed in point 2
here https://docs.microsoft.com/en-us/onedrive/use-group-policy#:~:text=Manage%20OneDrive%20using%20Group%20Policy%201%20Install%20the,the%20.adml%20and%20.admx%20files.%20More%20items...%20

_**Browse to %localappdata%\Microsoft\OneDrive\BuildNumber\adm\ (for per-machine sync app browse to C:\Program Files (x86)\Microsoft OneDrive\BuildNumber\adm), to the subfolder for your language, as necessary (where BuildNumber is the number displayed in sync app settings on the About tab).**_

These do not exist, where can these ADM/ADMX/ADML files be located, there does not seem to be a separate download package available from Microsoft. 

Any help out there?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tommurphy288** [comment]
> Thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Sorry, this is not closed and I don't need to log this as a support ticket with MS. the instructions on this page are wrong. 

For anyone that finds this, you need to remove OneDrive from your system and re-install from a downloaded copy from MS, then you get the path that has the ADM files. Perhaps this could be added to the official instructions so that others don't waste hours with this.
