### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by erictechtips** [MicrosoftDocs/OfficeDocs-SharePoint#2952]
This section has a broken link "Home sites are generally high-traffic sites that should be optimized for performance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82db6898-47a9-4518-103c-b1bd44d4888b
* Version Independent ID: dd76cad9-5bf2-704a-2447-832d5a123756
* Content: [Guide to setting up Viva Connections (Preview) - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/guide-to-setting-up-viva-connections)
* Content Source: [SharePoint/SharePointOnline/guide-to-setting-up-viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/guide-to-setting-up-viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thanks for the heads up @erictechtips , this will get corrected in the next few hours. 

PR #3910
