### ISSUE TITLE
Multiple broken links on Overview: Viva Connections (Preview) page

### ISSUE THREAD

**Issue by Danorexic** [MicrosoftDocs/OfficeDocs-SharePoint#2956]
Good evening,

While browsing this page, I encountered multiple broken links. It seems like frequently has to do with capitalization in the URL. 

**Overview: Viva Connections (Preview) section:**
Text "Learn more about Viva Connections desktop" link is broken. 

**Dashboard, Feed, and Resources section:**
Text "SharePoint Framework (SPFx)" link is broken.
Text "SPFx web parts and extensions" link is broken.

**Viva Connections Resources section:**
Text "SharePoint app bar" link is broken.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958b2a50-d11c-7b65-21c1-7789f5c6c071
* Version Independent ID: 0162517a-2007-2258-46d8-55518e22581f
* Content: [Overview: Viva Connections (Preview) - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/viva-connections-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thanks for catching this @Danorexic ! Just submitted edits.
