### ISSUE TITLE
Case-sensitive information is missing

### ISSUE THREAD

**Issue by dmahendranme** [MicrosoftDocs/OfficeDocs-SharePoint#296]
Team,
I was informed by Microsoft Support Engineer that the Implicit managed property is case-sensitive including on REST api calls. It is missing in this documentation. Please include it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a04f2619-a855-4d1b-3d32-de0f0a1bcb7e
* Version Independent ID: 0b76c5be-c85c-1e18-d53c-1585ba3e4549
* Content: [Automatically created managed properties in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/automatically-created-managed-properties-in-sharepoint)
* Content Source: [SharePoint/SharePointServer/technical-reference/automatically-created-managed-properties-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/automatically-created-managed-properties-in-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@dmahendranme Thank you for this information

I will make this information about the case sensitivity gets infront of the SharePoint team so that we can get it added to the article. 


The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by wobba** [comment]
@dmahendranme do you mean the managed property name or content being queries? Either way they are both insensitive in all my tests. Can you enlighten on the case where this information originates?

**Comment by dmahendranme** [comment]
Hi @wobba 
This is what I did.
I created a site column "Dept". In SharePoint, implicit managed property will be created. In my case, its "DeptOWSCHCS". 
Now I want to build a feature using javascript or jQuery to fetch items based on the Dept value. Therefore I used search REST api. It has a property called "selectproperties". You shall mention the property names to read the values of those properties. In my case, I mentioned "deptOWSCHCS" (notice the first letter, its small 'd'). It was **working fine for more than 8 months**. 
And suddenly the property "deptOWSCHCS" started **returning null value**. 

I have created a ticket and Microsoft support engineer from Fast search team confirmed that the implicit property names are case-sensitive. 
Now I changed the property's first letter to capital "D" i.e., DeptOWSCHCS. It started working fine. 

This information should be available in the documentation. Hope I explained well. 
Still wondering, how it was working for more than 8 months. I think Microsoft had pushed some updates that caused this issue. 
**Note: This is on SharePoint Online**

**Comment by dmahendranme** [comment]
Thanks @wobba 
Make sure you are testing in SharePoint Online with **IMPLICIT** property.

**Comment by wobba** [comment]
@dmahendranme I wrote a short blog post about it as well - and I agree the docs should be updated.

**Comment by tseward** [comment]
@AndreaBarr please assign this to me. I'll take care of the doc.

**Comment by dmahendranme** [comment]
Thank you @wobba 

@tseward Thank you for taking care of it.

**Comment by wobba** [comment]
@dmahendranme Would it be useful if the docs mentioned that this also applies to SP2019 (which it does)?

**Comment by tseward** [comment]
@wobba it has the 2013, 2016, and 2019 tag on it.

**Comment by wobba** [comment]
Indeed @tseward...it's missing the SPO one 😉 oh well.

**Comment by tseward** [comment]
https://docs.microsoft.com/en-us/sharepoint/manage-search-schema under the **Auto-generated managed properties** heading. Not quite the same, but probably the appropriate article to tag, unless the SharePoint Server information is identical to the SPO information. Thoughts?

**Comment by wobba** [comment]
For these optimizations it's the same. Which means, in general if you align with the casing listed you will always be ok. But those two articles should be linked if they are not. Seems to be a lot of articles excluding SPO in what it applies to, which is not correct, as most classic search API/config apply to SPO as well. Then again, doing the work to go over all the articles to fix them is a lot of work.
