### ISSUE TITLE
where are runner servers located due to data residence per european law?

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-SharePoint#2960]
[In the Documentation, it is mentioned under: “user data as it flows through us”, that the data will be temp. stored locally until the data is final uploaded.

We would need to know "where" those servers are located due to many companies in finance and insurance sectors
are not allowed by european law that any personal/corporate data from Europe is stored outside European Data centers.

Pls can you add any reference to the page about the geo location ?
Thanks and cheers, Steve]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a322ff-ef0c-3e25-5989-cc1f0b4ed57e
* Version Independent ID: d6dacddd-72cd-9ef1-ceb8-adf7b1cc8e2a
* Content: [Mover services migration security - Migrate to Microsoft 365](https://docs.microsoft.com/en-gb/sharepointmigration/mover-security#user-data-as-it-flows-through-us)
* Content Source: [migration/mover-security.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-security.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by JoanneHendrickson** [comment]
Checking with team.

**Comment by JoanneHendrickson** [comment]
Mover has two geo locations for server farms. The largest is in North America and other is in Europe - specifically in Amsterdam.

**Comment by get-itips** [comment]
Thanks @JoanneHendrickson

**Comment by get-itips** [comment]
@scanum

**Comment by stche** [comment]
@JoanneHendrickson - Thanks for the answer, now we're still not clear on when and where data is hosted while processed!??
a) if data migration is initiated from europe, can we say that it will be stored temporarily by Runner servers of Mover in Amsterdam datacenters (which would then follow EU data regulation data not to leave country)
or
b) it will be always processed via NA servers and can just randomly sit on Amsterdam DC?
This is really important to know for our customer in europe as this would block them usign Mover tool if data cannot be hold in EUROPE!
