### ISSUE TITLE
Incorrect/unhelpful link

### ISSUE THREAD

**Issue by JAndre7** [MicrosoftDocs/OfficeDocs-SharePoint#2963]
The article includes this paragraph:

**Global navigation in the SharePoint app bar must be enabled in order for SharePoint resources to display in the Microsoft Teams app bar for Viva Connections.**

where "Global navigation in the SharePoint app bar" is a hyperlink. I assumed that hyperlink would educate me about what I need to do to enable the global navigation, BUT the hyperlink just points to the same page which provide no value and wastes time. Please correct this to provide a link that explains to people how to enable global navigation. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections desktop to Microsoft Teams - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/viva-connections)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Holland-ODSP** [comment]
Thanks for your entry @JAndre7 , I just fixed this
