### ISSUE TITLE
authentication context with SharePoint sites license requirements - any plan on including Microsoft 365 E5 Developer (without Windows and Audio Conferencing)? 

### ISSUE THREAD

**Issue by aspnet4you** [MicrosoftDocs/OfficeDocs-SharePoint#2965]
As per documentation - Using authentication context with SharePoint sites requires at least one of the below licenses:
Office 365 E5
Office 365 A5 for faculty
Office 365 A5 for students
Microsoft 365 E5
Microsoft 365 E5 Compliance
Microsoft 365 E5 Information Protection and Governance
Microsoft 365 Security And Compliance For FLW
Microsoft 365 A5 for faculty
Microsoft 365 A5 for students

Question: Is there any plan on adding "Microsoft 365 E5 Developer (without Windows and Audio Conferencing)" to the list?

Up until July 2021 set-sposite command worked with Microsoft 365 E5 Developer (without Windows and Audio Conferencing) license but it has been broken since Aug 2021. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0333d571-acdd-5efb-f22f-6c75822ce12c
* Version Independent ID: e7e2d85d-053e-164f-4ddd-675c5ccc97f4
* Content: [Manage site access based on sensitivity label - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/authentication-context-example)
* Content Source: [SharePoint/SharePointOnline/authentication-context-example.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/authentication-context-example.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@SanjoyanM can you help?

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by aspnet4you** [comment]
@MikePlumleyMSFT - Updating the documentation will help but update should reflect the reality. User with Microsoft 365 E5 Developer (without Windows and Audio Conferencing) license no longer allowed to run set-sposite command. You will get the following error-

![image](https://user-images.githubusercontent.com/33773493/136322408-6e974fd9-bee4-41e0-bce5-e3460b4f1bbe.png)

**Comment by aspnet4you** [comment]
@scanum, @SanjoyanM and @MikePlumleyMSFT -
Thanks for resolving the license issue. I am able to run Set-SPOSite with Microsoft 365 E5 Developer (without Windows and Audio Conferencing) license. Just tested and it is working (see below)-

![image](https://user-images.githubusercontent.com/33773493/145664674-ad88cff8-bd99-4858-a811-b4ba92abc8b7.png)
