### ISSUE TITLE
Further clarification on path change behavior for KFM feature

### ISSUE THREAD

**Issue by ChelseaMSFT** [MicrosoftDocs/OfficeDocs-SharePoint#2966]
KFM enablement will cause a change to end users in their navigation experience while using commands. 

Will it be possible to document this under the KFM section for end users reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
