### ISSUE TITLE
Outdated steps

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/OfficeDocs-SharePoint#2967]
These steps are no longer valid

To enable Azure AD passcode authentication

Sign in to the Azure portal as an Azure AD global admin.
In the nav pane, select Azure Active Directory.
Under Manage, click External identities.
Click External collaboration settings.
Under Email one-time passcode for guests, choose Enable email one-time passcode for guests effective now.
Select Save.

**Email one-time passcode for guests has been moved to All Identity Providers.**

![image](https://user-images.githubusercontent.com/8972968/135123507-a1223b10-c75b-45a2-87d0-f1280052c6d8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @zlDev
