### ISSUE TITLE
incorrect or missing information

### ISSUE THREAD

**Issue by stche** [MicrosoftDocs/OfficeDocs-SharePoint#2970]
[In this article, almost bottom down, under the anchor "Transition from Windows Folder Redirection Group Policy Objects", you'll find this:
* If folders have been redirected to a network file share:
   (...)
   3.  Enable KFM Group Policy. Known folders move to OneDrive and will merge with the existing Desktop, Documents, and Pictures folders, which contain all the file share content that you moved in the first step.

-- > This is only true, if these folders are sitting at the root of OneDrive. If the previous Windows Folder redirection used to have a different folder structure such as "Documents\Desktop...  etc. then KFM will not recognize the subfolder level and will recreate the Known folders on root again. This will then confuse the end users as they are trying to find their files under the KFM redirected folders which are empty while maybe at backend a migration copied all those into the subfolder hierarchy.

# Please add this information into the  post as we have seen many customer running into that issue.
thanks, steve, a FastTrack EE]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @stche Steve, I am looking into this. Thanks

**Comment by enigmanet** [comment]
The article/summary above does that plus more.  If the user has anything left on his desktop, etc. it also creates duplicate folders as stated in the feedback [#3109]([[url](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3109)](url)).  The only work around is to have the items removed or cleared out if migrated to cloud already and let it sync down.  Ideally you would want to have the "merge" happen but it's not possible as of right now.

**Comment by stche** [comment]
@enigmanet 
Thanks for your comment but I still do miss out that piece of information on the article, so could you please add it to the description to make it fully clear that the KFM folders will be created/only merged when they are sitting on ODB root level?

By now what commonly happens is that, once a windows folder redirection was previously in place, the folder structure is quite often like having a "My Documents folder" at the file share as redirection point and all other folders like "Documents, Desktop, Pictures,..etc." are sitting underneath. Now one KFM kicks in, it will look at root level in ODB whether those folders do exist and if not, they will be created by KFM.

Confusion for Customers and users is now that way:
A data migration at backend happens. From previous folder redirection, the folder structure is not as expected by KFM and that leads to data being copied into a subfolder in ODB and when KFM is enabled those folders are empty or not having the date expected because from data migration it sits underneath another folder (ex. "My Documents folder") and is not linked to any of the known folders.

Thats what should be clarified and called out in the post as it leads to many support cases where customer are complaining about that lack of information!

This was my initial intend to get this updated in the article. I understand that the "auto merge" action si not yet possible but the article should explain the caveats related to a previous Folder redirection and what to consider when switch to KFM!
So please can you reopen and fix this please?

Tx i.Advance and kr, Steve
