### ISSUE TITLE
[Mobile] App acquisition flow. Workaround is to install missing app from desktop

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-SharePoint#2971]
How do I get more details about this issue? I think we are facing similar issue with recently rolled out custom app in our organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958b2a50-d11c-7b65-21c1-7789f5c6c071
* Version Independent ID: 0162517a-2007-2258-46d8-55518e22581f
* Content: [Overview: Viva Connections (Preview) - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/viva-connections-overview)
* Content Source: [SharePoint/SharePointOnline/viva-connections-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Holland-ODSP** [comment]
Hey @NWH-SAmin5 thanks for your patience while we got back to you.

Did you originally get the first version of this product, Viva Connections desktop? And now you want mobile? If so, follow the [guidance here](https://docs.microsoft.com/en-us/sharepoint/viva-connections#how-to-add-the-mobile-experience) and then use the newest instructions to [get the desktop and mobile experience.](https://docs.microsoft.com/en-us/sharepoint/guide-to-setting-up-viva-connections)

**Comment by Holland-ODSP** [comment]
Hello and my sincere apologies for my late response.

I want to connect you with the product team but need more information from you:

Is your situation that you installed the desktop-only application first, and then went to install the desktop/mobile version and now mobile doesn't work? Or something else?

**Comment by NWH-SAmin5** [comment]
Thanks for reaching out

We used **Teams app setup policy** for installing app for all users

For some users Viva connections app did not appear on mobile phones, same thing happened with our custom app as well which was also pushed using **Teams app setup policy**

**Comment by Holland-ODSP** [comment]
Ok got it. Do you know if users were successful in launching the app manually? Or did you experience more problems? Also do you have a sense for about how many people in your org were impacted? Thanks for helping us learn more so we can improve the experience.

**Comment by get-itips** [comment]
@NWH-SAmin5 Did you have chance to see @Holland-ODSP last comment? thanks
