### ISSUE TITLE
Typo for the word policy

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/OfficeDocs-SharePoint#2972]
In the Important message section:

 Important

Unless you want to block access to all locations by default and only allow locations authorized in a DLP **polcy**, the DLP policy must include all SharePoint sites and OneDrive accounts and exclude none.

Typo for the word policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Mark new files as sensitive by default - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks! @Rykimaruh
