### ISSUE TITLE
Unmanaged Devices - Conditional Access Policy - Add Note to delete

### ISSUE THREAD

**Issue by jstrong013** [MicrosoftDocs/OfficeDocs-SharePoint#2975]
When you set the setting "allow limited, web-only access," from the SharePoint admin center  (Unmanaged devices), it creates a conditional access policy on behalf of the user with a title of "[SharePoint admin center]Block access from apps on unmanaged devices - Date" 

If you wish to revert this behavior, by then selecting "Allow full access from desktop apps, mobile apps, and the web" in the SharePoint admin center (Unmanaged devices) it puts the state of the conditional access policy to "off" but does not honor this state. It still requires the device to be managed. You also have to manually delete the conditional access policy. 

A note should be added to the documentation that if you wish to revert this behavior you have to delete the conditional access policy created as well. 

This behavior was confirmed in Microsoft case (Azure Team) number: 2109290040004664 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#limit-access)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jstrong013 Jeremiah, how are you?

Hope you are doing good.

I tested this on my lab, I could verify what you describe here with one difference, I could log in with an unmanaged device after reverting to allow full access, I just had to wait more or less 24 hours.

Thanks

**Comment by jstrong013** [comment]
@get-itips Andres, I'm alright. Hope you are doing good as well!  

Appreciate the time and discoveries! 

I do believe this would be a nice thing to add to the documentation. Most front line support support only references the documentation. Thus, without this knowledge addition, they spend a lot of extra time troubleshooting. Thoughts on adding? 

If not beneficial in your eyes, feel free to close the issue. 

Cheers

**Comment by get-itips** [comment]
@jstrong013 Jeremiah, thanks for returning and sharing your feedback, I'll propose adding that information, if it gets approval, it will be published. Thanks again
