### ISSUE TITLE
Clarification for delay and which apps templates will appear in

### ISSUE THREAD

**Issue by OzmeisterO** [MicrosoftDocs/OfficeDocs-SharePoint#2976]
[Enter feedback here]
Thanks for the info. on this page.  Having been through the process, there's 2 clarifications which would really help:
1. The page just mentions PowerPoint with regards templates.  There's a lot of confusion on the chatrooms as this process seems to enable templates for Word, Excel, and PowerPoint desktop apps, but only PowerPoint web app.  Is this by design, are changes being implemented, or is something not working?
2. Please could you include an indication of how long it is likely to take for the templates to appear in the desktop / browser applications once the script has been run.  My experience was about an hour for PowerPoint web app and 6 hours for all the desktop apps.  Others have complained of having to wait over 24 hours, days, or even months!

Thank you - it was a simple process with your instructions, but the wait and different experience in different apps has caused confusion.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@OzmeisterO Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
