### ISSUE TITLE
Effect of MC270671 on Documentation for Hybrid federated search

### ISSUE THREAD

**Issue by ssandu** [MicrosoftDocs/OfficeDocs-SharePoint#2977]
According to MC270671 we will do some changes on Hybrid Federated Search. We should also change the article with configuring or add a note about this script.

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-hybrid-federated-search-sharepoint-serverroadmap.md

**Comment by scanum** [comment]
@ssandu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ssandu looking into this. Thanks
