### ISSUE TITLE
URL ERROR

### ISSUE THREAD

**Issue by asumner** [MicrosoftDocs/OfficeDocs-SharePoint#2978]
Hi, On-->To approve a request, use the cmdlet Approve-SPOTenantServicePrincipalPermissionRequest. link goes to the wrong command "Approve-SPOTenantServicePrincipalPermissionGrant"
Instead of 
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/approve-spotenantserviceprincipalpermissionrequest
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28adf02-7572-f60e-7b06-bb83c558166c
* Version Independent ID: 08d0f581-9739-12b6-fa27-1fcf2d74ebdf
* Content: [Manage access to Azure AD-secured APIs - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-US/sharepoint/api-access)
* Content Source: [SharePoint/SharePointOnline/api-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/api-access.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@asumner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
