### ISSUE TITLE
Link error (404) on link to UserVoice at end of page

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/OfficeDocs-SharePoint#2984]
[Enter feedback here]

The link to
https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration?category_id=144408
at the end of the article, in the FAQ section, 
(for feedback about the provisioning service)
is a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3739a833-d9b7-baee-2d17-26cba48d7da8
* Version Independent ID: 0618f0c0-e98a-d932-fb29-65a4852fe90b
* Content: [Overview of the Microsoft New Employee Onboarding sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub)
* Content Source: [SharePoint/SharePointOnline/provision-neo-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/provision-neo-hub.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by lindspea** [comment]
@robertafreese thank you for reaching out and helping improve Microsoft Docs. Please see the note in this article with regards to User Voice - "Microsoft will be moving from UserVoice to our own customer feedback solution on a product-by-product basis during 2021," as well as this linked article - https://support.microsoft.com/office/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a. The article will be updated soon with new information.
