### ISSUE TITLE
Time limit for redirect?

### ISSUE THREAD

**Issue by PauliRekola** [MicrosoftDocs/OfficeDocs-SharePoint#2994]
Hi,
There is mention "When you rename your SharePoint domain, we create a redirect at the previous address." how long this redirecting will work? Is there some time limit or does it work forever?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by WayneEwington** [comment]
@PauliRekola This question is answered in [Frequently asked questions about SharePoint Domain renames
](https://docs.microsoft.com/sharepoint/troubleshoot/administration/domain-rename-faq). 
_As of today, Microsoft will not delete any redirected sites that were created as part of a tenant rename but this may change in the future._

**Comment by get-itips** [comment]
Thanks @WayneEwington
