### ISSUE TITLE
The urls parameter must be url encode

### ISSUE THREAD

**Issue by waldo2188** [MicrosoftDocs/OfficeDocs-SharePoint#2997]
In tne part[Auto-configure SharePoint site synchronizationof the documentation, I think it will be a good thing to explained that the parameters (siteId, , webId, webUr, listIdl, userEmail, webTitle, listTitle) mus be URL encode. Without URL encode, OneDrive doesn't care about the parameters.

Here is an example.

```powershell
Add-Type -AssemblyName System.Web
$WebURL = [System.Web.HttpUtility]::UrlEncode("https://plop.sharepoint.com")
$SiteID = [System.Web.HttpUtility]::UrlEncode("{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
$WebID = [System.Web.HttpUtility]::UrlEncode("{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}")
$ListID = [System.Web.HttpUtility]::UrlEncode("{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}")
$WebTitle = [System.Web.HttpUtility]::UrlEncode("PLOP")
$ListTitle = [System.Web.HttpUtility]::UrlEncode("Folder")
$UserName = [System.Web.HttpUtility]::UrlEncode("me@exemple.com")

Write-Output "Configure OneDrive"
$odopen = "odopen://sync/?onPrem=0&webTemplate=68&libraryType=4&siteId=" + $SiteID + "&webId=" + $WebID + "&webUrl=" + $webURL + "&listId=" + $ListID + "&userEmail=" + $UserName + "&webTitle=" + $WebTitle + "&listTitle=" + $ListTitle

Start-Process $odopen
```

Here is the related issue : [Add office365 Sharepoint library to OneDrive Sync](https://serverfault.com/questions/1080214/add-office365-sharepoint-library-to-onedrive-sync)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using Microsoft Endpoint Configuration Manager - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows#deploy-the-onedrive-app-on-mobile-devices-running-ios-or-android)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
