### ISSUE TITLE
Markdown formatting error

### ISSUE THREAD

**Issue by RicardoSilveira23** [MicrosoftDocs/OfficeDocs-SharePoint#30]
Documentation page: 
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/overview-of-the-services-upgrade-process.md

In this page there is an extra space placed after "Summary:" that doesn't allow for the markdown to process the bold.

` **Summary: ** Create a `

![not_bold](https://user-images.githubusercontent.com/24255374/38876916-5c5985fc-4255-11e8-8e88-4a5fb97d75ad.PNG)

**Comment by Techwriter40** [comment]
updated and republished
