### ISSUE TITLE
Refinable is disabled

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-SharePoint#300]
Why we could not set Refinable and is there a way we can create Refinable property via PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b707d763-4c82-0d68-9cc7-35fb66935d25
* Version Independent ID: 4da67e73-1af9-ed9d-f367-4048ce5897fd
* Content: [Manage the search schema in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-search-schema?redirectSourcePath=%252fen-us%252farticle%252fManage-the-search-schema-in-SharePoint-Online-d4fab46d-ba41-4c03-9d4c-32b5b33198b6)
* Content Source: [SharePoint/SharePointOnline/manage-search-schema.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-search-schema.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by AndreaBarr** [comment]
@ravick4u Thank you for this feedback

I an not sure if we can set Refinable or a if there is a way to create a Refinable property via PowerShell. I will get this inquiry over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
You cannot create Refinable properties in SPO. You can, however, use one of the couple of hundred precreated Refinable properties. These will start with the word "Refinable", e.g. RefinableString00, RefinableInt00, and so forth.
