### ISSUE TITLE
Enabling this integration prevents file sharing with users in national clouds and the document should say that

### ISSUE THREAD

**Issue by supportguy** [MicrosoftDocs/OfficeDocs-SharePoint#3001]
This document should have a limitation/issues section that calls out what issues will occur if you turn on this feature.

For example enabled AzureB2B collaboration will prevent you from being able to share file with M365 users using national cloud/Gov instances of M365. 

What other limitations are there with this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by salarson** [comment]
@tiburd  - We can add the following:

"At this time, customers in national and restricted clouds who enable Azure B2B Integration with SharePoint Online will not be able to share files and folders with recipients outside those environments."

**Comment by supportguy** [comment]
I think that will be a good addition.

**Comment by get-itips** [comment]
Thanks @salarson Sam.
I see the addition is merged so closing.
It should be in the published version soon.
Thanks for your feedback @supportguy
