### ISSUE TITLE
Details around the 3 downloads?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/OfficeDocs-SharePoint#3003]
Can you please provide some details about Public Preview vs. First Release vs. GA? It's a really confusing situation:

1. The latter two links go to the same place. What's the reason for this?
1. Is Public Preview link for a newer version than GA, or it is pre-GA and now obsolete?
1. Which link is intended to go to the latest version? 
1. Are there version numbers for the tool and if so, where to find them? The download pages does not seem to have them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VitalyMCT** [comment]
Thanks @get-itips, this answers most of my questions. 

The only thing I am still confused about is the purpose of the "first release" builds. What are they and when should they be used? 

Perhaps this aspect can be elaborated on in the documentation. I am well-familiar with the GA and preview releases for other services/software.

**Comment by VitalyMCT** [comment]
Thanks @get-itips , this is very helpful. Appreciate your response & the extra info.
