### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by doulouz** [MicrosoftDocs/OfficeDocs-SharePoint#3006]
[Enter feedback here]

There is a broken link in this section

"When information barriers are enabled on SharePoint and OneDrive, the OneDrive of segmented users are automatically protected with IB policies. Information barriers modes help strengthen access, sharing, and membership of a OneDrive site based on its IB mode and segments associated with the OneDrive."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef03ccd-fd27-4724-75c1-eec90be8ad8b
* Version Independent ID: a9e393d2-9bcc-3814-2654-bd40f23d5306
* Content: [Use information barriers with OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/information-barriers)
* Content Source: [OneDrive/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/information-barriers.md)
* Service: **one-drive**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Thanks for your feedback! @doulouz
