### ISSUE TITLE
Please add a section that enumerates what changes happen when you designate a home site. 

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SharePoint#3011]
Please add a section that enumerates what changes happen when you designate a home site. This would help organizations prepare before going live with the home site. 

This [article ](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/sharepoint-home-sites-a-landing-for-your-organization-on-the/ba-p/621933) mentions the below changes that happen, but having something officially added as part of this page would make it more accessible and could be more comprehensive as the product evolves:  

- The site is configured as an official organizational news site.
- Search scope is set to tenant wide for the home site.
- Enables one click access from the SharePoint mobile app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98d3b9c-948e-7719-defd-3b604523c492
* Version Independent ID: f43d1a28-3690-6921-52b4-02a8d85f18a5
* Content: [Plan, build, and launch a home site for your organization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site-plan)
* Content Source: [SharePoint/SharePointOnline/home-site-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/home-site-plan.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thanks all for your further exploration and feedback. I agree with you @soyalejolopez and will incorporate more information that explain how a home site technically makes the features work.

**Comment by soyalejolopez** [comment]
Excellent, thank you Holland!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
