### ISSUE TITLE
example transfer log doesn't exist

### ISSUE THREAD

**Issue by ed-roberts** [MicrosoftDocs/OfficeDocs-SharePoint#3025]
Click example transfer log html file leads to nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614bed2e-9902-91da-ccee-1ebefbea49b3
* Version Independent ID: c0702d8a-9650-e9e3-c30c-fc8361786b55
* Content: [Mover transfer logs - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-transfer-logs#interpreting-a-log-file)
* Content Source: [migration/mover-transfer-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mover-transfer-logs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
fixed.
