### ISSUE TITLE
How can we delete Result source

### ISSUE THREAD

**Issue by CarlVerret** [MicrosoftDocs/OfficeDocs-SharePoint#3027]
[Enter feedback here]
Hi there, I can easily add and modifiy seach result source but I can't find a way to simply delete tests sources that I've made in my tenant.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4072d3b5-45f9-746a-2954-64006add2181
* Version Independent ID: 66f9429e-6fd5-500b-048f-add3fdb61b5f
* Content: [Manage result sources - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-result-sources)
* Content Source: [SharePoint/SharePointOnline/manage-result-sources.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-result-sources.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @CarlVerret 

You have the option selecting the down arrow next to the result source, for example:

![image](https://user-images.githubusercontent.com/36666927/140535981-a32594e1-0193-4dcd-9f84-c1113104a522.png)

hope this information helps you,

**Comment by CarlVerret** [comment]
Thanks!  I finally figured it out, problem is that there's no mention of it in doc +  the tiny arrow is quite far away and only appears when you hover over the list items.  Maybe doc can be adujsted to mention it ?

**Comment by get-itips** [comment]
> Thanks! I finally figured it out, problem is that there's no mention of it in doc + the tiny arrow is quite far away and only appears when you hover over the list items. Maybe doc can be adujsted to mention it ?

@CarlVerret Carl, will propose it, if it gets approval, it will be published.
Thanks
