### ISSUE TITLE
Consider changing Titles to be more friendly 

### ISSUE THREAD

**Issue by brockwaltersstarz** [MicrosoftDocs/OfficeDocs-SharePoint#3028]
The names of the configuration options don't make that much sense or have little relationship to what the option actually does. They are also in a terrible order & not grouped together by function which makes the options harder to use.

Attached is a version of a custom json schema for use in Jamf Pro with changed titles for options. Thanks.

[schema.json.zip](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/7472521/schema.json.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#hydrationdisallowedapps)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @brockwaltersstarz 
how are you? Hope you are doing well
Here, we are limited to documentation changes and improvements.
The feedback you are providing is more suitable for the product group, currently, the _uservoice_ pages for SPO/ODB were deprecated but you can check [here](https://support.microsoft.com/en-us/office/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a) for the status of the replacements.
Hope this helps you,
