### ISSUE TITLE
Additional Questions to this documentation

### ISSUE THREAD

**Issue by AndreSchiemann** [MicrosoftDocs/OfficeDocs-SharePoint#3029]
[Enter feedback here]
my Questions related to this documentation:
Is the color block for news posts in the UI the only outcome of setting a website as a organizational news source?
Is it possible to deregister the home site as non organizational news source?

Thanks,
André
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaab219-ec0f-143b-b418-36fea8322393
* Version Independent ID: 2054b3a7-5acd-fd32-4517-442a48abbff4
* Content: [Create an organization news site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-news-site)
* Content Source: [SharePoint/SharePointOnline/organization-news-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/organization-news-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @AndreSchiemann Andre,


> [Enter feedback here] my Questions related to this documentation: Is the color block for news posts in the UI the only outcome of setting a website as a organizational news source?

they also _appear on the SharePoint start page._ as the article states.

> Is it possible to deregister the home site as non organizational news source?

The comm home site is not returned as a result of `Get-SPOOrgNewsSite` nor it is recognized when tryint to deregister with `Remove-SPOOrgNewsSite`

Hope this information helps you,

**Comment by get-itips** [comment]
> Thanks for the feedback. I have to correct you, meanwhile I tried it: Remove-SPOOrgNewsSite recognizes and is able to deregister the home site. I did this in a tenant in order to fulfil customer requirements.

Thank you for that feedback, I'll test again. Can you share the exact SPO PowerShell module used? Thanks

**Comment by get-itips** [comment]
@AndreSchiemann Checking back if you could see my question

**Comment by get-itips** [comment]
@scanum
