### ISSUE TITLE
is the KB3092179 still applicable?

### ISSUE THREAD

**Issue by armely** [MicrosoftDocs/OfficeDocs-SharePoint#303]
The download says it's no longer available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03471062-4810-b5b9-2caa-286e5ed90706
* Version Independent ID: 4b2baed1-f7b4-81d1-dedd-28f45b5e31f1
* Content: [Use a sample MIM solution in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/administration/use-a-sample-mim-solution-in-sharepoint-server-2016#BKMK_Download)
* Content Source: [SharePoint/SharePointServer/administration/use-a-sample-mim-solution-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/use-a-sample-mim-solution-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@armely Thank you for this feedback

It appears like Trevor updated the document to reflect the correct information. I am going to close this as resolved. If this update didn't answer your question please reopen the issue.
