### ISSUE TITLE
Minor issue with graphic showing upload format

### ISSUE THREAD

**Issue by itencate** [MicrosoftDocs/OfficeDocs-SharePoint#3030]
The screenshot of the upload format in Excel is missing a "/" between the word "personal" and the user's name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [Bulk upload tasks into Migration Manager using a CSV or JSON file - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for the feedback @itencate
