### ISSUE TITLE
Broken link when accessing from Hub-Settings via Admin

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/OfficeDocs-SharePoint#3035]
[Enter feedback here]
When, from the Admin Edit Hub Settings area, there is a link to "learn more" that should take you to this page, but it has an extra "s" a the end and results in a 404 error.

https://docs.microsoft.com/en-us/sharepoint/hub-to-hub-association**s**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/hub-to-hub-association)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
@melkinsco Thank you so much for catching that - just fixed.
