### ISSUE TITLE
Clarification on search scope

### ISSUE THREAD

**Issue by melkinsco** [MicrosoftDocs/OfficeDocs-SharePoint#3036]
[Enter feedback here]
Clarification. Hub-to-hub associations only allow one to search content specifically on the associated hub sites and not on sites attached to the associated hub site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/hub-to-hub-association)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
@melkinsco - Good question. The search scope when hubs are associated to each other does scope to the sites that are associated too up to 3 "levels" of site associations down.
