### ISSUE TITLE
Small correction in Path for ADMx

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/OfficeDocs-SharePoint#3038]
Hi,
See Topic: Manage OneDrive using Group Policy
2. Browse to %localappdata%\Microsoft\OneDrive\BuildNumber\adm\ (for per-machine sync app browse to C:\Program Files (x86)\Microsoft OneDrive\BuildNumber\adm)

You are using  %localappdata%, but not for %ProgramFiles(x86)%

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy?fbclid=IwAR23V2CW1zNwlanqTRPnes415t0XRpExSNf63DO0dxPgH6t4NuIXqJNHDQ0)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by HansBrender** [comment]
and for  Machine Installation
32 Bit:  %ProgramFiles(x86)%\Microsoft OneDrive\BuildNumber\adm
64 Bit:  %ProgramFiles%\Microsoft OneDrive\BuildNumber\adm)

**Comment by mm201** [comment]
Same problem on https://learn.microsoft.com/en-us/sharepoint/install/configure-syncing-with-the-onedrive-sync-app#using-group-policy
