### ISSUE TITLE
create-claims-based-web-applications.md has instructions to create a classic

### ISSUE THREAD

**Issue by mikelee1313** [MicrosoftDocs/OfficeDocs-SharePoint#3042]
SharePoint/SharePointServer/security-for-sharepoint-server/create-claims-based-web-applications.md

This article is titled "**Create claims-based web applications in SharePoint Server**" but has instructions to create a classic web application, which is in a separate document.  This should be removed from this document.

Here is the other document: https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/create-web-applications-that-use-classic-mode-authentication.

Also, creating a classic mode web application does not apply to "Subscription Edition.

**Comment by get-itips** [comment]
Hello @mikelee1313 
How are you?
I understand what you say, however, the article is already letting us know that it is also including a small set of instructions to create a classic, and the reason for that

> However, this article also provides guidance for using PowerShell to create classic-mode web applications if you have a specific scenario that cannot support claims-based authentication.

And it is also including a link to the other, more extended, instructions that you also included in your message.

I'll check what you say about SE.

Thanks for your feedback!
