### ISSUE TITLE
"create-web-applications-that-use-classic-mode-authentication.md" does not apply to "Subscription Edition"

### ISSUE THREAD

**Issue by mikelee1313** [MicrosoftDocs/OfficeDocs-SharePoint#3043]
This document says it applies to "**Subscription Edition**" but it does not.

SharePoint/SharePointServer/security-for-sharepoint-server/create-web-applications-that-use-classic-mode-authentication.md

Classic mode is removed from "Subscription Edition" for Web applications and it should not apply to this article.

**Comment by scanum** [comment]
@mikelee1313 Hi! Please link the article you are referring to. Thank you

**Comment by fowl2** [comment]
Drive by, but I'm assuming:

This is the article that states that Subscription edition is supported -> https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/create-web-applications-that-use-classic-mode-authentication

And 

This is the "features removed" page stating it's not supported -> https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-subscription-edition#classic-authentication-mode-for-content-web-applications
