### ISSUE TITLE
The "Storage and SQL Server capacity planning and configuration (SharePoint Server)" page does not include any information about SP Subscription Edition

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint#3045]
The "Applies To" section in the page "Storage and SQL Server capacity planning and configuration (SharePoint Server)" page mentions SP Subscription Edition, but the rest of the page never mentioned Subscription Edition or any information that applies to Subscription Edition. Can this page please be updated to also reflect SPSE info?

Page: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointServer/administration/storage-and-sql-server-capacity-planning-and-configuration.md

**Comment by get-itips** [comment]
Hello @ykuijs Yorick,
I am looking into this.
Thanks

**Comment by tiburd** [comment]
@ykuijs 
Hi,

Thank you for bringing this to our attention. The team is in the process of updating this article, as well as others, to include the Subscription Edition. 

Closing this issue now.

cc: @get-itips @scanum
