### ISSUE TITLE
Two dead links in article

### ISSUE THREAD

**Issue by jbienstman** [MicrosoftDocs/OfficeDocs-SharePoint#3046]
Hi,

The "Create communication sites in SharePoint" and "Create team sites in SharePoint" throw a 404 - Page not found.

Kind Regards,

Jim
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e23d5c-f139-adcb-ed0e-cf395fda8906
* Version Independent ID: f09f734d-de34-4120-996f-4c2eb0bb89d7
* Content: [Creating and launching a healthy SharePoint portal - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/SharePoint/portal-health?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/portal-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/portal-health.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback @jbienstman Jim, fixing
