### ISSUE TITLE
Suggestion for improvement in user experience

### ISSUE THREAD

**Issue by mugscari** [MicrosoftDocs/OfficeDocs-SharePoint#3048]
We have tried the procedure and we get error 773, which means it is not available yet for our tenant.

I would suggest 2 alternatives to improve the user experience:

1. Implement the possibility to apply to all tenants BEFORE publishing the page
2. Supply a request form so that the tenants who are interested in applying immediately the change can do so (clearly with a queue based on the date of the request).

Under the latter, you could also estimate a date of implementation for the requesting tenant based on the queue, instead of the answer we got on our ticket "Unfortunately, we cannot provide you with and implementation date..."

In case someone from Microsoft is reading this post, we are interested in applying the change asap.
Please contact me if you need the details of our tenant.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
