### ISSUE TITLE
Posters & Email Templates Link incorrect

### ISSUE THREAD

**Issue by fns-it** [MicrosoftDocs/OfficeDocs-SharePoint#3051]
Under "Onboarding related resources", the link for **Posters, email templates**  directs to https://support.microsoft.com/office/create-and-use-site-templates-in-sharepoint-server-versions-60371b0f-00e0-4c49-a844-34759ebdd989

That link is for how to create and use site templates in SharePoint and does not link to the stated resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks @fns-it
