### ISSUE TITLE
Numbers don't add up

### ISSUE THREAD

**Issue by TravisGuinn** [MicrosoftDocs/OfficeDocs-SharePoint#3053]
In this paragraph:
"For example, it is common for there to be **half a second** of overhead per file being moved. If you are moving 200,000 files, this would be **200,000 seconds** or more than two days' worth of overhead alone!"

It states 1/2 second of overhead on 200,000 files equals 200,000 seconds. Wouldn't that be **100,000** seconds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f08a57-d8a0-86d8-d81e-b1d8d6c34644
* Version Independent ID: 024af5b6-c33b-d571-1bdb-4a2934432984
* Content: [Mover Migration Tools overview and planning - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-plan-migration)
* Content Source: [migration/mover-plan-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mover-plan-migration.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback @TravisGuinn
