### ISSUE TITLE
brian

### ISSUE THREAD

**Issue by ubhub** [MicrosoftDocs/OfficeDocs-SharePoint#306]
I'm confused. I want to set up OneDriveforBusiness for my teaching files on my personal computer. I don't want to mess with my personal OneDrive. I don't have Office installed at mo. It's on an old PC. I don't have a 365 sub and neither does my school. I downloaded the ODfB zip and extracted and opened the Deploy … file to get me here. Do you have a video? I ran sccm create device collection from my start button and got to another support page https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/create-collections . Can you help?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-au/onedrive/deploy-on-windows?redirectSourcePath=%252farticle%252f3f3a511c-30c6-404a-98bf-76f95c519668)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@ubhub Thank you for this inquiry. 

I am not sure where in the process you are or how exaclty to help you get ondrive for business installed at your stage in the process. I do know that Support has more resources than we do here to bring your issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
