### ISSUE TITLE
Improving guidance about site redirect 

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/OfficeDocs-SharePoint#3063]
From our experience, swapping the root site only provide redirect from the source (site added as root), but not from the target (site removed as root).

We used the PowerShell to be able to edit the Archive URL for the root site being replaced to "/sites/legacy". We replaced a classic publishing portal site with a Communication site. After the site was replaced without errors, all links referring to old root site, and its subsites, stopped working. For example links to SP Lists included in Outlook invitation.. After the site was replaced without errors, all links referring to old root site, and its subsites, stopped working. For example links to SP Lists included in Outlook invitation.

We suspect this is because the URL is reserved for the new root site and it would be impossible to redirect.  Of course the redirect created from the source as that URL is no longer occupied.

The guidance is quite clear when I read it again, but we missed the fact that redirect only works for the source of the swap: "By default, a site redirect will be created that will redirect traffic from the source site to the root site."

We would have appreciated seeing a warning that no redirect from the old root site can be created. All such links will need manual updates.

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
