### ISSUE TITLE
How to create security groups?

### ISSUE THREAD

**Issue by justinmacleod** [MicrosoftDocs/OfficeDocs-SharePoint#3064]
This page talks about how to limit sharing to members of a specific security group. It would be great to know how to create these groups or have it as a referenced page.

Justin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage security groups - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-security-groups)
* Content Source: [SharePoint/SharePointOnline/manage-security-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-security-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by justinmacleod** [comment]
Maybe a reference link on the page should go to this support article: https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-edit-or-delete-a-security-group?view=o365-worldwide

**Comment by get-itips** [comment]
Hello @justinmacleod Justin, how are you?
_Security Groups_ is one of the many pillars in Microsoft 365, I am not 100% sure about adding a link to this article about that. Thanks for your feedback!
