### ISSUE TITLE
Broken "Download the PDF" link

### ISSUE THREAD

**Issue by valtrig** [MicrosoftDocs/OfficeDocs-SharePoint#3067]
The "Download the PDF" link at the top of the page is broken. It seems that the '.../raw/live/...' part of the URL should be '.../raw/public/...' instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56a7c7c-1b7d-dd7a-684e-df2cdf991582
* Version Independent ID: 7bb3885c-77bc-fee9-a705-b3054d31bf0a
* Content: [Create guidelines for site usage - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sites-usage-guidelines)
* Content Source: [SharePoint/SharePointOnline/sites-usage-guidelines.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sites-usage-guidelines.md)
* Service: **sharepoint-online**
* GitHub Login: @jhendr
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback!
