### ISSUE TITLE
Roadmap info for cross-org MFA support?

### ISSUE THREAD

**Issue by jitterbox** [MicrosoftDocs/OfficeDocs-SharePoint#3068]
When is cross-organizational (with MFA) support expected to be available in B2B sync?
Listing latest-release features and known issues is very helpful as long as they're kept up-to-date. Is there a roadmap available with an ETA for this feature?

"Multifactor authentication from an external organization is not yet supported. Only guest accounts that don't require MFA will sync."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync - OneDrive](https://docs.microsoft.com/en-us/onedrive/b2b-sync)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @jitterbox I am looking into this.

**Comment by gojo119** [comment]
Hello @get-itips , do you have any update regarding the b2b mfa support?

**Comment by get-itips** [comment]
> Hello @get-itips , do you have any update regarding the b2b mfa support?

Still trying to get the information for you, will reply  as soon as I get it

**Comment by get-itips** [comment]
@gojo119 What I got at this moment is the timeline is January 2022 however I'll try to confirm.

**Comment by gojo119** [comment]
Hello @get-itips , that sounds very promising! Thank you for keeping us updated! 👍

**Comment by get-itips** [comment]
@scanum

**Comment by jitterbox** [comment]
Is this issue being closed because you *did *confirm that it will be
resolved in January 2022, or because you could not?
Can you provide a link to a roadmap item regarding a fix?

**Comment by BillSproule** [comment]
OneDrive sync engineering team has cross cloud B2B on our backlog. We will update the documentation as the feature is available for preview.

**Comment by AndrewPascoCS** [comment]
can you please have the Roadmap updated with the the plan.

https://www.microsoft.com/en-AU/microsoft-365/roadmap?filters=OneDrive&searchterms=sync

**Comment by GitHubAdminAccount** [comment]
Hi @BillSproule! Thanks for all your help on these threads.  To clarify, was cross-organizational (with MFA) support made available in B2B sync in January per the thread above, or is support for MFA delayed and on the backlog without a clear roadmap date and not tracked in the public roadmap?  Appreciate it, thank again!
