### ISSUE TITLE
Minimum requirements show unsupported products

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint#3070]
The minimum required operating system shows: Windows Server 2008 R2, Windows 7 updated or better.NET Framework 4.6.2 or later

Since Windows Server 2008 R2 and Windows 7 are unsupported since January 2020: Don't think we should be mentioning unsupported products here. Please update to a supported OS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e2247-016b-74b2-cf03-3041af3df550
* Version Independent ID: 3d6d4b62-4f26-81d1-6be2-ecfe7ebd81bf
* Content: [Prerequisites and Endpoints for SharePoint Migration Tool - Migrate to Microsoft 365](https://review.docs.microsoft.com/en-us/sharepointmigration/spmt-prerequisites)
* Content Source: [migration/SPMT-Prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/SPMT-Prerequisites.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @ykuijs Yorick,

I'll propose to update that, if it gets approval, it will be on the published version of the article.

Thanks for your feedback,
