### ISSUE TITLE
start-spotenantrename is not recognized

### ISSUE THREAD

**Issue by ACSirus** [MicrosoftDocs/OfficeDocs-SharePoint#3073]
The term 'start-spotenantrename' is not recognized as the name of a cmdlet,...

I am using the latest Powershell Module

get-installedmodule | Where-Object {$_.Name -match "Microsoft.Online.SharePoint.Powershell"} | select version

Version         
-------         
16.0.21909.12000

What is going wrong?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
