### ISSUE TITLE
3650 is not a typo for 365? just checking

### ISSUE THREAD

**Issue by mcasaz** [MicrosoftDocs/OfficeDocs-SharePoint#3079]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users - OneDrive](https://docs.microsoft.com/en-us/onedrive/set-retention)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by anooptp** [comment]
@mcasaz - I think it correct. 
It should be 3650, which means the retention days can be between 1 months to 10 years.

![image](https://user-images.githubusercontent.com/6757444/145088546-cfa717af-460f-45f7-9893-899b4780af8e.png)
