### ISSUE TITLE
New and Existing External Users

### ISSUE THREAD

**Issue by jt980** [MicrosoftDocs/OfficeDocs-SharePoint#308]
"New external users will be added to Azure Active Directory when they sign in to view the shared item. "  &lt;-- Does this mean that everyone (external) who views shared files is automatically added to our internal Active Directory?  Because that is what it is saying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a570bb-2567-565c-e9ff-bf1ccbf38d0e
* Version Independent ID: 3d342dea-9dd3-008c-20c6-902452302e95
* Content: [Manage sharing in OneDrive and SharePoint](https://docs.microsoft.com/en-us/onedrive/manage-sharing#externalsharing)
* Content Source: [OneDrive/manage-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/manage-sharing.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jt980 Thank you for this inquiry. 

I would say yes, this means everyone external that views the shared files are automatically added to the internal AD. I want to get confirmation on this though so I am going to get this in front of the SharePoint team for investication and clerification. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jt980** [comment]
Confirmation would be great.  Having outside uses added to our internal AD would be a problem.  Thank you for the assistance!


Thank you,

Johnny Trombley
Eastern Los Angeles Regional Center  / IT Department
[cid:image004.png@01D36D11.A7F68920]<http://www.elarc.org/>  [cid:image005.png@01D36D11.A7F68920] <https://www.facebook.com/easternlosangelesregionalcenter/>   [cid:image006.png@01D36D11.A7F68920] <https://twitter.com/EasternLA_RC>   [cid:image007.jpg@01D36D11.A7F68920] <https://www.instagram.com/elarcfordd/>

**Comment by swhite-strath** [comment]
I read the same thing and decided to test it out, when I shared to an external recipient there was no guest accounts created. I think this function has now been changed according to this, 

[https://docs.microsoft.com/en-gb/sharepoint/what-s-new-in-sharing-in-targeted-release](url)

I think this applies to sharing files with One Drive for business also?

**Comment by MikePlumleyMSFT** [comment]
A more complete description of the external sharing functionality in OneDrive and SharePoint can be found in [External sharing overview](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview). Generally speaking, if you share with someone who has an Azure AD / Office 365 account, they are added to the directory as a guest; otherwise, they are not.

**Comment by swhite-strath** [comment]
I initially tested with a gmail and hotmail account, but I just tested it with another company who has office 365 and same thing, no guest account was created. They just gain access using the verification code.

**Comment by sharmajnu** [comment]
Both @swhite-strath and @AndreaBarr  are right here. 

In the previous implementation if you invite an external user and when the accept invitation they used to be added automatically to AD.
However this is no longer done, now they have access only using verification code and they are not added to AD anymore. 

This was done to have better control on Azure AD still allowing sharing around 6 month back or so(don't remember exact time frame)

**Comment by scanum** [comment]
@jt980 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
