### ISSUE TITLE
Migrator only migrating content of folders and not a whole folder

### ISSUE THREAD

**Issue by rooobeert** [MicrosoftDocs/OfficeDocs-SharePoint#3084]
Hi all, 

I just discovered that when using the migration manager for file shares, it treats something like this:
\\servershare\folder
and this:
\\servershare\folder\ 
exactly the same. 

When I used \\servershare\folder I was expecting to see the folder as is inside SharePoint Online. What I found instead was all the files and folders from inside of that folder. 

I´m not sure if this is expected or not. Any way it messed up my whole migration because I used a bulk csv. 

Appreciate any help. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [Bulk upload tasks into Migration Manager using a CSV or JSON file - Migrate to Microsoft 365](https://docs.microsoft.com/en-US/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @rooobeert 

I tested and as you said specifying both ..folder\ and ..folder is the same, the contents of the folder are copied.

To my understanding, that is indicated in the current dialog in the _Add Task_ wizard:

_Enter the file share **that contains** the content you want to migrate_

Let me know if I understood you correctly,

Thank you

**Comment by rooobeert** [comment]
Hello @get-itips, 
thanks for the reply. You understood me correctly. 
I thought it would be a different behavior, thanks for testing!

Everything is fine then!
