### ISSUE TITLE
More detail for how the feed is personalized.

### ISSUE THREAD

**Issue by DarrellaaS** [MicrosoftDocs/OfficeDocs-SharePoint#3086]
This page is really helpful. It explains a lot about how the Connections Feed works. However, on Q&A pair starts to explain the content is sorted into 3 buckets. But it's not clear what those buckets are based on the following bullets and content. 
Can you clarify or add to the question? 

[Link to the question on the page](https://docs.microsoft.com/en-us/sharepoint/faqs-viva-connections-feed#question-how-is-the-feed-personalized-and-how-is-content-ranked)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9328b13-0713-a038-ff1b-e4528c31d22f
* Version Independent ID: aa1ee2fa-9434-fcf6-18d3-4c34eca9eaa9
* Content: [Frequently asked questions about the Feed for Viva Connections - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/faqs-viva-connections-feed)
* Content Source: [SharePoint/SharePointOnline/faqs-viva-connections-feed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/faqs-viva-connections-feed.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by get-itips** [comment]
Hello @DarrellaaS how are you?

I think that, _how is the feed personalized_ is answered [here](https://docs.microsoft.com/en-us/viva/connections/viva-connections-overview#feed-content-sources)

Does this answer your question?

Thanks

**Comment by Holland-ODSP** [comment]
Hey @DarrellaaS - Thanks for your feedback. I revised the second FAQ to be clearer and include more detail about the 3 buckets. Take a look and let me know if you think I missed anything. Going to close this chat for now but please reopen if you have more feedback.
