### ISSUE TITLE
Disabled app from central app catalog breaks functionality on deployed webparts

### ISSUE THREAD

**Issue by AlexFilipovici** [MicrosoftDocs/OfficeDocs-SharePoint#3087]
I uploaded an SPFX webpart to the tenant app catalog. Since I want this to be optional by site, I didn't deploy tenant wide. When "Enabled", I can add the app to a site via "Add an app" and the webpart renders for that site. If I uncheck "Enable", the app is no longer available in "Add an app: as expected, but also **the functionality no longer works and the webpart just shows an empty space**.

Please see this issue reported also below:
https://sharepoint.stackexchange.com/q/268623/13225

-----------

UPDATE: The issue can be reproduced also if deployed to site collection app catalog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc1e9c0-2e35-3357-7f57-5bd02b0e10bc
* Version Independent ID: 1443a95a-ce5b-024d-d942-001b83bf8d8c
* Content: [Manage apps using the App Catalog - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/use-app-catalog)
* Content Source: [SharePoint/SharePointOnline/use-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-app-catalog.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @AlexFilipovici Alex, how are you?
I tested this on my lab tenant, added a custom app (an SPFX webpart) to the app catalog, and then added it to a site, and then added it to a page, unchecked "enable" in the app catalog, however, the webpart is still showing information and I could still change settings, as expected I could not see it as available to add.
Could this be specifically with the spfx you are trying to use?

Hope this information helps you,

Andrés

**Comment by AlexFilipovici** [comment]
hi @get-itips, have you hard refreshed the page a few times?

**Comment by get-itips** [comment]
> hi @get-itips, have you hard refreshed the page a few times?

Hello Alex, how are you? yes I did, several times to make sure. Maybe you want to try with another solution spfx.

**Comment by AlexFilipovici** [comment]
> > hi @get-itips, have you hard refreshed the page a few times?
> 
> Hello Alex, how are you? yes I did, several times to make sure. Maybe you want to try with another solution spfx.

How would _another_ SPFX solution be an answer to the problem?

**Comment by get-itips** [comment]
Hello @AlexFilipovici Alex, how are you? Hope you are doing well.
Here, we are limited to documentation changes and improvements. I tried to reproduce to understand if we needed to adjust any part of the article, however, I could not reproduce it. I'll repeat the test and get back to you.

**Comment by get-itips** [comment]
Hello @AlexFilipovici Alex, finally, after waiting longer, the webpart functionality was gone from the site page I added it.
I'll propose adding this detail to the article.
thank you
