### ISSUE TITLE
FilesOnDemandEnabled and DefaultFolderLocation are no longer options after the switch to "CloudStorage"

### ISSUE THREAD

**Issue by timnottom** [MicrosoftDocs/OfficeDocs-SharePoint#3089]
Hi,

[FilesOnDemandEnabled](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#filesondemandenabled) and [DefaultFolderLocation](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#defaultfolderlocation) are no longer options when the OneDrive client is moved from `/Users/<nameofuser>/OneDrive` to `/Users/<nameofuser>/Library/CloudStorage/Onedrive`.

I think this should be mentioned in the doc.

**Comment by get-itips** [comment]
Hello @timnottom Tim, I am looking into this.

**Comment by get-itips** [comment]
Hello @timnottom I could get some information about this

A note about FilesOnDemandEnabled was added to the article

> Beginning in macOS Monterey 12.1, Files On-Demand will be the default and there will not be a setting for users to turn it off.

**Comment by timnottom** [comment]
Thank you @get-itips for changing FilesOnDemandEnabled. I think [DefaultFolderLocation](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#defaultfolderlocation) also needs a similar banner stating that this is no longer possible to change.
