### ISSUE TITLE
Incorrect side effect ???  "File search	Search in Teams will show files only from sites whose addresses have not been changed."

### ISSUE THREAD

**Issue by fklx** [MicrosoftDocs/OfficeDocs-SharePoint#3090]
[Enter feedback here]
Hello docs team,

my customer came to me asking about the side effect when renaming a SharePoint site URL affecting SharePoint and Teams. It is abot this statement "Search in Teams will show files only from sites whose addresses have not been changed."

We tested with files published onto the Teams files BEFORE and AFTER renaming. Search (Teams and SharePoint) both showed the files published BEFORE and AFTER and no issue was found. 

Therefore asking: Is the limitation still valid?

THX and best regards Frank 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address#effects-of-changing-a-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by MikePlumleyMSFT** [comment]
@WayneEwington can you help?

**Comment by WayneEwington** [comment]
Thank you for bringing this to my attention. A number of the documented limitations are out of date and need to be corrected (including the searching of files within Teams). I will work with the technical writers to get this addressed. In the meantime, I would refer to the limitations at [https://docs.microsoft.com/sharepoint/change-your-sharepoint-domain-name](https://docs.microsoft.com/sharepoint/change-your-sharepoint-domain-name). Although these are for a changing the SharePoint domain the limitations at the site level are the same.

**Comment by get-itips** [comment]
@fklx The article has been updated thanks to your feedback.
@scanum please close
