### ISSUE TITLE
Update Pre-Provision instructions to use newer PnP.Powershell command

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/OfficeDocs-SharePoint#3091]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/request-pnppersonalsite?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization - OneDrive](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @JustinGrote Justin,

How are you? Is there any special reason why you recommend replacing the current script that uses the SharePoint Online Management Shell module?

Thanks

**Comment by get-itips** [comment]
Hello @JustinGrote 
I asked internally about this, and for consistency across other documentation where it is also used, the decision is to keep the SPO Management Shell cmdlet for the provision script.
Thanks!!

**Comment by get-itips** [comment]
@scanum
