### ISSUE TITLE
Typo: Translation Mangers

### ISSUE THREAD

**Issue by gmbrinkmann** [MicrosoftDocs/OfficeDocs-SharePoint#3092]
Typo: Translation Mangers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 815ec832-b81d-d057-27e6-a73ddf5a6632
* Version Independent ID: 7062cc8d-9769-3463-6b75-226679d720d1
* Content: [Default SharePoint groups - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups)
* Content Source: [SharePoint/SharePointOnline/default-sharepoint-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/default-sharepoint-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
