### ISSUE TITLE
Conditional Access Policy for Azure AD joined devices

### ISSUE THREAD

**Issue by Nuno83** [MicrosoftDocs/OfficeDocs-SharePoint#3093]
Hi, 

On the article there is a note informing that for devices which are only Azure AD joined to consider using a Conditional Access Policy instead.
Can you clarify how can this be achieved?
Is possible to 100% mimic the OneDrive Policy for Azure AD joined devices through a Conditional Access Policy?
If not can you change the article to be more clear on that part.
Thank you.

**Comment by scanum** [comment]
@Nuno83 Please link the article you are referring to. Thanks!

**Comment by Nuno83** [comment]
@scanum This is the article that I was referring to https://docs.microsoft.com/en-us/onedrive/allow-syncing-only-on-specific-domains. Sorry that I didn't referred to it earlier. Thank you.

**Comment by get-itips** [comment]
Hello @Nuno83 how are you?
Thanks for including the article you were referring to.
To my understanding, the use of a conditional access policy is (quoting the article) _To make sure that users sync OneDrive files **only on managed computers**_ so you can find more information on how to set up a CP, in this article for example:

https://docs.microsoft.com/en-us/onedrive/enable-conditional-access

And OneDrive is included in the _Office 365 client app_

https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365-preview

Does this answer your question?

Thank you

**Comment by Nuno83** [comment]
Hi @get-itips thank you for the fast reply.
I will provide this information to my team and verify if it is what we were looking for.
Thank you and Merry Christmas.

**Comment by get-itips** [comment]
To you too!
