### ISSUE TITLE
Please add a clear overview of inheritance of features between Parent Hub and Associated Hub AND what is the difference with associating a 'regular' non-Hub site

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-SharePoint#3096]
Adding the table on this page to the Microsoft Docs page would clarify a lot:
https://blogs.perficient.com/2021/10/19/associate-a-hub-site-to-another-hub-site-in-sharepoint-online/
Thanks Nidhi Shah!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/hub-to-hub-association)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
@SjoerdV I think you are right, that table is super helpful.

Looks like you are the original author of that table? And you don't mind if we use your content for inspiration?

**Comment by SjoerdV** [comment]
No I am not the original author. But it seems hard to track down this particular Nidhi Shah... Could referencing the article be enough to give credit perhaps. In any case I don't know MS guidelines for such a situation.
