### ISSUE TITLE
Incoherent paragraph format 

### ISSUE THREAD

**Issue by RicardoSilveira23** [MicrosoftDocs/OfficeDocs-SharePoint#31]
Documentation page: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-a-site-collection.md

In this page after the bullet list, the first paragraph is wrongly formatted in comparison to the others in the same page.  
<pre> **Content databases upgrade**-
  
To upgrade the databases run the ...</pre>

![error](https://user-images.githubusercontent.com/24255374/38943271-e2848bb2-4328-11e8-9824-0fde5404d7a6.PNG)

**Comment by Techwriter40** [comment]
can you be more specific on what exactly needs to be changed? I am not seeing anything wrong with that sentence.  thanks .

**Comment by RicardoSilveira23** [comment]
Surely, well at least in my view, all the text should follow the same logic, that is, on the same page you find what I believe to be the correct way:
![correct](https://user-images.githubusercontent.com/24255374/39006734-edc58822-43fb-11e8-876a-2ef418b91c5b.PNG)

And on this one the you have this:
![incorrect](https://user-images.githubusercontent.com/24255374/39006754-fd287572-43fb-11e8-8523-2f2d6fb6a74a.PNG)

Caused by what I believe to be an unintended break line, showcase on my first comment retrieved from the raw markdown file.

**Comment by Techwriter40** [comment]
I have made a change and republished, let me know if this is correct or any other changes needed. ty for your comment.
