### ISSUE TITLE
SharePoint Server 2016 zero downtime patching steps - readability

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-SharePoint#310]
Some sections of the current documentation are hard to read. Steps, that should be executed one after another are placed in one line with an arrow in between. This is confusing and blocks copy+paste.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ccb7df-8dca-b5fc-4e84-e3624d2804cc
* Version Independent ID: 669daf62-d97c-3489-786b-6924c1e755b0
* Content: [SharePoint Server 2016 zero downtime patching steps](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@andikrueger Thank you for this feedback

Techwriter40 approved your changes and I merged the pull request for you. We appricate you making this article easier to read.
