### ISSUE TITLE
Deploy OneDrive apps by using Intune doesn't have instructions on installing OneDrive with Intune on Windows 10

### ISSUE THREAD

**Issue by elliotnycruns** [MicrosoftDocs/OfficeDocs-SharePoint#3100]
The section "Deploy the OneDrive sync app to Windows 10 devices" doesn't mention actually using Intune for the Deployment.
All the files there are provide on the site are .exe, and Intune won't support that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-intune)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by get-itips** [comment]
Hello @elliotnycruns I am looking into this.

**Comment by get-itips** [comment]
Hello @elliotnycruns 
Found this

> OneDrive is automatically installed when you install Microsoft 365 Apps or install individual applications, such as Word, Excel, PowerPoint, Publisher, Visio, or Skype

[source ](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options)

I am trying to confirm if that is the current method and if the article needs an update.

Thank you

**Comment by elliotnycruns** [comment]
Hey Andres,

Microsoft makes the suggestion that you switch from the default install (per user) to the per machine.

But nothing about per machine installation by using Intune.
Does that make sense?


Deploy OneDrive apps using Intune - OneDrive | Microsoft Docs<https://docs.microsoft.com/en-us/onedrive/deploy-intune>
Although the sync app comes with Windows 10, you might choose to switch to per-machine installation<https://docs.microsoft.com/en-us/onedrive/per-machine-installation>.


Install the sync app per machine - OneDrive | Microsoft Docs<https://docs.microsoft.com/en-us/onedrive/per-machine-installation>

Deployment instructions
1.     Download OneDriveSetup.exe.
2.     Run "OneDriveSetup.exe /allusers" from a command prompt window (will result in a UAC prompt) or by using Microsoft Endpoint Configuration Manager. This will install the sync app under the "Program Files (x86)\Microsoft OneDrive" directory. When setup completes, OneDrive will start. If accounts were added on the computer, they'll be migrated automatically.



But no

Elliot Inz
Senior Event Manager
New York City Runs<http://www.nycruns.com/>
NYCRUNS Brooklyn Marathon & Half Marathon<http://www.thebrooklynmarathon.com/>
[NYCRUNS_WinYourRace_MAIN]

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
