### ISSUE TITLE
Restore Deleted Site Does Not Move to Active

### ISSUE THREAD

**Issue by nicholasdmburgess** [MicrosoftDocs/OfficeDocs-SharePoint#3101]
Hi. Based on this article, I utilised the restore function.

![image](https://user-images.githubusercontent.com/96858536/147725349-d4f088d2-1adf-4954-93fb-de3a435b611c.png)

The Deleted sites screen then updated like this

![image](https://user-images.githubusercontent.com/96858536/147725382-4088da66-d52f-4571-97ea-40ab1bd4db6e.png)

I selected the Refresh button

![image](https://user-images.githubusercontent.com/96858536/147725399-71e9957a-8208-4534-8c78-968d71e8e92e.png)

But then when I go back to Deleted sites, the site hasn't been restored and/or moved to Active?

![image](https://user-images.githubusercontent.com/96858536/147725445-ff592c0d-ba67-49ba-87d3-7a562affc23f.png)

Does it take some time to move to Active?

**Comment by get-itips** [comment]
Hello @nicholasdmburgess how are you?
I tested this, the restored site was back in the active sites list and was removed from Deleted sites list. I could not reproduce what you experienced.
Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
