### ISSUE TITLE
How hub to hub associations work

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SharePoint#3102]
I have configured the Hub to Hub association for 12 weeks now, but the search results still do not show breadcrumb as described in your chapter. The Hub to Hub association for the Hubs are fine. If I open the top Hub site the sub Hubs are listed as associated Hubs. 
I assume that when searching for a document stored in a child hub site, the breadcrumbs should list the hub associations. But nothing has changed, no breadcrumbs. I see this behavior also in other tenants and have no explanation why the Hub to Hub association is not visible in search results. Is this Hub to Hub search breadcrumb limited to Pages, Documents,... results? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/hub-to-hub-association)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
