### ISSUE TITLE
Broken links on page

### ISSUE THREAD

**Issue by Curtica** [MicrosoftDocs/OfficeDocs-SharePoint#3107]
In the "Roles and tasks at-a-glance" section, the links for **intranet lifecycle** and **building blocks** are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aade0ae3-162e-c946-bb76-58d8aab252af
* Version Independent ID: f22dc636-f039-8be8-e524-ce146739a1d7
* Content: [Intelligent intranet roles and tasks - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/intranet-roles-tasks)
* Content Source: [SharePoint/SharePointOnline/intranet-roles-tasks.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/intranet-roles-tasks.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @Curtica thanks for your feedback!, fixing.
