### ISSUE TITLE
Suggested addition in text

### ISSUE THREAD

**Issue by TopNotch115** [MicrosoftDocs/OfficeDocs-SharePoint#3108]
For bulk tasks using a .csv. If you're migrating files to a user's OneDrive Document folder, you can just specify the email address and not have to formulate the OneDrive / Sharepoint link. Much simpler, and easy. I'm suggesting to let the readers know by adding that bit of information so they don't have to test it out before trying. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [Bulk upload tasks into Migration Manager using a CSV or JSON file - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @TopNotch115 Nicholas,

That is already described in the Column D's description 

>Column D: Enter the SharePoint site URL or OneDrive **email**/URL

Thanks for your feedback,

**Comment by get-itips** [comment]
@scanum
