### ISSUE TITLE
Incorrect Information | KFM & WFRG Policy | Section 3 / ... and will merge. 

### ISSUE THREAD

**Issue by enigmanet** [MicrosoftDocs/OfficeDocs-SharePoint#3109]
The documentation needs to be changed, we have multiple clients and we can repro the issue every time.

Statement: Enable KFM Group Policy. Known folders move to OneDrive and **will merge** with the **existing** Desktop, Documents, and Pictures folders, which contain all the file share content that you moved in the first step.

- That is incorrect and the way OneDrive Sync Client and Windows API works it 

Scenario: If we gather user's documents from a share, or their own desktop and documents, use either Migration agent or SPMT to migrate data, and later user connects for the first time to their OneDrive with sync client, with Silent Login, KFM takes places and KFM changes path to %userprofile%\OneDrive - Tenant\Desktop \ Docs etc, will create duplicate files/folders.  There is no merging whatsoever as the paragraph states. 

The only fix or work-around is to:  Once the data has been migrated to the cloud, making sure that the data doesn't exist on device and let it sync down from the cloud.

What we are getting here is the - Copy, - Copy 1, - Copy 2, we know this is standard Windows functionality, so when KFM kicks in all it's doing is a drag and drop from existing desktop folder, into the folder that's in OD.  OD doesn't do any syncing, merging between desktop and the cloud.   It's a Windows file move operation and if there is a conflict in there and because it is being done silently it ads a - Copy at the end of the File/Folder. 

So if you already have the files in the OneDrive you will not want them in your default known folder, because that's when the duplication will occur. 

Please reach out for further details if needed.

**Comment by MikePlumleyMSFT** [comment]
@adeejoseph @cartergreen fyi

[Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/onedrive/redirect-known-folders)
