### ISSUE TITLE
What to do with the not supported databases?

### ISSUE THREAD

**Issue by tbebekis** [MicrosoftDocs/OfficeDocs-SharePoint#311]
I have a SP 2016 Farm in 3 subnets, in 3 cities, in 2 continents, Europe and America. In each subnet there is
- a Web Server (role: Front-end and Distributed cache),
- an App Server (role: Application with search)
- and a DB Server (MsSql 2017 Enterprise)

Obviously we cannot use Sync mode. Moreover the document says: "_Some SharePoint Server databases do not support SQL Server Always On Availability Groups._ " 

**Questions**
1.  What we have to do with the not supported databases?
2. Is there a proper way of mirroring/replicating those not supported databases, in my secondary DB Server cluster nodes?
3. Since our main concern is an internet connection outage of one of the 3 spots, what databases we need present in each sort in order to have a functional read-only, cut off, farm?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae7dce3-cff3-7417-c77a-1cb9cc8ddaad
* Version Independent ID: d16ebb8f-67f4-c49b-b5d5-54a24ea2633e
* Content: [Configure SQL Server AlwaysOn Availability Groups for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-an-alwayson-availability-group)
* Content Source: [SharePoint/SharePointServer/administration/configure-an-alwayson-availability-group.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-an-alwayson-availability-group.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tbebekis** [comment]
No. I have just a single SP2016 Farm which spans in 3 subnets

**Comment by tseward** [comment]
Remember that the maximum distance in a vacuum for a SharePoint farm to be separated is roughly 300km. If your farm exceeds that distance, you're in an unsupported state (and due to physics, you won't be able to get close to that distance). SharePoint farms require 1Gbps connectivity and 1ms response time between servers (SharePoint -> SharePoint and SharePoint -> SQL). More info here:

https://docs.microsoft.com/en-us/SharePoint/administration/plan-for-high-availability#configure-two-data-centers-as-a-single-farm-stretched-farm-to-provide-high-availability

Do you meet those requirements?

**Comment by tbebekis** [comment]
No. Is there any other solution?

**Comment by tseward** [comment]
Negative. You need to instead bring your farm into a supported state per the article. At that point, you can stand up DR farm(s) in remote locations. All of your users, worldwide, will only use the active farm. Only during a DR event will you failover to a remote farm that your users will begin using.

DR is a rather complex topic and not suited to GitHub. I'd suggest opening a thread on TechNet.

**Comment by tbebekis** [comment]
There is a peculiarity. On one of the three points (subnets) the internet connection is often cut off. Is there any thought about how this could be addressed?

**Comment by tseward** [comment]
Again, I'd suggest starting a topic on TechNet.

https://social.technet.microsoft.com/Forums/sharepoint/en-US/home?forum=SP2016

**Comment by AndreaBarr** [comment]
@tbebekis thank you for this feedback

It looks like Trevor has answered your question. I am going to close this as resolved. If this doesn't answer your question then please re-open this issue.
