### ISSUE TITLE
View SharePoint files with File Explorer in Microsoft Edge on RDS

### ISSUE THREAD

**Issue by rvdwijst** [MicrosoftDocs/OfficeDocs-SharePoint#3112]
https://docs.microsoft.com/en-us/SharePoint/sharepoint-view-in-edge

Will this work in user session on a Server 2019 RDS environment?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rvdwijst** [comment]
Hi Scanum,

I`ve made some headway with this. Apparently you need WebDAV Redirector to be installed on Server 2019 for this to work.
I think this might be helpfull info for future visitors.

I couldn`t find the correct link for Server 2019. This is the link for Server 2008/2012:
https://docs.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector

On Server 2019 you can install and start automatically with following Powershell commands:
Install-WindowsFeature WebDAV-Redirector –Restart
Set-Service WebClient -StartupType Automatic
Start-Service WebClient

Thank you for taking the time to reply to me.
