### ISSUE TITLE
Does not describe how to change link sharing to "Only people with existing access"

### ISSUE THREAD

**Issue by SPDEVGUY** [MicrosoftDocs/OfficeDocs-SharePoint#3115]
The page does not tell the admin how to change the default setting at the organizational level to prevent permission-granting links from being shared.  The "People with existing access" link option which is available when setting the option at the site level doesn't seem to be available at the tenant level..

![image](https://user-images.githubusercontent.com/3208188/149569374-ad502a88-80fc-4b1a-974a-eab451373c45.png)

Example of option on the site level, that we want to set as the default for all sites:
![image](https://user-images.githubusercontent.com/3208188/149569431-34bb8848-fbad-41a5-bc7f-6c905da3368c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Manage sharing settings - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off#file-and-folder-links)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @SPDEVGUY Kevin, how are you?

The property you are looking for is `defaultLinkToExistingAccess`, this property only exists at Site level currently, that's the reason you do not have the option at tenant level in the Admin center for SharePoint.

You could set this property for all sites using PowerShell.

Hope this information helps you!

**Comment by get-itips** [comment]
@scanum
