### ISSUE TITLE
Missing Details on User Experience

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#3116]
OneNote is one of the most challenging aspects of migrating to OneDrive. This page could use some details on what the experience for the user is going to be and the additional actions that they need to take.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fff09a1-5bc3-a9ea-ace0-5f3e865efbe2
* Version Independent ID: 08a51327-644d-9099-efb2-b2d7523b2e1b
* Content: [Migrating OneNote folders with the SharePoint Migration Tool (SPMT) - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/migrate-onenote-spmt)
* Content Source: [migration/migrate-onenote-spmt.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/migrate-onenote-spmt.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by danmyhre** [comment]
Yes, users need to disconnect their notebook(s) from the OneNote desktop app and then reconnect from its new home in OneDrive.

**Comment by get-itips** [comment]
> Yes, users need to disconnect their notebook(s) from the OneNote desktop app and then reconnect from its new home in OneDrive.

Thanks for clarifying, I'll propose adding a reference to that in this article, if it gets approval, it will be in the published version of the article.
