### ISSUE TITLE
Firewall rules are incomplete

### ISSUE THREAD

**Issue by vojinle** [MicrosoftDocs/OfficeDocs-SharePoint#3118]
https://login.windows.net is one of login redirections and it is not listed as required firewall rule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b383a083-49a6-72b8-46f4-954c96192353
* Version Independent ID: 35ab28d5-eddf-181b-c13b-bd7d20164b90
* Content: [Migration Manager Prerequisites and Endpoints - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-prerequisites)
* Content Source: [migration/mm-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-prerequisites.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
thanks for your feedback!
