### ISSUE TITLE
The link to Information Barrier Modes is a bad link

### ISSUE THREAD

**Issue by Mike-Barrett** [MicrosoftDocs/OfficeDocs-SharePoint#3119]
The link to Information Barrier Modes is a bad link:
https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies.md#step-6-information-barriers-modes

The above is giving a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a21b65-b5cb-b777-842f-c5d6ac78dd31
* Version Independent ID: 88cb0db2-f421-cf77-8926-9290db598d1a
* Content: [Use information barriers with SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/information-barriers?source=docs)
* Content Source: [SharePoint/SharePointOnline/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/information-barriers.md)
* Service: **sharepoint-online**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@Mike-Barrett - thanks for the feedback, this link has been fixed and should render correctly in 10-15 minutes.
