### ISSUE TITLE
Clarification points and more detail around some of the concepts for MarkNewFilesSensitiveByDefault 

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#3120]
Hi, 

I have a lot of questions around this which i think would be very useful to expand / clarify the text on.

Q1. If you do not create a DLP policy, setting this tenant wide setting will this block all files from being shared from OneDrive or SharePoint? 

Q2. How long does the setting Set-SPOTenant -MarkNewFilesSensitiveByDefault take to activate and rollback?  I have read 15mins.

Q3. Importantly, How do you know it is actually working, as expected, or can test it? If the DLP policy runs quick enough it may not even be able to be shared in the first place, so is there any Audit logging / reporting on guest users trying to get access but showing as blocked as the scan has not run? And this is different from a standard DLP block? I think this is important as MS roll out changes, things may break and if there is no way of testing it in a consistent manner how do we know its working.

Q4. Will guest users get a message immediately clicking the shareable link in email or after entering their one time pass code?

Q5. You say to create a new DLP policy "includes all locations" do you mean create a new DLP Policy that includes just sharepoint and OneDrive locations i.e. places that store files? For example i assume you dont need to include exchange. Also when you say has "any" content contains, I assume you mean absolutely any condition, so this could be anything like a rando, word/ label,it just has to scan each file in a location… period... As the DLP screen wants you to specify at least one content contains clause, you cannot leave it blank

Q6. For the new policy you recommend to cover "all locations" but take not action, is the recommendation that it should be the very last DLP policy / rule in your DLP Policy list orderng? For example if it were first then as soon as its processed it, you could share it. You would think it would need to check all the remaining DLP rules for sensitivity labels, sensitive information types and then finally do the DLP policy that allows access.

Q7. I would be worth explaining / showing the user experience for the receiving guest user, i.e. if the file has not yet been scanned what they can expect and how long they can be expected to wait, can this be sped up in anyway, does the end user have to keep trying and trying? What is a typical time range

Q8. I am struggling to get my head round the explanation text and context of the text in the important box
"Any content not in the scope of DLP policies would not be blocked for external access"

You have just said create a DLP policy that scans all locations and then you say important, Any content not in the scope of DLP policies would not be blocked for external access". I think this could be worded to remove the double negative and perhaps a few examples.

Q9. If a user tries to access a file and they get the message "This file is being scanned right now. Please try again in a few minutes" does this in anyway influence a job in the background to prioritise this file or does the DLP scanner just work independently.

Apologies if I have misunderstood key concepts here, happy to discuss further

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Mark new files as sensitive by default - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @obhayes I am looking into this

**Comment by obhayes** [comment]
HI @MikePlumleyMSFT Can you provide a justification why this is closed rather than just closing it? I believe there is an additional open issue 3125 against this same article, which is also requiring further clarification, that is 2 in a week. For something as high profile as Data loss prevention i think this article could do with further detail. regards.

**Comment by get-itips** [comment]
> HI @MikePlumleyMSFT Can you provide a justification why this is closed rather than just closing it? I believe there is an additional open issue 3125 against this same article, which is also requiring further clarification, that is 2 in a week. For something as high profile as Data loss prevention i think this article could do with further detail. regards.

@obhayes a PR improving the article, based on your feedback, was merged, and as it is linked to this issue, it is closed, I am also getting more info from the team that I'll paste here for you

**Comment by obhayes** [comment]
@get-itips many thanks for this, is very useful. Thank you. Id also love to see the responses to issue 3125 once that gets adressed.
