### ISSUE TITLE
Timeline needs to be updated.

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SharePoint#3123]
The timeline has shifted a couple times since this was updated. According to today's message center post update, the preview is done and general availability will happen mid-February through mid-March, 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd05a015-115f-0e1d-e607-64a0c08a77a1
* Version Independent ID: 6ac538e0-2010-34db-7b06-d31272bfae28
* Content: [Data access governance reports - SharePoint in Microsoft 365](https://review.docs.microsoft.com/en-us/SharePoint/data-access-governance-reports)
* Content Source: [SharePoint/SharePointOnline/data-access-governance-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/data-access-governance-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by get-itips** [comment]
Thanks for your feedback!
