### ISSUE TITLE
MarkNewFilesSensitiveByDefault on Brand New SPO Files

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/OfficeDocs-SharePoint#3125]
I have a request for some clarification on this document.

MarkNewFilesSensitiveByDefault applies to any newly-uploaded files within SPO/ODB, prior to being scanned by DLP. However, what about any Newly-Created files (i.e. New DOCX/XLSX/PPTX) via the SPO/ODB Interfaces? 

- Are these exempt from MarkNewFilesSensitiveByDefault? 
- Is DLP Scanning against brand new files (with no data) so quick that there is no immediate need for MarkNewFilesSensitiveByDefault?
- Is there any order in which this process occurs for brand new files? i.e. File Created > DLP Scanning > Sharable _OR_ File Created > MarkNewFileSensitiveByDefault > DLP Scanning > Sharable?

Looking forward to any clarity that can be brought to this type of example, as it has come up in testing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Mark new files as sensitive by default - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by obhayes** [comment]
@SeanTGeoghegan i have logged similar questions prior to your one against this MS article, please take a look. You raise some great questions. I have also posted in the Information protection forum, i was testing with files created in the via the SP/OD4B and could not get this to trigger which was a concern
https://www.yammer.com/askipteam/#/threads/show?threadId=1570794645815296

**Comment by SeanTGeoghegan** [comment]
I have confirmed that MarkNewFilesSensitiveByDefault _does_ apply to newly-created files, however DLP scans them far too quickly to get results. This type of scenario may be helpful to point out in a note.

**Comment by get-itips** [comment]
Hello @SeanTGeoghegan 
Please have a look at https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3120
Does that help answering your question?
Thank you

**Comment by SeanTGeoghegan** [comment]
@get-itips 

Thanks for the response - my questions seem to be answered with that update that was made. Thank you very much!
