### ISSUE TITLE
Exchange account seems needed for the sharing recipient to use OneDrive B2B Sync functionality

### ISSUE THREAD

**Issue by motla** [MicrosoftDocs/OfficeDocs-SharePoint#3126]
Hello,

We struggled to make OneDrive B2B Sync work, because it seems that **the sharing recipient account must be an Exchange account**.
The use case is : when you create a tenant, you can link the DNS of the website of your company to get e-mail adresses with your domain name. But you can also choose not to configure Exchange and let another provider take care of the e-mail hosting. In this particular case, it seems B2B Sync is not working and you get the famous message:

![image](https://user-images.githubusercontent.com/16179413/150595939-46ac328f-85a1-4b00-9c98-8811996d5885.png)

with no error code or no explanation whatsoever. So it is quite annoying to find where it is coming from.

Could you check that it was really the cause and if it is, add it as a requirement to the B2B Sync documentation?
And maybe also update OneDrive so that it is more verbose when these kind of errors happen?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync - OneDrive](https://docs.microsoft.com/en-us/onedrive/b2b-sync)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by BillSproule** [comment]
@motla feel free to reach out to me via email. I can look at your logs and determine what's going on.

The typical failures are not sharing the content document library or folder to an AAD user account, not having external sharing properly enabled in the resource (content owning) tenant, or a conditional access (CA) requirement in the resource tenant which B2B sync does not yet support.

Bill

**Comment by motla** [comment]
@BillSproule That is nice from you but I won't bother my client again with all this, now that the configuration works 🙂

What I'm sure is the issue was on the recipient side (me). I had my address ***@motla.design that had a 365 work license enabled, no MFA, and wouldn't work without knowing why. We tried everything in AD and Office admin of the tenant and the recipient. It took us several weeks. I finally had to get rid of this address and create a ***@***.onmicrosoft.com, so with no domain name, and under Exchange, and then it worked.

If the typical failures are known, you could inform the user of the cause of the error directly on OneDrive interface, that will avoid a lot of frustration and your users will have a much better UX. Typically the "try again later" error is very confusing for users. It has no reason to appear other than temporary server maintenance, yet it appeared all the time.
Of course telling me precisely what's wrong with my account and what is the required action would have been great.
But in the case of an unknown error, at least give us something to investigate like an error code or a log snippet. There must be something to show other than "please try again", which is not helpful.

If you are sure that non-Exchange recipient accounts can work with B2B, then it was probably another cause. Given the complexity of your infrastructure, there are always edge/unknown errors, just inform the user would be my only request.

Thanks for reaching to this issue.

**Comment by BillSproule** [comment]
Thank you for the feedback Romain.  We will continue to work to improve the product’s failure messaging and make it easier to diagnose problems. I appreciate you taking the time to reach out.

If its been within 30 days of the problem occurring, its possible if you reach out to me privately via email (see my github profile) I could pull logs for your machine’s sync interaction to understand more details. This could be helpful in improving the error messaging you were shown.  I would need the approximate date of the problem as well as either your OneDrive device ID (see the OneDrive settings dialog, about tab) or your email address you were signed into OneDrive sync client with at the time of the problem.

Thank you for using OneDrive.
Bill
