### ISSUE TITLE
Link to "Intranet lifecycle" is broken

### ISSUE THREAD

**Issue by hekessel** [MicrosoftDocs/OfficeDocs-SharePoint#3127]
[Enter feedback here]
Link to Intranet lifecycle is broken: [https://raw.githubusercontent.com/MicrosoftDocs/OfficeDocs-SharePoint/live/SharePoint/SharePointOnline/spodownloads/Intranet%20lifecycle.pdf](url)

guessing it should be this one?: [https://raw.githubusercontent.com/MicrosoftDocs/OfficeDocs-SharePoint/public/SharePoint/SharePointOnline/spodownloads/Intranet%20lifecycle.pdf](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab8a948-7330-5238-1c04-4a95db4cda5d
* Version Independent ID: 4597b4bb-3cc6-99b2-ca68-2006cb7c73a5
* Content: [Intelligent intranet overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/intelligent-internet-overview)
* Content Source: [SharePoint/SharePointOnline/intelligent-internet-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/intelligent-internet-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by get-itips** [comment]
Link was fixed
