### ISSUE TITLE
Update information about OTP with OneDrive/SharePoint integration

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SharePoint#3129]
[Hello, from my understanding when reading this information it isn't made clear that the following will happen with EOTP and AAD B2B integration for SharePoint & OneDrive enabled.

**Scenario:** A tenant has enabled Azure AD B2B integration for SharePoint & OneDrive and consequently the EOTP feature. When sharing a secure link from SharePoint to an anonymous account (such as Gmail) with no association to the sending organization and not configured as identity provider it is true that a OTP will be sent to the Gmail account - BUT - after entering the code the "join sending tenant prompt" will appear. When accepting as the Gmail user a guest account in the host tenant will be created automatically, and at the same time the user will access the shared item.

*edit* Accidently stumbled across this again. It's true that a guest account is created as per above, but when sharing continues it happens with a OTP.

Perhaps use this info here too? https://docs.microsoft.com/en-us/azure/active-directory/external-identities/one-time-passcode#when-does-a-guest-user-get-a-one-time-passcode

Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration#enabling-the-integration.%5D)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ChristianJBergstrom 
I tested this on a newly created demo tenant.
Enabled EOTP and B2B integration, and then, send a sharing link to a document from SharePoint to a Gmail address.
Only the OTP was used to log-in and no user was created in AAD.

Please let me know if I understood correctly your inquiry,

Thanks

**Comment by ChristianJBergstrom** [comment]
Hello @get-itips Was this Gmail address you used a new address? Are you certain it wasn't already added to your organization as a guest user and also not having any Google Identity provider configured?

**Comment by get-itips** [comment]
@ChristianJBergstrom Yes, brand new tenant, the gmail address was never used with this tenant at all. Default identity providers.

**Comment by ChristianJBergstrom** [comment]
So you ran these @get-itips 
Set-SPOTenant -EnableAzureADB2BIntegration $true
Set-SPOTenant -SyncAadB2BManagementPolicy $true

and

Verified this:
![image](https://user-images.githubusercontent.com/90273807/151426575-5648f990-0acb-4f22-9ba5-5721a79005a5.png)

And still you didn't get added to your sharing tenant as a guest user after typing the OTP?

**Comment by get-itips** [comment]
Yes. Exactly.

**Comment by ChristianJBergstrom** [comment]
@get-itips So how long ago did you enable the integration? I just now created a brand new Gmail account and shared a file from SharePoint. Same behavior as already mentioned.

![1](https://user-images.githubusercontent.com/90273807/151428109-15880d71-6e4f-481b-9942-f15b21a1818f.PNG)
![2](https://user-images.githubusercontent.com/90273807/151428125-ee699e6e-8315-498f-bf62-76571150b6a9.PNG)
![3](https://user-images.githubusercontent.com/90273807/151428133-4877d589-1fdb-45de-9f68-f1f0700b7585.PNG)
![4](https://user-images.githubusercontent.com/90273807/151428138-1588d268-c9a2-46bd-b3de-264e4bc57d1b.PNG)
![5](https://user-images.githubusercontent.com/90273807/151428149-bea5ff9f-0473-41d3-8323-42e501bc305b.PNG)
![6](https://user-images.githubusercontent.com/90273807/151428159-ef9d0de0-10d2-4ea7-b625-590ed329f19e.PNG)

**Comment by ChristianJBergstrom** [comment]
@get-itips Perhaps this is the reason for the inconsistent behavior between us?

"Updated January 25, 2022: Based on learnings from our early rings, we have made the decision to make additional changes before we proceed with the rollout. We will deliver a new Message center post once we re-start the rollout. The preview can still be enabled following the link instructions in the link below. Thank you for your patience."

**Comment by get-itips** [comment]
@ChristianJBergstrom It could be, I guess we would need to test again soon

**Comment by ChristianJBergstrom** [comment]
@get-itips I got a reply from Stephen Rice, so adding it below. I also replied with a couple of follow-up questions I had. Will update here if I get an answer on them too.

"If Azure B2B integration with SPO is enabled, then the behavior you are describing is expected. Once the guest account is created in the host tenant, administrators can then apply policy or require the user to have a password, if desired. If the recipient is an O365 account, they will just use their existing credentials."

So, the previous dumps are describing what is supposed to happen.

**Comment by ChristianJBergstrom** [comment]
@get-itips Just wanted to let you know I set up a new tenant and tried it out from scratch, it works as above here too (entering code is followed by the "join tenant prompt" and an added guest account). This with a personal Gmail account without any association to the resource org.

In contrast when sharing with a personal Microsoft account it's seamless as you're simply accepting the "join tenant prompt".

**Comment by get-itips** [comment]
@ChristianJBergstrom I now experienced similar, so I'll ask to confirm behavior.

**Comment by get-itips** [comment]
@ChristianJBergstrom What I did have is the option to cancel the login using regular credentials and receive the one-time passcode, did that happen to you?

**Comment by get-itips** [comment]
so in that case, i think that is covered by the following sentence 

>Azure B2B Invitation Manager one-time passcode feature allows users who don't have existing Work or School accounts or Microsoft Accounts **to not have to create accounts to authenticate, but can instead use the one time passcode to verify their identity.**

**Comment by ChristianJBergstrom** [comment]
> @ChristianJBergstrom What I did have is the option to cancel the login using regular credentials and receive the one-time passcode, did that happen to you?

No. When the integration is enabled and I click on the link as an "anonymous" user (gmail.com) I get the "send a code", after entering that in the next prompt I'm asked to accept the host org. terms (join tenant prompt), if not accepting that, I do not get access and I am not presented with any other option.

**Comment by ChristianJBergstrom** [comment]
> so in that case, i think that is covered by the following sentence
> 
> > Azure B2B Invitation Manager one-time passcode feature allows users who don't have existing Work or School accounts or Microsoft Accounts **to not have to create accounts to authenticate, but can instead use the one time passcode to verify their identity.**

To be honest I think that sentence sounds like AAD EOTP in general.

**Comment by ChristianJBergstrom** [comment]
@StephenRiceMSFT Would you mind stepping in and/or tag additional people?

**Comment by get-itips** [comment]
> > @ChristianJBergstrom What I did have is the option to cancel the login using regular credentials and receive the one-time passcode, did that happen to you?
> 
> No. When the integration is enabled and I click on the link as an "anonymous" user (gmail.com) I get the "send a code", after entering that in the next prompt I'm asked to accept the host org. terms (join tenant prompt), if not accepting that, I do not get access and I am not presented with any other option.

Ok so we have a slight difference, the behavior I am seeing, I think, is more aligned to what the article is currently stating.
Will make further tests.

**Comment by ChristianJBergstrom** [comment]
> > > @ChristianJBergstrom What I did have is the option to cancel the login using regular credentials and receive the one-time passcode, did that happen to you?
> > 
> > 
> > No. When the integration is enabled and I click on the link as an "anonymous" user (gmail.com) I get the "send a code", after entering that in the next prompt I'm asked to accept the host org. terms (join tenant prompt), if not accepting that, I do not get access and I am not presented with any other option.
> 
> Ok so we have a slight difference, the behavior I am seeing, I think, is more aligned to what the article is currently stating. Will make further tests.

Would you mind sharing a step-by-step so I can see it?

**Comment by ChristianJBergstrom** [comment]
Hello @get-itips I am adding here so it can be tracked. Just very brief comments from me now. What I feel is missing or should be worked on in this article is that EOTP is one thing, and the OD/SP integration another. So perhaps separate those features or explain that they work/how they work together because, when I'm reading at least, it's now a mix of both and kind of makes it confusing.

Also it's mentioned in the "Note" purple box that _"When the integration is enabled, people outside the organization will be invited via the Azure B2B platform when sharing from SharePoint. **If** the Azure B2B One Time Passcode option is enabled..._

**If** should be _when_ as you cannot use the integration without EOTP.

And as how I started the very first comment, one don't really get that everyone will get a guest account created automatically after verifying with the EOTP when the integration is enabled. And keep using that when not having a Microsoft identity and having identity issuer to mail.

![image](https://user-images.githubusercontent.com/90273807/155299825-2aabd1aa-f9a4-441d-96fd-2306ecb9eb96.png)

Thank you

**Comment by get-itips** [comment]
Hello @ChristianJBergstrom I've been reading and re-reading this and the article and these are my conclusions

Is it clear that an account will be created in the tenant? To my understanding, YES ->

> Invited people outside your organization **are each given an account in the directory and are subject to Azure AD access policies** such as multi-factor authentication.

Is it clear if OTP or a sign-in experience with accounts will be used? Here we have the information about that

> Any sharing to new people outside the organizaton may result in **either Azure AD-backed accounts** or **SharePoint-only email auth guests that use a SharePoint One Time Passcode** experience to sign in.

I think that is the paragraph that could be improved to made it more clear.

**Comment by ChristianJBergstrom** [comment]
Hello, I’ve added my two cents. You can do as you like with the article 😊
