### ISSUE TITLE
Unable to save changes in Ondrive Admin center

### ISSUE THREAD

**Issue by samikroy** [MicrosoftDocs/OfficeDocs-SharePoint#313]
External Sharing needs to turned on for SPO but not for One drive, hence tried to change referring this article 
[https://docs.microsoft.com/en-us/onedrive/manage-sharing](url)

While saving getting below error.

<img width="948" alt="err" src="https://user-images.githubusercontent.com/20562985/46799987-f5964800-cd73-11e8-835d-baf238aa5f85.PNG">

Please share any alternative approach available like PowerShell to apply the same settings.

**Comment by AndreaBarr** [comment]
@samikroy Thank you for this feedback

I am not sure why you are getting this error. I want to get you over to Support for this. They have more resources then we do here to dig in and help figure out what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by samikroy** [comment]
This issue persisted only in developer tenant, worked fine in test environment.

**Comment by AndreaBarr** [comment]
@samikroy okay. I still stand with having you open a support ticket so we can document what was happening.
