### ISSUE TITLE
ADFS Update

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-SharePoint#3134]
Minor note ADFS  should be AD FS - note the space.

Can that be updated please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app - OneDrive](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by adeejoseph** [comment]
Hi @r-milne, great catch! Thanks so much for making us aware of this. I've updated the article, just waiting for the changes to be reviewed and merged. This issue will close automatically when the merge occurs. Have a great week!
