### ISSUE TITLE
fantastic Microsoft advertising e-mail

### ISSUE THREAD

**Issue by alessio-businaro** [MicrosoftDocs/OfficeDocs-SharePoint#3138]
I think an important note is missing, any time after creating a group on SharePoint, Microsoft send to all people of this group a fantastic advertising e-mail to congratulate with all this people for buying a 365 lincenses, no matter if in this group you have thousands of users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e8d0f1-f6a3-82c0-e46b-974e167fe5b1
* Version Independent ID: 22b0a6c2-2e90-34ab-c3c8-bd7ba721c791
* Content: [Customize SharePoint site permissions - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions?source=docs#feedback)
* Content Source: [SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @alessio-businaro 
I am trying to reproduce this, but I am only getting the "[user] is inviting you to collaborate on [group]" e-mail
Can yo detail the exact steps taken?
Thank you

**Comment by get-itips** [comment]
@alessio-businaro Could you see my comment here? Thanks

**Comment by alessio-businaro** [comment]
Hi @get-itips thanks for your answer, sorry for my bad english.
I have created a AzureAD Dynamic groups with a Rules expression
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-dynamic-membership

and several minutes after, when AzureAD have completed the Rules expression and created the group with thousands of users Microsoft sent to all users of this dynamic group a beautifull mail, i think Microsoft call that mail "Welcome mail", in the footer of this mail you can read something like "we want to congratulate you.... thank to have buy Microsoft 365...".

unfortunately for me that dynamic group included CEO, Manager, VIP users, my boss...thousands of users, it was not nice.

https://techcommunity.microsoft.com/t5/microsoft-365-groups/how-to-remove-the-welcome-message-when-a-new-member-joins-a/m-p/56573

**Comment by get-itips** [comment]
@alessio-businaro Hello Alessio,
I am afraid that I could not reproduce that. If you can share the subject I might be able to confirm is not an SPO email.
Thank you

**Comment by get-itips** [comment]
@alessio-businaro How are you? Checking to understand if you could see my last comment, thanks
