### ISSUE TITLE
Microsoft.SharePointOnline.CSOM Install issue

### ISSUE THREAD

**Issue by brpowershell** [MicrosoftDocs/OfficeDocs-SharePoint#314]
PS C:\> Install-Package Microsoft.SharePointOnline.CSOM -RequiredVersion 16.1.8119.1200
Install-Package : No match was found for the specified search criteria and package name
'Microsoft.SharePointOnline.CSOM'. Try Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Install-Package Microsoft.SharePointOnline.CSOM -RequiredVersion 16.1 ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by AndreaBarr** [comment]
@brpowershell Thank you for this feedback

I want to make sure this error you are getting is properly addressed. I want to get you over to Support. They have more resources then we do here to dig in and see what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
