### ISSUE TITLE
Users must have read access to SharePoint root site

### ISSUE THREAD

**Issue by kovnojava** [MicrosoftDocs/OfficeDocs-SharePoint#3145]
The following requirement should be added to the **Note** section already present under the **Office templates** section:

* In order for the Office templates files to show up in Office products, the recipient of the templates must have at least read access on the tenant's SharePoint root site, e.g. https://tenantname.sharepoint.com.

We just found that out the hard way, after someone had removed user access to the root site during implementation of a new Intranet site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @kovnojava 
I am looking into this, thanks for  your feedback.

**Comment by get-itips** [comment]
Hello @kovnojava I could reproduce, I'll propose adding that information.
