### ISSUE TITLE
Permissions for managing navigation

### ISSUE THREAD

**Issue by tombraman** [MicrosoftDocs/OfficeDocs-SharePoint#3146]
This page doesn't indicate what permission levels are necessary to manage global and local permissions. What levels are required? Thank you. - tom braman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels?redirectSourcePath=%252fen-us%252farticle%252fUnderstanding-permission-levels-in-SharePoint-87ecbb0e-6550-491a-8826-c075e4859848)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @tombraman how are you?
Do you mean the permissions required to manage permissions?

Please see here https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions#customize-site-permissions

> To do the following steps, you need a permission level that includes permissions to Create Groups and Manage Permissions. The Full Control level has both.

Does this answers your question? Let me know if I understood you correctly.

Thank you

**Comment by get-itips** [comment]
@tombraman did you see my comment here? thank you

**Comment by tombraman** [comment]
Apologies for not responding sooner -- I was on vacation. My initial question was unclear, too -- double apologies. I meant to write that the page doesn't indicate what permission is necessary to manage global and local navigation. I have a customer who wants to grant that permission, but not via the Full Control permission level, which grants more permissions than the customer wants. Thank you for your persistence! - tom

**Comment by get-itips** [comment]
@tombraman Understood Tom

I think you have here the answer

https://support.microsoft.com/en-us/office/customize-the-navigation-on-your-sharepoint-site-3cd61ae7-a9ed-4e1e-bf6d-4655f0bf25ca?ui=es-es&rs=es-es&ad=es

You get that link from here https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience

**Comment by tombraman** [comment]
No, I'm not looking for information on how to customize navigation. Rather, I need to know what specific SharePoint permission (not permission level) allows users to customize or prevents users from customizing navigation. Thank you.

**Comment by get-itips** [comment]
> No, I'm not looking for information on how to customize navigation. Rather, I need to know what specific SharePoint permission (not permission level) allows users to customize or prevents users from customizing navigation. Thank you.

The site I referenced says:

> You need to be a site owner to make changes to the navigation of a site.

Is that the answer you are looking for? Thank you

**Comment by tombraman** [comment]
No. I think you may want to bubble this question up to somebody who understands SharePoint permissions. A Site Owner is simply a group to which permissions are applied. Full Control is a permission level often given to Site Owner groups. The Full Control permission level is comprised of various SharePoint permissions. I am trying to determine which of those permissions controls a user's ability to manage navigation. A person with expertise in SharePoint permissions would likely know the answer. Thank you.

**Comment by get-itips** [comment]
I understand SharePoint permissions and what you are looking for, however, what is documented is the role. which is site owner.

Will try to find out for you if the specific permission exists for site navigation.

Thank you!

**Comment by tseward** [comment]
@tombraman Verified that the "Manage List" right is the minimum required permission (which grants other rights along with it, such as Open Items).

From `Microsoft.SharePoint.ApplicationPages.TopNavigation`:

```csharp
protected override SPBasePermissions RightsRequired =>
    SPBasePermissions.EmptyMask | SPBasePermissions.ManageLists;
```

**Comment by get-itips** [comment]
@tombraman Hello, does @tseward information answers your question? thank you

**Comment by tombraman** [comment]
yes it does, thank you!
