### ISSUE TITLE
Wrong file format (missing header)

### ISSUE THREAD

**Issue by gerardborras** [MicrosoftDocs/OfficeDocs-SharePoint#3150]
I've been having problems with validating the user mapping CSV file until I've added the headers.

Sample .csv:

OnPremSID,UPN,isGroup
domain\user,user@domain.com,FALSE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user-mapping file for data content migration - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @gerardborras 
I tested this to see if we needed to adjust the article however, I could successfully migrate using a csv file for user mappings without headers.
What version of SPMT are you using?
Thanks

**Comment by gerardborras** [comment]
I'm using the latest version available. Maybe the problem was The file had only 1 row?

**Comment by get-itips** [comment]
> I'm using the latest version available. Maybe the problem was The file had only 1 row?

Could you specify the exact version? as there are multiple releases (Public preview, first release, rolling out, and GA), so I can test with the exact version as you

**Comment by gerardborras** [comment]
Version 3.4.121.7

**Comment by get-itips** [comment]
> Version 3.4.121.7

It's the same I am using. Maybe you can share the error, at the moment I can not reproduce.

**Comment by gerardborras** [comment]
Ok I may have found the problem.

It works perfect with one row without headers, but Excel, by default, exports CSV with ";" and not ",".

I was trying to change my csv file manually but once replaced ";" by "," I had to close the tool and reopen it again.

**Comment by gerardborras** [comment]
Sorry: with ";" character the error is "Invalid user mapping: (ErrorCode: 0x2010008)"

**Comment by get-itips** [comment]
Thanks for returning and sharing that, I guess we can now close this issue

**Comment by get-itips** [comment]
@scanum
