### ISSUE TITLE
How OneDrive sync works PDF contains incorrect domain name

### ISSUE THREAD

**Issue by thetuvix** [MicrosoftDocs/OfficeDocs-SharePoint#3151]
The PDF at the "Download the PDF" link mentions three URLs on the first page in the "Technologies used in sync" section.  The domain in two of them is shown as `Microsoft-my.sharepoint.com` - however, this would only be true for the Microsoft tenant.  `Microsoft` in that URL would be replaced by the tenant name for any other tenant.

For example:
* For the Microsoft tenant, the URL would start with `Microsoft-my.sharepoint.com`.
* For the Contoso tenant, the URL would start with `Contoso-my.sharepoint.com`.

The doc article itself correctly refers to `https://<tenant_name, i.e. contoso>-my.sharepoint.com` in a later section.  However, the linked PDF is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df67a6d7-8d87-cd0f-ceba-740727cc2aa7
* Version Independent ID: 0e33e2ed-b837-46b1-c587-0be823f12e5e
* Content: [How sync works - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-process?source=docs)
* Content Source: [OneDrive/sync-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-process.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @thetuvix Alex, how are you?
Thanks for your feedback! As the PDF itself is hosted in another repository, we can't modify it, however, will try to pass this on.
Thanks again,

**Comment by get-itips** [comment]
@scanum
