### ISSUE TITLE
Errors for Product Key in Windows & Sharepoint 2016 in VMWare.

### ISSUE THREAD

**Issue by Naveen6660** [MicrosoftDocs/OfficeDocs-SharePoint#3153]
![Screenshot (1)](https://user-images.githubusercontent.com/98951070/152328504-c7a3e101-cd1d-4ad8-890e-c3302c0fe520.png)

Same is being experiencing with Windows2016 Server too.
Kindly help the same.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
