### ISSUE TITLE
How to combine with tenant external sharing settings

### ISSUE THREAD

**Issue by henricstromgren** [MicrosoftDocs/OfficeDocs-SharePoint#3154]
It would be good to know how the options for "More external sharing settings" should be combined with the overall External Sharing settings.

For example, our External sharing setting for OneDrive is set to "Only people in your organization". When I enable option "Allow on users in specific security group to share externally" this has no effect on the users in the secutiry group sharing possiblities: It is still restricted.
My understanding was that we could have least permissive setting on tenant level but allow some users in one (or several) security groups to share content. 

But as this does not seem to work, I guess it is the other way around - we have to enable sharing with "Anyone" (most permissive) and then restrict users by enabling the option "Allow on users in specific security group to share externally" which will give us option to allow for some security groups.

Would be good if this can be clear in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9f7bfd-4962-7f83-b09c-6ee338296ec3
* Version Independent ID: d0fc2b43-93e7-a8c0-f541-557a65cc9256
* Content: [Manage security groups - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-security-groups)
* Content Source: [SharePoint/SharePointOnline/manage-security-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-security-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @henricstromgren 
I tested this 

>we have to enable sharing with "Anyone" (most permissive) and then restrict users by enabling the option "Allow on users in specific security group to share externally" which will give us option to allow for some security groups.

and I could verify.

However, I think that is mentioned in the introduction of the article

>As a SharePoint or global admin in Microsoft 365, **you restrict external sharing of SharePoint and OneDrive content so that only users in specific security groups can share externally.**

Let me know if I understood you correctly, thank you!

**Comment by henricstromgren** [comment]
Hi, yes you are right.

Then it's ok. It will not work for our use case where we like some users to
be able to share one drive externally but all users to be share SharePoint
external.

But at least I understand know.

Thanks


Den ons 16 feb. 2022 23:13Andres Mariano Gorzelany ***@***.***>
skrev:

**Comment by get-itips** [comment]
Thanks for returning and sharing your feedback @henricstromgren !
