### ISSUE TITLE
question re migrating from DropBox to oneDrive via MOVER

### ISSUE THREAD

**Issue by ronnykorner** [MicrosoftDocs/OfficeDocs-SharePoint#3155]
Hi
The Mover tool looks very good,  However:
1. Will I loose all file creation dates if I migrate using MOVER?
2. Are you going to change this anytime soon ?
Another Q:
3. What happens to directories that reside on my Dropbox cloud  and do not exist on my PC (to save space)
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bb5783d-8e13-a082-66dc-86a3e87e2252
* Version Independent ID: 10739dac-3f2e-5403-6f0e-3d3cb4868e13
* Content: [Mover Microsoft 365 Migration FAQ - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-microsoft-365-faq)
* Content Source: [migration/mover-microsoft-365-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mover-microsoft-365-faq.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
