### ISSUE TITLE
This method doesn't work anymore.

### ISSUE THREAD

**Issue by mauroreyes** [MicrosoftDocs/OfficeDocs-SharePoint#3163]
[Hi Joanne, nice to meet you, I'm Mauro CEO of wingsoft, a software company in Chile.

Following your tutorial I found an error, so I raised a ticket to Egnyte and I'm writing to notify you of what happened.

When trying your method I get the following error:
"Incorrect Request Type GET for resource flow owner . Please check the documentation and try again"
The error message suggests your API key is configured for an internal application which only supports OAuth Resource Owner Password Credentials grant. You would need to make a POST request to /puboauth/token endpoint to generate the token. It looks like you made a GET request and hence this error was returned.

Please refer to the following API doc for details.
https://developers.egnyte.com/docs/read/Public_API_Authentication#Internal-Applications

A hug
Saludos!

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Version Independent ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Content: [Step 1: Connect to Egnyte - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-egnyte-step1-connect?source=docs#feedback)
* Content Source: [migration/mm-egnyte-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-egnyte-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Mauro:

Thanks for reaching out –Can you create a support ticket with Microsoft so our migration support team can help with this? Also include (it would be helpful) the date/time and tenant information when you tried to authorize the Egnyte connector.

Thanks!

Joanne


From: mauroreyes ***@***.***>
Sent: Friday, February 11, 2022 7:29 AM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Joanne Hendrickson ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/OfficeDocs-SharePoint] This method doesn't work anymore. (Issue #3163)


[Hi Joanne, nice to meet you, I'm Mauro CEO of wingsoft, a software company in Chile.

Following your tutorial I found an error, so I raised a ticket to Egnyte and I'm writing to notify you of what happened.

When trying your method I get the following error:
"Incorrect Request Type GET for resource flow owner . Please check the documentation and try again"
The error message suggests your API key is configured for an internal application which only supports OAuth Resource Owner Password Credentials grant. You would need to make a POST request to /puboauth/token endpoint to generate the token. It looks like you made a GET request and hence this error was returned.

Please refer to the following API doc for details.
https://developers.egnyte.com/docs/read/Public_API_Authentication#Internal-Applications<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.egnyte.com%2Fdocs%2Fread%2FPublic_API_Authentication%23Internal-Applications&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=apd1b0OFs0ssTayQ2zlkWd1sj3I%2FqlCcYELybBxzaQo%3D&reserved=0>

A hug
Saludos!

]

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
  *   Version Independent ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
  *   Content: Step 1: Connect to Egnyte - Migrate to Microsoft 365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsharepointmigration%2Fmm-egnyte-step1-connect%3Fsource%3Ddocs%23feedback&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JrG4UXjLotBaZda5WxMFy9sK1LJ1GKT1nA33ScxnE1A%3D&reserved=0>
  *   Content Source: migration/mm-egnyte-step1-connect.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fblob%2Fpublic%2Fmigration%2Fmm-egnyte-step1-connect.md&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HTlmu4na%2FdVTc%2Fy7fUYoQyOySW78rcXz198W%2F98r48w%3D&reserved=0>
  *   Service: sharepoint-online
  *   Sub-service: sharepoint-migration
  *   GitHub Login: @JoanneHendrickson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJoanneHendrickson&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NPZ8SsarKRXKTjo9QhC4Hg18Rk3yHkRJXXwsiJM5k%2Bk%3D&reserved=0>
  *   Microsoft Alias: jhendr

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fissues%2F3163&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6GfIqXilSUmk19LxuB0zTmO1gZ36KJdhHgQzdcCs3SY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHJJJGGL4EBMXQ5OUE5FHELU2UTMJANCNFSM5OESZDVA&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533701171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rogd7X95E8bGvV%2BTDOu%2BmzLPN4dA%2Bbc84OGwcvC5Yr8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533751156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8nWOt5OYSOXovuL7LkJUe3nTXLBdvXCXB7%2Fng7bcXQA%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjhendr%40microsoft.com%7Cb28b7baa853943574ae408d9ed733f39%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801901533751156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iT%2FTaLdA62ff%2FD6WLV2Y5amqMPxfXy52fzjDet2J970%3D&reserved=0>.
