### ISSUE TITLE
SPMT migration guides seem misplaced under Egnyte solution

### ISSUE THREAD

**Issue by ed-roberts** [MicrosoftDocs/OfficeDocs-SharePoint#3166]
I'd expect the SPMT migration guides to be under solutions, or parallel to the Egnyte solution guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae73baef-10f3-db39-177d-ad5750e0ffd9
* Version Independent ID: ae73baef-10f3-db39-177d-ad5750e0ffd9
* Content: [Overview: Migrate Egnyte using Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-egnyte-overview)
* Content Source: [migration/mm-egnyte-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-egnyte-overview.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by ed-roberts** [comment]
I believe the bug already got fixed! Thank you for checking in though.

From: Andres Mariano Gorzelany ***@***.***>
Date: Monday, February 14, 2022 at 6:12 AM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Ed Roberts ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] SPMT migration guides seem misplaced under Egnyte solution (Issue #3166)

Hello @ed-roberts<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fed-roberts&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qeaEOzCfMZc2sPfcsqp1bRrN3kmBGIg4I0d6YZ34kP8%3D&reserved=0>
I am seeing SPMT at the same level and not under egnyte, do you see different?

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36666927%2F153875450-3023798b-0689-49bc-b972-ff080dea8109.png&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t2x0f3Wa2VI0ZhGRDek3WeZ0WTEvUC4J4SRCXajoNj8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fissues%2F3166%23issuecomment-1039104072&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i8aUSwldHs300KHWJnJrmmPXGO3h0xkgd9oNG5pohro%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUREIT2AOOKT6Z26PDOJZ6TU3EBKTANCNFSM5OFLY2WQ&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OpBxrbjkOWAkY00L7FRxuJOUMoEHXC5AKCsdXUtBwBg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QzjfiGdRJVXKLR8%2F3U7MtB69CzdvdvB%2FGhJ2n%2FfQsy4%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ced.roberts%40microsoft.com%7C9b2ba48313ff4e606f5808d9efc4058d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637804447586527302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nmvnzlfOhDN%2FzKooi7%2Fwyx9P%2BiIsLs9Y56xKGWH41DI%3D&reserved=0>.

**Comment by get-itips** [comment]
@scanum
