### ISSUE TITLE
No information on result codes

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/OfficeDocs-SharePoint#3170]
We are preparing to migrate our legacy user folders to OneDrive and I am trying to create documentation to help users understand the scan logs which we will send them. Ideally, this page should include the possible values for the ResultCode field of the scan logs, but I cannot find that information anywhere. We have performed a few test scans and I know there are at least two: INVALID_SHAREPOINT_NAME and ITEM_IS_EMPTY. 

Are there more? 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
