### ISSUE TITLE
What does small to medium migrations mean in terms of number of items and data?

### ISSUE THREAD

**Issue by DeeMacDermott** [MicrosoftDocs/OfficeDocs-SharePoint#3173]
Hi,
I am struggling to find any info on how big the migrations can be fo MS own migration tool and I am getting around 50% of my files skipped when trying to do migrations.
Looking at migrating 430 users GDrives to OneDrive. Approx 40TB of data.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b62f24-44b9-731f-f143-6a05fa1da328
* Version Independent ID: 15452c1d-d06c-e8f5-9b87-b5fdd0f375ab
* Content: [Migration Manager Google FAQs - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs-google)
* Content Source: [migration/mm-faqs-google.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-faqs-google.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by DeeMacDermott** [comment]
Hi @scanum,
Thank you for getting back.
It appears the skipped files was not actually an issue, but partially failed migrations with another tool, so MS migration tool actually just didn't need to copy them. No issue there.
MS migration tool has been working insanely well. I can't see any issue with migration of 430 users, but if there is any reason I shouldn't be migrating this many please could you give me a heads up.
It's the best performing migration tool I have seen so far by a long shot in terms of speed.
