### ISSUE TITLE
Blocking Uploading of specific File Types 

### ISSUE THREAD

**Issue by nmohanlfs** [MicrosoftDocs/OfficeDocs-SharePoint#3174]
[The content was pretty clear. I have a specific query though. Can this policy be imposed on some users and not be imposed on some users ? or is the policy applied on all users ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by HansBrender** [comment]
I know, ther is no policy "Blocking Uploading of specific File types"
I only know "Exclude specific kinds of files beeing uploaded", but this is a Computer Policy, not a user Policy
