### ISSUE TITLE
SiteIncludeList instead of SiteSkipList

### ISSUE THREAD

**Issue by Maurikrm** [MicrosoftDocs/OfficeDocs-SharePoint#3176]
I have a customer who wants to run the SMAT tool for a single site but to do so they have to put 25.000+ sites in the SiteSkipList.csv. Is it possible to create a parameter to use an include list instead of an exclude list?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
