### ISSUE TITLE
Does this tool work with MFA, such as Okta?

### ISSUE THREAD

**Issue by mikey217** [MicrosoftDocs/OfficeDocs-SharePoint#3177]
I have a customer that uses Okta to access Google Workspace.  Migration Manager can connect and see the drives, but cannot scan or migrate them.  Are there any extra steps to take in order to get this to work with something like Okta?

Thanks,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 845775d4-7e19-6de1-8174-2e7c2a772f92
* Version Independent ID: 9aadf253-fba6-7be3-9a63-a7c4b0df84d0
* Content: [Connect to Google with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-US/sharepointmigration/mm-google-step1-connect?WT.mc_id=365AdminCSH_spo)
* Content Source: [migration/mm-google-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-google-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Mike -- checking for you.  Will post as soon as I find out.

**Comment by JoanneHendrickson** [comment]
@mikey217 Can you submit a support ticket on this? Include the tenant ID, task ID which failed to scan, etc. Also what kind of Google account used to connect, etc. thanks! joanne
