### ISSUE TITLE
Limitations of Menus

### ISSUE THREAD

**Issue by shelagh03** [MicrosoftDocs/OfficeDocs-SharePoint#3178]
Is there a limit on the number of items in a menu? (I remember there used to be a limit of 50 items in the classic SharePoint sites)
Would targeting have any impact on that limit?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Plan and implement SharePoint site navigation - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @shelagh03 I am looking into this

**Comment by get-itips** [comment]
Hello @shelagh03 I could get information that, currently, there is no limit.
Hope this information helps you,
