### ISSUE TITLE
"Usage navigation tab" should be "Navigation tab"

### ISSUE THREAD

**Issue by jdata1** [MicrosoftDocs/OfficeDocs-SharePoint#3179]
In the section header and in the body text, the language seems behind changes in the term store UI for this tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449a5cb7-2200-f64b-ee4f-c0af2c7ba7ad
* Version Independent ID: 18da722e-9d9a-2858-e4dc-91fd99b7656c
* Content: [Set up a new term set - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/set-up-new-term-set?source=docs)
* Content Source: [SharePoint/SharePointOnline/set-up-new-term-set.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/set-up-new-term-set.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
