### ISSUE TITLE
Security trimming

### ISSUE THREAD

**Issue by ceaheart** [MicrosoftDocs/OfficeDocs-SharePoint#318]
I'm reading that security trimming is now implemented - is that correct?  When this was announced, security trimming did not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@ceaheart, I'm curious where you heard that security trimming is implemented. I confirmed that it is not. The team is looking into audience targeting in the hub nav, but has not added this to the roadmap. I hope this helps!

**Comment by ceaheart** [comment]
@kaarins - I provided a link to the documentation, which says "Association with a hub does not change the permissions on a site. If you associate a site that has restricted access with a hub, only users who have access to the restricted site will see content rolled up on the hub. Information surfaced on the hub site is security trimmed: if you don't have access to the content, you won't see it. Something you may want to consider is adjusting permissions on the associated sites after you have assembled your hub family."

Additionally, I talked to the author of the documentation @SusanHanley who said that this should work and to file a ticket with MSFT.

**Comment by scanum** [comment]
@kaarins Any update on this? Thanks!

**Comment by kaarins** [comment]
Search and the info that rolls up on the hub site is security trimmed. The navigation is not, so if someone has permission to the hub site but not an associated site, they will still see the link. When they click the link, they will get an access denied message.
