### ISSUE TITLE
Another reason you may need to change a SharePoint domain

### ISSUE THREAD

**Issue by tenetchew** [MicrosoftDocs/OfficeDocs-SharePoint#3180]
The first part of the second paragraph should read, "If your organization has gone through a rebranding, merger, acquisition, or if you were unable to use your actual domain name because your domain name plus the needlessly lengthy "onmicrosoft.com" violated the length limit for domain names, all because the developers at Microsoft couldn't have come up with anything shorter than "onmicrosoft.com" to begin with".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name?source=docs)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
