### ISSUE TITLE
error-0x8004de40 Article is outdated 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SharePoint#3181]
https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/error-0x8004de40-in-onedrive?ns-enrollment-type=Collection&ns-enrollment-id=bookmarks

The [Easy Fix Tool](https://download.microsoft.com/download/0/6/5/0658B1A7-6D2E-474F-BC2C-D69E5B9E9A68/MicrosoftEasyFix51044.msi) does not work on windows server 2012 R2.

**Comment by lindspea** [comment]
@robinpoulose1 thank you for reaching out and helping to improve Microsoft Docs. Does this article help at all - https://docs.microsoft.com/troubleshoot/windows-server/identity/apps-forcibly-closed-tls-connection-errors
