### ISSUE TITLE
Devices on the Deferred ring aren't eligible... or are they?

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/OfficeDocs-SharePoint#3182]
Requirements:
OneDrive sync apps on the Insiders or Production ring. **Devices on the Deferred ring aren't eligible for the preview.**
**OneDrive Sync app version 21.078 or later for Windows**. Support for Mac isn't available yet.

The latest deferred ring version is 21.230.1107.0004. Does this mean devices on the deferred ring *ARE* eligible?

Thanks!
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-health)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @matziq I am looking into this

**Comment by HansBrender** [comment]
The sync reports are still in Preview. I think thats the reason for the requirements.

**Comment by adeejoseph** [comment]
Hi @matziq - Deferred ring devices are not eligible in preview. This is separate from the version. Devices must be on the Insiders or Production ring to be eligible.

**Comment by matziq** [comment]
Thanks!

**Comment by get-itips** [comment]
Thanks @adeejoseph !
