### ISSUE TITLE
My Teams app only allows 2 channel types: Standard vs. Private.  There is nothing relevant to the "Shared Channel" as a third option.

### ISSUE THREAD

**Issue by tsiricha** [MicrosoftDocs/OfficeDocs-SharePoint#3190]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bc6df5-e361-4aeb-6eb4-20a8c017fa39
* Version Independent ID: 1c50aa81-9779-8725-963a-5dc94a60940d
* Content: [Teams and SharePoint integration - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites)
* Content Source: [SharePoint/SharePointOnline/teams-connected-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/teams-connected-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thank you for your comment @tsiricha. Shared channels are coming in March/April 2022. I've updated the article, so we don't talk about shared channels for now.
