### ISSUE TITLE
Is the M365 Migration app for Google Workspaces still viable?

### ISSUE THREAD

**Issue by PaintrockConsulting** [MicrosoftDocs/OfficeDocs-SharePoint#3192]
Looks like the M365 migration app / domain installer is no longer available. (global admin on m365 and Gworkspaces)
![2022-02-25 11_30_46-Microsoft 365 migration - Google Workspace Marketplace and 6 more pages - Kristi](https://user-images.githubusercontent.com/20844514/155768879-fdd2ce3a-181f-426e-b902-2672e7303d8c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 845775d4-7e19-6de1-8174-2e7c2a772f92
* Version Independent ID: 9aadf253-fba6-7be3-9a63-a7c4b0df84d0
* Content: [Connect to Google with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-US/sharepointmigration/mm-google-step1-connect?WT.mc_id=365AdminCSH_spo)
* Content Source: [migration/mm-google-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-google-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @PaintrockConsulting Kristi, how are you?
Do you mean that you have the install button grayed out? I followed the instructions and is available for me.
Thanks for clarifying,

**Comment by PaintrockConsulting** [comment]
Hello – thank you for asking; yes – the install button is greyed out.  I used a different utility to perform the migration.  Thank you.



Regards,

Kristi Robison
+1.307.431.8690 (US; GMT - 6)
***@***.******@***.***>
