### ISSUE TITLE
All Microsoft Teams Connected Sites in Search

### ISSUE THREAD

**Issue by Jiannko** [MicrosoftDocs/OfficeDocs-SharePoint#3193]
I have mapped the crawled property ows_IsTeamsConnectedSite to a RefinableString to use it as a Refiner in the pnpSearchWebpart
. I dont see the results as expected . Can this crawled property be used?
Please redirect me to correct group if this is not the right one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b707d763-4c82-0d68-9cc7-35fb66935d25
* Version Independent ID: 4da67e73-1af9-ed9d-f367-4048ce5897fd
* Content: [Manage the search schema in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-search-schema)
* Content Source: [SharePoint/SharePointOnline/manage-search-schema.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-search-schema.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
@scanum
