### ISSUE TITLE
Organization of information on page inconsistent

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/OfficeDocs-SharePoint#3197]
Greetings! This page about product integration is helpful and clear. I have a few observations:

- Some of the points (e.g. descriptions of Standard and Private channels, Parent sites and Channel sites) are strangely isolated from one another. It seems to me that related or comparative information should be grouped together.
- The statement "There are three types of channels in Teams: standard and private" seems to anticipate the introduction of shared channels, but that variety is left out of both the statement and the bullet points.
- Underlying services and technologies, such as Microsoft 365 Groups and Azure AD, should perhaps come at the end of the list. It's disruptive to the reader, in my opinion, to have that information offered when it's not necessarily expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bc6df5-e361-4aeb-6eb4-20a8c017fa39
* Version Independent ID: 1c50aa81-9779-8725-963a-5dc94a60940d
* Content: [Teams and SharePoint integration - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites)
* Content Source: [SharePoint/SharePointOnline/teams-connected-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/teams-connected-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Hello @DFLiddle thank you so much for your feedback. Really great recommendations. We will be editing this content in the next handful of business days and will include your feedback. Thank you!
