### ISSUE TITLE
Clearify organization-assets-library working with Office 2016/2019

### ISSUE THREAD

**Issue by caspChristian** [MicrosoftDocs/OfficeDocs-SharePoint#3198]
Please make it clear if Templates are working with Office 2016/2019 or not.
It mentions Microsoft 365, But does not say that Office 365 is required. Many Many people are expecting this to work with Office 2019 as well.

And if it does not, make sure to explain where to find documentation for deployment in non 365 office.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @caspChristian I am looking into this

**Comment by get-itips** [comment]
Closing this issue as the article clearly states that it requires 365 services and it is under SharePoint online content.

**Comment by caspChristian** [comment]
It is in no way clear, note that it works with Office 2021, Office 365 IS NOT REQUIRED.
Maybe check _actual_ facts and update accordingly.

**Comment by caspChristian** [comment]
Reopen, or i Will create a new issue until the issue is actually fixed.

**Comment by get-itips** [comment]
@caspChristian Christian,
Maybe I did not fully understand your inquiry, if that is it, please let me know.
Organization assets library require Office 365 services to work, as they rely on SharePoint Online to create this library.
Once again, if I did not understand your question, please let me know.

**Comment by caspChristian** [comment]
It requires Office 365 Services yes.

But does it work with Office 2016/2019/2021 or which version of the desktop application is required to work?
We know it works in 2021, but there is no mention of that. So why should I not expect it to work in 2019?
![image](https://user-images.githubusercontent.com/13637507/175610573-bb0011a8-b53a-4f1e-981f-222efcdf77c4.png)

**Comment by get-itips** [comment]
Hello @caspChristian how are you?

> But does it work with Office 2016/2019/2021 or which version of the desktop application is required to work?

I've got confirmation from the team that organization-assets libraries are only **supported**/require:

>The following Office apps are supported: 
> Microsoft 365 Apps Version 2002 or later is also required.

As the article currently says.

**Comment by caspChristian** [comment]
Ok, but as I said, that is not totally correct since it works in 2021 as well.

And as the page says and you are quoting "Version **2002** or later" Which 2021 is.
I understand that your intended meaning is "Version 2002 or later of Microsoft 365 Apps"
However since it, as I said, works with 2021, this is confusing.

**Comment by get-itips** [comment]
@caspChristian Hello Christian, please take note that the word used in the article is **supported** which is different from "it works".
It is version 2002 of the **Microsoft 365 Apps** as the same sentence says (see here https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date)

**Comment by caspChristian** [comment]
English might not be my native language, but the current way it is written leaves it open to interpet as any Microsoft Office 365 2002 or later, which in fact 2021 is.

If it works, then our users actually expect it to be supported.
We made the decision to use 2021 from that it worked in our tests. This just... plain frankly sucks!
