### ISSUE TITLE
Invalid link on this page

### ISSUE THREAD

**Issue by ZatGH** [MicrosoftDocs/OfficeDocs-SharePoint#3199]
[Enter feedback here]

[Plan your Office 365 Launch: Communication and Training Guide](https://aka.ms/commandtraining)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises - OneDrive](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ZatGH I am looking into this
