### ISSUE TITLE
SQL Always -on Cluster

### ISSUE THREAD

**Issue by mdittakavi** [MicrosoftDocs/OfficeDocs-SharePoint#32]
Hi Team,
we have tried the steps as per this document in our Production environment to upgrade March 2018 CU patch and encountered below issues. We have SQL server with Always-On configured and SQL AG listener service. Could you update this article how to handle in  cluster scenario. Also, when to run upgrade-spcontnetdatabase. is it before PSCONFIG or after. if there is no DB schema update as per patch KB article. Do we need to run still this command.

Error received: Task upgrade has failed with a PostSetupConfigurationTaskException An exception of type Microsoft.SharePoint.PostSetupConfiguration.PostSetupConfigurationTaskException was thrown.  Additional exception information: The upgrade command is invalid or a failure has been encountered.

Upgrade [SPUsageDatabase Name=SP_UsageAndHealth] failed.     (EventID:an59t)

Exception: The operation cannot be performed on database "SP16_UsageAndHealth" because it is involved in a database mirroring session or an availability group. Some operations are not allowed on a database that is participating in a database mirroring session or in an availability group.ALTER DATABASE statement failed.         (EventID:an59t)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ccb7df-8dca-b5fc-4e84-e3624d2804cc
* Version Independent ID: 669daf62-d97c-3489-786b-6924c1e755b0
* Content: [SharePoint Server 2016 zero downtime patching steps](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
You should not have the Usage database in a mirror or AlwaysOn session. Remove that database from the AOAG and point the Usage service at a specific SQL server.

**Comment by kenwith** [comment]
@tseward - would it be possible for you to incorporate your expert knowledge on this scenario into the doc as a PR?

@mdittakavi - sorry for the delay on this and that it has gone stale in the documentation issues. I know it has been a very long time so I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
