### ISSUE TITLE
qualifying Microsoft 365 subscription 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SharePoint#3202]
If your organization has a qualifying Microsoft 365 subscription and five (5) or more users, you can change the storage space to more than 5 TB. To discuss your needs, contact Microsoft support. You must assign at least one license to a user before you can increase the default OneDrive storage space.. "

What are the qualifying plan please elaborate ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users - OneDrive](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @robinpoulose1 how are you? I am looking into this

**Comment by get-itips** [comment]
Hello @robinpoulose1 

You can see here which plans have eligible unlimited OneDrive storage 

https://www.microsoftpartnercommunity.com/atvwr79957/attachments/atvwr79957/NLMW/96/3/Modern%20Work%20User%20Subscription%20Plan%20Comparison%20for%20Enterprise.pdf

Hope this information helps you

**Comment by robinpoulose1** [comment]
> Hello @robinpoulose1
> 
> You can see here which plans have eligible >5TB OneDrive storage
> 
> https://www.microsoftpartnercommunity.com/atvwr79957/attachments/atvwr79957/NLMW/96/3/Modern%20Work%20User%20Subscription%20Plan%20Comparison%20for%20Enterprise.pdf
> 
> Hope this information helps you

Thanks ! it  is clarified now.
