### ISSUE TITLE
URL in manage-loop-components.md for Office 365 URLs and IP Addresses is broken

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/OfficeDocs-SharePoint#3207]
The link for Office 365 URLs and IP Addresses is broken and produces a 404 message when followed by the reader. [https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md)

the link currently points to [https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges)

**Comment by lindspea** [comment]
@loaderladdy thank you for reaching out. For me to further assist please can you link the article that you are making reference to. Thank you

**Comment by loaderladdy** [comment]
Hi Lindsay,  ah my fault I didn't do the markdown for the links correctly... doh! 🤦‍♂️🤦‍♂️  the links are now fixed.  Many thanks.

**Comment by lindspea** [comment]
@scanum you can close this thank you.

**Comment by loaderladdy** [comment]
Hi, sorry, I'm not very good at this, I meant the links in my original issue were fixed not the link in the article, that link is still broken 😳

```
![image](https://user-images.githubusercontent.com/15855352/158554138-d0a67a7a-2e0f-4f26-9d27-9c6d7270fc80.png) 
```

> Article showing link

```
![image](https://user-images.githubusercontent.com/15855352/158555122-71843f88-0b77-42e7-b207-48ca6f33403f.png)
```

> Broken link

**Comment by loaderladdy** [comment]
I thought it was this one Lindsay " https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md ".  Is it a different link?

**Comment by lindspea** [comment]
@loaderladdy thank you for clearing this up. I checked the URLs and IP Addresses link in the Manage Loop Components article and it seems to be working from my side. Please can you check and confirm if it's working now.

**Comment by loaderladdy** [comment]
Hi Lindsay, I've checked the online article https://docs.microsoft.com/en-us/sharepoint/manage-loop-components and can see the link within the article does indeed work and points to https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide 

I w one of I got confused because the link within the MD file in the GitHub repository doesn't work but it does work in the published article. Is this a GitHub 'feature'?
