### ISSUE TITLE
does this work accross site collections

### ISSUE THREAD

**Issue by kdubelang** [MicrosoftDocs/OfficeDocs-SharePoint#3208]
in the old days of on premise sharepoint you could not use library templates across site collections because they had pointers to things in the site collections (like hidden managed metdata lists ie the Hidden Taxonomy List )  we got severely burned on this.  What i'm wondering is if i create my list templates using this new powershell will that problem present itself?

the old issue:

https://social.msdn.microsoft.com/Forums/en-US/674fe737-0bbf-4a59-9fd6-1a951f28d042/is-using-document-library-templates-across-site-collections-supported?forum=sharepointdevelopmentprevious

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by kdubelang** [comment]
thanks for the feedback, i did try and test this and can confirm that it failed... i don't think it  supports it.  Sorry i don't have time to chase microsoft support on this i was hoping that you guys could ask the question...

**Comment by kdubelang** [comment]
the error i got was "The parent content type specified by content type identifier (GUID) does not exist".  In this context what I believe this error means is that its trying to create child content types before the parents are created.  Whats interesting is that the parent content type is coming from the content type gallery (so it should be able to access it).
