### ISSUE TITLE
Update content to include warning that MSFT support is needed if you put in the wrong IP range

### ISSUE THREAD

**Issue by hdonaldMSFT** [MicrosoftDocs/OfficeDocs-SharePoint#321]
We've had several customers mis-set their allowable IP ranges. When applied, they get locked out and can't fix the mistake they've made. Admins have been banging their heads trying to figure out how to self serve, but you can't - you have to call support. Can we be more explicit about the risk of mis-setting and the fact that if you do mis-set, you will need to contact support to get unblocked?

The other bit of feedback we received was: specifically say "not only will this change restrict your user facing onedrive and SharePoint sites, but it will also restrict your access to the OneDrive Admin site, thus preventing your ability to undo this change outside of the specified IPs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Control access to SharePoint Online and OneDrive data based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@hdonaldMSFT Thank you for this feedback. 

I will get this information to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, any updates on this? Thanks!

**Comment by kaarins** [comment]
I added this right away months ago, but missed closing it.
