### ISSUE TITLE
'Sharing' toggle is not available for Teams channels

### ISSUE THREAD

**Issue by hugoideler** [MicrosoftDocs/OfficeDocs-SharePoint#3211]
In the section [Change the default link type for a site](https://docs.microsoft.com/en-us/sharepoint/change-default-sharing-link#change-the-default-link-type-for-a-site-1) a number of steps are listed that you can use to set this policy for SharePoint sites.

While this indeed works for SharePoint sites including Teams, I think it's worthwhile to mention in the documentation that this method cannot be used for (private) Teams _channels_ (sub-sites). As an example, see the following.

<img src="https://user-images.githubusercontent.com/547309/158069293-78cd127b-3faf-486d-ae64-c3017fdd4f49.png" width="75%">

1. The sharing button is available, but it only affects the main/default channel of the Team site. It does not apply to channel sub-sites.
2. You need to click the "sites" link to see these sub-sites.

<img src="https://user-images.githubusercontent.com/547309/158069365-636efb0e-513d-4bc7-a0b4-66d9b24752b5.png" width="55%">

3. But when you view these sub-sites, there is no "Sharing" button. Therefore, using the UI you cannot set the default link sharing policy for (private) channels.

A solution that the article can suggest for these cases, is to go the PowerShell route using the URL of the channel, e.g.:

```PS1
Set-SPOSite -identity $site -DefaultLinkToExistingAccess $true
```

NB: I only tested this with private channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default sharing link for a site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-default-sharing-link)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hugoideler** [comment]
Hi @scanum, I am not asking for support; I am providing feedback on how to improve the documentation. There is a limitation in the UI that the current documentation does not cover. See my issue above for a description of this use case and a suggested workaround that users can apply.
