### ISSUE TITLE
The required endpoint contains inappropriate characters.

### ISSUE THREAD

**Issue by akkomats** [MicrosoftDocs/OfficeDocs-SharePoint#3212]
The required endpoint contains inappropriate characters.
![image](https://user-images.githubusercontent.com/56673047/158091694-99835221-ff51-4865-b9fc-82ffc9aa3920.png)

Current
- https://\<spam\>\<spam\>spmt.\<spam\>\<spam\>sharepointonline.<spam><spam>com"
- "https://\<span\>\<span\>*.table.core.windows.net"

Need to modify as follows
- https://spmt.sharepointonline.com
- https://*.table.core.windows.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573e2247-016b-74b2-cf03-3041af3df550
* Version Independent ID: 3d6d4b62-4f26-81d1-6be2-ecfe7ebd81bf
* Content: [Prerequisites and Endpoints for SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/spmt-prerequisites)
* Content Source: [migration/SPMT-Prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/SPMT-Prerequisites.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback! @akkomats
