### ISSUE TITLE
how long for the sensitivity label to be updated in the admin page

### ISSUE THREAD

**Issue by longnlp** [MicrosoftDocs/OfficeDocs-SharePoint#3217]
I'm applying the sensitivity label to the site collection with two methods, and I found the admin page is not updated automatically for one case, so please help investigate this.

Successful case
Change sensitivity label in the SharePoint admin center -> Active Sites

Failed Case
Change the sensitivity label in the site collection -> site information (not in SharePoint admin center)

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f0e99c-724d-9fc3-6b8b-bda185f92c19
* Version Independent ID: d38a6ff9-e4cd-5776-b152-9694fcafbee1
* Content: [What's new in the SharePoint admin center - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-admin-center#feedback)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/what-s-new-in-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
