### ISSUE TITLE
SilentAccountConfig is not actually silent

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/OfficeDocs-SharePoint#3218]
When configuring this GPO/registry key, the sign in is silent but there is still a pop up "we're getting things ready for you" with a progress bar. Based on this we have not been able to silently deploy OneDrive client and need to prompt the user to install the OneDrive package deployed via SCCM.

How can we make it actually silent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @nickp85 
While I try to reproduce, please kindly confirm you tested on computers joined to Azure AD as the article mentions.
Thank you!

**Comment by nickp85** [comment]
Our machines are hybrid joined to Azure AD.

Thanks

**Comment by get-itips** [comment]
Hello @nickp85 sorry for the delay, did you try the steps outlined [here](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#verify-that-single-sign-on-sso-is-working)?
If you did, the best would be to open a support request from your tenant, as here we are limited to **documentation** issues.

Thank you

**Comment by get-itips** [comment]
@scanum
