### ISSUE TITLE
Garbled Up, Not Helpful

### ISSUE THREAD

**Issue by ChrisMwai** [MicrosoftDocs/OfficeDocs-SharePoint#322]
90% of the steps outlined require the user to go elsewhere and follow another set of instructions that will also have many steps directing elsewhere. I have found myself 5 topics away from the article I was supposed to read.

Why not set up a complete series containing the documentation? Why create articles with millions of detours? You must be aware that for someone to find themselves Reding the article, they must have encountered the problem outlined in the subject topic. You are supposed to ensure that they have an answer to their problem within the article OR direct them to read the series that covers the setup from A to Z.

7 browser tabs later, still no headway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1285fcf0-476f-b431-c8f0-ae395c31418e
* Version Independent ID: a5679b64-68bf-42fb-98f0-51d1625a102e
* Content: [Transition from the previous OneDrive for Business sync client](https://docs.microsoft.com/en-us/onedrive/transition-from-previous-sync-client)
* Content Source: [OneDrive/transition-from-previous-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/transition-from-previous-sync-client.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@ChrisMwai, thanks for this feedback. We're working on a rewrite of this article that we hope to publish in the next few days. If you're looking for specific info that you think should be added to this article, please let me know, and I will incorporate it when we update the article.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, any updates on this? Thanks!

**Comment by kaarins** [comment]
Sorry I forgot to close this issue. The updates were published on Nov 6, right after I commented.
