### ISSUE TITLE
How "MigrationComplexity" and "MigrationComplexityPoints" are calculated in SharePoint Migration Assessment Tool (SMAT) report?

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/OfficeDocs-SharePoint#3220]
How "MigrationComplexity" and "MigrationComplexityPoints" are calculated in SharePoint Migration Assessment Tool (SMAT) report?
What is the logic behind calculation of MigrationComplexity(critical/high/medium/low) and MigrationComplexityPoints(integer)? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc1ccc3-1713-6a8f-8120-28ca04a7eed8
* Version Independent ID: d0ac879e-81d4-ca80-b83d-ea1e318a9fa8
* Content: [SharePoint Migration Assessment Tool Scan Reports Roadmap - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-assessment-toolscan-reports-roadmap)
* Content Source: [migration/sharepoint-migration-assessment-toolscan-reports-roadmap.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/sharepoint-migration-assessment-toolscan-reports-roadmap.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jaganpt** [comment]
Any update on this?

**Comment by get-itips** [comment]
Hello @jaganpt can you please detail in which report scan specifically did you see those properties? Thank you

**Comment by jaganpt** [comment]
One of the SMAT generated reports "MigrationReport_Overview.csv" has the columns "MigrationComplexity" and "MigrationComplexityPoints".
What is the logic behind calculation of MigrationComplexity(critical/high/medium/low) and MigrationComplexityPoints(integer)?

**Comment by get-itips** [comment]
Thanks for clarification, will look into that

**Comment by get-itips** [comment]
Hello @jaganpt 
I can't seem to be able to reproduce that report on my environment, did you run the SMAT with default settings? is it against a 2010 or 2013 SharePoint?
Thanks

**Comment by jaganpt** [comment]
It is against SharePoint 2019.

**Comment by get-itips** [comment]
> It is against SharePoint 2019.

Ok please kindly confirm you are using RTM_Update6_1 of SMAT tool and if scandef.json was customized or is by default.

Thanks!

**Comment by jaganpt** [comment]
Yes I can confirm that the tool is SMAT_RTM_Update6_1
There were no customization on any part of, it was run as-is.

**Comment by get-itips** [comment]
Hello @jaganpt Jagan,
Just to verify, does this match your version?

![image](https://user-images.githubusercontent.com/36666927/160645409-3c09505d-1f34-4ebf-bced-524923a3b3c8.png)

Thanks

**Comment by jaganpt** [comment]
Hello @get-itips,
Yes, it is the same version.

**Comment by jaganpt** [comment]
Hi @get-itips ,
Any update on this?

**Comment by jaganpt** [comment]
Hello @get-itips,
Any update on this would really help us. Thanks.

**Comment by get-itips** [comment]
Adding the writer input required label as **I could not reproduce**.
