### ISSUE TITLE
Cannot expand to 5TB

### ISSUE THREAD

**Issue by pocket9** [MicrosoftDocs/OfficeDocs-SharePoint#3221]
I had expanded the OneDrive space to 5TB last year. It was working fine up until last week when it reverted back to 1TB. No changes were done to the environment to cause this. This was for a Business Standard account. 

The article below shows that it can be expanded to 5TB but it will not allow without additional cost. Has anyone else had this challenge? 

https://docs.microsoft.com/en-US/onedrive/change-user-storage

**Comment by get-itips** [comment]
Hello @pocket9 how are you?
Did you follow this section in the article that talks about that?
https://docs.microsoft.com/en-us/onedrive/change-user-storage#diagnose-issues-with-changing-the-onedrive-storage

**Comment by pocket9** [comment]
Hi,

I'm so sorry. I did do the diagnostics but it reported that 5TB was the maximum and that it couldn't expand further although the user was still at 1TB. After trying several other steps, I was able to get it to upgrade to 5TB by changing it to an E3 business license. Thanks so much for your help!

**Comment by get-itips** [comment]
Thanks for returning and sharing your feedback!
