### ISSUE TITLE
User mapping file issue

### ISSUE THREAD

**Issue by PikeSal** [MicrosoftDocs/OfficeDocs-SharePoint#3224]
[Unable to map users using the instructions in this article. the user's are not added to the SharePoint site.

I tried both combinations using SID and username.

![image](https://user-images.githubusercontent.com/73570781/159593430-985aa4fa-c337-4f00-af78-606cf9192d65.png)
https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration

The log files don't show any errors using Migration Mgr or SPMT

File share to SharePoint Online
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user-mapping file for data content migration - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @PikeSal 
I tested this on my lab tenant from my lab SP Server and I could successfully migrate and map users using the csv file, sharing an example with you 

![image](https://user-images.githubusercontent.com/36666927/159960582-ddc0aa7c-1de6-4b49-b09c-ae5e3a097a87.png)



Also, if you look at the migration report, you should see in the file UserMapped_R1.csv if the mapping was successful.

Hope this information helps you,

**Comment by get-itips** [comment]
Hello @PikeSal could you see my last comment? Thank you

**Comment by JoanneHendrickson** [comment]
@pikesal -- is this a File share to SharePoint migration? or SharePoint Server to SharePoint online?

**Comment by PikeSal** [comment]
Fileshare to SharePoint online.

**Comment by get-itips** [comment]
> Fileshare to SharePoint online.

Hello @PikeSal 
I've just tested File Share to SPO and the mapping file was used and applied.
For your information I used the same format I showed you in my first reply.
Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
