### ISSUE TITLE
Where are the screenshots?

### ISSUE THREAD

**Issue by Karlstens** [MicrosoftDocs/OfficeDocs-SharePoint#3228]
This article absolutely needs accompanying screenshots to assist users as they work through the detailed processes within the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b707d763-4c82-0d68-9cc7-35fb66935d25
* Version Independent ID: 4da67e73-1af9-ed9d-f367-4048ce5897fd
* Content: [Manage the search schema in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-search-schema)
* Content Source: [SharePoint/SharePointOnline/manage-search-schema.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-search-schema.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by tiburd** [comment]
Thanks for the feedback. It's been forwarded to the documentation team.
