### ISSUE TITLE
Page out of date

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/OfficeDocs-SharePoint#3231]
Content does not correspond to the new modern App Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b12ead9-dcc9-19af-e7b1-d846f8116300
* Version Independent ID: 45ad5ca0-5c6f-c058-90e7-27f7824e937e
* Content: [Configure settings for the SharePoint Store - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/configure-sharepoint-store-settings)
* Content Source: [SharePoint/SharePointOnline/configure-sharepoint-store-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/configure-sharepoint-store-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @angoo-atea Andrew, hoy are you?

I could follow the instructions currently in the SharePoint Admin Center that this article specifies, can you please specify what you see is outdated?

Thanks

**Comment by get-itips** [comment]
Hello @angoo-atea could you see my last comment here?

**Comment by get-itips** [comment]
@scanum
