### ISSUE TITLE
I understand but I seriously dislike the content of this page.

### ISSUE THREAD

**Issue by spikedlemon** [MicrosoftDocs/OfficeDocs-SharePoint#3233]
As per title. I understand the content of this article, but seriously dislike the direction that has been taken and the day-to-day usability that has been taken from users. I sincerely hope that Microsoft reverses its direction on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by adeejoseph** [comment]
Hi @spikedlemon,

Thank you for your feedback. Can you help me understand your sentiments a bit more? If I understand correctly, you are saying that you dislike Microsoft's choice in no longer supporting Internet Explorer 11. Is that correct?

**Comment by spikedlemon** [comment]
> Hi @spikedlemon,
> 
> Thank you for your feedback. Can you help me understand your sentiments a bit more? If I understand correctly, you are saying that you dislike Microsoft's choice in no longer supporting Internet Explorer 11. Is that correct?

Yes, this is correct. Thank you for humouring me with an honest response, it simply represents a significant reduction in day-to-day QOL by the majority of the users at our organization.

**Comment by adeejoseph** [comment]
Thanks for the response. I'd love to learn more about this. What challenges are you all facing now? If you don't mind me asking, have you considered using the Internet Explorer functionality within Microsoft Edge?

**Comment by adeejoseph** [comment]
Closing due to stale state.

**Comment by spikedlemon** [comment]
Primary issues: Navigability is vastly decreased through web view. Quickly
accessing sub-folders (and seeing what level of folder you're in), CTRL-C/V
of files, double-click-to-rename functionality is all lost by web system.
It becomes a very cumbersome, and slow system to perform previously quick
actions.

Secondary issues: older excel files with significant number of macros/VBA
content regularly becomes corrupt and requires download onto your HDD on
new sharepoint for work, and then re-uploaded when saved. It loses, fully,
the collaborative functionality that was inherent in SP.
