### ISSUE TITLE
How to Disable "Edit in grid view" PnP Provisining

### ISSUE THREAD

**Issue by HiighQ** [MicrosoftDocs/OfficeDocs-SharePoint#3234]
Greetings,

i habe got the assgnment to build a list where the "Edit in grid view" is hidden.
Now i know how to do it using the PnP Module:
`$List = Get-PnPList -Identity $ListName
$list.DisableGridEditing = $True
$List.Update()
Invoke-PnPQuery`

But my colleague want me to do that directly in the XML Site Template but i cant seem to find a Atribute for this cause.

Greatfull for any help!
For more infos Please Let me know.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
