### ISSUE TITLE
Refer to SPO Management Shell Page

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-SharePoint#3235]
Currently the page refers directly to [https://go.microsoft.com/fwlink/p/?LinkId=255251](https://go.microsoft.com/fwlink/p/?LinkId=255251) to download the latest SharePoint Online Management Shell. May I suggest instead referring to the page [https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online) so that people are aware of the module also being available from the PowerShell Gallery, which should be the preferred way to install modules.

Thanks.

**Comment by get-itips** [comment]
Hello @aakash-shah 
Can you please link here the article you are talking about that includes the link https://go.microsoft.com/fwlink/p/?LinkId=255251 ?

Thank you

**Comment by get-itips** [comment]
@scanum
