### ISSUE TITLE
Preview Features

### ISSUE THREAD

**Issue by matttheba** [MicrosoftDocs/OfficeDocs-SharePoint#3236]
Hi,

Why is this option no longer available? What is the replacement? I don't understand why this is not related to targeted features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6668926-c332-1348-2559-ee4e6dbf68a9
* Version Independent ID: 214e5b3a-ba59-2dd3-5e97-7d642072afaf
* Content: [Enable or disable preview features in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/enable-or-disable-preview-features)
* Content Source: [SharePoint/SharePointOnline/enable-or-disable-preview-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/enable-or-disable-preview-features.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
