### ISSUE TITLE
Need documentation on what happens with guest users when IB is turned on in SPO

### ISSUE THREAD

**Issue by jarossmsft** [MicrosoftDocs/OfficeDocs-SharePoint#3238]
Article needs better documentation around what happens with external guest user access when a customer is using Information Barriers. See example escalation: https://portal.microsofticm.com/imp/v3/incidents/details/291416361/home.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a21b65-b5cb-b777-842f-c5d6ac78dd31
* Version Independent ID: 88cb0db2-f421-cf77-8926-9290db598d1a
* Content: [Use information barriers with SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/information-barriers)
* Content Source: [SharePoint/SharePointOnline/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/information-barriers.md)
* Service: **sharepoint-online**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Hello @jarossmsft Jason, how are you?
Unfortunately, I do not have access to the site you shared here, but I am looking into this.

**Comment by robmazz** [comment]
@jarossmsft - I see that Nikita (IB PM) was on the escalation thread, she and I have pending updates scheduled for the topic. Will double-check that we are addressing this issue in the upcoming updates. Thanks!
