### ISSUE TITLE
Sync block is 1 Way - upload only

### ISSUE THREAD

**Issue by dobby10** [MicrosoftDocs/OfficeDocs-SharePoint#324]
This document should state the sync block ONLY blocks the ODFB Sync client from uploading a file. It does not block the sync client from downloading a file type that has been blocked.  (One way Sync Block, not a Two way block)
This behavior can result in data loss when a user edits a blocked file type in a sync folder, causing the file to be deleted from ODFB and unsynced locally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@dobby10, Thanks for this feedback. I thought I had already updated this article to clarify, but it looks like I never published the changes. Publishing them now!

**Comment by kaarins** [comment]
The updates have been published. The formatting of the note is off, but I've fixed it and it will go live soon. :)
