### ISSUE TITLE
User Profile Property mapping for "Work phone"  should be AAD Attribute "businessPhones"

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#3240]
The "Work phone" SharePoint User Profile Property is from AAD Attribute `businessPhones`, not `telephoneNumber` (which is an AD attribute).

PS it would be great if the internal names (eg. `WorkPhone`) of the properties were included on this page. Oh and the names of the columns in the user information list too ;) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ff426d-6bba-75ea-970b-03f16fe191b5
* Version Independent ID: 51db9ad2-9e46-4391-601a-062b640b00d2
* Content: [About user profile synchronization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/user-profile-sync)
* Content Source: [SharePoint/SharePointOnline/user-profile-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/user-profile-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @fowl2 James, how are you?

`telephoneNumber` is the property name used by _Azure AD Graph_ and ` businessPhones` is the one used by _Microsoft Graph_

See here for more information https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences

**Comment by fowl2** [comment]
Ahh could the docs be updated to be more specific about this then? 

Perhaps the existing column could be renamed to specify "Azure AD Graph" and a new "Microsoft Graph" column added.
