### ISSUE TITLE
Need correction of two vs three

### ISSUE THREAD

**Issue by suhood** [MicrosoftDocs/OfficeDocs-SharePoint#3241]
"There are three types of channels in Teams: standard and private."

Should include the third, which is shared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bc6df5-e361-4aeb-6eb4-20a8c017fa39
* Version Independent ID: 1c50aa81-9779-8725-963a-5dc94a60940d
* Content: [Teams and SharePoint integration - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites?bc=%252fteamss%252fbreadcrumb%252ftoc.json&toc=%252fteams%252ftoc.json)
* Content Source: [SharePoint/SharePointOnline/teams-connected-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/teams-connected-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by get-itips** [comment]
Hello @suhood looking into this

**Comment by Holland-ODSP** [comment]
@get-itips we corrected this one so we can close the ticket. Thank you.
