### ISSUE TITLE
Most of these pages are not seamless

### ISSUE THREAD

**Issue by X105Stidis** [MicrosoftDocs/OfficeDocs-SharePoint#3242]
So the bookmarks on the right are not consistent with the titles inside the page there for as a result the user using this page for their customer will waist time and be confused.  Also the breadcrumbs do not match either.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d22faa3-6e72-a382-cb45-fd2f98d735d2
* Version Independent ID: 8e095a7f-d8af-4105-6c4a-effe3d3856bc
* Content: [Add featured links to the SharePoint start page - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-links-list-on-sharepoint-home-page)
* Content Source: [SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-links-list-on-sharepoint-home-page.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @X105Stidis 
I think you refer to this?
![image](https://user-images.githubusercontent.com/36666927/163442616-591259b6-792c-45ac-9f83-7fb1e98def99.png)

I see those links matching the titles in the article.

Let me know if I understood you correctly, thank you

**Comment by get-itips** [comment]
Hello @X105Stidis could you see my last comment? thank you

**Comment by X105Stidis** [comment]
I did and replied.

**Comment by get-itips** [comment]
Hello @X105Stidis I am sorry but your reply isn't registered on the issue can you check? thanks

**Comment by X105Stidis** [comment]
I am not referring to that:

Referring to this example

***@***.***

**Comment by get-itips** [comment]
Hello @X105Stidis 
Please check your reply in the browser as the information you are trying to attach/talking about is not present. Thanks

**Comment by X105Stidis** [comment]
I am not referring to that:

Referring to this example

![Docs Links](https://user-images.githubusercontent.com/103443670/163857275-34f75ef7-f644-4bee-8f72-58cb665a6288.png)

**Comment by get-itips** [comment]
Thanks, The image is there now, will take a look and let you know

**Comment by X105Stidis** [comment]
Thank you

**Comment by get-itips** [comment]
Hello @X105Stidis 

I can see now, the page https://docs.microsoft.com/en-us/security/compass/network-containment-videos-and-decks you included a screenshot is hosted in another repository, to report an issue for that page you need to use this other link

https://github.com/MicrosoftDocs/security/issues

Do you have an issue similar to that one but in this repository? https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/

Thanks

**Comment by get-itips** [comment]
@scanum

**Comment by X105Stidis** [comment]
I am not referring to that:

Referring to this example

***@***.***
