### ISSUE TITLE
Registry Value Elaboration Missing

### ISSUE THREAD

**Issue by SabrinaKay** [MicrosoftDocs/OfficeDocs-SharePoint#3245]
I've notice there is missing information on configuring the registry item for this portion https://docs.microsoft.com/en-us/onedrive/use-group-policy#silently-move-windows-known-folders-to-onedrive There is no type of registry listed such as String value or DWORD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Thanks @SabrinaKay for your feedback that improves Docs!
