### ISSUE TITLE
Update info for Intune

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-SharePoint#3247]
Using Intune / EndPoint manager, it is also possible to use Devices > Windows > Administrative Template, to apply GPO.
However, please state correct value for setting OneDrive\Sync Admin Reports, and field Tenant Association Key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-health)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by HansBrender** [comment]
So you do not need a TAK (tenant Association Key) anymore. 
With OneDrive Insider  Vetrsion 22.050.0306.0001  there is a new  GPO Called [ Enabled sync Health Reporting for OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#allow-tenant-health-reporting-from-onedrive)
The name in this document is false, but the key is the rigtht one. 

With OneDrive Version 22.070.0403.0002 the old GPO "Sync Admin Reports"  with the TAK is no longer in the OneDrive Group Policies

**Comment by JohnMoor** [comment]
Thanks @HansBrender. Not sure though if it answers the question, though. The [documentation page](https://docs.microsoft.com/en-us/onedrive/sync-health) is not clear (to me).

> You can enable this setting in multiple ways:

Describes in to detail how to enable editing registry and gpedit.msc.

> Use [Group Policy](https://docs.microsoft.com/en-us/onedrive/use-group-policy#manage-onedrive-using-group-policy) or [administrative templates in Intune](https://docs.microsoft.com/en-us/onedrive/configure-sync-intune).

Just points to a page with general info on Admin Templates. It would help to list **exactly** which Policy Name to search for.

I tried searching for the following (and more phrases), but can't find the setting in Intune.

- Enabled sync Health Reporting for OneDrive
- EnableSyncAdminReports
- Allow tenant health reporting from OneDrive

BTW. The Onedrive settings in gpedit.exe are not found on my laptop under "Computer Configuration\Administrative Templates\OneDrive" I do see some in "Computer Configuration\Administrative Templates\Windows Components\OneDrive" but not the "Enable sync health reporting for OneDrive." as documented. Running the latest version of the OneDrive app (22.070)

**Comment by HansBrender** [comment]
Hey @JohnMoor , Did you move the GPO ADMX/ADML from the latest OneDrive to C:\Windows\PolicyDefinitions and the adml subdirectory? You find the actual admx/adml  inside the the [OneDrive files ](https://hansbrender.files.wordpress.com/2022/04/group-policy-location.png)

After installimng the neweset admx/adml files you find it in the[ Local Group Policy Editor](https://hansbrender.files.wordpress.com/2022/04/group-policy-onedrive-22.070.png)

"**Enable Sync Admin Reports**" are gone with 22.070. Now You have only  **Enabled sync Health Reporting for OneDrive**
There is still an error in the description:  "EnableSyncAdminReports" is not a GPO, it is the String in the [Windos Registry ](https://hansbrender.files.wordpress.com/2022/04/registry-old-and-new.png )

I have informed the Microsoft Product Group in Redmond about the errors
I cannot say anything about Intune, sorry

**Comment by adeejoseph** [comment]
Hi all -

We've made a few changes to the documentation that may not be reflected currently. **The new setting name is: Enable sync health reporting for OneDrive**

@hkusulja As Hans mentioned, you will no longer need TAK. You can find the updated policy here: [Enable sync health reporting for OneDrive](https://docs.microsoft.com/onedrive/use-group-policy#enable-sync-health-reporting-for-onedrive). 

@JohnMoor  - Thank you for the feedback. I will update the document to link directly to the **Enable sync health reporting for OneDrive** policy name for the Group Policy hyperlink. We will provide more details around Intune and update the article accordingly. If I understand correctly, would it be more helpful to list the Intune steps directly within the sync article? 

All the best,
AHJ

**Comment by hkusulja** [comment]
Hello, I am using Intune / Administration Templates.
Sync Admin Reports is there same as before, prompting for the Tenant Association Key
![image](https://user-images.githubusercontent.com/7479326/163966511-9c0bf82e-6449-4048-9279-d3c1b59e054a.png)

**Comment by HansBrender** [comment]
@hkusulja 
After The Admin Reports are out of PÜreview, then this Key is no longer valid after 90 days after GA
You should use [Enable sync health reporting for OneDrive](https://docs.microsoft.com/onedrive/use-group-policy#enable-sync-health-reporting-for-onedrive)

**Comment by adeejoseph** [comment]
> Hello, I am using Intune / Administration Templates. Sync Admin Reports is there same as before, prompting for the Tenant Association Key ![image](https://user-images.githubusercontent.com/7479326/163966511-9c0bf82e-6449-4048-9279-d3c1b59e054a.png)

@hkusulja Hi! I recommend that you deploy the new **Enable sync health reporting for OneDrive** policy to ensure that you will have a smooth transition when General Availability comes around. Although the SyncAdminReports policy is still supported at this moment, it will only be supported for 60 days after General Availability is announced. Avoid any disruptions by making the switch now.

**Comment by BigEaseGueldi** [comment]
Hi, I think the missing part is that EnableSyncAdminReports not yet available in Intune - opened a new issue for that: #3259
