### ISSUE TITLE
Why is the help for different versions mixed together?

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/OfficeDocs-SharePoint#325]
Don't you have respect for your customers? You're mixing "help" for two different versions  and you're not the best documentation writer. It's ambiguous at best. Add to that the fact that one of the software packages mentioned here isn't even release yet and even if it were, what guarantees you we'd be moving from 2016? Are you planning to drop support for your 2016 customers when 2019 ships? What's this all about? Why can't you just duplicate the page and change the title to 2019 and focus on that and that only. Your customers already have the task to come looking for help and when they do, it's poorly written. Not every customer can pay for the ridiculous licensing plus an IT department to run it, I thought maybe it's pricey because it's well thought out and easy to use, like Macs--well, like Macs were until recently, but, I see that's not the case. Confluence runs on a single server and help is clear..er. And, not every low-count user base wants to move to the cloud, and if they were, they might want options other than Azure and you have zero documentation for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca9caedd-719e-e80b-8052-c8b3a262d7ee
* Version Independent ID: 0c363923-2851-0f8c-0e59-654f20588479
* Content: [Install SharePoint Servers 2016 or 2019 Public Preview on one server](https://docs.microsoft.com/en-us/SharePoint/install/install-sharepoint-server-2016-on-one-server)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-on-one-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@vitaprimo Thank you for your feedback

I will get this passed on to the writing team. 

Thank you for reporting and making the docs better. Much appreciated.
