### ISSUE TITLE
Migration Offerings Table Incorrect

### ISSUE THREAD

**Issue by briggsb9** [MicrosoftDocs/OfficeDocs-SharePoint#3251]
The table under '[Migration Offerings](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide#migration-offerings)'  looks wrong. The headings and values make no sense in relation to each other. Would be great to fix this please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee6b3fe-cc73-cf65-8f91-aa75b2bda8f8
* Version Independent ID: a49a2330-4e5b-922e-870c-26aca6f63892
* Content: [Migrate file shares to SharePoint and OneDrive - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/fileshare-to-odsp-migration-guide)
* Content Source: [migration/Fileshare-to-ODSP-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/Fileshare-to-ODSP-migration-guide.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @briggsb9 Ben, thanks for your feedback, will propose to improve the table reading.
