### ISSUE TITLE
View File in Explorer

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#3254]
Hello,

Somehow in the article cannot find if using new EDGE the option "View File in Explorer" is being audited for file operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @lightupdifire I am looking into this

**Comment by get-itips** [comment]
Hello @lightupdifire 
This is the information I could get

"View in File Explorer" is an ODOpen protocol handler invocation of the sync client from the SharePoint web experience. Note: this feature only works if the user is already syncing the content they are attempting to view in explorer. The sync client does not make events visible in the Windows event viewer. As the sync client keeps the local folder in sync with the cloud folder/document library, the download activity would be auditable within SPO. For example: sync activity reports will show a list of all sync clients in an organization."

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum

**Comment by mkbond007** [comment]
Added [OneDrive sync reports in the Apps Admin Center - OneDrive | Microsoft Docs](https://docs.microsoft.com/en-us/onedrive/sync-health) to Learn More area in [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365 | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
