### ISSUE TITLE
MFA Requirements

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/OfficeDocs-SharePoint#3257]
If the tenant settings require MFA then the external user cannot accept the invite.

The user gets a "Failed to accept invitation" error message.

If they go directly to the link of the shared document library, it takes them through the MFA setup process for the tenant and then lets them in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @OffColour thanks for your feedback,
So I can reproduce, do you happen to be on the side of the tenant that requires MFA? Is it using security defaults or enabling MFA through Conditional Access Policies?
Thank you

**Comment by get-itips** [comment]
Also, please take this into account 

> If Azure AD B2B integration is enabled, recipients may be prompted to sign in or use a one-time passcode, depending on your organization's Azure AD B2B settings.

> More information about Azure AD B2B integration can be found at [SharePoint and OneDrive integration with Azure AD B2B](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration).

And 
> Invited people outside your organization are each given an account in the directory and are subject to Azure AD access policies such as multi-factor authentication.

**Comment by OffColour** [comment]
@get-itips 
Hi,

OK, so a full scenario.

Tenant A is our tenant and requires MFA
Tenant B is a third party
No B2B setup

1. Go to sharepoint site in tenant A
2. Invite user from tenant B to have permissions on a document library (not the site or its group)
3. User in tenant B clicks the invite link
4. User gets an error saying "Failed to login"
5. User goes directly to the link to the document library and gets prompted to login and setup MFA for their tenant A user for use in Tenant B.

So the issue seems to be that the invite link doesn't route correctly to send the user down the MFA setup path.

**Comment by get-itips** [comment]
@OffColour Thanks, I'll try to reproduce and see if we need to make any change to documentation

**Comment by get-itips** [comment]
Hello @OffColour how are you?

I followed the exact steps you shared with a Tenant A requiring MFA and a Tenant B with no B2B setup.

When Tenant B user received the _shared "DL" with you_ email, I was invited to follow the MFA registration process and I could access the library without any issues.

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
