### ISSUE TITLE
mismatch of the synced properties between documentation and user profile application

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/OfficeDocs-SharePoint#3258]
At the page https://docs.microsoft.com/en-us/sharepoint/user-profile-sync#properties-that-are-synced-into-sharepoint-user-profiles you find a table with properties which are synced into SharePoint user profiles. When I look in the SharePoint Admin Center at the User Profile Application in SharePoint Online I find more attributes that are marked by the icon which indicates that these are synced from AAD. So which of both sources is the truth? Example "Display Order" or "Web Site".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ff426d-6bba-75ea-970b-03f16fe191b5
* Version Independent ID: 51db9ad2-9e46-4391-601a-062b640b00d2
* Content: [About user profile synchronization - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/user-profile-sync#properties-that-are-synced-into-sharepoint-user-profiles)
* Content Source: [SharePoint/SharePointOnline/user-profile-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/user-profile-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @LennartaeHoefer how are you?

It's true the icon hints you to believe that the property is being synced from Azure AD, however, and I checked an On-Premises SharePoint to compare, those two that you mention have also that icon but they do not sync from local AD.
That leads me to believe the icon is not entirely correct and we should follow this article.

Thank you

**Comment by LennartaeHoefer** [comment]
Dear @get-itips, to get it right: the article we are talking about has the correct attributes named but the icon is not 100% correctly displayed in the SharePoint Admin Center for some of the attributes. Right?

**Comment by get-itips** [comment]
> Dear @get-itips, to get it right: the article we are talking about has the correct attributes named but the icon is not 100% correctly displayed in the SharePoint Admin Center for some of the attributes. Right?

That is my guess, but I'll try to confirm, Thank you

**Comment by get-itips** [comment]
I managed to pass this information to the SPO team.
@scanum
