### ISSUE TITLE
EnableSyncAdminReports not yet available in Intune

### ISSUE THREAD

**Issue by BigEaseGueldi** [MicrosoftDocs/OfficeDocs-SharePoint#3259]
Please note that the new "EnableSyncAdminReports" is not yet available as a computer configuration setting in an administrative template in Intune.

Best regards
Dirk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://docs.microsoft.com/en-us/onedrive/sync-health)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
@scanum

**Comment by hkusulja** [comment]
@get-itips any status on this? based on https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3247#issuecomment-1106234152 ?
