### ISSUE TITLE
Use System Center Configuration Manager to deploy the OneDrive sync client

### ISSUE THREAD

**Issue by sehtashamulhassan** [MicrosoftDocs/OfficeDocs-SharePoint#326]
incorrect information, both the installer link download the same installer file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@sehtashamulhassan  Thank you for this feedback. 

We apricate you pointing this link issue out to us. I will get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kaarins** [comment]
@sehtashamulhassan, we checked the installer links, and the Production link goes to build 18.172.0826.10. The Enterprise link goes to 18.111.0603.6. These are the latest builds listed in the release notes here https://support.office.com/en-us/article/new-onedrive-sync-client-release-notes. Maybe I am not understanding the issue correctly. If you can give me more details about the issue you're experiencing, I can investigate further. Thanks!
