### ISSUE TITLE
Update doc - Manage Loop components in SharePoint

### ISSUE THREAD

**Issue by gmykon** [MicrosoftDocs/OfficeDocs-SharePoint#3261]
In 
https://docs.microsoft.com/en-us/sharepoint/manage-loop-components#settings-management
change property name 
from 
IsCollabMeetingNotesEnabled
to
IsCollabMeetingNotesFluidEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c41c35b5-e159-ed6d-a9ff-bea0ef7f0736
* Version Independent ID: 2eca8e70-2e83-b100-890b-03b4377186e9
* Content: [Manage Loop components in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-loop-components)
* Content Source: [SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
