### ISSUE TITLE
View File in Explorer

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#3267]
Hello Team :)

Quick few questions:

1. Are there other ways to open the SharePoint Document library except:

1. Windows Explorer
2. Web browsers
3. OneDrive client

2. And is it possible to enable "View File in Explorer" per the SharePoint site?

We see that "View File in Explorer" is nice for Performance, at least we see that browsing sites via EDGE, to go to the needed folder takes about 1 minute to get to the file, but if use Explorer, then it is quite quick, but then there is no audit... So we are looking for a balance between security and performance.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
