### ISSUE TITLE
User based file type restrictions

### ISSUE THREAD

**Issue by darthstingy123** [MicrosoftDocs/OfficeDocs-SharePoint#327]
It would be great to be able to restrict which files can be uploaded/downloaded by certain groups.
As an educational institution, we would like to be able to set restrictions to prevent students and teachers from uploading certain file types i.e. bat files, but would like this restriction not to apply to IT Staff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@darthstingy123 Thank you for this feedback

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
