### ISSUE TITLE
Bad link in Related Topics -- can't find target

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-SharePoint#3272]
Section "Related Topics" has a link [Monitor apps for your SharePoint environment](https://docs.microsoft.com/en-us/sharepoint/monitor-apps). That link redirects to the article I'm reading (https://docs.microsoft.com/en-us/sharepoint/use-app-catalog), rather than an article on monitoring. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc1e9c0-2e35-3357-7f57-5bd02b0e10bc
* Version Independent ID: 1443a95a-ce5b-024d-d942-001b83bf8d8c
* Content: [Manage apps using the Apps site - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/use-app-catalog?source=docs)
* Content Source: [SharePoint/SharePointOnline/use-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-app-catalog.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback! @fselkirk
