### ISSUE TITLE
Search Scope when making a site a home site

### ISSUE THREAD

**Issue by wobba** [MicrosoftDocs/OfficeDocs-SharePoint#3274]
Docs mentioned that when you opt-out of site being a home site search scope is returned to "site" scope. It does not say scope will be "tenant" when you opt-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d3ba5d-e16b-0d9b-c623-37a75802d6ea
* Version Independent ID: 24f1a751-a2de-ee1d-a58e-c4a630d543fb
* Content: [Set a site as your home site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/home-site)
* Content Source: [SharePoint/SharePointOnline/home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/home-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello Mikael @wobba 
That is mentioned in

> Before you begin, make sure you've reviewed how to [plan, build, and launch a home site](https://docs.microsoft.com/en-us/sharepoint/home-site-plan).

->

> This becomes possible because the search scope for the home site searches the entire intranet instead of just the site collection like a typical site.

Thank you!

**Comment by wobba** [comment]
"The entire intranet" can be somewhat mis-leading as an intranet often is scoped to a hub-scenario and/or intranet content/news. As more entities are onboarded into the search experience phrasing it as "..home site searches all of Microsoft Search" might be better?

**Comment by wobba** [comment]
Doing good and happy to discuss the wording :)
