### ISSUE TITLE
Wrong content

### ISSUE THREAD

**Issue by nordtorp** [MicrosoftDocs/OfficeDocs-SharePoint#3275]
Description on this page does not match the options you are presented with in the UI!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3eaf13d-c0f2-5f45-8fe7-a647d3e0da40
* Version Independent ID: a644e742-fb10-6c67-dbf0-1c3469234e0f
* Content: [Connect to Box with Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-box-step1-connect)
* Content Source: [migration/mm-box-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @nordtorp the document has now been updated.
Thanks for your feedback!
