### ISSUE TITLE
Customized pages - migration 

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/OfficeDocs-SharePoint#3276]
In the article it is mentioned that "**During migration, these pages will be reverted to their uncustomized state**."
What is the meaning of this? Is that all customizations are gone post migration?
For example, if a content editor webpart with some html/script, that content will be migrated or not?
Can you please elaborate on this please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed29f0e-1cb7-613e-39ec-dd213b19206b
* Version Independent ID: d4c60a80-4f0d-5b2e-ea9d-77503ae3b534
* Content: [Migration Assessment Scan Customized Pages - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/migration-assessment-scan-customized-pages)
* Content Source: [migration/migration-assessment-scan-customized-pages.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/migration-assessment-scan-customized-pages.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jaganpt** [comment]
Any update on this?

**Comment by get-itips** [comment]
Hello @jaganpt 
That sentence refers to when the page (aspx) file is customized

> A common example is using a tool like SharePoint Designer to open a site and modify the default.aspx file of a site.

The best to understand which customized pages exists is to analyze the resultant report that article describes.

To understand webparts support, see https://docs.microsoft.com/en-us/sharepointmigration/spmt-supported-webparts

Hope this information helps you,

**Comment by jaganpt** [comment]
"During migration, these pages will be reverted to their uncustomized state."
So, if custom script feature not enabled, then all unsupported webparts will be gone. But the above statement saying that all pages will be reverted to their uncustomized state. Can you please confirm whether the above statement still valid?

**Comment by get-itips** [comment]
Hello @jaganpt While I try to confirm, did you already run the SMAT tool and analyze the report?

**Comment by jaganpt** [comment]
Yes.

**Comment by get-itips** [comment]
Hello, I got a reply and as Docs currently say, content editor web parts are supported in SPMT according to 

https://docs.microsoft.com/en-us/sharepointmigration/spmt-supported-webparts

Clearly, before every migration a report should be run and analyzed to review possible impact.

Hope this information helps you,
