### ISSUE TITLE
App Licenses for SharePoint Store

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint#3278]
Hello, community

The following article clearly states that all apps in the SharePoint Store is free.

https://docs.microsoft.com/en-us/sharepoint/manage-app-licenses?msclkid=005236cdcf3511ec96d00e5e761bb39f

> All apps in the [SharePoint Store](https://appsource.microsoft.com/marketplace/apps?product=sharepoint) are now free, so you no longer need to manage licenses. The Manage Licenses page in the classic SharePoint admin center no longer has any effect.

But, actually, some apps may require a valid license. As an example, adobe's add-ins clearly state that a valid license is required.

![image](https://user-images.githubusercontent.com/13634805/167325614-f3d1b3af-5376-436e-b852-97a4dc132d12.png)

https://appsource.microsoft.com/en-us/product/office/WA104381012?tab=Overview
> Licensing Information:
> This add-in requires a valid license of Adobe Acrobat Sign for enterprise edition.
 
Suggestion
-------------
Administrators can configure users to add apps themselves, but if there are apps that require valid licenses, administrators will want to avoid license violations. Therefore, shouldn't it be stated that a license may be required for each app? Plus, since there are apps that require a license, the statement **"All apps in the SharePoint Store are now free, so you no longer need to manage licenses."** is misleading and should be worded to encourage users to check each app's terms of use individually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8cbe11-ee04-b26f-bfd4-9334fac38b68
* Version Independent ID: 6a6fde7f-12c4-2ac5-24d0-7efe70da58c1
* Content: [Manage app licenses for a SharePoint environment - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-app-licenses?source=docs)
* Content Source: [SharePoint/SharePointOnline/manage-app-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-app-licenses.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by kefujino** [comment]
The following article also states that the application is free. We believe that this article should also state that some apps may require an additional valid license.

https://docs.microsoft.com/en-us/sharepoint/configure-sharepoint-store-settings
```
Next to App Purchases, do one of the following:

If you want users to be able to add apps, select Yes. (The setting uses the word "purchases" and mentions paid apps, but **all apps in the SharePoint Store are now free.**)
```

**Comment by MikePlumleyMSFT** [comment]
@kefujino Thanks for your feedback. I've updated the first article you mentioned to clarify that licensing and cost are up to the app developer, and removed the free statement from the second article.

**Comment by get-itips** [comment]
@scanum Article has been updated by @MikePlumleyMSFT and the published version now reflects this.
Thanks
