### ISSUE TITLE
Auto Tenant Mount + Limits

### ISSUE THREAD

**Issue by grangeway** [MicrosoftDocs/OfficeDocs-SharePoint#3280]
"Do not enable this setting for libraries with more than 5,000 files or folders."

This line is still quite confusing in the docs as it is not clear whether this is a only a strong recommendation or a functionality requirement i.e. it will break - and has come up multiple times in previous issues

It was discussed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1834

Where a PR was submitted and then @aarins stated that the recommendation is not to use this policy on libraries with more then 5000 files.

As previously stated by others, the service descriptions
https://docs.microsoft.com/en-gb/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#sync

We then have https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2523 which was opened asking for clarification then closed stating this is specifically about the tenant automount policy.

https://docs.microsoft.com/en-us/onedrive/deploy-on-windows?WT.mc_id=EM-MVP-5004228 states that you can auto-configure sharepoint site synchronisation by called odopen:/sync/... - and then also references that you can use the policy do this

The support article at https://support.microsoft.com/en-us/office/map-a-network-drive-to-a-sharepoint-library-751148de-f579-42f9-bc8c-fcd80ccf0f53?msclkid=6695f2cdcff211ecb04ae627ee977064 states that whilst you can use a network drive to map to sharepoint, that is uses a component linked to internet explorer which has been deprecated and recommends that sync is used instead

I'm therefore trying to understand whether:

a) it's OK to use odopen://sync... on a library with >5000

b) Whether the "do not enable this setting for libraries" on the auto mount policy is just a recommendation (or actually a fixed limit aka groove.exe)

c) Whether the behaviour of the client when connecting to the library that has been shared by the auto mount policy is different to the behaviour of the client when it has been sync'd via odopen:// url or manually

d) What happens if a tenant auto mount policy is enabled on a library with <5,000 files and then the library were to grow to exceed 5,000 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#configure-team-site-libraries-to-sync-automatically)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @grangeway 
I am looking into this

**Comment by get-itips** [comment]
Hello @grangeway I am still waiting on an answer from the right people

**Comment by get-itips** [comment]
> This line is still quite confusing in the docs as it is not clear whether this is a only a strong recommendation or a functionality requirement i.e. it will break - and has come up multiple times in previous issues

I received feedback from the Team that this is a soft limit / recommendation

**Comment by grangeway** [comment]
so I think that covers that A,B,D are soft limits - what about C on the implementation?

**Comment by get-itips** [comment]
Hello @grangeway how are you?

About C 

>If you enable this setting, the OneDrive sync app automatically syncs the contents of the libraries you specified as online-only files the next time the user signs in. The user isn't able to stop syncing the libraries.

**Comment by grangeway** [comment]
@get-itips - not too bad thanks. I guess that answers all the questions I raised - so to move this back to the documentation and whether we should just close this issue, or as it's caused confusion in the past, I'll suggest a proposal to reword the following:

_Do not enable this setting for libraries with more than 5,000 files or folders. Do not enable this setting for the same library to more than 1,000 devices._

To:

We recommend you consider whether automount is appropriate for your environment and libraries:
1.  **Do not** sync the same library to more then 1,000 devices, due to Windows Push Notification Services limits.
2.  The current recommendation is that this setting should not be used for libraries with more than 5,000 files or folders, and consideration should be given to the [SharePoint limits](https://docs.microsoft.com/en-gb/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#sync)
