### ISSUE TITLE
The create content type screenshot has changed

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SharePoint#3285]
The create content type screenshot has changed
![image](https://user-images.githubusercontent.com/69439002/168191788-73085505-db6f-415e-85d1-ac2edccd54ba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96aaa197-d69d-0cc1-aa52-7c1519442fc2
* Version Independent ID: a60ef9d8-b49f-c983-e4b6-0c30b388116c
* Content: [Create or customize a content type - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/create-customize-content-type)
* Content Source: [SharePoint/SharePointOnline/create-customize-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/create-customize-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
