### ISSUE TITLE
DisableAutoConfig missing from ADMX

### ISSUE THREAD

**Issue by benhbom** [MicrosoftDocs/OfficeDocs-SharePoint#3287]
The policy mentioned that sets DisableAutoConfig seems to be missing in the ADMX/ADML included with the latest version 22.089 and the other downloadable version 22.077. MC362284 said the policy is available in 22.065. I can set by registry, but this needs to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy#prevent-authentication-from-automatically-happening)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by benhbom** [comment]
Thanks, it's important for us to know if this feature is coming. If it is coming, it needs to be added to the ADMX, if it's no longer coming, the website and MC362284 need updating.

**Comment by get-itips** [comment]
Hello @benhbom I got confirmation that it will be included in future versions of the ADMX file and that for now, it can be set by registry, will propose an update to the article.

Thanks for your feedback!

**Comment by get-itips** [comment]
I was notified that the update to the ADMX is coming soon so the edit to the article won't be necessary

**Comment by get-itips** [comment]
@scanum
