### ISSUE TITLE
Set-SPOCustomFontCatalog does not work for Azure AD MFA-enabled accounts

### ISSUE THREAD

**Issue by adamstoffel** [MicrosoftDocs/OfficeDocs-SharePoint#3291]
After authenticating (`Connect-SPOService -Url https://contoso-admin.sharepoint.com`) using MFA following these instructions: https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps#to-connect-with-multifactor-authentication-mfa
When running the `Set-SPOCustomFontCatalog` command, a dialog prompts for credentials. Even when providing the right password, the command still fails with the error:
`Set-SPOCustomFontCatalog : The sign-in name or password does not match one in the Microsoft account system.`

As documented [here](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps) under Example 3, you must use the non-credential auth method for admin accounts with MFA. As recommended by Microsoft, current security defaults require MFA for all admins, so we are unable to bypass this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a81f0-e811-3420-5270-16bc0eb21baf
* Version Independent ID: 8012480a-b73b-21b1-7212-911064182582
* Content: [Support for organization fonts in PowerPoint for the web - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web)
* Content Source: [SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md)
* Service: **sharepoint-online**
* GitHub Login: @sheshachary
* Microsoft Alias: **v-shesna**

**Comment by get-itips** [comment]
Hello @adamstoffel Adam, how are you?
I tested this using SharePoint Online PowerShell version `16.0.22413.12000`

and I could succesfully set the custom font catalog, as output of the cmdlet I've got

>Succesfully uploaded custom fonts
Please note, if you would like to add, update, or remove any fonts, put all the fonts you would like uploaded, including the ones that didn't change, in to your font folder and rerun this command.

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum

**Comment by Eddga** [comment]
Hello @get-itips and @scanum

I'm in the same boat now as the OP. My Azure admin account is MFA enabled, too.
I have installed and used the Microsoft.Online.SharePoint.PowerShell module in version 16.0.22713.12000 with PowerShell version 5.1.22000.653 on Windows 11.
I successfully connect to the SPO service using `Connect-SPOService -Url https://contoso-admin.sharepoint.com`
When I use `Set-SPOCustomFontCatalog -LibraryUrl 'https://contoso.sharepoint.com/sites/OrgAssets/Fonts -FontFolder 'C:\Fonts'` and confirm all by pressing [A], a basic credential window pops up. When I insert my Azure admin username and password (no field for MFA) I get the error:
`Set-SPOCustomFontCatalog : The sign-in name or password does not match one in the Microsoft account system.`
`CategoryInfo          : NotSpecified: (:) [Set-SPOCustomFontCatalog], IdcrlException`
`FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.Online.SharePoint.PowerShell.SetSPOCustomFontCatalog`
I even tried creating and using an app password for the basic auth window. But that throws the same error.
I also noticed that when running this command in a non-elevated terminal I get the following error:
`Set-SPOCustomFontCatalog : Access to the registry key 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\StrongName\Verification\*,*' is denied.`
... even when I have run it as administrator before and said RegKey has been created.

Thanks in advance for any help on this.

**Comment by JiriManek** [comment]
Same thing here as Eddga ... we've raised a MS case and they are trying to find the way how to do it with MFA enabled accounts. So far they came back saying that we have to allow the Apps that don't use modern authentication. Which is no go with our security guys .. as taking that into effect might requires to keep this open for longer than 24 hours.

**Comment by Eddga** [comment]
> Same thing here as Eddga ... we've raised a MS case and they are trying to find the way how to do it with MFA enabled accounts. So far they came back saying that we have to allow the Apps that don't use modern authentication. Which is no go with our security guys .. as taking that into effect might requires to keep this open for longer than 24 hours.

I haven't tested it, but in the issue linked above #3498 the last comment says, that with the latest version 16.0.23019.12000 of the SPO module the issue was fixed and basic auth isn't used anymore in the cmdlet. You may want to update your module and test again.
