### ISSUE TITLE
Defaultfolderlocation should be in an array

### ISSUE THREAD

**Issue by timnottom** [MicrosoftDocs/OfficeDocs-SharePoint#3293]
The key for "DefaultFolderLocation" should be in an array to work. The example says otherwise, but when using the example as it is right now, it doesn't work.

Direct link: https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#defaultfolderlocation

What it says right now in the documentation:
```
<key>DefaultFolder</key>
  <dict>
    <key>Path</key>
    <string>(DefaultFolderPath)</string>
    <key>TenantId</key>
    <string>(TenantID)</string>
</dict>

```

it should be:
```
<key>DefaultFolder</key>
<array>
  <dict>
    <key>Path</key>
    <string>(DefaultFolderPath)</string>
    <key>TenantId</key>
    <string>(TenantID)</string>
  </dict>
</array>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos#defaultfolderlocation)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @timnottom I am looking into this

**Comment by get-itips** [comment]
Hello @timnottom Tim,
Can you please confirm if you still have to set it as an Array?
Thank you

**Comment by timnottom** [comment]
Hi @get-itips I've just tried it with macOS Monterey 12.5, Onedrive 22.151.0717 and yes it still needs to be in an array.

**Comment by get-itips** [comment]
Hello @timnottom Tim, I asked the team and they suggested to open a support request as that was not experienced by others, in any case, if, as a result of the support analysis, an update is required we will be impacting the article.
Thanks for your feedback.
