### ISSUE TITLE
Another setting missing from ADMX

### ISSUE THREAD

**Issue by benhbom** [MicrosoftDocs/OfficeDocs-SharePoint#3296]
The settings DisableNucleusSync is missing from the current ADMX included with the latest OneDrive client 22.099.0508.0001.

Please confirm if this will also be added to the ADMX? For now we will set via registry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment]
Hello @benhbom I am looking into this

**Comment by benhbom** [comment]
In the ADMX included with 22.121.0605.0002, DisableNucleusSync is now there, but the policy name is shown at DisableListSync with valuename DisableNucleusSync.

<policy name="DisableListSync" class="Machine" displayName="$(string.DisableListSync)" explainText="$(string.DisableListSync_help)" key="SOFTWARE\Policies\Microsoft\OneDrive" valueName="DisableNucleusSync">

**Comment by benhbom** [comment]
`<policy name="DisableListSync" class="Machine" displayName="$(string.DisableListSync)" explainText="$(string.DisableListSync_help)" key="SOFTWARE\Policies\Microsoft\OneDrive" valueName="DisableNucleusSync">`

**Comment by get-itips** [comment]
Great find @benhbom thanks for sharing

**Comment by get-itips** [comment]
@scanum
