### ISSUE TITLE
Specify agent group for Scans

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-SharePoint#3297]
Is there a way to specify which agent group to use for "Scans" just as you can when doing "Migrations"? Or does Scans assume that all Agents have line of sight access to all shares so it chooses a Agent group randomly / or always Default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d251718d-fb13-abb8-6c2e-55b3b1fa6eef
* Version Independent ID: 2695af9b-f62a-8bae-b59d-113903365560
* Content: [Step 2: Scan and assess file shares using Migration Manager - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-fileshare-scan-assess)
* Content Source: [migration/mm-fileshare-scan-assess.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-fileshare-scan-assess.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
