### ISSUE TITLE
Underscore isn't escaped correctly.

### ISSUE THREAD

**Issue by morganthrapp** [MicrosoftDocs/OfficeDocs-SharePoint#33]
The underscore in the example path `/_layouts/newdwp.aspx` isn't escaped. This causes the path to render in italics, without the leading underscore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1658f0a4-c470-1236-df0c-b7c51306bf57
* Version Independent ID: 23728a25-8e4c-1703-2431-9b91484097d2
* Content: [Configure and deploy web parts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/configure-and-deploy-web-parts)
* Content Source: [SharePoint/SharePointServer/sites/configure-and-deploy-web-parts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/configure-and-deploy-web-parts.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
I've cleaned the formatting for the URL and sentence, and then republished.
