### ISSUE TITLE
Shortlink to site blocked to public access

### ISSUE THREAD

**Issue by AHelsby** [MicrosoftDocs/OfficeDocs-SharePoint#3303]
The https://aka.ms/ODSP-MM shortlink seems to be restricted - I get prompted to sign in and then access is denied to the sharepoint link afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e08e70-cb60-d860-0003-4b094b220ee9
* Version Independent ID: f1e08e70-cb60-d860-0003-4b094b220ee9
* Content: [Mover retirement timeline - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-retirement-timeline)
* Content Source: [migration/mover-retirement-timeline.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mover-retirement-timeline.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by Absoblogginlutely** [comment]
AH! So it is, Thank you.
Confirmed with my admin account vs my normal account. Might be worth noting this in the documentation as it's not obvious this is required. There's a lot of documentation about the migration program that does not need to be logged in as admin so this is a bit confusing
