### ISSUE TITLE
Typo at point 6 example code

### ISSUE THREAD

**Issue by PhilvdHeide** [MicrosoftDocs/OfficeDocs-SharePoint#3305]
Typo in example code at Point 6: 
Add-SPOOrgAssets**Libary** -LibraryUrl https://constosofonts.sharepoint.com/FontLibrary -OrgAssetType OfficeFontLibrary -CdnType Public
There is a missing "r" in the cmdlet. Should be "Add-SPOOrgAssetsLib**r**ary"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a81f0-e811-3420-5270-16bc0eb21baf
* Version Independent ID: 8012480a-b73b-21b1-7212-911064182582
* Content: [Support for organization fonts in PowerPoint for the web - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web)
* Content Source: [SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md)
* Service: **sharepoint-online**
* GitHub Login: @sheshachary
* Microsoft Alias: **v-shesna**

**Comment by get-itips** [comment]
Thanks for your feedback! already fixed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/4a50294f539d2380d2cc3ef6b118d703ee1b8a36
