### ISSUE TITLE
User Profile Timer Job failed

### ISSUE THREAD

**Issue by waqa5** [MicrosoftDocs/OfficeDocs-SharePoint#331]
SCOM health explorer keep showing the below error and there is no clear guidelines what this error is about. We tried to restart the timer job and administration services, and everything else seems fine. I suppose you should cover this error as well in this article.

User Profile Service Timer Job Failed - [SERVER_NAME] (TimerJob instance for UserProfile Service 2013)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f7be136-2beb-b9ab-eb36-ddc428d81e1c
* Version Independent ID: 20129468-489d-69bb-a49d-137787d7df87
* Content: [System Center Operations Manager knowledge articles for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/system-center-operations-manager-knowledge-articles)
* Content Source: [SharePoint/SharePointServer/technical-reference/system-center-operations-manager-knowledge-articles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/system-center-operations-manager-knowledge-articles.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@waqa5 Thank you for this feedback

I want to make sure your timer error is addressed properly. Support has more resources than we do here and can handle this to resolution. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
