### ISSUE TITLE
Clarification on domain allow setting expectation

### ISSUE THREAD

**Issue by massiveloop** [MicrosoftDocs/OfficeDocs-SharePoint#3310]
Hello,
I cannot find confirmation anywhere in the docs and need to confirm if the results I'm getting (which I want) are due to an issue and will eventually break or by design for the SharePoint file store connected to a Teams group...

**Org-level settings:**
External sharing (SPO+1drive) = Anyone  (and using a security group allowed to share externally)
General users cannot create guest accounts (Azure setting)

**Test Site settings:**
External Sharing = New and existing guests
Limit sharing by domain is CHECKED and specific Allowed domains applied
Internal user thats sharing is in the external sharing security group applied at the org level (noted above). 

Even though the site is set to only allow new and existing guests only, when sharing to an email within the site's allowed domain list BUT NOT a guest in the tenant, the link is delivered and the external person  (who is not prompted for anything other than an OTP email code) is able to open the file. 

The biggest thing I wanted for this site was to eliminate the ability to use the Anyone link, which was achieved(it was greyed out as an option) by using the allowed domain list at the site settings, but I would have assumed that the external person would have been stopped for not being able to authenticate as a guest but they got to the file. Before this, I tried selecting 'Anyone' at the site level thinking that would apply to 'anyone' on the allowed domains but that was not the case because it allows the anyone (unauthd) link to be generated too which completely bypassed the domain list restriction (as noted in the setting page). 

I could not find any confirmation of this behavior I experienced when searching the Msft docs and other sites for ways to simply turn off the 'Anyone' link creation ability for certain sites and sort of stumbled across this solution when playing with settings. 

**Can you confirm that I can rest on this continuing to work as stated or have I uncovered a glitch that will eventually be fixed and break my solution?** 

If it will break, what options are there to prevent the Anyone link (unauthed) from being used on certain sites? Not finding any PowerShell or anything else for this. 

Thanks for your time, 
~Graham

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by massiveloop** [comment]
Hello--I was just circling back on this inquiry. Thank you for any insight you can provide here. 
~gC

**Comment by get-itips** [comment]
Hello @massiveloop 
How are you?

> the link is delivered and the external person (who is not prompted for anything other than an OTP email code) is able to open the file.

Did this created a guest in the tenant? I guess not, right?

As the description for new and existing guests says, "Guests must sign-in or provide a verification code", I think that, when guests creation is disabled for regular users, SPO falls back to verification code

Then I think your external person falls into the "ad hoc external recipient" described here

https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-sharing-in-targeted-release

**Comment by get-itips** [comment]
Hello @massiveloop Could you see my comment here? Thanks

**Comment by massiveloop** [comment]
@get-itips --Hi, correct it did not create a guest user. Sounds like the behavior I experienced then is by-design for the way we set it up. 
If there is no easier way to eliminate the 'anyone' sharing links on specific sites then I suppose this can be closed. 
Thanks
~gC

**Comment by get-itips** [comment]
Thanks for returning and sharing your feedback!
