### ISSUE TITLE
"Where's my data?" Link not resolvable via DNS

### ISSUE THREAD

**Issue by TestinProd123** [MicrosoftDocs/OfficeDocs-SharePoint#3311]
[Where's my data?](https://o365datacentermap.azurewebsites.net/) Link is not resolvable via DNS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f3baf1-62a6-348a-8f7d-25ba27d7b292
* Version Independent ID: 520aaaa6-1d41-9712-0dd6-67a8ff586f3b
* Content: [Cloud data security measures in SharePoint & OneDrive - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/safeguarding-your-data)
* Content Source: [SharePoint/SharePointOnline/safeguarding-your-data.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/safeguarding-your-data.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback! @TestinProd123
