### ISSUE TITLE
The picture at the top of the page doesn't show up well in dark mode

### ISSUE THREAD

**Issue by dpearcemsft** [MicrosoftDocs/OfficeDocs-SharePoint#3313]
[Enter feedback here]
The picture at the top of the page doesn't show up well in dark mode.
![image](https://user-images.githubusercontent.com/88451734/172169372-10dbaa96-6c96-45a6-9dac-9ce68fed0eef.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a81f0-e811-3420-5270-16bc0eb21baf
* Version Independent ID: 8012480a-b73b-21b1-7212-911064182582
* Content: [Support for organization fonts in PowerPoint for the web - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web)
* Content Source: [SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md)
* Service: **sharepoint-online**
* GitHub Login: @sheshachary
* Microsoft Alias: **v-shesna**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
