### ISSUE TITLE
OneDrive Recycle Bin and Indexing

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/OfficeDocs-SharePoint#3316]
This text needs some explanation:

The Recycle Bin is not indexed and therefore searches do not find content there. This means that an eDiscovery hold can't locate any content in the Recycle Bin in order to hold it.

I am absolutely able to run discovery searches for items in the OneDrive recycle bin. Findings are documented here:

https://office365itpros.com/2022/06/10/onedrive-for-business-recycle-bin/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762932d1-8eef-ea51-c51d-a40ed88b8237
* Version Independent ID: d0ef71ba-21b3-1352-85b5-63d7882782da
* Content: [OneDrive retention and deletion - OneDrive](https://docs.microsoft.com/en-us/onedrive/retention-and-deletion)
* Content Source: [OneDrive/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @12Knocksinna Tony, I am looking into this, thanks for your feedback.

**Comment by captainhook** [comment]
I am unable to search for items in OneDrive recycle bin - no retention policies in place. @12Knocksinna can you confirm you are still able to do this?

**Comment by 12Knocksinna** [comment]
I can search for deleted documents in the OneDrive recycle bin. Yes.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
