### ISSUE TITLE
PerformanceReport.csv has a lot more columns than described on this page

### ISSUE THREAD

**Issue by ConaxLiu** [MicrosoftDocs/OfficeDocs-SharePoint#3319]
Hi, The PerformanceReport.csv I'm seeing in the Report\Details folder is very much different from what this page is describing. The report has a lot more columns:
Timestamp,LiveTimeSeconds,PackedPacks,UploadedPacks,SubmittedPacks,MigratedPacks,CompletedPacks,PackedFiles,UploadedFiles,SubmittedFiles,MigratedFiles,PackedBytes,UploadedBytes,SubmittedBytes,MigratedBytes,Speed_Packing,Speed_Uploading,Speed_Processing,Speed_Migration,PackTimePercent_MetaReading,PackTimePercent_FileReading,PackTimePercent_DiskWriting,TasksSchemaMigration,TasksWaittingPacking,ActivePackEngine,CurrentPackedPackages,PacksInUploading,CurrentUploadedPacks,JobsInProcessing,UploadingParallalism,CPU%,Memory bytes,IO_Write ops/sec,IO_Read ops/sec,Network Received byte/sec,Network Send byte/sec

This page does not describe these columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9a5578-afdc-5a5b-4255-85c4deb33b6c
* Version Independent ID: 92e37fdd-c0d1-2fc0-4c98-989d292fcddf
* Content: [Assess SharePoint Migration Tool reports - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/using-the-sharepoint-migration-tool-reports#hub-site-report)
* Content Source: [migration/using-the-sharepoint-migration-tool-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/using-the-sharepoint-migration-tool-reports.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ConaxLiu** [comment]
Thanks for the reply, Manuela.

Am I correctly understand that the community that maintains the documentation is then different from the community that develops and maintains the product?

Kind regards
