### ISSUE TITLE
Typos on this page

### ISSUE THREAD

**Issue by geordonp** [MicrosoftDocs/OfficeDocs-SharePoint#3320]
[Enter feedback here]
1. One of the sidebars has group misspelled as "gorup".
2. Near the end of the document, this sentence refers to internet, but I think it should be intranet. "Every site in the internet..."
3. The last paragraph has a visible <Token> tag and icon, which seems out of place.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
fixed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/3321
