### ISSUE TITLE
Users and Permissions missing

### ISSUE THREAD

**Issue by Kav7** [MicrosoftDocs/OfficeDocs-SharePoint#3323]
In step 2, "On the Site Settings page, under Users and Permissions, click Site Permissions", this section & option does not exist in the SharePoint site settings I am looking at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e8d0f1-f6a3-82c0-e46b-974e167fe5b1
* Version Independent ID: 22b0a6c2-2e90-34ab-c3c8-bd7ba721c791
* Content: [Customize SharePoint site permissions - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions)
* Content Source: [SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/customize-sharepoint-site-permissions.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback! Proposing to update the article
