### ISSUE TITLE
NEO Site Solution Page - Link broken

### ISSUE THREAD

**Issue by RyanSil** [MicrosoftDocs/OfficeDocs-SharePoint#3324]
On this [page](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub), the NEO Site Solutions Page link is broken. 

Broken link: [NEO Site Solutions Page](https://[provisioning.sharepointpnp.com](https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239)/details/3df8bd55-b872-4c9d-88e3-6b2f05344239)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3739a833-d9b7-baee-2d17-26cba48d7da8
* Version Independent ID: 0618f0c0-e98a-d932-fb29-65a4852fe90b
* Content: [Overview of the Microsoft New Employee Onboarding sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub)
* Content Source: [SharePoint/SharePointOnline/provision-neo-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/provision-neo-hub.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Thanks for your feedback!
