### ISSUE TITLE
MC 340783 was posted to GCC tenants when the feature is not available to government plans?

### ISSUE THREAD

**Issue by airdouglas** [MicrosoftDocs/OfficeDocs-SharePoint#3326]
MC 340783 was posted to GCC tenant when the feature is noted as not being available for Government plans.  Should the documentation be updated because it will be available?  Or was the message center post made in error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a81f0-e811-3420-5270-16bc0eb21baf
* Version Independent ID: 8012480a-b73b-21b1-7212-911064182582
* Content: [Support for organization fonts in PowerPoint for the web - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web)
* Content Source: [SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md)
* Service: **sharepoint-online**
* GitHub Login: @sheshachary
* Microsoft Alias: **v-shesna**

**Comment by get-itips** [comment]
Hello @airdouglas Sean, how are you?
Unfortunately i do not have access to a GCC tenant to verify, however, upon checking 365 Roadmap, the availability is, as you say, only for Worldwide (Standard Multi-Tenant) so the MC was probably not intended to GCC tenants.
Thanks for your feedback!

**Comment by get-itips** [comment]
@scanum
