### ISSUE TITLE
sites vs standard channels

### ISSUE THREAD

**Issue by lukaszkruk** [MicrosoftDocs/OfficeDocs-SharePoint#3329]
I'm confused about the 10th bullet point on this page. It reads:

Channel site - The SharePoint site that is created when you create a standard (other than General), private or shared channel in a team. Only owners and members of the private or shared channel have access to this site.

However, the illustration below shows all standard channels linked to one single SharePoint site. 

So is each standard channel linked to a separate SharePoint site, or are all the standard channels in one Team linked to a single site?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bc6df5-e361-4aeb-6eb4-20a8c017fa39
* Version Independent ID: 1c50aa81-9779-8725-963a-5dc94a60940d
* Content: [Teams and SharePoint integration - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/teams-connected-sites)
* Content Source: [SharePoint/SharePointOnline/teams-connected-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/teams-connected-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by lukaszkruk** [comment]
I'm supposed to go through tenant level customer support to amend SharePoint documentation? Are you sure you got this right?
