### ISSUE TITLE
Incorrect instruction to setup Agents for Migration Manager

### ISSUE THREAD

**Issue by kc-va541-web** [MicrosoftDocs/OfficeDocs-SharePoint#3331]
https://docs.microsoft.com/en-us/sharepointmigration/mm-setup-clients#set-up-an-agent 
Step 1 of the instructions does not specifically tell you tell log into the machine with the account that will have read access to the source, but this is show on the agent setup's splash screen as a requirement. In Step 7, you cannot enter the credentials that will provide access to all  the files being migrated, but rather only the password for the currently logged in user, which is shown on the setup screen.

**Comment by get-itips** [comment]
Hello @kc-va541-web 

I tested this,

About read access to the source, this is already indicated at the beginning of the article

> When you run the setup file, you are prompted for two sets of credentials. You need SharePoint Admin credentials to access your destination, and Windows credentials with read access to the source. 

It is true that you can only enter the password of the current loggend on user, will propose an edit to the article.

Thanks for your feedback!
