### ISSUE TITLE
Error on Overview of the Microsoft New Employee Onboarding sites

### ISSUE THREAD

**Issue by LukeRiches** [MicrosoftDocs/OfficeDocs-SharePoint#3341]
[Enter feedback here]
Error on NEO sites solution page section, link not working as site can't be reached "Check if there is a typo in provisioning.sharepointpnp.com. DNS_PROBE_FINISHED_NXDOMAIN"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3739a833-d9b7-baee-2d17-26cba48d7da8
* Version Independent ID: 0618f0c0-e98a-d932-fb29-65a4852fe90b
* Content: [Overview of the Microsoft New Employee Onboarding sites - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/provision-neo-hub)
* Content Source: [SharePoint/SharePointOnline/provision-neo-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/provision-neo-hub.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by scanum** [comment]
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!
