### ISSUE TITLE
Error in hyper link

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#3348]
The link "[Learn more about the Microsoft Search experience for users](https://support.office.com/article/d5ed5d11-9e5d-4f1d-b8b4-3d371fe0cb87)." is broken. needs to be fixed.
thanks
Bradley

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f89b7-afd4-1b65-f3ad-c802c7dd5a47
* Version Independent ID: 0f3e61c4-6b03-dccb-6067-09ed98228f62
* Content: [Difference between classic & modern search experiences - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search)
* Content Source: [SharePoint/SharePointOnline/differences-classic-modern-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/differences-classic-modern-search.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @obhayes I can follow that link successfully, can you check now? Thanks

**Comment by get-itips** [comment]
@scanum
