### ISSUE TITLE
Anonymous Access

### ISSUE THREAD

**Issue by ffhirata** [MicrosoftDocs/OfficeDocs-SharePoint#335]
Is there a possibility to configure a sharepoint site that are access free of Microsoft Sign in? It is not clear for me, because it is annoying for the purpose of guest users accessing communication site. They want only to access the contents and if it is needed to sign in, they will be not interested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b52267-3e1c-f371-a64a-29429151e207
* Version Independent ID: b39fef1f-8e0f-519c-bbe4-415b1c6d584c
* Content: [Create an external business-sharing site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-external-business-sharing-site#monitoring-external-user-activity)
* Content Source: [SharePoint/SharePointOnline/create-external-business-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-external-business-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@ffhirata Thank you for this feedback

I am unsure on the answer for this. I will get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@ffhirata Anonymous access to a site is not available in SharePoint Online.

**Comment by scanum** [comment]
@ffhirata  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
