### ISSUE TITLE
More / better examples please

### ISSUE THREAD

**Issue by jmbainbridge** [MicrosoftDocs/OfficeDocs-SharePoint#3350]
[Enter feedback here]
Could more detail be given on how to populate the CSV file - especially for OneDrive

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [Bulk upload tasks into Migration Manager using a CSV or JSON file - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @jmbainbridge how are you? There is currently an example about OneDrive in the CSV, can you please detail what would be the example missing from this article that you think it would be good to include? Thank you

**Comment by get-itips** [comment]
Hello @jmbainbridge could you see my last message here? Thanks

**Comment by get-itips** [comment]
@scanum
