### ISSUE TITLE
Request for adding the Note for Wiki Page Library support = Yes

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/OfficeDocs-SharePoint#3351]
Wiki Page Library did not show up in drop list when select SP server as migration source.
Could you add the note below for Supported by SPMT field of 119 WikiPageLibrary. 
Wiki page library is supported in whole site migration. Not supported in single list selection, because this template of library often has innate references to other lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390c33f7-7e70-6741-2a61-9538b87bec0a
* Version Independent ID: c3be3fb4-c28b-5513-651a-fe8b174a0a33
* Content: [SharePoint Migration Tool supported SharePoint List templates - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-migration-supported-list-templates)
* Content Source: [migration/sharepoint-migration-supported-list-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/sharepoint-migration-supported-list-templates.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @sasaito 
I could verify what you say here on my lab, I'll analyze how are we going to add this to the article.
Thank you
