### ISSUE TITLE
Instructions for accessing crawl logs

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/OfficeDocs-SharePoint#3352]
While this was asked and addressed previously, there are currently no Microsoft instructions available and correctly working for how to access the crawl logs. Please advise. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e17f59-b027-4994-a928-4ef9f5db58cd
* Version Independent ID: 10c23c98-44d1-c53d-a6ab-86345cafed85
* Content: [Check logs, limits and reports - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/check-logs-limits-and-reports)
* Content Source: [SharePoint/SharePointOnline/check-logs-limits-and-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/check-logs-limits-and-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @aandrew129 I am looking into this.
