### ISSUE TITLE
SPMT - Outdated link to C++ runtime

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#3355]
Unless there's a really good reason to point people to a specific outdated RC, this page should be updated to link to [Microsoft Visual C++ Redistributable latest supported downloads
](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues - Migrate to Microsoft 365](https://docs.microsoft.com/en-gb/sharepointmigration/spmt-install-issues)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/spmt-install-issues.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback @fowl2
