### ISSUE TITLE
SPMT - Support link 

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#3356]
The last link on this page is to "[SharePoint Migration Tool Feedback and Support Forum](https://social.technet.microsoft.com/Forums/en-US/home?forum=SharePointMigrationTool)", which is now archived:

![image](https://user-images.githubusercontent.com/12844147/177323494-1e89ebaa-289e-4009-8d93-a16cf6a90711.png)

Unfortunately the [link in that announcement](https://docs.microsoft.com/en-us/answers/products/m365) doesn't seem to have any section for SPMT.

Could this page please be updated with the current location for support?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use SharePoint Migration Tool - Migrate to Microsoft 365](https://docs.microsoft.com/en-gb/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/how-to-use-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback! @fowl2
