### ISSUE TITLE
Can we connect to sharepoint associated to MS Teams from ADF?

### ISSUE THREAD

**Issue by harithamaddi-ops** [MicrosoftDocs/OfficeDocs-SharePoint#3360]
Hi Team,

We tried following the prerequisites as mentioned in this [article]([https://docs.microsoft.com/en-us/azure/data-factory/connector-sharepoint-online-list?tabs=data-factory#prerequisites](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdata-factory%2Fconnector-sharepoint-online-list%3Ftabs%3Ddata-factory%23prerequisites&data=05%7C01%7CMaddi.Haritha%40pepsico.com%7C5379384f79614e4b5d1008da536e8274%7C42cc3295cd0e449cb98e5ce5b560c1d3%7C0%7C0%7C637914031346543778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bhxi0jx%2BOXBO9zXB0REqOOh5zgXHs4ZwioopOScdcY8%3D&reserved=0).) but unable to connect from ADF to our MS Teams site as shown below. 

<img width="310" alt="image" src="https://user-images.githubusercontent.com/63502781/177950932-f2b29268-6af1-496b-979c-03eee0b01864.png">

Please suggest if this is feasible to do or restricted from MS Teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e46ced8-c494-5828-13b1-68d9118e838e
* Version Independent ID: 044b07e7-3af2-6a3e-bec8-d46f7e6fdc1c
* Content: [Manage settings and permissions when SharePoint and Teams are integrated - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-teams-sharepoint-experiences)
* Content Source: [SharePoint/SharePointOnline/manage-teams-sharepoint-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-teams-sharepoint-experiences.md)
* Service: **sharepoint-online**
* GitHub Login: @AtkinE
* Microsoft Alias: **evanatkin**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
