### ISSUE TITLE
No mention of SharePoint 2019

### ISSUE THREAD

**Issue by will73** [MicrosoftDocs/OfficeDocs-SharePoint#3367]
It would be nice is there is some guidance for customers that want to migrate SharePoint 2019 to SharePoint Online.  My understanding that the SPMT doesn't support SP 2019, but an estimated release date or some type of recommendations on 3rd party tools would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to Microsoft 365 - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/migrate-to-sharepoint-online.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @will73 
I am looking into this

**Comment by get-itips** [comment]
Hello @will73 
I am looking into this

**Comment by get-itips** [comment]
@will73 

This roadmap item has just showed up about SPMT & 2019 with the expected availability

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=93408

**Comment by get-itips** [comment]
@scanum
