### ISSUE TITLE
SPMT PowerShell module online docs "404 - page not found"

### ISSUE THREAD

**Issue by rva3** [MicrosoftDocs/OfficeDocs-SharePoint#3369]
When attempting to view the online version of SPMT PowerShell modules located at https://docs.microsoft.com/en-us/powershell/module/spmt/* linked from the article at https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets all of the cmdlet pages display an "404 - Page not found".  The expected behavior is to view the web pages of each SPMT cmdlet located at the following location https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/spmt/spmt-ps/spmt/*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Migrate to SharePoint and OneDrive using PowerShell cmdlets - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/overview-SPMT-PS-cmdlets.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @rva3 
Issue is now resolved, thanks for your feedback!

cc @traya1
