### ISSUE TITLE
Enable the preview

### ISSUE THREAD

**Issue by nicksequeira** [MicrosoftDocs/OfficeDocs-SharePoint#337]
Organization wide share settings seems to be broken in some places, specifically Additional Settings, enable the preview and set sharing per-site to bypass. I wasn't even able to find an acceptable user or group using the lookup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@nicksequeira Thank you for this feedback

I will get this information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dplotnikov** [comment]
hello, @nicksequeira I've made a couple clarifications and they'll be live as soon as repo owner will merge it, so it should be more accurate from a content perspective. as for your mentioned issues, it looks more like a product issue and not as a content one.

**Comment by nicksequeira** [comment]
Right on, glad to see y'all working on it. I'll check it out in a few weeks
thanks
