### ISSUE TITLE
 Update the IB mode to 'Mixed' mode instead of 'Inferred' mode.

### ISSUE THREAD

**Issue by eaarora-ms** [MicrosoftDocs/OfficeDocs-SharePoint#3370]
The latest IB document needs to be updated to reflect the new name of 'Inferred' IB mode instead of Mixed. This caused an ICM on our team last week. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef03ccd-fd27-4724-75c1-eec90be8ad8b
* Version Independent ID: a9e393d2-9bcc-3814-2654-bd40f23d5306
* Content: [Use information barriers with OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/information-barriers?source=docs#information-barriers-modes-and-onedrive)
* Content Source: [OneDrive/information-barriers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/information-barriers.md)
* Service: **one-drive**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@eaarora-ms - thanks for the feedback, this has been updated and published.
