### ISSUE TITLE
IE mode in Edge supportability

### ISSUE THREAD

**Issue by jarossmsft** [MicrosoftDocs/OfficeDocs-SharePoint#3371]
We need verbiage in this article if IE mode is Edge is a supported configuration for M365 services especially for SharePoint Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d9effc-1329-b03d-b6d6-f0d7ff88a6de
* Version Independent ID: 4f6bfbe6-b14f-baa7-e80d-20f7ca8a3427
* Content: [Prepare your SharePoint environment for the retirement of Internet Explorer 11 for Microsoft 365 apps and services - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/prepare-ie11)
* Content Source: [SharePoint/SharePointOnline/Prepare-IE11.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/Prepare-IE11.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @jarossmsft Jason,

The article already has an note about that

>Internet Explorer 11 and **Edge IE compatibility mode** are not supported in Team sites, OneDrive personal sites, or any other types of SharePoint content sites. Microsoft recommends exploring Microsoft Edge as the replacement for Internet Explorer 11.

Thanks

**Comment by get-itips** [comment]
@scanum
