### ISSUE TITLE
Permissions requirements

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#3374]
It used to be that a GA or SharePoint admin could change the URL of the site. The system is now requiring GAs to manually add themselves to the site collections owners list. Support said this is by design. It produces the following error if this is not done:

This site address can't be changed.  Unknown error 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-site-address)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @danmyhre Dan,
I tested this, I used a SharePoint Administrator, not SC owner of the target site, and I could successfully change the URL.
Please let me know if I understood you correctly.

**Comment by get-itips** [comment]
@danmyhre Could you see my last comment?

**Comment by danmyhre** [comment]
@get-itips Support was wrong. This was a defect that was rolled out and has now been resolved. There was a service incident about it today. You can close this update.
