### ISSUE TITLE
Handling error 0x8004de81 on OneDrive client sync with Sharepoint Server Subscription Edition

### ISSUE THREAD

**Issue by JMyklebust** [MicrosoftDocs/OfficeDocs-SharePoint#3375]
When I'm setting up OneDrive client sync with a Sharepoint Server Subscription Edition I get error ``0x8004de81`` when trying to connect.
The error message is not terribly helpful here:
![image](https://user-images.githubusercontent.com/48317811/179739636-4eedaac3-9d69-476e-8c71-e57a73b4ad45.png)

I've specified the required Group Policy as defined here:
https://docs.microsoft.com/en-us/sharepoint/install/configure-syncing-with-the-onedrive-sync-app#using-group-policy

This is also seems to be the same issue described in #1946 (which is where my search lead me), thought that seems to have been closed with a message telling to open a service ticket for the tenant... 
That is not a very helpful feedback since no tenant is actually involved here (it's on-prem Sharepoint after all)....

There is basically no information anywhere on this error code, no leads on what to check....

We are running SharePoint Server Subscription Edition on Windows Server 2022.
I'm pretty sure it's impossible to be more up to date there.
OneDrive client is build 22.131.0619.0001 and as far as I can see that is the latest main release of the client.

This is not time critical, that's why I'm opening an issue here.
But it is fairly frustrating to get a completely undocumented error code, with no useful help text at all.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JMyklebust** [comment]
Which tenant are you talking about on a self-hostet Sharepoint Server?
This is not Office 365 but SharePoint **_Server_** Subscription Edition....
