### ISSUE TITLE
No mention of Learning Pathways in build-learning-and-training-experiences-for-employees.md

### ISSUE THREAD

**Issue by eemancini** [MicrosoftDocs/OfficeDocs-SharePoint#3376]
I was reviewing https://docs.microsoft.com/en-us/sharepoint/build-learning-and-training-experiences-for-employees and see the guidance only included Viva Learning. What about including content for Learning Pathways, especially considering the future integration? For the past few years, our recommendations with clients have been to transform training documents into SharePoint pages so they can be surfaced within Learning Pathways playlists. Viva Learn currently only supports documents in a library, not SharePoint pages. Until Viva Learning can support SharePoint pages, there is still a giant need to surface this training content. After spending years transforming data from documents into pages, it would be a very hard sell to have organization turn their pages back into documents which is where they started years ago.

**Comment by get-itips** [comment]
Hello @eemancini Emily, I'll try to pass this feedback to the article's author.

**Comment by Holland-ODSP** [comment]
Thanks for your feedback @eemancini . You are right, we should mention other learning opportunities for people who don't use Viva and just to be more through in explaining our offerings. We also have this article that will need some updating too.

https://docs.microsoft.com/en-us/sharepoint/build-learning-and-training-experiences-for-employees

I'll work with the writers in this area to include more guidance on other paths to creating training solutions.

**Comment by get-itips** [comment]
@scanum
