### ISSUE TITLE
Microsoft One Drive - Silently Configure User Accounts - Breaks login feature (In OneDrive) and persists after reinstall

### ISSUE THREAD

**Issue by seamaster300** [MicrosoftDocs/OfficeDocs-SharePoint#3379]
I ran the powershell on my computer Windows 11 Pro (build 22000.795) with OneDrive (22.131.0619.0001).  Before running, I was logged out of OneDrive, and the app closed.  After running the powershell, I am unable to sign in. Clicking sign in does not do anything. Clicking settings and attempting to add an account does nothing.

I've tried uninstalling, and reinstalling One Drive with the latest build .0002. Rebooted same issue.

Tried uninstalling and reinstalling office.  Rebooted same issue.

Tried uninstalling, and reinstalling One Drive with the stable build .0001. Rebooted same issue.

Tried deleting the registries created with the script, but they were not created.

Tried disabling group policies that would prevent OneDrive startup, but that was also not enabled and had no effect. Rebooted same issue.

Tried SFC /scannnow and it found corrupt files and successfully fixed them. Rebooted same issue.

Tried running OneDrive in compatibility mode. Rebooted same issue.

Tried clearing ALL cached windows credentials. Rebooted same issue.

I'm ready to format the computer after running this script. Is there anything else that would have been changed or that should be added to the reference docs that should be considered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by HansBrender** [comment]
Did you have checked all registry keys described in the document?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
