### ISSUE TITLE
Hyperlink problem on this post

### ISSUE THREAD

**Issue by billyoungs** [MicrosoftDocs/OfficeDocs-SharePoint#338]
The hyperlink was linked to article for SharePoint 2016, but this article is about SharePoint 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4051e8c-ef8d-1812-efdc-a65bdc1a6364
* Version Independent ID: 1659ed3b-750c-5136-64f4-0b6fa3053e15
* Content: [Get started with upgrades to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/get-started-with-upgrade-2019)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/get-started-with-upgrade-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/get-started-with-upgrade-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@billyoungs Thank you for this feedback

I will get this hyperlink issue over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by RussC19** [comment]
@AndreaBarr 

This looks to have already been completed.
![image](https://user-images.githubusercontent.com/47165527/53377488-c3892980-3994-11e9-8878-487e1c49adfa.png)
