### ISSUE TITLE
Egnyte domain that you will use for testing field requirement

### ISSUE THREAD

**Issue by rf-bcit** [MicrosoftDocs/OfficeDocs-SharePoint#3380]
Hello Team,

The "Egnyte domain that you will use for testing" field required an entry. The instructions here stated 'Leave this field empty'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Version Independent ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Content: [Step 1: Connect to Egnyte - Migrate to Microsoft 365](https://docs.microsoft.com/en-US/sharepointmigration/mm-egnyte-step1-connect?WT.mc_id=365AdminCSH_spo)
* Content Source: [migration/mm-egnyte-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-egnyte-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for reporting! @rf-bcit
