### ISSUE TITLE
Missing Policy = Disable Filesync NGSC

### ISSUE THREAD

**Issue by Akadelvo** [MicrosoftDocs/OfficeDocs-SharePoint#3381]
Seems, that the policy for disabling file sync is missing on that site.
admx reference: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.OneDrive::PreventOnedriveFileSync

Can you confirm and fix that?

Best regards
Akadelvo

**Comment by get-itips** [comment]
Hello @Akadelvo can you please post here the article under Docs that you are referring to? thank you

**Comment by HansBrender** [comment]
@get-itips : Thats are old group Policies, thgat are not coming with the current admx/adml files with each update.
@gacarini : can you check that: This are Windows Components Group Policies and that should be also on the doccs, if they are still valid or not
1) Save documents to OneDrive by default
2) Prevent the usage of OneDrigve for File storage on windows 8.1
3) Prevent the usage of OneDrive for file storage
4) Prevent OneDrive from generating network traffic until the user signs in to OneDrive
5) prevent OneDrive files from syncing over metered Connections

**Comment by get-itips** [comment]
Thanks @HansBrender can you please open another issue so we can check those on a separate thread from this one?

@Akadelvo this is the article you should use as a reference for OneDrive's GPs https://docs.microsoft.com/en-us/onedrive/use-group-policy I could't find DisableFileSyncNGSC in the admx file for version 22.166.0807.0002, please let me know if I understood you correctly.

**Comment by get-itips** [comment]
@Akadelvo could you see my comment? thanks

**Comment by get-itips** [comment]
@scanum
