### ISSUE TITLE
what is the recommended tool for tenant to tenant OneDrive/SPO migrations?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SharePoint#3384]
This article states that mover between two O365 tenants will be retired in early 2023 (next year). Can you add a faq item that explains what the plan is for this feature? It doesn't look like the migration manager supports this workload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e08e70-cb60-d860-0003-4b094b220ee9
* Version Independent ID: f1e08e70-cb60-d860-0003-4b094b220ee9
* Content: [Mover retirement timeline - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mover-retirement-timeline)
* Content Source: [migration/mover-retirement-timeline.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mover-retirement-timeline.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @Mike-Crowley Mike, I am looking into this.

**Comment by get-itips** [comment]
The information is already being added in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3384
Thank you!

**Comment by get-itips** [comment]
Information was merged into the article, it should appear in the published version soon.
Thanks for your feedback!

**Comment by Mike-Crowley** [comment]
There is now native "Cross-tenant OneDrive migration", licensed per-user, per migration.


The article could point to this link: https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration?view=o365-worldwide#licensing
