### ISSUE TITLE
Supportability of feature - SharePoint admin center- Tenant rename

### ISSUE THREAD

**Issue by Rangeball** [MicrosoftDocs/OfficeDocs-SharePoint#3386]
Could supportability statements be added to the documentation. It's unclear if this feature which is in "Preview" will be supported by Microsoft.

The documentation should be updated to make "Preview" clear and consistent in meaning e.g. see section here for example that provides more clarity for a different Microsoft 365 preview capability https://docs.microsoft.com/en-us/windows-365/public-preview#what-you-need-to-know.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name?source=docs)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Rangeball I am looking into this.

**Comment by get-itips** [comment]
Hello, feedback was received by the Docs team about adding an explanation of public preview for SharePoint articles like this one.
