### ISSUE TITLE
The setting is activated for the next user that is deleted as well as any users that are in the process of being deleted

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#3387]
Hello,

About this "The setting is activated for the next user that is deleted as well as any users that are in the process of being deleted. The count begins as soon as the user account was deleted in the Microsoft 365 admin center, even though the deletion process takes time."

If we take as an example this scenario:

1. Used AD Connect to sync users from on-premise
2. Current policy is set for 30 days
3. User "Test.UserA" was deleted two weeks ago July 20, 2022, so user retention left like ~15 days
4. We change now policy from 30 to 90 days

Question: the user "Test.UserA" retention will be extended to ~75 days?

Somehow not clear :)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users - OneDrive](https://docs.microsoft.com/en-us/onedrive/set-retention)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @lightupdifire 

> User "Test.UserA" **was deleted** two weeks ago July 20, 2022, so user retention left like ~15 days

I think the retention will not be extended because:

> The setting is activated for the next user that is deleted

**Comment by lightupdifire** [comment]
You think? :) So there could be another flow?

пт, 19 авг. 2022 г., 18:38 Andres Mariano Gorzelany <
***@***.***>:

**Comment by get-itips** [comment]
Hello @lightupdifire 

I've been digging into this to see if there is a way to actually check the retention of a single deleted onedrive/user, what you can use is

`Get-SPODeletedSite -IncludePersonalSite:$true`

and check the _Days remaining_ and also maybe _Deletion time_ properties.

and also revisiting the example you suggested: what I was trying to say in my last answer is that, in your example, you already mentioned that the user was indeed deleted so the retention applied was the one at the time of the user deletion.

Hope this information helps you,
