### ISSUE TITLE
The text for the site creation setting is out-of-date

### ISSUE THREAD

**Issue by Kath-Anne** [MicrosoftDocs/OfficeDocs-SharePoint#3389]
The text now displays "show the options to create a site in SharePoint and create a shared library from OneDrive".

I assume the underlying permission change is the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29978b1-a400-bacb-1330-55ed3d652053
* Version Independent ID: eae9fd16-57fc-1a80-3ce9-9b34b68eb1e0
* Content: [Manage site creation in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation)
* Content Source: [SharePoint/SharePointOnline/manage-site-creation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-site-creation.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello, thanks for your feedback!
