### ISSUE TITLE
That worflow manager must use for SharePoint 2019 ?

### ISSUE THREAD

**Issue by paololec** [MicrosoftDocs/OfficeDocs-SharePoint#339]
That worflow manager must use for SharePoint 2019 ?
"SharePoint Workflow Manager Preview" is the right product or I need to use "Workflow Manager 1.0 Cumulative Update 5" ? Missing install documentation..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716557e6-63fd-f26f-dd96-a2565081e03a
* Version Independent ID: 6360722b-3970-776b-3440-4a1b984edf0a
* Content: [Overview of SharePoint Workflow Manager in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/governance/configure-sharepoint-workflowmanager-2019)
* Content Source: [SharePoint/SharePointServer/governance/configure-SharePoint-WorkflowManager-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/configure-SharePoint-WorkflowManager-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @kirks
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@paololec Thank you for this feedback

I am not sure what workflow manager you need. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@paololec You will need to use Workflow Manager 1.0 CU5 and Azure ServiceBus 1.1. This is the same product you can use with SharePoint 2013/2016.

**Comment by tseward** [comment]
@scanum you can close this one as this page was removed.
