### ISSUE TITLE
Please make this config setting granular so admins can choose which specific folders, not just apply to all three.

### ISSUE THREAD

**Issue by RyanSpoonerJCB** [MicrosoftDocs/OfficeDocs-SharePoint#3397]
Please make this config setting granular so admins can choose which specific folders, not just apply to all three.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by CallumCrowley** [comment]
@RyanSpoonerJCB this is an issue list for problems with the documentation rather than an area for suggestions, the best place for product suggestions is the [Microsoft Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/e3f04660-2c1c-ec11-b6e7-0022481f8472).
