### ISSUE TITLE
clarifying what groups can scan

### ISSUE THREAD

**Issue by jaraizer** [MicrosoftDocs/OfficeDocs-SharePoint#3398]
Add a note:

"When trying to complete a scan of a file share. Only Agents in the default group are utilized."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a94b401-5a3e-7b47-f264-1b1bea8cbccb
* Version Independent ID: a7f30ee0-4a71-a37d-50ec-2b0d44cbdf72
* Content: [Agent groups in Migration Manager' - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-agent-targeting)
* Content Source: [migration/mm-agent-targeting.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-agent-targeting.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Updating -- thanks Jarai!

**Comment by JoanneHendrickson** [comment]
@jaraizer    

This has been added to the Troubleshooting document and to the Step 2 topic in the File Share solution.
