### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mike-pshell** [MicrosoftDocs/OfficeDocs-SharePoint#3399]
The article states "it takes a while for them to be crawled and indexed".  I understand that this is a tenant by tenant issue, can you provide guideline on how long this is expected to take?  i.e. when should we raise this to support if content is not being scanned.  Is this minutes? 10 of minutes?  Hours?

This may be better in a separate article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Mark new files as sensitive by default - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@SanjoyanM can you help?

**Comment by SanjoyanM** [comment]
@mike-pshell : Your question is more related to crawling and searching of content in SPO. This feature inherits the same limitations which   crawling and searching of content in SPO has.

**Comment by mike-pshell** [comment]
I struggle to find a document that describes the "expected" timelines for a crawl/search for DLP

**Comment by SanjoyanM** [comment]
I agree but that is not related to labels. Probably you need to raise the question in DLP forum

**Comment by scanum** [comment]
Hi @SanjoyanM Hope all is well. Is there an update on this issue? Thanks.

**Comment by SanjoyanM** [comment]
@MikePlumleyMSFT and @scanum : Just FYI we DO NOT have any customer facing SLA for crawling and search in general. Also I am NOT the PM for crawling and search. You can Neetha Tuluri <netulu@microsoft.com> for this generic question. 

Fo now since this question is not specific to this feature BUT a very generic question on SharePoint hence I request to close this issue.

**Comment by MikePlumleyMSFT** [comment]
As Sanjoyan mentioned above, it's best to post this to a DLP forum or as in issue on a DLP article. Closing this one out.
