### ISSUE TITLE
FOD should be disabled when using DiskSpaceCheckThresholdMB.

### ISSUE THREAD

**Issue by kenmoritest** [MicrosoftDocs/OfficeDocs-SharePoint#340]
FOD should be disabled when using DiskSpaceCheckThresholdMB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@kenmoritest Thank you for this feedback

I will get this information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, any updates on this?

**Comment by kaarins** [comment]
We say to use DiskSpaceCheckThresholdMB on devices that don't have FOD enabled. With FOD, files don't take up space on disk, so DiskSpaceCheckThresholdMB isn't needed. For Windows 10 devices, we recommend FOD.
