### ISSUE TITLE
Missing details on full disk access requirement

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#3400]
In order for KFM to work, the OneDrive app needs full disk access. Please add details on how to deploy that via Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40801de8-cfb0-7f2d-ac91-c7b4b3b8c1f4
* Version Independent ID: 8d2445aa-5934-16fb-6b29-81d5b4d4c59e
* Content: [Deploy and configure the new OneDrive sync app for Mac - OneDrive](https://docs.microsoft.com/en-us/onedrive/deploy-and-configure-on-macos)
* Content Source: [OneDrive/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @danmyhre I am looking into this

**Comment by get-itips** [comment]
Dan, is this what you are looking for?

https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-macos

> Full disk access: Your options:
Not configured: Intune doesn't change or update this setting.
Allow: Allows the app to access all protected files, including system administration files. Apply this setting with caution.
Block: Prevents the app from accessing these protected files.

**Comment by get-itips** [comment]
And I also found this

https://docs.microsoft.com/en-us/onedrive/redirect-known-folders-macos

>This app requires Full Disk Access, which can be granted and deployed by IT admins.

**Comment by danmyhre** [comment]
Hi - I don't think the first one is specific to the OneDrive app, which is what needs the access.

The second one is what needs the details added.

**Comment by get-itips** [comment]
Hello @danmyhre 
The last link I shared already has the Full Disk Access requirement mentioned.

Please let me know if I understood you correctly. Thanks

**Comment by get-itips** [comment]
@danmyhre Have you seen my last comment? Thanks

**Comment by danmyhre** [comment]
Hi - yes, I know the requirement is there...the issue is there is no documentation on how to actually deploy that. See original comment.

**Comment by danmyhre** [comment]
@get-itips Looks like some additional info would still be beneficial here. For the device restriction configuration, please provide:
- App Name
- Identifier Type
- Bundle ID
- Code Requirement
