### ISSUE TITLE
I could not get this to work,  as written.   Is there something missing?  

### ISSUE THREAD

**Issue by ruderod** [MicrosoftDocs/OfficeDocs-SharePoint#3401]
I could not get this to work,  as written.   Is there something missing?  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharing-reports)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ruderod I could follow the instructions in the article, at what point you couldn't follow the procedure?

**Comment by get-itips** [comment]
Closing for now @scanum
