### ISSUE TITLE
OneDrive command line requires OneDrive to be off/not running

### ISSUE THREAD

**Issue by bkibbeyWork** [MicrosoftDocs/OfficeDocs-SharePoint#3403]
When running this OneDrive /getpin command (and others) - it returns because "Another instance of OneDrive is already running. Shutting down." but this is not mentioned in the documentation at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116a7d33-b79a-f07d-b9de-d032d805c8d5
* Version Independent ID: 94908ca2-5edc-eb8c-b8a2-72cf61969dc7
* Content: [Set Files On-Demand states on Mac - OneDrive](https://docs.microsoft.com/en-us/OneDrive/files-on-demand-mac)
* Content Source: [OneDrive/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @bkibbeyWork 
I could verify, I'll propose to add that to the article.
