### ISSUE TITLE
Typo on limitation #2 

### ISSUE THREAD

**Issue by jdunbar-ecm** [MicrosoftDocs/OfficeDocs-SharePoint#3404]
Under limitations for point 2 it says
"The current root site can't be connected to a Microsoft 365 group."

This is suggesting that you could have a M365 group connected Team Site as your root site but can not ever change it?

This must be a typo... should it not say "The new root site can't be connected to a Microsoft 365 group." ? You can not change a root site to a group connected Team Site, therefore, this doesn't make sense. The current root site could never be a Microsoft 365 group connected site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @jdunbar-ecm I am looking into this
