### ISSUE TITLE
Page contradicts itself about whether the "Source DocLib" field is required

### ISSUE THREAD

**Issue by benrifkah** [MicrosoftDocs/OfficeDocs-SharePoint#3405]
The [JSON file section](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration?redirectSourcePath=%252farticle%252f9183b289-f1cf-4c69-8240-8bfcdf3809bb#use-a-json-file-for-bulk-upload) says it is **required** as with CSV files:

> As with a CSV file, the minimum required values are Source, **Source DocLib**, Target Web, and Target DocLib.

(emphasis mine)

However, the [CSV file section](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration?redirectSourcePath=%252farticle%252f9183b289-f1cf-4c69-8240-8bfcdf3809bb#use-a-csv-file-for-bulk-upload) says it is **optional**:

<html>
<body>
<blockquote>

Column content | Description
-- | --
... | ...
Column 2 "Source DocLib" | **_Optional._** Enter the name of the SharePoint Server document library that you're migrating. If you leave this field empty, all document libraries will be migrated. This column needs to be empty when migrating from a local file share.

</blockquote>
</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [Format your JSON or CSV file for data content migration - SharePoint - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration?redirectSourcePath=%252farticle%252f9183b289-f1cf-4c69-8240-8bfcdf3809bb)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback
