### ISSUE TITLE
Use OneDrive policies to control sync settings should be more clear whether feature is available in OneDrive personal

### ISSUE THREAD

**Issue by ductoanvo** [MicrosoftDocs/OfficeDocs-SharePoint#3408]
Hi, I'm working on a ReactJs project and using OneDrive to sync project when I'm not ready to commit to the remote repository. Since I've found this doc shows that I can use Policy to exclude a folder from syncing (like the `node_modules` folder). 

Unfortunately, this documentation haven't indicated whether this feature is available on OneDrive Personal despite the `"adm"` folder already on my computer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use OneDrive policies to control sync settings - OneDrive](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by CallumCrowley** [comment]
@ductoanvo this documentation is specifically for OneDrive for Business which is a separate product. This is the documentation for OneDrive personal:

[OneDrive help & learning](https://support.microsoft.com/onedrive)

**Comment by HansBrender** [comment]
@ductoanvo some Group Policies also work in OneDrive Personal, but there is no Group Policy to exclude a folder. Only exclude  files. The GPO name is"Exclude specific kinds of files from being uploaded"

**Comment by get-itips** [comment]
Thanks @CallumCrowley and @HansBrender for adding more information.
