### ISSUE TITLE
Some Confusing Sentences and Statements due to wording and lack of context

### ISSUE THREAD

**Issue by digitalzomb** [MicrosoftDocs/OfficeDocs-SharePoint#3410]
The second paragraph and first numbered paragraph leave a lot of room for confusion when reading it for me. In fact, to really _think_ I understand the issue, I've had to read this article ten times. It's worded strangely, and it's hard to explain -- but I think it needs to be broken down better to help people looking to implement this option.

1. We need to be able to see the requirements broken out of a paragraph and into bullet points.
2. We also need to be more clearly able to identify what the actual impact of this setting will be, and what it won't be. Again -- bullet points help here.

- This sentence needs more context: "However, this doesn't work if external sharing is explicitly authorized in a DLP rule and the lack of sensitive content that goes against the policy rules has been verified."
  - **What doesn't work, the PowerShell flag to mark new files as sensitive? 
  - **What does it mean to "explicitly authorize" external sharing in a DLP rule? A link to an example of a rule that would break this or specific explanation would be very helpful
  - **"and the lack of sensitive content that goes against the policy rules has been verified" seems out of place here, so it's saying if there's no sensitive content it won't be sharable, or is this just an 'even if' statement compounding on the explicit authorization caveat. 

The next paragraph is the most confusing, however, and should be broken down better:

"Since any content that isn't explicitly checked in a DLP policy will not be blocked from being externally accessed after this setting is enabled, you must ensure any content that needs to be shared externally is covered by at least one DLP policy. If you prefer to require explicit authorization in a DLP policy for a site to be shareable, no further action is needed after this setting is enabled. If not all locations with content that needs to be shared externally are already covered by an existing DLP policy, you must add them to at least one policy. The easiest way to do this is to create a DLP policy that includes all SharePoint or OneDrive locations, that has any "content contains" condition selected, and that specifies no actions, no alerts, no notifications and no reports."

- "Since any content that isn't explicitly checked in a DLP policy will not be blocked from being externally accessed after this setting is enabled, you must ensure any content that needs to be shared externally is covered by at least one DLP policy. + The easiest way to do this is to create a DLP policy that includes all SharePoint or OneDrive locations, that has any "content contains" condition selected, and that specifies no actions, no alerts, no notifications and no reports"
   - **These two together appear to be a bad security recommendation, but are also confusing. You recommend that in order to protect any sites that can be externally shared, it needs to be covered by a DLP policy to prevent initial access. You then go on to recommend creating an essentially blank, actionless policy that will ultimately potentially grant external access to all documents potentially prior to being scanned by the real DLP policies that take action. What's the point of this suggestion?

- "If you prefer to require explicit authorization in a DLP policy for a site to be shareable, no further action is needed after this setting is enabled. If not all locations with content that needs to be shared externally are already covered by an existing DLP policy, you must add them to at least one policy."
    - The "if not all" reads in a confusing manner, as most people will initially read it as "If not, all locations" because the prior sentence is a potential way one might have things configured. This requires a re-read halfway through the sentence to understand the requirement. 
    - The explicit authorization piece comes up again without an example, and it says no further action is needed -- so all set right? However, the previous paragraph said "this doesn't work if external sharing is explicitly authorized in a DLP rule and the lack of sensitive content that goes against the policy rules has been verified," which now confuses me to think that using "explicitly authorized in a DLP rule" does work?

Hopefully someone can relate, I've had a few other people read it an scratch their heads. 

Given my confusion, maybe someone can clarify my question in return for my feedback: 
I have DLP policies that "Restrict access or encrypt the content in M365 Locations," set to "Block only people outside your organization" when "Content is shared from M365 with people outside my organization," and contains certain PII value. I am covering all OneDrive and SharePoint sites, but then may EXCLUDE certain people or sites. Will those excluded people/sites still be able to share externally with guests, or will the guests be consistently unable to access as a DLP scan never occurs since they're excluded from the policy?

Or, if I specifically target sites and drives, will sites and drives not covered by a DLP policy be stuck on "This file is being scanned right now," because they're not part of a policy? I ask this because of the very odd suggestion to create a DLP policy that covers everything, looks for arbitrary data, and does nothing at all in the first numbered paragraph on the page...

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Mark new files as sensitive by default - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @digitalzomb I am looking into this
