### ISSUE TITLE
Maximum value documented for Excel document size a crawl component can download is wrong

### ISSUE THREAD

**Issue by saregbesola** [MicrosoftDocs/OfficeDocs-SharePoint#3412]
This is related to limit and boundaries article for SP 2016, 2019 & SPSE. The maximum value documented for Excel document size a crawl component can download in the article below does not match the value returned when the following command is executed in 2016 and above.
$s = Get-SPEnterpriseSearchServiceApplication
 $s.GetProperty("MaxDownloadSizeExcel") 

This returns 4 for SP 2016 & above but returns 3 for SP 2013. Kindly update the documentation to reflect the correct value.

Article: https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-limits-2019#search-item-size-limits

**Comment by get-itips** [comment]
Thanks for your feedback!
