### ISSUE TITLE
Broken link on Intelligent Intranet Overview

### ISSUE THREAD

**Issue by alandillon** [MicrosoftDocs/OfficeDocs-SharePoint#3414]
Process of creating an intranet link is broken.

https://resources.techcommunity.microsoft.com/intelligent-intranet/align/

![image](https://user-images.githubusercontent.com/3331097/186504599-0d9aa1e1-4843-462c-9358-a275f6d08ee6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab8a948-7330-5238-1c04-4a95db4cda5d
* Version Independent ID: 4597b4bb-3cc6-99b2-ca68-2006cb7c73a5
* Content: [Intelligent intranet overview - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/intelligent-internet-overview)
* Content Source: [SharePoint/SharePointOnline/intelligent-internet-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/intelligent-internet-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @alandillon Alan,
I am looking into this.
