### ISSUE TITLE
Organization Assets Library needs to clearly state the limitations.

### ISSUE THREAD

**Issue by IP-dbruce** [MicrosoftDocs/OfficeDocs-SharePoint#3417]
This page needs to clearly point out the following limitations:

1.) Templates from the organization assets library **do not** work in Word on the web or Excel on the web.  They only work on PowerPoint on the web.
2.) Inserting images from your organization assets library is limited to SharePoint Online.  You will not see these images if you attempt to insert a picture in PowerPoint, Word, or Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/organization-assets-library)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @IP-dbruce 

Thanks for your feedback, I analyzed your suggestions

About 1)

The article currently clearly states the required versions for Office Templates and does not mention  Word on the web or Excel on the web

>**Office templates:** When a user creates a new Office document, they can select the tab for your organization to see the available templates. The following Office apps are supported:
**Word, Excel, or PowerPoint desktop apps. Microsoft 365 Apps Version 2002 or later is also required.**

And then mentions

>**PowerPoint on the web.** Templates aren't available from the New menu. Instead, users need to go to the PowerPoint start page and select Office Template Library. For the organization assets library to appear to a user in PowerPoint on the web, the user must be assigned a license to Office 365 E3 or E5.

About 2) 

The article does not mention that inserting images will be available from Office apps/web

> Images such as photos and logos: When a user adds a web part to any modern page **in SharePoint** and that web part opens the file picker, the user can select "Your organization" in the left pane to browse the libraries you've specified.

Hope this clarifies it to you, thanks again!

**Comment by IP-dbruce** [comment]
When you know the exact limitations and read the article I admit, the article never specifically promises to do anything other than what is stated.  However, I think what you are failing to realize is what a customer looking for a digital asset management solution incorrectly assumes when reading this article.   
   "If your organization needs to store and manage files for all your users to use, you can specify one or more document libraries on a SharePoint site as an "organization assets library."  
     When a customer reads the above statement we think a centralized repository for storing images and office document templates.   And then of of course there is the integration with office apps.  I would argue that the typical office worker seeks to use corporate images in PowerPoint and Word far more often than modifying a SharePoint page.  It seems a blatantly obvious expectation that the logical expectation is to consume images from within the Office applications.  
    The bullet regarding PowerPoint for the web was mistaken as a statement of exception in how to execute rather than an announcement that Microsoft didn't bother to add similar functionality into Word for the web or Excel for the web.
    We were not the first to make this mistake as evidenced from others' feedback.  All I am asking is that you explicitly call out what is NOT supported in Word for the web or Excel for the web.  And call out that the consumption images is limited to SharePoint only.  

     If these two items were clear I wouldn't have wasted my time setting up the Organization Asset Library.

**Comment by get-itips** [comment]
@IP-dbruce  Thanks for sharing your point of view, I'll review if an update to the article is required
