### ISSUE TITLE
Features that only work in IE table

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#342]
This table is missing the "Edit List" (opens in Sharepoint Designer) button being disabled in browsers other than IE. 

Also the table is a bit confusing as it doesn't make it clear if a feature is completely unavailable or just less functional.

* "Open with Access" is disabled, whereas;
* "Open in Excel" requires one extra click in Edge and two extra clicks in Firefox
*  "Connect with Outlook" is the obvious feature for the "StssyncHandler" row, but seems to work fine in Edge

Thanks =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d1b075-d17b-510d-f886-4f5deed4cc9e
* Version Independent ID: 336f78e0-78e2-0a55-5e1b-2bf41072a0cb
* Content: [Plan browser support in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/browser-support-planning-0)
* Content Source: [SharePoint/SharePointServer/install/browser-support-planning-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/browser-support-planning-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@fowl2 Thank you for this feedback

I will get this missing table information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by kilasuit** [comment]
@tseward any updates on this being added as of yet?

**Comment by scanum** [comment]
@fowl2  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by fowl2** [comment]
@scanum note there is no notification of commits/PRs referencing issues on Github.   

This update still doesn't cover "Edit List".

But I'd argue that the way this information is presented could be more useful if it was written for the perspective of someone trying to phase out IE and evaluating the impact. As it is now it's like it's trying to help allow/block activex controls or something.

While I'm here, the reference to 32bit Internet Explorer should probably mention something about IE's 'Enhanced Protected Mode' which is how most people could end up with a 64 bit IE.

Thanks =)

**Comment by fowl2** [comment]
@scanum Non-contributors can't reopen issues, could you please re-open this?
