### ISSUE TITLE
The sequence of this page is misleading, admin may accidentally apply to all users blocking some users whilke actually intending only a small user test

### ISSUE THREAD

**Issue by fmiltner** [MicrosoftDocs/OfficeDocs-SharePoint#3420]
You explain the feature works with Conditional Access and start with explaining the scope from SharePoint to all off O365, but you do not have any note of caution, that the steps under 'Block Access' respectively 'Limit Access' create an immediately-on Conditional Access policy for All Users. 
This can create situations, where while testing this, valid users get locked out before someone notices and scopes the Test-policy to the test-group first. Please add a note of caution to go to the conditional Access policy and adjust scope as needed immediately after putting the setting into effect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [SharePoint and OneDrive unmanaged device access controls for administrators - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @fmiltner 
The article currently states for _Block Access_ and _Limit Access_ procedures:

> Selecting this option disables any previous conditional access policies you created from this page, **and creates a new conditional access policy that applies to all users.**

Please kindly let me know if I understood you correctly,

**Comment by fmiltner** [comment]
Hm, then I was successfully able to miss it - but in brackets under point 3 and only indirectly as setting it resets previously created rules? I feel that deserves a forth point "check the CA policy created and adjust per your needs"

**Comment by get-itips** [comment]
@fmiltner I'll propose to give more emphasis to the sentence through an important note.

**Comment by fmiltner** [comment]
Thanks! and maybe along that important note make aa remark to cross-check for interference with other existing CA policies and services (e.g. when you deploy it as-is you break certain PowerAutomate actions for all users in the tenant (example being https://docs.microsoft.com/en-us/connectors/sharepointonline/#get-file-content - so some careful scoping considerations are needed.
