### ISSUE TITLE
Missing feature name / id for classic experience.

### ISSUE THREAD

**Issue by SPDEVGUY** [MicrosoftDocs/OfficeDocs-SharePoint#3427]
[Enter feedback here]
Article is missing critical information on how someone can set the default experience back to classic.  It instead links to a generic how to activate features (but does not describe what feature)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f1bd4ab-c640-1db8-05bb-e249129dfa46
* Version Independent ID: 4ceb7bc8-39c0-61fb-b31c-381cb7a5018b
* Content: [Change the default list and library experience - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-default-list-and-library-experience)
* Content Source: [SharePoint/SharePointOnline/change-default-list-and-library-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-default-list-and-library-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @SPDEVGUY Kevin, thanks for your feedback, I am proposing adding that information.
