### ISSUE TITLE
Error in command

### ISSUE THREAD

**Issue by ON6PH** [MicrosoftDocs/OfficeDocs-SharePoint#3428]
On this page the powershell command is missing the -Url parameter. 
It reads: Set-PnPSite <SiteURL> -NoScriptSite $false
It sould read: Set-PnPSite -URL <SiteURL> -NoScriptSite $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ON6PH Pieter

Thanks for your feedback, looking at the code Identity is the parameter name and Url is an alias, I'll propose to specify it.

Thanks
