### ISSUE TITLE
Cloud App Security has been rebranded to Defender for Cloud Apps

### ISSUE THREAD

**Issue by dcurwin** [MicrosoftDocs/OfficeDocs-SharePoint#3431]
Cloud App Security has been rebranded to Defender for Cloud Apps. Please update the phrase in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d05bf3d-a92d-86ae-f5a9-8d9fe2918297
* Version Independent ID: ff487db5-cc00-c0f7-3d0a-e7874ec773a4
* Content: [Use SharePoint as a business-to-business (B2B) extranet solution - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/create-b2b-extranet)
* Content Source: [SharePoint/SharePointOnline/create-b2b-extranet.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/create-b2b-extranet.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
I see you fixed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/534c54c141bb00193ae637ddbbb5573c6141d102 thanks!
