### ISSUE TITLE
Typos in page ("readd")

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/OfficeDocs-SharePoint#3432]
In several places the word "readd" appears, which should be "read" (one 'd').

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks, I see you fixed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/6b2e407ac0aae438667ebf032cfc6b4f1bae5be9
