### ISSUE TITLE
Agent needed in default group for scanning

### ISSUE THREAD

**Issue by RicardoDekkers** [MicrosoftDocs/OfficeDocs-SharePoint#3439]
After installing the agent and putting it in another than the default agent group, make sure to have another agent in de default group remaining. All scans are being done by the default agent group. If this group is empty, the scan jobs will never run, of remain queued.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f662d3a5-c95f-1f1f-737c-88031bb294dc
* Version Independent ID: 574b61ce-1d65-8481-d3ca-e0f118e80959
* Content: [Migration Manager Scan - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-scan?source=recommendations)
* Content Source: [migration/mm-scan.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-scan.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
