### ISSUE TITLE
Manage apps page

### ISSUE THREAD

**Issue by roaima** [MicrosoftDocs/OfficeDocs-SharePoint#3443]
Step 1. What or where is the "Manage apps page"?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc1e9c0-2e35-3357-7f57-5bd02b0e10bc
* Version Independent ID: 1443a95a-ce5b-024d-d942-001b83bf8d8c
* Content: [Manage apps using the Apps site - SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-app-catalog)
* Content Source: [SharePoint/SharePointOnline/use-app-catalog.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-app-catalog.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback! I'll propose to add that to the article
