### ISSUE TITLE
Links don't work!

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/OfficeDocs-SharePoint#3445]
The links to parts of the admin centre don't work as MS Defender for Cloud Apps redirects to the homepage.  You need to explain how to navigate to the page in question.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c744272-76d3-f60a-9d06-570d36ffb529
* Version Independent ID: 24208c34-c0f1-4ab0-5d92-9c3997211729
* Content: [Manage sites in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center)
* Content Source: [SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @lkchild 

I reviewed the article you opened the issue for https://learn.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center 

Do you mean this link? https://go.microsoft.com/fwlink/?linkid=2185220

**Comment by lkchild** [comment]
Hiya,

Yes.  When you access it via MCAS/Defender for Cloud Apps, it gives you the pop up for "Access to the MS365 admin centre is monitored" and then redirects to the homepage of the admin portal, not the one you are linking to.

Thus if you don't explain how to navigate to the page that has these settings on it, you can't change them.  You need to say where in the portal to look, not just link to it.
