### ISSUE TITLE
Missing Known Folder Move PowerShell script link

### ISSUE THREAD

**Issue by SirMikeDouglas** [MicrosoftDocs/OfficeDocs-SharePoint#3449]
The article mentions "Known Folder Move PowerShell script" but doesn't give any link to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive - OneDrive](https://learn.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @SirMikeDouglas 
I am looking into this

**Comment by get-itips** [comment]
Document has been updated.
