### ISSUE TITLE
Next steps for migration from RBS back to a normal Content database.

### ISSUE THREAD

**Issue by jasonwbaxter1990** [MicrosoftDocs/OfficeDocs-SharePoint#345]
Firstly thank you  , I've been wanting this sort of documentation specific to SharePoint, and i'm so happy to see it.
I've read through all of the Manage RBS steps in this article.
You mention , its not recommended to uninstall RBS ,So how do i get my content database back to normal?
If you run these commands , the RBS tables are still in the content database and the filestream file is not removed from the database.
So my question is how best to migrate to a new content database ? Move-spsite ? Maybe you can link that as a concept for people to follow on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b6ac330-c6a2-d444-1caa-97acda01118a
* Version Independent ID: 9e3db03f-5da8-7766-3b64-f78e5b356e3f
* Content: [Disable RBS on content databases in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/disable-rbs-on-a-content-database)
* Content Source: [SharePoint/SharePointServer/administration/disable-rbs-on-a-content-database.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/disable-rbs-on-a-content-database.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@scanum you can close this.
