### ISSUE TITLE
Link to "Learn more about Microsoft 365 intranet governance decisions." broke

### ISSUE THREAD

**Issue by hekessel** [MicrosoftDocs/OfficeDocs-SharePoint#3450]
[Enter feedback here]

Should it refer to: https://learn.microsoft.com/en-us/sharepoint/governance-overview ??
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb43d6e3-6ceb-adfe-640c-b87fb133c7fd
* Version Independent ID: 0c6d323b-84ea-7c16-7879-8664404f7bc8
* Content: [Planning intranet governance - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/intranet-governance?source=docs)
* Content Source: [SharePoint/SharePointOnline/intranet-governance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/intranet-governance.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
@hekessel Hello, I am looking into this
