### ISSUE TITLE
Sync client - frequency that it reports back?

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#3451]
Could the article please be updated to 

1) Reflect how often the client device running the sync client attempts to synchronises back, when on and running. for example is this once a day, every x hours from logon? Whilst the report shows a column Last status reported timestamp (UTC), it would be useful to know how often it attempts to synchronise back i.e. so you can be proactive in fixing user issues.

2) If possible it would also be worth including a bit more info about the tenant association key (TAK), i have never known this blank and what is the risk of generating a new one? maybe this should be called out or another article referenced?

thanks
	
Brad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67197abd-ee35-668f-c454-eb4b07f4a6f9
* Version Independent ID: 647d2380-5ddd-cc17-9f43-93773ff75b9c
* Content: [OneDrive sync reports in the Apps Admin Center - OneDrive](https://learn.microsoft.com/en-us/onedrive/sync-health?tabs=windows)
* Content Source: [OneDrive/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-health.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Hello @obhayes 
About Q1: this is covered in another article of the same section https://learn.microsoft.com/en-us/onedrive/sync-process as it is not a fixed time but based on a notification system to track the changes.

Q2: The TenantAssociationKey was used with HKLM\SOFTWARE\Policies\Microsoft\OneDrive\SyncAdminReports key, where you had to put the value in there, but as you can see in the current note "is still supported and will continue to be supported for 60 days after General Availability is announced. We recommend that admins deploy the GPO now, to ensure a smooth transition at that time." so if you are starting with this you should follow the current procedure. 

In case you are interested, you can read the previous procedure [here](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/7b006e6706985edb6358aed243058a777607f95e/OneDrive/sync-health.md) where more information about the key was present.

hope this information helps you,

**Comment by get-itips** [comment]
@scanum
