### ISSUE TITLE
Win 11 missing

### ISSUE THREAD

**Issue by chraymu** [MicrosoftDocs/OfficeDocs-SharePoint#3456]
Windows 11 is missing from this article.  Is there plans to include it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc677c5-4514-fb8b-a864-4edd711d6f44
* Version Independent ID: 1e3dbf59-48d4-2696-ad8a-7f9cb60871ec
* Content: [Use the sync app on virtual desktops - OneDrive](https://learn.microsoft.com/en-us/onedrive/sync-vdi-support#feedback)
* Content Source: [OneDrive/sync-vdi-support.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/sync-vdi-support.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
