### ISSUE TITLE
I do not see "searchable columns" on any of our sites.

### ISSUE THREAD

**Issue by AnnaEAbba** [MicrosoftDocs/OfficeDocs-SharePoint#3457]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5faf2831-9899-0574-2de8-bfece943e3e6
* Version Independent ID: 2884bfdb-c023-8a53-2380-628c3ae86086
* Content: [Enable content on a site to be searchable - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/make-site-content-searchable?source=recommendations)
* Content Source: [SharePoint/SharePointOnline/make-site-content-searchable.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/make-site-content-searchable.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
