### ISSUE TITLE
EnableSyncAdminReports

### ISSUE THREAD

**Issue by rezabj** [MicrosoftDocs/OfficeDocs-SharePoint#3459]
In "List of settings" is missing "EnableSyncAdminReports". 
See: https://learn.microsoft.com/cs-cz/sharepoint/sync-health?tabs=macos

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1c2c011-76e8-89ef-a20f-1b76773c0f21
* Version Independent ID: 1fcdcae0-f5ad-c8e8-72f6-1f729351b595
* Content: [Deploy and configure the OneDrive sync app for Mac - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/deploy-and-configure-on-macos)
* Content Source: [SharePoint/SharePointOnline/deploy-and-configure-on-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/deploy-and-configure-on-macos.md)
* Service: **one-drive**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by get-itips** [comment]
Thanks for your feedback!
