### ISSUE TITLE
Migrating Libraries created site unusable

### ISSUE THREAD

**Issue by Jeff1138** [MicrosoftDocs/OfficeDocs-SharePoint#346]
Hello, while migrating a library from an onpremise 2013 server to SharePoint Online, we started experiencing a lot of weird behaviors such as getting errors while creating libraries/lists (the libraries/lists would still get created) and getting an error while creating subsites (the site would never get created).  Working with SPO support, we found this in the error log:

Feature Activation: Threw an exception, attempting to roll back.  Feature 'DocumentLibraryInstance' (ID: 'b77b6484-364e-4356-8c72-1bb55b81c6b3').  Exception: System.ArgumentException: Value does not fall within the expected range.

After doing a number of tests it was determined that the migration tool was the problem.  I had to recreate the site collection and migrate everything using Windows Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@Jeff1138 Thank you for pointing this out to us. 

I will get this migration information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by anyITsolution** [comment]
Hi Adrea, I also noticed there's no where in this article describing the Features that need to be enabled for the tool to work properly when doing a file / folder migration from on prem share folder. they talked about enabling customer scripts but did not mention that Publishing Infrastructure needs to be enable at the Root level and at the Teams Site/ Group site level. if you can work on adding that underneath the custom scripts enablement that would rock this tool would get more utilization my customer was about to call BitTitan because this tool would not let us change the sharepoint site and would only allow OneDrive libraries. Thanks.

**Comment by scanum** [comment]
@Jeff1138 Thank you very much for your kind feedback. We recommend logging it in [Uservoice](https://sharepoint.uservoice.com/). The concerning team will evaluate and take the appropriate action, as per their schedule. We appreciate you taking out some time and sharing your feedback to make the product and service better.

**Comment by anyITsolution** [comment]
I did aready
Thanks!

https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/36986683-sharepoint-migration-tool-pre-requisites-custom

I hope you can vote.
