### ISSUE TITLE
OneDrive policies - Exclude specific kinds of files from being uploaded - Note - *.lnk not synced is incorrect

### ISSUE THREAD

**Issue by SasStu** [MicrosoftDocs/OfficeDocs-SharePoint#3465]
The recently changed **Note** to the OneDrive setting **Exclude specific kinds of files from being uploaded** states that *.lnk files are not synced at all. Which is not the case at least in the deferred ring for now. 

If there is a minimum version for this to be the case, please add the version to the box.

![image](https://user-images.githubusercontent.com/28406607/194829680-03c8dc2d-62d7-4d04-b088-fa84966a193f.png)

File: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md

**Comment by get-itips** [comment]
Hello @SasStu I am looking into this
