### ISSUE TITLE
 Manage Audience supports Microsoft 365 Groups

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SharePoint#3467]
The Manage Audience section needs updating.

You can also create audiences using Microsoft 365 Groups.

This is detailed in the link you have in the same section [Target content to specific audiences](https://support.office.com/article/33d84cb6-14ed-4e53-a426-74c38ea32293).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-user-profiles)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for feedback!
