### ISSUE TITLE
Disable View File in Explorer or scoped deployment

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-SharePoint#3469]
Hello,

We would like to enable this feature, but only for 10 users.

But it seems if we run:

Set-SPOTenant -ViewInFileExplorerEnabled $True

Then this is enabled for the whole tenant, then even if the registry entry exists or not in 
"Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ConfigureViewInFileExplorer"
The access via Windows Explorer directly still works.

If the registry does not exist, then the user still can open Windows Explorer and type directly site URL and hit Enter:
"https://tenant.sharepoint.com/sites/demosite/Shared Documents"
And the user will be able to access files.

So this means that if we deploy 2x policies for users:
1. GPO to disable ViewFileInExplorer
2. GPO to enable ViewFileInExplorer

The user that has 1st policy opens Windows Explorer and tries to access the SharePoint site by URL, the user will be able to access it.
So this means there is no way that we can deploy it in a controlled way, like for some users enable this option or for some users disable this option.

Also tried to deploy GPO with the below record:
"[   {     "domain": "mytenant.sharepoint.com",     "cookies": [       "rtFa",       "FedAuth**Block**"     ]   } ]"
This simply disables the user to use the ViewInExplorer button in the EDGE browser, but the user again can open Windows Explorer and access the URL.

![image](https://user-images.githubusercontent.com/39700914/195291423-b3b9d534-a0a0-4946-a3cd-0b959308b539.png)

Please confirm that this is the case and that there is no way to do the scoped deployment per user/device?

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
