### ISSUE TITLE
macOS Redirection - Existing installs

### ISSUE THREAD

**Issue by jaredhasenklein** [MicrosoftDocs/OfficeDocs-SharePoint#3470]
The new redirection article for macOS explains how to implement KFM on new OneDrive installs, but there is no documentation for existing installs. It seems that the experience varies on existing installs (in that the feature isn't immediately visible after an update, etc.) so having documentation for the expected behavior would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19c725af-36ac-8f78-981e-3c73e615e86c
* Version Independent ID: 2cba462a-e5c4-e8ff-b8c3-cb9c0f170231
* Content: [Redirect and move macOS known folders to OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/redirect-known-folders-macos)
* Content Source: [SharePoint/SharePointOnline/redirect-known-folders-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/redirect-known-folders-macos.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
