### ISSUE TITLE
Page diagnostics tool required to be run before performing site swap not documented

### ISSUE THREAD

**Issue by robcarrington91** [MicrosoftDocs/OfficeDocs-SharePoint#3475]
Hi I noticed when trying to perform a root site swap, if the page diagnostics tool had not been run on the site intended to be the new site, you'll receive a warning message that you will need to perform this first. Could be good to include in pre-requisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a824ca6-37ae-11c4-f04e-5de1ba5551c5
* Version Independent ID: b02f6141-9dc9-1e26-8beb-9a1f21dd042e
* Content: [Modernize your root site - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/modern-root-site)
* Content Source: [SharePoint/SharePointOnline/modern-root-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/modern-root-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
