### ISSUE TITLE
Step mentions "Settings" but should be "Setup"

### ISSUE THREAD

**Issue by loosus** [MicrosoftDocs/OfficeDocs-SharePoint#3477]
Step 5 for Windows indicates the following: In the left navigation menu, select **Settings**.

Instead of "Settings," it should say **Setup**.

The step:
![image](https://user-images.githubusercontent.com/25268183/195928358-419f3f7a-4fbe-436d-9f7a-2437039a6013.png)

The admin center page:
![image](https://user-images.githubusercontent.com/25268183/195928579-8f06ef94-87fd-4509-b25a-50d224fe290f.png)

**Comment by loosus** [comment]
Just for clarification, this issue is about the following file: sync-health.md

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by loosus** [comment]
@scanum there is no problem with the tenant.  The problem is with the documentation.
