### ISSUE TITLE
Needs updates

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#3479]
All of this is basically pointless as query rules don't work anymore. There was no replacement delivered. The tenant level settings don't come close to meeting requirements for search customization.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f082d30-62d1-e099-8307-5ab5c15d410f
* Version Independent ID: 24906b5f-8745-96f9-0f79-3dc67f1e6720
* Content: [Manage query rules - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-query-rules)
* Content Source: [SharePoint/SharePointOnline/manage-query-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-query-rules.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @danmyhre Dan,

By tenant level settings you mean the bookmarks feature that is offered in this article?

Thanks for clarifying,

**Comment by danmyhre** [comment]
Yes, bookmarks is one of the things at the tenant level in modern search, but that doesn't help site searching at all. There is also no way to actually tune results.  Search has taken a huge step backwards.

**Comment by get-itips** [comment]
@danmyhre I can understand Dan, however, is there anything that can be fixed at documentation level or is this a feature request/improvement?, as here we are limited to documentation changes. 

Maybe it would be better SharePoint Feedback? For example I found requests about query rules improvement here https://feedbackportal.microsoft.com/feedback/search/06735c62-321c-ec11-b6e7-0022481f8472?q=query+rules

Let me know if I understood you correctly,

**Comment by danmyhre** [comment]
I would recommend the entire section be split into 2. Since these are completely different in functionality, everything that has to do with classic needs its own section so it is clear what is in each experience and what actually has an impact on search results.

**Comment by get-itips** [comment]
Thanks for the feedback @danmyhre

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
