### ISSUE TITLE
The description of "This page describes ...." is incorrect. SharePoint admin center is not used for this scenario.

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/OfficeDocs-SharePoint#3482]
[Enter feedback here]
This page describes how to use the search report in site level. SharePoint admin center is not used in this scenario.
So I think the following description is unnecessary and should be removed.

---
This article describes how you can use search reports in the [SharePoint admin center](https://go.microsoft.com/fwlink/?linkid=2185219) to find answers to these questions.
---

https://learn.microsoft.com/en-us/sharepoint/view-search-usage-reports-modern-sites

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ada8124-63bd-7532-3cc6-28eb2c9dbc45
* Version Independent ID: 1533d7e3-0127-2008-b567-bad28c67727c
* Content: [View search usage reports in modern sites - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/view-search-usage-reports-modern-sites)
* Content Source: [SharePoint/SharePointOnline/view-search-usage-reports-modern-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/view-search-usage-reports-modern-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **v-lsaldanha**

**Comment by mitanabe** [comment]
![image](https://user-images.githubusercontent.com/50765231/196578090-e89294f9-8f73-4223-bb20-6272a1fb0a7d.png)

**Comment by get-itips** [comment]
Thanks for your feedback!
