### ISSUE TITLE
Performance with User mapping file

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/OfficeDocs-SharePoint#3484]
Hi I've been reading and using the SPMT tool at a customer and I'm trying to understand if there is any performance improvement if I use a User Mapping file or the Auto Mapping Feature.

Can you propose any guidelines, Also there is no guidance on how to generate the User mapping file , perhaps we can give links to exporting users from SharePoint / File Server and exporting AAD  + Vlookup in excel etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30e1dc7e-46ae-1b74-a205-e6f75a1f4cdd
* Version Independent ID: e1e8803a-0190-429e-fa3f-4a410bf580c0
* Content: [Improve SPMT or Migration Manager agent performance - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/spmt-performance-guidance)
* Content Source: [migration/SPMT-performance-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/SPMT-performance-guidance.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @jasonwbaxter 

About the first question, I am trying to find out if there is any performance improvement.

About the 2nd one, I guess you already visited https://learn.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration 

what else would you like to see there? how to get the SID of a user/group, for example?

Thanks for clarifying

**Comment by jasonwbaxter** [comment]
Thanks Andres

I think we can add some guidance here to remove orphaned users from SharePoint. And then to script out the users from AAD / SP to help with the CSV file.

What I'm seeing is that there are many users that have left an organisation but they still reside in sharePoint , and during the migration it checks several times for a matching user, for a large org with thousands of users this severely slows down the migration.



If you need to have a meeting with me you can see my availability from My Online Schedule ***@***.***/bookings/> and book the respective meeting.



Kind regards



Jason Baxter

he/him
Customer Engineer
Customer Success Unit - Modern Work
Office: +27113618866<tel:+27113618866>
Mobile: +27762490644<tel:+27762490644>
***@***.******@***.***>

[Microsoft Logo]

________________________________

**Comment by get-itips** [comment]
@scanum
