### ISSUE TITLE
Configuration options and the importance

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/OfficeDocs-SharePoint#3485]
Hi i'm following this article looking for pointers to give my customers.

One of the things I noticed is that there is no reference into this article to which settings to use the for a certain scenario.

Do you have the correct architecture in place?
 
- Virtual machine , Close to the Server farm , Direct breakout.  System requirements met.

## Scenarios:
e.g. : Pre-migration  scenario from SharePoint server. Use setting x, y , z turn off Auto mapping etc. Choose scan only..

Initial Migration:
Generate Mapping file , choose mapping file , turn off Auto Mapping . Limit versions to last 100 ,  Don't run this tool on a VDI environment.Save migration

Migration:
Run incremental migration from Saved Migration , Mark site as read only , etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8385fe4a-3c2e-2c8a-5042-cf4b34151804
* Version Independent ID: 11d6795f-5246-4996-a6ac-2b1678e2dbaf
* Content: [Create a task in SharePoint Migration Tool (SPMT) - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/spmt-create-task)
* Content Source: [migration/spmt-create-task.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/spmt-create-task.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @jasonwbaxter Jason,

I think this differs significantly depending on the scenario of each SP deployment, what is required, the type and size of the migration, past experience migrating the same content, and so on.

Let me know if I understood you correctly,

**Comment by get-itips** [comment]
@scanum
