### ISSUE TITLE
Users Storage used no longer has edit option

### ISSUE THREAD

**Issue by abates100** [MicrosoftDocs/OfficeDocs-SharePoint#3486]
[Enter feedback here]
This section is incorrect as these options are no longer available.

Select the OneDrive tab.

Under Storage used click Edit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: feeb9370-51c8-dbb3-57b9-792f4d22624d
* Version Independent ID: 7337e3b2-278f-f12f-a041-fc7e372205f0
* Content: [Change a specific user's OneDrive storage space - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-user-storage#change-a-users-storage-space-in-the-microsoft-365-admin-center)
* Content Source: [SharePoint/SharePointOnline/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
@abates100 : I followed the rules and it works like the article 
(The only difference: I use the tenant admin, not the SharePoint Admin)

**Comment by get-itips** [comment]
@abates100 I was able to follow the procedure using a SharePoint admin-only user.

**Comment by get-itips** [comment]
@scanum
