### ISSUE TITLE
Misspelling in Training subsection

### ISSUE THREAD

**Issue by nortonck** [MicrosoftDocs/OfficeDocs-SharePoint#3487]
There is a misspelling on this page under the Training subsection.  It is circled in yellow on the image for your review.

![image](https://user-images.githubusercontent.com/30570719/196751414-a9da939f-8f4d-4dc7-94ec-ad62e4b4ca41.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1787d668-b65b-8de4-a182-2b22b43e429e
* Version Independent ID: 64957a69-2f4b-3947-d631-ac9c29e6f68b
* Content: [Introduction to SharePoint and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/introduction)
* Content Source: [SharePoint/SharePointOnline/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/introduction.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
