### ISSUE TITLE
Page does not add additional info or context

### ISSUE THREAD

**Issue by caseykeller2** [MicrosoftDocs/OfficeDocs-SharePoint#3493]
This documentation page only presents a screenshot of the tool, plus the same sentence that's also on the tool's page ("Schedule task(s) a minimum of 30 minutes in advance. The actual start time depends on agent availability.").

This page could be improved by clarifying whether the time scheduled option is in UTC or in PT. It could be read as "UTC, which is 7 hours behind Pacific Time" or "Pacific Time, which is UTC minus 7 hours". Ideally, the option in the tool would just clearly state UTC or PT, and this documentation page could be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9987ad30-b466-2e88-800d-4fd5de647c39
* Version Independent ID: ff348097-e178-f64f-4872-b173567df74b
* Content: [Setting migration task schedules in Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-US/sharepointmigration/mm-scheduling?WT.mc_id=365AdminCSH_spo)
* Content Source: [migration/mm-scheduling.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-scheduling.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback!
