### ISSUE TITLE
Affect on existing schedules

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#35]
If we enable Continuous Crawling on a source that previously had Full and Incremental schedules set, what, if anything do we need to do with those schedules? are they deactivated automatically or do we need to make a change manually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89352e-bd59-5b52-c0b8-4b5b19bf4d6b
* Version Independent ID: 06a19e26-98c3-ca35-8bcb-8cad4eaf7ca9
* Content: [Manage continuous crawls in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/search/manage-continuous-crawls)
* Content Source: [SharePoint/SharePointServer/search/manage-continuous-crawls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/manage-continuous-crawls.md)
* Service: **unspecified**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Incremental is automatically deactivated. Fulls shouldn't be used except under unusual circumstances after the initial full crawl.

**Comment by jay1050** [comment]
It looks like crawl logs are only available after full crawl has completed
https://docs.microsoft.com/en-us/sharepoint/search/view-search-diagnostics

However i think what has been suggested above is that we do not really need full crawl schedule. So would we never have logs available for continuous crawls ?
