### ISSUE TITLE
Domain Joined

### ISSUE THREAD

**Issue by rhyspaterson** [MicrosoftDocs/OfficeDocs-SharePoint#350]
In the 'those not joined to a domain or compliant in Intune' statement, are you referring to Azure Active Directory domain joined? What happens if we have devices joined to an internal, non-Azure, but trusted domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices?redirectSourcePath=%252fen-us%252farticle%252fControl-access-from-unmanaged-devices-5ae550c4-bd20-4257-847b-5c20fb053622)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@rhyspaterson Thank you for this inquiry

I am not sure about the answer to this Azure inquiry. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lightupdifire** [comment]
Hello,
The "Joined" does it mean really like a Azure AD domain joined, or device can be also Azure AD domain registered?

**Comment by MaximeRastello** [comment]
@lightupdifire : its is none of these cases, "Hybrid Azure AD Join" is a local AD domain joined PC also registered in Azure AD using an automatic process : https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-managed-domains

**Comment by lightupdifire** [comment]
@MaximeRastello 
Thank, I found it out too, when policy is activated, the Conditional Access policy created, where it is set: require Compliant device. Then device can be "MDM+AD registered" only as soon as it become compliant by MDM all works fine.

**Comment by scanum** [comment]
@rhyspaterson  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
