### ISSUE TITLE
Site permissions and dependent permissions table are broken.

### ISSUE THREAD

**Issue by kenmoritest** [MicrosoftDocs/OfficeDocs-SharePoint#3502]
Hi Team,

It seems that the "Site permissions and dependent permissions" section is completely broken during the edit.
Please check the previous version of table and fix the documentation.

SharePoint OnPrem table looks correct.
https://learn.microsoft.com/en-us/sharepoint/sites/user-permissions-and-permission-levels#site-permissions

**Detail**
Permission | Description | Dependent permissions
-- | -- | --
Manage Permissions | Create and change permission levels on the website and assign permissions to users and groups. | Approve Items, Enumerate Permissions, Open
View Web Analytics Data | View reports on website usage. | Approve Items, Open

"Approve Item" has nothing to do with Manage Permissions. So does View Web Analytics Data.
This is just a couple of examples. Overall, the permission dependency tables are smaller than what is specified in SPS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/understanding-permission-levels#permissions-and-dependent-permissions)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback, I created a PR to correct the table
