### ISSUE TITLE
Missing the Set-SPOTenant -UsePersistentCookiesForExplorerView $True   setting

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/OfficeDocs-SharePoint#3503]
This document is missing the additional required setting **Set-SPOTenant -UsePersistentCookiesForExplorerView $True** thats needed at the SPO tenant level in order for File Explorer view to work in Edge

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/SharePoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Jvasil 
Please see this note

>This setting is not used anymore with Internet Explorer (IE) retired and the parameter would be removed soon. Users need to select "Yes" when prompted for "Stay signed in?" at the time of sign-in for "View in File Explorer" to work with Microsoft Edge.

here https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps

**Comment by get-itips** [comment]
@scanum
