### ISSUE TITLE
SCCM Detection Script doesn't work

### ISSUE THREAD

**Issue by AkaIntern** [MicrosoftDocs/OfficeDocs-SharePoint#3507]
I tried to deploy the OneDriveSync app through SCCM using the steps described with the sample package and the script user for detection method gives me a Null error for the $username variable.

I've fixed my side replacing like bellow:

`##$User = gwmi win32_computersystem -Property Username

$UserName = $env:username

#$UserSplit = $UserName.Split("")

$OneDrive = "$env:SystemDrive\users\" + $UserName +"\appdata\local\microsoft\onedrive\onedrive.exe"`

Also the documentation doesn't make any reference for another very usefull tip for SCCM deploy that is the "/allusers" parameters described in the article bellow (Per Machine Installation).

https://learn.microsoft.com/en-us/sharepoint/per-machine-installation

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 068634d0-772a-1818-61bf-05927956e49d
* Version Independent ID: 799a77c7-b615-cb97-1867-769fc5ddb3b3
* Content: [Deploy OneDrive apps using Microsoft Endpoint Configuration Manager - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/deploy-on-windows)
* Content Source: [SharePoint/SharePointOnline/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@get-itips can you add a link to [Install the sync app per-machine](https://learn.microsoft.com/sharepoint/per-machine-installation) to this article and call out that it's another method of deploying? Maybe in that "Deploy the OneDrive sync app for Windows" section near the top.

**Comment by get-itips** [comment]
@MikePlumleyMSFT Actually, there is already a NOTE in the article talking about the per-machine installation option. Do you want me to move it to that section?

>Office is installed per machine, whereas OneDrive is installed per user by default. [Learn about installing OneDrive per machine](https://learn.microsoft.com/en-us/sharepoint/per-machine-installation).

**Comment by MikePlumleyMSFT** [comment]
Thanks @get-itips, I didn't see it there. Yes, let's move it up to that section. I think it'll be more visible there.
