### ISSUE TITLE
-ExcludeBlockDownloadPolicySiteOwners

### ISSUE THREAD

**Issue by craigmogs** [MicrosoftDocs/OfficeDocs-SharePoint#3508]
[Enter feedback here]
Has anyone been able to use the -ExcludeBlockDownloadPolicySiteOwners parameter?  It appears that it does not exist.
I am trying to find a way to allow Owners to download, but have been unable to find the owners GUID. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acbfb458-2ccd-84ed-b5dd-9493f6d5c003
* Version Independent ID: a7db833e-2f56-e147-8f84-ccf1a86ed71a
* Content: [Block the download of files from a SharePoint site or OneDrive (preview) - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/block-download-from-sites)
* Content Source: [SharePoint/SharePointOnline/block-download-from-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/block-download-from-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
