### ISSUE TITLE
wrong "settings" menu option

### ISSUE THREAD

**Issue by nmbrites** [MicrosoftDocs/OfficeDocs-SharePoint#3509]
On the Set up phase, item 5 (settings) the menu option on the left (in the M365 apps admin center) is Setup and not Settings. 

![image](https://user-images.githubusercontent.com/8376706/198878371-1b0afaee-f504-49aa-92d5-fe3fea06ca4b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=macos)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
@nmbrites Thank you for the information. In the early days the confirmation was correct. . This should becorrected.
But if you are working with this GPO, you should change  to a newer GPO "Enabale Sync Health reporting for OneDrive", which does not need the TAK anymore
