### ISSUE TITLE
Is the download gone?

### ISSUE THREAD

**Issue by ToddKlindt** [MicrosoftDocs/OfficeDocs-SharePoint#351]
I get a 404 on the file download. Is the link incorrect or is it not available anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [Overview of the SharePoint Migration Assessment Tool](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
I just checked both of the download links in the article and they work fine for me; can you try again?
Thanks!

**Comment by fbastone** [comment]
Please confirm if this is also available for SP2010.  The Intro page that this is for SP2013 while the overview page states "The tool is built to be run from within a SharePoint 2010 or 2013 farm".  Thanks.

**Comment by JeighBI** [comment]
fbastone, yes it's available and compatible with SP2010. It is the same download for both versions.
