### ISSUE TITLE
Destination Path format

### ISSUE THREAD

**Issue by mcloum** [MicrosoftDocs/OfficeDocs-SharePoint#3510]
Can someone advise on what format the destination path needs to be?

I have tried the following and nothing seems to populate the destination path on the migration jobs:

- Full URL to users OneDrive including destination subfolder.
- Just the Destination folder name, for example "BoxData" i have also tried including a / "/BoxData"
- Short path such as "Documents/BoxData"
- ".../Documents/BoxData" as shown in the UI when you choose a destination manually.

Also, is the destination folder created automatically if it doesn't exist? If not is there guidance on how to mass create a destination folder in users OneDrive accounts?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87ed69e8-7a5e-5e4b-12e5-0824ab5ef010
* Version Independent ID: 80535eb7-e53c-7718-4426-a424af712ec6
* Content: [Review the destination paths for your Box migration with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-box-step4-review-destinations)
* Content Source: [migration/mm-box-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step4-review-destinations.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mcloum** [comment]
I already did this, apparently you use the full URL and include any sub folders you want to create, they are created automatically. Turns out editing the CSV in Excel breaks the formatting of the CSV files you download so edit them in notepad or something similar like notepad++
