### ISSUE TITLE
Update client id in article

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-SharePoint#3511]
[The client id provided in the article is the one from the legacy Mover.io. Migration Manager uses **5vsg3adjt5j6f4frodvg7ik57hzslpev**.  As with legacy Mover, if your organization has enable the Box setting “Disable unpublished apps by default” you will need to add this client id under "Except for".  (See https://learn.microsoft.com/en-us/sharepointmigration/mover-box#app-permissions for the corresponding Mover documentation.) ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3eaf13d-c0f2-5f45-8fe7-a647d3e0da40
* Version Independent ID: a644e742-fb10-6c67-dbf0-1c3469234e0f
* Content: [Connect to Box with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-box-step1-connect)
* Content Source: [migration/mm-box-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by fselkirk** [comment]
Hi Manuela,

I am from Support, and this is not tenant-dependent. The article is wrong. The text was updated when the feature changed, but the image showing the ID wasn't, and the ID doesn't match the current feature.  It should be changed to 5vsg3adjt5j6f4frodvg7ik57hzslpev.

Please let me know if I need to file a new request to have the content corrected. I missed this email when it came in.

Thanks,

Frances Selkirk
Sr. Support Escalation Engineer
SharePoint and OneDrive Technical Support
+1 (857) 453-6233
Working Hours: M-Th, 9:30-6:00 ET  (Friday hours limited)

Need help outside of my working hours?
Manager: David Dockter ***@***.******@***.***>

**Comment by JoanneHendrickson** [comment]
@fselkirk :  I will update this article with the correct information and screen shots. Will follow up with you tomorrow.  Joanne

**Comment by scanum** [comment]
@fselkirk An apology for the misunderstanding. Thank you for your help @JoanneHendrickson, really appreciate it!
