### ISSUE TITLE
Parameters do not work as intended

### ISSUE THREAD

**Issue by tomleicher** [MicrosoftDocs/OfficeDocs-SharePoint#3514]
The parameter to exclude site owners from the policy does not seem to exist yet.

```
PS C:\> Set-SPOSite -Identity https://company.sharepoint.com/sites/C-2022-0014 -BlockDownloadPolicy $true -ExcludeBlockDownloadPolicySiteOwners $true
Set-SPOSite : A parameter cannot be found that matches parameter name 'ExcludeBlockDownloadPolicySiteOwners'.
```

The parameter to exclude group ID's from the policy seems to only accept the group GUID instead of the regular ID.
But I cannot seem to find the GUID for Sharepoint groups anywhere.

```
PS C:\> Set-SPOSite -Identity https://company.sharepoint.com/sites/C-2022-0014 -BlockDownloadPolicy $true -ExcludedBlockDownloadGroupIds "21"
Set-SPOSite : Cannot bind parameter 'ExcludedBlockDownloadGroupIds'. Cannot convert value "21" to type "System.Guid". E
rror: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acbfb458-2ccd-84ed-b5dd-9493f6d5c003
* Version Independent ID: a7db833e-2f56-e147-8f84-ccf1a86ed71a
* Content: [Block the download of files from a SharePoint site or OneDrive (preview) - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/block-download-from-sites)
* Content Source: [SharePoint/SharePointOnline/block-download-from-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/block-download-from-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @tomleicher 

`ExcludeBlockDownloadPolicySiteOwners` is present in `16.0.23019.12000`

I was able to specify a 365 group GUID for `ExcludedBlockDownloadGroupId`

**Comment by get-itips** [comment]
@scanum
