### ISSUE TITLE
SPO auto-acceleration for guests: What is the official endpoint URL of Azure AD sign-in screen for authentication?

### ISSUE THREAD

**Issue by vherrlein** [MicrosoftDocs/OfficeDocs-SharePoint#3515]
When the auto-acceleration is enabled for guests, would you clarify the official AAD sign-in screen endpoint URL with required tokens ?

After some investigations, it seems to be that one:
```
- URL Format: https://login.microsoftonline.com/login.srf?wa=wsignin1.0&whr=[Primary Domain Name]&wreply=https://[Tenant Name].sharepoint.com/_forms/default.aspx
- Primary Domain Name: contoso.onmicrosoft.com
- Tenant Name: contoso
```

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21bd120e-26c1-3a5a-499b-8dbd01a435e6
* Version Independent ID: 2ced3050-f8ce-a5c3-a292-e0d668e4a47a
* Content: [Enable auto-acceleration in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/enable-auto-acceleration?redirectSourcePath=%252fen-us%252farticle%252fEnable-auto-acceleration-for-your-SharePoint-Online-tenancy-74985ebf-39e1-4c59-a74a-dcdfd678ef83)
* Content Source: [SharePoint/SharePointOnline/enable-auto-acceleration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/enable-auto-acceleration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @vherrlein I am looking into this

**Comment by get-itips** [comment]
Hello @vherrlein 
I asked around and was instructed that Support services might be able to help provide this information, so please open a support request from your tenant to ask for this specific information.
Thank you
