### ISSUE TITLE
New Site creation Settings were retired?

### ISSUE THREAD

**Issue by frodale** [MicrosoftDocs/OfficeDocs-SharePoint#3517]
What happened with the new settings page?

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!

**Comment by frodale** [comment]
That link doesn't work either

**Comment by HansBrender** [comment]
@scanum https://sharepoint.uservoice.com/ is no longer available !
