### ISSUE TITLE
Minor error in the text

### ISSUE THREAD

**Issue by dontpanicse** [MicrosoftDocs/OfficeDocs-SharePoint#3519]
[Skriv din feedback här]
It says gpedit.exe but should be gpedit.msc to start the Group Policy Editor

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för learn.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/sv-se/sharepoint/sync-health?tabs=windows)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello, thanks for your feedback
