### ISSUE TITLE
Migration Manager - Powershell Commands

### ISSUE THREAD

**Issue by Coma665** [MicrosoftDocs/OfficeDocs-SharePoint#3523]
Hi, is there or will there be PowerShell commands to manage migration jobs e.g. Google Drive Migrations?

A customer has asked if we can periodically migrate changes, we can one off schedule within the dashboard but would like to automate this.

Any ideas?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
