### ISSUE TITLE
ExcludeBlockDownloadPolicySiteOwners parameter not correct

### ISSUE THREAD

**Issue by oilerhead** [MicrosoftDocs/OfficeDocs-SharePoint#3524]
Either this parameter doesn't exist, or it is shown incorrectly in the documentation.  I copied it straight from the documentation into the PowerShell window.  The other exclude parameter is correct, but not what I want.

Set-SPOSite : A parameter cannot be found that matches parameter name 'ExcludeBlockDownloadPolicySiteOwners'.
At line:1 char:79
+ ... nt.com/sites/ExternalTest -ExcludeBlockDownloadPolicySiteOwners $true
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SPOSite], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Online.SharePoint.PowerShell.SetSite

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
