### ISSUE TITLE
PowerShell Methods?

### ISSUE THREAD

**Issue by tinojr** [MicrosoftDocs/OfficeDocs-SharePoint#3525]
This is good information for UI, but what about PowerShell? How can get a list of all site owners? Why are there no PowerShell examples in these kb's?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be31bf07-922b-7307-a30e-f09d00fb79f3
* Version Independent ID: a42d0699-1acf-808c-0d86-dc3516f4dfaf
* Content: [Manage user profiles in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-US/sharepoint/manage-user-profiles?WT.mc_id=365AdminCSH_spo)
* Content Source: [SharePoint/SharePointOnline/manage-user-profiles.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-user-profiles.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
@scanum
