### ISSUE TITLE
Restricting Domains - Gmail.com

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SharePoint#3530]
I'm working with a client. They are trying to restrict to certain domains. The issue is that when he tries to add gmail.com, it does not stay in that field. It is automatically removed. Can someone confirm if this is by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Jmartinez589** [comment]
Hello Manuela,

I have worked with support. The issue is that this appears to be part of the product design. Support is not offering an answer, and the product team could be in a better position to answer this question.

The question again is, does the domain inclusion option also work with gmail.com specifically?
________________________________
