### ISSUE TITLE
Unclear behavior for 2 migration manager options - AND or OR?

### ISSUE THREAD

**Issue by leviu-ofek** [MicrosoftDocs/OfficeDocs-SharePoint#3534]
In regard to [Migration Manager task settings](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-settings.md), there are 2 filters that are documented:
> Migrate files created after
> Migrate files modified after

What is not clear if they are ORed or ANDed?
i.e. if both are set will the files be migrated only if both conditions are met or either condition is met

Example:
File created in 20/1/2022 and modified on 25/10/2022.
Migration filter set to "created after" 1/10/2022 and "modified after" 1/10/2022. 
Will this file be uploaded or skipped?

Use case:
Delta migration.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by leviu-ofek** [comment]
> Thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs. Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

It's not urgent - I just run the final "delta" migration as is without any of these options.

Will testing it out and see how it behaves also be acceptable? Or an official ticket is required to update the docs. I've never "edited" or opened an issue for Microsoft Docs before...

**Comment by JoanneHendrickson** [comment]
@scanum  @leviu-ofek    I am confirming the behavior with the product team now. Will update you as soon as I hear back.   thanks!   Joanne

**Comment by JoanneHendrickson** [comment]
@leviu-ofek  @scanum 

Just an update -- after checking with the product team, they confirmed the relationship is AND.  I will update the article. thanks!  Joanne
