### ISSUE TITLE
ID in this article needs to be updated. 

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-SharePoint#3540]
The image in this article is outdated, and shows the client id used by the previous migration app, not the current one. The article does not provide customers with enough information to successfully perform this migration, at least if the organization has enabled the the Box setting “Disable unpublished apps by default”. They need to know what client id to approve. It's **5vsg3adjt5j6f4frodvg7ik57hzslpev**. While the image implies that this string will be available for the customer to copy before they reach this point, this isn't true, or at least wasn't as of 11/01/22. (As I don't have a Box account, I can't test this today.) 

Previously submitted as request https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3511, but Manuela seemed to think I was a customer having an issue. I am a SharePoint Support escalation engineer who solved this problem for a customer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3eaf13d-c0f2-5f45-8fe7-a647d3e0da40
* Version Independent ID: a644e742-fb10-6c67-dbf0-1c3469234e0f
* Content: [Connect to Box with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-box-step1-connect)
* Content Source: [migration/mm-box-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Article was updated
