### ISSUE TITLE
Need to fix translation bug.(ja-jp)

### ISSUE THREAD

**Issue by kokurata** [MicrosoftDocs/OfficeDocs-SharePoint#3541]
Need to fix translation bug.

Original statement:
Change your SharePoint domain name
https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name
-----------------------------
This feature is currently available to organizations that have no more than 10,000 total SharePoint sites and OneDrive accounts combined.
-----------------------------

Actual statement:
https://learn.microsoft.com/ja-jp/sharepoint/change-your-sharepoint-domain-name
-----------------------------
この機能はパブリック プレビュー段階にあり、現在、SharePoint サイトと OneDrive アカウントの合計が 10,000 個を超える組織で利用できます。
-----------------------------

Expected statement:
-----------------------------
この機能はパブリック プレビュー段階にあり、現在、SharePoint サイトと OneDrive アカウントの合計が 10,000 個を超えない組織で利用できます。
-----------------------------

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [251125](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/251125)

I'm closing this issue because the Global Services team will handle it from here.

**Comment by tiburd** [comment]
Reported as fixed.
