### ISSUE TITLE
Document needs more information or links to other sources

### ISSUE THREAD

**Issue by MSUMOLL** [MicrosoftDocs/OfficeDocs-SharePoint#3544]
I'm trying to find out what "impressions" means in this context. The descriptor of what the report shows does not answer this question, instead it describes the data that is clearly visible in the given graph. I'd appreciate some clarity on what these terms mean. thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ada8124-63bd-7532-3cc6-28eb2c9dbc45
* Version Independent ID: 1533d7e3-0127-2008-b567-bad28c67727c
* Content: [View search usage reports in modern sites - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/view-search-usage-reports-modern-sites)
* Content Source: [SharePoint/SharePointOnline/view-search-usage-reports-modern-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/view-search-usage-reports-modern-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **v-lsaldanha**

**Comment by get-itips** [comment]
Hello @MSUMOLL 
Impressions in the context of search results usually mean the number of times a particular result was listed in a search result, in this example, result types.
Does this answer your question or do you feel that you need more explanation?
Thanks!

**Comment by MSUMOLL** [comment]
Yes, thanks! That's a very succinct answer. 
Is this a common term in search engine parlance, or is this a microsoft-specific term? If the latter, it seems appropriate to put some language clarifying this on the page.

**Comment by get-itips** [comment]
Well, It's a common term in search engine topics, I'll check with the article's author.

**Comment by get-itips** [comment]
@scanum Document has been decided to leave as-is.
