### ISSUE TITLE
GA or preview?

### ISSUE THREAD

**Issue by fjuhasz** [MicrosoftDocs/OfficeDocs-SharePoint#3546]
Hi,

Your roadmap page (Feature ID: 82162) shows this as a preview feature https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=tenant%20rename 
Meanwhile the article itself does not mention that this is a preview feature only.

Could you advice if this is a preview feature or GA now?

BR,
Ferenc

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Item is already gone from roadmap.
