### ISSUE TITLE
Don't know how to get "rtFA" & "FedAuth"

### ISSUE THREAD

**Issue by Kingzoey** [MicrosoftDocs/OfficeDocs-SharePoint#3548]
[Enter feedback here]

Hi, I am trying to change some configurations with your documentation. I want to ask a question that how can I get **"rtFa"** and **"FedAuth"**? I don't find a way to get them and I think it is the reason I didn't succeed. I would appreciate it if you can give me a solution :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello,
You can get more insights on those cookies here 

https://learn.microsoft.com/en-us/sharepoint/authentication

and 

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#configureviewinfileexplorer

Hope this information helps you,
