### ISSUE TITLE
Conditional Access Policy caused business impact

### ISSUE THREAD

**Issue by ghostinthecable** [MicrosoftDocs/OfficeDocs-SharePoint#3549]
When selecting "Allow limited, web-only access", the service then proceeds to **deploy a Conditional Access Policy requiring unmanaged device enrolment**. Why?

This, in many environments, can cause severe business impact and potentially loss of revenue.

It is suggested that a message is displayed within the documentation to inform administrators of this Conditional Access Policy's Grant actions (**namely**, "Require Hybrid Azure AD joined device").

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [SharePoint and OneDrive unmanaged device access controls for administrators - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
