### ISSUE TITLE
SPMT release notes error on page

### ISSUE THREAD

**Issue by redamaleki** [MicrosoftDocs/OfficeDocs-SharePoint#3550]
There appears to be a formatting error on the release notes page for SPMT, the latest notes are not appearing the same as previous versions.

Also, it appears that the same version is set for Public Preview, First Release, and Rolling Out.  According to the roadmap - https://www.microsoft.com/en-us/microsoft-365/roadmap?filters&filters=&searchterms=93408, there was supposed to be a 2019 compatible version releasing into public preview sometime this month. Will that still be happening?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c911d1d-3570-6e0a-cfa7-77b7516a1f55
* Version Independent ID: 261252f1-7191-5be9-a735-cdb307b72a7c
* Content: [SharePoint Migration Tool (SPMT) Release notes - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool)
* Content Source: [migration/new-and-improved-features-in-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/new-and-improved-features-in-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @redamaleki 
I think the difference in the format is intended, and it is due to the fact of the 4.0 major release, where more detailed information is included.
About the other question, if the roadmap item is still there I guess it is still coming.
