### ISSUE TITLE
The hard block information in the note on this page makes it sound like both modern and classic experience pages will be hard blocked. Is this correct? I ask because in the message in our Message Center in our GCC tenant, it notes users currently see a soft block message, and that will be replaced with the hard block - however, only modern pages currently display the soft block, leading me to wonder if classic experience pages will not be blocked in IE mode in Edge. Please confirm/verify. Thank you.

### ISSUE THREAD

**Issue by VARenee** [MicrosoftDocs/OfficeDocs-SharePoint#3556]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d9effc-1329-b03d-b6d6-f0d7ff88a6de
* Version Independent ID: 4f6bfbe6-b14f-baa7-e80d-20f7ca8a3427
* Content: [Prepare your SharePoint environment for the retirement of Internet Explorer 11 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/prepare-ie11)
* Content Source: [SharePoint/SharePointOnline/Prepare-IE11.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/Prepare-IE11.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @VARenee 
I am looking into this.

**Comment by get-itips** [comment]
Hello @VARenee I got confirmation that it would be any page of SPO, both modern and classic.

**Comment by VARenee** [comment]
Thank you for verifying this! I really appreciate it.

Renee

From: Andres Mariano Gorzelany ***@***.***>
Sent: Tuesday, January 3, 2023 6:41 AM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Barnette, Renee ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-SharePoint] The hard block information in the note on this page makes it sound like both modern and classic experience pages will be hard blocked. Is this correct? I ask because in the message in our Message Cen...


Hello @VARenee<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVARenee&data=05%7C01%7C%7Cdde7f94f16a346996ebd08daed90224f%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638083500548652933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nu%2FwLLrxaPafpsLbcROL9BOkdDk%2BQUd%2FTjpztOJctTo%3D&reserved=0> I got confirmation that it would be any page of SPO, both modern and classic.

-
