### ISSUE TITLE
api.office.com endpoint might need to be removed from this article

### ISSUE THREAD

**Issue by JeremyEsposito** [MicrosoftDocs/OfficeDocs-SharePoint#3561]
api.office.com is listed as a required endpoint.

api.office.com does not resolve in DNS. Is this endpoint deprecated?
 

_PS> test-netconnection api.office.com -port 443
WARNING: Name resolution of api.office.com failed

ComputerName   : api.office.com
RemoteAddress  :
InterfaceAlias :
SourceAddress  :
PingSucceeded  : False

PS> Resolve-DnsName api.office.com
Resolve-DnsName : api.office.com : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName api.office.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (api.office.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName__

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b383a083-49a6-72b8-46f4-954c96192353
* Version Independent ID: 35ab28d5-eddf-181b-c13b-bd7d20164b90
* Content: [Migration Manager Prerequisites and Endpoints - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-prerequisites#required-endpoints)
* Content Source: [migration/mm-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-prerequisites.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @JeremyEsposito 
I am looking into this.

**Comment by get-itips** [comment]
An update to the article is coming

**Comment by JoanneHendrickson** [comment]
@get-itips @JeremyEsposito    I have removed this endpoint from the list and the change is now live.  Thanks!   joanne
