### ISSUE TITLE
Link to next page is incorrect, minor typo takes you to wrong page (same as prior step, as well)

### ISSUE THREAD

**Issue by gborhegyi** [MicrosoftDocs/OfficeDocs-SharePoint#3563]
The link to the next step goes to the integration for "Box". and not "Dropbox", as it should.
You just need to correct "box" to "dropbox" in the URL for the link to the next step (Step 5) and you should be fine; the proper page exists, only the link is wrong.

Thanks!

-George Borhegyi

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b683af2f-25e8-d1ef-3161-3736d481fef0
* Version Independent ID: 8c7300b4-9115-69f5-1c59-d1f85799923f
* Content: [Review the destination paths for your Dropbox migration with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-dropbox-step4-review-destinations?source=recommendations)
* Content Source: [migration/mm-dropbox-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-dropbox-step4-review-destinations.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback!
