### ISSUE TITLE
Switch to Connect-MgGraph PowerShell for Automation (App-only)

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-SharePoint#3567]
Hi SharePoint-Team

I would like to switch from the "SharePoint Online Management Shell" to "Microsoft Graph PowerShell", because we can then automate this request, over an App Registration (Enterprise App) instead of a Service Account.

Please update the documentation how to request this for SharePoint!

Here my Idea:
```
Connect-MgGraph -Scopes "Sites.Read.All"
# Select-MgProfile -Name "beta"
$sitesGraph = Get-MgSite -Search * -Property * -All
$sitesGraph | Select -First 1 -ExpandProperty Drive
Get-MgSiteDrive -SiteId ($sitesGraph | Select -First 1).Id -Property Quota | Select -ExpandProperty Quota  # Empty
Get-MgSiteDrive -SiteId ($sitesGraph | Select -First 1).Id -Property Quota -ExpandProperty Quota | fl # Get-MgSiteDrive : Parsing OData Select and Expand failed: Property 'Quota' on type 'microsoft.graph.drive' is not
```

I was not able to convert this, got just 198 of over 3000 sites and didn't get the usage attribute out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
