### ISSUE TITLE
SharePoint Site permissions for Partner Delegated admins

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-SharePoint#3568]
SharePoint Admin Center classic, did have option "Add Support Partner", this option is not available in modern SharePoint Admin Center.

This page does not provide information how to setup in a new way. It also referes to the Set-SPOUser powershell which also does not provide information.

Please update documentation / page, on how to setup new support partner / Partner delegated permissions on site level, weather via interface or via powershell.
Also, please include way / example when using GDAP and DAP examples.

Thank you,
Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd224d48-9dab-31ae-6548-2e929bd62d7c
* Version Independent ID: 6a98ec78-5f74-266f-61a5-95dfdcf673e9
* Content: [Find site collection features in the new SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-US/sharepoint/site-collections-page?WT.mc_id=365AdminCSH_spo)
* Content Source: [SharePoint/SharePointOnline/site-collections-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/site-collections-page.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by hkusulja** [comment]
Referring also [#369 ](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/369)

**Comment by tiburd** [comment]
It looks like the article has been updated:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/54688693/2c591b5e-5222-48fb-89ca-1c9c6014b0c4)

Closing this issue.

**Comment by hkusulja** [comment]
@tiburd  sorry, this is not resolved, please write more detailed explaining including PowerShell example for particular scenario, where to put which ID (where to get the encoded string for the partner) ? etc. 
Thank you
