### ISSUE TITLE
How many requests per second?

### ISSUE THREAD

**Issue by andygett** [MicrosoftDocs/OfficeDocs-SharePoint#3572]
In response to my request, Egnyte has granted this to my Egnyte Connect API:
User (Access Token) Rate Limits
6	Calls per second
518,400	Calls per day

When doing a scan, I'm still getting 
ResultCode | TopFailureReason
MBACKOFF | Could not get ACLs: ERR_403_DEVELOPER_OVER_QPS. See Mashery docs for   Egnyte for more info

I interpret this to mean SP Migration Manager is sometimes making more than six calls per second, but frankly, this seems like a reasonable limit which the Microsoft SharePoint Migration Manager should be able to work with.  

How do I resolve this?  
1. Should I ask for a higher limit than six calls per second?   If so, how much?
2. Is there a way to get the SP migration manager to handle such issues automatically?  E.g., catch the error, wait, retry.
3. Is there a way to throttle the number of calls per second that SP migration manager makes?

I realize questions 2 and 3 may be beyond the scope of this page, but really, for question 1, the documentation should show actual numbers in the text of the "Rate limit increase" email, "x calls per second" and "y calls per day".  Give practical values for x and y that will work with Migration Manager please.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Version Independent ID: 89dafe22-954c-8eaf-6b93-9d33eb8a9f65
* Content: [Step 1: Connect to Egnyte - Migrate to Microsoft 365](https://learn.microsoft.com/en-US/sharepointmigration/mm-egnyte-step1-connect?WT.mc_id=365AdminCSH_spo#request-rate-limit-increase)
* Content Source: [migration/mm-egnyte-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-egnyte-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
