### ISSUE TITLE
No clear instructions to implement redirection to a different tenant

### ISSUE THREAD

**Issue by ChrisNoelBritto** [MicrosoftDocs/OfficeDocs-SharePoint#3574]
No clear instructions to implement redirection to a different tenant. Where to make these changes? What PS commands to use? Examples?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfb6e9b-57d4-749f-a1d0-5f5c24e141ce
* Version Independent ID: e67e1021-7801-477b-1642-43c283742e59
* Content: [Manage site redirects - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-site-redirects)
* Content Source: [SharePoint/SharePointOnline/manage-site-redirects.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-site-redirects.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ChrisNoelBritto 

I don't see this article mentioning that as possible or am I missing something? Redirects are created automatically as a result of 

changing a SharePoint site address, moving a site to a different geo-location or swapping a site.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
