### ISSUE TITLE
SharePoint 'attachments' in Outlook no longer function after domain change

### ISSUE THREAD

**Issue by jpjm** [MicrosoftDocs/OfficeDocs-SharePoint#3575]
Could you update the Limitations section of this document with information that when files are shared in Outlook using the "share link" feature, that they don't work after the domain is changed?

The issue seems to be that these links trigger MS Word to open and then passes the (old) URL through to Word, which doesn't seem to be able to follow the redirect and gives a "We can't open your file. Your file has moved to a new location" error. Using the "Open file location" drop-down loads a browser which does then follow the redirect from where people can open the files in Word or in browser without issue. Using Outlook Web App also uses the browser to follow the redirect and works.

Obviously new files shared this way will have the new domain and won't be an issue, but there might be a several week period where our users are trying to open work in progress and will need to work around by using Outlook Web App or the "open file location" drop-down.

What's interesting is that sometimes when I open these SharePoint links in Outlook, Word *does* follow the redirect and the file opens from the new domain, but this isn't something that can be reproduced in a consistent way (it's not like opening it once causes a problem and then subsequent attempts work without issue).

My OneDrive version is 22.248.1127.0001, Outlook and Word is 2212 Build 15928.20198.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by jpjm** [comment]
I didn't because I assumed there wasn't really much they would be able to do, people had already encountered the issue and worked around it so there was nothing really that needed doing, and it's a problem that solves itself over time as old emails with the SharePoint attachments in stop being referenced.

**Comment by get-itips** [comment]
Hello @jpjm 
The product group was unable to reproduce what you described.
Can you confirm you followed the steps in the article exactly?
Thank you

**Comment by jpjm** [comment]
I am sure I did, this isn't an issue now since it's been a couple of months of people using the new paths. If it can't be reproduced then it might as well be closed.

**Comment by get-itips** [comment]
Thanks for returning and sharing that information
@scanum
