### ISSUE TITLE
Experimental Feature

### ISSUE THREAD

**Issue by mikecneill** [MicrosoftDocs/OfficeDocs-SharePoint#3576]
When running the commands as directed we are receiving an error saying this is experimental. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6665386e-1ad4-e9d3-565b-4b3cb3c3ea99
* Version Independent ID: 870237f7-66ec-270e-1372-c993e8dedbe9
* Content: [Custom list templates - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/lists-custom-template)
* Content Source: [SharePoint/SharePointOnline/lists-custom-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/lists-custom-template.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @mikecneill 
Thanks for your feedback, what was specifically the cmdlet that returned that message to you? Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
