### ISSUE TITLE
example URLs

### ISSUE THREAD

**Issue by jlemoo** [MicrosoftDocs/OfficeDocs-SharePoint#3579]
it would be helpful for an example of a URL to remove. I'm not sure if wildcards are permitted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6483a618-3769-564c-6497-cede9ab053c9
* Version Independent ID: 6953d747-40ec-6a06-7877-a98e42dcce1f
* Content: [Remove search results - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/remove-search-results)
* Content Source: [SharePoint/SharePointOnline/remove-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/remove-search-results.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
I'll add an example to the article, thanks for your feedback
