### ISSUE TITLE
User accounts and computer accounts in separate domains - which GUID is needed?

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/OfficeDocs-SharePoint#358]
For companies which have the user accounts and the computer accounts in separate domains, which GUID should they use? It seems that it's the domain hosting the computer accounts but the doc is ambiguous. E.g. it says "Add the GUID of each domain where you want to allow **users** to sync files" but also "To allow syncing only on **PCs** joined to specific domains".

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a62d5896-3262-b49f-aeb1-2fe8aceed122
* Version Independent ID: bc621edd-c309-1ccb-bfb8-104eae7204fb
* Content: [Permitir sincronización sólo en los equipos que se unen a dominios específicos](https://docs.microsoft.com/es-es/onedrive/allow-syncing-only-on-specific-domains)
* Content Source: [OneDrive/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jordi-j Did the update that Trevor did to this article clear things up for you?

**Comment by jordi-j** [comment]
Yes, it's clearer now.
Thanks Adrea.

**Comment by tseward** [comment]
@scanum you can close this.
