### ISSUE TITLE
Disable (not Enable) Access by Security Group

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/OfficeDocs-SharePoint#3580]
The options to disable for all, but enable access by security groups has already existed in the SharePoint Admin center for a while on the User Profiles > Use Permissions page. Perhaps that approach is being depreciated? Anyway, we've had a solution for that and I don't see any sort of solution to leave access enabled for 'everyone' except _**disable**_ access for users in a specific user group. If such a solution exists, then it would be squarely under the banner of this support page. If there is a solution, then can you please post it on this page. If not, then are you able to pass this feature need to the product group, or do I need to send feedback on the product instead? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33c02128-4157-692a-e161-7208faf41756
* Version Independent ID: 8e50bb47-75c6-09d3-d751-59f69adb3d8c
* Content: [Limit access - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/limit-access)
* Content Source: [SharePoint/SharePointOnline/limit-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/limit-access.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 
How are you?

I think this will require an entry in the feedback portal https://feedbackportal.microsoft.com/feedback/forum/e3f04660-2c1c-ec11-b6e7-0022481f8472

I'll try to pass this on too.

Thanks!

**Comment by DontNeedNoGit** [comment]
Am I correct that your feedbackportal link is for consumer OneDrive? 
My need is for OneDrive for Business. 

It would be great if such a solution could be implemeted. 

Use case: we want our staff in China to have access to email and Office apps and even be able to access SharePoint files (but not upload to sites). However, they shouldn't use OneDrive for Business so that the data they create doesn't get uploaded to US servers. We can't risk the possibility of data that shouldn't leave China due to strict privacy laws. If they violate that, then it could get them in big trouble. So, we want to disable OneDrive for our staff in China to avoid this risk. 
Workarounds and why they don't work: Conditional Access based on geography wouldn't be quite right since US-based staff may visit China and need to access their OneDrive folders. We also can't remove their license for SharePoint since we want them to be able to access data that originated from colleagues outside of China.

**Comment by get-itips** [comment]
I also see posts for OneDrive for business in the OneDrive section of the feedback portal, but in any case, you could cross-post to SharePoint feedback here https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 
Have you seen my last comment about this?
Thank you
