### ISSUE TITLE
Not Always 403 Error

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/OfficeDocs-SharePoint#3581]
I used the powershell command to disable access:
Set-SPOSite -Identity "<SiteURL>" -LockState NoAccess 

It is indeed effective at preventing access. However, this page indicates that it will produce a 403 error if you don't enable a redirect. However, this is only sorta true. 
OneDrive desktop app -- sign-in not allowed. Good.
Going to exact <siteurl> does produce a 403 error. However, I don't see a command to hide the app from tehapp launcher on a per user basis (please share if I've missed that). So, when you click the app launcher, it takes you to a page that partially loads, which is a bit confusing. I think this is because that link takes you to a slightly different URL. 

So, for example, if I were doing this for Bill Gats, I'd run:
Set-SPOSite -Identity "https://microsoftcom-my.sharepoint.com/personal/bgates_microsoft_com" -LockState NoAccess 

However, the app launcher would take him to something like this:
https://microsoftcom-my.sharepoint.com/personal/bgates_microsoft_com/_layouts/15/onedrive.aspx?login_hint=bgates%40microsoft%2Ecom&view=3

In the latter, you get a partially loaded page with a blank frame. It mostly works, but it would be good for the powershell command to result in a 403 for anything https://microsoftcom-my.sharepoint.com/personal/bgates_microsoft_com/*

Also, we need a similar command to *dynamically* do this for all members of a security group, though I understand that is outside the scope of this article.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bea1ac5a-f66c-3678-e5e5-7672407d395f
* Version Independent ID: 00fffbdd-9663-2441-a5e8-2bf541f7b1d1
* Content: [Lock and unlock sites - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-lock-status)
* Content Source: [SharePoint/SharePointOnline/manage-lock-status.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-lock-status.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 

I think this is a very specific case when using de lock against a OneDrive site while the owner tries to browse it from the launcher.
Please let me know if I understood you correctly.

Thanks

**Comment by DontNeedNoGit** [comment]
I would say this is not a "very specific case" that is outside the bounds of the support article. The article explains how to lock access to a , which is my goal. I don't want these users to access their OneDrives, and it should produce a 403b error as described in your support article. However, the app launcher button does not produce that error. I wouldn't call usage of the app launcher a "very specific case." That's how many users get to their web apps.

**Comment by get-itips** [comment]
Hello @DontNeedNoGit 

I think you misunderstood me, I am trying to understand better what you are trying to do, so I can understand if there is a need to edit the article.

I tried and could reproduce what you describe, however, it seems that currently is the way it works if OneDrive is selected from the Launcher, as you said, because of the URL being slightly different.
I'll try to report this to the team, however, a support case opened from your side would also be helpful to reach the team that can make the required adjustments to the behavior of the launcher.

Thanks for the feedback,

**Comment by DontNeedNoGit** [comment]
The article incorrectly states that a 403b error will occur. That doesn't happen with the app launcher, which I'd suggest is the main way people access it. That error only happens if someone has a shortcut to one specific URL for their OneDrive (other shortcuts won't produce a 403). 
I understand a support ticket might help, but that is a **huge** time sink for me for them to tell me it's "working as designed" and I have to submit a DCR.  
So if you think that's the only way for this to create a consistent experience, then perhaps the article should be updated to say "a 403b error will sometimes appear. Other times a partially loaded page will appear."

**Comment by get-itips** [comment]
@DontNeedNoGit Managed to report this to the product group, and I'll wait for feedback before any update to the article.
Thank you!

**Comment by get-itips** [comment]
I asked the article's author and the decision is to leave the article as-is. Also managed to report about this to the OneDrive's team.

@scanum
