### ISSUE TITLE
Remove reference to requiring Insiders Ring

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-SharePoint#3582]
Per Microsoft case #:34552889, the Microsoft engineer I worked with has confirmed that the OneDrive sync client with Folder Backup support is now in production and no longer requires being in the Insiders Ring. Please remove the first note on the page indicating that the Insiders Ring is necessary to get Folder Backup support.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19c725af-36ac-8f78-981e-3c73e615e86c
* Version Independent ID: 2cba462a-e5c4-e8ff-b8c3-cb9c0f170231
* Content: [Redirect and move macOS known folders to OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/redirect-known-folders-macos)
* Content Source: [SharePoint/SharePointOnline/redirect-known-folders-macos.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/redirect-known-folders-macos.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @aakash-shah 
We don't have access to the support case, can you kindly tell me which version in production they confirmed has the feature?
Thank you

**Comment by aakash-shah** [comment]
Sure, they informed me that build 22.217 supports it.

Here is the exact text from Case #:34552889 on 2023-01-10:

> Known Folder Move (KMF) ramped to 100% Production with build 22.217. Customers can now start planning and executing on their KFM rollout within their workspace as long as everyone is on sync client version 22.217.

>Please ensure that macOS 12.1 Monterey or later version of macOS is rolled out within your workplace and that you enable the best plist entries for your workspace once the feature has rolled out (KFMOptInWithWizard, KFMSilentOptIn, KFMBlockOptIn, KFMBlockOptOut)

>Finally, the [standalone OneDrive sync app](https://support.microsoft.com/en-us/office/onedrive-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0#OSVersion=Mac)  (not from the Mac App Store) is required for Folder Backup. This app requires Full Disk Access, which can be granted and deployed by IT admins.

However in re-reading the page, it looks like it has already been updated and no longer references the Insider ring being required. Both these pages no longer refer to this requiring the Insiders ring:
https://learn.microsoft.com/en-us/sharepoint/redirect-known-folders-macos
https://learn.microsoft.com/en-us/sharepoint/deploy-and-configure-on-macos

**Comment by get-itips** [comment]
Thanks!
