### ISSUE TITLE
Wrong key for restricting personal OneDrive use

### ISSUE THREAD

**Issue by v-rodriguesb** [MicrosoftDocs/OfficeDocs-SharePoint#3583]
The incorrect key that is on the documentation is:
**[HKCU\SOFTWARE\Policies\Microsoft\OneDrive]"DisablePersonalSync"="dword:00000001"**

The correct key is:
**[HKEY_CURRENT_USER\Software\Policies\Microsoft\OneDrive]
"DisablePersonalSync"=dword:00000001**

if the **dword:00000001** has inverted commas, the value will not be a **dword32** but a **Chain** value

this fix was tested in both Windows 10 and 11 with success
Please fix this documentation so there won't be more complains from customers

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#prevent-users-from-syncing-personal-onedrive-accounts)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
Thats only an example, Then **all** [HKCU] on the page must be replaced
Check it with a lokal Group Policiy Editor... it writes the correct Dword

**Comment by v-rodriguesb** [comment]
Hi, thanks for your quick reply.

the error is not on HKCU, is in the DWord that if it has the inverted commas, when saved in a ".reg" file, it will not work and will not create a DWord32 value but a Chain value, that is the issue in this documentation. Test it, it will not work.

**Comment by HansBrender** [comment]
I test all without any big tools (Intune, MDM…)
I test it with a local group Policy editor, then export the values from the registry.



Von: v-rodriguesb ***@***.***>
Gesendet: Dienstag, 10. Januar 2023 21:46
An: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Hans Brender ***@***.***>; Comment ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Wrong key for restricting personal OneDrive use (Issue #3583)


Hi, thanks for your quick reply.

the error is not on HKCU, is in the DWord that if it has the inverted commas, when saved in a ".reg" file, it will not work and will not create a DWord32 value but a Chain value, that is the issue in this documentation. Test it, it will not work.

**Comment by get-itips** [comment]
Hello,
I've analyzed other articles and indeed double quotes are not used, so I'll propose to remove them.
Thanks for your feedback
