### ISSUE TITLE
No mention of the fact that you need the assigned role for the 'local term set' too

### ISSUE THREAD

**Issue by WimVandierendonck** [MicrosoftDocs/OfficeDocs-SharePoint#3589]
This article does not explicitly mention the fact that you need the assigned role for both the global term store _and local term stores_.
In a way it is implied, but you must do a lot of reading between the lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5356ce0-3900-09a4-c9e7-5d9804302f71
* Version Independent ID: 7136f8c3-11d7-1bec-9355-26e42787e0b2
* Content: [Assign roles and permissions to manage term sets - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/assign-roles-and-permissions-to-manage-term-sets)
* Content Source: [SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/assign-roles-and-permissions-to-manage-term-sets.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello, with local term store do you refer to the specific _site level_ term groups?
Thanks for clarifying

**Comment by WimVandierendonck** [comment]
That's what I was referring to indeed.

**Comment by get-itips** [comment]
Hello @WimVandierendonck how are you?
Thanks for clarifying,

Do you think this is not being clear enough and more emphasis should be added?

> Site users who have appropriate permissions (such as site owners) can create new managed metadata columns for lists, libraries, or content types. When site users create these columns, they can create new term sets that apply only to the site (previously called "site collection"), and they can manage the terms within these term sets.

**Comment by get-itips** [comment]
@scanum
