### ISSUE TITLE
Update to the ODB provisioning script sample

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-SharePoint#3594]
Since the MSOnline module is planned for deprecation, I would like to propose this script to replace the sample on the page:

````
# Requires global administrator to consent one time for the User.Read.All permission
Connect-MgGraph -Scopes User.Read.All

# Arguments for Get-MgUser
$activeOdspUsers = @{
  # Ensure we get all users (all pages of the response)
  All = $true

  # For speed, only return the email property
  Select = 'mail'

  # Filter non-guests who have an active SharePoint license
  Filter = "assignedPlans/any(a:a/capabilityStatus eq 'Enabled') and assignedPlans/any(a:a/service eq 'SharePoint') and userType eq 'member'"

  # Add $count=true and consistency level header per https://learn.microsoft.com/en-us/graph/aad-advanced-queries
  CountVariable = 'licensedUserCount'
  ConsistencyLevel = 'eventual'
}

$licensedUsers = Get-MgUser @activeOdspUsers

# Connect to the SPO admin center
$adminCenterUrl = 'https://contoso-admin.sharepoint.com'
Connect-SPOService -Url $adminCenterUrl

$count = 0
do {
  # Extract 200 email addresses at a time
  $emails = $licensedUsers.Mail[$count..$count+199]

  Request-SPOPersonalSite -UserEmails $emails -NoWait
  $count += 200
}
until ($count -ge $licensedUserCount)
````

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a44f106d-ea01-b0b3-a538-ffca3eeeb29f
* Version Independent ID: 074a92aa-3117-8795-c6ff-149cff16ca25
* Content: [Pre-provision OneDrive for users in your organization - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/pre-provision-accounts)
* Content Source: [SharePoint/SharePointOnline/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
I was able to pass this feedback on, however unfortunately I don't have a timeline.
Closing this for now.
Thank you,
