### ISSUE TITLE
Page Has Incorrect Instructions

### ISSUE THREAD

**Issue by kculpepperhpc** [MicrosoftDocs/OfficeDocs-SharePoint#3595]
The instructions say to click on Users > Active users > select a user > OneDrive tab > Sharing section.  That doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec52357-8785-615f-e52f-cc9e38c8989f
* Version Independent ID: 405f0ace-09c2-0f33-5078-dc657c9dec24
* Content: [Change the external sharing setting for a user's OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/user-external-sharing-settings)
* Content Source: [SharePoint/SharePointOnline/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @kculpepperhpc 
I could successfully follow those instructions.
Are you in the Microsoft 365 admin center, right?
Thanks

**Comment by kculpepperhpc** [comment]
Yes, it looks as though now the documentation matches the UI and I am able to follow the instructions.
