### ISSUE TITLE
Needs more detail, and clarity on JSON formatting

### ISSUE THREAD

**Issue by starwispy** [MicrosoftDocs/OfficeDocs-SharePoint#3597]
Can this page please be updated to include whether JSON view formatting (applied to the base list used in site script creation) will come across in the deployed list template. When testing with a formatted gallery view, lists created from the deployed templated are missing the JSON formatting. It's unclear if this is by design.

Also the current instructions for deploying list templates have very little detail. For example:
* What are the icon names?
* What are the available colours?

Thankfully I found the below articles, but this level of detail should be in the product documentation:
https://normyoung.ca/2021/07/24/a-first-look-at-templates-in-microsoft-lists/
https://wonderlaura.com/2021/09/21/sharepoint-custom-list-templates/

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6665386e-1ad4-e9d3-565b-4b3cb3c3ea99
* Version Independent ID: 870237f7-66ec-270e-1372-c993e8dedbe9
* Content: [Custom list templates - SharePoint in Microsoft 365](https://learn.microsoft.com/en-au/sharepoint/lists-custom-template)
* Content Source: [SharePoint/SharePointOnline/lists-custom-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/lists-custom-template.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @starwispy how are you?
Can you please confirm we are talking about column formatting using JSON? https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting
thank you

**Comment by starwispy** [comment]
> Hello @starwispy how are you? Can you please confirm we are talking about column formatting using JSON? https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting thank you

Hi get-itips. Thanks for your response. This was in relation to view formatting using JSON (https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)

The issue I described where JSON was missing from the deployed list template appears to be resolved. But I believe it will still be helpful to update the article to include the relevant values for list icons and colors (so admins don't have to guess valid values for these parameters). E.g.
#Icons: Bug, Calendar, BullseyeTarget, ClipboardList, Color, Rocket, Insights, CubShape, TestBeakerSolid, Robot, Savings, Airplane
#Colors: DarkRed, Red, Orange, Green, DarkGreen, Teal, Blue, NavyBlue, BluePurple, DarkBlue, Lavendar, Pink

As well as an example of use, e.g.
Add-SPOListDesign -Title "Employee spotlight" -Description "Showcase nominated employees in a gallery view." -SiteScripts "<siteScriptID>" -ListColor DarkBlue -ListIcon Clipboard -Thumbnail "<imageURL>"

Thank you.

**Comment by get-itips** [comment]
@starwispy Larissa,
Thanks for getting back and sharing more information.

Valid values for parameters are usually in the cmdlet's article, however, I checked and Add-SPOListDesign currently has no documentation, I'll dig into that and return.

Thanks for your feedback that makes better documentation

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
