### ISSUE TITLE
LNK exclusion

### ISSUE THREAD

**Issue by FaffyBucket** [MicrosoftDocs/OfficeDocs-SharePoint#3598]
[Enter feedback here]
The excluded file types on this page seems to be incorrect, or not working. .LNK files are synced for me and all the users in my company. I have a colleague at another company with the same experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31fd97e0-7bfe-0d85-a52c-1ba28f3337c3
* Version Independent ID: 696ee19b-4364-d548-0dcb-afa6a9fff031
* Content: [Block syncing of specific file types - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/block-file-types)
* Content Source: [SharePoint/SharePointOnline/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by FaffyBucket** [comment]
We are using OneDrive with our Microsoft 365 Business Premium subscription. The Windows 11 client version we are using is currently 23.020.0125.0001, though this issue has been present at my colleague's company for over a year, so it must affect many versions.

Not sure why you are asking if I've tested default behaviour using Group Policy. I guess the answer is "yes", but the question doesn't make sense.

**Comment by get-itips** [comment]
Hello @FaffyBucket 
I tested this, and I was prevented from synchronizing .lnk files. FYI I am using version 23.038.0219.0001

**Comment by FaffyBucket** [comment]
I'm now on build 23.045.0228.0001 and .lnk files still sync :(
![5 - Build 23 045 0228 0001](https://user-images.githubusercontent.com/7036140/224196997-aee9a6c1-a50d-4afc-8729-c256e71e3328.png)

**Comment by get-itips** [comment]
Hello @FaffyBucket how are you?
I understand, I think the best in this case would be to open a support request from your tenant. As I can't reproduce and I we are limited to documentation changes and fixes.
Thanks

**Comment by FaffyBucket** [comment]
With which support team? I have already opened a ticket with Intune Support, who redirected me to 365 Support, who redirected me here.
