### ISSUE TITLE
Default setting for Rule

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#36]
Is the statement "By default, the Repair Automatically option is enabled for this rule" correct? in my farms this is DISABLED by default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59fa2ba1-01a4-d787-e7d8-7734686c55c8
* Version Independent ID: dc2de12e-3433-0f4f-dee3-e42d092d6d66
* Content: [One of the cache hosts in the cluster is down (SharePoint Server)](https://docs.microsoft.com/en-us/SharePoint/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down)
* Content Source: [SharePoint/SharePointServer/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
It is set as default, so not sure what has turned this off for you. Follow the procedure at end of this topic to turn it back on.

**Comment by DeanGross** [comment]
When I go to the Monitoring page, this rule is in the Availability category instead of the Configuration category as documented above.  Which is correct, my 2016 farm, or this documentation?

**Comment by tseward** [comment]
The Availability category is correct for 2016/2013. I've updated the doc. Repair automatically is enabled by default.

**Comment by bentoncity** [comment]
Updated correct Category to show Availability and republished topic.
