### ISSUE TITLE
Licencing clarification

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SharePoint#3608]
Please can you confirm whether Microsoft Syntex Advanced Management is part of Microsoft Purview E5 Compliance or the full E5 suite. Or this is an add.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9aa1a91-e838-41c6-45cb-6a2a4dbf1a7a
* Version Independent ID: 5f5c1b99-126f-2a70-20c8-f00136927e31
* Content: [Microsoft Syntex Advanced Management (Preview) overview - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/advanced-management)
* Content Source: [SharePoint/SharePointOnline/advanced-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/advanced-management.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by ChristianJBergstrom** [comment]
I second @nikki-c for the licensing details. We are aware that it's an add-on, but I just can't find any proper license information about the "Syntex Advanced Management" itself. The features are well described though. Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
