### ISSUE TITLE
"Silently move Windows known folders to OneDrive" does not notify on failure

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/OfficeDocs-SharePoint#361]
We're trying to deploy KFM with the option of "Silently move Windows known folders to OneDrive". 

One problem has arrised:
* It it fails to move some folders, due to symlinks in my case, the user get's no notification that KFM failed.

Me as an administrator get no notification for failed users either. It's easy to think that "Ahh, KFM is deployed, and all my users folders are protected". But thats not the case.

I think we will stick with the "Prompt users to move Windows known folders to OneDrive" option for now.

**Comment by AndreaBarr** [comment]
@o-l-a-v Thank you for the feedback on this. 

We appricate you pointing this out to us. I'm going to get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@AndreaBarr This should be raised to the PG to include some form of error notification during the migration process with some logging.

@o-l-a-v Not copying symlinked folders does make sense as OneDrive wouldn't know how to handle that. That functionality doesn't exist in OneDrive or SharePoint.

**Comment by o-l-a-v** [comment]
> @o-l-a-v Not copying symlinked folders does make sense as OneDrive wouldn't know how to handle that. That functionality doesn't exist in OneDrive or SharePoint.

I totally get that. But OneDrive should either skip it or show me an error. The first option would be preferable, as I should be able to use symlinks locally if I wish to. Or else KFM is useless for me, and I'd have to create a library outside OneDrive synced folders to get my environment working as I want it to.

**Comment by tseward** [comment]
@o-l-a-v I would post this as a feature request on https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365. That will get the attention of the engineers who work on the tool.

**Comment by o-l-a-v** [comment]
I would not categorize a bug / missing feature that should have been there in the first place, as a feature request. This is more of a major design flaw if you ask me.

**Comment by AndreaBarr** [comment]
@o-l-a-v I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
