### ISSUE TITLE
Block uploads from external users

### ISSUE THREAD

**Issue by scottw-at-ivetoplaysports-dot-com** [MicrosoftDocs/OfficeDocs-SharePoint#3615]
This block sync is inadequate in the face of how Sharepoint is used. Will a blocked extension be effective in blocking external users with permission to upload to a site. Is it possible to prevent external users from uploading specific file types? Sync is only one part, a smaller part, of the security questions. The more significant need is to restrict external uploads.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31fd97e0-7bfe-0d85-a52c-1ba28f3337c3
* Version Independent ID: 696ee19b-4364-d548-0dcb-afa6a9fff031
* Content: [Block syncing of specific file types - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/block-file-types)
* Content Source: [SharePoint/SharePointOnline/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @scottw-at-ivetoplaysports-dot-com 
Here we are limited to documentation changes and fixes, is there any fix to the documentation that you see is necessary? 
Otherwise, if it is a feature request, the best resource would be https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
