### ISSUE TITLE
"Errors or timeout for Server Processing the file:Not all the items in the package have been migrated"

### ISSUE THREAD

**Issue by cafranjul** [MicrosoftDocs/OfficeDocs-SharePoint#362]
Hello, 

While trying to upload documents from a on-prem 2013 SharePoint to Office 365 Sharepoint, using SPMT v2.1.101.6 and after 3 rounds, I have 0 documents being migrated, on the  'ItemFailureReport_R1.csv' I have all the documents with this error:

"SERVER FAILURE","Errors or timeout for Server Processing the file:Not all the items in the package have been migrated"

I am administrator on both on-prem SP, and o365 SP. 

there's no much details on why  not all the items in the package have been migrated, I mean, is it because permission? time out to trying to connect internet (which the server doesn't have really), what is it? 

any help will be really appreciated. 

thanks,
Juan Carlos Munoz

**Comment by AndreaBarr** [comment]
@cafranjul Thank you for reaching out to us. 

Let me get this migration issue over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
@AndreaBarr @scanum 
This issue is a technical issue, and it should be resolved using a regular case to the O365 enterprise support.

**Comment by scanum** [comment]
@cafranjul - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
