### ISSUE TITLE
Incorrect information is described about SharePoint Migration Tool

### ISSUE THREAD

**Issue by hysenyu9527** [MicrosoftDocs/OfficeDocs-SharePoint#3628]
In the documentation below, It says SPMT only migrates default SharePoint groups from SharePoint On-premises site to SharePoint Online.
But I have verified not only the default SharePoint group, the SharePoint groups that created by the user are also migrated to SharePoint Online.
So if it is true that all SharePoint groups of a On-premises site can be migrated to SharePoint Online by SMPT, the document below is misleading now.

Create a user-mapping file for data content migration - Migrate to Microsoft 365 | Microsoft Learn
https://learn.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration
----
SPMT only migrates default SharePoint groups.
----
 
It should be corrected like below
----
SPMT migrates all SharePoint groups. (including the default SharePoint groups and the SharePoint groups created by the user)
----

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user-mapping file for data content migration - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @hysenyu9527 
Can you please specify the version of SPMT used?
Thanks

**Comment by scanum** [comment]
@get-itips

**Comment by get-itips** [comment]
I could finally get information

"SPMT can migrate SP Groups only when migrating the whole site. Source and destination are mapped by group name."
