### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by princemanjee** [MicrosoftDocs/OfficeDocs-SharePoint#363]
NO User Profile Service Upgrade Info here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67cc68b-2d40-7d78-9ae5-a71938b6fa78
* Version Independent ID: 52fd8de6-598e-7672-eb34-2fa7a46b0182
* Content: [Upgrade service applications to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016#see-also)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@princemanjee Did Trevors update to the article resolve this issue?

**Comment by princemanjee** [comment]
@AndreaBarr  Yes it does. Thank you for the update!
