### ISSUE TITLE
SCCM Application Detection Method

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/OfficeDocs-SharePoint#365]
The Script detection method in the sample application provided only checks for the existence of OneDrive.  It does not do a version check.  How do we use this for updating an existing installation of the OneDrive client? What is the best way to determine the client version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows?redirectSourcePath=%252farticle%252f3f3a511c-30c6-404a-98bf-76f95c519668)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jpoling1 Thank you for this inquiry

I am not sure what the best way to determine the client version would be. Let me get this over to the SharePoint team for investigatoin. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@jpoling1 As OneDrive automatically updates in a silent fashion under the context of the user, there is no need to update the client application via SCCM or any other IT-controlled method. This ensures you have the latest version of the client and that you do not fall behind in versions.

You could execute the following application, although this application is installed on a per-user basis.

    C:\Users\userName\AppData\Local\Microsoft\OneDrive\OneDriveStandaloneUpdater.exe

**Comment by MatthewCKelly** [comment]
Updated SCCM Detection Rule script
`<#  
Test to see if OneDrive exists and correct version.

Onedrive exists ?

# C:\Users\MattTheDomainUser\AppData\Local\Microsoft\OneDrive\OneDrive.exe

About SID's https://msdn.microsoft.com/en-us/library/windows/desktop/aa379649(v=vs.85).aspx

OneDrive Versions : https://support.office.com/en-us/article/New-OneDrive-sync-client-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0

#>


Function Write-Log {
<#
    .SYNOPSIS
	Writes to host formatted 
    .DESCRIPTION
	"Write-Log"
    .PARAMETER logstring

    .INPUTS
        [String]

    .OUTPUTS
        [Standard file]
    .EXAMPLE
	    Write-Log -logstring "This is my message for the log file."
    .LINK
#>
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, ValueFromPipeline = $true,HelpMessage="Please Enter string to display.")]
        [string]
        [ValidateNotNullOrEmpty()]
        $logstring
    )

    If (Test-Path $Logfile -PathType Leaf ) {
        If ((Get-Item $Logfile).Length -gt 5MB) {
                        Rename-Item $Logfile $Logfile“.bak” -Force
        }
    }
    $WriteLine = "$(Get-Date -Format s)`t$($MyInvocation.ScriptLineNumber) `t- $logstring"
    Add-content $Logfile -value $WriteLine
}          # End of Write-Log


# onedrive Version
$oneDrvVersion    = "18.192.0920.0015"

$sessionGUID    = [System.Guid]::NewGuid().ToString().toUpper();
$tmpPath        = [System.Environment]::ExpandEnvironmentVariables("%tmp%");
$Logfile        = "$tmpPath`\Install-OneDrive.log"
$myLoop         = $true;

if ($env:SESSIONNAME -like 'Console' ) {
    # Logged into the device locally.
    Write-log           "local User."

    $UserObj           = Get-WmiObject win32_computersystem -Property Username
    if ( [string]::IsNullOrEmpty($UserObj.UserName) -eq $true ) {
        Write-log       "Offline use local - ?"
        $UserName       = "$env:USERNAME"
        Write-Log       "UserName `"$UserName`""

    } else {
        Write-log       "WMI username `"$($UserObj.UserName)`""
        $UserName       = [string]$UserObj.UserName
        Write-Log       "UserName Full `t`"$UserName`""
        $UserSplit      = $User.UserName.Split("\")
        $UserName       = $UserSplit[1];
        Write-Log       "UserName `"$UserName`""
    }


    $OneDrivePath   = Join-Path $env:SystemDrive -ChildPath "users\$UserName\appdata\local\microsoft\onedrive\onedrive.exe"


    } else {
       Write-log "Remoted onto the machine"
        # Get-WmiObject  Win32_UserProfile -Property Username 
       $LocalSession  =  Get-WmiObject -Namespace root\cimv2 -query 'Select LocalPath, Loaded, SID From Win32_UserProfile  Where Loaded = 1 AND  SID <> "S-1-5-20" AND SID <> "S-1-5-19" AND SID <> "S-1-5-18" '
       if ( $($LocalSession | Measure-Object).Count -eq 1  ) {
        $OneDrivePath   = Join-Path $($LocalSession.LocalPath) -ChildPath "appdata\local\microsoft\onedrive\onedrive.exe"
       }
}


Write-log "Using profile path `"$OneDrivePath`""

Write-Log "Checking for `"$OneDrivePath`""
if ( test-path $OneDrivePath -PathType Leaf ) {
    Write-Log "is `"$OneDrivePath`" OneDrive installed !"
    $tmpFile = Get-Item $OneDrivePath;
    write-log "OneDrive.exe version : `"$($tmpFile.VersionInfo.ProductVersion)`""
    if ( $tmpFile.VersionInfo.ProductVersion -ge $oneDrvVersion) {
        Write-Log "`tCorrect version installed $($tmpFile.VersionInfo.ProductVersion)"
        $myLoop = $false
    } else {
       Write-log "Wrong version installed, need the correct OneDrive for installing"
        $myLoop = $true
    }

}


if ( $myLoop -eq $false ) {
    write-host "OneDrive installed and correct version !"
    exit 0
} else {
# write-host "OneDrive not found, install !"
#  exit 1

}
`

**Comment by GTAfanattic** [comment]
Changed line 25:
If(Test-Path $OneDrive) 
to 
if ((Get-Item $OneDrive).VersionInfo.FileVersion -gt '18')

Clients were version 17 or lower, needed them to be 18 or higher. They were being detected as installed as the detection rule was only checking the presence of the file rather than the version.

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by get-itips** [comment]
Hello @kaarins can you help us with this? We could make the proposed changes but as some time has passed I would like to check with you. Thank you.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, wondering if there is any updates on this? Thanks!

**Comment by get-itips** [comment]
Hello @kaarins can you kindly help us with this? Thank you

**Comment by scanum** [comment]
@get-itips Hi Andres please make proposed changes. Thanks!

**Comment by MikePlumleyMSFT** [comment]
Seems like the original question was answered in this thread. Please reopen if anything additional is needed.

**Comment by rickym61** [comment]
Detection method still doesn’t work in the package sample, if you run it manually complains about null values. Anyone got this working?
