### ISSUE TITLE
Missing information about authentication in Hybrid scenarios

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/OfficeDocs-SharePoint#3660]
What is the authentication flow for access to SharePoint in hybrid scenarios where AD/AAD connect exists?
How do internal and external users authenticate against a) local AD/SharePoint on-prem vs b) AAD/SharePoint online? 
How is authentication managed for content existing on-prem when accessed from the cloud and vice versa?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 351d4d9a-7c97-ee21-fe87-1071ae099717
* Version Independent ID: 818f8e43-033e-868c-6c66-39fc7840f65d
* Content: [SharePoint authentication - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/authentication)
* Content Source: [SharePoint/SharePointOnline/authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/authentication.md)
* Service: **sharepoint-online**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by get-itips** [comment]
Hello @a-goo how are you?

Have you seen this resource?

https://learn.microsoft.com/en-us/sharepoint/hybrid/the-building-blocks-of-office-365-hybrid

**Comment by a-goo** [comment]
> Hello @a-goo how are you?
> 
> Have you seen this resource?
> 
> https://learn.microsoft.com/en-us/sharepoint/hybrid/the-building-blocks-of-office-365-hybrid

Yes. My point is that the source page here: https://learn.microsoft.com/en-us/sharepoint/authentication makes ZERO references to any other MS documentation regarding HYBRID authentication. Where's the page interlinking? Were's the cross referencing? Where's the deep linking to specific content??
