### ISSUE TITLE
Should "OneDrive" license be added to the requirements section?

### ISSUE THREAD

**Issue by thiagottss** [MicrosoftDocs/OfficeDocs-SharePoint#3667]
Is a OneDrive/SharePoint license required for the Guest User to be able to sync a library with OneDrive? 

![image](https://user-images.githubusercontent.com/22349671/222440324-2bbcfd0f-725f-4edf-b1c6-fa9c1fca024e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 551144b4-b57a-251c-79ef-7bbddfd60e16
* Version Independent ID: 2eab7898-16c7-d764-2334-fb561b34c8fb
* Content: [B2B Sync - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/b2b-sync)
* Content Source: [SharePoint/SharePointOnline/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @thiagottss 
How are you?
I think that is implied and covered by

> Sharing recipients must have a Microsoft 365 work or school account (in Azure AD).

Was the user you were trying to use not licensed at all?

Thanks

**Comment by thiagottss** [comment]
> Hello @thiagottss How are you? I think that is implied and covered by
> 
> > Sharing recipients must have a Microsoft 365 work or school account (in Azure AD).
> 
> Was the user you were trying to use not licensed at all?
> 
> Thanks

Hi! 
He was a guest of our tenant. He had a license for their own tenant not for ours. 

We were trying to share a large number of files and folders with him and the sync would help a lot.

Thanks,
Thiago.

**Comment by get-itips** [comment]
Hello @thiagottss Thiago,
I tested the scenario on my lab based on your comments, and I had no issues to sync the shared content.
If you still face issues I recommend opening a support request.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by get-itips** [comment]
> > Hello @thiagottss Thiago, I tested the scenario on my lab based on your comments, and I had no issues to sync the shared content. If you still face issues I recommend opening a support request.
> 
> Were you able to sync a library from another tenant? Without the need of assigning a license to the Guest account?

I can confirm I just followed the instructions here.

**Comment by HansBrender** [comment]
I learned that the "Source" organization needs 1/5 license for external users for B2B
