### ISSUE TITLE
What about SharePoint version 2019?

### ISSUE THREAD

**Issue by scarolaa** [MicrosoftDocs/OfficeDocs-SharePoint#3668]
It seems that 2019 should be added to the list of supported versions, as Microsoft itself states that it is supported: [https://learn.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool](https://learn.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)

This is specifically regarding the page at https://learn.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt

**Comment by scarolaa** [comment]
Mistakenly posted this to the wrong page.

**Comment by get-itips** [comment]
Thanks for your feedback, I see your PR has been merged.

**Comment by scarolaa** [comment]
Awesome! Thank you
