### ISSUE TITLE
Proceed or precede?

### ISSUE THREAD

**Issue by tombraman** [MicrosoftDocs/OfficeDocs-SharePoint#3680]
Did you mean the word "preceding" rather than "proceeding" in the following sentence: " This level (and all proceeding levels) of peer associated hubs behaves the same way as the first level. "

To me, the word "preceding" suggests that the levels 1 and 2 sites will be included in search scopes when searching in levels 1, 2, or 3. The word "proceeding" suggests that levels beyond 1, 2, and 3 (i.e., 4, 5, and so on) will be included in search scopes, but as the follow-up sentence in the article says, that's not the case.

If the word "proceeding" is actually correct, could you clarify what's meant by "behaves"? Thank you! - tom

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/hub-to-hub-association)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by MattEEvans** [comment]
Thanks for the feedback. I think it should say "preceding" as Tom suggested.
