### ISSUE TITLE
No setting in the UI?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-SharePoint#3681]
Is there really not a checkbox or On/Off slider for the File Request feature?  Jumping through all kinds of pages and running a dozens commands just to turn something on is really annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb80c7f-b87a-6910-b145-1261ce7be4fc
* Version Independent ID: 6085e0fb-1eb5-3a33-9771-11a4b4c6bee2
* Content: [Enable File Requests in SharePoint or OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/enable-file-requests)
* Content Source: [SharePoint/SharePointOnline/enable-file-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/enable-file-requests.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
