### ISSUE TITLE
Elaborate "Replace STS Certificate" steps

### ISSUE THREAD

**Issue by kannanambadi** [MicrosoftDocs/OfficeDocs-SharePoint#37]
Why did you removed the detailed steps given in the previous technet article? 
Configure the Security Token Service (STS) in SharePoint Server:
Create a new STS certificate.
Replace the default STS certificate on each server in your SharePoint Server farm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d499cfa0-9a8e-37c8-4607-874d3d72ed69
* Version Independent ID: 267ded1d-8e8d-3d11-44b4-3e83c70d40c8
* Content: [Configure server-to-server authentication from SharePoint Server to SharePoint Online](https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-server-to-server-authentication)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md)
* Service: **unspecified**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by kenwith** [comment]
@kannanambadi - the articles were recently moved from TechNet to an open source format that uses GitHub. This might be a gap that needs to be explored. Sorry for the delay on the response. We will look into the steps that were removed and how this article can be more clear. Let's leave this open for now. If you have any more information please feel free to respond here. In the meantime we will get this in our backlog to have a Subject Matter Expert (SME) research and evaluate the gap you identified.

**Comment by kenwith** [comment]
@kannanambadi - I was able to get this into the backlog for the steps in the article you mentioned from TechNet. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay!

**Comment by AndreaBarr** [comment]
@tseward Is investigation this issue.

**Comment by cjtireus** [comment]
Pretty good summary here, https://msdn.microsoft.com/en-us/data/dn551378(v=office.14) Copy&paste to Git?

**Comment by MikePlumleyMSFT** [comment]
There's a new article that covers replacing the STS cert in a farm. [Replace the STS certificate for SharePoint Server](https://docs.microsoft.com/sharepoint/administration/replace-the-sts-certificate). It's no longer necessary to replace the default STS cert for configuring hybrid unless you want to use a cert from a public authority.

**Comment by MikePlumleyMSFT** [comment]
That's correct. We recommend using [the hybrid picker](https://docs.microsoft.com/en-us/sharepoint/hybrid/hybrid-picker-in-the-sharepoint-online-admin-center) to configure SharePoint hybrid.

**Comment by cjtireus** [comment]
Also for outbound federated hybrid search configuration from SP2013 to SPO? Hybrid picker is the MS recommended way to go?

**Comment by MikePlumleyMSFT** [comment]
Yup. (Adding @tklarsen in case I'm missing anything.)

**Comment by kenwith** [comment]
This seems like an awesome conversation and it is over the top of my head. Would @cjtireus @kannanambadi be willing to capture this expertise you have into the document? Maybe as a note so others can benefit from this one when they read the document? :)  I can guide you through how to do a Pull Request and you then become 'contributors' on the content too. The conversation just seems really valuable so I am thinking of a way to capture it in the doc for the community.

**Comment by kenwith** [comment]
@tseward - maybe something you could add too? @tseward is a SharePoint MVP. :)

**Comment by kannanambadi** [comment]
Thank you all for your prompt responses👍👍👍

I have hybrid deployment planned for next week. It is one way OUTBOUND hybrid between SharePoint 2013 onprem to SharePoint Online. I would be happy to know that we do not need to replace default STS certificate.

Sent from mobile

________________________________

**Comment by tseward** [comment]
If I recall, you can go through one of the Hybrid wizard scenarios like Hybrid B2B sites which doesn't make any changes but it does configure the ACS proxy and app principal in Azure AD.

Might be worth going that route so you only have to configure Search after that. Here's an old article by Bill Baer on federated search: https://blogs.technet.microsoft.com/wbaer/2014/03/24/one-way-outbound-hybrid-search-step-by-step-and-onedrive-for-business/.

**Comment by JonathanHerschel** [comment]
@MikePlumleyMSFT, if Hybrid Picker is recommended for Hybrid Search, can you add a note to the top of this page?  I have been running through steps for past week and didn't realize there were comments down here on the bottom of the page and it might save future readers time to know some of above is no longer necessary.

**Comment by tseward** [comment]
@JonathanHerschel Can do. @AndreaBarr please assign this to me.

**Comment by ashokgop** [comment]
Sorry I am now confused!  Are we now saying that "we DO NOT need to replace the STS certificate on the on-prem SharePoint servers when configuring SharePoint for one-way Outbound Hybrid search?  If so why is the main article above not updated to reflect this new recommendation?
