### ISSUE TITLE
Troubleshooting section?

### ISSUE THREAD

**Issue by LemmingFMGL** [MicrosoftDocs/OfficeDocs-SharePoint#3705]
This page desperately DESPERATELY needs information on how to troubleshoot sync issues. Information on how sync works doesn't help you when sync is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 367f3b91-1252-7bce-fd1e-21ceb1ae12f3
* Version Independent ID: 66e3f10a-0231-e7e0-0659-0be66eaf13fa
* Content: [Sync in SharePoint and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-sync)
* Content Source: [SharePoint/SharePointOnline/sharepoint-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
so for me its: 
1) a [support page with restrictions and limitations](https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa) for OneDrive and OneDrive for Business
2) Roll out a GPO [EnableSyncAdminReports](https://docs.microsoft.com/en-us/onedrive/use-group-policy?WT.mc_id=M365-MVP-4040055#allow-tenant-health-reporting-from-onedrive) , so the you find aan error for a user, you can step in and often got a direct lin, whats wrong

**Comment by scanum** [comment]
/
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
