### ISSUE TITLE
Typo </integer>

### ISSUE THREAD

**Issue by bootrec** [MicrosoftDocs/OfficeDocs-SharePoint#3710]
There's a typo in this document:

```
Enter the following preference key to enable the setting:
<key>EnableSyncAdminReports</key>
</integer>1</integer>
```

Last line should be
`<integer>1</integer>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=macos)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
