### ISSUE TITLE
Clarifying what happens when "Set-SPOTenant -HideSyncButtonOnTeamSite $true" is run.

### ISSUE THREAD

**Issue by sm3phx6j** [MicrosoftDocs/OfficeDocs-SharePoint#3712]
[Enter feedback here]
Can the KB be clarified if running "Set-SPOTenant -HideSyncButtonOnTeamSite $true" will just prevent users from creating new syncs with the "Sync" button?  Or will it also stop existing syncs made with the "Sync" button made before the change from working?  Basically, can the administrator prevent new syncs with the "Sync" button but not affect the existing syncs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 367f3b91-1252-7bce-fd1e-21ceb1ae12f3
* Version Independent ID: 66e3f10a-0231-e7e0-0659-0be66eaf13fa
* Content: [Sync in SharePoint and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-sync)
* Content Source: [SharePoint/SharePointOnline/sharepoint-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@sm3phx6j hiding the button only affects new syncs. Existing syncs continue to run. I'll update the article to clarify.
