### ISSUE TITLE
Search Config List is not available

### ISSUE THREAD

**Issue by merlinbrohl-adesso** [MicrosoftDocs/OfficeDocs-SharePoint#3716]
In the "Import customized search configuration settings to a (...)" sections, the document states "On the Search Config List page, verify that:(...)".
That list is not available via the Browser - the redirect to [tenant]-admin.sharepoint.com/Lists/SearchConfig/AllItems.aspx results in a "File Not Found." error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6d5348-0b97-842d-cc4d-e50c04bd8bd4
* Version Independent ID: 1a9d4b68-d4cb-ff62-cd2d-32c0e7e73298
* Content: [Export and import customized search configuration settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/export-and-import-search-settings)
* Content Source: [SharePoint/SharePointOnline/export-and-import-search-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/export-and-import-search-settings.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @merlinbrohl-adesso 
I could follow the process and the redirect to 

https://tenant-admin.sharepoint.com/Lists/SearchConfig/AllItems.aspx

didn't result in 404 for me.

If it is still not working for you I recommend to open a support request.

Thank you!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by merlinbrohl-adesso** [comment]
Sorry, I wasn't describing my issue correctly. This issue is sepcific to importing the search config to a tenant, not at any other scope (section https://learn.microsoft.com/en-us/sharepoint/export-and-import-search-settings#import-customized-search-configuration-settings-to-a-tenant).
The List "SearchConfig" exists and I can query it using e.g. the REST API. But the AllItems.aspx View seems to be nonexistent in the tenant admin site.
I could reproduce this in four different tenants, that I have access to.
