### ISSUE TITLE
Missing secure configuration information

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-SharePoint#3720]
This page is missing to information on setting the Organization default for sharing links as "People with Existing Access link (which does not modify permissions)" that is required by Zero trust Architecture, please provide the steps for this.  Obviously we do not want links creating access that is different than what has already been configured for a site.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default sharing link for a site - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-default-sharing-link)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @ssmiller60 

Probably you are talking about what you can set with the `-DefaultLinkToExistingAccess` parameter in `Set-SPOSite`

> When set to TRUE, the DefaultSharingLinkType will be overriden and the default sharing link will a People with Existing Access link (which does not modify permissions). When set to FALSE (the default), the default sharing link type is controlled by the DefaultSharingLinkType parameter

The page you opened the issue for is specifically to modify it for a specific site but you mention at organization level, I'm not seeing the same setting at Tenant level.

Please let me know if I understood you correctly,

Thank you!

**Comment by ssmiller60** [comment]
Yes, this is the info I had in mind and WOW I am absolutely flooded that
Microsoft would make such a clear security misstep by not allowing for an
option that the existing defined security would be the default across the
entire tenant!!! Is the the twilight zone??? This is crazy town!!

**Comment by get-itips** [comment]
Hello @ssmiller60 

Please share your feedback here https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472 as here we are limited to documentation changes and I'll also get back to this thread if I found out more in the future.

Thank you,

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
