### ISSUE TITLE
Installations instructions for Azure Fabric should be added

### ISSUE THREAD

**Issue by stefangossner** [MicrosoftDocs/OfficeDocs-SharePoint#3726]
Feedback from customer: Some clear instructions on installing the prerequisite Azure Fabric would probably also be exceedingly helpful because the existing documentation on that product isn't really targeted at what you need to do with that installation to specifically support this workflow product.

**Comment by scanum** [comment]
Hi @stefangossner hope all is well. Could you please help me link the article?

**Comment by get-itips** [comment]
@stefangossner Can you please add the article you are talking about? Thank you

**Comment by stefangossner** [comment]
There is currently no such article. This is information which is currently missing but not available.

**Comment by get-itips** [comment]
I understand, however, this issue was created under the SharePoint documentation

**Comment by stefangossner** [comment]
I see your point. Azure Service Fabric is a prereq for SharePoint Workflow Manager and we require it to be installed first, but if instructions on how to install it would be better included in an Azure Service Fabric article. Is that what you mean?

**Comment by get-itips** [comment]
Thanks Stefan,

I understand now that you are talking about **SharePoint Workflow Manager**, probably you have seen this article? 

https://learn.microsoft.com/en-us/sharepoint/governance/install-and-configure-workflow-for-sharepoint-server#prerequisites

There, you have the instructions on how to install the Azure Service Fabric runtime. Do you still feel those instructions are not complete?

Thanks,

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
