### ISSUE TITLE
Include guidance for cloud-only scenarios.

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SharePoint#3728]
As cloud adoption continues, fewer users will be joining workstations to an AD DS domain. This "Allow syncing only on computers joined to specific domains" setting is not compatible with the modern landscape and at the least, the article should suggest Conditional Access policies to people looking to lock down OneDrive sync.

A link to this article would be good enough: https://learn.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aff608fe-1f13-ad08-df3e-d2db050b87f8
* Version Independent ID: 32325172-804d-fac1-5deb-9e51ccc6dd75
* Content: [Allow syncing only on computers joined to specific domains - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/allow-syncing-only-on-specific-domains)
* Content Source: [SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello, I'll propose to add that link to the article, if it gets approval, it will be in the published version of the article.
Thanks for your feedback,
