### ISSUE TITLE
DLM - How does the OneDrive Clean Up Job work together with retention policies/labels?

### ISSUE THREAD

**Issue by janvonr** [MicrosoftDocs/OfficeDocs-SharePoint#3733]
[Enter feedback here]

The following topics/questions are not completely answered in the documentation and customers are often asking for a clear feedback regarding them, as this could have a big impact on the retention/deletion implementation.

How does the OneDrive Clean Up Job work together with retention policies/labels?

If a retention policy is applied on the OneDrive site, the whole site and its content will be retained -->  If the retention period is over will the OneDrive site be automatically deleted? If not, how should customers handle these orphaned sites, how can they be identified?

What's the behavior if we work with retention labels? As the OneDrive site cannot be deleted, will all content remain where it is regardless of whether a label is assigned or not? If the retention period for all the labels is over will the OneDrive site be deleted automatically?

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 330f0ccf-dad3-a11e-f5b8-050c149e6148
* Version Independent ID: 6323126b-d8b2-3eab-98c6-dfa570bec23c
* Content: [OneDrive retention and deletion - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/retention-and-deletion#the-onedrive-deletion-process)
* Content Source: [SharePoint/SharePointOnline/retention-and-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/retention-and-deletion.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
