### ISSUE TITLE
Please clarify the meaning of this phrase: "The Loop app does not yet support eDiscovery workflows."

### ISSUE THREAD

**Issue by sandra-titarelli** [MicrosoftDocs/OfficeDocs-SharePoint#3738]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41c35b5-e159-ed6d-a9ff-bea0ef7f0736
* Version Independent ID: 2eca8e70-2e83-b100-890b-03b4377186e9
* Content: [Manage Loop experiences (Loop app and Loop components) in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-loop-components#ediscovery)
* Content Source: [SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @sandra-titarelli 

The note has been updated recently and right above more information about what is supported is provided.

Thank you

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
