### ISSUE TITLE
Clarification on 93 Days "start time"

### ISSUE THREAD

**Issue by jmaiher** [MicrosoftDocs/OfficeDocs-SharePoint#3742]
In the first paragraph where it talks about the time durations, I undestand that during the retention period (default 30 days) shared content can still be accessed by other users. It then states "At the end of the time, the OneDrive will be in a deleted state for 93 days and can only be restored by a global or SharePoint admin". 

Can we get clarification as to whether the "93 days" starts when the account is first deleted, or, if it starts at the end of the retention time? 

For example, with default settings in place:
1/1/23 - Acct deleted in AD
1/31/23 - Shared Content is no longer available (or shouldn't be per the article)
Does the OneDrive stay in a deleted state until 4/4/23 (93 days from 1/1/23) or 5/4/23 (93 days from 1/31/23)

May wish to also change the sentence to "At the end of the time, shared content can no longer be accessed by other users, and, the OneDrive will be in a deleted state for 93 days where it can only be restored by a global or SharePoint admin"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42531982-8c57-550c-e108-f72992368510
* Version Independent ID: 5c90f1d2-e171-a242-737d-9f3113f12eb2
* Content: [Restore a deleted OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restore-deleted-onedrive)
* Content Source: [SharePoint/SharePointOnline/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @jmaiher 

How are you?

I'll try to confirm however I believe the 93 days count will begin once this 30 day ends, because it says

_During **this time**, shared content can still be accessed by other users. At the end of **the time**..._

Maybe it would be more clear to say "At the end of **this** time...".
