### ISSUE TITLE
Managing Search Schema Permissions should be available to those who have Full Control, not just Administration

### ISSUE THREAD

**Issue by zen-out** [MicrosoftDocs/OfficeDocs-SharePoint#3744]
I'm referring to this article: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-search-schema.md - users who have full control of the website should also be allowed to change the Search Schema... not just Administrators.

**Comment by get-itips** [comment]
Hello @zen-out 
Here, we are limited to documentation changes and improvements, for feature requests and feedback, this is the best resource
https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472
Thanks for your feedback
