### ISSUE TITLE
Share point online : context.ExecuteQuery() -> "Access denied" for File.

### ISSUE THREAD

**Issue by jiaudheenam** [MicrosoftDocs/OfficeDocs-SharePoint#3749]
Hi,
I have an AAD registered app with Api permission "**SharePoint/Sites.Selected**". The permission for the app to access those selected sites are provided in the SharePoint online.  
My app also set with **Full Control** to sitecollection scope in the SharePoint. 
My request is authenticated successfully and authorized until executing ExecuteQuery() at Web and Root Folders contexts.

When I execute ExecuteQuery() for reading a file in the document library, "**Access denied**" exception is thrown. My assumption is, if the app has set with Full Control to sitecollection scope, it should allow to read the files in the permitted SharePoint sites. Correct me if I am wrong. 
Need your inputs to resolve this issue.

Code snippet attached,
[SP access  issues code snippet.txt](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/11092832/SP.access.issues.code.snippet.txt)
        
Thanks.
![image](https://user-images.githubusercontent.com/100896192/228324727-13e2b1a4-f6e2-42a6-89d3-c3447e495c55.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/100896192/228328070-35c89ddd-faa4-4648-aaaa-62a6d8ee10ff.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
