### ISSUE TITLE
OneDrive: "Sign in to turn on offline access to your lists" pointing to *removed* work account - follow up

### ISSUE THREAD

**Issue by RGlanzmann** [MicrosoftDocs/OfficeDocs-SharePoint#3754]
As you requested, 

I opened a support case (TrackingID#2303141420000146). They have no clue. Support first suggested to just switch off List Sync.

• Navigate to HKLM\SOFTWARE\Policies\Microsoft\OneDrive] "DisableNucleusSync" = "dword:1"

Now they wanted me to run Network Packet analyzer software and help them re-engineer/understand how YOUR software works? 

But in the meantime I found the formers employers servers listed in this file:
"C:\Users\remog\AppData\Local\Microsoft\OneDrive\ListSync\Business1\settings\Microsoft.ListSync.db"

As other users already found out, simply deleting the folder seems not to solve the issue, there seems to be a cloud-side reference somewhere as well.

How on earth can we get a developer to properly investigate this issue? 57 users need a solution. The community thread has over 1300 views and counting ...

https://answers.microsoft.com/en-us/msoffice/forum/all/remove-sign-in-to-turn-on-offline-access-to-your/94c46653-75b7-4447-9bc4-0542b7637822

I feel like I have to personally drag this case all the way from Shanghai (MS Support Subcontractor) to you to get the attention of people who can actually help to solve the issue. This is frustrating.

**Comment by get-itips** [comment]
hello @RGlanzmann 
Here we are limited only to documentation changes and fixes, can you please point to the article you are talking about and kindly tell us what you see is wrong with it? Thank you

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
