### ISSUE TITLE
About standard license.

### ISSUE THREAD

**Issue by mgoto-git** [MicrosoftDocs/OfficeDocs-SharePoint#3755]
[Enter feedback here]

Please clarify limitations for standard license in this function.

Without SharePoint Advanced Management license , it seems only actions in browser session are displayed , but it is not described.

It's not clear what are "**Some features** in this article require Microsoft Syntex - SharePoint Advanced Management".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef1b620-0a97-5677-fe80-3129f2103024
* Version Independent ID: 4f253654-152f-c5bd-056d-8fc188de7850
* Content: [Review recent SharePoint site actions - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/SharePoint/recent-actions-panel)
* Content Source: [SharePoint/SharePointOnline/recent-actions-panel.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/recent-actions-panel.md)
* Service: **sharepoint-online**
* GitHub Login: @MachelleTranMSFT
* Microsoft Alias: **mactra**

**Comment by TobiasAT** [comment]
Have the same question, what's the difference between Standard and Premium (the SharePoint Advanced Management license add-on)? As scanum is assigned to this issue I assume we get the standard response of opening a support case.

**Comment by get-itips** [comment]
Hello @mgoto-git I'm working on this.

**Comment by get-itips** [comment]
Article has been updated, thank you!

**Comment by mgoto-git** [comment]
Hello, @get-itips . Thank you for quick update.
