### ISSUE TITLE
Edit permission gives more control than what's specified in this page. Edit permission will let user Add/customize page however the table does not have it checked implying this permission cannot make any changes in regards to Ass and Customize pages. 

### ISSUE THREAD

**Issue by pratikbhusal18** [MicrosoftDocs/OfficeDocs-SharePoint#3776]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint - SharePoint in Microsoft 365](https://review.learn.microsoft.com/en-us/sharepoint/understanding-permission-levels)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by pratikbhusal18** [comment]
Like the title says 
Edit permission gives more control than what's specified in this page. Edit permission will let user Add/customize page however the table does not have it checked implying this permission cannot make any changes in regards to Ass and Customize pages.

**Comment by get-itips** [comment]
Hello @pratikbhusal18 

I checked an out of the box site's permission levels and "_**Add and Customize Pages**  -  Add, change, or delete HTML pages or Web Part Pages, and edit the Web site using a Microsoft SharePoint Foundation-compatible editor._" is not checked as included in that permission level.

Can you please details what you have experienced?

Thank you

**Comment by get-itips** [comment]
Hello @pratikbhusal18 Could you see my comments here?
