### ISSUE TITLE
Request to update Requirements section

### ISSUE THREAD

**Issue by msjoat** [MicrosoftDocs/OfficeDocs-SharePoint#3782]
Could you please remove the following bullet point from the Requirements section as it is causing some confusion now that all rings, including the Deferred ring, are past the v22.232 requirement, as per [onedrive-release-notes](https://support.microsoft.com/en-us/office/onedrive-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0).

**- OneDrive sync apps on the Insiders or Production ring. Users on Deferred rings can access the dashboard once 22.232 has rolled out to the ring. [Set the sync app update ring](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#set-the-sync-app-update-ring).**

The way this statement reads can give an impression that the sync apps must (still) be on the Insiders or Production ring.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=windows)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
Removed in https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/commit/166f63a7d1610cd1aee73d48d32013d6739354e0
