### ISSUE TITLE
Add-on is not available for M365 Business Premium licenses

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/OfficeDocs-SharePoint#3783]
Seems the product team forgot that a M365 Business Premium license includes a SharePoint Plan 1. 
In the current state customers with M365 Business Premium licenses are not able to order the add-on. 

![image](https://user-images.githubusercontent.com/7470044/231127341-541493cd-db1b-4365-a634-b32cbdcda270.png)

With this message the cause is unclear. But if a partner tries to order the add-on, then the system includes the required base offers. 

```
Add-on can not be ordered without the corresponding base offer.
Please order one of the below base offers first:

- Microsoft 365 Business Standard 
- Office 365 E1 
- Office 365 E3 
- Office 365 E5
- Microsoft 365 E3
- Microsoft 365 E5 
- SharePoint (Plan 1)
- SharePoint (Plan 2) 
- Microsoft 365 Business Basic 
```

Please fix this.

Thanks
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9aa1a91-e838-41c6-45cb-6a2a4dbf1a7a
* Version Independent ID: 5f5c1b99-126f-2a70-20c8-f00136927e31
* Content: [Microsoft Syntex - SharePoint Advanced Management overview - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/SharePoint/advanced-management)
* Content Source: [SharePoint/SharePointOnline/advanced-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/advanced-management.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by YakovGoldberger** [comment]
When will this be resolved? we're unable to purchase licenses.

**Comment by TobiasAT** [comment]
For @scanum, I created support case 2304101420000716 on 10. April, but your colleagues don't believe it's an issue with M365 Business Premium license. I can prove this issue in several tenants. No recent update.

**Comment by TobiasAT** [comment]
Still missing in M365 Business Premium licenses.

**Comment by tiburd** [comment]
We (the documentation team) have reached out to the product group; we don't yet have updates from them that we can add to the article.

In the meantime, you're welcome to submit your feedback to the [SharePoint Feedback Forum](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472).

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
