### ISSUE TITLE
Needs to be an "upload only" option on folders.

### ISSUE THREAD

**Issue by brianleesmith** [MicrosoftDocs/OfficeDocs-SharePoint#3785]
Companies will want to keep the Anyone link option disabled for outbound sharing, but may want to enable it for inbound receiving to eliminate other third-party options.  Without an **_upload only_** option for folder permissions, this is not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb80c7f-b87a-6910-b145-1261ce7be4fc
* Version Independent ID: 6085e0fb-1eb5-3a33-9771-11a4b4c6bee2
* Content: [Enable File Requests in SharePoint or OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/enable-file-requests)
* Content Source: [SharePoint/SharePointOnline/enable-file-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/enable-file-requests.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @brianleesmith 
How are you?
Thanks for your feedback, however, here we are limited to documentation changes and improvements.
For your inquiry, the best would be this other resource https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472
