### ISSUE TITLE
Missing link to sharepoint admin center

### ISSUE THREAD

**Issue by ronnessim** [MicrosoftDocs/OfficeDocs-SharePoint#3789]
The most critical piece of information needed to use this article is the link to the admin center. I landed on this page from a google search, and if people can't find the entry point to use this information the rest of the article might as well not even exist.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c744272-76d3-f60a-9d06-570d36ffb529
* Version Independent ID: 24208c34-c0f1-4ab0-5d92-9c3997211729
* Content: [Manage sites in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center)
* Content Source: [SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
