### ISSUE TITLE
OneDrive syncs .lnk files -- is documentation wrong?

### ISSUE THREAD

**Issue by loosus** [MicrosoftDocs/OfficeDocs-SharePoint#3792]
On this page:

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/tree/public/SharePoint/SharePointOnline)/block-file-types.md

It states the following: "The OneDrive sync app doesn't sync .tmp, .ini, and .lnk files."

This seems to be incorrect.  Based on my own testing using the latest OneDrive sync client, *.lnk files are synchronized by the OneDrive sync application.

Therefore, is the documentation wrong, or is the behavior by the latest OneDrive sync client incorrect?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
