### ISSUE TITLE
What about Intune configuration profiles?

### ISSUE THREAD

**Issue by benoithamet** [MicrosoftDocs/OfficeDocs-SharePoint#3808]
The OneDrive sync report is currently enabled and configured using Intune configuration profile.
This page only explains how to enable/configure it with either registry or group policy

Are you planning to:
* either update this page to provide configuration options using Intune
* or update the Intune settings for configuration profile

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=windows)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by benoithamet** [comment]
Thank you for adding the information for Intune but it does not specify if the new settings will be automatically applied if it is already configured; also there is no new setting matching this new way (only the 'legacy' one is present)
