### ISSUE TITLE
Link is not correct --- Replace the STS certificate.---

### ISSUE THREAD

**Issue by kannanambadi** [MicrosoftDocs/OfficeDocs-SharePoint#381]
Link given for "Replace the STS certificate." is not correct, please check. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daec777e-686e-a949-a729-6d6cb2e0c05b
* Version Independent ID: 38f948f7-cea3-2f0f-9596-09c8e07e6583
* Content: [Hardware and software requirements for SharePoint hybrid](https://docs.microsoft.com/en-us/sharepoint/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid)
* Content Source: [SharePoint/SharePointServer/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@kannanambadi Thank you for this feedback

I will this link information over to the SharePoint team for investigatoin. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@scanum you can close this.
