### ISSUE TITLE
Does "Set-SPOTenant -HideSyncButtonOnTeamSite $true" remove the sync button but allow the "add a shortcut button"?

### ISSUE THREAD

**Issue by LycheeYum** [MicrosoftDocs/OfficeDocs-SharePoint#3815]
Does this command remove the sync button but allow the "add a shortcut button" to function?

The command is Set-SPOTenant -HideSyncButtonOnTeamSite $true

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 367f3b91-1252-7bce-fd1e-21ceb1ae12f3
* Version Independent ID: 66e3f10a-0231-e7e0-0659-0be66eaf13fa
* Content: [Sync in SharePoint and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-sync#sharepoint-file-sync-and-onedrive-shortcuts)
* Content Source: [SharePoint/SharePointOnline/sharepoint-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by LycheeYum** [comment]
Thank you for the prompt reply.  Should it also appear in the list of other documented parameters here https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps?
