### ISSUE TITLE
Wrong Troubleshooting info under macOS tab

### ISSUE THREAD

**Issue by cashxx** [MicrosoftDocs/OfficeDocs-SharePoint#3817]
Under the "macOS" tab then under "Troubleshooting" section, the directions to troubleshoot are for Windows and not macOS.  I have macOS clients setup correctly and not showing under Devices in OneDrive Sync App Health devices tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=macos)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by cashxx** [comment]
@scanum Not sure what there was to respond too?   Info on the page is wrong and is troubleshooting info for Windows and not macOS.   Nothing else I can offer on my end.
