### ISSUE TITLE
Doesn't work with Teams created sharepoints sites?

### ISSUE THREAD

**Issue by a7259w** [MicrosoftDocs/OfficeDocs-SharePoint#382]
I wanted to try this tool to move large files from my computer to a Microsoft Teams I am part of.
In Teams i select "Open in Sharepoint" and then copy the URL to the migration tool.
But whatever I try I get "Sorry, you don't have access to this site. Please enter a different Sharepoint online sit." (yes, it cuts of there). . . 
I can upload files through Teams just fine so I DO have access!
Can you please fix this in the application? Or at least let the documentation reflect that it doesn't work with Microsoft Teams created Sharepoint-sites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by joegasper** [comment]
If you are using the exact URL you are sent to after you "Open in SharePoint", that might not work. Try removing everything after and including "/Shared%20Documents/..." in the URL - just provide the URL to the SharePoint site - the Migration Tool will then list the available document libraries. Be sure to upload into one of the Teams' channels subfolder (i.e., "General"). Also, make sure you don't migrate or create new permissions during the migration - you don't want to break the existing permissions on the document library for the Team.

**Comment by gurramsubrahmanyam** [comment]
Is that tool supports migration from SP 2010 to SharePoint Online?

**Comment by DeanGross** [comment]
@gurramsubrahmanyam no it does not.

**Comment by planetparker** [comment]
Anyone else seeing issues where not all the lists and libraries get migrated over from SharePoint 2013 to SP Online?  Also, when trying to target specific lists and libraries in SP 2013, the drop down list within SPMT selection doesn't reveal all the lists and libraries.  It shouldn't be a permissions issue, since I am site collection admin.  It seems like this issue was introduced with the latest update--I don't remember seeing this same problem in prior version.

**Comment by AndreaBarr** [comment]
@a7259w @planetparker Thank you for the feedback

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
