### ISSUE TITLE
Published applications support

### ISSUE THREAD

**Issue by dp001** [MicrosoftDocs/OfficeDocs-SharePoint#3820]
Is it valid for both published applications and desktop or only for the latter one?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67210c40-a20f-cf02-6fc0-834fa6795a09
* Version Independent ID: e3ff92b2-6e58-dd9c-f0a6-0f88cd28b5fd
* Content: [Set up OneDrive in Citrix Virtual Apps - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/onedrive-in-citrix-virtual-apps-deployment-guide)
* Content Source: [SharePoint/SharePointOnline/onedrive-in-citrix-virtual-apps-deployment-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/onedrive-in-citrix-virtual-apps-deployment-guide.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
