### ISSUE TITLE
Powershell script changes 

### ISSUE THREAD

**Issue by sprider** [MicrosoftDocs/OfficeDocs-SharePoint#383]
I found two issues with the PowerShell script used here to create different VMs. 

1) -StorageAccountType "StandardLRS" should be changed to -StorageAccountType Standard_LRS

2) In phase 2, Get-AzureRmSubscription -Name $subscrName | Select-AzureRmSubscription should be changed to Get-AzureRmSubscription -SubscriptionName $subscrName | Select-AzureRmSubscription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@sprider Did the updates Trevor did resolve this issue?

**Comment by sprider** [comment]
Yes, It does. Thank you team
