### ISSUE TITLE
Workflow migration feature in version 4.1 ?

### ISSUE THREAD

**Issue by KuotingChiu** [MicrosoftDocs/OfficeDocs-SharePoint#3830]
Hi, I've downloaded the beta version of 4.1 and did not see the workflow migration feature in it while this page states it should be there.   Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c911d1d-3570-6e0a-cfa7-77b7516a1f55
* Version Independent ID: 261252f1-7191-5be9-a735-cdb307b72a7c
* Content: [SharePoint Migration Tool (SPMT) Release notes - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool#spmt-41)
* Content Source: [migration/new-and-improved-features-in-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/new-and-improved-features-in-the-sharepoint-migration-tool.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @KuotingChiu 
How are you?
Did you follow this other article on the prerequisites to migrate workflows?

https://learn.microsoft.com/en-us/sharepointmigration/spmt-workflow-overview

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
