### ISSUE TITLE
Use sync instead of Open with Explorer or View in File Explorer

### ISSUE THREAD

**Issue by tico1177** [MicrosoftDocs/OfficeDocs-SharePoint#3834]
This is a security issue at this point in terms of systems being crypto-ed. When you have files sync'ed to the computer, then that computer is infected, those same files now sync back to SharePoint Online.  Thus users must get with Microsoft to have restore of the library or they must restore files to previous version themselves.

It is not recommended to do Network Mapped drives to SPO folders as the same concept applies.  Having the ability to open a SharePoint site with Windows File Explorer is important not only for users, but admins as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40d9effc-1329-b03d-b6d6-f0d7ff88a6de
* Version Independent ID: 4f6bfbe6-b14f-baa7-e80d-20f7ca8a3427
* Content: [Prepare your SharePoint environment for the retirement of Internet Explorer 11 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/prepare-ie11)
* Content Source: [SharePoint/SharePointOnline/Prepare-IE11.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/Prepare-IE11.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @tico1177 
Here we are limited to documentation changes and fixes, for feedback, please use this resource instead https://feedbackportal.microsoft.com/feedback/
