### ISSUE TITLE
BlockDownloadPolicy to Exclude Specific Libraries?

### ISSUE THREAD

**Issue by dilkry** [MicrosoftDocs/OfficeDocs-SharePoint#3835]
Will there be an option to apply BlockDownloadPolicy to specific libraries or exclude certain libraries from this rule? I have a site where we want most of the files to not be able to download except for a Forms library where users need to be able to download the form templates.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
