### ISSUE TITLE
Troubles with configuring OIDC based on the guide

### ISSUE THREAD

**Issue by KamilPacanek** [MicrosoftDocs/OfficeDocs-SharePoint#3838]
### Refers to
[Set up OIDC authentication in SharePoint Server with Microsoft Azure Active Directory (Azure AD)
](https://learn.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/set-up-oidc-auth-in-sharepoint-server-with-msaad#step-7-set-up-people-picker)

### Description
I have followed the guide successfully so far - I can use Azure accounts to log in the on-prem SharePoint (SE). I'm stuck on configuring User Profiles synchronization. I don't know what to fill in the "Add new synchronization connection" form. The only way I was able to add a connection was to put the details of my AD, ending with the connection that has my local domain as a source.
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/20944885/e8ffe424-35c3-4e74-ac32-7e1c999ae9e1)

From what I understand, I want to achieve synchronization of Azure Accounts to the on-prem UPSA - so they can be searchable in people pickers - but I found no way to specify Azure details on that form. I'm getting a not so helpful error message.
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/20944885/77654ab3-e8e5-4234-8b12-5a8268743a4c)

When I click "Populate containers" I am having error message
`Unable to find domain controller for the specified domain. Please explicitly specify the domain controller.`

Even when I go with that connection what I have - no Azure profiles are being imported - which does not surprise me as it clearly tries to pull from my AD instead of Azure AD.

What should I do?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by KamilPacanek** [comment]
I've sent a ticket to our support contact, I hope it will be resolved, and I could return with some feedback.
