### ISSUE TITLE
App Catalog Settings

### ISSUE THREAD

**Issue by sprider** [MicrosoftDocs/OfficeDocs-SharePoint#384]
Could you please add the instructions to setup app catalog in SharePoint 2016 as it required to develop and test Host Provider Hosted/SharePoint Hosted/SharePoint Frmaework apps in this environment? 

Example : https://content.akumina.com/learningcenter/Content/IG/AMOPInsall/CreateSPAPPCatalog.htm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@sprider Did Trevors update resolve this issue?

**Comment by tseward** [comment]
@scanum you can close this.
