### ISSUE TITLE
Don't see the template ID of template name : Playlist

### ISSUE THREAD

**Issue by ZICZAC1989** [MicrosoftDocs/OfficeDocs-SharePoint#3840]
Dear Expert,
I need turn-off all template lists, but i can't see the ID template Playlist. And i don't know why i can't disable template Expense Tracker , although command ran it's okey.
Set-SPOTenant -DisableModernListTemplateIds '96D6DBE5-D7C3-430A-867A-0B72EB4065AB'

So please give me your solution to fix it. Thanks you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf2d4570-0024-e5c0-035a-8827759aeabc
* Version Independent ID: 42e2105b-5ede-3d22-139d-96cc61cf4ec5
* Content: [Control Microsoft Lists - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/control-lists#disable-built-in-list-templates)
* Content Source: [SharePoint/SharePointOnline/control-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/control-lists.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by ZICZAC1989** [comment]
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/81660939/64a1ae5c-8295-4f43-be59-8688b813a65f)

**Comment by get-itips** [comment]
Hello @ZICZAC1989 

Looks like the correct id for Expense Tracker is '96d6dbe5-d7c3-030a-867a-0b72eb0ff1ce'

and for playlist '3a867b4a-7429-0e1a-b02e-bf4b240ff1ce'

I'll update the article

**Comment by ZICZAC1989** [comment]
Dear,

Thank you so much!



Kind Regards,

***@***.***

**Comment by ZICZAC1989** [comment]
Dear,
I hoping you are doing well,

You know when I try used 2 templated Id that you provide me, it’s okey with platform Web.
But I trying to use on Mobile, all template Id from MS still showing up. I don’t know why.
So please help me check a fix it. 
Thank you so much!
