### ISSUE TITLE
Cloud Policy, Secondary/Primary unclear

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/OfficeDocs-SharePoint#3841]
It is not explained and afaik no standard term 

Cloud Policy, Secondary
Cloud Policy, Primary

Would be helpful to add some information and/or reference. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41c35b5-e159-ed6d-a9ff-bea0ef7f0736
* Version Independent ID: 2eca8e70-2e83-b100-890b-03b4377186e9
* Content: [Manage Loop experiences (Loop app and Loop components) in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-loop-components)
* Content Source: [SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@dancontoso can you help?

**Comment by dancontoso** [comment]
Yes, intended to reinforce what’s in the Notes column of the summary table: the Secondary Outlook setting first checks the Primary Microsoft setting. In other words, if you turn off the Primary Microsoft-wide setting, then Loop components are always off, regardless of the setting for the secondary Outlook setting. You have to enable the Primary setting for the Secondary setting to be considered.

**Comment by tiburd** [comment]
@MikePlumleyMSFT 
Hi Mike,
It looks like Dan replied - do you want to update the article in the private repo?
Let us know if you want our team to update it.
Thank you!

**Comment by MikePlumleyMSFT** [comment]
@dancontoso do you want to update the article?

**Comment by MikePlumleyMSFT** [comment]
Closing old issues. Please open a new issue if there are still questions.
