### ISSUE TITLE
Isn't B2B integration on by default now?

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-SharePoint#3856]
Current article, published 13 Mar 2023 states:
> SharePoint and OneDrive integration with the Azure AD B2B one-time passcode feature is currently not enabled by default.

Per M365 admin center message ID MC526130, new tenants have this on by default as of 31 Mar 2023. Can we get a clarifying statement added to this page, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
