### ISSUE TITLE
Settings management in Cloud Policy for Microsoft Loop experience issue

### ISSUE THREAD

**Issue by cloudyqintian** [MicrosoftDocs/OfficeDocs-SharePoint#3857]
The steps to enable loop is wrong/inconsistent. I spent quite some time troubleshooting what went wrong when we are enabling the Loop for my client. The documentation said to assign loop to **security group**, it worked for my tenant when I tested it but not for my client's tenant. After some troubleshooting, Microsoft engineer advised to reassign the policy to **M365 group**. Then my client was able to use Loop.
https://techcommunity.microsoft.com/t5/microsoft-365-blog/learn-how-to-enable-the-microsoft-loop-app-now-in-public-preview/ba-p/3769013

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41c35b5-e159-ed6d-a9ff-bea0ef7f0736
* Version Independent ID: 2eca8e70-2e83-b100-890b-03b4377186e9
* Content: [Manage Loop experiences (Loop workspaces and Loop components) in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-loop-components#settings-management-in-cloud-policy)
* Content Source: [SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointO
![Screenshot 2023-05-31 170507](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/76044094/d1d96420-a6a9-4b3b-baec-44bd49390aba)
![Screenshot 2023-05-31 170553](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/76044094/d1540271-ff20-417a-95ca-055867b9a911)
nline/manage-loop-components.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
