### ISSUE TITLE
No mention of API Access screen

### ISSUE THREAD

**Issue by EllyaGold** [MicrosoftDocs/OfficeDocs-SharePoint#3858]
Hi, 

API Access approvals used to be part of the SharePoint admin role, but now when I try to approve API Access for updated SharePoint apps, I get an error saying I now need to be Global Admin or Application Admin. Given the API Access item is on the SharePoint Admin menu, it might be worth updating this doc to reflect that.

Many thanks, Ellya

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7461c2ef-3439-2c86-4dde-8992b62bf9a7
* Version Independent ID: faa4e3aa-8ec4-f1f1-d4bd-4058999545f3
* Content: [About the SharePoint admin role in Microsoft 365 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-admin-role)
* Content Source: [SharePoint/SharePointOnline/sharepoint-admin-role.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-admin-role.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
