### ISSUE TITLE
External Sharing settings broken on old Admin Center

### ISSUE THREAD

**Issue by fletchonides** [MicrosoftDocs/OfficeDocs-SharePoint#386]
I created 2 site collections with the current SharePoint Admin Center, and enabled external sharing for both (new and existing external users). When I tried to send sharing invite emails for the site; I get an error that external sharing is not allowed in my organisation. In the new Admin Center preview, sharing settings for the site collections show as not shared.  if I enable them there, then sharing is turned on. 
Please make them consistent, so they display and behave the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@fletchonides Thank you for this feedback

I'll get this sharing information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kaarins** [comment]
@fletchonides , thank you for reporting this issue! We're working to make sharing settings use the same controls and language across the admin centers, and to fix other issues with the experience. I know this area is a pain point, and helping to improve the experience is one of my top priorities. A new Sharing page in the new SharePoint admin center preview is coming soon.
