### ISSUE TITLE
Which date were those new properties added to the search index schema?

### ISSUE THREAD

**Issue by kasperbolarsen** [MicrosoftDocs/OfficeDocs-SharePoint#3862]
I assume that the new properties ModifierAADIDs and ModifierNames gets populated when a file or a page changes version? Therefor it would be beneficial to know from which date this change took place.
I assume that you haven't populated those fields retroactively?

Example 
fileversion, date, user
0.1, 01-01-2021 , John
1.0, 02-02-2021, Ann
2.0, 05-05-2023, Mikael
3.0, 06-06-2023, Agnes

Which of the uses should I expect to see in the ModifierNames property? 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adb6ad45-00c5-d3bc-8db1-d707f2fa7f4e
* Version Independent ID: b8cabb67-95e9-fe03-f8ab-cc760a0a5014
* Content: [Overview of crawled and managed properties in SharePoint Online - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/crawled-and-managed-properties-overview)
* Content Source: [SharePoint/SharePointOnline/crawled-and-managed-properties-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/crawled-and-managed-properties-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @kasperbolarsen 
I'm working on this

**Comment by kasperbolarsen** [comment]
@get-itips thanks for the update 👌

**Comment by wobba** [comment]
Hi @kasperbolarsen. The fields were introduced a while back and we have run backfills. There's a note in the documentation saying "Property is not guaranteed to contain data", which means you can do some checks yourself per tenant to see what the actual coverage is.

That said, coverage should be quite high, and I have items in my dev tenant not touched since 2012 which has the properties set. Data may differ on files vs pages as well. Hope this helps.

**Comment by kasperbolarsen** [comment]
I had a feeling that this issue might end up on you table :-)

I guess there are no way to trigger this backfill process on an item/library? I have some pretty critical libraries where the backfill hasn't been activated.

**Comment by wobba** [comment]
@kasperbolarsen as it is based on graph signals, a user edit on an item should populate the fields. It's applicable to Pages and Files - meaning items in libraries. Any solution build on these properties should also rely on AuthorOWSUser and EditorOWSUser for completeness, who would be the same values as the first and last modifier.

**Comment by get-itips** [comment]
Thanks @wobba !
