### ISSUE TITLE
No Data Governance visible

### ISSUE THREAD

**Issue by JamesMClinton** [MicrosoftDocs/OfficeDocs-SharePoint#3863]
Any info on how to make Data governance appear in the reports section, I'm a global admin and this article just "assumes" it's there already

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd05a015-115f-0e1d-e607-64a0c08a77a1
* Version Independent ID: 6ac538e0-2010-34db-7b06-d31272bfae28
* Content: [Data access governance reports for SharePoint sites - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/data-access-governance-reports)
* Content Source: [SharePoint/SharePointOnline/data-access-governance-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/data-access-governance-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MachelleTranMSFT
* Microsoft Alias: **mactra**

**Comment by get-itips** [comment]
Hello @JamesMClinton 
Do you refer to the menu option?
I tested and it is there for me in multiple tenants.

**Comment by JamesMClinton** [comment]
I'm happy for you, but how do I get it?
________________________________

**Comment by get-itips** [comment]
I'm reviewing the requirements, please let me know if you comply with

>This feature requires a Microsoft Syntex - SharePoint Advanced Management license.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
