### ISSUE TITLE
E4ではなくE5ではないでしょうか

### ISSUE THREAD

**Issue by sums33** [MicrosoftDocs/OfficeDocs-SharePoint#387]
E4は既に廃止されているため、E5ではないでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b21ad738-c2a1-ef1f-d745-eebe907311ac
* Version Independent ID: e931c7e1-fdb4-414b-986d-d7755fc797c4
* Content: [Office 365 管理者向け Office Delve](https://docs.microsoft.com/ja-jp/sharepoint/delve-for-office-365-admins?redirectSourcePath=%252fja-jp%252farticle%252foffice-delve-office-365-%2525E7%2525AE%2525A1%2525E7%252590%252586%2525E8%252580%252585%2525E5%252590%252591%2525E3%252581%252591-54f87a42-15a4-44b4-9df0-d36287d9531b#bkmk_delveonoff)
* Content Source: [SharePoint/SharePointOnline/delve-for-office-365-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delve-for-office-365-admins.md)
* Service: **sharepoint-online**
* GitHub Login: @gretel
* Microsoft Alias: **gretel**

**Comment by AndreaBarr** [comment]
@sums33 Thank you for this feedback. 

I am not sure on the answer for this. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
