### ISSUE TITLE
Conflicting eDiscovery description?

### ISSUE THREAD

**Issue by infamousdanno** [MicrosoftDocs/OfficeDocs-SharePoint#3875]
[Enter feedback here]

The "eDiscovery for Loop components" sections says "Loop components created in Teams or Outlook are discoverable and have eDiscovery workflow support using the Microsoft Purview tool".  The note in the purple section below that says "The Loop app and content created in the Loop app does not yet support eDiscovery workflows."

I feel like this is either conflicting information or needs more clarification.  If Loop app is comprised of Loop components in a page or workspace, what is or isn't in eDiscovery?  Is it that the components are but the encompassing pages and workspaces are not?

Somewhat relatedly, is there any clarification available about the location where all of the Loop content (components and app) are stored?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c41c35b5-e159-ed6d-a9ff-bea0ef7f0736
* Version Independent ID: 2eca8e70-2e83-b100-890b-03b4377186e9
* Content: [Manage Loop experiences (Loop workspaces and Loop components) in SharePoint - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-loop-components)
* Content Source: [SharePoint/SharePointOnline/manage-loop-components.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-loop-components.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@dancontoso can you take a look?

**Comment by get-itips** [comment]
Thanks @MikePlumleyMSFT

**Comment by get-itips** [comment]
Hello @infamousdanno 

Essentially, if you use Teams or Outlook to create the Loop components -> eDiscovery workflow is supported
If you use Loop directly -> not **yet** supported

More information about storage

https://learn.microsoft.com/en-us/microsoft-365/loop/loop-workspaces-storage-permission?view=o365-worldwide

https://learn.microsoft.com/en-us/microsoft-365/loop/loop-components-teams?view=o365-worldwide

Thank you,
