### ISSUE TITLE
use-silent-account-configuration

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/OfficeDocs-SharePoint#3879]
Has the GPO functionality that controls the "use-silent-account-configuration" option been changed in a newer version of the ADMX for OneDrive?  or the Client itself?  I recently updated our Central Policy Store with the latest and now Silent Auto-Login for OneDrive doesn't work if you specify the username in the full UPN format.  i.e. username works, OneDrive signs in Automatically, username@domain.com doesn't autologin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @mattsmacblog 
I have no record of any change at least on release notes.
The best in this case would be to open a support request from your tenant, where they will be able to assist you.
Thank you
