### ISSUE TITLE
Error trying to restore deleted onedrive

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SharePoint#3880]
Hello, a users license was removed 30 days ago, and when the OneDrive became unavailable an admin relicensed the user. This did not restore the previously deleted OneDrive but instead created a new OneDrive site.

The instructions for recovering a deleted OneDrive doesn't address this scenario.

I found this exact question posted over [here](https://learn.microsoft.com/en-us/answers/questions/57520/restore-personal-site-onedrive-via-powershell), and the accepted answer is to run the Remove-SPODeletedSite command, which appears to delete the most recently deleted site (leaving the older site with content available to be restored).

The Remove-SPODeletedSite command doesn't describe how it handles the situation of two deleted sites with the same Url.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42531982-8c57-550c-e108-f72992368510
* Version Independent ID: 5c90f1d2-e171-a242-737d-9f3113f12eb2
* Content: [Restore a deleted OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restore-deleted-onedrive)
* Content Source: [SharePoint/SharePointOnline/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by jonwbstr** [comment]
Correction, the community solution is:
1. Use Remove-SPOSite -identity $url # to delete the new (empty OneDrive site) creating a second deleted site without content
2. Use Remove-SPODeletedSite -Identity $url # to permanently delete the second deleted site without content
3. Use Restore-SPODeletedSite -identity $url # restore the most recently deleted site (the first deleted site with content)

**Comment by jonwbstr** [comment]
I spoke with support and learned this article does not address how to access the onedrive of a user that is visible in the admin portal as an active user with no license assigned.

When the user appears in the active user list, you can get access to the users files using the following steps:
NOTE: This link also adds permissions to the onedrive site. (it may be useful to describe how to give other users access to the files also)
1. From the M365 admin portal expand Active Users, then select the desired user
2. Click the OneDrive Tab, then click "Create link to files" in the Get access to files section of the tab:
    > **Get access to files**
    > Create a link to view and edit ‎[the user's] ‎OneDrive‎ files.
3. Navigate to the link generated

A key difference when the user is still listed in the user portal appears to be that the onedrive site for the unlicensed user is listed as both an active SharePoint site, and a deleted sharepoint site? I'm not 100% confident my understanding is accurate as another admin was also actively working on this issue and may have been making changes I am unaware of at the same time.

**Comment by get-itips** [comment]
Hello @jonwbstr 
I understand. Thank you
Due to some uncertainty on what lead to that scenario, and as you said multiple admins were on this so we are not sure about the exact actions taken, it is difficult for me to try to reproduce to see if we need to adjust or correct this article.

**Comment by jonwbstr** [comment]
I spoke to the admins today, they didn't take any steps to restore the
OneDrive site.

There are 4 scenarios, this article documents the first one
1) recover OneDrive from a deleted user
- This article
2) recover OneDrive from user unlicensed for 30 days
- use m365 admin portal?
3) recover OneDrive from user unlicensed for 30 days and then relicensed.
- use m365 admin portal?
4) recover OneDrive from user unlicensed for 30 days + 93 days
- 14 day recovery window via backend team?

**Comment by get-itips** [comment]
@jonwbstr Just to let  you know that I was able to pass this feedback to the author and Learn team and it will be taken in account, at the moment for your specific scenario it is advisable to open a support request as you already did.
Thank you
