### ISSUE TITLE
Was hoping for a diagram of Sharing SharePoint documents

### ISSUE THREAD

**Issue by MrVP** [MicrosoftDocs/OfficeDocs-SharePoint#3884]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [Overview of external sharing in SharePoint and OneDrive in Microsoft 365 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/external-sharing-overview)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @MrVP 
Can you please detail a little bit more your feedback so I can pass this on?
Thank you

**Comment by MrVP** [comment]
> Hello @MrVP Can you please detail a little bit more your feedback so I can pass this on? Thank you

Hello,

I was hoping  to see a work flow diagram of the steps taken to do this.  Pictures go a long way.  or Screenshots of the step by step process for my end users.

Oddly when I send documentation and they look for a menu item...they can never find it...
Does that help?

**Comment by get-itips** [comment]
Hello @MrVP Thanks for returning and sharing more information.

This article is an overview, for step-by-step artciles, you have the other ones located under the same section, for example, _Manage Sharing Settings_, which has a video and screenshots, the same for the others. Have you seen those?

thanks

**Comment by MrVP** [comment]
I have not!!! My apologies!

Get Outlook for iOS<https://aka.ms/o0ukef>


Security Classification: Protected A

________________________________
