### ISSUE TITLE
is it just me? 

### ISSUE THREAD

**Issue by dullawolf** [MicrosoftDocs/OfficeDocs-SharePoint#39]
trying to use this migration tool. I think it is going to be a great tool but how long is it supposed to take to migrate the data? I left the tool running for 25 minutes to move 78mb of data and it was still processing. it saw the files but nothing was happening.

**Comment by dullawolf** [comment]
reporting back. job failed after over a half hour of running. 
     error: Failed to Submit the Job to Server:Unknown failed reason when submitting a job.
     errorcode: 0x01610002

**Comment by JoanneHendrickson** [comment]
@Techwriter40  - already investigating issue.

**Comment by JoanneHendrickson** [comment]
Hi Dullawolf:

Sorry you are having issues -- we want to help!  What version are you using?  Is it the beta version?  Can you send me the log files? It should be in your \AppData\Roaming\Microsoft\MigrationTool\ folder.

Thanks

Joanne

**Comment by dullawolf** [comment]
Joanne, 
I attached the entire folder. After i received your email, i had an epiphany. Is it because i am on the windows insider version of windows? i am on windows 10 version 1803 build 17134.1. 
i will try running this on my surface pro 3 with deferred channel windows 10 and report back. 
thanks, 
Michael Wolf

    On Thursday, April 26, 2018, 6:07:34 PM EDT, JoanneHendrickson <notifications@github.com> wrote:  
 
 
Hi Dullawolf:

Sorry you are having issues -- we want to help! What version are you using? Is it the beta version? Can you send me the log files? It should be in your \AppData\Roaming\Microsoft\MigrationTool\ folder.

Thanks

Joanne

**Comment by JoanneHendrickson** [comment]
Following up -- didn't receive your files attached --  If you are still having issues email them directly to me

**Comment by dullawolf** [comment]
The folder is attached. it is called miagrationtool.zip. it has all the log files. 
thanks, 
michael wolf
    On Tuesday, May 8, 2018, 10:36:05 AM EDT, JoanneHendrickson <notifications@github.com> wrote:  
 
 
Following up -- didn't receive your files attached -- If you are still having issues email them directly to me

**Comment by JoanneHendrickson** [comment]
Hi Michael:  Can you email them to me directly at jhendr@microsoft.com?  They don't appear to be coming through.  Thanks!

Joanne

**Comment by kenwith** [comment]
@dullawolf - sorry for the delay on this and that it has gone stale in the documentation issues. I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
