### ISSUE TITLE
Retrieving usage stats like ViewLastMonths3 via search api

### ISSUE THREAD

**Issue by mikezimm** [MicrosoftDocs/OfficeDocs-SharePoint#3901]
I have come across older posts saying you can retrieve usage statistics like these by updating the search schema on a tenant, but they also indicated it was relating to classic.

ViewLastMonths1
ViewLastMonths2
ViewLastMonths3

I am wondering if there is any documented way to get longer View statistics in modern pages?
I know that the modern Site Usage page goes back to 90 days so the data has to be available.

Thanks for any help you can provide.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
