### ISSUE TITLE
"Use form at this url is not working"

### ISSUE THREAD

**Issue by jain9177** [MicrosoftDocs/OfficeDocs-SharePoint#391]
Hi Team,

Even though i add my custom infopath form url in the "user form at this url " the new site button is going to default form. Do i need to change some setting my tenant to make this to work?

Thanks,
Vijay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29978b1-a400-bacb-1330-55ed3d652053
* Version Independent ID: eae9fd16-57fc-1a80-3ce9-9b34b68eb1e0
* Content: [Manage site creation in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation)
* Content Source: [SharePoint/SharePointOnline/manage-site-creation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-creation.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jain9177 Thank you for this inquiry. 

I am not sure what needs to be done for this site button. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kaarins** [comment]
@jain9177 , I raised this question with the feature team, and they are not aware of any issues with the custom form URL. Will you please file a support ticket so that we can collect more info to track down the problem? Thank you!

**Comment by rishabhymathur** [comment]
I am seeing the same behavior as described above, this does not seem to be working. Any specific setting at tenant level to make it work?
