### ISSUE TITLE
Get-SPOSite does not return correct information even days after a Start-SPOTenantRename

### ISSUE THREAD

**Issue by dvillarejo** [MicrosoftDocs/OfficeDocs-SharePoint#3911]
Get-SPOSite does not return correct information, many sites appear as ReadOnly and with the old url even a day later

Document Details
⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
Service: sharepoint-online
GitHub Login: @MikePlumleyMSFT
Microsoft Alias: mikeplum

**Comment by dvillarejo** [comment]
I just verified that using Get-SPOSite to locate one of those sites that reported me with the old url, two sites appear, one with the old url and with lockstate as readonly and another with the new url and with lockstate unlock.

I think I understand that the first one has been generated to facilitate the redirection from the old url to the new one and it is hidden in the SharePoint administration console. If this is the case, they should warn about it in the documentation since it can create confusion and cause some error of administrators used to managing the environment via powershell.

Example:

Get-SPOSite -Filter {url -like "Community1011"} | fl 


LastContentModifiedDate                     : 29/06/2023 16:04:38
Status                                      : Active
ResourceUsageCurrent                        : 0
ResourceUsageAverage                        : 0
StorageUsageCurrent                         : 0
LockIssue                                   :
WebsCount                                   : 0
CompatibilityLevel                          : 15
DisableSharingForNonOwnersStatus            :
HubSiteId                                   : 00000000-0000-0000-0000-000000000000
IsHubSite                                   : False
RelatedGroupId                              : 00000000-0000-0000-0000-000000000000
GroupId                                     : 00000000-0000-0000-0000-000000000000
Url                                         : https://m365x94075399.sharepoint.com/sites/Community1011
LocaleId                                    : 1033
LockState                                   : ReadOnly
Owner                                       :
StorageQuota                                : 26214400
StorageQuotaWarningLevel                    : 25574400
ResourceQuota                               : 300
ResourceQuotaWarningLevel                   : 100
Template                                    : RedirectSite#0
Title                                       : RedirectSite
AllowSelfServiceUpgrade                     : True
DenyAddAndCustomizePages                    : Disabled
PWAEnabled                                  : Disabled
SharingCapability                           : Disabled
SiteDefinedSharingCapability                : Disabled
SandboxedCodeActivationCapability           : Unknown
DisableCompanyWideSharingLinks              : Unknown
DisableAppViews                             : Unknown
DisableFlows                                : Unknown
AuthenticationContextName                   :
StorageQuotaType                            :
RestrictedToGeo                             : Unknown
ShowPeoplePickerSuggestionsForGuestUsers    : False
SharingDomainRestrictionMode                : None
SharingAllowedDomainList                    :
SharingBlockedDomainList                    :
ConditionalAccessPolicy                     : AllowFullAccess
AllowDownloadingNonWebViewableFiles         : False
LimitedAccessFileType                       : OfficeOnlineFilesOnly
AllowEditing                                : False
SensitivityLabel                            :
CommentsOnSitePagesDisabled                 : False
SocialBarOnSitePagesDisabled                : False
DefaultSharingLinkType                      : None
DefaultLinkPermission                       : None
DefaultLinkToExistingAccess                 : False
AnonymousLinkExpirationInDays               : 0
OverrideTenantAnonymousLinkExpirationPolicy : False
ExternalUserExpirationInDays                : 0
OverrideTenantExternalUserExpirationPolicy  : False
SharingLockDownEnabled                      : False
SharingLockDownCanBeCleared                 : False
InformationSegment                          : {}
InformationBarriersMode                     :
BlockDownloadLinksFileType                  : 0
OverrideBlockUserInfoVisibility             : OrganizationDefault
IsTeamsConnected                            : False
IsTeamsChannelConnected                     : False
TeamsChannelType                            : None
MediaTranscription                          : Enabled
ExcludedBlockDownloadGroupIds               : {}
ExcludeBlockDownloadPolicySiteOwners        : False
ReadOnlyForBlockDownloadPolicy              : False
ExcludeBlockDownloadSharePointGroups        :
BlockDownloadPolicy                         : False
LoopSharingCapability                       : Disabled
LoopOverrideSharingCapability               : False
LoopDefaultSharingLinkScope                 : Anyone
LoopDefaultSharingLinkRole                  : None
RequestFilesLinkEnabled                     : False
RequestFilesLinkExpirationInDays            : 0
OverrideSharingCapability                   : False
DefaultShareLinkScope                       : Anyone
DefaultShareLinkRole                        : None
BlockGuestsAsSiteAdmin                      : Unspecified
ReadOnlyForUnmanagedDevices                 : False
RestrictedAccessControl                     : False
AuthenticationContextLimitedAccess          : False
RestrictedAccessControlGroups               :
ListsShowHeaderAndNavigation                : False

LastContentModifiedDate                     : 30/06/2023 5:55:22
Status                                      : Active
ResourceUsageCurrent                        : 0
ResourceUsageAverage                        : 0
StorageUsageCurrent                         : 2
LockIssue                                   :
WebsCount                                   : 0
CompatibilityLevel                          : 15
DisableSharingForNonOwnersStatus            :
HubSiteId                                   : 00000000-0000-0000-0000-000000000000
IsHubSite                                   : False
RelatedGroupId                              : 00000000-0000-0000-0000-000000000000
GroupId                                     : 00000000-0000-0000-0000-000000000000
Url                                         : https://astatest02.sharepoint.com/sites/Community1011
LocaleId                                    : 1033
LockState                                   : Unlock
Owner                                       : admin@m365x94075399.onmicrosoft.com
StorageQuota                                : 26214400
StorageQuotaWarningLevel                    : 25574400
ResourceQuota                               : 25
ResourceQuotaWarningLevel                   : 0
Template                                    : COMMUNITY#0
Title                                       : Community Site 1011
AllowSelfServiceUpgrade                     : True
DenyAddAndCustomizePages                    : Disabled
PWAEnabled                                  : Disabled
SharingCapability                           : Disabled
SiteDefinedSharingCapability                : Disabled
SandboxedCodeActivationCapability           : Unknown
DisableCompanyWideSharingLinks              : Unknown
DisableAppViews                             : Unknown
DisableFlows                                : Unknown
AuthenticationContextName                   :
StorageQuotaType                            :
RestrictedToGeo                             : Unknown
ShowPeoplePickerSuggestionsForGuestUsers    : False
SharingDomainRestrictionMode                : None
SharingAllowedDomainList                    :
SharingBlockedDomainList                    :
ConditionalAccessPolicy                     : AllowFullAccess
AllowDownloadingNonWebViewableFiles         : False
LimitedAccessFileType                       : OfficeOnlineFilesOnly
AllowEditing                                : False
SensitivityLabel                            :
CommentsOnSitePagesDisabled                 : False
SocialBarOnSitePagesDisabled                : False
DefaultSharingLinkType                      : None
DefaultLinkPermission                       : None
DefaultLinkToExistingAccess                 : False
AnonymousLinkExpirationInDays               : 0
OverrideTenantAnonymousLinkExpirationPolicy : False
ExternalUserExpirationInDays                : 0
OverrideTenantExternalUserExpirationPolicy  : False
SharingLockDownEnabled                      : False
SharingLockDownCanBeCleared                 : False
InformationSegment                          : {}
InformationBarriersMode                     :
BlockDownloadLinksFileType                  : 0
OverrideBlockUserInfoVisibility             : OrganizationDefault
IsTeamsConnected                            : False
IsTeamsChannelConnected                     : False
TeamsChannelType                            : None
MediaTranscription                          : Enabled
ExcludedBlockDownloadGroupIds               : {}
ExcludeBlockDownloadPolicySiteOwners        : False
ReadOnlyForBlockDownloadPolicy              : False
ExcludeBlockDownloadSharePointGroups        :
BlockDownloadPolicy                         : False
LoopSharingCapability                       : Disabled
LoopOverrideSharingCapability               : False
LoopDefaultSharingLinkScope                 : Anyone
LoopDefaultSharingLinkRole                  : None
RequestFilesLinkEnabled                     : False
RequestFilesLinkExpirationInDays            : 0
OverrideSharingCapability                   : False
DefaultShareLinkScope                       : Anyone
DefaultShareLinkRole                        : None
BlockGuestsAsSiteAdmin                      : Unspecified
ReadOnlyForUnmanagedDevices                 : False
RestrictedAccessControl                     : False
AuthenticationContextLimitedAccess          : False
RestrictedAccessControlGroups               :
ListsShowHeaderAndNavigation                : False

**Comment by get-itips** [comment]
Hello @dvillarejo David,

The redirect behavior is documented here [https://learn.microsoft.com/en-us/sharepoint/change-site-address](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)  on the home for tenant renames

> When you rename your SharePoint domain, we create a redirect at the previous address which will expire 1 year after the rename.

Do you still feel a note about this is needed in the Get-SPOSite article?

Thank you,

**Comment by dvillarejo** [comment]
I think it would be recommended because, although it is true that the creation of redirections is warned but not how they are done, there are many possible methods to create redirections (network devices, application gateways.....)
And it would avoid confusion like the one I had at the beginning when I thought that sites had not been renamed or that the powershell commands did not receive correct information.
I take this opportunity to ask you if these redirection sites can be managed in any way by a tenant administrator, for example if they can be deleted when they are not necessary, if they can be regenerated or extended when the one-year period is over or if in general you can interact with them in some way.

**Comment by get-itips** [comment]
@dvillarejo David, I'll propose to add a comment to this article, if it gets approval from reviewers, it will be then in the published version of the article.

> I take this opportunity to ask you if these redirection sites can be managed in any way by a tenant administrator

https://learn.microsoft.com/en-us/sharepoint/manage-site-redirects
