### ISSUE TITLE
Example to show customers how to add allowed/blocked domain list for OneDrive set-spotenant command

### ISSUE THREAD

**Issue by debaxtermsft** [MicrosoftDocs/OfficeDocs-SharePoint#3914]
Please add to this documentation HOW to set the OneDrive allowed/blocked domains list, not just a link to the set-spotenant doc which does not have an example for doing this.

Example: AllowList
1 domain
Set-SPOTenant -SharingDomainRestrictionMode "AllowList" -SharingBlockedDomainList "domain.com"
2 domains
Set-SPOTenant -SharingDomainRestrictionMode "AllowList" -SharingBlockedDomainList "domain1.com domain2.com"

Example: BlockList
1 domain
Set-SPOTenant -SharingDomainRestrictionMode "BlockList" -SharingBlockedDomainList "domain.com"
2 domains
Set-SPOTenant -SharingDomainRestrictionMode "BlockList" -SharingBlockedDomainList "domain1.com domain2.com"

AllowedDomains and BlockedDomains cannot be used together :
AllowedDomains = whitelisting domains that can be shared with listed domains
BlockedDomains = blacklisting domains that cannot be shared with listed domains
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
