### ISSUE TITLE
KB 997872 , from Mai 2022 - still a prerequisite ?

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-SharePoint#3917]
[Enter feedback here]
is KB5014022 still a prerequisite ?
This is a cumulative kb from 2022.05. Isn't this included/ superseded by the latest CU's for WS 2019 ? 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67210c40-a20f-cf02-6fc0-834fa6795a09
* Version Independent ID: e3ff92b2-6e58-dd9c-f0a6-0f88cd28b5fd
* Content: [Set up OneDrive in Citrix Virtual Apps - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/onedrive-in-citrix-virtual-apps-deployment-guide)
* Content Source: [SharePoint/SharePointOnline/onedrive-in-citrix-virtual-apps-deployment-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/onedrive-in-citrix-virtual-apps-deployment-guide.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
This repository is for PowerShell core documentation. You seem to be looking for support, which we can't provide here.
 
I suggest you try posting your issue with context in one of the available [community support forums][1].
 
[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
