### ISSUE TITLE
Grammar problem

### ISSUE THREAD

**Issue by jlackman** [MicrosoftDocs/OfficeDocs-SharePoint#3925]
this sentence;
"This setting has does not affect users. "

suggest removing the "has".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f65565e-e318-a6d3-2216-b81243b753f3
* Version Independent ID: 905fabb5-f3cb-0dd4-af58-f785a45002a5
* Content: [OneDrive sync reports in the Apps Admin Center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-health?tabs=windows)
* Content Source: [SharePoint/SharePointOnline/sync-health.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-health.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback!
