### ISSUE TITLE
Missing site collection feature in SPSE

### ISSUE THREAD

**Issue by lordBrightLord** [MicrosoftDocs/OfficeDocs-SharePoint#3929]
I'm using Sharepoint server subscription edition, and this article's instructions do not apply there. I've checked multiple site collections, and there's no such site collection feature titled _SharePoint Lists and Libraries experience_. Please update w/ the correct info.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f1bd4ab-c640-1db8-05bb-e249129dfa46
* Version Independent ID: 4ceb7bc8-39c0-61fb-b31c-381cb7a5018b
* Content: [Change the default list and library experience - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-default-list-and-library-experience)
* Content Source: [SharePoint/SharePointOnline/change-default-list-and-library-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-default-list-and-library-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @lordBrightLord 
How are you?
This article is under SharePoint Online content so it applies to it only.
Thank you
