### ISSUE TITLE
Feedback: Provide Clarification on SilentAccountConfig and AAD Joined Systems

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/OfficeDocs-SharePoint#3931]
Hey Team, I believe it would help if we can provide more clarification on this statement.  I believe this really only works right with Azure AD joined systems.  This setting **does not work** with Domain Joined system and I believe even Hybrid AD Joined systems.  I feel that needs to be called out.  There's a lot of challenges with customers using this setting incorrectly.  Hope this helps.

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/26752719/afe35e84-1334-4e89-8340-3601445e402b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#silently-sign-in-users-to-the-onedrive-sync-app-with-their-windows-credentials)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @brmcmill Brandon, how are you?

To clarify, on Azure AD joined systems (as the article says) it is working ok.
on any other type of domain joined (Hybrid or Domain) it is not working.

The article is currently not mentioning any other domain joined type other than Azure AD, do you still feel a call out is required?

Thanks for clarification,

**Comment by brmcmill** [comment]
Hello!  I do think it will help to call that out.  I've had to help a few customers and colleagues understand they should not use that setting unless they are in the right scenario.

**Comment by get-itips** [comment]
I'll propose to add it
