### ISSUE TITLE
Can't query or set on-demand states from command line

### ISSUE THREAD

**Issue by neldredge-unco** [MicrosoftDocs/OfficeDocs-SharePoint#3935]
The commands described here do not work for me.  For instance, trying the `/getpin` option, I get the output
```
% /Applications/OneDrive.app/Contents/MacOS/OneDrive /getpin hello.txt
objc[20383]: Class MSError is implemented in both /System/Library/PrivateFrameworks/MessageSecurity.framework/Versions/A/MessageSecurity (0x232251c28) and /Applications/OneDrive.app/Contents/Frameworks/MSCommon.framework/Versions/A/MSCommon (0x104f043b8). One of the two will be used. Which one is undefined.
2023-07-13 19:53:47.973 OneDrive[20383:341739] MSEnvironment: returning 0
2023-07-13 19:53:48.063 OneDrive[20383:341739] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
2023-07-13 19:53:48.089 OneDrive[20383:341739] -[NSTaggedPointerString getCharacters:range:]: Range {0, 46} out of bounds; string length 9
2023-07-13 19:53:48.402 OneDrive[20383:341739] -[NSTaggedPointerString getCharacters:range:]: Range {0, 46} out of bounds; string length 9
```
and then the command just hangs until you Ctrl-C it. 

I'm using OneDrive Version 23.132.0625.0001 (Standalone) (Apple silicon) under MacOS Ventura 13.4.1(c) on an M1 Macbook Pro.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9537147b-4205-3355-c7ff-a3a8c115d0ae
* Version Independent ID: cc079c73-e4fc-d5be-69e6-742e335d375e
* Content: [Set Files On-Demand states on Mac - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/files-on-demand-mac)
* Content Source: [SharePoint/SharePointOnline/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @neldredge-unco 
From what I could investigate, the ODB team is working on this.

**Comment by get-itips** [comment]
Other than that, as the team is aware, no documentation changes are required.
Please kindly follow up with support and also keep the ODB client updated.
