### ISSUE TITLE
Error encountered - Failed to login in to M365

### ISSUE THREAD

**Issue by CeesMIM** [MicrosoftDocs/OfficeDocs-SharePoint#3943]
When starting the agentsetup.exe as administrator from a VM server where this account also is domain admin and has the role as Sharepoint Administrator. It shows by start the welcome and after several seconds you can click Next and then the error shows.

Error encountered

Failed to login in to M365
You must be signed in as a Global or Sharepoint admin. Please check your credentials and try agian.

The error says he is looking on wich account has been logged in on the server and those credentials are wrong, or something graphical isn't right and by clicking Next it asks to put in the credentials @ the welcome screen, but there is nothing to fill in.

Also checked firewall and added the agentsetup.exe to exclude from Defender. Beside that, the server is open to 443 and can resolve websites of the internet.

Eventviewer is doens't show me anything (application, security-wise)

For the graphical part I installed .NET 3.5, but didn't help. The 4.7 was already there.

System OS is Windows Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 624f51bf-bf14-03ae-099b-2ee8b8657bf2
* Version Independent ID: 71bc428f-3fe9-1e9b-a996-871407127f96
* Content: [Setup Migration Manager agents - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-setup-clients)
* Content Source: [migration/mm-setup-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-setup-clients.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by CeesMIM** [comment]
<img width="1046" alt="Scherm­afbeelding 2023-07-18 om 10 13 36" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/139856998/d3d7e4b5-bb9a-483f-b814-2ead8e0d7d4a">

**Comment by CeesMIM** [comment]
I've tried the agentsetup.exe on a other server wich is running OS Server 2022, it came further and showed me the popup to authenticate with M365 with credentials of my choise.

With this knowledge I returned to my fileserver and started a Powershell and installed Azure Connect module and gave the command: Connect-AzureAD

This resulted with a error:  Connect-AzureAD : The browser based authentication dialog failed to complete. Reason: The server or proxy was not found. 

I've troublehoot this error and found nothing to fix it.

In the internet settings the connection is automaticly with no proxy settings active.
I do have internet and can browse to websites
I do can NSLOOKUP our M365 tenant
I've turned of firewall and Defender as Anti-Virus separately from each other with no luck

The only thing left to do is plan a inplace upgrade to Server 2022 and see if that helps

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
