### ISSUE TITLE
Missing components such as webparts/flows/infopath forms generated via SMAT inventory reports

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [MicrosoftDocs/OfficeDocs-SharePoint#3944]
Dear Team,
 
This is regarding the SMAT tool descripency we are currently facing with one of our customers to succefully migrate their on premises workload ( SP 2016) into SharePoint online.
 
We have noticed that many webparts/flows/forms have been not present in the SMAT tool reports which has put us in quite a challanging situation. It will be greatly appreicated if you could share whether SMAT tool reports are reliable to onclude all componenets? If not, what approach should we consider to gather inventory reports in SharePoint on premises?
 
We have also tried creating Powershell Scripts + Sharegate reports - all are having discrepencies more or less - We require a guidance on how should we approach this situation.
 
Kindly help. Thank you very much for your time in advance!
 
Best Regards,
Dipti

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [SharePoint Migration Assessment Tool - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by DiptiC-InsightRun** [comment]
Hello Team,

Just wanted to check up on this issue. Please share if I should be taking care of any information from my side.

Looking forward!

Best Regards,
Dipti

**Comment by get-itips** [comment]
Hello @DiptiC-InsightRun 
I think for this inquiry the best would be to open a support request as here we are limited to documentation fixes and changes.
Thank you,
