### ISSUE TITLE
Unable to locate this setting

### ISSUE THREAD

**Issue by iganu** [MicrosoftDocs/OfficeDocs-SharePoint#3952]
Note able to locate this => Select the OneDrive tab, and under Sharing, select Manage external sharing.

=> Maybe bcos Organisation level settings are lower

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec52357-8785-615f-e52f-cc9e38c8989f
* Version Independent ID: 405f0ace-09c2-0f33-5078-dc657c9dec24
* Content: [Change the external sharing setting for a user's OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/user-external-sharing-settings)
* Content Source: [SharePoint/SharePointOnline/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @iganu 
I was able to follow the instructions, can you please show what you see to understand if we need to update the article?
Thanks

**Comment by iganu** [comment]
Hi, That is bcos the Org Wide settings were lower not allowing for external sharing. In this article, we have to mention to check first with Admin the Org Site level settings to be increased to external sharing; only then these options are available to all users.

**Comment by HansBrender** [comment]
@get-itips 
I think @iganu  want a comment, to check first the Tenant settings or Org site lever settings and then follow the description

Both settings are higher in the hirarchy
