### ISSUE TITLE
How are subdomains handled for Allowed Domains?

### ISSUE THREAD

**Issue by SP-INV** [MicrosoftDocs/OfficeDocs-SharePoint#3960]
Hi

How are subdomains handled by SharePoint Online for the list of Allowed Domains?
Does adding the primary domain also encapsulate all subdomains, or do they need to be explicitly added as separate entries?

The doco states that wildcards are not valid, so that option can't be used.

Basic example:
Will the entry
  microsoft.com
also allow
  sharepoint.microsoft.com
  teams.microsoft.com
  exchange.microsoft.com

Thanks
Sean

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restricted-domains-sharing)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @SP-INV 
AFAIK you also have to specify subdomains. https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps#-sharingalloweddomainlist

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
