### ISSUE TITLE
settings that need to be removed to "reset" a client for silent AccountConfiguration.

### ISSUE THREAD

**Issue by IP-dbruce** [MicrosoftDocs/OfficeDocs-SharePoint#3964]
In addition to removing the "SilentBusinessConfigCompleted" entry you also need to remove the "ClientEverSignedIn" entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17aec87c-a56c-91c0-b2d5-5f9f11322c1e
* Version Independent ID: 439abe40-cdab-e480-0df9-30aa183ef521
* Content: [Silently configure user accounts - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-silent-account-configuration)
* Content Source: [SharePoint/SharePointOnline/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @IP-dbruce 
I'm working on this.
