### ISSUE TITLE
Wrong reg key for "verify per-machine install" on OneDrive sync app "Per-machine installation" page?

### ISSUE THREAD

**Issue by apjanke-demex** [MicrosoftDocs/OfficeDocs-SharePoint#3967]
The "Per-machine installation" page for the SharePoint sync app (that's the same thing as "OneDrive", right?) has instructions for verifying that your computer has a per-machine installation of OneDrive. It tells you to check the registry key HKLM\SOFTWARE\Microsoft\OneDrive\Version and see if it contains the value "19.043.0304.0007".

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/103077281/853491ad-2ca5-4f19-b2cb-0ba37fd31695)

That seems like it's checking the version of OneDrive you have installed, and not whether it's a per-machine installation? At the least, OneDrive is now on version 23.147.x, so won't that test return false unless your machine has a specific older version of OneDrive?

Does the mere existence of the registry key HKLM\SOFTWARE\Microsoft\OneDrive under HKEY_LOCAL_MACHINE instead of HKEY_CURRENT_USER imply that it's a per-machine installation? In that case, maybe it should be checking for just the existence of the key, and not that it has a particular value for Version?

I see an "AllUsersInstall" item with a value of 1 under the HKLM\SOFTWARE\Microsoft\OneDrive key on my machine which I think has a per-machine installation (because this is a VM from an Azure "Windows 10 Multi-Session with Office Apps" image (win10-22h2-avd-m365-g2) and that OneDrive is what came with the image). Should this verification test be checking that thing instead?

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/103077281/3642c6e1-cf36-495a-b9f0-41e740dd6355)

Cheers,
Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d03e432e-17b8-cdf8-5cd1-158f19d493e4
* Version Independent ID: 699feed2-7123-c54d-8e01-4be30466f3e4
* Content: [Install the sync app per-machine (Windows) - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/per-machine-installation)
* Content Source: [SharePoint/SharePointOnline/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
@apjanke-demex 
If you do not have an installtion made with /allusers

- You not have the HKLM\Software\Microsoft\    No OneDrive folder OR
- You see HKLM\Software\Microsoft\OneDrive  and the miss the Key AllUsersInstall
Then ist is a Installation in the users Path  C:\Users\[User]\Appdata\local\Microsoft\OneDrive\  OR
C:\Program Files x86\Microsoft OneDrive\ for 32 Bit OR
C:\Program Files\Microsoft OneDrive\  for 64 Bit

But if you have taken a preconfigured Version (as you described) OR
Deinstall a configured version and install  it with the /Allusers parameter,
then the Key HKLM\Software\Microsoft\OneDrive  AllUsers is set to 1
so all users on this device uses the same OneDrive version, and  only one automatic Update will be done for all users.

The Item AllUsersInstall  with an Value=1 makes the difference 

@gacarini
