### ISSUE TITLE
Location of the adml file

### ISSUE THREAD

**Issue by alexfreu69** [MicrosoftDocs/OfficeDocs-SharePoint#3968]
[Enter feedback here]

Please don't put the OneDrive.adml into the adm top folder. It belongs into en-US. Otherwise you will get an error message while using gpedit.msc.

---------------------------
Administrative Templates
---------------------------
An appropriate resource file could not be found for file C:\WINDOWS\PolicyDefinitions\OneDrive.admx (error = 2): The system cannot find the file specified.

---------------------------
OK   
---------------------------

Please create a folder en-US and en-GB and put the OneDrive.adml there. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
it depends, what language you have installed.
The OneDrive.admx from you OneDrive Installation
a) C:\Users\[User]\Appdata\Local\Micxrosoft\OneDrive\[OneDriveVersion]\adm\OneDrive.admx    User Installation  OR
b) C:\Program Files X86\Microsoft\OneDrive\[OneDriveVersion]\adm\OneDrive.admx    32 Bit Installation  OR
c) C:\Program Files\Microsoft OneDrive\[OneDriveVersion]\adm\OneDrive.admx   64 Bit Installation

has to be copled into C:\PolicyDefinitions

The corrosponding OneDrive.adml where you copied the admx file is the EN-US Version
There are some other languages with the language of your system
Folder de is a german version
Folder fr is a french version

Inside the Policy definition you have at least 1 language folder
en-US   or
de-DE  ....

so the right adml file form the current OneDrive version installation must be copied into to the corresponding PolicyDefinitions path.
if there are more than one language copy all OneDrive.adml into the corresponding Policydefinitions path

You do nt have to create a PolicyDefinitions path manualy. If you install a second language The PolicyDefinitions path with the Language Abbreviation will be created.

**Comment by alexfreu69** [comment]
That is all clear. When I copy admx and adml files from other sources (Office zip files for instance) I mark the admx files and the folders en-us and de-de, copy them and paste them into PolicyDefinitions. Finished in 3 seconds. Try the same with the OneDrive adm* files. This is no issue at all. Just something that can be improved in my opinion to match the layouts.

**Comment by tiburd** [comment]
Closing this issue because it is not related to documentation.

cc: @scanum
