### ISSUE TITLE
Introducing acronyms without defining them

### ISSUE THREAD

**Issue by m0fugga** [MicrosoftDocs/OfficeDocs-SharePoint#3969]
Introducing acronyms without defining them is poor form.  The first time you introduce an acronym in writing, you should spell out the entire term and include the acronym in parentheses before referencing the acronym directly thereafter.  The acronym ADAL is mentioned 6 times in the article and not once defined.  For more information, please reference your first semester in college.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17aec87c-a56c-91c0-b2d5-5f9f11322c1e
* Version Independent ID: 439abe40-cdab-e480-0df9-30aa183ef521
* Content: [Silently configure user accounts - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-silent-account-configuration)
* Content Source: [SharePoint/SharePointOnline/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
