### ISSUE TITLE
MarkNewFilesSensitiveByDefault causes double alerts

### ISSUE THREAD

**Issue by GeorgeChiuTheHartford** [MicrosoftDocs/OfficeDocs-SharePoint#3970]
This feature seems to cause document update and thus if document library alert is set, users will get doubt alerts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a19bcff-df5b-bc9f-269d-482d44d70b61
* Version Independent ID: 31a35f88-d3ca-f765-7678-339ad81771f9
* Content: [Prevent guest access to files while DLP rules are applied - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sensitive-by-default)
* Content Source: [SharePoint/SharePointOnline/sensitive-by-default.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sensitive-by-default.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by GeorgeChiuTheHartford** [comment]
The following will result in two alerts being sent.  It looks like a document update done on the background and the library alert for any changes (new/modification) is acting upon to send two alerts - first for file creation and 2nd for document update
https://learn.microsoft.com/en-us/sharepoint/sensitive-by-default

Set-SPOTenant -MarkNewFilesSensitiveByDefault BlockExternalSharing

**Comment by get-itips** [comment]
Hello @GeorgeChiuTheHartford 

I tested this and I did not receive alerts when I set Set-SPOTenant -MarkNewFilesSensitiveByDefault BlockExternalSharing

Can you please detail if any other configuration was present? To understand if I need to edit any documentation.
Thank you

**Comment by GeorgeChiuTheHartford** [comment]
Hi Andres,


It is after you set “Set-SPOTenant -MarkNewFilesSensitiveByDefault BlockExternalSharing” , your exiting or new library alerts (link below) will send you two alerts for any new document.    If BlockExternalSharing is NOT set, for newly uploaded file,  you will just get a single alert.


Create an alert to get notified when a file or folder changes in SharePoint - Microsoft Support<https://support.microsoft.com/en-us/office/create-an-alert-to-get-notified-when-a-file-or-folder-changes-in-sharepoint-e5a79e7b-a146-46da-a9ef-d65409ba8918>



Thanks,



George

**Comment by GeorgeChiuTheHartford** [comment]
Andres:

Yes you also need to configure an SPO Library alert as well, using 'all changes' options.  They are 2 separate alerts, one from the person that uploads the file to the library as an 'ADD' alert and one from 'System Account' that tags the file as 'Sensitive By Default' 'CHANGED' alert..


Thanks,

Jim




From: Chiu, George (Infrastructure) ***@***.***>
Sent: Wednesday, August 2, 2023 3:02 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>; MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Mention ***@***.***>; Penna, James (Infrastructure) ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SharePoint] MarkNewFilesSensitiveByDefault causes double alerts (Issue #3970)

Hi Andres,


It is after you set "Set-SPOTenant -MarkNewFilesSensitiveByDefault BlockExternalSharing" , your exiting or new library alerts (link below) will send you two alerts for any new document.    If BlockExternalSharing is NOT set, for newly uploaded file,  you will just get a single alert.


Create an alert to get notified when a file or folder changes in SharePoint - Microsoft Support<https://support.microsoft.com/en-us/office/create-an-alert-to-get-notified-when-a-file-or-folder-changes-in-sharepoint-e5a79e7b-a146-46da-a9ef-d65409ba8918>



Thanks,



George

**Comment by get-itips** [comment]
Yes, I already had all changes alert set, but I'm afraid I did not receive any alert when I use the cmdlet.

**Comment by GeorgeChiuTheHartford** [comment]
Hi Andres.

We tested in multiple tenants.   Have you uploaded any documents to trigger the alert after running the powershell cmet?

Thanks,

George


Thanks,

George Chiu
________________________________

**Comment by GeorgeChiuTheHartford** [comment]
Hi Andres,

There is no documentation errors but a bug.   We have also used the premium support channel to report this issue and Microsoft support team has confirmed they can reproduce this issue.

Thanks,

George

**Comment by get-itips** [comment]
@GeorgeChiuTheHartford I understand George, however here we can not handle bugs, only documentation fixes.

**Comment by GeorgeChiuTheHartford** [comment]
Understood
