### ISSUE TITLE
Can't enter valid destination site

### ISSUE THREAD

**Issue by jeffreyoliver** [MicrosoftDocs/OfficeDocs-SharePoint#3987]
I've entered in a valid URL for a SharePoint site and the UI is telling me "No results found". 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87ed69e8-7a5e-5e4b-12e5-0824ab5ef010
* Version Independent ID: 80535eb7-e53c-7718-4426-a424af712ec6
* Content: [Review the destination paths for your Box migration with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-box-step4-review-destinations)
* Content Source: [migration/mm-box-step4-review-destinations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step4-review-destinations.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @jeffreyoliver 
How are you?
The best in your case would be to open a support request directly from the 365 admin center as here we are limited to documentation issues.
Thank you
