### ISSUE TITLE
21V CCB2B is now supported

### ISSUE THREAD

**Issue by rmrosen** [MicrosoftDocs/OfficeDocs-SharePoint#3995]
Where it says in a Note "This integration isn't supported in Office 365 operated by 21Vianet." is not correct.  Cross-cloud B2B (CCB2B) is now supported. Please make the update. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @rmrosen I'm working on this.

**Comment by get-itips** [comment]
An update to the article is coming soon

**Comment by get-itips** [comment]
Article updated after review by team

**Comment by rmrosen** [comment]
Hello @get-itips , @scanum 

The article online is still dated from Mar 2023. Any idea when it will reflect the updates?

Thanks,
Ray
