### ISSUE TITLE
SharePoint Admin Center Access Requirements

### ISSUE THREAD

**Issue by johnmconner** [MicrosoftDocs/OfficeDocs-SharePoint#3999]
"Users assigned the SharePoint Administrator role have access to the SharePoint admin center" This is inaccurate. Access to the SharePoint Admin Center requires BOTH the SharePoint Admin Role AND the Teams Admin Role. I just spent an hour trying to figure out why a user was unable to access the SharePoint Admin Center after being assigned the SP Admin Role. Found the solution on reddit. Adding the Teams Admin Role resolved the issue. Please confirm and update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7461c2ef-3439-2c86-4dde-8992b62bf9a7
* Version Independent ID: faa4e3aa-8ec4-f1f1-d4bd-4058999545f3
* Content: [About the SharePoint Administrator role in Microsoft 365 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-admin-role)
* Content Source: [SharePoint/SharePointOnline/sharepoint-admin-role.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-admin-role.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @johnmconner John,

I tested this several times, and only SharePoint Administrator role was enough to access the SP Admin Center.

Thank you,

**Comment by get-itips** [comment]
Closing @scanum
