### ISSUE TITLE
"can't ... neither ... nor" is not correct

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#400]
Re this sentence fragment: "you can’t turn off neither classic nor modern search", this is not a correct usage of "neither ... nor". It should either be:

"you can turn of neither classic nor modern search"

or

"you can't turn off either classic or modern search"

Using "can't" with "neither" is a double-negative.

I think the first option is grammatically better, but probably the second is the better choice for an international audience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f89b7-afd4-1b65-f3ad-c802c7dd5a47
* Version Independent ID: 0f3e61c4-6b03-dccb-6067-09ed98228f62
* Content: [Differences between the classic and modern search experiences in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search#feedback)
* Content Source: [SharePoint/SharePointOnline/differences-classic-modern-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/differences-classic-modern-search.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by AndreaBarr** [comment]
@repton-infinity Thank you for pointing this out

I will get this sentance fragment over to the SharePoint Team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tklarsen** [comment]
Fixed :-)
