### ISSUE TITLE
Syncing IRM-protected libraries now supported on Mac?

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SharePoint#401]
In the Client Release Notes article at https://support.office.com/en-us/article/new-onedrive-sync-client-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0, it indicates that syncing SharePoint libraries protected is now supported by the Mac client as of versions 18.111.0603.0004﻿﻿﻿ (Released June 26, 2018) on the Enterprise ring and 18.172.0826.0013 (Released October 15, 2018) on the Production ring. 

The release notes link to this article, which still states that Mac is not supported. Is the feature still rolling out? If not, this article needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930a4d28-a511-e037-fa15-e4f3aebc7064
* Version Independent ID: 22a6cf03-0378-84b1-0ade-236018d49b3b
* Content: [Let users sync IRM-protected files with the OneDrive sync client](https://docs.microsoft.com/en-us/sharepoint/let-users-sync-irm-protected-files?redirectSourcePath=%252fen-us%252farticle%252fEnable-users-to-sync-IRM-protected-files-with-the-OneDrive-sync-client-Preview-6778d4de-b5f8-423c-af43-a1b2449e9b99)
* Content Source: [SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@rgsteele Thank you for this inquiry

I do now know the answer for this question regarding Macs and SharePoint. Let me get this to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by gacarini** [comment]
I've just submitted a change to remove the reference to Mac IRM in the release notes for the 18.111 build.
