### ISSUE TITLE
Workflow migration feature in version 4.1 - is SPO site source supported?

### ISSUE THREAD

**Issue by KuotingChiu** [MicrosoftDocs/OfficeDocs-SharePoint#4010]
I am so sorry that I am re-opening issue #3830 regarding workflow migration feature.

Can you please help clarifying if the migration source can be SharePoint Online?  Please review the 2 screenshots I provided in the attachment.   Our use case is that we have already migrated all SharePoint sites from on-prem to SharePoint online already but has some  2013 type of workflow still thee in SPO that we'd like to see SPMT can be used to migrate workflows in SPO sites to Power Automate.

[Screenshots.docx](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/12365204/Screenshots.docx)

**Comment by KuotingChiu** [comment]
Any news?  @get-itips or @scanum ?

**Comment by get-itips** [comment]
Hello @KuotingChiu 
How are you? AFAIK SPMT supports only On-Premises sources

https://learn.microsoft.com/en-us/sharepointmigration/what-is-supported-spmt

**Comment by KuotingChiu** [comment]
Thanks!  That's seems to be the case the tool cannot use the URL of SPO as the source.   Too bad it is not supported as we have sunset our on-prem SharePoint farms already.

**Comment by KuotingChiu** [comment]
Not sure if a product design change request/idea can be submitted
