### ISSUE TITLE
Cannot remove Google Drive migration project from dropdown in Project Settings

### ISSUE THREAD

**Issue by KevinAWorthington** [MicrosoftDocs/OfficeDocs-SharePoint#4018]
Hello, is there any way to remove a Google Drive migration project from the project selector dropdown (where it says "Create new migration"? The "add project" input displays the message "Note: There is a 5 project limit". If there is no way to remove completed projects, then tenants are effectively limited to 5 Google Drive projects in total.

![MM](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/50425395/b6358a26-966c-4072-ba6a-837b5945234f)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
