### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Mitzhel** [MicrosoftDocs/OfficeDocs-SharePoint#402]
Hello.

Is there a way to stop OneDrive from syncing shortcuts(Ink files) when using Redirect known folders?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@Mitzhel Thank you for this inquiry. 

I am not sure if there is a shortcut for this. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Mitzhel** [comment]
@AndreaBarr @tseward 

Thank you for your answers. Can i request this feature then?

It's gonna get messy real quick if OneDrive starts syncing
broken shortcuts between all shared computers that our students use.

We really want to use OneDrive with "Redirect known folders", but if all our students and
teachers's desktop is gonna eventually be filled up with broken shortcuts, then we are gonna have to wait.

@radiosavage 
I Agree.

**Comment by tseward** [comment]
@Mitzhel I would post on the OneDrive Uservoice; that is the proper place to make feature requests.

https://onedrive.uservoice.com/forums/913522

**Comment by doucheface1** [comment]
can someone twll me if this policy works with on premise ondrive. the policy asks for a tenant ID which you do not have for on-premise sharepoint My site ondrive

**Comment by kaarins** [comment]
Hi, the known folder move policies don't work with SharePoint Server 2019. I will add that to the article. Thank you! To request this feature, please go to the OneDrive UserVoice: https://onedrive.uservoice.com/forums/913522
