### ISSUE TITLE
No Download Link for the OneDrive ADMX files

### ISSUE THREAD

**Issue by cmrsearch** [MicrosoftDocs/OfficeDocs-SharePoint#4020]
Step by step instructions on how to install the OneDrive ADMX files to a Central Store, but nowhere is there a link yet it is this page that comes up when searching for said OneDrive ADMX download.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy#manage-onedrive-using-group-policy)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
@cmrsearch  With each Installation/Update of the Sync client  they also install the current admx/adml files in a subdirectory  of your current version . This subfolder is the first one named "adm" So teher you find the OneDrive.admx and the us version of OneDrive.adml. For your language there are language folders starting with de (Germany)

**Comment by tiburd** [comment]
Thank you for your contributions. It sounds like the question is answered, so we're closing this issue.
