### ISSUE TITLE
Intelligent Intranet Envisioning Workshop PowerPoint deck link not working

### ISSUE THREAD

**Issue by Elangamban** [MicrosoftDocs/OfficeDocs-SharePoint#4021]
The PPT link is not working.

[Intelligent Intranet Envisioning Workshop PowerPoint deck](https://resources.techcommunity.microsoft.com/link/sharepoint-envisioning-workshop-concept/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91eac3ca-b2e9-1591-629c-670bee1f709e
* Version Independent ID: 06a0ddf7-3e07-0681-777b-4257dd5bd668
* Content: [Intelligent intranet introduction - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/intranet-team-overview)
* Content Source: [SharePoint/SharePointOnline/intranet-team-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/intranet-team-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Thanks for your feedback!
