### ISSUE TITLE
Extend documentation about automatically updates to reflect changes on managed metadata (merge)

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/OfficeDocs-SharePoint#4022]
https://learn.microsoft.com/en-us/sharepoint/managed-metadata#increased-flexibility

This part describes what happens if you merge 2 terms.

_For example, if you merge multiple terms into one term, content that is tagged with these terms is automatically updated to reflect this change._

However, it would be useful to get more information about where we can automatically see these updated terms.
- New items that are tagged
- Existing items that were previously tagged

Also, when will these changes apply? Is this an hourly sync, immediately only on update item action?

And finally, how can we troubleshoot cases in which changes to terms do not reflect after couple of days?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4d14723-ab30-719c-c69d-e42f94a680b5
* Version Independent ID: 182bf188-87f6-f966-4e86-77ef8927905c
* Content: [Introduction to managed metadata - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/managed-metadata#increased-flexibility)
* Content Source: [SharePoint/SharePointOnline/managed-metadata.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/managed-metadata.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @yvesrosius 
How are you?
I tested this, 
It took less than an hour to reflect in the already tagged content, and it was automatically available for new content.

Hope this answer your question.

**Comment by yvesrosius** [comment]
Hi Andres

Yes, that would be an answer :-)

But it would be handy to have documentation about this. Because now, this is just a test case in a controlled environment.

I would like to know what to expect exactly, and what we can do if things go wrong. So that the Microsoft Learn article displays this information.
