### ISSUE TITLE
Cannot delete a subkey tree because the subkey does not exist

### ISSUE THREAD

**Issue by Mwille93** [MicrosoftDocs/OfficeDocs-SharePoint#4027]
I make my sharepoint site just as described here https://learn.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web and all previous commands work fine, however whenever I try to run the Set-SPOCustomFontCatalog with my path and library URL I keep getting the Cannot delete a subkey tree because the subkey does not exist error. 
![Fonts](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/143615430/af8e60cb-a851-48f3-b658-1af040768de5)

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
