### ISSUE TITLE
More Detailed Documentation on Migration Options

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/OfficeDocs-SharePoint#4029]
Could you please expand the documentation to describe what ALL of the settings are that are available for migrations?  My specific use case is to filter out documents that are X number of years old. I can't tell from the documentation if that is possible. The configuration settings section has a section called "All settings". What are the options in that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e06d8f2b-828c-aafe-41cc-30be91fbdf41
* Version Independent ID: 1ed236b8-ab64-6f0e-1cab-901743d575dc
* Content: [Step 3: Copy to migrations for file share migration - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-fileshare-copy-to-migrations)
* Content Source: [migration/mm-fileshare-copy-to-migrations.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-fileshare-copy-to-migrations.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @robertcaretta 
How are you?

That's documented here 

https://learn.microsoft.com/en-us/sharepointmigration/mm-settings
