### ISSUE TITLE
Integration with Conditional Access

### ISSUE THREAD

**Issue by ihloff** [MicrosoftDocs/OfficeDocs-SharePoint#403]
How does this  function work with a Conditional Access Policy applied? Is this ruleset applied independent from Conditional Access?

**Comment by AndreaBarr** [comment]
@ihloff Thank you for this inquiry.

I am not sure how this function works with a Conditional Access Policy applied. Let me get this over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@ihloff can you indicate which function you're talking about? There's no reference to the original source document/tech in your issue.

**Comment by tseward** [comment]
The OneDrive domain policy only applies to clients which are capable of Active Directory domain join, so you're correct they do not prevent mobile clients from synchronizing.

As far as conditional access policy, they are independent settings. Both policies will be evaluated. Typically in the order of Conditional Access Policy then OneDrive domain policy (Azure is the front door, here).

**Comment by tseward** [comment]
@scanum please close.
