### ISSUE TITLE
Indexing after a permissions change

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/OfficeDocs-SharePoint#4031]
It appears that reindexing is limited to actual changes to the file or its associated metadata.
How long after the permissions are changed on an item will it be reindexed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d18cdf74-1e86-aa79-3282-69ffc9cdd282
* Version Independent ID: 39cea6c4-be38-1908-7815-aa9ee552cedf
* Content: [Manually request crawling and reindexing of a site, a library or a list - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/crawl-site-content)
* Content Source: [SharePoint/SharePointOnline/crawl-site-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/crawl-site-content.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
