### ISSUE TITLE
GCCH Call out

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SharePoint#4043]
Thank you for specifically calling out that this feature is available in GCCH. You mention the cost for commercial. Can you add additional language on pricing for GCCH. "If you are looking to use SharePoint Advanced Mgmt P1 in GCCH please contact your Microsoft account team or AOS-G Partner for pricing". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9aa1a91-e838-41c6-45cb-6a2a4dbf1a7a
* Version Independent ID: 5f5c1b99-126f-2a70-20c8-f00136927e31
* Content: [Microsoft Syntex - SharePoint Advanced Management overview - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/advanced-management)
* Content Source: [SharePoint/SharePointOnline/advanced-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/advanced-management.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello, I'll propose to add that to the article.
