### ISSUE TITLE
This page is outdated, please update

### ISSUE THREAD

**Issue by MojoMoe** [MicrosoftDocs/OfficeDocs-SharePoint#4047]
The 'create new migration' option in Admin Center looks like it was recently updated. Please update the page/guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a83a2dc-b338-fcbe-1c12-f837396516fd
* Version Independent ID: ee0ef078-f0ac-c411-027a-bedfc62f934d
* Content: [Connect to Dropbox with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-dropbox-step1-connect)
* Content Source: [migration/mm-dropbox-step1-connect.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-dropbox-step1-connect.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @MojoMoe Moe, how are you?
While I investigate this, can you please detail which step/option you could not follow compared to the article?
Thank you!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by MojoMoe** [comment]
The option to add a new connection to Dropbox for migration has changed to 5 new connections rather than being limited to 1. The entire process needs to be documented and the instructions/guide needs to be updated to reflect these changes that were made in August or September 2023. I have created another issue here for a similarly outdated page - https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/4060

**Comment by MojoMoe** [comment]
> We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
> 
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

The option to add a new connection to Dropbox for migration has changed to 5 new connections rather than being limited to 1. The entire process needs to be documented and the instructions/guide needs to be updated to reflect these changes that were made in August or September 2023. I have created another issue here for a similarly outdated page - https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/4060
