### ISSUE TITLE
Confusion on license requirements

### ISSUE THREAD

**Issue by peterfle71** [MicrosoftDocs/OfficeDocs-SharePoint#4048]
Advanced Compliance license seems like an odd choice for "Apply the authentication context directly to a site" as this SKU is not available anymore. Furthermore the license requirement is in contradiction to https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling (see section for applying conditional access policies via authentication context to SharePoint sites using sensitivity labels.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0333d571-acdd-5efb-f22f-6c75822ce12c
* Version Independent ID: e7e2d85d-053e-164f-4ddd-675c5ccc97f4
* Content: [Conditional access policy for SharePoint sites and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/authentication-context-example)
* Content Source: [SharePoint/SharePointOnline/authentication-context-example.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/authentication-context-example.md)
* Service: **sharepoint-online**
* GitHub Login: @MachelleTranMSFT
* Microsoft Alias: **mactra**

**Comment by peterfle71** [comment]
Hello @get-itips,

I also had a support ticket 2309191420002002 for a technical problem about this and the support engineer just informed me that this feature is E5 only. No E3 + some E5 add-on. Pure and complete E5 is needed.

Just wanted to let you know.

Regards

Peter

**Comment by get-itips** [comment]
Hello,
I checked internally and after analysis by the team I was let know that both articles are currently ok.
