### ISSUE TITLE
Broken link in Article..

### ISSUE THREAD

**Issue by bodowney** [MicrosoftDocs/OfficeDocs-SharePoint#405]
Link labeled "How to set Azure Active Directory device-based conditional access policy for access control to Azure Active Directory connected applications" is broken.... Leads to a 404.. )  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync client for Windows](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access#feedback)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@bodowney Thanks for reporting this! I fixed the links!
