### ISSUE TITLE
The strange phenomenon of a scheduled task being modified to "run now"

### ISSUE THREAD

**Issue by ferrarifan-bj** [MicrosoftDocs/OfficeDocs-SharePoint#4051]
Hi everyone,
After I successfully submitted a scheduled task, then I edited the scheduled time and changed the radio button from "run later" to "run now". Next, an idle agent will run it, but after the run is completed, the status of this task is not "complete", but it will maintain the original scheduled time status. Why? And What is the correct operating way？

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9987ad30-b466-2e88-800d-4fd5de647c39
* Version Independent ID: ff348097-e178-f64f-4872-b173567df74b
* Content: [Setting migration task schedules in Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-scheduling)
* Content Source: [migration/mm-scheduling.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-scheduling.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
