### ISSUE TITLE
Please clarify support for OneDrive

### ISSUE THREAD

**Issue by Greg-T8** [MicrosoftDocs/OfficeDocs-SharePoint#4053]
Hello,

While the title of the article indicates Azure AD B2B integration for SharePoint and OneDrive, I'm only finding that guest accounts are created in SharePoint and not in OneDrive. 

Line 50 of this article reads "When the integration is enabled, people outside the organization will be invited via the Azure B2B platform when sharing *from SharePoint*."  Given my findings from above, this sentence seems to imply that the AzureB2B platform only applies for SharePoint (given that it leaves out OneDrive).

Can you please adjust for clarity and confirm whether OneDrive is indeed supported for the Azure B2B platform?  

See here for more context: https://learn.microsoft.com/en-us/answers/questions/1369242/expectations-for-automatic-guest-creation-when-sha

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [Azure AD B2B integration for SharePoint & OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Greg-T8** [comment]
I figured out the issue after working w/ Microsoft Support.  The default sharing link options in SharePoint Admin are set as **Anyone with the link**.  Guest accounts aren't created when sharing links using this method.  

I recommend adding a note on this page that guest accounts are created when using the sharing link option **Specific People**.

**Comment by get-itips** [comment]
Hello @Greg-T8 Greg, how are you?
That is called out in this article https://learn.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off#file-and-folder-links in the important note, please let me know if I understood correctly.
Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
