### ISSUE TITLE
can not find "Site storage limits"

### ISSUE THREAD

**Issue by zhanglongqi** [MicrosoftDocs/OfficeDocs-SharePoint#4054]
[Enter feedback here]

can not find "Site storage limits"

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/956693/074fe738-368e-4e21-89bf-b7a69a78dffa)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits in SharePoint in Microsoft 365 - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
