### ISSUE TITLE
/pin is the correct command.  /setpin is invalid.

### ISSUE THREAD

**Issue by atlauren** [MicrosoftDocs/OfficeDocs-SharePoint#4055]
Hello,

As of OneDrive.app 23.189.0910.00001, the documentation for Files-on-Demand is incorrect.

The prescribed `/setpin` is nonfunctional.  If using `/setpin`, the full client launches and never returns to the shell. 

After some digging on the Macadmins Slack I found this hint:
https://macadmins.slack.com/archives/C1HNS6CTB/p1644360665140419?thread_ts=1644352628.958319&cid=C1HNS6CTB

I've verified via strings that there are no instances of `/setpin` in the OneDrive binary.  Meanwhile, `/pin` *does* appear.

If substituting `/pin`, the documented commands and experience succeed as described.

Please revise the documentation to match product reality.

Kind regards,
Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9537147b-4205-3355-c7ff-a3a8c115d0ae
* Version Independent ID: cc079c73-e4fc-d5be-69e6-742e335d375e
* Content: [Set Files On-Demand states on Mac - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/files-on-demand-mac)
* Content Source: [SharePoint/SharePointOnline/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @atlauren Andrew,
[Last time I checked](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3935), ODB Team was working on fixing this, I'll try to confirm if they replaced setpin with pin
