### ISSUE TITLE
Support for multigeo?

### ISSUE THREAD

**Issue by fthorild** [MicrosoftDocs/OfficeDocs-SharePoint#4059]
When running the below cmdlet in step 8...
 `Set-SPOCustomFontCatalog -FontFolder <Local Font Folder Location> -LibraryUrl <Document Library SharePoint URL>` 

...I get this error. 

` Set-SPOCustomFontCatalog : Failed to udpate the cross geo property in local tenant store of default location: Object reference not set to an instance of an object `

The tenant I am working on do have multigeo enabled but I/we are not sure how to proceed to get this working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a81f0-e811-3420-5270-16bc0eb21baf
* Version Independent ID: 8012480a-b73b-21b1-7212-911064182582
* Content: [Support for organization fonts in PowerPoint for the web - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/support-for-organization-fonts-in-powerpoint-for-the-web#adding-organization-fonts-to-sharepoint-as-an-organization-asset-library)
* Content Source: [SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/support-for-organization-fonts-in-powerpoint-for-the-web.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
