### ISSUE TITLE
Incorrect video thumbnail image

### ISSUE THREAD

**Issue by simpkinspete** [MicrosoftDocs/OfficeDocs-SharePoint#4063]
The thumbnail for the video on this page is incorrect and needs to be updated; The video content is accurate.  The thumbnail image says "Microsoft PowerPoint - Layer objects on Slides" instead of "Microsoft SharePoint - Rename your SharePoint domain."

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13559778/c3394a94-e88f-443c-888b-48726a596a49)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @simpkinspete Pete,
Thanks for your feedback, unfortunately, the video thumbnail is out of control of Learn/Docs, but I'll pass this feedback on.
Thanks again,
