### ISSUE TITLE
Set-SPOTenant : Field or property "SyncAadB2BManagementPolicy" does not exist.

### ISSUE THREAD

**Issue by MubSalim** [MicrosoftDocs/OfficeDocs-SharePoint#4064]
Hi 

When I run the following commands:

```
Set-SPOTenant -EnableAzureADB2BIntegration $true
Set-SPOTenant -SyncAadB2BManagementPolicy $true
```

the first one works but the second (SyncAadB2BManagementPolicy) returns the following error:

```
Set-SPOTenant : Field or property "SyncAadB2BManagementPolicy" does not exist.
At line:1 char:1
+ Set-SPOTenant -SyncAadB2BManagementPolicy $true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOTenant], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetTenant
```

This confused me as intellisense picks up the SyncAadB2BManagementPolicy property and I would assume that it therefore is a valid command.

I understand the property is not one that can be set and it just kicks off a sync of AAD B2B policies. I was just confused and seeking clarification about the message that is returned.

Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
