### ISSUE TITLE
Clarify if turning off OneDrive sync for SharePoint libraries impacts 'Add shortcut to OneDrive'

### ISSUE THREAD

**Issue by simpkinspete** [MicrosoftDocs/OfficeDocs-SharePoint#4066]
Can you clarify how the PowerShell script mentioned under the **Turn off OneDrive syn for SharePoint libraries** section will impact the ability to use the _Add shortcut to OneDrive_ feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 367f3b91-1252-7bce-fd1e-21ceb1ae12f3
* Version Independent ID: 66e3f10a-0231-e7e0-0659-0be66eaf13fa
* Content: [Sync in SharePoint and OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sharepoint-sync#sharepoint-file-sync-and-onedrive-shortcuts)
* Content Source: [SharePoint/SharePointOnline/sharepoint-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-sync.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
**You can only sync once.** The PowerShell Script disable the sync Button, but existing  connections are still valid
_Removing the sync button blocks new syncs from being started but doesn't affect existing syncs._

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
