### ISSUE TITLE
Are there any plans to fix the bug that allows sharing files to external users in the Sharepoint mobile iOS app?

### ISSUE THREAD

**Issue by bic-taniya** [MicrosoftDocs/OfficeDocs-SharePoint#4067]
Are there any plans to fix the bug that allows sharing files to external users in the Sharepoint mobile iOS app?

If you use a browser instead of a mobile device, it cannot be accessed from outside even if you share it.

In the answer by Microsoft Japan
It appears that you cannot share files using "Send link" in the Sharepoint iOS app, and "Invite users" directly restricts access, and external users are required to sign in.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
