### ISSUE TITLE
Restrict sharing experience by domain for OneDrive for Business

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint#4068]
Hello,

I am testing restrict sharing by domain on SharePoint Online and OneDrive for Business.
I have a question about experence when a shareable domain (allowlist) has been set up and is to be shared with **existing** guests.

According to the below article, it is noted in parentheses that when sharing to an existing guest in SPO site, no error is displayed on sharing dialog, but access will be blocked if the domain isn't allowed.

>(If the user is already in your directory, you won't see the error, but they will be blocked if they attempt to access the site.)

<img width="534" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13634805/f1773bfd-92a0-42ef-8cac-d6aa36cde413">

As far as I tested, the behavior on OneDrive sites is as well. In other words, when sharing to an existing guest user that the user's domain is doesn't allowed, there is no error on sharing dialog, but the user can't access the shared content.

In the article, the below note specified sharing on SPO site only, but I think it can apply on OneDrive site as well. 
If my understanding is correct, could you please clarify that the below note applies to both SPO and OneDrive sites?

> (If the user is already in your directory, you won't see the error, but they will be blocked if they attempt to access the site.)

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e6adf5-c322-b7f1-9359-1f9e0723374b
* Version Independent ID: 0071fb22-d32b-da3f-aec1-60772b341bd0
* Content: [Domain restrictions when sharing SharePoint & OneDrive content - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/restricted-domains-sharing?redirectSourcePath=%252fen-us%252farticle%252fRestricted-Domains-Sharing-in-O365-SharePoint-Online-and-OneDrive-for-Business-5d7589cd-0997-4a00-a2ba-2320ec49c4e9)
* Content Source: [SharePoint/SharePointOnline/restricted-domains-sharing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/restricted-domains-sharing.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
