### ISSUE TITLE
Google Forms now migrated

### ISSUE THREAD

**Issue by bharto** [MicrosoftDocs/OfficeDocs-SharePoint#4069]
Google Forms are now migrated to Microsoft Forms, documentation can be changed to reflect:

Please reach out to alias bharto if confirmation through MSFT internal documentation is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e276bebe-2aaa-5701-57da-59a2baa73c58
* Version Independent ID: 1405b814-f193-5950-1908-6d1bac65d004
* Content: [Overview: Migrate Google Workspace to Microsoft 365 with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-google-overview#google-drawings-forms-sites-and-maps)
* Content Source: [migration/mm-google-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-google-overview.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @bharto Brad, how are you?
I see that was added somewhat recently with a note 

> Google Forms are now supported.

Or do you mean to specify those will migrate to Microsoft Forms?

Thanks,

**Comment by bharto** [comment]
Ah this was corrected since submission. Please disregard!
