### ISSUE TITLE
Move the content of the Note-section to a new page?

### ISSUE THREAD

**Issue by JormaLinikko** [MicrosoftDocs/OfficeDocs-SharePoint#407]
Would it be better, if you would make a new page for the content in the Note-section? Perhaps making a page called Change your  site collection url and moving the contents of the Note-section there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@JormaLinikko Thank you for the suggestion

I am not sure what the article owner wants to do with the page organization but I will get this suggestion over to them for investigatoin. 

We always appricate suggestions for making the Docs better. 

I have made a note to request the owner of the article respond to you with any information about this suggestion that they have.

**Comment by kaarins** [comment]
@JormaLinikko , this is great feedback. The SharePoint admin center team is actually working to make it possible to change site URLs, and when the feature comes out, I will link to a new article about it! Thanks again!

**Comment by anthony-irl** [comment]
Do you know if there an ETA for the delivery of this feature?
