### ISSUE TITLE
Update rolling out section with year information

### ISSUE THREAD

**Issue by thewidup** [MicrosoftDocs/OfficeDocs-SharePoint#4071]
[Enter feedback here]
The page was updated on 9/23 and said it's rolling out and should be available to tenants in March/April but it does not indicate the calendar year.  Does that mean it was rolling out in March/Aprli of CY23 or CY24?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9aa1a91-e838-41c6-45cb-6a2a4dbf1a7a
* Version Independent ID: 5f5c1b99-126f-2a70-20c8-f00136927e31
* Content: [Microsoft Syntex - SharePoint Advanced Management overview - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/advanced-management)
* Content Source: [SharePoint/SharePointOnline/advanced-management.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/advanced-management.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@thewidup that's a leftover note. I'll submit an update to remove it.
