### ISSUE TITLE
HitHighlightedSummary missing tags

### ISSUE THREAD

**Issue by AlexFilipovici** [MicrosoftDocs/OfficeDocs-SharePoint#4072]
Since migrating to SharePoint Online, we've noticed that the **HitHighlightedSummary** property for the search results returned by the SharePoint search REST API is missing the special tags for highlighting the hits of the searched term in the summary (e.g. `<c0/>`,`<ddd/>`), but only for the list items (and not for the files).

If this intended, could you please document this change? If not intended, please check it with the development team - it's probably a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55be1fa6-d7e0-7ce7-bb0e-b68e6d7597db
* Version Independent ID: 6740381f-cfd1-3c64-59c4-2eb60b12dd3b
* Content: [Change how search results look by using result types and display templates - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-result-types-and-display-templates?source=recommendations)
* Content Source: [SharePoint/SharePointOnline/use-result-types-and-display-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-result-types-and-display-templates.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
