### ISSUE TITLE
Seamless Single Sign On configuration supported?

### ISSUE THREAD

**Issue by Niels-NL** [MicrosoftDocs/OfficeDocs-SharePoint#4073]
The documentation is not clear if a Seamless Single Sign On configuration is supported or not.
Would please so kind to clarify this.

With kind regards,
Niels

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17aec87c-a56c-91c0-b2d5-5f9f11322c1e
* Version Independent ID: 439abe40-cdab-e480-0df9-30aa183ef521
* Content: [Silently configure user accounts - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-silent-account-configuration)
* Content Source: [SharePoint/SharePointOnline/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Niels-NL How are you?
I did not test it myself however If I read the article it seems that it is, but, to understand better, is there any issue with the current instructions that you are facing?

**Comment by get-itips** [comment]
Closing with no answer but can be re-opened.
Thanks
