### ISSUE TITLE
DAG (Data Access Governance) in SPO admin center requires E5?

### ISSUE THREAD

**Issue by howardzhangmsft** [MicrosoftDocs/OfficeDocs-SharePoint#4077]
M365 global admin cannot see the Reports tab in Sharepoint online admin center, the tenant is Microsoft E3.
Please clarify what is needed to see the DAG report, if we don't have "
SharePoint advanced management plan" licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd05a015-115f-0e1d-e607-64a0c08a77a1
* Version Independent ID: 6ac538e0-2010-34db-7b06-d31272bfae28
* Content: [Data access governance reports for SharePoint sites - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/data-access-governance-reports)
* Content Source: [SharePoint/SharePointOnline/data-access-governance-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/data-access-governance-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MachelleTranMSFT
* Microsoft Alias: **mactra**

**Comment by howardzhangmsft** [comment]
Is E5 required to see the DAG?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
