### ISSUE TITLE
Organizational Assets Library - Public Display name (in Office) is Tenant name

### ISSUE THREAD

**Issue by Finklesdata** [MicrosoftDocs/OfficeDocs-SharePoint#4079]
Under step 6, this line is apparently incorrect: "The name publicly displayed for the library will be the name of the library on the SharePoint site."

The publicly displayed name for the library in Office is our Azure Tenant name. Note that our sharepoint library name does have a space 'ABC Templates'.

https://answers.microsoft.com/en-us/msoffice/forum/all/sharepoint-organizational-asset-library-public/967e19f7-3fae-4b80-84cb-5594a47bcb6f

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bacce83-65f6-b862-e413-09122aee356d
* Version Independent ID: 5c4e1169-1d5d-6e0d-d574-f3aaba0a5d92
* Content: [Create an organization assets library - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/organization-assets-library?source=docs)
* Content Source: [SharePoint/SharePointOnline/organization-assets-library.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/organization-assets-library.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
