### ISSUE TITLE
Script to Batch Provision Users - output stating count of users being provisioned not clear

### ISSUE THREAD

**Issue by MH-TD** [MicrosoftDocs/OfficeDocs-SharePoint#4082]
[Enter feedback here]
I have just run this script for 2400 users. The output displays 1/2400 up to 199/2400, pauses then again shows 1/2400 up to 199/2400 however this is confusing as it looks like the script is repeatedly running on the first 199. The script is actually running correct but the output doesn't show this.

I've adjusted the script to the following, using a new variable j to record the total users and leaving the variable i to record the current batch. Then two additional comments - Write-Host "Batch limit reached, requesting provision" and Write-Host "Completed OneDrive Provisioning for $j users"

$list = @()
#Count of number of users within 199 batch
$i = 0
#Count of current user within whole list
$j = 0

#Get licensed users
$users = Get-MsolUser -All | Where-Object { $_.islicensed -eq $true }
#total licensed users
$count = $users.count

foreach ($u in $users) {
    $i++
    $j++
    Write-Host "$j/$count"

    $upn = $u.userprincipalname
    $list += $upn

    if ($i -eq 199) {
        #We reached the limit
        Write-Host "Batch limit reached, requesting provision"
        Request-SPOPersonalSite -UserEmails $list -NoWait
        Start-Sleep -Milliseconds 655
        $list = @()
        $i = 0
    }
}

if ($i -gt 0) {
    Request-SPOPersonalSite -UserEmails $list -NoWait
}
Write-Host "Completed OneDrive Provisioning for $j users"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a44f106d-ea01-b0b3-a538-ffca3eeeb29f
* Version Independent ID: 074a92aa-3117-8795-c6ff-149cff16ca25
* Content: [Pre-provision OneDrive for users in your organization - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/pre-provision-accounts)
* Content Source: [SharePoint/SharePointOnline/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @MH-TD 
Thank you for your contribution, I tested it and I am proposing it through a pull request.
