### ISSUE TITLE
What is the upper limit for automatic container detection in the Stream Migration tool: 49,500 or 40,000?

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint#4088]
Hello,

This is feedback on the following 2 articles regarding Stream Classic Migration. 

1. https://learn.microsoft.com/en-us/stream/streamnew/understand-the-tool#rules--constraints
2. https://learn.microsoft.com/en-us/stream/streamnew/step-by-step-guide

I couldn't find a GitHub submission form at the bottom of those articles, so I'm posting it here, but if you have an appropriate repository, please direct me to it.

**1. https://learn.microsoft.com/en-us/stream/streamnew/understand-the-tool#rules--constraints**

This article states the MAX of containers auto-detected by the Stream Classic Migration Tool, but there is a mix of 49,500 and 40,000 in the same article. I think 40,000 is correct, but could you please correct it to the correct value?

 **Section of "Rules & constraints"**
 
<img width="446" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13634805/efeca091-12c1-48db-a601-22201fb3592e">

**Section of "Add Containers manually"**
<img width="448" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13634805/cf916874-623b-4318-ae01-9577d5ebf686">

**2. https://learn.microsoft.com/en-us/stream/streamnew/step-by-step-guide**

49,500 and 40,000 are also mixed as well.

<img width="365" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13634805/e29479d1-2274-436b-9cd9-e8aacc291f97">

<img width="368" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/13634805/b1460c76-1884-45d2-a443-4f873060ab76">

**Comment by get-itips** [comment]
Hello @kefujino 
How are you?
Stream articles are not in a public repository AFAIK so it is not possible as you could identify to open issues against them.
I'll try to pass this feedback on. @tiburd
