### ISSUE TITLE
Authoring 'generic' links to OneDrive tabs

### ISSUE THREAD

**Issue by Rossolson** [MicrosoftDocs/OfficeDocs-SharePoint#4090]
When creating documentation for OneDrive, it would be helpful to have generic links that will send a reader to their own OneDrive and the associated tabs. While linking to the OneDrive home page can be done through:

> https://<tenant name>-my.sharepoint.com/

...it would be nice to link to the other tabs such as 'My Files' and 'Favorites'. The onedrive.aspx file takes a 'view' query string parameter such as "view=0" or view="21" for those two tabs respectively. It would be nice if I could simply have the query strings forwarded to the final URL so that...

> https://<tenant name>-my.sharepoint.com/<user principal name>/?view=0

...resolves to...

> https://<tenant name>-my.sharepoint.com/<user principal name>/_layouts/15/onedrive.aspx?&view=0

Perhaps there is already an existing URL for linking to the tabs within OneDrive. Having those documented here would be helpful also.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b18e0e4-4198-070c-54fc-7d36eae8438f
* Version Independent ID: b8b5c3ba-cdff-cc94-9140-7d39a6ee463b
* Content: [View the list of OneDrive URLs for users in your organization - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/list-onedrive-urls)
* Content Source: [SharePoint/SharePointOnline/list-onedrive-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/list-onedrive-urls.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Rossolson** [comment]
I'm not sure how this would be resolved in a single tenant. It would be a platform-level feature. There is nothing to resolve, nor anything to resolve ASAP. It is simply a request for a non-user-specific URL to a generic resource, that resolves to a specific resource based on the user's own files.
