### ISSUE TITLE
Content Type loss warning

### ISSUE THREAD

**Issue by Baldgyt** [MicrosoftDocs/OfficeDocs-SharePoint#4091]
Ths article should include warnings about loss of built in office 365 doc types (Excel, Word, PowerPoint) which seem to disappear as soon as you add a content type to a library. Add one, lose 4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96aaa197-d69d-0cc1-aa52-7c1519442fc2
* Version Independent ID: a60ef9d8-b49f-c983-e4b6-0c30b388116c
* Content: [Create or customize a content type - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/create-customize-content-type)
* Content Source: [SharePoint/SharePointOnline/create-customize-content-type.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/create-customize-content-type.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Baldgyt how are you?
I tested this, while it is true that after you add a new content type to the library the word, excel and ppt options will not be in the new menu anymore, you can add those to the New button again by editing the new menu.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
