### ISSUE TITLE
Enable File Requests in SharePoint or OneDrive Missing Instruction

### ISSUE THREAD

**Issue by JGonzales55** [MicrosoftDocs/OfficeDocs-SharePoint#4092]
The Enable File Requests in SharePoint or OneDrive instructions do not include a note that if "Allow only users in specific security groups to share externally" is checkmarked and a group is set up the feature will not work even if the user trying to set up File Requests is in the allowed security group. We just ran in to this on our tenant and it took awhile to figure out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb80c7f-b87a-6910-b145-1261ce7be4fc
* Version Independent ID: 6085e0fb-1eb5-3a33-9771-11a4b4c6bee2
* Content: [Enable File Requests in SharePoint or OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/enable-file-requests)
* Content Source: [SharePoint/SharePointOnline/enable-file-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/enable-file-requests.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Thanks for your feedback
