### ISSUE TITLE
SPMT v4.1.125.5 bug on calculated column with non english site - error migration

### ISSUE THREAD

**Issue by paoIpao** [MicrosoftDocs/OfficeDocs-SharePoint#4098]
Steps to repro the problems:
-create a sharepoint on-prem site with italian language
-from a browser (with italian language) add a list with a calculated column with a formula like =SINISTRA(Title;3)
-migrate with SPMT site to a sharepoint online site (new site created by default, italian language).
-error in reports of migration, no content migration because failed on field create/update with calculated column (seems the code send the formula in italian language! and sharepoint respond with invalid because expect =left(title,3).

To resolve bug fix:
-read schemaxml of the calculated field that contains formula in english and fix the bug on spmt migration code.

Temporary woraround:
-after first migration with no content read StructureFailureReport.csv and check all fields go to error (are all calculated field..)
-go to the list on shp online and add manually calculated field (and copy formula, with same internal name and rename the field if description is different) ; alternative: read schemaxml with powershell of the field (remove sourceId and generate a new id with newguid() .. ) and use as schema xml to create the field on shp online list with pnp or similar using Add-PnPFieldFromXml .
-relaunch migration and when works fine.

Thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by paoIpao** [comment]
Thanks, open support case and send log error to support engineer to investigation on bug.
