### ISSUE TITLE
SPMT v4.1.125.5 bug if installed on non-english windows server

### ISSUE THREAD

**Issue by paoIpao** [MicrosoftDocs/OfficeDocs-SharePoint#4099]
SPMT works fine only if installed on windows server with language set into control panel - region in english.

if installed on a windows server with language set for example in italian , when copy a site with italian language from on-prem to shp online all number are in wrong format and migrate not correctly (decimal period and comma are inverted.. ). so for example 850,47 is wrong migrate as 85.047 .
No errore reported but the data migration are invalid!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
