### ISSUE TITLE
Timer Job Differences for SP2016

### ISSUE THREAD

**Issue by papercrane10** [MicrosoftDocs/OfficeDocs-SharePoint#41]
Hello, what are the differences between the two timer jobs below? What is the difference between database and application? 

User Profile service application - Per database User Profile to SharePoint full synchronization 

Synchronizes user information from the User Profile application to SharePoint users and from SharePoint site memberships to the User Profile application for a database.

User Profile service application - User Profile to SharePoint full synchronization 
Synchronizes user information from the User Profile service application to SharePoint users and synchronizes site memberships from SharePoint to the User Profile service application. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93814f2-26ac-7e20-9f8c-c69a7a131ddc
* Version Independent ID: f5cd34ba-f0bc-4fe4-9477-5026eb3a447b
* Content: [Timer job reference for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/technical-reference/timer-job-reference-for-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/technical-reference/timer-job-reference-for-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/timer-job-reference-for-sharepoint-server-2016.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
The per database job (UserProfile_WSSProfilePerDbSyncJob) is not enabled for on-perm farms (the *job* is enabled, but it has a value check that prevents it's full execution on-prem). It is used in SPO only.

**Comment by papercrane10** [comment]
So I ran Get-SPTimerJob | Select Name, IsServiceJob to get a list of the jobs that have the $false value. However, I see a discrepancy between timer jobs from the Get-SPTimerJob and the list of Timer Jobs in SharePoint GUI. I can't seem to locate  
User Profile Service Application - User Profile to SharePoint Full Synchronization as a timer job with powershell. Is there another command I am suppose to run that I do not know of or is it under a different name?

**Comment by tseward** [comment]
You probably want JobDisplayName.

    Get-SPTimerJob | ?{$_.Name -match 'Profile'} | select name,jobdisplayname
