### ISSUE TITLE
Menu for opening Sharepoint from a Team's channel is out of date. 

### ISSUE THREAD

**Issue by jochilds-ms** [MicrosoftDocs/OfficeDocs-SharePoint#4100]
The screenshot used to display opening Sharepoint from a Team's channel is out of date. 

This is now done from ellipses a row lower:

<img width="753" alt="Open in SPO" src="https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/72813926/2594a9e9-2c8c-4f6e-9e03-8e730c67d179">

I've had a customer request for this be updated as they are directly users to this guidance page. 

https://learn.microsoft.com/en-us/sharepoint/manage-teams-sharepoint-experiences#how-to-identify-and-navigate-between-sharepoint-and-teams

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jochilds-ms** [comment]
Hi @scanum, please can you clarify how we can get a request for this documentation to be updated raised? Many thanks,
