### ISSUE TITLE
pre-provisioning script is broken

### ISSUE THREAD

**Issue by drkmccy** [MicrosoftDocs/OfficeDocs-SharePoint#4102]
The script doesnt work anymore, getting this:

_Get-MgUser : Insufficient privileges to complete the operation_

**Comment by drkmccy** [comment]
I've reverted back to the old script using connect-msolservice and that works so either it needs reverting or fixing.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
