### ISSUE TITLE
Incorrect working folder details

### ISSUE THREAD

**Issue by IT-RD** [MicrosoftDocs/OfficeDocs-SharePoint#4104]
Table in [Advanced ](https://learn.microsoft.com/en-us/sharepointmigration/spmt-settings#advanced) section shows the wrong path.

Currently:
> Note: By default, the working folder is %appdata%\Microsoft\MigrationTool. 

The correct path to the MigrationTool folder should be:  %APPDATA%\Microsoft\SPMigration\Logs\Migration\MigrationTool, however it is unclear what "**working folder**" is meant to signify.

If temp files for the migration job, I believe this should be %APPDATA%\Microsoft\SPMigration\Logs\Migration as this contains both MigrationTool and MigrationToolStorage "working" folders.

A breakdown of all paths and their specific migration related contents could be more valuable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dad86450-d9ac-4cc4-fc75-63f8b285c298
* Version Independent ID: d1e8c85a-b365-78c0-be1a-5a03ee082491
* Content: [SharePoint Migration Tool settings - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/spmt-settings)
* Content Source: [migration/SPMT-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/SPMT-settings.md)
* Service: **microsoft-365-migration**
* GitHub Login: @MachelleTranMSFT
* Microsoft Alias: **mactra**

**Comment by get-itips** [comment]
Hello @IT-RD 
The folder that you are talking about here is the Logs folder for **Migration Manager**

It's documented here

https://learn.microsoft.com/en-us/sharepointmigration/mm-faqs

>Question: Where are local Migration Manager logs stored?
Answer: The logs are stored here: C:\Users\<Username>\AppData\Roaming\Microsoft\SPMigration.
