### ISSUE TITLE
Wording used in last sentence on page.

### ISSUE THREAD

**Issue by iragusa67** [MicrosoftDocs/OfficeDocs-SharePoint#4107]
In the last sentence of this document: "Enable Known Folder Move Group Policy. Known folders move to OneDrive and will merge with the existing Desktop, Documents, and Pictures folders, which contain all the file share content that you moved in the first step."  
I recommend changing the wording from "that you moved in the first step" to "that you copied in the first step".  Since we specify that the first step needs to be a copy and not a move the last step should just re-emphasize that point rather than confuse the reader and potentially motivate the reader to perform a move instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd9bb99f-256c-f719-8d64-5c95b1a97d15
* Version Independent ID: 18673c5f-127d-1f38-3d6f-575434ab516a
* Content: [Redirect and move Windows known folders to OneDrive - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/redirect-known-folders)
* Content Source: [SharePoint/SharePointOnline/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by HansBrender** [comment]
It is not a copy. it is a move  of a  "known" folder below "OneDrive"
You do not have the files on his origin palce anymore

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
