### ISSUE TITLE
What counts as an indexed item from onprem

### ISSUE THREAD

**Issue by bestcomy-duplicate** [MicrosoftDocs/OfficeDocs-SharePoint#412]
Limit "Maximum number of on-premises items indexed in Office 365 "
•	What is the max or hard limit of what is indexed?
•	What counts as an indexed item from onprem? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171ee42a-95a9-6543-dd99-696ba7025cd0
* Version Independent ID: a3b3b40f-b808-7ac6-b420-a9b7bb0361fb
* Content: [Search limits for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/search-limits)
* Content Source: [SharePoint/SharePointOnline/search-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/search-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by AndreaBarr** [comment]
@bestcomy-duplicate Thank you for this inquiry

I am not sure on the answers for these two on-premises questions. Let me get this over to the SharePoint team for investigation and clerification. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@bestcomy-duplicate It is outlined in the document:

"This quota is by default limited upwards to 20 million items. To increase the number of items that can be indexed beyond 20 million items, contact Microsoft Support."

There is no hard cap per the above but you do need to contact support if you're going above 20 million indexed items. Indexed items count for any crawled item (document, list item, pages, people).

**Comment by tseward** [comment]
@scanum please close this.
