### ISSUE TITLE
Unable to create sites names starting with "com".

### ISSUE THREAD

**Issue by pavan2920** [MicrosoftDocs/OfficeDocs-SharePoint#413]
Hi Team, 

We are not able to create sites with Names "com" followed with single digit numbers. We have tried creating sites from Admin Center and Modern UI. 

Could you please help us out in understanding and solving issue. 

Thanks & Regards, 
Pavan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0419db4c-9918-fcbe-53b3-4aca315e7703
* Version Independent ID: 0eca18cd-d073-8a6c-47ba-3e3330d63167
* Content: [Create a site collection](https://docs.microsoft.com/en-us/sharepoint/create-site-collection)
* Content Source: [SharePoint/SharePointOnline/create-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@pavan2920 Thank you for this inquiry

I am not sure why your experiancing this issue with the naming of your sites. Let me get this over to the SharePoint team for investigatoin. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@pavan2920 "COM1", "COM2" and so forth are reserved names in Windows. While you can create the site, they will 404. See https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#naming-conventions.

"Do not use the following reserved names for the name of a file:

CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9."

**Comment by tseward** [comment]
@scanum please close this.
