### ISSUE TITLE
Does Not Recognize

### ISSUE THREAD

**Issue by jsmileyb** [MicrosoftDocs/OfficeDocs-SharePoint#414]
I'm attempting to manage the storage quota on a Teams site, but I'm receiving an error "Get-SPOSite : A parameter cannot be found that matches parameter name 'Identity'."

Even after updating my SPO Management Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c744272-76d3-f60a-9d06-570d36ffb529
* Version Independent ID: 24208c34-c0f1-4ab0-5d92-9c3997211729
* Content: [Manage team sites and communication sites by using PowerShell](https://docs.microsoft.com/en-us/sharepoint/manage-team-and-communication-sites-in-powershell?redirectSourcePath=%252fen-us%252farticle%252fmanage-team-sites-and-communication-sites-by-using-powershell-52ecc2ab-88c3-486e-b8ff-ef6a968ccd87)
* Content Source: [SharePoint/SharePointOnline/manage-team-and-communication-sites-in-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-team-and-communication-sites-in-powershell.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@jsmileyb Thank you for this inquiry

I am not sure about this storage quota issue you are experiancing. I want to make sure you get the appropriate help with this issue. I think the best step from here is to get you over to Support where they have more resources than we have here to help dig in and figure out a resolution for this issue. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
