### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pkotov87** [MicrosoftDocs/OfficeDocs-SharePoint#416]
Software boundaries and limits for SharePoint Server 2019 fills.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937a1f68-4cf6-f243-b219-dc154bae6714
* Version Independent ID: 7f3050b3-7a3d-d467-64cc-bc0edbe1521e
* Content: [System requirements for SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/system-requirements-for-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/install/system-requirements-for-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/system-requirements-for-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@pkotov87, thank you for your feedback. Unfortunately, could you be more specific of the exact request or change you like to make?

**Comment by sassdawe** [comment]
@Techwriter40, I think @pkotov87 is missing the 2019 version of the "software-boundaries-and-limits-0.md" file. I was looking for it too.

Btw, was your file naming convention documented somewhere?
I see .md file without numbers at the end and also with "-0", "-2016" and "-2019".
I'd be happy to help out validating the file names and the titles of the articles.

**Comment by Techwriter40** [comment]
there is not a separate 2019 version as there were minimal changes. What applies for 2016 also is valid for 2019, hence contained in one article title system requirements for SharePoint Servers 2016 and 2019.

**Comment by pkotov87** [comment]
Exactly what @sassdawe said, checkbox was only for 2016. Now it stands for both. Thank you!

**Comment by Techwriter40** [comment]
@pkotov87, your welcome. since issue is resolved, I will close comment.
