### ISSUE TITLE
Intructions in wrong part of Table of contents

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#42]
This page is for SP 2013 but it shows up under the SP 2016 heading, is there another page for 2016, or does this apply to both version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757daa4f-85eb-2b0e-094a-f01b9ed3d874
* Version Independent ID: acfb92cf-1d51-d6a7-bebc-9c145f5b7710
* Content: [Install a software update for SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Yeah I see what's happening. The article path in GitHub is identical. @Techwriter40 how do we go about fixing issues with this where there is a significant distinction for the same process? IMO we should have a completely separate page for SharePoint 2016.

**Comment by kenwith** [comment]
I just looked into this and it looks like this was resolved. If it is not please re-open as necessary. As Kirk mentioned this was likely an issue with the migration from TechNet to the new open source GitHub system. Thank you for taking the time to report it. Very much appreciated!
