### ISSUE TITLE
Direction of the trust

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#423]
Can the trust be applied in only one direction (SharePoint 2016 farm receiving results from SharePoint 2013 farm) or in both the directions (SharePoint 2016 farm receiving results from SharePoint 2013 farm and vice versa)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5028b4-a194-498e-326d-1fdd56eb97bc
* Version Independent ID: a480b9b7-0f95-2b00-5d86-e6f16d7cb4bf
* Content: [Configure trust for search between two SharePoint Server farms](https://docs.microsoft.com/en-us/SharePoint/search/configure-trust-for-search-between-two-sharepoint-server-farms)
* Content Source: [SharePoint/SharePointServer/search/configure-trust-for-search-between-two-sharepoint-server-farms.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/configure-trust-for-search-between-two-sharepoint-server-farms.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
The trust goes from N to N (2016 -> 2016) or N to N-1 (2016 -> 2013). However results can be retrieved on any farm for any other farm part of that trust. Does that help?

**Comment by AndreaBarr** [comment]
@LuigiBruno Did what Trevor respond with resolve your issue?

**Comment by tseward** [comment]
@scanum I think we can close this one.
