### ISSUE TITLE
Incorrect definition 

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/OfficeDocs-SharePoint#424]
This policy will not take effect if you've enabled "Prompt users to move Windows known folders to OneDrive" or "Silently redirect Windows known folders to OneDrive."

should refer to the policy Silently move Windows known folders to OneDrive

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-gb/onedrive/use-group-policy#KFMOptInNoWizard)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@danjpadgett Thank you for pointing this out

I will get this information for OneDrive over to the SharePoint team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@danjpadgett Sorry, which policy won't take effect? You linked to the anchor 'Silently move Windows known folders to OneDrive' in that article.

**Comment by danjpadgett** [comment]
@tseward - it appears the policy name of 'Silently redirect Windows known folders to OneDrive' has changed to 'Silently move Windows known folders to OneDrive', therefore the wording in the section below needs to be updated:

If you enable this setting, users won't be prompted with the "Set up protection of important folders" window, and the "Start protection" command will be disabled. If the user has already moved their known folders, the files in those folders will remain in OneDrive. This policy will not take effect if you've enabled "Prompt users to move Windows known folders to OneDrive" or "Silently redirect Windows known folders to OneDrive."

see - https://docs.microsoft.com/en-us/onedrive/use-group-policy#silently-move-windows-known-folders-to-onedrive
