### ISSUE TITLE
Mentioning MAC OS in a windows article

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-SharePoint#427]
Conditional access is not supported for MacOS. Beside the fact that no Mac support has just set back our argument with security. This is a windows article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync client for Windows](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@bakerm00 Thank you for this feedback

I will get this Mac OS information over to the SharePoint writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by nenonix** [comment]
@bakerm00  Thank you for taking time to improve the content. I have submitted a change that removes the reference you refer to.
