### ISSUE TITLE
Is managing AppFabric service via services console is safe ?

### ISSUE THREAD

**Issue by UmrG** [MicrosoftDocs/OfficeDocs-SharePoint#429]
There is a number of articles from knows MVPs and some TechNet articles suggest not to manage AppFabric service via services.msc console, this can leave your farm in unmanageable state and might have to rebuild the farm. This is the only article I find that is suggesting to do that. Please review. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59fa2ba1-01a4-d787-e7d8-7734686c55c8
* Version Independent ID: dc2de12e-3433-0f4f-dee3-e42d092d6d66
* Content: [One of the cache hosts in the cluster is down (SharePoint Server)](https://docs.microsoft.com/en-us/sharepoint/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down)
* Content Source: [SharePoint/SharePointServer/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/one-of-the-cache-hosts-in-the-cluster-is-down.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by UmrG** [comment]
https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service
"Do not administer the AppFabric Caching Service from the Services window in Administrative Tools in Control Panel."

**Comment by tseward** [comment]
This is a health analyzer rule and would require a product change to be fixed.

**Comment by AndreaBarr** [comment]
@UmrG Did Trevor's information resolve this issue?

**Comment by tseward** [comment]
@scanum please close this one.

@UmrG if you'd like to see a product change, I'd recommend posting at https://sharepoint.uservoice.com/forums/330318-sharepoint-administration where it will get the attention of the engineers.
