### ISSUE TITLE
Sharepoint MIgration Tool doestn do anything

### ISSUE THREAD

**Issue by LoniBoy** [MicrosoftDocs/OfficeDocs-SharePoint#43]
i have a little problem with my sharepoint migration.
i want to migrate from on-prem server 2013 to SharePoint Online(O365).
Now i used the Migration tool with no success.
The tool everytime runs for half an hour but nothing happens.

In the error-log i found this:

https://thisis.yoursite.com/sites/spielwiese/Lists/Demoliste/1_.000,"https://newcotec.sharepoint.com/sites/Spielwiese/Lists/Demoliste/1_.000","1_.000",".000","0","Item","Failed","SERVER FAILURE","Errors or timeout for Server Processing the file:Not all the items in the package have been migrated","0x01710009","7cf0e3fb-7f45-4c3c-9a5d-49cfffb71722","7cf0e3fb-7f45-4c3c-9a5d-49cfffb71722","N/A","N/A","3","2486bd00-6668-483f-952b-3bf86e3246be","TESTCLIENT01"
![error](https://user-images.githubusercontent.com/38783307/39357080-033bf936-4a12-11e8-8213-6fee0cd65f32.JPG)

**Comment by wenhua-helen** [comment]
@LoniBoy  
Please contact Migration feature crew <migration_team@microsoft.com> for issue investigation. 
Remember to share everything under C:\Users\%user name%\AppData\Roaming\Microsoft\MigrationTool\admin@XXXX.onmicrosoft.com\WF_XXXXX folder when you contact Migration feature crew migration_team@microsoft.com. 
We would like to work with you to address the issue encountered in your migration.

Migration feature crew team
