### ISSUE TITLE
Support On-Premise syncing using the new client

### ISSUE THREAD

**Issue by thshdw** [MicrosoftDocs/OfficeDocs-SharePoint#431]
We cannot migrate off the Groove.exe client until we can sync with our On Premise libraries. Will syncing with On Premise be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1285fcf0-476f-b431-c8f0-ae395c31418e
* Version Independent ID: a5679b64-68bf-42fb-98f0-51d1625a102e
* Content: [Transition from the previous OneDrive for Business sync client](https://docs.microsoft.com/en-us/onedrive/transition-from-previous-sync-client?redirectSourcePath=%252farticle%252f4100df3a-0c96-464f-b0a8-c20de34da6fa)
* Content Source: [OneDrive/transition-from-previous-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/transition-from-previous-sync-client.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by thshdw** [comment]
Maybe change "On-premises locations in SharePoint Server 2016 or earlier." to something like "Syncing using the new client only available in SharePoint Server 2019, prior versions not supported." 

"The following library types are not yet supported" infers that 2016 maybe supported in the future but this is not the case so for me its a bit misleading.

**Comment by thshdw** [comment]
Maybe someone can update this https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/10005837-sharepoint-on-premises-support to let the users that wanted this feature that its only going to be supported in Sharepoint Server 2019

**Comment by tseward** [comment]
@Techwriter40 can you address the uservoice?

**Comment by tseward** [comment]
@scanum Go ahead and close this one.
