### ISSUE TITLE
SNAC From Section 1.4 No Longer Available

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#433]
SNAC from section 1.4 of this article (https://support.microsoft.com/en-us/hotfix/kbhotfix?kbnum=3098860&kbln=en-us) is no longer available. What is the alternative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59acdf52-b8f5-f140-317e-00747b5d80d5
* Version Independent ID: ba2e186b-c2b6-4e09-208e-1b622ebcfed1
* Content: [Enable TLS and SSL support in SharePoint 2013](https://docs.microsoft.com/en-in/SharePoint/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013#14---install-sql-server-2008-r2-native-client-update-for-tls-12-support)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
I sent this to Troy, PM for SharePoint who should give me an answer.

**Comment by Techwriter40** [comment]
I sent this to Troy, PM for SharePoint who should give me an answer.

**Comment by sbinnasa** [comment]
I am very interested in the outcome of this issue.  I have SharePoint servers on which I need to turn TLS 1.0 off and I can't update the 2008 R2 SNAC past its current 10.51.2500.0.

**Comment by tseward** [comment]
Updated the article. SNAC is available from https://www.microsoft.com/en-us/download/details.aspx?id=57606.

**Comment by Techwriter40** [comment]
2013 and 2010 versions of this article have been updated to include the correct download link.
