### ISSUE TITLE
Contradiction about Excel client

### ISSUE THREAD

**Issue by ConradIlgmann** [MicrosoftDocs/OfficeDocs-SharePoint#434]
Here: 

If anyone uses Excel (the client application) to access the workbook, co-authoring in Excel Web App will be disabled for that workbook while it is open in the client application.

And in https://support.office.com/en-us/article/excel-file-is-locked-for-editing-by-another-user-6fa93887-2c2c-45f0-abcc-31b04aed68b3: 

Versions of Excel that support co-authoring:
Excel for Office 365*
Excel for Office 365 for Mac*
Excel Online
Excel for Android
Excel for iOS
Excel Mobile

What is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b626929-198d-3be9-d202-df1c80699327
* Version Independent ID: 7bed15b6-1a2d-fff5-c62e-3c07308882c6
* Content: [Overview of co-authoring in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/governance/co-authoring-overview#understanding-the-end-user-experience-of-co-authoring-in-sharepoint-server-and-sharepoint-online)
* Content Source: [SharePoint/SharePointServer/governance/co-authoring-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/co-authoring-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
I think that the difference, for Excel, is for SharePoint Server and not for SharePoint Online. https://support.office.com/en-us/article/collaborate-on-excel-workbooks-at-the-same-time-with-co-authoring-7152aa8b-b791-414c-a3bb-3024e46fb104 has the following note, "Please note that SharePoint On-Premises sites (sites that are not hosted by Microsoft), do not support co-authoring."

**Comment by tomresing** [comment]
It is possible in SharePoint Online, and OneDrive through Office 365, with the newest client.

**Comment by itthing** [comment]
My experience with a file hosted in Teams/SharePoint online, is that Excel does NOT consistently support coauthoring.

**Comment by tomresing** [comment]
@itthing, Excel must be updated to the latest version available with an Office 365 Subscription to support full co-authoring. https://support.office.com/article/what-s-the-difference-between-office-365-and-office-2019-ed447ebf-6060-46f9-9e90-a239bd27eb96
