### ISSUE TITLE
red x warnings show up when you put ignored file extensions in the one drive folder.

### ISSUE THREAD

**Issue by rolandh** [MicrosoftDocs/OfficeDocs-SharePoint#438]
I don't want to block file types, I just want to ignore certain files in certain folders. If I block file types I get annoying red Xs in one drive and "sync problems". I know they are ignored, I put the ignore filter in, why does it feel the need  to tell me every 3 seconds that a file has been ignored?

Why can't I just tell one drive to ignore all files in a certain folder and to not warn me constantly about it?

I need the files in the folder as the local application requires them, I just don't want them synced to one drive!

SO FRUSTRATING

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@rolandh Thank you for this feedback

I am not sure if there is a feature for this already. Let me get this over to the SharePoint team for investigation. 

@tseward Could you look into this one for me?

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@rolandh I would suggest putting this on the OneDrive Uservoice -https://onedrive.uservoice.com/forums/913534

**Comment by Convincible** [comment]
Agreed, there is no point in this feature if what it achieves is to give all users with a blocked file type a blocking error. The blocked file type should simply be ignored/not sync.

**Comment by tseward** [comment]
@scanum go ahead and close this.

**Comment by rolandh** [comment]
Close it?

So this will not be implemented? User voice seems go be ignored and a waste of time. There items there regarding this problem (lack of a gitignore style ignore file) for 8+ years with 1000s of votes.

**Comment by kaarins** [comment]
@rolandh , I checked with the team and they are aware of this issue and are investigating a feature change. I don't have a release date to share with you yet, but I look forward to updating this article with new info when the feature improvement is released.

**Comment by Jonny2026** [comment]
https://onedrive.uservoice.com/forums/913522-onedrive-on-windows/suggestions/38634169-do-not-show-error-messages-for-excluded-filetypes
