### ISSUE TITLE
Can't extend SharePoint 2019 web application

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint#440]
The Contribute group of the ribbon in Sharepoint 2019 is all greyed out.
 No way to extend, new or delete web application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0557a7c7-64a6-98c4-ee3d-ed7b1deacccf
* Version Independent ID: 93057560-a33e-08a3-0a24-2bb484f4aa34
* Content: [Extend claims-based web applications in SharePoint](https://docs.microsoft.com/en-us/SharePoint/administration/extend-a-claims-based-web-application)
* Content Source: [SharePoint/SharePointServer/administration/extend-a-claims-based-web-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/extend-a-claims-based-web-application.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
This would mean you're either not a local administrator on the SharePoint server(s) or you're not running IE as Admin when browsing CA from the SharePoint server.

**Comment by tseward** [comment]
@scanum go ahead and close this one as it is a support issue.
