### ISSUE TITLE
Text Layout change

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/OfficeDocs-SharePoint#444]
Please move the section under "Check if users already have the OneDrive sync client" to a separate purple "Note" box to make it more noticeable? ... "Office is installed per machine, whereas OneDrive needs to be installed per user. If you plan on deploying Office to your organization, you will need to deploy OneDrive.exe separately for additional users on individual machines."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-us/OneDrive/deploy-on-windows)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@Skatterbrainz Thank you for this feedback

I will get these suggestions over to the SharePoint team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by scanum** [comment]
@Skatterbrainz  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedcosbot close

**Comment by Skatterbrainz** [comment]
Thank you!  Sorry I'm slow to reply.
