### ISSUE TITLE
Table: Sample navigation term set Makes no Sense

### ISSUE THREAD

**Issue by GodTigga** [MicrosoftDocs/OfficeDocs-SharePoint#445]
Products is a top level item. Cameras, Film and Digital fall under products so that would make them level 2 items. However in the table "Film and Digital" are shown as Level 3 Items. How can they be level 3 items if they fall under "Products" & not "Cameras"...

If this is a mistake should we really be reading any of this information? How many other mistakes like this are all over the place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62087ee5-ca4b-4b84-19f8-885155be70d9
* Version Independent ID: 4f3683d8-e961-ba9b-038c-74cf3f09f4a1
* Content: [Plan navigation term sets in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/plan-navigation-term-sets)
* Content Source: [SharePoint/SharePointServer/administration/plan-navigation-term-sets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-navigation-term-sets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@AndreaBarr

**Comment by tseward** [comment]
@scanum go ahead and close.
