### ISSUE TITLE
SharePoint 2019 Farm Configuration Warning

### ISSUE THREAD

**Issue by krishnachaluvadi** [MicrosoftDocs/OfficeDocs-SharePoint#446]
Hi, I used PowerShell to configure SharePoint farm, during "Provisioning Central Administration" site, I received below warning. Is it going to impact SharePoint 2019 functionality? What is the fix?
![image](https://user-images.githubusercontent.com/10298191/49092920-1554d300-f231-11e8-8193-384136d5585f.png)

Regards,
Krishna.

**Comment by tseward** [comment]
@scanum go ahead and close this as it is an issue that needs to be addressed via support forums.
