### ISSUE TITLE
Recommended limit for document library size

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#448]
Is there any recommended limit for the size (not the number of items) of a SharePoint document library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
You will follow the content database size limits in this case. There is no defined limit on a per-library basis for size.

@AndreaBarr

**Comment by tseward** [comment]
@scanum go ahead and close this.
