### ISSUE TITLE
Model applicability to SP 2019

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#449]
The Note states that the models from 2013 apply to 2016, but what about 2019. I assume that still apply, can you please confirm and update the Note above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d9ca21c-546c-0d36-2dd7-026f6b06f0c4
* Version Independent ID: 74cffa3d-349a-394f-2156-ff4720598414
* Content: [SharePoint Server design samples Corporate portal and extranet sites](https://docs.microsoft.com/en-us/sharepoint/administration/corporate-portal-and-extranet-sites-design-samples)
* Content Source: [SharePoint/SharePointServer/administration/corporate-portal-and-extranet-sites-design-samples.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/corporate-portal-and-extranet-sites-design-samples.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
DeanGross, yes, this applies to 2019 as well, it should be noted in the Applies To section of the article.
