### ISSUE TITLE
Redundant space in the "**" characters 

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/OfficeDocs-SharePoint#45]
There is a redundant space between the bold character which makes them appear appear next to the text.
**Note**
I believe that these three articles aren't the only ones with this type of issue would it be possible to check/fix all the articles affected with this issue ?

**Repro steps:**
1. Go to 
https://review.docs.microsoft.com/en-us/SharePoint/technical-reference/technical-reference?branch=live-sxs
https://review.docs.microsoft.com/en-us/SharePoint/administration/demonstrate-profile-synchronization?branch=live-sxs
https://docs.microsoft.com/en-us/SharePoint/administration/configure-intranet-and-team-sites?branch=live-sxs
2. See the "**" characters

**Actual results:**
" ** " characters are visible
**Expected results:**
" ** " should not be visible 

**GH articles:**
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/blob/live/SharePoint/SharePointServer/technical-reference/technical-reference.md
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr/blob/live/SharePoint/SharePointServer/administration/demonstrate-profile-synchronization.md
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-intranet-and-team-sites.md

![error](https://user-images.githubusercontent.com/16706698/39364750-47639d5e-4a2f-11e8-9d04-08ca3833a57b.png)

**Comment by MikePlumleyMSFT** [comment]
Fixed.
