### ISSUE TITLE
Upon deleting a site collection Is it possible to redirect user to other url ? 

### ISSUE THREAD

**Issue by pavan2920** [MicrosoftDocs/OfficeDocs-SharePoint#450]
Hi, 

From modern page if we delete a site collection is it possible to redirect user to other page ? 

Thanks,
Pavan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bd11d3-f2a4-2811-09bd-449c3c3607da
* Version Independent ID: 2f47da99-02e6-3357-ed41-b28bd5190907
* Content: [Delete a site collection](https://docs.microsoft.com/en-us/sharepoint/delete-site-collection)
* Content Source: [SharePoint/SharePointOnline/delete-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delete-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@scanum go ahead and close.
