### ISSUE TITLE
Deprecated feature: Machine Translations (and Variations)

### ISSUE THREAD

**Issue by kirankakanur** [MicrosoftDocs/OfficeDocs-SharePoint#451]
It says "Machine Translations (and Variations)" is deprecated. 

Question - Are Variations entirely deprecated or is it just with using Machine Translations to support Variations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@tseward I have requested a review so we can merge your changes
