### ISSUE TITLE
Where are the new items?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#454]
Nothing new has been added in a long time. When can we expect to get some more new content.
Also, please add dates to each feature so that we can easily tell what the newest items are. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f0e99c-724d-9fc3-6b8b-bda185f92c19
* Version Independent ID: d38a6ff9-e4cd-5776-b152-9694fcafbee1
* Content: [What's new in the SharePoint admin center](https://docs.microsoft.com/en-US/sharepoint/what-s-new-in-admin-center)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this inquiry

I will get this inquiry over to the SharePoint writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward Could you please investigate this?

**Comment by tseward** [comment]
@AndreaBarr this one should belong to the individual(s) within the PG who manages the release notes.

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by kaarins** [comment]
This article will now list the features that are released each month (if any are released that month). Unfortunately, the article won't be able to specify exactly which features are available at a specific point in time as features roll out to Targeted Release and Standard Release. The product team is working on ways to bring visibility to this in the UI.
