### ISSUE TITLE
Indicate how to assign this role in Office 365

### ISSUE THREAD

**Issue by missilelaunchr** [MicrosoftDocs/OfficeDocs-SharePoint#455]
The basic "how" is often missing from instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7461c2ef-3439-2c86-4dde-8992b62bf9a7
* Version Independent ID: faa4e3aa-8ec4-f1f1-d4bd-4058999545f3
* Content: [About the SharePoint admin role in Office 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-admin-role)
* Content Source: [SharePoint/SharePointOnline/sharepoint-admin-role.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-admin-role.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@missilelaunchr thank you for this feedback! I'm moving the link to "Assign admin roles" to the top of the article so it isn't buried in the "See also" section. :)
