### ISSUE TITLE
Effect of enabling sharing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#456]
One of my customers recently enabled external sharing at the tenant level, and almost all of the existing sites are now showing "This site can be shared with new and existing external users who sign in". We were expecting that each site would have remained "This site can’t be shared with external users" until we specifically change the setting on a site by site basis.
This behavior is not clearly documented above. Not all of the sites were enabled. How is this supposed to work, please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this inquiry

I will get this request for clerification over to the SharePoint writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MikePlumleyMSFT** [comment]
@DeanGross I've updated the article to clarify. Basically, the tenant settings override the site settings, but don't change them. If external sharing is on at the tenant level and some sites as well, and you turn external sharing off at the tenant level, then the sites will have external sharing disabled also. If you later turn external sharing back on at the tenant level, the sites will resume their original setting.

**Comment by AndreaBarr** [comment]
@DeanGross It looks like Mike was able to resolve this. I am going to close this at this time. If this is not resolved please re-open this issue.
