### ISSUE TITLE
Search Service Application upgrade should not contain .ForceResume(0x02)

### ISSUE THREAD

**Issue by Pillen** [MicrosoftDocs/OfficeDocs-SharePoint#464]
Resuming the Search Service Application with .ForceResume(0x02) leaves the Search Service Application in "Paused for: External request" administrative status. This should only be used in certain cases. $ssa.Resume() is sufficient here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67cc68b-2d40-7d78-9ae5-a71938b6fa78
* Version Independent ID: 52fd8de6-598e-7672-eb34-2fa7a46b0182
* Content: [Upgrade service applications to SharePoint Server 2016](https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016#upgrade-the-search-service-application)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@Pillen, thank you for your comment. If possible, can you please submit this as a Pull request. I will close this comment. thanks.
