### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#467]
Any update about the support for Windows Server 2016 (maybe using SharePoint Server 2013 with SP1)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171d6bb7-4f08-573b-a2c7-5e78add14340
* Version Independent ID: 8c204184-9c39-727c-2ac3-6106be7ce1b8
* Content: [Hardware and software requirements for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-0)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@Luigi, thank you for your comment. At this time, Windows Server 2016 is still not supported. If it changes, I will let you know. thanks .

**Comment by LuigiBruno** [comment]
Thank you @Techwriter40.
It is important due to the questions asked by users in SharePoint Forums.
