### ISSUE TITLE
External users not able to access folders

### ISSUE THREAD

**Issue by JeighBI** [MicrosoftDocs/OfficeDocs-SharePoint#468]
Did something just change? (I see this article was updated 12/3/2018) I have site with a folder that has been shared with external users who don't have a Microsoft account. For the past few months they have been able to access everything just fine. It appears, as of this morning (12/4/2018), external access links don't seem to be working... and we didn't change anything. What happened??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@scanum let's go ahead and close.
