### ISSUE TITLE
SQL Collation for SharePoint Databases – Latin1_General_CI_AS_KS_WS

### ISSUE THREAD

**Issue by patenik2** [MicrosoftDocs/OfficeDocs-SharePoint#469]
Why there are no recommendations for SQL Collation for SharePoint databases? 

Here is what I used to recommend to my customers for SharePoint 2013 and prior environments - SQL Collation for SharePoint Databases – Latin1_General_CI_AS_KS_WS for the SharePoint Databases
Supportability regarding SQL collation for SharePoint Databases and TempDB
https://nikpatel.net/2013/09/05/use-latin1_general_ci_as_ks_ws-collation-for-sharepoint-database-engine/ 

Thanks,
Nik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588cac-efbb-da8f-8b1f-8f4a21298116
* Version Independent ID: d5fead27-6212-5bc7-5bbf-9ce2066f479d
* Content: [Best practices for SQL Server in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm)
* Content Source: [SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by patenik2** [comment]
here is the missing link in above comment - Supportability regarding SQL collation for SharePoint Databases and TempDB - https://support.microsoft.com/en-us/help/2008668/supportability-regarding-sql-collation-for-sharepoint-databases-and-te

**Comment by bentoncity** [comment]
Nik, this also came up for SharePoint 2016 but according to this blog (https://social.technet.microsoft.com/Forums/office/en-US/4b7170a2-6df0-489d-88fb-cbb2d3e9521c/sql-server-collation-for-sharepoint-2016), SharePoint automatically applies this collation as needed.

**Comment by patenik2** [comment]
I am confused.. Is that forum saying Latin1_General_CI_AS_KS_WS is automatically configured for the SharePoint Databases? This is no longer required for the DBAs to configure?

**Comment by bentoncity** [comment]
@patenik2 I took it to mean that, but now I'm not sure. In the forum Paul Stork says: "The standard default is supported for the system databases like master and tempdb. The alternate collation is only required for SharePoint content databases and will automatically be applied by SharePoint when those content databases are created."

**Comment by tseward** [comment]
SharePoint *automatically* uses the correct collation. The reason this recommendation is in place is that sometimes DBAs pre-create databases and this is guidance for them.

**Comment by patenik2** [comment]
@tseward - Thanks. I have verified that SP2016 automatically applies SQL collation (Latin1_General_CI_AS_KS_WS) to SQL Server 2016 instance with SQL_Latin1_General_CP1_CI_AS collation. All SP databases including service applications and content databases have Latin1_General_CI_AS_KS_WS automatically applied. All four system databases (master, model, msdb, tempdb) uses SQL_Latin1_General_CP1_CI_AS collation including SQL server instance. I have tested SP installation and so far, I haven't seen any weird issues.

**Comment by tseward** [comment]
@patenik2 If your issue is resolved, can you go ahead and close this issue? Thanks!
