### ISSUE TITLE
Redirect and move known folder to OneDrive from Mac OSX

### ISSUE THREAD

**Issue by okhster** [MicrosoftDocs/OfficeDocs-SharePoint#470]
When will we see this feature for OneDrive for Business on Mac's?

It'll be very helpful and beneficial to help all MOF org structures to get this functionality pushed to Mac OSX 10.13.x and 10.14.x asap. 

We have a lot of trouble getting our Mac users to use OneDrive as it doesn't seamlessly sync the most crucial folders in Finder: Documents, Pictures, Desktop and Download. or even give the option to actually choose specific computer folders to sync.

Thanks! So far a great product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#feedback)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by swy** [comment]
+1 to this request.  I would like to push for company policy to be "store files in ~/OneDrive - employer to have backups and recovery", but that became harder to advocate for when Apple now gives us Stacks in 10.14, making the Desktop less of a disaster to store many files.  We all know that reality is that we can teach and set policy that the OD folder is the only safe place, but folks WILL use the Desktop, and need IT admins to help protect them.

**Comment by kaarins** [comment]
Thanks for this feedback. @swy , I see that you've already voted on this feature :) (https://onedrive.uservoice.com/forums/913525-onedrive-on-mac/suggestions/34742176-kfm-known-folder-move-for-mac)! I know the team would definitely like to add it. No announcements have been made yet, though.

**Comment by AwakeGitten** [comment]
We've deployed this through GPO and Hybrid Join - works very well with the /allusers install option.  

Does anyone know of a script that has been written to accomplish the same thing on Mac OS?  We'd love to test it.

**Comment by samspade21** [comment]
> When will we see this feature for OneDrive for Business on Mac's?
> 
> It'll be very helpful and beneficial to help all MOF org structures to get this functionality pushed to Mac OSX 10.13.x and 10.14.x asap.
> 
> We have a lot of trouble getting our Mac users to use OneDrive as it doesn't seamlessly sync the most crucial folders in Finder: Documents, Pictures, Desktop and Download. or even give the option to actually choose specific computer folders to sync.
> 
> Thanks! So far a great product.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
> * Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
> * Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#feedback)
> * Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
> * Service: **one-drive**
> * GitHub Login: @kaarins
> * Microsoft Alias: **kaarins**

We have an application we use for KFM on OneDrive for MacOS.  It creates symlinks for Documents and Desktop.  It can be found here: https://github.com/synapsepd/MacOS-OneDrive-KFM

**Comment by notanewbie** [comment]
So how long is this going to sit here without a response? I'm working with our IT team to deploy Macs and we were hoping we could sync the Windows folders up with the Mac folders. People have been asking for this feature for years, and frankly, if Microsoft refuses to add it, we will have to switch to something else, that's actually practical.
