### ISSUE TITLE
Azure SQL Managed Instance

### ISSUE THREAD

**Issue by harrisonkirby** [MicrosoftDocs/OfficeDocs-SharePoint#472]
Hi

In relation to this note:
 Note

"SQL Server Express is not supported. SQL Azure (the SaaS service) is also not supported for any SharePoint databases."

Since the last iteration of this document Microsoft have released Azure SQL Managed Instances, which gives you the option to select NSGs, therefore, so long as the Sharepoint Server and Azure SQL Managed Instance are in the same NSG (or region) this should mitigate the latency risk which currently blocks Azure SQL and Sharepoint 2016 ?

Link to article here:

https://azure.microsoft.com/en-gb/blog/azure-sql-database-managed-instance-general-purpose-tier-general-availability/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a397fdd2-9945-dd56-2a66-61c6c478f1bb
* Version Independent ID: 9ac6cdbe-ad5e-1a00-7978-0801733d1b75
* Content: [Hardware and software requirements for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nenonix** [comment]
@harrisonkirby  Thank you for taking time to improve the Microsoft Docs. Can you help me to edit the content you refer to so that this is made clearer? What would you suggest?

**Comment by tseward** [comment]
This scenario is (likely) not supported. The primary reason would be lack of support for Windows credentials. SharePoint requires this. I ran the database compat checker for SQL -> Azure SQL MI and the Windows Auth was called out as the only migration blocker for the Config/Admin databases (other databases may have further issues).

The T-SQL scripts SharePoint uses would also need to be validated to verify they're not making statements which are not supported in SQL MI.

Lastly, SharePoint does make reference to the database engine type -- While there are references for both on-prem and Azure SQL PaaS (not supported), I've never seen a reference to SQL MI which may mean that various scenarios would not function correctly in SharePoint's own code.

There are other questions I'd have about this, including some of the T-SQL statements which are not supported. I also cannot find information about changing MAXDOP to 1.

**Comment by AndreaBarr** [comment]
@harrisonkirby It looks like Trevor has resolved this issue. I am going to close this issue. If this is not resolved please re-open this issue.
