### ISSUE TITLE
Excel application co-authoring

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-SharePoint#476]
Office 365 monthly channel already support Excel client application co-authoring for SharePoint Online/OneDrive Online files.
Does it also apply for SharePoint 2016/2019 server? if yes, do we need OOS support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b626929-198d-3be9-d202-df1c80699327
* Version Independent ID: 7bed15b6-1a2d-fff5-c62e-3c07308882c6
* Content: [Overview of co-authoring in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/governance/co-authoring-overview#bkmk_sw_version_req)
* Content Source: [SharePoint/SharePointServer/governance/co-authoring-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/co-authoring-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
It does not apply. There is a note in this document covering that case

> The Excel client application does not support co-authoring workbooks in SharePoint Server. The Excel client application uses the Shared Workbook feature to support non-real-time co-authoring workbooks that are stored locally or on network (UNC) paths. Co-authoring workbooks in SharePoint is supported by using the Excel Web App.
