### ISSUE TITLE
Udpate URL for "Microsoft SQL Server 2012 Service Pack 4 (SP4) Native Client (installs with Microsoft SQL Server 2012 Feature Pack)"

### ISSUE THREAD

**Issue by mikelee-msft** [MicrosoftDocs/OfficeDocs-SharePoint#478]
Please update the software URL for : "Microsoft SQL Server 2012 Service Pack 4 (SP4) Native Client (installs with Microsoft SQL Server 2012 Feature Pack)" in section, https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019#links-to-applicable-software

with this:

"Microsoft SQL Server 2012 Service Pack 4 (SP4) Native Client"
and url: https://go.microsoft.com/fwlink/?LinkId=867003

This is the URL we use during the pre-req installer, so we would link to the same installer within this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fbcb0b-9e6d-d2e7-5194-5593d35fff63
* Version Independent ID: f6d30df6-858b-4d3c-542f-a4d6b45ec3d8
* Content: [Hardware and software requirements for SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019#links-to-applicable-software)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@mikelee-msft, thank you for your feedback, if possible, can you please submit as a Pull request?  thanks.
