### ISSUE TITLE
Enabling silent account config key performs azure ad join

### ISSUE THREAD

**Issue by zburtondbrs** [MicrosoftDocs/OfficeDocs-SharePoint#479]
Hey there,

In my testing, if I enable the silent account config policies, this joins the machine to Azure AD after the first sign-in attempt. This is fine for me, but this is not mentioned anywhere in the documentation.

I suggest that you update this document to clarify what will occur if the machine is already not joined to Azure AD.

Thanks,
Zane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by cartergreen** [comment]
@zburtondbrs Joining Azure AD is one of the pre-requirements for silent account config.  We do have AAD joined device as the first pre-req documented.
I'm not sure what you mean by saying it joins the "machine" to Azure AD.  You're machine would need to already be joined to AAD for silent account config to successfully run in the first place.  Please clarify so we can satisfy your request?

**Comment by zburtondbrs** [comment]
@cartergreen I hear ya. I set the registry key before my machine was joined to Azure AD. If the machine is not already joined to Azure AD, setting the registry key joins the machine to Azure AD. Not a huge deal, but it's probably worth mentioning in the documentation in case there's an admistrator out there that is paranoid about having machines joined to Azure AD.

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by kaarins** [comment]
I added this info to the step where the setting is enabled.
