### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaitrum** [MicrosoftDocs/OfficeDocs-SharePoint#48]
En la primera parte, pone 
- TLS 3.0*
cuando debe indicar (SSL 3.0)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 202566b7-cb2c-a612-8467-2c11c1b0c15f
* Version Independent ID: d170523c-1344-84eb-ca3f-d7a08b658fa2
* Content: [Secure Sockets Layer (SSL) y protocolo de seguridad de capa de transporte (TLS) se admiten en SharePoint Server](https://docs.microsoft.com/es-es/sharepoint/security-for-sharepoint-server/secure-sockets-layer-ssl-and-transport-layer-security-tls-protocol-support-in-sh#feedback)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/secure-sockets-layer-ssl-and-transport-layer-security-tls-protocol-support-in-sh.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr.es-ES/blob/live-sxs/SharePoint/SharePointServer/security-for-sharepoint-server/secure-sockets-layer-ssl-and-transport-layer-security-tls-protocol-support-in-sh.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
what is your exact change request?

**Comment by tseward** [comment]
@Techwriter40 the page says "TLS 3.0". It should say "SSL 3.0". I fixed it on the en-us page.

**Comment by Techwriter40** [comment]
@tseward thank you. I will change
