### ISSUE TITLE
Sub Sites

### ISSUE THREAD

**Issue by smitman3405** [MicrosoftDocs/OfficeDocs-SharePoint#480]
Is there a way to scan subsites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [Overview of the SharePoint Migration Assessment Tool](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@smitman3405 Thank you for this inquiry

I think the best way to address this is to have you contact support. They have more resources than we do here to find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
