### ISSUE TITLE
Global Navigation

### ISSUE THREAD

**Issue by SabbeRubbish** [MicrosoftDocs/OfficeDocs-SharePoint#483]
Is said to be on the roadmap, however, except mega menu, there is no clear mention of this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by nenonix** [comment]
Thank you for your feedback. I am going to research this issue and then try work with you to improve the content and reflect your concerns.

**Comment by SabbeRubbish** [comment]
You'd better actually ADD it to the roadmap, committing to promises ;-)

**Comment by nenonix** [comment]
@SabbeRubbish  We have reached out to the Roadmap team and will get back to you as soon as they clarify this issue.
@ocarcallas Thank you for your query. I will do my best to connect you with the support resources you have requested.

**Comment by nenonix** [comment]
@SabbeRubbish Feedback is that this feature is not going to added to Roadmap any time soon. I am going to remove the reference for now. Thank you for pointing this out and for helping to improve Microsoft Docs.

**Comment by MadaNechifor** [comment]
Hello! Are there any news on the global navigation in terms of its availability?
