### ISSUE TITLE
Sending docs to record center

### ISSUE THREAD

**Issue by datarchitect** [MicrosoftDocs/OfficeDocs-SharePoint#49]
How do we use this connection in a site to send documents to record center? Apparently the "Send To Location" has been removed from team sites now. What's the new way?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb2447b-a827-0d50-ee81-5b6f603dc5fb
* Version Independent ID: 4ac95806-98f8-cf56-5562-8419b3c4bc4b
* Content: [Manage a connection to a document center or a records center in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/manage-a-connection-to-a-document-center-or-a-records-center)
* Content Source: [SharePoint/SharePointServer/sites/manage-a-connection-to-a-document-center-or-a-records-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/manage-a-connection-to-a-document-center-or-a-records-center.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
I've asked the product team who owns this area about this and will address the topic when I receive more information.

**Comment by bentoncity** [comment]
After talking with the product team they agree this is a high priority item and will work to get this operational. No timeline but this sounds promising.
