### ISSUE TITLE
Not linked from left navigation

### ISSUE THREAD

**Issue by fredericklin** [MicrosoftDocs/OfficeDocs-SharePoint#496]
This page isn't linked from left navigation, which discourages discoverability of this page.  I got here from a direct link elsewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-sharing-in-targeted-release?redirectSourcePath=%252farticle%252fcc78357c-6d48-499c-9cc7-dae447d0d391)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by nenonix** [comment]
Hi. We really appreciate your efforts to improve Microsoft Docs, I will look into this issue and add the link you suggest. Thank you.

**Comment by nenonix** [comment]
I have added a link on the  External Sharing Overview page and am consulting with my team about adding a link in the left navigation.

**Comment by kenwith** [comment]
@nenonix - the person that can provide guidance on where to put the article in the TOC (left nav) is @MikePlumleyMSFT --- it might be a situation where it shouldn't be in the TOC but I am not sure. @fredericklin - thanks for this catch and opening the issue. 

@nenonix - to put the link in the left nav TOC I believe it is the toc.md file that is in the same directory as this file.. here is a link: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/toc.md

**Comment by MikePlumleyMSFT** [comment]
Correct, this article should not be in the TOC. It is scheduled to be retired in the next few months. The information therein will be moved to a different article.

**Comment by kenwith** [comment]
Thanks for clarification! Let's close this issue out.

**Comment by fredericklin** [comment]
@Mike-Ubezzi-MSFT I'm confused; If this is retired in the next few months, Is the ad-hoc external recipient implementation going away?

**Comment by kenwith** [comment]
I think what @MikePlumleyMSFT said was that the information is being moved to a different article which is why this article isn't in the TOC.  Usually what happens at that point is a redirect from this article would automatically send people to the new article. So links in blogs and things still work to get the relevant content.

**Comment by MikePlumleyMSFT** [comment]
@fredericklin, no, we're just reorganizing the content. This article was migrated from another site and isn't well integrated with our other sharing admin content. Once we've found a better home for the information, the current URL will redirect to the new location.
