### ISSUE TITLE
Search_Service_Application_AnalyticsReportingStoreDB_{ID} table shows 4 types of events - 1,2,3,4

### ISSUE THREAD

**Issue by kdhindsa** [MicrosoftDocs/OfficeDocs-SharePoint#498]
Is this documentation up to date? I am not seeing event type "4" in this documentation. Please ignore if I am looking at the wrong table in SP DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a38666-02c8-975c-5ed5-39c21f17f53e
* Version Independent ID: 03d7cded-bd50-06ab-c418-e638f9c7a9ca
* Content: [An introduction to recommendations and popular items in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/an-introduction-to-recommendations-and-popular-items)
* Content Source: [SharePoint/SharePointServer/administration/an-introduction-to-recommendations-and-popular-items.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/an-introduction-to-recommendations-and-popular-items.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@AndreaBarr can you assign this to me?
