### ISSUE TITLE
UNRESOLVED_TOKEN_VAL in document

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#5]
The doc https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md has a number of lines containing UNRESOLVED_TOKEN_VAL. These should be fixed or removed.

**Comment by kenwith** [comment]
@tseward - thanks for this info! I think I saw a number of PR's from you so this is probably already fixed. Sorry for the delay in closing this out.
