### ISSUE TITLE
Liste der Sprachen - Zuordnung fehlerhaft

### ISSUE THREAD

**Issue by NNaumburger** [MicrosoftDocs/OfficeDocs-SharePoint#501]
In der Liste der Sprachen sind die Bezeichnungen teilweise verschoben. Beispiel: Deutsch - bg -bg 1030 -&gt; Korrekt wäre Deutsch - de - de - 1031

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 44037d12-85d4-e21e-d78a-440de38c48bd
* Version Independent ID: 830be840-8a90-192f-3b7f-0da8964edb5c
* Content: [Installieren oder Deinstallieren von Sprachpaketen für SharePoint Server 2016 und 2019](https://docs.microsoft.com/de-de/sharepoint/install/install-or-uninstall-language-packs-0)
* Content Source: [SharePoint/SharePointServer/install/install-or-uninstall-language-packs-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-or-uninstall-language-packs-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nenonix** [comment]
Danke für Ihre Rückmeldung. Ich werde das prüfen und versuchen, mit Ihnen zusammenzuarbeiten, um den Inhalt so zu verbessern, wie Sie es vorschlagen.
