### ISSUE TITLE
Link explaining how to install the update goes to the wrong page

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#509]
If you click on the link "Install a software update for SharePoint Server 2013", it takes you to this page:
https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/install-a-software-update

which only applies to SharePoint Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a90935-fb89-c75b-f0c3-683c45dbaad4
* Version Independent ID: a01cb7f5-097f-629d-ded6-bf1362de329a
* Content: [Deploy software updates for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/deploy-software-updates-for-sharepoint-2013)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/deploy-software-updates-for-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/deploy-software-updates-for-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr I'll take this one.

**Comment by tseward** [comment]
@repton-infinity looking at this, while the specific article applies to 2016 and does have some 16-specific paths in some of the commands, the procedure is identical to 2013. There are even 2013-only references, such as the UPSS :)

@Techwriter40 how should this best be handled? _Most_ of the information here is accurate for both versions, just some very minor detail differences.

**Comment by scanum** [comment]
@repton-infinity  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
