### ISSUE TITLE
Setting new Authentication Realm appears to affect existing Workflow Manager configuration.

### ISSUE THREAD

**Issue by kennatom** [MicrosoftDocs/OfficeDocs-SharePoint#51]
Our Consuming Farm has web applications configured/registered to a Workflow Manager.  Upon setting a Realm value, as instructed here, existing custom workflows used in sites on this farm began failing.  For example, when attempting to view a workflow properties on a list, an error would be generated.  The ULS logs would report errors similar to the following:
"The caller does not have the necessary permissions required for this operation. Permissions granted: None. Required permissions: ReadScope."
To fix this issue, one needs to re-register any *one* site that was initially registered during the first configuration of Workflow Manager, using the Powershell cmdlet Register-SPWorkflowService.

If this is a normal occurrence when modifying Realm values, I would recommend a warning or reminder of this effect (and possibly others) included in this documentation.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96585065-aad9-9205-e602-a7426824031e
* Version Independent ID: 7362519a-9a74-5b56-8f49-2bd5c5429fcd
* Content: [Configure server-to-server authentication between publishing and consuming farms](https://docs.microsoft.com/en-us/sharepoint/administration/configure-server-to-server-authentication-in-sharepoint)
* Content Source: [SharePoint/SharePointServer/administration/configure-server-to-server-authentication-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-server-to-server-authentication-in-sharepoint.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Tom, have researched this issue with product team, added an Important note with links to the PS cmdlet and additional links for more information. I've republished this topic.
