### ISSUE TITLE
Several code blocks in this article that should be normal text

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#510]
There are several code blocks in this page that should be normal text, e.g. 

"""
For more information, see [Best Practices for using Windows Azure Cache/Windows Server Appfabric Cache](http://go.microsoft.com/fwlink/?LinkID=614969&amp;clcid=0x409) and [Application Configuration Settings (Windows Server AppFabric Caching)](http://go.microsoft.com/fwlink/?LinkID=614970&amp;clcid=0x409). For additional information about Windows PowerShell scripts and .ps1 files, see [Running Windows PowerShell Scripts](http://technet.microsoft.com/library/ee176949).
"""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff8221d-8995-2bd1-9ab4-e0043afe1c5f
* Version Independent ID: 2b157758-daa4-dad2-5edb-891e421d921f
* Content: [Manage the Distributed Cache service in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr Assign this to me please.
