### ISSUE TITLE
Result source already configured

### ISSUE THREAD

**Issue by sharepointalex** [MicrosoftDocs/OfficeDocs-SharePoint#513]
I have observed that using the PowerShell scripts (not sure about the hybrid picker) that the Cloud SSA already has the remote result source configured. Therefore I'm not 100% sure if this step is actually required in this documentation...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38066437-8d64-308a-2b10-ad4b66a8cc1a
* Version Independent ID: 0a12aad8-0822-0c9b-e685-a550687ac216
* Content: [Show results from Office 365 in on-premises SharePoint with cloud hybrid search](https://docs.microsoft.com/en-us/sharepoint/hybrid/show-results-from-office-365-in-on-premises-sharepoint-with-cloud-hybrid-search)
* Content Source: [SharePoint/SharePointServer/hybrid/show-results-from-office-365-in-on-premises-sharepoint-with-cloud-hybrid-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/show-results-from-office-365-in-on-premises-sharepoint-with-cloud-hybrid-search.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
What version of SharePoint did you do this with? I set this up back in October on 2016 and the result source was _not_ configured.

**Comment by tseward** [comment]
@scanum please close.
