### ISSUE TITLE
Beta for fix

### ISSUE THREAD

**Issue by SeanDeasyMM** [MicrosoftDocs/OfficeDocs-SharePoint#514]
Hi - I understand there is a beta version of a fix to allow this change. Can you advise how to enrol? Thank you, Seán

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
Hi @SeanDeasyMM, thanks for your comment. The team is investigating this feature, but we don't have a public beta program at this time. I hope we will soon - we know we need this feature!

**Comment by daughtkom** [comment]
@kaarins I am very hopeful about this feature.  Is there a place to track this and get notified when released?  Thanks.

**Comment by Jas0** [comment]
Absolutely would love this feature. Not sure why Microsoft does not support this. Not very professional sending links to shared files from one drive which has an old company name attached to it. Until they fix this, my money for file sharing is elsewhere.

**Comment by seanpanter** [comment]
@kaarins can you provide any timeline for this? Can we expect this in 2019? We have a client that would really benefit from this feature. Thank you!

**Comment by tazmon95** [comment]
@kaarins, has there been any more progress on this?  We really want our site address to match our primary domain and not the original tenant name which has nothing to do with our business.
