### ISSUE TITLE
mitigating risks

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#516]
Is there anything that can be done to ensure that file metadata is not lost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0386fc0-8592-8798-65ad-e6dfc18a6334
* Version Independent ID: c7767a55-cd31-a472-d039-76d07178ab27
* Content: [How to migrate your file share content to SharePoint Online using the Azure Data Box](https://docs.microsoft.com/en-us/sharepointmigration/how-to-migrate-file-share-content-to-spo-using-azuredatabox)
* Content Source: [migration/how-to-migrate-file-share-content-to-SPO-using-AzureDataBox.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-migrate-file-share-content-to-SPO-using-AzureDataBox.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@DeanGross using a tool like robocopy to preserve the limited amount of metadata NTFS provides would be the solution.

This particular solution is not designed for SharePoint on-prem sources.

**Comment by tseward** [comment]
@scanum please close.
