### ISSUE TITLE
Footnote update

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/OfficeDocs-SharePoint#52]
Hi!
The footnote (2) for the minimum hardware resources needs to be updated for the small, medium, and large search farms.  It states: With SharePoint Server 2013 the minimum amount of resources needed are 500 GB RAM, 16 GB RAM, and four CPU cores. What is probably intended is:  500 GB storage, 16 GB RAM, and four CPU cores. 

Thanks for your hard work and dedication!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e12588-d632-a9fa-c3e8-aa6bb1b46f73
* Version Independent ID: a7c0a603-f37a-ebad-2870-b35a9b3e76e3
* Content: [Plan enterprise search architecture in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/search/plan-enterprise-search-architecture#minimum-hardware-resources-for-the-small-search-farm)
* Content Source: [SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md)
* Service: **unspecified**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by Techwriter40** [comment]
@tklarsen please review and respond. thanks

**Comment by tklarsen** [comment]
Thanks for noticing and letting us know! It's fixed now.
