### ISSUE TITLE
Kerberos authentication resource list - one of the referenced articles has truncated name

### ISSUE THREAD

**Issue by mikerodionov** [MicrosoftDocs/OfficeDocs-SharePoint#522]
In "For more information about Kerberos authentication, see the following resources:" section we have article listed as "How the Kerberos Version 5" - obviously truncated name which should be replaced witch complete one - "How the Kerberos Version 5 Authentication Protocol Works"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f878d753-1311-3aff-406f-f33436cee5e7
* Version Independent ID: 52f317cb-685d-741a-77bc-f63d40519026
* Content: [Plan for Kerberos authentication in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/kerberos-authentication-planning)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/kerberos-authentication-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/kerberos-authentication-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nenonix** [comment]
@mikerodionov Thank you for pointing this out.

**Comment by tseward** [comment]
@nenonix There are a few formatting issues with links in this article, can you fix those as well? A couple of the links are no longer up to date or the content of those links is poorly formatted (check the ones that point to TN URLs).

It's probably a good idea to find a few replacement articles.

**Comment by nenonix** [comment]
will do
