### ISSUE TITLE
Quick Links label

### ISSUE THREAD

**Issue by thomas-bak** [MicrosoftDocs/OfficeDocs-SharePoint#524]
In the "Labeling" section on this page you present the following recommendation:

"For example, think twice before you use these labels: Quick Links"

But one of the default SharePoint web parts is called just that.
It's confusing when you deliver a product with labeling that you recommend against using.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by LoreenLa** [comment]
Thanks for your feedback, @thomas-bak! I can see how that would sound contradictory. The Quick links title for the web part is intended to be very general, just to describe the web part itself. When you use it and add your links to it, we suggest you change the title in the web part to something specific that describes the links you add. You can do this by typing over the Quick links title in the web part when you are in edit mode.
