### ISSUE TITLE
Silent config via Autopilot and Intune

### ISSUE THREAD

**Issue by JasonTimmins** [MicrosoftDocs/OfficeDocs-SharePoint#527]
Hi There,
I'm trying to get this working using an Intune-based PS policy delivered as the machine does the Autopilot process but it's just not working. What am I missing? Have you tried it this way? Surely having OneDrive automatically configure as part of Autopilot is something you'd want?!
Cheers
Jason.

**Comment by scanum** [comment]
@JasonTimmins  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by JasonTimmins** [comment]
Hi There,

I’m afraid that doesn’t work. I’ve had three tickets with various departments, no-one would take ownership or solve the problem. Office 365 supports says that it’s a MICROSOFT 365 issue and they are not changed on MICROSOFT 365. OneDrive support say it’s an Intune issue. Intune say it’s a OneDrive issue. I need someone who’s ACTUALLY DONE THIS to tell me what to expect and how to get it working.

Also, we’re a Microsoft partner so I’m happy to use our ‘partner support hours’, etc to get to the bottom of this but I’m not doing that if you just all blame one another! #Shambles.

Jason.

Jason Timmins
Technical Director
MBM Ltd<https://www.mbmltd.co.uk> ISO9001:2015
Keeping Business in Business

01902 324494
jason@mbmltd.co.uk<mailto:jason@mbmltd.co.uk>
www.twitter.com/mbmltd<http://www.twitter.com/mbmltd>
www.facebook.com/mbmltd<http://www.facebook.com/mbmltd>

[cid:image001.jpg@01D3CFD3.C3514A50]<https://www.mbmltd.co.uk/>

[cid:image002.jpg@01D3CFD3.C3514A50]<https://www.prowifi.co.uk/>

[cid:image003.png@01D4F4FC.71FE63A0]<https://sft.mbmltd.co.uk/>

[cid:image004.jpg@01D4F4FC.71FE63A0]
