### ISSUE TITLE
Number of supported servers

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#528]
It could be useful adding an information about the different supported topologies (number of servers) for a Workflow Manager Farm: as far as I know, a Workflow Manager Farm can only be composed either by 1 server or 3 servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9696f9c-aeb8-e0b9-2a43-bc24e9c7b2b2
* Version Independent ID: e267b2fe-5cb3-9f79-f062-4f02763d7505
* Content: [Install and configure workflow for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/install-and-configure-workflow-for-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
Thanks for reading and making the suggestion @LuigiBruno!
SharePoint Server 2019's release [doesn't change high availability](https://social.technet.microsoft.com/Forums/en-US/ca1950fc-f7f1-4d85-99a3-5d0cb1a08238/workflow-manager-architecture?forum=SP2019) of Workflow Manager which is covered in the [Workflow Manager system requirements](https://docs.microsoft.com/previous-versions/dotnet/workflow-manager/jj193451(v%3dazure.10)#high-availability).

**Comment by LuigiBruno** [comment]
Thanks @tomresing.

**Comment by tomresing** [comment]
What about 7?
