### ISSUE TITLE
SharePoint Management Agent Configuration fails

### ISSUE THREAD

**Issue by thockman64** [MicrosoftDocs/OfficeDocs-SharePoint#533]
I have followed the instructions for running the SharePoint MA configuration, but the powershell keeps blowing up about properties like 'name' cannot be found. Verify that property exists, etc.. I have set directory partitions and OU paths correctly and used valid credentials. Not sure why it will not load to an 
otherwise working instance of MIM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03471062-4810-b5b9-2caa-286e5ed90706
* Version Independent ID: 4b2baed1-f7b4-81d1-dedd-28f45b5e31f1
* Content: [Use a sample MIM solution in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/SharePoint/administration/use-a-sample-mim-solution-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/administration/use-a-sample-mim-solution-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/use-a-sample-mim-solution-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@thockman64 I would suggest posting this on the TechNet forums at https://social.technet.microsoft.com/Forums/sharepoint/en-US/home?forum=SP2016 where we can diagnose and go through the issues. If we find a deficiency in the documentation after going through some troubleshooting, I'd be more than happy to update the docs.

**Comment by tseward** [comment]
@scanum please close as a support issue.
