### ISSUE TITLE
Content database size (general usage scenarios) - Description incorrect

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint#54]
The description of the "Content database size (general usage scenarios)" is incorrect. The first lines are talking about the max file upload size:

"The default file size is 50 MB, which can be increased to a maximum of 2 GB. You can fit 100 files in each content database. Multiple site collections can share a single content database. Each site collection needs to be fully stored in a single content database. 
We strongly recommended limiting the size of content databases to 200 GB, except when the circumstances in the following rows in this table apply. 
If you are using Remote BLOB Storage (RBS), the total volume of remote BLOB storage and metadata in the content database must not exceed the 200GB limit. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Service: **unspecified**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
merged. and closed
