### ISSUE TITLE
Microsoft sharepoint migration tool support for quickparts

### ISSUE THREAD

**Issue by sagaracharya21** [MicrosoftDocs/OfficeDocs-SharePoint#541]
Hello,

Does this tool support to migrate quickparts embedded in document ?

Thanks
Sagar Acharya

**Comment by hotmael22** [comment]
@Rakanfalroba 
[4AEE18F83AFDEB2,https_  github,4AEE18F83AFDEB2,https_  www.sol,4AEE18F83AFDEB2(1).pdf](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/2718645/4AEE18F83AFDEB2.https_.github.4AEE18F83AFDEB2.https_.www.sol.4AEE18F83AFDEB2.1.pdf)

**Comment by tseward** [comment]
@AndreaBarr assign this to me, please.

**Comment by tseward** [comment]
@sagaracharya21 In my testing, while SMAT keeps the data that was previously entered into the quick part, the quick part is no longer attached to the library property that drove it. So if you had entered data, yes it will be preserved during the migration, but that quick part becomes unusable to change the data within the document.

If this is a feature you need, I would suggest adding it to the SharePoint Migration Tool Uservoice at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365.
