### ISSUE TITLE
Target to folder instead of root of document library

### ISSUE THREAD

**Issue by MDKBreinwave** [MicrosoftDocs/OfficeDocs-SharePoint#542]
Is it possible to set the target to a folder in a document library instead of the root of a document library? Via the UI it's not possible so I tried saving the task as json and then add the folder path to the target URL. Got error code: 0x0201000F. If this is not an option, will this be possible in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by MDKBreinwave** [comment]
> Is it possible to set the target to a folder in a document library instead of the root of a document library? Via the UI it's not possible so I tried saving the task as json and then add the folder path to the target URL. Got error code: 0x0201000F. If this is not an option, will this be possible in the future?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 193d7cc4-4270-f69e-262b-6384a273f835
> * Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
> * Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
> * Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
> * Product: **sharepoint-server-itpro**
> * GitHub Login: @JoanneHendrickson
> * Microsoft Alias: **jhendr**

**Comment by MDKBreinwave** [comment]
I tried yesterday to add the subfolder via the csv import  but no matter what I try the migration tool doesn't accept the csv file. Do I need a specific csv format? In Excel you have several options. The json import would be fine too but I could not figure out what the syntax is for routing the documents to a subfolder. Let's say I have the following parameters:
site - http://mysite.sharepoint.com/projects
doclibrary - Project1Docs
subfolder - Planning

What would be the full json syntax for importing? Many thanks for your help.

**Comment by tseward** [comment]
@AndreaBarr Assign to me please.

**Comment by JoanneHendrickson** [comment]
@tseward I have already contacted the PM regarding this.

**Comment by JoanneHendrickson** [comment]
Have you looked at the formatting requirements in this topic?   https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration

**Comment by Eillirand** [comment]
Yes, this is much desired. We are moving thousands of folders and need to move them into certain folder structures in SharePoint Online.  It is a pain as right now, I have to move them to the root then wait for the migration tool to complete, them manually moved them into the folder. And let's just say, the later is a pain. Brower manageability of SPO is still lacking (often times out)

**Comment by robidog** [comment]
Agree with @Eillirand. Need to be able to specify target folder.

**Comment by AltCoyne** [comment]
This is a huge requirement.

**Comment by scanum** [comment]
@JoanneHendrickson Any updates on this? Thanks!

**Comment by JoanneHendrickson** [comment]
This ability to select a subfolder is development under consideration.  Please go to UserVoice and vote for it:
https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-and-migration/suggestions/36503032-support-targetlistrelativepath-in-sharepoint-migra

**Comment by rohit404404** [comment]
i see this is available through UI now. are powershell commands updated? I dont see any updated documentation around this.
