### ISSUE TITLE
Microsoft Teams will work after delete? 

### ISSUE THREAD

**Issue by filipkcz** [MicrosoftDocs/OfficeDocs-SharePoint#543]
Will MS teams work after deleting the default site collection?

I need recreate default site and select different template. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bd11d3-f2a4-2811-09bd-449c3c3607da
* Version Independent ID: 2f47da99-02e6-3357-ed41-b28bd5190907
* Content: [Delete a site collection](https://docs.microsoft.com/en-us/sharepoint/delete-site-collection)
* Content Source: [SharePoint/SharePointOnline/delete-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/delete-site-collection.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@AndreaBarr Assign to me.

@filipkcz When you delete the site associated with a Group, it will delete the site, Office 365 Group, and Microsoft Team.

Or are you asking about the root site (https://tenantName.sharepoint.com/)? Recreating this with another template is not supported at this time.
