### ISSUE TITLE
Site Library Count Limits

### ISSUE THREAD

**Issue by tallman5** [MicrosoftDocs/OfficeDocs-SharePoint#544]
Is there a limit to the number of document libraries in a site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d1a46c-4a3b-f99d-cca8-326b36235b1d
* Version Independent ID: d99a6050-b1af-afa2-8948-b1bba2ea7398
* Content: [Software boundaries and limits for SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me.

@tallman5  There are no defined limits.
