### ISSUE TITLE
Sharepoint 2019

### ISSUE THREAD

**Issue by bradgillap** [MicrosoftDocs/OfficeDocs-SharePoint#545]
The link is incorrect for web tiles. Sharepoint 2019

It should be 

https://web_app/Lists/Custom%20Tiles/AllItems.aspx

not

http://web_app/lists/custom tiles

Which should be in quotes if you are going to put spaces in a web address with no indication that the web address has ended. Technical writing is hard. I get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244110ff-0cc2-1acf-7fa3-ac1d29ea667b
* Version Independent ID: 6945082c-071a-dfd3-cd86-54e8cd33ff5e
* Content: [Custom Tiles in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/SharePoint/administration/custom-tiles-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/administration/custom-tiles-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/custom-tiles-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@bradgillap thank you for your feedback, this has been updated and republished.
