### ISSUE TITLE
Broken link to Ranking Model Tuning App

### ISSUE THREAD

**Issue by danglund** [MicrosoftDocs/OfficeDocs-SharePoint#547]
The link to ranking model tuning app is broken. 

https://office.microsoft.com/en-us/office365-sharepoint-online-enterprise-help/create-a-custom-ranking-model-by-using-the-ranking-model-tuning-app-HA104104860.aspx?CTT=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84aa98d-55e2-d8fe-02b7-acbd27657a20
* Version Independent ID: 19e3fbe0-a505-dcaa-14e9-3f4ad8f9782b
* Content: [Overview of search result ranking in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/overview-of-search-result-ranking)
* Content Source: [SharePoint/SharePointServer/search/overview-of-search-result-ranking.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/overview-of-search-result-ranking.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by nenonix** [comment]
@danglund Thank you for contributing to the quality of the documentation. I will work with you to fix the problem you describe.
