### ISSUE TITLE
Is XSL Link available in SharePoint Server 2019

### ISSUE THREAD

**Issue by thshdw** [MicrosoftDocs/OfficeDocs-SharePoint#549]
In Sharepoint 2016 each list or webpart properties had a Miscellaneous section where you could add your own xslt. Is this still available in 2019?

![image](https://user-images.githubusercontent.com/4992951/50805050-e741c480-12ad-11e9-9337-eb91f1229a5c.png)

I can't find any confirmation that this still exists in 2019. I use this a lot in Sharepoint 2016.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019#removed-features-in-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@AndreaBarr Assign to me, please.

In terms of XSL, yes that option is still there in classic mode sites only. It will not be present on modern pages using modern webparts.

**Comment by tseward** [comment]
Only issue with doing this is there are quite a few features that are classic-only, so it would become a very long list of what is still available, but only in classic.

**Comment by thshdw** [comment]
Thanks! The closest document that I could find that compares modern to classic is 

https://support.office.com/en-us/article/differences-between-sharepoint-server-2016-and-2019-ba84c8a3-3ce2-4252-926e-c67654ceb4a3

But no mention of xslt support in Modern.

**Comment by tseward** [comment]
Yep, and again there are so many differences that calling them out may not be feasible. @tomresing, since this is a support.office.com article @thshdw referenced, any thoughts?

**Comment by thshdw** [comment]
I'm not sure how popular XSLT is in 2016. It's important to me as I'm using it to extend webpart lists in various ways. It's something that I would want to use on some pages in 2019. I'm happy its still around. Others wanting to know if XSL functionality still exists hopefully will stumble upon this thread. Thanks for answering my question 😄

**Comment by tomresing** [comment]
Thanks @thshdw and @tseward. I've added [a note about XSL link in the types of customizations only available in classic ](https://support.office.com/article/differences-between-the-new-and-classic-experiences-for-lists-and-libraries-30e1aab0-a5cc-4363-b7f2-09e2ae07d4dc)linked to from that 2019 end support.office.com article.
