### ISSUE TITLE
The new version 2.1.103.8420 fails to migrate to OneDrive

### ISSUE THREAD

**Issue by technoself** [MicrosoftDocs/OfficeDocs-SharePoint#550]
Had version 2.1.106 installed on machine but agreed to update to newer version before doing scheduled File share to SharePoint migration. The new version gave an error on CSV file that my account is not SharePoint Admin. Tried the same file on another machine that luckily still have older version and the CSV file worked fine. For both cases used the same credentials. When tried one-off OneDrive migration from file share using new version I got an error on the OneDrive destination URL. 
Microsoft Team please verify the new version can do OneDrive migration!
Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by harrynode** [comment]
+1

Luckily we have the older version that still works. The new version 2.1.103.11 is not accepting CSV files.

**Comment by mohdmurtuzakhan** [comment]
> Had version 2.1.106 installed on machine but agreed to update to newer version before doing scheduled File share to SharePoint migration. The new version gave an error on CSV file that my account is not SharePoint Admin. Tried the same file on another machine that luckily still have older version and the CSV file worked fine. For both cases used the same credentials. When tried one-off OneDrive migration from file share using new version I got an error on the OneDrive destination URL.
> Microsoft Team please verify the new version can do OneDrive migration!
> Thank you
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
> * Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
> * Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
> * Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
> * Product: **sharepoint-server-itpro**
> * GitHub Login: @JoanneHendrickson
> * Microsoft Alias: **jhendr**

Kindly post and update once finished resolving this issue.
I have some queries, What is the maximum number of Task I can perform in a single Round? or What is the maximum records I can put in CSV file for migration? What is the maximum data allowed per Task?

**Comment by scanum** [comment]
@JoanneHendrickson Any updates on this? Thanks!

**Comment by jimdavis66** [comment]
+1 

Would love this to be fixed in the next week or so. Does anyone have a workaround that doesn't involve having to add the admin account to every SharePoint user profile?

**Comment by scanum** [comment]
@JoanneHendrickson Any updates on this? Thanks!

**Comment by NikNak82** [comment]
This is still a problem. Is there any update on this? Has the ability to migrate to Onedrive folders been removed?

**Comment by jimdavis66** [comment]
It's frustrating this hasn't been fixed yet. The workaround I had to do was add my migration user as a "Site Collection Administrator" to every OneDrive site. Luckily this can be done with powershell:
`Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.sharepoint.com/personal/" | ForEach {Set-SPOUser -IsSiteCollectionAdmin $true -LoginName o365admin@contoso.com -Site $_.Url}`

**Comment by JoanneHendrickson** [comment]
This issue has been resolved in the most current build, Version 3.1.110.1. The tool will grant permission and remove it afterward.  To download:  https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

Thanks!
