### ISSUE TITLE
Description of item (Content column) - wrong SharePoint version

### ISSUE THREAD

**Issue by grosvnor** [MicrosoftDocs/OfficeDocs-SharePoint#551]
On the second item should be "SharePoint Server 2016" instead of "SharePoint Server 2013".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78719121-dd09-71ab-5f96-319abe2b97fd
* Version Independent ID: 98699f5d-6750-ee03-1918-b53667c69482
* Content: [User profiles and identities](https://docs.microsoft.com/en-us/SharePoint/administration/user-profiles-and-identities#section1)
* Content Source: [SharePoint/SharePointServer/administration/user-profiles-and-identities.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/user-profiles-and-identities.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please
