### ISSUE TITLE
Edit needed to SharePoint Designer entry

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-SharePoint#552]
This currently says "Users can still open data sources." This is incorrect. 
It should be: 
For each SharePoint Designer session, the first site opened must allow custom script. Once that connection is created, additional sites in the same tenant can be opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by nenonix** [comment]
Thank you for pointing this out. I will edit the document accordingly. Would it work if we said "Users can still open data sources, but for each session....." Or are you saying that "Users can still open data sources," is incorrect.

**Comment by fselkirk** [comment]
You  can open some data sources (lists and libraries) directly from SharePoint, but only from Classic experience, and only from Internet Explorer, and only if you already have SharePoint Designer already open (in this case). We probably don’t want to mention that method, as we are clearly moving away from it. Usually, you would start in SharePoint Designer with the “Open Site” button, so I think that terminology is clearer.

How about:

To open a site that does not allow custom script in SharePoint Designer, you must first open a site that does allow custom script.

To clarify, here’s how you access the site from SharePoint Designer:

[cid:image003.jpg@01D4A834.D45D5840]


Once you’re in, you see something like this:

[cid:image006.jpg@01D4A834.D45D5840]


Does that help?


Frances Selkirk
Support Escalation Engineer | SharePoint Online and SharePoint Client Technical Support
fselkirk@Microsoft.com<mailto:fselkirk@Microsoft.com> | +1 (857) 453-6233 | Available Monday – Thursday: 9 :30 – 17 :30, ET (GMT -5 :00)
Manager: Floyd Mathias |  floydm@microsoft.com<mailto:floydm@microsoft.com> | +1 (781) 487-6679
Case Backup: Brian Yau | bryau@microsoft.com<mailto:bryau@microsoft.com>  |  +1 (781) 487-6613

Did you know? You can submit your O365 service and support feedback from the admin portal<http://aka.ms/o365satisfaction> by viewing support service requests.

**Comment by nenonix** [comment]
@fselkirk Thank you that is a great help. I will post back here when the changes have been made.
