### ISSUE TITLE
Minimum Storage Quota

### ISSUE THREAD

**Issue by mattengibous** [MicrosoftDocs/OfficeDocs-SharePoint#553]
The minimum storage quota is 1GB or 1024. Setting User's OneDrive storage to 512 with PowerShell rounds up o 1024. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bca1c5d-b73f-1780-b002-81c8f7ef4c0a
* Version Independent ID: 8a98d773-6bb4-8182-5405-2ce80c5b54ea
* Content: [Change a specific user's OneDrive storage space](https://docs.microsoft.com/en-us/onedrive/change-user-storage)
* Content Source: [OneDrive/change-user-storage.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/change-user-storage.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by nenonix** [comment]
@mattengibous Thank you for contributing to better Microsoft Documents.  I will research the issue and report back here when the content has been modified.

**Comment by scanum** [comment]
@kaarins Hi Kaarin, any updates on this issue? Thanks

**Comment by kaarins** [comment]
We say that 1024 is the minimum, but I reworded to be clear that PS accepts lower values and rounds up to 1024.
