### ISSUE TITLE
Doesn't work (with Azure AD)

### ISSUE THREAD

**Issue by JasonTimmins** [MicrosoftDocs/OfficeDocs-SharePoint#555]
This PowerShell script either just doesn't work or doesn't work with PCs connected to Azure AD. Can someone verify that it works with Azure AD connected PCs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@JasonTimmins , thank you for this feedback. I'm investigating and will update this when I find out more.

**Comment by cartergreen** [comment]
@JasonTimmins, I'm not sure what you mean by doesn't work.  All the script is doing is setting a registry key, can you confirm that the registry key gets set?  If not, then please try to manually set it then launch the sync client and see if that works for you.

**Comment by JasonTimmins** [comment]
Hi There,

OK, I’m prepared to acknowledge that the script does actually add entries to the registry but those registry entries don’t work, they don’t make OneDrive install silently. That’s the real issue.

Cheers
Jason.

Jason Timmins
Technical Director
MBM Ltd<https://www.mbmltd.co.uk> ISO9001:2015
Keeping Business in Business

01902 324494
jason@mbmltd.co.uk<mailto:jason@mbmltd.co.uk>
www.twitter.com/mbmltd<http://www.twitter.com/mbmltd>
www.facebook.com/mbmltd<http://www.facebook.com/mbmltd>

[cid:image001.jpg@01D3CFD3.C3514A50]<https://www.mbmltd.co.uk/>

[cid:image002.jpg@01D3CFD3.C3514A50]<https://www.prowifi.co.uk/>

[cid:image005.png@01D4B2FC.D659D060]<https://sft.mbmltd.co.uk/>

[cid:image006.png@01D4B2FC.D659D060]

**Comment by scanum** [comment]
@JoanneHendrickson Any updates on this? Thanks!

**Comment by bmcdade00** [comment]
@kaarins Any update?

**Comment by get-itips** [comment]
Hello @JasonTimmins how are you? Wanted to know if you also apply registry keys and directions on [this article ](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
I assume also that MFA isn't enabled for your devices as per the article says.
Thanks

**Comment by scanum** [comment]
@JasonTimmins We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
