### ISSUE TITLE
Markdown is a little messed up here

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#556]
Lots of cases where normal text is mistakenly in a code block

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceaea670-5dc7-1f74-2828-91d889dab921
* Version Independent ID: 6f01ff83-0eb1-129a-f443-a047fc5d4292
* Content: [Assign or remove administrators of service applications in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/assign-or-remove-administrators-of-service-applications)
* Content Source: [SharePoint/SharePointServer/administration/assign-or-remove-administrators-of-service-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/assign-or-remove-administrators-of-service-applications.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by bentoncity** [comment]
I reformatted the markdown and republished.
