### ISSUE TITLE
Applies to section not correct

### ISSUE THREAD

**Issue by zsolt-illes** [MicrosoftDocs/OfficeDocs-SharePoint#559]
If I understand correctly, the same process applies to SP2019, which means it that the article's "Applies to" section is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ccb7df-8dca-b5fc-4e84-e3624d2804cc
* Version Independent ID: 669daf62-d97c-3489-786b-6924c1e755b0
* Content: [SharePoint Server 2016 zero downtime patching steps](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@zsolt-illes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
