### ISSUE TITLE
Workflow Manager Requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#56]
Please update the information above to incorporate the announcement at https://blogs.msdn.microsoft.com/workflowteam/2017/07/25/workflow-manager-1-0-now-supported-on-windows-server-2016-with-cu4/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 225f1d58-9378-5f53-3115-c7b4ff5709e0
* Version Independent ID: 91a46552-54dd-d126-b8d1-4d8aa4a9894f
* Content: [Create a high availability architecture and strategy for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/plan-for-high-availability)
* Content Source: [SharePoint/SharePointServer/administration/plan-for-high-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-high-availability.md)
* Service: **unspecified**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
This should probably go in the WFM docs which have not moved over. They require a fair amount of re-write.

**Comment by bentoncity** [comment]
The Workflow Manager team will update their documents.
