### ISSUE TITLE
no option for "People with Existing Access" to the Default Link Types

### ISSUE THREAD

**Issue by ddudekJFF** [MicrosoftDocs/OfficeDocs-SharePoint#560]
Why is there no option for "People with Existing Access" to the Default Link Types under SharePoint Admin Center's sharing options. https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/33706777-add-people-with-existing-access-to-the-default-l

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4d52c4-16bf-1a8c-ae40-e19e82976c8a
* Version Independent ID: 1d13e7f9-8c1d-043a-5929-3d4622b3d9e5
* Content: [Change the default link type when users get links for sharing](https://docs.microsoft.com/en-us/sharepoint/change-default-sharing-link)
* Content Source: [SharePoint/SharePointOnline/change-default-sharing-link.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-sharing-link.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
@ddudekJFF thank you for pointing this out. I'll investigate further and revert soonest.

**Comment by tseward** [comment]
The product group is well aware of this issue. You can vote on this issue at https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/suggestions/33706777-add-people-with-existing-access-to-the-default-l.

**Comment by scanum** [comment]
@ddudekJFF Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
