### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by andrekrijnen** [MicrosoftDocs/OfficeDocs-SharePoint#561]
All Web Applications sans Central Administration when the language is EN-US, should be All Web Applications without Central Administration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73d53bc-485a-a5d8-d864-e2e402c07625
* Version Independent ID: 72edd383-b5cb-3b66-4fb2-e9f5ab7d56ce
* Content: [Account permissions and security settings in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by nenonix** [comment]
@andrekrijnen Thank you for pointing this out. The change has been submitted.

**Comment by tseward** [comment]
FYI "sans" is in common usage in American English :-)

**Comment by nenonix** [comment]
@tseward Even so "without" is the better, simpler universal word to use, so I went with the proposed edit as per the Microsoft style guidelines.

**Comment by Techwriter40** [comment]
nenonix, thank you for your feedback. I have made the change to "without".  closing comment
