### ISSUE TITLE
Sync Updates

### ISSUE THREAD

**Issue by ToddKlindt** [MicrosoftDocs/OfficeDocs-SharePoint#562]
The two options given to sync custom profile properties are a few years old. You may want to add a link to this newer method, https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online#call-the-import-api-from-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 089de41e-64c6-4698-5a2e-deafe6fac8ea
* Version Independent ID: 99812440-95be-2284-4b90-3088f55b3772
* Content: [Add and edit user profile properties in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/add-and-edit-user-profile-properties)
* Content Source: [SharePoint/SharePointOnline/add-and-edit-user-profile-properties.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/add-and-edit-user-profile-properties.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
Thanks, Todd! Will do!

**Comment by scanum** [comment]
@kaarins Any updates on this issue? Thanks!

**Comment by kaarins** [comment]
This change was published immediately, and I just missed closing the issue. :)
