### ISSUE TITLE
User is not in directory

### ISSUE THREAD

**Issue by RiccardoAmadi** [MicrosoftDocs/OfficeDocs-SharePoint#563]
I have now allowed external sharing with anyone on my tenant from the admin center, on the site collection, on the site permission and i have also enabled access requests at all levels.
I'm trying to open the link to a document from an user outside the organization

Expected behaviour:
Access Request form is displayed

Actual behaviour:
An error is displayed which roughly translates to: <User> is not in the <URL> directory

How can I allow access requests to a single document from external users? Which link should i share to external users in order for them to try opening it and then receive the access request form?

**Comment by scanum** [comment]
@RiccardoAmadi  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
