### ISSUE TITLE
Sharing with blocked download on unmanaged devices

### ISSUE THREAD

**Issue by IstvanYbema** [MicrosoftDocs/OfficeDocs-SharePoint#566]
Could you clarify the proces when sharing with external users and the 'block download (SP admin) on unmanaged devices' setting enabled? It looks like in this situation Ad-hoc external recipients cannot edit the document in the Desktop Office App, but Guest users (added to the AAD) can?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint Online](https://docs.microsoft.com/nl-nl/sharepoint/what-s-new-in-sharing-in-targeted-release?redirectSourcePath=%252farticle%252fcc78357c-6d48-499c-9cc7-dae447d0d391)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by kaarins** [comment]
@IstvanYbema , thank you for this feedback. I am investigating and will comment when I know more.

**Comment by SanjoyanM** [comment]
@IstvanYbema : the Adhoc users are "one time users". They do not have any "identity" like guest users in AAD do. By default the adhoc users are blocked and Set-SPOTenant -ApplyAppEnforcedRestrictionsToAdHocRecipients $false will remove that blockage.

**Comment by IstvanYbema** [comment]
According to the powershell documentation on Set-SPOtenant this value is by default false.

**Comment by SanjoyanM** [comment]
Ok what is the behavior you are observing?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IstvanYbema** [comment]
Hi Sanyon,
The documentation does not describe the difference between guest sharing and adhoc sharing with the setting in SharePoint admin enabled for blocking download access on managed devices. I have tested this and found that the proces and result is different. When sharing to an external guest it depends if the guest has a managed device is his own Tenant. As you might espect Downloading should be blocked, since your source Tenant does not manage the device. But the guest can still download the document. This is not the case for adhoc sharing though.

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by SanjoyanM** [comment]
Yes. Your testing is correct. If the source tenant trusts the other tenant and guest belongs to other tenant then he can download. This can be stopped by raising a ticket with AAD. Do you want to do that? I take your feedback on mentioning this in documentation.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IstvanYbema** [comment]
Ok, Thank you. I guess it is important to mention when a Tenant is trusted and the different behavior between adhoc and oldschool guest. Is the a Way to Block downloads for guest users on managed Tenant?

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by SanjoyanM** [comment]
It can done from backend by Azure. If you want you need to raise a support ticket with azure

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scanum** [comment]
@JoanneHendrickson Any updates on this? Thanks.
