### ISSUE TITLE
Covering MMS/Term Store in SPO

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-SharePoint#567]
There seems to be a content gap for SPO in that this article doesn't cover MMS/Term Store in SPO and I can't find anything from a quick search. Is there a place to adopt this article for SPO, given that most of it (except for the overview section) does apply?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7213563-d247-f578-b39d-8d0bbf036d25
* Version Independent ID: f3a72367-1289-7fa0-c43c-a748744c77ba
* Content: [Plan for managed metadata in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/managed-metadata-planning)
* Content Source: [SharePoint/SharePointServer/governance/managed-metadata-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/managed-metadata-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by bernardlam** [comment]
I thought so too. in this case shall we change the "Applies To" indicator to show that the article does apply to SPO, and call out specific sections that don't apply?

**Comment by bernardlam** [comment]
Hi Trevor,

I just got around to do a quick comparison of the two articles. In response to your question, here’s a few suggested changes for the SPO article:

  *   Social Tags section
     *   I think it’s referring to the Tags and Notes feature which is retired (https://support.office.com/en-us/article/sharepoint-online-tags-notes-feature-retired-77851bd5-6d5e-42fe-9bf6-d7c17eeb771f). shall we remove this section or at least indicate it’s retired?
  *   Mention scalability limits/performance recommendations (or point to relevant articles)
     *   I’m heard from my teammates  (SP PFEs and Consultants) that having too many Managed Metadata columns in Metadata Navigation (say >10) may result in slow page load.
     *   Also there’s specific recommendations with using Managed Metadata field in group by (see https://support.office.com/en-us/article/Use-grouping-to-modify-a-SharePoint-view-18548b63-a869-4fcf-89b1-ba3d04784df7)

As for the on-prem article (https://docs.microsoft.com/en-us/sharepoint/governance/managed-metadata-planning) would it be possible to add a link to refer to the SPO article? This is one thing that my teammates found confusing, and people who only sees that on-prem article may get the wrong impression that managed metadata shouldn’t be used in SPO.

Bernard

**Comment by tseward** [comment]
@bernardlam thank you for the feedback. I'll incorporate those into this article.
