### ISSUE TITLE
Navigation with in the article is wrong.

### ISSUE THREAD

**Issue by Charan-Thota** [MicrosoftDocs/OfficeDocs-SharePoint#57]
Under in-place method without backward compatibility, clicking on the link(Install a software update for SharePoint Server 2016) takes you to the top of the page but I guess it should navigate to "Install a software update on servers that host Search components" which is at the bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757daa4f-85eb-2b0e-094a-f01b9ed3d874
* Version Independent ID: acfb92cf-1d51-d6a7-bebc-9c145f5b7710
* Content: [Install a software update for SharePoint Server 2016](https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/install-a-software-update#install-a-software-update-on-servers-that-host-search-components)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/install-a-software-update.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@Charan-Thota - thanks for reporting and sorry for the delay. This is fixed now and I forgot to close this here. Appreciate the feedback and making the docs better!
