### ISSUE TITLE
Incorrect statement in documentation

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/OfficeDocs-SharePoint#570]
The statements below which are located the "Which option to select" section are incorrect. 
They are incorrect because by default, the "Allow members to share the site and individual files and folders" setting is enabled on ALL site collections, which means that users in the "Members" group (that does not have full control permission) can share sites, files and folders. 
"Site owners or others with full control permission can share sites with external users." 
"Site owners or others with full control permissions on a site can share documents with external users."

Should be 
"Site owners and members can share sites with external users." 
"Site owners and members of a site can share documents with external users."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by nenonix** [comment]
@Jvasil thank you for sharing your feedback and helping us improve the docs.  I will do my best to reflect your changes in the content.

**Comment by nenonix** [comment]
@Jvasil Just for clarity please tell me, is the statement is wrong for all the options in the **Which Option to Choose** table? Or just for the third option"Allow users to invite and share with authenticated external users "?

**Comment by tseward** [comment]
In this case, the documentation is indeed correct. Sharing can be done with users who not external users and in AAD by site members, as you noted. The controls mentioned in the documentation are very specific to external users/anonymous links, however.

**Comment by Jvasil** [comment]
Sorry for my delayed response on this and Closed #570<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fissues%2F570&data=02%7C01%7Cjvasil%40microsoft.com%7Cd2c40abae9f9408847cb08d68d5fe451%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636851840322529155&sdata=HCuKhxwVSrWZ1Ff1W4VJtfDN7Qv124yOa2qTWJ4jrtE%3D&reserved=0>.
This point is that by default “Members” can share with external users.. and by default Members do NOT have full control permission.
Therefore the statements below which are located the "Which option to select" section are incorrect of that document are incorrect.
============================================================================================================================================================
They are incorrect because by default, the "Allow members to share the site and individual files and folders" setting is enabled on ALL site collections, which means that users in the "Members" group (that does not have full control permission) can share sites, files and folders.
"Site owners or others with full control permission can share sites with external users."
"Site owners or others with full control permissions on a site can share documents with external users."
Should be
"Site owners and members can share sites with external users."
"Site owners and members of a site can share documents with external users."
=======================================================================================================

**Comment by tseward** [comment]
@Jvasil but keep in mind the context of the article. The context of the article is about SPO Admin Center settings, not the per-site setting you're referring to.

**Comment by Jvasil** [comment]
Yes I know and realize that. I believe your  missing my point.. with the highlighted setting selected at tenant level, the highlighted statement is incorrect because “site Members” can also share with external users.
Site Members do not have full control permission, nor are they Site Owners. However they can still share a site, they are a member of, with external users.


New and existing external users (sign-in required)

Require external users who have received invitations to view sites or content to sign-in with a Microsoft account before they can access the content.
Site owners or others with full control permission can share sites with external users.
Site owners or others with full control permissions on a site can share documents with external users.
All external users will be required to sign in before they can view content.
Invitations to view content can be redeemed only once. After an invitation has been accepted, it cannot be shared or used by others to gain access.



Joe Vasil

Senior Premier Field Engineer
Office 365 - SharePoint Online
US PFE - East Region

Office: +1 (980) 776-7488
jvasil@microsoft.com<mailto:jvasil@microsoft.com>

[MSFT_logo]

**Comment by MikePlumleyMSFT** [comment]
@Jvasil, agreed, the current text is incorrect for the default settings. I've updated the article.

**Comment by Jvasil** [comment]
Excellent! Thanks Mike

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
