### ISSUE TITLE
Need more information about SPO default ranking models

### ISSUE THREAD

**Issue by KimiyoSei** [MicrosoftDocs/OfficeDocs-SharePoint#571]
there are more ranking models In SharePoint Online like below. please inform about them
-MainResultsDefaultRankingModel
-O16 MainResultsDefaultRankingModel
-Highlights ranking model

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b84aa98d-55e2-d8fe-02b7-acbd27657a20
* Version Independent ID: 19e3fbe0-a505-dcaa-14e9-3f4ad8f9782b
* Content: [SharePoint Server での検索結果の概要](https://docs.microsoft.com/ja-jp/sharepoint/search/overview-of-search-result-ranking)
* Content Source: [SharePoint/SharePointServer/search/overview-of-search-result-ranking.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/overview-of-search-result-ranking.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by lindspea** [comment]
@samanthaw  @AndreaBarr

**Comment by AndreaBarr** [comment]
@tseward Could you please investigate this?

**Comment by tseward** [comment]
@AndreaBarr this will need to go to the PG.

**Comment by scanum** [comment]
@tklarsen Hi Tone! Hope you are doing well. Could you please help us with taking this to the PG? Thanks

**Comment by scanum** [comment]
@tklarsen Hi Tone, any updates on this?

**Comment by scanum** [comment]
@tklarsen Hi Tone, following up on this. Please let me know if there is anything I can do to help.

**Comment by lindspea** [comment]
@tklarsen

**Comment by tseward** [comment]
Folks, I do not believe we'll get an answer on this one. Microsoft may want to keep the models internal only and/or these models continuously change. I would suggest closing this.

**Comment by lindspea** [comment]
@scanum please close this one, thanks.

**Comment by scanum** [comment]
@KimiyoSei Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
