### ISSUE TITLE
Microsoft SharePoint Migration Tool, 10 items limit in CSV ! ?

### ISSUE THREAD

**Issue by DougPunchak** [MicrosoftDocs/OfficeDocs-SharePoint#577]
When using the SharePoint Migration Tool, the CSV file fails if I have more than 10 rows in the CSV file.  Is this a limit that can be changed?

**Comment by DougPunchak** [comment]
I'm referring to the Microsoft Provided SharePoint migration tool and using the CSV file.
https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

**Comment by tseward** [comment]
@AndreaBarr assign to me.

**Comment by DougPunchak** [comment]
Hi Andrea,
Any information or assistance you can provide would be very helpful.  Doing only 10 at a time is very time consuming.

**Comment by tseward** [comment]
@DougPunchak Working on it :-)

**Comment by tseward** [comment]
I just ran this local drive to SPO site migration without issue. There are 20 line items. Can you describe in more detail as to what you're migrating/seeing as the output? I don't think there is an actual limit and if that is the case, we'd want you to open up a thread in the technical support forum at https://techcommunity.microsoft.com/t5/SharePoint/ct-p/SharePoint.

```
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents2,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents3,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents4,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents5,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents6,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents7,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents8,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents9,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents10,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents11,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents12,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents13,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents14,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents15,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents16,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents17,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents18,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents19,,
C:\Office365Logs,,,https://tenantName.sharepoint.com,Documents20,,
```

**Comment by DougPunchak** [comment]
Thanks Trevor,
It looks like the issue wasn't with the tool but more with the error reporting. We had 21 items in a CSV and we weren't a collection admin for 1 of them (actually, OneDrive wasn't even provisioned).  The message was "Task 1. You must be a site collection administrator in the destination to perform this task."
I guess this could have been avoided if the error message told us which destination URL we didn't have access to.
Is there anywhere we can submit a 'feature enhancement' to better report errors like this?

**Comment by tseward** [comment]
@DougPunchak Yes, please go here to submit a feature request (or see if it has already been submitted):

https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365

**Comment by scanum** [comment]
@DougPunchak  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
