### ISSUE TITLE
Missing SharePoint Online Limit - 10,000 unique token limit

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/OfficeDocs-SharePoint#578]
During a recent customer escalation, the SAI team (contact was Chris Mitchell) confirmed that SPO has a 10,000 limit on the number of unique body tokens. This limit is not documented on this page, which can result in customer dissatisfaction and potential GDPR liability. Please update this page with this limit (after confirming with the SAI team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171ee42a-95a9-6543-dd99-696ba7025cd0
* Version Independent ID: a3b3b40f-b808-7ac6-b420-a9b7bb0361fb
* Content: [Search limits for SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/search-limits?redirectSourcePath=%252farticle%252f7c06e9ed-98b6-4304-a900-14773a8fa32f)
* Content Source: [SharePoint/SharePointOnline/search-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/search-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by nenonix** [comment]
@MSFTEfeedback  Thank you for this helpful feedback. We will contact the SAI team to confirm.

**Comment by tklarsen** [comment]
Working on this.
