### ISSUE TITLE
Minimum SharePoint 2013 Build Number for upgrade

### ISSUE THREAD

**Issue by SubhanAhsan** [MicrosoftDocs/OfficeDocs-SharePoint#582]
This page tells minimum required build is March 2013 PU (15.0.4481.1005) for migrating to SharePoint 2016. On other pages, it refers to SharePoint 2013 SP1.
Its not clear if database-attach is supported from SharePoint 2013 without SP1 to SharePoint 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 674623db-614a-e72f-dddd-63ec00af6bb8
* Version Independent ID: 65f1e16f-d9f9-3497-05e5-d0a139b33a66
* Content: [Overview of the upgrade process to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/overview-of-the-upgrade-process)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/overview-of-the-upgrade-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/overview-of-the-upgrade-process.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by tseward** [comment]
@kenwith @AndreaBarr FYI this one has multiple PRs

@SubhanAhsan I *think* I got all of them, but after this is merged into Live and you find others, open a new Issue and I'll follow up.
