### ISSUE TITLE
Microsoft has deprecated AzureRm

### ISSUE THREAD

**Issue by mcnaugha** [MicrosoftDocs/OfficeDocs-SharePoint#583]
This article could do with the PowerShell section being updated to the latest syntax required with the new Az commands. The experience now seems to be more complicated than this article would elude.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93351c-948b-67f7-edd7-8f84982f1834
* Version Independent ID: b3d722cc-3e6e-9b0a-efdb-7d61a76c874f
* Content: [Find your Office 365 tenant ID](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id)
* Content Source: [OneDrive/find-your-office-365-tenant-id.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/find-your-office-365-tenant-id.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
