### ISSUE TITLE
Add Prerequisites/Requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#584]
Please add some information about the security requirements that must be met to do this, i.e, what roles can do this, I'm assuming a SPO Admin and what version of the SPO Management shell is needed to get the cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd09eee5-c545-e689-1194-e6b6cd70d63c
* Version Independent ID: 81523a20-4bed-a41c-9f5e-e5b5200d2f75
* Content: [Set up a site design for your hub site](https://docs.microsoft.com/en-us/sharepoint/set-up-site-design-hub-site)
* Content Source: [SharePoint/SharePointOnline/set-up-site-design-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/set-up-site-design-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
