### ISSUE TITLE
If we want to remove "Create Site" command only

### ISSUE THREAD

**Issue by Chatou7** [MicrosoftDocs/OfficeDocs-SharePoint#585]
If we remove the "Create Site" links, will the users still be able to create Teams and Groups ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29978b1-a400-bacb-1330-55ed3d652053
* Version Independent ID: eae9fd16-57fc-1a80-3ce9-9b34b68eb1e0
* Content: [Manage site creation in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation)
* Content Source: [SharePoint/SharePointOnline/manage-site-creation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-creation.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@AndreaBarr Please assign to me.

@Chatou7 Yes, you can still create Teams (thus Groups) and the SharePoint Online site via Teams if you disable Create Site via the SPO Admin Center. The setting you reference causes the button to disappear from the SharePoint Home.

**Comment by Chatou7** [comment]
@AndreaBarr : Sorry for this late response ... did not see the notification earlier ... 
Yes, for sure. Thanks a lot :-)
