### ISSUE TITLE
Web Application URL verses public i.e load balanced URL

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/OfficeDocs-SharePoint#59]
When you are referring to the http://Web_application_public_URL, are you referring to the default zone ( internal web application URL) or the public intranet zone URL.  The later could change if a load balancer and or SSL  is configured at sometime after the original installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaac1f4e-14d7-4c36-6968-e10fcdab12de
* Version Independent ID: 290f10e2-1dfe-0fd9-38a0-bbe20cbb54a9
* Content: [Best practices for crawling in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/best-practices-for-crawling)
* Content Source: [SharePoint/SharePointServer/search/best-practices-for-crawling.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/best-practices-for-crawling.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
Waiting for feedback from product team.

**Comment by tseward** [comment]
@westerdaled Yes it refers to the Default Zone URL. You should only crawl the Default Zone URL, regardless of what that URL is. If you update the Default Zone URL, you would need to adjust the URL on the Content Source.

**Comment by kenwith** [comment]
@tseward - this is great info! Would you mind adding it as a Pull Request so we can get it in the official doc above?
