### ISSUE TITLE
Module MSOnlineExtended replaced with MSOnlineExt

### ISSUE THREAD

**Issue by JonathanHerschel** [MicrosoftDocs/OfficeDocs-SharePoint#590]
Under step 10, Import-Module MSOnlineExtended -force shows error that it is not valid module.
Should be replaced by Import-Module MSOnlineExt -force.  I couldn't figure it out and found others had same issue: https://social.msdn.microsoft.com/Forums/en-US/73512b3a-b186-4ad0-9b1d-507c285b4103/how-to-install-msonlineextended-module-?forum=WindowsAzureAD
After I replaced MSOnlineExtended with MSOnlineExt, I was able to proceed.   thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d499cfa0-9a8e-37c8-4607-874d3d72ed69
* Version Independent ID: 267ded1d-8e8d-3d11-44b4-3e83c70d40c8
* Content: [Configure server-to-server authentication from SharePoint Server to SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-server-to-server-authentication)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
Hi @JonathanHerschel.  Thank you for pointing this out and for your valuable contribution in helping improve MS docs.  I will work to have the changes made as soon as possible. 
@scanum @AndreaBarr
