### ISSUE TITLE
Is there any way to set web-limited access for all OneDrive users instead of just one account?

### ISSUE THREAD

**Issue by liutiger27** [MicrosoftDocs/OfficeDocs-SharePoint#591]
I think our use case is a common use scenario. We would like enable the web-limited access for all of our OneDrive files. We do not want the restrictions to apply to other SharePoint collections. 

How could we achieve this?

The power shell command give us this error, and I don't see why we should do this on each user's account. (considering there are thousands of users). 

PS C:\WINDOWS\system32&gt; Set-SPOSite -Identity https://CompanyName-my.sharepoint.com -ConditionalAccessPolicy AllowLimitedAccess
Set-SPOSite : The property ConditionalAccessPolicy cannot be set on the MySite host.
At line:1 char:1
+ Set-SPOSite -Identity https://CompanyName-my.sharepoint.com -Conditiona ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOSite], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetSite

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by SanjoyanM** [comment]
You can go ahead a file a DCR for this.

**Comment by kaarins** [comment]
@SanjoyanM, will do - thank you! @liutiger27, thank you for this feedback. I will file it as a change request for this feature.
