### ISSUE TITLE
Word missing from sentence

### ISSUE THREAD

**Issue by statto1974** [MicrosoftDocs/OfficeDocs-SharePoint#592]
"Instead certain of the classic search settings also apply to the modern search experience" should probably be something like "Instead certain aspects of the classic search settings also apply to the modern search experience"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f89b7-afd4-1b65-f3ad-c802c7dd5a47
* Version Independent ID: 0f3e61c4-6b03-dccb-6067-09ed98228f62
* Content: [Differences between the classic and modern search experiences in SharePoint Online](https://docs.microsoft.com/en-us/SharePoint/differences-classic-modern-search)
* Content Source: [SharePoint/SharePointOnline/differences-classic-modern-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/differences-classic-modern-search.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
@AndreaBarr Assign to me, please.
