### ISSUE TITLE
Typo in the page

### ISSUE THREAD

**Issue by krisdasword** [MicrosoftDocs/OfficeDocs-SharePoint#6]
This is "know" as a managed path
URL -  https://docs.microsoft.com/en-us/SharePoint/administration/define-managed-paths

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1358d198-0bf5-9f7f-88d8-a039b95fc040
* Version Independent ID: 5596582e-67ce-0ab2-3ab1-ba226d119d46
* Content: [Define managed paths in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/define-managed-paths)
* Content Source: [SharePoint/SharePointServer/administration/define-managed-paths.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/define-managed-paths.md)
* Service: **unspecified**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Fix in the queue for next merge.
