### ISSUE TITLE
Dedicated server vs Dedicated Instance

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#60]
Does the recommendation for a Dedicated Server mean that we should not have multiple Instances on the same Server, i.e. a SharePoint Instance and another Instance for other line-of-business application databases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588cac-efbb-da8f-8b1f-8f4a21298116
* Version Independent ID: d5fead27-6212-5bc7-5bbf-9ce2066f479d
* Content: [Best practices for SQL Server in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm#use-a-dedicated-server-for-sql-server)
* Content Source: [SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
Yes, it should be dedicated. There are considerations of contention between multiple instances on the same SQL Server. These can be mitigated, but the 'use a dedicated server' is going to be the best guidance available.

**Comment by Techwriter40** [comment]
@bentoncity for awareness
