### ISSUE TITLE
SMAT Tool will not open on Server 2008 R2 SharePoint 2010

### ISSUE THREAD

**Issue by StacyRacks** [MicrosoftDocs/OfficeDocs-SharePoint#606]
Hello,

We've downloaded the most recent version of the SMAT tool and when attempting to run it, the initial command line -esque window opens says that SMAT is gonna run, then that window closes and nothing happens.  The build is version 14.0.7175.5000.  

If we try to run SMAT2010, it errors out and says 

This tool detects the version of SharePoint and launches the
appropriate scan engine. The scan engine will start in a new console
window and this program will exit.

Thank you for using the SharePoint Migration Assessment Tool!

D:\190122-07812\SMAT_RTM_Update6_1&gt;smat2010.exe -sv

A failure occurred. Error: SMAT2010.exe is only supported on
SharePoint 2010 installations. Run SMAT.exe directly to have the
tooling determine the correct executable to run on this
installation.

D:\190122-07812\SMAT_RTM_Update6_1&gt;

Please advise on what we can check to get this to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c27cc7d-bb92-c1bc-4330-ae2bb54846bc
* Version Independent ID: f14f15f3-e079-a6c6-d9ef-d7698f2e989f
* Content: [Overview of the SharePoint Migration Assessment Tool](https://docs.microsoft.com/en-us/sharepointmigration/overview-of-the-sharepoint-migration-assessment-tool)
* Content Source: [migration/overview-of-the-sharepoint-migration-assessment-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-of-the-sharepoint-migration-assessment-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by StacyRacks** [comment]
Hi,

Another thing to note:  The logging does not appear to be happening, At ALL.  I ran SMAT.exe -o <path> where <path> is the path to where the SMAT.exe is located, this command said it completed, but still same behavior of the SMAT tool.

**Comment by StacyRacks** [comment]
Made sure WSS_ADMIN_WPG local group has full control on the directory where SMAT.exe and the other files are located.

**Comment by scanum** [comment]
@StacyRacks Thank you very much for your kind feedback. We recommend logging it in [Uservoice](https://sharepoint.uservoice.com/). The concerning team will evaluate and take the appropriate action, as per their schedule. We appreciate you taking out some time and sharing your feedback to make the product and service better.

**Comment by useyourblinker** [comment]
Did this issue find a resolution for anyone? I am experiencing the same thing on two Sharepoint 2010 sites, and the documentation for troubleshooting is scant (read: doesn't exist). We have lots of sites that were using SBS2011 that need to finally move to the cloud, but are stuck with manual migrations and dealing with whatever troubleshooting needs to be done, due to the lack of SMAT.
