### ISSUE TITLE
Does this article apply to SharePoint Online as well?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-SharePoint#607]
I was redirected to this article from Office 365 DLP page: https://docs.microsoft.com/en-us/office365/securitycompliance/data-loss-prevention-policies#how-dlp-policies-work. I was surprised to see that this article doesn't apply to SharePoint Online. Could you please verify if this article really doesn't apply to SPO. If it is true where can I find an article describing files indexed by SharePoint Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca49f43-3737-be54-f95f-0e510c892143
* Version Independent ID: 0d3fb4e8-008a-a864-5702-20dc966f3856
* Content: [Default crawled file name extensions and parsed file types in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types)
* Content Source: [SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/default-crawled-file-name-extensions-and-parsed-file-types.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by dplotnikov** [comment]
hey @pawp81 as you can see, there is a reference to SPO in the Note section but looks like you were confused by the fact that SPO wasn't marked as supported in **APPLIES TO:** section. Did I miss something?

**Comment by pawp81** [comment]
Yes. This article seems to indicates that SPO is not supported. There is "X" icon next to SPO.

**Comment by dplotnikov** [comment]
hey @pawp81 I've made a pull request to this article just to specify that it's accurate for SPO as well and it should be fine after someone will merge my change. Please let me know if you still have any questions here.
