### ISSUE TITLE
Does not work on SharePoint 2016?

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint#608]
There is no mention of SharePoint 2016 and it did not let me log in to my SharePoint 2016.
Any plan to migrate a whole site collection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@Ofer-Gal SharePoint 2016 is not supported at this time.

@scanum please close.
