### ISSUE TITLE
SPMT question: use Migration Tool libraries in .NET project

### ISSUE THREAD

**Issue by vtkachenko** [MicrosoftDocs/OfficeDocs-SharePoint#611]
I'm very interested in **implementing .NET application for migrating the sites from on-premise SP 2013 to SPO** and want to utilize SharePoint Migration Tool resources ( `microsoft.sharepoint.migrationtool.migrationlib.dll` in particular) to achieve it. Basically - it should be old SharePoint 2013 webpart, server-side .NET code on every site. Call it "Migration Wizard", for example:

![image](https://user-images.githubusercontent.com/2527647/51831695-6cdbf180-22fb-11e9-91e3-c0d6ab466d29.png)

In short - I want [to do the same](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets) in .NET, that you guys do in `Microsoft.SharePoint.MigrationTool.PowerShell`. I can include the reference to `Microsoft.Sharepoint.Migrationtool.Migrationlib.dll` and try using the same classes and actions, but:

1. I didn't find any **documentation of using SPMT in .NET projects**. Can somebody help me out to do that?
2. I'm concerned about the **SESSION**, which is created by PowerShell - and don't know, how to do it in .NET code. Is it better to use "RegisterSPMTMigration" class from `Microsoft.SharePoint.MigrationTool.PowerShell` ?
3. Are there any plans to **make SPMT code open-source** in future? That would be a great step, I suppose!

P.S. Great work with SharePoint Migration Tool **v3.0.104.2 Beta**, guys! It resolved a bunch of issues from prev releases! Thanks and keep up great work!)

**Comment by tseward** [comment]
SPMT libraries are not designed/packaged to use with your own projects. You can use the SharePoint APIs to create your own migration tool, though.

As this repository is for documentation feedback, I'd suggest you post in the product feedback at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365.

**Comment by vtkachenko** [comment]
Thanks for the answer, @tseward ! Usage of Migration API in our own small, customer-specific migration tool requires much more coding, while Migration Tool does the same job out-of-the-box - that was the reason on asking. 

As you suggested - I added a [post in UserVoice ](https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/36658378-allow-spmt-libraries-to-be-used-as-a-source-in-our) with that suggestion - let's see, whether it's supported by the community or not.

What about my question 3 - **plans to make migration tool open-source?** Any plans to do it in future?

**Comment by tseward** [comment]
@vtkachenko I can't speak for Microsoft but there are no announced plans to do so. Again, I'd suggest adding that request to UserVoice.

**Comment by vtkachenko** [comment]
> 
> 
> @vtkachenko I can't speak for Microsoft but there are no announced plans to do so. Again, I'd suggest adding that request to UserVoice.

Thanks! It's already [done in June 2018](https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/34657027-open-source-the-sharepoint-migration-tool). I voted for that as well.

**Comment by vtkachenko** [comment]
Any comments from **SPMT team** regarding the questions above are greatly appreciated! If the answers are the same, as Trevor said - we can close the issue for now, I guess.

**Comment by tseward** [comment]
@scanum please close. @vtkachenko since this repository is for the documentation of the product, Uservoice would be the best place to get any answers.
