### ISSUE TITLE
Upgrade of User Profile Service Application is missing

### ISSUE THREAD

**Issue by DennisGoss** [MicrosoftDocs/OfficeDocs-SharePoint#612]
The overview page (https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/overview-of-the-services-upgrade-process-2019) seems to indicate that this page should include the User Profile Service app upgrade steps. There are 2 mentions of User Profile on this page but seem to be mistakes in the Performance Point section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97493854-efe6-3451-d96b-a04b6ac32075
* Version Independent ID: 46b84a4a-fbe2-5afc-f442-13d8411e395e
* Content: [Upgrade service applications to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@DennisGoss Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
