### ISSUE TITLE
Incorrect information in user profile upgrade section.

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#613]
？ ＆  

 

Hi i think there is typo / copy paste error in this article, when you look at the user profile upgrade steps, there is a line that talks about getting the Id for the search service application, but we are in the user profile service? So i think the mention of search service is incorrect here?

6.Create the User Profile service application proxy and add it to the default proxy group by completing these actions:

•Type the following command to get the ID for the Search service application and store it as a variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67cc68b-2d40-7d78-9ae5-a71938b6fa78
* Version Independent ID: 52fd8de6-598e-7672-eb34-2fa7a46b0182
* Content: [Upgrade service applications to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016#upgrade-the-user-profile-service-application)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@obhayes  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
