### ISSUE TITLE
Fileshare Migration and Full Control permission

### ISSUE THREAD

**Issue by jerryyasir** [MicrosoftDocs/OfficeDocs-SharePoint#614]
Is there any timeline when the tool will be able to handle the full control permissions? I tried few migrations and users with full control were granted contribute permissions on the files and folders which is kind of show stopper for the migrations.  Any work around availalbe?

**Comment by tseward** [comment]
Full Control is roughly analogous to Contribute. FC allows create/edit/delete as does the contribute right in SharePoint.

**Comment by jerryyasir** [comment]
>           Full Control is roughly analogous to Contribute. FC allows create/edit/delete as does the contribute right in SharePoint.

Trevor, The problem is that contribute permission level does not have "Manage Permissions" permission.  The migration I am talking about have 100s of folders with deep with different owners. after migration permission inheritance is broken and owner become a contribute and then he can't share the folder or sub folders with anyone.  This is where we have to involve SCA to manage permissions resulting in very high number of tickets.

**Comment by jerryyasir** [comment]
I am not getting the point on why dev team restricted permission to read and contribute only while they were enumerating the file share content permissions anyway.

**Comment by tseward** [comment]
Contributors can share a document in SharePoint provided that the site allows it -- you don't need Owner rights to do so.

Manage Permission is a high level right in SharePoint and I can see why they would do this as the current design/thinking in SPO is to have Owners, Members (via Office 365 Groups), and Viewers with no break in inheritance and so on. Instead, the current thinking is that where you'd need such a break in permissions, you'd isolate those assets into their own sites so they wouldn't require a break in inheritance. I get that this doesn't fit every need, but it is the model Microsoft is currently trying to drive towards.

**Comment by jerryyasir** [comment]
Does not work in case of this customer with over 200 file shares.  We have already broken large folders in smaller pieces for smaller migration batches but can't go deeper that 2 levels.  This is a serious limitation of the tool and would be great if we can find a workaround or may be timeline for fix. Thanks

**Comment by tseward** [comment]
I would suggest posting your feature request at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365. The engineering teams look over all requests to prioritize them appropriately.

**Comment by jerryyasir** [comment]
Done.  Thanks Trevor.

**Comment by tseward** [comment]
@scanum please close.
