### ISSUE TITLE
PowerShell command

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/OfficeDocs-SharePoint#616]
Please provide the PowerShell command used to configure this file blocklist in an Office365 tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@SwiftOnSecurity , thanks for this feedback. I'm adding the link to the PowerShell documentation now!
