### ISSUE TITLE
wrong tagging. Tag this for SP2016 

### ISSUE THREAD

**Issue by JamesRajavarman** [MicrosoftDocs/OfficeDocs-SharePoint#619]
I face the behavior mentioned in the below link in SP2016 as well. Hence update this article, tag this in SP2016 as well. 

https://docs.microsoft.com/en-us/SharePoint/administration/maintain-profile-synchronization#remove-obsolete-users-and-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a839181-5593-8258-d7c3-62fe07006469
* Version Independent ID: da4b5d7f-e9a0-e216-f543-02cc623324df
* Content: [Maintain user profile synchronization settings in SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/maintain-profile-synchronization)
* Content Source: [SharePoint/SharePointServer/administration/maintain-profile-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/maintain-profile-synchronization.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@JamesRajavarman  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
