### ISSUE TITLE
Mobile experience for SP 2016

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#62]
Where is the content about mobile devices for SP 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38a7e64-2648-48a2-0b57-5af4a5d99ec7
* Version Independent ID: af9ef4d2-dfca-f44f-cfe5-050cf2e963bf
* Content: [Overview of mobile devices and SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/mobile-devices-overview#see-also)
* Content Source: [SharePoint/SharePointServer/administration/mobile-devices-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/mobile-devices-overview.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tomresing** [comment]
Hi Dean, Thanks for reading and commenting. The most significant change around the 2016 release is the addition of the mobile app. If you're interested, you can read more in the last article of this section, Supporting the SharePoint mobile apps online and on-premises.

**Comment by DeanGross** [comment]
Ok, thanks for the quick response and your statement is consistent with my understanding. I think that it would be helpful if this discussion clearly stated that it applies to 2016 also, this would eliminate any ambiguity. Many pages do state that they apply to both, and when a page does not, it begs the question.

**Comment by tomresing** [comment]
Agreed. If you were to submit a pull request with the changes, I would be happy to review for quick publishing.

**Comment by kenwith** [comment]
@DeanGross - thanks for taking the time to identify this gap and thanks Tom for the info! I have gone ahead and created the request in the SharePoint writers team backlog and they can get it prioritized. I looked through the documentation for 2013 too and was really excited to find the article Tom pointed out. It would definitely be great to have more info in that area. Also, as Tom mentioned if you are open to submit a Pull Request to share some of your expert knowledge in the area the community would be ever grateful or if you prefer to open an issue with a request that is always welcome too. Thanks again!
