### ISSUE TITLE
The PDF link for "Microsoft SharePoint Servers 2016 and 2019 MinRole Topology" refers to a visio

### ISSUE THREAD

**Issue by trir262** [MicrosoftDocs/OfficeDocs-SharePoint#626]
The section "Microsoft SharePoint Servers 2016 and 2019 MinRole Topology" provides two downloads: a visio and a pdf. However the link for the pdf downloads a visio as well.
pdf link = http://download.microsoft.com/download/5/F/4/5F4107F5-ECFA-49EA-A02A-799D9EAFB03C/MinRole_Topology_Tabloid_Nov2018.vsdx
visio link = https://go.microsoft.com/fwlink/?linkid=837452, which in turn refers to the same link as the pdf link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf2e5c6-3ad1-d485-9dc0-30f246ea61da
* Version Independent ID: 67f737d9-e522-06ab-bffa-081f0c86a88b
* Content: [Technical diagrams for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/technical-diagrams)
* Content Source: [SharePoint/SharePointServer/technical-reference/technical-diagrams.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/technical-diagrams.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@trir262 the product group is investigating this. I'll get back to you when I have more info/can update the article.

**Comment by angoo-atea** [comment]
All the Search and Database reference PDF lins are also to Visio diagrams.

**Comment by tseward** [comment]
@Techwriter40 can you please take a look?

**Comment by scanum** [comment]
@Techwriter40 Hi Kirk, any updates? Thanks!

**Comment by scanum** [comment]
@MikePlumleyMSFT Hi Mike, could you please assist us with next steps? Thanks!

**Comment by MishaTravis** [comment]
Links corrected - https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/1393
