### ISSUE TITLE
Yammer with SP 2016

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#63]
Where is this content for SP 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8d833d-52ed-69a0-efa2-d395a1be8839
* Version Independent ID: 7f3b837d-61c5-1251-1585-a5df05b1690c
* Content: [Integrate Yammer with on-premises SharePoint 2013 environments](https://docs.microsoft.com/en-us/sharepoint/administration/integrate-yammer-with-on-premises-sharepoint-2013-environments)
* Content Source: [SharePoint/SharePointServer/administration/integrate-yammer-with-on-premises-sharepoint-2013-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/integrate-yammer-with-on-premises-sharepoint-2013-environments.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by IrenePasternack** [comment]
SharePoint Server integration with Yammer files have now been updated to include SharePoint Server 2016.
