### ISSUE TITLE
"& を = en)。" needs to be replaced with "&displaylang=en)."

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SharePoint#633]
https://docs.microsoft.com/ja-jp/sharepoint/administration/performance-testing

(http://www.microsoft.com/downloads/details.aspx?FamilyId=718447d8-0814-427a-81c3-c9c3d84c456e& を = en)。
 → 
(http://www.microsoft.com/downloads/details.aspx?FamilyId=718447d8-0814-427a-81c3-c9c3d84c456e&displaylang=en).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5724d1c4-32e6-afcf-9d12-42c21df1c1ee
* Version Independent ID: aceb8897-78f4-05cd-a39f-1a22b8b7be0a
* Content: [Performance testing for SharePoint Server 2013](https://docs.microsoft.com/en-us/sharepoint/administration/performance-testing)
* Content Source: [SharePoint/SharePointServer/administration/performance-testing.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/performance-testing.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jamesrhea** [comment]
Thanks for the feedback, @hyoshioka0128. Several links in that article are not formatted correctly. We'll look into this issue.

**Comment by scanum** [comment]
@hyoshioka0128  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot Close

**Comment by scanum** [comment]
@officedocsbot Could you please look at this? Thanks.
