### ISSUE TITLE
Error in documentation for search service application upgrade

### ISSUE THREAD

**Issue by desmondkung** [MicrosoftDocs/OfficeDocs-SharePoint#635]
1) Start the SharePoint 2019 Management Shell.
2) Set the Search Administration database to read-only. In the second phase of the process to upgrade SharePoint Server 2016 data and sites to SharePoint Server 2019, you set all the other databases to read-only. Follow the same instructions now for the Search Administration database.
3) Pause the Search service application. At the PowerShell command prompt, type the following command:

Point 1 should be SharePoint 2016 Management Shell. Point 2 and 3 should swap order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97493854-efe6-3451-d96b-a04b6ac32075
* Version Independent ID: 46b84a4a-fbe2-5afc-f442-13d8411e395e
* Content: [Upgrade service applications to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019#upgrade-the-search-service-application)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@desmondkung Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
