### ISSUE TITLE
Remove IE10 support for SP2016

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint#636]
Since IE10 isn't supported on Windows 7 anymore (https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support), shouldn't this version be removed from the supported browser list for SP2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5d1b075-d17b-510d-f886-4f5deed4cc9e
* Version Independent ID: 336f78e0-78e2-0a55-5e1b-2bf41072a0cb
* Content: [Plan browser support in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/SharePoint/install/browser-support-planning-0#key-planning-phase-of-browser-support)
* Content Source: [SharePoint/SharePointServer/install/browser-support-planning-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/browser-support-planning-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Unless the SharePoint PG changes something in the product, no.

**Comment by ykuijs** [comment]
Which would mean that SharePoint 2016 supports a product that isn't even supported by the Internet Explorer PG. Sounds a bit strange.

**Comment by kilasuit** [comment]
Surely this should be "supported with limitations" / "Supported by not recommended"
