### ISSUE TITLE
Support for SharePoint 2010

### ISSUE THREAD

**Issue by ziffo777** [MicrosoftDocs/OfficeDocs-SharePoint#637]
Hi, are you planning to support SharePoint 2010 in the near future? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
I would suggest posting this on Uservoice at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365 which will let the engineers know you have an interest in using the tool to migrate from 2010 to SPO.
