### ISSUE TITLE
Deploy updates missing for SharePoint 2019

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint#638]
According to the "Applies To" section, the current Deploy updates section only applies to SharePoint 2016. However articles on how to apply updates to SharePoint 2019 are missing.

Can the current articles either be updated to also apply to SharePoint 2019 or a new set of articles for SharePoint 2019 added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb410df-2cc3-9a2c-c083-46bb5c9ea3fa
* Version Independent ID: ba4cf001-91aa-221c-147b-1a79d645d619
* Content: [Deploy software updates for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/deploy-updates-for-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/deploy-updates-for-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/deploy-updates-for-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
