### ISSUE TITLE
Applicability to SP2016

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#64]
How do these recommendations apply to SP 2016, if at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da68dc34-edaa-5bdd-674f-a8e4638fde48
* Version Independent ID: b45c67c0-0f24-6f68-0bd3-17c27e9d1d05
* Content: [Performance and capacity test results and recommendations (SharePoint Server 2013)](https://docs.microsoft.com/en-us/sharepoint/administration/performance-and-capacity-test-results-and-recommendations-for-sharepoint-2013)
* Content Source: [SharePoint/SharePointServer/administration/performance-and-capacity-test-results-and-recommendations-for-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/performance-and-capacity-test-results-and-recommendations-for-sharepoint-2013.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by Techwriter40** [comment]
@JoanneHendrickson for awareness

**Comment by kenwith** [comment]
I noticed an article specifically for 2016 and a link was added to this one. Here is the link: https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits-0  I also know this is on the radar of the writing team as they are preparing for 2019. Thanks for taking the time to provide feedback.
