### ISSUE TITLE
Missing Required "EnableTeamTier_Internal" registry Key

### ISSUE THREAD

**Issue by mikelee-msft** [MicrosoftDocs/OfficeDocs-SharePoint#640]
This document is missing the required "EnableTeamTier_Internal" registry key. It used to be referenced in a ZIP file in the requirements section, but it has been removed.

Example:

Opt-in to the Insiders Program for OneDrive

1.	Currently On-prem sync functionality is only available to users that are part of the OneDrive “Insiders” program. You can opt-in to the program using the following registry key addition:

reg.exe add HKCU\SOFTWARE\Microsoft\OneDrive /v EnableTeamTier_Internal /t REG_DWORD /d 1 /f

2.	After adding the registry key, new settings will be added to OneDrive. These setting are stored in a file name “PreSignInSettingsConfig.json”. 
	
 	Note: This file is automatically refreshed every 24 hours, but it can be manually refreshed by deleting the setting files and re-starting the OneDrive client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0d9527-a78b-d18b-d218-881fac11423d
* Version Independent ID: 3ad8fc7b-4869-dbdc-802b-a804f65d0e39
* Content: [Configure syncing with the new OneDrive sync client for Sharepoint 2019](https://docs.microsoft.com/en-us/sharepoint/install/new-onedrive-sync-client#feedback)
* Content Source: [SharePoint/SharePointServer/install/new-onedrive-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/new-onedrive-sync-client.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

@mikelee-msft any idea about how long this will be valid (i.e. when this will go into the production ring of release)?

**Comment by mikelee-msft** [comment]
Just had a quick conversation with the PG contact for NGSC. It looks like the newest build no longer requires this flag. I guess we close this feedback since it's not needed.
