### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by SteveHernou** [MicrosoftDocs/OfficeDocs-SharePoint#644]
Hi, I have been trying to install the tool (tested 2 devices, 2 browsers on each - Edge and Chrome) but it always fails.
Error is always the same in the log file.
* Activation of https://spmtreleasescus.blob.core.windows.net/build-firstrelease/build-firstrelease.application resulted in exception. Following failure messages were detected:
		+ Downloading http://spmtreleasescus.blob.core.windows.net/build-firstrelease/migrationtoolinstall/libcef.dll.deploy did not succeed.
		+ Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
		+ An existing connection was forcibly closed by the remote host

P.S. Even though I did not select 'Install first release', the URL seems to point to the first release build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Steve:  Investigating this now.

**Comment by SteveHernou** [comment]
Hi Joanne, seems like 'Abenold' is experiencing something similar. Same dll is showing in his log.

**Comment by scanum** [comment]
@JoanneHendrickson any updates on this? Thanks!

**Comment by kalyanThumu** [comment]
@JoanneHendrickson Any updated on this, still not able to install the software.

**Comment by JoanneHendrickson** [comment]
Please see https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues for help -- specifically this section:

**Download the tool instead**

If you still are experiencing unexplained errors, try downloading the SPMT tool to your local computer.

1. Download zip package to your local computer: Download SPMT.zip package.
2. Right-click the zip file, and click properties.
3. On the General tab, select Unblock and then click OK.
4. Open the zip file and extract all files.
5. Run the build.application file.

We have found downloading the tool first resolves the issue for people experiencing this. Hope this helps.
