### ISSUE TITLE
Onedrive autosetup Signin not working anymore for new machines post client update to 18.240.1202.0004

### ISSUE THREAD

**Issue by rstilekar** [MicrosoftDocs/OfficeDocs-SharePoint#645]
We are testing onedrive on our new Win10 machines. WE had previous onedrive client from December that works great with the GPO settings for "Silently sign in users to the OneDrive sync client with their Windows credentials". It was working great on all new PCs. But now the onedrive client is updated to 18.240.1202.0004 and the auto signin doens't works although i can see the GPO set in gpresult on local machine as well as in registry path "Datamaskin\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\OneDrive" with SilentAccountConfig setting for dword as 1. All seems good but the sign-in is not triggering itself. IF i manually sign-in with my windows account in onedrive then only its working. I stopped the client updates and installed our old onedrive client from December and it works great but not with the new client 18.240.1202.0004 and also its not working with the Insiders ring client 19.002.0107.0008 that is to be released on 18th Feb this month. 

Please fix the issue with new clients as its only working with earlier clients but not with new ones.

REgards,
Ramakant.

**Comment by scanum** [comment]
@rstilekar Thank you very much for your kind feedback. We recommend logging it in [Uservoice](https://sharepoint.uservoice.com/). The concerning team will evaluate and take the appropriate action, as per their schedule. We appreciate you taking out some time and sharing your feedback to make the product and service better.
