### ISSUE TITLE
Need to specify Temp-path

### ISSUE THREAD

**Issue by MarkvanGurchom** [MicrosoftDocs/OfficeDocs-SharePoint#646]
Hi, is there a variable to set the Temp-path. c:\ is filling-up

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets#feedback)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tseward** [comment]
@MarkvanGurchom Looking at this, I think what you want is to use `Register-SPMTMigrationTask -WorkingFolder <Path>`. See https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps.

By default, the working folder is `%appdata%\Microsoft\MigrationTool`
Let me know if that helps.

**Comment by MarkvanGurchom** [comment]
Thanks... I'll check it next time.


________________________________

Met vriendelijke groet,
Mark van Gurchom
e: mark@cubics.nl
Ringbaan Oost 148a | 5013 CE | Tilburg
t: +31 (0)13 5321486
www.cubics.nl
Onze helpdesk is te bereiken via: +31 (0)13 7507600 of helpdesk@cubics.nl
Denk aan het milieu voordat u deze e-mail print.
disclaimer
Van: Trevor Seward <notifications@github.com>
Verzonden: zaterdag 9 februari 2019 19:20
Aan: MicrosoftDocs/OfficeDocs-SharePoint
CC: Mark van Gurchom; Mention
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Need to specify Temp-path (#646)


@MarkvanGurchom<https://github.com/MarkvanGurchom> Looking at this, I think what you want is to use Register-SPMTMigrationTask -WorkingFolder <Path>. See https://docs.microsoft.com/en-us/powershell/module/spmt/register-spmtmigration?view=spmt-ps.

By default, the working folder is %appdata%\Microsoft\MigrationTool
Let me know if that helps.

**Comment by tseward** [comment]
@MarkvanGurchom Did you have a chance to test this? If so, may we close the issue?

**Comment by MarkvanGurchom** [comment]
Hi Trevor, not yet, but in the next 2-weeks we are going to testdrive with aprox 350GB. I’ll you know how it was


________________________________

Met vriendelijke groet,
Mark van Gurchom
e: mark@cubics.nl
Ringbaan Oost 148a | 5013 CE | Tilburg
t: +31 (0)13 5321486
www.cubics.nl
Onze helpdesk is te bereiken via: +31 (0)13 7507600 of helpdesk@cubics.nl
Denk aan het milieu voordat u deze e-mail print.
disclaimer
Van: Trevor Seward <notifications@github.com>
Verzonden: vrijdag, maart 22, 2019 5:09 PM
Aan: MicrosoftDocs/OfficeDocs-SharePoint
CC: Mark van Gurchom; Mention
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Need to specify Temp-path (#646)


@MarkvanGurchom<https://github.com/MarkvanGurchom> Did you have a chance to test this? If so, may we close the issue?

**Comment by MarkvanGurchom** [comment]
Hi Trevor,


Thanks for your assistance. This did the trick.


But it is an option from the GUI-tool to (maybe its a new feature). This also works.


Best regards,


Mark


________________________________

Met vriendelijke groet,
Mark van Gurchom
e: mark@cubics.nl
Ringbaan Oost 148a | 5013 CE | Tilburg
t: +31 (0)13 5321486
www.cubics.nl
Onze helpdesk is te bereiken via: +31 (0)13 7507600 of helpdesk@cubics.nl
Denk aan het milieu voordat u deze e-mail print.
disclaimer
Van: Mark van Gurchom
Verzonden: vrijdag 22 maart 2019 19:29
Aan: MicrosoftDocs/OfficeDocs-SharePoint; MicrosoftDocs/OfficeDocs-SharePoint
CC: Mention
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Need to specify Temp-path (#646)

Hi Trevor, not yet, but in the next 2-weeks we are going to testdrive with aprox 350GB. I’ll you know how it was


________________________________
Van: Trevor Seward <notifications@github.com>
Verzonden: vrijdag, maart 22, 2019 5:09 PM
Aan: MicrosoftDocs/OfficeDocs-SharePoint
CC: Mark van Gurchom; Mention
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Need to specify Temp-path (#646)


@MarkvanGurchom<https://github.com/MarkvanGurchom> Did you have a chance to test this? If so, may we close the issue?

**Comment by scanum** [comment]
@MarkvanGurchom  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
