### ISSUE TITLE
Please provide PowerShell examples

### ISSUE THREAD

**Issue by dmahendranme** [MicrosoftDocs/OfficeDocs-SharePoint#647]
We received this message yesterday and we are very much concerned. 
https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Delivering-SharePoint-modern-experiences/ba-p/315023

How to disable it through PowerShell for SharePoint Online sites? 
I found this article; https://techcommunity.microsoft.com/t5/SharePoint-Support-Blog/How-to-disable-the-modern-experience-in-SharePoint-2019/ba-p/303649 it seems it is applicable for SharePoint 2019, not Online versions. 

and we have several sites that has both classic list and modern list. What happens if we disable at site collection level? Does it change the existing modern experience lists to classic or ignores it? 
Expected behavior is it should ignore because we have explicitly defined as Modern experience on those lists/libraries. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f1bd4ab-c640-1db8-05bb-e249129dfa46
* Version Independent ID: 4ceb7bc8-39c0-61fb-b31c-381cb7a5018b
* Content: [Change the default list and library experience](https://docs.microsoft.com/en-us/sharepoint/change-default-list-and-library-experience)
* Content Source: [SharePoint/SharePointOnline/change-default-list-and-library-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-list-and-library-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by ldemaris** [comment]
Hello, please see this page for information on how to opt out a site collection or site use PowerShell:
[`Opting out of the modern list and library experience`](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-optout)

If you enable this feature to opt out a site collection, and then you enable modern on a list or library inside that site collection, then that list or library will use modern mode.  The lowest-level setting wins.

**Comment by dmahendranme** [comment]
Thank you @ldemaris . Please include that information in the document. "Lowest-level setting wins". You shall put it under FAQs too.

**Comment by dmahendranme** [comment]
@ldemaris And I tried this PnP example at site collection level. Nothing happens. 
Here are the details;
- Site collection is Classic team site
- Few list are modern and few are classic
- Executed both Disable and Enable scripts

Nothing happens. No change in the list and libraries. 

I have created a new custom list after Disable and Enable. 
It is still creating a Classic custom list. 

Am I missing anything?

**Comment by ldemaris** [comment]
The PowerShell feature can not be used for _enabling_ modern in a site collection.  It can only be used for _disabling_ modern.  Turning the feature on in a site collection will ensure that every list inside that site collection stays classic, unless that list specifies a modern setting.

**Comment by dmahendranme** [comment]
@ldemaris I'm confused here. I see this below line in the documentation
# And again enable modern lists and libraries at site collection level
#Disable-PnPFeature -Identity E3540C7D-6BEA-403C-A224-1A12EAFEE4C4 -Scope Site

But you are saying that this command will not work !!!!! 
Please clarify.

**Comment by ldemaris** [comment]
Thank you for the feedback, the wording in this article could definitely be improved.  Enabling the feature will cause that site collection's lists to stay in classic, unless those lists are configured to use modern.  Disabling the feature will not force all libraries into modern; it will cause those libraries instead to defer to the tenant-wide setting.

**Comment by dmahendranme** [comment]
Thanks @ldemaris 
So, if I try it on or after April 1, 2019, we could see the differences. Am I right? 
Because according to [this](https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Delivering-SharePoint-modern-experiences/ba-p/315023) announcement, tenant's opt out setting will be switched to Modern. 
(Currently my tenant setting is "Classic")

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by kaarins** [comment]
Updated article with the removal of the organization-level setting.
