### ISSUE TITLE
Group Reader

### ISSUE THREAD

**Issue by avisuj** [MicrosoftDocs/OfficeDocs-SharePoint#649]
In sharing in permissions, I believe there is a type.  where it says ". . . be classified as either group owner or a group reader" it should read "be classified as either group owner or a group member".  I'm not familiar with the "group reader" role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bafe04ef-69e9-ade6-9e2a-9e29fa918ee3
* Version Independent ID: 27056c77-62eb-2a5a-2afd-08c2eedb844e
* Content: [Guide to the Modern experience in SharePoint](https://docs.microsoft.com/en-us/sharepoint/guide-to-sharepoint-modern-experience#sharing-and-permissions)
* Content Source: [SharePoint/SharePointOnline/guide-to-sharepoint-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/guide-to-sharepoint-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by tseward** [comment]
@AndreaBarr PR submitted, assign to me please.

**Comment by scanum** [comment]
@avisuj  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
