### ISSUE TITLE
Account Recommendations

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#65]
This article does not dive into a real-world scenario for required/recommended accounts. Since the early days of 2013, Microsoft has leaned towards the usage of a minimal number of accounts to extract the best performance and memory usage out of a farm; there appears to be little value in separating service accounts from a security perspective. It would be great if the article could express Microsoft's recommendations.

In addition, the concept and usage of a 'setup' account really isn't a good idea. From an accountability and audit perspective, shared accounts such as a 'setup' account are a poor choice. In my opinion, the wording of the setup account in this article should change, something along the lines of 'a farm administrator needs these rights...'.

On a formatting issue for this document, the tables appear to be missing info or just formatted incorrectly. Each service has a heading of "Service", "Purpose", "Requirements" which don't have any info in the rows directly underneath. Is something missing here?

@Techwriter40 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0151f1-a178-6675-31df-19b130f4e1c2
* Version Independent ID: 10fb7e98-2870-68c5-5ad2-791beaaca583
* Content: [Plan for administrative and service accounts in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/plan-for-administrative-and-service-accounts.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
I think I got the formatting fixed. This one was a gnarly one with so many tables. When we moved everything from TechNet to the new open source system on GitHub the tables were converted but it is sure a tricky thing to work with them sometimes. Closing this out and agree on your points about the article and would love to get your knowledge into the article as a PR.
