### ISSUE TITLE
 MISSING "set the sync client update ring"

### ISSUE THREAD

**Issue by lifeisgood19** [MicrosoftDocs/OfficeDocs-SharePoint#652]
Downloaded the latest OneDrive Sync Client version available to us which is 19.002.0107.0008 and imported the ADMX template, however it is still missing "Set the sync client update ring" which according to this article should be found under Configuration\Policies\Administrative Templates\OneDrive.

What is the deal here? Is the new template not available until either version 19.012.0121.0005 or 19.017.0128.0003 or did you guys just mess up on this article? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy?redirectSourcePath=%252fen-us%252farticle%252fuse-group-policy-to-control-onedrive-sync-client-settings-0ecb2cf5-8882-42b3-a6e9-be6bda30899c#enableenterpriseupdate)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@lifeisgood19, this new setting is in one of the Insiders builds right now. I will find out which one and add a note. Thank you!
