### ISSUE TITLE
This Page has a repeated formatting flaw

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/OfficeDocs-SharePoint#653]
This page has several links that start with "Content that is part of an eDiscovery case..." that are hyperlinked and poorly formatted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e806c519-1c30-5c66-68cb-c6020900896e
* Version Independent ID: 10a2b6db-de88-e8ce-7e6d-bec088868d07
* Content: [Add content to a case and place sources on hold in the eDiscovery Center](https://docs.microsoft.com/en-us/SharePoint/governance/add-content-to-a-case-and-place-sources-on-hold-in-the-ediscovery-center?redirectSourcePath=%252farticle%252f54d70de9-1ec2-4325-84f3-aeb588554479)
* Content Source: [SharePoint/SharePointServer/governance/add-content-to-a-case-and-place-sources-on-hold-in-the-ediscovery-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/add-content-to-a-case-and-place-sources-on-hold-in-the-ediscovery-center.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @markjjo
* Microsoft Alias: **MARKJJO**

**Comment by markjjo** [comment]
@MatthewMcD Thanks for the heads up. The topic is fixed.
