### ISSUE TITLE
Solution Used?

### ISSUE THREAD

**Issue by SheTriedIt** [MicrosoftDocs/OfficeDocs-SharePoint#660]
Was this user guide created with SharePoint? An App? GitHub? I'd like to create a user guide just like this - today. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659548ea-eb6e-8eee-2892-f352512db6a1
* Version Independent ID: 2e0e6017-2b29-e831-ff61-0a798dfb175f
* Content: [Manage site collection administrators](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-administrators)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-administrators.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-administrators.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SheTriedIt  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better and they might also be able to answer your question. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
