### ISSUE TITLE
table at the start doesnt match the flow of the article

### ISSUE THREAD

**Issue by killerewok2000** [MicrosoftDocs/OfficeDocs-SharePoint#661]
table at the start doesnt match the flow of the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088d4ec6-16f9-7af9-006b-db169d3390d2
* Version Independent ID: 6a4171f9-b32f-baa5-47b1-ca4d1475acae
* Content: [MySites to OneDrive and SharePoint Migration Guide](https://docs.microsoft.com/en-us/sharepointmigration/mysites-to-onedrive-migration-guide)
* Content Source: [migration/MySites-to-OneDrive-Migration-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/MySites-to-OneDrive-Migration-Guide.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
will correct.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@JoanneHendrickson Wondering if there were any updates on this? Thanks

**Comment by scanum** [comment]
@killerewok2000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
