### ISSUE TITLE
Configure team site libraries to sync automatically

### ISSUE THREAD

**Issue by gallantrinity** [MicrosoftDocs/OfficeDocs-SharePoint#662]
Why the 1,000 device limit? Haven't seen this limitation in any of the SharePoint Online limitation documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@gallantrinity , Because this is a new feature, I haven't added the info to the limits article yet. I will though, if this limit persists. Thank you!

**Comment by gallantrinity** [comment]
Although the OneDrive policy is new, SharePoint sync has been around for a long time now. You didn’t answer the question as to why the limitation of 1,000 devices. Sync is available to everyone, what if everyone in our company (far exceeds 1,000 devices) decides to sync the same library on their own? Could you direct me to the documentation of this limitation?

Thanks,

George Allan
Systems Administrator

TRINITY PROPERTY CONSULTANTS
2082 Michelson Drive, 4th Floor
Irvine, CA 92612

T 949.299.0815 | F 949.399.2530
GAllan@trinity-pm.com<mailto:GAllan@trinity-pm.com>  | www.FPAMF.com<http://www.fpamf.com/> |  www.trinity-pm.com<http://www.trinity-pm.com/>
Click to open a Helpdesk<https://trinitypm.zendesk.com/> Ticket

[cid:image001.jpg@01D41EA5.E54FDB00]<http://www.fpamf.com/>     [cid:image002.png@01D41EA5.E54FDB00] <http://www.trinity-pm.com/>

ATLANTA   -   DALLAS   -   DENVER   -   IRVINE   -   MINNEAPOLIS   -   PORTLAND   -   SAN FRANCISCO

[Description: Description: cid:image001.gif@01C948B1.CFC0CC60] Please consider the environment before printing this e-mail [Description: Description: cid:image001.gif@01C948B1.CFC0CC60]

**Comment by kaarins** [comment]
@gallantrinity , I believe that this limitation applies only to the new policy. Adding @IoTJonL to confirm and add any other comments

**Comment by gallantrinity** [comment]
Thanks Kaarin! Appreciate any feedback on this subject as we are very close to migrating to SharePoint Online and want to understand any limitations that may apply to our business.

George Allan
Systems Administrator

TRINITY PROPERTY CONSULTANTS
2082 Michelson Drive, 4th Floor
Irvine, CA 92612

T 949.299.0815 | F 949.399.2530
GAllan@trinity-pm.com<mailto:GAllan@trinity-pm.com>  | www.FPAMF.com<http://www.fpamf.com/> |  www.trinity-pm.com<http://www.trinity-pm.com/>
Click to open a Helpdesk<https://trinitypm.zendesk.com/> Ticket

[cid:image001.jpg@01D41EA5.E54FDB00]<http://www.fpamf.com/>     [cid:image002.png@01D41EA5.E54FDB00] <http://www.trinity-pm.com/>

ATLANTA   -   DALLAS   -   DENVER   -   IRVINE   -   MINNEAPOLIS   -   PORTLAND   -   SAN FRANCISCO

[Description: Description: cid:image001.gif@01C948B1.CFC0CC60] Please consider the environment before printing this e-mail [Description: Description: cid:image001.gif@01C948B1.CFC0CC60]

**Comment by JoleungMSFT** [comment]
@gallantrinity - The 1000 device limit is for performance reasons due to the notification pipeline per library. Each library has a maximum limit of devices that can be connected to at any time. Once that limit is broken, performance will degrade as the client switches to a polling model rather than a notification model. 

Note - this is Per Library, so it is unlikely for this limit to ever be hit, unless you configure this policy onto 1,000s devices - which is why it is noted here.

**Comment by gallantrinity** [comment]
Jonathan,

Thank you for your response! Does performance drop off significantly or is it a gradual decline in performance. We want to sync a single document library on all devices. Could you point me to the documentation about this limitation?

Thanks,

George Allan
Systems Administrator

TRINITY PROPERTY CONSULTANTS
2082 Michelson Drive, 4th Floor
Irvine, CA 92612

T 949.299.0815 | F 949.399.2530
GAllan@trinity-pm.com<mailto:GAllan@trinity-pm.com>  | www.FPAMF.com<http://www.fpamf.com/> |  www.trinity-pm.com<http://www.trinity-pm.com/>
Click to open a Helpdesk<https://trinitypm.zendesk.com/> Ticket

[cid:image001.jpg@01D41EA5.E54FDB00]<http://www.fpamf.com/>     [cid:image002.png@01D41EA5.E54FDB00] <http://www.trinity-pm.com/>

ATLANTA   -   DALLAS   -   DENVER   -   IRVINE   -   MINNEAPOLIS   -   PORTLAND   -   SAN FRANCISCO

[Description: Description: cid:image001.gif@01C948B1.CFC0CC60] Please consider the environment before printing this e-mail [Description: Description: cid:image001.gif@01C948B1.CFC0CC60]

**Comment by JoleungMSFT** [comment]
@gallantrinity it's a gradual decline - in general the more devices, and the more files/content in a library, the worst the performance is going to be. The ability to enforce this configuration on all deployed devices is likely to cause a large amount of load, thus we are giving the guidance above. We are actively monitoring and if we see that the performance is still acceptable/useable we will increase the guidance limits.

**Comment by scanum** [comment]
@officedocsbot assign @scanum
