### ISSUE TITLE
Managed Properties

### ISSUE THREAD

**Issue by Saurabh-Chauhan** [MicrosoftDocs/OfficeDocs-SharePoint#664]
Why we can only choose managed properties that have already been created and configured. 
Need more example on Judgement Queries.
I need an example on Add queries manually in Judgement Sets.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f058cbb9-524c-560c-c42a-2a14a246f4f9
* Version Independent ID: 8ad7d9b3-68d2-12e5-3e9a-c120960842ff
* Content: [Create a custom ranking model by using the Ranking Model Tuning App](https://docs.microsoft.com/en-gb/SharePoint/search/create-custom-ranking-model#step-2-add-a-judgment-set)
* Content Source: [SharePoint/SharePointServer/search/create-custom-ranking-model.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/create-custom-ranking-model.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Jcoetsee** [comment]
@tklarsen Can you review the question above and possibly provide insight of possible? Should this be considered as an item to add to the article based on what is requested?

**Comment by scanum** [comment]
@Saurabh-Chauhan  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
