### ISSUE TITLE
Web Platform Installer

### ISSUE THREAD

**Issue by seraphim72** [MicrosoftDocs/OfficeDocs-SharePoint#666]
There should be a note about doing this by WPI and also one about the 5 CUs to Workflow Manager that have come out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9696f9c-aeb8-e0b9-2a43-bc24e9c7b2b2
* Version Independent ID: e267b2fe-5cb3-9f79-f062-4f02763d7505
* Content: [Install and configure workflow for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/install-and-configure-workflow-for-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/install-and-configure-workflow-for-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tomresing** [comment]
Published changes look good to me. Thanks, @tseward!
