### ISSUE TITLE
"guest アカウント" needs to be replaced with "ゲスト アカウント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SharePoint#668]
https://docs.microsoft.com/ja-jp/onedrive/b2b-sync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Jcoetsee** [comment]
@kaarins Can you please review the question here. Would making the change on the linked document reflect on the translated document or the documentation that's in a different language?

**Comment by Jcoetsee** [comment]
@kaarins Just another follow up on this. As stated I don't see grammatical issues with the document so wanted some insight from you.

**Comment by scanum** [comment]
@officedocsbot assign @Officeglobal

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this issue? Thanks.

**Comment by OfficeGlobal** [comment]
@MollyMalone 

Hello @hyoshioka0128 ,

The "guest アカウント" is approved MS term therefore we will not change the translation.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #668
