### ISSUE TITLE
Sizing guidance for 2016

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#67]
this provides a lot of guidance for sizing 2013 farms, but nothing about 2016. Are there any plans to add a similar document for 2016 with the minrole configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 072373e3-bd34-eca0-575a-f83e85563e01
* Version Independent ID: f48cfb5a-db02-f242-08e2-71f4232382b2
* Content: [Capacity management and sizing overview for SharePoint Server 2013](https://docs.microsoft.com/en-us/SharePoint/install/capacity-management-and-sizing-overview#reference-architectures)
* Content Source: [SharePoint/SharePointServer/install/capacity-management-and-sizing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/capacity-management-and-sizing-overview.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
Dean, thanks for your comment.  At this time, we have no plans to update the document for 2016 and MinRole.  The guidance for 2013 should be followed.
