### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/OfficeDocs-SharePoint#670]
Link "Securing SharePoint: Harden SQL Server in SharePoint Environments" does not work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: effa11e2-25b6-3ba0-e54f-1901ce490f0f
* Version Independent ID: 22e3de07-f162-5b71-6a00-34262dfbddca
* Content: [Configure SQL Server security for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/configure-sql-server-security-for-sharepoint-environments)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/configure-sql-server-security-for-sharepoint-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/configure-sql-server-security-for-sharepoint-environments.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by scanum** [comment]
@officedocsbot close
