### ISSUE TITLE
Navigation on Mobile not working

### ISSUE THREAD

**Issue by gcrockenberg** [MicrosoftDocs/OfficeDocs-SharePoint#673]
When resizing your browser or on mobile devices the shared navigation disappears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@gcrockenberg  Thank you very much for your kind feedback. Could you confirm that this is still an ongoing issue?  We recommend that you submit this feedback into Outlook [Support](https://support.office.com/home/contact). The team will evaluate and take the appropriate action, as per their schedule. We strongly appreciate you for taking time and sharing your feedback.

**Comment by gcrockenberg** [comment]
The Hub Site navigation now moves into the hamburger menu on resize.  Thanks
