### ISSUE TITLE
Could you add information about how to use powershell to resume a stuck paused Search Service Application?

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/OfficeDocs-SharePoint#675]
I have used this information to confirm and administrative pause but I want to know how to reume the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea0ba5bd-cc19-bb57-b16c-1ecb16becc8e
* Version Independent ID: ec016404-f9bd-7318-5162-1ec538bc7b3b
* Content: [Manage a paused Search service application in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/search/manage-a-paused-search-service-application)
* Content Source: [SharePoint/SharePointServer/search/manage-a-paused-search-service-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/manage-a-paused-search-service-application.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@pagejustin Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
