### ISSUE TITLE
Application Validation did not Succeed - v2.1.103.8510

### ISSUE THREAD

**Issue by solinear** [MicrosoftDocs/OfficeDocs-SharePoint#676]
Both versions (current release and public preview) fail on install.

Windows 10.0.14393.0

All prereqs are present

Failure: Activation of http://spmtreleasescus.blob.core.windows.net/build-firstrelease/build-firstrelease.application resulted in exception.  Following failure messages were detected:
+ File, oncloudify_x86.dll, has a different computed hash than specified in manifest.

Let me know what I need to do in order to get past this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool#see-also)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by solinear** [comment]
Ironically, I have another off-prem machine that I used for testing that has 2.1.103.8511 AND 3.0.104.8529 installed successfully.  I'm curious how I installed a newer version than what is listed here.

**Comment by solinear** [comment]
I have tested this on Win7, Win10, and Server 2016 and get the same error.

It would be nice if there was just an install instead of this obtuse build.

**Comment by scanum** [comment]
@solinear  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
