### ISSUE TITLE
Migration to OneDrive

### ISSUE THREAD

**Issue by solinear** [MicrosoftDocs/OfficeDocs-SharePoint#677]
To migrate to OneDrive the target DocLib MUST be "Documents", as in the following CSV example:

D:\Data\username,,,https://organization-my.sharepoint.com/personal/userID_domain_com/,Documents,TargetFolderName

I tend to use "Old_HomeDrive" for the TargetFolderName, as it's pretty much guaranteed to not exist (it will create it automatically).  This can be a little confusing, as it does not go into the OneDrive "Documents" folder, but instead a subfolder under the root of the user's OneDrive (or the root, if no TargetFolderName is specified).

I discovered this through lame trial and error, due to the lack of this being clarified in the documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by AltCoyne** [comment]
Thanks for posting, I was shocked by the lack of info around OneDrive in this doc.

**Comment by scanum** [comment]
@solinear  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
