### ISSUE TITLE
Update Strategy for HA Farm

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#68]
The note above states "The information in this section is valid if you farm is not in a high availability (HA) environment", where is the info that is valid when a farm is HA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d5bda8-9221-95d9-517e-99dfafa480ad
* Version Independent ID: 568872c6-5498-04a3-6263-a603f7c73292
* Content: [Software updates overview for SharePoint Server 2016](https://docs.microsoft.com/en-us/SharePoint/upgrade-and-update/software-updates-overview#software-update-deployment-cycle)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/software-updates-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/software-updates-overview.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
Thanks for report @DeanGross and fix @tseward . Much appreciated. Sorry for the delay on getting this closed out.
