### ISSUE TITLE
ClearSuiteLinksCache() not available on SharePoint 2019

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/OfficeDocs-SharePoint#684]
The command `ClearSuiteLinksCache()` mentioned to invalidate the suite links cache is not recognized in SharePoint 2019. Chrome and IE11 both throw an error that the command "ClearSuiteLinksCache" is not defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244110ff-0cc2-1acf-7fa3-ac1d29ea667b
* Version Independent ID: 6945082c-071a-dfd3-cd86-54e8cd33ff5e
* Content: [Custom Tiles in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/administration/custom-tiles-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/administration/custom-tiles-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/custom-tiles-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@lafe Thank you for your feedback. I have updated the article to include this information.
