### ISSUE TITLE
Limited Access System Group

### ISSUE THREAD

**Issue by kathyfurtado** [MicrosoftDocs/OfficeDocs-SharePoint#686]
I'm wondering what is a "Limited Access System Group"? One of my users can't access the site and I came across this term.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c264ede0-8da5-b812-c36b-f1c3c03ac590
* Version Independent ID: 27b51f79-ce96-99c4-d1e8-10288e71ff6c
* Content: [Default SharePoint groups](https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups)
* Content Source: [SharePoint/SharePointOnline/default-sharepoint-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/default-sharepoint-groups.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by vijaynikam** [comment]
You can Company Administrator as an admin to any site, but you can't add it as a primary admin. If you remove it as the primary admin for your root site, you can't add it back.

This note is incorrect. You can add 'Company administrator' as a primary admin to any site and you can also add back 'Company administrator' as primary admin to your root site.

**Comment by VLG17** [comment]
@kathyfurtado you can find more information about the permission levels within Sharepoint here - https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels

Limited Access - Enables a user or group to browse to a site page or library to access a specific content item when they do not have permissions to open or edit any other items in the site or library. This level is automatically assigned by SharePoint when you provide access to one specific item. You cannot assign Limited Access permissions directly to a user or group yourself. Instead, when you assign edit or open permissions to the single item, SharePoint automatically assigns Limited Access to other required locations, such as the site or library in which the single item is located. 

Hope this helps.

**Comment by scanum** [comment]
@kathyfurtado  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
