### ISSUE TITLE
Domain functional level

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#689]
Is there any special requirement for the domain functional level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48fbcb0b-9e6d-d2e7-5194-5593d35fff63
* Version Independent ID: f6d30df6-858b-4d3c-542f-a4d6b45ec3d8
* Content: [Hardware and software requirements for SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements-2019)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

@LuigiBruno just 2003 native mode. I will update the article this weekend to reflect that. This is a fairly common question.

**Comment by Techwriter40** [comment]
@LuigiBruno I have merged the changes from Trevor and the article should be re-published soon. thanks for your feedback.

**Comment by LuigiBruno** [comment]
Thank you @tseward and Techwriter40.
