### ISSUE TITLE
HTML Field Security is still available?

### ISSUE THREAD

**Issue by robinmeure** [MicrosoftDocs/OfficeDocs-SharePoint#690]
HTML Field Security is still available as a link and can be configured on Modern teamsites. The setting is read by the Embed WebPart which checks whether or not this has been configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa561c35-c73d-32d1-a553-5c96ce179a8c
* Version Independent ID: 819af39f-8ee0-e7f8-f591-09d464225e50
* Content: [Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#features-affected-when-custom-script-is-blocked)
* Content Source: [SharePoint/SharePointOnline/allow-or-prevent-custom-script.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/allow-or-prevent-custom-script.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Take a look at https://techcommunity.microsoft.com/t5/Office-365-Groups/HTML-Field-Security-Group-Sites/m-p/42311/highlight/true#M1869. Does that answer the question?
