### ISSUE TITLE
affect on visibility of account in other locations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#691]
How does this affect the presence of the account in a SharePoint group and the SharePoint User Information list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a01697-2af8-ea42-05bb-7c36afe38870
* Version Independent ID: e7f310af-5642-cee5-2048-98b054e54abc
* Content: [Set the OneDrive retention for deleted users](https://docs.microsoft.com/en-us/onedrive/set-retention)
* Content Source: [OneDrive/set-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-retention.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
No changes. UIL/SharePoint Groups do not remove users upon them being de-licensed, deleted or disabled.
