### ISSUE TITLE
IRM-protected library feature support on MacOS

### ISSUE THREAD

**Issue by sabbour** [MicrosoftDocs/OfficeDocs-SharePoint#694]
Is this feature still not supported on MacOS? I got an error and I upgraded my client to 19.033.0218.001 and it seemed to sync afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930a4d28-a511-e037-fa15-e4f3aebc7064
* Version Independent ID: 22a6cf03-0378-84b1-0ade-236018d49b3b
* Content: [Let users sync IRM-protected files with the OneDrive sync client](https://docs.microsoft.com/en-us/sharepoint/let-users-sync-irm-protected-files)
* Content Source: [SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/let-users-sync-irm-protected-files.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by JoleungMSFT** [comment]
IRM protected libraries are supported - you got a CVR message for a new feature, per item (label based) IRM scenario, which requires everyone at **Microsoft** to be on the latest version of the sync client.

**Comment by scanum** [comment]
@kaarins Hi Kaarins, any updates on this? Thanks!

**Comment by kaarins** [comment]
I removed the note about the Windows requirement.
