### ISSUE TITLE
Alert on Site Pages does not trigger on SharePoint Online

### ISSUE THREAD

**Issue by fguicc** [MicrosoftDocs/OfficeDocs-SharePoint#695]
In SharePoint Online I have set an alert on the site pages library. 
If the option "All changes" is selected it works and I receive the notification but if the option "New items are added" is selected it doesn't work since I don't receive any notification

**Comment by tseward** [comment]
@fguicc I would suggest opening a support case at admin.microsoft.com to report this as a bug.
