### ISSUE TITLE
Followed site list display also sites that have been deleted

### ISSUE THREAD

**Issue by fguicc** [MicrosoftDocs/OfficeDocs-SharePoint#696]
The following page 
https://[tenant].sharepoint.com/_layouts/15/sharepoint.aspx?v=following
displays also sites that have been deleted.
Same thing If I retrieve the list of followed sites using REST APIs.

If a site has been deleted should not appear.

**Comment by tseward** [comment]
@fguicc I would suggest opening a support request via admin.microsoft.com. This is a known issue, but this is not a documentation issue which is what this repo is intended for.
