### ISSUE TITLE
External users programmatic access.

### ISSUE THREAD

**Issue by joliving** [MicrosoftDocs/OfficeDocs-SharePoint#698]
Hi there,

Can external users have access to sharepoint's Microsoft Graph API?

thanks

**Comment by scanum** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/698

**Comment by scanum** [comment]
@joliving  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
