### ISSUE TITLE
Inconsistent Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#70]
V2 of the tool has been released but many of the pages in this section still refer to the Beta Version which is confusing. Please review the pages and update as necessary

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89de996c-fdbe-91dd-75c2-34b7e12b1f49
* Version Independent ID: 9961e4fe-6764-d6c8-9bde-271ef81c5a6d
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepoint/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/introducing-the-sharepoint-migration-tool.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@DeanGross - Looks like this is fixed now. Thanks for taking the time to report and keeping a close eye on the docs. The community really benefits and it is very much appreciated!
