### ISSUE TITLE
Storage account type 'Standard_LRS' should be 'StandardLRS'

### ISSUE THREAD

**Issue by martinlingstuyl** [MicrosoftDocs/OfficeDocs-SharePoint#701]
The script creating the adVM causes issues, because Standard_LRS is not a valid option, please change to StandardLRS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e02c018-709f-3fc6-becd-a92793ecc0b7
* Version Independent ID: fa10d53d-30c1-2087-fabf-86d2c0e232f2
* Content: [SharePoint Server 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/sharepoint/administration/sharepoint-server-2016-dev-test-environment-in-azure#phase-1-deploy-the-virtual-network-and-a-domain-controller)
* Content Source: [SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/sharepoint-server-2016-dev-test-environment-in-azure.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by tseward** [comment]
"Standard_LRS" is still correct for the cmdlets, even the newer Az module. Can you provide the error message(s) you were seeing?

**Comment by martinlingstuyl** [comment]
Hi @tseward,

When using the following script:

```
$vmSize="Standard_D1_v2"
$vm=New-AzureRMVMConfig -VMName "test" -VMSize $vmSize
$vm=Set-AzureRmVMOSDisk -VM $vm -Name ("test-OS") -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"
```

I'm receiving the following error:

```
Set-AzureRmVMOSDisk : Cannot bind parameter 'StorageAccountType'. Cannot convert value "Standard_LRS" to type "Microsoft.Azure.Management.Compute.Models.StorageAccountTypes". Error: "Unable 
to match the identifier name Standard_LRS to a valid enumerator name. Specify one of the following enumerator names and try again:
StandardLRS, PremiumLRS"
At line:10 char:113
+ ... zeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"
+                                                            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmVMOSDisk], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Compute.SetAzureVMOSDiskCommand
```

I do see I'm having multiple versions of AzureRM installed on my system. Maybe thats the problem:
```
Name    Version
----    -------
AzureRM 3.8.0  
AzureRM 5.7.0  
AzureRM 6.13.1 
AzureRM 6.9.0  
```

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by tseward** [comment]
Confirmed using the current version of Azure RM that -StorageAccountType expects Standard_LRS.

```

Name                            Version
----                            -------
AzureRM.Compute                 5.9.1
AzureRM.Network                 6.11.1
AzureRM.profile                 5.8.2
AzureRM.Storage                 5.2.0
```

https://www.powershellgallery.com/packages/AzureRM/6.13.1

**Comment by martinlingstuyl** [comment]
In that case it probably commandlet version on my end
