### ISSUE TITLE
Ability to follow

### ISSUE THREAD

**Issue by itprotj** [MicrosoftDocs/OfficeDocs-SharePoint#703]
Are we able to "follow" another sharepoint when its between two different microsoft365 organizations?
I get up to the point of sharing a sharepoint site with another organization but they are unable to "follow" it meaning they can't have it in their sidebar for easy access. Or is there another step required to make this happen?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b52267-3e1c-f371-a64a-29429151e207
* Version Independent ID: b39fef1f-8e0f-519c-bbe4-415b1c6d584c
* Content: [Create an external business-sharing site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-external-business-sharing-site)
* Content Source: [SharePoint/SharePointOnline/create-external-business-sharing-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-external-business-sharing-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by VLG17** [comment]
@itprotj External users, even if they have a Microsoft Account, don't have a llicense to your Office 365 subscription, so they are limited to basic collaboration tasks - hence the missing "Follow" option

More info here - https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview

**Comment by itprotj** [comment]
Hi I see your reasoning behind this as then members will not be obliging with an office licence.
However if we were able to assign external users licences from our 365 account then I reckon that would adequately make this work alright. Do you have any plans for this?

**Comment by scanum** [comment]
@VLG17

**Comment by VLG17** [comment]
@itprotj although technically possible, it's not supported to add licenses to external users. Should you require this, i recommend providing this feedback on the official channel (it's your best bet of getting something changed): https://office365.uservoice.com/

**Comment by scanum** [comment]
@itprotj  thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
