### ISSUE TITLE
CSV file format is lacking 'individual' files option that will prevent restructuring the data

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-SharePoint#704]
What I would like to see is a totally revised and more simple CSV input format:
"[full source path of file]","[full target path of file]"
Who ever came up with this rediculous 6 column format, as it is totally unneccesary,bloated and not suitable for migrations targetting specific source files and there verious intended target locations?
And really I (as a user) don't care if something is a share, site, library or folder. I just want to supply the full URL/path for both source and target.

Back to my own Powershell...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@SjoerdV thank you for the suggestion. As this is repo is for documentation issues, can you please post your product change suggestion at https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365?

**Comment by SjoerdV** [comment]
https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/37036207-easier-csv-input-for-sharepoint-migration-tool
