### ISSUE TITLE
Issue with detection script

### ISSUE THREAD

**Issue by RowdyChildren** [MicrosoftDocs/OfficeDocs-SharePoint#706]
The detection method in the linked example package uses "smart quotes". this causes execution to fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@kaarins Any updates on this issue? Thanks!

**Comment by RowdyChildren** [comment]
I would even suggest not uploading an example package and merely providing the detection method and user experience settings that are needed. Its such a simple package that it shouldn't be a big deal for the average SCCM admin to follow the steps to make it.

**Comment by Fredrro** [comment]
Here is a link to the fixed powershell detection check. Otherwise you can always do as @rowdychildren said and just use a reg key or another way of detection.

https://hastebin.com/aruwepibap.pl

**Comment by RowdyChildren** [comment]
@Fredrro, the need for that script is due to the fact the installer needs to run as system the first time but it installs and we have to check the currently logged on user profile. Registry Keys would not work since it would be looking in the system context

**Comment by Fredrro** [comment]
What if you just install the app as user instead of system via sccm? Then the detection check can just be for the current user key. If not there it will install for new user on the workstation. I guess this depends on if you want to do a per machine or user specific push.

**Comment by RowdyChildren** [comment]
So thats the fun part about the installer. If OneDrive is not installed in any user profile you must run the installer with Admin permissions, even though it installs per user on Windows 7 (on Windows 10 this is not the case)

**Comment by Fredrro** [comment]
I am just setting this up in SCCM for my org now. I was planning on using the Current user key it generates after install of a user for the detection check. Then doing install as user in the setup of the app instead of install as system. This should install the app per user login correct? It is either that or i still do install as system but use a script such as 

$Path = “$env:LOCALAPPDATA\Microsoft\OneDrive\OneDrive.exe”
If (Test-Path $Path){Write-Host “$Path Exists”}

**Comment by scanum** [comment]
@RowdyChildren Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
