### ISSUE TITLE
Versions at the top are out of date

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#713]
v3 is in public preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac22961-da69-7b22-6dff-f7bc5ee82ed3
* Version Independent ID: dd4ed11e-a0f9-4e97-48ae-8bd94f510c07
* Content: [How the SharePoint Migration Tool works](https://docs.microsoft.com/en-us/sharepointmigration/how-the-sharepoint-migration-tool-works)
* Content Source: [migration/how-the-sharepoint-migration-tool-works.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-the-sharepoint-migration-tool-works.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@danmyhre thank you for reaching out. Please let me know exactly which versions are out of date so I can add the necessary changes.

**Comment by danmyhre** [comment]
It looks like that section of the page has been removed since this was submitted.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@danmyhre  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
