### ISSUE TITLE
This page is missing from the navigation

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#714]
This page is missing from the navigation on the left

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac22961-da69-7b22-6dff-f7bc5ee82ed3
* Version Independent ID: dd4ed11e-a0f9-4e97-48ae-8bd94f510c07
* Content: [How the SharePoint Migration Tool works](https://docs.microsoft.com/en-us/sharepointmigration/how-the-sharepoint-migration-tool-works)
* Content Source: [migration/how-the-sharepoint-migration-tool-works.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-the-sharepoint-migration-tool-works.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
