### ISSUE TITLE
Language Neutral Tokenization and Finer Query Tokenization not exist in SP 2013 and SP 2016

### ISSUE THREAD

**Issue by santanayana** [MicrosoftDocs/OfficeDocs-SharePoint#716]
Hello,
2 new properties as in title not exist on SP 2013 and SP 2016 by default. Should we install any special patch or do something else to enable this kind of properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e19898d-6400-f2ad-63aa-825469026e99
* Version Independent ID: 79bc10e2-1ee3-00aa-82b2-ffe0bc14914e
* Content: [Overview of the search schema in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/search/search-schema-overview)
* Content Source: [SharePoint/SharePointServer/search/search-schema-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/search-schema-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tseward** [comment]
@santanayana I put a note that those two features are SP 2019 only.

**Comment by scanum** [comment]
@santanayana Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
