### ISSUE TITLE
Blocking file "types" is insufficient. Must be able to block names/patterns

### ISSUE THREAD

**Issue by libove** [MicrosoftDocs/OfficeDocs-SharePoint#717]
It is wholly inadequate to be able to block file "Types" such as "db", as there may be "*.db" files which COULD AND SHOULD be OneDrive sync'able, whereas there is the one widely known breaks-OneDrive (shouldn't; OneDrive should come out-of-the-box with this excluded!) "Thumbs.db" file which is not representative of what other ".db" files might be/contain.
OneDrive must allow excluding of specific file NAMES and (Regular Expression) PATTERNS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types?redirectSourcePath=%252fen-us%252farticle%252fblock-syncing-of-specific-file-types-7d7168dd-9015-4245-a971-61b504f834d6)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@libove  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by libove** [comment]
This shouldn't be closed. It's pretty clear that the current product design doesn't support the suggested feature, so I don't know what a support ticket would achieve, other than to be told to make a UserVoice or other suggestion (such as I just did here).
What do you suggest that I ask support? "How do I do this thing that the documentation says that the product doesn't do"?
Or, do I misunderstand this channel, and this channel is only about the content of the documentation, but not the feature set of the product?
thank you.

**Comment by dpgator33** [comment]
This seems like it should be a really easy fix for SOMEBODY at Microsoft.  We were just about to roll this out until VS Code started freaking out in testing.  We have dozens of developers who would not tolerate this, so we're dead in the water.
