### ISSUE TITLE
Coauthoring for Excel

### ISSUE THREAD

**Issue by sir79** [MicrosoftDocs/OfficeDocs-SharePoint#718]
Coahthoring limits are only mentioned for Word and Powerpoint. What about Excel? Do the same limits also accounts for Excel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by VLG17** [comment]
@sir79  keeping in mind that the article applies to 2013, if you use a version of Excel that has Co-authoring enabled, then yes, the limits apply - "10 concurrent editors per document" is the recommended value, the hard limit is 99.

**Comment by scanum** [comment]
@sir79  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
