### ISSUE TITLE
Errors in PowerShell scripts

### ISSUE THREAD

**Issue by wiktorwandachowicz** [MicrosoftDocs/OfficeDocs-SharePoint#719]
Three times in scripts there are parameters "StandardLRS", which are incorrect. Trying to run scripts with these results in errors.
These should be "Standard_LRS" instead.

One more error is in script for creating SharePoint Server 2016 virtual machine. In the line:
$vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" 
there is "DC1-OS" disk mentioned. But it was used in previous example, and since following the tutorials it already exists!
This disk should probably be named "SP1-OS" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b41818-1125-408f-dee5-c3ba0af8b5b1
* Version Independent ID: c1e611cc-113f-a77f-1cb7-c819560a172d
* Content: [Intranet SharePoint Server 2016 in Azure dev/test environment](https://docs.microsoft.com/en-us/sharepoint/administration/intranet-sharepoint-server-2016-in-azure-dev-test-environment#feedback)
* Content Source: [SharePoint/SharePointServer/administration/intranet-sharepoint-server-2016-in-azure-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/intranet-sharepoint-server-2016-in-azure-dev-test-environment.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@wiktorwandachowicz Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
