### ISSUE TITLE
Explain Column limit in detail

### ISSUE THREAD

**Issue by jigargandhi** [MicrosoftDocs/OfficeDocs-SharePoint#72]
In the Column Limits section, there is a table with "Size per Column" please describe whether it is size of the column in database. Also the relation between Maximum Size and Size per column needs to be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits#Column)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
@jigargandhi - I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay!

**Comment by AndreaBarr** [comment]
@tseward Is investigation this issue.
