### ISSUE TITLE
Question re: Link Targets

### ISSUE THREAD

**Issue by annloftus** [MicrosoftDocs/OfficeDocs-SharePoint#720]
In your article you indicate:  
Link points to a page or site in the same tenant (same site or another site): Links open in the same tab - ok, this make sense
Link points to a document (same site or different site): Links open in a new tab -   ok, this make sense
Link points to an external (internet) site or document: Links in a new tab - what does this mean?   Did you mean to state "links open in the SAME tab"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience#feedback)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@annloftus  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by mmohamedbasith** [comment]
> @officedocsbot close

@annloftus @scanum  

"Link points to a page or site in the same tenant (same site or another site): Links open in the same tab"

This is not the case in Hub Site navigation links. Different site (in same tenant) link opens in new tab . It should open same tab
