### ISSUE TITLE
Missing text in multiple places

### ISSUE THREAD

**Issue by ttplaya** [MicrosoftDocs/OfficeDocs-SharePoint#721]
In multiple places on this page, when it gives a code snippet example and then says "Where:" then has a list of bullets that describe what each tag in angled brackets is for, most of the tags are missing in the bullets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f60077-848f-40d7-8ac9-b0b6bcd8201b
* Version Independent ID: 07bdb9d0-cec1-e4b5-bd41-a5f5867a8bf8
* Content: [Configure recommendations and usage event types in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-recommendations-and-usage-event-types)
* Content Source: [SharePoint/SharePointServer/administration/configure-recommendations-and-usage-event-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-recommendations-and-usage-event-types.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@ttplaya Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
