### ISSUE TITLE
Code section when not logged in

### ISSUE THREAD

**Issue by Naxxan60** [MicrosoftDocs/OfficeDocs-SharePoint#729]
Hello,
When I wasnt logged in to Github, I got some addtionnal "code section" with the content "Where :" inside and the part with the cmdlets. Don't know if it's a bug in this page or for all pages.
Now logged in, I havent the problem, I logout from Github, the problem comes back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67cc68b-2d40-7d78-9ae5-a71938b6fa78
* Version Independent ID: 52fd8de6-598e-7672-eb34-2fa7a46b0182
* Content: [Upgrade service applications to SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016#see-also)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Naxxan60** [comment]
Now, I logged in and I still have the problem. I don't understand.

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@Naxxan60 Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
