### ISSUE TITLE
Step 4 -Scripts instead of Azure Site Recovery

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#73]
Why do you recommend using scripts to rebuild the SP servers instead of just using Azure Site Recovery to copy the on-premises servers to Azure?
I'd like to know why we should use this approach instead of the approach described at https://docs.microsoft.com/en-us/azure/site-recovery/site-recovery-sharepoint#prerequisites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4b307e-efda-a478-3d50-7c9411df0179
* Version Independent ID: 495502ce-42b9-98fd-c29a-cd06d2b1c52a
* Content: [Plan for SQL Server Always On and Microsoft Azure for SharePoint Server Disaster Recovery](https://docs.microsoft.com/en-us/SharePoint/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery#Bp4)
* Content Source: [SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Azure Site Recovery is supported with SharePoint, however, it doesn't cover SharePoint Search service. I will add a note stating that if you deploy Search service in your SharePoint farm, you need to use scripts.
