### ISSUE TITLE
Unable to invite internal member by email to a group drive item.

### ISSUE THREAD

**Issue by sharmajnu** [MicrosoftDocs/OfficeDocs-SharePoint#733]
At one of our customer invite call for an internal member(who is not a group member) to invite a group drive folder fails with 403 status. For all other tenants this works fine.

The person who is sharing is a group owner.

I have gone through document lots of OneDrive and SharePoint settings, did not find any settings useful settings with which can control it. Is there a way to stop sharing all together in OneDrive?

**Comment by scanum** [comment]
@sharmajnu  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
