### ISSUE TITLE
Microsoft Support has a beta program for this

### ISSUE THREAD

**Issue by Jameswmayberry** [MicrosoftDocs/OfficeDocs-SharePoint#737]
So after much back and forth with Microsoft support, they sent me a pilot program they are offering. Has anyone here gone down that path yet? Wondering how the results were? Link to take part in SharePoint Tenant Rename Pilot Program: 
https://aka.ms/spo-rename 
Note from Microsoft "Please note that this is a pilot program and we can’t guarantee any specific features or timelines."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fff5ef6-b4cc-5a18-10a8-7b5182e2deae
* Version Independent ID: 8176e436-b25b-e455-09ac-be08bea2bfcb
* Content: [Change your SharePoint domain name](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Jameswmayberry  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint* better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
