### ISSUE TITLE
wrong link to remove search result?

### ISSUE THREAD

**Issue by pjbarry21** [MicrosoftDocs/OfficeDocs-SharePoint#738]
Second to last bullet, starting with "If you temporarily remove..." links to: https://docs.microsoft.com/en-us/sharepoint/manage-result-sources

I think maybe it should link to: https://docs.microsoft.com/en-us/sharepoint/remove-search-results

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f89b7-afd4-1b65-f3ad-c802c7dd5a47
* Version Independent ID: 0f3e61c4-6b03-dccb-6067-09ed98228f62
* Content: [Differences between the classic and modern search experiences in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search)
* Content Source: [SharePoint/SharePointOnline/differences-classic-modern-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/differences-classic-modern-search.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.
