### ISSUE TITLE
Install on non system drive  ????

### ISSUE THREAD

**Issue by UmrG** [MicrosoftDocs/OfficeDocs-SharePoint#739]
As mentioned in the article "As a best practice, we recommend that you install SharePoint Server on a non-system drive." how Can you move the Hive folder for any SharePoint version to nonsystem drive. The only files you can move to nonsystem drive is "install directory", not more than 2GB in size. What will be the benefit of moving it to non C: Drive and why is it a good recommendation?? 
Please add some more details on the page. 
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8234ffd6-eecf-088e-6ac4-76a750c123a9
* Version Independent ID: 7dfd076b-7c10-948d-4a48-3ddefc3c8795
* Content: [Install SharePoint Servers 2016 or 2019 across multiple servers](https://docs.microsoft.com/en-us/sharepoint/install/install-sharepoint-server-2016-across-multiple-servers)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@UmrG thank you for your feedback. I am researching this question with the product team and get an answer back to you shortly. thank you.

**Comment by tseward** [comment]
@UmrG The only thing you can move off of C: (during install only) is the Office Server related components (think Search). You cannot move the hive or some other dependent folders.

The reason you would move this off of C: is that regardless of where your Search index is, items are processed within the Office Server directory. In other words, if I have my Search index on D:\Index and I leave the default to install all of SharePoint on C:, search will still process files on C:\Program Files\Microsoft Office Servers\.... prior to being added to the index and it isn't something I can change post-install.

Ultimately, this will be for disk performance as this processing is one of the higher I/O intensive tasks. But keep in mind, these instructions were created when 10k RPM SCSI was still standard.

**Comment by UmrG** [comment]
Thank you Trevor for explaining this. Could not find this information any where but its an important factor you mentioned here. It will be nice to add this in your new book for 2019  not too late yet.

**Comment by tseward** [comment]
@UmrG too late for that, but let me see if I can find the proper docs article where it would fit the best (if not already mentioned).

**Comment by UmrG** [comment]
Thank you !
