### ISSUE TITLE
Windows Workflow Manager

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#74]
How would this process change if Windows Workflow Manager is being used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4b307e-efda-a478-3d50-7c9411df0179
* Version Independent ID: 495502ce-42b9-98fd-c29a-cd06d2b1c52a
* Content: [Plan for SQL Server Always On and Microsoft Azure for SharePoint Server Disaster Recovery](https://docs.microsoft.com/en-us/SharePoint/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery#Bp4)
* Content Source: [SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Hi Dean, as long as you're on the latest Cumulative Update (CU) for Windows Workflow Manager, then Always On is supported.

**Comment by DeanGross** [comment]
Sorry, I was not very clear. I'm curious about how we could use Azure for disaster recovery of the  Windows Workflow Manager servers that are supporting a SP 2016 farm.

**Comment by bentoncity** [comment]
Great question Dean, but you'd have to check the Windows Workflow Manager or Azure documentation for what they recommend.

**Comment by DeanGross** [comment]
Thanks, but that team seems to have been disbanded, they seldom update anything and since SP can depend heavily on Windows Workflow, I thought this would be best place to get a complete DR story

**Comment by tseward** [comment]
The Workflow Manager documentation should be separate with perhaps a link from this page to the WFM DR page (one doesn't exist right now). Since they're separate products, they should be treated as such.

**Comment by bentoncity** [comment]
As soon as the WFM documentation is updated I will place a link to their DR story in this topic. Hopefully this will happen soon.
