### ISSUE TITLE
Clarification on note about using Hybrid Picker

### ISSUE THREAD

**Issue by alwalters** [MicrosoftDocs/OfficeDocs-SharePoint#740]
re: the note "We recommend using the SharePoint Hybrid Picker to establish the Server-to-Server authentication between SharePoint Server and SharePoint Online."  Is the idea that the ideal is to use the Picker, but if for some reason you can't/aren't, follow the rest of the steps in this document?  Or are you supposed to do the picker and then the rest of the steps?  I'm guessing the former, but it's very unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d499cfa0-9a8e-37c8-4607-874d3d72ed69
* Version Independent ID: 267ded1d-8e8d-3d11-44b4-3e83c70d40c8
* Content: [Configure server-to-server authentication from SharePoint Server to SharePoint Online](https://docs.microsoft.com/en-us/SharePoint/hybrid/configure-server-to-server-authentication)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@alwalters We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by alwalters** [comment]
What response are you waiting for?  I don't see any questions for me.
