### ISSUE TITLE
How to get Tenant ID for SharePoint 2019 On-Premises 

### ISSUE THREAD

**Issue by janis-veinbergs** [MicrosoftDocs/OfficeDocs-SharePoint#742]
Now that OneDrive can be used with SharePoint 2019 On-Premises, it is not clear how to get Tenant ID for on-premises instance.

Multiple GPO items require TenantID. What to input for On-Prem installations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
There is no Tenant ID with on-prem. Those settings that make use of it should be considered non-applicable.

**Comment by janis-veinbergs** [comment]
@tseward pity. *Allow syncing OneDrive accounts for only specific organizations* looks useful or *Silently move Windows known folders to OneDrive*.

Guess then docs should be updated to indicate what is applicable to on-prem and online.

**Comment by kaarins** [comment]
@janis-veinbergs , thank you for your feedback - we are working on this!

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by kaarins** [comment]
This article has been updated with the tenant ID info for SharePoint Server, and a note that the Known Folder Move policies don't work for SharePoint Server. https://docs.microsoft.com/en-us/sharepoint/install/new-onedrive-sync-client
