### ISSUE TITLE
Wrong typing

### ISSUE THREAD

**Issue by Naxxan60** [MicrosoftDocs/OfficeDocs-SharePoint#748]
it's wrote : "Recommendations Clicked. The number of times s single item", the 's' is not the wished character I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849aee0b-2a53-7231-6106-e652c03bc378
* Version Independent ID: 9c0aebac-8e48-43a6-afb6-ef08e8f78715
* Content: [View usage reports in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/view-usage-reports)
* Content Source: [SharePoint/SharePointServer/administration/view-usage-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/view-usage-reports.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@Naxxan60  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
