### ISSUE TITLE
Change not saving

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/OfficeDocs-SharePoint#749]
I followed the above instructions and go to the "infopath" settings in the legacy SPO portal, when I enable I get a popup warning that it's being replaced along with a link (that goes to a "404" page) and clicking OK on that popup and then OK to save the change and I'm forwarded to the new SPO admin portal. I go back and the change wasn't saved, it's still not activated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9bd7-cf8a-779b-368a-41187574834d
* Version Independent ID: 76da0413-17e0-94fa-e59b-e667b459cce5
* Content: [Configure InfoPath Forms Services](https://docs.microsoft.com/en-us/sharepoint/configure-infopath-forms-services)
* Content Source: [SharePoint/SharePointOnline/configure-infopath-forms-services.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/configure-infopath-forms-services.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@stoff75 , thanks for reporting this issue. We looked into it and found that it can take a while for the change to be saved. You should be able to see the change if you wait about 15 minutes. If you still don't, please use the Feedback button or open a support ticket to send the issue to the team to investigate. Thank you!
