### ISSUE TITLE
Drawing Discrepancies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#75]
Figure 2 shows one SQL Server in the Azure recovery environment, Figure 3 shows 2 SQL servers in that environment. Why is there a difference in the diagrams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff4b307e-efda-a478-3d50-7c9411df0179
* Version Independent ID: 495502ce-42b9-98fd-c29a-cd06d2b1c52a
* Content: [Plan for SQL Server Always On and Microsoft Azure for SharePoint Server Disaster Recovery](https://docs.microsoft.com/en-us/SharePoint/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery#Bp4)
* Content Source: [SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/plan-for-sql-server-always-on-and-microsoft-azure-disaster-recovery.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
This is likely an oversight in figure 2, showing a representation of HA farm with search. Figure 3, shows accurate details for a Warm standby farm for disaster recovery as required.
