### ISSUE TITLE
Recommend disabling antivirus scanning including Windows Defender

### ISSUE THREAD

**Issue by larslynch** [MicrosoftDocs/OfficeDocs-SharePoint#750]
Most antivirus programs including Windows Defender will want to scan each and every file processed by the SharePoint Migration Tool in the scanning stage.  This increases network traffic immensely and slows down the whole process.

Windows Defender can be disabled via the Local Policy editor (run "gpedit.msc" and then find the Computer Configuration &gt; Administrative Templates &gt; Windows Components &gt; Windows Defender &gt; Turn off Windows Defender entry and set to Enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@larslynch  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
