### ISSUE TITLE
SCCM OneDrive sample

### ISSUE THREAD

**Issue by JJbansh** [MicrosoftDocs/OfficeDocs-SharePoint#753]
the Zip fails to import. Please advise.

"the specified file does not contain a configuration manager application"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a307a-4572-7255-eaad-34a0884cb93d
* Version Independent ID: 976efb44-bf8a-ed55-c854-6c49ecdea722
* Content: [Deploy OneDrive apps using SCCM](https://docs.microsoft.com/en-us/onedrive/deploy-on-windows#feedback)
* Content Source: [OneDrive/deploy-on-windows.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-on-windows.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
@JJbansh , thanks for reporting this. The team is investigating. We recently fixed a different issue, and may have introduced a new problem. I'm sorry I can't help yet, but I'll comment here when I hear more.

**Comment by kaarins** [comment]
@JJbansh , I think we identified and fixed the issue. Please let me know if the sample package still fails to import. Thanks again!
