### ISSUE TITLE
Number of sites

### ISSUE THREAD

**Issue by 2x4b523p** [MicrosoftDocs/OfficeDocs-SharePoint#755]
The article doesn't mention if there are limits on the number of sites associated with a hub site. I'd hate to assume something this important. Is that information available somewhere?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites#feedback)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by kaarins** [comment]
Hi @2x4b523p , thanks for asking. There is no limit on the number of sites that can be associated with a hub site. We note this in the article about creating hub sites, but not in this article. That would be a good addition. Thanks again!
