### ISSUE TITLE
Unable to change users who can associate site

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#756]
The note in step 6 states that we should be able to use the Hub Site Settings to change the list of people who can associate sites with the hub site, when I go to a hub site, i do not see this option. Has it been deployed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4df1d8-955c-63d2-628e-8359391b8710
* Version Independent ID: 01326ab6-1270-d096-64e8-eb7d63ea9863
* Content: [Create a hub site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-hub-site)
* Content Source: [SharePoint/SharePointOnline/create-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by boby5555** [comment]
I think this is a mistake from Microsoft. If you want to change the list of users who can associate sites to the hub site, you need to go in the Active sites in the central admin -> Select your site -> List menu Hub Site -> Change hub site settings. If you go directly on the site, you can just edit the hub site navigation name, hub site logo and Site design applied.

**Comment by VLG17** [comment]
@DeanGross I have tested the behavior described in the article and it works as described for me. I guess the article got updated, because it describes exactly the steps mentioned by @boby5555.

Could you please check again? 

Make sure you're in the **new** Sharepoint Admin Center -> Active Sites -> select a site -> select **Hub site**, and then select **Register as hub site** -> and there you will have the option described.

**Comment by scanum** [comment]
@DeanGross  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@DeanGross  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
