### ISSUE TITLE
Mobile App & Azure AD Application Proxy

### ISSUE THREAD

**Issue by pmaeschli** [MicrosoftDocs/OfficeDocs-SharePoint#768]
Hi, can you please confirm, if the scenario using the mobile app via an azure ad application proxy is supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42bcdeb-a2a5-e6f1-4779-d7d5b837db1e
* Version Independent ID: 2d2bc902-f138-621f-3fc2-1de76bbe3f22
* Content: [Supporting the SharePoint mobile apps online and on-premises](https://docs.microsoft.com/en-us/sharepoint/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises#feedback)
* Content Source: [SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/supporting-the-sharepoint-mobile-apps-online-and-on-premises.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by tseward** [comment]
It is not supported. Only NTLM at this time.
