### ISSUE TITLE
Configuration DB Recommendations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#77]
You state "Full. We recommend that you switch the configuration database to the simple recovery model to restrict growth of the log file" but in the notes you state that we should backup the Transaction log frequently to force truncation. We can't do both of these, can you please clarify the guidance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8065895-eb6b-e4a5-967a-73bee4605d50
* Version Independent ID: ce168605-1ed4-d626-476d-d4120be2a6cf
* Content: [Database types and descriptions in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/technical-reference/database-types-and-descriptions)
* Content Source: [SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/database-types-and-descriptions.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by Techwriter40** [comment]
@bentoncity please review and correct.

**Comment by bentoncity** [comment]
Hi Dean, I'm researching the note to see if this should actually be removed. Will address as soon as I get more information from the product team.

**Comment by bentoncity** [comment]
Revised the statements to show the preferred method is to set the config database to full recovery model and to take backups to truncate the logs.
