### ISSUE TITLE
Block syncing of specific file types on onedrive

### ISSUE THREAD

**Issue by vishwalshah** [MicrosoftDocs/OfficeDocs-SharePoint#770]
The page does not load properly. There is a processing/ waiting sign and inaccessible components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3a0cebd-7e82-6631-bdee-031b3b84f74d
* Version Independent ID: ee04db29-a6db-2874-2573-d80f0b415308
* Content: [Block syncing of specific file types](https://docs.microsoft.com/en-us/onedrive/block-file-types?redirectSourcePath=%252fen-us%252farticle%252fblock-syncing-of-specific-file-types-7d7168dd-9015-4245-a971-61b504f834d6#feedback)
* Content Source: [OneDrive/block-file-types.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/block-file-types.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
This looks like a temporary issue @vishwalshah, @scanum.
- Is this issue still present?
- What part of the documentation you would like to be added?

Jose

**Comment by scanum** [comment]
@vishwalshah  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
