### ISSUE TITLE
Visual C++ redistributable version

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-SharePoint#771]
There are several versions of the Visual C++ Redistributable Package for Visual Studio 2012: which is the right one for SharePoint 2016? Does the redistributable version matter according to the Windows Server version used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a397fdd2-9945-dd56-2a66-61c6c478f1bb
* Version Independent ID: 9ac6cdbe-ad5e-1a00-7978-0801733d1b75
* Content: [Hardware and software requirements for SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements#feedback)
* Content Source: [SharePoint/SharePointServer/install/hardware-and-software-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/hardware-and-software-requirements.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
The correct links are listed here: https://docs.microsoft.com/en-us/sharepoint/install/hardware-and-software-requirements#links-to-applicable-software

**Comment by Techwriter40** [comment]
@LuigiBruno It appears Trevor has answered your question.  I am closing the comment for now, but feel free to reopen at anytime.  thanks for your feedback.
