### ISSUE TITLE
No Way To Block by IP Range?

### ISSUE THREAD

**Issue by andrewc513** [MicrosoftDocs/OfficeDocs-SharePoint#772]
In the OneDrive admin center, you can use these docs to only allow access by specific IP ranges, but not block specific IP ranges.  If you use Conditional Access to block by IP ranges, you have to scope the policy to SharePoint Online, which will also blocks access to SharePoint sites, Teams, Planner, Delve, etc.. which is undesirable.

Is there no other way to accomplish merely blocking OneDrive for Business access by IP range? I feel like an extra button for a "block" action in the same place as the "allow" action in this documentation would be simple enough, no?

This design makes compliance for some of our departmental units very difficult.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4264cd-3476-61ae-49dc-c5fa6118722a
* Version Independent ID: 8c419a14-db06-3b0d-66d3-ab396924721e
* Content: [Control access based on network location or app](https://docs.microsoft.com/en-us/onedrive/control-access-based-on-network-location-or-app#feedback)
* Content Source: [OneDrive/control-access-based-on-network-location-or-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/control-access-based-on-network-location-or-app.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by VLG17** [comment]
@andrewc513 you raised a valid point! I suggest providing this feedback by using User Voice for OneDrive: https://onedrive.uservoice.com/ -> it's your best bet at changing the current design.

At the moment, blocking an address range is done by excluding it from what you allow. And yes, conditional access cannot be used because it will block also other features/services (which is expected, given that OneDrive for Business works on top of Sharepoint, as do Teams, Planner and others).

**Comment by scanum** [comment]
@andrewc513 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by abid1975** [comment]
when i am adding a private IP range 10.242.0.0/16, it is not accepting. please help me know what could be the possible reason?
