### ISSUE TITLE
External user definitions

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/OfficeDocs-SharePoint#773]
Howdy - this is not consistent with the licensing definition of an External User. This is likely to cause confusion. Other organisations with the same ownership ('affiliates') cannot be treated as External Users as the licensing treatment is different.

What is an external user?
An external user is someone from outside your Office 365 subscription to whom you have given access to one or more sites, files, or folders. 

From the OST: 
“External User” means a user of an Online Service that is not an employee, onsite contractor, or onsite agent of Customer or its Affiliates.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview](https://docs.microsoft.com/en-nz/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@PeteHaigh-MSFT, there is some terminology coherence work going on in this area. Ping me on email if you would like to chat about it.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by PeteHaigh-MSFT** [comment]
@MikePlumleyMSFT I'll give you a shout ...

**Comment by scanum** [comment]
@PeteHaigh-MSFT We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
