### ISSUE TITLE
Configure Team site libraries to sync automatically

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/OfficeDocs-SharePoint#774]
Can you please add support to deploy this setting via Intune CSP utilising the Admx backend policy?? All the other policies can be easily deployed using the admx but this one because the way the url needs to be input and the way the url is parsed by the windows 10 device once received in xml there is apparently no way to use the coded string for - “dash” which is (%2D) without breaking the xml parsing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@schenardie  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint* better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
