### ISSUE TITLE
ADAL doesn't seem to be disabled on some clients

### ISSUE THREAD

**Issue by ScHwAnG86** [MicrosoftDocs/OfficeDocs-SharePoint#775]
I'm getting a "Sorry, OneDrive can't add your folder right now" for some users in my tenant. I've confirmed they have access to the Sharepoint site in the other organisation, and it works on several other PCs in the same domain. I've checked that the EnableADAL registry key is set to 0 and rerun the command a number of times - is it possible that this EnableADAL key is being ignored by a new build of OneDrive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync#feedback)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@ScHwAnG86  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ScHwAnG86** [comment]
Note I have now resolved the issue - it looks like disabling ADAL via the registry key listed above doesn't always take effect immediately, on some clients I had to wait a few hours before it took effect. Even rebooting, restarting the OneDrive client etc. did not make it take effect. Hopefully will help someone suffering the same issue!
