### ISSUE TITLE
Love the layout

### ISSUE THREAD

**Issue by richlow** [MicrosoftDocs/OfficeDocs-SharePoint#776]
Hey, I am a big fan of the three column layout that you guys are running here... 

I am keen to use something similar on my companies Sharepoint instance... is there an open template or something else that I could use?

Keep up the nice clean design

Rich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c744272-76d3-f60a-9d06-570d36ffb529
* Version Independent ID: 24208c34-c0f1-4ab0-5d92-9c3997211729
* Content: [Manage sites in the new SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/manage-sites-in-new-admin-center#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@richlow  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
