### ISSUE TITLE
Sample commands do not work

### ISSUE THREAD

**Issue by LouFarho** [MicrosoftDocs/OfficeDocs-SharePoint#777]
I have copied the commands and tried to execute it. I am a global admin for my DEV Tenant. I also downloaded the latest release of SPO Management Shell and installed it. 

Get-SPOSite is failing. I am able to successfully connect to the admin tenant using connect-sposervice 
C:\WINDOWS\system32&gt;  Get-SPOSite -Identity https://7slots.sharepoint.com
Get-SPOSite : The type of data at position 1629 is different than the one expected.
At line:1 char:2
+  Get-SPOSite -Identity https://7slots.sharepoint.com
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOSite], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Online.SharePoint.PowerShell.GetSite

If I try another site, I get the following:
Get-SPOSite : The type of data at position 1743 is different than the one expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f92a9b5-b3b2-aceb-9813-a3e48bb469ca
* Version Independent ID: 55aa37c6-998b-a8d8-8986-88c4ed868aea
* Content: [Get a list of all user OneDrive URLs in your organization](https://docs.microsoft.com/en-us/onedrive/list-onedrive-urls?redirectSourcePath=%252fen-us%252farticle%252f8e200cb2-c768-49cb-88ec-53493e8ad80a)
* Content Source: [OneDrive/list-onedrive-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/list-onedrive-urls.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@LouFarho  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
