### ISSUE TITLE
MinRole Shared Role

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#78]
How does the Application with Search minrole align with the above architectural suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e12588-d632-a9fa-c3e8-aa6bb1b46f73
* Version Independent ID: a7c0a603-f37a-ebad-2870-b35a9b3e76e3
* Content: [Plan enterprise search architecture in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/search/plan-enterprise-search-architecture)
* Content Source: [SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/plan-enterprise-search-architecture.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
I'm not sure I understand your question completely. All servers that shall be part of the enterprise search architecture need SharePoint to be installed with the Search MinRole. After creating the SSA you have all search components on one server, and then have to move them to the designated servers (with Search MinRole) ([here's](https://docs.microsoft.com/en-us/sharepoint/search/change-the-default-search-topology) an example). Let me know if this didn't answer your question.

**Comment by DeanGross** [comment]
All of the recommendations seem to be for farms in which the Search roles are on dedicated servers. It would be helpful if there were architectural diagrams and tables of Minimum Hardware Resources for scenarios with Shared Role servers e.g., Application with Search

**Comment by tseward** [comment]
That would be a "it depends".

**Comment by kenwith** [comment]
I am going to close this one out but please re-open if needed. I think @tseward might have the most experience here and maybe he could submit a PR with some of that knowledge to help clarify the article. Appreciated everyone!

**Comment by tklarsen** [comment]
I checked with the product team on the request for guidelines for mixing search and other roles on the same server. The answer is that mixing roles is not recommended in production because it leads to large and unpredictable variations in performance. The alternative is to split up in several VMs and assign them to distinct roles.
