### ISSUE TITLE
Missing nbr of variables for SPD 2013

### ISSUE THREAD

**Issue by sharvancik** [MicrosoftDocs/OfficeDocs-SharePoint#781]
So reviewing these limits, I see no mention of the number of variables that SharePoint Designer 2013 on premise has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/install/software-boundaries-and-limits#feedback)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@sharvancik thank you for reaching out and helping improve MS docs.  I'll look into this and have an answer for you soonest.

**Comment by Techwriter40** [comment]
@sharvancik Thank your for your feedback.  Can you tell me what specific limit you are looking for in regards to SPD 2013 ??

**Comment by scanum** [comment]
@sharvancik  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
