### ISSUE TITLE
Metadata Upload

### ISSUE THREAD

**Issue by nickisashkir** [MicrosoftDocs/OfficeDocs-SharePoint#787]
Hello,

I have over 40,000 files I need to upload into about 500 individual folders. Problem is I'm uploading them in chunks. I can create CSVs easily. But, can I also have it "fill out" the metadata via the CSV? This is the only thing holding me back from using sharepoint instead of springcm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration#feedback)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi:  Researching this for you now.

**Comment by JoanneHendrickson** [comment]
Hi:

Unfortunately, we don't support this.  However, can you suggest this idea on Uservoice? The product team is actively looking at it and looking for the community to vote on what they want to see next.
 
https://Aka.ms/migrationuservoice  


Joanne

**Comment by scanum** [comment]
@nickisashkir  - thank you for submitting feedback.

As @JoanneHendrickson suggested,I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
