### ISSUE TITLE
Download tool... doesn't work

### ISSUE THREAD

**Issue by solinear** [MicrosoftDocs/OfficeDocs-SharePoint#788]
I was crazy happy when I saw "Download the tool".  Then I ran it... so excited.... then I see in the "From:" field "spmtreleasesus.blob.core.windows.net" and my heart sank.  You provided all the files in the download, then made the build.application go and redownload it all and I am still getting the same error (not surprised). 

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Solinear:   
Did you remember to  “unblock” the zip file first? Without unblocking, it will behave as you experienced; you being sent to the remote installation site.  Sorry you are having this problem -- can you try this again and let me know.

1.Download SPMT.zip package.
2.Right-click the zip file, and then click properties.
3.On the General tab, select Unblock. Click OK.
4.Open the zip file and extract all files.
5.Run the build.application file.

**Comment by solinear** [comment]
I did unblock it and that didn't help and it seemed to keep going out to the internet to pull down the files.  Today I went and tried again (just in case something was updated) and when I ran the build.application, it 'downloaded' in about 1 second (versus the 1-2 minutes when it pulls it from the internet) and *bam!* it installed and is now working.

I had tried the normal installer on the internet and it failed right immediately before redownloading the package here, unblocking, unzipping and running again, so I think it was something that changed in the installer, not my machine.

Whatever was changed, it's working now.  Thanks!

**Comment by scanum** [comment]
@solinear  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by GitWesDone** [comment]
Nope not resolved.
