### ISSUE TITLE
Mount-SPContentDatabase is linked to wrong URL

### ISSUE THREAD

**Issue by uakkab** [MicrosoftDocs/OfficeDocs-SharePoint#789]
Mount-SPContentDatabase is going to the wrong url https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/Get-SPAlternateURL?view=sharepoint-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 752b9f67-0df0-861b-e83b-80c4801162c1
* Version Independent ID: f58c9647-7042-4f12-9986-79f1f025e6bf
* Content: [Copy configuration settings between farms in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/copy-configuration-settings-between-farms)
* Content Source: [SharePoint/SharePointServer/administration/copy-configuration-settings-between-farms.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/copy-configuration-settings-between-farms.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tseward** [comment]
@AndreaBarr this can be closed.
