### ISSUE TITLE
Footnote question - amount of RAM

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#79]
What does this phrase mean, why are there 2 values for RAM? with less resources than 500 GB RAM, 32 GB RAM, and eight CPU cores.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b34432-147d-b671-a32a-b534bcdbd36a
* Version Independent ID: cf305ace-225c-e3e9-b11f-7c18c930c31c
* Content: [Redesign enterprise search topology for specific performance requirements in SharePoint 2016](https://docs.microsoft.com/en-us/sharepoint/search/redesign-for-specific-performance-requirements)
* Content Source: [SharePoint/SharePointServer/search/redesign-for-specific-performance-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/search/redesign-for-specific-performance-requirements.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tklarsen** [comment]
This was a typo and has been corrected now. There should only be one value for RAM.
