### ISSUE TITLE
Totally Wrong. Just Wrong

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/OfficeDocs-SharePoint#790]
First, there is no such option under Policies. The only option under policies in Access Control.

There is something under Sites &gt; Active Sites &gt; &lt;Select Site&gt; &gt; Sharing

Not only is the UI incredibly stupid (Do we really, really, need five separate places to enable this?) but the docs are just plain wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@boomalator thank you for reaching out and helping to improve MS docs. We value your contribution.  Could you maybe suggest the changes that you think should be put in place to improve the UI?

**Comment by kaarins** [comment]
@boomalator Sorry for the confusion. We recently rolled out a new Sharing page and updated this article to correspond, but not everyone had the new page yet. I have since updated this article with new screenshots, and I hope you're now seeing the page shown in the screenshots.
