### ISSUE TITLE
Clarify the setting of `enable auto-create statistics`

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/OfficeDocs-SharePoint#791]
In the section "Configure specific SQL Server settings before you deploy SharePoint Server" the bulletpoints say (in order):

> * Do not enable auto-create statistics on SharePoint content databases. [...]
> * For SharePoint Server 2013 [...]
>    * Content databases have the Auto Update Statistics property set to **False**
> * For SharePoint Server 2016 and 2019 [...]
>    * Content databases have the Auto Update Statistics property set to **True**

I'm guessing the first point is outdated and the second and third are correct. Can someone please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31588cac-efbb-da8f-8b1f-8f4a21298116
* Version Independent ID: d5fead27-6212-5bc7-5bbf-9ce2066f479d
* Content: [Best practices for SQL Server in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm#configure-specific-sql-server-settings-before-you-deploy-sharepoint-server)
* Content Source: [SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/best-practices-for-sql-server-in-a-sharepoint-server-farm.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@AndreaBarr can you assign to me, please?

@nils-a auto update is supported for 2016/2019.

**Comment by tseward** [comment]
@nils-a Did this answer your question? Do you believe the doc could be clarified in any way?

**Comment by nils-a** [comment]
After reading the Text a couple of times more. I came to the conclusion I got confused by "auto create" and "auto update".

So... The text is fine and the error is mine. :-)
Sorry for the confusion.
