### ISSUE TITLE
"Create a permission level" section is inaccurate

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/OfficeDocs-SharePoint#794]
Step #2 is incorrect ("On the Site Settings page, in the Users and Permissions section, choose Site permissions.").  The new navigation path in SharePoint Online seems to be: Gear icon &gt; Site Permissions &gt; Advanced Site Permissions. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db58d185-0ee0-84a4-1569-3ff03555f387
* Version Independent ID: 95bd3846-4772-6130-a552-0f31df69053d
* Content: [How to create and edit permission levels](https://docs.microsoft.com/en-us/sharepoint/how-to-create-and-edit-permission-levels)
* Content Source: [SharePoint/SharePointOnline/how-to-create-and-edit-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/how-to-create-and-edit-permission-levels.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@chrisweis It will depend on if you're using Classic or Modern sites. Yes, the steps you describe is correct for Modern. We'll have to create a split in content, here.

@AndreaBarr can you assign to me, please?

**Comment by scanum** [comment]
@chrisweis We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by chrisweis** [comment]
Why was this closed?  The comment above from tseward acknowledged the issue, no?

**Comment by tseward** [comment]
@chrisweis it was closed as there was a fix implemented (that's what the purple Merged icon means when you read the thread). You can see the changes here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/849
