### ISSUE TITLE
Help Content does not match the current new SharePoint admin in our tenant

### ISSUE THREAD

**Issue by SteveMinar** [MicrosoftDocs/OfficeDocs-SharePoint#796]
From the text above: In the left pane of the new SharePoint admin center, under Policies, select Sharing.

There is no Sharing link/section under Policies in our current version of the new SharePoint admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed46514-8036-a543-d690-73d48acef690
* Version Independent ID: 8542c3ce-3012-3d23-c3e4-4331dac033d2
* Content: [Turn external sharing on or off](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off)
* Content Source: [SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/turn-external-sharing-on-or-off.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tseward** [comment]
@SteveMinar would you mind clarifying? The section is certainly there in the modern admin center.

**Comment by SteveMinar** [comment]
@tseward Let me see if I can clarify a bit.

I was in the process of setting up external sharing for our Office 365 tenant, including creating job aids and a screenshare video. At that moment in time, the website was not offering the Sharing feature in the modern admin center. I tried using Chrome, Safari and Firefox on OS X (High Sierra, all browsers up-to-date). I also tried using Chrome and Edge on Windows 10. Private/Incognito browser sessions were attempted as well. Microsoft support participated via live screenshare for some of these tests. I did logout/login numerous times and even attempted to use VPN to see if site access from a different geographic location would serve different content. No apparent differences were observed. Microsoft support staff I worked with were not yet well versed in the external sharing changes/features.

The same behavior was seen for much of the day.

Several days later, the modern admin center began presenting the Sharing section. It seems to be working.

I still haven't found a strong, accurate overview of the current sharing functionality in Office 365 / SharePoint. If you are aware of a good resource, I'd love a link.
We've been waiting for more functional external sharing. If I recall correctly, sharing to a specific person and anonymous sharing became available for use at the same time and required allowing anonymous sharing in your tenant. It was as if sharing to a specific person was treated as one form of anonymous sharing. All other sharing required an MSA account, a work/school account or membership in the source tenant. You used to be able to create and send a sharing link that helped the receiver use or create an MSA account.

If I understand the current sharing features correctly:
- You can control the available sharing level of SharePoint and OneDrive separately for the whole tenant.
- Changing the setting for the tenant doesn't change the sharing settings for existing SharePoint sites. You have to go to each site and set the desired sharing level.
- Changing the setting for the tenant doesn't seem to affect the default settings for new SharePoint sites. We changed our tenant setting to allow anonymous sharing, but new Teams (which create underlying SharePoint sites) do not get anonymous sharing at creation time.
- sharing to specific users (sharing to a specific email address) is now treated differently. It's not considered anonymous sharing
- I can set sharing expiration for anonymous sharing, but I can't do so for sharing to specific users
- I don't see an obvious way to share a file/folder that helps the recipient create or use an MSA account. It seems like I have to add them as a guest in our tenant first (i've not tested this extensively yet)
- I am unaware of any easy way (in Office 365) for an admin to report on what files/folders have been shared with whom and in what way.

**Comment by tseward** [comment]
Nothing you state sounds incorrect. SPO evolves so rapidly at times that these issues/points will change and no longer be applicable. I suppose the best overview would be at https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview.

Is there anything we need to do in the doc you referenced originally, or may we close this issue?

**Comment by scanum** [comment]
@SteveMinar  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by SteveMinar** [comment]
My apologies for the slow response. Hit hard by the flu.
Situation appears to be resolved - agree with closing the issue.
Only request is for continued improvement at releasing docs at the same time features show up. Not an easy task, I'm sure. It would have saved me a significant amount of time in this particular instance. Thanks for your help and followup.
