### ISSUE TITLE
OneDrive Settings

### ISSUE THREAD

**Issue by tristanpen** [MicrosoftDocs/OfficeDocs-SharePoint#797]
Just going through this help page and following the instructions to change External sharing for a user's OneDrive.  However, under Users &gt; Active users there is no OneDrive Settings under the new Admin experience.  I have tried clicking on Manage Product Licences to see if I can change the OneDrive settings there but nothing happens when I click on it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Change the external sharing setting for a user's OneDrive](https://docs.microsoft.com/en-us/onedrive/user-external-sharing-settings#feedback)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@tristanpen  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by greendx** [comment]
I have the same question. I'm not seeing an option for onedrive settings for active users. Can you clarify how to get to this setting?
