### ISSUE TITLE
IRM Enabled Document Libraries break Sharing and Collaboration abilities 

### ISSUE THREAD

**Issue by jkoenig-mgm** [MicrosoftDocs/OfficeDocs-SharePoint#799]
when IRM is enabled on a SharePoint Online Group's Document library, Documents that are opened from a Synced library, will not open from windows explorer (a message is received, that states the user does not have rights to view document)... If the same document is opened by using the File Open menu from word (365), the file becomes locked to that user (checked out), even if open as read-only. this means the file can not be viewed in word-online or MS Teams. Is the only solution for this, moving from IRM to Azure RMS ? Or is this an environment issue in our company ? (we are using Azure AD, only for Dynamics 365)

**Comment by scanum** [comment]
@jkoenig-mgm  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
