### ISSUE TITLE
The Table under Service application accounts is broken

### ISSUE THREAD

**Issue by itbland** [MicrosoftDocs/OfficeDocs-SharePoint#8]
I presume the translation to markdown has destroyed this table--the information presented makes no sense. It appears that the nested table became broken, but I can't make any sense of the information at all.
https://docs.microsoft.com/en-us/SharePoint/security-for-sharepoint-server/plan-for-administrative-and-service-accounts#service-application-accounts

**Comment by itbland** [comment]
Here is a look at the old site with the property nested table. [https://web.archive.org/web/20170722145353/https://technet.microsoft.com/en-us/library/cc263445.aspx](url) Also, the first row of the table is missing that the account must be a member of the Farm Admins group (I think!)

**Comment by Techwriter40** [comment]
updated table..closing comment
