### ISSUE TITLE
Use-CacheCluster is not a valid command

### ISSUE THREAD

**Issue by njmathews8** [MicrosoftDocs/OfficeDocs-SharePoint#802]
Use-CacheCluster is not a valid command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff8221d-8995-2bd1-9ab4-e0043afe1c5f
* Version Independent ID: 2b157758-daa4-dad2-5edb-891e421d921f
* Content: [Manage the Distributed Cache service in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/manage-the-distributed-cache-service)
* Content Source: [SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/manage-the-distributed-cache-service.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
It is a valid cmdlet but will only be available on SharePoint servers which have Distributed Cache provisioned.

**Comment by scanum** [comment]
@njmathews8  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
