### ISSUE TITLE
ADAL Requirement

### ISSUE THREAD

**Issue by CraigWalls** [MicrosoftDocs/OfficeDocs-SharePoint#803]
Hi there,

Really pleased to see this feature getting rolled out as my clients have been waiting a long time for it. One question - any ideas when we might see the ADAL restriction removed?

Generally we're dealing with non-technical users on the guest side so getting them to work through these requirements is problematic to say the least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69433cdb-79fb-e59d-e208-0c1201b74bfa
* Version Independent ID: e69001d7-2292-9f1a-e3d8-cf0afb9b18df
* Content: [B2B Sync](https://docs.microsoft.com/en-us/onedrive/b2b-sync#disable-adal)
* Content Source: [OneDrive/b2b-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/b2b-sync.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@CraigWalls  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
