### ISSUE TITLE
Creating subsites in modern site [collections]

### ISSUE THREAD

**Issue by LisaJo48** [MicrosoftDocs/OfficeDocs-SharePoint#804]
Any curious site owner will find that with all the hidden links and pages related to site creation via the Admin Portal leaves a sneaky gap. Go to Site Settings and click on "Sites and workspaces" and voila: there's a lovely 'Create' link that takes you straight to the classic site creation page and includes both classic and modern templates to choose from.

If you're going to hide stuff, Microsoft, HIDE IT ALL!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29978b1-a400-bacb-1330-55ed3d652053
* Version Independent ID: eae9fd16-57fc-1a80-3ce9-9b34b68eb1e0
* Content: [Manage site creation in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/manage-site-creation#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-site-creation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-creation.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@LisaJo48  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
