### ISSUE TITLE
Create a site in SharePoint Online is loading with empty panel

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [MicrosoftDocs/OfficeDocs-SharePoint#806]
Select + Create site on the SharePoint homepage.

Instead of showing the Team and Communication site templates, we are getting an empty panel.

![image](https://user-images.githubusercontent.com/18693389/54734653-feaeff00-4bc6-11e9-8185-c5a6983baafe.png)

In the console we are getting the following error message.

![image](https://user-images.githubusercontent.com/18693389/54734682-4897e500-4bc7-11e9-9cd0-cc975a179f6c.png)

**We are able to reproduce this issue in more than three tenants, it is intermittent.**

**Comment by tseward** [comment]
@Prakash-Ramasamy as this is a product issue, can you please raise a support case? You can open it in any one of the impacted tenants via admin.microsoft.com.

**Comment by scanum** [comment]
@Prakash-Ramasamy - thank you for submitting feedback.

As @tseward said, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Prakash-Ramasamy** [comment]
> @Prakash-Ramasamy - thank you for submitting feedback.
> 
> As @tseward said, I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> 
> Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> 
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@scanum Thank you for your response and solution. We will raise service ticket from our tenant.
