### ISSUE TITLE
 No "site migration" in SPMT V3(latest public preview)

### ISSUE THREAD

**Issue by fz2019** [MicrosoftDocs/OfficeDocs-SharePoint#809]
Can't find "site migration" option in SPMT V3(latest public preview), also "Pages" library isn't showing.

**Comment by killerewok2000** [comment]
if you try this build https://spmtreleasescus.blob.core.windows.net/betainstall/default.htm 
and you create a task for a site and keep the setting as default the full pages, navigation, webpart and structure. 
If this doesnt work please reach out to migrationuservoice@microsoft.com
Thanks

**Comment by scanum** [comment]
@fz2019  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
