### ISSUE TITLE
Recommendations on migrating 2TB of data to SharePoint?

### ISSUE THREAD

**Issue by jackxxu** [MicrosoftDocs/OfficeDocs-SharePoint#81]
I have 2TB PDF documents (around 1 million of them) that I would like to migrate to Sharepoint O365. The files are currently on my local Mac. What is the recommended approach to upload them so to maximize throughput and minimize the time it takes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bfd13a-2c3d-795e-fc52-855733971a27
* Version Independent ID: 207d3266-02ac-deb8-f5b3-165a0806501d
* Content: [SharePoint Online and OneDrive Migration Speed](https://docs.microsoft.com/en-us/SharePoint/migrate-to-sharepoint-online/sharepoint-online-and-onedrive-migration-speed#feedback)
* Content Source: [SharePoint/SharePointServer/migrate-to-sharepoint-online/sharepoint-online-and-onedrive-migration-speed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/migrate-to-sharepoint-online/sharepoint-online-and-onedrive-migration-speed.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jackxxu** [comment]
I have tried the SharePoint Migration Tool but selecting a local directory, but it simply takes too long and will take around 60+ days for 2TB of data.

**Comment by wenhua-helen** [comment]
@jackxxu 
In order to have good migration experiences, the recommended network card speed, RAM, CPU etc. are mentioned in http://aka.ms/spmt. 
Based on latest report from a customer with FastTrack servicing,   they migrated  4TB+ within several hours successfully. 
if you believe it is an issue with tool, please feel free to share everything under C:\Users\%user name%\AppData\Roaming\Microsoft\MigrationTool\admin@XXXX.onmicrosoft.com\WF_XXXXX folder to Migration dev servicing migration_team@microsoft.com.

**Comment by jackxxu** [comment]
@wenhua-helen I have sent the email to the address you provided. looking forward to hearing from you. 👀

**Comment by kenwith** [comment]
@jackxxu - hope this was resolved. @wenhua-helen is the person that runs the product team for this and it is super appreciated she jumped in.

If you haven't already resolved, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

I am personally very excited about the use case of migrating massive amounts of data (in TB) so looking forward to using this tool myself!
