### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by kcswe** [MicrosoftDocs/OfficeDocs-SharePoint#813]
In the following sentence: "For the Enterprise ring, until recently, the group policy set a reistry key under HKCU." the word "registry" is misspelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine (preview)](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by gacarini** [comment]
Good catch, this has been fixed!

**Comment by kaarins** [comment]
Thanks @kcswe and @gacarini
