### ISSUE TITLE
More info on updating the per-machine installed client

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-SharePoint#816]
Can we get a bit of detail on how the client updates itself when installed at the machine level?  
- Does it require admin rights to install the updates? 
- If not, how does it handle updating itself in the program files directory without admin rights?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by gacarini** [comment]
I've added a question to help answer this in the FAQ. See "Do automatic updates of the per-machine sync client require user intervention?" Let me know if that helps to clarify.

**Comment by NeighborGeek** [comment]
That's perfect, thanks!

Now, can you teach the Teams devs how to do a proper per machine install?

:)

**Comment by kaarins** [comment]
Thanks @NeighborGeek and @gacarini !
