### ISSUE TITLE
Sharepoint migration tool error showing "failed to submit the job to server" while migrating the data from file server 

### ISSUE THREAD

**Issue by Amitosh89** [MicrosoftDocs/OfficeDocs-SharePoint#82]
i was migrating the Data from the file server and getting error that failed to submit the job to server.

Data size only 12.08 GB with 4335 files 

please help on this

**Comment by kenwith** [comment]
@Amitosh89 - it is great we have the product team providing info too. This is an issue list for documentation and it is totally fine to open any issue here but I don't want your issue to go stale in this documentation issue list. 

If you haven't already got this resolved, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
