### ISSUE TITLE
Display template reference in SharePoint 2013 specifically excludes SharePoint Online

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/OfficeDocs-SharePoint#822]
The reference:
For a full list of available display templates, see Display templates for the Search Results Web Part in Display template reference in SharePoint Server 2013.

The page linked: https://docs.microsoft.com/en-us/SharePoint/technical-reference/display-template-reference-in-sharepoint-server
specifically excludes SharePoint Online.

Is there a separate list for SPOnline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55be1fa6-d7e0-7ce7-bb0e-b68e6d7597db
* Version Independent ID: 6740381f-cfd1-3c64-59c4-2eb60b12dd3b
* Content: [Change how search results look by using result types and display templates](https://docs.microsoft.com/en-us/sharepoint/use-result-types-and-display-templates)
* Content Source: [SharePoint/SharePointOnline/use-result-types-and-display-templates.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/use-result-types-and-display-templates.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@CraigHumphrey thank you for pointing this out and helping improve MS docs.  I'll investigate and have an answer for you soonest.

**Comment by scanum** [comment]
@CraigHumphrey  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
