### ISSUE TITLE
OneDrive Per-Machine - WIndows Server

### ISSUE THREAD

**Issue by nivaldotwtinfo** [MicrosoftDocs/OfficeDocs-SharePoint#824]
Hi guys, does Per-Machine version, will work as a service, meaning that i´ll not need to keep an open session on the machine so the files are synced?

Regards,
Nivaldo Soraggi Fernandes

**Comment by gacarini** [comment]
@nivaldotwtinfo Can you provide some more context on what you mean by not keeping an open session on the machine?

**Comment by nivaldotwtinfo** [comment]
Good afternoon Gaia. Today if I want my onedrive to sync with the cloud, my user session has to be open, meaning that it can´t be logout. My question was if with this update, onedrive would be able to work as a service, running on background whenever I´m loged in or not.

Att,
Nivaldo Soraggi Fernandes

Rua Paraíba, 1323  |  2º andar | Savassi


Av. Brig. Luis Antônio 2344 | Conj 111   | Bela Vista

Belo Horizonte/MG | CEP 30130-148

São Paulo/SP | CEP 01311-000

Fone +55 (31) 3273-1800

Fone: (11) 3522-3314  | (11) 3284-6691


[rodape-novembro azul (3)]
[Logo TWT em curvas]<http://www.twtinfo.com.br/>         [cid:image002.jpg@01D2336A.23189810]    [01] <http://www.facebook.com/pages/TWT-INFO/183955434977822> [03] <https://twitter.com/twtsoftware> [02] <http://www.linkedin.com/company/twt-info?trk=hb_tab_compy_id_1256295>

Nota de Confidencialidade: Esta mensagem e seus eventuais anexos podem conter dados confidenciais ou privilegiados. Se você os recebeu por engano ou não é um dos destinatários aos quais ela foi endereçada, por favor destrua-a e a todos os seus eventuais anexos ou copias realizadas,imediatamente. Por favor,informe-nos sobre o recebimento indevido desta mensagem, retornando-a para o autor. Agradecemos a gentileza de sua cooperação.

Confidential Note: This e-mail and any attachments are confidential or legally privileged. If you receveid this message in error or are not the intended recepient, forgive us for the mistake and please destroy the e-mail message and any attachments or copies. Please inform us of the erroneous delivery by return this e-mail. Thank you for your kind cooperation.

De: Gaia Carini <notifications@github.com>
Enviada em: sexta-feira, 29 de março de 2019 14:19
Para: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
Cc: Nivaldo S. Fernandes <nivaldo@twtinfo.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/OfficeDocs-SharePoint] OneDrive Per-Machine - WIndows Server (#824)


@nivaldotwtinfo<https://github.com/nivaldotwtinfo> Can you provide some more context on what you mean by not keeping an open session on the machine?

**Comment by gacarini** [comment]
Ah ok got it. Nothing changes about how OneDrive actually runs. The OneDrive.exe process is still in the context of a user's profile so if they log off, OneDrive will not be running. The service mentioned in the documentation is only for the auto-updates. Hope that helps clarify.

**Comment by nivaldotwtinfo** [comment]
Ok, thank you for the clarification.

Att,
Nivaldo Soraggi Fernandes

Rua Paraíba, 1323  |  2º andar | Savassi


Av. Brig. Luis Antônio 2344 | Conj 111   | Bela Vista

Belo Horizonte/MG | CEP 30130-148

São Paulo/SP | CEP 01311-000

Fone +55 (31) 3273-1800

Fone: (11) 3522-3314  | (11) 3284-6691


[rodape-novembro azul (3)]
[Logo TWT em curvas]<http://www.twtinfo.com.br/>         [cid:image002.jpg@01D2336A.23189810]    [01] <http://www.facebook.com/pages/TWT-INFO/183955434977822> [03] <https://twitter.com/twtsoftware> [02] <http://www.linkedin.com/company/twt-info?trk=hb_tab_compy_id_1256295>

Nota de Confidencialidade: Esta mensagem e seus eventuais anexos podem conter dados confidenciais ou privilegiados. Se você os recebeu por engano ou não é um dos destinatários aos quais ela foi endereçada, por favor destrua-a e a todos os seus eventuais anexos ou copias realizadas,imediatamente. Por favor,informe-nos sobre o recebimento indevido desta mensagem, retornando-a para o autor. Agradecemos a gentileza de sua cooperação.

Confidential Note: This e-mail and any attachments are confidential or legally privileged. If you receveid this message in error or are not the intended recepient, forgive us for the mistake and please destroy the e-mail message and any attachments or copies. Please inform us of the erroneous delivery by return this e-mail. Thank you for your kind cooperation.

De: Gaia Carini <notifications@github.com>
Enviada em: sexta-feira, 29 de março de 2019 15:10
Para: MicrosoftDocs/OfficeDocs-SharePoint <OfficeDocs-SharePoint@noreply.github.com>
Cc: Nivaldo S. Fernandes <nivaldo@twtinfo.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/OfficeDocs-SharePoint] OneDrive Per-Machine - WIndows Server (#824)


Ah ok got it. Nothing changes about how OneDrive actually runs. The OneDrive.exe process is still in the context of a user's profile so if they log off, OneDrive will not be running. The service mentioned in the documentation is only for the auto-updates. Hope that helps clarify.

**Comment by scanum** [comment]
@nivaldotwtinfo  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
