### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by jusmig** [MicrosoftDocs/OfficeDocs-SharePoint#825]
Visual issue: a comma "," is missing between 'item(s) with scan issues' and 'item(s) filtered out.'

![Screen Shot 2019-03-25 at 11 57 32 AM](https://user-images.githubusercontent.com/8533701/54934662-47cbbf80-4ef5-11e9-94a8-dbee36520429.png)

**Comment by scanum** [comment]
@offiedocsbot assign @scanum

**Comment by scanum** [comment]
@jusmig Hi Justin, thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by j0rt3g4** [comment]
Hi, @Justfyn  Following what @scanum  says, basically we work on the documentation department, and we can't do changes in an application level, we can change just the documentation, not the apps. Thank you for reporting this.
