### ISSUE TITLE
Invite to external domains not always sent

### ISSUE THREAD

**Issue by ogghi** [MicrosoftDocs/OfficeDocs-SharePoint#826]
Hi, 

we are trying to invite external users by email to some files.
Some are getting the mail, some are not.

Is there any debug info / log we can see when using the online version?

Best regards
David

**Comment by scanum** [comment]
@ogghi  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
