### ISSUE TITLE
Not able to sync sharepoint files to onedrive using domain credentials.

### ISSUE THREAD

**Issue by Harinath-Reddy** [MicrosoftDocs/OfficeDocs-SharePoint#828]
Hi,
i followed the below document in link for configuring onedrive for sharepoint 2019 using GPO.

https://docs.microsoft.com/en-us/sharepoint/install/new-onedrive-sync-client.

But i am not able to sync sharepoint files from sites to onedrive using domain credentials and throwing error when i enter domain credentials like below.

![image](https://user-images.githubusercontent.com/39045928/54996086-5c3fb300-4fee-11e9-9fc8-751fe94a43fc.png)

please let me know where i am doing wrong.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Harinath-Reddy  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
