### ISSUE TITLE
Error on upload file to SharePoint online tenant using CSOM client in client web api application in .net framework 4.7.1

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/OfficeDocs-SharePoint#829]
When I try to upload file using a valid bearer token to communicate with my SharePoint Online tenant I receive this error :

The URL <URL> is invalid. It may refer to a nonexistent file or folder, or refer to a valid file or folder that is not in the current Web.

To obtain SP bearer I use this method :

```
private string BearerHeader
        {
            get
            {
                AuthenticationResult authResult = null;
                string result = string.Empty;
                if (HttpContext.Current != null)
                {
                    string sourceBearer = HttpContext.Current.Request.Headers["Authorization"];
                    if (sourceBearer.IndexOf(BearerPrefix) <= -1)
                    {
                        return string.Empty;
                    }
                    ClientCredential clientCred = new ClientCredential(ConfigurationManager.AppSettings["ida:Audience"], ConfigurationManager.AppSettings["ida:Secret"]);
                    UserAssertion userAssertion = new UserAssertion(sourceBearer.Split(' ')[1]);
                    AuthenticationContext authContext = new AuthenticationContext(ConfigurationManager.AppSettings["ida:Instance"] + ConfigurationManager.AppSettings["ida:Tenant"]);
                    var resource = new Uri(ConfigurationManager.AppSettings["SharePointCollection"]).GetLeftPart(UriPartial.Authority);
                    authResult = authContext.AcquireTokenAsync(resource, clientCred, userAssertion).Result;
                    result = authResult.AccessToken;
                }

                return BearerPrefix + result;
            }
        }
```

The bearer token works with SPQuery, read and delete commands.

When I use the same code with service account 

`context.Credentials = new SharePointOnlineCredentials("xxxx@xxxx.onmicrosoft.com", securepassword); `

the upload is working good.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@bertrandpons Thank you for reaching out. Please could you let me know what document or article you're referring to.

**Comment by scanum** [comment]
@bertrandpons We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
