### ISSUE TITLE
SQL Native Client for SharePoint 2013

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#83]
In the documentation, it indicates you should update the SQL Server 2008 R2 Native client on Windows Server to 10.50.6537.0. However, the SharePoint Server 2013 with Service Pack 1 bits point to a newer Native client for the pre-req installer, version 10.51.2500.0. The documentation should be clarified that the SQL Native client only needs to be updated if you are using SharePoint Server 2013 RTM media.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59acdf52-b8f5-f140-317e-00747b5d80d5
* Version Independent ID: ba2e186b-c2b6-4e09-208e-1b622ebcfed1
* Content: [Enable TLS and SSL support in SharePoint 2013](https://docs.microsoft.com/en-us/SharePoint/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013#step-1-update-sharepoint-servers-in-your-sharepoint-farm)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@tseward can you submit a PR and I will change it.. thanks

**Comment by tseward** [comment]
@Techwriter40 Could you engage someone from the SQL tiger team? The SNAC builds are a bit confusing. SNAC included with 2013 w/ SP1 is 10.51.2500.0. The hotfix is labeled as "SP3" but the version number is 10.50.6537.0. However, if downloading from the 2008 R2 SP3 Feature Pack, the SNAC version is 10.53.6000.34.

We know we cannot install the SNAC build from our SharePoint 2013 TLS 1.2 article, but I suspect that we might still need a newer SNAC build than what the pre-req installer for 2013 w/ SP1 downloads.

**Comment by Techwriter40** [comment]
@bentoncity can you check with the SQL team on Trevor's ask?  thanks

**Comment by bentoncity** [comment]
I've contacted several SQL and CSS folks to look at this.  Will comment when answer is found.

**Comment by tseward** [comment]
Any update on this one @bentoncity?

**Comment by bentoncity** [comment]
One of my SQL contacts gave me a couple aliases for the tiger team so I an ask on this to both.  This was on the 1st and haven't gotten any replies yet so I'll follow up and reping both aliases. Trevor, contact me and I'll send you the aliases.

**Comment by kenwith** [comment]
Ok awesome, would you mind opening a service ticket @tseward so we can get it routed and prioritized? Would love to see a PR for any updates. Super appreciate all the work on the docs!
