### ISSUE TITLE
"Lists & Libraries Doesn't Appear"

### ISSUE THREAD

**Issue by tangoprjct** [MicrosoftDocs/OfficeDocs-SharePoint#830]
I have followed these directions to the letter, but when I select "Settings", I don't have the option for "Lists & Libraries". Any thoughts as to why?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f1bd4ab-c640-1db8-05bb-e249129dfa46
* Version Independent ID: 4ceb7bc8-39c0-61fb-b31c-381cb7a5018b
* Content: [Change the default list and library experience](https://docs.microsoft.com/en-us/sharepoint/change-default-list-and-library-experience#feedback)
* Content Source: [SharePoint/SharePointOnline/change-default-list-and-library-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-list-and-library-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by hallje** [comment]
Had a site revert back to classic, came in to make sure this was still set to modern and also gone. What happen to it ?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@tangoprjct Thank you for reaching out.  There was a previous issue as well if you scroll to the bottom of the document.  This was supposed to be resolved on the 1st April 2019, so please have a look and let me know if you are still having this problem.

**Comment by scanum** [comment]
@tangoprjct  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by tangoprjct** [comment]
I just saw this update. I still don't have the "Lists and Libraries" option.

**Comment by lindspea** [comment]
@tangoprjct thanks for letting us know.  I'll have the team look into this and get back to you.

**Comment by lindspea** [comment]
@tangoprjct please have a look at this link.  If you switch over to 'modern' mode it might help. https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Delivering-SharePoint-modern-experiences/ba-p/315023

**Comment by giveitaGo** [comment]
@lindspea - The article you mention above mentions this:

" Disable modern experience for specific site collections. Administrators can use a PowerShell script to enable or disable the modern experience for a single site collection or for a list of site collections as provided by the SharePoint Modernization scanner.  Alternately, users can still use the “return to classic” option on modern views of lists or libraries to temporary return to classic, and list owners can use List Settings to configure that list to use the classic experience for all users. "

There is no mention of using a feature to accomplish this. Further, like the OP, I have looked Site Collection features, and in Site Features (SP 2019), and I cannot find anything that looks like it would help change the experience. Also, the contextual link to "Enable or disable site collection features" is a generic link to enable or disable a feature. It does not name the feature. This is confusing. 

From what I can tell, the only way to change this is via PowerShell. If that is the case, please update the documentation.

**Comment by giveitaGo** [comment]
I see this thread is intended for SP Online, but I do think you should still update the documentation to show the feature name. This link seems to be the true solution:
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-optout
