### ISSUE TITLE
Cannot create new template under the default "tenant.sharepoint.com" URL.

### ISSUE THREAD

**Issue by Svek** [MicrosoftDocs/OfficeDocs-SharePoint#832]
I was trying to upgrade our SharePoint experience from the old 2013 template to the **newer** ones. 

Apparently, it is not possible to recreate it under the new "Create a site" wizard.  I have attached a screenshot of it here.

![bug-report-1](https://user-images.githubusercontent.com/25241292/55084093-33471d00-50d7-11e9-87e7-423f0c6a372e.jpg)

_Note: that I was able to create it using the old 2013 template using the "Classic SharePoint admin center"_

**Comment by tseward** [comment]
There is a [new cmdlet released the other day](https://developer.microsoft.com/en-us/office/blogs/new-sharepoint-csom-version-released-for-sharepoint-online-march-2019/) called `Enable-SPOCommSite` which is used to replace the classic site at the root with a Communications Site (not Modern Team). This cmdlet is currently marked as experimental and may not work with your tenant.

In other words, to remain supported, you must wait until Microsoft enables this functionality in your tenant and you will not be able to use a Modern Team site template.

**Comment by scanum** [comment]
@Svek  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
