### ISSUE TITLE
Simplifying our SharePoint integration story.

### ISSUE THREAD

**Issue by bschwetz** [MicrosoftDocs/OfficeDocs-SharePoint#833]
Link to info does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5144c0-b2a7-8fce-e915-28b0e7f44ca0
* Version Independent ID: 3558508e-be15-dfec-5c98-6f2f7e5cba63
* Content: [What's deprecated or removed from SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019#feedback)
* Content Source: [SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/what-s-deprecated-or-removed-from-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment]
@bschwetz can you check again? The link is working for me.

**Comment by scanum** [comment]
@bschwetz  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
