### ISSUE TITLE
Error in documentation for "Start the service instances" section

### ISSUE THREAD

**Issue by RickBertuzzi** [MicrosoftDocs/OfficeDocs-SharePoint#835]
In the "Manage services on server" page in Central Admin (/_admin/Server.aspx) you can't click "Start" to start the services. There are only options to "Stop" or "Restart" depending on the service; most services don't have either option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97493854-efe6-3451-d96b-a04b6ac32075
* Version Independent ID: 46b84a4a-fbe2-5afc-f442-13d8411e395e
* Content: [Upgrade service applications to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/upgrade-service-applications-to-sharepoint-server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr  please assign to me.

**Comment by tseward** [comment]
@RickBertuzzi when a service instance is in a stopped state _and_ it can be managed, it will have a Start option. In certain scenarios, the same service instance may not have a start or stop option, such as when the server is configured with a particular MinRole like WebFrontEnd. Does this help?

**Comment by RickBertuzzi** [comment]
Hi @tseward . Thanks. Yes some clarification around why there may not be a Start option helps. Not a huge deal, just thought I'd point it out in case someone new to SharePoint is scratching their head looking for "Start".

**Comment by scanum** [comment]
@RickBertuzzi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
