### ISSUE TITLE
This is a joke, right?

### ISSUE THREAD

**Issue by christopherdengler** [MicrosoftDocs/OfficeDocs-SharePoint#836]
This is a joke, right?  In order to exclude certain products from installation users must edit XML configuration files?  So, IN ADDITION to the fact that you CANNOT install Office on ANY other drive other than C: with some really obscure registry hack (which can and does screw up your system), people can't uninstall programs from the Office Suite that they NEVER USE?  What happened to Microsoft?  This is not rocket science?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e41333c0-77d5-b375-1e0b-c92c4a5a90d9
* Version Independent ID: 7160e9ae-ffff-f979-d145-587f8c9eb2bc
* Content: [Changes to OneDrive sync client deployment in Office Click-to-Run](https://docs.microsoft.com/en-us/onedrive/exclude-or-uninstall-previous-sync-client)
* Content Source: [OneDrive/exclude-or-uninstall-previous-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/exclude-or-uninstall-previous-sync-client.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@christopherdengler Thank you for reaching out.  I'll look into this and get back to you soonest.

**Comment by christopherdengler** [comment]
It would really help if there was SOME sort of context in this email?

**Comment by kaarins** [comment]
@christopherdengler I checked with the Office CTR team and you are correct and Office must be installed on the C drive and you must use the Office Deployment Tool and a configuration XML. You can submit feedback on the Office UserVoice to request to change this. https://office365.uservoice.com/forums/264636-general. If you have a specific scenario that you'd like to share with the team, I'm also happy to pass along the info to them. Sorry.

**Comment by christopherdude** [comment]
@kaarins - See https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/330 - this is an ongoing issue that no one does anything about.  I appreciate you passing it along, but it hasn't been implemented despite 3 years of complaints.
