### ISSUE TITLE
SharePoint Server 2013 - End of Life for SQL and OS older versions

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#838]
Since SQL Server 2008 R2 and Windows Server 2008 R2 are nearing end of line (July 2019 and Jan 2020), what are the recommended approaches for upgrading? 

SQL can be upgraded via standing up a new SQL Server, restoring the databases and re-connecting the SP Farm. 

Similar to the SP 2016 upgrade approach above, Windows Server upgrade on the WFE is a bit more complicated, since any custom WSPs, 3rd party products, and configuration will need to be configured. The approach here would be to create a new side-by-side SP Farm (you might want to consider upgrading SP to 2016 at this point) with new the new OS, then install SharePoint and configure your farms services and service applications. WSPs can be extracted via PowerShell and copied over to the new SP Server and installed easily. 3rd party solutions (such as DLLs, libraries, etc.) may need to be installed on the new SP Farm. Then you can do a database-attach and cut over any DNS to the new servers. Then search can be recrawled, and other services synced up to the migrated content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef5bf9a-6a8a-b9cd-ab2a-0f79a7094f50
* Version Independent ID: d899b2ea-8d8d-32bc-57f1-e6438918e351
* Content: [High level overview to upgrade from SharePoint 2013 to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/upgrade-from-sharepoint2013-to-sharepointserver-2019)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/Upgrade-from-SharePoint2013-to-SharePointServer-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/Upgrade-from-SharePoint2013-to-SharePointServer-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
Recommended path for SharePoint Server would be to add servers with the desired/supported version of Windows Server to the existing farm. Minimal configuration should be required (IIS Bindings and SSL certs, any 3rd party apps you need to install locally). Other artifacts, such as WSPs are stored in the Config database and deployed as part of a Web App/farm deployment. DNS records may need to be adjusted. Search topology will need to be adjusted. As you add new SharePoint servers to the farm, eject the old ones they replace.

Web.config changes should never be made by hand, instead using the [`SPWebCofnigModification` class](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/bb861909(v%3doffice.14)).

This is the supported method to upgrading SharePoint servers to a newer version of Windows Server -- but you shouldn't remain in a mixed-OS state for SharePoint servers for very long.

**Comment by scanum** [comment]
@eschrader Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
