### ISSUE TITLE
SharePoint Foundation Support

### ISSUE THREAD

**Issue by systemsleitner** [MicrosoftDocs/OfficeDocs-SharePoint#842]
Does the SharePoint Migration Tool (Version 3.0.108.1) only support the SharePoint 2013 Server edition or also the SharePoint 2013 Foundation?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@systemsleitner Thank you for reaching out.  I'll have an answer for you shortly.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@systemsleitner  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
