### ISSUE TITLE
clarification on service account permissio

### ISSUE THREAD

**Issue by adalfa** [MicrosoftDocs/OfficeDocs-SharePoint#843]
in the section "Choosing MIM for use with SharePoint Server", step 3:  "Run as a service"  is a policy or any other kind of permission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efa9cc0-f34e-5987-5e4e-ed7740af689a
* Version Independent ID: 61dfe25a-aa67-7d00-edab-3b2647f53bab
* Content: [Install Microsoft Identity Manager for User Profiles in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/sharepoint/administration/install-microsoft-identity-manager-for-user-profiles-in-sharepoint-server-2016#feedback)
* Content Source: [SharePoint/SharePointServer/administration/install-microsoft-identity-manager-for-user-profiles-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/install-microsoft-identity-manager-for-user-profiles-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

@adalfa Yes, this is a Local Security Policy (secpol.msc) under User Rights Assignments. I will add some verbiage to point people towards that tool.

**Comment by adalfa** [comment]
@tseward thanks for the response, but while "log on as service" is a well know settings, "run as service" is for what I know absent in "User Right Assignment" or i am missing something.
thanks

**Comment by scanum** [comment]
@adalfa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
