### ISSUE TITLE
Please add information what license can be increased to 5TB

### ISSUE THREAD

**Issue by ufkz2909** [MicrosoftDocs/OfficeDocs-SharePoint#844]
Office 365 Enterprise E3 and E5Office 365 Government E3 and E5Office 365 Education and Office 365 Education E5OneDrive for Business Plan 2 and SharePoint Online Plan 2 - only license that can be incresed to 5 Tb

Because from your article look like all clients that have 5 license can increse their storage to 5 TB:

"For help finding out which subscription you have, see What Office 365 for business subscription do I have?
If your organization has 5 or more users, you can change the storage space to more than 5 TB. Contact Microsoft support to discuss your needs. You must assign at least one license to a user before you can increase the default OneDrive storage space.""

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space#feedback)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ufkz2909 Thank you for reaching out and helping improve MS docs.  Please have a look at this article and see if it answers your questions. https://docs.microsoft.com/office365/servicedescriptions/onedrive-for-business-service-description

**Comment by ufkz2909** [comment]
I know the answer, but it is much better when info is showing up in 1 article, and you don’t need to jump from 1 article to another it is very confusing:

Can you please complete article with all info. So cu will be able to see everything in one page. Like here for example:

http://help.dagobertogarcia.com/articles/22137-increase-onedrive-for-business-storage-up-to-5tb

**Comment by kaarins** [comment]
@ufkz2909 Thanks for this suggestion to help improve the documentation. I totally agree with you that having the plan info in this article would be way nicer. Unfortunately, because the plans change and we want to make sure we're always communicating the right info, we have to keep it in one place in the service description. :( I did update the note to clarify that the "more than 5 TB" part also depends on the plan. Thanks again!
