### ISSUE TITLE
What about Office 365 records?

### ISSUE THREAD

**Issue by PlanetWilson** [MicrosoftDocs/OfficeDocs-SharePoint#85]
Is there clear guidance on whether to use this or the more general Office 365 eDiscovery capabilities. That seems to be where the investment is, a system which covers all content repositories in Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19be9e48-8841-5d96-beab-d162a473f45d
* Version Independent ID: 7fac7443-168e-bc97-54d7-ed71394e5ccd
* Content: [Plan ways to convert active documents to records in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/plan-how-records-are-collected)
* Content Source: [SharePoint/SharePointServer/governance/plan-how-records-are-collected.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/plan-how-records-are-collected.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@PlanetWilson - I did find this information on Office 365: https://technet.microsoft.com/library/dn876574.aspx  It is still on TechNet and all content is moving to the new open source system on GitHub. So expect that it will move and likely be updated in future. But hope that helps.
