### ISSUE TITLE
Link labels

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/OfficeDocs-SharePoint#854]
Greetings,
It seems that each link to a page in "support.office.com" is automatically displaying the page title as the link label.
Depending on each sentence, the link label might need to be adequately edited.

&gt; Link 1:
In the intro paragraph, at the top of the page:
" [What is a SharePoint hub site?] help you organize your intranet. "
The link label should most probably be "Hub sites", and the sentence would become:
"[Hub sites] help you organize your intranet."

&gt; Link 2:
Section "Can I make just one hub site for my whole organization?"
" Naming conventions: Add a prefix to news article titles and use a [Use the Highlighted content web part] to roll up news (...) "
The link label should simply be "Highlighted content web part", and the sentence would become:
" Add a prefix to news article titles and use a [Highlighted content web part] to roll up news (...) "

&gt; Link 3:
Section "How should I organize my hub site? / Association"
"A site becomes part of a hub family by [Associate a SharePoint site with a hub site]. "
This one does not sound as weird as "Link 1" and "Link 2", but still, it might deserve review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d8d3fd-3c87-c237-495d-01ac9bcd7944
* Version Independent ID: 2c621ca7-5395-f4b8-b66a-aa8a8ab4b1e5
* Content: [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites)
* Content Source: [SharePoint/SharePointOnline/planning-hub-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/planning-hub-sites.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@a-zaf Thank you for your suggestions and improving MS docs.  I'll have them reviewed soonest.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@a-zaf  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
