### ISSUE TITLE
Improvements to German translation

### ISSUE THREAD

**Issue by gacarini** [MicrosoftDocs/OfficeDocs-SharePoint#857]
Filing based on feedback I received offline on the German translation
- synchronisierungsclient should be capitalized: Synchronisierungsclient
- Ordner% LocalAppData% has incorrect spacing with "%"
- "Anders als bei der Installation des Synchronisierungs Clients bleibt alles anders." --&gt; "Das Verhalten des Synchronisierungsclients ist absolut identisch."
- "Automatische Konvertierung von Benutzer auf pro Computer" --&gt; "Automatische Konvertierung von pro Benutzer auf pro Computer"
- "befinden" --&gt; "bleiben"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@gacarini Thank you for your help with this and helping improve MS docs.  We will send it to our translation team to sort out as soon as possible. 
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@MollyMalone , @lindspea Working on a fix (Bug 3276143)

**Comment by OfficeGlobal** [comment]
@gacarini , @MollyMalone The article has been HumanTranslated and published live

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@gacarini  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
