### ISSUE TITLE
Step # 3 could use details or link to do

### ISSUE THREAD

**Issue by JonathanHerschel** [MicrosoftDocs/OfficeDocs-SharePoint#858]
Step #3 says: Optional: Make the Office Online Server accessible outside the corporate network.
I can't find any detailed instructions on how to restrict only traffic from our SharePoint online tenant to access our on Prem OOS farm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a5545f-63bd-ebee-58d3-eedc755d333a
* Version Independent ID: 0850e274-de49-d0e4-4509-1a11216f81d1
* Content: [Enable previews of on-premises search results in cloud hybrid search](https://docs.microsoft.com/en-us/SharePoint/hybrid/enable-previews-of-on-premises-search-results-in-cloud-hybrid-search)
* Content Source: [SharePoint/SharePointServer/hybrid/enable-previews-of-on-premises-search-results-in-cloud-hybrid-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/enable-previews-of-on-premises-search-results-in-cloud-hybrid-search.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by Reeced40** [comment]
@JonathanHerschel Thank you for reaching out, I'll investigate and revert soonest.

**Comment by JonathanHerschel** [comment]
I recently submitted a MS ticket and confirmed that On Premise Document preview does not currently work in Modern Search, might want to make note of that.  Also was told Modern Search uses different mechanism, so is Office Online Server needed for new Modern Search document Preview?

**Comment by tseward** [comment]
@JonathanHerschel to answer the original question, you can use `Set-OfficeWebAppsHost` to narrow it down to your SharePoint on-prem Web App URLs. There's nothing you can do about previews in modern with on-prem content. I'll get the doc updated with the original issue you raised.

**Comment by tseward** [comment]
@JonathanHerschel I've added a brief overview of what must be done to make OOS accessible in this hybrid scenario. For modern search, there isn't anything you can do about file previews [at this time].

**Comment by scanum** [comment]
@JonathanHerschel Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
