### ISSUE TITLE
Installing EWS Managed API

### ISSUE THREAD

**Issue by tomrune** [MicrosoftDocs/OfficeDocs-SharePoint#86]
The EwsManagedAPI 2.2 can be installed With the slightly simpler syntax of:
msiexec /I EwsManagedApi.msi addlocal="ExchangeWebServicesApi_Feature" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7397955b-f709-07cd-91cd-fac746329614
* Version Independent ID: 3c5e58fc-10ee-bc5c-7c2d-9e881d058094
* Content: [Configure site mailboxes in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-site-mailboxes-in-sharepoint)
* Content Source: [SharePoint/SharePointServer/administration/configure-site-mailboxes-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-site-mailboxes-in-sharepoint.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by bentoncity** [comment]
Thanks Tom, I've revised as you show and republished this topic.
