### ISSUE TITLE
How to read data

### ISSUE THREAD

**Issue by clxiong123** [MicrosoftDocs/OfficeDocs-SharePoint#866]
I have test in my tenant. But I don't know how to read the data from the two uri : JobQueueUri and AzureContainerManifestUri

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa19c8fd-ca72-2fef-0be1-859e57b862c4
* Version Independent ID: 629968f3-9317-0c5a-3ea1-48c2ea102ac4
* Content: [Migration Asynchronous Metadata Read API](https://docs.microsoft.com/en-us/sharepointmigration/asynchronous-metadata-read-api#feedback)
* Content Source: [migration/Asynchronous-metadata-read-api.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Asynchronous-metadata-read-api.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@clxiong123 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
