### ISSUE TITLE
Incorrect environment variable syntax in Before You Begin Section

### ISSUE THREAD

**Issue by AspenForester** [MicrosoftDocs/OfficeDocs-SharePoint#867]
In the "Before You Begin" section, the UserProfile environment variable is referred to, but it is referred to in CMD syntax `%UserProfile%`, when, since this is in a PowerShell context, after all, it should be `$env:UserProfile`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by JoanneHendrickson** [comment]
Thanks for catching that! I have updated the article with the correct syntax.
