### ISSUE TITLE
Update Documentation to state that Conditional access is now supported on Chrome with the add-on 'Windows 10 accounts'

### ISSUE THREAD

**Issue by rpopatia** [MicrosoftDocs/OfficeDocs-SharePoint#869]
The documentation states that users on managed devices will have limited access when they use chrome browser. But with the add-on 'Windows 10 accounts' released by MS  you are no longer limited access. 

More info: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/17438821-add-support-for-google-chrome-under-azure-ad-condi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices?redirectSourcePath=%252farticle%252f5ae550c4-bd20-4257-847b-5c20fb053622#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@rpopatia Thank you for pointing this out and helping improve MS Docs. Please can you specify under which heading the changes need to be made to make it conditional access.

**Comment by lindspea** [comment]
@kaarins

**Comment by kaarins** [comment]
Thank you! I'm investigating!

**Comment by scanum** [comment]
@rpopatia We understand that this issue has been resolved. Also, we appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by kaarins** [comment]
The change didn't actually address the issue. I'm still waiting to hear back.

**Comment by scanum** [comment]
@kaarins Any updates on this? Thanks!

**Comment by rpopatia** [comment]
I see that the Chrome support information is already added to the
documentation.

Thanks,
Riyaz

**Comment by scanum** [comment]
@rpopatia @officedocsbot close
