### ISSUE TITLE
KB3042604 Points to an incorrect link

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-SharePoint#87]
The KB article https://support.microsoft.com/en-us/help/3042604/the-convert-spwebapplication-command-cannot-convert-from-windows-claim has a link at the top that refers to "Migration of Windows claims authentication to SAML-based claims authentication in SharePoint Server 2013". It currently sends us here:

https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/security-for-sharepoint-server

The old link was https://msdn.microsoft.com/en-us/help/dn744263, which if I recall, had information on how to convert data in each service app, like MMS for the conversion.

The link https://technet.microsoft.com/en-us/library/hh305235.aspx should also send us to the SAML conversion page.

@Techwriter40

**Comment by kenwith** [comment]
@tseward - seems like all of these links point to the same location now (https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/security-for-sharepoint-server). I am going to open a bug internally with the team that owns the KB articles and see if they can update the link. Thanks for reporting!

**Comment by kenwith** [comment]
@pamgreen-msft - here is the GitHub issue referencing the KB link I just sent you email on. Thanks for any info!

**Comment by tseward** [comment]
@kenwith I was hoping we could get the documentation that was on TN resurfaced to docs.microsoft.com. The TN articles provided much better details about the conversion from Windows claims/classic to SAML than the current docs.

**Comment by kenwith** [comment]
Ok got you, let's keep this open and we can research how to find that topic. In meantime I am also tracking down how to get the link fixed in the KB.

**Comment by kenwith** [comment]
@tseward - Jose, who handles KB articles, can fix the link for us. He had a question. Where should the link point? Here? https://social.technet.microsoft.com/wiki/contents/articles/14214.sharepoint-2013-claims-based-authentication.aspx


We can also try to find out from a SME internally but I thought to ask you first since your knowledge is incredible in the SharePoint space. :)

**Comment by kenwith** [comment]
I also noticed the link above was published by @JoeDavies-MSFT . It looks like amazing content! I wonder if it is moving to docs.microsoft.com Joe? Any ideas on where the link in the KB should point? https://support.microsoft.com/en-us/help/3042604/the-convert-spwebapplication-command-cannot-convert-from-windows-claim

**Comment by tseward** [comment]
@kenwith I do not see anything in the TN wiki that reflects the content I was referring to originally. Is it possible someone (@Techwriter40 maybe?) could take a look at those original URLs internally on the legacy system and port them to docs.msft.com?

**Comment by jlriesco** [comment]
Please let me know if you want me to update the KB or if it would be better to redirect it to the TechNet article in docs.

Thanks,
Jose

**Comment by kenwith** [comment]
@tseward and @jlriesco - Just a quick update. I haven't been able to find it yet but I am pinging some people with knowledge of the old system to see if we can find anything. I will keep you posted.

**Comment by kenwith** [comment]
@tseward and @jlriesco - I am making progress. I opened a request with the team that has access to those legacy article databases to get the article. Will keep you posted.

**Comment by AndreaBarr** [comment]
@tseward Thank you for this feedback. 

I have added this to the SharePoint teams backlog so that we can get this updated. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jlriesco** [comment]
Hello everyone, any progress with this request? I can update the link in the KB if you tell me the right destination.
Thanks,
Jose

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by jlriesco** [comment]
@tseward @AndreaBarr Any progress with this? It's been several months now.
Thank you,
Jose

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tseward** [comment]
Going to close this one. While we don't have a resolution, this has been open for a bit too long.
