### ISSUE TITLE
OneDriveSetup.exe /allusers

### ISSUE THREAD

**Issue by jtrzebuckowski** [MicrosoftDocs/OfficeDocs-SharePoint#871]
Microsoft just released a (preview) article to deploy OneDrive to install OneDrive per machiene rather in the a per user context. In the link below states to execute the file with an /allusers switch to install in a system context. I have the correct version installed, and doing so doesn't install within Program Files x86, and stayed within the user context under App data when launching the program.

https://docs.microsoft.com/en-us/onedrive/per-machine-installation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@jtrzebuckowski  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by gacarini** [comment]
@jtrzebuckowski We'd love to take a look at the setup logs to see what went wrong. Can you right click on the cloud icon in the systray from the machine where this occurred, click on "Send feedback" and then "I don't like something." That should open a ticket in our system and if you share the ticket number that got created, we can take a look and reach out.

**Comment by scerazy** [comment]
Does EVEYTHING has to be Closed with "solution" = open a service ticket ?
