### ISSUE TITLE
SharePoint migration tool - "You need to be site collection administrator"

### ISSUE THREAD

**Issue by Aleksa7** [MicrosoftDocs/OfficeDocs-SharePoint#875]
I am Global Admin on the tenant and site collection administrator on onprem SharePoint2013 .
When I launch SPMT, I can login using my Global Admin O365 credentials for my destination/target.
When I enter sp2013 onprem url, and want to select library (which I plan to migrate), I get login prompt and when I enter credentials get the error : You need to be site collection administrator.
There is no proxy. spmt is installed on updated win 7 workstation not on the SharePoint2013 server.
Any help, ideas ? Thank you.

**Comment by scanum** [comment]
@Aleksa7  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
