### ISSUE TITLE
OneDrive / allusers

### ISSUE THREAD

**Issue by phillipc100** [MicrosoftDocs/OfficeDocs-SharePoint#876]
Once OneDrive is setup under \Program Files x86. What is the best way to automate the signin for the additional user profiles? (Other than GPO, we don't have Workplace device registration)

Thinking about runonce:  odopen://sync?useremail=youruseremail@organization.com

Thoughts ?

**Comment by scanum** [comment]
@phillipc100  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
