### ISSUE TITLE
Silent Configuration with Intune

### ISSUE THREAD

**Issue by RyanMorash** [MicrosoftDocs/OfficeDocs-SharePoint#877]
Under the “Setup silent configuration” section, it is recommended that for Azure AD joined devices we deploy a PowerShell script through Intune. What is the reasoning for this over a custom ADMX backed policy based off of the OneDrive ADMX?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/OneDrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@RyanMorash Thank you for reaching out.  I have the team looking into this and will revert soonest.

**Comment by scanum** [comment]
@RyanMorash We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
