### ISSUE TITLE
Protected folders

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/OfficeDocs-SharePoint#879]
The GPO's and registry keys allow you to turn ON or OFF protection but you cannot set the folders you want to allow for protection. This is only an option when users are presented with the GUI. Can we have a registry key and GPO so we can set the folders we want protected. e.g. I want Documents and Pictures only. 

If desktop is protected if you login to another device which auto configured OneDrive then you get duplicated desktop icons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#BlockKnownFolderMove)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Known Folders doesn't allow you to arbitrarily set what folders to protect. Documents, Pictures, and Desktop are the folders that get protected (synced).

**Comment by chiners68** [comment]
steward,
You can control whether you want one or all 3 of these on the GUI presented to users on setup or by the settings of the OneDrive Sync client. Would be good to have a GPO and or registry keys to select for Silent configuration what of the 3 folders we want to be protected.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tseward** [comment]
@chiners68 No, but if you want to submit a feature request, I'd recommend doing so at https://onedrive.uservoice.com/forums/913534.

**Comment by scanum** [comment]
@chiners68 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
