### ISSUE TITLE
Wrong URL for migration tool

### ISSUE THREAD

**Issue by SaratchandraPeddinti** [MicrosoftDocs/OfficeDocs-SharePoint#88]
"SharePoint Migration Tool" link is returning an error xml with message "BlobNotFound" & value "The specified blob does not exist. RequestId:52cebb67-501e-0046-18c8-f6f00d000000 Time:2018-05-28T21:14:34.0018089Z".
Please update the **"SharePoint Migration Tool"** link in the **"Note" section** to
"http://spmtreleasescus.blob.core.windows.net/install/default.htm" instead of "http://spmtreleasescus.blob.core.windows.net/install/default.md"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b01f633-962a-274d-1769-e008e7049f03
* Version Independent ID: c63b4c45-f5c6-d0fb-e14f-095f79b1a415
* Content: [Upload on-premises content to SharePoint Online using PowerShell cmdlets](https://docs.microsoft.com/en-us/sharepointmigration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets#step-1-install-the-sharepoint-online-management-shell)
* Content Source: [migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by wenhua-helen** [comment]
@SaratchandraPeddinti  Which link you clicked? 
When I click [SharePoint Migration Tool Version 2](http://spmtreleasescus.blob.core.windows.net/install/default.htm) from http://aka.ms/spmt, it works.

**Comment by Reclad** [comment]
I confirm that, please fix it.

**Comment by JoanneHendrickson** [comment]
Thanks for the feedback; link has been fixed in topic.
