### ISSUE TITLE
Restarting stopped migrations

### ISSUE THREAD

**Issue by kevball2** [MicrosoftDocs/OfficeDocs-SharePoint#880]
Is is possible to restart stopped migrations? it does not appear the the start-SPTMigration cmdlet can restart a stopped migration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets#feedback)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by kevball2** [comment]
@lindspea thank you for the update. Is there any way to expose those features from the GUI?

**Comment by lindspea** [comment]
@kevball2 Just to let you know I'm still looking into this for you.  Will let you know as soon as I have an answer.

**Comment by scanum** [comment]
@kevball2 thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
