### ISSUE TITLE
How to do this in Sharepoint Server

### ISSUE THREAD

**Issue by halldororn** [MicrosoftDocs/OfficeDocs-SharePoint#881]
How do I set the default experience when I am using SharePoint Server and not SharePoint Online ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f1bd4ab-c640-1db8-05bb-e249129dfa46
* Version Independent ID: 4ceb7bc8-39c0-61fb-b31c-381cb7a5018b
* Content: [Change the default list and library experience](https://docs.microsoft.com/en-gb/sharepoint/change-default-list-and-library-experience)
* Content Source: [SharePoint/SharePointOnline/change-default-list-and-library-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-default-list-and-library-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@AndreaBarr assign to me, please.

**Comment by tseward** [comment]
@halldororn you can use the same cmdlets. You'll want to get the PnP PoSh from the PowerShell Gallery for SharePoint 2019 (https://www.powershellgallery.com/packages/SharePointPnPPowerShell2019/3.8.1904.0) then just run the same cmdlets, adjusting URLs accordingly.

**Comment by scanum** [comment]
@halldororn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
