### ISSUE TITLE
Authentication, tenant restrictions and Secure Links sharing

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-SharePoint#882]
How is authentication looking when a file is shared via Secure Link (ad-hoc user)? Would Tenant Restrictions policies apply? Imagine organization A has configured tenant restrictions at their web proxy. Now user from organization B invites user from organization A as ad-hoc user via Secure Link. Would tenant restrictions block access to organization B?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d2b5a-bc14-e0f3-1269-716383939212
* Version Independent ID: 879c8636-ab9a-0440-039a-f3eac8d41a1f
* Content: [Secure external sharing in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-sharing-in-targeted-release)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-sharing-in-targeted-release.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
