### ISSUE TITLE
Managing OneDrive Profiles

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-SharePoint#884]
Where is the OneDrive profile management? This new admin center does not have the old admin center's section for managing onedrives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f0e99c-724d-9fc3-6b8b-bda185f92c19
* Version Independent ID: d38a6ff9-e4cd-5776-b152-9694fcafbee1
* Content: [What's new in the SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/what-s-new-in-admin-center)
* Content Source: [SharePoint/SharePointOnline/what-s-new-in-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/what-s-new-in-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@ferrety2006 are you referring to the User Profiles? If so, the new interface does not have certain features (yet!), but the product group is working hard on making sure a vast majority of features from the classic admin center make it into the new admin center experience. If you want to add your feedback regarding the new admin center, I would suggest posting this in the SharePoint UserVoice at https://sharepoint.uservoice.com/forums/330318-sharepoint-administration/. The SharePoint product group reviews this UserVoice on a regular basis.

**Comment by scanum** [comment]
@ferrety2006  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
