### ISSUE TITLE
Hub Site Settings different within a site collection and central admin

### ISSUE THREAD

**Issue by boby5555** [MicrosoftDocs/OfficeDocs-SharePoint#886]
Hello, 

Is it normal that Hub Site settings are differents within a site collection and the central admin. In a site coll, you can edit de Logo, Name and Site design applied to associated sites. In central admin, you can just edit the name and the people who can associate sites with this hub site. Why can't we have the same options for both menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4df1d8-955c-63d2-628e-8359391b8710
* Version Independent ID: 01326ab6-1270-d096-64e8-eb7d63ea9863
* Content: [Create a hub site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-hub-site)
* Content Source: [SharePoint/SharePointOnline/create-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
@boby5555 since this is a feature request, you may want to repost this at https://sharepoint.uservoice.com/forums/330318-sharepoint-administration which the SharePoint product group reviews regularly.

**Comment by scanum** [comment]
@boby5555  - thank you for engaging with the community here for the docs.

As Trevor suggested, I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
