### ISSUE TITLE
App enforced Restrictions vs. MCAS Conditional Access App Control

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/OfficeDocs-SharePoint#888]
This is a great article, but I don't understand the pro/cons best practices to using "App enforced Restrictions" vs. using "MCAS Conditional Access App Control" for Exchange Online and SharePoint Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by SanjoyanM** [comment]
App enforce restriction applied to only SPO and EXO and it means for device based CA policy AAD is handing over the responsibility to SPO and EXO to do the enforcement --- at a resource level.

**Comment by SanjoyanM** [comment]
If you read the documentation it says no download no print no sync by SPO. So yes it is web only access to SPO resources.

Using MCAS depends on your business scenario. SPO supports the feature natively and many customers do not rely on a proxy solution for various reasons, latency being one. You should play with both and choose the one that fits your bill.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Mark7even Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
