### ISSUE TITLE
Silently sign in users to OneDrive, primary Windows account on domain or any account on Azure AD Joined device?

### ISSUE THREAD

**Issue by ajh0912** [MicrosoftDocs/OfficeDocs-SharePoint#889]
Currently "Silently sign in users to the OneDrive sync client with their Windows credentials" states:
"If you enable this setting, users who are signed in on a PC with the primary Windows account (the account used to join the PC to the domain) can set up the sync client without entering their account credentials.",
but this page https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#enable-silent-configuration states silent OneDrive logins work for users on Azure AD Joined devices, that contradicts this page stating only the 'primary Windows account (the account used to join the PC to the domain)' can use silent OneDrive logins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ajh0912 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
