### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by storyid** [MicrosoftDocs/OfficeDocs-SharePoint#89]
The "Related Topics" section has formatting issues (the link, weird brackets, etc.).  We should also note not to have versions spread across packages (like where we note not to have more than 1000 items and 100MB in a package, the exception to that would be if your document has versions exceeding 1000 or 100MB, they all must come together).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ed221a-ca52-7a6a-4b89-1417066ffcbd
* Version Independent ID: e7fdb3a0-c148-85d1-48cf-57998d190a8a
* Content: [SharePoint Online and OneDrive Migration Speed](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-online-and-onedrive-migration-speed)
* Content Source: [migration/sharepoint-online-and-onedrive-migration-speed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-online-and-onedrive-migration-speed.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@storyid - this is fixed now. I believe it had to do with the conversion from TechNet to the new open source GitHub system. Some of the articles have to be manually fixed so if you see any other weird formatting please let me know. On the note, I am not a Subject Matter Expert on this area but if you are willing to submit a Pull Request I could get it approved by the right people on the product team and get this added to the documenation. I have a README that shows up at the bottom of the PowerShell repo here: https://github.com/MicrosoftDocs/office-docs-powershell on how to make edits and submit Pull Requests. You can find the source article at the top of this Issue. The process is the same for all GitHub articles though. If you submit a Pull Request you will show up with credits as a contributor here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/graphs/contributors or if you would prefer it is totally fine to open issues too. Thanks for taking the time on providing feedback!
