### ISSUE TITLE
Microsoft SharePoint Foundation Workflow Timer Service 

### ISSUE THREAD

**Issue by lehuspohus** [MicrosoftDocs/OfficeDocs-SharePoint#890]
Is it required to run Microsoft SharePoint Foundation Workflow Timer Service on app-server, not front-end? Some articles recommend to stop this on app servers and start it only on servers where Foundation Web Application service is running, i.e. front-end servers. What is recommended behaviour about this service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbcd95d-56ce-63b6-804f-14098ce1953b
* Version Independent ID: 78166e52-c779-2ad6-7b1f-cc3bcde47515
* Content: [Description of MinRole and associated services in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/en-us/SharePoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016#feedback)
* Content Source: [SharePoint/SharePointServer/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@lehuspohus are they Microsoft articles which make that suggestion, and if so, can you supply the url(s)? Workflow timer, as a batch service, should only run on App.

**Comment by lehuspohus** [comment]
@tseward It comes from old [SP2010 article](https://support.microsoft.com/en-us/help/2674684/sharepoint-2010-workflow-fails-to-run-after-pause) on support.microsoft.com. 
And also from [topologies for SP2010](https://www.microsoft.com/en-us/download/details.aspx?id=6096) whitepaper. As I understand, reqirements has been changed in SP2016 but it is not clear anyway.

**Comment by tseward** [comment]
@lehuspohus there have been quite a few changes and no, this KB/topology doc wouldn't apply.

**Comment by lehuspohus** [comment]
Ok, thanks for clarification!
