### ISSUE TITLE
Missing steps

### ISSUE THREAD

**Issue by Naxxan60** [MicrosoftDocs/OfficeDocs-SharePoint#891]
Hello,
Nothing is mentioned about the need to change the My site setting in the User Profile Service. You need to change the my site host location (as you created a new web application)
You need also to enable the self-service site creation on your new web application settings.
These two steps need to be done for SP2013, 2016 and 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 280234eb-2143-b9a5-7c2e-4abf8849f1c7
* Version Independent ID: 56d589df-9205-d692-8a14-9c148380cdb2
* Content: [Set up OneDrive for Business in a SharePoint Server on-premises environment](https://docs.microsoft.com/en-us/sharepoint/sites/set-up-onedrive-for-business)
* Content Source: [SharePoint/SharePointServer/sites/set-up-onedrive-for-business.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/set-up-onedrive-for-business.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
The info for this would fall under https://docs.microsoft.com/en-us/sharepoint/install/create-a-user-profile-service-application. With that said, @AndreaBarr can you assign to me and I'll add a pointer?

**Comment by scanum** [comment]
@officedocsbot assign @tseward

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Naxxan60 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
