### ISSUE TITLE
Exchange Versions

### ISSUE THREAD

**Issue by brenle** [MicrosoftDocs/OfficeDocs-SharePoint#893]
Exchange 2015 is a typo - the correct version is Exchange 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66c4b90-6314-e356-d752-021ee48d5aab
* Version Independent ID: 0d73e841-ca55-f726-df21-bb9be17ecb3e
* Content: [Configure eDiscovery in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/configure-ediscovery-0#feedback)
* Content Source: [SharePoint/SharePointServer/governance/configure-ediscovery-0.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/configure-ediscovery-0.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by brenle** [comment]
To discover content in Exchange Server from a SharePoint eDiscovery Center, you must be running ***Exchange Server 2019, 2015, or 2013***.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by ojrb** [comment]
@scanum the PR #945 solved this issue ! Please review and Merge !

**Comment by scanum** [comment]
@brenle Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
