### ISSUE TITLE
What is the best way to migrate SharePoint 2013 On Prim to SharePoint 2019 on prim ?

### ISSUE THREAD

**Issue by manojkke** [MicrosoftDocs/OfficeDocs-SharePoint#894]
What is the best way to migrate SharePoint 2013 On Prim to SharePoint 2019 on prim? 

We are currently using SharePoint 2013 on prim. We want to migrate it to SharePoint 2019 On Prim(Not SPO). 
It seems **[SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool# )**  is equipped only to migrate from 2013 to SharePoint Online, not on prim.

**Comment by scanum** [comment]
@manojkke  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
