### ISSUE TITLE
typo there

### ISSUE THREAD

**Issue by luobod** [MicrosoftDocs/OfficeDocs-SharePoint#898]
Saw a typo there, "remote blog storage" should be "remote blob storage"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b18e9a-c7a8-e1a0-889b-80c7d35db286
* Version Independent ID: 73b90d6d-7af2-0899-960a-801c19397720
* Content: [Best practices for upgrading from SharePoint 2010 to SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/best-practices-for-upgrading-from-sharepoint-2010-to-sharepoint-2013#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/best-practices-for-upgrading-from-sharepoint-2010-to-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/best-practices-for-upgrading-from-sharepoint-2010-to-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@officedocsbot assign @scanum
