### ISSUE TITLE
Enabling SharePoint 2013 Hybrid Search with the BIG-IP has been moved

### ISSUE THREAD

**Issue by ericvdkh** [MicrosoftDocs/OfficeDocs-SharePoint#90]
The document referred to in the link "Enabling SharePoint 2013 Hybrid Search with the BIG-IP .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daec777e-686e-a949-a729-6d6cb2e0c05b
* Version Independent ID: 38f948f7-cea3-2f0f-9596-09c8e07e6583
* Content: [Hardware and software requirements for SharePoint hybrid](https://docs.microsoft.com/en-us/sharepoint/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid)
* Content Source: [SharePoint/SharePointServer/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/hardware-and-software-requirements-for-sharepoint-hybrid.md)
* Service: **unspecified**
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
@Techwriter40 The correct URL is https://devcentral.f5.com/articles/enabling-sharepoint-2013-hybrid-search-with-the-big-ip. The go.microsoft.com link needs to be updated to point to that.

**Comment by MikePlumleyMSFT** [comment]
Thanks @ericvdkh, @tseward. Article republished with updated links.
