### ISSUE TITLE
SharePoint 2013 to SharePoint online migration issue

### ISSUE THREAD

**Issue by ajay-baliyan** [MicrosoftDocs/OfficeDocs-SharePoint#900]
I have a list on SharePoint 2013 with 43 items with attachments. When I try to migrate it, SPMT tool migrate only 5 items and if I run it in incremental mode, again it migrate same records means still SharePoint online list has 5 records. Please suggest for this issue.

**Comment by scanum** [comment]
@ajay-baliyan  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
