### ISSUE TITLE
KeySpec attribute causes certreq -net request.inf to fail

### ISSUE THREAD

**Issue by si1ic0ngh0st** [MicrosoftDocs/OfficeDocs-SharePoint#901]
The KeySpec = "AT_KEYEXCHANGE" line of the suggested request.inf file causes the command "certreq -net request.inf" to fail.  If you remove this line from the request.inf, then the command works just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f58e6f-436d-1be5-1160-c4a026f3835b
* Version Independent ID: f6232934-7bf4-3fe5-f752-2067d57bcd28
* Content: [Replace the STS certificate for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/replace-the-sts-certificate)
* Content Source: [SharePoint/SharePointServer/administration/replace-the-sts-certificate.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/replace-the-sts-certificate.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
@AndreaBarr please assign to me.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@si1ic0ngh0st Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
