### ISSUE TITLE
OneDrive.exe /allusers - per machine installation

### ISSUE THREAD

**Issue by HSN42** [MicrosoftDocs/OfficeDocs-SharePoint#902]
Hi,
Can you tell me when the preview of the "OneDrive per machine installation" will be released?
Greetings Holger

**Comment by scanum** [comment]
@HSN42  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
