### ISSUE TITLE
Cost for data trasfert between Azure and Sharepoint Online (SharePoint Online using the Azure Data Box)

### ISSUE THREAD

**Issue by Rikonimo** [MicrosoftDocs/OfficeDocs-SharePoint#903]
Hello, 

In case of SharePoint Online migration using the Azure Data Box, what will be the cost for the data tranfering between the Azure VM and the SharePoint Online ? (Outgoing bandwith from Azure ?)

Regards

**Comment by scanum** [comment]
@Rikonimo - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@oficedocsbot close
