### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Damag3d** [MicrosoftDocs/OfficeDocs-SharePoint#904]
Please, clarify whether search is enabled for file names only or contents as well in files on-demand scenario. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Damag3d Thank you for reaching out. The search is for files as well as content of the files.

**Comment by Damag3d** [comment]
So if file is not synced locally, how does it performs search in content? Does it use SharePoint search instead of local indexing, what about language specific search settings? I am confused.

**Comment by tseward** [comment]
@Damag3d so your question is, from Windows Explorer, if a file is just a place holder (FoD), how does it search the contents of those files?

**Comment by scanum** [comment]
@Damag3d  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
