### ISSUE TITLE
Remove "Replace STS Certificate" steps in overview

### ISSUE THREAD

**Issue by PiAnAnXa** [MicrosoftDocs/OfficeDocs-SharePoint#905]
I've been searching for a long time how to work out how the STS Certificate should be handled. I just found out that the part to create a new certificate has been removed from the documentation because it is not needed anymore. However in the "[Configure server-to-server authentication between on-premises SharePoint Server and SharePoint Online](https://docs.microsoft.com/nl-be/SharePoint/hybrid/configure-server-to-server-authentication#configure-server-to-server-authentication-between-on-premises-sharepoint-server-and-sharepoint-online)" steps overview, the first step is still mentioned that a new certificate has to be created and replaced for theSTS certificate.

Please just remove this mention. This will make the documentation much less confusing and will save a lot of people time to implement Sharepoint Hybride

**Comment by tseward** [comment]
This should stay. Having manual steps is always good. At the top of the article is a note that you should use the Hybrid Wizard, but if you can't, to follow the article.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@PiAnAnXa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
