### ISSUE TITLE
Why does the same ID have different names?

### ISSUE THREAD

**Issue by MadDenker** [MicrosoftDocs/OfficeDocs-SharePoint#908]
Azure seems to have this repeating issue of having different names for IDs in Portal, than in documentation, than in code.  This is a perfect example of how the same ID is called a tenant ID in one place and Directory ID in another.  

Please ensure that IDs have consistent names.  Otherwise, Azure is not usable, because you can never find the correct ID to access the resources you need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a93351c-948b-67f7-edd7-8f84982f1834
* Version Independent ID: b3d722cc-3e6e-9b0a-efdb-7d61a76c874f
* Content: [Find your Office 365 tenant ID](https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id)
* Content Source: [OneDrive/find-your-office-365-tenant-id.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/find-your-office-365-tenant-id.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @MadDenker 

Thank you for sharing your views.

Both the names "Tenant ID" and "Directory ID" refers to the same. i.e. "Azure Active Directory Tenant ID". 

Hope this information is helpful. Kindly confirm. Thank you.

**Comment by hawkbox** [comment]
Then why is there more than one name for it? This problem is all over the place, it will be subscription ID in one place, Tenant ID in another, subscription name in a third.  The lack of consistency is a serious problem.

**Comment by scanum** [comment]
@sowjanya365

**Comment by sowjanya365** [comment]
Hi @hawkbox 

Thank you very much for sharing your views. 

We will take this one as a good feedback and report it to the team. Thank you so much for your wonderful contribution.

**Comment by scanum** [comment]
@MadDenker Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
