### ISSUE TITLE
Setting could not be done

### ISSUE THREAD

**Issue by sachiko99** [MicrosoftDocs/OfficeDocs-SharePoint#91]
Thank you for your help.
I made SharePoint settings based on this information, but I got an error.

Execute command:. \ Set - SiteMailboxConfig.ps1 - ExchangeSiteMailboxDomain xxxx.com - ExchangeServer Exchange1.xxxx.com - ExchangeAutodiscoverDomain https://Exchange1.xxxx.com/autodiscover/metadata/json/1 - WebApplicationUrl https: // sharepoint2
======

error contents:
Origin location c: \ users \ administrator.xxxx \ Desktop \ sp \ Set-SiteMailboxConfig.ps1: 101 Characters: 43
+ ... = & amp; $ script: currentDirectory \ Check-SiteMailboxConfig.ps1 -Return ...
+
You can not use an expression or statement token '\ Check - SiteMailboxConfig.ps1'.
+ CategoryInfo: ParserError :( :) [], ParseException
+ FullyQualifiedErrorId: UnexpectedToken

======

Would you please assist us as we need to change any of the listed commands?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7397955b-f709-07cd-91cd-fac746329614
* Version Independent ID: 3c5e58fc-10ee-bc5c-7c2d-9e881d058094
* Content: [SharePoint Server でサイト メールボックスを構成する](https://docs.microsoft.com/ja-jp/sharepoint/administration/configure-site-mailboxes-in-sharepoint#feedback)
* Content Source: [SharePoint/SharePointServer/administration/configure-site-mailboxes-in-sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-pr.ja-JP/blob/live-sxs/SharePoint/SharePointServer/administration/configure-site-mailboxes-in-sharepoint.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by kenwith** [comment]
@sachiko99 - sorry for the delay on this and that it has gone stale in the documentation issues. I know it has been a very long time so I hope you have this resolved. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.


Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by sachiko99** [comment]
Thank you for your reply
Problem solved
I appreciate your support !

**Comment by Ajeet1986** [comment]
Dear Members,
I am facing same issue, Please give me the solution.

Error:
PS C:\site-mailbox> .\Set-SiteMailboxConfig.ps1
At C:\site-mailbox\Set-SiteMailboxConfig.ps1:101 char:43
+ $warnings = &amp; $script:currentDirectory\Check-SiteMailboxConfig.ps1
-ReturnWa ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token '\Check-SiteMailboxConfig.ps1' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by kenwith** [comment]
@Ajeet1986 - I am not sure the solution. If you open a support ticket they can guide you. See above on how to open a support request. 

@sachiko99 if you have any solution you can share to update in the doc please let me know.
