### ISSUE TITLE
Filling the blanks, plus trivial typos

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/OfficeDocs-SharePoint#918]
[1] In "Navigation Fundamentals" / Intro paragraph
"This is why organizing and labeling your navigation links is so critical (*) usability and findability."
(*) something is missing here.
For example: " critical for usability and findability."
Or: " critical in purpose of usability and findability."
Etc...

[2] In "Navigation Fundamentals" / "Labeling" / "Consistent"
"When we have a lot of content on sites, we often need to use a combination (*) category and sub-links on pages."
(*) missing: "of"
should be: " a combination of category and sub-links "

[3] In "Navigation Fundamentals" / "Link Targets"
(the very last sentence)
"[...] such as the text web part where you can open elect to open a link in a new window."
&gt;&gt; should be: " [...] where you can elect to open [...] "

[4] In "Navigation in the Flat World" / "Local Navigation" / "Link to pages, not individual documents."

[4.1] "But when navigation points to a page with an embedded (*) instead of directly to a document, [...] "
(*) missing: "document"
should be: "But when navigation points to a page with an embedded document instead of directly to a document, [...] "

[4.2] (later in the same section)
"The page allows you to provide context for the document and it also and keeps the reader in the context of your site."
&gt;&gt; should be: " [...] and it also keeps the reader [...] "

[5] In "Navigation in the Flat World" / "Hub Navigation"
(below the picture...)
"Hub site navigation is established in the on the site that is declared to be the hub."
&gt;&gt; should be: " [...] established in the site that is declared [...] "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576791-f019-67e1-3d31-fccefd6a165b
* Version Independent ID: 4844c3bf-70cd-e5f4-2380-59db5ad32ae5
* Content: [Planning Navigation for the modern SharePoint experience](https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience)
* Content Source: [SharePoint/SharePointOnline/plan-navigation-modern-experience.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/plan-navigation-modern-experience.md)
* Service: **sharepoint-online**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by a-zaf** [comment]
Greetings,
Thank you @scanum for taking ownership of this submission!
Meanwhile, the same point number "[5]" above has been addressed through Pull Request #935
Accordingly, point "[5]" can be dropped from the above list.
Kind Regards.

**Comment by scanum** [comment]
@a-zaf Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by a-zaf** [comment]
Hello @scanum, thanks for the notification!
So far, the changes have not been published online.
I will verify again when the changes do go live, but by looking at the pull request #946 ,
it seems that from the original list above, all points have been covered except point "[4.2]"
It's just a little typo, if it matters.
Otherwise, if you deem it unimportant, then please close this issue again and just "let it fly" :-)
