### ISSUE TITLE
Wrong url on suggested link?

### ISSUE THREAD

**Issue by SRissveds58** [MicrosoftDocs/OfficeDocs-SharePoint#921]
When using link to suggested 'Upgrade databases from SharePoint 2016 to SharePoint Server 2019' article one seems to be directed to wrong page. The title being  'Upgrade databases from SharePoint 2013 to SharePoint Server 2016' instead of the suggested one.

Is it a wrong link or should the information be the same (doubt that)?

/Stefan 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9786937e-19b0-834c-2f93-6ac4d4afbdec
* Version Independent ID: c5634de0-0965-1e4a-2491-0cdc5f9db839
* Content: [Overview of the upgrade process to SharePoint Server 2019](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/overview-of-the-upgrade-process-2019#feedback)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/overview-of-the-upgrade-process-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/overview-of-the-upgrade-process-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@SRissveds58 thank you for your feedback. I am not finding the link you mentioned in the article. Can you be more specific in what section this link is in ?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by SRissveds58** [comment]
Hi Kirk,

It is the link in this part of the page (https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/overview-of-the-upgrade-process-2019 )

[cid:image001.jpg@01D4FA8D.FD274910]

/Stefan

**Comment by tseward** [comment]
@scanum the correct link is https://docs.microsoft.com/sharepoint/upgrade-and-update/upgrade-databases-2019. Right now it is pointing to the 2013 -> 2016 version of this article.

**Comment by scanum** [comment]
@SRissveds58 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
