### ISSUE TITLE
What if you're in SharePoint 2016 and are exploring moving to SharePoint Online?

### ISSUE THREAD

**Issue by RexRhyne** [MicrosoftDocs/OfficeDocs-SharePoint#922]
What if you're in SharePoint 2016 and are exploring moving to SharePoint Online?  Is there an assessment tool available?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online#feedback)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migrate-to-sharepoint-online.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@RexRhyne  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
