### ISSUE TITLE
Can't externally share

### ISSUE THREAD

**Issue by bennykaye11** [MicrosoftDocs/OfficeDocs-SharePoint#925]
Want to share a document externally from our Sharepoint. Have adjusted the sharing privacy slider to most permissive but it still prevents me from choosing the "anyone with a link" option when I try to share a file. Am I missing something?

**Comment by scanum** [comment]
@bennykaye11  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
