### ISSUE TITLE
SPMT.zip still fails without internet access

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-SharePoint#927]
SPMT.zip file still requires internet access to install.  It should work offline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bace7b-082e-b83d-5489-a9891d2c4e3a
* Version Independent ID: d2777cb8-575d-064b-481c-9c870d8420b7
* Content: [Troubleshooting SPMT installation issues](https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues#feedback)
* Content Source: [migration/spmt-install-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/spmt-install-issues.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@GitWesDone Thank you for reaching out and helping improve MS Docs. The application is ClickOnce, so you need internet access.  It does not work offline.

**Comment by GitWesDone** [comment]
This page specifically provides a SPMT.zip file for installing the tool.
Does that zip file still require internet access?

https://docs.microsoft.com/en-us/sharepointmigration/spmt-install-issues

**Comment by lindspea** [comment]
@GitWesDone yes it does. It requires high speed internet connection.

**Comment by scanum** [comment]
@GitWesDone Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
