### ISSUE TITLE
Report for that?

### ISSUE THREAD

**Issue by T182** [MicrosoftDocs/OfficeDocs-SharePoint#929]
Is there a report that I can generate in o365 to see what devices still use Groove.Exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e41333c0-77d5-b375-1e0b-c92c4a5a90d9
* Version Independent ID: 7160e9ae-ffff-f979-d145-587f8c9eb2bc
* Content: [Changes to OneDrive sync client deployment in Office Click-to-Run](https://docs.microsoft.com/en-us/onedrive/exclude-or-uninstall-previous-sync-client#feedback)
* Content Source: [OneDrive/exclude-or-uninstall-previous-sync-client.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/exclude-or-uninstall-previous-sync-client.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@T182  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
