### ISSUE TITLE
Setting "Read" permission on "Everyone Except External Users" is reverting to "Edit" on public group site after a period of time

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/OfficeDocs-SharePoint#934]
Can someone confirm this is a known behavior? After a certain period of time (from an hour to a couple of days) there is a job using the Microsoft\ServiceAccount that removes "Everyone Except External Users" from the SP visitors group and put in back into the SP members group with edit permissions on sites related to Office 365 PUBLIC groups. This was confirm to me to be a known and normal behavior by escalation team but not documented. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels#feedback)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Product: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by abhitalks** [comment]
This is documented here: https://support.microsoft.com/en-us/help/4492201/everyone-except-external-users-group-is-removed 

However, needless to say, this is utter nonsensical. Especially when the UI in the team site explicitly prompts users to specify if the permissions are for "this site only"!

**Comment by coupalm** [comment]
@abhitalks , this article refers to private group and not public group. It does not explain the behavior of "Everyone Except External Users" reverting to edit after being set to read in public group site.

> Summary: The "Everyone except external users" group is removed by a managed service account on a Microsoft Office 365 **Private group** website.

**Comment by scanum** [comment]
@coupalm - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by tseward** [comment]
The behavior is also inconsistent from tenant to tenant. I'm not seeing this on my personal tenant; other MVPs have indicated they see this behavior on some tenants but not others.

**Comment by coupalm** [comment]
Yes, this background job is definitly inconsistent. I just saw today one of my customer private group site that I did last year where we added the EEEU in the visitors group and it still there... It should have been removed.. For now on, I stick with team sites not connected to O365 group as much as possible until this is sorted out.

**Comment by majidali** [comment]
This link explains the behavior of Everyone Except External Users for public and private group.

https://docs.microsoft.com/en-us/sharepoint/default-sharepoint-groups

**Comment by coupalm** [comment]
@majidali, the behavior they explained below is not consistent on every tenants. Sometimes I'm able to change EEEU on public group from Edit to Read and it will not change, sometimes it will change back to Edit. I was also able to add EEEU to the visitors group on private group site and it was never removed. The background job does not work properly.

"Everyone except external users All users added to your organization automatically become members of "Everyone except external users". Please note that you cannot change default permissions granted to "Everyone except external users" on Office 365 group-connected team sites. If a group-connected team site is set to "Public," "Everyone except external users" has a default permission level of "Edit." When a group-connected team site is set to "Private," "Everyone except external users" can't be granted any permission to the site. Although the "Site permissions" tab will allow modifications to be granted, a background job will block such modifications to take effect. To change the privacy setting for a group-connected team site, select the Settings icon, and then select Site information."

**Comment by scanum** [comment]
@coupalm Thank you for submitting feedback. We appreciate your suggestions and we will consider adding something in the future. However, at the moment we will not.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
