### ISSUE TITLE
Detection Method

### ISSUE THREAD

**Issue by PHesk83** [MicrosoftDocs/OfficeDocs-SharePoint#937]
Do you know when these instructions will be expanded to match the old ones? https://docs.microsoft.com/en-us/onedrive/deploy-on-windows 

Particularly, the switches for silent install and uninstall and the detection method.  Is it ok to simply detect based on the folder path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by PHesk83** [comment]
...plus all additional options like 'User experience'.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by robhardman** [comment]
For SCCM, to detect the install we used the following two registry detection rules with an OR() connector;
HKLM\SOFTWARE\Wow6432Node\Microsoft\OneDrive | Version | 32bit on 64bit TRUE | Type=Version | >= 19.043.0304.0007
HKLM\SOFTWARE\Microsoft\OneDrive | Version | 32bit on 64bit FALSE | Type=Version | >= 19.043.0304.0007

This allows the per-machine version to be detected independent of the underlying client architecture.

**Comment by robhardman** [comment]
(Just one thing to add, be careful with your version strings in the rules above. It seems that one some clients a slightly earlier build was getting installed, so I contracted the Version number to 19.043.0304.0000.

YMMV.)

**Comment by scanum** [comment]
@PHesk83 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by PHesk83** [comment]
@robhardman I don't see those reg keys on the users that I have installed the per machine client.  Do you have a screenshot of the mentioned reg keys?

**Comment by robhardman** [comment]
@PHesk83 Here you go https://imgur.com/MIaBg5v

**Comment by PHesk83** [comment]
@robhardman That was rapid.  Thanks a lot mate, got it now :)
