### ISSUE TITLE
Work Accounts Constantly Prompted for Verification Code

### ISSUE THREAD

**Issue by charlieparmiter** [MicrosoftDocs/OfficeDocs-SharePoint#939]
When I'm sharing with work accounts the users are being prompted every-time for a verification code and not given the option to login. This doesn't reflect what the document suggests should be the end user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@charlieparmiter - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@charlieparmiter - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
