### ISSUE TITLE
Moving between tenants

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#94]
can this be used to move content between different SharePoint Online Tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85a08784-543a-32b7-1e83-4f3ebf5bc6d4
* Version Independent ID: 7234f9f2-a3a1-b37b-4153-f86ec483993c
* Content: [Migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online)
* Content Source: [migration/migrate-to-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/migrate-to-sharepoint-online.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Dean:  At this time, it cannot be used to content between SPO tenants.
Joanne

**Comment by kenwith** [comment]
@DeanGross and @Lalith09 - There is a similar thread here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/84

We found out from the product team that the tool does not support moving between SharePoint Online tenants right now. But there is an active User Voice thread to up-vote and request the feature. You can find a link on the thread I linked above. Please up vote! :)

**Comment by thehypebeast** [comment]
Hi, Is it possible to move files between sharepoint online sites? Lets say you have a old sharepoint site and just created a new one and want to move the files there?
