### ISSUE TITLE
Building with MDT

### ISSUE THREAD

**Issue by clreinki** [MicrosoftDocs/OfficeDocs-SharePoint#940]
When doing a build and capture sequence with MDT, can we include the per-machine installation or will the sysprep process reset anything needed by the per-machine installation of Onedrive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@clreinki -Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@clreinki  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
