### ISSUE TITLE
Site collection scoped termset limitations

### ISSUE THREAD

**Issue by beckettkev** [MicrosoftDocs/OfficeDocs-SharePoint#941]
In regards to the Managed Metadata term store (database) limits section, please can we have some documentation or clarification on the limitations around site collection scoped termsets and terms? For example, are they considered in the global pool or are they separate? 

Is the global limit of 1,000 global limit of termsets including these or is this global limit not including the site collection scoped termsets?

If the answer is that they are not included, then are there hard limits for them at the site collection scope?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0e611-8cbd-1b44-6e09-487b15307c6a
* Version Independent ID: b00c5b8b-c735-6473-a492-b82ae4e8a02f
* Content: [Software boundaries and limits for SharePoint 2013](https://docs.microsoft.com/en-gb/SharePoint/install/software-boundaries-and-limits#feedback)
* Content Source: [SharePoint/SharePointServer/install/software-boundaries-and-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/software-boundaries-and-limits.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@beckettkev - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by beckettkev** [comment]
@scanum - Thank you. Any news?

**Comment by scanum** [comment]
@beckettkev Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
