### ISSUE TITLE
[LOC] "HKEY_ローカル_マシン\ソフトウェア\" needs to be replaced with "HKEY_LOCAL_MACHINE\SOFTWARE\"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SharePoint#942]
https://docs.microsoft.com/ja-jp/onedrive/plan-onedrive-enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@hyoshioka0128
Thank you for submitting this feedback.

Could you please provide more info in what is needed so I can  get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@officeglobal could you please aid us on next steps? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the HKEY value is updated at live page

![image](https://user-images.githubusercontent.com/47977325/58165134-677a2c80-7c87-11e9-9448-ecbf8bf91284.png)

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
