### ISSUE TITLE
Deletion of site is taking more than 24 hours

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [MicrosoftDocs/OfficeDocs-SharePoint#943]
If we delete a SharePoint site collection from modern page > Settings > Site Information> Delete site, the site is not getting deleted immediately. Users will be able to access the site for more than one day. But previously it used to delete immediately, if users try to access then they will get 404 error. We are facing this behavior recently. 
   
   But if we delete the site from admin center, site is getting deleted immediately as excepted.

Is it a bug or new behavior, could anyone please confirm this ?

**Comment by scanum** [comment]
@Prakash-Ramasamy 
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Prakash-Ramasamy thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Prakash-Ramasamy** [comment]
The deletion of the SharePoint site has an issue and it was fixed by creating MS support ticket for our tenant. There is no delay in deleting a site collection. It is an immediate process.

FYI,
 https://answers.microsoft.com/en-us/msoffice/forum/msoffice_sharepoint-mso_win10-mso_o365b/deletion-of-the-site-is-not-happening-from-modern/c652af97-6b48-4e09-af91-1481f268b47b?messageId=ab75f1b5-9541-4af8-b481-78640d9fb540

Regards,
Prakash R
