### ISSUE TITLE
Deploy OneDrive to macOS devices by using Intune

### ISSUE THREAD

**Issue by Pentao** [MicrosoftDocs/OfficeDocs-SharePoint#944]
How to do you deploy the latest OneDrive to macOS devices though? 
The steps seem different than what it is documented iOS.
On the App information section I typed OneDrive on *Suite Name, but it only got the version 18.xx at the time I'm writing this, the latest version is 19.033.x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d65d08-b216-1f92-cc37-40690fb3d627
* Version Independent ID: ee040702-91ce-203a-7ae2-1fa9a52a9843
* Content: [Deploy OneDrive apps using Intune](https://docs.microsoft.com/en-us/onedrive/deploy-intune#feedback)
* Content Source: [OneDrive/deploy-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/deploy-intune.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@Pentao Thanks for submitting feedback. We are currently investigating this. 

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Pentao Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
