### ISSUE TITLE
Wrong PowerShell Comdlet

### ISSUE THREAD

**Issue by zilongchang** [MicrosoftDocs/OfficeDocs-SharePoint#949]
In section "Block or limit access to a specific SharePoint site or OneDrive" step 9, "To update multiple sites at once, use the following command as an example:"
(Get-SPOSite -IncludePersonalSite $true -Limit all -Filter "Url -like '-my.spgrid.com/personal/") | Set-SPOTenant -ConditionalAccessPolicy AllowLimitedAccess

It should be Set-SPOSite after the pipe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#feedback)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@zilongchang Thanks for submitting feedback. We are investigating this.

**Comment by get-itips** [comment]
Hello @zilongchang 
Thanks for your feedback, I created a PR to correct the article using the right cmdlet after the pipe.
Thank you

**Comment by scanum** [comment]
@zilongchang Thank you for submitting feedback. We appreciate your suggestions and will consider them in the future. However, the author considers the documentation correct at the moment.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by andersidahl** [comment]
@scanum it's still the wrong command in the documentation
