### ISSUE TITLE
Founder

### ISSUE THREAD

**Issue by FoundryFounder** [MicrosoftDocs/OfficeDocs-SharePoint#95]
It would be nice if the PSConfig.exe command about the middle of this article had "secureresources" spelled correctly, given that a "copy" is provided.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ccb7df-8dca-b5fc-4e84-e3624d2804cc
* Version Independent ID: 669daf62-d97c-3489-786b-6924c1e755b0
* Content: [SharePoint Server 2016 zero downtime patching steps](https://docs.microsoft.com/en-us/sharepoint/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps)
* Content Source: [SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by Techwriter40** [comment]
@FoundryFounder.  thanks for your request. This has been updated.
