### ISSUE TITLE
Support for SharePoint 2019

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/OfficeDocs-SharePoint#952]
This article mentions that known folder move is not supported in SharePoint Server in section: About the Known Folder Move Group Policy objects: https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#about-the-known-folder-move-group-policy-objects

"Known Folder Move does not work for users syncing OneDrive files in SharePoint Server"

However, the article in the link below indicates that it is.
https://support.office.com/en-us/article/back-up-your-documents-pictures-and-desktop-folders-with-onedrive-d61a7930-a6fb-4b95-b28a-6552e77c3057?ui=en-US&rs=en-US&ad=US

I am trying to identify if there is an issue with one of the two articles or if they are referencing two different features.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fd3d64-02a4-74dd-1f2a-a25ed9a8cef8
* Version Independent ID: cc17b035-3597-7194-2544-3805ad380d5d
* Content: [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/en-us/onedrive/redirect-known-folders#about-the-known-folder-move-group-policy-objects)
* Content Source: [OneDrive/redirect-known-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/redirect-known-folders.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JoeAlanis Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by JoeAlanis** [comment]
@scanum  The list of supported platforms in the second link appears to be incorrect. I submitted a request internally to remove SharePoint 2019 from the list of supported platforms. The article from docs is correct.

**Comment by ojrb** [comment]
Hi @JoeAlanis based on you comment, the article from docs does not need to be modified? Please confirm !

**Comment by ojrb** [comment]
Hi @JoeAlanis  waiting for your valuable comments !

**Comment by JoeAlanis** [comment]
Hi @ojrb, I have validated that KFM is not supported for SP2019. This [article](https://support.office.com/en-us/article/back-up-your-documents-pictures-and-desktop-folders-with-onedrive-d61a7930-a6fb-4b95-b28a-6552e77c3057?ui=en-US&rs=en-US&ad=US) needs to be corrected by a different group since it's not hosted on docs. It's OK to close this issue.

**Comment by scanum** [comment]
@ojrb

**Comment by scanum** [comment]
@JoeAlanis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
