### ISSUE TITLE
Install-Module -Name Microsoft.Online.SharePoint.PowerShell fails with error ""Could not load type 'Microsoft.SharePoint.Client.CustomerKeyVaultKeyType' from assembly 'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'."

### ISSUE THREAD

**Issue by ashokgop** [MicrosoftDocs/OfficeDocs-SharePoint#953]
I am attempting to configure a one-way Outbound Hybrid with my SP2016 on-prem farm (w/April 20019 CU).  I am executing the steps in the article https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-server-to-server-authentication.  On Step 10 of "To install the online service management tools and configure the PowerShell window:" provides the following commands:
Add-PSSnapin Microsoft.SharePoint.PowerShell
Import-Module Microsoft.PowerShell.Utility
Import-Module MSOnline -force
Import-Module MSOnlineExt -force
Import-Module Microsoft.Online.SharePoint.PowerShell -force

The Import-Module Microsoft.Online.SharePoint.PowerShell -force fails so I run the Install-Module for this module and it successfully installs version 16.0.8812.1200 of the module.  After this when I attempt to execute Import-Module (as above) I get the following error:
>> TerminatingError(Import-Module): "Could not load type 'Microsoft.SharePoint.Client.CustomerKeyVaultKeyType' from assembly 'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'."
Import-Module : Could not load type 'Microsoft.SharePoint.Client.CustomerKeyVaultKeyType' from assembly 
'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.
At line:1 char:1
+ Import-Module -Name Microsoft.Online.SharePoint.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
Import-Module : Could not load type 'Microsoft.SharePoint.Client.CustomerKeyVaultKeyType' from assembly
'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.
At line:1 char:1
+ Import-Module -Name Microsoft.Online.SharePoint.PowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

After some digging I found some reference to articles that seemed to suggest that these module require specific version of server-side modules to be present.  So I naturally thought of downgrading the module.  When I try to Uninstall the module it will not le let me uninstall too.

Any suggestions is greatly appreciated.

**Comment by tseward** [comment]
Is there a reason you're not using the Hybrid Config wizard? This is the *strongly* recommended way to configure any hybrid scenario (Search will just require the extra onboarding script post-Hybrid config wizard run).

**Comment by ashokgop** [comment]
Are you referring to this script?
https://blogs.msdn.microsoft.com/spses/2015/11/17/office-365-sharepoint-hybrid-configuration-wizard/

**Comment by ashokgop** [comment]
It appears that when you execute "Install-Module -Name Microsoft.Online.SharePoint.PowerShell" it picks up the latest version (i.e. 16.0.8812.1200) in the gallery.  However if you install the "SharePoint Online Management Shell" from the download link (https://www.microsoft.com/en-us/download/details.aspx?id=35588) using SharePointOnlineManagementShell_8812-1200_x64_en-us.msi, it installs version 16.0.8812.0. 

Initially I had downloaded from the PowerShell gallery and the subsequent Import-Module cmd for this was failing with the above errors.
After I downloaded and installed from the .msi, I found the result of Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version returns the following output:

Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.8812.1200
Microsoft.Online.SharePoint.PowerShell 16.0.8812.0

After this I was able to successfully run Import-Module.  

Not sure if there are any differences between the two.

**Comment by scanum** [comment]
@ashokgop Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@ashokgop Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
