### ISSUE TITLE
Can I use this tool to migrate content from on-prem Sharepoint 2013 to on-prem Sharepoint 2013 ?

### ISSUE THREAD

**Issue by raymondhahs** [MicrosoftDocs/OfficeDocs-SharePoint#957]
Hi, i need to migrate one on-prem SP 2013 site collection few content (about 1TB) to another new site.  Can i use this tool to perform the migration?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@raymondhahs Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@raymondhahs thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
