### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#960]
This statement is now incorrect: "By default, major versioning is not enabled in SharePoint Server."  

In SharePoint 2019 and SPO, versioning is enabled by default (major versioning)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b626929-198d-3be9-d202-df1c80699327
* Version Independent ID: 7bed15b6-1a2d-fff5-c62e-3c07308882c6
* Content: [Overview of co-authoring in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/co-authoring-overview)
* Content Source: [SharePoint/SharePointServer/governance/co-authoring-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/co-authoring-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by ojrb** [comment]
Hi @scanum the PR #980 solve this issue ! Please review and Merge !

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
