### ISSUE TITLE
Excel Co-Authoring

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#961]
SPO now supports co-authoring in the Excel client.  Article is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b626929-198d-3be9-d202-df1c80699327
* Version Independent ID: 7bed15b6-1a2d-fff5-c62e-3c07308882c6
* Content: [Overview of co-authoring in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/governance/co-authoring-overview)
* Content Source: [SharePoint/SharePointServer/governance/co-authoring-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/governance/co-authoring-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @tomresing
* Microsoft Alias: **toresing**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by ojrb** [comment]
Hi @scanum The PR #981 solve this issue, please review and merge

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We appreciate your suggestions, however, the rich client version of Excel on Windows doesn’t support co-authoring with any version of SharePoint Server. Some versions of Excel on Windows do support co-authoring with SharePoint Online. Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by danmyhre** [comment]
I know, that is why I said SPO, not SPS.  The applies to at the top of the page also lists SPO, which makes this article unclear.

Thanks,
Dan

**Comment by tomresing** [comment]
Good point. I must have missed that. I've merged a new pull request removing the SharePoint Online part of the applies to. Thanks!
