### ISSUE TITLE
Why is there no discussion of mapping the property?

### ISSUE THREAD

**Issue by vaderj** [MicrosoftDocs/OfficeDocs-SharePoint#964]
I mean, seriously. The word MAP appears NO where in this article, though its on the Edit Property page 6x.

I mean, not that matters as the process is obviously broken ... Profiles are being synced but there is no ability to select anything in the "Source Data Connection" or "Attribute" dropdowns, and additionally, the "Attribute" text input is disabled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 089de41e-64c6-4698-5a2e-deafe6fac8ea
* Version Independent ID: 99812440-95be-2284-4b90-3088f55b3772
* Content: [Add and edit user profile properties in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/add-and-edit-user-profile-properties)
* Content Source: [SharePoint/SharePointOnline/add-and-edit-user-profile-properties.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/add-and-edit-user-profile-properties.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment]
Because you can't map the property. SPO consumes specific attributes from Azure AD and only those attributes. Any other attributes you want to sync with a data source need to be done outside of the context of this sync, e.g. using a CSOM application to pull data from AD or AAD -> SPO UPSA directly.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@vaderj Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
