### ISSUE TITLE
SharePoint Migration Tool also supports on-premises file shares

### ISSUE THREAD

**Issue by mhunsberger** [MicrosoftDocs/OfficeDocs-SharePoint#965]
Check this link for details: https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises](https://docs.microsoft.com/en-us/OneDrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mhunsberger Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
On the link you're referring to, it's already "network share, file shares".
and on the one you want to modify (plan-onedrive-enterprise.md) it's not present because SharePoint is different than onedrive.

**Comment by scanum** [comment]
@mhunsberger Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
