### ISSUE TITLE
Applicable to GCC

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-SharePoint#966]
These settings are disabled (and unable to be changed) in the few GCC tenants I've checked. Does this page not apply to government community cloud tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6668926-c332-1348-2559-ee4e6dbf68a9
* Version Independent ID: 214e5b3a-ba59-2dd3-5e97-7d642072afaf
* Content: [Enable or disable preview features in SharePoint](https://docs.microsoft.com/en-us/sharepoint/enable-or-disable-preview-features?redirectSourcePath=%252fen-us%252farticle%252fPreview-features-setting-in-SharePoint-admin-center-88c69842-7eba-4372-953f-e4cff5818b88)
* Content Source: [SharePoint/SharePointOnline/enable-or-disable-preview-features.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/enable-or-disable-preview-features.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@sparkitect Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@sparkitect thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
