### ISSUE TITLE
Register the SharePoint Online application principal object ID with SharePoint Server fails

### ISSUE THREAD

**Issue by ashokgop** [MicrosoftDocs/OfficeDocs-SharePoint#969]
This step fails on the following command:
$appPrincipal = Register-SPAppPrincipal -site $site.rootweb -nameIdentifier $sponameidentifier -displayName "SharePoint Online"

with the following error message:
Register-SPAppPrincipal : We're sorry, we weren't able to complete the operation, please try again in a few minutes. If you see this
message repeatedly, contact your administrator.
At line:1 char:17
+ ... Principal = Register-SPAppPrincipal -site $site.rootweb -nameIdentifi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Share...terAppPrincipal:SPCmdletRegisterAppPrincipal) [Register-SPAppPrincipal], SPE
xception  + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletRegisterAppPrincipal

I have tried twice after a few minutes and continue to get this error.  
Am I missing something in the command?

Thank you!
AG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d499cfa0-9a8e-37c8-4607-874d3d72ed69
* Version Independent ID: 267ded1d-8e8d-3d11-44b4-3e83c70d40c8
* Content: [Configure server-to-server authentication from SharePoint Server to SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-server-to-server-authentication)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Is there a reason you're not using the SharePoint Hybrid wizard instead?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by ashokgop** [comment]
> Is there a reason you're not using the SharePoint Hybrid wizard instead?

What is the link to the download?

**Comment by tseward** [comment]
In the SPO admin center, it is under Classic Features -> More Classic Features -> Hybrid picker.

**Comment by ashokgop** [comment]
I downloaded the Hybrid Picker from https://docs.microsoft.com/en-us/sharepoint/hybrid/run-hybrid-picker.  I tried to run the tool and it sure is good.  I am setting up a prototype for my team and want to build a hybrid in a progressive manner; first with one-way Outbound Hybrid search, next one-way Inbound Hybrid and finally the two-way bidirectional hybrid.  As part of that I am following these articles and want to be able to understand the deployment and configuration.  How can I achieve this?

**Comment by ashokgop** [comment]
I have now resolved the issue. It appears to be an issue with a delay in the response of the SPO service.  I opened a support ticket and worked with the tech.  When I repeated the step, the script executed successfully!

I think the lesson learnt here is that if you get this error, take a break and try later; maybe next day.  And it should work.  Thanks!

**Comment by scanum** [comment]
@ashokgop thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
