### ISSUE TITLE
User navigation

### ISSUE THREAD

**Issue by cjahydac** [MicrosoftDocs/OfficeDocs-SharePoint#972]
Link bulleted post install tasks to configuration steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8234ffd6-eecf-088e-6ac4-76a750c123a9
* Version Independent ID: 7dfd076b-7c10-948d-4a48-3ddefc3c8795
* Content: [Install SharePoint Servers 2016 or 2019 across multiple servers](https://docs.microsoft.com/en-us/sharepoint/install/install-sharepoint-server-2016-across-multiple-servers#feedback)
* Content Source: [SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/install-sharepoint-server-2016-across-multiple-servers.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by scanum** [comment]
@cjahydac  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @cjahydac 

Thank you for reaching out!

Would you be so kind to elaborate more on this? It would help us to understand the issue and take appropriate steps to resolve it. Thank you.

**Comment by scanum** [comment]
@v-bawu We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
