### ISSUE TITLE
CreateSPAsyncReadJob stays in Queued state

### ISSUE THREAD

**Issue by BrilliantBrains** [MicrosoftDocs/OfficeDocs-SharePoint#973]
I am referring to the Migration Asynchronous Read API that allows creating a read job on SharePoint using CSOM. I am able to create the read job successfully but unfortunately, the job stays in a queue state since long.

The function returns the Object that includes UniqueJobID, AzureContainerManifestUri, AzureQueueReportUri and EncryptionKey

By using clientContext.Site.GetMigrationJobStatus method I am able to check the read job status that always returns Queued

Here is the sample code for reference:

    using (var clientContext = new ClientContext(siteUrl))
    {
    	clientContext.Credentials = new SharePointOnlineCredentials(userName, password);
    
    	var result = clientContext.Site.CreateSPAsyncReadJob($"{siteUrl}/List/MyList", new AsyncReadOptions { });
    	clientContext.ExecuteQuery();
    
    	MigrationJobState state;
    	do
    	{
    		var status = clientContext.Site.GetMigrationJobStatus(result[0].JobId);
    		clientContext.ExecuteQuery();
                state = status.Value;
    	} while (state == MigrationJobState.Queued);
    }

I have also tried to connect to the AzureQueueReportUri queue that contains the message with encrypted content. I am not sure how we can decrypt the content to make it human readable. Here is the sample message:

    {
    	"Label": "Encrypted",
    	"JobId": "079ece4a-cfd2-4676-a27d-2662beb5bb0a",
    	"IV": "RYc+ZA2feX1hnAcVWR1R+w==",
    	"Content": "qbjTBbb2N+DkNumLoCJSAAfwj8etDLgjxp+..."
    }

I am also not able to connect the AzureContainerManifestUri blob container. It fails with an error Authentication Error. Signature did not match.

Can anyone please guide me how can I proceed ahead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39174cb2-71d0-b58a-6edc-3fcabd922e8e
* Version Independent ID: fae882c6-c489-6992-a343-6f0d657fb212
* Content: [Migration Asynchronous Read API](https://docs.microsoft.com/en-us/sharepointmigration/spo-asynchronous-read-api#feedback)
* Content Source: [migration/SPO-asynchronous-read-API.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/SPO-asynchronous-read-API.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@BrilliantBrains Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by techmadness** [comment]
@scanum Any updates on this?

**Comment by scanum** [comment]
@BrilliantBrains thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by techmadness** [comment]
Sample: [https://gist.github.com/techmadness/484e7de0a7c51e5faf952a79f1eacb85](https://gist.github.com/techmadness/484e7de0a7c51e5faf952a79f1eacb85)
