### ISSUE TITLE
Writing Error

### ISSUE THREAD

**Issue by sualehalam** [MicrosoftDocs/OfficeDocs-SharePoint#976]
On this page the last note reads as "When you set site storage limits in PowerShell, you enter them in MB. The values are converted and rounded down to the nearest integer to appear in the admin centers in GB. So a value of 5000 MB becomes 4 GB. If you set a value of less than 1024 MB by using PowerShell, it will be rounded up to 1 GB. "  

 It should be [ So a value of 5000 MB becomes 5 GB ] but originally it's written 4GB which is an error.

Please fix it to improve your service and reputation because these sort of errors are not common in Microsoft. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space#feedback)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@sualehalam Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@sualehalam Thank you for the feeback. We have made the changes via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/997

**Comment by scanum** [comment]
@sualehalam Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
