### ISSUE TITLE
Typo in the source sentence

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/OfficeDocs-SharePoint#977]
There is a typo in the sentence: "These two This is because these property values are BASE64 encoded blob...". Please update the source accordingly.

Thanks,
Petr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcf1408-5e6c-1883-a450-32f5f4b5c54b
* Version Independent ID: 759ad004-5772-496a-77b5-ec71d081652f
* Content: [Migration of Web parts in the migration API](https://docs.microsoft.com/en-us/sharepointmigration/migration-web-parts-migrationapi#feedback)
* Content Source: [migration/Migration-web-parts-migrationAPI.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/Migration-web-parts-migrationAPI.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@OfficeGSX Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@OfficeGSX Thank you for the feedback. We have made the necessary changes to the document via PR https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/999

**Comment by scanum** [comment]
@OfficeGSX Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
