### ISSUE TITLE
Missed hash in Powershell script

### ISSUE THREAD

**Issue by EmmanuelJahan** [MicrosoftDocs/OfficeDocs-SharePoint#978]
Hello,
Just need to add hash at the begin of this line in PowerShell Script :
"Sending email with output file as attachment"
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657793d-ad57-3801-6586-9c36b949386f
* Version Independent ID: ce570a07-c861-b43c-67c3-088780ee8fec
* Content: [Manage site storage limits](https://docs.microsoft.com/en-us/sharepoint/manage-site-collection-storage-limits#feedback)
* Content Source: [SharePoint/SharePointOnline/manage-site-collection-storage-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-site-collection-storage-limits.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@EmmanuelJahan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by EmmanuelJahan** [comment]
@msbemba Thanks for your job :)
