### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/OfficeDocs-SharePoint#979]
The tile of this article in English is below.
Plan to transform queries and order results in SharePoint Server
In Japanese, localized text is this.
SharePoint Server でクエリの変換と注文の結果を計画する

This title contains wrong localization, "注文" part should be "順序".
Note : "注文" means the order (in restaurant).

**Comment by takawazoe** [comment]
The tile of this article in English is below.
Plan to transform queries and order results in SharePoint Server
In Japanese, localized text is this.
SharePoint Server でクエリの変換と注文の結果を計画する

This title contains wrong localization, "注文" part should be "順序".
Note : "注文" means the order (in restaurant).

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@takawazo Could you please link the doc so the changes can be made? Thanks

**Comment by takawazoe** [comment]
@scanum  this is the link for the document mentioned above.
https://docs.microsoft.com/ja-jp/sharepoint/search/plan-to-transform-queries-and-order-results 
Thanks

**Comment by scanum** [comment]
@officeglobal Hi! Could you please look at this issue? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by OfficeGlobal** [comment]
We're working on a fix

**Comment by OfficeGlobal** [comment]
@takawazoe , @scanum article has been HumanTranslated and published live.

**Comment by scanum** [comment]
@takawazo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
