### ISSUE TITLE
Can't find language pack French

### ISSUE THREAD

**Issue by seaSide974** [MicrosoftDocs/OfficeDocs-SharePoint#984]
Hi when i click the language pack link, it is dead link
thank you

**Comment by scanum** [comment]
@seaSide974 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by seaSide974** [comment]
This is for sharepoint 2019 on premise Server. No such thing as tickets in tenant...
