### ISSUE TITLE
"Images" & "Site Collection Images" Libraries aren't migrated to SPOnline

### ISSUE THREAD

**Issue by GamalMohamed** [MicrosoftDocs/OfficeDocs-SharePoint#987]
I used the PowerShell commands to migrate to SPonline from SP2013 On-Premises. All lists and libraries content were migrated successfully, but the "Images" & "Site Collection Images" content is missed totally.
I also tried the migration tool and gives the same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@GamalMohamed thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
