### ISSUE TITLE
In what format should AAD accounts be specified?

### ISSUE THREAD

**Issue by LenCardinal** [MicrosoftDocs/OfficeDocs-SharePoint#989]
When setting the credentials for a connection, what format should AAD accounts be in?
Is it 'user@domain.com' or something like the old NT format such as 'MicrosoftOnline{xyz}\user'? Since there is no easy way to verify if the credentials are valid, this is kind of important to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78da1cd-d47b-3dea-5c7e-7d7ed5061cdf
* Version Independent ID: a92e04f1-723d-f665-d377-fc2eff3a0ba3
* Content: [Create or edit a Secure Store Target Application](https://docs.microsoft.com/en-us/sharepoint/create-or-edit-secure-store-target-application#feedback)
* Content Source: [SharePoint/SharePointOnline/create-or-edit-secure-store-target-application.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-or-edit-secure-store-target-application.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@LenCardinal thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by LenCardinal** [comment]
It sounds like there is no simple answer? Has anyone tried the article with Azure Ad accounts??



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
