### ISSUE TITLE
Error in refered version

### ISSUE THREAD

**Issue by fdelossantos** [MicrosoftDocs/OfficeDocs-SharePoint#99]
The first paragraph after Summary states: "TLS protocol version 1.1 and 1.2 support is not enabled by default in SharePoint Server 2016", but the current document is about the 2013 version of SharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59acdf52-b8f5-f140-317e-00747b5d80d5
* Version Independent ID: ba2e186b-c2b6-4e09-208e-1b622ebcfed1
* Content: [Enable TLS and SSL support in SharePoint 2013](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/enable-tls-and-ssl-support-in-sharepoint-2013.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by kenwith** [comment]
Thanks for reporting @fdelossantos  and thanks for PR fix @tseward !  I see it is merged. Great work all.
