### ISSUE TITLE
Behaviour has changed for SilentConfig configured via GPO?

### ISSUE THREAD

**Issue by MatthewPrime** [MicrosoftDocs/OfficeDocs-SharePoint#990]
This has stopped working correctly in our environment on AD Domain / Hybrid AD joined windows 10 computers. Users are no longer silently signed in and must enter user credentials.  We've recently updated the OneDrive ADMX templates to a later version.

Description of the GPO setting used to include "..OneDrive will attempt to sign in on every account on the machine.."

It now says "...users who are signed in on the PC with the primary Windows account (the account used to join the PC to the domain) can set up the sync client without entering the credentials for the account..."

Given that our computers are joined to the domain as part of imaging process, using an admin account, this seemingly changed behaviour is useless and a big step backwards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@MatthewPrime thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by anwarmahmood1** [comment]
It is now 29/08/2019 and OneDrive 19.152.801.7 still has the updated behaviour; ie the group policy description for "Silently sign in users to their OneDrive sync client with their Windows credentials" still says "If you enable this setting, users who are signed in on the PC with the primary Windows account (the account used to join the PC to the domain) can set up the sync client without entering the credentials for the account".

This is now *useless* for multi-user computers, and managed computers.

Evidently, this is a permanent change; you need to update this page with this *SEVERE* limitation for shared computers.  This *acutely* affects environments such as education where students move from computer to computer.

**Comment by anwarmahmood1** [comment]
Just tried with a *NEW* profile.  It works with a *NEW* roaming profile, but not an *EXISTING* roaming profile.  Deleting the cached copy of the roaming profile (using Control Panel) doesn't remedy this.  Only a new profile does.  This is still different behaviour.

**Comment by anwarmahmood1** [comment]
It prompts for login if you logon with an existing roaming profile.  This isn't ideal.  It should always be "silent" - either work for a new profile *SILENTLY*, or not even prompt.  This behaviour - where it might work perfectly, or might prompt you - is a terrible situation!
