### ISSUE TITLE
Complete the Article

### ISSUE THREAD

**Issue by wonderboy703** [MicrosoftDocs/OfficeDocs-SharePoint#992]
This page appears to be partially complete. Could you add a code section after step 4. versus a link to the syntax page? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1227a8-793e-aa70-7ff1-bf51c523ffaf
* Version Independent ID: a040d269-6f8f-ca49-fd63-5fa388207e1f
* Content: [Pre-provision OneDrive for users in your organization](https://docs.microsoft.com/en-us/onedrive/pre-provision-accounts#feedback)
* Content Source: [OneDrive/pre-provision-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/pre-provision-accounts.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@wonderboy703 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @wonderboy703 

We've updated the document with the below example. Once the PR gets merged you will be able to see the modifications. 

$users = Get-Content -path "C:\Users.txt"
Request-SPOPersonalSite -UserEmails $users

Thank you for reporting and making the docs better. Much appreciated.

**Comment by wonderboy703** [comment]
Awesome thanks!!

**Comment by scanum** [comment]
@wonderboy703 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
