### ISSUE TITLE
SP2010 now supported? 

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-SharePoint#993]
The link to the SPMT preview version says SharePoint Server 2010 included. So does the "What is supported by SPMT" article. If these are now supported - yay! - we should call that out in this page as well to avoid confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193d7cc4-4270-f69e-262b-6384a273f835
* Version Independent ID: 6625a0f7-e4d0-2352-d78a-0a82273b1f07
* Content: [Introducing the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool#feedback)
* Content Source: [migration/introducing-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/introducing-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
Hi Alejandro: thanks for the suggestion! I made a couple quick edits and will be increasing the visibility next week (after the holiday).

Thanks!
Joanne

**Comment by soyalejolopez** [comment]
Perfect, thank you Joanne! :)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Simpuhl** [comment]
Anyway to migrate personal views only?

**Comment by get-itips** [comment]
Hello, document has been updated by @JoanneHendrickson with a link to what is supported so we consider this resolved.
@Simpuhl stay tuned to released new features [here](https://docs.microsoft.com/en-us/sharepointmigration/new-and-improved-features-in-the-sharepoint-migration-tool)

Thanks to everyone

**Comment by scanum** [comment]
@officedocsbot close
