### ISSUE TITLE
Some text displayed as code when it shouldn't be

### ISSUE THREAD

**Issue by repton-infinity** [MicrosoftDocs/OfficeDocs-SharePoint#994]
Some regular text is mistakenly displayed as code.

Also when it says "Find the GUID of the Application Discovery and Load Balancer service.", it might be helpful to include something like this:

Get-SPServiceInstance -All | Where-Object {$_.TypeName -eq "Application Discovery and Load Balancer Service"} | Format-Table -Property {$_.Server.Address}, Status, Id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1affde-a962-47cf-662b-9ae2a8cdf044
* Version Independent ID: af6ae831-2288-1670-2f9b-1adba51ce519
* Content: [The Application Discovery and Load Balancer Service is not running in this farm (SharePoint Server)](https://docs.microsoft.com/en-us/sharepoint/technical-reference/the-application-discovery-and-load-balancer-service-is-not-running-in-this-farm)
* Content Source: [SharePoint/SharePointServer/technical-reference/the-application-discovery-and-load-balancer-service-is-not-running-in-this-farm.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/technical-reference/the-application-discovery-and-load-balancer-service-is-not-running-in-this-farm.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by scanum** [comment]
@repton-infinity  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @repton-infinity 

Thank you for helping improve the content. 

Get-SPServiceInstance cmdlet reference has been added to the document now. Once the PR gets merged with the document you will be able to see the modifications. Thank you.

**Comment by scanum** [comment]
@repton-infinity Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
