### ISSUE TITLE
[LOC] Missing period and grammar issues leading to unclear source 

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SharePoint#995]
Hello,

 could you please go to article _https://docs.microsoft.com/en-us/sharepointmigration/spo-asynchronous-read-api_ and check the paragraph "_For example, if for a document library url: https://www.contoso.com/my-resource-document/ for any files or folder shares the same root URL, the supporting content will be read back https://www.contoso.com/my-resource-document/file1.doc or https://www.contoso.com/my-resource-document/folderA/file2.doc Only the root url needs to be specified and sends as a single read request._"

**We have received a request:** 
Is there a period missing before "Only"? 

Should 
 - "if for a document library url: https://www.contoso.com/my-resource-document/ for any files or folder shares the same root URL, the supporting content will be read back https://www.contoso.com/my-resource-document/file1.doc or https://www.contoso.com/my-resource-document/folderA/file2.doc"

be rephrased to something like 

 - "if a document library URL is https://www.contoso.com/my-resource-document/, any files or folders share the same root URL, their individual URLs will look like https://www.contoso.com/my-resource-document/file1.doc or https://www.contoso.com/my-resource-document/folderA/file2.doc"?

Should "_and sends as a single request_" be replaced with "_and it should be sent as a single request_"?

Thank you

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @OfficeGlobal 

Thank you for reporting and making the docs better. Much appreciated. 

We've corrected the missing period and grammar issues. Once the PR gets merged we will be able to see the modifications. Thank you.

**Comment by scanum** [comment]
@Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
