### ISSUE TITLE
Azure Application Proxy

### ISSUE THREAD

**Issue by michael-msft** [MicrosoftDocs/OfficeDocs-SharePoint#998]
I miss information on whether it's supported to use Azure Application Proxy (and if it's supported some guidelines how to implement). Sorry if I missed the information ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b11e775-a1e8-2053-3545-9464f226552a
* Version Independent ID: da7b6520-43eb-e9ec-11a5-28d404802c1c
* Content: [Configure a reverse proxy device for SharePoint Server hybrid](https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-a-reverse-proxy-device-for-sharepoint-server-hybrid#feedback)
* Content Source: [SharePoint/SharePointServer/hybrid/configure-a-reverse-proxy-device-for-sharepoint-server-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/hybrid/configure-a-reverse-proxy-device-for-sharepoint-server-hybrid.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@michael-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@michael-msft Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
